### ISSUE TITLE
Multiple jobTitle

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#1000]
We have a case where a `@Person` `worksFor` 2+ `@Organization`. That person has a `jobTitle` for each organization.

How can we express that?

The least sophisticated solution is to use an array and delineate ["jobTitle-1, Organization-1", "jobTitle-2, Organization-2", ...].

An alternative is to assign a different `jobTitle` for a person when `@Person` is linked to `@Organization`. However, this approach defeats reuse as a person will have multiple instances, each based on the `jobTitle` for the linked organization.

Is there a better way to handle this problem?

/jay gray

**Comment by Dataliberate** [comment]
This type of use case is handled by the Role construct, which allows you to qualify a relationship between  entities.

In your particular scenario I would suggest the use of Role to qualify one or more worksFor links to Organizations.

Person - worksFor > Role (roleName 'job1') - worksFor > Organization - 'name1'
Person - worksFor > Role (roleName 'job2') - worksFor > Organization - 'name2'

This construct can be a little difficult to get your head around when you first meet it - I wrote a blog post a while back _[The role of Role in Schema.org](http://dataliberate.com/2015/04/15/the-role-of-role-in-schema-org/)_ to help.

**Comment by jaygray0919** [comment]
+1. We will follow your advice.
/j
