### ISSUE TITLE
Request: Please add mascot to SportsTeam

### ISSUE THREAD

**Issue by KenSharp** [schemaorg/schemaorg#1003]
Would it be possible to add `mascot` to `SportsTeam`?

A lot of teams have mascots. In the U.K. nearly every football (soccer) team does, and there are a _lot_ of websites that talk about football. I believe this is true globally and with many sports.

It would complement `athlete` and `coach`, and `employee` seems quite vague for the subject matter.

[This](http://kennysfunfacts.blogspot.com/2012/04/monkey-hanger-is-not-insult.html) might be an example `BlogPosting`. I'm sure there'll be thousands more.

**Comment by danbri** [comment]
What would the value of a 'mascot' property be?

**Comment by KenSharp** [comment]
The exact same "value" as `coach`, `athlete` or `employee` for all the reasons I have already explained.

I'll be genuinely amazed if I need to explain what a mascot is.

**Comment by vholland** [comment]
I think the question is what is the value of the mascot? Is it a Person? A Thing? For the Boston Red Sox, I could see someone claiming the former (Wally the Green Monster) or the latter (Red Sox).

**Comment by danbri** [comment]
@KenSharp - as @vholland said, we would need to decide how mascots are described. For real world people (i.e. your typical coaches, athletes, employees etc.) we have a pretty good handle on that. Usually using a link, or the Person type.  Our definition for Person does allow for fictitious and historical people, but there are some aspects of mascot that are closer to describing logos and brands. 
e.g. https://en.wikipedia.org/wiki/Chief_Wahoo for https://en.wikipedia.org/wiki/Cleveland_Indians to pick an example that has some controversy around it. Is Chief Wahoo a Person, a Brand, a logo etc...?

**Comment by KenSharp** [comment]
Apologies for not responding to this. I had no idea there were any replies until this was closed. I don't know why I didn't get any notifications. Apologies again.

I understand your question now: H'Angus, in my example, is an anthropomorphic monkey (historical reasons)... so, yes, what would that fall under? He has been played on the pitch by a number of people (including the town mayor, believe it or not), but his image is also used.

I'll come back to this later when the brain fog clears.
