### ISSUE TITLE
Add Service to range of some Product properties

### ISSUE THREAD

**Issue by Dataliberate** [schemaorg/schemaorg#1005]
There are some descriptive similarities between [Product](http://schema.org/Product)s and Services that are not currently supported by the available properties on [Service](http://schema.org/Service).  The following properties should have their domain expanded to include Service to enable a fuller description of services offered by an organization:
- [audience](http://schema.org/audience)
- [brand](http://schema.org/brand)
- [logo](http://schema.org/logo)
- [isRelatedTo](http://schema.org/isRelatedTo) (range also to include Service)
- [isSimilarTo](http://schema.org/isSimilarTo) (range also to include Service)

This was originally proposed as part of the Financial (FIBO) proposals for core vocabulary (#965) and in discussion with @mfhepp in relation to GoodRelations derived terms.  

As this is of broader interest and relevance than just the financial industry, this request is being taken out of the FIBO PR so that it can be reviewed in an independent context.

**Comment by vholland** [comment]
+1

**Comment by danbri** [comment]
Merged (via #1006) into next candidate release. Pinging /cc @mfhepp @chaals @shankarnat @scor @rvguha @pmika

**Comment by danbri** [comment]
Merged into sdo-deimos; reopen if it doesn't make it through final review.

**Comment by danbri** [comment]
http://webschemas.org/docs/releases.html#g1005
