### ISSUE TITLE
Failed aggregateRating validation of Google's example by SDTT

### ISSUE THREAD

**Issue by e-orlov** [schemaorg/schemaorg#1009]
Try to validate with SDTT the first example from this url: https://developers.google.com/structured-data/rich-snippets/reviews, this one:
`<div itemscope itemtype="http://schema.org/Thing">
  <h2 itemprop="name"> Super Book </h2>
  <div itemprop="description">Ultra interesting. Super impressive.</div>
  <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <div>Book rating:
      <span itemprop="ratingValue">88</span> out of 
      <span itemprop="bestRating">100</span> with
      <span itemprop="ratingCount">20</span> ratings
    </div>
  </div>
</div>`

You'll get an error `The property aggregateRating is not recognized by Google for an object of type Thing`.
It seem to be a Schema.org issue - here, `https://schema.org/AggregateRating`, is written, that `Thing ` since unknown time doesn't allowed to be rated/reviewed, but only `Place, Event, Service, CreativeWork, Product, Brand, Offer, Organization`

**Comment by vholland** [comment]
What is the Thing you are describing? I am trying to think of a case where it has reviews, but is not some type of Place, Event, Service, CreativeWork, Product, Brand, Offer, or Organization.

**Comment by DDeering** [comment]
@e-orlov The issue is actually not on schema.org's side.  Google's Structured Data Testing Tool (_Google's_ tool, not schema.org's) just does not accept that particular markup for a Thing.  Change Thing to Product, Organization, Service, etc and it tests fine.  The markup itself is fine.  Google's testing tool just has not been set up to accept it.

**Comment by danbri** [comment]
While the specifics here (posting examples which don't valid with a checker on the same site) are a Google issue, there is still an underlying confusion coming from schema.org: 

* http://schema.org/itemReviewed (from AggregateReview or Rating to Thing), vs
* http://schema.org/aggregateRating (from Brand, CreativeWork, Event, Offer, Organization, Place, Product, Service, to an AggregateReview)

Also, any http://schema.org/Rating is somehow tied to a Review, via http://schema.org/reviewRating.

It seems to me that (1.) it should be possible to review/rate more or less anything, and as @vholland suggests the list Brand, CreativeWork, Event, Offer, Organization, Place, Product, Service comes close to approximating "Thing". This list omits Intangible, Person, Action and MedicalEntity, of which Person seems the most interesting and controversial. I don't think we are in a hurry to encourage schema.org use for rating people. (2.) the direction in which a relationship is named is logically arbitrary, but in practice we all tend to let it influence our thinking: there is a waryness of 'cluttering' Thing with out-going properties, while being more liberal in tolerating properties whose values are Things.

**Comment by danbri** [comment]
Updated title from "Failed aggregateRating validation of Google's example by SDTT" to capture the most obvious work item for schema.org (rather than Google).

**Comment by danbri** [comment]
Hmm, I said that I changed the title but it didn't seem to stick. I don't see an obvious schema.org issue here, but I believe the general issue around ratings/reviews and the list of things those can be attached to is already discussed in several other issues, notably #637 so I will close out this issue in hope of concentrating attention in a smaller list of places. Thanks @e-orlov
