### ISSUE TITLE
Proposal for Movie schema - add Cinematographer

### ISSUE THREAD

**Issue by SensicalCat** [schemaorg/schemaorg#1010]
It would be good to add 'cinematographer' to the movie schema. Additionally, it should also be added to TVSeries. 

Movie & TVSeries both have 'director'. Creativework covers 'editor', 'producer' and 'writer'
Cinematographer is a major above the line role. Worthy of a Academy Award category.

The omission was puzzling.

**Comment by danbri** [comment]
Thanks for the suggestion. Using the [Academy awards](https://en.wikipedia.org/wiki/Academy_Awards#Current_categories) (or similar) as a threshold is an interesting idea. 

I'm going to close this issue now (part of a move towards having fewer open dangling issues) but it will be logged in #2 for review, and remains available here for discussion.

Tagged as "Closed but Noted (and possibly queued)" to indicate that this
has been closed but not forgotten (see #1 #2 #3 for overviews). 
This makes it easier to see issues that are explicitly open for more focussed attention; 
it should not discourage community members from collaborating or discussing an idea or proposal.

**Comment by FAHADXK88** [comment]
هل كان الحق ينصف الباطل ام الباطل أدرك الحقوق في حوكمة المحروم ¿

**Comment by FAHADXK88** [comment]
كان خبراً اجبرنا عن استمرار الموانع في شواهد العين في منتجات المسبرن ₩
