### ISSUE TITLE
Issue when 0 ratingCount and 1 reviewCount in AggregateRating

### ISSUE THREAD

**Issue by r-kovalenko** [schemaorg/schemaorg#1013]
I have products with no rating yet, but with review. I can't solve this.

`<span itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating" class="hidden">
					<meta itemprop="ratingValue" content="0">
					<meta itemprop="worstRating" content="1">
					<meta itemprop="bestRating" content="5">
					<meta itemprop="ratingCount" content="0">
					<meta itemprop="reviewCount" content="1">
				</span>`

I have an error in testing-tool. **Rating could not be normalized**.

**Comment by mfhepp** [comment]
Simply use http://schema.org/review directly on http://schema.org/Product. Do not use the ratingXYZ constructs if you have no ratings.

Also, please note that Google product forums are a better place for such questions.
