### ISSUE TITLE
Typo in FoodEstablishment first example

### ISSUE THREAD

**Issue by mrshannonyoung** [schemaorg/schemaorg#1015]
**content** misspelled.

> `<meta itemprop="postalCode" cotent="02142" />`

Should be:

`<meta itemprop="postalCode" content="02142" />`

**Comment by unor** [comment]
Thanks for the notice! 

@gammamatrix submitted a PR to fix this, but it’s not yet committed: https://github.com/schemaorg/schemaorg/pull/954

**Comment by danbri** [comment]
Committed! thanks all :)
