### ISSUE TITLE
New types for Conversation and Message

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1020]
Schema.org currently has EmailMessage for describing a message, but there is no way to model other types of messages or link them together as a conversation.

I propose adding:

- **Thing > CreativeWork > Conversation**: One or more messages between organizations or people on a particular topic.
- **Thing > CreativeWork > Message**: A single message from a sender to one or more organizations or people. Properties include:
  - **sender**: Already exists on ReceiveAction.
  - **recipient**: Already exists on SendAction.
  - **dateRead**: The date/time at which the message has been read by the recipient if a single recipient exists.
  - **messageAttachment**: A CreativeWork attached to the message.

We could then move EmailMessage to be a subtype of Message.

**Comment by vholland** [comment]
See pull request #1021 for examples.

**Comment by danbri** [comment]
Thanks @vholland. Some scoping questions:

* would a letter e.g. to/from [Charles Darwin](https://www.darwinproject.ac.uk/) be a Message in this sense? 
* would you expect [a page describing such a letter](https://www.darwinproject.ac.uk/letter/DCP-LETT-6976.xml) to be described as a Message?
* how about a blog post whose content was explicitly communicative, for example this recent [open letter to Stephen Fry about mental health](http://liberalengland.blogspot.co.uk/2016/02/an-open-letter-to-stephen-fry-on-mental.html)

My intuition is that these kind of thing are mostly not intended core use of the Message type, whereas maybe ...

* Twitter posts, with (and possibly without) '@'-mentions of other users, or '#'-tagging of topics
* Some but not all instances of SocialMediaPosting.
* A http://schema.org/AudioObject (e.g. a Web portal for answerphone messages) or http://schema.org/VideoObject (possibly including message-oriented videos e.g. [on youtube](https://www.youtube.com/watch?v=WqSTXuJeTks) 

... could be in scope.

How much of threaded forum discussions would this be expected to handle? Are we in https://www.phpbb.com/ territory?

**Comment by vholland** [comment]
> would a letter e.g. to/from Charles Darwin be a Message in this sense?

The letter itself would me a Message.

> would you expect a page describing such a letter to be described as a Message?

In this case no. The page itself is a CreativeWork about the Message.

> how about a blog post whose content was explicitly communicative, for example this recent open letter to Stephen Fry about mental health

I think this is an edge case where it depends on the intent of  the author, but realistically the markup is going to come from the blogging platform, and I doubt we will see anything finer than BlogPosting from those sites. It is too hard to do algorithmically.


> My intuition is that these kind of thing are mostly not intended core use of the Message type, whereas maybe ...
> 
> How much of threaded forum discussions would this be expected to handle? Are we in https://www.phpbb.com/ territory?

I was thinking Message is more for a small, targeted audience where discussion forums, blogs, etc. are not.

**Comment by danbri** [comment]
Seems pretty uncontroversial, I'll merge this for review in the upcoming release candidate.

**Comment by danbri** [comment]
Queued for review as part of sdo-deimos release candidate. see http://webschemas.org/EmailMessage etc.

**Comment by danbri** [comment]
Closing per http://webschemas.org/docs/releases.html#g1020
