### ISSUE TITLE
per-Property, per-enumerated-value pages should show acknowledgements (and multiple should be possible)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1022]
When the schema definitions include acknowledgments for project collaboration, we should show these on property and enumerated value pages too, not just for per-term pages.

Note also that potentially multiple acknowledgements may be applicable to a single term. This is probably most true of types. 

Background: we [added per-property pages some time ago](https://lists.w3.org/Archives/Public/public-vocabs/2013Jul/0067.html) but didn't implement acknowledgements.

Also note that now that we have the notion of hosted extensions, the subdomain homepage for extension(s) e.g. http://bib.schema.org, http://auto.schema.org gives some additional place for explaining and linking to collaborative work.

**Comment by danbri** [comment]
I had a quick look, and made some initial tweaks for the GR case, where we had some awkwardly (because per-term pages were only for types) worded acknowledgement markup. I made a URL for both and worded around "terms" instead. It used to say "This class contains derivatives of properties" e.g. on Property. I think we should use "This term uses terminology from the ..." and apply it to every property, term and type, linking to http://blog.schema.org/2012/11/good-relations-and-schemaorg.html ... I've tweaked the file accordingly.

    17:20 $ ./scripts/rdfa2nt file:data/schema.rdfa | grep GoodRelationsTerms | grep 'terms/source'

    <http://schema.org/Product> <http://purl.org/dc/terms/source> <http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsTerms> .

    <http://schema.org/priceComponent> <http://purl.org/dc/terms/source> <http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsTerms> .

    <http://schema.org/referenceQuantity> <http://purl.org/dc/terms/source> <http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsTerms> .

    <http://schema.org/Offer> <http://purl.org/dc/terms/source> <http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsTerms> . 

This clearly omits a lot of terms, and

**Comment by danbri** [comment]
http://webschemas.org/Product has both forms of wording currently. I think we can converge them into a single acknowledgement form. I'll tweak and check with Martin.

**Comment by danbri** [comment]
Pinging @mfhepp - do you have to hand a complete list of GR terms (not just types but enumerated values and properties) that were included into schema.org? 

Context: we're working to update the old acknowledgements machinery to take advantage of the fact that every schema.org term now has its own page. To simplify things I'd like to find a form of words that is neutral w.r.t. to class/property/enumvalue, hence some of the discussion above. Will need to do same with MusicBrainz et al too but will test first with GoodRelations.

**Comment by Dataliberate** [comment]
Checked the code and confirmed that acknowledgments will display for all Types, Properties and Enumerations if they have a correctly formatted ```<span>Source:  <a property="dc:source" href="....">...</a></span>``` element in their definition.

Once all relevant terms identified, will just need a batch update to the RDFa file(s)

**Comment by danbri** [comment]
Great, thanks!

**Comment by danbri** [comment]
I've checked in a utility scripts/acks.py that turns a one-per-line file containing property URLs, and generates the appropriate metadata. Plus run this for a list of GoodRelations URLs, results in data/gr-property-acks.rdfa.

**Comment by danbri** [comment]
I think we can close this now. I will revisit the larger topic of ongoing and retrospective acks separately.

**Comment by RichardWallis** [comment]
Fixed in V3.0
