### ISSUE TITLE
schema.org/TermsOfService

### ISSUE THREAD

**Issue by teolemon** [schemaorg/schemaorg#1026]
I've realized that there is no Schema.org vocabulary for Terms of Use, or Terms & Conditions. 
Having such a vocabulary would be good to allow to markup the terms of use on websites.
Some crowdsourced initiative do exist, such as ToS;DR (https://tosdr.org/topics.html#topics), but letting webmasters flag their ToS, and Conditions of Use would be way more powerful.

Properties:
- Name of the legal entity
- Topic of the clause "legal period for cause of action"
- Full text of the clause "Any action against **\* must begin within one year after the cause of action accrues. If not, the cause of the action is considered as permanently barred."
- Summarized content of the clause "Reduction of legal period for cause of action"
- …

Use cases: 
- enabling automated monitoring of changes to Terms and Conditions
- enable automatic extraction and analysis on a large scale...

**Comment by danbri** [comment]
The closest is http://schema.org/license but historically we have been wary of getting into this kind of territory at schema.org, in part to avoid confusing (potentially complex) schema.org markup with the very simple and widely understood robots.txt conventions.

**Comment by teolemon** [comment]
I do agree that I can become complex. Being just able to flag the Terms of Service as a whole would be the safest first step.
