### ISSUE TITLE
the page at docs/search_results.html should be more hidden (exclude it from search results; add to a robots.txt)

### ISSUE THREAD

**Issue by ebbeck** [schemaorg/schemaorg#1027]
https://schema.org/docs/search_results.html

this leads to a blank page. Is this a valid schema tag?

**Comment by Dataliberate** [comment]
Have you tried searching for something when you arrive at that page?

~Richard

**Comment by danbri** [comment]
http://webschemas.org/robots.txt

Will go out with next release to schema.org.

**Comment by Aaranged** [comment]
@danbri The content of http://webschemas.org/robots.txt as currently coded instructs the search engines not to index _any_ content on webschemas.org.

The correct markup to exclude only the search results page is:
`User-agent: *`
`Disallow: /docs/search_results.html`

**Comment by danbri** [comment]
Thanks @Aaranged - eagle eyed as ever. In this case @RichardWallis and I decided it was best not to confuse things by having the webschemas draft site show up. Depending on whether the site is running in "official" mode or webschemas-etc mode, we serve a different robots.txt - https://github.com/schemaorg/schemaorg/blob/sdo-callisto/docs/robots-blockall.txt vs https://github.com/schemaorg/schemaorg/blob/sdo-callisto/docs/robots.txt

The goryAppEngine details are in the corresponding *.yaml files. Amongst other things, the official site version should serve a simple sitemap...

**Comment by AymenLoukil** [comment]
Hello all,

the recommended method to block indexing a page is meta tags. 

We should add : <meta name="robots" content="noindex"> in the header of https://github.com/schemaorg/schemaorg/blob/sdo-callisto/docs/search_results.html

Diff between the two methods : 
Robots.txt : Please don't crawl this page / folder but you can continue de show it in your index
Robots meta tags : You can visit this page /folder but you are not authorized to continue indexing it
