### ISSUE TITLE
Proposed new properties for Event

### ISSUE THREAD

**Issue by martin-nc** [schemaorg/schemaorg#1029]
I work as part of the Bioschemas project (see [this post](https://github.com/schemaorg/schemaorg/issues/1028) and the [website](http://bioschemas.org/)). After looking at the fields used in events across a sample of popular life science websites, we found that there are some fields with no equivalent properties in the Event type. These fields are applicable to a wide range of events, not just ones in life science.

We’d like to propose these fields as new properties for the Events type:
- **prerequisite** (Text): A list of prerequisites to be able to attend the event.
- ~~**fee** (Offer): Price of the event.~~ (see @Dataliberate's comment below)
- **accreditation** (Organization or Text): Type of accreditation or organisation that accredits the event.
- **eligibility** (Text): Defines the type of eligibility to attend this event e.g first come, first served.
- **capacity** (Integer): Available number of spaces.
- **contact** (Organization or Person): Main point of contact that can be contacted for general queries. This would be an event organiser or an administrator.
- **attachment** (URL): Any files or related websites which give more information about this event. e.g. flyers, third party sites handling tickets. 
- **socialMedia** (URL): Link to social media websites like Twitter or Facebook.
- **lastUpdate** (Date): Date when the event was last modified.
- **deadline** (Text): Deadlines dates for this event e.g. application deadline, poster submission, paper submission, early registration. 
- **acceptanceNotificationDate** (Date): Date for the host to confirm acceptance to applicants.
- **eventType** (Text): type of event (e.g. conference, seminar, launch).
- **topic** (Text): allows the use of a controlled vocabulary appropriate to a particular domain, and supplements keywords below.
- **keywords** (keywords): (not currently included in Event).
- **targetAudience** (Audience): Who the event is for.
- **spotlight** (boolean): Event highlighted by the event provider. Whether or not the event provider wishes to highlight this event as very important/significant or promoted.
- **programme** (Text or URL): A plan or schedule of activities or procedures the event will follow.
- **submitter** (Organization  or Person): The person or organization who submits an event to a repository or registry of events. 
- **hostInstitution** (Organization): The organization or institution responsible for hosting the event (not necessarily responsible for organizing). 
- **sponsor** (Organization): The organization or institutions providing sponsorship for the event. 
- **registrationStatus** (Registration Status): Enumerative type displaying the status of registration for an event. See the notes below.

You can find the rationale and research behind these suggestions in the proposed [Bioschemas Events specification](https://docs.google.com/document/d/12O8gsOuH2qHKpis6vTHxXExraNH5XZEnoilwNgWWgaQ/edit#). As I said, though, the proposed properties are generic enough to cover many types of events.

Alternatively, if there are existing properties we could use instead of suggesting new ones then please do let us know. Thanks!

**Comment by unor** [comment]
> **fee** (Offer): Price of the event.

`Event` has the [`offers` property](http://schema.org/offers) (expects an `Offer` as value), which can be used to provide the price for attending the event: "An offer to […] give away tickets to an event."

**Comment by philbarker** [comment]
I think that several of these proposed properties would be useful for describing educational courses (see #195 ). For example eventType (e.g. seminar, lecture, lab class), programme, prerequisite, eligibility, targetAudience, capacity all seem immediately relevant

I think accreditation might need clarification: is it the event that is accredited or does it mean that the event leads to some accreditation for the attendees?

**Comment by martin-nc** [comment]
@unor Thanks for that. I was thinking of a case where there is a regular fee but also a special offer (early bird registration or a discount for people belonging to a certain organisation). We were thinking of using `offers` for the latter (i.e. special offers) and then have `fee` for the normal price, to distinguish the two prices. But instead perhaps we could use the `priceValidUntil` property of `Offer` for time-based offers, or the [`discount`](https://schema.org/discount) property otherwise. 

@philbarker Yes, there's quite a bit of overlap there. It feels like there should be a parent type to inherit these more generic properties from, I mean a parent both of Event and of Course/EducationEvent. Otherwise the Event and Course/EducationEvent types could just share properties, even if it feels a bit redundant.

A radical alternative is to bundle them all together and forget about the course/event distinction. Just have a long list of properties you could use, some of which apply more to courses, some of which apply to events, but many of which apply to both. Anyway, I'll to catch up on discussions about this.

`accreditation`: yes, it is pretty ambiguous now that I look at it. A use case might be this: someone organises a conference about Microsoft SharePoint and how it is used in the education sector. Microsoft approve the conference, and allow to organiser to say they approve, but Microsoft don't organise the event or sponsor it financially. So Microsoft 'accredit' the event in the sense they guarantee the competence of the organiser and those taking part. Maybe that's still `sponsor`?

**Comment by philbarker** [comment]
@martin-nc No need common parent to get these properties in to the modelling of courses. We have modelled the delivery of a Course as a CourseInstance, which is a subtype of Event. If these properties are of Event are accepted by schema.org they will be available for describing courses.

Read my comment as a +1 for these properties on the basis that they will help describe courses. I could have been clearer about that.

**Comment by Dataliberate** [comment]
On 17 March 2016 at 12:09, Martin Cook <notifications@github.com> wrote:

> @unor <https://github.com/unor> Thanks for that. I was thinking of a case
> where there is a regular fee but also a special offer (early bird
> registration or a discount for people belonging to a certain organisation).
> We were thinking of using offers for the latter (i.e. special offers) and
> then have fee for the normal price, to distinguish the two prices. But
> instead perhaps we could use the priceValidUntil property of Offer for
> time-based offers,
>
The pattern already established for offers across Schema is to have an
Offer for each set of circumstances - time based, eligibility based, etc.
Introducing a separate ‘fee’ property would create an exception path which
would introduce confusion.  To cover the organisation based example you
quote, there may be a case for a more generic eligibility, or possibly
eligibleOrganization, property on Offer.


> or the discount <https://schema.org/discount> property otherwise.
>
discount is a property on Order and is more appropriate for discount given
(which would have ben described in an offer or a manual adjustment on a
transaction of some sort)

> ~Richard

**Comment by martin-nc** [comment]
@philbarker Thanks - I've  had a look on the [W3C Community page about it](https://www.w3.org/community/schema-course-extend/2016/03/16/progress-update-feb-mid-march/), and the CourseInstance approach looks like a good fix. 

@Dataliberate 
> The pattern already established for offers across Schema is to have an Offer for each set of circumstances - time based, eligibility based, etc.
Thanks, that's great - I hadn't realised this. It looks like the `eligibleCustomerType` and `eligibleDuration` properties might do the job. I'll remove `fee` as a proposed new property. 

I knew discount was a property for Order but didn't know if it was possible to embed in Offer. As you say, it's not necessary anyway.

**Comment by philbarker** [comment]
@martin-nc on accreditation: for courses we have a use case where the searcher is concerned about the provenance of a course, e.g. the institution which is offering it or organisation/s which endorsed the course. I wonder if "endorsement" might be a better term than accreditation?

**Comment by martin-nc** [comment]
@philbarker Sounds good to me. It's less ambiguous. I'll see if others are happy with that, too.

**Comment by mfhepp** [comment]
> The pattern already established for offers across Schema is to have an
> Offer for each set of circumstances - time based, eligibility based, etc.
> Introducing a separate ‘fee’ property would create an exception path which
> would introduce confusion. To cover the organisation based example you
> quote, there may be a case for a more generic eligibility, or possibly
> eligibleOrganization, property on Offer.
> 
Yes, that is exactly right and should be kept.

Note that you can also use multiple UnitPriceSpecifications on the very same order as long as they are characterized by non-overlapping constraints at the level of the http://schema.org/UnitPriceSpecification entities, e.g. using

http://schema.org/eligibleQuantity
http://schema.org/eligibleTransactionVolume
http://schema.org/validFrom
http://schema.org/validThrough

So the same offer can have multiple prices in different moments in time.

Some constraints must be put at the level of the offer, and then you must use multiple offers for different prices, e.g.

http://schema.org/areaServed
http://schema.org/advanceBookingRequirement

Some properties can be used both at the level of the offer and at the level of the price, depending on whether you want to constrain the offer, i.e. the fact that you are willing to transfer a bundle of rights on the thing, or constrain the price, i.e. the exact monetary compension asked. In theory (while not for rich snippets), you can also articulate an offer without specifying the price.

Martin

**Comment by martin-nc** [comment]
@mfhepp Thanks for your info on that. I hadn't explored the "Thing > Intangible > StructuredValue" path with regard to prices. I wasn't aware of the detail you could go into about them!

**Comment by clairejohnson20** [comment]
From my experience of course fees for the on-course.eu project, it’s incredibly difficult to deal with all the different variations that occur. There can be fees for EU and non-EU students, an academic rate and industry rate, fees can include or exclude VAT, can include accommodation or not….. list goes on. Even free courses can be difficult to define. Happy to advise on pros and cons for solutions proposed.

Claire

 

Claire Johnson

Training Information & Liaison Officer

EMBL- European Bioinformatics Institute

Wellcome Genome Campus

Hinxton, Cambridge

CB10 1SD

UK

+44 (0)1223 494 566

 <mailto:claire@ebi.ac.uk> claire@ebi.ac.uk

 <http://www.ebi.ac.uk/training> www.ebi.ac.uk/training |  <https://twitter.com/EBItraining> @EBItraining |  <http://www.ebi.ac.uk/training/webinars> Have you seen our webinars?

 

Join us at the  <http://www.embl.de/training/events/2016/LLL16-01/index.html> EMBL conference on Lifelong Learning in the Biomedical Sciences 5-7th July 2016

**Comment by mfhepp** [comment]
Well, the pricing mechanisms in schema.org and the option to model bundles using http://schema.org/TypeAndQuantityNode should provide most of the vocabulary for even very advanced use-cases.


-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by clairejohnson20** [comment]
Again, the on-course.eu team have had many discussions on accreditation and related terms as there are lots of ambiguities. 

Any true accreditation will be audited by an official/authoritative body and will have full documentation. We’ve only used the term ‘university accreditation’ as this is universally understood. But for bioschemas you will probably need the wider ‘accreditation’ term.

Other terms such as endorsement/endorsed by, recognition/recognised by, recommended, approved by etc. are much looser and mean different things depending on the organisation. For anything other than university accreditation, we decided to use ‘recognised by’ as it is the loosest term but could encompass the other terms.

Claire

 

Claire Johnson

Training Information & Liaison Officer

EMBL- European Bioinformatics Institute

Wellcome Genome Campus

Hinxton, Cambridge

CB10 1SD

UK

+44 (0)1223 494 566

 <mailto:claire@ebi.ac.uk> claire@ebi.ac.uk

 <http://www.ebi.ac.uk/training> www.ebi.ac.uk/training |  <https://twitter.com/EBItraining> @EBItraining |  <http://www.ebi.ac.uk/training/webinars> Have you seen our webinars?

 

Join us at the  <http://www.embl.de/training/events/2016/LLL16-01/index.html> EMBL conference on Lifelong Learning in the Biomedical Sciences 5-7th July 2016

**Comment by martin-nc** [comment]
So after taking Phil's and Clare's comments into account, and a bit of research, it looks like there could be two properties:

1. Accreditation: this has a specific meaning in higher education.  It involves a formal procedure where the organiser or organisation needs to meet specific requirements (see [https://en.wikipedia.org/wiki/Higher_education_accreditation](https://en.wikipedia.org/wiki/Higher_education_accreditation)). This meaning has been discussed in the context of schema.org already (see [this thread from 2012](https://groups.google.com/forum/#%21topic/lrmi/hS0FFFzoCTk)), but I can't see that anything was added to schema.org as a result, or in the new [course proposal](http://course.schema-course-extend.appspot.com/Course). Perhaps I've missed it?

2. 'Recognised by'/'Endorsed by': informal approval.

The question is: is the accreditation property as defined in 1 too obscure to use on schema.org, and would one generic property be better? As Phil says, maybe 'accreditation' implies the event is a course with an 'accredited' certificate at the end, so it may be ambiguous for some.

**Comment by ptrelford** [comment]
I'd find the following proposed properties useful for describing conference events:
- topic (for conference presentation events)
- deadline (for conference Call for Papers/Presentations)

**Comment by RichardWallis** [comment]
On a similar issue (#1275) I just commented that _topic_ could be handled by [_about_ ](http://schema.org/about).  _about_ currently covers a similar multitude of subject/topic/theme relationships on CreativeWork, that are also associated with events.

_deadline_ would probably be better named _submissionDeadline_.

Not sure what you mean by _spotlight_ but it seems to refer to things that would be described as [subEvent](http://schema.org/subEvent)s

**Comment by chaals** [comment]
I don't understand spotlight either :(

dueDate is a pretty general concept - it covers invoices and things as well as conference submissions.

**Comment by ptrelford** [comment]
@RichardWallis on the proposed deadline (Text) property, I prefer your suggestion of submissionDeadline (Date) property  or perhaps a submission (Event) property so that along with the submission date a name, description and url could also be given.

**Comment by martin-nc** [comment]
I think the idea behind 'Spotlight' was to highlight a subevent that has a special status. Let's say you had a two-day conference about tree surgery. The conference includes a series of talks, and a keynote lecture by world-famous tree surgeon Joe Bloggs. This lecture is one of the main selling points of the conference, and isn’t just a normal ‘subEvent’. Ideally, it would be highlighted in a [Rich card or Rich snippet](https://webmasters.googleblog.com/2016/05/introducing-rich-cards.html) so people would see Joe Bloggs’ name in their search results. You would then give this talk the ‘Spotlight’ property.   

I wonder if the deadline issue isn’t a broader one in schema.org. There’s the [paymentDueDate](https://schema.org/paymentDueDate) property for Invoice and Order, but not a more generic ‘DueDate’ property that I can find. Would it be better to take @chaals' suggestion and propose a generic DueDate property that can be used across more types than just Event?

We didn’t include the ‘About’ property because it doesn’t appear in the [Event type](https://schema.org/Event), among the properties inherited from ‘Thing’. ‘Event’ also doesn’t appear in the ‘Used on these types’ list on the [‘About’ page](https://schema.org/about). If it’s okay to use it, though, then that would be fine. I’m not sure how strict schema.org is about these things.
