### ISSUE TITLE
schema:encodesCreativeWork should be declared inverse of schema:encoding

### ISSUE THREAD

**Issue by tfrancart** [schemaorg/schemaorg#1030]
schema:encodesCreativeWork : The CreativeWork encoded by this media object.
schema:encoding : A media object that encodes this CreativeWork.

I don't see why they are not inverse of each other.

**Comment by unor** [comment]
In case this finds agreement: https://github.com/schemaorg/schemaorg/pull/1039

**Comment by danbri** [comment]
You are right, sorry we missed this!
