### ISSUE TITLE
schemas.html datamodel link 404

### ISSUE THREAD

**Issue by hsolbrig** [schemaorg/schemaorg#1033]
The current schemas.html page has a link to the data model towards the bottom of the page "available here" -- this should links to docs/datamodel.html rather than just datamodel.html

**Comment by danbri** [comment]
Thanks @hsolbrig - fix should go out with next release in the near future.

**Comment by danbri** [comment]
queued as http://sdo-deimos.appspot.com/docs/schemas.html
