### ISSUE TITLE
RDFa representation contains HTML comment with definition of "hasReleaseRegion" property

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1044]
The RDFa data model contains this HTML comment:

```
<!-- orig proposal: -->
<!--    <div typeof="rdf:Property" resource="http://schema.org/hasReleaseRegion">
  <span class="h" property="rdfs:label">hasReleaseRegion</span>
  <span property="rdfs:comment">The place and time the release was issued.</span>
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/CreativeWork">CreativeWork</a></span>
  <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/CreativeWorkReleaseRegion">CreativeWorkReleaseRegion</a></span>
</div>
-->
```

A `hasReleaseRegion` property and a `CreativeWorkReleaseRegion` type are currently not defined. Is here some proposal hidden, or can this comment be removed?

(For the HTML comment after this one, see PR https://github.com/schemaorg/schemaorg/pull/1043)

(For other music-related possible TODOs, one of which mentions `CreativeWorkReleaseRegion`, see https://github.com/schemaorg/schemaorg/issues/1041)

**Comment by danbri** [comment]
This is probably the remains of some earlier draft of the music schema. 

Commenting out rather than deleting is an indication that this was me :) I remember little of the details though.

@vholland do you remember why we passed on this? Do you know of any reason the idea might be worth revisiting?

**Comment by vholland** [comment]
I believe it was renamed "releasedEvent" to have some symmetry with PublicationEvent, which already existed before the work on Music.
