### ISSUE TITLE
For works about an Event, add the ability to specify the time described

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1050]
In many cases, Articles, VideoObjects, etc are about a particular moment within an Event. Currently, there is no way to specify the time of the moment being discussed.

We should add a new property **contentReferenceTime** to CreativeWork to for this purpose. The property would expect the wall clock datetime of the moment as calculating the time elapsed within an event can be difficult. As an example:

```
{
  "@context": "http://schema.org/",
  "@type": "Article",
  "name": "Apple announces iPhone SE",
  "description": "New iPhone announced at 11:30 in California.",
  "about": {
    "@type": "Event",
    "name": "Apple's March 21 Announcements"
  },
  "contentReferenceTime": "2016-03-21T11:30:00-07:00"
}
```

**Comment by betehess** [comment]
What if the article mentions two events, happening at different times?

**Comment by Dataliberate** [comment]
Two events would be an issue, but I think that is just symptomatic of separating what is effectively information about an event out into a non-event type.

Would this not be better handled by more effectively describing part of an event with a type designed for the job.

```
Intangible > EventPart
   startTime   DateTime
   endTime    DateTime
   duration     Duration
   partOfEvent   Event
```
Then for the use described:
```
{
  "@context": "http://schema.org/",
  "@type": "Article",
  "name": "Apple announces iPhone SE",
  "description": "New iPhone announced at 11:30 in California.",
  "about": {
    "@type": "EventPart",
    "startTime": "2016-03-21T11:30:00-07:00",
    "partOfEvent" {
        "@type": "Event",
        "name": "Apple's March 21 Announcements"
    }
  }
}
```

Potentially this more generic solution could also solve some other Event based issues that are underway at the moment, such as presentations within a conference;  sessions/innings in a sports event; acts within a theatre event.  In which case Event would benefit from a hasEventPart property.

**Comment by vholland** [comment]
@betehess I don't think we will be able to get into such detail that an Article can be about multiple events and also be able to pinpoint exact sub-parts of each event.

@Dataliberate I considered that, but it seemed like a lot of complexity with an additional type to pinpoint a time for the focus of the Article.

**Comment by Dataliberate** [comment]
@vholland I see an Article about a specific part of an Event as a very narrow use case.  If we imagined that only Article would want to reference part of an Event I would agree with your proposal, and your analysis of what I suggested.  However there are many potential needs to reference such.  

I get the feeling that this could easily become one of those odd-ball very specific constructs that we will soon regret later.

**Comment by vholland** [comment]
@Dataliberate It is increasingly common on sites like nytimes.com and washingtonpost.com to have articles or updates about specific moments. For example, for the bombings in Brussels, the nytimes had http://www.nytimes.com/live/brussels-airport-explosions-live-coverage/ with updates all around the bombings. Some sites do not bother giving the updates headlines as the NY Times does. Instead, it is a list of timestamps.

**Comment by Dataliberate** [comment]
@vholland I recognise the need you describe, although in the specific nytimes case you reference the time used is the time of the [update] article not necessarily the time of the event [part].

I do not see however, how that should cause us to implement a one-off simple single case solution that does not add any generic value to other similar cases.

As to Articles not potentially being about be about multiple events and be able to pinpoint exact sub-parts of each event.   That may well be true when you are thinking about articles in daily newspapers etc.  Broaden your scope to more scholarly articles or detailed analysis articles in a journal or Sunday Newspaper Supplement, it could be very possible.

Yes creating a new ```EventPart``` Type is a little more complex than just adding a property to CreativeWork; whilst adding little extra complexity to markup usage.   However it makes more modelling sense in associating parts of an event with the event itself instead on one specific non-event type that might reference it.  It also delivers generic benefit for all areas of the vocabulary that reference events, and potentially parts thereof.

**Comment by danbri** [comment]
Events can already have parts (subEvent / superEvent). But that doesn't give the useful hint from @vholland 's design which is that the document is specifically talking about moment(s) within the larger event.  

You couldn't use CreativeWork + about + subEvent to distinguish between a post being about a battle that was part of WW-1, from being about a particular moment during an eventful day.

@betehess 's point is worth considering. If the constraint is being made that we're taking the primary or main topic, that ought to be reflected in the property's description. Alternatively, if the property is repeatable that ought to be made clear as well. 

BTW I am floating a new workflow idea: I've made an experimental 'pending' extension for proposed terms, and am testing it on this issue, hence http://pending.webschemas.org/contentReferenceTime

**Comment by danbri** [comment]
OK this is "fixed" by virtue of being published in "pending", but I suggest we adopt the convention of leaving such issues open since we're soliciting feedback, discussion and deployment experience.

**Comment by danbri** [comment]
Here is some feedback from Google based on our experience with this property so far:


> Regarding http://pending.schema.org/contentReferenceTime
>
> Our feedback on this proposed property is that 1.) it adds useful expressivity into schema.org and has a reasonably clear meaning. 2.) we saw relatively low uptake in our use of the property so far in trials with publishers. We think this is partly because it was not essential to our usecase or required by our application-level validation 2.) it is was often difficult to identify the specific correct time to use in the markup. In conclusion we believe it is worth including the property in schema.org but that it will likely remain at a relatively low adoption level.
>
> Our use case is basically mapping pieces of content (e.g. sports highlight videos) to the time point in a game during which the events actually occurred. Since content may have a variable publish latency, the contentReferenceTime property would help us understand the actual time the content maps back to.

**Comment by danbri** [comment]
My suggestion is that we keep this parked in Pending until it has a good accompanying example, at least capturing a 'breaking news' and/or sports usecase.

**Comment by danbri** [comment]
We could add @vholland 's original example:

    {
      "@context": "http://schema.org/",
      "@type": "Article",
      "name": "Apple announces iPhone SE",
      "description": "New iPhone announced at 11:30 in California.",
      "about": {
        "@type": "Event",
        "name": "Apple's March 21 Announcements"
      },
      "contentReferenceTime": "2016-03-21T11:30:00-07:00"
    }

... although to be realistic I'd expect at least a URL for the article. Are there important cases where we're not just giving URL of an article but also of sections within it? I'd also welcome clarification on how it might be used with https://schema.org/LiveBlogPosting

**Comment by gmackenz** [comment]
Should have plenty of liveblogging example for Apple's upcoming event this
week :)


Gordon Mackenzie |  Schema Wrangler (Ontologist) |  gmackenz@google.com |

**Comment by danbri** [comment]
ping @betehess :)

**Comment by danbri** [comment]
I'm adding the above example. Copying my git commit msg here,


> /cc #1050 @vholland 
also @nicolastorzec who was asking about related patterns for NewsArticle,
or rather, suggesting that we document them better. It seems we did not
publish an example when contentReferenceTime was added to Pending.

**Comment by nicolastorzec** [comment]
+1 
ContentReferenceTime is a useful property for anchoring CreativeWork in time.
It's parallel to contentLocation...

**Comment by VladimirAlexiev** [comment]
I have to disagree.
- "time" is an attribute of the subevent, not of the CreativeWork. I can already express the start-end time of a (sub)event, so it's better to make it out as a subevent then just say the work is `about` that subevent
- Once made as a subevent you can say more things about it, eg that a goal is scored at that moment, who scores it, and against whom
- As expressed (absolute time), this applies only to modern events but not to older historic events. Eg to say "the painting depicts the onset of battle X" or "the endspiel of chess game Y", I have to use subevents anyway
- So `contentReferenceTime` is basically a shortcut for those too lazy to make a subevent
- In any case, the relation of `contentReferenceTime` to `temporalCoverage` should be explained

**Comment by VladimirAlexiev** [comment]
Looking above at the [Sep 3, 2016 example](https://github.com/schemaorg/schemaorg/issues/1050#issuecomment-244533574), it's obvious that "California" and "2016-03-21T11:30:00-07:00" pertain to the `Event`, not to the `Article`. The event happened at a certain time and place, and the article is about the event, not about that time and place

**Comment by vholland** [comment]
schema.org/contentReferenceTime was added in schema.org 3.0.

**Comment by danbri** [comment]
This proposal came from Google. Our original expectation was that we would use it, but this does not seem to be happening. 

Is anyone else consuming data that uses this property?
