### ISSUE TITLE
Question: itemprop=author in examples with type "Text", but it is Person or Organization

### ISSUE THREAD

**Issue by kyptov** [schemaorg/schemaorg#1052]
I made a parser by specs and got an error.
For example https://schema.org/Recipe, this type has property "author" inherit from CreativeWork. 
As I see on https://schema.org/author values of this property expected to be type of Person or Organization, not Text.
But in example on  https://schema.org/Recipe I see plain text. 

`<span itemprop="author">John Smith</span>`

but it need to be something like this:

`<span itemprop="author" itemscope itemtype="http://schema.org/Person">`
`    ``<span itemprop="name">John Smith</span>`
`</span>`

I tested example from https://schema.org/Recipe in [google tool](https://developers.google.com/structured-data/testing-tool/) and google converts property author to type "Thing".

So, how to understand  itemprop="author" as plain text?

**Comment by unor** [comment]
Relevant:

From [Data Model](http://schema.org/docs/datamodel.html) (bold emphasis mine):

> While we would like all the markup we get to follow the schema, in practice, we expect a lot of data that does not. We expect schema.org properties to be used with new types. **We also expect that often, where we expect a property value of type Person, Place, Organization or some other subClassOf Thing, we will get a text string.** In the spirit of "some data is better than none", we will accept this markup and do the best we can. 

From [Getting Started: Expected types, text, and URLs](http://schema.org/docs/gs.html#schemaorg_expected):

> **Expected types vs text.** When browsing the schema.org types, you will notice that many properties have "expected types". This means that the value of the property can itself be an embedded item (see section 1d: embedded items). But this is not a requirement—it's fine to include just regular text or a URL. In addition, whenever an expected type is specified, it is also fine to embed an item that is a child type of the expected type. For example, if the expected type is Place, it's also OK to embed a LocalBusiness.

**Comment by kyptov** [comment]
@unor, thanks.
