### ISSUE TITLE
Proposal to make JobPosting a subtype of Demand

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1060]
/cc @chaals @rvguha @shankarnat @pmika 

@mfhepp has argued in #961 and #1054 that JobPosting naturally fits the definition of Demand, and should be marked as a subtype. 

@vholland has responded by arguing that http://schema.org/Demand carries many (Offer-like) properties that are not applicable and that the conceptual benefits of adding an explicit subtype to Demand would be outweighed by the usability impact.

**Comment by danbri** [comment]
I have seen no further evidence of interest in making JobPosting into a formal subtype Demand, so I suggest that for now we acknowledge that there is some similarity between JobPosting and Demand but that we're not going there right now.

**Comment by rvguha** [comment]
Sounds good.

guha
