### ISSUE TITLE
Add vocab to support markup of fact-checking sites

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1061]
The following markup is proposed for use by a collaboration amongst fact-checking sites.

It adds vocabulary around Review to make more explicit when these are from fact-checking sites:
- 1.) ClaimReview as a subtype of Review. "A fact-checking review of claims made in some creative work."
- 2.) claimReviewed as a property of ClaimReview. "A short summary of the specific claims reviewed in a ClaimReview."
- 3.) It uses the existing 'author' property on Review to indicate the organization behind the review.
- 4.) ~~It uses a new property, claimReviewSiteLogo on the (Claim)Review to indicate the fact-checking organization's logo.~~
- 5.) It uses the existing itemReviewed property to indicate the document that carries the claims being reviewed (which could include as shown here, offline newspaper articles).
# Example 

(updated for Feb 2017 but [original](https://gist.github.com/danbri/15b56c9847f2132aa912675e89e6fa2b) was close)

```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type":  "ClaimReview",
    "datePublished": "2014-07-23",
    "url": "http://www.politifact.com/texas/statements/2014/jul/23/rick-perry/rick-perry-claim-about-3000-homicides-illegal-immi/",
    "author": {
        "@type": "Organization",
        "url": "http://www.politifact.com/",
        "sameAs": "https://twitter.com/politifact"
    },
    "claimReviewed": "More than 3,000 homicides were committed by \"illegal aliens\" over the past six years.",
    "reviewRating": {
        "@type": "Rating",
        "ratingValue": 1,
        "bestRating": 6,
        "alternateName": "True",
        "image": "http://static.politifact.com/mediapage/jpgs/politifact-logo-big.jpg"
    },
    "itemReviewed": {
        "@type": "CreativeWork",
        "author": {
            "@type": "Person",
            "name": "Rich Perry",
            "jobTitle": "Former Governor of Texas",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Gov._Perry_CPAC_February_2015.jpg/440px-Gov._Perry_CPAC_February_2015.jpg",
            "sameAs": [
                "https://en.wikipedia.org/wiki/Rick_Perry",
                "https://rickperry.org/"
            ]
        },
        "datePublished": "2014-07-17",
        "name": "The St. Petersburg Times interview [...]"
    }
}
</script>




```
#  See also
-  https://github.com/ReportersLabDuke/Widget/  "A fact-checking widget developed by the Reporters' Lab at Duke University. Working in conjunction with fact-checking sites around the world, the Reporters' Lab has developed this widget to help fact-checkers with search engine optimization and provide shareable content for their articles."
  - example usage, http://www.politifact.com/texas/statements/2016/jan/06/donald-trump/donald-trump-incorrectly-says-ted-cruz-has-had-dou/

**Comment by danbri** [comment]
Draft at http://pending.webschemas.org/ClaimReview

**Comment by danbri** [comment]
Suggestions:

* Instead of 'twitter' as a property, use 'sameAs' with full URL.
* Can we use 'logo' of the Organization instead of claimReviewSiteLogo?

**Comment by danbri** [comment]
Note that #271 proposes a Quotation type under CreativeWork, now implemented within the pending extension as http://pending.webschemas.org/Quotation ... this should plug in directly here.

**Comment by danbri** [comment]
An update on adoption of this vocabulary, for those who might have missed it. If you inspect (via  in-browser element inspection) the post-Javascript DOM of URLs such as 

http://www.factcheck.org/2016/07/groundhog-friday-7/ 
http://www.politifact.com/truth-o-meter/article/2016/may/17/fact-checking-pro-clinton-super-pacs-attacks-donal/
https://www.washingtonpost.com/news/fact-checker/wp/2016/06/17/fact-checking-three-democratic-claims-on-assault-rifles-and-guns/

you will see Widget-injected JSON-LD using the ClaimReview type, and that augments the Rating item with (in the last case) a 'name' property that carries non-numeric codes, e.g. 

    "reviewRating": {
       "@type": "Rating",
       "ratingValue": "2",
       "bestRating": "5",
       "name": "Two Pinocchios",
       "image" : "https://s3.amazonaws.com/share-the-facts/rating_images/washpo/washpo_pinnochios_2.png"
     },

See also https://github.com/ReportersLabDuke/Widget/ which has related widget code.

I mention this in part because of nearby discussion (#668 #915 and most recently #780) around the question of representing awards, "star ratings" (esp. for accomodation) and other endorsements, and how general vs domain specific we want various constructions to be. 

The point of overlap (beyond the general connection to the notion of Review and/or Rating) is that the fact checking sites have situations such as "Two Pinocchios" in which a well known (and site/provider-specific) informal but named code is applied to something. The broadly analogous situation with awards is that something is awarded "critic's pick", "x of the year" etc., which can be conceived of as a kind of rating. Meanwhile schema.org/Rating defaults to 5-point scales. 

Despite that discussion, my feeling is that ClaimReview has proved its worth and the design seems reasonably stable. I suggest we move it into the core (it is currently staged in pending.schema.org) to encourage further adoption.

**Comment by danbri** [comment]
Given the relatively small number of sites in the fact-checking audience, I believe having politifact, factcheck.org and the Washington Post is excellent progress. I'll proceed with moving this into Core just as soon as we figure out how exactly to structure this technically (so that the old URLs are still useful). /cc @shankarnat @tmarshbing @chaals @nicolastorzec @scor @mfhepp @rvguha @vholland in case anyone cares to suggest another course of action.

**Comment by bquinn** [comment]
Just thought I'd mention that this proposal gets a mention in the recent [fullfact.org "State of Automated Factchecking" report](https://fullfact.org/blog/2016/aug/automated-factchecking/) in case that adds fuel to the fire of getting it moved into schema.org core.

**Comment by danbri** [comment]
Oh, that is nice, thanks @bquinn. Makes a change from reading about "post factual" democracy...

**Comment by unor** [comment]
For reference:

Google News suggests to use `ClaimReview` in their blog post [*Labeling fact-check articles in Google News*](https://blog.google/topics/journalism-news/labeling-fact-check-articles-google-news/) (link to pending) and in their [help about source labels (*Fact Check*)](https://support.google.com/news/publisher/answer/4582731#fact-checking) (link core, where the type does not yet exist).

**Comment by danbri** [comment]
See also blog post with ideas around this from Leigh Dodds @ldodds https://twitter.com/ldodds/status/793538304981528576

**Comment by thinkcontext** [comment]
Suggestion, it would be helpful to include a property for a link to a source for where the claim is made.  Most fact checking articles include such a link to an original piece of news reporting or a primary source that is the origin (or close to the origin) of the claim.

**Comment by unor** [comment]
@thinkcontext The description of `ClaimReview` suggests to reference the work where the claim is made with the `itemReviewed` property.

For example:

```html
<article vocab="http://schema.org/" typeof="ClaimReview">
  <h2 property="name">Fact check: Foo (example.com)</h2>

  <div property="itemReviewed" typeof="Article">
    <a property="url" href="http://example.com/articles/foo"><cite property="name">Foo</cite></a>
  </div>

</article>
```

Does this work for you?

**Comment by thinkcontext** [comment]
I see, thanks for that clarification @unor

**Comment by melvincarvalho** [comment]
The use of sameAs in the example, seems kind of problematic, particularly in the context of reviews.

I might like Ricky Martin's home page, but not like Ricky Martin.

**Comment by stefanw** [comment]
How should the markup work when reviewing a claim that has spread around and is present on multiple URLs? We don't want to publish a `ClaimReview` for each of these sites.

Is using `sameAs` appropriate in this case? E.g.

```
...
    "itemReviewed": {
        "@type": "CreativeWork",
        "url": "http://example.org/example-1",
        "sameAs": [
                "http://example.com/example-2",
                "http://example.com/example-3"
        ]
    }
...
```
Or should one place multiple `itemReviewed` properties in one `ClaimReview`? Or are multiple instances of `workExample` the appropriate property, as the reviewed claim has many concrete URLs?

I don't necessarily want to identify the URLs as the same, only similar enough to warrant the same `claimReview`.

**Comment by unor** [comment]
@stefanw: Using multiple `itemReviewed` values should be the right way:

```json
    "itemReviewed": [
        {
          "@type": "CreativeWork",
          "url": "http://example.org/example-1"
        },
        {
          "@type": "CreativeWork",
          "url": "http://example.org/example-2"
        }
    ]
```

**Comment by danbri** [comment]
Mission accomplished folks. The ClaimReview markup is very much out there. Particular thanks to @BillAdairDuke for getting this started and for his tireless advocacy ever since :)

I will close this issue now. Please see #1969 as our new tracking issue for this work and sub-issues.

Note btw that we added (per #1828) a Claim type (as pending while we tidy up the messaging and examples) as part of last week's v3.4 release.

**Comment by danbri** [comment]
For info, from Facebook: https://newsroom.fb.com/news/2018/06/increasing-our-efforts-to-fight-false-news/ and a while back, Microsoft Bing, https://blogs.bing.com/Webmaster-Blog/September-2017/Bing-adds-Fact-Check-label-in-SERP-to-support-the-ClaimReview-markup
