### ISSUE TITLE
Schema.org CG meeting at W3C TPAC?

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1067]
Raised by @betehess in https://lists.w3.org/Archives/Public/public-schemaorg/2016Mar/0080.html

Collecting schedule-related information towards proposing meeting slots.

When, if at all, are these groups meeting?
- digital publishing group
- healthcare and lifesciences
- ...others?

**Comment by TzviyaSiegman** [comment]
Digital Publishing has requested Monday/Tuesday. Many of us will be there
all week. See you in Lisbon.

**Comment by danbri** [comment]
@TzviyaSiegman :) ok, so that's a strong bias towards thurs/friday then
