### ISSUE TITLE
Documentation Examples: Multiple Store Locations

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#1072]
Requesting [schema.org/Store](https://schema.org/Store) include an example section for multiple store locations.

**Comment by vholland** [comment]
The ```parentOrganization``` and ```subOrganization`` properties should be use to link the branch to the parent or vice-versa depending on your data. The ```branchCode``` property is also useful (if available) to distinguish locations.

**Comment by danbri** [comment]
I thought we had decent examples for this [digs around] ah yes - they are just hidden away a bit: http://schema.org/Pharmacy has sequence of several examples that build in complexity (I think these were donated from Google's SD site so you might have seen similar already there). @inetbiz - can you take a look? We could make those examples show up under Store trivially.

**Comment by inetbiz** [comment]
@danbri those examples look like departments. I'm curious about retail stores that are in more than one location. Acme Retail - wadawada washington, seattle washington and tacoma with their store NAP

**Comment by danbri** [comment]
Ah, in that case yeah @vholland was pointing in the right direction. But yup we ought to add more / better examples at some point.
