### ISSUE TITLE
Repeated branchCode property in Store

### ISSUE THREAD

**Issue by Dataliberate** [schemaorg/schemaorg#1073]
The branchCode property is repeated 3 times on the [Store](https://schema.org/Store) term page and twice on the [LocalBusiness](https://schema.org/LocalBusiness) page.

Basic reason is that the property is unnecessarily defined as having a domainIncludes for Place, LocalBusiness, and Store.  Place would be sufficient as it would be inherited by the others.

Need to fix definition and consider checks in the display code to prevent repeat display and possibly warn  of the circumstance.

**Comment by danbri** [comment]
Fixed, thanks @RichardWallis 

Queued for next release,

* http://webschemas.org/branchCode
* http://webschemas.org/Store
