### ISSUE TITLE
Organization's subtype NewsMagazine ?

### ISSUE THREAD

**Issue by Stephanereboul** [schemaorg/schemaorg#1085]
Hello, 
It would be usefull to have a NewsMagazine type to describe clearly some articles.
For example, when an article is written, we have to specify the publisher of the article. Many times, the article is written by a NewsMagazine. 
This way we could code : `<span itemprop="publisher" itemscope itemtype="http://schema.org/NewsMagazine">` to precise that the article comes from a newspaper, which is different to a laboratory or a Website.

Elsewhere, anybody has an advice about another issue I posted ?
https://github.com/schemaorg/schemaorg/issues/1034

Thank you for your answers.

Stéphane
www.globetrottoirs.com

**Comment by danbri** [comment]
Thanks for the suggestion. I've filed it under "noted" so will close the issue for now (we need to do this to handle the 100s of issues that get raised). Currently Organization does not cover a huge range of specific Organization types but if we expand it, this is a good suggestion to come back to.

**Comment by Stephanereboul** [comment]
Thank you for your answer.

 

I will look for it.

 

Is it usefull that I open a new repository about this ?

 

Have you visited also #1034 issue which treats of CreativeWork subtype
called StageWork ?

 

Have a nice day.

 

Stéphane Reboul

 

  _____  

De : Dan Brickley [mailto:notifications@github.com] 
Envoyé : jeudi 7 avril 2016 16:09
À : schemaorg/schemaorg
Cc : Stephanereboul
Objet : Re: [schemaorg/schemaorg] Organization's subtype NewsMagazine ?
(#1085)

 

Thanks for the suggestion. I've filed it under "noted" so will close the
issue for now (we need to do this to handle the 100s of issues that get
raised). Currently Organization does not cover a huge range of specific
Organization types but if we expand it, this is a good suggestion to come
back to. 


You are receiving this because you authored the thread.
Reply to this email directly or
<https://github.com/schemaorg/schemaorg/issues/1085#issuecomment-206923451>
view it on GitHub
<https://github.com/notifications/beacon/ARF8WLvwMfGfSUvlXvICOFpZWQBbYJumks5
p1Q_igaJpZM4IBzSM.gif>
