### ISSUE TITLE
We have CreativeWorkSeries but don't say how it relates to the earlier Series

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1090]
- #417 added CreativeWorkSeries in v2.0 http://schema.org/docs/releases.html
- the RDFS in data/schema.org says: supersededBy http://schema.org/CreativeWorkSeries
- the schema.org site UI has no support for this construct on types or enumerated values, only properties
- EventSeries is proposed as a subtype of Series despite it being superseded
  - We should have a unit test to make sure no proposals are in pending.schema.org that depend upon superseded vocabulary.

Proposed actions: 
- remove the supersededBy on Series, restore it as a supertype of both CreativeWorkSeries and EventSeries; polish definitions accordingly.
- this should work with #447 as-is

**Comment by danbri** [comment]
Alternative (after chatting with @vholland ) would be to continue to retire Series, and to allow CreativeWorkSeries to continue under CreativeWork, plus adding new EventSeries under Event for #447.

**Comment by Dataliberate** [comment]
Pragmatically this sounds a better solution.  A CreativeWorkSeries has many CreativeWork attributes associated with it that are not particularly relevant to Events (author, etc.) 

Properties of CreativeWork that were intended to enable EventSeries - I am presuming hasPart & isPartOf would need their range extending

**Comment by vberkel** [comment]
@danbri in moving the Series, the properties isPartOf and hasPart are no longer available as their domain was CreativeWork. The JSON-LD example for EventSeries series uses hasPart, but that is not available to the Class. Should the domain of hasPart and isPartOf add Series?

**Comment by RichardWallis** [comment]
+1 expanding domain of isPartOf & hasPart to Series

**Comment by danbri** [comment]
There was a comment here recently that I now don't see,

> @danbri in moving the Series, the properties isPartOf and hasPart are no longer available as their domain was CreativeWork. The JSON-LD example for EventSeries series uses hasPart, but that is not available to the Class. Should the domain of hasPart and isPartOf add Series?

I continue to resist extending isPartOf outside of CreativeWork, where it is already plenty ambiguous. We can't pack a theory of parts into one property that applies across too many diverse types. I suggest  we look at this after 3.4 is out as part of stabilizing various things like EventSeries that are in Pending, but http://schema.org/subEvent looks like it could do the job.

**Comment by RichardWallis** [comment]
Proposed actions were applied.
All superseded terms [of all types] now indicate their superseded state.
