### ISSUE TITLE
JSON-LD example for OrderAction uses OrderedAction

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#1093]
The JSON-LD example for [OrderAction](http://schema.org/OrderAction) has this:

`"@type": "OrderedAction",`

AFAIK there is no "OrderedAction" - at least at time of writing it 404s.  Accordingly, the line cited should read:

`"@type": "OrderAction",`

**Comment by unor** [comment]
+1 

I guess it’s also an error that `location` has a `Product` value (with the `name` "Amazon").
