### ISSUE TITLE
Schema.org needs a site-wide convention for abbreviating enumerated value URLs as strings

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1094]
This generalizes a debate in #921 regarding the DayOfWeek enumeration.

Goal: make it easier for publishers to write e.g. "False" instead of the URL http://schema.org/False, and make it clearer how consumers can canonicalize certain string forms into the corresponding official schema.org URLs. 

Background:
- JSON-LD forces us to specify explicitly how every property's values are interpreted:
  - for a property/value pair written "foo": "bar", if "foo" defaults to @id, then "bar" might expand to an URL e.g. http://somebaseurl.example.com/etc/bar. Otherwise it might result in a simple string, "bar"
- The use of URLs as property values in schema.org can be confusing for webmasters / publishers, in cases where the property is not relationship-oriented (isPartOf, worksFor), but instead takes a small enumerated list of values e.g. an EventStatusType  such as EventCancelled or EventPostponed being written as URLs, http://schema.org/EventCancelled, http://schema.org/EventPostponed.
- Schema.org has general (and somewhat vague) language in http://schema.org/docs/datamodel.html indicating that consumers will likely apply heuristics when encountering "strings" where the vocabulary indicates that "things" (i.e. objects, entities) are to be expected. It is not immediately clear whether or how this applies to a "thing" like http://schema.org/False.
- There is general interest in defining some kind of mechanism that documents a convention for writing "False" as a shorthand for an URL like http://schema.org/False, for all schema.org enumerated values.
  - This should probably work across at least Microdata, RDFa and JSON-LD. There may be syntax-specific mechanisms that need consideration e.g. @contexts, or for RDF-based languages like JSON-LD and RDFa, datatypes.
  - At some point it becomes impossible to anticipate all variant forms that publishers might use, and the process becomes heuristic and contextual.

/cc @betehess who championed this issue for dayOfWeek. Alexandre - did I miss anything?

**Comment by akuckartz** [comment]
:+1:

**Comment by danbri** [comment]
from #json-ld IRC channel on Freenode, 

      danbri
      6:25 q: can we use JSON-LD contexts to expand things in the value of a property?
      6:26 e.g.  if we have "xyz": "foo", can the context rig things so that "foo" becomes some nice URI, rather than relative to the instance data

      dlongley
      6:31 danbri: yes
      6:31 you use `"xyz": {"@id": "ex:someurl", "@type": "@vocab"}, "foo": "ex:someotherUrl"}`
      6:32 that will define `xyz` as a term that accepts "vocab" values
      6:32 and if you define something in the context like "foo" and map that to a URL, then when you use "foo" as the value for "xyz", it will expand to whatever you mapped "foo" to.
      6:34 danbri: http://json-ld.org/playground/#/gist/c9c1708671f1a93d60b7d5306a472f18

      danbri
      6:39 oh, interesting, thanks!

**Comment by danbri** [comment]
http://json-ld.org/playground/#/gist/c9c1708671f1a93d60b7d5306a472f18  
has

  {
      "@context": {
        "day": {
          "@id": "http://example.org/day",
          "@type": "@vocab"
        },
        "Monday": "http://example.org#Monday",
        "Tuesday": "http://example.org#Tuesday",
        "Wednesday": "http://example.org#Wednesday",
        "Thursday": "http://example.org#Thursday"
      },
      "day": "Thursday"
    }

parsing to 

_:b0 <http://example.org/day> <http://example.org#Thursday> .

**Comment by thadguidry** [comment]
@danbri so as you said in #1186 the last entry gets the last word ?  its Thursday's URL.  Do we care ? Does last entry rule have a benefit somehow ?

**Comment by danbri** [comment]
Last context URL gets last word. It matters in the case multiple contexts declare same term eg "author".

**Comment by thadguidry** [comment]
@danbri see my update about default above.
