### ISSUE TITLE
Grouping of terms in listing on extension home page

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1096]
On the home page of a hosted extension such as http://bib.schema.org or http://health-lifesci.webschemas.org the terms contained in that extension are listed.  As an extension such as health-lifesci can bring together terms from separate but associated areas, it would be useful and clearer to group the listings by those areas.

Will require some UI work, associated with an additional property that can be added to a term definition to associate it with other similar terms.  It would be preferable to reuse an existing property, potential candidates include: keywords, dc:source (already used for acknowledgements but could be dual purpose), about, category.

Would also be helpful in the _pending_ extension to group terms by proposal.

**Comment by danbri** [comment]
Thanks for picking this one up. I will hold off on cleanups to the CSS until you're done. For example health-lifesci.webschemas.org looks a bit wonky and I was previously putting CSS inline in HTML inline in Python in sdoapp.py, for which I am duly ashamed :)

**Comment by danbri** [comment]
@RichardWallis is this done? I know it works on http://pending.webschemas.org but not sure re http://health-lifesci.webschemas.org/ etc if there's a way to invoke groupings...

**Comment by RichardWallis** [comment]
Fixed in V3.0
