### ISSUE TITLE
Update rdfa2nt and rdfa2nq to expland markdown markup into appropriately escaped HTML

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1106]
There are a couple of very simple Python scripts used to generate  NTriples and NQuads files for each release.

* https://github.com/schemaorg/schemaorg/blob/sdo-deimos/scripts/rdfa2nt
* https://github.com/schemaorg/schemaorg/blob/sdo-deimos/scripts/rdfa2nq

These need updating as we start to include markdown in our master RDFS (RDFa/JSON) files - see #181.

The generated URIs should presumably use absolute URIs. Markdown could be processed before RDFa parsing, or afterwards.

**Comment by RichardWallis** [comment]
Solved by introducing exportgraphs.py
