### ISSUE TITLE
Supersedes or Superseded by not displayed for Types

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1109]
Only currently visible on attribute pages

**Comment by danbri** [comment]
I was pretty sure we had an issue for this, but I've not managed to find it yet :)

**Comment by danbri** [comment]
Merged the pull request. But do you handle if a type is superseded but not by any particular new term, i.e. obsolete/deprecated. I think that was the other issue I left open somewhere...

**Comment by danbri** [comment]
Ok this is live on webschemas.org - is there a good example we can look at to test?

**Comment by Dataliberate** [comment]
http://webschemas.org/CreativeWorkSeason
http://webschemas.org/Season

“do you handle if a type is superseded but not by any particular new term”
 - would need to find an example to check

We should in addition probably display a warning near the top saying “This
term has been superseded by XXXX.  Please consider before using”

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by danbri** [comment]
We shouldn't make the warnings too heavy or it creates awkwardness e.g. when search marketing people have recommended something then it gets superseded. We want consumers to respect older structures wherever possible and not worry publishers into constantly updating in the absence of concrete product-related incentives imho.

**Comment by RichardWallis** [comment]
Fixed in V3.0

**Comment by unor** [comment]
> “do you handle if a type is superseded but not by any particular new term”   
> - would need to find an example to check

Maybe a relevant case is `ProfessionalService`? See #1418
