### ISSUE TITLE
Bug?  "Available properties in extensions From Enumeration: supersededBy" 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1113]
"Available properties in extensions From Enumeration: supersededBy" shows up in lots of extension pages eg. http://health-lifesci.webschemas.org/MedicalProcedureType

Not even sure what it means! Can you take a look @RichardWallis ?

**Comment by twamarc** [comment]
Yeah, strange indeed! I will also investigate this ...

**Comment by danbri** [comment]
@twamarc it isn't only in medical - I think this is more a software issue for all enumerations. BTW I'm working through detailed review/integration of the medical stuff right now.

**Comment by Dataliberate** [comment]
Although strange, it is operating as [currently] expected.   In most cases we want to highlight that there are more properties available in extensions for a type that you are looking at in the core.

Prior to the creation of meta.schema.org this property used to appear in the main listing of properties.

I suggest that we suppress the display of properties from meta.schema.org in such circumstances.

**Comment by danbri** [comment]
Yes please!

**Comment by RichardWallis** [comment]
Fixed
