### ISSUE TITLE
health-lifesci.schema.org tracking issue

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1116]
This issue tracks potential updates to the new health-lifesci hosted extension.

Currently the extension contains revisions to the 2013 schema.org medical vocabularies, but we also have nearby #1028, #1062 as related collaborations, in addition to plans for further improvements and collaborations as discussed here and in the schemed community group.

We can consider also adding PhysicalActivityCategory, LeisureTimeActivity etc. to health-lifesci.

**Comment by donli4** [comment]
Hi Dan,
The health-lifesci.schema.org extension is not working and leads to a 404 page actually.
I'm not familiar with schema.org so I'm not sure whether it's my own problem. 
Just let you know:)

**Comment by danbri** [comment]
Thanks - yeah we have a problem with the v3 launch. It is going to take a day or two to get the subdomains working properly so I'm going to rollback to v2.3 for now. Sorry about that. The v3 site remains accessible via http://webschemas.org/

**Comment by donli4** [comment]
Wow that's a fast reply!
Thanks Dan! You've done amazing job already.

**Comment by jvandriel** [comment]
I'd like to add an additional wish to twamarc/ScheMed#32, namely that the domain of ```adverseOutcome``` and ```seriousAdverseOutcome``` also gets expanded to ```schema.org/Drug```.

And I also noticed I forgot to suggest that the domain of ```contraindication``` also gets expanded to ```MedicalProcedure``` and ```schema.org/Drug```.

In regards to ```schema.org/Drug```, I currently have a case for which I'm marking up drugs and on the pages of each drug there's a 'Side effects' section (= ```adverseOutcome``` and ```seriousAdverseOutcome```) and 'When not to take' (= ```contraindication```) which I currently can't describe without making the entity involved a triple Multi-Type Entity (= ["Product","Drug","MedicalTherapy").

Which technically might be correct, but besides the fact it feels clumsy I mostly find it strange ```schema.org/Drug``` currently doesn't have the mentioned properties even though leaflets that comes with drugs almost always mention these. So how come we can't mention these in markup unless using a 'messy' MTE?

**Comment by twamarc** [comment]
I do not see another way to avoid MTE than extending to domain of the two properties ``adverseOutcome `` and `` seriousAdverseOutcome``  with  `` schema.org/Drug`` .
Normally this is not expensive but we are still currently fixing some strange breaks in 3.0 (https://github.com/schemaorg/schemaorg/issues/1203)  I hope after that we will include this extend in coming patch.

**Comment by jvandriel** [comment]
I agree that at this moment there's no other option than an MTE @twamarc. Though my request was aimed at when we continue to update/modify the extension, not immediately.   :)

**Comment by ldodds** [comment]
I've been wondering about use of PhysicalActivity outside of life sciences. I've filed that in a new issue #1480 to focus discussion there. I'd welcome feedback/input from those of you familiar with the life sciences extension.

**Comment by jvandriel** [comment]
A couple of years have passed by now but alas the domain of `adverseOutcome` and `seriousAdverseOutcome` still haven't been expanded to `MedicalProcedure` nor `Drug`.

Can I expect this to happen somewhere during the next decade, or is there a chance if I make a pull request to fix this that it will be added?

**Comment by twamarc** [comment]
Hi @jvandriel : Thanks raising this again. Is it possible to prepare a PR for this and submit it? then It can be discussed and pushed.

**Comment by jvandriel** [comment]
Hopefully I'll get around to doing so somewhere next week @twamarc.

**Comment by jvandriel** [comment]
Since these properties are part of an extension I was wondering whether you can tell me which file(s) I need to edit and where I can find them @twamarc ?

**Comment by danbri** [comment]
Look under data/ext/

**Comment by jvandriel** [comment]
Thanks @danbri
