### ISSUE TITLE
For extension documentation: avoid types in core having supertypes that are only in extension

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1117]
As part of the large medical vocab move into health-lifesci, we find ourselves with this structure:

[core]Thing > [health-lifesci]MedicalEntity >[health-lifesci] MedicalTherapy >[health-lifesci] LifestyleModification > [core]PhysicalActivity >[core] ExercisePlan.

To workaround here I suggest bringing the latter two into health-lifesci but this is also something to document better for future work on extensions.

/cc @RichardWallis @rvguha @twamarc 

Consider both unit tests and a list of human-friendly rules.

**Comment by danbri** [comment]
Note extra complication here, since we have exercisePlan and ExerciseAction.

    <div typeof="rdf:Property" resource="http://schema.org/exercisePlan">
       <span class="h" property="rdfs:label">exercisePlan</span>
       <span property="rdfs:comment">A sub property of instrument. The exercise plan used on this action.</span>
       <link property="rdfs:subPropertyOf" href="http://schema.org/instrument" />
       <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/ExerciseAction"> ExerciseAction</a></span>
       <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/ExercisePlan"> ExercisePlan</a></span>
     </div>

This property is not much use without ExercisePlan so I suggest we 1.) also move it into health-lifesci (leaving the type for now), and add some workflow documentation that notes that core shouldn't have *properties* that rely on extension types. Those associations are added in the extensions as annotations.

**Comment by twamarc** [comment]
+1
As discussed I support to move them both to extension.
