### ISSUE TITLE
What sort of Thing is the atmosphere?

### ISSUE THREAD

**Issue by martinjuckes** [schemaorg/schemaorg#1118]
I'm leading a project developing a data platform for climate data (www.clipc.eu) and it would clearly be good thing to mark up some of our data with schema.org metadata. The data we have is split into properties (e.g. temperature) of the land, atmosphere and ocean, so a good starting point might be to create an enumeration of parts of the environment (we also have properties of glaciers, ice sheets, sea ice and many over specific things within the Earth system). My impression is that these won't fit under any of the top level types -- but I'm new to schema.org so I could well be missing something. The atmosphere is, I think , too tangible to go under "intangible", and to extensive to be considered a "place".  Otherwise, would it make sense to define an "environmentalEntity", analogous to a "MedicalEntity".

**Comment by danbri** [comment]
Hmm, the closest we have is http://schema.org/Landform as a kind of place. I can just about imagine atmosphere and ocean as 'places' but the word 'land' is a poor fit there. There's a sense in which the whole planet is a place too, but I doubt the properties are a good fit. Do you have some examples of the kind of properties you're looking to attach? We've had some discussion about weather in #362 too...

@rvguha @6a6d74 any thoughts?

**Comment by martinjuckes** [comment]
Well, http://schema.org/BodyOfWater is already listed as a Landform, so it would be possible to add a "BodyOfAir". However, your question about the properties to attach sent me back to various usage examples, as I am still trying to work out how schema.org can help the general discoverability and linkedness of a range of web pages and datasets about the environment. It may be that a more suitable approach is via an http://schema.org/Enumeration (e.g. ComponentOfClimateSystem) with valid values "Ocean", "Atmosphere", "Land" etc. The key difference, which I hadn't realised before is that the LandForm "Mountain", for example, is designed to allow you to distinguish between different mountains, whereas I am interested in just labelling documents as being related to the atmosphere/ocean/etc.

The weather report discussion #362 is looking at methods of encoding data values into a schema.org document, whereas I am interested in labelling documents about the atmosphere and particular parameters in the atmosphere. I'm not sure whether the two can be handled together.
Using a "ComponentOfClimateSystem" enumeration, I would be able to mark up various "CreativeWork" items as being "schema.org/about ComponentOfClimateSystem=Atmosphere". It would be useful to extend this with "ParameterOfTheClimateSystem", taking values temperature, pressure etc (using an external list of such parameters).
