### ISSUE TITLE
Add PreOrderAction 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1125]
Proposed by @betehess via implementation at #1058. Creating an issue distinct from its implementation here.

> An order suggests that the thing being ordered is available. For legal reasons, this is different from a pre-order, where the item is not yet available and no promise is made re: availability.

**Comment by danbri** [comment]
See http://pending.webschemas.org/PreOrderAction

**Comment by RichardWallis** [comment]
Implemented in [release 3.5 ](https://schema.org/docs/releases.html#v3.5)
