### ISSUE TITLE
MusicGroup doesn't have a video property

### ISSUE THREAD

**Issue by mariusvetrici** [schemaorg/schemaorg#1129]
On this page:
http://schema.org/MusicGroup

There's this example (scroll to the bottom):
<img width="993" alt="00001020" src="https://cloud.githubusercontent.com/assets/9729098/14855647/833b9376-0c9d-11e6-9bce-f0a9a6c36c73.png">

However, the Schema specification doesn't mention any video property under MusicGroup.

I think this example should be re-written.

Thanks.

**Comment by danbri** [comment]
You're right, looks like a bug. http://schema.org/video is for embedded videos.  Thanks.

@vholland any thoughts (since you looked into music most deeply recently)? We might try saying that the video is "about" or has "creator" the group...

**Comment by vholland** [comment]
At one point, there was a discussion of adding  http://schema.org/video to http://schema.org/Thing. I'm guessing that example was written back then.

**Comment by jvandriel** [comment]
_"At one point, there was a discussion of..."_

Actually that discussion moved on from adding 'video' to adding 'associatedMedia' to schema.org/Thing. Although issue #292 still is open. I would love to bring it back to the table though.

**Comment by RichardWallis** [comment]
Example fixed sometime ago.
