### ISSUE TITLE
version or build hash on schema.org

### ISSUE THREAD

**Issue by ghost** [schemaorg/schemaorg#1141]
Hi,

it would be nice to have a version or even better a git hash value on the schema.org site to see which version was deployed. The reason for that is, I figured out that there is a link at the live site which does not work.

If you have a look at: http://schema.org/docs/schemas.html in the last sentence the last link to here does not work.

 So I wanted to fix it. After forking, cloning and checking the sources I realized that this problem was already fixed. So I guess the version which is deployed at schema.org is not the latest version :-)

BR Frank :-)

**Comment by danbri** [comment]
Thanks for the efforts! The new version also contains a new docs/howwework.html doc that makes some of our processes clearer, including more visible status for the webschemas.org dev version of the site. Maybe we should cross ref dev and published versions of each page too?

**Comment by danbri** [comment]
I've added the SCHEMA_RELEASE variable (3.0 currently) to the project's homepage. I think that's sufficient to close out this issue, though there are various other ways in which would could make clearer that the live site at schema.org isn't 1:1 with the current main github branch.

(I also looked somewhat briefly into ident and $Id$ but I don't think it's a great fit for this...)
