### ISSUE TITLE
Mark successorOf/predecessorOf as mutual inverses

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1142]
- http://schema.org/successorOf
- http://schema.org/predecessorOf

This is vocabulary originally from GoodRelations, and pre-dates our ability to express inverseOf relationships (which means cross-links between the corresponding pages are missing).

**Comment by mfhepp** [comment]
+1
This is also how it was defined in GoodRelations:
http://www.heppnetz.de/ontologies/goodrelations/v1.html#predecessorOf

**Comment by RichardWallis** [comment]
Fixed by commit df0d380947fadf62dcfe29436c1c7c69844107c3

**Comment by RichardWallis** [comment]
Ignore previous commit notice - caused by a typo in a not connected commit elsewhere.

~Richard
