### ISSUE TITLE
Inverse property of schema:brand

### ISSUE THREAD

**Issue by betehess** [schemaorg/schemaorg#1143]
Here is the use-case: a `Brand` should be able to associate a bunch of products that belong to that `Brand`, instead of letting the products declaring that they are part of the `Brand`.

It's about the `Brand` being authoritative for what belongs to it, and also about grouping those statements together.

For example:

```turtle
<http://www.apple.com/iphone/#thing> a schema:Brand ;
  schema:isBrandFor <http://www.apple.com/iphone-5/#thing>, <http://www.apple.com/iphone-6s/#thing> .
```

Note: I have no idea if `isBrandOf` would be a good term.

**Comment by mfhepp** [comment]
Hi Alexandre:
Can't this be handled at the level of the markup syntax? All relevant syntaxes except for Microdata have a mechanism for inverse properties, an even for Microdata there is a specification that would benefit from adoption?

See this thread

    https://lists.w3.org/Archives/Public/public-vocabs/2014Aug/0000.html

and

    https://www.w3.org/wiki/WebSchemas/InverseProperties (might not be 100% in sync with the final mechanism)
    https://github.com/w3c/microdata-rdf/issues/5

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by akuckartz** [comment]
Please do not create pairs of properties but use mechanisms like JSON-LD "@reverse" instead.

**Comment by mfhepp** [comment]
Alexandre:
I see your use-case, but I strongly suggest to handle the need for inverse properties at the level of the markup syntax instead of at the level of the vocabulary. We already had a lengthy discussion about this in the mailing list thread https://lists.w3.org/Archives/Public/public-vocabs/2014Aug/0000.html.

Simply use RDFa and the "rev" attribute and it will be perfectly fine to define the brand entity and nest the products inside.
```
<div typeof="schema:Brand">
  <h1 property="schema:name">Apple</h1>
  <div rev="schema:brand">
    <div typeof="schema:ProductModel">
      <div property="schema:name">iCanoe - Foldable Canoe with IOS9</div>
    </div>
    <div typeof="schema:ProductModel">
      <div property="schema:name">iBike - Foldable Bike with IOS9</div>
    </div>
  </div>
</div>
```

IMO the aspect of authority for declaring  a product belonging to a brand is pretty much independent of the exact markup patterns.

Martin

**Comment by jaygray0919** [comment]
@mfhepp Good advice Martin. But does **@reverse** work in JSON-LD structure that is accepted by Google Structure Data Testing Tool (GSDTT). If you have an example, would you share? We need to use **@reverse**  in a JSON-LD structure (not an RDFa structure) and are wrasslin' with GSDTT.

**Comment by betehess** [comment]
> I strongly suggest to handle the need for inverse properties at the level of the markup syntax instead of at the level of the vocabulary.

@mfhepp I had never used `@reverse` before and had completely forgotten about it. I agree this is the best way to do that.

> But does `@reverse` work in JSON-LD structure that is accepted by Google Structure Data Testing Tool (GSDTT).

@jaygray0919 Whether this is supported (or not) by the main data consumers was also my first question :-)

Apparently it works perfectly in GSDTT: (this is taken from [their own example](https://developers.google.com/structured-data/rich-snippets/articles#examples))

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@id": "#article",
  "@type": "NewsArticle",
  "mainEntityOfPage":{
    "@type":"WebPage",
    "@id":"https://google.com/article"
  },
  "headline": "Article headline",
  "image": {
    "@type": "ImageObject",
    "url": "https://google.com/thumbnail1.jpg",
    "height": 800,
    "width": 800
  },
  "datePublished": "2015-02-05T08:00:00+08:00",
  "dateModified": "2015-02-05T09:20:00+08:00",
  "author": {
    "@type": "Person",
    "name": "John Doe"
  },
  "description": "A most wonderful article"
}
</script>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Organization",
    "@id": "#organization",
    "name": "Google",
    "logo": {
      "@type": "ImageObject",
      "url": "https://google.com/logo.jpg",
      "width": 600,
      "height": 60
    },
    "@reverse": { "publisher": { "@id": "#article" } }
}
</script>
```

**Comment by jaygray0919** [comment]
TY @betehess Have looked all over for such an example. It was hiding in plain sight. @danbri I had wrongfully complained that **@reverse** did not work in GSDTT. Will stop complaining ...
