### ISSUE TITLE
Examples using JSON-LD @reverse and RDFa rev for reverse properties

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1144]
We usually avoid adding named reverse properties (e.g. memberOf and member are exceptions). We should have more examples using JSON-LD's @reverse and RDFA's rev syntax for specifying reverse relationships.

I am not sure the best place to highlight this as burying under specific types or properties will not aid discovery.

**Comment by betehess** [comment]
👍 

Maybe we can just add an entry in https://schema.org/docs/datamodel.html ? If that document is growing too big because of the examples, we could split it in several smaller documents at the same time.

**Comment by gkellogg** [comment]
Note that we add @itemprop-reverse [1] as an experimental Microdata attribute in the last round for this purpose. If it gets some use, we can likely make it an official part of Microdata.

I’ve noted that using @rev in HTML5 is now generating validation errors, although it is certainly legitimate when used with RDFa.

Gregg Kellogg
gregg@greggkellogg.net

[1] http://www.w3.org/TR/microdata-rdf/#reverse-itemprop <http://www.w3.org/TR/microdata-rdf/#reverse-itemprop>
