### ISSUE TITLE
How to use schema.org's actions to describe typical forms on websites?

### ISSUE THREAD

**Issue by maxboehm** [schemaorg/schemaorg#1149]
I recently stumbled upon actions within the schema.org vocabulary. As far as I understood them, they can be used to label forms and signalize their type of action.

As I want to label the actions on websites I manage, I am not sure how to label typical use cases I have found.

This are the cases I have currently deployed. Some are quite clear, others are rather fuzzy and for some of them I did not find any correspondent class at all.

Would you keep this labelling?

- search=SearchAction
- contact=CommunicateAction
- login=CheckInAction
- register=RegisterAction
- newsletter=SubscribeAction
- feedback=InformAction
- comment=CommentAction

And, how would you label this cases?

- upload_file(s)=?
- reset_pw=?
- filter=?
- abuse=?
- poll=?
- add2cart=?
- orderby=?

'filter' is the typical limitation of a resultset and 'orderby' is to change the order of a resultset by some criteria. 'reset_pw' is the typical form where you enter your email address and you get a mail to reset your password.

Thank you!
Max

PS.: [Cross posting](http://stackoverflow.com/questions/36982781/how-to-use-schema-orgs-actions-to-describe-typical-forms-on-websites).

**Comment by grgarside** [comment]
I agree with all the actions you labelled, apart from matching login to CheckInAction. CheckInAction is a child of CommunicateAction, which would strongly imply some sort of communication taking place as part of the 'check in'. I'm not sure I'd use this action in this way, but it does seem to be the closest one to fit.

For the others, here's my opinion:

- > upload_files

  [SendAction](http://schema.org/SendAction) seems most appropriate here, as it's for "electronically dispatching an object for transfer from an origin to a destination" which is essentially what uploading is.

- > reset_pw

  Possibly [UpdateAction](http://schema.org/UpdateAction) but similar to login there doesn't seem to be a really good fit for this kind of operation.

- > filter

  I'd use [SearchAction](http://schema.org/SearchAction) again. Filtering is essentially searching with a defined [query](http://schema.org/query).

- > abuse

  I'm not sure this is entirely enough information to choose an action for, but if this is essentially a 'report' feature, I'm not sure there's an action which fits this. All the actions such as [SuspendAction](http://schema.org/SuspendAction) suggest an immediate effect which wouldn't be the case with a user report.

- > poll

  Again, this is unclear exactly what this does, but if you're creating a poll with this action then I suggest [AskAction](http://schema.org/AskAction) as you're essentially asking a multiple choice question.

- > add2cart

  [BuyAction](http://schema.org/BuyAction) may fit but is a bit more absolute than just adding an item to the cart. More generally, adding a product to a cart is essentially adding an item to a list, which means you can use [AddAction](http://schema.org/AddAction) to add the item and [DeleteAction](http://schema.org/DeleteAction) to remove it.

- > orderby

  This is too similar to filtering that I'd use the same as filter: [SearchAction](http://schema.org/SearchAction).
