### ISSUE TITLE
Improve definition of property "encodingFormat" (vs "fileFormat")

### ISSUE THREAD

**Issue by tfrancart** [schemaorg/schemaorg#1155]
Current definition of encodingFormat on schema:MediaObject : "mp3, mpeg4, etc."

Proposal :
"The encoding of the media object. A good practice is to use mime types codes listed at www.iana.org/assignments/media-types/media-types.xhtml, such as "audio/mpeg", "video/ogg", etc."

**Comment by vholland** [comment]
+1

**Comment by sballesteros** [comment]
It may be good to clarify the difference with http://schema.org/fileFormat that explicitly ask for the MIME type.

**Comment by tfrancart** [comment]
Seems like encodingFormat is a duplicate of fileFormat ?

**Comment by danbri** [comment]
Coming to this late, but yeah - it seems both properties are in use in much the same way. The "fileFormat" property always had a weird name in that HTTP-streamed content is generally not thought of as "files". 

I suggest we converge them, by making encodingFormat the preferred term, and indicating fileFormat as supersededBy encodingFormat.

We would need to converge the textual definitions, and also

* allow encodingFormat on CreativeWork, not just MediaObject
* allow encodingFormat to take both Text and URL values; we allowed URLs to support scientific file formats on Dataset distributions i.e. DataDownload, when the format is well known and documented but doesn't have an IANA media type, see #1191. 
* we will need some wording to explain possible confusion around the "encoding" property, which relates the vaguer kinds of CreativeWork (like a Book or blog post) to specific digital representations e.g. particular ebook formats.
* will also need to scan through our examples and update accordingly (see below)

@rvguha - does this make sense to you?


## Examples that mention fileFormat

```-bash-3.2$ find . -name \*examples.txt -exec grep -Hn fileFormat {} \;
./examples.txt:8857:TYPES: accessibilityFeature, accessibilityHazard, fileFormat
./examples.txt:8869: <meta itemprop="fileFormat" content="image/png">
./examples.txt:8880: <meta property="fileFormat" content="image/png">
./examples.txt:8889:TYPES: fileFormat, accessibilityHazard, accessibilityFeature, accessibilityControl, accessibilityAPI
./examples.txt:8902:   <meta itemprop="fileFormat" content="text/html"/>
./examples.txt:8903:   <meta itemprop="fileFormat" content="image/png"/>
./examples.txt:8904:   <meta itemprop="fileFormat" content="text/css"/>
./examples.txt:8905:   <meta itemprop="fileFormat" content="text/javascript"/>
./examples.txt:8923:   <meta property="fileFormat" content="text/html"/>
./examples.txt:8924:   <meta property="fileFormat" content="image/png"/>
./examples.txt:8925:   <meta property="fileFormat" content="text/css"/>
./examples.txt:8926:   <meta property="fileFormat" content="text/javascript"/>
./examples.txt:8948: "fileFormat" : [```

**Comment by danbri** [comment]
Ok I have implemented this change, queued for review at http://webschemas.org/encodingFormat and http://webschemas.org/fileFormat . The phrasing is still a bit awkward, but we've effectively moved the definitions from fileFormat over to be the new preferred term encodingFormat. I've updated the examples to match, including changing values to be MIME style where needed.

**Comment by danbri** [comment]
We did it!
