### ISSUE TITLE
500 error served to W3C validator

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1157]
Both webschemas.org and schema.org (sdo-deimos / master codebase) give an HTTP 500 error to W3C's validator:

http://validator.w3.org/check?uri=http%3A%2F%2Fwebschemas.org%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

@RichardWallis can you have a look?

**Comment by RichardWallis** [comment]
Fixed in V3.0
