### ISSUE TITLE
"manufacturer" dropped from Product ?

### ISSUE THREAD

**Issue by radusi** [schemaorg/schemaorg#1158]
v2.2 has "manufacturer" Property for Product, while v3.0 hasn't [ in appears only for http://health-lifesci.schema.org/Product ]

**Comment by mfhepp** [comment]
Thanks for spotting this, this needs to be fixed!!!

**Comment by twamarc** [comment]
This comes from ``` med-health-core.rdfa (line 2239)``` 
mistakenly by extending the domain of  we ended up with:
``` 
<div typeof="rdf:Property" resource="http://schema.org/manufacturer">
  <span class="h" property="rdfs:label">manufacturer</span>
  <span property="rdfs:comment">The manufacturer of the product.</span>
  <link property="http://schema.org/isPartOf" href="http://health-lifesci.schema.org" />
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/DietarySupplement">DietarySupplement</a></span>
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Drug">Drug</a></span>
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Product">Product</a></span>
  <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Organization">Organization</a></span>
</div>
``` 
I suggest to remove the <link> line:
```  <link property="http://schema.org/isPartOf" href="http://health-lifesci.schema.org" /> ``` 
If it's in the following shape, then it will be fixed:
``` 
<div typeof="rdf:Property" resource="http://schema.org/manufacturer">
  <span class="h" property="rdfs:label">manufacturer</span>
  <span property="rdfs:comment">The manufacturer of the product.</span>
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/DietarySupplement">DietarySupplement</a></span>
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Drug">Drug</a></span>
  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Product">Product</a></span>
  <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Organization">Organization</a></span>
</div> 
``` 
But please note that the 2 new types extended for domain remains in: ``` health-lifesci.schema.org``` extension.

@RichardWallis :  Are you going to fix this together with the bug fixing https://github.com/schemaorg/schemaorg/pull/1159 or I submit another pull request for that?

**Comment by danbri** [comment]
I will hot fix this between releases. But shouldn't it still show up in the extensions section of the page, @richardwalli

**Comment by danbri** [comment]
Ah I see it now

**Comment by mfhepp** [comment]
thanks!
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
Ok, http://schema.org/docs/releases.html should show the fix now.

**Comment by danbri** [comment]
Confirming that this is still fixed - see http://schema.org/manufacturer - I'll close the issue. Thanks @radusi et al.
