### ISSUE TITLE
We should credit opendomain for the domain name

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#116]
My bad for not having done this already. --Dan

**Comment by opendomain** [comment]
Please re-open - you have buried the link to OpenDomain 
Please put in footer like https://xmpp.org/

**Comment by danbri** [comment]
Hi! We talked about this in Twitter DMs, right? I would advise against putting this in the footer, it's prominent in the FAQ - which will show up properly in the site navigation again after the next round of changes. The site needs to be less cluttered not more, as folks are browsing it on mobile. I think the FAQ page is a fair place for the acknowledgement, and I hope the wording there is grateful enough.

**Comment by opendomain** [comment]
The FAQ page is no longer linked and so the link no longer has exposure.

I have been asking about this for months. This is not the first time that we had this problem.

This may not be important to you, but it is important to me.  This is part of the agreement for the domain.

**Comment by danbri** [comment]
The FAQ page is also important to us.

It is temporarily less findable right now, but we are moving to a new
documentation system that will benefit everyone.
