### ISSUE TITLE
Problem with ItemList

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#1175]
Example 4 on this page:

[https://schema.org/ItemList](url)

concatenates two types ("@type": ["ItemList", "CreativeWork"],).

But GSDTT throws an error "ItemList (`The @type is required and cannot be an empty string.)`

Despite the error, GSDTT appears to handle the structure correctly. It's an `ItemList`, it recognizes the `@type MusicRecording` and properly handles `itemListElement`.

Is the error message a "false negative" or is there another method to implement Example 4?

/jay gray

**Comment by danbri** [comment]
The Google SDTT tool does not have a good understanding of entities with multiple types, unfortunately. It's a known problem within Google and not something we can directly affect here, so I'll close this issue. But thanks for reporting the problem! http://json-ld.org/playground/ is also a good place to double check JSON-LD issues.

**Comment by jaygray0919** [comment]
@danbri You do a brilliant job at managing a huge project. Always a light but directed touch. Many on other similar projects could learn from your approach. Hats off to you.
