### ISSUE TITLE
change to Dataset?

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#1179]
Google SDTT is throwing an error on Dataset:
"The property includedInDataCatalog is not recognized by Google for an object of type Dataset."

A couple of weeks back, this was valid:

```
<script type="application/ld+json" id="24">
{
"@context":
    {
        "@vocab": "http://schema.org/",
        "id": "@id",
        "graph": "@graph",
        "type": "@type"
    },
"graph":
    [
        {
        "type": "Dataset",
        "id": "http://example.com/identifier/type/CreativeWork/Dataset/12170300001001",
        "name": "Occupation title",
        "url": "",
        "description": "",
        "includedInDataCatalog":
            {
            "type": "DataCatalog",
            "id": "http://example.com/identifier/type/CreativeWork/DataCatalog/12180300001001"
            }
        }
    ]
}
</script>
```

Anthing changed here?

**Comment by jaygray0919** [comment]
has a dup when GitHub was locked up

**Comment by joshsh** [comment]
Interesting that it was previously accepted.  Substituting the old "catalog" for "includedInDataCatalog" succeeds.

**Comment by jaygray0919** [comment]
We are seeing several unexpected results; ones that are different from a baseline we ran during a 30-60 day period about a month ago.

**Comment by danbri** [comment]
This is not a Google forum, we cant handle Google SDTT problems here. That said I will mention that in process of updating that tool for v3 (still in progress) some problems with v3 have come to light. So whatever trouble you have is not caused by a change to v3 as that update is still in progress.
