### ISSUE TITLE
Content negotiation

### ISSUE THREAD

**Issue by athalhammer** [schemaorg/schemaorg#118]
Hi,

I was wondering if it would make sense to consider different RDF serializations as a possible output format rather than RDFa only. This could happen via content negotiation. If you are a search bot and you would like to get some more information about the underlying schema you would ask most vocabulary pages in a way similar to the following:

    curl -H "accept: application/rdf+xml" "http://schema.org/inLanguage"

Now, if the response header provides HTML rather than the suggested format, the bot could start parsing the page wrt RDFa and find out that there is indeed some useful information. Alternatively, schema.org could respond with a corresponding header that suggests that the returned entity can be parsed with a corresponding parser. From what I know, the latter option would be more in line with current best practices.

Andreas

**Comment by athalhammer** [comment]
see #317

**Comment by danbri** [comment]
We now have datestamped releases in a variety of formats, but no plan to conneg these. You can find the files in data/releases/* in the repo or the most recent variants at http://schema.org/docs/developers.html
