### ISSUE TITLE
New AggregateReview type

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1182]
Sites with reviews of local businesses often have reviews of both the business and the individual services offered. Currently, it is difficult to maintain the order of the individual reviews. I propose adding a new `AgregateReview` type which is a subtype of both `Review` and `ItemList` to allow marking up these sites. A brief example would be:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Service",
  "name": "Hair coloring",
  "provider": {
    "@type": "HairSalon",
    "name": "Local Neighborhood Salon",
    "review": {
      "@type": "Review",
      "description": "Review of Local Neighborhood Salon"
    }
  },
  "review": {
    "@type": "AggregateReview",
    "reviewCount": 2,
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "item": {
          "@type": "Review",
          "creator": {
            "@type": "Person",
            "name": "Tara B."
          },
          "dateCreated": "2016-05-24",
          "description": "I love my new color!",
          "reviewRating": {
            "@type": "Rating",
            "worstRating": 1,
            "bestRating": 5,
            "ratingValue": "5"
          }
        }
      },
      {
        "@type": "ListItem",
        "position": 2,
        "item": {
          "@type": "Review",
          "creator": {
            "@type": "Person",
            "name": "Laura L."
          },
          "dateCreated": "2016-05-22",
          "description": "Color did not last",
          "reviewRating": {
            "@type": "Rating",
            "worstRating": 1,
            "bestRating": 5,
            "ratingValue": "2"
          }
        }
      }
    ]
  }
}
</script>
```

**Comment by vholland** [comment]
See pull request #1183 for more details.

**Comment by jvandriel** [comment]
Is there a real need to preserve the order beyond ```dateCreated``` and/or ```datePublished```, or in other words, what's the value for publishers*?

*_I'm trying to think of situations where I think it'd be useful, but even though I work for a review site I don't see why I should use it._

**Comment by jvandriel** [comment]
To be a bit more specific, this is an example of the type of markup I'm talking about:
```
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "Explosive Tennis Balls",
  "brand": {
    "@type": "Corporation",
    "name": "Acme Inc.",
    "review": {
      "@type": "Review",
      "reviewBody": "This company's products deliver a serious bang for your buck."
    }
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "reviewCount": 2,
    "bestRating": "5",
    "ratingValue": "3.5",
    "worstRating": "1"
  },
  "review": [{
    "@type": "Review",
    "author": {
      "@type": "Person",
      "name": "Tara B."
    },
    "datePublished": "2016-05-24T15:52:01+00:00",
    "reviewBody": "I love the colors of the explosions.",
    "reviewRating": {
      "@type": "Rating",
      "worstRating": 1,
      "bestRating": 5,
      "ratingValue": "5"
    }
  },{
    "@type": "Review",
    "author": {
      "@type": "Person",
      "name": "Laura L."
    },
    "datePublished": "2016-05-22T22:37:58+00:00",
    "reviewBody": "My tennis balls didn't explode.",
    "reviewRating": {
      "@type": "Rating",
      "worstRating": 1,
      "bestRating": 5,
      "ratingValue": "2"
    }
  }]
}
</script>
```

**Comment by vholland** [comment]
@jvandriel Yes, not all publishers order by date. Sometimes they order by "useful" where the definition of useful is not defined (at least externally).

**Comment by radusi** [comment]
It would be useful also for products, not only services, wouldn't it ? Thank you, both

**Comment by vholland** [comment]
@radusi Yes. I don't think we should limit to Services. That was a convenient example.

**Comment by jvandriel** [comment]
I get your point @vholland, although doesn't that imply there should also be a ```order``` or ```sortOrder``` property for ```AggregateReview``` so to be able to provide some context as how the list is ordered, eg 'usefulness', 'best reviewed', etc? 

And just so that I don't blame myself later for not asking, how do you feel about naming the type ```ReviewList``` instead?

And how about making it a sub type of ```Rating``` as opposed to ```Review```?
That way it won't inherit ```reviewBody``` and ```reviewrating``` - which are properties for a single ```Review``` - but inherit ```reviewCount```, ```bestRating```, ```ratingValue``` and ```worstRating``` - thus making it able to add the aggregated rating.

Plus ```Review``` doesn't have a ```reviewCount``` property, ```AggregateRating``` does however.

**Comment by vholland** [comment]
In the pull request, I have:

1. Made AggregateReview a subtype of both Review and ItemList. This gives it the properties of both (including itemListOrder).
2. Added AggregateReview to the domain for reviewCount.

I disagree that this should be a subtype of AggregateRating as it's not a Rating and may not have rating scores.

Also, I think it is clearer from the name AggregateReview that it is a combination of reviews of a single item rather than a list of reviews, which may or may not be related.

**Comment by betehess** [comment]
Just asking: why defining such a new class when a thing can already has 2 (or more) different types? It seems more modular that way.

**Comment by mfhepp** [comment]
Can't we simply use itemReviewed to keep separate reviews about a place from reviews about its products and services?

I am sorry to say that I am not convinced by the motivation and modeling approach.

Also, this is not really an aggregate review, because any averages etc. will be meaningless, comparing apples and oranges.

If the motivation for this comes from advanced Google snippets that keep apart the place (e.g. Mario's Deli) from its products (e.g. the Pizza Hawai at Mario's Deli), then simply recommend the use of two Review or AggregateReview entities, one referring to the place and one for each of its products or services.

I am very much in favor of extending the review model, because we also need support for dimensions of a review (cleanliness, food, quality of service, ...) and context (e.g. who is the reviewer - single traveler, family, business, ...).

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
@betehess I'm certainly in favour of more free-form multiple inheritance (e.g. sites using Book + Product together on one entity) and wish for better tool support there. However it is still useful to have some cases where the multiple supertypes are anticipated in advance and their combination named. We do that for the LocalBusiness hierarchy, for example, and it removes a little markup complexity.

**Comment by vholland** [comment]
@mfhepp Yes, there can be multiple reviews, but it is difficult to maintain order of the data when given a bunch of triples. The idea is AggregateReview would use ItemList to allow the order to be maintained.

**Comment by mfhepp** [comment]
@vholland If preserving order is a general problem, I think a quick fix specific solely for reviews makes schema.org pretty confusing.

Can't you achieve the same goal by creating and https://schema.org/ItemList of https://schema.org/Review entities, each pointing to the respective reviewed item via itemReviewed? This would preserve the order in the very same way as your proposal without introducing a pretty proprietary pattern.

**Comment by vholland** [comment]
This was superseded by the addition of AggregateRating.
