### ISSUE TITLE
We have relatedTo and isRelatedTo. This is embarrassing.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1187]

**Comment by danbri** [comment]
(This is our 400th open bug. Do I get a prize?)

**Comment by jaygray0919** [comment]
It depends on whether it is a item in ListItem with position: 400.

**Comment by danbri** [comment]
Oh, I forgot to fully complain: relatedTo and isRelatedTo mean very different things.

**Comment by tfrancart** [comment]
See also #1152
