### ISSUE TITLE
Add details to the property Global Location Information in Organization

### ISSUE THREAD

**Issue by ekgs1** [schemaorg/schemaorg#119]
Links have been provided to GS1 pages on GTIN8, GTIN13 and GTIN14 in Offer and Product. It would be helpful as well to add links to GS1 information on the Global Location Number in the Organization class. These are the links to the GS1 Global Data Dictionary definition for GLN as well as the GS1 GLN Summary:
 
http://apps.gs1.org/GDD/glossary/Pages/Global%20Location%20Number%20(GLN).aspx
http://www.gs1.org/barcodes/technical/idkeys/gln

**Comment by danbri** [comment]
@ekgs1 - do you have a single preferred link? Ifwe add one link for GLN, which should it be?

Is https://en.wikipedia.org/wiki/Global_Location_Number accurate?

**Comment by danbri** [comment]
(I've emailed Eric to ask advice too, awaiting reply...)

**Comment by danbri** [comment]
From @ekgs1 : "This link provides the best summary on the Global Location Number. http://www.gs1.org/barcodes/technical/idkeys/gln"

**Comment by danbri** [comment]
Done - thanks Eric!

**Comment by danbri** [comment]
FYI this launched last week with v2, http://schema.org/docs/releases.html#v2.0 http://schema.org/globalLocationNumber - thanks @ekgs1 :)
