### ISSUE TITLE
DataDownload is subtype MediaObject - definition of latter needs tweaking

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1190]
Considering #1083 http://schema.org/DataDownload is technically a MediaObject, however this is mostly about images/videos. If we keep this, the definition of MediaObject should be updated. Otherwise we could take the best properties from it and attach them to DataDownload directly.

**Comment by agbeltran** [comment]
I think it would be better to make DataDownload not a subtype of MediaObject, as MediaObject name already has some connotation about 'media' files (even if its definition could change) and it is not generic enough for any Dataset.

**Comment by sballesteros** [comment]
I wonder if it would not make sense for schema.org to have a systematic separation between creative works and their 'encoding'.  
For instance:
-  Dataset (work) and DataDownload (encoding) 
-  Image (work, currently non existing) and ImageObject (encoding)
-  Video (work , currently non existing) and VideoObject (encoding)
- etc. 

That will make it super easy to use the `encoding` property of `CreativeWork` (or `distribution` for `Dataset`). While I am at this, it may make sense to deprecate the `distribution` property of Dataset and just have `encoding`.

In that world it would be great to have DataDownload as a subclass of the parent class for all things encoding (right now that parent class seems to be MediaObject).

So we would have 2 parent classes CreativeWork and Encoding (currently MediaObject). A sort of super simplified [FRBR](https://en.wikipedia.org/wiki/Functional_Requirements_for_Bibliographic_Records) model.

**Comment by tfrancart** [comment]
See also #1153

**Comment by danbri** [comment]
Doing a FRBR-lite is a perpetual temptation. For now I would like to make some minimal tweak to the MediaObject definition to make DataDownload a more acceptable subtype. Scanning CreativeWork for all FRBR-like structures and reconciling them is a much larger job. It might be that we could put most CreativeWork subtypes somewhere on a Work-Expression-Manifestation-Item spectrum...
