### ISSUE TITLE
fileFormat assumes registered mediatypes - need an idiom for obscure formats

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1191]
#1083 

usecase: describing scientific datasets where the formats are relatively obscure (but still known within their community). URLs to well known READMEs are often the best thing out there - how to express these in schema.org.

**Comment by agbeltran** [comment]
For domains such as life sciences, there are resources such as [BioSharing.org](http://biosharing.org), which compile information about the standards (formats, ontologies, minimum information guidelines) used by different communities. 

Vocabularies such as DCTerms have the notion of conformance to standards (e.g formats) - see [http://purl.org/dc/terms/conformsTo](http://purl.org/dc/terms/conformsTo).

An approach like this has been used in [HCLS dataset description](https://www.w3.org/TR/hcls-dataset/) and the [bioCADDIE DATS model](https://biocaddie.org/workgroup-3-group-links).

**Comment by tfrancart** [comment]
See also #1155 ?
