### ISSUE TITLE
Review & Mapping by Biocaddie DATS [Metadata Working Group 3]

### ISSUE THREAD

**Issue by proccaserra** [schemaorg/schemaorg#1196]
*linked to the following issue, "Improving Dataset descriptions":
https://github.com/schemaorg/schemaorg/issues/1083

*NIH BD2K BioCaddie DATS slides:
https://biocaddie.org/sites/default/files/d7/webinar/551/datameddatsv2-webinar-1jun2016.pdf

presented during the following seminar:
https://biocaddie.org/events/webinars/special-webinar-datameds-dats-model-annotated-schema-org

*Mapping File between BioCaddie DATS elements and Schema.org/LifeScience extension:
https://docs.google.com/spreadsheets/d/1la7Cpg1TAURNgjHyzhjf3MH8KWvO1ASjt7APvkCpXx0/edit#gid=0
- BioCaddie DATS JSON-LD context file corresponding to the Mapping above:
  https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/DATS-context.jsonld

by @agbeltran & @proccaserra

schema.org
-No notion of Grant , Funding agency (but there is sponsor)
-No notion of Data Model, Specification, Standard (closest match: DigitalDocument and relation

lifescience-extension
-No notion of variable (dependent or independent)
-Need to extend/refine Substance to allow talking about Protein, RNA, DNA, small molecules.
-Study restricted to 'Medical Study' (ie only Human can be participants) 
-TreatmentAgent only available in the context of 
-Treatment intensity only available to 'physicalExercise'
-No notion of 'Organism' except in the context of an infection agent.

work with Bioschema.org group too.

**Comment by agbeltran** [comment]
Also related to [#1991](https://github.com/schemaorg/schemaorg/issues/1191), [#383](https://github.com/schemaorg/schemaorg/issues/383), [#1190](https://github.com/schemaorg/schemaorg/issues/1190).

**Comment by danbri** [comment]
Thanks for theseI For the core schema.org issues:

1.) "No notion of Grant , Funding agency (but there is sponsor)". 

In http://schema.org/docs/releases.html#g1083 we have now 'funder' property, "A person or organization that supports (sponsors) something through some kind of financial contribution."  (sub-property of sponsor)

This addresses the most basic usecase, but does not let us directly talk about a specific *grant*. Events, organizations, creative works, and also people can have funders; but we don't have grants as a type, or the somewhat related notion of a project. I would be interested to look into the latter first, as it could also help improve our coverage of opensource software efforts and suchlike. Perhaps @rvguha has thoughts on how we could handle this. You could take the view that a project is a subtype of Organization, or you could model things using existing (longer-lived multi-project) organizations, with the "project" handled more as their CreativeWork output. I'm not sure which works best.

How much interest / value is there in having a type for Grant? 

2.) "No notion of Data Model, Specification, Standard (closest match: DigitalDocument and relation"

This is interesting. Could you give some specific examples? Are we concerned here solely with datasets, or would this apply to ScholarlyArticle and other works in general too? Is the data widely available?

**Comment by agbeltran** [comment]
Thanks @danbri for all the comments.

On point 1). 

Since @proccaserra posted the issue, we followed the addition of https://schema.org/funder and are using it (see e.g. https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/contexts/dataset_sdo_context.jsonld).

I agree that looking at the addition of Project in the first instance would be better to tackle this from a more generic perspective. 

I think that having Grant would be useful (at least from the academic perspective). Issue #383 is also about this and it refers to the FundRef API (http://help.crossref.org/fundref-api) that represents funders/works/grants and it would be great to link to it from our project's perspective ([DataMed](http://datamed.org)/[DATS](http://github.com/biocaddie/WG3-MetadataSpecifications/)).

**Comment by danbri** [comment]
What would you suggest for a supertype for Grant? (and/or Project?). Is "Funding" in #383 broadly same as a Grant? (/cc @hubgit). We should probably move to #383 for that discussion...

**Comment by dr-shorthair** [comment]
Of course 'Project' is probably a sub-class of 'Action' - being a time-bounded thing with inputs and outputs. 'Grant' is a kind of academic shorthand for 'externally funded project'. I did a bit of a survey of how the notion of 'project' is modeled in various vocabularies. The DBPedia ontology has far and away the richest model, though as usual it has some some curious fluff on it as well. 
See http://dbpedia.org/ontology/Project and also http://dbpedia.org/ontology/ResearchProject
