### ISSUE TITLE
schema.org presentation for use and reuse

### ISSUE THREAD

**Issue by rajido** [schemaorg/schemaorg#1197]
I will give a talk about schema.org on Sunday (June 12, 2016) in a popular bioinformatics event ... http://2016.biohackathon.org/ ... I was wondering if you know about slides or any other resource that I could use/reuse for my presentation.

The audience has a clear affinity for semantic web and RDF topics. The title of my talk is “Impact of schema.org in the semantic web and interoperability of life sciences data”.

Any help would be much appreciated. 

Regards,
Rafael

**Comment by RichardWallis** [comment]
You are welcome to use slides from any of my presentations:
http://www.slideshare.net/rjw/presentations

This type of message would probably be best placed on the https://lists.w3.org/Archives/Public/public-schemaorg/ mailing list.

~Richard.

**Comment by Aaranged** [comment]
Here are two further essential external resources, IMO, and pointer to an on-site resource it's easy to misss.  Note that Phil and Lorna's document is published under a CC-By licence, so you can use their work with attribution.

Schema.org: Evolution of Structured Data on the Web
http://queue.acm.org/detail.cfm?id=2857276

What is Schema.org?
http://publications.cetis.org.uk/2014/960

How we work - schema.org
https://schema.org/docs/howwework.html
