### ISSUE TITLE
/AppliancePartsStore as an exact schema

### ISSUE THREAD

**Issue by abonez** [schemaorg/schemaorg#1199]
Appliance Parts stores are specific entities that can be better identified than /Store. Requesting review to add Schema.org/AppliancePartsStore as an approved type.

Reference document: https://docs.google.com/spreadsheets/d/1Ed6RmI01rx4UdW40ciWgz2oS_Kx37_-sPi7sba_jC3w/edit#gid=0

**Comment by mfhepp** [comment]
Categories for stores based on the types of products they offer are inherently problematic. I think this can be better handled by attaching offers that describe the range of products. 

Also note that you can always use external types via http://schema.org/additionalType or multi-typed entities in RDFa or JSON-LD.

If such a feature is needed, I would rather expand the domain of http://schema.org/category to include http://schema.org/Place.

**Comment by abonez** [comment]
Thank you for the review. I agree that offers are a great way to refine and be more specific. From the list that is linked above, there are examples of Jewelry Stores: http://schema.org/JewelryStore and Furniture Stores. Are those different or do you consider those in the same problematic bucket?

**Comment by abonez** [comment]
Hello! We reviewed this and have a follow up question. Could we possibly do Schema.org/ReplacementPartsStore - this is a distinct entity not reliant on the category or types of products. Whole goods are not sold and it is inherently a place where parts can be found. Thoughts?

**Comment by mfhepp** [comment]
Even if we already have quite some distinct types for stores, I strongly suggest to treat this as a difficult legacy and refrain from adding more. We know from product taxonomies like eClass, UNSPSC or ETIM that there are tens of thousands of product categories and thus classifying a store by the mix of products or services it is offering is a dead end. Just use http://schema.org/Store and describe the range of products and services via offers (don't need to have a price - can be generic just saying you offer spare parts) or via schema:name and schema:description.

**Comment by jaygray0919** [comment]
And as the product taxonomies publish their vocabularies as structured data, we can include their data in a complementary graph.

**Comment by RLRichardson** [comment]
1000% (no typo) agree with Martin on this point.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Jun 17, 2016 at 2:46 AM -0400, "Martin Hepp" <notifications@github.com<mailto:notifications@github.com>> wrote:


Even if we already have quite some distinct types for stores, I strongly suggest to treat this as a difficult legacy and refrain from adding more. We know from product taxonomies like eClass, UNSPSC or ETIM that there are tens of thousands of product categories and thus classifying a store by the mix of products or services it is offering is a dead end. Just use http://schema.org/Store and describe the range of products and services via offers (don't need to have a price - can be generic just saying you offer spare parts) or via schema:name and schema:description.

�

**Comment by abonez** [comment]
Thank you for the comments and clarification on the direction of Schema moving forward. Nesting more specific properties inside a general schema makes sense. We will proceed with that option. The confirmation that we can mark up an offer without price or an exact product is good to hear. I was not sure if that was acceptable or not. Thank you all!
