### ISSUE TITLE
Missing property invoiceID on Invoice

### ISSUE THREAD

**Issue by nikolaik** [schemaorg/schemaorg#1206]
Hi, most countries requires invoices to be uniquely identifiable and I'm not sure if there is an existing property representing that information today on https://schema.org/Invoice. Or am I missing something? Do you have a suggestion for what property could be used for that?

If not, I suggest adding an invoiceID property to Invoice, f.ex. to make importing to accounting software from marked up emails easier.

**Comment by chaals** [comment]
I can't see anything - `disambiguatingDescription` seems the closest, but it seems to me that this is ust an oversight and we should have `invoiceID` or something.

**Comment by danbri** [comment]
We could add a custom property for this, or consider adding a once-and-for-all Text-valued "identifier" property at the thing level. This would complement the existing sameAs mechanism which can handle all existing URL-based identifiers. We could then go through and declare (probably) dozens of existing text-valued identifier properties (e.g. gtins) as sub-properties.
