### ISSUE TITLE
Should i use "Webpage" or "Article" or i can use both of them simultaneously?

### ISSUE THREAD

**Issue by zenyaz** [schemaorg/schemaorg#1208]
For example i have information article about TeddyBears (8000 letters).
I want to use following scheme

```
WebPage {
  WPHeader
    <main itemprop="mainContentOfPage">
          <article itemscope itemtype="http://schema.org/Article">
                   Text about TeddyBears
          </article>
</main>
  WPFooter
}
```

As you see i use both WebPage and Article entities.
Validator not show mistakes, but how search engine will understand my page?
Is it normally, or i must choose something one of them?

Or, by the way somewhere i must use "MainEntity" property. Where?

**Comment by khusamalfas** [comment]
@zenyaz i think you need to use MainEntity in place MainContentOfPage so it's will be look like 

`WebPage {
  WPHeader
    <main id="main" itemprop="MainEntity" itemscope itemtype="http://schema.org/Article" itemid="URL/#main">
<article >
         <header id="articleid" class="articleid">
<h1 itemprop="name headline">This article title</h1>
</header>
          <div class="articletext" id="articleid" itemprop="articleBody">
                   Text about TeddyBears
         </div>
          </article>
</main>
  WPFooter
}`
