### ISSUE TITLE
Add information about places available at event

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#1209]
There should be some way to identify the number of places that are available for an event. Both in total, as sometimes it matters whether an event in a small gathering of a few people or a coming together of thousands, and also the number of places that remain available, as sometimes it is useful to know that an event is about to sell-out. 

This came up in the context of educational courses as events (see [email discussion](https://lists.w3.org/Archives/Public/public-schema-course-extend/2016Apr/0000.html) for the schema-course-extend group, also mentioned in issue #1092); but seems broader than educational courses.

I suggest two properties:
eventCapacity: integer; the total number of individuals that may attend the event.
placesRemaining: integer; the number of places for the event that remain unallocated.

(Maybe the inventoryLevel property of Offer can be used for places remaining, but it would require a change to the definition)

**Comment by vholland** [comment]
It seems reasonable to me.

I was originally going to suggest we add this to Place instead, but there would be no way to express the capacity for virtual events. Should we change the name to ```maximumCapacity``` and add it to both http://schema.org/Event and http://schema.org/Place?

In which case, I would suggest renaming ```placesRemaining``` to ```remainingCapacity``` to make it clearer the two properties are related.

**Comment by chaals** [comment]
+1 to @vholland's suggestion (for some reason the reaction thing didn't seem to work). Also because not mentioning "place" removes ambiguity.

**Comment by danbri** [comment]
This looks good to me, and the tweaks are good improvements. Additional LGTM's and comments welcomed from @scor @shankarnat @tmarshbing @nicolastorzec @rvguha and /cc @mfhepp who is supposed to be on vacation and not reading Github right now. 

As soon as I'm done wrapping up the housekeeping from the 3.1 release I'll get this merged into our next release branch.

Thanks!

**Comment by nicolastorzec** [comment]
+1: very useful for Event and Places.

Many events and places actually distinguish even further: e.g. seat capacity, standup capacity, capacity for disabled persons, etc.

**Comment by danbri** [comment]
Merged, although I think I'd rather rename these to include some notion of 'attendee' in the name.

For comparison, we have https://schema.org/vehicleSeatingCapacity which indicates what the capacity is about.

**Comment by danbri** [comment]
Queued for review as part of next release via http://webschemas.org/docs/releases.html#g1209

"Added maximumAttendeeCapacity and remainingAttendeeCapacity for describing places and events."
