### ISSUE TITLE
Meta-issue for sdo-makemake release (likely as version 3.1)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1212]
This issue tracks release planning for schema.org's release codenamed sdo-makemake.

The release is codenamed after the dwarf planet [Makemake](https://en.wikipedia.org/wiki/Makemake), and because our focus for this release is primarily fixups:

* The priority for the release is to correct some unintended reversions (#1203) that were included in 3.0 during the major changes that moved medical terminology into the health-lifesci extension. 
* Secondary priority is to get us back on a faster release cycle.
* Include "low hanging fruit" vocabulary improvements but publish ASAP rather than wait for more complex designs (e.g. hotels) to complete. We should always be ready to release a new version with low administrative cost; "waiting for x to be completed" is an unfortunate pattern to slip into.
* update July 26: we will include hotels too.

**Comment by danbri** [comment]
See webschemas.org/docs/releases.html for some more stuff that's in there. We are close to wrapping up hotels, and there is also some modest but useful polish around dataset description.

**Comment by danbri** [comment]
Proposed for release c/o https://lists.w3.org/Archives/Public/public-schemaorg/2016Jul/0015.html

**Comment by danbri** [comment]
Feedback received elsewhere in review (I'll edit this post)

* [From @vholland](https://github.com/schemaorg/schemaorg/issues/1262#issuecomment-236212226) w.r.t. amenityFeature, "can we change the domain to LocalBusiness (instead of the more specific LodgingBusiness)?"

**Comment by chaals** [comment]
Looks good to me.

**Comment by mfhepp** [comment]
Looks good to me, too.

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
thanks! ping @scor @shankarnat @tmarshbing

**Comment by danbri** [comment]
Relaying from @scor in 1:1 mail , "looks good!"

> Message-ID: CAGR+nnGFMEJ2FREjM0jn6vdn+auCM4Ye1unq_ptR6Kiz8BSbRA@mail.gmail.com
Subject: Re: Schema.org v3.1 release candidate (sdo-makemake branch) - please
 review for release in 1-2 weeks
To: Dan Brickley <danbri@google.com>
looks good! thanks for pinging me!

...and I heard from @shankarnat who is aiming to complete his review today (Aug 3rd).

**Comment by danbri** [comment]
ping @shankarnat @tmarshbing

**Comment by shankarnat** [comment]
Thanks Dan for pinging me, looks good to me.

**Comment by shankarnat** [comment]
Thanks Dan for Pinging me, looks good to me.

**Comment by danbri** [comment]
Ok, all reviews are in. Thanks everyone! There are some modest todos listed [above](https://github.com/schemaorg/schemaorg/issues/1212#issuecomment-236215279), and I'll make a final round of technical checks with @RichardWallis to try to avoid a repeat of the problems we had last time. Aiming for publication early next week! Thanks again :)

**Comment by danbri** [comment]
I believe all the little fixes listed [above](https://github.com/schemaorg/schemaorg/issues/1212#issuecomment-236215279) are now correctly implemented. I'm sketching this for a release next week on Tuesday 9th August.

**Comment by danbri** [comment]
Ok I have published tomorrow's release to http://schema.org/ 

Technically we are a few hours early, but it gives us time to verify that everything is functioning properly.

Thanks everyone!

**Comment by twamarc** [comment]
A possible bug on home page text of ```health-lifesci extension```: ```http://health-lifesci.schema.org/ ```:
It's just the text I think.
```The schema.org klzzwxh:0004 was klzzwxh:0005 in collaboration with klzzwxh:0006 and others. Recent improvements including the migration into the health-lifesci extension has been led by the Healthcare Schema (klzzwxh:0007) community group at W3C. The health-lifesci schema.org extension is US healthcare insurance networks for other collaborative schema.org extensions in topics centred on healthcare, medicine and the lifesciences (e.g. see also klzzwxh:0001, and the klzzwxh:0002 proposals for describing ).US healthcare insurance networks for other collaborative schema.org extensions in topics centred on healthcare, medicine and the lifesciences (e.g. see also klzzwxh:0001, and the klzzwxh:0002 proposals for describing ).````

**Comment by danbri** [comment]
Thanks @twamarc - could you post a screenshot somewhere? e.g. http://imgur.com/ or email it...

**Comment by danbri** [comment]
Don't worry, I see it now. @RichardWallis and I are investigating.

**Comment by danbri** [comment]
Seems to be mis-processing of the markdown fragments in https://github.com/schemaorg/schemaorg/blob/sdo-makemake/data/extdefs.jsonld#L39

**Comment by danbri** [comment]
Unless we find some other flaw I suggest we leave things up until a quick fix is ready (rather than roll back to 3.0, which has many other deeper problems than 3.1).

**Comment by danbri** [comment]
Worst case we expand the markdown manually to make it readable before blogging, but hopefully @RichardWallis will figure out the bug.

**Comment by twamarc** [comment]
![image](https://cloud.githubusercontent.com/assets/3585551/17488078/f95fa010-5d97-11e6-80bb-d53cfeb83ca2.png)

**Comment by twamarc** [comment]
ok! sorry posted the image before seeing your message. Ok Let's keep things as they are until a quick fix is ready. Thanks

**Comment by brewerdigital** [comment]
Dan,

Since numberOfRooms didn't make the final build, can it be removed from the
dedicated documentation page examples?

https://github.com/schemaorg/schemaorg/issues/915#issuecomment-200536969
"narrow down domain of numberOfRooms to House, Apartment, Suite and
SingleFamilyHome (to avoid e.g. Rooms to have a number of rooms property)"

Or was Martin trying to add it back in on Jun 23rd but had a typo by not
changing House text?
https://github.com/mfhepp/schemaorg/commit/2d62bdba7710616c62ecb7f137d3067e28b430e6?diff=split
"added Hotel to domain of numberOfRooms"

Brad

**Comment by danbri** [comment]
Thanks @brewerdigital - I'm not sure the intention there. @vholland @gmackenz do you have a sense for where the rough consensus ended up? It certainly looks like Martin meant something different with that last edit.

The property does exist btw, http://schema.org/numberOfRooms however it looks like "The number of rooms (excluding bathrooms and closets) of the acccommodation or lodging business. Typical unit code(s): ROM for room or C62 for no unit. The type of room can be put in the unitText property of the QuantitativeValue." needs updating. I think part of the awkwardness here was the different counting conventions for hotels versus anticipated future work on real estate listings.

**Comment by danbri** [comment]
@twamarc et al., I've just deployed a quick fix from @RichardWallis that seems to have repaired http://health-lifesci.webschemas.org/ - we'll need to investigate whether other pages are also affected, it's an issue with the python markdown library we're using.

**Comment by danbri** [comment]
Martin Cook reports:

    If I go here and click on a type in the hierarchy the site hangs:
    http://webschemas.org/version/3.1/ 
    Then I get : 

    =================
    Error: Server Error

    The server encountered an error and could not complete your request.
    Please try again in 30 seconds.

    =================
    Direct links from the release page work fine for me, though, and on poking around the pages look fine too.

I think that's from     <base href="/version/build-latest/" ></base> ... should it be /version/3.1/ ? @RichardWallis

**Comment by danbri** [comment]
I've committed a fix for that, and pushed to webschemas.org which now has working hyperlinks. I expect it will work on schema.org will won't update the site until @RichardWallis 's ready as we have markdown fixes to evaluate too.

**Comment by martin-nc** [comment]
Thanks - links working fine for me now at http://webschemas.org/version/3.1/.

**Comment by danbri** [comment]
http://schema.org/version/3.1/ is update too now, seems ok.

**Comment by danbri** [comment]
Ok, enough with the bugfixes. I think we're calling this done.

Blogged: http://blog.schema.org/2016/08/schemaorg-update-hotels-datasets-health.html

Thanks everyone!
