### ISSUE TITLE
Caching problems with JSON-LD Context output

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1219]
Requests to http://schema.org can either return the html home page or [_if an accept type of application/ld+json is passed in the request_] it can return the json-ld context file.

With http caching enabled, using etags etc. browsers (Chrome) are not differentiating between the two.  

Result is that if a browser has cached the context file, prior to visiting the home page, the user can be presented with JSON-LD output instead of the html home page.   

This happens if an in-browser application asks for the context file.   Example applications where this can occur include the [JSON-LD Playground](http://json-ld.org/playground/) and the [Openlink Structured Data Sniffer](http://osds.openlinksw.com/) extension tool. 

Also if the html version of the page has been cached in the browser when applications such as JSON-LD Playground request the context file, they get the html which causes an error reading the context.

Fix required to ensure that json-ld context and html home page are not confused in browser caches.

**Comment by danbri** [comment]
Steps to reproduce:

* 1. empty browser cache (last hour)
* 2. show Person example in json-ld playground
* 3. in other tab go to http://schema.org - get context file displayed

Related links:

* https://gist.github.com/danbri/b7d85676eb2bf01240020602cbca0ac7 (HEAD responses)
* [related Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=94369#c82)
* Jake's article, https://jakearchibald.com/2014/browser-cache-vary-broken/

From @lanthaler "It was the vary header as initially suspected.  When you respond with JSON-LD, you don't set it. You need to set it in all cases."

> curl -H "Accept: application/ld+json" -I http://schema.org/ 

The relevant code is at https://github.com/schemaorg/schemaorg/blob/sdo-makemake/sdoapp.py#L1064

        if (ENABLE_JSONLD_CONTEXT and (jsonld_score < html_score and jsonld_score < xhtml_score)):
            jsonldcontext = GetJsonLdContext(layers=ALL_LAYERS)
            self.response.headers['Content-Type'] = "application/ld+json"
            #self.emitCacheHeaders()
            self.response.out.write( jsonldcontext )
            return True

**Comment by RichardWallis** [comment]
Fixed in 3.1
