### ISSUE TITLE
schema.rdfa no longer defines domainIncludes/rangeIncludes

### ISSUE THREAD

**Issue by gkellogg** [schemaorg/schemaorg#1226]
Although an important part of defining the vocabulary, the file no longer actually defines `domainIncludes` or `rangeIncludes` as `rdf:Property` instances.

**Comment by RichardWallis** [comment]
These 'schema internal' values can now be found in the meta extension: http://meta.schema.org/

**Comment by gkellogg** [comment]
Also `inverseOf`.

**Comment by RichardWallis** [comment]
Terms defined or referenced in the 'meta' extension.

Types (2)
Class, Property
Properties (5)
category, domainIncludes, inverseOf, rangeIncludes, supersededBy

**Comment by gkellogg** [comment]
Okay, I missed that this had been moved to the "meta" extension.

**Comment by gkellogg** [comment]
@RichardWallis Where can I find the RDFa defining the extension vocabularies? I get the core vocabulary at http://schema.org/docs/schema_org_rdfa.html. The extensions are defined in GitHub under /data/ext/auto/auto.rdfa (for example), but not clear how it reflects through the web interface. Also, meta seems to be in transition? (meta.rdfaX or meta.jsonld).

**Comment by RichardWallis** [comment]
You are right about meta being in transition - from rdfa to jsonld.   meta.rdfaX should be removed.

Also in transition is what representation is available via a web interface, with the total graph of terms being constructed from an increasing series of source files.  As you have spotted http://schema.org/docs/schema_org_rdfa.html only now does part of the job.

Currently the only full dump of the full graph including extensions is available in quad form via git here: https://github.com/schemaorg/schemaorg/blob/sdo-makemake/data/releases/3.0/all-layers.nq

The intention is to expand on the different formats offered here, and potentially make some of them available via the web interface.

Suggestions welcome.

**Comment by gkellogg** [comment]
Thanks @RichardWallis, if the all-layers.nq file is kept up to date, that works nicely.

It would be nice to get a full RDF representation via the web interface, perhaps using content detection off of http://schema.org/ for an appropriate RDF type. This would be a problem for JSON-LD, because you likely don't want to include the RDFS definition along with the context, but other RDF types would be useful.

Alternatively, a descrbedby link relation might do.

For quad formats, placing the different layers in different named graphs makes sense, although not useful for my application. Turtle and/or TriG would be nice representations to support.
