### ISSUE TITLE
Remove 'category' from Meta extension?

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1228]
The [Meta extension](http://meta.schema.org/) defines `category` (in meta.jsonld. but not in meta.rdfaX), but it’s also defined in core’s schema.rdfa.

According to [the definition of `category`](http://schema.org/category), it doesn’t seem to be a property that is "primarily designed to support the implementation of the Schema.org vocabulary itself".

I think `category` should be removed from Meta. (Or does it serve a purpose there?)

**Comment by RichardWallis** [comment]
[`category`](http://schema.org/category) is extended in the [meta](http://meta.schema.org/ to include [Class](http://meta.schema.org/Class) and [Property](http://meta.schema.org/Property) in its range.  It is then used to categorize terms within an extension - 'Comics' terms within [bib](http://bib.schema.org/) - terms by issue in [pending](http://pending.schema.org/)

Meta.rdfaX, needs to be removed - Noted in (#1230)
