### ISSUE TITLE
[Interface/usability] Switching syntax for all examples at once

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1229]
I primarily use the examples to see if (and how) a certain property is used.  For that I switch each example to the intended syntax and start an on-page search (e.g., for `itemprop="sameAs"`).

I think it would be useful to be able to switch all examples to the intended syntax at once (instead of having to do this manually for each example).

(Not sure if it would be worth keeping the per-example switcher in addition; at least I never need to see _at the same time_ one example in, for example, RDFa and another one in, for example, JSON-LD.)

**Comment by thadguidry** [comment]
:+1:
