### ISSUE TITLE
Missing reference to extension defined Types in 'may appear as values' section

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1234]
If a Type that would appear in the "Instances of XXXX may appear as values for the following properties" listing is defined in an extension that is not being shown, that type is not displayed.

Example compare http://webschemas.org/ContactPoint with http://pending.webschemas.org/ContactPoint

In the latter HealthInsurancePlan is displayed as a type in the listing but not in the former.

**Comment by danbri** [comment]
Published via http://schema.org/docs/releases.html#v3.1
http://blog.schema.org/2016/08/schemaorg-update-hotels-datasets-health.html
