### ISSUE TITLE
4 not equal to 3

### ISSUE THREAD

**Issue by gasyoun** [schemaorg/schemaorg#1245]
At https://schema.org/docs/faq.html
`Bing, Google, Yahoo! and Yandex`  = 4
`schemas that three major search engines will support` = 3

How come?

**Comment by nerdfiles** [comment]
Because we invented the Periodic Table of Information, so now it's time to chart qubits in the web[0]. Dual-Aspect Blockchain in, digital dark age out.

—
[0]: https://yandex.com/support/webmaster/schema-org/what-is-schema-org.xml

**Comment by danbri** [comment]
Thanks, fixed.
