### ISSUE TITLE
Description (rdfs:comment) contains <pre><code>, making markup visible

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1246]
For http://webschemas.org/Article as well as http://schema.org/Article

```
<pre><code>  &lt;br/&gt;&lt;br/&gt;See also &lt;a href="http://blog.schema.org/2014/09/schemaorg-support-for-bibliographic_2.html"&gt;blog post&lt;/a&gt;.
</code></pre>
```

**Comment by RichardWallis** [comment]
There is a Pull Request (#1222) which covers this and other formatting issues introduced with Markdown capability that is targeted for 3.1

**Comment by danbri** [comment]
Ok #1222 is (manually) merged, and published to the webschemas site.

http://webschemas.org/Article is looking better...

I'll close this now but @RichardWallis if you can do a bit of sanity checking too that'd be great :)
