### ISSUE TITLE
Need easy way to download rdf definition files 

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1249]
At release time RDF files are created in .nt, .nq, turtle & jsonld formats for the core and extension vocabularies.

Although available via Github, these files are not available for developers, and others interested, to easily discover and download.

We need a downloads page linked from the documents page or a developers page.

**Comment by danbri** [comment]
Thanks, merged and queued for review: http://webschemas.org/docs/releases.html -> http://webschemas.org/docs/dumps.html

**Comment by danbri** [comment]
todo: fix typo "Defintion"

**Comment by danbri** [comment]
Done. Also linked to Github.

**Comment by RichardWallis** [comment]
Solved by the introduction of [Vocabulary Definition File download](http://schema.org/docs/developers.html#defs) feature introduced in 3.1
