### ISSUE TITLE
Expand the domain of schema.org/location to schema.org/Map

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#1250]
I'd like to request we expand the domain of ```location``` to ```schema.org/Map```.

Reason being that I'm currently working on a site that publishes maps with locations for certain things. Which lead me to discover there's no method of expressing locations on a map, let alone being able to express what those locations stand for. Which, to me, seems to sort of defeat the purpose of defining the data contained on a ```schema.org/Map```.

I'd like to be able to express things like this:

```
<script type="application/ld+json">
{
  "@context":"http://schema.org",
  "@type":"Map",
  "location":
  [
  {
    "@type":"LocalBusiness",
    "name":"Acme",
    "geo":
    {
      "@type":"GeoCoordinates",
      "latitude":"40.7141667",
      "longitude":"-74.0063889"
    }
  },
  {
    "@type":"LocalBusiness",
    "name":"Etc"
  }
  ]
}
</script>
```

Does this make sense to anybody else?

**Comment by thadguidry** [comment]
@jvandriel Your map describes a location ?

**Comment by jvandriel** [comment]
To be exact, the maps contain markers representing the locations of different types of things (including some data about per thing).

**Comment by thadguidry** [comment]
@jvandriel Right, so the answer is yes.  So instead of expanded the domain...which isn't really needed, just use our existing property for this purpose:  http://schema.org/contentLocation

**Comment by jvandriel** [comment]
Well, that resolves it. thanks for pointing out the property @thadguidry.

**Comment by thadguidry** [comment]
@jvandriel Hey... let's explain better for others next time... make a pull request to expand the description of contentLocation to say .... in a photograph or painting or a map.
