### ISSUE TITLE
Move Fibo.schema.org v1.0 proposal in pending for review

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1253]
**Move proposal from Pull Request (#1163)  for a FIBO financial extension into _pending_ extension referencing this issue.**

_Text from PR:_
This Pull Request constitutes a proposal for a FIBO extension to Schema.org from the [Financial Industry Business Ontology Community Group](https://www.w3.org/community/fibo/).

This proposal builds upon the the new types and properties for the support of financial products and services introduced into Schema.org V3.0.

It introduces a first raft of new and modified Types and Properties to support in more detail the requirements for sharing financial products, services and organisations using Schema.org on the Web. This initial (v1.0) proposal has a focus on the area of loans, plus the addition of some more generally useful terms.

The proposal offered by the Group is based on the work of the [Financial Industry Business Ontology project](http://www.fibo.org/schema) to extend the capabilities of Schema.org aligned with the Financial Industry Business Ontology (FIBO). This has been a team effort utilising the expert knowledge and know-how of members of the FIBO Content Team involved in creating the Financial Industry Business Ontology, working with others familiar with Schema.org including Mirek Sopek, and Richard Wallis.

More detail and links to the definitions in a test version of schema.org (http://fibo.sdo-fibo.appspot.com/) are available in the [Group Wiki](https://www.w3.org/community/fibo/wiki/Fibo.schema.org_v1.0_Proposal).

**Comment by danbri** [comment]
Hi FIBO folk. Could you please give a short list of the terms that you're proposing we allocate? Is it (from http://fibo.sdo-fibo.appspot.com/):

* Types (6): BrokerageAccount, ExchangeRateSpecification, InvestmentFund, MoneyTransfer, MortgageLoan, RepaymentSpecification
* Properties (25):, bankAccountType, beneficiaryBank, cashBack, contactlessPayment, currentExchangeRate, domiciled, downPayment, earlyPrepaymentPenalty, exchangeRate, exchangeRateSpread, floorLimit, gracePeriod, loanMortgageMandateAmount, loanType, minimumInflow, mobileApp, monthlyMinimumRepaymentAmount, numberOfPayments, overdraftLimit, paymentAmount, paymentFrequency, recourseLoan, renegotiable, repaymentForm, textChat
* Already existing but adapted for this proposal: amount, currency, email

This is quite a collection, I'd like our steering group to look these over before we move ahead. Pinging @scor @rvguha @mfhepp @nicolastorzec @vholland @chaals @shankarnat @tmarshbing ...

**Comment by RichardWallis** [comment]
That is not quite the state of this.  For some reason sdo-fibo.appspot.com was serving up an old version.  

The proposal for terms to be moved into pending is _**now**_ is visible as issue-1253 on [pending.sdo-fibo.appspot.com ](http://pending.sdo-fibo.appspot.com/)

It includes:

- issue-1253 Types (6):  [BrokerageAccount](http://pending.sdo-fibo.appspot.com/BrokerageAccount), [ExchangeRateSpecification](http://pending.sdo-fibo.appspot.com/ExchangeRateSpecification), [InvestmentFund](http://pending.sdo-fibo.appspot.com/InvestmentFund), [MoneyTransfer](http://pending.sdo-fibo.appspot.com/MoneyTransfer), [MortgageLoan](http://pending.sdo-fibo.appspot.com/MortgageLoan), [RepaymentSpecification](http://pending.sdo-fibo.appspot.com/RepaymentSpecification)

- issue-1253 Properties (25): [accountMinimumInflow](http://pending.sdo-fibo.appspot.com/accountMinimumInflow), [accountOverdraftLimit](http://pending.sdo-fibo.appspot.com/accountOverdraftLimit), [amount](http://pending.sdo-fibo.appspot.com/amount), [bankAccountType](http://pending.sdo-fibo.appspot.com/bankAccountType), [beneficiaryBank](http://pending.sdo-fibo.appspot.com/beneficiaryBank), [cashBack](http://pending.sdo-fibo.appspot.com/cashBack), [contactlessPayment](http://pending.sdo-fibo.appspot.com/contactlessPayment), [currency](http://pending.sdo-fibo.appspot.com/currency), [currentExchangeRate](http://pending.sdo-fibo.appspot.com/currentExchangeRate), [domiciledMortgage](http://pending.sdo-fibo.appspot.com/domiciledMortgage), [downPayment](http://pending.sdo-fibo.appspot.com/downPayment), [earlyPrepaymentPenalty](http://pending.sdo-fibo.appspot.com/earlyPrepaymentPenalty), [exchangeRate](http://pending.sdo-fibo.appspot.com/exchangeRate), [exchangeRateSpread](http://pending.sdo-fibo.appspot.com/exchangeRateSpread), [floorLimit](http://pending.sdo-fibo.appspot.com/floorLimit), [gracePeriod](http://pending.sdo-fibo.appspot.com/gracePeriod), [loanMortgageMandateAmount](http://pending.sdo-fibo.appspot.com/loanMortgageMandateAmount), [loanPaymentAmount](http://pending.sdo-fibo.appspot.com/loanPaymentAmount), [loanPaymentFrequency](http://pending.sdo-fibo.appspot.com/loanPaymentFrequency), [loanRepaymentForm](http://pending.sdo-fibo.appspot.com/loanRepaymentForm), [loanType](http://pending.sdo-fibo.appspot.com/loanType), [monthlyMinimumRepaymentAmount](http://pending.sdo-fibo.appspot.com/monthlyMinimumRepaymentAmount), [numberOfLoanPayments](http://pending.sdo-fibo.appspot.com/numberOfLoanPayments), [recourseLoan](recourseLoan), [renegotiableLoan](http://pending.sdo-fibo.appspot.com/renegotiableLoan)

- [amount](http://pending.sdo-fibo.appspot.com/amount) & [currency](http://pending.sdo-fibo.appspot.com/currency) are referenced as they have some proposed types added to their rangeIncludes.

**Comment by danbri** [comment]
@rvguha will take a look at this.

**Comment by sopekmir** [comment]
Dan, All, 
what is the chance for letting this extension to go to pending, or into its own extension, soon?
I have queries from people from banks when we could go ahead with this important extension.

Of course if there is still something to modify/improve - please let me/us know. We may engage more "brains" from our team working on the proposal, and make progress pretty fast.

**Comment by RichardWallis** [comment]
@rvguha any thoughts on this?

**Comment by richardhundt** [comment]
Hi all,

I can't figure out how `MoneyTransfer` can usefully express a transfer of money in that there's no way to specify the source and destination bank accounts. Since `BankAccount` is a `FinancialProduct` and not a `Place`, you can't put those into `fromLocation` and `toLocation` (inherited from `TransferAction`).

It seems like such an obvious thing to want to model, I'm sure I'm missing something, but I can't figure out what it is. Any tips?

Thanks!

**Comment by danbri** [comment]
Yes, the supertype seems to be physical/literal, whereas the financially-oriented subtype is more symbolic/abstract/virtual in its notion of movement.

I have not yet seen a compelling usecase for this particular piece of vocabulary, @sopekmir @mfhepp @RichardWallis may be able to shed more light on what the FIBO community have in mind.

**Comment by mfhepp** [comment]
My memory of the design decisions is not fresh anymore, but I guess the whole point was being able to model financial service types and their terms and conditions - e.g. "one money transfer by wire costs 1 USD", not so much individual money transactions.

**Comment by RichardWallis** [comment]
Yes my memory of it was similar - model the service (potential action), which you would want to share on the web, not individual transactions which you wouldn't want to share with the world.

**Comment by richardhundt** [comment]
The thing is, there's this whole PSD2 directive hitting the EU early next year which is forcing banks to open up their APIs to third party providers. This seems to be a global "open banking revolution", mainly due to regulatory vacuum wrt. FinTechs who've been screen scraping until now. The alternative is ISO20022 messaging which really isn't very pretty, so I can see a real use case for more verbs in the schema describing actual transactions and payments.

Anyway, thanks for your consideration, and I can understand if this isn't in scope for your efforts.

**Comment by thadguidry** [comment]
Hmm, this is a bit too flat still and only covers core Banking and Mortgage with a sprinkle of an Investment Account.
The general organization of this FIBO proposal seems primarily from a Product perspective and causes issues when you get into an Asset Management perspective (I.E. the **FinancialProduct Providers...who have a need to say a lot of things about themselves, some legally required to say and report about, and not just their FinancialProducts alone.**

For instance, if you wanted to say that your $1000 deposit into your [BrokerageAccount](http://pending.fibo.sdo-fibo.appspot.com/BrokerageAccount) that is provided by a BrokerageFirm which has [assets under management](https://www.wikidata.org/wiki/Property_talk:P4103) = $25 Billion , we have no easy way to say that.  We have to make long leaps to Service:provider.

1. Suggest that we add missing "provider" to [BrokerageAccount](http://pending.fibo.sdo-fibo.appspot.com/BrokerageAccount) and others.

2. We are lacking ways to easily say Financial Health and Asset Management things about any FinancialProduct Providers themselves.  (probably need a few more Types and Properties)

Good first pass team !

**Comment by thadguidry** [comment]
QUESTION: Does loanPaymentFrequency need to also expect a type of Duration and Text ?  Like we did for http://schema.org/repeatFrequency ?

**Comment by sdml** [comment]
I agree,
loanPaymentFrequency should have Duration and Text in Range. In [RepaymentSpecification](http://pending.schema.org/RepaymentSpecification) example it is used as a text property.

Sorry for (a very) late reaction to the posts here.

**Comment by magico** [comment]
Agreed.

**Comment by Rajskc** [comment]
Hi all, I want to get URI link to use the financial ontology in protege, but I am not able to find it. Where can I find the same? Thanks.

**Comment by rivettp** [comment]
floorLimit is surely a property of the Merchant receiving payment via cards, and not a property of a specific PaymentCard as proposed.

**Comment by nohu98** [comment]
> **Di chuyển đề xuất từ ​​Yêu cầu kéo ( [#1163](https://github.com/schemaorg/schemaorg/pull/1163) ) về việc gia hạn tài chính FIBO sang việc gia hạn _đang chờ xử_ lý có tham chiếu đến vấn đề này.**
> 
> _Văn bản từ PR:_ Yêu cầu kéo này cấu thành đề xuất mở rộng FIBO cho Schema.org từ [Nhóm cộng đồng Financial Industry Business Ontology](https://www.w3.org/community/fibo/) .
> 
> Đề xuất này dựa trên các loại và thuộc tính mới để hỗ trợ các sản phẩm và dịch vụ tài chính được giới thiệu trong Schema.org V3.0.
> 
> Nó giới thiệu một loạt các Loại và Thuộc tính mới và đã sửa đổi đầu tiên để hỗ trợ chi tiết hơn các yêu cầu chia sẻ sản phẩm, dịch vụ và tổ chức tài chính bằng Schema.org trên Web. Đề xuất ban đầu này (v1.0) tập trung vào lĩnh vực cho vay, cùng với việc bổ sung một số thuật ngữ hữu ích hơn nói chung.
> 
> Đề xuất do Nhóm đưa ra dựa trên công trình của [dự án Financial Industry Business Ontology](http://www.fibo.org/schema) nhằm mở rộng khả năng của Schema.org phù hợp với Financial Industry Business Ontology (FIBO). Đây là nỗ lực của nhóm sử dụng kiến ​​thức chuyên môn và bí quyết của các thành viên trong Nhóm nội dung FIBO tham gia vào việc tạo ra Financial Industry Business Ontology, làm việc với những người khác quen thuộc với Schema.org bao gồm Mirek Sopek và Richard Wallis.
> 
> Để biết thêm thông tin chi tiết và liên kết đến các định nghĩa trong phiên bản thử nghiệm của schema.org ( http://fibo.sdo-fibo.appspot.com/ ), hãy truy cập [Group Wiki](https://www.w3.org/community/fibo/wiki/Fibo.schema.org_v1.0_Proposal) .

https://github.com/schemaorg/schemaorg/issues/1253#issue-166802582
https://github.com/schemaorg/schemaorg/issues/1253
