### ISSUE TITLE
Invalid entry in schema.org JSON-LD context file

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1256]
Following invalid entry contained in [context file being served from webschemas.org ](http://webschemas.org/docs/jsonldcontext.json.txt).
 ```"": { "@id": "schema:"},```
Need to identify term causing it.

Also consider introducing a test to identify future similar issues.

**Comment by RichardWallis** [comment]
Tracked down to an error in the definition of ```openingHours``` where the resource was only set to "http://schema.org/" instead of "http://schema.org/openingHours".

Created a test to identify terms that do not have a rdfs:label that matches the term id.  Added in commit [ae74693](https://github.com/schemaorg/schemaorg/commit/ae74693418b7de2c5414b108aaa35f38f5fa5ab6).

Opening a new issue to fix the identified terms.

**Comment by danbri** [comment]
A new test :) I love tests. Someday I'll wire up Github to run them in the cloud...

**Comment by danbri** [comment]
Fixed these.
