### ISSUE TITLE
usedBy and uses have landed into Wikidata and we should have them also

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1258]
**Uses**  https://www.wikidata.org/wiki/Property:P2283
item used by the subject

**Used by** (inverse of Uses) https://www.wikidata.org/wiki/Property:P1535
item that makes use of the subject

These Using or Usage properties also help make distinct relationships and avoid confusion with current limits for developers around:

isBasedOn
relatedTo
seeAlso  (not implemented currently)
about

**Comment by danbri** [comment]
Can you give a few examples of situations where we'd (a) want to assert this in schema.org, (b) not use 'uses'? 

Does a WebPage use an image that it includes? Does an employer use an employee? does an event use its venue? Does http://schema.org/instrument relate any pair of items where one uses the other? etc.

**Comment by thadguidry** [comment]
@danbri Your thinking of placing limits on this ?  Wikidata lets it slide, and only goes by the definition.  A Pencil is used by ? ... could be Human, or Artist, but not a Dolphin or Giraffe or Spider.  A Paintbrush ?  well, currently that's Human and Elephant :)

I'd rather not go down limiting rabbit holes, for these "expansion" properties to help model the Long tail domains, that would make use of them perhaps more than our everyday domains.  What do you think ?

**Comment by danbri** [comment]
@thadguidry the less constrained it is, the more likely you'll find a situation where two diverse interpretations of the same property apply. For example if we said "isPartOf" relates a page to a book, and a book to a multi-volume work, as well as a book to a library, and a library to the city it's in, ... then you end up wondering whether a page of a book is a part of a city. The notion of "uses" is similarly vague. In particular whether we're capturing generalizations (artists use pencils) or specific situations (pencil_no_621351251_6b usedBy artist_no_2213515_thadguidry) or both.

**Comment by thadguidry** [comment]
@danbri 
book IS A type of physical item used by humans.
city IS A type of location with boundaries inhabited by humans.
They are 2 different types in my world, and isPartOf doesn't make the leap when it crosses a type in my applications.  Dunno what Google or Yandex does here, but mine doesn't.

This would be used for specific situations.  We can certainly put that in the description of the proposed if you want.  I'm ok with that.  I don't think this will be abused if we make the description clear.  

For example, "A specific item that is used by a subject(s).  This is not intended for deep object to subject linking, such as a house is used by rodents or mortgage companies, but instead simpler cases like a house is used by a family, or a hammer is used by a carpenter, or a contract is used by both a seller and a buyer."
