### ISSUE TITLE
Product example 1 is missing itemprop="image"

### ISSUE THREAD

**Issue by Scopestyle** [schemaorg/schemaorg#1260]
Hi!

Not sure if this is the right place to post but I would like to notify that the [schema.org product page](https://schema.org/Product) shows example 1 without the microdata itemprop="image", whereas example 2 shows the image correctly. 

Kind regards,

Erik

**Comment by RichardWallis** [comment]
Yes @Scopestyle you can 'notify' things like that here.

Strictly, as no properties are mandatory, the example you reference is OK markup.  However as the example html does contain reference to an image, it does seem at least odd that it is not referenced with schema:image.

Will fix.

**Comment by Scopestyle** [comment]
Cheers @RichardWallis, another thing I noticed that the introduction text on the [Article](https://schema.org/Article) page the link to the blog gets shown in an html block. I don't believe that this was meant to look this way. :wink:

**Comment by Dataliberate** [comment]
Fix now in Pull request #1261
<https://github.com/schemaorg/schemaorg/pull/1261>.

Problem with Article is fixed as part of PR #1222
<https://github.com/schemaorg/schemaorg/pull/1222> and visible in
pre-release: http://webschemas.org/Article

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by danbri** [comment]
Merged, thanks
