### ISSUE TITLE
Remove BedType until we have clearer use cases

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1263]
http://webschemas.org/BedType was introduced as part of the hotels proposal in pull request #1224. It is difficult to create an international list of the types of beds offered in an accommodation.

http://webschemas.org/bed and http://webschemas.org/BedDetails already allows a user to describe the type of bed using text. It is unclear how to use BedType and right now it offers no more standardization than text.

I propose we remove BedType until we have a clearer use case and values for authors to use.

**Comment by HughP** [comment]
There is actually a pretty good list of bed sizes  on this linked wikipedia article. I imagine that we could use it as a list of bed types. https://en.wikipedia.org/wiki/Bed_size

**Comment by mfhepp** [comment]
@HughP @vholland @danbri 
1. In the initial proposal, we had all bed types from Wikipedia as predefined enumerations. We removed the instances in favor of values defined on a per-site basis.

2. BedType allows a hotel or hotel chain to define the bed categories and attach text and images to it, which is frequently found information on hotel sites.

So I suggest to keep the current design.

Without the BedType type, a site cannot define meta-data for a bed type nor establish a reliable reference for it.

**Comment by vholland** [comment]
Do we have examples of sites who will provide metadata for the bed type beyond the name? If they only provide the name, they are going to simply revert to text.

**Comment by mfhepp** [comment]
See e.g.
https://www.travelchinaguide.com/essential/terms-hotel.htm
http://www.ottawakiosk.com/hotelarticle_roomtypes.html
https://www.hotelpenn.com/accommodations/classic-rooms-suites/
http://blog.homearena.co.uk/list-of-20-different-types-of-beds/

BTW, I think the need for defining bed types will be even greater in AirBnB-style offers with a greater variety of choices.


-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by vholland** [comment]
@mfhepp, yes there are sites like www.travelchinaguide.com and www.ottawakiosk.com which explain the local terms for beds, but they aren't linked to accommodations in any useful way and aren't canonical sources. The example of hotel only gives the names of the bed types.

I looked at AirBnB and they are even less structured with examples like https://www.airbnb.com/rooms/13886865?s=-dMX22Ku which use "real bed".

Are there examples of accommodation sites which give more than a name for the bed type? Those are the only authors who will need the BedType type to give dimensions, etc.

**Comment by mfhepp** [comment]
I have no clue and at this level this is all speculation about how hotels will use the advanced markup. Please decide, I am fine with whatever decision you take. To be frank, I would have hoped to have received these requests in the "final" conference call a couple of months ago.

**Comment by vholland** [comment]
I'm sorry you view it that way. Nothing precludes us from adding BedType again when we have a better sense of its usage.

**Comment by mfhepp** [comment]
As seed, please decide (and align these changes with all documentation and examples), but please, please, please let's get going. Schema.org was released in 2011 it took us five years to add support for something as simple as hotel rooms.

**Comment by thadguidry** [comment]
The BedType I suppose usage would be like what I have seen in Unusual Luxury Resort listings having Stone beds, Water beds, Fur beds, and yes...Coffin beds (Yikes!)  http://www.propeller-island.de/rooms_neu/room_detail/31/index.php 

bedSize is not a BedType.

**Comment by mfhepp** [comment]
Thanks. I am sure there are also much more traditional bed types for which images and other meta-data are defined on a single hotel site.

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
I had a quick look (ok, I googled [opentravel bed types]) to see what opentravel do. I didn't dig deep into specs but the thread at http://www.opentravelcommunityforum.com/forum/viewtopic.php?f=8&t=237 suggests that, at least in 2012, they had left this relatively unconstrained.

How about we stick all of hotels except BedType into 3.1, and BedType goes into pending.schema.org while we figure this out? It would allow it to be used and refined and for us to move along...

**Comment by mfhepp** [comment]
I can live with that ;-)
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
ok this is now in pending. @RichardWallis is investigating a software issue https://github.com/schemaorg/schemaorg/issues/1268 around domain/range mixup in pages like /bed but that's a separate matter.

**Comment by RichardWallis** [comment]
Fix to issue (#1268) removed the software issue.  Bed pages now displaying correctly.
