### ISSUE TITLE
Add serviceMobileApp serviceEmail & serviceTextChat to ServiceChannel

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1265]
Extracted from the FIBO extension proposal (#1253 & #1163) and updated a little as they are not totally finance focused.

Two new properties with range of [ServiceChannel](http://schema.org/ServiceChannel):

`serviceMobileApp` range `URL` & `MobileApplication` "Mobile application used to access the service."
`serviceTextChat` range `URL` "TextChat access to the Service"
`serviceEmail` range `Text` "email to access to the Service" - sub-property of `email`

Property names prefixed with 'service' to distinguish them from broader usage (as with other ServiceChannel properties that could be different to those associated with the Organization offering the service).

**Optional:**
`textChat` could be potentially added to  `ContactPoint` and possibly be made a super-property to `serviceTextChat`

**Comment by danbri** [comment]
Looking into this, can you articulate the (current) relationship between 'ServiceChannel', 'ContactPoint' and 'department'?

**Comment by RichardWallis** [comment]
`ServiceChannel` is directly related to `Service` via `availableChannel` supplying "_A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)._".

Organisations can offer services through channels that do not have a direct relationship with the contact points or departments of the organisation.

For example an online, or phone, banking service will have phone numbers and/or web addresses that are specific to the service which differ from the contactpoint details of the bank or its branches.

This proposal is to add 3 new properties to ServiceChannel to reflect an omission (`serviceEmail` probably should have been there originally) and new ways to access such services that are now commonly appearing: `TextChat` the URL to the service specific chat-bot/live chat, and  `serviceMobileApp` a `MobileApplication` to access the service such as a banking-app now made available by most banks.

Although the examples given here are from the banking domain, these services and service access methods are becoming common in many other areas - chat-help for online retail sites, mobile apps for online auction services, media-streaming services, etc.

**Comment by vholland** [comment]
Adding textChat to ContactPoint seems generally useful.

Should we add something for SMS as well? It is not altogether clear how to specify that a phone number is for texting an organization rather than speaking with a person.

**Comment by Dataliberate** [comment]
Sounds like a logical move to do at the same time.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by RichardWallis** [comment]
More thoughts on this?

**Comment by thadguidry** [comment]
@vholland In the ICT world (Information and communications technology, also known as Telecom), we treat SMS as a feature (or you could say a service) on a phone line/ phone #.  Other features are Voicemail, Call Forwarding, etc, etc.  3GPP is the standard that sorta wraps all this up.

**Comment by vholland** [comment]
@thadguidry Right. I am coming from the service organization perspective. I doubt they know anything about 3GPP. All they know is 1-617-555-5555 is an SMS number.

**Comment by thadguidry** [comment]
@vholland Maybe we can just do like ICT does ?

Phone Number
  Feature: SMS
  Feature: Voicemail
  Feature: Enhanced Voicemail

Or with my and @rvguha proposal...for the simple new List type...

Phone Number
  Feature: 'SMS, Voicemail, Enhanced Voicemail'

**Comment by vholland** [comment]
@thadguidry I'm not sure I understand the use case for Voicemail in ServiceChannel. Are you proposing creating a new PhoneNumber type?

**Comment by RichardWallis** [comment]
I think we are going off at a bit of a tangent here into defining the capabilities associated with a phone number - you can call it/send it a SMS/ it has voicemail etc.

An area for discussion, but not the proposal here.

We have [ServiceChannel](http://schema.org/ServiceChannel)  (eg. The Gold Membership section of a well known frequent flier program, or the Spanish speaking customer service department for a bank)  and currently we can describe things such as the service specific phone number, web page (serviceUrl), contact sms etc.  

Currently however you cannot describe other ways of contacting the service such as email, a mobileApp, or textChat (or chat bot).  

This proposal is to add those properties.

**Comment by thadguidry** [comment]
@vholland  no, no... wasn't about the ServiceChannel... its about the Service itself.

Opened new issue #1359 for this idea, since its not directly about ServiceChannel in this discussion, but Service instead.
