### ISSUE TITLE
byArtist and performer cover similar situations

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1271]
- http://schema.org/performer
  - definition: "A performer at the event—for example, a presenter, musician, musical group or actor."
  - rangeIncludes (i.e. values are): Organization Person
  - domainIncludes (i.e. used on): Event
- http://schema.org/byArtist
  - definition: "The artist that performed this album or recording."
  - rangeIncludes (i.e. values are): MusicGroup
  - domainIncludes (i.e. used on): MusicAlbum MusicRecording

Thanks @thadguidry for pointing this out. /cc @vholland 

The performer property has been around since the beginning (indicated the awkward 'performers' property which preceded it), and describes only events. The byArtist property was added a while back when we added substantial vocab around music heavily inspired by MusicBrainz's schemas.

Differences: 

A "performer" at an Event could easily be a non-musical artist (e.g. dancer, poet, live action painter...), whereas "byArtist" currently only applies to music-oriented types and takes music-oriented values.

Note that http://schema.org/PerformingGroup exists, with group subtypes for DanceGroup, MusicGroup, TheatreGroup.

Suggestions:

Perhaps extend "performer" to allow MusicGroup (or PerformingGroup) as another expected type of value.  Extend domain of "performer" (cautiously by including MusicAlbum MusicRecording or liberally by allowing it on any CreativeWork?). Declare byArtist as a subproperty of performer. Consider extending range of byArtist to Person too; how _do_ we handle solo artists?

This wouldn't force a convergence or a replacement of one by the other, but would at least give the impression the terms are part of a unified vocabulary.

**Comment by danbri** [comment]
Alternatively, we could decide the usecases are different enough that all we need is a cross-reference in the human-facing definitions. However only today did I notice that we have PerformingGroup and performer but no integration between the two terms, it feels to me like something more is needed.

**Comment by thadguidry** [comment]
@danbri Your welcome.  Thanks to Wikidata schema alignment work actually :)

**Comment by thadguidry** [comment]
@danbri 
+1 Perhaps extend "performer" to allow MusicGroup (or PerformingGroup) as another expected type of value.
+1 Extend domain of "performer" (cautiously by including MusicAlbum MusicRecording or liberally by allowing it on any CreativeWork?).
+1 Declare byArtist as a subproperty of performer.
+1 Consider extending range of byArtist to Person too; how do we handle solo artists?

We handle solo artist by saying that they are just "performer".  What more do you need...or is it that you want some way to know if a "performer" is a group or a solo artist ? I don't worry about that, I and my apps just look at the extra data around to determine that...which is, does the performer / MusicGroup have more than 1 member or not.  This one btw, is now superseded with http://schema.org/musicGroupMember

**Comment by pasqLisena** [comment]
> Perhaps extend "performer" to allow MusicGroup (or PerformingGroup) as another expected type of value.

PerformingGroup/MusicGroup are yet allowed in facts, because they are subclasses of Organization.

+1 for the rest.

**Comment by danbri** [comment]
@pasqLisena - you are correct, thanks I had missed that.

**Comment by vholland** [comment]
Back when the music schema was overhauled, we decided that if someone wanted to discuss a solo artist as a Person, both types should be provided. In other words:

```
{
    "@context": "http://schema.org/",
    "@type": ["MusicGroup", "Person"],
    "name": "Beyoncé",
    "album": {
        "@type": "MusicAlbum",
        "name": "Lemonade"
    },
    "birthDate": "1981-09-04"
}

```

byArtist was intended for the primary artist(s). So, "All You Need is Love" would be "byArtist" the Beatles. You could also note that Mick Jagger contributed to the vocals using "performer".

This suggests we should tighten up the definitions of each property.

**Comment by danbri** [comment]
@vholland that's the kind of pragmatic multiple typing that I hope we'll be seeing more of...

**Comment by thadguidry** [comment]
@danbri @vholland Nice!  We eating our dogfood already. Barf!

Agreed, we need to fix the definitions.
