### ISSUE TITLE
Organization/LocalBusiness/xxxxService/Occupation

### ISSUE THREAD

**Issue by WeaverStever** [schemaorg/schemaorg#1276]
New follower of the group, forgive me if this has been discussed.

I've noticed that some service providing entities have Schema definitions, others don't, and still others are deprecated.  For instance, Attorney is deprecated, Notary is not.  Instead of creating every industry-classification and occupation....

The NAICS property is included in Organization, Person and LocalBusiness (but LocalBusiness is not reflected on the NAICS definitions page at https://schema.org/naics).  

The NAICS defines two standards, the Standard **Industry** Classifications (formerly SIC) and Standard **Occupational** Classifications (SOC), where the SOC is more verbose than the SIC, in which, occupations are grouped by industry. 

In mixing persons with organizations and localbusinesses, the guidance is unclear as to whether the (NAICS) SIC or SOC is expected.  A Person would likely choose to use the SOC, an Organization would likely choose SIC derived number, but from which year?  And from which source?  (There are conflicting /aging Internet sources that present varying information.)

Additionally, the NAICS codes change over time, so I'm wondering if Schema.org should clarify and provide a link to (or publish a static version of)  the type of code(s) expected.
1.  Should Organizations and LocalBusinesses be classified by the NAICS-SIC?
2. Should Persons be classified by the NAICS-SOC? 
3. Should the guidance reflect a preferred (year) version(s), or provide authoritative source(s) for the expected codes? (The SOC codes can change several times per decade and the 2010 specification was pretty drastic/disruptive.)

http://www.nsca.org/naicssoc-codes/

**Comment by RichardWallis** [comment]
Welcome aboard @WeaverStever!
A few points on your questions:

> For instance, Attorney is deprecated, Notary is not. Instead of creating every industry-classification and occupation...

Attorney was deprecated in favour of LegalService after a long conversation on issue #784.  The arguments that let to that decision are probably equally valid for Notary.  A matching issue could raised.

> The NAICS property is included in Organization, Person and LocalBusiness (but LocalBusiness is not reflected on the NAICS definitions page at https://schema.org/naics).

As [naics](http://schema.org/naics) has [Organization](http://schema.org/Organization) in its range it is available to all the subtypes of Organization, as can be seen on the term page for [LocalBusiness](http://schema.org/LocalBusiness), [LegalService]( http://schema.org/LegalService), etc.

As to values to be used for a [naics](http://schema.org/naics), it is not really the role of of Schema.org to define, and keep up with changes to, external authoritative codes and values.  However for such a specific property, it would be appropriate in the term description to provide a link to relevant external guidance documentation. Where would you suggest for such a link?  

The creation of a couple of examples, with appropriate codes, for inclusion on that page would also help.

Additionally are there authoritative URIs for the NAICS codes?  They could also be used in examples

**Comment by WeaverStever** [comment]
Yes, I noticed a while back that the Schema was starting to include narrower industry/occupations, which could/should be handled externally with the NAICS codes. However, a person with one occupation can be employed in numerous industries.  As a systems administrator, I was employed in five different industries over time.  Ultimately, persons are going to affiliate themselves with their occupation and organizations will generally identify with their industry.  

Since the NAICS field is just text, I'd suppose that even a mixture of SOC and SIC codes would be valid.  I am aware that other nations (GB, Australia, Canada) have their own systems, so I guess the categorization of entities would only be limited by the sources that query them.  For this reason, the guidance should indicate to the search engine programmers where to look for indexes to associate with titles (industry/occupation).     

United States resources:
Ultimately, the NAICS is a Census program.
**Industries:** http://www.census.gov/eos/www/naics/

The Bureau of Labor Statistics (OES) has occupations 
**Occupations** http://www.bls.gov/oes/current/oes_stru.htm

Tables can be found here:
http://www.census.gov/people/io/methodology/indexes.html

I think I have a working NAICS microdata profile, I'll see what I can do about providing an example.

**Comment by WeaverStever** [comment]
Taken from Example 3 on the LocalBusiness schema.org site. Passes Google SDTT.
(Code window seems to uglify the code -- see what happens when I save.)

`<div itemscope itemtype="http://schema.org/LocalBusiness">
  <h1><span itemprop="name">Beachwalk Beachwear & Giftware</span></h1>
  <span itemprop="description"> A superb collection of fine gifts and clothing
  to accent your stay in Mexico Beach.</span>
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span itemprop="streetAddress">3102 Highway 98</span>
    <span itemprop="addressLocality">Mexico Beach</span>,
    <span itemprop="addressRegion">FL</span>
  </div>
  Phone: <span itemprop="telephone">850-648-4200</span>
  <meta itemprop="naics" content="448190"/> 
  <meta itemprop="naics" content="453220"/> 
</div>`

**Comment by RichardWallis** [comment]
@WeaverStever I've tweaked the display of your code snippet to improve display.

That would make a good example, if accompanied by a Person based one, and also shown in RDFa & json-ld we would have the basis for an addition to the term page.

If we also updated the description to something like:
_The North American Industry Classification System (NAICS) code for a particular organization or business person.  Indexes of available codes are available from the [United States Census Bureau](http://www.census.gov/people/io/methodology/indexes.html)._

It would round things off nicely.

Yes you are right about international differences - as a Brit, NAICS means very little to me ;-)

**Comment by WeaverStever** [comment]
@RichardWallis, 
Thanks for fixing that! I'll add the RDFa and JSON-LD examples with the LocalBusiness sample I provided earlier

For description clarity I'd suggest...   _The North American Industry Classification System (NAICS) code**(s)** for a particular organization or business person. Indexes **of industry and occupational codes** are available from the [United States Census Bureau](http://www.census.gov/people/io/methodology/indexes.html)._

Google's SDTT recognizes multiple industries/occupations. Organizations and persons are generally a member of one or more occupations and industries. For instance, a service company may be more descriptive by using an occupational code, rather than, or in addition to the industry code. 

In emphasizing multiples, I think we paint a more complete data-view of the entity and reduce the temptation to try to define every occupation.

schema.org/person Example 8

**microdata**
~~~~
<div itemscope itemtype="http://schema.org/Person">
  <span itemprop="name">Jane Doe</span>
  <img src="janedoe.jpg" itemprop="image" alt="Photo of Jane Joe"/>
  <span itemprop="jobTitle">Professor</span>
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span itemprop="streetAddress">
      20341 Whitworth Institute
      405 N. Whitworth
    </span>
    <span itemprop="addressLocality">Seattle</span>,
    <span itemprop="addressRegion">WA</span>
    <span itemprop="postalCode">98052</span>
  </div>
  <span itemprop="telephone">(425) 123-4567</span>
  <a href="mailto:jane-doe@xyz.edu" itemprop="email">
    jane-doe@xyz.edu</a>    
  <meta itemprop="naics" content="25-1067"/> <!--25-1067 Sociology Teachers... (occupation)-->
  <meta itemprop="naics" content="611300"/> <!--611300 Colleges, Universities... (industry)-->
  Jane's home page:
  <a href="http://www.janedoe.com" itemprop="url">janedoe.com</a>
  Graduate students:
  <a href="http://www.xyz.edu/students/alicejones.html" itemprop="colleague">
    Alice Jones</a>
  <a href="http://www.xyz.edu/students/bobsmith.html" itemprop="colleague">
    Bob Smith</a>
</div>
~~~~

**RDFa** 
~~~~
<div vocab="http://schema.org/" typeof="Person">
  <span property="name">Jane Doe</span>
  <img src="janedoe.jpg" property="image" alt="Photo of Jane Joe"/>
  <span property="jobTitle">Professor</span>
  <div property="address" typeof="PostalAddress">
    <span property="streetAddress">
      20341 Whitworth Institute
      405 N. Whitworth
    </span>
    <span property="addressLocality">Seattle</span>,
    <span property="addressRegion">WA</span>
    <span property="postalCode">98052</span>
  </div>
  <span property="telephone">(425) 123-4567</span>
  <a href="mailto:jane-doe@xyz.edu" property="email">
    jane-doe@xyz.edu</a>
  <meta property="naics" content="25-1067"/> <!--25-1067 Sociology Teachers... (occupation)-->
  <meta property="naics" content="611300"/> <!--611300 Colleges, Universities... (industry)-->
  Jane's home page:
  <a href="http://www.janedoe.com" property="url">janedoe.com</a>
  Graduate students:
  <a href="http://www.xyz.edu/students/alicejones.html" property="colleague">
    Alice Jones</a>
  <a href="http://www.xyz.edu/students/bobsmith.html" property="colleague">
    Bob Smith</a>
</div
~~~~

**JSON-LD**
~~~~
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Person",
  "address": {
    "@type": "PostalAddress",
    "addressLocality": "Seattle",
    "addressRegion": "WA",
    "postalCode": "98052",
    "streetAddress": "20341 Whitworth Institute 405 N. Whitworth"
  },
  "naics":[
  "25-1067",
  "611300"
  ],
  "colleague": [
    "http://www.xyz.edu/students/alicejones.html",
    "http://www.xyz.edu/students/bobsmith.html"
  ],
  "email": "mailto:jane-doe@xyz.edu",
  "image": "janedoe.jpg",
  "jobTitle": "Professor",
  "name": "Jane Doe",
  "telephone": "(425) 123-4567",
  "url": "http://www.janedoe.com"
}
</script>
~~~~

**Comment by WeaverStever** [comment]
Follow up:

The isicV4 field is similar to the naics industry codes, with the exception that isicV4 codes are international in scope (United Nations).

isicV4 codes can be found here:
http://unstats.un.org/unsd/cr/registry/isic-4.asp 
and here: 
http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=27

The schema guidance is unclear as to whether the alpha prefix is to be included.
