### ISSUE TITLE
Make the source RDFa file XHTML compliant

### ISSUE THREAD

**Issue by tfrancart** [schemaorg/schemaorg#1277]
This would help some XSLT-based RDFa parsers making sense of raw schema.org data.
And I found out that this is not too difficult to achieve :

```
replace <hr> with <hr />
replace <link property="(.*)" href="(.*)"> with <link property="$1" href="$2"/> (to close <link> elements)
manually close the 2 <meta> tags in the header
```

Further copy/paste modification of the file can then benefit from this enhanced structure.

**Comment by RichardWallis** [comment]
Thanks @tfrancart for looking at this.

We have also been looking at improving how developers can get hold of raw data for the Schema.org schemas.

Working with the schema.rdfa file is not an ideal route, even cleaning up the structure as you describe. It is a file that is contributed to by many, and hence difficult to police adherence to such patterns. Also it is now getting a bit on the large side so may at a later date benefit from splitting.  Most importantly it does not contain the data for extensions.

So, in the imminent 3.1 release, we have introduced the ability to download definition files of the total vocabulary including extensions, or only the core, or individual extensions.  These are available in triples, quads, json-ld, and  turtle formats.

You can see what is coming on the webschemas.org development version site: http://webschemas.org/docs/developers.html#defs

Let's see how useful these are before investing in other work in this area.  To that end I'm closing this issue.

~Richard.

**Comment by tfrancart** [comment]
Swell !
I see a download URL of the core schema is http://webschemas.org/releases/3.1/schema.ttl, but it would be nice to have a persistent URL to always get to the latest version of the schema (.../latest/schema.ttl).

**Comment by danbri** [comment]
In tests/test_basics.py we have

    class SchemaWellformedTestCase(unittest.TestCase):

      def test_wellformed(self):

        from xml.etree import ElementTree
        tree = ElementTree.parse(schema_path)
        rootElem = tree.getroot()
        log.debug("Root element of schema file: "+ rootElem.tag)
        self.assertEqual("html", rootElem.tag, "Expected root element of schema to be 'html'.")

... I believe the intent of this was to ensure wellformedness of the source RDFa.

I tried messing up data/schema.rdfa by adding &lt;br&gt; but it didn't even get to this test, instead Exception: RDFa parsing Error! mismatched tag: line 10961, column 2.

I don't see how our unit tests could run with non-wellformed XML at least in data/schema.rdfa (although it might not be good XHTML I guess...).

**Comment by tfrancart** [comment]
Apologies, I may have looked at a slightly older version of the file.
Thanks for looking into this

**Comment by danbri** [comment]
No worries, I'm very happy to have people engaging with this level of the project - it helps us a lot with QA to have multiple consumers of these files.

**Comment by unor** [comment]
(For getting related issues linked: #360)
