### ISSUE TITLE
Markdown bug injecting ‘klzzwxh’ into pages, need a fix and tests to ensure it stays fix

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1285]
@RichardWallis suggested making a "test to try all Term pages on http://schema.org looking for ‘klzzwxh’"

+1

Immediate fixes and more diagnosis also needed, we've repaired health-lifesci.schema.org but the markdown library seems prone to this so unit tests are essential to avoid future recurrence of the problem.

**Comment by AymenLoukil** [comment]
Search page http://schema.org/docs/search_results.html#q=klzzwxh is showing klzzwxh

**Comment by danbri** [comment]
See also: 
* https://sourceforge.net/p/python-markdown/mailman/message/24612191/
* https://github.com/waylan/Python-Markdown/issues/354
* https://github.com/waylan/Python-Markdown/issues/32

**Comment by danbri** [comment]
We decided to switch to a different markdown library, plus a custom function for parsing wikilink-style link syntax.

* https://github.com/schemaorg/schemaorg/pull/1287 merged.

**Comment by danbri** [comment]
Deployed! Cleanup tasks -

* expunge old library (and file a bug for them, although we can't reproduce it reliably)
* updated scripts/*py to use markdown2
* given the library switch do we still need to integrate tests for klzzwxh or is that string tied to the oddities of the first library? (if in doubt, test, I guess...)
* anything else @RichardWallis ?

**Comment by RichardWallis** [comment]
This problem was specific to the Markdown library being used.

This has been replaced by another ([Markdown2](https://github.com/trentm/python-markdown2)) library, implemented in an entirely different way so 'this' problem will not reappear in this form.

Hense closing.

**Comment by danbri** [comment]
@RichardWallis can you confirm everything in scripts/ uses the new lib?

**Comment by RichardWallis** [comment]
Yes - no code including scripts and tests make reference to the old Markdown library.

Commit 661088b removes references to it in SOFTWARE_README.md
