### ISSUE TITLE
New Fields and Subclasses for IndividualProduct

### ISSUE THREAD

**Issue by gdmichaels** [schemaorg/schemaorg#1289]
Hi folks, my first posting here, so please cut me a little slack if my question seems inane.

My database is for collectible items and many of these items seem to fit into schema.org as 'IndividualProduct' objects.

Several obvious (to me) attributes of this object seem to be missing and I am curious to see how I would go about requesting them to be added.

To start with:

MSRP
MSRP Currency

Also, I am interested in requesting (or adding myself) new sub products for various classes such as Toys and Game and Antiques.  Any advice would be welcome.

Thanks!

George

-- 
George Michaels
Founder, TroveStar LLC
gdm@trovestar.com
www.trovestar.com

**Comment by mfhepp** [comment]
simply use additionalProperty (see examples there) and additionalType with www.productontology.org class ids.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by danbri** [comment]
+1 to using additionalProperty

I've tagged this issue "closed and noted", noting the suggestion in our overview issue #2 to aid findability and for future review. In the interests of keeping a manageable number of open issues I'll go ahead and close it now, but discussions are still very much welcomed here. Thanks again!
