### ISSUE TITLE
False and True are subtypes of Boolean. They should be instances /  enumerated values.

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#129]
In the current version of schema.org, False and True are subtypes of Boolean. They should be instances /  enumerated values.

**Comment by danbri** [comment]
Several duplications, closing this one.

* https://github.com/schemaorg/schemaorg/issues/130
* https://github.com/schemaorg/schemaorg/issues?q=is%3Aissue+is%3Aopen+True+False+
