### ISSUE TITLE
Check/Fix status of True and False

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#130]
http://schema.org/True
http://schema.org/False

"One thing, though: In the current version of schema.org, False and True are subtypes of Boolean. They should be instances /  enumerated values."

Mostly recently pointed out by Martin Hepp, http://lists.w3.org/Archives/Public/public-vocabs/2014Sep/0191.html

(There's also the issue that such values very often show up as literals in data, even if they should be URIs. Could either try to fix documentation to encourage URI use, or document this as an 'expect the unexpected' pattern.)

**Comment by danbri** [comment]
Another duplicate! https://github.com/schemaorg/schemaorg/issues/130 

Let's fix this... I've asked for sanity check from @rvguha first in case the model was intended.

**Comment by danbri** [comment]
For reference,

        danbri-macbookpro:data danbri$ rdfa schema.rdfa | grep '/True'
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/Boolean> .
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#label> "True" .
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#comment> "The boolean value true" .
        <http://schema.org/True> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .
        danbri-macbookpro:data danbri$ rdfa schema.rdfa | grep '/False'
        <http://schema.org/False> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/Boolean> .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#label> "False" .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#comment> "The boolean value false" .

Closing nearby duplicate report https://github.com/schemaorg/schemaorg/issues/226 (thanks @sesuncedu)

**Comment by danbri** [comment]
Also noting from https://www.w3.org/2011/webschema/track/issues/14 there are reasonable questions about the actual property values. Whether 'true', 'false' literals should be documented as acceptable.

I won't open another issue as it is better to get a unified understanding here. Copying in Martin Hepp's original comments:

        From Martin Hepp in https://docs.google.com/document/pub?id=1Kx63gW9DBky1j97Jpwl3dU9k0pKPSgCT3EntTVvGjX4

        You have to clarify the usage of http://schema.org/Boolean. The schema.org sponsors should clarify whether to use the RDF-compatible text (true/false) or the
        URIs http://schema.org/True and http://schema.org/False.
        For now, one would assume that you use the two values as individuals, e.g.
        <link itemprop=â€propertynameâ€ href=â€http://schema.org/Trueâ€ />
        <link itemprop=â€propertynameâ€ href=â€http://schema.org/Falseâ€ />
        which is incompatible with the RDFa patterns and also less concise.
        I suggest
        <meta itemprop="propertyname" content="true" >
        <meta itemprop="propertyname" content="false" >


        Proposed change:

        A simple text amendment for http://schema.org/True, http://schema.org/False, and http://schema.org/Boolean would do the trick.:

        Note: The recommended use of this datatype is with a string â€œtrueâ€ or â€œfalseâ€ indicating the value of the respective property.
        Example:
        <div itemscope itemtype="http://schema.org/Book">
        <span itemprop="name">The Catcher in the Rye</span>
        Family-friendly: <meta itemprop="isFamilyFriendly" content="true"> yes
        </div>

**Comment by danbri** [comment]
Also Migrating notes from W3C:

        I talked to Ivan Herman, and we both thing simple text values 'true', 'false' ought to work ok in RDFa Lite as well as Microdata. It might not be formally datatyped but I think that's bearable.

        I took a look for properties that reference Boolean in the schema:


        TellyClub:alpha danbri$ grep -i Boolean _schema.nt 
        <http://schema.org/isFamilyFriendly> <http://schema.org/range> <http://schema.org/Boolean> .
        <http://schema.org/isDownloadable> <http://schema.org/range> <http://schema.org/Boolean> .
        <http://schema.org/representativeOfPage> <http://schema.org/range> <http://schema.org/Boolean> .
        <http://schema.org/Boolean> <http://www.w3.org/2000/01/rdf-schema#label> "Boolean" .
        <http://schema.org/Boolean> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .
        <http://schema.org/Boolean> <http://www.w3.org/2000/01/rdf-schema#comment> "Boolean: True or False." .
        <http://schema.org/Boolean> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
        <http://schema.org/requiresSubscription> <http://schema.org/range> <http://schema.org/Boolean> .

        ...for the record.

        Dan Brickley, 9 May 2012, 16:30:28

**Comment by rvguha** [comment]
Looks fine.

**Comment by danbri** [comment]
Status quo looks fine, or the suggestion to avoid having them as subtypes?

**Comment by sesuncedu** [comment]
The only possible member of the extension of class schema:True is the
individual, schema:True.
This must be intensional, but surely can't be intentional (unless one
thinks about it).

Does the sentence "The subclass assertions for True and False should be
removed" obtain?

**Comment by rvguha** [comment]
Sorry, what I meant was that we should have:

typeOf(True, Boolean) and
typeOf(False, Boolean) and
subClassOf(Boolean, Class)

**Comment by danbri** [comment]
I've fixed the raw modeling. There are some HTML navigation consequences to address but I'll file that separately. Closing this one - thanks!

**Comment by rvguha** [comment]
So, it might be time to bite the bullet and do this more correctly.

Boolean, Integer, etc. are classes, i.e., typeOf(Boolean, Class). They are
also instances of DataType, i.e., typeOf(Boolean, DataType).

What is DataType itself? Since instances of it are classes, it has to be a
subclass of Class.

guha

**Comment by danbri** [comment]
Re-opening w.r.t. "more correctly" (and related #218).

Here is what we have in the pending release:

    <http://schema.org/Boolean> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .
    <http://schema.org/False> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .
    <http://schema.org/Boolean> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
    <http://schema.org/True> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .

Proposal is:

* Boolean type DataType.
* Boolean type Class.
* False type Boolean.
* True type Boolean
* DataType subClassOf Class.
* (... and likewise for other datatypes)

**Comment by danbri** [comment]
Ping @rvguha  - can you clarify 'more correctly' vs what we have now, as summarised above?

**Comment by rvguha** [comment]
What I meant was that it is time for us to do it the way more expressive systems do it and have subclasses of Class. Exactly the way you list it above.

**Comment by danbri** [comment]
Thanks. In that case I believe we ought to be good to go. This is in the current repo:

    rdfa data/schema.rdfa | grep DataType
    <http://schema.org/DataType> <http://www.w3.org/2000/01/rdf-schema#comment> "The basic data types such as Integers, Strings, etc." .
    <http://schema.org/DataType> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
    <http://schema.org/DataType> <http://www.w3.org/2000/01/rdf-schema#label> "DataType" .
    <http://schema.org/Text> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .
    <http://schema.org/Date> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .
    <http://schema.org/Boolean> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .
    <http://schema.org/Number> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .
    <http://schema.org/Time> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .
    <http://schema.org/DateTime> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/DataType> .

... i.e. regular treatment of our 6 datatypes as subclasses of DataType. For completeness we could add the assertion that "DataType rdfs:subClassOf rdfs:Class", although that's implied by subtyping of it. Boolean was special in that its members are actually enumerated as schema.org terms; this is not the case for Text, Date, Number, Time or DateTime. I believe the only Boolean-specific issues left are regarding navigating between the Boolean type and its enumerated members, True and False. That is tracked as #433. It does leave one minor modeling-related issue:

Should we say that Boolean is also an Enumeration and try to re-use front-end display code, or adapt the site navigation specifically for this case? When I tested this the display was screwed up, but I've not investigated fully why yet. I'll track that at #433 and close this issue. Opinions (here or there) on whether we consider Boolean an Enumeration are welcomed. Default will be to do whatever is easiest.

**Comment by danbri** [comment]
I'm sorry - I misread this. Reviewing #218 I see now that we have Boolean/Time/etc subClassOf DataType instead of 'type DataType'. Will fix.

**Comment by danbri** [comment]
Ok, here is what we now have in the next pending release (sdo-gozer):

    rdfa data/schema.rdfa | grep DataType
    <http://schema.org/DataType> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
    <http://schema.org/DataType> <http://www.w3.org/2000/01/rdf-schema#comment> "The basic data types such as Integers, Strings, etc." .
    <http://schema.org/DataType> <http://www.w3.org/2000/01/rdf-schema#label> "DataType" .
    <http://schema.org/Date> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DataType> .
    <http://schema.org/DateTime> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DataType> .
    <http://schema.org/Time> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DataType> .
    <http://schema.org/Number> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DataType> .
    <http://schema.org/Boolean> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DataType> .
    <http://schema.org/Text> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DataType> .

This has now somewhat messed up the site navigation that we have in http://schema.org/DataType, since 'more specific types' (i.e. subtypes) list is empty.  I also had to make some changes to our RDFa (hack)parser to support whitespace-separated multiple types in @typeof, and/or use of @property with rdf:type.

**Comment by danbri** [comment]
I believe the raw schema/vocab aspect is settled (and documented briefly in docs/releases.html). See #463 for UI/python fixes required to make this navigable.
