### ISSUE TITLE
Sub Property and Super Property missing docs, data model, & getting started 

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1301]
I crawled through the site and did not find official info on the WHAT or USE of  Sub Property or Super Property.  Web developers typically will not understand this and we need to give clear examples and documentation in various areas of the site.

**Provide sections for explaining Sub Property and Super Property on:**
- Data Model http://webschemas.org/docs/datamodel.html
- Getting Started http://webschemas.org/docs/gs.html
- Meta https://meta.schema.org/  (this one hopefully addressed with #1267)

**Comment by danbri** [comment]
Good point.

@rvguha how about you take this one? At least an appendix to datamodel.html would be useful, more for would-be schema designers than for publishers/webmasters.

BTW, here's what we have (in nquads, i.e. triples plus a layer indicating core or extension):

14:06 $ grep subPropertyOf data/releases/3.1/all-layers.nq > ~/Desktop/subproperties.txt

https://gist.github.com/danbri/6bc3ee96ffb2a8b340dda2aacba2977a
