### ISSUE TITLE
'logo' for 'WebSite'

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1303]
The [`logo` property](http://schema.org/logo) can be used on `Brand`, `Organization`, `Place`, `Product`, and `Service`. 

Proposal: Add [`WebSite`](http://schema.org/WebSite) as domain.

While the logo could be applied to the `Organization` entity for company websites etc. (they typically have the same logo for the organization and the website), many websites are not published by an organization (e.g., personal sites), but still have a logo.

**Comment by jaygray0919** [comment]
Note: Goodle SDTT currently does not accept logo on `@Service`. A moderator on the Google WebMaster forum is looking into it.

**Comment by danbri** [comment]
@jaygray0919 do you have a link to the Webmaster forum thread?

**Comment by danbri** [comment]
Re Website, that seems reasonable to me, although it'll open us up to reasonable questions about favicon etc.

**Comment by jaygray0919** [comment]
@danbri 

Yes Sir

https://productforums.google.com/forum/#!topic/webmasters/NOr6L__fsm4;context-place=topicsearchin/webmasters/category$3Astructured-data%7Csort:relevance%7Cspell:false
