### ISSUE TITLE
Consider datacite wrt Dataset vocab

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1305]
https://schema.datacite.org/

**Comment by danbri** [comment]
Also http://www.nationalarchives.gov.uk/PRONOM/Default.aspx maybe oais too

**Comment by akuckartz** [comment]
Slightly on-topic, a W3C workshop:

> The need to describe data with metadata is well understood: the problem is how best to do it. There are many answers to that question which in itself creates a further problem: with so many standards to choose from, which one should I use to describe my data? With so many is use, which one(s) should I build my application to look for?

>Topics for the workshop include, but are not limited to:
    Approaches to dataset descriptions
    Experience of using DCAT and/or other dataset description vocabularies
    Defining and using metadata profiles
    Discovering metadata profiles
    Providing and using metadata in multiple profiles for multiple contexts
    Experiences of developing, managing and mapping vocabularies.

> Smart Descriptions & Smarter Vocabularies (SDSVoc)
30 November - 1 December, CWI, Amsterdam Science Park
https://www.w3.org/2016/11/sdsvoc/

I hope that the schema.org developers will be represented there !
