### ISSUE TITLE
Description and sub-properties of 'productID'

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1309]
[`productID`](http://schema.org/productID) (Domain: `Product`, Range: `Text`):

> The product identifier, such as ISBN. For example: `meta itemprop="productID" content="isbn:123-456-789"`.

---
### Description

I think it could use a more detailed description about the expected value. No expectation/recommendation, or does it have to use some format (like `prefix:value`)? 

And maybe it would be better to keep the description syntax-neutral (i.e., removing the Microdata example)?

See also @danbri’s [comment from 2014](https://github.com/schemaorg/schemaorg/issues/99#issuecomment-52653478):

> http://schema.org/productID is vague too; what should it contain?
> 
> "What are the allowed prefixes? isbn? gtin? ean? jan? upc? sku? mpn? is the colon mandatory? Is the prefix case sensitive?"
> (Matthias)

Some discussion (from 2015) about this starting at https://github.com/schemaorg/schemaorg/issues/428#issuecomment-93724706
### Sub-properties

Currently no property has `productID` as super-property. Would it work to add the "gtin" properties as sub-properties? They are also defined for `Offer`/`Demand`, but `productID` isn’t.

See also @mfhepp’s [comment from 2015](https://github.com/schemaorg/schemaorg/issues/428#issuecomment-93709711):

> […] (same as productID is a superproperty to gtin13 etc.)
> 
> Note that the superproperty relations for productID are still missing in schema.org (but will follow)

**Comment by wiesmann** [comment]
What is the difference between a productID of the form prefix:value and a PropertyValue where the name=prefix and value=value?
