### ISSUE TITLE
Include schema:Product in range of schema:category

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#131]
When we integrated GoodRelations, we skipped the category property for reasons I do not remember.

This should be fixed - simply add
```<span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Product">Product</a></span>```

in the block for

```<div typeof="rdf:Property" resource="http://schema.org/category">```

This will also make this consistent with 

http://www.heppnetz.de/ontologies/goodrelations/v1.html#category

**Comment by mfhepp** [comment]
I fixed the title, because it was about the domain, not the range of the property.

**Comment by danbri** [comment]
see also #160
