### ISSUE TITLE
Capturing Taxi drop-off location and time, and expanding to ride sharing services

### ISSUE THREAD

**Issue by nicolastorzec** [schemaorg/schemaorg#1310]
**1) How to best capture Taxi drop-off locations and times?**
- Option 1: Add dropOffLocation and dropOffTime in [TaxiReservation](http://schema.org/TaxiReservation), similarly to [pickupLocation](http://schema.org/pickupLocation) and [pickupTime](http://schema.org/pickupTime)?
- Option 2: Add such details in a new TaxiTrip class (i.e. similarly to [BusTrip](https://schema.org/BusTrip), [TrainTrip](https://schema.org/TrainTrip), and [Flight](https://schema.org/Flight)), and link to it from TaxiReservation via [reservationFor](http://schema.org/reservationFor)?
## 

**2) Would it make sense to capture reservations and trips from "ride sharing" services similarly?**
- If it makes sense to capture reservations and trips from "ride sharing" and "vehicle for hire" services, we could either expand Taxi-related classes and properties, or create new ones.
## 

@vholland, @danbri, @chaals, @rvguha, others?
=> If this topic has already been addressed, please close and point me to the suggested resolution.

**Comment by vholland** [comment]
The most expedient thing would be to add dropOffLocation and dropOffTime to TaxiReservation, but I am not opposed to adding a TaxiTrip to have something similar to the other trip types.

By "ride sharing" do you mean car pool services or something more like uberPOOL?

I think it would be better to relax the definition of "TaxiReservation" to include ride services like Uber and Lyft. The space is evolving and it may be hard to define the lines between types otherwise. (For example, what is uberTAXI if we try to split out traditional taxis from other ride services?)

**Comment by danbri** [comment]
Maybe "taxi" in the US is more fluid and colloquial, but calling private hire cars "taxis" in the UK is a very big deal. Particularly in London with "The [Knowledge](https://en.wikipedia.org/wiki/Taxicabs_of_the_United_Kingdom#The_Knowledge)". I can see the case for capturing the commonalities between taxis, private hire cars, ride-sharing services etc., but using the term "taxi" would be needlessly controversial (nearby: [sample news story](http://www.bbc.co.uk/news/technology-27517914)).

So +1 on addressing these issues in general, -1 on the specific of "I think it would be better to relax the definition of "TaxiReservation".

**Comment by gmackenz** [comment]
Maybe we leave TaxiReservation as is —just for registered tax services—and have a supertype for VehicleReservation for taxi service and all other non-taxi-services.

**Comment by vholland** [comment]
@gmackenz's solution sounds good to me.

**Comment by danbri** [comment]
LGTM. @nicolastorzec ?

**Comment by nicolastorzec** [comment]
Let's keep TaxiReservation for registered taxi services for now, and work on "private hire cars" and " ride-sharing" services in a separate track.

If there are enough commonalities among them, we should indeed create a VehicleReservation or TransportReservation class. Same applies to Flight, TrainTrip, and BusTrip: common properties could be captured in a TransportTrip class holding concepts like departure/arrival, etc. 

Meanwhile, what shall we do with dropOffTime and dropOffLocations data properties? Add them into the TaxiReservation or add them in a new TaxiTrip class along with other properties about the course?

I have a slight preference towards creating a TaxiTrip/TaxiCourse class (esp. because we may not know about all the course details at the time of the reservation) but that may be a bit overkilling.

**Comment by ikonst** [comment]
As a result, do we have a schema for ride sharing rides that took place? Seeing the conversation ended in 2016.

**Comment by chaals** [comment]
A few thoughts:

"Taxi" means in many places a dedicated, licensed service that operates with special rules.

Then there are vehicles with drivers, which may or may not be taxis. Minicabs in the UK, uber services in many places, a chap driving down the street who will stop if you wave in many places, limo services and the like.

Uber services are often called shared rides, but they are not, in any obvious sense. Someone picks you up where you want them to, and drops you where you want them to, in a vehicle which offers what amounts to a private service for the passenger(s), as opposed to a shared ride in e.g. a minibus or a vehicle which simultaneously accepts other passengers for a different journey.

But in this case I am in favour of using the same term for uber, taxis, minicabs, limo services, and anything where someone else drives exclusively you and those you choose to somewhere you request a "taxi" or "PrivateVehicleHire" or something. Annotating the base type with some specific service details (provider-type, service provider, bus company, etc) where that makes sense seems more reasonable to me.

I would save the idea of a shared ride for services like US airport shuttles that may have fixed departure/arrival points, or offer drop-off/pickup at points of your choosing, but which differ from a private vehicle service in that other passengers may share the vehicle with you, whether going to the same or different destinations.

Note that I would suggest a service like a "hotel shuttle" that runs on a fixed route and takes passengers is actually the same as a regular bus - which shares many features with a train, scheduled airline flight, or ferry service.

Transport services for *things* should also align. From postal services for letters, to the people who hang around outside furniture shops and will take your big object in their van, or messenger / courier services.

**Comment by ikonst** [comment]
From a brand perspective, at Lyft we seem to have an aversion from our service being referred to as "taxi". In the business ride sector, the term "ground transportation" is often used.

Regardless, I was looking into whether we could decorate our receipts with schema so they render better in Gmail, etc. and saw there's apparently no schema for this.

**Comment by thadguidry** [comment]
@ikonst Don't worry about if we don't have schema yet for all this.  Just put together a strawman example proposal in any form or format for now (even simple text of the types and properties your thinking of) and link to the document or gist for all to review and make comments here.

**Comment by nicolastorzec** [comment]
Strawmen we discussed so far:

* Option 1:
Add dropOffLocation and dropOffTime in TaxiReservation, similarly to pickupLocation and pickupTime?

* Option 2:
Add such details in a new TaxiTrip class (i.e. similarly to BusTrip, TrainTrip, and Flight), and link to it from TaxiReservation via reservationFor?

**Comment by nicolastorzec** [comment]
This came up again while discussing product use cases around private vehicle trips, taxi trips, bus trip, train trips, flights, and cruises.

Any new thought on this @danbri @thadguidry @gmackenz @ikonst @chaals @vholland ?

(Also see #889, which is related)

**Comment by ikonst** [comment]
At Lyft we've just finished launching [integration with multiple expense management systems](https://blog.lyft.com/posts/automatic-expensing-with-7-new-expense-management-partners). While we used a proprietary schema for this, it was my goal to revisit this after the launch to formalize a standard schema.

**Comment by danbri** [comment]
I wish we could think of a good general word to avoid using Taxi for non-Taxis. I don't have a strong view on option 1 vs option 2, but would love to see us move forward with either if there's some rough consensus here. @ikonst - it would be great to see what you've done in this area.

(re the word "Taxi" this is a very heated topic in UK e.g. https://www.theguardian.com/technology/2016/feb/12/war-on-wheels-uber-driver-black-cab-driver-debate-london-taxi-trade )

**Comment by ikonst** [comment]
Let's leave the question of "taxi" vs. "limo" vs. "ground transportation" for last, otherwise we risk bikesheding.
