### ISSUE TITLE
Displays the search google Rating

### ISSUE THREAD

**Issue by diemnga09** [schemaorg/schemaorg#1312]
Hi all,

I have one problem you would like assistance.
I want to get out evaluations when searching with google search.
My website: [http://thanhhuongthebest.com/](http://thanhhuongthebest.com/)
What can I do???
![capture](https://cloud.githubusercontent.com/assets/21051333/17688056/adadf874-63a5-11e6-999a-65e006287e6c.JPG)

**Comment by danbri** [comment]
Try asking in Google's product forums. This is the project site for schema.org itself, we can't help with product-specific questions. Good luck!
