### ISSUE TITLE
Create process/UI/etc for terms that graduate from Pending (or get archived/abandoned)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1318]
We now have the Pending section as a place for proposed new terms. It isn't required for every schema.org change, especially those entangled with existing terms, but it is a useful way to make new schema ideas easier to find than they have previously been.

The next step is making sure have the workflow for these terms as they evolve further.
1. If a term (let's use "Course" as an example) is published initially in pending.schema.org but gets rough consensus and progresses to be added to the core, let's make sure that the old URLs still work. They should do, e.g. http://pending.schema.org/Person gives the pending section's view of a term from the core. We could probably do more to indicate status/history though.
2. If a term is retired, e.g. the proposal is retracted, or remodelled, or abandoned, how can we document that?

From https://twitter.com/danbri/status/766866355886911488 - suggestion of attic.schema.org,

> .@rjw idea... http://attic.schema.org  "this section contains deprecated, superseded & obsolete terms + proposals that have been abandoned."?

See also 'term status' discussion in #465 (such vocabulary would be defined in 'meta' section).

**Comment by RichardWallis** [comment]
Propose that 'attic' terms display (probably with a warning)  if directly accessed but not to display in default listings (full.html), dumps (eg. all-layers.nt), etc.  With an attic specific dump available in all usual forms.

**Comment by danbri** [comment]
@RichardWallis as discussed I see this as a "would be nice", I guess as I was assuming we would cut down the proposed terms to be quite minimal. But it makes sense to avoid cluttering the dumps and Web views. Currently we do already suppress superseded properties from most views.

**Comment by danbri** [comment]
(I've just added "attic" to the webschemas.org DNS to try out the above idea)

**Comment by danbri** [comment]
Obsolete - we have been moving away from using subdomains
