### ISSUE TITLE
Three different spellings of "educationalLevel" alignment type

### ISSUE THREAD

**Issue by acka47** [schemaorg/schemaorg#1321]
On the [`alignmentType` page](http://schema.org/alignmentType ) itself "educationLevel" is listed as recommended value but it actually isn't used anywhere in the ecamples. Instead one finds the same examples using both "educationalLevel" (Example 1) and "Educational level" (Example 2) on the following pages:

- http://schema.org/alignmentType
- http://schema.org/educationalFramework
- http://schema.org/targetName
- http://schema.org/AlignmentObject
- http://schema.org/targetUrl

I am will make a pull request for this one changing the recommended value to "educationalLevel" and adjusting the examples.

**Comment by philbarker** [comment]
It should indeed be educational level / educationalLevel .

Thank you @acka47

**Comment by acka47** [comment]
You are welcome, Phil.

**Comment by danbri** [comment]
@philbarker can you close this when the edit is made? @acka47 thanks for the Pull Request. We've recently reorganized the way we're handling git between central schema.org and the course schemas community group, so I'll leave it in Phil's hands as to how to handle the fix (manually or pull request).

**Comment by philbarker** [comment]
@danbri this isn't really part of the schema course extension work, it's a bug from a previous commit that I made from LRMI. @acka47 's changes are perfectly in line with current LRMI work to build SKOS definitions for terms like these (see https://github.com/dcmi/LRMI_Vocabs/blob/master/alignmentType.ttl )--which is not surprising as he has contributed to that effort also.  I would rather not mix this in the schema course extension work, which involves a slightly different group of people, so it is probably best if you accept https://github.com/acka47/schemaorg/commit/166724870370e4a088af06403ad49283c97f0153 as is

**Comment by danbri** [comment]
ok, thanks both! https://github.com/schemaorg/schemaorg/pull/1322 is merged
