### ISSUE TITLE
Default schema.org to HTTPS

### ISSUE THREAD

**Issue by bhubbard** [schemaorg/schemaorg#1325]
I would like to see the schema.org website default to `https`. 

Once this is done examples on the website can start to be updated to use `https` as well.

**Comment by danbri** [comment]
It will happen. We wanted to give a bit of time for http://schema.org/docs/faq.html#19 to settle in first...

**Comment by bhubbard** [comment]
I understand, just glad to see its on the radar. My only thought is as a standard its sets a good example for others by seeing schema.org making the move soon. I would prefer the FAQ say that developers should going forward only use `HTTPS`, but still be clear that `HTTP` is still acceptable. 

So maybe the examples should be updated before the site forces `https`?

**Comment by Dataliberate** [comment]
I’m probably going to regret this, but I’ll dive in anyway.

As the FAQ says, “both ‘https://schema.org' and ‘http://schema.org' are
fine."

In the sense of data identifiers, the URIs (URLs) ‘
http://schema.org/CreativeWork' and ‘https://schema.org/CreativeWork' are
different identifiers and, for instance, in a simple dataset matching query
they would not be matched to each other.  It is only in the hands of the
data consumers (search engines and others) to implicitly treat them as
equal.

The main point of moving towards https for web requests, which I whole
heartedly agree with, is to prevent requests and responses being sent in
clear text.  Defining a type or a property in the markup on a web page as ‘
http://schema.org/Book' or ‘https://schema.org/about', does not in
themselves instigate requests, they are just being used as an identifier
for the types and properties used.

So a page containing structured markup being identified as
https://example.com/page has many well discussed benefits.  Indicating
within the page markup that the thing being described as a
https://schema.org/Product or a http://Product has zero impact on the
security of that page or its use.

To that end, I think it would be detrimental, especially to new users, of
Schema.org to insist or imply that all term URLs should be of the https
form. The site and its terms operate under both protocols and it should
continue to do so.

~Richard.




Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by unor** [comment]
Also note that W3C’s [RDFa Core Initial Context](https://www.w3.org/2011/rdfa-context/rdfa-1.1) (which is [also used for JSON-LD](http://www.w3.org/2013/json-ld-context/rdfa11)) defines that the prefix `schema` is used for the HTTP variant (`http://schema.org/`).

So whenever authors use the `schema` prefix in RDFa/JSON-LD without specifying their own mapping for it, the HTTP Schema.org URIs will be used.

**Comment by gkellogg** [comment]
Agree with Richard, it’s important for backwards compatibility that schema.org terms remain in the “http:” schema. However requests to this should redirect to “https:”. This should be the same for the JSON-LD Context at “http://schema.org/“ (with appropriate content negotiation).

Ideally, TLS could be supported using the “http” scheme, without requiring redirects, something which I think may be coming to HTTP in the future.

(Also, note that JSON-LD does _not_ use the RDFa initial context; a JSON-LD context needs to be explicitly provided).

Gregg Kellogg
gregg@greggkellogg.net

**Comment by danbri** [comment]
See also #1338 for a glitch in the https version currently.

I believe we could migrate the site to default to https without changing all examples, however we should expect to see https: creeping into use within schema.org structured data, and it would be prudent to explore the impact of that with various JSON-LD, Microdata and RDFa tools before pushing it heavily.

One relatively cheap step we could try would be to have a new prefix in RDFa and (the optional) JSON-LD initial context (if they're open for updates) using e.g. 'sdo:' or 's:' but pointing to the https: URL instead of http:.

**Comment by Aaranged** [comment]
A lightweight interim improvement here would be at least to provide rel="canonical" on each page that points to the HTTPS version.  As this is simply a piece of search engine-facing metadata it should have null impact on any processes or tools (as any URL could still be accessed as HTTP), but would help the search engines which URL to preferentially return in search results.

E.g. for Thing this code in the `<head>` (for both http://schema.org/Thing and https://Thing):
<link rel="canonical" href="https://schema.org/Thing" />

**Comment by AymenLoukil** [comment]
+1 @Aaranged. And then provide only https version in Sitemap.xml #1483

**Comment by deadjdona** [comment]
Good day.

Just a thought:
As both http and https versions of site are working fine now, maybe it's better to **start using https in examples on site right now**, so new users (and some existing users) will use https version from start?

Also this will allow plugin makers (for various CMS) update their plugins in meantime, as they will see strong signal for coming migration.

And there will be less redirects from http to https after you set http -> https redirect for site migration.

**Comment by deadjdona** [comment]
and there are both http://example.com/ and https://example.com/ versions used in examples.
