### ISSUE TITLE
CODE: support markdown (GFM) in http://schema.org/docs

### ISSUE THREAD

**Issue by elf-pavlik** [schemaorg/schemaorg#133]
It could make it straight forward to work in github issues and wiki pages, and then once something matures move it to http://schema.org/docs/

You can find example of schema.org documentation done with GFM in #125 

I could also help here with another example and rewrite http://schema.org/docs/actions.html in GFM #123 

Nice Markdown(+GFM) guide (3min claim) available at: https://guides.github.com/features/mastering-markdown/

This library for python looks quite popular: https://github.com/trentm/python-markdown2

**Comment by danbri** [comment]
I'm filing this in the wontfix/someday pile, although I appreciate the suggestion and it is worth exploring. For starters I suggest we make it clear to those who like markdown how to convert to HTML for use on the site, and take it from there. The actions.html doc was exported from Google Docs, for example, and some people prefer word-processing environments for the commenting etc. I'm not sure we'll find a single workflow that suits everyone.
