### ISSUE TITLE
We have some enumerations that don't appear to be enumerated - these need checking

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1332]
From the new test added by @RichardWallis -

test_EnumerationWithoutEnums (test_graphs.SDOGraphSetupTestCase) ... INFO:test_graphs:Enumeration Type without Enumeration value(s) errors!!!

INFO:test_graphs:Enumeration Type 'http://schema.org/BedType' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/BusinessEntityType' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/BusinessFunction' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/CreditCard' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/DrugClass' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/DrugCost' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/EnumerationValue' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/LockerDelivery' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/MedicalEnumeration' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/ParcelService' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/Patient' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/PaymentCard' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/PaymentMethod' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/QualitativeValue' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/Specialty' has no matching enum values
INFO:test_graphs:Enumeration Type 'http://schema.org/WarrantyScope' has no matching enum values

**Comment by mfhepp** [comment]
Many of those are meant to allow the site-wide definition of enumerations, so this is not always a bug.
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
Probably time we did a compare/contrast with @RichardWallis 's https://github.com/schemaorg/schemaorg/issues/894 proposal

**Comment by vholland** [comment]
Some of these are from GoodRelations. We put examples in the description, but may be we should add something machine readable.

**Comment by Dataliberate** [comment]
I can understand the need for an area specific super-type (sub type of
Enumeration) so I agree its probably not always a bug.

Maybe there is internal, as well as external, capability that Enumeration
value (from #894 <https://github.com/schemaorg/schemaorg/issues/894>),
could bring.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by danbri** [comment]
I have marked this test as expectedFailure for now, but ongoing attention would be worthwhile.

**Comment by RehanSaeed** [comment]
I'm using the machine readable JSON-LD to generate concrete POCO classes in C# at https://github.com/RehanSaeed/Schema.NET (Doing this has been much more difficult than I expected, it seems schema.org is not the single source of truth I expected it to be).

I've also come across the missing enumeration values in the machine readable content. Where can I get these enumeration values in a machine readable format? Should I exclude these properties altogether?

What is mean by:

> Many of those are meant to allow the site-wide definition of enumerations, so this is not always a bug.

I've also come across GoodRelations in the JSON-LD. What is this and what can/should I do with it:

```
"http://purl.org/dc/terms/source": {
    "@id": "http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsTerms"
},
```

**Comment by mfhepp** [comment]
>I've also come across GoodRelations in the JSON-LD. What is this and what can/should I do with it:
>
>"http://purl.org/dc/terms/source": {
>    "@id": >"http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsTerms"
>},

This is one of the values for identifying the sources of major contributions to schema.org and it is used to trigger the proper acknowledgments in the human-readable documentation. They are not meant for typical end-users.

>Also QualitativeValue seems to be a special case. It inherits from Enumeration but nothing >inherits from it.
QualitativeValue is the class for enumerated values that represent qualitative aspects. Most such values are defined in instance data, not inside schema.org.  See also

http://www.heppnetz.de/ontologies/goodrelations/v1.html#QualitativeValue

**Comment by RehanSaeed** [comment]
@mfhepp Thanks for that.

**Comment by RehanSaeed** [comment]
@mfhepp Thanks for that. 

Is there any machine readable format for all of the enumeration values above or is it the case that they are too open ended and the expectation is that users will have to go off to some other source of information and manually figure things out? 

In the documentation I read, the Countries list is like that, you are expected to use a two letter ISO code which schema.org does not maintain.

**Comment by RichardWallis** [comment]
Pull #2614 closes this issue in its current form.
There may well be opportunity for further rationalisation in the future.
