### ISSUE TITLE
No schemas viewed on webschemas app

### ISSUE THREAD

**Issue by aparna-thuluva** [schemaorg/schemaorg#1335]
Hi,

I am new to schemaorg project. I installed Google App Engine for python and loaded schemaorg project into the App engine and ran the project. But, in http://localhost:8080 i cannot see any schemas.

I checked the app.yaml and found that the files used in app.yaml such as /docs/schema_org_rdfa.html, /docs/jsonldcontext.json._, /docs/schemas.html, /docs/developers.html and /docs/tree.json._ are not present in docs folder.

Could someone please let me know the fix for this issue.

**Comment by RichardWallis** [comment]
Hi,

The files you mention are created programatically so it is correct you won't see them in the folder.

Couple of questions, to help me help you.

What operating system are you on?
Are you running from the Google App Engine launcher or the commandline?
What do you get when you connect to locahost:8080 ?

You may find this [blog post](http://dataliberate.com/2016/02/10/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/) helpful in identifying where your problem may be.

~Richard.
