### ISSUE TITLE
author property not showing on [https version of] CreativeWork page

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1338]
Reported by Thad in https://lists.w3.org/Archives/Public/public-schemaorg/2016Sep/0013.html and Aaron notes it as an intermittent bug.

http://schema.org/author lists it as applicable to CreativeWork, and data/schema.rdfa has the following triples:

```
<http://schema.org/author> <http://schema.org/domainIncludes> <http://schema.org/CreativeWork> .
<http://schema.org/author> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://schema.org/author> <http://www.w3.org/2000/01/rdf-schema#comment> "The author of this content or rating. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably." .
<http://schema.org/author> <http://schema.org/domainIncludes> <http://schema.org/Rating> .
<http://schema.org/creator> <http://www.w3.org/2000/01/rdf-schema#comment> "The creator/author of this CreativeWork. This is the same as the Author property for CreativeWork." .
<http://schema.org/author> <http://schema.org/rangeIncludes> <http://schema.org/Person> .
<http://schema.org/author> <http://schema.org/rangeIncludes> <http://schema.org/Organization> .
<http://schema.org/author> <http://www.w3.org/2000/01/rdf-schema#label> "author" .
```

Thad's post also notes that the wording of /creator isn't ideal, but let's worry about that elsewhere - this bug is about the presentation of author on CreativeWork (and anything systematically equivalent to this).

/cc @RichardWallis

**Comment by danbri** [comment]
Two views of CreativeWork (in zip): 

* 322531 Sep  1 23:45 CreativeWork - schema.org.html (loaded from http://schema.org/)
* 307424 Sep  1 23:45 CreativeWork - schema.org2.html  (loaded from https://schema.org/)

[CreativeWork_1338_bug.zip](https://github.com/schemaorg/schemaorg/files/450862/CreativeWork_1338_bug.zip)

**Comment by RichardWallis** [comment]
Analysis showing that it is a consistent difference between the http & https versions of the page - not unexpected as the versions will be cached separately in the page cache.
Other differences also noted: accessibilityAPI & associatedMedia  are also missing from https version

**Comment by danbri** [comment]
[httpsoops.zip](https://github.com/schemaorg/schemaorg/files/451663/httpsoops.zip)

**Comment by vberkel** [comment]
Found a related issue, datePublished is missing on https://schema.org/BlogPosting while it is there for http

**Comment by danbri** [comment]
Thanks @vberkel. This seems to be a sporadic problem with the https. @RichardWallis any progress diagnosing?

**Comment by RichardWallis** [comment]
Not much progress on diagnosing the cause at the moment.

Not seeing the difference with datePublished on http/https versions of BlogPosting as described, whereas previous reported differences were solid, before a restart cleared them.

**Comment by vberkel** [comment]
@RichardWallis the problem resolved for me when I emptied my cache and reloaded the page. Sorry for the false report.

**Comment by bquinn** [comment]
I can't replicate this, it seems to be fixed. I suggest that it this issue is closed.
