### ISSUE TITLE
RDFa expression of equivalent term mappings not showing up

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1341]
We collect mappings to other schemas (and these are showing up in the dumps, see https://github.com/schemaorg/schemaorg/issues/1337#issuecomment-244339641 ) but apparently not currently in per-term RDFa pages.

At least types like our Event -> Dublin Core event used to have in-page owl equivalences inline in RDFa. Looking at https://github.com/schemaorg/schemaorg/blob/sdo-callisto/sdoapp.py#L369 we should have properties too. This seems not to be working.

@RichardWallis can you investigate + figure out an approach to unit testing such things so functionality can't silently break?

**Comment by RichardWallis** [comment]
Fixed in PR (#1345)

Need a bigger test issue to identify such changes as this was effectively an unknown unknown.

**Comment by RichardWallis** [comment]
Fixed
