### ISSUE TITLE
Add 'owned by' - the inverse of our existing 'owns' property

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1342]
Wikidata has this: **owned by** https://www.wikidata.org/wiki/Property:P127

**Comment by mfhepp** [comment]
No inverse properties please, unless absolutely necessary.
Most syntaxes for schema.org have proper support for using the very same property in both directions, so there is no need to bloat the vocabulary with inverses :-;
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
@mfhepp "absolutely necessary" is hard to quantify, often it is more a matter of phrasing and usability. But I agree that it would be too much to default to adding pairs of properties on every occasion.

**Comment by thadguidry** [comment]
@danbri @mfhepp Ah ok.  Didn't realize we had drew the line.  This makes sense to me also.  Closing.
