### ISSUE TITLE
Fix Schema.org search input box indexing for names, keywords, descriptions, Types, Properties

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1347]
Complaints from web developers:
"Schema.org's search box does not work very well, sometimes it completely misses showing results for Types or Properties that have the term I searched for'
"Why didn't that even show up on page 1 of the results instead of not at all ? OMG"

What I saw just now as well during my testing...
When I type 'price' or 'amount' in Schema.org search input box... 'Monetary Amount' falls far down the result ranking ... in fact ... so far down... it doesn't show up in results !!!
The description in MonetaryAmount has the term 'amount' but for some reason it doesn't return in 1-4 pages of the result set either.

Monetary Amount is a way to say "Schema.org's Price Type" and it should return on page 1 result set if a user types 'price' or 'amount', **instead of not appear on any of the result pages as its currently doing for some strange reason.**

Others terms seem to show up just fine within descriptions... like 'periodical' https://schema.org/docs/search_results.html#q=periodical

UPDATE:
another example search that should be at the top of results, but fails to show on any results:
http://schema.org/docs/search_results.html#q=areaServed

**Comment by danbri** [comment]
It's a Google custom search engine, afaik without a lot of customization. I inherited it and have tweaked it trivially but never really looked deeply.
