### ISSUE TITLE
Testing new output formats

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1355]
Pull request (#1351) has introduced new output formats - csv for [download files](http://webschemas.org/docs/developers.html#defs) and csv, n-triples, rdf/xml, json-ld, turtle for per-term outputs.

These could benefit from a look over on webschemas.org, before release, by many eyes to check and comment.

Per-term outputs can be accessed in two ways. Firstly by adding the appropriate suffix (.csv, .nt, .jsonld, .rdf, .ttl) to the term URI:
- http://webschemas.org/Book.ttl
- http://webschemas.org/Product.rdf
- http://webschemas.org/description.jsonld
- http://webschemas.org/Paperback.nt
- http://webschemas.org/LocalBusiness.csv

Secondly they are available using content-negotiation, supplying the appropriate value for 'Accept' in the http request header (text/csv, text/plain, application/ld+json, application/rdf+xml, application/x-turtle).

**Comment by danbri** [comment]
For .rdf, http://rdflib3.readthedocs.io/en/latest/faq.html reports that "pretty-xml" could make the RDF/XML use some syntax shortcuts that reduces verbosity. Have you tried it?

**Comment by Dataliberate** [comment]
No but will take a look.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by RichardWallis** [comment]
PR (#1357) introduces "pretty-xml"

**Comment by danbri** [comment]
What's the goal of this open issue? To ensure we've had review of all the formats?

**Comment by RichardWallis** [comment]
Yes, and a place for comments to be collected - the individual elements are spread across several other issues.

This one can be closed when we are not inviting more comments.

**Comment by JimSaiya** [comment]
I noticed the page at http://webschemas.org/docs/developers.html#defs returns a file with extension `.xml` when format "RDF/XML" is selected.  As noted in the original comment, you add '.rdf` to a term URI to get RDF/XML output.  I'm guessing we want both methods to use the same extension.

If we have a choice, I'd prefer `.rdf` myself.

**Comment by RichardWallis** [comment]
Thanks @JimSaiya  - taken onboard in PR(#1366)
