### ISSUE TITLE
Support feature or sub-service for those pick-n-play style Service offerings

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1359]
Let me explain the use case.  Pay-to-play services are offered by many phone carriers, even online poker gaming :).  Some folks call these Service packages, etc.  But basically, you have websites were you can order cell phone service and pick and choose the sub-services or features of the service that you want....all of which are tied to your base cell phone service (not your account, and that's where the difference is).

So... we already have Offer > Service ... and under Service, I didn't see a way to fully express that a Mobile Phone service (the base service) has additional pick and choose sub-services available.

**I only saw isRelatedTo and we need something more concrete, like 'subService', 'ancillaryService' or 'serviceFeature'** which expects another Service or perhaps even better and more appropriate a new ServiceFeature.  (If you were invoiced for it all...these would be line items under your base service)

@mfhepp @vholland any thoughts there ?

**Comment by RichardWallis** [comment]
Could you follow the Offer model with [addOn](http://schema.org/addOn) having its domain, range, and description tweaked to include Service?

Or is it good enough as it is with addOn offers to the offer of the basic service?

**Comment by thadguidry** [comment]
@RichardWallis Ah, addOn ... let me think...are there any cons to the Offer model for pick-n-play services I wonder...no...there are cons on Service, since it doesn't have Price or SKU.

OK, so there it is ... addOn would work.

**Comment by mfhepp** [comment]
+1 to use addOn for indication optional additional products or services for which the pricing and availability is dependent on the context of a base product or service offer.

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by thadguidry** [comment]
@mfhepp Thanks for weighing in on this issue Martin.

TODO:  Someone to create an example for addOn and then close this issue.
