### ISSUE TITLE
Question: Correct way to mark up a blog?

### ISSUE THREAD

**Issue by ayumihamsaki** [schemaorg/schemaorg#1360]
Hi, I have a technical question about how to write a blog using schema. I will outline what I think and then look forward to hearing people's views on it?

(On https://schema.org/Blog it says Usage: Over 1,000,000 domains but there is no real example on correct usage I have a feeling 99% of these are creating them wrong).

Ok outline on writing a blog???

**To me schema:blog is the same as schema:webpage.
Also schema:BlogPosting is the same as schema:article.**

So using it like that I want to try and create a category page and an article page.

# Article Page:

Was thinking to use:

schema:BlogPosting for the article and schema:webpage for the webpage and then label the schema:mainEntity as schema:BlogPosting.

(Please note you can not use schema:Blog with schema:BlogPosting together seems to cause an error so hence why some people seem to use schema:webpage instead. Not sure if this is an error in the onotogology?)

# Category Page:

Was thinking to use:

schema:blog for the webpage and then list all the schema:BlogPosting (Blog Posts) under a mainEntity called: schema:blogPost. This to me is the biggest problem due to the lack of info on schema.org in how do I create the list? If say I use JSON-LD would I do something like this:

```
[ {
blog post 1
},
{
blog post 2
} ]
```

Or should I do something using schema:ItemList in the schema:blogPost? 

p.s. the English is very bad here as it says "A posting that is part of this blog. Supersedes blogPosts." This means a blogpost is pural not singular in this case.

Any help or ideas would be great and thanks in advance. I really want to find a correct way to mark up a blog.

(An example on the https://schema.org/Blog webpage would be helpful to show how to correctly outline a blog list as I am guessing this is where we can list all the blog posts).

**Comment by RichardWallis** [comment]
Yes @ayumihamsaki you are correct to identify we are a bit thin on examples in this area.

In json-ld I would recommend something like this:

**On the blogsite home page**:
```
{
  "@context":"http://schema.org",
  "@type":"Blog",
  "@id":"http://blog.example.com",
  "name": "My Test Blog Site",
  "description": "An imaginary site to test Schema.org markup",
  "blogPost": ["http://blog.example.com/myfirstpost.html","http://blog.example.com/anotherofmyposts.html"]
}
```
**On an individual blog post page**:
```
{
    "@context":"http://schema.org",
    "@type":"BlogPosting",
    "@id":"http://blog.example.com/myfirstpost.html",
    "name": "My First Post",
    "articleBody": "A few words to test my theory",
    "isPartOf": "http://blog.example.com"
}
```

If you wanted to prescribe the order the posts are referenced on the blogsite home page, you could indeed use ItemList.

**Comment by ayumihamsaki** [comment]
@RichardWallis Thanks that looks good what you have written and was what I was thinking. I didn't think to add the "isPartOf" back to the category/home page, which is a good idea.

In Google Testing Tool it is asking for more details for each blogPost like author, publisher etc so this is the reason why I am thinking to create an ItemList.

Many thanks for your comment, I am sure I can finish off the markup code now. (please feel free to close this issue if you want too).

**Comment by RichardWallis** [comment]
Glad you found it useful. 

Yes I will close it now, but do not let that stop you feeding back any experience you gain in taking this further.
