### ISSUE TITLE
Expand domain of schema:about property

### ISSUE THREAD

**Issue by EricAxel** [schemaorg/schemaorg#1361]
Hi All,

I'm opening this issue to discuss expanding the domain of [schema:about](https://schema.org/about). Currently, that domain is limited to [CreativeWork](https://schema.org/CreativeWork) and [CommunicateAction](https://schema.org/CommunicateAction). 

I propose that the domain be expanded to include Event and subTypes of Event. Throwing a few quick examples out: 

- A ChildrensEvent about Harry Potter: http://leacockmuseum.com/festival/harry-potter-childrens-day/
- A DanceEvent about history: https://govisland.com/blog/a-weekend-of-song-dance-performance-and-history
- An EducationEvent about chemistry, corrosion, rusting...: http://www.rsc.org/eic/2016/03/corrosion-rusting-electrochemistry-demonstration
- A ScreeningEvent about Alfred Hitchcock: http://minneapolis.happeningmag.com/hitchcock-festival/

**A full example:**
I've experimented with this idea, marking up this BusinessEvent, which covers multiple topics:
http://edw2016.dataversity.net/ 
The result is visible here: https://search.google.com/structured-data/testing-tool/u/0/?url=http://edw2016.dataversity.net/#url=http%3A%2F%2Fedw2016.dataversity.net%2F

What do folks think of this proposal? I can work up more formal examples if there is agreement it's worth the effort.

Also, are there other types that would benefit from inheriting the about property? I can foresee a desire to describe a [schema:Organization](https://schema.org/Organization) in this manner:

The [World Food Program](http://www.wfp.org/) is about: https://en.wikipedia.org/wiki/Malnutrition 

Cheers,
--Eric

**Comment by RichardWallis** [comment]
This is a repeat of issue (#1296) which I have closed in favour of this one as you have included more detail.

**Comment by rvguha** [comment]
Sounds reasonable to me.

guha

**Comment by vholland** [comment]
The Event use case makes sense to me. I am not convinced that "about" works on Organization.

**Comment by danbri** [comment]
I agree - let's do it for Event. For People, Organization, Place I would continue to do this indirectly via relations to entities where "about" directly makes more sense. For Action in the past-tense sense, there is perhaps a case for "about" since actions are really kinds of events, even if we didn't reflect that truth into the type hierarchy. For Product, we could go either way. It might be more compelling if there were more of an ecosystem of usage around "about" pointing into existing controlled vocabularies.

**Comment by RichardWallis** [comment]
+1

**Comment by thadguidry** [comment]
My comments to Eric on mailing list:

In the past, I've voted to stick 'about' right onto schema.org/Thing :)  any Thing can be about anyThing :)
But that was deemed overkill.  I like killing things I guess. :)
In general, and a few folks swayed my mind into conciseness, having 'about' available on Types where it makes common sense for that Type in the wild is usually a best practice.
So if you have more than just Event that you feel 'about' or 'aboutness' is a common occurrence that your seeing, then let's expand into those domains as well.

A few that I see with my quick 1 minute eyes :

http://schema.org/TelevisionChannel  - home improvement, gardening, etc - HGTV
http://schema.org/JobPosting - industry=gaming, skills=machine learning, about=Biological Systems
http://schema.org/ReservationPackage - I recall folks in Travel industry wanting 'about' to help sell their tour packages in niche markets like 'ecology', 'space', etc.
http://schema.org/Organization  and http://schema.org/NGO  and probably any sub Organization types we have like GovernmentOrganization  - In Freebase we had a really cool 'aboutness' property called 'scope' or something, forgot what it was actually called, to note what an organization is involved in, not just its naics code or industry.  Like PETA would have a scope of 'animal rights'.

and so many more I forgotten about.

**Comment by thadguidry** [comment]
@RichardWallis and Richard don't just +1  :)  I want to really hear your Librarian voice saying ...

'about: should always be constrained to the notion of a Thing having a subject.  Anything more than a Thing being about a subject(s), then we ought to discover what that 'subject' alternative would be.  I.E. genre, applied in field of science, activism area, etc.  And create nice good properties for those.'

**Comment by RichardWallis** [comment]
@thadguidry sorry for 'just +1ing' ;-)

I was commenting on @danbri's "_let's do it for Event_", having already commented on the issue I closed in favour of this one (#1296)

To expand I go along with the idea that there are certain types of _thing_  (CreativeWorks, Events, communications) that can be '_about_' (have a subject of) something else.  But saying a Person or an Organisation is about another thing is stretching the generally understood meaning of the word about.  There may be very similar, yet sufficiently different, terms (scope, focus, mission,...) that could be introduced as being applicable in these areas.

**Comment by thadguidry** [comment]
@RichardWallis thank you :)

**Comment by jvandriel** [comment]
As you're discussing 'aboutness' here, might I remind you there's a related topic that still needs closure, namely that of ```about```'s inverse: ```topicOf``` (#1115). I'd love to see some movement on it.

**Comment by danbri** [comment]
Done! http://webschemas.org/about

**Comment by danbri** [comment]
Thanks @rtroncy!

**Comment by rtroncy** [comment]
cc @rbailly !
