### ISSUE TITLE
blogPost: adding hasPart as super-property?

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1362]
I think [`blogPost`](http://schema.org/blogPost) should have [`hasPart`](http://schema.org/hasPart) as super-property.

Thoughts?

**Comment by danbri** [comment]
I can see where you're going with that, and I do think we could do more with superproperties or other forms of metadata about properties ... but where would we [stop](http://plato.stanford.edu/entries/mereology/)? I'm skeptical about bringing a theory of parts to schema.org.

Do teams have parts that are their members? Do local businesses have parts that are their departments, or corporations have parts that are their local branches? Do departments of local branches have parts that are their employees, and those employees have parts that are their [nerves](http://health-lifesci.schema.org/nerveMotor)? There are so many senses of 'part' whose usage might overlap, I'm not sure what could be practically inferred at the instance level if we declared them all to imply 'hasPart'.

Random thought on the blogPost front: can a blog post be part of two blogs? Maybe via iframe, js or RSS/Atom syndication, eg. planet sites like http://planetrdf.com/

**Comment by RichardWallis** [comment]
I can also see where @unor is coming from and in isolation it seems a sensible suggestion, if nothing else giving a bit of a clue that a blog is made up of blog postings.

@danbri is right however to raise the broader concern as to the potential sub-property flood gates that this could open.  So, I am undecided as to if I should support this or not and would be happy with a decision either way.

As to @danbri's random thought, yes a blog post could easily be part of more than one blog - guest postings repeated on home blogs, and blog aggregation sites demonstrate this possibility.

**Comment by thadguidry** [comment]
-1 for this proposal.  Agreed with @danbri this causes to much inference issues for machine reading and understanding.

**Comment by unor** [comment]
@danbri: But the `hasPart` property has only `CreativeWork` as domain and range, so the mentioned examples (teams & members, local businesses & departments, corporations and branches, local branches & employees, employees & nerves) don’t seem to apply to this specific property, right? We don’t want to broaden it. I’m aware of the potential problems with mereology, but as long as we stay in the same domain (`CreativeWork`), couldn’t it work?

From the author perspective: 

1. I consider to use `hasPart` to add a `BlogPosting` to a `Blog`
2. I check the definition of `hasPart`: its definition matches ("a CreativeWork that is (in some sense) a part of this CreativeWork")
3. I check the 'Sub-properties' of `hasPart`, maybe there is a more specific property available: `containsSeason`, `episode`, `hasEnumerationValue`, `season` don’t seem to apply, so I go with `hasPart`

If we’d add `blogPost`, authors could find this property that way, just like authors could find `episode`.

Even just looking at the definitions of the two properties in question, it seems as they are perfect matches:

> A posting that is part of this blog.  
> […] a CreativeWork that is […] part of this CreativeWork.

**Comment by danbri** [comment]
Yes, maybe you triggered my standard anti-parts rant ;) There is some sense in which an entire blog could be considered a Creative Work, and "I can’t think of a case where using blogPost is appropriate, but hasPart would not be" is a good test. Anyone else have views?

**Comment by thadguidry** [comment]
@danbri Hmm... Well, as long as we don't assume anything about 'containerization' here with blogPost being a part of a Blog.  I guess I could live with the proposal.  In fact, this whole discussion makes me want to lean over the edge and see us explicitly call that out in the hasPart definition. 'this property does not assume any form of containerization', just to avoid artifacts of mereology potentially coming into the picture ?

**Comment by Estavio** [comment]
Sorry for my question.  Is my "hasPart" correct?


<!DOCTYPE html> 

<html itemscope itemtype="http://schema.org/WebSite">
<head>
</head>
<body itemprop="hasPart" itemscope itemtype="http://schema.org/WebPage">
    <link itemprop="mainEntityOfPage" href="http://example.com/" />
    <link itemprop="specialty" href="http://schema.org/Dentistry" />
    <link itemprop="audience" href="http://schema.org/Patient" />
    <div class="wrapper">
        <header itemprop="hasPart" class="header" itemscope itemtype="http://schema.org/WebPage">
        </header>
        <nav itemprop="hasPart"  itemscope="" itemtype="http://schema.org/SiteNavigationElement">
            <ul>
                <li><a href="/">something</a></li>
                <li><a href="#">something</a></li>
                <li><a href="#">something></li>
            </ul>
        </nav>
        <main class="main">
            <section>
                <article class="content">
     
                    <div class="flex-container">
                    </div>
                </article>
            </section>
            <section class="news">
<aticle itemprop="hasPart" itemscope itemtype="http://schema.org/NewsArticle"> 

</article>
         </section>
        </main>
        <aside itemprop="hasPart" itemscope itemtype="https://schema.org/WPSideBar">
        </aside>
        <footer itemprop="hasPart" class="footer" itemscope="" itemtype="http://schema.org/WPFooter"
        </footer>
    </div>

</body>
</html>
