### ISSUE TITLE
TelevisionChannel needs genre

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1364]
http://schema.org/TelevisionChannel currently doesn't have a property to hold **genre**

(There might be other Types in Schema.org within Entertainment, Creative forms that could also benefit from having a **genre** property)

(we have **category** available on Service http://schema.org/BroadcastService , but that's different )
 
Use case Examples:

{
  "@context":"http://schema.org",
  "@type":"TelevisionChannel",
  "name": "ESPN2",
  **"genre": "Sports",**
  "broadcastChannelId":"016",
  "broadcastServiceTier":"Premium",
  "inBroadcastLineup":{
    "@type":"CableOrSatelliteService",
    "name": "Comcast",
  }
}

{
  "@context":"http://schema.org",
  "@type":"TelevisionChannel",
  "name": "MTV HD",
  **"genre": ["Music", "Reality"],**
  "broadcastChannelId":"69",
  "broadcastServiceTier":"Standard TV",
  "inBroadcastLineup":{
    "@type":"CableOrSatelliteService",
    "name": "TimeWarner Cable",
  }
}

![capture](https://cloud.githubusercontent.com/assets/986438/18489485/5b7f31ec-79c3-11e6-820b-a08c979ec3be.PNG)

**Comment by vholland** [comment]
+1

We could add the property to BroadcastChannel so RadioChannel could benefit as well.

**Comment by danbri** [comment]
Sounds good to me.

**Comment by danbri** [comment]
Queued at http://webschemas.org/docs/releases.html#g1364
