### ISSUE TITLE
replace interactionCount with interaction

### ISSUE THREAD

**Issue by elf-pavlik** [schemaorg/schemaorg#137]
In one of last emails about differences between *potential* and *active/compleated* Action, I suggested introducing new property *interaction* which would supersede *interactionCount* -  http://lists.w3.org/Archives/Public/public-vocabs/2014Sep/0174.html

```js
{
  "@type": "WebPage",
  "@id": "http://example.net/",
  "interaction": [
    {
      "@type": "ViewAction",
      "@id": "http://mypds.net/joe/ew0r98a0ga",
      "actionStatus": "CompletedActionStatus",
      "object": "http://example.net/",
      "endTime": "2017-01-04T10:32:15+01:00"
    },
    {
      "@type": "ReadAction",
      "@id": "http://mypds.net/joe/0a9fd80gh7",
      "actionStatus": "CompletedActionStatus",
      "object": "http://example.net/",
      "startTime": "2017-01-04T10:32:15+01:00",
      "endTime": "2017-01-04T10:37:04+01:00"
    }
  ]
}
```

>While on it, I would like to bring attention (for the 4th time in last 2
years) to: http://schema.org/interactionCount

>And propose to replace it with *interaction* which would accompany
*potentialAction* on Thing.

>* Thing --{potentialAction}--> Action --{actionStatus}-->
PotentialActionStatus

>* Thing --{interaction}--> Action --{actionStatus}--> ActiveActionStatus
|| CompletedActionStatus

**Comment by danbri** [comment]
Thanks for the detailed proposal. This clearly needs some attention now that Actions has shipped...

**Comment by vholland** [comment]
For issue #170, we were going to deprecate all of UserInteraction, which makes interactionCount useless.

It would be useful to have some sort of AggregateInteractionCount class so pages could mention how many times something has been liked or tweeted, which I think was the original intent of UserInteraction, but that is for another release.

**Comment by danbri** [comment]
I've generously assigned this to Vicki, since she is handling the UserInteraction area (and which looks likely to go away and take interactionCount with it).

Since the issue here is also forward looking, once interactionCount goes away, I'm moving it out from sdo-gozer into sometime-in-Q2.

**Comment by vholland** [comment]
In the spirit of @elf-pavlik's proposal, I put together https://github.com/vholland/schemaorg/commit/a8c3e6c1a7bf4f2ba6f9b0a31d176cc06c36f3a2


The major difference is I did not leverage Action, for two reasons:
1. We would need to modify VoteAction or (create UpVoteAction and DownVoteAction) to make the up vote/down vote use cases work.

2. Other than the specific verbs chosen by various services, the semantic difference of "up voting", "liking", "plus'ing", etc are ambiguous. I would like to future-proof for the next big social media site that supports "hurrays".

To that end, I added the ability to say which site/app is used for the interaction so one can separate out Facebook likes from Youtube up votes.

**Comment by vholland** [comment]
Actually, the more I think about it, @elf-pavlik had the right idea. If I stop thinking in terms of up/down vote and in terms of http://schema.org/LikeAction and http://schema.org/DislikeAction, it works. It ties in Actions and doesn't require a bunch of new types.

I'll make that change tomorrow.

**Comment by vholland** [comment]
Please see pull request #514 for an implementation that uses Actions.

**Comment by danbri** [comment]
@chaals - did you reach an opinion on this and the corresponding pull request, #514 ? /cc @tilid @ajax-als  ... I believe everyone else is signed off. I will go ahead and merge it into the work-in-progress next release branch sdo-ganymede but do take a look...

**Comment by danbri** [comment]
see final review thread https://lists.w3.org/Archives/Public/public-schemaorg/2015Jul/0047.html
