### ISSUE TITLE
http://schema.org/VisualArtwork: participation history

### ISSUE THREAD

**Issue by Mailis** [schemaorg/schemaorg#1370]
Visual Artwork has also participation history: participated exhibitions, auctions or some other kind of happenings.

**Comment by RichardWallis** [comment]
@Mailis It may be a good idea to pull together the several issues you are raising around VisualArtwork into a single proposal to enhance the Type.  That would provide a single place to focus discussion, and provide some examples, about your suggestions.

For clarity you can then close the individual ones.

**Comment by RichardWallis** [comment]
From a property name point of view the ```isPartOf``` property seems to do the job.  

However it would need its range expanding to include ```Event```.  Potentially a useful addition anyway.

**Comment by sfolsom** [comment]
With workFeatured available was there any discussion about an inverse (e.g. featuredIn), or is the recommendation to use isPartOf? In our case we want to link library items to the exhibitions that they were featured. If inverses are created, consideration of the the sub-properties might be useful too.

**Comment by Dataliberate** [comment]
I do not remember any discussions about an inverse of workFeatured.

As, within knowledge graphs, relationships are bidirectional, inverses are
not always encouraged or absolutely necessary in the vocabulary.    That is
not to minimise the desire to for the expression of relationships as you
describe.   With the current vocabulary I would be inclined to use the
subjectOf <https://pending.schema.org/subjectOf> property.



Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by sfolsom** [comment]
Thanks for the quick response, Richard. 

I understand the "more parts, more problems" and redundancy arguments against inverses, but I also think there's an argument for allowing the one to dereference the Work to find a link to ExhibitionEvent without having to know that there's an RDF blob about the Exhibition in the Work RDF that needs to be interpreted.

There's also the social aspect of inverses. It gives a clear way to implement a particular pattern. In this issue we have now discussed three possible patterns for a simple bit of semantics, not to mention someone could externally create an inverse. FWIW, without the inverse, I'm inclined to use isPartOf in our case. subjectOf isn't quite precise enough; an exhibition could be about a particular book (but not featured), and have other books featured in the Exhibition.
