### ISSUE TITLE
http://schema.org/VisualArtwork: style/schoolings

### ISSUE THREAD

**Issue by Mailis** [schemaorg/schemaorg#1372]
There are many beliefs/styles/fashions what is an artwork. If someone wants to search for particular style, e.g. "french painting school" or "modern art" - there should be a term in the ontology for the style also.

**Comment by rvguha** [comment]
Same thing applies to other kinds of art, like music. We should consider
sharing vocabulary. And some might consider cooking/food an art form :)

guha

**Comment by RichardWallis** [comment]
I am tempted to suggest using the [category](http://schema.org/category) property for this - "modern art category, heavy rock music category, etc.) 

Except however currently it seems to have a  Product/Service focus.

"_consider cooking/food an art form_"?  Not when I do it! ;-)

**Comment by gmackenz** [comment]
I wouldn't call 'modern art' or 'French painting school' a style, maybe
more like a category, they are usually considered a classification of
specific movement or period of time/place for visual artworks. As for music
as style or category such as for 'heavy metal' I would assume it would best
match with the existing genre property for CreativeWork and MusicGroup.

I agree the current category property is really product focused. Wikidata
(and Freebase before that) used Movement
<https://www.wikidata.org/wiki/Property:P135>.




Gordon Mackenzie |  Schema Wrangler (Ontologist) |  gmackenz@google.com |

**Comment by Mailis** [comment]
yes, I was meaning movement.

**Comment by rvguha** [comment]
movement sounds too ambiguous. We will need a more self explanatory term.

guha

**Comment by gmackenz** [comment]
Art Movement (sometimes conflated with an Art Period) is the preferred term for the visual art as there identifiable time-related tendency or style in art created by a group of artist often associated with a goal or philosophy. Kanō school, Impressionism, Pop Art are classic examples of a distinct art movements. Tends to be used primarily 19th century to today.

Before the 19th century, Art Period is often used more than Art Movement in how how visual arts are usually classified—by specific time periods of an identifiably specific art form (that may or may not have an identified goal or philosophy associated with itself). Examples: Ancient Egyptian art, Hellenistic period, Baroque, Mannerism, etc.

**Comment by pasqLisena** [comment]
I am reading your examples and most of them (_Baroque_, _Heavy Rock_, _Modern Art_) could fall in the [genre property](http://schema.org/genre) of CreativeWork.
Moreover, the example in the website for genre is _Late Renaissance_, which can also be considered a school/movement.

**Comment by RichardWallis** [comment]
Are we saying that [genre](http://schema.org/genre), perhaps with a few more examples would satisfy the need here?  

Would it be applicable to food? - I think so

**Comment by thadguidry** [comment]
@Mailis Schema.org does not necessarily have to have a term for every possible subproperty in Art.
You can always use additionalType to fill in gaps that Schema.org has for long tail domains such as Art.

Having said that...
Movement(new), Periods(new), Culture (new), and Manufactory (utilize genre), Geography (where found, sometimes overlaps with Culture) are sometimes used by curators.
I've sent a quick request to a friend at the The Met to ask for their schema...just as a double-check.

http://www.metmuseum.org/exhibitions/view?exhibitionId=%7b118765df-ee1c-4f92-9606-27916c0763ab%7d&amp;oid=197733

http://www.metmuseum.org/exhibitions/view?exhibitionId=%7b118765df-ee1c-4f92-9606-27916c0763ab%7d&amp;oid=70541

http://www.metmuseum.org/exhibitions/view?exhibitionId=%7b118765df-ee1c-4f92-9606-27916c0763ab%7d&amp;oid=451008
