### ISSUE TITLE
Restaurant health inspections: Review? Report? Article?

### ISSUE THREAD

**Issue by dogweather** [schemaorg/schemaorg#1373]
Hi,

I build open-government-data sites with content like this: https://eaternet.io/us/ca/sf/the-stinking-rose/443.

I'd really like to use (restaurant) Review for it, because so much of the metadata and typical presentation in search engine results could apply. But I'm not sure that these inspections are in the spirit of review, and so may not be appropriate.

I'd appreciate any guidance!

**Comment by rvguha** [comment]
This would be awesome! I think they are very much in the spirit of the
review, where the reviewer is the health department.

guha

**Comment by dogweather** [comment]
> the reviewer is the health department

Thanks; that's exactly what I'm thinking. I have all the information about each health department and could easily populate lots of the review attributes.

An alternate possibility is to propose a new review subtype, e.g. `inspection`. So I'm taking the temperature here to see how people feel this should go.

**Comment by rvguha** [comment]
SanitationInspection (or whatever the full name is), would be a good
subclass of Review.

guha

**Comment by vholland** [comment]
+1 to a SanitationInspection type to differentiate that it is not a Review based on opinion, but on health guidelines.

**Comment by dogweather** [comment]
I'm wondering if it should be more generic, i.e. as Inspection, because I'm considering also publishing fire safety inspections. (And hopefully others are too.) Every restaurant (and many other public businesses) are inspected perdiocally by the fire department in many countries. 

I think this will serve a good public purpose. E.g., I spoke to our fire chief and she told me that there's a wide range of findings in the buildings they inspect, and there are some she won't go in, even though they're able to remain open to the public.

**Comment by rvguha** [comment]
Are these published? Would be good to see an example

**Comment by dogweather** [comment]
@rvguha No, I've just been doing the initial research on fire and safety inspections, and how to get the data.

**Comment by thadguidry** [comment]
@rvguha its public data when done by a government official, or a contractor fulfilling a government contract.  There are also federal Right-To-Know laws around hazardous materials, etc.  Getting the data for fire and safety inspections is sometimes fairly easy with a request to the city...some keep very good aggregate records, some do not and are individualized.  ex. https://www.columbus.gov/public-safety/fire/inspections/Permits-and-Records-Office/

**Comment by RichardWallis** [comment]
This looks like a good proposal to extend reviews/rating types into the area of official inspection reporting.  

I would support more generic type names, not only so that they can cover other inspection areas such as fire safety etc. but also to avoid localised confusion.  The term SanitationInspection would have no meaning in the UK for example.

Whilst looking at official/government reviews/inspection it could also be useful to include official ratings.

In the UK we have a government organisation - The Food Standards Agency - which inspects and rates restaurants and food related businesses, giving them a rating 0-5 for which they display a relevant sign in the window of the business.  The data is openly available.

Here for example is a listing of ratings <http://ratings.food.gov.uk/enhanced-search/en-GB/%5E/Evesham/Relevance/0/%5E/EqualAll/0/1/10> for businesses local to me, including inspection dates etc.

A great candidate use-case for this type of information.

**Comment by thadguidry** [comment]
@RichardWallis is the food still tasty at a 0 rating ?  have you dare tried ? :)

**Comment by dogweather** [comment]
@RichardWallis
> is the food still tasty at a 0 rating ? have you dare tried ?

I think we all have; we just never knew it. 😷

**Comment by danbri** [comment]
+1 for doing this, and building it around Review.

BTW I've been meaning to try the Stinking Rose, is it any good? :)

**Comment by dogweather** [comment]
@RichardWallis 

> UK Food Standards Agency . . .

Yes! The UK has excellent data, and they're top on my todo list.

Denmark is another country that's a role model, with the Smiley System, e.g.: http://www.findsmiley.dk/130223 — also a great use case.

![screen-shot-2016-04-04-at-08-27-56](https://cloud.githubusercontent.com/assets/150670/18532274/ff59d336-7a8f-11e6-8517-4c29ca646983.png)

**Comment by dogweather** [comment]
@danbri I'm new to the schema.org process, but I'm down for jumping in with this.

**Comment by rvguha** [comment]
Where are we on this?

guha

**Comment by dogweather** [comment]
@rvguha I've finished a first pass at implementing the inspection markup simply as a Review. Here's [a gist of the json](https://gist.github.com/dogweather/f5d97445ddca95062368a5e1f7efdcee) for a [live page](https://eaternet.io/us/ca/sf/the-stinking-rose/443).

Today I'll read the docs for submitting a proposal and get the ball rolling.

**Comment by rvguha** [comment]
I think it might be a good idea to have a subclass of Review for Health and
Safety Inspection reports. Not sure what the right name should be, but that
would make things clear

guha

**Comment by dogweather** [comment]
@rvguha I agree, a subclass makes sense because an inspection can be understood as a specific kind-of review.
