### ISSUE TITLE
How to create a third party schema?

### ISSUE THREAD

**Issue by greysondn** [schemaorg/schemaorg#1378]
The documentation is unclear. I'd split this between "community question" and "possible documentation problem".

As a trite example, I have a roleplaying site and wish to extend Person to Character (or my own variant), which would have species and also preferences for RP. As a step beyond this, perhaps I also want to embed someone's D&D character character sheet or tag it. Whatever.

So.

[Documentation](http://schema.org/docs/extension.html) reads:

> Sometimes there might be a need for a third party (such as an app developer) to create extensions specific to their application. For example, Pinterest might want to extend the schema.org concept of ‘Sharing’ with ‘Pinning’. In such a case, they can create schema.pinterest.com and put up their extensions, specifying how it links with core schema.org. We will refer to these as external extensions.
> 
> There are also cases where a third party might want to host a broadly applicable extension themselves. In such cases, the extension may go through the kind of feedback process that reviewed extensions go through, but can be hosted on the third party's site.

Continues later on in a different heading:

> We would like extension creators to not have to worry about running a website for their extension. Once the extension is approved, they simply upload a file with their extension into a certain directory on github. Changes are made through the same mechanism.
> 
> Since the source code for schema.org is publicly available, we encourage creators of external extensions to use the same application.

However, despite this, there's no clear indication of how to host a schema. Not only this, but I find it doubtful that a niche fetishist community would need mainstream acceptance so much as providing inter-operability and future proofing would make sense. (I have been working on generalizing roleplay preferences into a standardized format, by the way, inspired by none other than F-List and their public API.)

---

Also an aside, and at discretion perhaps suit for a second issue that would be of interest to the larger schema.org community, lack of a species notation makes animals all but impractical for markup. There's a joke that goes here about Harambe and poor representation of his identity, but even when it's down to it I would willingly abuse a race field for that except - taderp - no race field in Person, either.

---

Edit: fix my horizontal rule, was using wrong markdown dialect.

**Comment by Aaranged** [comment]
Couple of notes @greysondn.

First, you don't need to "extend Person to Character" this is already supported.  [Game](http://schema.org/Game) takes the property [character](http://schema.org/character), which has an expected type of [Person ](http://schema.org/Person) or Organization.

So to accomplish what you want to do, the only extending you'd need to do is the addition of an additional property for Person.

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Game",
  "name": "Dungeons & Dragons",
  "character": {
    "@type":"Person",
    "name": "Some Name",
    "species": "Some Species"
  }
}
</script>
```

Regarding extension protocols, without addressing the robustness of the schema.org documentation on this, I do recommend this three-part series from @RichardWallis ([part 1](http://dataliberate.com/2016/02/10/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/), [part 2](http://dataliberate.com/2016/02/25/evolving-schema-org-in-practice-pt2-working-within-the-vocabulary/), [part 3](http://dataliberate.com/2016/03/01/evolving-schema-org-in-practice-pt3-choosing-where-to-extend/)).

**Comment by thadguidry** [comment]
@Aaranged Person != Monster != Jellyfish

**Comment by Aaranged** [comment]
@thadguidry Hmm, yes ... I guess "Person" does in itself denote that the species being described is Homo Sapiens.

**Comment by darobin** [comment]
Limiting `Person` to a given species is a pretty strong decision. There exist volume upon volume of philosophy, sci-fi, politics, and more about the issues surrounding personhood. I would suggest keeping it loose for now; if and when we meet aliens, AIs, sentient lizard overlords, etc. we can revisit the nuances.

I would therefore content that treating a monster as a `Person` is correct, in addition to being quite progressive.

**Comment by gkellogg** [comment]
We discussed this at length several years ago when we were trying to distinguish between fictional and real things. IIRC, we settled on creating a FictionalThing class, which could be mixed in as a type to distinguish it from something that (may be) real. This is necessary not only for People/Characters, but Places (e.g., Middle Earth) and Events. 

Gregg Kellogg

**Comment by Dataliberate** [comment]
Thing > Person

A person (alive, dead, undead, or fictional).

No mention of a specific species!


~Richard

**Comment by thadguidry** [comment]
@Dataliberate pfft.  Not helpful enough :) Then we should not have choosen to use the term "Person". Oh well.  Its history now and all we can do is 'clean up the definition'.  So... how to clean this up and not be so limiting in our definition ?  Or do we keep Person as is and simply create a new type ?  I want my talking SpongeBob Squarepants not to be typed as a Person during roleplaying.

My suggestion for a better definition to clean up to:
"Person in schema.org means any type of being or species (alive, dead, undead, fictional, monster). This is not limited to just Homo Sapiens, entities in the human race"

Do we limit ourselves here to 'a biological entity' ?  or not ?  Talking Jellyfish ? how to handle ?

See the big can of worms that you Nice Semantic Folks (me included) drove me into opening ? :)

**Comment by greysondn** [comment]
I will wait until the discussion coalesces into a given state on species, but I would like to point out that even if "Person" only meant "human" or "Homo Sapiens", it still is often of interest - both from a human rights perspective and historic anthropology perspective - to know the race or identified race of a person. That field's absence seems like an oversight, bare minimum.

And I could dive into other problems with Person besides but I had zero intention of being obtuse.

Not addressed was:

> and also preferences for RP

While I appreciate people making light of the situation, the upshot of providing a markup for such data is that to retrieve a person's data all someone has to do is scrape the page, presumably. Not all RP is of a sexual nature but... Well, by storage volume, the internet *IS* mostly porn, you know.

**Comment by RichardWallis** [comment]
Sorry if a bit Friday Afternoon flippancy entered the conversation - but it is Friday. ;-)

More seriously I remember raising the FictionalType ( A new type with potential references back to the CreativeWork it came from) issue many months ago and IIRC there was general agreement on the need but a lack of enthusiasm on the practice as MTEs were not being pushed as much.  IIRC also there was a more restricted suggestion of a boolean property for Thing - fictionalThing.

As to the current definition, checking dictionaries for inspiration there were many references to _human being_ and _homo sapiens_ - I did find this however:  "_Philosophy_. a self-conscious or rational being."

**Comment by greysondn** [comment]
> Sorry if a bit Friday Afternoon flippancy entered the conversation - but it is Friday. ;-)

I'm not certain who you're directing this at or if it is directed at anyone at particular at all but... for what it's worth, the humor doesn't bother me at all. I'm a very morose person but I don't fault people for being high-spirited ;D

**Comment by thadguidry** [comment]
@greysondn Richard's just being cool :)  In case anyone gets high-spirited with him as he slowly begins to drink his spirits this afternoon :) (or very shortly)

@greysondn We all understand the issue very well.  We'll get you sorted out, one way or another.  Most of all of us have played roleplaying games and understand your needs very, very well.  We're just trying to address high-level issues that we talked about in the past that directly impact your issue on how to best frame up 'fictional' things.

@greysondn To address your issue , we have the Property of https://schema.org/character ... and what you and many others need and have requested is a Type for that also... perhaps just https://schema.org/Character  (not existing yet, but looks like you and others are asking for this in this issue) and that would have some nice common properties underneath it and that could be a sub-type of our FictionalThing past proposal new Type.

All - I would be +1 for a new type 'FictionalThing'
All - I would be +1 for a new Type 'Character'  (it can be a sub-type of FictionalThing to start out with)

**Comment by Aaranged** [comment]
> All - I would be +1 for a new type 'FictionalThing'
> All - I would be +1 for a new Type 'Character' (it can be a sub-type of FictionalThing to start out with)

My +1s for both of these as well.

**Comment by Dataliberate** [comment]
I've found out my original proposal for a FictionalThing type from February 2013  - doesn't time fly by when you are having fun!


> https://www.w3.org/wiki/WebSchemas/FictionalThing


You can see from the language it was from a time when MTEs were new and a bit of a mystery to some.   

Nevertheless it covers many aspects of how fictional things might be described. 

~Richard

**Comment by danbri** [comment]
Lets not get caught up in the specifics of the example. Using a type like FictionalThing is difficult approach, since fact and fiction are inter-twined in the literary world. Historical figures - realistically or imaginatively altered - very often play a role in fiction (e.g. but not limited to SciFi). It is not a coincidence that the FOAF vocabulary also has a very broad definition for [foaf:Person](http://xmlns.com/foaf/spec/#term_Person), "The Person class represents people. Something is a Person if it is a person. We don't nitpic about whether they're alive, dead, real, or imaginary.". Eventually many types have to be grounded in social practice, natural language etc.

Regarding extensions, I think we are at a relatively early state and the looseness in the documentation reflects that. As far as I know, no major search engine yet has documented any features (or ability to consume) external-to-schema.org extensions (beyond their respective own, at least). I expect this situation will evolve over time. There are also technological aspects which need further exploration, in particular the possibilities and challenges presented by JSON-LD's context file.  Please take a look at https://github.com/schemaorg/schemaorg/issues/1186 for some examples that explore this via Wikidata-based-extensions as a usecase. For the most mature and well documented external extension, see GS1's work: http://gs1.org/voc/

**Comment by danbri** [comment]
The general issue with extension documentation (hosted, external, or change proposal) is now noted under broad themes in #1.
