### ISSUE TITLE
Deprecate the entire UserInteraction sub-tree in favor of Action

### ISSUE THREAD

**Issue by elf-pavlik** [schemaorg/schemaorg#138]
http://schema.org/UserInteraction

[search results for UserInteraction in public-vocabs archives](http://www.w3.org/Search/Mail/Public/search?keywords=UserInteraction&hdr-1-name=subject&hdr-1-query=&index-grp=Public_FULL&index-type=t&type-index=public-vocabs) *19 messages*

I raised while ago an issue about *UserInteraction* type and its subtypes. They seem like a left over from pre-Action work: http://schema.org/UserInteraction

>As Dan said earlier, the plan here is to deprecate UserInteraction and its
subtree in favor of actions. We believe this is a much more scalable
sub-tree with a more solid foundation for extensions.

>Dan: is there a process for deprecating sub-trees?

Sam Goto *http://lists.w3.org/Archives/Public/public-vocabs/2013Nov/0198.html*

Earlier today I confused it with #137

**Comment by danbri** [comment]
Yes we should do this ASAP.

**Comment by danbri** [comment]
Migrating in from https://www.w3.org/2011/webschema/track/issues/32

        From: ☮ elf Pavlik ☮ <perpetual-tripper@wwelves.org> 
        Date: Mon, 25 Nov 2013 10:17:41 +0100
        Message-ID: <529315B5.6030301@wwelves.org> 
        To: "public-vocabs@w3.org" <public-vocabs@w3.org> 

        In http://lists.w3.org/Archives/Public/public-vocabs/2013Nov/0194.html

        """
        I noticed some duplication (which causes confusion at least for me) between:
        *Thing > Event > UserInteraction* - "A user interacting with a page" 
        http://schema.org/UserInteraction
        vs.
        *Thing > Action > InteractAction* - "The act of interacting with another 
        person or organization." - http://schema.org/InteractAction

        including many specific types like:
        *> UserInteraction > UserCheckins* - "User interaction: Check-in at a 
        place."" - http://schema.org/UserCheckins
        vs.
        *> InteractAction > CommunicateAction > CheckInAction* - "The act of an 
        agent communicating (service provider, social media, etc) their arrival 
        by registering/confirming for a previously reserved service (e.g. flight 
        check in) or at a place (e.g. hotel), possibly resulting in a result 
        (boarding pass, etc)." - http://schema.org/CheckInAction"""

**Comment by sesuncedu** [comment]
@danbri and Donald Davidson understand why this hurts my head ;)

Given that Event in schema has mostly narrowed to "things to do", purging
the schema:Event hierarchy of Davidsonian Events might make sense.

There are a relatively small number of these ; Delivery Event seems to be
one ; PublicationEvent is somewhat marginal, though its subclasses are
clearly within the narrower meaning.

Also,  checking in is *not* an antagonym of checking out- an antagonym is
more commonly called an auto-antonym.
You might want to remove the word then replace it.  With something else.

http://en.m.wikipedia.org/wiki/Auto-antonym

**Comment by danbri** [comment]
re antagonym -> https://github.com/schemaorg/schemaorg/issues/247

re events (and actions) we might consider whether an upcoming 'things to do' opportunity (e.g. a gig with tickets, or an Action with potentialAction) should be considered to be the selfsame thing once it has occurred. If not, by what relationship are they linked, and how do we describe events in the past? In the action case, a potentialAction description (e.g. watch HG Wells Things To Come on archive.org, https://archive.org/details/things_to_come_ipod_version ) you might watch it twice). And if a potential event never gets eventualized, is it still a thing?

**Comment by elf-pavlik** [comment]
```shell
grep User schema.rdfa | grep Class
```
I understand that all types will have *schema:supersededBy* statements added

what about domain/rangeIncludes, they will simply get removed?
```shell
grep User schema.rdfa | grep Includes
```

**Comment by danbri** [comment]
I believe we have rough consensus on marking UserInteraction, its subtypes, and interactionCount as deprecated.  Subtypes included would be:

UserBlocks
UserCheckins
UserComments
UserDownloads
UserLikes
UserPageVisits
UserPlays
UserPlusOnes
UserTweets

To implement this we'll need to add a small amount of infrastructure for flagging terms as deprecated/removed/archaic (pick your metaphor...).

/cc @vholland

**Comment by scor** [comment]
:+1:  Having reported problems with UserInteraction pretty much from day 1, I like this idea a lot.

**Comment by danbri** [comment]
Ok, this is done via textual descriptions for now. Will have a more schema-visible / site-navigable mechanism for this later. #465 tracks that.
