### ISSUE TITLE
rdflib not loading in Windows

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1384]
Raised via a Stackoverflow qustion: http://stackoverflow.com/q/39776881/1306933?sem=2 <cid:part1.F13E5ACF.B4AB0FE6@psynchronous.com>

**Comment by kevinawilson** [comment]
As the person who wrote the StackOverflow question, I wanted to add a bit of information.

I've now uploaded the project to the Google App Engine Cloud Service. The deployment was successful, although I received a lot of "Could not guess mimetype" warnings. The application is at [http://sdo-addiction.appspot.com]. When I run the app, I receive a 500 error, and the GAE console shows an RDFa parsing error.

**Comment by Dataliberate** [comment]
Great, thanks for the extra helpful info. 

Do not be concerned with guessing mime-type errors, that is normal at the moment. 

~Richard

**Comment by kevinawilson** [comment]
I posted a proposal for adding addiction-related vocabulary to the 
schema.org ontology yesterday. It can be found at the GitHub site, Issue 
#1402 <https://github.com/schemaorg/schemaorg/issues/1402>. I would 
appreciate any feedback participants could offer.

-- 
Kevin A. Wilson
Writer
Psynchronous Communications



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Dataliberate** [comment]
Hi Kevin,

As to the loading under Windows problem, I hope to get towards a solution
in the coming week - I have been embedded in other areas of the code
recently and attending the DCMI conference.

If get chance, I’ll also give your proposal the more than a skim read that
it deserves.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by RichardWallis** [comment]
Fixed by commit df0d380947fadf62dcfe29436c1c7c69844107c3

**Comment by RichardWallis** [comment]
Closed in favour of (#1412)
