### ISSUE TITLE
How to record a 11179 data element (aka. variable)?

### ISSUE THREAD

**Issue by LegoStormtroopr** [schemaorg/schemaorg#1386]
The new dataset extension, which allows for the capture of recorded variables allows for text or a url, but there is no way to describe the definition for an individual variable? This is required for being compatible with SKOs/11179/etc. to help official statistical agencies and open data groups share context for their datasets.

https://developers.google.com/search/docs/data-types/datasets

In JSON-LD format being able to record the following would be useful:

```
{
  "@context": "http://schema.org/",
  "@type": "dataElement",
  "name": "Person-Age, Whole years",
  "definition": "The age in whole years of a human being",
  "class": "link_to_a_schema_org_class",
  "property": "link_to_a_schema_org_property",
  "enumeration": "link_to_a_schema_org_enumeration",
}

```

**Comment by thadguidry** [comment]
@LegoStormtroopr You should be able to describe the definition of an individual variable (the key here is to think of a variable as a property itself I think. (property=value, key=value ... variable=value) by using https://schema.org/PropertyValue and https://schema.org/propertyID and a little bit of this just in case https://schema.org/PropertyValueSpecification  ?

**Comment by LegoStormtroopr** [comment]
Hmmm... `PropertyValueSpecification` looks like the thing.

Is there anyway to add an arbitrary link? Say between a `PropertyValueSpecification` and a `Class` and a `Property`?

Say:

```
{
  "@context": "http://schema.org/",
  "@type": "PropertyValueSpecification",
  "name": "Person-Age, Whole years",
  "definition": "The age in whole years of a human being",
  "class": "example.com/rdfs/person",
  "property": "example.com/rdfs/age",
}

```

where the class and property are is:

``` Lets say the id is 'example.com/rdfs/person
{
  "@context": "http://schema.org/",
  "@type": "Class",
  "name": "Person",
  "definition": "A human being",
}

Again, the id is example.com/rdfs/age
{
  "@context": "http://schema.org/",
  "@type": "Property",
  "name": "Age",
  "definition": "The age of an entity",
}
```

Naturally, these are simple example and similar to things in FOAF and schema, but I'm looking at capturing the variable that records a labour force status or educational attainment, etc...

**Comment by mfhepp** [comment]
From the top of my head, schema:additionalProperty is the way to go. We might need to expand its domain (as I had initially proposed).
