### ISSUE TITLE
Provide a mechanism equivalent to Atom's "<complete>" element for indicating completeness of feeds

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1397]
http://schema.org/DataFeed does not currently distinguish between a feed that contains all current items, vs those that don't. The Atom format defines such a notion via a 'complete' element.

This information would be useful for interpreting whether entries missing from the feed should be treated as no longer existing (if it's a complete feed), or simply not part of this partial representation of the feed (if it's not a complete feed).

**Proposal**

Add a simple subtype of DataFeed called CompleteDataFeed. Definition along these lines:

> CompleteDataFeed: 
> A CompleteDataFeed is a DataFeed whose standard representation includes content for every item currently in the feed. 
> 
> This is the equivalent of Atom's <complete> element as defined by Feed Paging and Archiving (RFC 5005), https://tools.ietf.org/html/rfc5005
> 
> For example (and as defined for Atom), when using data from a feed that represents a collection of items that varies over time (e.g. "Top Twenty Records") there is no need to have newer entries mixed in alongside older, obsolete entries. By marking this feed as a CompleteDataFeed, old entries can be safely discarded when the feed is refreshed, since we can assume the feed has provided descriptions for all current items.

**Comment by danbri** [comment]
Drafted in pending for review: http://pending.webschemas.org/CompleteDataFeed

**Comment by thadguidry** [comment]
@danbri are you fairly confident that this is better as a subtype rather than a property on DataFeed ?  Pros/Cons ?

**Comment by beccahughes** [comment]
`CompleteDataFeed` has been pending for a few years, is this something that is going to become part of schema.org?
