### ISSUE TITLE
Wire up schema.org production site for cookie-based A-B testing.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1399]
@RichardWallis is taking a look. We have had some hiccups in the past because schema.org itself is served from a slightly different Google appengine environment, this should give us a way of testing things properly when making official releases.

See also
- http://stackoverflow.com/questions/15032531/traffic-splitting-by-ip-address-on-google-app-engine
- https://cloud.google.com/appengine/docs/python/splitting-traffic?csw=1

**Comment by rvguha** [comment]
This is great!

guha
