### ISSUE TITLE
Description of Rating is inadequate

### ISSUE THREAD

**Issue by awfuchs** [schemaorg/schemaorg#140]
http://schema.org/Rating

At http://schema.org/Rating, the description says "The rating of the video." However, Rating can apply to many non-video things including the microwave oven in the example on that same page.

**Comment by danbri** [comment]
Should Rating be a CreativeWork?

**Comment by thadguidry** [comment]
+1 for Rating being a CreativeWork - #206 has my examples in it and we have 2 stakeholder agreement.

**Comment by danbri** [comment]
It looks from http://schema.org/Rating as if we already addressed @awfuchs 's specific issue - I don't see "of the video" in that page any more. I suggest this issue can be closed in favour of the more active #206.

**Comment by danbri** [comment]
Closing, "A rating is an evaluation on a numeric scale, such as 1 to 5 stars" is ok. Thanks!
