### ISSUE TITLE
vehicles > boats

### ISSUE THREAD

**Issue by h-e-r-b-e-r-t** [schemaorg/schemaorg#1405]
What is the recent state of the **vehicles** > **boats** proposal. I've only found archived entry: https://www.w3.org/wiki/WebSchemas/Vehicles:
_This is an archived WebSchemas proposal for Vehicles (Cars, Bikes, **Boats**, etc.)_ ....

Need to mark up following properties to JSON-LD:
**speed** | **length** | **width** | **draft** | **capacity** | **seats** | **year of construction** | **dockyard**

**Comment by mfhepp** [comment]
Im my opinion, the current vocabulary covers most needs regarding boats:

Simply use

1. http://schema.org/Vehicle
2. in combination with (via additionalType) http://www.productontology.org/id/Boat or another vessel type from a Wikipedia lemma, like http://www.productontology.org/id/Sailboat
(www.productontology.org currently shows 404s for all of them, but this will be fixed and does not invalidate markup).
3. and http://schema.org/additionalProperty for any more specific properties regarding the vessel. See the examples at the bottom of http://schema.org/PropertyValue for typical patterns.

This should do the trick without any need to change schema.org.

**Comment by h-e-r-b-e-r-t** [comment]
Great, sounds like solving my problem. 
Thank you very much mfhepp!!!
