### ISSUE TITLE
Campground should ideally be under 1 parent type, not 2

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1406]
http://schema.org/Campground

Thing > Place > LocalBusiness > LodgingBusiness > Campground 
Thing > Place > CivicStructure > Campground
[
Thoughts and Discussion from Mailing List Here](https://lists.w3.org/Archives/Public/public-schemaorg/2016Oct/0008.html)

**Comment by chaals** [comment]
@thadguidry [wrote in the email thread](https://lists.w3.org/Archives/Public/public-schemaorg/2016Oct/0014.html) 
>Does anyone feel strongly that there is NO WAY in Schema.org that you could
not distinguish between a commercial campground like KOA (percievably more
expensive, might have more amenities), or a civic or public campground
(perceiveably less expensive and fewer amentities) , if we reduced to only
1 hierarchy level under the existing CivicStructure and removed Campground
from under LodgingBusiness ?

I'm not sure I understand the question, but I don't think the question of whether a campground is a commercial enterprise or a government-sponsored facility is a distinctive feature.

Certainly, the price and level of amenity doesn't depend on who runs it, in the reality I am used to.

As noted earlier, there are useful properties of a LodgingBusiness that are important for campgrounds of most kinds.

**Comment by danbri** [comment]
I agree with @chaals. Public-private is an every-changing spectrum, but the types in these two hierarchies both come with useful properties for this situation.

**Comment by thadguidry** [comment]
@danbri Agreed its every changing, so it needs to be elevated then.  We all agree that a Campground is a Campground.  1 Type.  I don't see the point of having things under multiple hierarchies...I'd rather us not dictate too much and instead push MTE use instead.  This would mean we remove Campground from being also subtyped under CivicStructure.

What properties fall under that Type we control that.  CivicStructure is nearly a bucket type...it currently has only 1 property...openingHours.  And for Campground, openingHours is already handled under LodgingBusiness and even Place with openingHoursSpecification and specialOpeningHoursSpecification.  So there's no need to keep Campground under CivicStructure...we're not saying much at all about a Campground under there...other than loosely categorizing it as some sort of Civic thing.

If you think it is important that folks are able to say that a Campground is a Civic thing....they can do that already with an MTE if need be...but we are dictating that by already subtyping it for them as a CivicStructure and LodgingBusiness, rather than giving them a choice,  How does a computer know that the Campground you describe on your webpage is a Public thing...or a Private thing ?

When something is either/or ... private/public...then a property could handle that...or a new Type could handle that.  **And I prefer properties pushed up to an appropriate level so that many things can make use of that property.**  WIkidata doesn't have Types, just for this reason..so that anything can grab a property and say something useful, but that leads to eventually Typeness with classes, etc as we already see in WIkidata..So I think Schema.org and Freebase have a better approach that affords a more realistic and less confusing view of our world...anyways.  Here's another rub...I think we already loosely categorized Campground as an Accommodation in its definition.

`An accommodation is a place that can accommodate human beings, e.g. a hotel room, a camping pitch, or a meeting room. Many accommodations are for overnight stays, but this is not a mandatory requirement. For more specific types of accommodations not defined in schema.org, one can use additionalType with external vocabularies.`

and in Campground's definition....we mention Accomodation again !
`See also the dedicated document on the use of schema.org for marking up hotels and other forms of accommodations.`

I have my prefered way to fix all this...as we did in Freebase...but I want to understand your thoughts that say..."no Thad, this should not be confusing for developers at all...they just need to do..X"

**Comment by mfhepp** [comment]
ok
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by Dataliberate** [comment]
I kind of agree with @thadguidry <https://github.com/thadguidry> on this.
The only property introduced by including CivicStructure is openingHours
and that is already available via LocalBusiness.

If it is important to make the distinction between public & private, there
is always the MTE option, or if it is *that* important a public/private
boolean property could be added.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw
