### ISSUE TITLE
http://schema.org/owns is ambiguous (or at least vaguely defined)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1407]
http://schema.org/owns

/cc @mfhepp 

Does the owning party own a particular individual product or the product itself?

"I liked the shaver so much, I [bought the company](https://www.youtube.com/watch?v=qf22bddvLnc)", etc. (i.e. Victor Kiam owns both a particular Remington M3 shaver, as well as the entire product line; does he schema:owns both too?).

@mfhepp was the intent here to cover "Kitkat is a Nestle product" (brand?) usecases, or "that's Dan's kitkat"? Or both? I assume more the former. It seems to cover only a subset of possible ownership situation e.g. if a company owns another we use parentOrganization.

**Comment by thadguidry** [comment]
For businesses, there's 2 levels of ownership.
You can own the patent on that Product.
You can own the brand on that Product.
You can own the Product itself (in your warehouse) until you transfer rights through a sale to a customer.

Beyond Products, I think it is also nice to have http://schema.org/owns as a grand property for the OwnershipInfo.  Which affords that any Thing can own any Thing.

@mfhepp I think we just need to clear up the definition of the property to be applicable at the grand scale.? Thoughts?

**Comment by mfhepp** [comment]
@thadguidry 
IMO, the levels of ownership don't matter.
If a business owns a patent, the schema:Product is the *patent*:

    ACME schema:owns[ foo:BogusPatent a schema:Product, foo:Patent].

If a business owns a brand, the schema:Product is the *brand*:

    ACME schema:owns[ foo:ACMEBrand a schema:Product, schema:Brand].

If a business or person owns a particular product instance, the schema:Product is the actual product:

    PeterMiller schema:owns [foo:TVSet123 a schema:IndividualProduct, pto:TV_Set].
Keep in mind that in schema.org/GoodRelations, being a product is just a role notion in the sense that any Thing can become a product by being referenced in a business context.

Essentially, if the range is Product in schema.org, you can always use any entity (but have to make it an MTE so that validators understand that you want to use the entity in a business context).

What you mention are relationships between things, i.e. that a product is based on a patent or that a product is sold under a certain brand (for which you can use the http://schema.org/brand property, like so

    foo:TVSet123  schema:brand foo foo:ACMEBrand.

If you want to understand our motivation behind "owns", see this paper:

Török, László; Hepp, Martin: Towards Portable Shopping Histories: Using GoodRelations to Expose Ownership Information to E-Commerce Sites, in: Proceedings of the 11th Extended Semantic Web Conference (ESWC 2014), May 25-29, 2014, Crete, Greece, Springer LNCS, pp. 691-705.

PDF at http://www.heppnetz.de/files/portable-shopping-histories-eswc2014.pdf

**Comment by mfhepp** [comment]
@danbri 

I hope my statement above answers your question. For a mere brand relationship ("Nestlé owns the Kitkat brand"), you can also use http://schema.org/brand (which is weaker than schema:owns):

    foo:Nestle schema:brand foo:KitkatBrand

schema:owns means legally owning it. In some cases, a legal entity does not own a brand but e.g. licenses it, e.g. in franchising scenarios.

So for corporation-brand relationships, I think schema:brand is more suitable because it does not require an exact understanding of the legal grounds of the brand usage.

I close this issue for now, feel free to reopen.

**Comment by thadguidry** [comment]
@mfhepp Ok...Product is a role.  'nuff said.  And you made one thing very clear to me, so.

Then I know that MANY MANY developers would like to see the definition like so, to clear up mass confusion...
"Products in Schema.org/GoodRelations are just a role notion in the sense that any Thing can become a product by being referenced in a business context.  This property describes a Product (role notion, any Thing) owned by the organization or person"

**Comment by Dataliberate** [comment]
Just to throw another comment into the pot…

It would be useful to add CreativeWork and Place to the rangeIncludes of
‘owns’ - Paintings etc. are usually owned by some person/organisation, some
Mountains are owned.

… or maybe just generalise its range to Thing.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by rvguha** [comment]
I can go for creative work, but I would prefer to leave Mountain out, at
least for now.

Ownership of a creative work is kind of tricky. The beatles own Hey Jude
and I own a CD and these are two very different notions of own.

guha

**Comment by Dataliberate** [comment]
On 28 October 2016 at 15:16, R.V.Guha <notifications@github.com> wrote:

> I can go for creative work, but I would prefer to leave Mountain out, at
> least for now.
>

I agree, although a few Scottish Lairds would disagree ;-)


>
> Ownership of a creative work is kind of tricky. The beatles own Hey Jude
> and I own a CD and these are two very different notions of own.
>

Hey Jude, the work is owned by Sony/ATV
<http://www.eonline.com/uk/news/132418/who-owns-the-beatles-songs-now-that-m-j-s-dead>.
The physical CD  (an MTE of a CreativeWork subtype and IndividualProduct)
that you purchased is owned by you.

~Richard.

**Comment by danbri** [comment]
@rvguha writes

> Ownership of a creative work is kind of tricky. The beatles own Hey Jude and I own a CD and these are two very different notions of own.

This pretty closely parallels the issue I flagged originally, which is that this term's documentation doesn't clarify the level of ownership. We have chosen, so far, not to impose a unified model on these similar distinctions w.r.t. CreativeWork vs Product, even though we accept that a single entity might reasonably carry types from both hierarchies. 

I might own a signed copy of Harry Potter and the Philosopher's Stone: (Illustrated Edition, Hardback), signed by J.K.Rowling; she owns the work itself. Modeled via CreativeWork, the thing that I 'owns' has an exampleOfWork relation to the thing that J.K.Rowling 'owns'. We could use 'Book' for either. My understanding is that viewed from the product perspective, those same two entities would respectively be instances of IndividualProduct and Product types.

Some CreativeWork subtypes e.g. http://schema.org/MusicRelease are closer to the notion of abstract works, others are more instantiations, e.g. a MusicRelease can have an 'encoding' which is a MediaObject.

**Comment by thadguidry** [comment]
@danbri No, you would not use 'Book' for either.  You jumped to far there.  That's the clear distinction that @mfhepp made me aware of.  We tend to lump those notions together in our human brains....but...You own the 'Book', but J.K. Rowing owns the CreativeWork.

Anyways, back to the "level" part...the heart of this issue as @danbri says.

The definition as-is does cover Product use really well.  So the problem part is the CreativeWorks, Patents, etc...that don't typically fall into the Product notion until they are wrapped with an MTE...and that's ugly for this ownership level problem, in my mind.

So, I vote not to use MTE's to disintangle ownership levels.  Its going to be messy here and already there is backlash with developers on this sticky point of product rights / creative works / work rights.  We handle Product side well, as @mfhepp showed to us...but Creative side and Rights...I think not so well,

We need something....else...somewhere...so we are not stuck in Product land all the time.

http://schema.org/Organization has brand...it expects a Brand or Organization....now...make the leap of Ownership levels on Brand or Organization..... uh oh.... you can only currently do so on Organization with its owns property.  But Brand....its left in the dark....no owns property.

A simple fix, as I look at things, is that http://schema.org/OwnershipInfo typeOfGood should also expect a CreativeWork, and not just Product or Service.

We are making it to hard for developers to have to plugin the Product hierarchy just to get to a CreativeWork, even if MTE's were used.  Let's fix those first.

1. Add owns property to https://schema.org/Brand
2. typeOfGood should also allow a CreativeWork, not just Product or Service.  (by saying that someone owns a CreativeWork, we say that they own the creative rights.
2a.  Or we create a ownsRights property.

I am ok with 2 or 2a... but giving us a choice.  I definitely want to see 1 happen.

**Comment by Dataliberate** [comment]
Adding owns property to Brand makes sense. 

My suggestion about adding CreativeWork to the range of owns was not so much about the ownership of conceptual works, although that would be potentially useful, but more enabling the description of ownership of subtypes such as Sculpture, Painting, Dataset, etc. 

~Richard

**Comment by mfhepp** [comment]
I think

1. We do not need to change the schema:owns property (maybe clarify its definition); the notion of the ownership *relationship* is pretty similar across different types of objects.

See e.g. https://en.wikipedia.org/wiki/Ownership
https://en.wikipedia.org/wiki/Property_rights_(economics)

Ownership is typicall understood as the most comprehensive set of rights on a property, like

a) "usus" - the right to use the good,
b) "usus fructus" - the right to keep the fruits of the good (and to carry/cover losses and responsibilities),
c) "abusus" - the right to modify the good
d) "ius abutendi" - the right to abuse, destroy, consume, or transfer ownership on, the good; see https://en.wikipedia.org/wiki/Ius_abutendi

Note that ownership (see above) and possession (the state of having actualy control over a good) are fundamentally different animals. You can own a thing without possessing it and you can possess it whithout owning it.

The exact bundle of rights associated with ownership might be constrained by the law (e.g. you cannot own certain things, like fellow humans; or ownership on a piece of creative work as an originator will e.g. be time-limited in most countries, or certain rights on private property might be granted to the general public (e.g. the right to access private land in the wilderness or in forests for recreational purposes).

But fundamentally, owning a brand, a company, a patent, or a car is the same type of relationship between an agent (Guha: sorry for the term ;-) and a tangible or intangible thing.

2. We indeed have a fundamental challenge with schema:Product.
In the original GoodRelations model, a product is essentially any Thing on which you can offer to grant some rights (not only ownership, but also temporary access etc.). So in purity, all properties that have schema:Product as their range should allow schema:Thing there.

schema:Product has now been a class that holds many properties that make perfect sense for products in the narrow meaning of industrially produced commodities, but which are not applicable to other forms of products.

We can either 

a) recommend the use of MTEs and make clear that MTEs are the way to go when you want to use a Thing in a product fashion, like Book, CreativeWorks, Company; or
or
b) add popular such classes to the range of all relevant properties.

or both.

a) will be more flexible, generic, and easier to maintain while b) will give better hints to Web developers.

But yes, Google Inc. schema:owns the Google brand and the Google logo same as any other part of its inventory.

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by mfhepp** [comment]
@rvguha

"Ownership of a creative work is kind of tricky. The beatles own Hey Jude and I own a CD and these are two very different notions of own."

No. What differs is not the relationship type but the nature and identity of the object (or subject, however direction you want to look at it) of ownership.

The Beatles or their heirs own the CreativeWorks "Hey Jude" in a very similar fashion in which you own a CD with the song on it. You can smash the CD, they can give up their rights and declare it public domain. You can sell the CD, they can transfer their rights to a licensee. Etc.

The confusion comes from the fact that there are relationships between the objects of ownership, like between the CD and the performance and the abstract piece of works.
