### ISSUE TITLE
How to define schema.org using schema.org

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#1408]
Using JSON-LD, how would a developer mark-up the description of schema.org?
For example, is schema.org a @Dataset?
How to define the number of @Property items in the mark-up?
We'll use the answer as a general purpose way to mark-up an ontology.

/jay gray

**Comment by thadguidry** [comment]
Schema.org does provide "data"... but it IS A (a Type of, a Class of) Vocabulary.
We don't have a Vocabulary Type currently.  Probably should create one however ! Why didn't we think of that ?!?

For current purposes you can say that:
Schema.org IS A [Organization](http://schema.org/Organization) that PRODUCES a [Product](http://schema.org/Product)...which is the Schema.org Vocabulary which is represented in one form AS A [RDFa document](https://github.com/schemaorg/schemaorg/blob/sdo-callisto/data/schema.rdfa)

**Comment by jaygray0919** [comment]
One test of a 'computer language' is whether a language can be used to 'write' (declare) itself. I use 'C' as an examples as I grew up on C; C is written in C.

It seems to me that there should be a @Thing which is used to declare an 'ontology'. An instance of an ontology is schema.org. Then @Class and @Property can be used to substantiate that @Thing. I have seen the @danbri JSON-LD document that defines all classes and properties (The RDF in JSON-LD syntax). IMHO, the only thing missing is the type of @Thing to which the classes and properties are assigned.

EDAM and IAO both have an information class that is an ontology. Perhaps we could align with those examples (in a similar manner to the wikidata alignment).

**Comment by danbri** [comment]
Schema.org prioritizes the description of common real life situations, particularly w.r.t. the kind of stuff that is widely present in the Web and discovery needs of mainstream users. Hence focus on events, people, reviews, recipes etc. While we do have terms for describing datasets, as well as RDFS-like vocabulary (domainIncludes etc.) in schema.org, we don't have enough to fully describe a relatively unusual thing/situation such as schema.org itself. This is quite reasonable given our focus; I don't think the analogy with self-hosting programming languages quite goes through here. 

Most of the specifics of defining Schema.org is accomplished using W3C RDFS vocabulary. For the specialized audience for that file, this is just fine; the usability considerations w.r.t. having a simple vocabulary that led to schema.org are more about relatively non-technical publishers. We've only diverged from RDFS when there was a need, e.g. rdfs:domain and rdfs:range didn't fit our project very well.

Given that we have ~500 open issues I will go ahead and close this one, but happy to continue to chat here...

/cc @rvguha

**Comment by danbri** [comment]
BTW the "triples" representation of schema.org can be found in various formats in our developers page, here's the latest version of that: http://webschemas.org/docs/developers.html

**Comment by jaygray0919** [comment]
TY for link - didn't know about it. Understand your point about 'real life' situations. NP closing the issue.

However, we are using S.O for situations complementary to core S.O. In order to do our work, we 'import' several ontologies into an S.O @Class and @Property structure. That enables us to make statements about a specific item that is a @Thing but not one of the S.O 'things.' That process works for items because the new @Class structure is 'just another structure.' But we have no method to express the provenance of the new structure - i.e. what ontology did we import to create the new structure. Hence my questions.

For now, we're just going to declare that the imported ontology is a @Dataset. Then we can attach provenance to the dataset.

/jay
