### ISSUE TITLE
clarify that schema.org/distribution doesn't mean statistical distribution 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1409]
We have this because W3C DCAT has https://www.w3.org/ns/dcat#distribution ... 

Let's add a few words making clear which sense of 'distribution' is intended as this can be confusing esp. with statistical datasets.

**Comment by rvguha** [comment]
We might consider changing the name ...

**Comment by danbri** [comment]
There's a workshop coming up focussed on W3C DCAT (which our terms are based on)  https://www.w3.org/2016/11/sdsvoc/ - I'll be there, will see if there's wider interest in renaming. I know some publishers are somewhat frustrated that they now have to choose between DCAT and Schema.org vocabulary, and there are efforts like https://joinup.ec.europa.eu/asset/dcat_application_profile/description which it would be good to stay in sync with.

**Comment by sballesteros** [comment]
If the name is changed, reusing `encoding` could be good (see https://github.com/schemaorg/schemaorg/issues/1190 for some previous discussions).

**Comment by rvguha** [comment]
We should suggest to the WG that they use a different name. Using the term
'distribution' in the context of statistical datasets to mean something
different from the sense in which it is used in statistics is asking for
confusion.

guha
