### ISSUE TITLE
JSON-LD context file should declare gs1 vocab prefix

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1411]
It would be great if anyone could write e.g.  gs1voc:AllergenTypeCode-WHEAT or somesuch without having to declare http://gs1.org/voc explicitly. To do this we'd need to add their preferred prefixes to our context (current status viewable at http://webschemas.org/docs/jsonldcontext.json), check for conflicts and also maybe liaise with W3C team about keeping, or not keeping, similar W3C lists in sync.

Similar considerations for https://github.com/schemaorg/schemaorg/issues/1390

There's also a strand of consideration around using multiple context files (or not) or a context that imports both. We don't really have a best practice yet. It might be good also to request schema: prefix in other popular context files, for similar reasons.

**Comment by jaygray0919** [comment]
We have re-formulated a subset of the GS1 OWL declarations as an S.O @Class @Property hierarchy?
Is that what you are looking for?

/jay
