### ISSUE TITLE
/isLiveBroadcast property has a typo (is -> if)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1417]
http://schema.org/isLiveBroadcast "True is the broadcast is of a live event."

This should be "if the...".

For sake of showing off a Pull Request -based workflow, let's fix this the complicated way.

/cc @gmackenz

**Comment by geirfp** [comment]
The typo is still there in the public page. Looks like the fix was not included in any pull request...?

**Comment by danbri** [comment]
Thanks @geirfp - looks like we lost our way on that one! I've fixed it directly.
