### ISSUE TITLE
Add broker to the domain of Service

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#1420]
I believe the property [broker](http://schema.org/broker) would be a valid property for [Service](http://schema.org/Service) (broker is currently available on [Invoice](http://schema.org/Invoice), [Order](http://schema.org/Order), & [Reservation](http://schema.org/Reservation)).

**Comment by danbri** [comment]
Sounds good, let's do it.

**Comment by gmackenz** [comment]
Pushed to core for next release.
