### ISSUE TITLE
Mark up a product and list all available sizes as offers under aggregateOffer by same merchant

### ISSUE THREAD

**Issue by DominikKrulak** [schemaorg/schemaorg#1424]
The definition of the aggregate offer says that: When a single product is associated with multiple offers (for example, the same pair of shoes is offered by different merchants).

I have a product (the same pair of jeans) in more sizes in different price tags. I'm not sure whether I can use this_(will hurt webpage markup)_  to mark up the same product and list all available sizes as aggregateOffer by same merchant?

**Comment by WeaverStever** [comment]
You might write it up and test it.
https://search.google.com/structured-data/testing-tool

(You can paste your code into the testing tool under the "code snippet" tab)

Usually, when multiples are not valid, the testing tool only retains the last entry. (I've seen this happen on reviews, and contacts).

**Comment by DominikKrulak** [comment]
`<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Product",
  "image": "dell-30in-lcd.jpg",
  "name": "Dell UltraSharp 30\" LCD Monitor",
  "offers": {
    "@type": "AggregateOffer",
    "highPrice": "1495",
    "lowPrice": "1250",
    "priceCurrency": "USD",
    "offerCount": "2",
    "offers": [
      {
        "@type": "Offer",
        "url": "save-a-lot-monitors.com/dell-30.html"
      },
      {
        "@type": "Offer",
        "url": "save-a-lot-monitors.com/dell-31.html"
      }
    ]
  }
 }
</script>`

The mark up was valid. Thanks for your comment @WeaverStever and direction 👍
