### ISSUE TITLE
Specifying ontologies in schema.org

### ISSUE THREAD

**Issue by martin-nc** [schemaorg/schemaorg#1426]
Is there a way of specifying ontologies in schema.org? Let's say I have an event in Life Science, and I'd like to use terms from the [EDAM ontology](http://bioportal.bioontology.org/ontologies/EDAM?p=classes) as keywords, is it possible to do something like this:

```
<div itemscope itemtype="http://schema.org/Event">
  <h2  itemprop="name">My Event Title</h2>
...
  <div>Keywords:
      <div itemscope itemtype="http://schema.org/ontology">
          <!-- Use the EDAM ontology -->
          <link itemprop="url" href="http://purl.bioontology.org/ontology/EDAM">
          <div  itemscope itemtype="http://schema.org/ontologyTerm">
              <meta itemprop="url" content="http://edamontology.org/topic_3174">
              <span itemprop="name">Metagenomics</span>,
          </div>
          <div  itemscope itemtype="http://schema.org/ontologyTerm">
              <meta itemprop="url" content="http://edamontology.org/topic_3387">
              <span itemprop="name">Marine Biology</span>
          </div>
      <div>,
   </div>
...
</div>
```

Of course the 'ontology' and 'ontologyTerm' types don't exist, but is there an equivalent? If not, could I propose something like the above?

I'm working within the [Bioschemas project](http://bioschemas.org/index.html) and we'd like to be able to apply this to a variety of types (Events, CreativeWork, Datasets). I'd imagine this might be useful across domains because it would allow people to use controlled vocabularies (for keywords etc). I guess 'taxonomy' could be an alternative term if 'ontology' is too domain-specific.

**Comment by RichardWallis** [comment]
@martin-nc You can already utilise terms from other vocabularies when describing things using Schema.org.

For example you could describe an event about Marine Biology thus:

```
{
   "@type": "BusinessEvent",
   "name": "The Global Online Marine Biology Conference",
   "about": "http://edamontology.org/topic_3387",
   "startDate": "2016-12-25"
}
```
_(Note: I used the version of [Event](http://webschemas.org/Event) from webschemas.org, which includes_ about _as a property in the next release of Schema.org)_

You could equally use URLs from [WikiData](https://www.wikidata.org/wiki/Q7173), or any other authoritative source.   This capability is available for any property - for example:
```
{ 
   "@type": "Book",
   "creator": "http://viaf.org/viaf/95218067",
   "name": "Lord of the Rings" 
}
```
You are correct that there is no formal way to indicate suitable vocabulary URLs to use for certain properties, although there is nothing to prevent hints being added to a property's description.

One reason for not specifying an external vocabulary as the source for acceptable values for a property would be to constrain the use of a property.  Inevitably, especially considering WikiData, Dbpedia, etc., there can always be more than one source such authoritative values.

**Comment by philbarker** [comment]
Or how about this?
```
 {
    "@type": "BusinessEvent",
    "name": "The Global Online Marine Biology Conference",
    "about": {
         "@type": "Thing",
         "@url":  "http://edamontology.org/topic_3387",
         "@name":  "Marine biology",
         "@description": "The study of organisms in the ocean or brackish waters."
     },
    "startDate": "2016-12-25"
 }
```
(May be better if (a) you're confident the tool consuming the LD will be as tolerant of giving a URL in the place of a Thing as the big search engines are and (b) you want to convey some more information so that the consumer doesn't have to look it up.--you know what to do if only (a) or (b) applies.)

**Comment by martin-nc** [comment]
@RichardWallis @philbarker Thanks for that. I didn't know about the forthcoming _about_ property. That looks like the simplest approach.

Could you have multiple instances of _Thing_ in the _about_ property? I'm wondering how you can add multiple terms. 

I like Phil's approach but I feel slightly uneasy that the ontology isn't explicitly declared before the terms. One of our use cases is to scrape sites from around the organisation (or grab the info via APIs) and to know which ontology is being used, but I guess it's not a big deal to deduce the ontology from the term urls.

**Comment by philbarker** [comment]
@martin-nc "Could you have multiple instances of Thing in the about property?" --Yes you can.

**Comment by RichardWallis** [comment]
@martin-nc  [about](http://webschemas.org/about) is available on several Types, adding it to Event was somewhat of a catch up.

All properties in Schema are both repeatable and not mandatary.

In JSON-lD repeated about statement would look like this:
```
{
   "@type": "BusinessEvent",
   "name": "The Global Online Marine Biology Conference",
   "about": ["http://edamontology.org/topic_3387","https://www.wikidata.org/wiki/Q7173"],
   "startDate": "2016-12-25"
}
```
