### ISSUE TITLE
What is the character limit for "alternativeHeadline"?

### ISSUE THREAD

**Issue by ayumihamsaki** [schemaorg/schemaorg#1429]
Hello,

I am wanting to know the character limit for alternativeHeadline in schema:article. For example, Google has said the headline is 110 characters limited.

I know headers in Google are all limited and I have spoken to a few managers at Google that have told me its 22 words max. But I would like to know the official limit in characters. 

There must be a limit for Google Crawlers, so please could someone let me know.

Thanks.

**Comment by akuckartz** [comment]
schema.org does not need to specify such limits.

**Comment by RichardWallis** [comment]
To clarify @akuckartz's comment.

The Schema.org vocabulary itself has no such restrictions.  However certain consumers of data in Schema.org form may apply their own preferences.  

The information you seek may be available via https://developers.google.com/search/docs/data-types/data-type-selector or via their associated communities: https://plus.google.com/+GoogleDevelopers

**Comment by thadguidry** [comment]
From a practical implementation, I can comment that my applications limit
to consuming 4000 characters for that alternativeHeadline field...the
maximum that can fit in an Oracle VARCHAR2 datatype.  For other properties,
I have no limit and sometimes just use CLOB datatype.

>
Hope this helps you think about it from a consumer standpoint and data
storage perspective.

**Comment by ayumihamsaki** [comment]
Hello,

Thank you all for your comments, I understand now that there are two sides to this problem. One side is with schema-org and they say there is no limit to the "alternativeHeadline" as it's labeled as "text". So will be subject to Database limits etc.

The other side is with Google and I believe this limit will be a lot smaller. I am trying to get a character limit for say a Google News schema article where someone creates an alternative header like this:

`<h2 itemprop="alternativeHeadline">xxxxxxxxx.</h2>`

So as everyone has correctly pointed out this would not be a schema-org problem but rather a Google problem. I was hoping someone from Google would jump in and give the answer. Will tag Dan into this maybe he can help but I know he is very busy (this is the only person I can think that maybe is writing the Google Schema Developer Help Pages).

@danbri
