### ISSUE TITLE
Examples on openingHours should not use the 'time' element

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#143]
http://schema.org/openingHours

The examples on [`openingHours`](http://schema.org/openingHours) use HTML5’s `time` element:

    <time itemprop="openingHours" datetime="Tu,Th 16:00-20:00">Tuesdays and Thursdays 4-8pm</time>
    <time itemprop="openingHours" datetime="Mo-Su">Monday through Sunday, all day</time>

The values "Tu,Th 16:00-20:00" and "Mo-Su" don’t seem to be valid [according to W3C’s HTML5](http://www.w3.org/TR/2014/PR-html5-20140916/text-level-semantics.html#the-time-element) or [according to WHATWG’s HTML](https://html.spec.whatwg.org/multipage/semantics.html#the-time-element).

The examples on [`LocalBusiness`](http://schema.org/LocalBusiness) use the `meta` element instead, which seems to be appropriate. The [`data` element might also be an appropriate alternative](http://stackoverflow.com/a/26159198/1591669).

**Comment by danbri** [comment]
I had a chat with Hixie about possibly getting HTML updated to allow this, if/when we get this micro-notation properly spec'd. But for now, I agree, time element is in-apropes.

**Comment by danbri** [comment]
Another nudge that we should address this. https://twitter.com/Nettsentrisk/status/574859464316219392 

I'd suggest:

 - [ ] stop promoting <time> for this markup 
 - [ ] specify the openingHours microsyntax more formally, suggest it to HTML5 groups for use with <time>

**Comment by danbri** [comment]
This needs doing, but bumping one more milestone.

Here's a grep of what's in the examples:

    <time itemprop="validFor" content="P1Y">1 year</time>
     <time property="validFor" content="P1Y">1 year</time>
     <div>asked <time itemprop="dateCreated" datetime="2010-11-04T20:07Z">Nov 11 '10 at 20:07</time></div>
       <div>answered <time itemprop="dateCreated" datetime="2010-12-01T22:01Z">Dec 1 '10 at 22:01</time></div>
       <div>answered <time itemprop="dateCreated" datetime="2010-12-06T21:11Z">Dec 6 '10 at 21:11</time></div>
     <div>asked <time property="dateCreated" datetime="2010-11-04T20:07Z">Nov 11 '10 at 20:07</time></div>
       <div>answered <time property="dateCreated" datetime="2010-12-01T22:01Z">Dec 1 '10 at 22:01</time></div>
       <div>answered <time property="dateCreated" datetime="2010-12-06T21:11Z">Dec 6 '10 at 21:11</time></div>
     <p>Open: <time itemprop="openingHours" datetime="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</time></p>
     <p>Open: <time property="openingHours" datetime="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</time></p>
       <p>Normally open <time itemprop="openingHours" datetime="Mo,Tu,We,Th,Fr,Sa,Su 09:00-14:00">daily 9am-2pm</time> except on:</p>
     <p>Normally open <time property="openingHours" datetime="Mo,Tu,We,Th,Fr,Sa,Su 09:00-14:00">daily 9am-2pm</time> except on:</p>
     <p>Open: <time itemprop="openingHours" datetime="Mo,Tu,We,Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
     <p>Open: <time property="openingHours" datetime="Mo,Tu,We,Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
         <p>Open: <time property="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
         <p>Open: <time property="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Fr 13:00-17:30">Open weekdays 1pm-5:30pm.</time></p>
       <p>Open: <time property="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
       <p>Open: <time property="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
       <p>Open: <time property="openingHours" datetime="Mo-Fr 13:00-17:30">Open weekdays 1pm-5:30pm.</time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
      <p>Open: <time itemprop="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
       <p>Open: <time property="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
       <p>Open: <time property="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
       <p>Open: <time itemprop="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>
       <p>Open: <time property="openingHours" datetime="Mo-Fr 07:00-23:00">Monday-Friday 7am-11pm </time></p>
       <p>Open: <time property="openingHours" datetime="Mo-Th 09:00-12:00">Monday-Thursday 9am-noon</time></p>


Are the P1Y values legit? i.e. 

<time property="validFor" content="P1Y">1 year</time> 

?

**Comment by danbri** [comment]
@unor looking at #533 (via #1012 which reminds us that http://schema.org/openingHours syntax isn't appropriate for 'time' element), it looks like your fixes don't directly address this problem. Am I missing something?

**Comment by unor** [comment]
@danbri Right, https://github.com/schemaorg/schemaorg/pull/533 only fixes/improves the `OpeningHoursSpecification` example "Middle of Nowhere Foods". It was not meant to fix this issue here about the description/definition of the `openingHours` property.

**Comment by danbri** [comment]
Ah, then I misunderstood your comment in #1012 - just wanted to make sure I wasn't overlooking an existing fix

**Comment by danbri** [comment]
Ping @chaals - can you suggest what we should do here? For openingHours microdata/rdfa attribute on an element instead of the 'time' element... which element to use? /cc @betehess who suggested some other opening hours cleanup in #923.

**Comment by danbri** [comment]
The 'data' element was suggested

* https://html.spec.whatwg.org/multipage/semantics.html#the-data-element
* https://www.w3.org/TR/html5/text-level-semantics.html#the-data-element

These both say "When the value is date- or time-related, the more specific time element can be used instead." which more or less advocates for the current usage of 'time'. Except the actual definition of 'time' isn't so broad and our usage is not currently a good fit.

So my suggestion is:

* We change all our use of 'time' to 'data' element in examples.
* We consider optionally reverting that for the 2 cases with: itemprop="validFor" content="P1Y" ...

**Comment by mfhepp** [comment]
+1
The on- and off-relationship of the HTML5 spec with the <time> element is hard to understand from an outsider perspective anyway.

RDFa was simpler in that aspect with a separate datatype mechanism and the choice of arbitrary HTML elements for any kind of data ;-)

Martin

**Comment by danbri** [comment]
Here is a list of every line from an examples*.txt file that contains "<time":

https://gist.githubusercontent.com/danbri/732e6747c4063a548feb0556405a2710/raw/393fea577a18a02802819d80e57a0c58022bd822/gistfile1.txt

**Comment by danbri** [comment]
Published - see http://schema.org/docs/releases.html
