### ISSUE TITLE
Question: https://schema.org/temporalCoverage

### ISSUE THREAD

**Issue by l00mi** [schemaorg/schemaorg#1433]
I am a tiny bit confused about which type to employ here in different cases. If we have something like in the example `"2011/2012"` we should use the _DateTime_ type? Is this valid?

If yes is it then also possible to use this for e.g. https://schema.org/startDate ?

If no, how can we distinguish a temporalCoverage according 8601 like `"2011/2012"` with the type _Text_ from something broader like `"before the last episode"`?

**Comment by l00mi** [comment]
Do I not make sense? Any other place to ask?

**Comment by RichardWallis** [comment]
[temporalCoverage](http://schema.org/temporalCoverage) is expected to describe a range of dates and or times potentially open ended such as ```"2000/"``` for _so far in the 21st Century_ or ```"/1950"``` _before 1950_.  It optionally takes a Text value which could satisfy some historical period such as ```"The Dark Ages"```.  Plus it can also take a URL that could link to a well known definition of a time period (eg. https://www.wikidata.org/entity/Q217192).

It is for the data consumer (a search engine or others) to interpret what is marked up in any property value.  You can therefore use something such as ```"before the last episode"```.  The question I would as myself before doing so is, what are data consumers going to make of that string?

As to [startDate](http://schema.org/startDate) it is explicitly expecting a Date or a DateTime value, so it is unlikely that a consumer of your data would make much sense of a date range as a value.

**Comment by l00mi** [comment]
Thank you for the answer, this clarifies it a lot.

So basically there is no way to explicitly state that a value is a valid interval as specified by ISO 8601. If there is the type _"text"_ we need to inspect the content to decide if it is an interval as specified by ISO 8601?

Would it make sense to add a new _DataType_ called _Interval_ or such? I know that is a lot to ask for, but I think it is a pity if we can't explicitly state that we adhere a standardized format.

If you think this is out of scope, please feel free to close the Issue.

**Comment by RichardWallis** [comment]
As all properties within Schema.org can potentially have a Text as their value, even if not explicitly defined as an expected type, that issue is true for most properties.

As ISO 8601 is a structured format, the expectation is that most data consumers will have little difficulty in identifying a value in that format.
