### ISSUE TITLE
Add markup for Satirical Articles (or as a subtype of NewsArticle, SatiricalNewsArticle)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1437]
Back in 2012, I proposed a "[vocab idea: SatiricalArticle](https://lists.w3.org/Archives/Public/public-vocabs/2012Apr/0076.html)" for schema.org.

As Jason Douglas put it at the time,

> so essentially you're looking for the schema.org equivalent to  **;-)** ?

At the time of the original 2012 proposal we had fairly detailed discussions but eventually did not progress the idea, in large part because it was unclear what incentive satirical publishers might have for including the markup. 

In 2016 the environment is somewhat different, and satirical news publishers may have some incentive to distinguish themselves from sites that falsely claim their innacurate stories to be true.

There were some useful suggestions that included official codes from IPTC (for news) and from EBU for TV/media, based on the idea that we can model these as a particular well-known [genre](http://schema.org/genre).  While expressing a mapping to those codes would be useful I suggest we optimize for publisher simplicity here, and address the basic case of satirical news articles through a subtype of NewsArticle called SatiricalNewsArticle.

This would complement the recent success of schema.org's fact checking markup, which adds a subtype of Review called [ClaimReview](http://pending.webschemas.org/ClaimReview) (and lists the specific claimReviewed), and would be highly topical given recent widespread attention to the problem of fake news. /cc #1061

**Comment by rvguha** [comment]
This is a great idea. Lets do it!

**Comment by danbri** [comment]
Aye aye cap'n

**Comment by thadguidry** [comment]
@danbri NO NO NO !  Lets use the defacto global standard of Star Wars !  (not Star Trek)

**Comment by danbri** [comment]
We're more in the [Pirates of the Caribbean](http://www.imdb.com/title/tt0325980/quotes) tradition around here

> And thirdly, the Code is more what you'd call “guidelines” than actual rules.

**Comment by bquinn** [comment]
> If you were waiting for the opportune moment, that was it!

**Comment by rvguha** [comment]
I would prefer Star Trek.

https://www.quora.com/Which-is-better-and-why-Star-Wars-or-Star-Trek

**Comment by mediaprophet** [comment]
Kinda enjoying Potter references atm...

What about fiction, nonfiction + subtype: genre + Style?

I was thinking about genre: news, style: Article being a content genre /
style?

Others could be Style: report Style: liveCoverage

Etc.

**Comment by mediaprophet** [comment]
Nb: https://schema.org/publication. Looks like it could be updated?

**Comment by danbri** [comment]
re genre, while we should be clear how to use genre for these things I'd suggest for usability/simplicity reasons a type is worth it here.

**Comment by mediaprophet** [comment]
More useful than first considered...

https://en.m.wikipedia.org/wiki/Genre

**Comment by mediaprophet** [comment]
seeAlso: https://en.m.wikipedia.org/wiki/List_of_genres

Ie:
https://en.m.wikipedia.org/wiki/Mythic_fiction
https://en.m.wikipedia.org/wiki/Urban_fantasy

**Comment by mediaprophet** [comment]
parody  would be valuable too

On Tue., 22 Nov. 2016, 3:01 am Timothy Holborn, <timothy.holborn@gmail.com>
wrote:

seeAlso: https://en.m.wikipedia.org/wiki/List_of_genres

Ie:
https://en.m.wikipedia.org/wiki/Mythic_fiction
https://en.m.wikipedia.org/wiki/Urban_fantasy

On Tue., 22 Nov. 2016, 2:47 am Timothy Holborn, <timothy.holborn@gmail.com>
wrote:

More useful than first considered...

https://en.m.wikipedia.org/wiki/Genre

On Tue., 22 Nov. 2016, 2:40 am Dan Brickley, <notifications@github.com>
wrote:

re genre, while we should be clear how to use genre for these things I'd
suggest for usability/simplicity reasons a type is worth it here.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/schemaorg/schemaorg/issues/1437#issuecomment-261972902>,
or mute the thread

**Comment by danbri** [comment]
This is released. We can close the issue and revisit as Pending section is reviewed periodically

**Comment by bquinn** [comment]
FYI earlier in 2020 we added http://cv.iptc.org/newscodes/genre/Satire to the IPTC genre vocabulary, as well as some other new entries like http://cv.iptc.org/newscodes/genre/Sponsored and http://cv.iptc.org/newscodes/genre/Supported.

But I agree that it makes sense to add SatiricalArticle as a type here.
