### ISSUE TITLE
Is NewsArticle for only "news" or does it include "opinion", "interviews" etc. too?

### ISSUE THREAD

**Issue by guyvalerio** [schemaorg/schemaorg#1439]
Could someone clarify for me whether NewsArticle is intended to mean only "news" content that a news organisation creates, or is it intended to include comment, interviews features etc too? 

We make a clear distinction in our internal data models between the genres of content and wondered how we might expose that in schema.org markup. 

Apologies if I'm going over old ground.

**Comment by mediaprophet** [comment]
seeAlso: https://github.com/schemaorg/schemaorg/issues/1437

**Comment by thadguidry** [comment]
@guyvalerio NewsArticle can be used.  Its based off the IPTC work.  In fact, if you look at IPTC codes, you will see that they have many additional ones compared to the simple cases that we absorbed into Schema.org.

IPTC already has "Interviewee" for instance: http://cv.iptc.org/newscodes/infosourcerole/

Anyways, spend some research time here: https://iptc.org/standards/subject-codes/ and https://iptc.org/standards/newscodes/

I forgot which code or type they have to hold the kind of Story or Article piece it is, like your use case for "Interview" "Opinion", etc.   But you can ask someone at IPTC about that specifically, and then post a reply here to give us all a better understanding :)  Thanks!  Help us and we'll help you :)

**Comment by guyvalerio** [comment]
Thanks @thadguidry 

IPTC, as I understand it, define the _genre_ of their "NewsItem" class using their http://cv.iptc.org/newscodes/genre/ vocabulary. Typical values being "analysis", "interview" and many more. They then have subclasses of NewsItem according to media ("Article", "VideoObject" etc) - that makes sense.

So I think that schema.org:NewsArticle is equivalent to rNews:NewsItem. In turn then, any type of content written by a news organisation whether it be news, comment, interview etc is a schema.org:NewsArticle but we cannot use schema.org to differentiate its _genre_ (as IPTC define it) yet.

**Comment by davecompton** [comment]
Hi @guyvalerio 
Afaik schema.org:NewsArticle inherits genre from CreativeWork per https://schema.org/NewsArticle . Does that work?

**Comment by RichardWallis** [comment]
That should work - even, as schema:genre takes a URL, using IPTC genre codes if you wanted.
```
{
  "context": "http://schema.org",
  "@type": "NewsArticle",
  "name": "A biography of some celebrity",
  "genre": "http://cv.iptc.org/newscodes/genre/Biography"
}
```

**Comment by guyvalerio** [comment]
@davecompton @RichardWallis 
Great, that answers it. Thank you.

**Comment by davecompton** [comment]
Just to finish off the side convo: At TR we have a genre CV but it does not include 'News' as a value. Using a newsItem (from [NewsML-G2](https://iptc.org/standards/newsml-g2/)) already provides the News context (as it would in rNews) ... the genre then indicates the 'style' of the article: Reviews | Interviews ...
