### ISSUE TITLE
Question: http://schema.org/worksFor

### ISSUE THREAD

**Issue by santoshs** [schemaorg/schemaorg#1440]
Scenario:

I work in a company called ABC. So the schema relationship will be:

```
Person WorksFor ABC
```
When I leave the company and join XYZ, the schema changes to

```
Person WorksFor XYZ
```

Now the history about 'Person worked for ABC' is lost. So the properties should contain some form of start and stop data.

```
Person WorksFor ABC {from: fromDate, to: toDate}.
Person WorksFor XYZ {form: fromDate}
```
Leaving out toDate can mean, the Person is currently employed in XYZ. How would we go about representing this currently?

**Comment by RichardWallis** [comment]
You can do this by qualifying the relationship (either via the employee property on Organization, or the worksFor property on Person) using the [Role](http://schema.org/Role) type.   Any property in Schema.org can have a Role Type as its value.  The basic Role type, and its subtypes, contain startDate and endDate properties to enable you to qualify the relationship as you describe.

The use of Role can at first be a little confusing, I suggest you take a look at a couple of blog posts for a fuller explanation: [Introducing Role](http://blog.schema.org/2014/06/introducing-role.html) and [The role of Role in Schema.org](http://dataliberate.com/2015/04/15/the-role-of-role-in-schema-org/).
