### ISSUE TITLE
http://schema.org/Product seems broken

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#1442]
The page at http://schema.org/Product lacks properties that used to be there, like schema:additionalProperty,  schema:gtin13 etc. Is this intended?

**Comment by jvandriel** [comment]
I'm getting mixed result. If I check the page on my laptop there are a ton of properties missing, yet when I check the page with my phone (different IP) the page does have ll properties.

**Comment by RichardWallis** [comment]
As per #1441 - yes this is a defect which is to be fixed in the next [imminent] release.

It is something to do with in memory caching.

**Comment by RLRichardson** [comment]
They’re now at IndividualProduct

**Comment by mfhepp** [comment]
why? the this means millions of webpages need to be updated. 

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by danbri** [comment]
Ancient bug, long fixed
