### ISSUE TITLE
Expand domain of video to Thing?

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1447]
Following on from an issue (#1446) regarding some errors in an example, it seems the intention of the creator of the example was to attach a [video](http://schema.org/video) property to a MusicGroup type, to link to a video of the group in question.

As the domainIncludes of _video_ is only _CreativeWork_ this is not possible. 

We could propose extending the domain to include _MusicGroup_ but that would only address a simple symptom of a potentially broader problem.

In this age of Snapchat, YouTube, etc., etc., there is a blurring of boundaries between what is an image or a video (moving) image.  How do we classify an IPhone Live Photo for example?

In the current Schema.org structure any _Thing_ can have an _image_.  Is it time to say that say any _Thing_ can also have a video image?

This could be addressed either by changing the domain of _video_ from _CreativeWork_ to _Thing_, or adding _VideoObject_ to the range of _image_.

Discuss...

**Comment by jvandriel** [comment]
This overlaps with issue #292 (something I'd really like to see resolved). The original request/discussion was about expanding the domain of ```video``` to ```schema.org/Thing```.

**Comment by danbri** [comment]
On the blurred lines front, we could also decide 'video' is a special case (subproperty) of 'image', i.e. image(s) that move.

**Comment by jvandriel** [comment]
Sorry to be nitpicky but I don't see a video as images that move. At best it's an collection of images that should be watched in a specific order (at a certain speed).

Now I understand the reluctance to keep adding new properties to ```schemna.org/Thing``` but given the fact video plays such an important role on the web nowadays and that you can find videos about any type of thing, wouldn't it just be easiest to add ```video``` to ```schema.org/Thing```.

After all, it would actually resolve real world issues webmasters have.

**Comment by RichardWallis** [comment]
I'm just revisiting this (in respect of Tourism) and believe @jvandriel's suggestion of adding video to Thing makes sense

**Comment by thadguidry** [comment]
@RichardWallis just one bit of a worry... it might be used as a mentioned....rather than a sameAs...or both.  We need to be clear about what we want in the description.

**Comment by vholland** [comment]
+1 to adding to Thing.

**Comment by felipesanti** [comment]
Hi, from a Tourism industry perspective I support the idea of adding video content to anything that can be of interest to potential tourists.

@thadguidry @RichardWallis regarding the implementation, in order to simplify the work of a developer, I would argue for directly adding the **video** property to the Thing class. The video could be a VideoObject or a URL (e.g. a link to Youtube). As a matter of detail, I understand this would imply removing this property from CreativeWork.

**Comment by RichardWallis** [comment]
Taking the lead from the description of the image property:

    A video of the item. This can be a URL or a fully described ImageObject.

**Comment by vholland** [comment]
Speaking of CreativeWork, we may want to add a property for ```embeddedVideo``` to cover the current definition of ```video```.

**Comment by thadguidry** [comment]
@RichardWallis That description is too generic.  It leaves a lot open for further questions by developers.

- a video OF the Thing.
  - What does OF really mean here?
  - ABOUT the Thing ONLY ?
  - ABOUT the Thing PRIMARILY ?
  - MENTIONS the Thing but may not be PRIMARILY about the Thing ?
  - The Thing is a subjectOf the video ?
- Any of the above?
