### ISSUE TITLE
PublicationEvent of articles, periodical issues, etc.

### ISSUE THREAD

**Issue by darobin** [schemaorg/schemaorg#1450]
We are trying to capture a feed of publication events that represent a `ScholarlyArticle` being published (in a `Periodical`, `Issue`, `Volume`...) or an `Issue` being published (also in a `Periodical`, `Volume`...) and so on.

Our first instinct is to go with `PublicationEvent`. The description makes it look like the right thing. However, the properties seem to be heavily skewed towards broadcasting. My question is therefore: should we file a pull request to modify `PublicationEvent` somewhat to be friendlier to `CreativeWork`s and `CreativeWorkSeries`?

If not we can probably head over to the feed stuff, but in that case I would suggest restricting the definition of `PublicationEvent`.

**Comment by RichardWallis** [comment]
_PublicationEvent_ is the correct type. Checkout the [bib.schema.org definition](http://bib.schema.org/PublicationEvent), which includes the _publishedBy_ property.

Using _publishedBy_, _location_, and _eventDate_, etc. in a _PublicationEvent_ event, provided as the _publication_ property of a CreativeWork subtype such as _ScholarlyArticle_ should satisfy your need.

As per many Types in Schema.org there are properties that are not relevant for all use cases.  As no properties are mandated, this is not a problem.

**Comment by darobin** [comment]
I understand that we don't care about extraneous properties, but there nevertheless seems to be a broadcasting slant, even with the bib extensions. For instance `publishedBy` appears to be the publisher in some form (in fact it's not clear from the description why it doesn't just use [`publisher`](http://schema.org/publisher)).

But that doesn't give us where is was published. We can have that indirectly as `workFeatured.isPartOf = Periodical` but it leaves me wondering why `publishedOn` takes `BroadcastService` but not `CreativeWorkSeries`?

I also wonder if there is a reverse property for `publication`?

**Comment by RichardWallis** [comment]
I tend to agree with you about _publishedBy_ - that could easily be superseded by _publisher_. 

Why does _location_ not give you the where option you are looking for?

There _is_ a broadcast meme to the Type, it was TV & Radio that first introduced a proposal in this area.  It also has physical event (concert, conference, etc.) meme, but I don't see that constraining its use either.  

I see a significant difference between publishedOn (the delivery channel for a programme to be broadcast via) and an an article being published as part of a series.

The fact that a work _isPartOf_ a series is a creative attribute of the Work.  Whereas a BroadcastService that a programme is transmitted upon is an extra pice of information that you do not get with Book/Article publication. _TVSeries_ would be more closely related to what you are looking for, which itself is a subtype of _CreativeWorkSeries_ and uses a similar pattern:

``` 
TVEpisode > partOfSeries > TVSeries
          > releasedEvent > PublicationEvent > startDate
                                             > location > Place
```
```
ScholarlyArticle > isPartOf > CreativeWorkSeries
                 > publication >  PublicationEvent > startDate
                                                   > location > Place
                                                   > publishedBy > Organization
```
or starting from _PublicationEvent_ 

```
PublicationEvent > location > Place
                 > startDate
                 > publishedBy > Organization
                 > workFeatured > ScholarlyArticle > creator
                                                   > isPartOf > CreativeWorkSeries
```

As to an inverse of _publisher_, it is _workFeatured_.

**Comment by thadguidry** [comment]
@darobin for the use case of WHERE IS PUBLISHED... just use Event:recordedIn and its an inherited property for PublicationEvent (a subtype of Event)

**Comment by thadguidry** [comment]
```
  {
      "@type": "DataFeedItem",
      "dateModified": "2015-01-02",
      "item": {
            "@type": "PublicationEvent",
            "startDate": "1968-11-25",
            "location": {
                "@type": "Country",
                "name": "United States"
            },
	    "workFeatured": {
                "@type": "ScholarlyArticle",
		"name": "Enrich Your Publications with Schema.org"
			}
      }
   }
```
