### ISSUE TITLE
WinAction has a loser, LoseAction has a winner

### ISSUE THREAD

**Issue by tyrosinase** [schemaorg/schemaorg#1453]
This is right, but it's sufficiently unintuitive that (1) it probably needs called out in the notes, and (2) the example on LoseAction is a WinAction... with a winner.

**Comment by 01e9** [comment]
https://schema.org/Person `winner: LoseAction`

Shouldn't it be `winner: WinAction`?

**Comment by alex-jansen** [comment]
The example is fixed, so closing
