### ISSUE TITLE
add a new property of deliveryFee to OrderAction

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#1461]
Add a property—deliveryFee—for the ability to directly associate a [DeliveryChargeSpecification](http://schema.org/DeliveryChargeSpecification) to an [OrderAction](http://schema.org/OrderAction). Pull request #1458

**Comment by mfhepp** [comment]
For the records: This would also be in conflict with the underlying core model from GoodRelations: 
A `schema:Offer` is the promise / announcement to transfer a bundle of rights (schema:BusinessFunction) on one item (`schema:Product`) or a bundle of items (via [`schema:includesObject`](https://schema.org/includesObject)) for a specified compensation (`schema:priceSpecification`, see e.g. the [hotels documentation for detailed examples](https://schema.org/docs/hotels.html#pricing)).

So when you accept the offer via an action, the terms and conditions are already given by the offer.
