### ISSUE TITLE
How to markup web software (accounting, invoicing, etc.)

### ISSUE THREAD

**Issue by MightyMartyn** [schemaorg/schemaorg#1463]
Software just like Waveapps.com or Due.com

I can't find the exact type for it. 

I consider 2 types

Businessfunction or FinancialService, but they don't pass exact.

Help pls, I'd appreciate it.

**Comment by mfhepp** [comment]
This is best modeled via a `schema:additionalType`  that  describes the type of software or service included in the offer.

The business function is meant to describe the **bundle of rights** that you will obtain on the product or service.

For examples, see e.g.

- http://www.productontology.org/doc/Word_processor
- http://www.productontology.org//doc/Platform_as_a_service


**References:**

- http://wiki.goodrelations-vocabulary.org/Documentation/Conceptual_model
- https://www.heppnetz.de/ontologies/goodrelations/v1.html#License
