### ISSUE TITLE
Add new format for how to / help articles

### ISSUE THREAD

**Issue by tbooch** [schemaorg/schemaorg#1464]
I am looking for a format to mark up help center documentation for a web product (to better guide Rich Snippets results from Google) and didn't find a format dedicated to this sort of thing. Closest option I found was recipe, but why not a more general "How to" format? Does it already exist? If not, this would be a huge help to have. Thanks and Happy Holidays!

**Comment by gmackenz** [comment]
I  believe this has been resolved with [HowTo](https://schema.org/HowTo)
