### ISSUE TITLE
SomePersons proposal

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#1466]
As [SomeProducts](https://schema.org/SomeProducts), **SomePersons** can be

> A placeholder for multiple persons that has a collective goal, but not is an organization.

... covering informal and ad-hoc groups of [Person](https://schema.org/Person)s, as [foaf:Group](http://xmlns.com/foaf/spec/#term_Group).

## NOTES:

* There are "loose organizations" as [MusicGroup](https://schema.org/MusicGroup) or [DanceGroup](https://schema.org/DanceGroup), but it not cover all usual cases, and in general is used for formal/professional groups, that are in fact organizations.

*  There are a demand for (aleatory examples) BikeGroup, FriendGroup, RunnerGroup, StudyGroup, SkateGroup, UserGroup,  etc. but they are not an explicit demand, we only need *SomePersons*, that will cover all variants (as SomeProducts).

**Comment by thadguidry** [comment]
Peter, I have a hunch that you specifically ran across some use case were you felt that Organization didn't fit well, or its description was a bit awkward ?  Can you explain that use case instead ?

(my other hunch is that Organization can fit all cases with regards to Human Organizational Behaviors or Collectives... for Scientific groups like "a colony of ants", we don't have a Type like that, or necessarily need it with the advent of AdditionalType)

**Comment by ppKrauss** [comment]
Hi @thadguidry, let's use as illustration two of cited ones:

* *TheatreGroup*: if [MusicGroup](https://schema.org/MusicGroup) and [DanceGroup](https://schema.org/DanceGroup) exist, why TheatreGroup not exist? <br/>There are two problems: 1. the creation of an "infinite specializations" that SchemaOrg not need. 2. the existence, in real life, of "informal groups" (of Music, Dance or Theatre) that are not organizations, are simple "task groups" (like Trello's task-groups or [teams](http://help.trello.com/article/927-what-are-teams)).

* *UserGroup*: an usual database or Linux user group. Imagine Users as a kind of [Person](https://schema.org/Person) specialization: it is not an organizarion.


PS: perhaps the focus of discussion is to remember that not exist an [wd:Organization](https://www.wikidata.org/wiki/Q43229) instance that is also (and "so informal" as) a [foaf:Group](http://xmlns.com/foaf/spec/#term_Group) instance... Well, I never see an example here in SchemaOrg, and it is not intuitive to "enforce other semantic" for Organization... Organizations are less informal,  have some "[contract costs](https://en.wikipedia.org/wiki/Transaction_cost)" to be created, and some "minimal stability" to exist.

**Comment by thadguidry** [comment]
Peter, your looking for a Social Group ?  Our Organization Type is already a subclass of that as implied... https://www.wikidata.org/wiki/Q874405

That's why I think you can just use Organization for your use case.  I think you are tripping up on the name itself "Organization" and thinking that it is formal....when in fact, we say that you can use it for formal and informal groups.

**Comment by rvguha** [comment]
I agree with Thad. I think our notion of Organization should cover both
'formal' organizations and informal ones.

It would be good to see examples of why Organization is inadequate.

guha

**Comment by ppKrauss** [comment]
Thanks @thadguidry to the good explanations.

 > your looking for a Social Group ? Our Organization Type is already a subclass of that as implied... https://www.wikidata.org/wiki/Q874405

Hum... Now we see the relevance of issue #280 (*"Schema.org should have mappings to Wikidata terms where possible"*) and  the need for [taking "both sides to build a bridge"](https://github.com/schemaorg/schemaorg/issues/280#issuecomment-270173446) (Withdata-to-SchemaOrg and SchemaOrg-to-Wikidata. 
If formal RDF SchemaOrg definition have a [wd:SocialGroup](https://www.wikidata.org/wiki/Q874405) link instead as "nothing", we not lost time here, and the web interface not produce error-prone interpretations.

On my opinion, without a Wikidata link, any reader will be interpret  [sc:Orgnanization](https://schema.org/Organization) as [wd:Organization](https://www.wikidata.org/wiki/Q43229), not as [wd:SocialGroup](https://www.wikidata.org/wiki/Q874405). Today we can add some words to reduce friction, showing that it is "informal or formal", but tomorow we will arrive with other problem, adding more words... And one day will copy all *SocialGroup*-Wikipedia-article's words to the definition ;-)

> Hope that helps. We can expand and add the terms "formal and informal" to the Organization definition

Yes (thanks!), and show some  examples of *informal Organization* (eg. Facebook group) to enhance it.

------

@rvguha thanks also.  
> It would be good to see examples of why Organization is inadequate.

I think it is not a problem of "inadequate or adequate"... If SchemaOrg defined, it is the definition... After definition, the public and users of SchemaOrg need clarity to interpret it, 
so the problem is the ambiguity of definition, that not stops by adding some words to a phrase.

In the Semantic Web the definitions are links, a graph of semantic links...

SchemaOrg is the "definition authority", have also some responsability to reduce the friction... Perhaps a simple solution, is priorizing  [issue #280 at "this side of the bridge"](https://github.com/schemaorg/schemaorg/issues/280#issuecomment-270173446)  ;-) 
(the map from SchemaOrg to Wikidata)
