### ISSUE TITLE
`timeRequired` examples show invalid values.

### ISSUE THREAD

**Issue by christianhujer** [schemaorg/schemaorg#1469]
The `timeRequired` example given 'P30M' probably shall mean "30 minutes". However, 'P30M' actually means a duration of 30 months, which I do not think was the intention. The correct way to specify a duration of 30 minutes is 'PT30M'.

The `timeRequired` example given 'P1H25M' is invalid, as "P1H25M" is not a valid duration string. The correct way to specify a duration of 1 hour and 25 minutes is 'PT1H25M'.

The `timeRequired` property: http://schema.org/timeRequired
Description of ISO8601 durations: https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by philbarker** [comment]
@danbri I think this reopening too? I screwed up putting a fix for this issue into an unrelated branch, then reverted the fix, but the PR closed this issue because of the original commit.
PR #1975 closes this issue properly.
