### ISSUE TITLE
`timeRequired` RDFa example uses invalid (ambiguous) duration

### ISSUE THREAD

**Issue by christianhujer** [schemaorg/schemaorg#1470]
The RDFa example for `timeRequired` contains the following HTML+RDFa fragment:
```
        Duration: <span property="duration">03:12</span>
```
This is ambiguous and therefore invalid: A tool wouldn't know whether the 03:12 represents 3 hours 12 minutes or 3 minutes 12 seconds. The corresponding HTML+RDFa should look like this:
```
Duration: <time property="duration" datetime="PT3H12M" content="PT3H12M">03:12</time>
```

Similarly, the markup for the following fragment of the same example should be improved:
```
       Typical length of lesson, <span property="timeRequired">1 hour</span>. 
```
to
```
       Typical length of lesson, <time property="timeRequired" datetime="PT1H" content="PT1H">1 hour</time>. 
```

**Comment by philbarker** [comment]
@danbri I think this reopening ? I screwed up putting a fix for this issue into an unrelated branch, then reverted the fix, but the PR closed this issue because of the original commit.
PR #1975 closes this issue properly.
