### ISSUE TITLE
contact point for datasets

### ISSUE THREAD

**Issue by ldodds** [schemaorg/schemaorg#1472]
I'm looking at how to describe some ONS datasets using the new Dataset term. Here's [an example](https://www.ons.gov.uk/economy/inflationandpriceindices/datasets/consumerpriceindices). 

Every dataset has a public contact point, which is a member of staff who can help with questions relating to the dataset. None of the existing properties seem to cover this. 

The person isn't necessarily the author, creator, editor, etc of the dataset. While they could arguably a described as a `contactPoint` for the Organisation publishing the dataset, in this case the named person isn't a general point of contact for the whole ONS, just for 1 or more datasets.

Perhaps datasets should have a `contactPoint`? 

Or is there a general property that could be used which I'm missing?

**Comment by darobin** [comment]
Yes, that would indeed be interesting. We considered using `accountablePerson` for that but rejected it as the legal bit seems restrictive.

**Comment by tfrancart** [comment]
We had pretty much the same requirement for describing Legislation (https://github.com/schemaorg/schemaorg/issues/1156), where we wanted to encode the person/service/ministry to reach if someone has a question on a particular law; this is not necessarily the service who wrote the initial law, neither a global contactPoint for that organisation. We ended up adding a custom property "legislationResponsible".

**Comment by ldodds** [comment]
I realised today that DCAT has contact point, so given schema.org is following it as a model, it seems worth adding. It's a recommendation property in the DCAT application profile for EU data portals

**Comment by mfenner** [comment]
@ldodds one idea would be to use the existing `contributor` property and provide the type of that contributor. We use this pattern with DataCite metadata for datasets and `ContactPerson` is one possible contributorType. We also have contributorType `DataCurator` which I am sure will also be requested for `Dataset`.

**Comment by ldodds** [comment]
@mfenner these contacts aren't necessarily a contributor, its a named contact in the statistical office who is the primary person to contact for questions about the dataset. A type contributor could work, but doesn't seem quite right. As DCAT already supports it and its recommended by the DCAT-AP I'd vote for just adding the existing property.

@danbri I've been testing this out in the Structured Data Tool which does warn about this not currently being allowed. Although it also tells me that a ``contactType`` must be one of the legal values, but I can't see those documented anywhere.

**Comment by ldodds** [comment]
Example of property in use: https://github.com/ldodds/ons-metadata-examples/blob/master/consumer-price-index-schema.org.jsonld

**Comment by mfenner** [comment]
@ldodds For DataCite a `contributor` is an organization or person involved with the generation or maintenance of a dataset, but is not an `author`/`creator`. I think Dublin Core uses this concept similarly.

Maybe it is a better fit for how schema.org works to have a `ContactPerson` class, either as subclass of `Person` or as subclass of `contributor`. I would also add `DataCurator`, a `Person tasked with reviewing, enhancing, cleaning, or standardizing metadata and the associated data`.

**Comment by danbri** [comment]
At some point in DC, contributor was considered a more general superproperty of 'creator' and 'publisher'. Am on a plane so can't check right now.

**Comment by ptsefton** [comment]
@ldodds What did you decide to do? I'm wrestling with the same problem at the moment trying to come up with a way of packaging research data using schema.org metadata.

Some kind of contactPoint-ish property on Dataset would be good. It would be good if that could have Person and Organisation values.

But in the short term, what can I do - if I use contributor with Person as a value, how do I distinguish contributor-as-contactPoint from other contributors?

My fallback has been to use accountablePerson, but that's not really a great match, and sometimes we might prefer an Organisation (or a ContactPoint) to be the point of contact.

**Comment by ldodds** [comment]
@ptsefton I haven't done more than what is noted and linked from this thread. 

I still think best option is to keep schema.org strongly aligned with DCAT and use contact point rather than getting into complexities of modelling additional roles.

**Comment by ptsefton** [comment]
Thanks @ldodds - I now have a [draft spec with some TODOs still in it](https://github.com/UTS-eResearch/datacrate/blob/develop/spec/0.1/data_crate_specification_v0.1.md)

At this stage I've gone with accountablePerson rather than contactPoint because the latter gave errors in the Google structured data checker. Does this matter? Also I read somewhere that schema.org is looking to get rid of Class/Property pairs that differ only by case, so the new property would be hasContactPoint, wouldn't it? 

Other things that would be useful for research data sets include a Project class that can be used for research projects, and an agreed way of linking to publications - (there's a ScholarlyArticle class but it has no properties of its own).

 Feedback on the above link would be appreciated, both on the approach and the style, I'm not used to writing specs.

**Comment by yayMark** [comment]
@ldodds On contactType, I found this information at Google: https://developers.google.com/search/docs/data-types/corporate-contacts

Basically, there's a set of contactType values they recognise. I assume its best to go with those. At the time of writing, they are: "customer support", "technical support", "billing support", "bill payment", "sales", "reservations", "credit card support", "emergency", "baggage tracking", "roadside assistance", "package tracking"
