### ISSUE TITLE
SportsEvent example uses non-existent type and properties

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#1479]
Example 2 for [SportsEvent](https://schema.org/SportsEvent) provides this code:

      "subEvent": {
       "@type": "OrderedEvent",
        "@id": "http://mlb.com/ws2013g1",
        "name": "Game 1",
        "eventOrderPosition": "1",
        "nextEvent": "http://mlb.com/ws2013g2"

Neither schema.org/OrderedEvent, schema.org/eventOrderPosition nor schema.org/nextEvent exists.

The provenance of this appears to be as a proposal in [2014 Schema.Org Sports Vocab Proposal v.3.0](https://www.w3.org/wiki/images/archive/b/b9/20140509192404!2014SportsVocab-v3.pdf).  However, [v.3.2](https://www.w3.org/wiki/images/b/b9/2014SportsVocab-v3.pdf) notes of v.3.0.3 (in the changelog) "removed classes / properties associated with ordered events; these will be handled via the proposed ItemList based model".  As [ItemList](https://schema.org/ItemList) is now live, the example should be updated to either use ItemList (though I don't see how, as instances ItemList may only currently appear as values for properties recipeInstructions, track, breadcrumb and hasOfferCatalog) or be removed altogether.

**Comment by RichardWallis** [comment]
Referenced example no longer visible.
