### ISSUE TITLE
Use of PhysicalActivity outside of life sciences domain

### ISSUE THREAD

**Issue by ldodds** [schemaorg/schemaorg#1480]
I'm currently working with a community group to define how to publish opportunities for people to take part in physical activities.

We're building around schema.org currently. There's a draft specification which outlines how we need to describe data around activities:

* https://www.openactive.io/modelling-opportunity-data/#activities (Activities and Programmes)
* https://www.openactive.io/modelling-opportunity-data/#activity-code-physicalactivity-code- (PhysicalActivity)

I'm trying to understand how our requirements align with PhysicalActicvity and PhysicalActivityCategory defined in the life science dimension.

My questions/comments so far:

* Are there examples of these types in use that I can refer to?
* I'm not really clear of the distinction between PhysicalActivity and PhysicalActivityCategory
* Is the PhysicalActivity type intended for use outside of life sciences? Most of its properties and description relate to that domain
* There's some potential clashes with properties like "recognisingAuthority". E.g. in the UK Sport England has [recognised sports](https://www.sportengland.org/our-work/national-governing-bodies/sports-that-we-recognise/). But [recognisingAuthority](http://health-lifesci.webschemas.org/recognizingAuthority) is defined in terms of a "medical practice".

I'm keen to build on existing work where necessary, but for most of our needs the category system outlined in #894 may be sufficient, assuming we define a property to associate an `Event` with an activity that will be included.

Tagging in #1116 to link this to the tracking issue.

**Comment by twamarc** [comment]
Hi @ldodds,
although the  ´´´  PhysicalActivity ´´´and ´´´PhysicalActivityCategory´´´ are defined in the life science extension they are rather generically defined here, and therefore they can be used outside lifescience domain as well. 
Personally I have no examples to share or uses-cases (despite the use between 10 and 100 domains recorded).
What is the purpose of your project? Any concrete use-case (a public domain) to consume/use your mappings to schema.org? 
~Marc
