### ISSUE TITLE
Sitemap.xml need to aid search engine discovery of Schema.org terms

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1483]
Schema.org terms and descriptions are not always easily discoverable via search engines.  This is also reflected in the quality of the schema.org site search powered by Google Custom Search.

Creation of a [sitemap file](https://developers.google.com/search/docs/guides/create-URLs) to direct search engine crawlers should go someway towards solving this issue.

**Comment by AymenLoukil** [comment]
I also suggest to create an HTML sitemap listing all the terms / vocabs ( alphabetical / chronological order) linking to single pages.

**Comment by Aaranged** [comment]
+1 @RichardWallis 

Question (and fair warning, it's a bit of a trick question), which one of these two URLs would you select to publish in your sitemap?:
http://schema.org/Thing
https://schema.org/Thing

Think you can see where I'm going here.  Permitting a web page to be accessed under both HTTP and HTTPS is decidedly _not_ a best practice.  And in terms of which formulation to prefer, ([Google is unambiguous](https://support.google.com/webmasters/answer/139066?hl=en#https) in regard to preference here).

Any support this year for my annual proposal that schema.org URIs be canonicalized under HTTPS, with the HTTP version 301 redirecting to the HTTPS version?  Apologies if I can't recall some deal-breaking objection as to why this is not possible (i.e. it breaks some functionality).  Perhaps absent any quick responses I'll just open a new issue proposing that (and rolling the use of rel="canonical" into this).

**Comment by AymenLoukil** [comment]
@Aaranged There are already some issues about http / https : 

#1486 and #1325

**Comment by Aaranged** [comment]
Thanks @AymenLoukil - in fact just came back to _this_ issue to see that I had seen #1325 and so to ignore my comment. :)

**Comment by jono-alderson** [comment]
Can we revisit this, now that we're HTTPS'd?

**Comment by RichardWallis** [comment]
Current sitemap looks like this:
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://schema.org/3DModel</loc>
<lastmod>2020-11-30</lastmod>
</url>
<url>
<loc>https://schema.org/AMRadioChannel</loc>
<lastmod>2020-11-30</lastmod>
</url>
<url>
<loc>https://schema.org/APIReference</loc>
<lastmod>2020-11-30</lastmod>
</url>
<url>
<loc>https://schema.org/Abdomen</loc>
<lastmod>2020-11-30</lastmod>
</url>
```
What needs visiting?

**Comment by jono-alderson** [comment]
Odd. When I requested that earlier I got a 404. Never mind! 😆
