### ISSUE TITLE
Automatically redirect http to https version

### ISSUE THREAD

**Issue by AymenLoukil** [schemaorg/schemaorg#1486]
Hi all,
Actually http version is **not redirecting to https one**. 

I recommend to make a 301 redirection by adding something like this to .htaccess file : 

RewriteEngine On
RewriteRule ^(.*)$ https://schema.org/$1 [R=301,L]

**Comment by RichardWallis** [comment]
This is already subject of issue #1325 which explores why it is not just a simple redirect solution.

Closing in favour of that issue
