### ISSUE TITLE
questions re: property occupationalCategory

### ISSUE THREAD

**Issue by mignon1915** [schemaorg/schemaorg#1487]
I'm interested in getting more context surrounding the use of the O*NET-SOC taxonomy with prop occupationalCategory. Is the use of that particular taxonomy required for population of values for this property, or is it just a recommendation? I know that the property is used in 1,000-10,000 domains, but is there any information available on the use of that taxonomy with this property? What is the recommended format for populating this property? I see that this property is under discussion [here](https://github.com/schemaorg/schemaorg/issues/280) and [here](https://github.com/schemaorg/schemaorg/issues/1410), but looking for some more direction for current implementation.

**Comment by RichardWallis** [comment]
As with all aspects of Schema.org nothing is **_required_**.  However information such as you reference in the descriptions help set the expectations of data consumers (such as the search engines) and the practices of the data producers.

Reading this particular description (I have no direct experience in using it) "_Ideally includes textual label and formal code_"  My expectation would be to see it marked up thus:
```"occupationalCategory": "51-6042.00 Shoe Machine Operators and Tenders",```

This text only format is open to interpretation by the consumers - how we can only guess ;-)

A more satisfactory way to explicitly mark is up is proposed in issue ( #894) _CategoryCode Proposal_ and a relevant example ([example 4 ](http://pending.webschemas.org/CategoryCode#catcode-4)) can be seen on webschemas.org.  If this is adopted it would be good if taxonomy publishers such as O*NET could be encouraged to publish there data in this way, with associated canonical URIs.

**Comment by mignon1915** [comment]
thanks for that @RichardWallis! 

I'm currently thinking about the value to be gained from making use of schema.org-recommended taxonomies, and it's very difficult to measure that since it's hard to find out what common practices there are out there for this particular property (I've found quite a few examples of misuse or population with non-O*NET values but NO examples of recommended use in the wild!).

Do you have any recommendations for how to analyse common practices or consumer expectations of this sort?

**Comment by RichardWallis** [comment]
I would treat descriptions associated with terms in Schema.org at the level of recommendations so I would not categorise not following them  as misuse - more like _not recommended_ practice.

The best way of potentially influencing the use of recommended practice is by example.

As to analysing current practice, it sounds like a useful and instructive project to make use of the [Common Crawl](http://commoncrawl.org/) data and the tools emerging around it.
