### ISSUE TITLE
The BorrowAction should allow Organizations to be the lender

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1494]
Currently, http://schema.org/lender only allows a Person as the expected type. It would be useful to allow Organizations to also be lenders.

**Comment by erimille** [comment]
+1

If specific examples are needed, I'd be happy to share from a Library perspective.

**Comment by AymenLoukil** [comment]
I agree +1 . In other perspectives also (eg : financial organizations..)

**Comment by RichardWallis** [comment]
I agree +1
Also for http://schema.org/borrower 
Most other sub-properties of http://schema.org/participant should too.  

Participant itself expects both Person and Organization.  

Are we not looking at an inheritance issue here?  Should not sub-properties inherit the expected properties of their super-property?  

If the answer to these two questions are yes, we are actually looking at a fix to the logic in the coding of the Schema.org site to automatically cary forward expected types from a property onto its sub-properties.

**Comment by danbri** [comment]
Re borrower and "most other sub-properties", if this isn't applicable to allow sub-properties we should go case by case. I'll fix this one for now. Richard - on the larger question of what the semantics are for subproperty/range/domain and whether the site should display, can you raise an issue?

**Comment by danbri** [comment]
http://webschemas.org/lender should be updated (but there can be cache-based delays; in my browser I had to use http://webschemas.org//lender to see the fix).

**Comment by AymenLoukil** [comment]
Yes it is showing both Person / Organization.
