### ISSUE TITLE
Inheritance of rangeInclude values by subproperties

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1496]
As raised in issue (#1494)

Unlike Types, which inherit available properties from their super-type, properties do not inherit their expected type values from their super-property.

It is proposed that properties should inherit the expected types of their super-properties

The expected types are defined in the rangeIncludes attribute of the property definitions.   To implement this proposal would require code enhancements to the site.

**Comment by jvandriel** [comment]
Makes sense.  +1

**Comment by gkellogg** [comment]
The Structured Data Linter entails rdfs:subPropertyOf to assert `:s :pp :o` where `:s :p :o` and `:p rdfs:subPropertyOf :pp`, which would automatically handle `rangeIncludes`. It also entails `rdfs:range` and `rdfs:domain`, but not `schema:rangeIncludes` or `schema:domainIncludes`, which would be fairly straightforward to do.

The effect of the first rule is to create a triple which does validate, but leaves the original triple not validating. Adding entailment for `rangeIncludes/domainIncludes` makes good sense.
