### ISSUE TITLE
Course Vocab add attribute to define expected time to take course

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#1497]
Most courses online are self-paced. But, an instructor in most LMS systems can define the amount of time it will take to complete the course. ( x days, x hours ) and that should be defined as an attribute of Course. https://pending.schema.org/Course

**Comment by philbarker** [comment]
Indeed. Course is a subtype of CreativeWork and so inherits the timeRequired property https://schema.org/timeRequired that allows exactly this.

**Comment by inetbiz** [comment]
alright, that makes sense. I would suggest @danbri label this for documentation and the example in json, microdata to include the timeRequired attribute?
