### ISSUE TITLE
Civic / Nonviolent Campaigning extension proposal

### ISSUE THREAD

**Issue by DmPo** [schemaorg/schemaorg#1501]
Sometimes civic structures - or even whole states - are captured and civic nonviolent action is needed to deal with the usurped states to bring democracy, human rights and rule of law back.

Although there are some great open government initiatives and standards around, openness is not enough to stop the usurpers - fact-based media coverage, nationwide civic coalitions, and strategic nonviolent actions might be needed to deal with them efficiently.

Schema.org has [CivicStructure](https://schema.org/CivicStructure), [Action](https://schema.org/Action), [Organization](https://schema.org/Organization) and other needed types in the core layer, but lacking is nonviolent civic actions elements.

As of today the types of possible nonviolent actions and strategies are well studied (for example, see [Why Civil Resistance Works: The Strategic Logic of Nonviolent Conflict](http://www.belfercenter.org/sites/default/files/legacy/files/IS3301_pp007-044_Stephan_Chenoweth.pdf)) and this is the time to bring them in the schema.org.

Feel free to contribute to the forked schemaorg at https://github.com/DmPo/Schemaorg_CivicOS

**Comment by mediaprophet** [comment]
That would be civics rather than civic.  Civics being something done by
citizens(with or without Gov), civic being something owned or operated by
government.

**Comment by akuckartz** [comment]
Why is a fork needed for that?

**Comment by DmPo** [comment]
Fork is not needed fir that? Fine, let's have it without fork.

**Comment by mediaprophet** [comment]
Fyi.  Other civics related considerations.
https://lists.w3.org/Archives/Public/public-schemaorg/2016Nov/0036.html
