### ISSUE TITLE
How can I nesting <meta>-Tags with 

### ISSUE THREAD

**Issue by janw1** [schemaorg/schemaorg#1506]
What I have is a kind of the following structure:
EVENT (itemtype="http://schema.org/Event)
... Name
... Date
... ...
... LOCATION (itemtype="http://schema.org/Place)
...... Name
......Url
...... ...

I wont show all the Place-Information on the website, but I want to use the information for microdata.
And so I want to add this tag: 
`<meta itemprop="LOCATION" itemscope itemtype="http://schema.org/Place">`
Works fine. 

But how can I add the itemprops for "name", "url", "address" for LOCATION?

It won't work like :
```
<meta itemprop="location" itemscope itemtype="http://schema.org/Place">
<meta itemprop="url" content="https://example-location.com">
<meta itemprop="name" content="exampleLocationName">
```

**Comment by mrshannonyoung** [comment]
@janw1

This is not the place to ask questions you have regarding support for your code, you should direct any questions, and would get a quicker answer over at [Stackoverflow](http://stackoverflow.com/questions/tagged/schema.org).

**Comment by janw1** [comment]
Oh, sorry!

So I will delete my question!
