### ISSUE TITLE
properties of BusinessAudience

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1510]
These props describe a business in general: `numberOfEmployees yearlyRevenue yearsInOperation` 
These are defined as properties of `BusinessAudience`. But `BusinessAudience` is a subclass of `Audience` (together with eg `Researcher EducationalAudience` etc) and  there's no relation between `LocalBusiness` and `BusinessAudience`.

Something seems amiss here

**Comment by RichardWallis** [comment]
@VladimirAlexiev It looks like you have identified an orphan Type, not defined as an expected type for any other Type and unlikely to be used in isolation as a primary entity.

Anyone else contradict this thought?

**Comment by VladimirAlexiev** [comment]
> not defined as an expected type for any other Type

@RichardWallis can you elaborate? It's a subclass of `Audience` which is the range of `audience`

**Comment by VladimirAlexiev** [comment]
IMHO the above 3 props should be attached to `Organization`

**Comment by RichardWallis** [comment]
@VladimirAlexiev Looking at this more closely (sorry if my previous quick reply led to confusion)
`audience` which expects `Audience` or one of its subtypes as a value is a property available on both `Product` and `Service`.  This enables the description of the target audience for individual Products and/or Services offered by an organisation or local business.  I presume the inclusion of properties such as `numberOfEmployees` enables the description of the resources applied to a service.

The logic behind this is that you would not add `audience` to a `LocalBusiness` as that would define that audience for all the products/services offered.  You add it more accurately to thier individual products/services.

It is somewhat of an anomaly however that `audience` is also available on `LodgingBusiness`.  

Independently I have some sympathy for your suggestion to add  `numberOfEmployees`,`yearlyRevenue`, `yearsInOperation` to `Organization` to which they are applicable separately to the products and services offered by the organisation.

**Comment by VladimirAlexiev** [comment]
@RichardWallis I don't understand. Product and Service have audience, and (BusinesS)Audience has numberOfEmployees. How does that make Service have numberOfEmployees?

**Comment by RichardWallis** [comment]
@VladimirAlexiev It does not, but it does allow the organisation offering the service [targeted at that particular audience] to identify the number of employees focussed on satisfying that audience.

**Comment by VladimirAlexiev** [comment]
So do you mean something like this?
```turtle
<service> a Service; audience <service/audience>.
<service/audience> a BusinessAudience;
  audienceType "Small and medium enterprises";
  geographicArea dbr:Bulgaria;
  numberOfEmployees 5;
  yearlyRevenue 100000;
  yearsInOperation 2.
```
Seems far fetched. 
IMHO the last 3 props are captured:
- most often for businesses
- less often for products and services (unless they are synonymous with the business, and act as its "trade style name")
- very rarely for specific audiences. 

Eg while you could track iPhone sales per country, you can hardly figure out how many employees worked on the production of iPhones this year (I've read 233 companies are involved), and it's impossible to say how many worked on the production of iPhones exported to Bulgaria this year.

**Comment by RichardWallis** [comment]
@VladimirAlexiev In principle yes.
Remember that there are no mandated properties in Schema.org

I do not necessarily think that the type of service you describe is an ideal candidate.  The following might be more appropriate:
```
{
"@type": "Service",
"name": "Youth Counselling Service"
"audience": {
                 "@type": "BusinesAudience",
                 "audienceType": "Under 18's",
                 "geographicArea": "Greater London",
                 "numberOfEmployees": 11,
                 "yearsInOperation: 5,
                 },
"provider": "London Personal Help Services"
}
```
For such a service the time a service has been in action and the number of employees running the service my well be a useful selection criteria.

I am not saying that this is the best, or most useful, area of the vocabulary but I do not see compelling reasons for change.

**Comment by VladimirAlexiev** [comment]
@RichardWallis Ok, let's add `domainIncludes Organization`
