### ISSUE TITLE
naming instances of schema:PhysicalExam

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1513]
```turtle
schema:Abdomen a schema:PhysicalExam ; *
schema:Appearance a schema:PhysicalExam ; **
schema:CardiovascularExam a schema:PhysicalExam ;
schema:Ear a schema:PhysicalExam ; *
schema:Eye a schema:PhysicalExam ; *
schema:Genitourinary a schema:PhysicalExam ; *
schema:Head a schema:PhysicalExam ; *
schema:Lung a schema:PhysicalExam ; *
schema:MusculoskeletalExam a schema:PhysicalExam ;
schema:Neck a schema:PhysicalExam ; *
schema:Neuro a schema:PhysicalExam ;
schema:Nose a schema:PhysicalExam ; *
schema:Skin a schema:PhysicalExam ; *
schema:Throat a schema:PhysicalExam ; *
```
- The instances marked with * refer to anatomical parts. I suggest to add the word `Exam`
- The instance marked with ** is named in an overly generic way. Most people will think of Hollywood when they hear `Appearance`

**Comment by twamarc** [comment]
+1
@VladimirAlexiev 
We have started extension types improvements and this is an ongoing work. I always welcome issues like this as they will extend our improvement list.
See also https://github.com/schemaorg/schemaorg/issues/1114
and
https://github.com/twamarc/ScheMed/issues/38

Please put in cc (for the medical |life sciences related issues) the ScheMed community.
https://www.w3.org/community/schemed/

**Comment by VladimirAlexiev** [comment]
#1736 shows examples where the lifesci extension has misappropriated common words like `action, warning, procedure, status`.

@twamarc Any progress on this?
