### ISSUE TITLE
nextItem vs. position

### ISSUE THREAD

**Issue by retog** [schemaorg/schemaorg#1518]
The description of `itemListElement` says to use `ListItem` with a 'position', however `ListItem` also has a 'nextItem' property. Is the creation of linked lists discouraged in schema.org?

**Comment by mfhepp** [comment]
When we originally designed the mechanism, we wanted to support two ways of modeling order, either by a linked list (aka nextItem etc.) or a simple literal with an implicit ordering relation (like position).

So from schema.org, both should work. 

The consumers of such markup might prefer one pattern over the other, of course.

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by jaygray0919** [comment]
If you have a moment Martin, would you analyze this request:
https://github.com/schemaorg/schemaorg/issues/1170

Many thanks,
/jay

**Comment by jvandriel** [comment]
During the original discussions about ```ItemList``` the following markup was discusses @jaygray0919:

```
<html>
    <body itemscope itemtype="http://schema.org/WebPage">
        <div itemprop="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
            <ol>
               <li id="ListItem-1" itemid="#ListItem-1" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                   <span itemprop="item" itemscope itemtype="http://schema.org/CollectionPage">
                       <a itemprop="url" href="http://example.com/books/">
                           <span itemprop="name">Books</span>
                       </a>
                   </span>
                   <link itemprop="nextItem" href="#ListItem-2">
               </li>
               <li id="ListItem-2" itemid="#ListItem-2" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                   <span itemprop="item" itemscope itemtype="http://schema.org/CollectionPage">
                       <a itemprop="url" href="http://www.example.com/books/authors/">
                           <span itemprop="name">Authors</span>
                       </a>
                   </span> 
                   <link itemprop="previousItem" href="#ListItem-1">
                   <link itemprop="nextItem" href="#ListItem-3">
               </li>
               <li id="ListItem-3" itemid="#ListItem-3" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                   <span itemprop="item" itemscope itemtype="http://schema.org/WebPage">
                       <a itemprop="url" href="http://www.example.com/books/authors/stephen-king/">
                           <span itemprop="name">Stephen King</span>
                       </a>
                   </span> 
                   <link itemprop="previousItem" href="#ListItem-2">
               </li>
            </ol>
        </div>
    </body>
</html>
```

Hope that helps.

**Comment by jaygray0919** [comment]
Am I missing a key point of your example @jvandriel ? Our issues is the limited domain for 'nextItem' in an ItemList. Does the example demonstrate that 'nextItem' can only be an 'ItemList'? We were hoping to expand the domain/range to include 'Thing' (as documentation implies). The answer may be that 'nextItem' has only one domain - ItemList. If that is the case, then we'll have to live with it.

**Comment by jvandriel** [comment]
> Does the example demonstrate that 'nextItem' can only be an 'ItemList'?

Not really. The example shows how its use was imagined when it was being discussed and created. Though as http://schema.org/nextItem shows, its domain and range are currently limited to ```ListItem``` (not ```ItemList```) as they are meant to be used to help express ordered lists of items.

Now whether or not that should stay that way is a whole different matter though. Over to #1170 to continue that discussion over there.
