### ISSUE TITLE
itemid attribute

### ISSUE THREAD

**Issue by Eyal-R** [schemaorg/schemaorg#1520]
Hi everybody,
I see that the attribute "itemid" is used a lot in examples in schema.org, for instance - see exmaple #1 in Book: https://schema.org/Book

However, I couldn't find any documentation about that in schema.org - can anybody please direct me to the documentation? (is it a prop field?)

Thanks,
Eyal

**Comment by dbs** [comment]
itemid is not a schema.org attribute; it is part of the microdata specification: https://html.spec.whatwg.org/multipage/microdata.html#attr-itemid

**Comment by Eyal-R** [comment]
Thanks a lot!
