### ISSUE TITLE
We should have more human readable terms and short names

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1523]
... in addition to our current "human readable labels" which are just a record of the exact term ID, i.e. the last part of the schema.org official URLs for each term.

See also https://lists.w3.org/Archives/Public/public-schemaorg/2017Feb/0023.html discussion thread.

**Comment by tfrancart** [comment]
Here is an automatically generated proposal of human labels based on the camel case identifier splitted :

[generate-sdo-label-from-camel-case.rq.txt](https://github.com/schemaorg/schemaorg/files/777890/generate-sdo-label-from-camel-case.rq.txt)

**Comment by RichardWallis** [comment]
@tfrancart's example is a good starting point, whilst working towards supporting labels and descriptions in multiple languages.

In Schema.org site coding terms, we could:

1. Run a one-off process to expand the current labels from camel case into a word separated string.  Note: I believe we have a current test that checks that the label matches the term id, that will need changing.

2. Introduce code to display the default label/description (not language tagged) when the user interface language (probably defaulting to english) is matched to a language tagged label/description.

3. Encourage interested groups to provide translations of labels/descriptions.  Maybe worth as a start looking at what the new 'intelligent' version of Google Translate can do.  I believe the current coding could support the use of separate language specific definition files for labels and descriptions only.

Of course introducing language specific versioning will open up requests for a totally language independent interface. ;-)

This work should probably be related to #721

**Comment by multimeric** [comment]
Agreed. The current `rdfs:label` triples should be space separated. camelCase makes sense in an IRI but not in a label, which should be designed for human comprehension. As a motivating example, how would we translate schema.org into other languages while it's in camelCase?

e.g.
```json
    {
      "@id": "schema:availableChannel",
      "@type": "rdf:Property",
      "rdfs:comment": "A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).",
      "rdfs:label": "availableChannel",
      "schema:domainIncludes": {
        "@id": "schema:Service"
      },
      "schema:rangeIncludes": {
        "@id": "schema:ServiceChannel"
      }
    }
```
