### ISSUE TITLE
occupancy property cannot be used on MeetingRoom

### ISSUE THREAD

**Issue by sumutcan** [schemaorg/schemaorg#1524]
Hi all,

It came to my attention that the occupancy property is used on these types: Apartment, HotelRoom, SingleFamilyResidence and Suite. However during a study we have been doing with hotels, I came across several occasions where the maximum occupancy of a meeting room is defined on the web pages.

An example is here : http://www.hotelamstephansplatz.at/en/meeting-rooms-vienna/

I can see that the type Room has only two subtypes, HotelRoom and MeetingRoom.  Is there any reason  that the type Room is not used in the domain of the property instead of HotelRoom?

Thanks
Umut

**Comment by danbri** [comment]
This seems reasonable, since the meaning is more or less the same. @mfhepp any thoughts?

**Comment by mfhepp** [comment]
No objections. I think it was initially that way and was removed when our original proposal was trimmed down as per Vicky's request.

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by sumutcan** [comment]
Hi,
any action needed for this issue?

Best
Umut

**Comment by mfhepp** [comment]
+1
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp
