### ISSUE TITLE
Resolving error - need help

### ISSUE THREAD

**Issue by vishysinghal** [schemaorg/schemaorg#1526]
Hi Guys, I am getting an error trying to resolve the following. Any help would be highly appreciated.

`<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "MusicAlbum",
  "name": "King of Limbs",
  "url":"/111/111",
  "byArtist": {
    "@type": "MusicGroup",
    "name": "Radiohead"
  },
  "track": {
    "@type": "ItemList",
    "numberOfItems": 8,
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "item": {
          "@type": "MusicRecording",
          "url":"/111/111",
          "name": "Bloom"
        }
      },
      {
        "@type": "ListItem",
        "position": 2,
        
        "item": {
          "@type": "MusicRecording","url":"/111/111",
          "name": "Morning Mr. Magpie"
        }
      },
      {
        "@type": "ListItem",
        "position": 3,
       
        "item": {
          "@type": "MusicRecording", "url":"/111/111",
          "name": "Little by Little"
        }
      }
    ]
  }
}
</script>``

**Comment by RichardWallis** [comment]
Hi @vishysinghal.

Formatting the code for readability (as below)  and pasting it in to one of the JSON-LD testing/translating tools (eg. [RDF Translator](http://rdf-translator.appspot.com/)) shows there is nothing structurally wrong with your data.  

Google's SDTT does highlight one issue with the data where you have used the same URL for all the items.  Providing different URLs and, for my sensibilities, correctly formatted ones - http://example.com/111, http://example.com/112, etc. fixes that.  

That then leads on to a report of the currently well discussed “_All values provided for url must point to the same page_” error from SDTT.

I point you at one of several blog posts that discuss and analyse this issue: https://dmytronikolayev.com/values-provided-url-must-point-page-problem-googles-sdtt/

Normally this list does not go into too much detail with the kind of direct help with implementation you were searching for. However I couldn't resist finding out what your problem was and then sharing the answer.
I will now close this issue.


```
<script type="application/ld+json">
{
	"@context": "http://schema.org",
	"@type": "MusicAlbum",
	"name": "King of Limbs",
	"url": "http://example.com/111",
	"byArtist": {
		"@type": "MusicGroup",
		"name": "Radiohead"
	},
	"track": {
		"@type": "ItemList",
		"numberOfItems": 8,
		"itemListElement": [
			{
				"@type": "ListItem",
				"position": 1,
				"item": {
					"@type": "MusicRecording",
					"url": "http://example.com/112",
					"name": "Bloom"
				}
			},
			{
				"@type": "ListItem",
				"position": 2,
				"item": {
					"@type": "MusicRecording",
					"url": "http://example.com/113",
					"name": "Morning Mr. Magpie"
				}
			},
			{
				"@type": "ListItem",
				"position": 3,
				"item": {
					"@type": "MusicRecording",
					"url": "http://example.com/114",
					"name": "Little by Little"
				}
			}
		]
	}
}
</script>
```

**Comment by vishysinghal** [comment]
Thanks for the reply.

the code seems to have error while testing with structured tool (google)
https://search.google.com/structured-data/testing-tool

**Comment by AmyManek** [comment]
Hi I am having issue with products and service page schema, Please check:
 <script type="application/ld+json">
       
    
            {
          "@context": "https://schema.org",
          "@type": "ItemList",
          "itemListElement": [
     
    {
      "@type": "ListItem",
      "position": 1,
      "item": {
                  "@type": "Product",
                  "image": "",
                  "url": "http://dev-airhawkac.pantheonsite.io/products/duct-work/",
                  "name": "Duct Work",
                  "description": "The duct work in your home is just as important as the equipment its connected to. A lot of the time duct work can be overlooked and rob performance from your high efficiency air conditioner."
        
            }    
    },   
         
    {
      "@type": "ListItem",
      "position": 1,
      "item": {
                  "@type": "Product",
                  "image": "",
                  "url": "http://dev-airhawkac.pantheonsite.io/products/ductless-split/",
                  "name": "Ductless Split System",
                  "description": ""
        
            }    
    },   
         
    {
      "@type": "ListItem",
      "position": 1,
      "item": {
                  "@type": "Product",
                  "image": "",
                  "url": "http://dev-airhawkac.pantheonsite.io/products/indoor-air-quality/",
                  "name": "Indoor Air Quality",
                  "description": ""
        
            }    
    },   
         
    {
      "@type": "ListItem",
      "position": 1,
      "item": {
                  "@type": "Product",
                  "image": "http://dev-airhawkac.pantheonsite.io/wp-content/uploads/rheem-1.jpg",
                  "url": "http://dev-airhawkac.pantheonsite.io/products/rheem/",
                  "name": "RHEEM",
                  "description": ""
        
            }    
    }    
             
  ]
}

    </script>
Its saying all URLs to redirect on same page and if I make all urls same then it is giving error of duplictae URLs.
Anyone can help me on this?

**Comment by bianqui149** [comment]
@AmyManek i am getting the same error any update?

**Comment by RichardWallis** [comment]
This channel is for discussion of the Schema.org vocabulary its structure and development and can not really help with individual implementation and the operation of tools provided by search engine organisations.

Beyond the useful blogpost on this issue: https://dmytronikolayev.com/values-provided-url-must-point-page-problem-googles-sdtt/

I suggest you direct these questions regarding the operation, and errors emanating from, Google's SDTT to the appropriate Google support forum.
Possibly:  https://productforums.google.com/forum/#!forum/webmasters

**Comment by dnikolayev** [comment]
Wow, Thnx @RichardWallis 
Now I know why traffic still goes to the post from the 2016 year :)
