### ISSUE TITLE
Type vs. subClassOf

### ISSUE THREAD

**Issue by ekkis** [schemaorg/schemaorg#1531]
hello everyone, I'm new to the project and have 3 questions:

1) am wondering as I look at the definition below:

```
        {     
          "@id": "http://schema.org/CommunityHealth",
          "@type": "http://schema.org/MedicalSpecialty",
          "http://schema.org/isPartOf": {
            "@id": "http://health-lifesci.schema.org"
          },    
          "rdfs:comment": "A field of public health focusing on improving health characteristics of a defined population in relation with their geographical or environment areas",
          "rdfs:label": "CommunityHealth",
          "rdfs:subClassOf": {
            "@id": "http://schema.org/MedicalBusiness"
          }     
        },    

```

is CommunityHealth a MedicalBusiness or a MedicalSpecialty? I mean, if an entity is of a certain type, then it's a subClass of that type, no? what is the semantic difference?

2) also, if I look in this page:

http://schema.org/docs/full.html

I see no MedicalSpecialty.  where do I find it?

3) where is the community? I logged into the IRC channel but it's empty, the mailing list for -contrib has zero traffic.  where do I meet others working on this project?

thanks in advance - e

**Comment by RichardWallis** [comment]
Hi @ekkis.

If you checkout the page for [CommunityHealth](http://health-lifesci.schema.org/CommunityHealth) you will see at the top its inheritance tree:
```
Thing > Intangible > Enumeration > Specialty > MedicalSpecialty :: CommunityHealth 
Thing > Intangible > Enumeration > MedicalEnumeration > MedicalSpecialty :: CommunityHealth
```
Note the '::' which indicates that it is an enumeration value for [MedicalSpecialty](http://health-lifesci.schema.org/MedicalSpecialty).  It is one of the many listed at the bottom of the page for that type.  So in answer to your question is that it is one of the enumerated types of MedicalSpeciality and hence can be used as one of the acceptable values for properties with MedicalSpeciality in their range.

The reason you do not initially see it in the [Full Hierarchy](http://schema.org/docs/full.html) listing is because it is defined in one of the extensions to Schema.org _[health-lifesci](http://health-lifesci.schema.org/)_.  This is noted at the top of the page describing the type.

The full listing page defaults to displaying only the core vocabulary.  If you select the _Core plus all extensions_ option you will find that it appears.

**Comment by ekkis** [comment]
my bad about not finding it.  I see it now, however, why is CommunityHealth a subclass of MedicalBusiness if it is a range value for MedicalSpecialty? in fact, neither of these pages: http://health-lifesci.schema.org/CommunityHealth, http://health-lifesci.schema.org/MedicalSpecialty contain a mention of MedicalBusiness at all

**Comment by ekkis** [comment]
as an adjunct question, if we look at:

```
        {
          "@id": "http://schema.org/MedicalSpecialty",
          "@type": "rdfs:Class",
[...]
          "rdfs:label": "MedicalSpecialty",
          "rdfs:subClassOf": [
            {
              "@id": "http://schema.org/MedicalEnumeration"
            },
            {
              "@id": "http://schema.org/Specialty"
            }
          ]
        },

```
why doesn't it have a `rangeIncludes` where it lists the values it enumerates e.g. `CommunityHealth`?

**Comment by ekkis** [comment]
also, to paraphrase my original question: I think of an entity's *type* as describing it to be a subclass of some other type.  so in essence, *subClassOf* and *type* are equivalent to my mind.  what is the distinction I'm missing here?

could we write:

```
        {     
          "@id": "http://schema.org/CommunityHealth",
          "@type": [
               "http://schema.org/MedicalSpecialty",
               "http://schema.org/MedicalBusiness"
          ]
```

as we write:

```
        {     
          "@id": "http://schema.org/CommunityHealth",
          "rdfs:subClassOf": {
            "@id": "http://schema.org/MedicalSpecialty",
            "@id": "http://schema.org/MedicalBusiness"
          }     
```
with equal meaning?

**Comment by rvguha** [comment]
Hope this example explains the difference:

DanBrickley --type--> BritishCitizen
BritishCitizen --subClassOf --> Person

BritishCitizen and Person are sets, with the former being a subset of the
later. Dan Brickley is an element of the former. DanBrickley is not a
subclass of either.

So, not DanBrickley --subClassOf --> BritishCitizen

**Comment by ekkis** [comment]
ah! DanBrickley is an instance of the `type`... that means that if I ever see both `type` and `subClassOf` then type better be `rdfs:Class`, as in the example of `MedicalSpecialty`.  makes perfect sense.  thank you!

what about my question regarding ranges and domains?

**Comment by thadguidry** [comment]
@ekkis What @rvguha forgot to further explain is that true, DanBrickley is not a subclass of either...but instead realize that he is an Instance of a BritishCitizen and an Instance of a Person.

For a quick primer of differences, you can look at Wikidata's Instance statement https://www.wikidata.org/wiki/Property:P31 and its description and scroll down to the See Also: [subclass of](https://www.wikidata.org/wiki/Property:P279)

**Comment by rvguha** [comment]
Yup, sorry, should have pointed that out.

guha

**Comment by ekkis** [comment]
ok, my assumption seems wrong.  this entity:
```
        {
          "@id": "http://schema.org/Oncologic",
          "@type": "http://schema.org/MedicalSpecialty",
          "http://schema.org/isPartOf": {
            "@id": "http://health-lifesci.schema.org"
          },
          "rdfs:comment": "A specific branch of medical science that deals with benign and malignant tumors, including the study of their development, diagnosis, treatment and prevention.",
          "rdfs:label": "Oncologic",
          "rdfs:subClassOf": {
            "@id": "http://schema.org/MedicalBusiness"
          }
        },
```
says it's an instance of type `MedicalSpecialty`, so it's not a class, it's an instance... yet, it indicates it's a sub-class of `MedicalBusiness`.  this doesn't make sense.  perhaps `MedicalSpecialty` is a subclass of `MedicalBusiness` but if so, that relationship shouldn't exist here.  so how does that work?

**Comment by ekkis** [comment]
here's another example that doesn't make sense to me:
```
        {
          "@id": "http://schema.org/SurgicalProcedure",
          "@type": [
            "http://schema.org/MedicalProcedureType",
            "rdfs:Class"
          ],
          "http://schema.org/isPartOf": {
            "@id": "http://health-lifesci.schema.org"
          },
          "http://www.w3.org/2002/07/owl#equivalentClass": {
            "@id": "http://purl.bioontology.org/ontology/SNOMEDCT/387713003"
          },
          "rdfs:comment": "A type of medical procedure that involves invasive surgical techniques.",
          "rdfs:label": "SurgicalProcedure",
          "rdfs:subClassOf": {
            "@id": "http://schema.org/MedicalProcedure"
          }
        },
```
so this is an instance of `MedicalProcedureType` but it's also a class... so it's both a class and an instance of something??? this can't be.  it's badly defined.  help?

**Comment by twamarc** [comment]
@ekkis. see the reply above from @rvguha and @thadguidry. From my end I am not quite sure I understand your concern about instance and class here. However if you asked specifically about RDFS based theory, yes.  This a very old discussion in semantic web- i will not restart it.
btw see some interesting discussions elsewhere:	http://stackoverflow.com/questions/35866473/is-it-correct-that-a-class-can-be-an-instance

**Comment by twamarc** [comment]
@ekkis: as I see you are interested in health-lifesci vocab. may I invite you to join the ScheMed community and share your thoughts, use-cases and suggestion please? https://www.w3.org/community/schemed/

**Comment by ekkis** [comment]
ok, thank you for all the support.  unfortunately, I think this project is not well suited to my needs.  I'll build my own ontology
