### ISSUE TITLE
Term reuse and name spaces

### ISSUE THREAD

**Issue by ekkis** [schemaorg/schemaorg#1533]
in this page: https://schema.org/docs/extension.html I find this assertion:

> we should not have the same term being reused to mean something completely different (e.g., we should not have two extensions, one using Bank to mean river bank and the other using Bank to mean financial institution)

which implies that extensions are not name spaces and don't segment the vocabulary.  this is problematic as it forces the terminology to embed namespace information in the term e.g. BankAsInFinancialInstitution vs. BankAsInRiparianLand instead of Industry:Finance:Institution:Bank vs. Geology:River:Bank

but the RDF does allow name spaces such that the term "Bank" can mean two different things depending on the context.  are there no name spaces in schema.org??

**Comment by ekkis** [comment]
another statement I find troublesome:

> Every item in the core (i.e., http://schema.org/) is also in every extension

in itself that seems perfectly logical, however, when I look at the core I see BuyAction, MovieClip, PresentationDigitalDocument and Festival, terms that clearly belong to domains I would never consider core.  terms like Class, Property, Event, etc. would seem like natural core terminology but I would put ComedyEvent (Event:Comedy) in an extension having to do with... I don't know... Industry:Entertainment?

so clearly the community views "core" differently than I do.  can anyone help explain to me how this makes sense?

and, sorry for all the questions.  I'm really hoping to leverage the work and the community for something more useful than marking up documents

**Comment by Dataliberate** [comment]
>  are there no name spaces in schema.org??

No.
Every term is defined within the http://schema.org space to prevent "the same term being reused to mean something completely different"

Extensions are a simple grouping of terms into sector related areas of interest to assist those searching for an appropriate item amongst the 1,500 plus available.

>RDF does allow name spaces

Yes, but we do not use them beyond everything being in the http://schema.org namespace.

As per my previous reply to #1532:
_With Schema.org we are not talking about an ontology to constrain how a data model is defined, we are talking about a vocabulary to identify how an Thing (instance of a Schema Type) can be described or marked-up on the web. The difference in implementation is subtle but important._

I understand that you are looking to utilise Schema.org in other ares.  However the millions of websites and approx 30% of web pages that use Schema.org to supply structured data representations of their contents and associated resources already find it very useful indeed.

If there are ways to capitalise on the thoughts you have, without adding complexity and thus barriers to use, by the thousands of current and future users that have no need or inclination to understand RDF and Linked Data etc. I am all for it.

Perhaps you might share what these 'more useful' areas might be.

**Comment by ekkis** [comment]
@Dataliberate, thanks for all the support.  I'm going to build my own ontology.  perhaps I could share it with you at some point for your thoughts?

**Comment by ekkis** [comment]
@Dataliberate I have something to show you.  would you be amenable to a Skype meeting?

**Comment by danbri** [comment]
"in itself that seems perfectly logical, however, when I look at the core I see BuyAction, MovieClip, PresentationDigitalDocument and Festival, terms that clearly belong to domains I would never consider core"

Yes, the core is large. It has volcanoes in it. Last year we made a large change by moving a *lot* of health/lifesci terms out into http://health-lifesci.schema.org/ - it is possible that we will do more of this. Schema.org's hosted extensions are essentially "tags" in almost the Web 2.0 sense, i.e. a lightweight mechanism that allows different views of a growing dictionary of terms.

>  RDF does allow name spaces 

We are very aware of this (I met @rvguha via the original W3C RDF work back in 1997-8). The idea of "external extensions" is closer to RDF-style namespaces, e.g. see [http://GS1.org/voc/](http://GS1.org/voc/) which from schema.org's point of view is an external extension, but from GS1's perspective can equally be considered its own vocabulary (and schema.org then becomes an extension of GS1). Either way, both vocabularies can still be processed as RDF (e.g. in SPARQL) and represented in RDF-oriented formats like RDFa, JSON-LD. Part of the motivation behind schema.org was a sense that beginning with RDF-style namespaces had led to excessive modularization, and that this had made things too hard for publishers.

I'm going to go ahead and close out this issue as it isn't immediately actionable, but that needn't stop the conversation here.

**Comment by ekkis** [comment]
@danbri, thanks for the feedback.  would you be interested in having a look at what I'm building?
