### ISSUE TITLE
Suggestion for Text as new subtype for CreativeWork

### ISSUE THREAD

**Issue by mfenner** [schemaorg/schemaorg#1535]
I am converting metadata using the [DataCite schema](http://schema.datacite.org/) back and forth to schema.org. One particular challenge is the mapping of the `@type`, called `resource-type-general` at DataCite and based on Dublin Core. I have a problem with mapping the very common `Text`, which DataCite and Dublin Core describe as `A resource consisting primarily of words for reading.` What is the appropriate type in schema.org? I only seem to find either the too generic `CreativeWork`, or the more specific `Article`, `Book`, `Review`, `Webpage`, etc. Or does schema.org need a new subtype of `CreativeWork` called `Text` (or named differently) for textual resources? At this point I don't need any specific properties.

**Comment by Dataliberate** [comment]
I have come across other situations, in the area of archives, that ideally needs something similarly generic and yet textual, that fits between **CreativeWork** and the more specific **Article**, **Book**, etc.

The though in that circumstance I had was for a **Document** type with a simple definition of _A text document._

**Comment by mfenner** [comment]
How would *Document* relate to *DigitalDocument* and *TextDigitalDocument*? Is a *TextDigitalDocument* an `exampleofWork` of a *Document/Text*? Do you worry that people get confused?

**Comment by Dataliberate** [comment]
I always worry that people will get confused!

The original suggestion for _Document_ predated the introduction _DigitalDocument_ & _TextDigitalDocument_.   

Looking at the descriptions of all three now, I would suggest that _TextDigitalDocument_ would become a subtype of both _Document_ and _DigitalDocument_.

I would not see exampleOfWork  having any special role here.

**Comment by mfenner** [comment]
@Dataliberate what are your thoughts regarding using **Text**, as used by Dublin Core (and DataCite). Or maybe **TextDocument**? **Document** is probably fine, but in common understanding often is not limited to textual documents (as you can see in the different flavors of **DigitalDocument**).

**Comment by RichardWallis** [comment]
**Text** would clash with the _[Text](http://schema.org/Text)_ DataType

I did consider **TextDocument** but concluded that it in edge cases it might introduce unnecessary confusion around documents that contained drawings, sketches, plans etc. 

I can understand the motivation in the digital world as the type can influence how they are handled.

**Comment by mfenner** [comment]
@RichardWallis this makes sense. I am all for **Document** then.
