### ISSUE TITLE
Consider menuAddOn property (+move proposed design into Pending)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1541]
Spin-off from discussion in #1288 around menus and menu items: the proposed menuAddOn piece of that design needs further discussion.

http://webschemas.org/menuAddOn

> "Additional menu item(s) such as a side dish of salad or side order of fries that can be added to this menu item. Additionally it can be a menu section containing allowed add-on menu items for this menu item."

Per #1288, decision is to move that property into Pending, the rest has rough consensus and is going directly into Core.

/cc @gmackenz

**Comment by gmackenz** [comment]
Agree completely with decision on menuAddOn.


Gordon Mackenzie |  Schema Wrangler (Ontologist) |  gmackenz@google.com |

**Comment by danbri** [comment]
http://webschemas.org/menuAddOn should reflect this change imminently.

**Comment by DDeering** [comment]
I know it's pending and I hate to be a stickler about it, but I'm still against using "menuAddOn" as the name of the property.  The term implies that something is being added to the menu.  But we're not using it to add something to a menu, we're adding something to a menu _item_.  So, wouldn't something like "menuItemAddOn" or "itemAddOn" be a more appropriate name for the property?

I apologize, @danbri and @gmackenz but I just think that the proposed property name would be confusing to users and wouldn't appropriately reflect its intended use.

**Comment by thadguidry** [comment]
I'm also for changing the name to itemAddOn to be less confusing. I worry
also like David.

**Comment by DDeering** [comment]
@danbri  Could we move forward with this property but name it "itemAddOn" instead of "menuAddOn"?

**Comment by gmackenz** [comment]
I wonder if 'itemAddOn' isn't just as confusable with '[addOn](http://schema.org/addOn)', I am not opposed to the notion of renaming to menuItemAddOn. That said, I don't think this is ever leaving pending anytime soon.

**Comment by DDeering** [comment]
Personally, I think that "itemAddOn" is rather clear and straightforward but I'm open to calling it whatever the majority chooses as long as it's not "menuAddOn" for the reasons I mentioned above.

**Comment by blerimj** [comment]
How do you solve the problem of MenuItem having multiple size offerings. I.e. Cheese Pizza small , Cheese Pizza Large and the price of toppings (menuItemAddOns) depend on the selection - small or large.

**Comment by danbri** [comment]
itemAddOn doesn't work well, since it is too generic and this property *is* all about menus and food

We are seeing it on a fair number of sites. It is a tiny change left over from the other menu work, let's stick it in the core rather than leaving it dangling.

**Comment by RichardWallis** [comment]
Implemented in [release 3.5 ](https://schema.org/docs/releases.html#v3.5)

**Comment by gregg-cbs** [comment]
How do we make use of this?
