### ISSUE TITLE
Release details page is missing for 3.2

### ISSUE THREAD

**Issue by AymenLoukil** [schemaorg/schemaorg#1544]
Clicking on 3.2 on the releases page gives 404 error 
[http://webschemas.org/version/3.1/](http://webschemas.org/version/3.2/)

**Comment by danbri** [comment]
Yup, thanks - we do a round of this at the very last step to make sure it is up to date. There's a (hopefully reasonably accurate) todo list at https://github.com/schemaorg/schemaorg/blob/sdo-callisto/RELEASING.TXT
