### ISSUE TITLE
Cleanup of terms that differ only in case

### ISSUE THREAD

**Issue by rvguha** [schemaorg/schemaorg#1545]
There are still some pairs of terms (such as 'Event' and 'event'), that are different but differ only in case. In my conversations with prospective users, this can be confusing. As far as I can make out, terms like lower case 'event' don't have as much adoption. Further, it is likely that at least 'event' uses should have been 'Event'.

I would like to clean things up so that we don't have such pairs.

Thoughts?

Guha

**Comment by danbri** [comment]
I also think it is time to clean this up. For one of several recent examples of confusion, I noticed colleagues mixing up these due to (very common) assumption that case does not matter.

In recent cases when a more natural name for a property was not available, we have used the "hasFoo" and "Foo" pattern. I suggest we migrate properties to that. We have previously changed many property names by retaining the old one and marking it "supersededBy" the new; we would do the same here.

I'll try a SPARQL query to find the current list... see also https://github.com/schemaorg/schemaorg/wiki/BlazeGraphSPARQLHowto or http://dydra.com/danbri/schema-org-3-1-sdo-makemake/

A subtask would then be to add a unit test so we don't slip in any new property/type pairs that downcase to the same string.

**Comment by danbri** [comment]
see http://dydra.com/danbri/webschemas-org/@query 

I think this misses any where the property/type pair straddles two graphs (aka hosted extensions or core).

```select ?term1 ?term2 ?g where { 
{ graph ?g {
 ?term1 ?a rdfs:Class .
 ?term2 ?a rdf:Property .
 FILTER ( ?term1 != ?term2 ) .
 FILTER ( lcase(str(?term1)) = lcase(str(?term2)) ).
 } 
} 
union {?s ?p ?o} } limit 10



Results:

```http://schema.org/AggregateRating	http://schema.org/aggregateRating	http://schema.org/#3.2
http://schema.org/Duration	http://schema.org/duration	http://schema.org/#3.2
http://schema.org/ContactPoint	http://schema.org/contactPoint	http://schema.org/#3.2
http://schema.org/Drug	http://schema.org/drug	http://health-lifesci.schema.org/#3.2
http://schema.org/Brand	http://schema.org/brand	http://schema.org/#3.2
http://schema.org/Comment	http://schema.org/comment	http://schema.org/#3.2
http://schema.org/Audience	http://schema.org/audience	http://schema.org/#3.2
http://schema.org/Event	http://schema.org/event	http://schema.org/#3.2
http://schema.org/DoseSchedule	http://schema.org/doseSchedule	http://health-lifesci.schema.org/#3.2
http://schema.org/InfectiousAgentClass	http://schema.org/infectiousAgentClass	http://health-lifesci.schema.org/#3.2

**Comment by danbri** [comment]
Ok the above was an underestimate - see http://dydra.com/danbri/webschemas-org/@query#case-screwups-v2 for a load more examples

**Comment by danbri** [comment]
http://schema.org/Action
http://schema.org/AggregateRating
http://schema.org/Audience
http://schema.org/Brand
http://schema.org/BusinessFunction
http://schema.org/Code
http://schema.org/Collection
http://schema.org/Comment
http://schema.org/ContactPoint
http://schema.org/Course
http://schema.org/Dataset
http://schema.org/DayOfWeek
http://schema.org/DeliveryMethod
http://schema.org/Diet
http://schema.org/Distance
http://schema.org/DoseSchedule
http://schema.org/Drug
http://schema.org/DrugClass
http://schema.org/Duration
http://schema.org/EntertainmentBusiness
http://schema.org/Episode
http://schema.org/Event
http://schema.org/ExercisePlan
http://schema.org/FoodEstablishment
http://schema.org/FoodEvent
http://schema.org/Game
http://schema.org/GameServer
http://schema.org/InfectiousAgentClass
http://schema.org/Language
http://schema.org/Map
http://schema.org/MedicalSpecialty
http://schema.org/MedicineSystem
http://schema.org/Menu
http://schema.org/Nerve
http://schema.org/OpeningHoursSpecification
http://schema.org/OrderStatus
http://schema.org/PaymentMethod
http://schema.org/PriceSpecification
http://schema.org/Question
http://schema.org/RealEstateAgent
http://schema.org/Recipe
http://schema.org/Review
http://schema.org/Season
http://schema.org/Specialty
http://schema.org/SportsActivityLocation
http://schema.org/SportsEvent
http://schema.org/SportsTeam
http://schema.org/Text
http://schema.org/URL
http://schema.org/WarrantyPromise
http://schema.org/WarrantyScope

**Comment by rvguha** [comment]
http://schema.org/Menu gives me a 404.

Can we sort these (both cases) by number of uses? We can then decide what
to do with each. SportsEvent usage for example is much more than that of
sportsEvent. Duration on the other hand is hardly used compared to duration.

guha

**Comment by danbri** [comment]
@rvguha Menu is queued up in the current proposed release, so on the staging site: http://webschemas.org/Menu

Agree re case by case

**Comment by danbri** [comment]
@RichardWallis - can you take a look at this - maybe a quick python notebook with sparql against the latest data dumps to see where we are? (I don't think we should depend on dydra for workflow, it seems un-maintained)
