### ISSUE TITLE
Need a "Schema.org example" type

### ISSUE THREAD

**Issue by JoeUX** [schemaorg/schemaorg#1547]
Search engines often have trouble discriminating between actual content and examples of that content. By _example_, I mean in the context of an article or tutorial where someone would present an example of X.

When X is Schema.org syntax, it would help to be able to mark it up as such, so that when I write an article giving example markup for a book, say using _Grapes of Wrath_ as the example, people who are actually searching on _Grapes of Wrath_ don't end up landing on my article, which is not what they would want.

Conversely, it would be nice if people searching for _Schema.org examples_ found them.

So I propose a `SchemaOrgExample` type under `Intangible`, or possibly under `CreativeWork`. One of the properties should be `SyntaxLanguage`, with possible values of `Microdata`, `RDFa`, and `JSON-LD`. This would be a huge help in partitioning off real content from example content.

**Comment by thadguidry** [comment]
@JoeArizona perhaps just a more abstract type name that could be used for other domains and usecases as well, not just for SchemaOrg ? Such as a type called CodeExample ?  Let's think bigger than just us.

**Comment by AymenLoukil** [comment]
Yeah, or may be CodeSnippet

**Comment by thadguidry** [comment]
@AymenLoukil we try to use Simple English whenever we can in Schema.org ...and when there is common lingo we usually just add that into the description... so it could look like:

type: CodeExample
description: example lines of code or a block of code or code snippet

**Comment by AymenLoukil** [comment]
Oh sorry didn't knew that the word snippet is not Simple English :) 
Ok but https://schema.org/citation may also include code examples,, what do you think ? @thadguidry @JoeArizona

**Comment by JoeArizona** [comment]
Sure, that makes sense. I meant to say something about a broader example type, but got distracted. Code seems like an overly narrow bucket if we're going to think broadly. A lot of example content won't be code – this is a deep meta dimension that might cut across lots of instructional and tutorial content. To make the type most useful for search, it needs to cleanly partition content that is about X from content that is not about X but incidentally uses X in an example.

The more granular reduction is _populating fields or data with otherwise meaningless examples_. So it doesn't seem to be about code _per se_, but about data stand-ins. In English we sometimes use genericisms for this, but much of the time we don't:

- Instead of saying Anytown, USA, people might say Boston, but the post has nothing to do with Boston.
- Instead of saying widgets, people might say "imagine you're selling Teslas" but the post has nothing to do with Teslas.
- Instead of saying foo and bar (which I completely despise as wildly unsemantic and terrible for teaching people who aren't English speakers, or even those who are), people might put ConjunctionFunction as their function name, and drag in a bunch of searchers looking for the song or whatever that is (Sesame Street? I'm drawing a blank.)

**Comment by thadguidry** [comment]
@JoeArizona right...an example... "hey, I was just giving an example....I didn't literally mean Boston the city you stupid computer / search engine".

So we know that want to say the type is some kind of Example... but what more ?  Is that it ?
Think like a computer...what are you telling it about an Example ? To not take me literally about my Example content and treat the content purely as a Type of Example.
Do we have a need for lots of sub types of Examples ?  Sure we do.
How would Schema.org handle lots of sub types of Examples ?  With MTE's (Multi Type Entities)

type: Example, Code
description: This is my hacked version of Ruby code using Schema.org syntax in places

type: Example, Dataset
description: This is a modified dataset for OpenRefine to use for Tutorials. It has not real data values.

type: Example, Event
description: We are undecided what kind of event we will ultimately need.  For now this is just our proposal until we work things out with our Vendor.

So answer a few questions from me to be clear about the use case:
All of the above would be Type: Example ... So to a computer or consuming app or search engine...
the content within that Type would not be....what? indexed? something else? not really useful so don't even parse this section of content ?

**Comment by JoeArizona** [comment]
I just realized that there's a potentially catastrophic incentive problem in the way I was framing it. This markup would have the interesting property of _reducing your traffic_ if all it did was tell search engines to not treat the contents of the snippet as substantive content.

How and when we expect publishers and bloggers to richly annotate non-product content is an interesting issue that I haven't thought much about. In any case, this type demands more symmetry than I was giving it earlier. There needs to be an exampleOf property, a way for them to tag this content as an example of a shopping cart or an example Ethereum contract or whatever they're discussing. I assume there are a massive amount of searches for examples of everything. I'm no expert, but I imagine the traffic win from being able to explicitly call out that they're presenting an example of something will generally be greater than the traffic loss from eliminating the spurious hits.

I wrote the above before you replied. To answer your question, the value of exampleOf needs to be open-ended, just like a name or a title of a creative work. It's going to be a string that in many cases will be obvious, and in some cases they might have to ponder a bit. It's basically just the topic, which we have on other types, like what an Article is about and so forth. There are lots of example shopping carts, JavaScript promises, knitted sweaters, etc. and the values would just be shopping cart, JavaScript promise, knitted sweater, etc.

It might be useful to have categories, as you sketched out, and the open-ended value, but I'd have to think about it a lot before I have much useful to say about that.

**Comment by Dataliberate** [comment]
A generic _Example_ Type seems to be a pragmatic solution - as @thadguidry describes, the use of MTEs will allow most anything to be described as an example of something else.

I also agree that we will need an _exampleOf_ property.  However I don't agree that it will necessarily often be a string value.  It should be encouraged (by property description and examples) for URLs to be used to link to the _Thing_ that the example is an exemplar of.

**Comment by tymakhadija** [comment]
Hello,
please any one here can help me to get the dataset that they are working on ???
