### ISSUE TITLE
SearchAction example uses "query-input" property that is not defined

### ISSUE THREAD

**Issue by dbs** [schemaorg/schemaorg#155]
http://schema.org/SearchAction
http://schema.org/Action
http://schema.org/query
http://schema.org/potentialAction

From @dbs: "This was pointed out/buried in #53 in the long list of problems with the samples, but one of the examples for SearchAction happens to use "query-input" instead of the defined "query" property--and this is problematic because it also happens to be one of the most visible and interesting JSON-LD schema.org action examples for webmasters. I assume this is because Google's Site Search Links feature uses "query-input" (https://developers.google.com/webmasters/richsnippets/sitelinkssearch). We could adopt it in schema.org, but that property name doesn't follow the normal schema.org camelCasing conventions. So the right thing to do would be to fix the example and get Google to update its documentation (and potentially its implementation) to accept the correct property."

The problem here is that http://schema.org/docs/actions.html defines a magic property-like syntax for use with potentialAction, but the documentation is rather hidden away and could be better explained.

**Comment by danbri** [comment]
http://schema.org/Action now points to the blog post and the /docs/action.html doc.

I don't think there's an issue here; rather the concern is with weak documentation of the Actions mechanism (to which I'd include 404-handling of these pseudo-properties). So I'll mark this as a wontfix and let's continue within https://github.com/schemaorg/schemaorg/issues/220

Thanks Dan!

**Comment by danbri** [comment]
I've updated the description, reclassifying this as an area where we expect to clean up our documentation to clarify what's happening with these potentialAction pseudo-properties.

**Comment by danbri** [comment]
FYI per #6 I've updated the 404 handler in sdo-gozer to respond slightly more helpfully to http://sdo-gozer.appspot.com/price-input and similar. Also /Person/Minister/Foo.  Leaving issue open as this could still be better documented.

**Comment by danbri** [comment]
FYI http://schema.org/query-input now has a sensible custom 404 handler. I'll close the issue out now, I think the general need for better documentation is appreciated.
