### ISSUE TITLE
Political Rhetoric Vocabulary

### ISSUE THREAD

**Issue by rvguha** [schemaorg/schemaorg#1556]
There is a project I am involved in, that requires vocabulary to describe the content on sites such as presidency.ucsb.edu and millercenter.org. 

We need some vocabulary related to political rhetoric. Some of this is US centric. One could argue for portions of this being in the core.

We would like feedback.

guha

Political Rhetoric Vocabulary

New subClass of CreativeWork: Speech, Legislation, PressRelease, USPresidentialStatement, Proclamation

New subClass of Speech: InauguralAddress, CollegeCommencementAddress, PartyConventionAddress, UnitedNationsAddress

New subClass of Event: PressEvent

New subClass of USPresidentialStatement: USPExecutiveOrder, USPStateOfUnionAddress, USPProclamation, USPInauguralAddress, USPPressEvent [PressEvent], USPFireSideChat, USPRadioAddress, USPStateOfUnionAddress [Speech], USPInauguralAddress [InauguralAddress], USPVetoMessage

(terms inside the square parens are additional super classes)

**Comment by RichardWallis** [comment]
Initial high-level thoughts

**Political Rhetoric Vocabulary**
I can see the need for describing these things and similar concepts. For example executive statements and announcements at company meetings, shareholder meetings, launch events etc.  So focusing in on this narrow use case may miss the potential to add broad value to the vocabulary.

- Speech - _candidate for core vocab_

- Legislation - _much previous work in this area: Issues #980, #1154, #1156, #1363, PR #1380._

-  PressRelease - _candidate for core vocab_
- USPresidentialStatement - _do we really need a whole Type just for these?  Looks like an overspecialisation of a potential generic _OfficialAnnouncement_ type_
-  Proclamation  - _looks like an overspecialisation of a generic _OfficialAnnouncement_ type_

- New subClass of Speech: InauguralAddress, CollegeCommencementAddress, PartyConventionAddress, UnitedNationsAddress - _these look more like enumeration values of a _speechType_ property._

- New subClass of Event: PressEvent - _OK_

- New subClass of USPresidentialStatement: USPExecutiveOrder, USPStateOfUnionAddress, USPProclamation, USPInauguralAddress, USPPressEvent [PressEvent], USPFireSideChat, USPRadioAddress, USPStateOfUnionAddress [Speech], USPInauguralAddress [InauguralAddress], USPVetoMessage - _Again these look more like enumeration values of a _speechType_ or _announcementType_ property.  Others could include PoliticalStatement, PoliticalManifesto._ 

For potential enumerated values as mentioned above, traditional advice in this forum would be to look to external authoritative sources such as Wikidata

**Comment by rvguha** [comment]
Thanks for the detailed feedback. 

It is probably best to leave Legislation out of this (meant to remove it before cutting and pasting, but forgot).

The reason for having these as categories vs external enumerations --- has to do with applications such as Google Custom Search (GCSE). GCSE can restrict search by Schema type, but doesn't do anything with enumerations. Since the point of schema.org markup is to enable applications, we need to be cognizant of these when designing the vocabulary.

Could you point me at the Wikidata list that contains the different possible values of speechType?

**Comment by thadguidry** [comment]
@RichardWallis @rvguha http://schema.org/Quotation could then add a new property called "fromSpeech" or similar.  Then we complete the circle of life for Lincoln's Gettysburg Address and various quotes from it.
