### ISSUE TITLE
mirror schema.org's schema description in china

### ISSUE THREAD

**Issue by lidingpku** [schemaorg/schemaorg#1561]
@danbri 

schema.org is blocked in China, such that web browsers are unable to view schema definition.   is there any plan ? 

P.S. I'm thinking about mirroring the current (v3.1) schema.org schema definition on a site which is accessible in china, any concern?

**Comment by rvguha** [comment]
Please go ahead. Thank you for doing so.

Guha

**Comment by danbri** [comment]
Yes, a mirror would be great. Note that @RichardWallis and I have been discussing a move to using more static file generation for the site, after which it should be easier to mirror all/most of it more easily. But starting with the 3.1 summary would be a great start.

**Comment by danbri** [comment]
@lidingpku  can you check whether http://webschemas.org/docs/releases.html visible in China?

**Comment by lidingpku** [comment]
@danbri  

no luck.  can even access the IP behind domain name.  Is the domain hosted at google app engine?  

> <script type="text/javascript" src="//www.google.com/jsapi"></script>
> <script type="text/javascript">
>   google.load('search', '1', {language : 'en', style : google.loader.themes.ESPRESSO});
>   google.setOnLoadCallback(function() {
>     var customSearchControl = new google.search.CustomSearchControl('013516846811604855281:nj5laplixaa');
>     customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
>     var options = new google.search.DrawOptions();
>     options.enableSearchboxOnly("../docs/search_results.html", null, false, '#');
>     customSearchControl.draw('cse-search-form', options);
>   }, true);
> </script>
>

**Comment by danbri** [comment]
yes, appengine

**Comment by lidingpku** [comment]
@danbri  google IP addresses are blocked, now I'm running a minimal mirror of schema.org,  http://cnschema.org
