### ISSUE TITLE
Schema.org documentation issue: example contains property not containing in a type

### ISSUE THREAD

**Issue by e-orlov** [schemaorg/schemaorg#1564]
An example for https://schema.org/FinancialProduct includes _amount_, which seems not to be a property of FinancialProduct. Or is it?

**Comment by RichardWallis** [comment]
Well spotted.

_amount_ is not a property of _FinancialProduct_ the examples need correcting.

**Comment by e-orlov** [comment]
pretty sad -  some more specific types of FinancialProduct, like LoanOrCredit, do have it. Maybe it worth to implement it for FinancialProduct as their generic term too?

**Comment by RichardWallis** [comment]
Something to be reviewed when applying the 'fix' ....
