### ISSUE TITLE
Avatar example in docs/gs.html contradicts itself -URLs should match 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1570]
![sdo-bug](https://cloud.githubusercontent.com/assets/170265/24415120/b4a0df98-13e0-11e7-8483-95fff76766c2.png)

http://schema.org/docs/gs.html

**Comment by brezelman** [comment]
Just noticed the same irritating description. This should be reopened and addressed.

I want to add: 

> Search engines can now understand […] that […] is a URL

is also misleading, because search engines definitely don't need the schema information to know that a href attribute value is (most likely) an URL.

**Comment by RichardWallis** [comment]
@brezelman - what it is saying is that in addition to being aware that the value is a URL linking to something, a search engine will now also be aware that the something is a trailer to the movie being described.

**Comment by brezelman** [comment]
> @brezelman - what it is saying is that in addition to being aware that the value is a URL linking to something, a search engine will now also be aware that the something is a trailer to the movie being described.
I understood "can now understand not just this, but also that" as "can now understand this and that". If this isn't a valid transformation, feel free to ignore this remark. The original statement of this issue is the important one here.
