### ISSUE TITLE
docs/sitemap.xml contains wrong updated date

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1571]
<lastmod>2017-01-19</lastmod> whenever buildSitemap.py is run

**Comment by AymenLoukil** [comment]
Yes @RichardWallis it should be the real last update date for each URL.

**Comment by Dataliberate** [comment]
Yup - thats why I raised the issue.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw
