### ISSUE TITLE
Sitemap.xml is listing subdomains URLS

### ISSUE THREAD

**Issue by AymenLoukil** [schemaorg/schemaorg#1572]
Actual sitemap.xml is listing subdomain URI such as : http://pending.schema.org/* locations.

Sub-domains should present different contents so for example [http://pending.schema.org/](http://pending.schema.org) should be considered as a separate website and should has its own sitemap.xml file

**Comment by RichardWallis** [comment]
This format passed the tests it was submitted to.

Looking to tune things up in the next release so we will review what reports we get from search engines after a few weeks.

**Comment by unor** [comment]
[Relevant section from the Sitemaps protocol](https://www.sitemaps.org/protocol.html#location):

>  Note that this means that all URLs listed in the Sitemap must use the same protocol (http, in this example) and reside on the same host as the Sitemap. For instance, if the Sitemap is located at `http://www.example.com/sitemap.xml`, it can't include URLs from `http://subdomain.example.com`.
