### ISSUE TITLE
Document how to describe infographics

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1575]
Whether with existing vocabulary or additions. Some but not all infographics are related to news articles. Some are static, but they might be interactive. Many of our patterns for describing datasets are relevant. It should be possible to tie infographics back to source papers, datasets etc.

Concrete usecases and specific infographic examples would be very useful at this point.

**Comment by hekl** [comment]
I would support a new creativeWork type for infographics or visualisations of figures. 
They have lots of things in common with images and datasets, and are usually based on a dataset. Still, when describing them I have used several schema.org properties and did not yet needed a special new property for them. I don't know if that is a precondition for creating a new type. One could also think of special properties like interactivity. We do use them in news articles, but also separately, as small applications.

Examples from my Statistics Netherlands (CBS) institute:
https://www.cbs.nl/nl-nl/nieuws/2017/31/meer-goederenvervoer-per-spoor-vooral-naar-italie
