### ISSUE TITLE
Add a new type EmployerReview as a more specific type of Review

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#1576]
We currently have [Review](http://schema.org/Review) and I would like to propose a new more specific type EmployerReview for reviews pertaining organizations being reviewed by an employee.

Description: "A review written by a current or former employee of an organization. The review is in the context of the organization as an employer."

**Comment by rvguha** [comment]
Do you have any ideas of who will sign up to use it?

guha

**Comment by gmackenz** [comment]
I don't in particular know offhand at the moment but it would be a great way to easily isolate job-related reviews from the default review markup of employers such as is available on sites that provide/allow posting of employee reviews.

**Comment by rvguha** [comment]
It would be good to get some folks from sites that have these kinds of
reviews involved in the design of the vocabulary.

guha

**Comment by thadguidry** [comment]
@gmackenz Are we talking something like CompanyReviews like what Glassdoor.com etc. provides ?  Those kind of EmployerReviews ?

**Comment by danbri** [comment]
Let's route this into pending.schema.org for a while, to give time for publishers and consumers to unveil themselves. I am happy with this pattern of contextualized Review sub-types. It isn't elegant but it is simple for publishers and adds clarity. 

(@thadguidry - yeah I believe those kinds of reviews)

**Comment by gmackenz** [comment]
@thadguidry — what @danbri said — I think those kind of sites could be excellent candidates for EmployerReview.

**Comment by danbri** [comment]
@gmackenz I'll code this up. Do you have any definition text in mind, Gordon?

**Comment by danbri** [comment]
Ah sorry, I see it now!

**Comment by danbri** [comment]
Something like...

```
<div>
  <div typeof="rdfs:Class" resource="http://schema.org/EmployerReview">
    <span>Subclass of: <a property="rdfs:subClassOf" href="http://schema.org/Review">Review</a></span>
    <span class="h" property="rdfs:label">EmployerReview</span>
    <span property="rdfs:comment">An [[EmployerReview]] is a review of an [[Organization]] regarding its role as an employer, written by a current or former employee of that organization.</span>
    <span property="schema:category">issue-1576</span>
    <a property="dc:source" href="https://github.com/schemaorg/schemaorg/issues/1589">#1576</a>
    <link property="http://schema.org/isPartOf" href="http://pending.schema.org" />
  </div>
</div>

**Comment by danbri** [comment]
-> http://webschemas.org/EmployerReview

**Comment by gmackenz** [comment]
LGTM. Simple, short, to the point.


Gordon Mackenzie |  Schema Wrangler (Ontologist) |  gmackenz@google.com |

**Comment by thadguidry** [comment]
@gmackenz what ?  I'm confused.  Was your comment here about LGTM supposed to land on this issue or another one ?

**Comment by thadguidry** [comment]
@danbri what if we sorta tweak the definition of reviewBody...  "the main body section of the review".  more Simple English.  or do you think that will confuse with the term "main" and folks might think "what do I use for my other review sections?"

**Comment by gmackenz** [comment]
Another one evidently...


Gordon Mackenzie |  Schema Wrangler (Ontologist) |  gmackenz@google.com |
