### ISSUE TITLE
Add an estimatedSalary property to JobPosting

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#1577]
[JobPosting](http://schema.org/JobPosting) currently has baseSalary but it would be advantagous to have also an estimated salary property as well—when such an estimate is provided by sources outside of the organization offering the job posting.

[estimatedSalary](http://schema.org/estimatedSalary): A property describing the estimated salary for the job posting based on a variety of variables including, but not limited to industry, job title, and location. The estimated salary is usually computed by outside organizations and therefore the hiring organization is not bound to this estimated salary.

Expected types should be similar for that of baseSalary: MonetaryAmount, Number, or 
PriceSpecification

**Comment by danbri** [comment]
I've just moved the Occupation vocabulary (which also included a version of this) into the core. The definition here is more comprehensive, if a little verbose. I will merge them and then remove this from the Pending area.

**Comment by danbri** [comment]
I'm tweaking it to:

> An estimated salary for a job posting based on a variety of variables including, 
but not limited to industry, job title, and location. Estimated salaries 
are often computed by outside organizations rather than the hiring 
organization, who may not have committed to the estimated value.
