### ISSUE TITLE
Please help to multi Products in one page

### ISSUE THREAD

**Issue by CollaiderKV** [schemaorg/schemaorg#1583]
1. Help to be defined: there is a page on which there is a table in which in TR goods with the different prices and suppliers are listed (in an investment an example). We shared opinions whether to make out the block in "Products" or through something else. In an official source (https://schema.org/Product), it seems, there are no mentions that on the page there have to be one goods in "Products". As you consider how it will be better?

Table for markup
![entable](https://cloud.githubusercontent.com/assets/26891626/24643113/f298f790-1935-11e7-9711-47a815f5f828.gif)

Current markup
![schema](https://cloud.githubusercontent.com/assets/26891626/24643126/0030dbfc-1936-11e7-948f-fbb4dca6d5ca.gif)

2. Whether there will be a mistake that on one page there be several Products blocks?
3. If the option doesn't approach what it is better to use?

**Comment by CollaiderKV** [comment]
Maybe I'm posted not there? :)
One day passed...

**Comment by wiesmann** [comment]
As far as I know, having multiple products per page is ok. 
I would recommend the following for your markup:

- Populate the 'name' field for the manufacturer, not 'brand'.
- Availability should be defined with the proper enum, not the localised name.
- Delivery lead time should be a QuantitativeValue you probably want to min-value to 5 and max-value to 6 and the unit to days (UN/CEFACT code 'd').

**Comment by CollaiderKV** [comment]
wiesmann, I thank you for the answer. I will finish the existing marking considering your comments.
