### ISSUE TITLE
Sometimes either the HTTP or the HTTPS page is missing parent types

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1584]
Currently http://schema.org/Article is missing the parent types in the breadcrumb and in the table:

![schema org_article_missing-parents](https://cloud.githubusercontent.com/assets/6901294/24712345/e37cc3e8-1a22-11e7-8d8f-1a605985dc12.png)

On https://schema.org/Article it works correctly.

**Edit** (a few hours later): Works again. I’ll leave this open in case there’s something that would need fixing.

**Comment by maikwosnitzka** [comment]
This seems to be a general bug. 
Currently happening for https://schema.org/Person, while working on http://schema.org/Person.

Sometimes the parent types are missing using https, while it works using http (or the other way around).

**Comment by unor** [comment]
And currently happening for `Organization`.

Got reported on the mailing list, too:  
https://lists.w3.org/Archives/Public/public-schemaorg/2017Apr/0028.html

**Comment by lidingpku** [comment]
I also observed such inconsistency between https and http over many other terms,   worth checking  the page generation mechanism.  Below is an example
 
http://schema.org/Report  

![image](https://cloud.githubusercontent.com/assets/638605/25770620/2a555350-31ef-11e7-8929-c71cb9f72085.png)

https://schema.org/Report  

![image](https://cloud.githubusercontent.com/assets/638605/25770616/176d5e86-31ef-11e7-8ee7-bc5733bf0466.png)

**Comment by RichardWallis** [comment]
@lidingpku thanks for reporting.

There is a fix in that should stop these anomalies that I hope to introduce in the next few days.

~Richard.

**Comment by lidingpku** [comment]
@RichardWallis  great, looking forward

**Comment by unor** [comment]
I noticed that sometimes a few properties for a correctly given parent type are missing.

For example, the `about` property was not listed (under the `CreativeWork` section) for `ItemList` (I have a screenshot). 

Is this known / the same bug? Or should I create a new issue for it?

**Comment by Dataliberate** [comment]
Looking like the same issue. 

~Richard

**Comment by steelstring94** [comment]
I am affected by something like this. On `http://schema.org/Product`, I see only `category` as a property of Product, when I am in my office, but when I go home, I can see the full list of Product properties.

**Comment by RichardWallis** [comment]
Closed - now covered under issue #2060
