### ISSUE TITLE
404 for schema.org/name

### ISSUE THREAD

**Issue by dschulten** [schemaorg/schemaorg#1592]
The item http://schema.org/name no longer resolves, rather you get 404, There is http://meta.schema.org/name now, but it says its canonical URL is http://schema.org/name. Therefore this seems to be a bug.

**Comment by jefft0** [comment]
http://schema.org/name works for me.

**Comment by wub** [comment]
Works for me, too...

**Comment by danbri** [comment]
@RichardWallis is this the same bug we discussed recently?

**Comment by RichardWallis** [comment]
@danbri - yes it is.

**Comment by rvguha** [comment]
Which is?

guha

**Comment by RichardWallis** [comment]
@rvguha in simple terms there is an issue (that only becomes apparent under the significant system loads that are experienced by the schema.org site itself, that is not apparent on test systems such as webschemas.org) where different cached versions of pages (for http, https, core, extensions) occasionally conflict with each other during page build.

This particular 404 error and others recently reported, such as variations in output between different versions of a page (http, https, etc.), are symptomatic of this.

This area of the application that runs the site has _evolved_ over the last few years as extensions were introduced and various piecemeal attempts were made to improve performance.  

This area is the focus of current rationalisation and simplification of code, caching patterns, and page navigation that should address these problems and provide a more solid base for future work on the site and its user interface.  This work is high on the [my] priority list, as we need a [more] stable foundation to move forward from as the vocabulary grows and changes and potentially more functionally (eg, Wikidata links) is added.

~Richard

**Comment by rvguha** [comment]
Lets have a chat about this, maybe on a smaller list. There are requests
for dumps of static pages (for translated versions and such). We can maybe
do one single cleaner rewrite for that.

guha

**Comment by nicolastorzec** [comment]
+1 for decreasing the overall Website's latency.
It's getting noticeably slow at time, especially when searching.

**Comment by lidingpku** [comment]
I'm working on a project generating static pages  based on the json-ld version (see https://github.com/cnschema/schemaorg2html),  still in progress and not yet perfect.  Preliminary preview  of the outcome is available at  http://cnschema.org/docs/full.html.  The site is hosted in china and made 3.2 site content visible in china (see https://github.com/schemaorg/schemaorg/issues/1561)

**Comment by RichardWallis** [comment]
Closed - now covered under issue #2060
