### ISSUE TITLE
ImageObject examples and class description on Schema.org not aligned

### ISSUE THREAD

**Issue by DimitrK** [schemaorg/schemaorg#1597]
https://schema.org/ImageObject

Based on documentation ImageObject does not inherit properties from any other Class, Thing included.

Yet again, the examples below the class definition showcasing its use with properties that do not exist in ImageObject such as: 
-  "author"
-  "contentLocation"
-  "contentUrl"
-  "datePublished"
-  "description"
-  "name"

Presumably, the ImageObject should inherit properties from MediaObject -> CreativeWork -> Thing

**Comment by RichardWallis** [comment]
You are seeing symptoms of an issue we are trying track down with the latest release on the schema.org site where some of the hierarchy of inheritance is not building correctly on occasional pages. 

You are correct I_mageObject should inherit properties from MediaObject -> CreativeWork -> Thing_.

**Comment by DimitrK** [comment]
Thank you. The inheritance chain is already corrected on schema.org .

The issue seems to be now [MediaObject](https://schema.org/MediaObject) page which has no properties listed. 

Note that MediaObject properties appear correctly on any other page describing a Class that inherits from MediaObject

**Comment by DimitrK** [comment]
It seems that the issues has been fixed. Thank you, closing!
