### ISSUE TITLE
/publishingPrinciples describes organizational principles, should be applicable to Org

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1601]
http://schema.org/publishingPrinciples currently only applies to a CreativeWork e.g. NewsArticle.

Current definition is: "Link to page describing the editorial principles of the organization primarily responsible for the creation of the CreativeWork."

This originated with rNews, see http://dev.iptc.org/rNews-1-The-NewsItem-Class who phrased it as "A link to a natural-language statement of the principles adhered to by the source of the NewsItem.".

Per #1525 I've been looking into capturing more nuance around News, including different kinds of publishing principles, e.g. ethics policies vs diversity policies. It looks straightforward to capture such things via sub-properties of the publishingPrinciples property. However since the emphasis is on organizational practices, it would sometimes be more straightforward if the property could apply directly to an Organization. 

Suggested revised definition:

> "The publishingPrinciples property indicates (typically via URL) a document describing the editorial principles of an organization that relate to its activities as a publisher, e.g. ethics or diversity policies. When applied to a CreativeWork (e.g. NewsArticle) the principles are those of the organization primarily responsible for the creation of the CreativeWork."

This definition allows the property to be applied directly to an Organization. We should also add this in the schemas, as well as (an oversight...) CreativeWork to the expected values of the property.

**Comment by danbri** [comment]
Ping @agebhard @kansandhaus

An open question: what might we say about content created and published by individuals, e.g. bloggers who have ethics/transparency or other statements. Should we add Person also?

**Comment by agebhard** [comment]
@danbri I'll discuss with the others and get back to you here. (Personally, I think this all sounds very reasonable, including the second suggestion to include Person.)

**Comment by darobin** [comment]
FWIW we use it to point to a tree of `Action`s that fully describe the peer-review process that a given `Article` has to go through. So you can see that an article has to be submitted, that there will be reviewers, that the editor will make an assessment, etc. with specific questions to the answered and all that. This may be too scholarly for #1525, just thought I'd share in case you reckon there's something you can reuse.

**Comment by danbri** [comment]
@darobin so if you have an article pointing to a publishingPractice URL, where do you attach the Action? on the article, on the URL, or does publishingPractice point to an Action? i.e. is http://schema.org/potentialAction used?

**Comment by kansandhaus** [comment]
I personally share Andreas' position as well. Extending to Person and Organization makes perfect sense to me.

**Comment by agebhard** [comment]
Excellent, @kansandhaus; I spoke to @stuartmyles as well -- he's on board, too. @danbri, let's go with your original suggestion above extending this to Organization + Person.

**Comment by danbri** [comment]
Thanks for the sanity check @agebhard, @kansandhaus, @stuartmyles! Nice to be back in touch btw:)

**Comment by danbri** [comment]
Deployed in v3.3, http://schema.org/docs/releases.html#v3.3
