### ISSUE TITLE
Query Data from Google Sheets Script

### ISSUE THREAD

**Issue by guicalman** [schemaorg/schemaorg#1603]
Hello I am trying to make a dynamic spreadsheet that depending the selection of the schema.org class, automatically fill all the possible fields this property has, but I am facing a big problem to query jsondl or rdfa.

I found a really useful but limited code in this link http://blog.fastfedora.com/projects/import-json

Example:
=importJson(CONCATENATE("http://schema.org/",B1,".jsonld"),"/@graph/schema:rangeIncludes/@id,/@graph/rdfs:label,/@graph/rdfs:comment","rawHeaders,noTruncate")

B1 is a cell that has a dropdown box to select the class you want to get it's properties, got using the following script
=importJson("http://schema.org/docs/tree.jsonld","/children/name","noHeaders")

But I tried to make queries by my self but I can not handle json objecto in gs scripts with jquery. 

I have this code, but I am stuck because I can not use jquery or some library to query the json.
 
function test(){
  
  var url="http://schema.org/docs/tree.jsonld";
  
  var jsondata = UrlFetchApp.fetch(url);
  
  var jsonTemp = JSON.parse(jsondata.getContentText());
  
  return specificQuery;
}
 
Can someone help me with this?

Thanks in advance

GC

**Comment by danbri** [comment]
I'd suggest trying the CSV we publish via http://schema.org/docs/developers.html

Does https://support.google.com/docs/answer/3093335?vid=0-1203560686303-1493314509086 help?

Put this in a cell in google spreadsheet. I think similar is available in other systems.

> =IMPORTDATA("http://schema.org/version/latest/all-layers-types.csv")

**Comment by danbri** [comment]
Did you get any further? I will close this issue since it is not a general issue for Schema.org as a project to resolve (and we have 100s already open!), but we can of course continue to discuss things here. I'd like to know whether you can achieve what you need using these data files...

**Comment by guicalman** [comment]
Thank you for the reply, I handled the  Google Sheets issue.

Now I have a different situation, so I want to reopen this issue.

I want to generate schema.org machine-readable definitions for Bioschemas types, similar to "http://schema.org/Dataset.jsonld". A bioschemas type is a simplification and extension of a Schema.org type. Simplification since it exposes few properties from a schema.org type and an extension since it adds cardinality as well as specific vocabularies to populate some properties. 

Is there a library, data model or anything that could help me to generate those Machine-readable definitions in json, rdfa, etc?

**Comment by danbri** [comment]
> A bioschemas type is a simplification and extension of a Schema.org type. Simplification since it exposes few properties from a schema.org type and an extension since it adds cardinality as well as specific vocabularies to populate some properties.

My feeling is that you may ultimately not want to treat these as new types, but rather as domain-specific best practice guidelines that re-use standard schema.org terms in a restricted way.

I'd suggest looking at W3C ShACL (or maybe Shex) RDF validation formats, to see if they can capture your restrictions.

**Comment by danbri** [comment]
In the case where you do introduce new vocabulary, look at data/ext/pending/* in this repo to see how we generate http://pending.schema.org/

**Comment by guicalman** [comment]
Yes, you got the correct idea, what we want to do is to generate data types re-using schema.org and in some cases, few ones, add new vocabulary.

I am really amazed of who you generate page content from a rdf and txt files, which tools do you use to make this automatic generation, you told me that have a complicated software for it, can you please list me the applications you use and if there is a tutorial to know how to implement our own vocabulary  pages for bioschemas, it should be very useful for us.

Thanks in advance.

**Comment by RichardWallis** [comment]
I can recommend my three part "_Schema.org in practice_" article series: [part 1](http://dataliberate.com/2016/02/10/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/), [2](http://dataliberate.com/2016/02/25/evolving-schema-org-in-practice-pt2-working-within-the-vocabulary/), and [3](http://dataliberate.com/2016/03/01/evolving-schema-org-in-practice-pt3-choosing-where-to-extend/), plus the [How We Work](http://schema.org/docs/howwework.html) documentation to help guide your work.
