### ISSUE TITLE
Ferry

### ISSUE THREAD

**Issue by sgodiv** [schemaorg/schemaorg#1608]
A ferry schedule like a the busTrip ferry ports like busStation, could be helpful.

**Comment by chaals** [comment]
Actually, it would be nice if we could remodel trips like this. ferries, buses, trains of various kinds, minibuses, trolleybuses, trams, and even some aircraft run regular routes, with stops.

Some stops are transfer points, either for a different form of the same transport - e.g. between two tram lines, or for multiple forms - e.g. a station where metro lines, long-distance trains and local and long-distance buses all connect to an airport...

**Comment by sgodiv** [comment]
I agree. instead of one narrow classified 'busTrip'  just make it 'route'. then have an industry classification.  Like the isicv4 (http://schema.org/isicV4) that is already a part of 'organization' and can be used with that classification.

Seems like it would be a simple 'generic trip' category as a duplicate of 'busTrip' that would allow multiple modes of transportation.  This would allow for 'city tours' and route tours, bike tours, all kinds of new applications.

**Comment by Dataliberate** [comment]
+1

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by vlahanas** [comment]
+1
