### ISSUE TITLE
Deprecated property interactionCount doesn't have domain/range

### ISSUE THREAD

**Issue by nicolastorzec** [schemaorg/schemaorg#1610]
The [interactionCount](http://schema.org/interactionCount) property doesn't have an explicit domain and range.

Probably because it has been deprecated?

Meanwhile, some pages may still be referencing it, and some parsers may expect some domain/range.

@danbri ?

**Comment by nicolastorzec** [comment]
Actually, it's consistent with owl:DeprecatedProperty.
Closing.

**Comment by danbri** [comment]
Thanks. Yes - we have soft, hint-like domains/ranges anyway so there is no huge contradiction here.
