### ISSUE TITLE
Using the rdf version of schema.org with Protégé

### ISSUE THREAD

**Issue by delahousse** [schemaorg/schemaorg#1611]
Hello,

I was really happy to find an updated version of the data model I can open in Protégé at http://schema.org/docs/developers.html . 
Just a question: it opens ok in Protégé, I can see all the class hierarchy and annotation properties, but I could not visualize in Protégé a property like schema:familyName, which is present in the rdf file. Do you know why ? 

Kind regards
Jean

[schema.nt.zip](https://github.com/schemaorg/schemaorg/files/976064/schema.nt.zip)

**Comment by RichardWallis** [comment]
I'm not a Protégé user so I do not know why, but my guess would be that in Schema.org we use _domainIncludes_ and _rangeIncludes_ not _domain_ and _range_ which Protégé may be expecting.

**Comment by nicolastorzec** [comment]
Correct.

The RDF version of schema.org is just an RDF file that borrows vocabulary from RDFS. It's neither a OWL model nor a pure RDFS model. 

As a workaround to quickly make it work in Protégé you can simply:
- replace schema:domainIncludes with rdfs:domain
- replace schema:rangeIncludes with rdfs:range
- optionally convert the schema:DataType statements into rdfs:Datatype statements

I have code to convert the schema.rdf files into more standard RDFS and OWL models if needed.

N.

**Comment by danbri** [comment]
Thanks @nicolastorzec. Yes, it would be great if you could share the code somewhere as people do periodically ask about this.

**Comment by delahousse** [comment]
Thanks a lot for your very useful answer.
Jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data
https://fr.linkedin.com/in/jeandelahousse
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

2017-05-04 22:00 GMT+02:00 Dan Brickley <notifications@github.com>:

**Comment by sumutcan** [comment]
Hi,
FYI, there is also the OWL mapping of schema.org here: http://topbraid.org/schema/

Judging from the last update date, it does not cover the version 3.2.

Greetings

Umut

**Comment by delahousse** [comment]
thanks for the info
Jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data
https://fr.linkedin.com/in/jeandelahousse
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

2017-05-09 9:25 GMT+02:00 Umutcan Şimşek <notifications@github.com>:

**Comment by danbri** [comment]
Closing as no action on this is planned.

@nicolastorzec - did you ever post your code?

**Comment by timojkankaanpaa** [comment]
> Hi,
> FYI, there is also the OWL mapping of schema.org here: http://topbraid.org/schema/
> 
> Judging from the last update date, it does not cover the version 3.2.
> 
> Greetings
> 
> Umut

Hi!

Could you please reopen the folder?

Br

Timo

**Comment by RichardWallis** [comment]
For info, there is also a [Schema.org OWL](https://schema.org/docs/schemaorg.owl) file listed in the experimental section of the [Developers](https://schema.org/docs/developers.html) documentation.  This will import directly into Protégé.

**Comment by PIJEPI** [comment]
Como se podría añadir un concepto de shema.org a en la herramienta de software Protegé sin necesidad de importar  esto dos ficheros https://schema.org/docs/schemaorg.owl  y https://schema.org/docs/developers.html. Y cual de estos dos ficheros es mejor para trabar en protege.
Gracias.
