### ISSUE TITLE
Missing documentation for TheaterEvent

### ISSUE THREAD

**Issue by styrheim** [schemaorg/schemaorg#1617]
[TheaterEvent](http://schema.org/TheaterEvent) has examples, but no other documentation. I do believe there used to be more. E.g. that it is a subtype of _Event_, and I think some additional properties, like _workPerformed_.

**Comment by RichardWallis** [comment]
This is another symptom of the issue reported in #1584 & #1592 - which is hopefully being fixed soon.

Closing in favour of those.
