### ISSUE TITLE
How to deal with new extension!

### ISSUE THREAD

**Issue by alinzm** [schemaorg/schemaorg#1618]
Hello, Everyone!

We are working on a website for ranking the airlines and airports. As we have no particular Schema for these topics, I am looking for some documents or help to know How can I make an extension to rate Airlines and Airports.

I look forward to hearing your fantastic ideas.
Best

**Comment by thadguidry** [comment]
Rank airlines from all 3 perspectives.... Airline companies, Pilots, and consumers.  Not just consumers.

**Comment by alinzm** [comment]
We have our way to rank them include their Aeroplanes, Service, Price, etc. But I am wondering how I can use reviewed/hosted extension for this.

**Comment by RichardWallis** [comment]
Firstly the question to ask is _does this warrant the creation of an extension_ to do this or does the current vocabulary, with some examples, and possibly a few proposed tweaks satisfy  your use case.

We have [Review](http://schema.org/Review), [Rating](http://schema.org/Rating) and 
[AggregateRating](http://schema.org/AggregateRating), which can be used to describe an [Organization](http://schema.org/Organization) and or a [Service](http://schema.org/Service)  These are currently being extended via issue #1589 with [CriticReview](http://webschemas.org/CriticReview) and [UserReview](http://webschemas.org/UserReview) subtypes.

If you believe an extension would be needed to group together a set of types and properties to fully describe this, and similar, domains,  I can recommend my three part "_Schema.org in practice_" article series: [part 1](http://dataliberate.com/2016/02/10/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/), [2](http://dataliberate.com/2016/02/25/evolving-schema-org-in-practice-pt2-working-within-the-vocabulary/), and [3](http://dataliberate.com/2016/03/01/evolving-schema-org-in-practice-pt3-choosing-where-to-extend/), plus the [How We Work](http://schema.org/docs/howwework.html) documentation to help guide your work.

**Comment by stuartasutton** [comment]
In addition to the recommendation of Richard's excellent three part guide, you can also check out the two webinars he did for DCMI (Dublin Core Metadata Initiative) on schema.org extensions. The first uses the bibiographic extension as an discussion example and the second is a more technical intro.
 
>Part 1:
https://www.youtube.com/watch?v=LlYNb7D9E94&t=13s
Part 2:
https://www.youtube.com/watch?v=WrnjO5zS_t0&t=3s
