### ISSUE TITLE
Wich is the vocabulary for resume/cv?

### ISSUE THREAD

**Issue by colomet** [schemaorg/schemaorg#1622]
I need to write the education of the users. Should I use alumni? 

even if it is not in the university anymore?

**Comment by colomet** [comment]
alumniOf?

**Comment by danbri** [comment]
We don't have one yet, apart from a few pieces.

The alumni / alumniOf property covers people who have left the educational institution. It is vague on whether they completed their studies fully. In future we may describe educational achievements more explicitly.

I will close this issue to focus discussion towards a similar issue on the same topic: #603

Thanks!
