### ISSUE TITLE
Show how to use W3C CSVW rdf mappings to extract Schema.org from CSVs

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1623]
W3C's [CSVW](https://www.w3.org/2013/csvw/wiki/Main_Page) format provides a JSON-LD-oriented representation of CSV and other tabular data files. In addition to describing the general properties of a tabular file (or collection of files), it also provides the ability to "look inside" the actual data  rows/cells using annotations that map those values into factual claims.

The W3C work supersedes Schema.org's own community discussions (see [LookInside](https://www.w3.org/wiki/WebSchemas/LookInside) in W3C webschemas wiki) and our [position paper](https://www.w3.org/2013/04/odw/odw13_submission_53.pdf) from W3C's 2013 [workshop](https://www.w3.org/2013/04/odw/papers). 

The [generating RDF](https://www.w3.org/TR/2015/REC-csv2rdf-20151217/) spec is the most important for these purposes, although see also the [model](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/), [metadata](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/), [json](https://www.w3.org/TR/2015/REC-csv2json-20151217/), [usecases](https://www.w3.org/TR/2016/NOTE-csvw-ucr-20160225/), [html embedding](https://www.w3.org/TR/2016/NOTE-csvw-html-20160225/) [use cases](https://www.w3.org/TR/2016/NOTE-csvw-ucr-20160225/) and [primer](https://www.w3.org/TR/2016/NOTE-tabular-data-primer-20160225/) documents. 

Section 7.3 of the "generating RDF" spec includes a full [schema.org example](https://www.w3.org/TR/2015/REC-csv2rdf-20151217/#example-events-listing) inspired by Google's existing support for JSON-LD [music event](https://developers.google.com/search/docs/data-types/events) description ([blog post](https://webmasters.googleblog.com/2014/03/musical-artists-your-official-tour.html)).

* @gkellogg has a blog post on [implementing csvw](http://www.greggkellogg.net/2015/04/implementing-csv-on-the-web/)
* There are other implementations - https://github.com/sebneu/csvw-parser + @jenit has a ruby implementation (@@url?)
* @danbri has a [Javascript demo](http://danbri.org/2016/browserdemo/helloworld.html) prototyping an approach to clientside implementation that is compatible with many of Google's structured data features.

It would be good to have an informal case study that shows how this technology can map fairly arbitrary CSV files into a Schema.org "view" of the data.

**Comment by danbri** [comment]
1st cut draft is in the pending section of the (editorial staging site) http://pending.webschemas.org/PublicToilet

It has no treatment of the gender issue, yet.

**Comment by gkellogg** [comment]
@JeniT's implementation is [CSVLint](https://csvlint.io), which is available on [GitHub](https://github.com/theodi/csvlint.rb).

Also, see the [CSVW Implementation Report](http://w3c.github.io/csvw/publishing-snapshots/PR-earl/earl.html).

**Comment by gkellogg** [comment]
The [RDF Distiller](http://rdf.greggkellogg.net/) also supports transforming CSV to RDF, using the [Ruby Gem](https://github.com/ruby-rdf/rdf-tabular).
