### ISSUE TITLE
Add a PublicToilet type

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1624]
This has often cropped up in conversation but we never put the time into actually adding the vocabulary. I suggest we add a type for PublicToilet as it addresses a fundamental and universal truth of human experience. 

Also specifically I would like to use it for two case studies:

* #254 - physical accessibility of places. We have discussed this before but got stuck on details/scope.
* #1623 - mapping of tabular data into schema.org descriptions. There are various efforts to make available datasets describing public toilets, their locations and other properties, typically using tabular data.

### Proposed definition

* The English Wikipedia says "A public toilet is a room or small building containing one or more toilets (and possibly also urinals) which is available for use by the general public, or by customers or employees of certain businesses."; this seems reasonable (Wikidata:
 [Q813966](https://www.wikidata.org/wiki/Q813966)).
* supertype would be [CivicStructure](http://schema.org/CivicStructure), i.e. a kind of [Place](http://schema.org/Place).
* We should show how to apply existing vocabulary for opening hours, locations, constraints on intended users including gender. Again from Wikipedia, "Public toilets are commonly separated into male and female facilities, although some can be unisex, particularly the smaller or single-occupancy types. Increasingly, public toilets are accessible to people with disabilities.".
* We should examing open data datasets and try to match as much of their expressivity as possible. This can be explored via W3C CSVW mappings, per #1623.

#### UK, thanks to GDS for details

From a UK [initiative](http://incentive.opendata.esd.org.uk/) in which various datasets (including public toilets data) were published by local authorities (exploratory / non-mandatory so only partial coverage).

*  [UK PublicToilets schema documentation](http://schemas.opendata.esd.org.uk/PublicToilets) including [pdf overview](http://schemas.opendata.esd.org.uk/PublicToilets/LocalOpenDataIncentiveSchemePublicToiletsSchemaGuidance.pdf) and [github](https://github.com/esd-org-uk/schemas/tree/master/PublicToilets).
 * The published toilets data to this schema by participating councils is available on data.gov.uk and on the [LGA’s open data resources pages](http://datasets.opendata.esd.org.uk/?schema=Public+toilets+(LGA)).
* An aggregation tool is [also available](http://aggregator.opendata.esd.org.uk/details?&schemaURI=http%3a%2f%2fschemas.opendata.esd.org.uk%2fPublicToilets)
- this creates a csv of all the data published to the schema (see the link at the bottom of the page in the previous [link](http://datasets.opendata.esd.org.uk/?schema=Public+toilets+(LGA))).
* [The Great British Toilet Map](https://greatbritishpublictoiletmap.rca.ac.uk/) (generated from this data)

Related UK data
* e.g. [Northumberland data](http://opendata.northumberland.gov.uk/datasets/public-toilets/)
* [Rushmoor](http://data.gov.uk/dataset/98f3eaac-fcac-438d-a284-c50bd9ef1fd1)
* [Banes / Bath](https://bath.azure-westeurope-prod.socrata.com/browse?category=Health&utf8=%E2%9C%93) via Socrata. /cc @ldodds

#### Other / misc

* [Australian National Public Toilet Map](https://researchdata.ands.org.au/national-public-toilet-map/643964?source=suggested_datasets) e.g. [Melbourne](https://data.melbourne.vic.gov.au/browse?tags=toilets&utf8=%E2%9C%93)

**Comment by danbri** [comment]
1st cut draft is in the pending section of the (editorial staging site) http://pending.webschemas.org/PublicToilet

It has no treatment of the gender issue, yet.

**Comment by thadguidry** [comment]
@danbri there is no gender issue. Toilets don't care.

**Comment by danbri** [comment]
@thadguidry we get to describe the world as it is, rather than the world as we'd like it to be. Given schema.org's search-oriented focus, helping people find toilets that they can comfortably use seems a good usecase. And comfort here will inevitably involve matters including physical accessibility and social comfort including gender-related expectations. 

FWIW the UK schema linked above has these values for 'category':
> Female; Male;  Female and male; Unisex; Male urinal;  Children only;  None

I wonder whether subtyping might be the best-fit for expressing these; it isn't a pure 'gender' property but also includes ('Male urinal') the kind of toilet facilities offered. Let's see what other countries / datasets have to say on the matter.

**Comment by danbri** [comment]
Perhaps as a stopgap mapping for prototypes, we could therefore represent strings like "Male urinal" as a http://schema.org/category on the Place (although 'category' doesn't technically apply to Place, at least yet).

**Comment by thadguidry** [comment]
@danbri It was a joke.  Forgot to include my smiley face :)  In the States, we're dealing with public pushback of laws allowing cross-gender access even in elementary schools (little boy allowed to go into little girls restroom if he tells teacher he fells more like a girl today).  For what its worth, I think folks here are just making too big a deal out of nothing and paranoia is running rampant.

But I am completely on-board with this proposal and agree with you and Tim @mediaprophet

**Comment by mediaprophet** [comment]
I think the US term might be restRoom?  Other places bathRoom?

The schema is actually more complicated than one would give it credit for.
Including typesoftoilets, Disabled access, hot/cold water,
babychangetables, sanitaryDisposal, opening hours, syringeBins, shower,
male/female/mixed, ElectricalOutlets, nightlighting,

Not sure about the squirter thing vs. toiletPaper, toiletseatprotectors,
Ratings,
GPS coordinates,

Not sure what else....??

Tim.h.

**Comment by mediaprophet** [comment]
Could also list vendingMachines (ie: condoms, sanitaryNapkins(?)), Oh and
drinking water...  Mirrors (and mirrorType?)

Whether their free, available for public use, customer use, fee payable
facilities, attendants, etc.

It's late.  Happy to write a more formal response tomorrow.

Might find a place becomes more.marketable with a good way to promote a
clean and comfortable "bathroom".

Tim.h.

**Comment by mediaprophet** [comment]
Sorry.  Forgot accessibility.  Ie: handrails, et.al.

Important for elderly.

**Comment by mediaprophet** [comment]
@danbri  based in AU conditions, i've outlined the following below.  I think the main 'big' thing is whether they're squat toilets or based on the design of the porcelain throne.  

The other thing i note, is that some use hand-dryers, paper towel, toilet paper or water squirter alternatives; and i'm not sure what the cultural implications are broadly speaking.  I've therefore added "toiletType". 

with respect to the cultural implications, i started: https://github.com/schemaorg/schemaorg/issues/1661 

notes: 
Name: "text"
Male: "boolean"	
Female: "boolean"	
Unisex: "boolean"	
FacilityType: "text"
ToiletType: "text"
accessibleMale: "boolean"
accessibleFemale: "boolean"
accessibleUnisex: "boolean"
paymentRequired: "boolean"	
keyRequired: "boolean"
keyLocation: "text" (or url?  ie: cafe or service station has the key to a public toilet)
handDryer: "boolean"
BabyChange: "boolean"	
Showers: "boolean"	
DrinkingWater: "boolean"	
SharpsDisposal: "boolean"
SanitaryDisposal: "boolean"
seatCovers: "boolean"
bidetShower: "boolean"
bidet: "boolean"
footBath: "boolean"
ablution: "boolean"
Parking: "boolean"
ParkingAccessible: "boolean"

WIKIDATA ENTRIES
https://www.wikidata.org/wiki/Q813966 (PUBLIC TOILET)

**Comment by stevenjmesser** [comment]
Really pleased to see that this has been picked up by the community and conversations continue. I was part of the team working on the original schema from the [incentive scheme](http://incentive.opendata.esd.org.uk/), and it's interesting to see lots of additional properties being mentioned.

The scope of our work was to encourage local authorities to publish more open data and train them to do so, but many of the properties you've suggested were left out, simply because it would take too much effort for strained LA teams to collect the data. But I imagine that could be easily overcome by starting a project akin to [OpenBenches](https://openbenches.org/) for public toilets.

**Comment by danbri** [comment]
Also noting for the record, http://toilet.org.sg/loomapdirectory - "A Gracious Society Embracing Excellence in Restroom Culture", directory of public toilets in Singapore. Via [Twitter discussion](https://twitter.com/yanoak/status/975746108059078657).

**Comment by cedon** [comment]
One thing to note, some venues here in the US also have what they call a "Family Toilet" as well. These are independent of the typical "Mens" and "Womens" rooms  and are for parent(s) with children. That way the age restrictions @nicolastorzec mentions are not a concern and a mother(s) and/or father(s) can take their kids into a single facility.

**Comment by opyh** [comment]
#2439 might be interesting as an extension here.

**Comment by danbri** [comment]
We did it, http://schema.org/PublicToilet

We can continue to discuss toilet data here, but I'll close the issue for now.
