### ISSUE TITLE
DeliveryMethod can't be validated if nested inside Offer

### ISSUE THREAD

**Issue by e-orlov** [schemaorg/schemaorg#1633]
According to documentation type DeliveryMethod may appear in different higher types, including Offer. But testing tool validates it errorfree only if DeliveryMethod appears inside Action. Nesting on Offer fails validation. The question is: on which side is the problem, on the testing tool's side or on the documentation's?

**Comment by danbri** [comment]
which testing tool?

**Comment by danbri** [comment]
If you are referring to http://developers.google.com/structured-data/testing-tool/ - that tool's error/warning messages are focussed on the specific requirements of user-visible Google product features. 

I'll close this issue but feel free to re-open it if you can share a small test case that illustrates your question. Thanks!
