### ISSUE TITLE
Broaden the domain of schema:issn

### ISSUE THREAD

**Issue by tfrancart** [schemaorg/schemaorg#1640]
Currently schema:issn is declared with a schema:domainIncludes on type Periodical only. While this is not strictly wrong according to the semantic of "domainIncludes", this is restrictive and might be misleading according to the possible kind of things on which an ISSN can be assigned; in particular **an ISSN can be assigned to any kind of series, but also to datasets or websites**. This is documented in the official ISSN documentation, the ISSN Manual, section 0.2 and 0.3 (see http://www.issn.org/understanding-the-issn/assignment-rules/issn-manual/#0-2-scope-of-issn and the PDF version at http://www.issn.org/wp-content/uploads/2013/09/ISSNManual_ENG2015_23-01-2015.pdf)

We thus suggest to broaden the domain of schema:issn to the following types :

- CreativeWorkSeries (which includes Periodicals)
- Blog
- Dataset
- Website

This suggestion has been discussed and approved by the ISSN International Center (http://www.issn.org/).

**Comment by nicolastorzec** [comment]
+1

@danbri @RichardWallis @vholland @chaals ?

**Comment by RichardWallis** [comment]
Makes sense. +1

**Comment by dbs** [comment]
Generally +1

I'm not keen about the revised sentence in the description "You can repeat this property to identify its different medium versions." though; the direct antecedent of "its" is "this property" instead of the intended "serial publication" from the previous sentence, which will be confusing, and "different medium versions", while used in the ISSN documentation, will take more effort for the target audience to scan and understand than the original "different formats".

Perhaps "You can repeat this property to identify different formats of this serial publication." to maintain the structure of the original and repeating "serial publication" to tie the second sentence of the description back to the first?

**Comment by nicolastorzec** [comment]
Thanks for the feedback Dan.

I don't have a strong opinion either way. I will change later this week to provide more time for feedback.

**Comment by tfrancart** [comment]
FYI, the ISSN numbers for the different formats of a continuing resource (e.g. printed vs. electronic) are aggregated into a single ISSN-L ("Linking ISSN") : http://www.issn.org/understanding-the-issn/assignment-rules/issn-manual/#3-1-designation-of-issn-l. The ISSN-L is a unique identifier for the continuing resource, independant from the medium/format.

**Comment by RichardWallis** [comment]
I support @dbs's suggested tweaking of the description.

**Comment by dbs** [comment]
@tfrancart Thanks! The members of the W3 Schema.org Bibliographic Extension group were made aware of the ISSN-L back in November 2013 and at that time agreed to [simply treat it as another instance of the repeatable schema:issn property for a given continuing resource](https://lists.w3.org/Archives/Public/public-schemabibex/2013Nov/0089.html). Such decisions can always be revisited, of course.

**Comment by nicolastorzec** [comment]
+1 on treating ISSN-L as an instance of schema::issn for a given continuing resource. (see Dan's [link](https://lists.w3.org/Archives/Public/public-schemabibex/2013Nov/0089.html))

Regarding the definition, I prefer the one that explicitly describes what to do with ISSN-L.

**Comment by nicolastorzec** [comment]
Committed new description per @dbs' suggestion. See https://github.com/schemaorg/schemaorg/pull/1669/commits/b5a2265153ca5522e7762d735a64b2d7054772a4

**Comment by danbri** [comment]
I've merged #1669 - thanks all!

**Comment by osma** [comment]
I think this issue is done and should be closed?

**Comment by nicolastorzec** [comment]
Solution committed. Closing.
