### ISSUE TITLE
How can I get a machine readable schema from Schema.org

### ISSUE THREAD

**Issue by RehanSaeed** [schemaorg/schemaorg#1648]
I found a JSON file which lists all schema classes at https://schema.org/docs/tree.jsonld

Now I want a machine readable copy of the properties in each class, ideally in JSON. Does such a thing exist? Where can I get it? I can't see a link on https://schema.org.

**Comment by RichardWallis** [comment]
Information about how to obtain these for individual terms and plus downloadable files containing definitions for the core vocabulary, all definitions, and individual extensions are available here: http://schema.org/docs/developers.html#defs 

~Richard
