### ISSUE TITLE
Schema Appspot URLs are indexed

### ISSUE THREAD

**Issue by AymenLoukil** [schemaorg/schemaorg#1649]
Appspot urls of Schema.org have been indexed and that's not good because we are duplicating the website:

Exemple :  [https://schemaorgae.appspot.com/Person](url)

![schema appspot](https://user-images.githubusercontent.com/5750656/26872598-6325ffc6-4b77-11e7-9882-3cd43686be19.png)

**Comment by RichardWallis** [comment]
Thanks for this.  Yes we are aware of the problem here and I am currently looking into a solution that can work not only on the live site and its appspot view, but also on the webschemas.org and other test sites.

~Richard

**Comment by AymenLoukil** [comment]
Personnally i don't believe that we need to index webschemas.org and appspot. no-indexing them ould be better.
Adding Canonical poitning to the original URL on Schema.org would be a good quick-fix.

Aymen

**Comment by RichardWallis** [comment]
That is our objective (to only index schema.org).

Unfortunately the pages are [currently] dynamically created which causes issues as to which domain is being addressed as some instances can support more than one.

Working on it!

**Comment by AymenLoukil** [comment]
I will be glad to help on that @RichardWallis  ;)
