### ISSUE TITLE
Ambiguous description of 'ingredients', 'recipeInstructions' in Recipe

### ISSUE THREAD

**Issue by LjWatson** [schemaorg/schemaorg#165]
http://schema.org/ingredients
http://schema.org/recipeInstructions

The description of the "ingredients" property in the Recipe schema is "An ingredient used in the recipe".

The property name is plural and the description singular, which makes its scope ambiguous. Should the property be applied to a collection of ingredients, or to an individual ingredient, or doesn't it matter?

Suggest changing the description to provide greater clarity.

**Comment by scor** [comment]
This is not fixed. I think we should rename the 'ingredients' property to be singluar according to my comment from http://www.w3.org/wiki/WebSchemas/Singularity#Follow_up_.28June_29th.2C_2012.29:
>  'ingredients' from Recipe ought to be singular since 1) its definition is "An ingredient used in the recipe." and 2) the example shows a list of multiple instances of ingredients. Finally 'ingredient' (singular) is consistent with the property defined in the Google documentation for Rich snippets - Recipes and used in microformats, microdata and RDFa. (I know this is not schema.org, but it will make the migration to schema.org markup easier and less error prone).

**Comment by danbri** [comment]
OK, re-opening.

**Comment by danbri** [comment]
questions -

* Would adding singular form i.e. 'ingredient' (superceding 'ingredients') fix things adequately?
* same for recipeInstruction(s)?
* should we add Product or Thing as another expected value, to open door to more structure? or delay that and just fix basics here?

**Comment by scor** [comment]
> Would adding singular form i.e. 'ingredient' (superceding 'ingredients') fix things adequately?
yes IMO

> same for recipeInstruction(s)?
I think this one is fine. According to the examples of https://developers.google.com/structured-data/rich-snippets/recipes and http://schema.org/Recipe, the instructions are not meant to be a list of single instructions, but rather a single text value (with maybe an HTML list).

> should we add Product or Thing as another expected value, to open door to more structure? or delay that and just fix basics here?
just fix the basics here.

**Comment by danbri** [comment]
Ah, so you prefer the current "The steps to make the dish." for recipeInstructions, rather than proposed "A step or instruction involved in making the recipe."...

**Comment by vholland** [comment]
It would be nice if recipeInstructions took an ItemList so one could mark up instructions separately and specify their order.

**Comment by scor** [comment]
> Ah, so you prefer the current "The steps to make the dish." for recipeInstructions, rather than proposed "A step or instruction involved in making the recipe."...

Yes. It is also what Google and schema.org currently recommends and shows in their examples.

**Comment by DDeering** [comment]
>should we add Product or Thing as another expected value, to open door to more structure? or delay that and just fix basics here?

Dan, if you're referring to adding a Product or Thing type for the ingredients property, I like that idea.  It would provide more structure to the recipe markup and disambiguate things a little more, in my opinion.

**Comment by rvguha** [comment]
Rather than just rename it to ingredient, can we make it 'recipeIngredient' so that it is less ambiguous?

**Comment by thadguidry** [comment]
@rvguha partially less ambiguous... I have a recipe for natural dog food and another recipe for Playdoh...so perhaps instead humanFoodRecipeIngredient ;)

**Comment by danbri** [comment]
So, can we all live with:

* recipeIngredient “A single ingredient used in the recipe, for example sugar, flour or garlic.”
* recipeInstructions "The steps to make the dish." (Text or ItemList)

(with appropriate supersededBy assertions for the earlier (quite widely used) spellings.)

**Comment by thadguidry** [comment]
+1  Can live with recipeIngredient and recipeInstructions

**Comment by LjWatson** [comment]
@danbri 
If the intention is to markup an individual ingredient or instruction (by putting the property on each list item in a list for example), then I think the property name should be singular. If the intention is to markup a collection of ingredients or instructions (by putting the property on a list for example), then it should be plural.

**Comment by chaals** [comment]
Sigh. I can live with recipeingredient.

But "ingredients" in english are almost always things that are in food - apart from recipes the term is used for the same thing in food labelling, and that is pretty much it. So we weren't IMHO saving ourselves from a real ambiguity, for once.

It seems to me that recipe would be appropriate for playdough, dog food, perfume and soap. Would using it in those ways cause problems?

**Comment by danbri** [comment]
@chaals note that @twamarc pointed out above the common other use of ingredients - for medicines and drugs. http://schema.org/Recipe has always been pretty oriented towards food recipes, even if the description is ... curt. The more extended use of Recipe you outline slides quickly into metaphor. At Google we have noticed that publishers do try to stretch Recipe to cover all kinds of other situations, hence https://developers.google.com/structured-data/rich-snippets/recipes "Recipe markup should be used for content about preparing a particular dish. For example, "facial scrub" or "party ideas" are not valid names for a dish", i.e. "Recipe for success!", howtos etc are out of scope.

@LjWatson - yes I think that fits the newly updated distinction between recipeIngredient (which would be repeated for each single ingredient) vs recipeInstructions (which is all the instructions in a blob of text, or in a list that would be the single value of one recipeInstructions property).

**Comment by LjWatson** [comment]
@Danbri

 

I dislike recipeInstruction and recipeIngredient. They both seem unwieldy, and I’m not sure how either will stop people trying to use Recipe for unintended purposes?

**Comment by danbri** [comment]
@LjWatson it has already been "recipeInstructions" for several years. For the other property, @scor asked that "ingredients" become "ingredient" for the good reason you've also given re singular (essentially this job was overlooked a few years ago when we de-pluralized many other properties that ended in a final 's'). The change from "ingredient" to "recipeIngredient" comes as both @twamarc and @rvguha noted that this is one of several cases where a very general word is used to mean something very specific. Changing it won't stop people's behavior, but it is an alternative to @chaals suggestion that the scope of the recipe terms could be broadened (e.g. from food to include e.g. soap making) i.e. bringing it closer to its dictionary reading. 

It may not be the most elegant package but i think it is reasonable. We already do have recipeCategory, recipeYield, recipeCuisine, recipeInstructions. We will never achieve 100% internal stylistic consistency but I still think this change will be progress.

**Comment by nicolastorzec** [comment]
Questions:
- What's the plan regarding food items in general?
- And how do they relate to recipes and ingredients.
- Especially, a food item can exist independently of a recipe (i.e. it's not just an ingredient)

For example, I may be interested in capturing information about natural food items (e.g. an apple) and prepared food items (e.g. Ben & Jerry chocolate ice cream), independently of the recipes they may be involved in, if any.

Specifically, an apple can exist without being part of a recipe, and I may want to describe its country of origin, scientific name, and nutrition facts.

**Comment by ekgs1** [comment]
A distinction should be made between food items and ingredients.  Ingredients can be captured for both a recipe and an item.  It could be beneficial though to be able to link a recipe to a specific item in addition to ingredients for example "tabasco-original-red-sauce". This would support the use case of a recipe promoting a specific food item instead of hot sauce in general.

**Comment by chaals** [comment]
Drugs are close enough to food items that I think trying to preserve the distinction is interesting to ontologists, but less so in the "real world", where people do want recipes for play-dough and soap - and most of those people also have recipes for bread and a medicinal herbal tea mix.

**Comment by thadguidry** [comment]
@nicolastorzec @ekgs1 @danbri @chaals 
Currently our "Food" is just a text type now and sits under here: https://schema.org/foodWarning

I opened a new issue https://github.com/schemaorg/schemaorg/issues/458 that addresses this need.

**Comment by rvguha** [comment]
Food/nutrition 'labels' are quite interesting and important. It would be
nice to have a detailed vocabulary for it.

guha

**Comment by danbri** [comment]
re Food/nutrition, GS1's external extension covered this in epic detail - http://blog.schema.org/2016/02/gs1-milestone-first-schemaorg-external.html (cheeseFirmness etc :)
