### ISSUE TITLE
seatingCapacity in the auto extension is redundant

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#1650]
We have 
- seatingCapacity in auto.schema.org
and
- vehicleSeatingCapacity in core.

The former should be removed, it is likely a remainder of the split of the auto proposal into core and extension.

**Comment by mfhepp** [comment]
Same for vehicleModelDate and modelDate.

**Comment by trypuz** [comment]
If we decide to remove seatingCapacity from auto.schema.org, then in core we should rather have something more general then vehicleSeatingCapacity - perhaps seatingCapacity would be the best option since "seatingCapacity may also be useful for buildings, boats, classrooms, etc." as pointed out in #825

**Comment by danbri** [comment]
I would advise to keep the property vehicle-specific for now.

We might add a general superproperty eventually but it would need some audit of the types it makes sense for, e.g. http://schema.org/Church might have a vehicle-like value, http://schema.org/MusicVenue  http://schema.org/MovieTheater http://schema.org/EventVenue .... ... are there other cases where non-vehicle seating capacities need to be described differently?

**Comment by trypuz** [comment]
If I correctly understood, the result of our discussion "for now" should be like here: http://sdo-auto-fix.appspot.com/seatingCapacity
That is:
1) http://auto.schema.org/seatingCapacity is removed from the auto hosted extension  
2) schema.org core property "vehicleSeatingCapacity" is renamed to "seatingCapacity"
3) new schema.org core property "seatingCapacity" is vehicle-specific (i.e. it has onty http://schema.org/Vehicle in its domain)
