### ISSUE TITLE
http://auto.schema.org/emissionsCO2 has range inconsistency

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#1651]
The text for http://auto.schema.org/emissionsCO2 implies one could use Number or QuantitativeValue, but formally, only Number is allowed.

Suggestion: Remove the text fragment that implies QuantitativeValue as a range or include QuantitativeValue in the list of permitted values.

**Comment by trypuz** [comment]
I do support adding QuantitativeValue to the range of http://auto.schema.org/emissionsCO2 .
