### ISSUE TITLE
We need a construction that points to other metadata formats e.g. for datasets

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1652]
Perhaps a property called "seeAlso" (in the rdfs:seeAlso tradition)?

Schema.org is quite big but does not attempt to do everything. We have hosted and external extensions for vocabulary that is to some extend integrated with Schema.org's approach - e.g. expressed in the same data model, file formats, and maybe with partially aligned schemas. But sometimes there are formats that go substantially deeper and which are in separate files. In the datasets case, the CSVW format defines a JSON-LD based approach that describes the detailed structure of tabular datasets. Similarly, W3C Data Cube has its own approach (and its [spec](https://www.w3.org/TR/vocab-data-cube/) shows some preference for the Turtle format, which is unusual w/ Schema.org.)

Proposal:

1. Add a "seeAlso" property with semantics similar to W3C [rdfs:seeAlso](https://www.w3.org/TR/rdf-schema/#ch_seealso) but a stronger expectation of a machine readable file being at the other end.
2. Show examples of this where we use http://schema.org/fileFormat to indicate that format
3. Create short-cut subproperties of seeAlso for formats that we are particularly interested in, such as dataset details: "seeAlsoCSVW", "seeAlsoDataCube". The definitions of these properties would then link to the appropriate W3C specs, and allow concise markup rather than requiring a nested object.

**Comment by danbri** [comment]
Conclusions from talking with @natashafn:

There are two ideas mixed up here. 

One is about pointing to another document (which might be in a schema.org-oriented format e.g. HTML / JSON-LD / Microdata / RDFa, or might not). This is roughly "seeAlso", and is where we'd want to use fileFormat for a mimetype or if unregistered an URL like https://developers.google.com/public-data/overview

The other idea is about the relationship between a Dataset or DataDownload entity and something expressed in a more detailed descriptive (RDF-ish) vocabulary such as W3C CSVW or W3C DataCube or W3C VOiD. We might call this something like "moreDatasetDetails". For CSVW it might be a Table or a TableGroup, ... [to be continued]

**Comment by danbri** [comment]
After slightly more discussion - suggest 'mainEntity' for the 2nd use case.

**Comment by hekl** [comment]
A property like "datasetVocabulary" of Dataset that shows which specific vocabulary is used, would be handy. It could then refer to prelisted types like DataCube, CSVW or SDMX. 
But would this facilitate the discovery, use and reuse of data enough? Another option might be to advise to store public authoritative data(sets) in WIkiData. It it would it a lot easier to find, use and reuse this data.

**Comment by katerobertsfreeman** [comment]
I'd like to see (if there isn't already one) a concept representing a url that points to the "authoritative, point-of-truth" full version of a dataset or dataservice's metadata - on the basis that the authoritative version of the metadata is often not in an html webpage containing schema.org.

There will inevitably be many re-presentations (by non-metadata owners) of a dataset's metadata.  But these all need a way to refer back to the official "authoritative / point-of-truth " version of that metadata.
Kate
