### ISSUE TITLE
schema:Person colleagues can be anything?

### ISSUE THREAD

**Issue by teledyn** [schemaorg/schemaorg#1657]
I'm proposing removing line 4200 in the current schema file: as it sits, while other people associated with schema:Person (children, parents, knows) have an rdfs:range of schema:Person, only the colleague is allowed to be either schema:Person or any URI. That seems odd.  I mean, hey, I love my phone, but I wouldn't (yet) consider Google Assistant to be a colleague ;)

Was there some reason why colleague was defined differently?

**Comment by nicolastorzec** [comment]
Agree. Changes committed. See PR 1665.
