### ISSUE TITLE
Hosted extensions are linked to '0.3-2f.schemaorgae.appspot.com'

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1658]
On http://schema.org/docs/schemas.html#hosted

The extensions in the list are linked to `*.0.3-2f.schemaorgae.appspot.com/` instead of `*.schema.org/`.

```html
<ul>

	<li><a href="http://auto.0.3-2f.schemaorgae.appspot.com">auto.schema.org</a></li>

	<li><a href="http://bib.0.3-2f.schemaorgae.appspot.com">bib.schema.org</a></li>

	<li><a href="http://health-lifesci.0.3-2f.schemaorgae.appspot.com">health-lifesci.schema.org</a></li>

	<li><a href="http://iot.0.3-2f.schemaorgae.appspot.com">iot.schema.org</a></li>

	<li><a href="http://meta.0.3-2f.schemaorgae.appspot.com">meta.schema.org</a></li>

	<li><a href="http://pending.0.3-2f.schemaorgae.appspot.com">pending.schema.org</a></li>

</ul>
```

**Comment by unor** [comment]
This seems to be the case for links to extension terms on core type pages, too.

For example, on [`CreativeWork`](http://schema.org/CreativeWork) the links are:

* http://bib.3-2f.schemaorgae.appspot.com/publisherImprint
* http://bib.3-2f.schemaorgae.appspot.com/Atlas
* http://pending.3-2f.schemaorgae.appspot.com/CategoryCodeSet
* …

**Comment by RichardWallis** [comment]
Thanks for highlighting this. 
I understand what is happening I've just got to get my head around how to stop it happening.
~Richard

**Comment by danbri** [comment]
Thanks all - this seems to have been addressed, either fixed directly or overtaken by events (i.e. the move to static-served content).
