### ISSUE TITLE
Receipt and/or TaxReceipt

### ISSUE THREAD

**Issue by ghost** [schemaorg/schemaorg#1664]
the ability to generate an RDF purchase receipt (itemised ideally)

**Comment by mediaprophet** [comment]
seeAlso: 
https://github.com/ouisharelabs/food-dashboard
https://github.com/ouisharelabs/food-dashboard/issues/6
https://github.com/schemaorg/schemaorg/issues/458
http://demoschemed.appspot.com/allergy
