### ISSUE TITLE
404 on http://schema.org/docs/release.html

### ISSUE THREAD

**Issue by bcawrse** [schemaorg/schemaorg#1673]
http://schema.org/docs/release.html is referenced from http://schema.org/docs/extension.html, but the link 404s.

References to /docs/release.html should be removed if it isn't maintained or documentation should be added at /docs/release.html.

![release html_404](https://user-images.githubusercontent.com/3941017/27338191-89db60cc-55a2-11e7-954d-dd5587515882.png)

**Comment by danbri** [comment]
Oops, that was a good old fashioned typo I think! Thanks for letting us know :)

**Comment by bcawrse** [comment]
Anytime @danbri!
