### ISSUE TITLE
A solution to 4 issues concerning schema:Vehicle properties

### ISSUE THREAD

**Issue by trypuz** [schemaorg/schemaorg#1674]
Below we propose a solution to 4 issues concerning schema:Vehicle properties
(see a test version of schema.org: http://sdo-auto-fix.appspot.com). If it is OK, we'll create a pull request.

1) Answering https://github.com/schemaorg/schemaorg/issues/1651

QuantitativeValue has been added to the range of schema:emissionsCO2.
See: http://auto.sdo-auto-fix.appspot.com/emissionsCO2

2) Answering https://github.com/schemaorg/schemaorg/issues/1650

Two properties have been removed from auto hosted extension
- http://auto.schema.org/seatingCapacity
- http://auto.schema.org/modelDate

Schema.org core properties
- schema:vehicleSeatingCapacity
- schema:vehicleModelDate
have been renamed to
- schema:seatingCapacity
- schema:modelDate

See: http://sdo-auto-fix.appspot.com/seatingCapacity and http://sdo-auto-fix.appspot.com/modelDate

3) In the examples for schema:Car " "airbags" : "6" " has been changed to " "numberOfAirbags" : "6" " and 3 new examples have been added (they answer the following issues: https://github.com/schemaorg/schemaorg/issues/1549 and https://github.com/schemaorg/schemaorg/issues/1588).

See the examples here:  http://sdo-auto-fix.appspot.com/Car

**Comment by danbri** [comment]
Thanks. This generally looks positive, though I've commented in #1650 on the seating capacity aspect.

**Comment by danbri** [comment]
Looks like bot over-reach / misconfig; investigating…
