### ISSUE TITLE
Show Multiple Inheritance in Machine Readable Format

### ISSUE THREAD

**Issue by RehanSaeed** [schemaorg/schemaorg#1679]
The machine readable https://schema.org/docs/tree.jsonld tree structure showing all schema.org classes does not show multiple inheritance e.g. `LocalBusiness` can be a child of `Place` but also `Organization` like so:

> Thing > Place > LocalBusiness
> Thing > Organization > LocalBusiness

**Comment by danbri** [comment]
Copying my comment from #78 

> @RehanSaeed yes - that was a pragmatic decision I made when building the tree representation. Perhaps in the future we might do something like give each type an annotation indicating its primary/dominant supertype, but for now the code simply picks one supertype so that we get a clean tree structure with no duplication.

To expand on this comment: when I first implemented this, and tried it with several D3 representations, it was generally not very useful. The inclusion of a type (or collection of types) several times in the hierarchical tree means that types that happen to have multiple supertypes un-naturally dominate any data visualizations. If you want to analyze schema.org data using other abstractions e.g. graph structures, you can access the raw underlying data via http://schema.org/docs/developers.html

I didn't keep a copy of the json with multiple supertypes but http://bl.ocks.org/danbri/1c121ea8bd2189cf411c shows an example using the current approach.

**Comment by RehanSaeed** [comment]
@danbri I'm working on https://github.com/RehanSaeed/Schema.NET which is a type-safe way to use schema.org in .NET. I need a machine readable way to determine the full tree structure of all classes including classes with multiple parents. For classes with multiple parents I plan to use C# interfaces or add new meta classes e.g. PlaceOrganization combined in the above example because the C# language does not support multiple inheritance.

Your idea for an annotation would be perfect but I suppose it would take some time to implement? You mention the raw underlying data has what I'm looking for, what data set do I need to look at in the developers page.

**Comment by thadguidry** [comment]
Muhammand,

You can use the file: schema and format: JSON-LD and click the download
button at the bottom.

Then parse the graph with .NET tools or libraries. (preferably those that
understand JSON-LD already)

You can see in the JSON-LD format easily even with your eyes that
LocalBusiness is a subclass of both Place and Organization.

 {
      "@id": "http://schema.org/LocalBusiness",
      "@type": "rdfs:Class",
      "http://www.w3.org/2004/02/skos/core#closeMatch": {
        "@id": "http://www.w3.org/ns/regorg#RegisteredOrganization"
      },
      "rdfs:comment": "A particular physical business or branch of an
organization. Examples of LocalBusiness include a restaurant, a particular
branch of a restaurant chain, a branch of a bank, a medical practice, a
club, a bowling alley, etc.",
      "rdfs:label": "LocalBusiness",
      "rdfs:subClassOf": [
        {
          "@id": "http://schema.org/Organization"
        },
        {
          "@id": "http://schema.org/Place"
        }
      ]
    }

-Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

>

**Comment by danbri** [comment]
@RehanSaeed ah, yes in that case you want the full dataset as @thadguidry explained just now

**Comment by RehanSaeed** [comment]
I've now switched to the full `all-layers` data set, Unfortunately, I'm still having to get the tree data set to get the layer property i.e. attic, meta, pending, core, auto etc. There is a `http://schema.org/isPartOf` property in `all-layers`, however, it's incomplete.

**Comment by RichardWallis** [comment]
isPartOf (in the vocabulary definition files) is only applied when a term is not part of the core vocabulary (ie. it is defined in an extension - bib, auto, pending, etc.)

As all terms have canonical URIs of the form http://schema.org/{term}, the extension URLs only being used for site organisation, documentation, etc., that should not be an issue for what I believe you are trying to achieve.

**Comment by RehanSaeed** [comment]
Thanks everyone for all the help.

My only remaining issue is that property/enumerations from `http://purl.org` are not listed in the all-layers.jsonld file and I'm not certain how I should handle them.

The above issue withstanding, I've now released [Schema.NET](https://github.com/RehanSaeed/Schema.NET) and written a blog post ["Structured Data using Schema.NET"](https://rehansaeed.com/structured-data-using-schema-net/).

I'll close this issue as it's now been addressed.
