### ISSUE TITLE
Typo error to be fixed: http://schema.org/clincalPharmacology

### ISSUE THREAD

**Issue by twamarc** [schemaorg/schemaorg#168]
This was submitted along ago with medicalEntity extension proposal, to be fixed. As It's taking time for the proposal to be adopted in schema.org, we should maybe fix this typo error as urgent and keep waiting the proposal to be accepted separately.
http://schema.org/clincalPharmacology to http://schema.org/clinicalPharmacology
Am looking for other similar  points throughout the vocabulary.

**Comment by danbri** [comment]
Thanks! Oh dear...

I've assigned this to a release we're planning for Feb.

**Comment by danbri** [comment]
I've fixed this in sdo-stantz, our candidate next release. For example see http://sdo-stantz.appspot.com/Drug - Thanks!

**Comment by twamarc** [comment]
Thanks!
