### ISSUE TITLE
Documentation for 'additionalProperty' is lacking.

### ISSUE THREAD

**Issue by Download** [schemaorg/schemaorg#1685]
I have read the docs on `additionalProperty` but it has left me puzzled.

> A property-value pair representing an additional characteristics of the entitity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.
> Note: Publishers should be aware that applications designed to use specific schema.org properties (e.g. http://schema.org/width, http://schema.org/color, http://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.

'A property-value pair' suggests there can be only one. However if I understand correctly, schema.org 'inherits' the additionalProperty mechanism from json-schema, which [describes](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.20) it like so:

> Validation with "additionalProperties" applies only to the child values of instance names that do not match any names in "properties", and do not match any regular expression in "patternProperties".
>
> For all such properties, validation succeeds if the child instance validates against the "additionalProperties" schema.

'For all such properties' suggests there can be more than one.

**Are schema.org `additionalProperty` and json-schema `additionalPorperties` related or is it just a big coincidence?**

Sadly for me, the docs on `additionalProperty` include no JSON-LD example. Also, there does not seem to be an explicit mention of the cardinality anywhere. So I am left guessing.

I now see 3 ways in which this could work but I have no idea which one is correct, or whether it even works completely different...

### 1. additionalProperty is a single property-value pair

```json
{
  "additionalProperty": {
    "@type": "PropertyValue",
    "name": "myCustomProperty",
    "value": "my custom value"
  }
}
```

### 2. additionalProperty can actually also be an array of property-value pairs

```json
{
  "additionalProperty": [
    {
      "@type": "PropertyValue",
      "name": "myCustomProperty",
      "value": "my custom value"
    },
    {
      "@type": "PropertyValue",
      "name": "myOtherCustomProperty",
      "value": "my other custom value"
    }
  ]
}
```

### 3. additionalProperty is actually an object, whose keys are the names of the key value pairs

```json
{
  "additionalProperty": 
  {
    "@type": "PropertyValue",
    "myCustomProperty": "my custom value",
    "myOtherCustomProperty": "my other custom value"
  }
}
```

### 4. ??
Some other mechanism entirely?

**Is there some piece of authorative text I can read that will help me understand which it is?**

**Comment by unor** [comment]
Every Schema.org property can be provided multiple times.

If you need only one `PropertyValue`, use your 1. example.  
If you need more than one `PropertyValue`, use your 2. example.

If you have multiple values for the same property, use one `PropertyValue` and provide an array for the `value` property.

**Comment by Download** [comment]
@unor Thanks for your help, this already clears up a lot!

One last question then since you seem to know this stuff... I tried adding `additionalProperty` to a `Product` but the Google validator tells me it's an unknow property. Is this property only on some things and not on others? What do you guys do when you need it on e.g. `Product`?

**Comment by vholland** [comment]
Perhaps something was mis-aligned? The following works in the Google validator:

```
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "Widget",
  "additionalProperty": {
    "@type": "PropertyValue",
    "name": "foo",
    "value": 42
  }
}
```

**Comment by Download** [comment]
You are right. I mixed up Organization and Product.

Try this one:

```json
{
  "@context": "http://schema.org/",
  "@type": "Organization",
  "name": "Widget",
  "additionalProperty": {
    "@type": "PropertyValue",
    "name": "foo",
    "value": 42
  }
}
```

Error:

> The property additionalProperty is not recognized by Google for an object of type Organization.

**Comment by Download** [comment]
So what to do if you have some additional info on an organization you would like to add? Am I right in thinking that then, you would need to create a custom schema and use `additionalTypes` to reference that?

**Comment by Dataliberate** [comment]
The simple answer would be to define the Organization as a LocalBusiness,
which as a subtype of Place has additionalProperty as a property.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by vholland** [comment]
My recollection is we limited additionalProperty to a few types out of an abundance of caution. Should we consider adding it to Organization?

**Comment by Download** [comment]
To be honest I initially expected it to be on Thing.
