### ISSUE TITLE
ClaimReview markup needs way to show shelf-life

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1687]
Some fact checks need review after ~1 year, others are relevant indefinitely. Markup could help.

#GlobalFact4 conference discussion

**Comment by danbri** [comment]
Perhaps http://schema.org/validUntil can be extended?

**Comment by danbri** [comment]
/cc @MevanBabakar (of fullfact.org) who raised this initially, and @tmarshbing who has been looking at ClaimReview lately.

Looking again (always a good idea given the size of schema.org) I see now that we have http://schema.org/expires ("Date the content expires and is no longer useful or available. Useful for videos."). This seems a better choice than validUntil.

I'm not particularly sure why we emphasise the video usecase (maybe @vholland remembers?). But it should do the job for ClaimReview too. We would need to amend its associated type from MediaObject to CreativeWork, or be conservative and just add it to ClaimReview.

Perhaps we could adjust the text to be something like: 

> "Date the content expires and is no longer useful or available. For example a VideoObject whose availability is time-limited, or a ClaimReview fact check whose publisher wants to indicate that it may no longer be relevant (or helpful to highlight) after some date."

@MevanBabakar - how does that look? Feel free to suggest tweaks.

**Comment by danbri** [comment]
Shipped in 3.3.

**Comment by danbri** [comment]
example of related human facing ui:

https://consumer.healthday.com/cancer-information-5/smoking-cessation-news-628/two-foods-could-help-ex-smokers-lungs-heal-729539.html

which says

> Please note: This article was published more than one year ago. The facts and conclusions presented may have since changed and may no longer be accurate. And "More information" links may no longer work. Questions about personal health should always be referred to a physician or other health care professional.

**Comment by DmPo** [comment]
Good point, Dan.

Sometimes fakes become real much faster, than in a year.

D
