### ISSUE TITLE
Add EmployerAggregateRating and reviewAspect

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1689]
In schema.org 3.3, we will be adding EmployerReview as discussed in issue #1576. Some review sites allow users to write reviews based on specific aspects (e.g. employer benefits or work-life balance). In some cases, the sites aggregate ratings across multiple reviews, so readers are presented with a number like "ACME Industries rates 4/5 stars".

To help authors of these pages better express their content, I propose adding the following.

- ```reviewAspect```: This Review or Rating is relevant to this part or feature of the ```itemReviewed```. 
  - Domain: http://schema.org/Review and http://schema.org/Rating
  - Range: Text
- ```EmployerAggregateRating```: An aggregate rating of an Organization related to its role as an employer.

**Comment by danbri** [comment]
for reviewAspect, can you give a few examples? ideally real sites.

for EmployerAggregateRating, do the relevant sites always hide individual ratings eg for privacy reasons there is no call for EmployerRating?

**Comment by vholland** [comment]
Glassdoor allows reviewers to review salaries and employee benefits. Benefits can further be broken down into health insurance, 401(k), discounts, etc. See https://www.glassdoor.com/Benefits/Apple-US-Benefits-EI_IE1138.0,5_IL.6,8_IN1.htm

Indeed also allows reviewing salary separately from benefits. It also allows for reviewing culture, work-life balance, management, etc. See https://www.indeed.com/cmp/Amazon.com/reviews

I thought about proposing EmployerRating, but in the examples I saw, individual ratings were linked to reviews, so you could infer it was an EmployerRating. I am not opposed to adding it for completeness.

**Comment by danbri** [comment]
Makes sense. so the text for the aspects is,  for now, likely to be based on per-site wording, unless/until broader consensus emerges...?

**Comment by vholland** [comment]
Yes. I thought about trying to create a small taxonomy of aspects, but decided it would be better to wait for some sort of consensus.

**Comment by vholland** [comment]
Merged into pending.

**Comment by danbri** [comment]
(on @scroobiustrip 's point, https://pending.schema.org/reviewAspect was there)

We should move this to core. It got used, e.g. see https://developers.google.com/search/docs/data-types/employer-rating
