### ISSUE TITLE
full text search glitches

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1694]
[Search for "depict"](http://schema.org/docs/search_results.html#q=depict):
- Why does it return http://schema.org/image ? That word doesn't appear there!
- Why does it not return http://schema.org/contentLocation where "depicted" appears?

**Comment by danbri** [comment]
I think this was fixed (perhaps by improved indexing via sitemap). https://schema.org/docs/search_results.html?q=depict looks better than the results from when you reported this (back in 2017, sorry!)
