### ISSUE TITLE
give example CreativeWork isPartOf Collection

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1696]
Wikidata has prop [P195 collection](https://www.wikidata.org/wiki/Property:P195), so I wondered what's the analog in Schema.
- please confirm `CreativeWork isPartOf Collection` is right, and give such example in both CreativeWork and Collection
- http://schema.org/collection is deprecated. So please add clarification there:
  To link `CreativeWork` to a `Collection`, use `isPartOf`

**Comment by chharvey** [comment]
http://schema.org/isPartOf
