### ISSUE TITLE
Clarify 'Times are specified using 24:00 time'

### ISSUE THREAD

**Issue by john1v** [schemaorg/schemaorg#1699]
Page https://schema.org/openingHours states: 
"Times are specified using 24:00 time. For example, 3pm is specified as 15:00. "
It is unclear how morning hours should be formatted.
Changing above line to the following (if correct) would be helpful: 
"Times are specified using 24:00 time. For example, 3pm is specified as 15:00, 3am is specified as 03:00. "

**Comment by Download** [comment]
And in addition, the very next line continues with an example that breaks this very rule:
```
Here is an example: <time itemprop="openingHours" datetime="Tu,Th 16:00-20:00">Tuesdays and Thursdays 4-8pm</time>.
```
Also, the page does explain how to list multiple days (separate with a comma), but does not mention what to de when there are multiple time ranges. E.g. what to do is a store is open from 09:00-12:00 and then again from 14:00-18:00 ?

**Comment by thadguidry** [comment]
Agreed, the definition shouldn't say "time" but instead say "format".  "Times are specified using 24:00 format".   From ISO8601 this statement is more useful than our current statement, it basically says "hh   = two digits of hour (00 through 23) (am/pm NOT allowed)".

So yeah, +1 to improving the definition to make it more clear to developers.

**Comment by RichardWallis** [comment]
Fixed in commit 4cf21be

**Comment by Download** [comment]
@RichardWallis 
What about the multiple time ranges?

If a store is open daily from 09:00-12:00 and from 13:00-17:00, how would this be specified?

**Comment by RichardWallis** [comment]
For more complex situations such as you describe I would suggest using [OpeningHoursSpecification](https://schema.org/OpeningHoursSpecification) to describe the times in more detail.

Although the [examples](https://schema.org/OpeningHoursSpecification#eg-0378) do not show your exact example, they give the foundation.  There should be no problem in specifying more than one for each day, with differing time ranges.
