### ISSUE TITLE
Google Webmaster Tools show the error in Manual Action for my web - https://infinitemlmsoftware.com/

### ISSUE THREAD

**Issue by ishap123456** [schemaorg/schemaorg#1706]
It is showing error as below
Spammy structured markup
Markup on some pages on this site appears to use techniques such as marking up content that is invisible to users, marking up irrelevant or misleading content, and/or other manipulative behavior that violates Google's Spammy Structured Markup guidelines.

I have deactivated some modules to fix that error and then sent Request to Review again but Google rejected reconsideration request.
While I see in Structured Data Testing Tool, it doesn't show any error.

[https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Finfinitemlmsoftware.com%2F](url)
Help me what should I do to fix that?

Thanks in advance.

**Comment by danbri** [comment]
Closing, because this project is not a support forum for Google product features. Such questions are best asked elsewhere (e.g. https://support.google.com/webmasters/community?hl=en)
