### ISSUE TITLE
http://schema.org/inLanguage field not specified in http://schema.org/EntryPoint

### ISSUE THREAD

**Issue by ayumihamsaki** [schemaorg/schemaorg#1708]
Hello,

I have looked through past issues here for this answer.

I know schema.org is not google. I just don't understand this and wondered if someone is working on this issue or not?

The webpage: https://developers.google.com/search/docs/data-types/local-businesses

It has an example says this:

```
<script type="application/ld+json">
{
  "@context":"http://schema.org",
  "@type":"LocalBusiness",
  "image": "http://www.example.com/yoga.jpg",
  "@id":"http://daveshouseofyoga.example.com/",
  "name":"Dave's House of Yoga",
  "address":{
    "@type":"PostalAddress",
    "streetAddress":"3986 Rivermark Pkwy",
    "addressLocality":"Santa Clara",
    "addressRegion":"CA",
    "postalCode":"95054",
    "addressCountry":"US"
  },
  "geo":{
    "@type":"GeoCoordinates",
    "latitude":37.3952149,
    "longitude":-121.9474023
  },
  "telephone":"+14085551135",
  "potentialAction":{
    "@type":"ReserveAction",
    "target":{
      "@type":"EntryPoint",
      "urlTemplate":"https://www.example.com/reserve?merchantId=20373",
      "inLanguage":"en-US",
      "actionPlatform":[
        "http://schema.org/DesktopWebPlatform",
        "http://schema.org/IOSPlatform",
        "http://schema.org/AndroidPlatform"
      ]
    },
    "result":{
      "@type":"Reservation",
      "name":"Book a class"
    }
  }
}
</script>
```

The trouble this would bring up the error message: 

WARNING: http://schema.org/inLanguage field not specified in http://schema.org/EntryPoint

This would be correct in a perfect world. But there is talk here about adding inLanguage to other property and classes see here: https://github.com/schemaorg/schemaorg/issues/1064

I just wondered if the clever guys working here are considering to add this?

Thanks.

**Comment by joo7** [comment]
I can confirm the issue testing here: https://webmaster.yandex.com/tools/microtest/

Testing here: https://search.google.com/structured-data/testing-tool only "priceRange" is missing (Warning)

Where do you get the error message?

**Comment by danbri** [comment]
See also #1064 #1671 

@vholland and @betehess  were involved in this previously. I've a feeling there was some rough consensus to adding inLanguage at least for EntryPoint. Views?

**Comment by vholland** [comment]
I think I muddied the waters by following this with proposing LinkRole (#1045), which was complicated and I abandoned the idea. I still think ```inLanguage``` is useful.

**Comment by ayumihamsaki** [comment]
@joo7 when I was testing I saw exactly the same as what you said in Google (warning) and Yandex (error). I just thought I'd open this issue as there seems to be many open/closed issues here asking for **inLanguage** to be expanded into other things.

Anyway I thought I let you guys know about it and let you decide what to do?

Personally I agree with vholland that inLanguage is very useful and it would be nice to see it expanded into other classes.

**Comment by 88kbbq** [comment]
inLanguage is not supported in testing tools, but the HTML lang attribute should declare your doc language. Maybe redundant.

**Comment by ayumihamsaki** [comment]
closing error now fixed
