### ISSUE TITLE
CreativeWork -> DictionaryItem? Meaning?

### ISSUE THREAD

**Issue by l00mi** [schemaorg/schemaorg#1711]
Is or was there a Type describing a DictionaryItem or Meaning inside a Dictionary?

The attributes should be able to cover entries like:
- http://www.urbandictionary.com/define.php?term=OOTD
- http://dictionary.cambridge.org/dictionary/english/adorable
- http://www.duden.de/rechtschreibung/Friedensabkommen
- http://www.larousse.fr/dictionnaires/francais/assurer/5921

References: https://www.w3.org/2004/02/skos/

**Comment by VladimirAlexiev** [comment]
@l00mi Lexicology is quite a complex discipline, so just 3 classes `Dictionary DictionaryItem Meaning` won't be enough.
The Linguistic Linked Data community has defined ontologies like LEMON, and Wikidata is now also doing it (since extracting RDF out of Wiktionary is quite a nightmare).

So what's the purpose of also doing it in Schema? Do you have some viable use cases, like demonstrable desire by Duden or Larousse to markup their pages with semantic data?

**Comment by l00mi** [comment]
Thank you for the answer.
DictionaryItem or Meaning where not final propositions or anything. Just to make myself clear what this is about.

Regarding Complex Ontologies, why not start simple for the use case of discovery on the web and then extend where necessary? Should be the approach of schema.org, no?

We work on publishing a Governmental Dictionary and like to annotate it with schema.org. These are quite specific terms which might be use full if index in search machines.

**Comment by HughP** [comment]
How is this simple ontology any more useful that what is already availible
in html ?

all the best,
- Hugh
via android from Northwest Nigeria

**Comment by l00mi** [comment]
Hmm, @HughP you ask why is a explicit ontology better than html?

**Comment by RichardWallis** [comment]
> "We work on publishing a Governmental Dictionary"

Rather than a generic dictionary use case this may well be more of a defined term list type of scenario that [CategoryCode](http://pending.schema.org/CategoryCode ) was introduced to support.

Building on some of the examples in the documentation you could imagine the following markup:
```
{
 "@context": "http://schema.org/",
 "@type": "CategoryCode",
 "name": "Budget",
 "description": "The process of delivering financial information to the parliament",
 "inCodeSet": "http://example.gov.org/GovernmentTermDictionary"
}
```
Excuse my simplistic example.

**Comment by l00mi** [comment]
@RichardWallis thank you very much for this pointer!

This might do for our use case. The only two things which bother me a bit are:
- We don't actually have __codeValue__ for our entries.
- And the naming __CategoryCode__ is kinda of misleading as this actually is a dictionary and not a code catalog.

I guess something like __Meaning__ or __DictionaryItem__ is a bit dangerous of a Type as it could be easily misunderstood / misused ? Other than the I kinda of wonder why it is not yet there?

**Comment by HughP** [comment]
I definitly see the benefit for overt definitions.

Within html I was referencing the <dd>, <dt>, and <dl> tags. I was assuming
that these elemnts have a use case and semqntics which fits the dictionary
space.

<dl>
  <dt>Coffee</dt>
  <dd>Black hot drink</dd>
  <dt>Milk</dt>
  <dd>White cold drink</dd>
</dl>
Try it Yourself »
<https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_dd_test>
------------------------------


https://www.w3schools.com/tags/tag_dd.asp

all the best,
- Hugh
via android from Northwest Nigeria

**Comment by l00mi** [comment]
@HughP Okay I see where you coming from. Now this seems on the other end of what @VladimirAlexiev is mentioning.. a bit too simple (-,

But I think the __CategoryCode__ proposed by @RichardWallis might cover our use case case quite well. I just need to wrap my head around the wording I guess.

**Comment by philbarker** [comment]
The definition for category code ("a category code") could be expanded to explain how it encompasses things that aren't codes and don't refer to categories :) "Defined term" might actually be the way forward here. @RichardWallis  how tied are you to the existing name / definition?

**Comment by l00mi** [comment]
That would be a splendid development from my point of view.

**Comment by RichardWallis** [comment]
The [CategoryCode](http://pending.schema.org/CategoryCode) name ended up being a compromise in the [proposal](https://github.com/schemaorg/schemaorg/issues/894) where it was initially named **EnumerationValue**.  The spirit of what we are talking about here was in there from the beginning "_When marking-up with Schema.org there is often need to associate the Thing being described with a pre-defined value - a type, category, subject, topic, definition, etc._"

I am not particularly tied to the current name, however there are use cases and examples based around things that most definitely fit the pattern of category definitions with codes.

As you can also see from this example http://pending.schema.org/CategoryCode#catcode-3 the dictionary term definition had already been catered for.

The current minimal description could be expanded as a start.

As it is still in pending, we could consider renaming to _CategoryCode_->_TermDefinition_, _CategoryCodeSet_->_TermDefinitionSet_, _inCodeSet_->_inTermSet_, _codeValue_->_termCode_, _hasCategoryCode_->_hasTermDefinition_.

The question being, would that move to make it more appropriate for the topic of this thread make it less appropriate for other code set use cases?

**Comment by HughP** [comment]
Also, In addition to LEMON there is the SIL XHTML defacto "standard" which
they are using to publish online dictionaries in minority languages.
http://software.sil.org/pathway/features/standards/dictionary-xhtml-proposed-standard/

There are some 100+ minority language dictionaries on Webonary.org SIL's
Publishing platform (and growing). So if this discussion is actually about
lexicography this resource might be a good thing to consult. From what I
gather from SIL they feel there isn't really any benefit for semantic
markup beyond what is needed in the publication process for layout on
physical pages. That is the use case / business case hasn't been made clear
to them why they should adopt an RDFa markup for online lexicons.

**Comment by l00mi** [comment]
@RichardWallis This would most definitely be perfect for our use case as the project itself uses the name "Term" in its title. (-:
Unfortunately I can't comment on the use cases where its is used for codes. But I guess as the property termCode stays it might be clear enough (after the Type __TermDefinition__ was found for the use case that is.)

**Comment by l00mi** [comment]
@HughP I see thank you. I like the project which I did not know until now. Myself speaking a minority dialect this might get into contact with them. (-, 

For our use case on the other hand we like to adopt schema.org for publishing.

**Comment by philbarker** [comment]
@RichardWallis Thanks Richard, I was aware of (and wary of) the long history of this proposal, but I do think that if it is meant to address describing things such as "a type, category, subject, topic, definition, etc." then picking only one of those things for the name is a mistake. Focussing on the fact that there is some thing with a pre-defined value seems overall better, to me. So, I would support that we consider renaming. 
I think that DefinedTerm is better than TermDefinitiion as it focusses more on the term than the definition which is closer to "category code" use cases, and so I think goes some way to addressing you point of needing to be appropriate for those other topics as well as this one.

As for the definition, how about:
DefinedTerm: a word or code with a formal definition. Often used in the context of category or subject classification, glossaries or dictionaries, product or creative work types, etc. Use the name property where term being defined is a natural language word, use termCode if the term is an alpha-numeric code, use description to provide the definition.

Perhaps we should discuss under issue #894 if we go any further.

**Comment by RichardWallis** [comment]
> Perhaps we should discuss under issue #894 if we go any further.

@philbarker Agree - lets just loop round one more time to get a bit of agreement to feed into that issue...

Liking the **DefinedTerm** name - so we would have:
_CategoryCode_->_DefinedTerm_, _CategoryCodeSet_->_DefinedTermSet_, _inCodeSet_->_inDefinedTermSet_, _codeValue_->_definedTermCode_ or just _termCode_, _hasCategoryCode_->_hasDefinedTerm_.

The **name** property would always be the term itself - the optional _definedTermCode_ would be used if the previously established term set already has codes allocated (for example Library of Congress Subject Headings).

Another go at definition:
DefinedTerm: a word, name, acronym, phrase, etc. with a formal definition. Often used in the context of category or subject classification, glossaries or dictionaries, product or creative work types, etc. Use the name property for the term being defined, use termCode if the term has an alpha-numeric code allocated, use description to provide the definition of the term.

**Comment by l00mi** [comment]
Sounds perfect to me! I have a slight preference for the __termCode__ as __definedTermCode__ makes me squint my eyes (-,

**Comment by philbarker** [comment]
Looks very good to me. I prefer termCode. I like the additions of acronym and phrase to the definition.  

I see your point about the 'code' being an identifier for the term that is defined, not the thing being defined, i.e. that the name is the term itself and you dropped 'code' from the examples of terms. However, people who deal with coding spaces seem to think more in terms of defining the codes that they use and then giving them a label or two (I've recently come from working on the coding scheme used to define the subjects of courses in UKHE). It might be worth keeping code in the examples of terms. But it's not a big issue for me.

**Comment by thadguidry** [comment]
FYI, Wikidata is going to be using LEMON also.

**Comment by VladimirAlexiev** [comment]
@l00mi For your dict, you can use `CategoryCodeSet` (or `TermSet` or whatever it gets renamed to), with `additionalType` designating Dictionary. Use https://www.wikidata.org/wiki/Q23622 to designate this: WD is an excellent inventory of types/entities 

and has a deep hierarchy, eg (numbers indicate the count of instances in WD):
lexicon 302 encyclopedic dictionary 189 machine-readable dictionary 185 glossary 18 reverse dictionary 9 specialized dictionary 7 bilingual dictionary 6 explanatory dictionary 6 rime dictionary 5 etymological dictionary 3 idioticon 2 slang dictionary 2 synonym dictionary 1 learner's dictionary 1 visual dictionary 1

@thadguidry >Denny is going to try to get the Babelnet mappings CC0
Please say more.

**Comment by l00mi** [comment]
@VladimirAlexiev Perfect, thank you very much.

**Comment by VladimirAlexiev** [comment]
That subclass list is from https://tools.wmflabs.org/sqid/#/view?id=Q23622 (wait half a minute).
I didn't know what is rime dictionary (it is rhyme dictionary), and idioticon (!) reminded me of the "For Dummies" book series, but it's something else

**Comment by l00mi** [comment]
@RichardWallis What would be necessary to push this through?

**Comment by stuartasutton** [comment]
I, too, like Richard's revised definition.

+1 DefinedTerm
+1 termCode

**Comment by RichardWallis** [comment]
Created issue #1775 to instigate changes.

**Comment by jvandriel** [comment]
Just to make sure that I'm understanding the changes appropriately... 

I'm working on a project for which I'll be publishing Google Adwords specific structured data (for analytical purposes) together with the rest of the markup and for which I was planning to use ```CategoryCode``` as such:

```
<script type="application/ld+json">
{
  "@context":"https://schema.org",
  "@type":"Product",
  "name":"Slim-fit jeans",
  "category":
  {
    "@type":"CategoryCode",
    "name":"Apparel & Accessories > Clothing > Pants",
    "codeValue":"204",
    "inCodeSet":"http://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.xls"
  }
}
</script>
```
Am I right assuming I should now write it like this?

```
<script type="application/ld+json">
{
  "@context":"https://schema.org",
  "@type":"Product",
  "name":"Slim-fit jeans",
  "category":
  {
    "@type":"DefinedTerm",
    "name":"Apparel & Accessories > Clothing > Pants",
    "termCode":"204",
    "inDefinedTermSet":"http://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.xls"
  }
}
</script>

**Comment by RichardWallis** [comment]
@jvandriel As a translation from the current version (in pending) to the proposed updated version, yes.

As to your actual real-world example, It would be nice if that taxonomy was web addressable and each term had its own URI. 

However what you have produced is a good example of how a useful structured [web] data description can be provided for structured data that is not directly web accessible, using this approach.

**Comment by jvandriel** [comment]
Thanks for the confirmation @RichardWallis.

As for the real-world example, like I said, I'm going to publish this data this for analytical purposes (by feeding it back into our systems) and am not expecting Google (Adwords) to understand/adopt it any day soon as Adwords doesn't support the 'category' property (yet).

Nevertheless I was happy to see EnumerationValue/CategoryCode/DefinedTerm being proposed as it provides me with ways to measure the results of front-end taxonomies against backend and marketing taxonomies by using some of the proposed Type(s) and properties. 

Yeah for looking beyond rich snippets for the advantages of structured data.   \o/

And who knows, maybe once I've got it all up and running I can convince some Adwords peeps to have a look at it and adopt the it as well.

**Comment by l00mi** [comment]
DefinedTerm is since some time in Pending and is used in multiple places as expected Value. Thank you for the help! Closing this issue.

One Issue which came up while using it for our use case: https://github.com/schemaorg/schemaorg/issues/2415

**Comment by VladimirAlexiev** [comment]
@thadguidry said "@vrandezo is going to try to get the Babelnet mappings CC0 licensed)".
I'm very interested in such developments. I searched for "babelnet" on lists.wikimedia.org but came up empty... https://www.google.com/search?q=babelnet+site%3Alists.wikimedia.org . Any news?
