### ISSUE TITLE
pagination for ItemList

### ISSUE THREAD

**Issue by Malvoz** [schemaorg/schemaorg#1714]
Can we allow [pagination](https://schema.org/pagination) for products lists ([ItemList](https://schema.org/ItemList))?

**Comment by VladimirAlexiev** [comment]
@Malvoz Can you elaborate with an example?
- That prop describes pagination of printed matter (eg "article takes pages 3,5-6 of a journal, where page 4 is an advertisement"), whereas I think you want a mechanism to express pagination of long lists on a website. See https://www.w3.org/2012/ldp/hg/ldp-paging.html for inspiration.
- Even if you want to capture only page numbers (not page URL pattern), then pageStart, pageEnd will suffice since we're talking continuous pages.

**Comment by diffen** [comment]
Say you have a catalog with a list of 35 products. You show 15 products per page (URL). So your `ItemList` will be spread across 3 pages. 

On each page your schema will state `numberOfItems` as 35. The `ListItems` on the first page will begin with `position` 1 and go on till `position` 15. The `ListItems` on the second page will begin with `position` 16 and so on. On each page, the schema will only have 15 `ListItems`. 

So we are unable to signal that the list on each page is a partial list. Pagination attributes on `ItemList`s will allow us to split them and use pointers to each other. Kind of like rel=next and rel=prev.

**Comment by VladimirAlexiev** [comment]
@diffen this is a good use case, but:
@Malvoz `pagination, firstPage, lastPage` are not appropriate for this purpose.
So could you make a specific example of what props you want to use for this purpose?

**Comment by VladimirAlexiev** [comment]
Note: LDP uses `rel=first,prev,next,last` links: https://www.w3.org/2012/ldp/hg/ldp-paging.html#ldpp-ex-paging-other-links

**Comment by diffen** [comment]
@VladimirAlexiev How about the following new properties for `ItemList`

Property     | Expected Type | Description
-------------|---------------|------------
isPaginated  | Boolean       | Whether an `ItemList` is partial and paginated.
nextPageUrl  | URL           | The URL where more items, with higher `ItemPosition`s, belonging to a paginated `ItemList` may be found.
prevPageUrl  | URL           | The URL where more items, with lower `ItemPosition`s, belonging to a paginated `ItemList` may be found.

**Comment by VladimirAlexiev** [comment]
I'd stick to canon: `prev, next`. And how about `first, last`?

But there's a bigger question here (@danbri @RichardWallis): how does Schema look at `Link: rel=` headers as used by LDP? Is it kosher to duplicate them in RDF?

Guess why not: the Portland Common Data Model (for DAMS) uses
```ttl
@prefix iana:  <http://www.iana.org/assignments/relation/> .
iana:first, iana:prev, iana:next, iana:last
```
See some diagrams https://github.com/duraspace/pcdm/wiki/Diagrams-with-rdfpuml

**Comment by jimmywarting** [comment]
+1 for `prev, next, first, last`

**Comment by jono-alderson** [comment]
I'd be really keen for this; it feels particularly awkward to describe a multi-page series in 'chunks' without any kind of indicators as to the relationship any given page has to its siblings.

For context, Google historically supported `link rel="next"` and `link rel="prev"` (though have recently deprecated them). As such, a lot of the infrastructure for broad adoption is readily available, but currently falling into disrepair.

+1 for adding `prev`, `next`, `first` and `last` properties to `itemlist`, each of which may expect a `URL` (for multi-page series, such as a blog archive) or a `CreativeWork` (for non- multi-page series, such as a magazine embedded in a webpage)

**Comment by jvandriel** [comment]
5 years ago I had a go at creating markup examples for paginated itemlists while we were discussing adding ```ItemList``` to the vocabulary. If you take a look at [the examples](https://www.w3.org/wiki/WebSchemas/ChainingLayoutElements#Paginated_Ordered_ItemList) I created you'll see that it easily becomes very tricky to do this correctly and the 'assumption' back then was that if we walk this route we'll only end up with more 'bad' implementations than 'correct' ones, and thus we let that idea go.

Having said that, since we weren't 100% sure about the assumptions made, ```nextItem``` and ```previousItem``` were added as properties for 'ListItem' so those that want to create paginated itemlists can do so (as shown in the example doc I shared aboved).

Might it be an idea somebody sets up a Google [custom search engine](https://cse.google.com/cse/) to find it whether or not anybody out there is actually using ```nextItem``` and ```previousItem``` before we continue this discussion?

**Comment by jono-alderson** [comment]
Hmm. Can you talk me through where you concerns for it failing are? 

To my mind, there are two key considerations which make this (seemingly) pretty straightforward:
- JSON-LD is increasingly the de-facto standard, and this sort of thing is much easier to represent when it's not tied to the HTML markup.
- A decent chunk of the web is already running code to determine and output the URLs for the next/prev pages in a set (and, in some cases, the first/last, too), and it should be relatively trivial to adapt/repurpose those (given that Google has discontinued support) to just output 'next' and 'prev' URL properties in existing `ItemList`.

Also worth noting that I'm keen to roll this into our Yoast-graph, and eventually with some wrangling, into WordPress core :)

**Comment by jvandriel** [comment]
> "Hmm. Can you talk me through where you concerns for it failing are?"

The main concern was that for this to work people would have to use either @itemid, @resource or @id. Something schema.org (and it's sponsors) has been trying to avoid as the concept of identifiers introduces a whole new level of complexity for the average publisher out there.

Now I'm not saying we shouldn't introduce a way for folks to express paginated content (did my fair share of trying to get this to happen) but by now I wonder what the purpose of it would be if no data consumer out there has ever publicly expressed any need for it.

And given the fact Google recently expressed they no longer use rel="next/prev" I doubt we'll get any support from their end. 

@danbri, can you give us any insights into whether any of the sponsors would be interested in markup that expresses pagination?

**Comment by mfhepp** [comment]
Hi Jarno:

> On 9. Oct 2019, at 15:29, Jarno van Driel <notifications@github.com> wrote:
> 
> Having said that, since we weren't 100% sure about the assumptions made, nextItem and previousItem were added as properties for 'ListItem' so those that want to create paginated itemlists can do so (as shown in the example doc I shared aboved).

If I remember correctly, the motivation for nextItem and previousItem was not so much pagination, but the ability to model ordering of ListItem elements either by the explicit or implicit sort order of the values for the position property, or by modeling a chain of nextItem and previousItem between elements that could be traversed.

Both a standard data structures in Computer Science, so at least I argued back then that both ways should be supported. The use of a literal value space with a sort order is easier to process in many query languages, while the nextItem and previousItem pairs are easier to traverse (e.g. determining if there is a next item and fetching that); and that ways supports cycles, if needed.

Best wishes
Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mfhepp@gmail.com
@mfhepp

**Comment by jono-alderson** [comment]
Gotcha. I hadn't considered the need for IDs to explicitly connect ItemLists split between pages; I'd glossed over that, with the assumption that it'd be enough that the presence of an ItemList which 'picks up' the series on a referenced page would be enough to infer the relationship...But obviously that gets complex in some scenarios (particularly if/when there are multiple lists).

From my exposure to Google's treatment of this sort of thing, there's no interest/capacity in multi-page graphs; only in the context of the page in question.

I find it hard to imagine that this wouldn't be useful to other consumers, though; there's literally no model at all on the public web which describes multi-page paginated content (such as a blog archive) in a structured manner. :/

**Comment by jvandriel** [comment]
You're absolutely correct @mfhepp. Now that you mention it I remember those discussions. Using the same mechanism for pagination was something I argued for, which in return triggered me to write those examples. Thanks for pointing it out.

**Comment by zicklag** [comment]
So, I have a blog-type list of articles display with a certain number per page with a pager at the bottom of the page. Am I correct in my understanding that there is currently no way to indicate with RDF that the links in the pager link to different pages of the same `Periodical`?

**Comment by RichardWallis** [comment]
@zicklag  If each individual article page is marked up, there should be no need to markup a list of links to those pages.  A list of links is to assist human navigation, whereas a search engine should already know about (have crawled) the individual pages and their markup.  

Hence structured data pagination becomes not an issue.

See this comment from Google's developer documentation:

> A category page listing several different products (or recipes, videos, or any other type). Each entity should be marked up using the relevant schema.org type, such as schema.org/Product for product category pages. However, if one item is marked, all items should be marked. **Also, unless this is a carousel page, the marked items should not link out to separate details pages**.

_My emphasis_
