### ISSUE TITLE
'familyName' definition shouldn't claim to replace 'name'

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1717]
Currently we say: "[familyName] can be used along with givenName instead of the name property."

This is not such a great idea. There are lots of names which do not break down into simple familyName and givenName parts easily, and it is often quite useful to have a simple 'name' property. Requirements as to which one to use ought to be left to consuming applications to articulate.

I suggest dropping that whole final sentence.

Via https://lists.w3.org/Archives/Public/public-schemaorg/2017Aug/0010.html

see also http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by makxdekkers** [comment]
Another useful reference: https://www.w3.org/International/questions/qa-personal-names

**Comment by nicolastorzec** [comment]
- +1 for dropping that last sentence from [familyName](http://schema.org/familyName)
- Same applies to [firstName](http://schema.org/firstName)
- Also there's a typo: the definition should read "In the U.S., the last name of ***a*** Person"

**Comment by VladimirAlexiev** [comment]
I don't think it should be dropped. If y'all are right, why do we have givenName and familyName then?
I think it should be replaced with a more elaborate text that explains:
- givenName and familyName are applicable mostly for Western names, so it's a good idea to also keep the full name;
- provide the two excellent links above ("falsehoods" and "qa")
- having separate givenName and familyName is sometimes useful for name matching, eg in bibliographic citations often the given name is shortened to an initial and swapped with the familyName
- familyName is useful for sorting purposes, and for genealogical research

**Comment by vholland** [comment]
@VladimirAlexiev I am not sure I understand your objection. As I read the previous comments, we would keep ```familyName``` and ```givenName```, but would stop suggesting that somehow concatenating the two is equivalent to ```name```.

**Comment by VladimirAlexiev** [comment]
My objection is that rather than removing altogether the comment explaining the relation between these props, we should make that comment more elaborate. We could further add: 
"Concatenating `familyName` and `givenName` doesn't necessarily produce a string that is equivalent to `name`, since `name` could also include middle name or initial, `honorificPrefix`, `honorificSuffix` or a generational suffix (eg "Sr", "Jr") that may not be captured"

**Comment by nicolastorzec** [comment]
@VladimirAlexiev, beyond noting that "givenName + familyName" is not equivalent to "name", 
Dan's point was also about simplifying the definition for content producers :)

**Comment by VladimirAlexiev** [comment]
@nicolastorzec  IMHO these descriptions are not definitions but scope notes (when to use what how): the more explanation and comparison, the better.
The very fact we're having this discussion suggests it's imprudent to kill any explanation of the relation between these 3 props.

**Comment by HughP** [comment]
@RichardWallis this is mostly a documentation issue not a schema issue per se. is there a label in the repo issue workflow for documentation issues?

**Comment by RichardWallis** [comment]
Fixed in commit af9e7bc for inclusion in next release.
