### ISSUE TITLE
sharedContent or image for embedded image in SocialMediaPosting?

### ISSUE THREAD

**Issue by tomwparsons** [schemaorg/schemaorg#1719]
Say a blog post has an embedded image(s) or a tweet has an image, do we use the sharedContent or image type? e.g.

`"sharedContent": [
    {
      "@type": "MediaObject",
      "publisher": "twitter",
      "url": "http://example.com/image_url"
    },
    { 
      "@type": "MediaObject",
      "url": "http://example.com/image_url1"
    }
  ]`

or

`"image": [
  {"@type":"ImageObject",
  "image":"https://pbs.twimg.com/media/DG9-w5kXcAALRRC.jpg:large"
  },
  {"@type":"ImageObject",
  "image":"https://pbs.twimg.com/media/DG9-w5kXcAALRRC.jpg:small"
  }
  ]`

**Comment by millercl** [comment]
[`Thing.image`](http://schema.org/image) is an image of the thing, like a screenshot of `div.tweet`, therefore not the second example.  [`articleBody`](http://schema.org/articleBody) for the `p.tweet-text` `innerText` while [`SocialMediaPosting.sharedContent`](http://schema.org/sharedContent) is the [`ImageObject`](http://schema.org/ImageObject), and therefore the first example. `sharedContent` could be considered `owl:sameAs` or `rdfs:subPropertyOf` to [`CreativeWork.hasPart`](http://schema.org/hasPart).
