### ISSUE TITLE
publisherImprint description and range

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1724]
@RichardWallis 
http://bib.schema.org/publisherImprint is described as "The publishing division which published the comic".

https://en.wikipedia.org/wiki/Imprint#Publishing defines 3 meanings relevant to us:
- Imprint (trade name), a publisher's trade name under which works are published
- Imprint (bibliography), bibliographic information about a book: the publisher's name and address, and the book's date of publication on a title page
- Impression (publishing), a fine distinction of a book's version, differentiating, for example, printing runs or publishers; used with ISBN

None of these meanings talks specifically about comics, and none is necessarily about a division (one publisher division may publish several imprints). The key word is "trade name", eg the https://en.wikipedia.org/wiki/For_Dummies book series that was published by 2-3 publishers (hardly divisions of each other!)

So I propose to change it as follows:
- description "Publisher division that published the CreativeWork (eg Nature as a division of Springer-Nature), or trade name that the CreativeWork was published under (eg the "For Dummies" book series, published by IDG Books / Hungry Minds, and later by John Wiley & Sons)."
- rangeIncludes: 
  - Organization (as now), 
  - CreativeWork (eg Journal or BookSeries)
  - text

**Comment by RichardWallis** [comment]
The mention of comics is a historical residue of the term's introduction and could easily be dropped.

I would agree with a description change to something like:

"Publisher division that published the CreativeWork (eg the Nature division of Springer-Nature), or trade name that the CreativeWork was published under (eg the "For Dummies" book series) provided as text or as a reference the CreativeWork with that [trade] name"

**Comment by VladimirAlexiev** [comment]
The last part "provided as text or as a reference the CreativeWork with that [trade] name" doesn't parse nicely. Please make it a separate sentence.
How about the `rangeIncludes` change?

**Comment by RichardWallis** [comment]
OK how about:

"Publisher division that published the CreativeWork (eg the Nature division of Springer-Nature), or trade name that the CreativeWork was published under (eg the "For Dummies" book series). Trade name should be provided as text or as a reference the CreativeWork with that [trade] name"

Adding CreativeWork to rangeIncludes yes.
All properties in Schema.org can default to either Text or URL, and I don't see the need to be explicit in this case.

**Comment by VladimirAlexiev** [comment]
- almost perfect, but how about: "`CreativeWork` (eg `BookSeries` or `Journal`) representing that trade name"
- "either Text or URL, and I don't see the need to be explicit": hmmm, eg http://health-lifesci.schema.org/status mentions Text. 
@danbri what do you say, should we mention "Text" specifically as possible value of `publisherImprint`?

**Comment by renevoorburg** [comment]
We are in need of a property for the bibliographic information about the publication (publisher + optional details + date) _in the way it is presented on the publication_.  That is an essential addition that for us defines a publication imprint. For just representing the actual publisher, date and place of a publication we use the schema:publication event. Indeed, this is in according to the second bullet given by @VladimirAlexiev: "bibliographic information about a book: the publisher's name and address, and the book's date of publication on a title page".

So I would propose a such a definition:

"Bibliographic information about a creative work as provided by on the title page: the publisher's name and optional additional details, as for example the address and date of publication."

The domain should be a CreativeWork and the range text. The essence of the bibliographical imprint is it literal nature.

**Comment by Dataliberate** [comment]
@renevoorburg  I understand the bibliographic cataloguing need to capture the actual publishing information and separately the way that information is presented on the publication.  

However, I believe trying capture that information in the _publisherImprint_ property conflicts with the use case being addressed in the main content of this issue. 

What you are trying to capture is the concatenated (in cataloguing/publisher shorthand) string that represents the individual elements of the PublicationEvent.  In that case I see it as a property of that PublicationEvent, not the CreativeWork that was published.  Using general Schema.org properties I would suggest:
```
{
  "@context": "http://schema.org",
   "@type":  "Book",
   "@id": "<uri_book>",
   "publication":  {
        "publishedBy": "<uri_publisher>",
        "startDate": "1699",
        "location": "Amsterdam",
       "description": "Amsteldam, erfg. J. Lescailje, 1699"
    }
}
```

_description_ may not be the best property - could use _name_ or _alternateName_.

**Comment by renevoorburg** [comment]
@Dataliberate that approach indeed fits what we want to capture. As you suggest, a property like _name_ might be even better. Thank you!

**Comment by VladimirAlexiev** [comment]
@renevoorburg there already is "name" but I would still use "description".
