### ISSUE TITLE
honorificSuffix description

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1725]
http://schema.org/honorificSuffix "An honorific suffix preceding a Person's name such as M.D. /PhD/MSCSW."
- should be "following" not "preceding"
- forgive my grammar skills, but shouldn't it start with "A honorific" not "An honorific"? This is EN not FR so the leading "h" is sounded

**Comment by philbarker** [comment]
On the second point, in this case no, the h isn't sounded, or at least it isn't stressed enough to make "a honorific" easier to say (in en-GB, other varieties of English may vary). https://www.quora.com/Is-it-an-honor-or-a-honor-Which-is-grammatically-correct

**Comment by vholland** [comment]
From en-US, 'an honorific' sounds more correct. But what do we know, we say 'erbs rather than herbs.

**Comment by philbarker** [comment]
@vholland so en-GB and en-US are the same for honorific (sorry wasn't explicit) in UK to "an honorific" sounds correct. (but oregAHno is a herb ;-)

**Comment by stuartasutton** [comment]
+1 "an honorific" in en-US since it is pronounced as a soft "h" (unlike "a house").

**Comment by HughP** [comment]
Actually @RichardWallis this issue was never corrected... the main issue was that the documentation has an error in it with the usage of preceding.
The OP states:
> -  should be "following" not "preceding"

**Comment by dr-shorthair** [comment]
or replace 'preceding' with 'to' or 'on', since 'suffix' already implies the ordering relationship.

**Comment by RichardWallis** [comment]
Fixed in commit 1d39620 - to be included in next release.

**Comment by dr-shorthair** [comment]
'suffix' together with 'following' is tautological, though harmless.
