### ISSUE TITLE
ItemList as CreativeWork

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#1728]
Lists don't often arise without someone/thing creating them. Sometimes it's useful to know who created them and when (e.g. in whose opinion are these the top 10 movies about weathermen, was the list made before or after Sharknado 4 was released?).
Is there a reason for ItemList not being a subtype of CreativeWork?

**Comment by RichardWallis** [comment]
Or you could define the thing you were describing as being both a CreativeWork and an ItemList.

```"@type": ["CreativeWork","ItemList"],```

I get the impression that ItemLists are being used to say order lists of products on a page etc.  In such a scenario the extra baggage of properties that come with CreativeWork as a supertype could well be confusing.

**Comment by philbarker** [comment]
Thanks @RichardWallis , I'll take that for now.
