### ISSUE TITLE
add intergovernmental organization  as specific type of Organization

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#1730]
IGO is [international governmental organization](https://www.wikidata.org/wiki/Q245065), Wikidata's `Q245065`, is a **[Organization](http://schema.org/Organization) Type**. Is used also in [cc-by-igo](https://creativecommons.org/licenses/by/3.0/igo/legalcode) and many other contexts (Europe, UN, etc.).

**Comment by akuckartz** [comment]
@danbri That bot is still to aggressive. My suggestion is to allow 1-2 months for reactions instead of just one week. @ppKrauss
