### ISSUE TITLE
MusicVideoObject should be a VideoObject

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1733]
Currently:

* http://schema.org/MusicVideoObject

  > `Thing` > `CreativeWork` > `MediaObject` > `MusicVideoObject` 

* http://schema.org/VideoObject

  > `Thing` > `CreativeWork` > `MediaObject` > `VideoObject`

**Proposal:** Add `VideoObject` as parent type of `MusicVideoObject`.

Then we can provide `actor`, `director` etc. also for `MusicVideoObject`. I guess it makes sense to use `musicBy` for the music video’s music.

**Comment by vholland** [comment]
+1

**Comment by AdrianMachado** [comment]
+1
