### ISSUE TITLE
What Type of schema.org should I use? 

### ISSUE THREAD

**Issue by delac147** [schemaorg/schemaorg#1735]
Hi, 

I am having trouble picking which kind of event should I pick, I want to implement schema.org vocabulary into the pages of my site that are offering different kinds of events such as: 

Christmas Parties, Rooftop Parties, Bespoke Parties or Events and Summer Parties among others. 

What Type should I choose, I can't seem to find any that would fit... 

Thanks!

**Comment by RichardWallis** [comment]
If, amongst the selection of Event subtypes, you do not find an exact match look for an approximate match.  eg. A children's party could use _**ChildrensEvent**_.   If there is still no obvious match, use the **_Event_** type.

In all cases you would use the properties of the chosen type to describe the event more fully - about, audience, description, etc.

**Comment by delac147** [comment]
Thanks, appreciate the help!
