### ISSUE TITLE
Help with EventVenue type and automatization 

### ISSUE THREAD

**Issue by delac147** [schemaorg/schemaorg#1737]
Hi, 
 
I have a question regarding an Idea I am not sure it would work. 
I would like to implement structured data into some pages. The pages are different places in where I offer to organise events. Therefore I will use the following EventVenue script: 

<script type='application/ld+json'>
{
	"@context": "http://schema.org/",
	"@type": "EventVenue",
	"telephone": "XXX XXXX XXXX",
	"alternateName": "Example",
	"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero",
	"image": {
		"@type": "ImageObject",
		"caption": "Lorem ipsum",
		"contentUrl": "http://example.com/wp-content/uploads/xxx/xxxx.jpg",
	},
	"mainEntityOfPage": "https://example.com/xxx/xxxxxx/",
	"name": "Lorem ipsum dolor"
}
</script>

All the data I need to fill into each script is at the same position on each page.

So, I was wondering if there is a way to write some kind of code that subtracts the information from the page and inserts it into the schema.org script, so I don't have to go page by page and insert the information manually.

**Comment by RichardWallis** [comment]
In principle what you seek is possible.  A Javascript inserted into your pages could capture the data you want from the page and create the correct insert.  Some search engines run the scripts they find in a crawled page before harvesting the data from them, hence making that data available to them.

However, as the discussion and issue forum for the maintenance and enhancement of the Schema.org vocabulary, this is not the place to raise such questions about implementation issues.

Hopefully you can find answers on another list or perhaps Stackoverflow.
