### ISSUE TITLE
Some schema.org pages not showing properties 

### ISSUE THREAD

**Issue by etaion** [schemaorg/schemaorg#1738]
Some pages are not showing properties:
http://schema.org/Service
http://schema.org/Event

**Comment by RichardWallis** [comment]
Thanks @etaion for pointing that out.

I have fixed those two particular instances of this issue.   I will leave the issue open for others if they spot similar problems which will be hopefully fixed in an upcoming release to fix caching & page rendering.

~Richard.

**Comment by jvandriel** [comment]
The same is also happenong for http://schema.org/HowToItem

**Comment by RichardWallis** [comment]
Also fixed

**Comment by jvandriel** [comment]
Thanks @RichardWallis

**Comment by jvandriel** [comment]
I crawled schema.org and found the following:

*Type pages without a breadcrumb*
- http://schema.org/AuthorizeAction
- http://schema.org/BookFormatType
- http://schema.org/BroadcastService
- http://schema.org/ComputerStore
- http://schema.org/CreditCard
- http://schema.org/DataType
- http://schema.org/Electrician
- http://schema.org/HairSalon
- http://schema.org/HowTo
- http://schema.org/LocationFeatureSpecification
- http://schema.org/MusicAlbum
- http://schema.org/NoteDigitalDocument
- http://schema.org/OwnershipInfo
- http://schema.org/ParcelDelivery
- http://schema.org/PresentationDigitalDocument
- http://schema.org/PropertyValue
- http://schema.org/TechArticle
- http://schema.org/TypeAndQuantityNode
- http://schema.org/UserDownloads

*Type & property pages without a breadcrumb, properties and/or values*
- http://schema.org/DatedMoneySpecification
- http://schema.org/EventCancelled
- http://schema.org/EventPostponed
- http://schema.org/ItemListUnordered
- http://schema.org/PropertyValueSpecification
- http://schema.org/RefurbishedCondition
- http://schema.org/target

**Comment by RichardWallis** [comment]
Thanks @jvandriel for this analysis.
Although a small percentage of all the pages, the number in list is far too long (as in greater than zero).

I am going to look into at least a temporary fix and may call on your crawling capabilities as a test in the next few days.
~Richard

**Comment by jvandriel** [comment]
Just let me know and I'll happily check again.

**Comment by gajus** [comment]
Adding

* http://schema.org/Movie

To the list.

**Comment by carotsay** [comment]
Does anyone have any experience in using EventPostponed? Is this still useful or understood by google data structure (Rich Snippets)?

**Comment by RichardWallis** [comment]
@carotsay  This is more a question for a forum on Google search such as https://productforums.google.com/forum/#!categories/webmasters/structured-data

As you point out the [Schema.org] vocabulary supports this term, the use of which one would expect under current circumstances to 'go viral'.  However, if it is being seen more and is, therefore, being taken notice of, is down to the data consumers such as Google, Bing, etc. to comment upon. This form is more for discussion of the details of the vocabulary itself.
