### ISSUE TITLE
enable https on webschemas.org

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1739]
https://cloudplatform.googleblog.com/2017/09/introducing-managed-SSL-for-Google-App-Engine.html

**Comment by danbri** [comment]
> Verification steps completed!
> The domain webschemas.org has been successfully verified.

**Comment by millette** [comment]
All that is left is a redirect from http to https :-)

**Comment by danbri** [comment]
There is some fiddlyness in the corresponding appengine cloud panels, looks easier to do for exactly "webschemas.org" than "*.webschemas.org". I am seeing "Managed certificate for webschemas.org activated." and HTTPS works for me. 

This btw also seems to mean that CORS headers are served for the webschemas copy of the site.

I have been trying to adapt our old D3 visualization to use webschemas instead of the official site, but for some reason https://webschemas.org/docs/tree.jsonld and http: variant are both 500 errors. But that's another problem!  http://bl.ocks.org/danbri/1c121ea8bd2189cf411c

**Comment by danbri** [comment]
We did this
