### ISSUE TITLE
Capturing file metadata for textDigitalDocument - file size?

### ISSUE THREAD

**Issue by tomwparsons** [schemaorg/schemaorg#1740]
How do we store the file size using the textDigitalDocument schema? the only likely place is using MediaObject but this refers to an embedded file and not the top-level document itself? e.g. a PDF described by textDigitalDocument is 1.1mb in size

**Comment by RichardWallis** [comment]
I would describe your document as being both a [TextDigitalDocument](http://schema.org/TextDigitalDocument) and a [MediaObject](http://schema.org/MediaObject) which would then make contentSize, encodingFormat, etc. available:

```
<script type=“application/ld+json”>
{
  “@context”: “http://schema.org”,
  “@type”: ["TextDigitalDocument","MediaObject”],
  "name": "The document",
  "contentSize": "1.1Mb",
  "encodingFormat": "pdf",
  "contentUrl": "http://example.com/docs/doc1.pdf"
}
</script>
```
