### ISSUE TITLE
Proposal for new DiscountOffer type for promo codes

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1742]
Many online retailers have promo codes or discount offers. To make it easier for authors to describe this situation, I propose adding a new subtype of  Offer: **DiscountOffer**, with the following properties:
- **discountPercentage**: The value of the discount as a percentage of the original price.
- **discount**: The value of the discount as a number. Note, to get the original price, add the discount value to the price value. This property already exists on Order.
- **discountCurrency**: The currency (in 3-letter ISO 4217 format) of the discount. This property already exists on Order.
- **discountCode**: Code used to redeem a discount. This property already exists on Order.

An example would be:
```
{
  "@context": "http://schema.org/",
  "@type": "DiscountOffer",
  "description": "Original price $100. $10 off when using promo code: PROMO",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget"
  },
  "discount": 10,
  "discountCurrency": "USD",
  "discountCode": "PROMO",
  "price": 90
  "priceCurrency": "USD"
}
```

Alternatively, as a percentage:
```
{
  "@context": "http://schema.org/",
  "@type": "DiscountOffer",
  "description": "Original price $100.  10% off when using promo code: PROMO",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget"
  },
  "discountPercentage": 10,
  "discountCurrency": "USD",
  "discountCode": "PROMO",
  "price": 90
  "priceCurrency": "USD"
}
```
@mfhepp

**Comment by mfhepp** [comment]
Why do you want to introduce a new (third) modeling pattern for prices if we already have two?
I would simply use two Offers attached to the same Product with different prices, and maybe (not sure) add new properties to UnitPriceSpecification that reflects the fact that it is a discount. This will even allow modeling date range during which the discount is offered (using validFrom/validThrough on the UnitPriceSpecification.

http://schema.org/priceType can be used to indicate that it is a discount (simply change the textual definition of http://schema.org/priceType -> "DISCOUNT".

http://schema.org/eligibleQuantity allows you to specify quantity discounts.

http://schema.org/eligibleTransactionVolume allows you to specify purchasing amount discounts.

So maybe all you need is one single new property "discountCode": "PROMO", with a domain of PriceSpecification OR Offer. This will allow you to specify both item price discounts as well as handling charge discounts like free shipping.

Or am I missing anything?

**Comment by vholland** [comment]
I don't view it as adding a new modeling pattern so much as providing idioms for authors who may not require the full expressiveness of Good Relations. The approaches you mention would remain available to authors who wish to use them.

**Comment by thadguidry** [comment]
Like this conversation so far... DiscountCode was also mentioned during W3C Web Payments meeting https://docs.google.com/document/d/14T4C_ToW2XSCaKeGIG3fGMcm5OTnM0Ra8cBzbht7xx0

BUT they handled Discount as a separate line item within an order, rather than directly attaching to an Offer itself.  Which I tend to prefer.  So for us it would look something like this...

http://tinyurl.com/y9dvpc76

```
{
  "@context": "http://schema.org/",
  "@type": "Offer",
  "description": "Original price $100.  10% off when using promo code: PROMO",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget",
    "price": 90,
    "priceCurrency": "USD"
  },
  "discountOffered": {
  "@type": "Discount",
  "name": "10% off all stock on till February 1st !!!",
  "discountPercentage": 10,
  "discountCurrency": "USD",
  "discountCode": "FEBRUARY_10"
}
}
```

**Comment by danielbodart** [comment]
Do you really need the discountCode property, wouldn't it just be better to use the identifier property?

**Comment by ldexterldesign** [comment]
> I envision more complex compound price specifications including discounts, fees etc @download - #380

**Comment by ldexterldesign** [comment]
How I'm currently handling discounts and tax - welcome input:

```json
            "priceSpecification": {
              "$comment": "https://schema.org/PriceSpecification",
              "properties": {
                "deliveryChargeSpecification": {
                  "$comment": "https://schema.org/DeliveryChargeSpecification",
                  "properties": {
                    "eligibleRegion": {
                      "$comment": "https://schema.org/eligibleRegion",
                      "items": {
                        "examples": [
                          "england",
                          "uk",
                          "malta",
                          "eu",
                          "world"
                        ],
                        "type": "string"
                      },
                      "type": "array"
                    },
                    "price": {
                      "$comment": "https://schema.org/price",
                      "type": "number"
                    }
                  },
                  "type": "object"
                },
                "discountAmount": {
                  "type": "number"
                },
                "discountIncluded": {
                  "type": "boolean"
                },
                "price": {
                  "$comment": "https://schema.org/price",
                  "type": "number"
                },
                "priceCurrency": {
                  "$comment": "https://schema.org/priceCurrency",
                  "description": "do use currency code. do not use symbol (i.e. £, €).",
                  "examples": [
                    "gbp, eur"
                  ],
                  "type": "string"
                },
                "totalPrice": {
                  "$comment": "https://schema.org/totalPrice",
                  "description": "price + shipping + valueAddedTaxAmount",
                  "type": "number"
                },
                "valueAddedTaxAmount": {
                  "type": "number"
                },
                "valueAddedTaxIncluded": {
                  "$comment": "https://schema.org/valueAddedTaxIncluded",
                  "type": "boolean"
                }
              },
              "type": "object"
            },
```

Yours hopefully

**Comment by fili** [comment]
This proposal would be very useful to have in schema.org! 

> ```
> {
>   "@context": "http://schema.org/",
>   "@type": "Offer",
>   "description": "Original price $100.  10% off when using promo code: PROMO",
>   "itemOffered": {
>     "@type": "Product",
>     "name": "Premier Widget",
>     "price": 90,
>     "priceCurrency": "USD"
>   },
>   "discountOffered": {
>     "@type": "Discount",
>     "name": "10% off all stock on till February 1st !!!",
>     "discountPercentage": 10,
>     "discountCurrency": "USD",
>     "discountCode": "FEBRUARY_10"
>   }
> }
> ```

A few questions:
1. Should the price not remain the same (100 instead of 90) as the price has not changed, just when using the discount in addition. This makes the discount offered an additional and optional data point, not one that guarantees changes to the original data (price of itemOffered) in this case. The naming "discountOffered" already suggests it is optional.

2. In addition, discountPercentage does not use any currency, so that seems irrelevant here.

3. discountPercentage is very useful to have, but sometimes the offer is a specific currency amount, e.g. "$200 off for 1 month" which would not fit here. 

4. I also feel that the name "10% off all stock on till February 1st !!!" is more a description, not the actual name. 

5. discountCode is also very optional, e.g. at the online grocery store when buying a bag of apples at a discounted rate.

6. Discounts may also be applied to the final total invoice rather than individual offers of products or services, so it may be beneficial to not restrict Discount usage to only Offers.

With that in mind, would the following make sense?

```
{
  "@context": "http://schema.org/",
  "@type": "Offer",
  "description": "Original price $100.  20 USD off when using promo code: PROMO",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget",
    "price": 100,
    "priceCurrency": "USD"
  },
  "discountOffered": {
    "@type": "Discount",
    "name": "20 USD discount",
    "description": "20 USD off all stock on till February 1st !!!",
    "price": "20",
    "priceCurrency": "USD",
    "discountCode": "FEBRUARY_20"
    "validFrom": "2020-02-01",
    "validThrough": "2020-02-29"
  }
}
```

or in case of percentage:

```
{
  "@context": "http://schema.org/",
  "@type": "Offer",
  "description": "Original price $100.  10% off when using promo code: PROMO",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget",
    "price": 100,
    "priceCurrency": "USD"
  },
  "discountOffered": {
    "@type": "Discount",
    "name": "10 percentage discount",
    "description": "10% off all stock on till February 1st !!!",
    "discountPercentage": "10",
    "discountCode": "FEBRUARY_10"
    "validFrom": "2020-02-01",
    "validThrough": "2020-02-29"
  }
}
```

It may be beneficial to collapse discountPercentage and price and priceCurrency under two options: Number/Float (for percentage) and PriceSpecification (for monetary values).

for example:

```
{
  "@context": "http://schema.org/",
  "@type": "Offer",
  "description": "Original price $100.  10% off when using promo code: PROMO",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget",
    "price": 100,
    "priceCurrency": "USD"
  },
  "discountOffered": {
    "@type": "Discount",
    "name": "10 percentage discount",
    "description": "10% off all stock on till February 1st !!!",
    "amount": "10.0",
    "discountCode": "FEBRUARY_10"
    "validFrom": "2020-02-01",
    "validThrough": "2020-02-29",
    "url": "https://example.com/dedicated-discount-landing-page/"
  }
}
```
and 

```
{
  "@context": "http://schema.org/",
  "@type": "Offer",
  "description": "Original price $100.  20 USD off when using promo code: PROMO",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget",
    "price": 100,
    "priceCurrency": "USD"
  },
  "discountOffered": {
    "@type": "Discount",
    "name": "20 USD discount",
    "description": "20 USD off all stock on till February 1st !!!",
    "amount": {
      "@type": "PriceSpecification",
      "price": "20",
      "priceCurrency": "USD"
    },
    "discountCode": "FEBRUARY_20"
    "validFrom": "2020-02-01",
    "validThrough": "2020-02-29",
    "url": "https://example.com/dedicated-discount-landing-page/"
  }
}

The nice thing of discountOffered is also that we can now attach it to any level (Offer or Invoice) and also include a list of different discounts based on different values (e.g. dates and/or amount and/or codes).

```
{
  "@context": "http://schema.org/",
  "@type": "Offer",
  "description": "Original price $100.",
  "itemOffered": {
    "@type": "Product",
    "name": "Premier Widget",
    "price": 100,
    "priceCurrency": "USD"
  },
  "discountOffered": [{
    "@type": "Discount",
    "name": "February discount",
    "description": "20 USD off all stock on till February 1st !!!",
    "amount": {
      "@type": "PriceSpecification",
      "price": "20",
      "priceCurrency": "USD"
    },
    "discountCode": "FEBRUARY_20"
    "validFrom": "2020-02-01",
    "validThrough": "2020-02-29",
    "url": "https://example.com/dedicated-discount-landing-page-february/"
  }, {
    "@type": "Discount",
    "name": "March discount",
    "description": "25% off all stock!!!",
    "amount": "25.0",
    "discountCode": "MARCH_20"
    "validFrom": "2020-03-01",
    "validThrough": "2020-03-30",
    "url": "https://example.com/dedicated-discount-landing-page-march/"
  }]
}
```

**Comment by ADTC** [comment]
Cases where a coupon code or a voucher can apply a percentage discount or a fixed discount on an **unknown** price at checkout cannot be adequately represented by the schema (structured data) currently, because all representation models require a fixed price to be **known** in advance.

Very sad that the purpose of this proposal was misunderstood.
