### ISSUE TITLE
Movie type is missing property documentation

### ISSUE THREAD

**Issue by gajus** [schemaorg/schemaorg#1751]
http://schema.org/Movie

All I see are examples. No property definitions.

<img width="1920" alt="screen shot 2017-09-24 at 13 01 43" src="https://user-images.githubusercontent.com/973543/30782352-88b28adc-a128-11e7-925a-6a1da7cd0011.png">

**Comment by gajus** [comment]
On a similar note, I am surprised to see that schema has chose "name" property to describe movie title, instead of a movie title. There is a subtle difference between the two.

> Now, the title in this sense would of course also be used as the name of the book should one wish to refer to it, or at least we might create a name for it by abbreviating the title (e.g. the book with the title The Life and Strange Surprizing Adventures of Robinson Crusoe, Of York, Mariner: Who lived Eight and Twenty Years, all alone in an un-inhabited Island on the Coast of America, near the Mouth of the Great River of Oroonoque; Having been cast on Shore by Shipwreck, wherein all the Men perished but himself. With An Account how he was at last as strangely deliver'd by Pyrates is best-known by the name "Robinson Crusoe").

– https://english.stackexchange.com/questions/173675/whats-the-difference-between-title-and-name

**Comment by Aaranged** [comment]
This is a known issue; see https://github.com/schemaorg/schemaorg/issues/1738

**Comment by gajus** [comment]
Closing as a duplicate of #1738
