### ISSUE TITLE
add Architecture (or building) as creative work type

### ISSUE THREAD

**Issue by andrearicci** [schemaorg/schemaorg#1752]
I wish I could use schema.org on my architectures portfolio site. Unfortunatelly I cant't find a dictionary.
I would like to give it properties like type (like Public, Commercial, Residential, Religious....), size (sqm/sqft-or volume), budget, etcetera.
http://andrearicci.it
Thank you

**Comment by RichardWallis** [comment]
Checkout the full vocabulary here:  http://schema.org/docs/full.html 

The subtypes below _Place_ may be of help to you.
