### ISSUE TITLE
Proposal: BoatTrip, BoatStop, Harbor

### ISSUE THREAD

**Issue by fili** [schemaorg/schemaorg#1755]
There are local and public boat services (ferries) around the world, similar to:

http://schema.org/BusStation
http://schema.org/BusStop
http://schema.org/TrainStation
http://schema.org/BusTrip
http://schema.org/TrainTrip
http://schema.org/TaxiStand

What is missing is a possibility to mark these up, and the time tables.

**Comment by chollma** [comment]
Is there any update on this issue? The parent type (https://schema.org/Trip) is sufficient, but I would love to be able to more specifically mark up water-based trips like cruises which may not use the modes of transportation currently available on schema.org.

**Comment by magico** [comment]
Here's a proposal that is consistent with other existing types.

**BoatTerminal** - http://schema.org/BoatTerminal
BoatTerminal inherits from CivicStructure and is defined the same way as similar existing types like [BusStop](https://schema.org/BusStop). It does not add any new properties.

**BoatReservation** - http://schema.org/BoatReservation
BoatReservation inherits from Reservation and adds no new properties. This is similar to  [BusReservation](https://schema.org/BusReservation) and [TrainReservation](https://schema.org/TrainReservation).

**BoatTrip** - http://schema.org/BoatTrip
BoatTrip inherits from Trip and adds new properties for arrival/departure terminal (arrivalBoatTerminal and departureBoatTerminal), the name of the boat (boatName) and the identifier for the boat (boatNumber). Similar to [BusTrip](https://schema.org/BusTrip) and  [TrainTrip](https://schema.org/TrainTrip).

Example
```
{
  "@context": "http://schema.org”,
  "@type": "http://schema.org/BoatReservation”,
  "reservationId": "10522083”,
  "reservationStatus": "http://schema.org/ReservationConfirmed”,
  "underName": {
    "@type": "http://schema.org/Person”,
    "name": "John Smith”
  },
  "reservationFor": {
    "@type": "http://schema.org/BoatTrip",
    "boatName": "Lady Annabelle",
    "boatNumber": "D2345",
    "departureBoatTerminal": {
      "@type": "http://schema.org/BoatTerminal",
      "name": "Chase Center Ferry Terminal",
      "telephone": "4082954153",
      "url": "www.departure.com",
      "address": "525 Terry A Francois Blvd, San Francisco, CA 94158"
    },
    "departureTime": "2019-11-10T20:30:00",
    "arrivalBoatTerminal": {
      "@type": "http://schema.org/BoatTerminal",
      "name": "Alameda-Oakland Ferry Terminal",
      "telephone": "2136298401",
      "url": "www.arrival.com",
      "address": "101 The Embarcadero #118, San Francisco, CA 94105"
    },
    "arrivalTime": "2019-11-11T10:32:00",
    "provider": {
      "@type": "http://schema.org/Organization",
      "name": "San Francisco Bay Ferries"
    }
  }
}
```

Thoughts?

**Comment by bquinn** [comment]
Instead of just having ""boatName" and "boatNumber" as part of the reservation, how about making the actual boat a first-order property as well? It could inherit from https://schema.org/Vehicle, some of the properties from Vehicle could be useful such as seatingCapacity, cargoVolume etc.

It could also be worth marking up extra properties of ferries such as the amenities on board: do they have bars, toilets, cabins, shops etc? Can you take your car or pet on board? Do they only operate at certain times of the year?

**Comment by rvguha** [comment]
boatName is incredibly specific and counter to the idiom of not mixing up
types with properties. The two should be orthogonal. Why isn't just name
enough?

**Comment by magico** [comment]
> boatName is incredibly specific and counter to the idiom of not mixing up types with properties. The two should be orthogonal. Why isn't just name enough?
> […](#)

I used `boatName` because we use properties such as `trainName` in https://schema.org/TrainTrip. However, it's a fair point. We can use  `name` instead of `boatName` and `identifier` instead of `boatNumber`

**Comment by rvguha** [comment]
Good catch. We should fix trainName.

**Comment by RichardWallis** [comment]
Referencing the discussion that has diverged into the "schema.org Mailing List" <public-schemaorg@w3.org> without keeping in sync ([latest](https://lists.w3.org/Archives/Public/public-schemaorg/2020Feb/0021.html)) - the proposal probably could do with minor tweaks and then building upon.

BoatTerminal as Felipe Santi points out is a bit specific, as boats, ships, etc. arrive and leave from ports, harbours, docks, jetties, water-bus stops, etc.

However if we are happy with _Boat_ as the superclass for all types of watercraft, then BoatTerminal would be OK as a superclass for Harbour etc.

**Comment by Maxszik** [comment]
I’m curious about cruises, are they meant to be covered here? A boat trip, in my mind, is a day trip, a commuter service, local transport lasting a couple of hours or over the day at most. Very common in some places. A ferry is pretty much the same, though they can be overnight, very rarely longer.

A cruise is a leisure holiday lasting many days. A cruise vessel is not a boat but a ship.

How are you reasoning here, does the cruise thing belong here at all? It’s a massive industry that deserves proper markup.

**Comment by danbri** [comment]
# postscript: name vs boatName

(This doesn't affect the changes committed for version 9.0 release.)

I can't find the discussion now, but on the point of "name" vs "trainName" etc., I believe someone (likely @vholland) pointed out that the /name is the name of the */Trip* not the name of the train, boat etc. In which case, simply using "name" doesn't capture the vehicle's name, only the name of a trip using it.

Most trips will not involve transport by a vehicle with a notably named vehicle, but if we do find a demand for this expressivity, I suggest we add /vehicleName (and potentially a /vehicleIdentifier) to /Trip. 

The "legacy" properties https://schema.org/busName and https://schema.org/trainName could be sub-properties of this. Note also that https://schema.org/Flight has /aircraft and /flightNumber. 

My preference would be not to add more complexity here without motivating application and investigating how transport-related standards deal with such matters.
