### ISSUE TITLE
Consider an EditedPhotograph subtype of ImageObject for manipulated imagery

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1760]
Thinking out loud here but why not have a machine equivalent to this?

http://www.bbc.co.uk/news/world-europe-41443027

> From Sunday, in France, any commercial image that has been digitally altered to make a model look thinner will have a cigarette-packet style warning on it. "Photographie retouchée", it will say, which translates to "edited photograph".

* Add a Type: EditedPhotograph
* Description (rough proposal): "A digital image that appears to be photographic but whose content has been significantly edited. Generic adjustment of colours and levels, brightness, contrast etc. are not considered 'editing' in this sense, whereas changes that make a person appear e.g. thinner, more stereotypically attractive, or that change skin colour, would constitute 'editing' here. "

Maybe language could be stronger

**Comment by rvguha** [comment]
Yes! Lets do it.

guha
