### ISSUE TITLE
When reviewCount is 0, display error "The value provided for reviewCount must be a positive value" 

### ISSUE THREAD

**Issue by yueshi277** [schemaorg/schemaorg#1770]

**Comment by jameswadsworth** [comment]
From [http://schema.org/ratingCount](url)

Values expected to be one of these types
--
Integer

I would expect 0 to be a valid integer value. It is very possible that nobody has rated an item/article

**Comment by yueshi277** [comment]
reviewCount is 0, display error "The value provided for reviewCount must be a positive value"
![screen shot 2017-10-31 at 9 41 58 am](https://user-images.githubusercontent.com/14883455/32226879-1f1802f4-be20-11e7-8939-d934f68a7b53.png)

**Comment by frxncisjoseph** [comment]
Any news?

**Comment by arthurlauck** [comment]
I'm having the same doubt, search google, is throwing me this error. Not sure if i need to hide the prop when is zero or is just a misunderstanding.

**Comment by frxncisjoseph** [comment]
AFAIK, Google doesn't penalize for now...

**Comment by frxncisjoseph** [comment]
@arthurlauck Ideally, you'd hide it on page render rather than dynamically using JavaScript.

**Comment by frxncisjoseph** [comment]
@jameswadsworth It's not implying that the value isn't a valid integer but that it's not a positive one (1 or above).

**Comment by arthurlauck** [comment]
@frxncisjoseph I still think the field review count should accept zero value, I hope one day this is fixed. I didn't hide, just ignored it the error.

**Comment by frxncisjoseph** [comment]
@arthurlauck Agreed, but it doesn't seem like anyone wants to address this yet. We shouldn't have to rely on hiding it through page render statically...

**Comment by chaals** [comment]
0 is an integer. This is an issue for Google's tools, not schema.org...

**Comment by junaidfarooqui** [comment]
I Putted if condition on aggregateRating, if rating is 0 it won't render aggregateRating, it doesn't make any sense to show aggregateRating if it's 0. it validates successfully.

**Comment by muster-mark** [comment]
> 0 is an integer.

-1 is an integer.

**Comment by jodyshop** [comment]
> I Putted if condition on aggregateRating, if rating is 0 it won't render aggregateRating, it doesn't make any sense to show aggregateRating if it's 0. it validates successfully.

That's a genuine solution, indeed, it's not feasible to review unrated items :) so hiding it until the first review is the best solution.

**Comment by devbyVeriTech** [comment]
It’s 2026 and this issue hasn’t been resolved
