### ISSUE TITLE
file:// URLs in core ontology

### ISSUE THREAD

**Issue by gooodguy** [schemaorg/schemaorg#1778]
Hi, 
I found these triples in the file https://github.com/schemaorg/schemaorg/blob/master/data/releases/3.3/schema.nt

`<file:///Users/danbri/sdo/official/schemaorg/data/schema.rdfa> <http://purl.org/dc/terms/source> <http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#IIT-CNR.it> .
<file:///Users/danbri/sdo/official/schemaorg/data/schema.rdfa> <http://purl.org/dc/terms/source> <http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#Tourism> .`

I assume that they have been accidently included and should be removed.

**Comment by danbri** [comment]
Thanks, that is a mistake :(  Will need to ...

* figure out what base URI to use
* fix the 3.3 files in-place 
* make a unit test to ensure we don't do it again

/cc @RichardWallis

**Comment by RichardWallis** [comment]
Fixed in commit 87cb205
