### ISSUE TITLE
Problem with URL that have non-English characters.

### ISSUE THREAD

**Issue by cheonmux** [schemaorg/schemaorg#1782]
Hi,

I am using product schema and URL of the product is written in Japanese. However, Schema does not recognize this URL. 

Please see my product here -> https://goo.gl/GDw5iy . 

Original url is https://ja.seoartgallery.com/shop/花の絵-風水-インテリア-絵画-アートパネル-1-2/ but schema recognize like https://ja.seoartgallery.com/shop/-----1-2/

 As it works properly when using English URL, the problems seems to be about languages.

 Could you tell us what to do?

Thank you.

**Comment by chaals** [comment]
I think you mean "The schema validator(s) I used" - schema itself does not say anything about URLs. I just tested this on [Yandex' Structured Data Validator](https://webmaster.yandex.ru/tools/microtest/), and it seemed to work without problems.

File bugs on the validators you are using, and ask the search engines you are looking at if they have the same i18n bugs in their internal architecture. 

For SEO purposes, you might want to avoid using internationalised URLs until the search engines you look at have fixed those bugs.

**Comment by cheonmux** [comment]
@chaals

Hi, Thanks for answering!

I checked schemas chrome develpoer console(F12) and Google [structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/) and see problem. 

and I tested it in  Yandex' Structured Data Validator you gave it, http://schema.org/url is displayed normally.

I am confused which test result is correct.

**Comment by danbri** [comment]
As @chaals points out, this is not a problem for schema.org - this project only defines the schemas. I will close this issue but we can continue to discuss here.

From looking at the [Google SDTT](https://developers.google.com/structured-data/testing-tool/?url=https://ja.seoartgallery.com/shop/花の絵-風水-インテリア-絵画-アートパネル-1-2/), it seems it encodes non-ascii characters. I can investigate but it would be good if you report the issue in a Google forum e.g. https://productforums.google.com/forum/#!forum/webmasters
