### ISSUE TITLE
Please help. We are trying to contact scholarshipsads.org to amend the information about our institution -Augsburg University. 

### ISSUE THREAD

**Issue by nancyshaeffer** [schemaorg/schemaorg#1790]
There is no contact information for the owners or authors of scholarshipsads.org and they list incorrect information about our institution -Augsburg University.  The web site https://www.scholarshipsads.com/full-presidential-scholarships-augsburg-university-usa-2018/#gs.ypgtV0k  says that we offer a full ride Presidential scholarships for our undergraduate and graduate programs, but we do not.   There is an undergraduate, very competitive President's scholarship, and ten are awarded.  One of the selected ten becomes a full scholarship after a on-site weekend of interviews and it is for first year's or freshmen undergraduates only. Because of the on-site component and other qualifying requirements, it is unlikely that an international student not living in the USA would qualify. We are getting an immense amount of applications that are clogging our application system for our graduate programs. Please take all of this information down as soon as possible.  Can you please help us?

Nancy Shaeffer
Augsburg University
Graduate Admissions
612-330-1520

**Comment by danbri** [comment]
This is the issue tracker for the Schema.org project, we have nothing to do with scholarshipsads.org or Augsberg University.

Good luck with your problem -sorry we cannot help.
