### ISSUE TITLE
missing content on SiteNavigationElement

### ISSUE THREAD

**Issue by irvin** [schemaorg/schemaorg#1793]
Seems that the whole page is pretty empty, broken?

<img width="742" alt="2017-11-13 19 35 41" src="https://user-images.githubusercontent.com/165936/32723867-f18adbb2-c866-11e7-82dd-934b55870d4f.png">

**Comment by RichardWallis** [comment]
Thanks @irvin for spotting this.
Symptomatic of a known occasional caching problem 
This particular instance now fixed.
