### ISSUE TITLE
inherited properties not listed on schema.org

### ISSUE THREAD

**Issue by tisdall** [schemaorg/schemaorg#1794]
I went to http://schema.org/Recipe and I only see the directly defined properties and no information about inherited attributes.  It's missing the properties from "Thing", "CreativeWork", and "HowTo".

**Comment by RichardWallis** [comment]
Thanks @tisdall  for spotting this.
Symptomatic of a known occasional caching problem
This particular instance now fixed.

**Comment by tisdall** [comment]
I saw you mention that on a closed issue, but wasn't sure if it was the same issue...  That's rather annoying for you guys!  Thank you.
