### ISSUE TITLE
Liquor, Alcohol in general, is it not allowed; or just forgotten about?

### ISSUE THREAD

**Issue by zzzspawn** [schemaorg/schemaorg#1798]
Hey(first issue raised ever, so please inform me if I need to formulate better/differently), I was wondering if different alcohols will/can be added; like general categories of wine, whisky, beer, etc?
Doing a school project on a site, and now that we started looking we didn't find any of those, only "Winery", "Distillery", "LiquorStore".. so was wondering if there is a rule against this, or if it is possible to add them? (if you have any guides on how I could help do this, I would of course try to help out).

Again, let me know if I need to format this in a different way/ask somewhere else/anything else wrong.. not quite sure what the etiquette is for these kind of things :)

**Comment by EricAxel** [comment]
Hi Petter,

I doubt it’s either not allowed nor forgotten. Rather, I think it’s merely too specific. 

Schema.org allows for modeling of products and offers of those products, but doesn’t get into the weeds on categories like this. Likewise, you won’t find different kinds of electronic goods (cameras, audio equipment...); grocery store items (bakery items, meats, produce...); you get the idea.

That said, there’s nothing that prohibits describing these categories (wine), varietals (Cabernet), and even specific brands of alcoholic products.

THAT SAID, I do recall hearing several years ago about an external (non-schema.org) vocabulary about wine and another about beer. Does anyone else on this list have knowledge of these?

Cheers,
--Eric

Eric Axel Franzon

**Comment by mfhepp** [comment]
Hi Eric, all:

> 
> THAT SAID, I do recall hearing several years ago about an external (non-schema.org) vocabulary about wine and another about beer. Does anyone else on this list have knowledge of these?

If you want to add more specific information about the type of product, simply use http://www.productontology.org.

See markup examples on the following pages:

http://www.productontology.org/doc/Red_wine
http://www.productontology.org/doc/Malt_whisky
http://www.productontology.org/doc/Alcopop
http://www.productontology.org/doc/Cider
http://www.productontology.org/doc/Vodka

Etc.

You basically use any type of alcoholic beverage for which there is an entry in the English Wikipedia.

This pattern is used on tens of thousands of sites globally.

Best wishes

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by zzzspawn** [comment]
Hey, Thank you guys for explaining so well, and thank you for being so quick to respond! :)

great resource as well! :)

Thanks again!
