### ISSUE TITLE
Sub-types of MedicalOrganization link to the wrong subdomain

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#1801]
At the bottom of:
http://schema.org/MedicalOrganization

We find this:

More specific Types available in extensions

- [DiagnosticLab](http://health-lifesci.3-2e.schemaorgae.appspot.com/DiagnosticLab)
- [MedicalClinic](http://health-lifesci.3-2e.schemaorgae.appspot.com/MedicalClinic)
- [VeterinaryCare](http://health-lifesci.3-2e.schemaorgae.appspot.com/VeterinaryCare)

As per the links above these point to:
http://health-lifesci.3-2e.schemaorgae.appspot.com

Not to, as they should:
http://health-lifesci.schema.org

Here are all the pages I could find (via a crawl) that link to URLs starting with:
http://health-lifesci.3-2e.schemaorgae.appspot.com
Or:
https://health-lifesci.3-2e.schemaorgae.appspot.com

http://attic.schema.org/MedicalOrganization
http://auto.schema.org/MedicalOrganization
http://bib.schema.org/MedicalOrganization
http://health-lifesci.schema.org/availableChannel
http://health-lifesci.schema.org/HowToDirection
http://health-lifesci.schema.org/LodgingBusiness
http://health-lifesci.schema.org/MedicalOrganization
http://health-lifesci.schema.org/MedicalTestPanel
http://health-lifesci.schema.org/MultiPlayer
http://health-lifesci.schema.org/OfflineTemporarily
http://health-lifesci.schema.org/PaymentDeclined
http://health-lifesci.schema.org/ReservationHold
http://health-lifesci.schema.org/ZoneBoardingPolicy
http://pending.schema.org/MedicalOrganization
http://schema.org/MedicalOrganization
https://auto.schema.org/MedicalOrganization
https://bib.schema.org/MedicalOrganization
https://health-lifesci.schema.org/availableChannel
https://health-lifesci.schema.org/LodgingBusiness
https://health-lifesci.schema.org/MedicalOrganization
https://health-lifesci.schema.org/MedicalTestPanel
https://health-lifesci.schema.org/OfflineTemporarily
https://health-lifesci.schema.org/PaymentDeclined
https://health-lifesci.schema.org/ReservationHold
https://health-lifesci.schema.org/ZoneBoardingPolicy
https://iot.schema.org/MedicalOrganization
https://meta.schema.org/MedicalOrganization
https://schema.org/MedicalOrganization

**Comment by jvandriel** [comment]
Not only do these subTypes link to the wrong subdomain but they are cause for confusion as well.

Both in the core and in the health-lifesci extension they're highlighted as subTypes of ```MedicalOrganization``` which gives no hint of the fact that they are subTypes of ```LocalBusiness``` (and more more specifically subTypes of ```MedicalBusiness``` in case of the health-lifesci extension).

Next to that subTypes like schema.org/Dentitst are subTypes of ```LocalBusiness``` in the core (inc. a breadcrumb that reflects this hierarchy), yet on health-lifesci.org they are subTypes of ```MedicalBusiness``` (with a breadcrumb that reflects another hierarchy than that of the core).

Yet if you look at health-lifesci.schema.org the breadcrumb almost becomes scary:
> [Thing](http://schema.org/Thing) > [Organization](http://schema.org/Organization) > [LocalBusiness](http://schema.org/LocalBusiness) > MedicalBusiness > [Dentist](http://schema.org/Dentist) 
> [Thing](http://schema.org/Thing) > [Organization](http://schema.org/Organization) > [LocalBusiness](http://schema.org/LocalBusiness) > [Dentist](http://schema.org/Dentist) 
> [Thing](http://schema.org/Thing) > [Organization](http://schema.org/Organization) > MedicalOrganization > [Dentist](http://schema.org/Dentist) 
> [Thing](http://schema.org/Thing) > [Place](http://schema.org/Place) > [LocalBusiness](http://schema.org/LocalBusiness) > MedicalBusiness > [Dentist](http://schema.org/Dentist) 
> [Thing](http://schema.org/Thing) > [Place](http://schema.org/Place) > [LocalBusiness](http://schema.org/LocalBusiness) > [Dentist](http://schema.org/Dentist)

I therefore like to suggest we help publishers out by harmonizing the situation between the core and health-lifesci extension by adding ```MedicalBusiness``` to the core and change the footnote of ```MedicalOrganization``` from:

> More specific Types
> 
> [Dentist](http://schema.org/Dentist)
> [Hospital](http://schema.org/Hospital)
> [Pharmacy](http://schema.org/Pharmacy)
> [Physician](http://schema.org/Physician)
> 
> More specific Types available in extensions
> [DiagnosticLab](http://health-lifesci.3-2e.schemaorgae.appspot.com/DiagnosticLab), [MedicalClinic](http://health-lifesci.3-2e.schemaorgae.appspot.com/MedicalClinic), [VeterinaryCare](http://health-lifesci.3-2e.schemaorgae.appspot.com/VeterinaryCare)
> 
> More specific Types
> [MedicalBusiness](http://schema.org/MedicalBusiness)
> 
> More specific Types available in extensions
> [DiagnosticLab](http://health-lifesci.schema.org/DiagnosticLab), [MedicalClinic](http://health-lifesci.schema.org/MedicalClinic), [VeterinaryCare](http://health-lifesci.schema.org/VeterinaryCare)
