### ISSUE TITLE
actor property should also accept a PerformanceRole in addition to Person

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1808]
We have a great example on [PerformanceRole](http://schema.org/PerformanceRole) of the actor property accepting a PerformanceRole type.  But currently on many types utilizing the actor property it only shows Person as an expected type, and not additionally the PerformanceRole type.  Let's fix that.

**Comment by RichardWallis** [comment]
What you are seeng in the example is a feature of _Role_ based Types to be accepted by any property; not it becoming an expected type for _actor_.

As described in the blog post http://blog.schema.org/2014/06/introducing-role.html.

**Comment by RichardWallis** [comment]
Closing as answer got thumbs up from issue raiser
