### ISSUE TITLE
Introduction of TouristDestination, TouristTrip and Trip Types

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1810]
Building on the work of enhancing the capabilities of the [TouristAttraction](http://schema.org/TouristAttraction) Type, the [Tourism Structured Web Data Community Group](https://www.w3.org/community/tourismdata/) propose two new Types _TouristDestination_ and _TouristTrip_.  

These proposals reflect the real needs of organisations such as city authorities, tourist boards, travel agents, etc. promoting tourist attractions in particular area  or; organised or recommended trips to visit attractions.

**TouristDestination** A tourist destination. In principle any _Place_ can be a _TouristDestination_ from a _City_, _Region_ or _Country_ to an _AmusementPark_ or _Hotel_. This Type can be used on its own to describe a general _TourstDestination_, or be used as an _additionalType_ to add tourist relevant properties to any other _Place_.  A _TouristDestination_ is defined as a _Place_ that contains, or is colocated with, one or more _TourstAttractions_, often linked by a similar theme or interest to  particular a _touristType_. The [UNWTO](http://www2.unwto.org/) defines Destination (main destination of a tourism trip) as the place visited that is central to the decision to take the trip.
- Subtype of: Place
- Property: [touristType](http://schema.org/touristType)
- Property: **includesAttraction** (new property): Attraction located at destination. [Expected types: _TouristAttraction_, _TouristDestiation_]

**TouristTrip** A tourist trip - a created itinerary of visits to one or more places of interest (_TouristAttraction_/_TouristDestination_) often linked by a similar theme, geographic area, or interest to a particular _touristType_. The [UNWTO](http://www2.unwto.org/) defines tourism trip as the Trip taken by visitors
- Subtype of: CreativeWork
- Property: [touristType](http://schema.org/touristType)
- Property: **itinerary** (new property): Destination(s) that make up a trip. For a trip where destination order is important, use _ItemList_ to specify that order. [Expected types: _Place_, _ItemList_]

See JSON-LD Examples below..

_Justification for a generic **Trip** Type?_   
Already defined are Types for other trip types: [BusTrip](http://schema.org/BusTrip), [TrainTrip](http://schema.org/TrainTrip), and [Flight](http://schema.org/Flight).   There is potential for a Generic **Trip** Type to act as a super-type for these plus _TouristTrip_, being the home for the following properties: _arrivalTime_, _departureTime_, _provider_, and _itinerary_.  This is offered as an alternative suggestion to the standalone _TouristTrip_.

_Examples:_

**TouristDestination** 
```
{
  "@context": "http://schema.org",
  "@type": "TouristDestination",
  "name": "Ribera del Duero Wine Route",
  "description": "Ribera del Duero is on the northern plateau of Spain and covers parts of the provinces of Burgos, Segovia, Soria and Valladolid. The course of the River Duero marks the landscape here, dotting it with gentle hills, valleys and moorland, where vines are mixed with cereal crops.\nThe wines from Ribera del Duero are the gateway to extensive and varied examples of its heritage; a sign of the cultural, historical and artistic wealth of the region.\nThe Ribera del Duero wine route offers visitors charming villages where they can find monuments, castles, towers, cloisters, squares with special columns, cloistered convents, monasteries, churches, museums and palaces. Buildings from the Romanesque, Gothic and medieval periods will fill visitors’ memories with spectacular moments and unforgettable instants.",
  "url": "http://www.rutadelvinoriberadelduero.es/en",
  "touristType": {
    "@type": "Audience",
    "audienceType": [
      "Wine tourism",
      "Cultural tourism"
    ]
  },
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": "41.67022",
    "longitude": "-3.6900"
  },
  "event": {
    "@type": "Event",
    "name": "European Wine Tourism Week",
    "description": "The six Castile and León's wine routes jointly promote their enoturistic wealth.",
    "location": [
      "Arlanza Wine Route",
      "Bierzo Wine Route",
      "Cigales Wine Route",
      "Sierra de Francia Wine Route",
      "Rueda Wine Route",
      "Ribera del Duero Wine Route"
    ],
    "startDate": "2017-11-06",
    "endDate": "2017-11-12",
    "url": "http://www.rutadelvinoriberadelduero.es/es/agenda/semana-europea-del-enoturismo-2017"
  },
  "includesAttraction": [
    {
      "@type": [
        "Winery",
        "TouristAttraction"
      ],
      "name": "Bodegas Protos",
      "sameAs": "http://www.bodegasprotos.com",
      "image": "https://commons.wikimedia.org/wiki/File%3AFoto_Bodega_Rogers2.jpg"
    },
    {
      "@type": [
        "Winery",
        "TouristAttraction"
      ],
      "name": "Bodega Alejandro F. Tinto Pesquera",
      "sameAs": "http://www.grupopesquera.com",
      "image": "https://commons.wikimedia.org/wiki/File%3ARibera_Del_Duero_Pesquera.JPG"
    },
    {
      "@type": [
        "City",
        "TouristAttraction"
      ],
      "name": "Peñafiel",
      "image": "https://commons.wikimedia.org/wiki/File:Castillo_pe%C3%B1afiel_desde_plaza_coso_valladolid.jpg"
    }
  ]
}

```

**TouristTrip**
```
{
  "@context": "http://schema.org",
  "@type": "TouristTrip",
  "name": "Shakespeare's London",
  "description": "Follow in the footsteps of the world-renowned dramatist and discover the city he made his home. Note: for the sake of example only two stages are presented out of 19 in total, see url for details.",
  "touristType": [
    "Urban tourism",
    "Cultural tourism"
  ],
  "subjectOf": {
    "@type": "CreativeWork",
    "name": "All about the trip",
    "url": "https://www.cityoflondon.gov.uk/things-to-do/visit-the-city/walks/Documents/Shakespeare_Walk_AA_accessible.pdf"
  },
  "itinerary": {
    "@type": "ItemList",
    "numberOfItems": 2,
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "item":
        {
          "@type": "TouristAttraction",
          "name": "Shakespeare’s Gatehouse",
          "description": "The Cockpit pub marks the approximate site of Shakespeare’s gatehouse. On 10 March 1613, Shakespeare bought the old priory gatehouse from Henry Walker, ‘citizen and minstrel (musician)’ for £140. It was later bought at an auction in 1843 by the City of London Corporation for £145. The deed of purchase for the property still exists today and is housed at the London Metropolitan Archives; it contains one of only six “authenticated” examples of Shakespeare’s signature. The property is particularly significant because – although Shakespeare owned property in Stratford – it is the only property he is known to have owned in London. Given its convenient proximity to the Blackfriars Playhouse and The Globe, Shakespeare may have intended to make it his home, yet no evidence suggests he lived here in the four years prior to his death in 1616."
        }
      },
      {
        "@type": "ListItem",
        "position": 2,
        "item":
        {
          "@type": "TouristAttraction",
          "name": "Blackfriars Playhouse",
          "description": "Shakespeare’s Blackfriars Playhouse stood in Playhouse Yard and is regarded as one of the most important sites in English theatre history. Richard Burbage formed a syndicate with Shakespeare, Henry Condell and John Heminge, among others, and together they purchased the playhouse in 1608; yet, due to the outbreak of plague, the opening was delayed until the winter of 1609. It is widely believed that The Winter’s Tale and Cymbeline were written with the Blackfriars Playhouse in mind, despite the fact both plays were also performed at The Globe theatre. The final show at Blackfriars Playhouse was performed in 1642, before it was pulled down in 1655."
        }
      }
    ]
  }
}
```

**Comment by thadguidry** [comment]
@RichardWallis just so I am clear... so TouristTrip is basically an alias for "Tour" ?  There's probably colloquialism in my chosen alias and what I am used to from an American perspective.  "I took a bunch of tours while I was in China" versus "I took a bunch of tourist trips while I was in China"

**Comment by vholland** [comment]
+1 to a generic **Trip** type and making the existing trip-related types subtypes.

Why make **TouristTrip** a subtype of **CreativeWork**? Are there semantics of **CreativeWork** you are trying to leverage? The other trip types are under **Intangible**. It would be good to have some consistency.

**Comment by RichardWallis** [comment]
@thadguidry yes Tour is another name for trip.  For reference the UN World Tourism Organization consider both Tourist Destination and Tourist Trip as 1st class citizens in their vocabulary.

@vholland **TouristTrip** is defined as a subtype of **CreativeWork** to leverage properties such as **offers**, to model entities offering a trip; **hasPart** to model trips containing trips (day1, day2, etc); tourist magazine contents; copyright info; **creator** information (eg. [Thomas Cook](https://en.wikipedia.org/wiki/Thomas_Cook
) created early trips/tours that are still of interest); etc.

In the case of introducing a generic **Trip** Type **TouristTrip** would share both **Trip** and **CreativeWork** as its super-types.

**Comment by rvguha** [comment]
No, we really can't make TouristTrip a subclass of CreativeWork ... that
would be way way too much of a hack.

Lets add more domain/ranges to the relevant properties.

**Comment by vholland** [comment]
+1 to adding the relevant properties to Trip rather than adding it as a subclass of CreativeWork.

**Comment by RichardWallis** [comment]
Following comments we have adjusted our proposal for **TouristTrip** as follows:
(_Note: Links in this description are to a development version of schema.org located at [sdo-tourism.appspot.com](sdo-tourism.appspot.com) to help visualise our proposal and to check out the examples included there._)
* As per our suggestion we have created a new type [**Trip**](http://sdo-tourism.appspot.com/Trip) (subtype of **Intangible**) "_A trip or journey. An itinerary of visits to one or more places._" as the new super-type for [**BusTrip**](http://sdo-tourism.appspot.com/BusTrip), [**Flight**](http://sdo-tourism.appspot.com/Flight), and [**TrainTrip**](http://sdo-tourism.appspot.com/TrainTrip).  
  * The following common properties of these types are transferred to the domain of **Trip**:
    * **arrivalTime**, **departureTime**, **provider**.
  * The following properties have their domain extended to include **Trip**:
    * **hasPart**, **isPartOf** -- to enable the modelling trips made up of a set of sub-trips (eg, _Bus Trip Across Europe_, _Day1_, _Day2_, etc.) 
    * **offers** -- To enable an **Offer** to provide a **Trip** to be modelled. (eg. by Bus/train company, airline, travel agent, etc.)
  * Create new property [**itinerary**](http://pending.sdo-tourism.appspot.com/itinerary) "_Destination(s) ( [Place](http://sdo-tourism.appspot.com/Place) ) that make up a trip._"  -- domain of **Trip**.

* **TouristTrip** A tourist trip - a created itinerary of visits to one or more places of interest (_TouristAttraction_/_TouristDestination_) often linked by a similar theme, geographic area, or interest to a particular _touristType_. The [UNWTO](http://www2.unwto.org/) defines tourism trip as the Trip taken by visitors.
  * Subtype of: [**Trip**](http://pending.sdo-tourism.appspot.com/Trip)
  * Property: [**touristType**](http://pending.sdo-tourism.appspot.com/touristType)

_Implementation Notes:_   We are preparing a PR to implement this proposal, with the following suggestions (as can be seen in the [sdo-tourism.appspot.com](sdo-tourism.appspot.com) version):
* Creation of new [**Trip**](http://pending.sdo-tourism.appspot.com/Trip) type and move of common properties into it - applied directly to core.
* Extending of domain for **hasPart**, **isPartOf**, and **offers** - applied directly to core.
* Creation of new Types [**TouristTrip**](http://pending.sdo-tourism.appspot.com/TouristTrip), [**TouristDestination**](http://pending.sdo-tourism.appspot.com/TouristDestination) - applied to pending.
* Creation of new properties [**itinerary**](http://pending.sdo-tourism.appspot.com/itinerary), [**includesAttraction**](http://pending.sdo-tourism.appspot.com/includesAttraction) - applied to pending

**Comment by thadguidry** [comment]
@RichardWallis This looks much better!

I feel however that we could also later on put some work in later to help with visualization efforts as well for the Tourism domain.  Our current Map is rather plain jane.  It would be neat to also somehow layer Trip with our Map.  Sites are currently doing this all the time and all of us rely on seeing our Trips and Itineraries on Maps (we'd be lost sometimes without them!)  One nice facet of somehow having Trip with Map is that you could train some search algorithms to also look at alternative Trips others have taken or different paths to a TouristAttraction that others reached.  " I visited Florence, Italy via a route from Milan to Genoa for a day of seaside shopping rather than through Bologna.  But others seemed to prefer going through Bologna to visit the Fountain of Neptune and get a glimpse of Little Venice"

**Comment by RichardWallis** [comment]
@thadguidry I agree about future potential . - let's get this in first ;-)

As **TouristAttraction** & **TouristDestination** are subtypes of **Place** there is already some potential for interesting integration with maps. Equally with **itinerary** on **Trip**, especially with an ordered **ItemList** of destination Places, could already supply the underlying data to drive a use case such as you describe.

**Comment by vholland** [comment]
+1. I think this is a good start and we can add to the schema as use cases present themselves.

**Comment by danbri** [comment]
Ok, sounds like some reasonable consensus here...

**Comment by globaldit** [comment]
Globaldit is a firm with 26 years of experience in the tourism sector, and we are members of the United Nations World Tourism Organization (UNWTO). We work in Spain and Latin America, and have a history of 2,000 projects for 200 destinations in 9 countries. 

From our experience we reckon the proposals for TouristTrip and TouristDestination are quite comprehensive and well suited to the reality they seek to represent.

**Comment by O-Mkt-Love** [comment]
Hi all, 
I'm currently working on the relaunch of a travel agency website and stumbled across the 2 new propsed Schemas (TouristTrip and TouristDestination), which I find fantastic. 
Can you provide me with an update on the current status of them? I cannot seem to use them yet (Google currently still tells me that it doesn't know about such Microdata/Schema type). 
I appreciate your time, thank you.
Kind regards

**Comment by vivipoit** [comment]
Coming from the travel agency and tour operator way of thinking, I'd like to know if it's possible to add information such as `price` and `duration` to `TouristTrip`. Or even better would be to somehow create the link or relation between `TouristTrip` and `Product`.

When I build an agency's website, I often end up doing these separate, as if each page had a `Product` and a `TouristTrip`, but the reality is that the `TouristTrip` **_IS_** the `Product` itself.

**Comment by RichardWallis** [comment]
What you are looking for is provided via the ```offers``` property of ```TouristTrip```.  This allows the assignment of an ```Offer``` Type which includes price information and links to the offering organization.  This is the same pattern as used elsewhere to provide offers for Products and Services.

Check out the [3rd example](https://pending.schema.org/TouristTrip#tourism-13) on the ```TouristTrip``` page, which demonstrates this.

**Comment by justmaj** [comment]
Is it possible fora trip to have arrivalTime and departureTime that doesn't require the date to be specified? For a service provider, trips are often the same every day - e.g. a tour operator will offer day tours to Destination X every day so having an departure date & arrival date doesn't really make much sense in this case. 

This is similar to the issue I have with the BusTrips schema.. If you run bus services that depart at the same times every day, it doesn't seem possible to add times unless you add every dates also, e.g. create a Bustrip for 17/02/2019 08:00, 17/02/2019 09:00, [...] and the same again for 18/02/2019, 19/02/2019 etc.

(Sorry if this isn't the place to ask, I'm a newbie to this forum but can't find useful information on the lesser uses schemas)

**Comment by thadguidry** [comment]
@justmaj It's possible now... we already support in pending... https://pending.schema.org/Schedule

**Comment by justmaj** [comment]
@thadguidry thanks for the quick reply & the info. So just to confirm - can I use the Schedule schema with Trip schema (or any of its specific types) now, or is this something that will be added in future?

**Comment by thadguidry** [comment]
@justmaj yes now I would say.  Schedule has had quite a bit of discussion and refinement already.  It will move into core soon-ish in my opinion.  Pending and How we work is mentioned here: https://schema.org/docs/howwework.html

**Comment by nickornotto** [comment]
It's great to have TouristTrip as a schema option however I do not quite understand why it doesn't have a review and aggregateRating property? Tours often come with customer reviews the same as products do so I am not very much inclined to use it instead of Product schema right now just because of this.

**Comment by RichardWallis** [comment]
Closing as implemented.
Suggestion in comments moved to https://github.com/schemaorg/suggestions-questions-brainstorming/issues/162

**Comment by huy113ym** [comment]
It doesn't work on: https://search.google.com/test/rich-results/
![image](https://github.com/user-attachments/assets/718efaa6-2737-4539-b618-1231e4dc9128)
