### ISSUE TITLE
Theatre Play

### ISSUE THREAD

**Issue by gregmatys** [schemaorg/schemaorg#1816]
There is no _**Theater Play**_ in _CreativeWork_ section.
I found _Theater Event_ but it's only a singular event, not a whole "piece of art".

**Comment by RichardWallis** [comment]
I am a little unclear by what you mean by _a whole "piece of art"_.

I _think_ you are describing a theatrical event that consists of either a Play consisting of more than one part (such as [Harry Potter and the Cursed Child Parts One & Two](https://www.harrypottertheplay.com/) ) or; a series/season of plays  that are connected in some way such as by an author, theme (such as [The Oscar Wilde season](http://www.whatsonstage.com/london-theatre/news/oscar-wilde-season-dominic-dromgoole-woman-no-importance_44056.html) ).

If that is the case, you can already model that using the [subEvent](http://pending.schema.org/subEvent) & [superEvent](http://pending.schema.org/superEvent) properties. You would create a [TheaterEvent](http://schema.org/TheaterEvent) for the collective description of the  Play [for a series you would also define it as being an [EventSeries](http://pending.schema.org/EventSeries)] eg "_Harry Potter and the Cursed Child_".  

You would create a TheaterEvent for each part ("_Harry Potter and the Cursed Child Part One"_, "_Harry Potter and the Cursed Child Part Two_" ). 

Then you can use the _subEvent_ & _superEvent_ properties to declare the relationship between them.

**Comment by gregmatys** [comment]
I mean I have website of theater. There is a list of plays.
Each theater play has an author, its story, cast, etc…
A play is not an "event". It's considered as piece of art in my opinion, like a book.

On this website each play has it's calendar, where I certainly can use _TheaterEvent_ which has its particular date. Am I wrong?

**Comment by RichardWallis** [comment]
OK I understand now...

So following the current patterns within Schema.org...

The Website would be effectively the definition of the **Organization** (Theatre Company) that would be putting on various **TheaterEvent**s (performances) each event would have properties for _startDate_, _location_, etc., plus the [workPerformed](http://schema.org/workPerformed) would be the **CreativeWork** (Play) created by the playwright (author).

This all makes sense until you look for the expected subtype of **CreativeWork** - **Play**,  as there is not one.  Checking back, there is an outstanding pull request ([#1449](https://github.com/schemaorg/schemaorg/pull/1449)) that seeks to add 4 new subtypes to CreativeWork (Manuscript, Poster, Drawing, SheetMusic).  Based on this thread, I am considering extending that PR to include **Play**.

**Comment by peteleco** [comment]
I'm at the same place of @gregmatys, at my website we sell play tickets, we are using the **Event Schema** to set all events of this play, but even when a play does not have a event, i need a schema only for the play, i saw **CreativeWork** as a solution, with this i can use **AggregateRating** at **CreativeWork** and **Event** with this i can display the rating of the play and event.
This is make sense?

**Comment by gregmatys** [comment]
@RichardWallis yes, that's similar to #1449, so please include **_Play_** in _Creative Work_.

**Comment by RichardWallis** [comment]
I have added 'Play' to PR (#1449)

**Comment by RichardWallis** [comment]
Implemented in [release 3.5 ](https://schema.org/docs/releases.html#v3.5)

**Comment by WeaverStever** [comment]
The Play type is missing its own set of properties. I would think that these properties should be similar to the ones found in https://schema.org/Movie.

In the "**Used on these types**"  guidance I note the absence of Play as a type for https://schema.org/director  and https://schema.org/actor  Similarly, actor, director and itemReviewed are not recognized properties for Play. (SDTT)

There is also a typo in the guidance for https://schema.org/Play
"Note the peformance of a Play would be a TheaterEvent - the Play being the workPerformed."

Should be...
"**A performance** of a Play would be a TheaterEvent - the Play being the workPerformed."

(Using the word "Play" we have to be careful of the context, Play could mean the creativework, an event, or a performance / collection of performances)
