### ISSUE TITLE
proposal: type for describing Tasks

### ISSUE THREAD

**Issue by chharvey** [schemaorg/schemaorg#1818]
I would like to see a type on Schema.org for describing a Task (, Issue, or WorkOrder). This could be used to mark up a GitHub issue, Asana task, or an item on a to-do list for example. Below, in JSON-LD format, are my ideas for property names and values.

```json
{
  "@context": "http://schema.org/",
  "@id": "http://schema.org/Task",
  "@type": "Class",
  "subClassOf": "http://schema.org/Intangible",
  "name": "Task",
  "description": "A task that can be assigned and completed.",
  "property": [
    {
      "@type": "Property",
      "@id": "http://schema.org/assignee",
      "name": "assignee",
      "description": "A person or organization to whom this task is assigned.",
      "rangeIncludes": [
        { "@id": "http://schema.org/Person" },
        { "@id": "http://schema.org/Organization" }
      ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/attachment",
      "name": "attachment",
      "description": "A relevant work attached to this task.",
      "rangeIncludes": [ { "@id": "http://schema.org/CreativeWork" } ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/category"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/comment"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/commentCount"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/completedBy",
      "name": "completedBy",
      "description": "The entity who completed this task.",
      "subPropertyOf": { "@id": "http://schema.org/contributor" },
      "rangeIncludes": [
        { "@id": "http://schema.org/Person" },
        { "@id": "http://schema.org/Organization" }
      ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/contributor"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/creator"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/dateCompleted",
      "name": "dateCompleted",
      "description": "The date/time on which this task was completed.",
      "rangeIncludes": [ { "@id": "http://schema.org/DateTime" } ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/dateCreated"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/dateDue",
      "name": "dateDue",
      "description": "The date/time on which this task is due.",
      "rangeIncludes": [ { "@id": "http://schema.org/DateTime" } ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/dateModified"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/dependency",
      "name": "dependency",
      "description": "A task that must be comleted before this task is completed.",
      "inverseOf": { "@id": "http://schema.org/dependent" },
      "rangeIncludes": [ { "@id": "http://schema.org/Task" } ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/dependent",
      "name": "dependent",
      "description": "A task that relies on the completion of this task.",
      "inverseOf": { "@id": "http://schema.org/dependency" },
      "rangeIncludes": [ { "@id": "http://schema.org/Task" } ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/downvoteCount"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/event"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/keywords"
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/subscriber",
      "name": "subscriber",
      "description": "Anyone who wishes to receive updates on this task.",
      "rangeIncludes": [
        { "@id": "http://schema.org/Person" },
        { "@id": "http://schema.org/Organization" }
      ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/subtask",
      "name": "subtask",
      "description": "A task that is a part of this task.",
      "inverseOf": { "@id": "http://schema.org/supertask" },
      "rangeIncludes": [ { "@id": "http://schema.org/Task" } ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/supertask",
      "name": "supertask",
      "description": "A task that this task is a part of.",
      "inverseOf": { "@id": "http://schema.org/subtask" },
      "rangeIncludes": [ { "@id": "http://schema.org/Task" } ]
    },
    {
      "@type": "Property",
      "@id": "http://schema.org/upvoteCount"
    }
  ]
}
```

Here’s example markup of issue #987 :

```json
{
  "@context": "http://schema.org/",
  "@type": "Task",
  "@id": "https://github.com/schemaorg/schemaorg/issues/987",
  "identifier": "987",
  "name": "provide a status property for CreativeWork",
  "description": "... I propose adding a similar property to CreativeWork, perhaps named creativeWorkStatus...",
  "assignee": [],
  "comment": [
    {
      "@type": "Comment",
      "text": "danbri added the schema.org vocab label on Mar 7, 2016"
    }
  ],
  "commentCount": 0,
  "creator": { "@type": "Person", "@id": "https://github.com/chharvey" },
  "dateCreated": "2016-02-15",
  "dateModified": "2017-01-14",
  "keywords": [ "schema.org vocab" ],
  "subscriber": [
    { "@type": "Person", "@id": "https://github.com/chharvey" },
    { "@type": "Person", "@id": "https://github.com/danbri" }
  ]
}
```

**Comment by rvguha** [comment]
This is a great idea. We should do it.

guha

**Comment by chharvey** [comment]
Coming back to this, `Task` seems to be more appropriate as a subclass of `CreativeWork`, instead of `Intangible`. Then I could then remove the following properties from the pseudo-JSON-LD definition above.

- comment
- commentCount
- contributor
- creator
- dateCreated
- dateModified
- keywords

**Comment by chharvey** [comment]
I created a mockup of the **Task** class, for those who would like a visual representation.

![schema org_task](https://user-images.githubusercontent.com/1362083/41115817-9f420942-6a56-11e8-8cd1-9793c46cec98.png)

**Comment by jlunman** [comment]
I recently went looking for this very type, and was surprised not to find it already on schema.org. In its absence, I think https://schema.org/Action seems like the closest fit.

The [agent](https://schema.org/agent) property lines up with the proposed `assignee`.

It has [startTime](https://schema.org/startTime) and [endTime](https://schema.org/endTime), the latter of which can be used for `dateCompleted`.

The [actionStatus](https://schema.org/actionStatus) property of type [ActionStatusType](https://schema.org/ActionStatusType) can be used to indicate "not started" (`PotentialActionStatus`), "in-progress" (`ActiveActionStatus`), "complete" (`CompletedActionStatus`), "reopened" (`FailedActionStatus`) states.

It does lack a few important properties, though. such as `dateDue`.  I also like the `dependency/dependent` and `subtask/supertask` relationships.

**Comment by philbarker** [comment]
The concept of 'task' is also important in defining job roles and competencies, where we need to know what is involved in a job/role and what someone filling that position needs to be able to do. For example the National Initiative for Cybersecurity Education (NICE) [Cybersecurity Workforce Framework](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-181.pdf) defines task as 
> "...[a] specific defined piece of work that, combined with other identified Tasks, 
> composes the work in a specific specialty area or work role."

example tasks in that framework include
> Acquire necessary resources, including financial resources, to conduct an effective
> enterprise continuity of operations program.

> Advise senior management (e.g., Chief Information Officer [CIO]) on risk levels and
> security posture.

(and 1005 others!)

It would be best if any wider concept of Task in schema.org were framed to include this conceptual task.

As such, a task is not a CreativeWork--the description of a task is different from the task--I would bump it back to being an Intangible or put it directly under Thing, and extend the domain of any existing properties it needs.

The NICE definition also has the advantage of not relying on the word task to define the term task.

**Comment by jlunman** [comment]
Interesting. The https://schema.org/JobPosting type has a `responsibilities` property but it's just a `Text` field, not more strongly typed.

**Comment by akuckartz** [comment]
@danbri I doubt that it really helps to automatically close issues just one week after marking them stale when many people potentially are on vacation.

**Comment by aitorllj93** [comment]
anything new about it?

**Comment by chrisspradling1980** [comment]
Until closure is accounted for numerous sensitive subjects around the world
which most are news or viral style releases, there will be none of this
except one.
I've never tagged schema to link my name with meta sourcing because I like
not having any meta except referenced by publicist however, the final
response:

Tasks: Mark down HTML5 into a compatible HTML4 versioning imperative.

#/The Who What Why When and Where/terminology_discrepancy_finder

I hope soon automation services with NLP or OWL will enable law makers
(consortium) a plea for a prayer upon submission from logcat Apache,
ardrino, Academia.edu , Google and eclipse can't interpret outliers to
confirm finalizing decent into closure. Mind control was filmed as a
confession of hope from a beautiful ladies volunteerism for a driven
passion inside an office/living area etc.
 I think about how many Americans should enjoy the luxury of Fame as much
to the President running into a house that he knows God fixed to own that
He's –or he's the owner while votes push planked finger tip voters  to move
him in and call him my boss? Such a clicked cliques— JFK IS NOT INVOLVED
DIRECTLY BUTT, we give away all the salary as charitable lottery, Uncle Sam
has been turned into Our Aunt Sammie something but a tranny tturruttee as a
woman turtle. It costs but, it's coming.

Chris

**Comment by danbri** [comment]
I have no idea what @chrisspradling1980 is on about. I asked ChatGPT and got this:

> This statement is difficult to understand and appears to be a mix of various topics and ideas. It seems to be discussing the need for closure on sensitive subjects, the use of HTML5 and HTML4 versions, and the potential use of automation services and NLP or OWL for law makers. It also mentions mind control and a confession of hope from a volunteer. Overall, the meaning is not clear.

As for Tasks, great in theory but we really ought to have some party building stuff that will use (and validate the design of) such proposed vocabulary. There are many ways it could be approached, and without a real usecase we won't know how we're doing.

**Comment by chharvey** [comment]
@danbri, in my opinion @chrisspradling1980’s text sounds like it was generated by some kind of AI, probably with the intent to spam. I would ask a moderator to flag/delete their comment above.

**Comment by chrisspradling1980** [comment]
I'm such an idiot. I fail to remind myself of the code of conduct and syntax of the GitHub standards. If it wasn't for @danbri  just now, I wouldn't know what ChatGPT is. 

I was responding to @aitorllj93 and totally forgot the "at" symbol to link.
@chharvey  no sir. It was me and I was rambling. I was definitely delirious.

In response to the proposal: type for describing tasks could break down for large tasks that have many steps to finalize in order to be complete such as, filing for a patent or preparations leading to a consortium event. All these tasks would be considered useful under a proposal circumstance.

**Comment by NoelDeMartin** [comment]
Hey @danbri, if you want a real use-case [I am building a Task Manager with Solid](https://github.com/NoelDeMartin/solid-focus/issues/10#issuecomment-1900631586), and I'm using `schema:Action` for now. But it lacks some things, as discussed in this thread. Also, a TODO list is something very common that people try to build as a first foray into new technology, kind of like [TodoMVC](https://todomvc.com/). So I think it would be nice to have a common Task class for any stack using RDF.
