### ISSUE TITLE
merging wikipidia , images , profiles links on Google Knowledge graph 

### ISSUE THREAD

**Issue by giomorassutti** [schemaorg/schemaorg#1819]
![mv5bmdk5ymfhn2itmjrlny00otm1lwjhmzytotc0ztzknjc2othkxkeyxkfqcgdeqxvyodm0mju0nzq _v1_uy317_cr21 0 214 317_al_](https://user-images.githubusercontent.com/35438397/34923801-66202cd4-f99f-11e7-8a92-55fe17c28178.jpg)

![12524416_10153534315196551_7941263030093909495_n](https://user-images.githubusercontent.com/35438397/34923829-9006d282-f99f-11e7-8af3-2bf23036d15c.jpg)

https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/G_M_.jpg/220px-G_M_.jpg

Hello, 
I´m trying to empower my knowledge graph: https://g.co/kgs/vLydvs
Do you know how to add images, merge Wikipedia info and create profile links ?
http://www.imdb.com/name/nm3466205/?ref_=nmmi_mi_nm
https://it.wikipedia.org/wiki/Giovanni_Morassutti
Thanks a lot!
Giovanni

**Comment by danbri** [comment]
This is not a Google product support forum, sorry we can't help you here.
