### ISSUE TITLE
Serve `.rdfa` files as `text/html`

### ISSUE THREAD

**Issue by BigBlueHat** [schemaorg/schemaorg#1822]
Currently, http://schema.org/version/3.3/schema.rdfa (and it's kin) are all served as `Content-Type: application/octet-stream` because there's no mapping in the App Engine server to serve them as `Content-Type: text/html`

I'm not familiar enough with App Engine's `app.yaml` to suggest a change there, and didn't find any clear (enough) example in https://cloud.google.com/appengine/docs/standard/python/config/appref to encourage a PR (sadly). However, it is hopefully just a small change to that file to set the `mime_type` for URLs ending in `.rdfa`

Cheers!
🎩

**Comment by RichardWallis** [comment]
Similar issue for .nq and .nt files

**Comment by RichardWallis** [comment]
Fixed awaiting release

**Comment by RichardWallis** [comment]
Released in V3.4
