### ISSUE TITLE
BUG: Grammar error on Corporation -> tickersymbol

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#1824]
The description for ticker symbol on http://schema.org/Corporation has spelling error I think?
> we reccommend using the controlled vocaulary of Market Identifier Codes (MIC) specified in ISO15022.
**recommend** & **vocabulary**

**Comment by RichardWallis** [comment]
Fixed awaiting release

**Comment by RichardWallis** [comment]
Released in V3.4
