### ISSUE TITLE
LibrarySystem vs Library

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#1825]
You have a pending type of https://pending.schema.org/LibrarySystem and http://schema.org/Library Will `Library` be removed when the `LibrarySystem` is finalized? Or, would a Government who has several libraries envelope them all into `LibrarySystem` ?

**Comment by RichardWallis** [comment]
No. 
If you check out the thread referenced at the end of the description you will see that an individual Library can be part of one or more LibrarySystems.
