### ISSUE TITLE
MedicalBusiness specific types problem

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#1827]
http://health-lifesci.schema.org/MedicalBusiness lists http://health-lifesci.schema.org/Nursing as a more specific type. But, Nursing is not linked as a local business or location type.

**Comment by JeffreyBurns** [comment]
Other classes listed as a more specific type of MedicalBusiness but are not child types of LocalBusiness are:

http://health-lifesci.schema.org/CommunityHealth
http://health-lifesci.schema.org/Dermatology
http://health-lifesci.schema.org/DietNutrition
http://health-lifesci.schema.org/Emergency
http://health-lifesci.schema.org/Geriatric
http://health-lifesci.schema.org/Gynecologic
http://health-lifesci.schema.org/Midwifery
http://health-lifesci.schema.org/Nursing
http://health-lifesci.schema.org/Obstetric
http://health-lifesci.schema.org/Oncologic
http://health-lifesci.schema.org/Optometric
http://health-lifesci.schema.org/Otolaryngologic
http://health-lifesci.schema.org/Pediatric
http://health-lifesci.schema.org/Physiotherapy
http://health-lifesci.schema.org/PlasticSurgery
http://health-lifesci.schema.org/Podiatric
http://health-lifesci.schema.org/PrimaryCare
http://health-lifesci.schema.org/Psychiatric
http://health-lifesci.schema.org/PublicHealth

**Comment by RichardWallis** [comment]
@JeffreyBurns I think you may have identified an error in the definition code somewhere.

For example if you look at [MedicalBusiness](http://health-lifesci.schema.org/MedicalBusiness) you will see [Nursing](http://health-lifesci.schema.org/Nursing) listed as a sub type, but when you look at the [Nursing](http://health-lifesci.schema.org/Nursing) page it only says it is a subtype of [MedicalSpecialty](http://health-lifesci.schema.org/MedicalSpecialty).

This probably needs some investigation.
cc @danbri

**Comment by twamarc** [comment]
Let's investigate further:
Most of listed here are not children of MedicalBusiness but MedicalSpeciality (Enumeration)
´´´Thing > Intangible > Enumeration > Specialty > MedicalSpecialty :: CommunityHealth´´´ 
´´´Thing > Intangible > Enumeration > MedicalEnumeration > MedicalSpecialty :: CommunityHealth´´´
Regarding making all of them children of LocalBusness, let's think wide on this as it will create redundant info. e.g we have some legacy here: 
´´´Thing > Organization > LocalBusiness > MedicalBusiness > Dentist´´´
    and
´´´Thing > Organization > LocalBusiness > Dentist´´´ 
As such is not an issue but we have to to agree on such choice.
