### ISSUE TITLE
typo: misspelt "precede"

### ISSUE THREAD

**Issue by chharvey** [schemaorg/schemaorg#1830]
https://github.com/schemaorg/schemaorg/blob/9e09f4150ca7667c9ab40d82b71c8b0c503c5055/data/schema.rdfa#L5145

Line 5145 should read: (emphasis mine)
> … Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a *preceding* zero. …

https://github.com/schemaorg/schemaorg/blob/9e09f4150ca7667c9ab40d82b71c8b0c503c5055/data/schema.rdfa#L8856

Line 8856 should read: (emphasis mine)
> … A link to the ListItem that *precedes* the current one. …

**Comment by chharvey** [comment]
I apologize in advance if submitting issues like this is too nitpicky. Just let me know :)

**Comment by danbri** [comment]
Thanks! Totally not too nitpicky, but we also have an issue here somewhere with new text from GS1 about gtins. I'm on my phone now and didn't find it but wanted to note this so we make sure not to reintroduce the typo.

/@philarcher

**Comment by philarcher** [comment]
Indeed, not too nit picky at all. Pedants welcome (or I'm in big trouble).

**Comment by ekgs1** [comment]
@danbri

Hi Dan, I had suggested a definition in the tread on GTINs.  Here is what GS1 is suggesting:

 "The Global Trade Item Number (GTIN) is used by companies to uniquely identify all of its trade items. Trade items are products or services that are priced, ordered or invoiced at any point in the supply chain.  The GTIN can be used to identify types of products at any packaging level (e.g., consumer unit, inner pack, case, pallet).  There are four GTIN formats (GTIN-8, GTIN-12, GTIN-13 and GTIN-14).  For applications that require a uniform 14-digit format, leading zeroes need to be added as filler digits:

000000nnnnnnnn (GTIN-8)
00nnnnnnnnnnnn (GTIN-12)
0nnnnnnnnnnnnn (GTIN-13)

See https://www.gs1.org/gtin  for more details. "

I may be missing something from above but is there an issue with this text?

**Comment by danbri** [comment]
Thanks @ekgs1 - it looks like you've used the phrase "leading zeroes", whereas previously we used "preceding", spelled wrongly as "preceeding".

https://github.com/schemaorg/schemaorg/issues/1244#issuecomment-356984166

Let's leave this issue open until we're sure all the preceedings are gone :)

**Comment by chharvey** [comment]
Thanks @danbri , and after all the "preceed"s are gone, you may proceed by closing this issue and its proceedings, from which no proceeds shall be gained.

**Comment by RichardWallis** [comment]
@danbri have all the "preceed"s been excised?

**Comment by danbri** [comment]
no idea! care to grep?:)

**Comment by RichardWallis** [comment]
Closing - 'preceding' spelling fixed in commit e4e6d68
