### ISSUE TITLE
wording of acceptedAnswer - some sites allow multiple acceptedAnswers

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1832]
eg https://ask.metafilter.com/318090/Can-I-file-taxes-before-I-get-this-form

**Comment by danbri** [comment]
Currently:

> The answer that has been accepted as best, typically on a Question/Answer site. Sites vary in their selection mechanisms, e.g. drawing on community opinion and/or the view of the Question author.

Suggested: "answer(s)"

**Comment by inetbiz** [comment]
@danbri how will this affect Google SERP rich snippet? StackExchange only accepts one answer. About the only domain I have seen rich snippet results.

**Comment by danbri** [comment]
@inetbiz - as always the relationship with anyone's product features is indirect. The initial concern is that the definition is good.
