### ISSUE TITLE
Add expected type ItemList in some common cases

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1833]
There are a few places where we ought to explicitly say "this property can have itemlist values".

 * acceptedAnswer (some sites [support several](https://github.com/schemaorg/schemaorg/issues/1832))
 * suggestedAnswer
 * ~~step (on HowTo)? not needed since HowTo is a subclassof ItemList and ListItem~~ ... 
 * http://webschemas.org/HowToSection should be a ListItem as well as an ItemList.
 * ~~http://schema.org/mainEntity ? not needed since it expects Thing~~

**Comment by kaylareedhanson** [comment]
Your change includes all the changes mentioned here, I think this can be closed?

**Comment by RichardWallis** [comment]
Released in V3.4
