### ISSUE TITLE
merging wikipedia page with Google Knowledge Graph 

### ISSUE THREAD

**Issue by giomorassutti** [schemaorg/schemaorg#1835]
Hello, 

I´m trying to merge my Wikipedia page (https://it.wikipedia.org/wiki/Giovanni_Morassutti) with the Google knowledge graph (https://g.co/kgs/7ZgngU).
Do I need to create structured data in order to do that ? 
Thanks 
Giovanni

**Comment by danbri** [comment]
Please ask at Google! Not something we can help with here.
