### ISSUE TITLE
schema url 

### ISSUE THREAD

**Issue by bianqui149** [schemaorg/schemaorg#1840]
hi!, i am getting this error "All values provided for url must point to the same page." when a place the url in the Structured Data Testing Tools from google, but if a place code snippet a get 0 errors
this is my snippet 
{
    "@context":"http://schema.org",
    "@type":"ItemList",
    "itemListElement":[

        {
            "@type":"ListItem",
            "position":1,
            "item":{
                "@type":"MusicEvent",
                "url":"http://schema-upd-pcms-concerts.pantheonsite.io/concerts#39427",
                "name":" 3 Concert Card - Valid for 2017-18 Season ",
                "image":"https://s3.amazonaws.com/pcms-concerts/wp-content/uploads/2013/07/concert-card1.jpg",
                "startDate":"May 16, 2018 At ",
                "location":{
                    "@type":"MusicVenue",
                    "name":"Perelman Theater",
                    "address":"1528 Walnut Street, Suite 301 Philadelphia, PA 19102"
                },
                "organizer":{
                    "@type":"Organization",
                    "name":"Kimmel Center"
                },
                "offers":{
                    "@type":"Offer",
                    "price":"85.00",
                    "priceCurrency":"USD",
                    "availability":"http://schema.org/InStock",
                    "availabilityStarts":"July 31, 2013"
                }
            }
        }
    ]
}

![schema](https://user-images.githubusercontent.com/22307049/35817841-3866c0ac-0a7d-11e8-9ea1-55a45034a431.png)

**Comment by RichardWallis** [comment]
Closing as is an issue for Google's SDTT forums.
