### ISSUE TITLE
how to add a schema?

### ISSUE THREAD

**Issue by rlzijdeman** [schemaorg/schemaorg#1847]
Hi, really sorry, for missing this: but where do I find info on how to propose a schema? I have transposed HISCO the ISCO'68/88/08 for historical occupations into a schema and would like provide it here. Best, Richard

**Comment by danbri** [comment]
In general we encourage proposals via issue-based discussion here. In the specific case of historical occupation codes, I don't believe we'd want to get schema.org into the business of actually representing that historical content, but it sounds sensible that historical occupation codes should be usable within schema.org markup (e.g. the occupationalCategory property on JobPosting). I see you've also joined in with the discussion nearby in #1698, and there are [others](https://github.com/schemaorg/schemaorg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+occupationalCategory) on related topics. I suggest we try to focus discussion on those issues, so I will close this issue for now.

**Comment by cedon** [comment]
It might not be a bad idea to update the readme for the repository with how to propose a schema.

**Comment by danbri** [comment]
@cedon I've added some notes to https://github.com/schemaorg/schemaorg/blob/master/README.md to set expectations. I didn't want to get too much into the technicalities of defining schemas there, but will need to update docs on that too.

**Comment by rlzijdeman** [comment]
hi @danbri sorry for the late response.
(1) thanks for the updates in the README.md, the focus of schema.org is much clearer to me now and I will refrain from offering a history-specific solution.
(2) I'd really love to use `schema.org:occupationalCategory`, but then the accompanying text in the manual "[Use BLS O*NET-SOC taxonomy](http://schema.org/occupationalCategory)" should be relaxed somewhat, namely that it can be used with _any_ taxonomy as long as the taxonomy is specified (e.g. being part of a collection). Across the world there are multiple schemes (e.g. ILO's ISCO on which SDMX is based, HISCO, OCCHISCO, and every national variant of SOC). Also just with your own use case in mind relaxing the "USE BLS" statement is important: as over time jobs disappear and new ones are invented, BLS has various versions of their taxonomy and it will be updated in the future.
I therefore propose that schema.org:occupationalCategory applies to any occupational taxonomy, e.g.:
```
<http://some.company.com/jobs/fm>;
    <schema.org:title>"Financial Manager"^^xsd:string .
    <schema.org:occupationalCategory><https://www.onetonline.org/link/summary/11-3031.00> .
 ```
That way, anyone could use any contemporary, future and past occupational taxonomy.
```
<http://some.company.com/jobs/fm>;
    <schema.org:title>"Financial Manager"^^xsd:string .
    <schema.org:occupationalCategory><https://www.onetonline.org/link/summary/11-3031.00> .
   <schema.org:occupationalCategory><https://www.bls.gov/soc/2018/11-3031> .
    <schema.org:occupationalCategory><https://iisg.amsterdam/hisco/category/21000>.
 ```

Best,

Richard
