### ISSUE TITLE
affiliation

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#1849]
`@Person` may have `affiliation` with `@Organization`.
Should `@Organization` have `affiliation` with `@Person`?
Perhaps `@Person` `hasAffiliation` just as `@Person` could be `alumniOf`.
Then `@Organization` would have `affiliation`.
Why might this be important? Because `@Person` may play `@Role` for `@Organization`.
I'm sure this has been discussed in the past - any new thoughts on this `Type/property` relationship?

/jay gray

**Comment by smrgeoinfo** [comment]
Doesn't the 'member' property fill that requirement?

**Comment by RichardWallis** [comment]
Answered
