### ISSUE TITLE
ItemAvailability enumeration missing Unknown value

### ISSUE THREAD

**Issue by KrzysztofPrzygoda** [schemaorg/schemaorg#1850]
I'm new to schema markup and I don't know if value "Unknown" can be even considered as valid in entire Schema idea, but I've found lack of it while trying to apply ItemAvailability in data mapping (no availability data present case).
Can anyone enlighten me if am I on the right track and is it worth to put any effort to extend ItemAvailability by Unknown member?

**Comment by thadguidry** [comment]
Most folks just deal with the concept of "Unknown" or "No Data" as a null void, blank, or empty string.

availability: 
availability: ""

availability: InStock
availability: Discontinued

**Comment by RichardWallis** [comment]
+1

If you haven't got data for a property - don't provide the property.  Then 'unknown' is definitely unknown.

**Comment by KrzysztofPrzygoda** [comment]
Thanks guys for your feedback!

@RichardWallis 
In my case only some data of the entire dataset have no availability value. Most of the dataset this value is present. I wouldn't want to sacrifice dataset structure consistency by skipping property when no value is present.

@thadguidry 
How would you resolve empty value case based on example below?
`<link itemprop="availability" href="http://schema.org/InStock" />In stock`

**Comment by thadguidry** [comment]
ah so microdata format ?  easy...

<link itemprop="availability">unknown</link>
<link itemprop="availability"></link>
<link itemprop="availability">hell if I know</link>

**Comment by RichardWallis** [comment]
@thadguidry I think the answer is don't provide the property!

That would not be inconsistent  (in data terms), whereas providing some value to represent a value you do not know, is inconsistent.

**Comment by thadguidry** [comment]
@RichardWallis up to what the publishers need is.  some still do want to expose the property for testing purposes and data validation :)  and not having the property exposed sometimes makes testing harder, so depends on publishers need.  I don't dictate one representation or another but leave it to the notion of "user knows best".

**Comment by KrzysztofPrzygoda** [comment]
@thadguidry You've caught my point. Sometimes availability is not possible to determine or omitted by mistake. In my case all other properties are more important than availability and it's better to expose incomplete dataset than waiting for its completeness.
