### ISSUE TITLE
Privider examples are the same

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#1858]
I am looking at: https://schema.org/provider

I notice that there are two examples. These seem to be exactly the same. Is this a data error of some kind? Why would there be two examples instead of one? 

It would be helpful if there were one example for "person" and one example for "organization".

**Comment by philbarker** [comment]
Duplication seems to be because two examples in https://github.com/schemaorg/schemaorg/blob/master/data/sdo-course-examples.txt have the same identifier.
