### ISSUE TITLE
Meta bug for expressivity and syntax issues around opening/closing hours

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#186]
Schema.org has several mechanisms related to opening / closing hours; these have expressivity gaps and other inclarities. Let's collect those here, with details in other related bugs if needed.

Brief overview:

Opening Hours
1. http://schema.org/openingHours the informal domain-specific language for common cases
2. http://schema.org/openingHoursSpecification (a property) + http://schema.org/OpeningHoursSpecification (a type, expected value of the property).

There is also the Event type. Although there was an earlier proposal, currently each event is described individually (i.e. there is no framework for repeated events). http://schema.org/Event says,

"An event happening at a certain time and location, such as a concert, lecture, or festival. Ticketing information may be added via the 'offers' property. Repeated events may be structured as separate Event objects."

Interactions? Should 'openingHours' be qualified with 'typical, usual', so that it can be over-ridden? Do we have a convention for treating all opening hours given in the same document/page/graph as together providing an overview of opening times? How can exceptions be recorded? How can closed-all-day situations be represented? Does the micro-language for openingHours tolerate a mix of case (mo vs MO)? Are 3-letter day codes acceptable? (Mon/MON/mon, ...).

See also: Museum-related notes, https://docs.google.com/a/danbri.org/document/d/1at0hgbzZIYDppgGudm0EHSV6vpc6OIv_YDAiydWg6aw/edit

**Comment by danbri** [comment]
See also https://github.com/schemaorg/schemaorg/issues/372

**Comment by danbri** [comment]
Postponing til post-gozer.

**Comment by Jonadabe** [comment]
Hi there,

I think it would be great having something like this:
    TimeTable (instead of openingHours)
        year (???);
        month (the opening and closing time can be seasonal?! Maybe not so usual)
        dayOfWeek (specifying the day can be important because it can be different for one or another day)
        startTime (for openings for a LocalBusiness or starting a work shift for a Person)
        endTime (for closing for a LocalBusiness or ending a work shift for a Person)
        breakPeriod (could be a time hour for lunch (or maybe a day, a month, holiday or vacation period?!)).

Just a though, I can't say if something like this could be implemented.

:-)
