### ISSUE TITLE
Representing ordered author list for creative works

### ISSUE THREAD

**Issue by dksanyal** [schemaorg/schemaorg#1864]
Hi,

I am trying to use Schema.org to model a large web-scale educational digital library. 

However, I find it difficult to model the simple case of an ordered list of authors of a Creative Work like an Article. I think  the order of elements in the mark-up (like a series of schema:author for a schema:Article) is not sufficient for indicating the order of authors. Please correct me if I am wrong.
However, if I am right, then we probably need to model a list of authors as a schema:ItemList with each schema:item having type schema:Person or schema:Organization. That way, though, I lose the succinct abstraction provided by the property schema:author.

Any thoughts on this is highly appreciated.

**Comment by akuckartz** [comment]
See also #1727

**Comment by dksanyal** [comment]
Thanks for linking to  #1727
<https://github.com/schemaorg/schemaorg/issues/1727>.
So the commonly expected solution is to model an author list as a
schema:ItemList.
Suppose Author is a type whose parents are schema:Organization and
schema:Person.
My question is, since we declare AuthorList as a subtype of
schema:ItemList, is there any way to state that the type of a schema:item
in an AuthorList MUST be Author instead of any schema:Thing?

Regards,
Debarshi

**Comment by dksanyal** [comment]
One way, I can think of, to ensure the constraint is to add a property to the new type AuthorList:

Property: authorListElement
Expected type (range): Author [subtype of Person and Organization] or AuthorItem [subtype of Item]

One should then use this property instead of schema:itemListElement from its parent schema:ItemList.

To illustrate it, I provide two examples below.

Example 1 [no explicit author ordering]:

<script type="application/ld+json">
{
  "@type": "AuthorList",
  "authorListElement": [{
      "@type": "Author",
      "name": "Manindra Agrawal"
    },{
      "@type": "Author",
      "name": "Neeraj Kayal"
    },{
      "@type": "Author",
      "name": "Nitin Saxena"
    }
  ]
}
</script>

Example 2 [with explicit author ordering]: 
<script type="application/ld+json">
{
  "@type": "AuthorList",
  "authorListElement": [{
     "@type": "AuthorItem",
     "position": 1,
     "item": {
        "@type": "Author",
        "name": "Manindra Agrawal" }
      },{
      "@type": "AuthorItem",
      "position": 2,
      "item": {
        "@type": "Author",
        "name": "Neeraj Kayal" }
      },{
      "@type": "AuthorItem",
      "position": 3,
      "item": {
        "@type": "Author",
        "name": "Nitin Saxena"}
      }
  ]
}
</script>

Request you to provide your views and feedback. 
Any other suggestions is also deeply appreciated.

Regards.

**Comment by rvguha** [comment]
Debarshi,

 Schema.org is not really meant for that kind of precise data type
modeling. It is intended to be an interchange mechanism for structured data.

 guha

**Comment by dksanyal** [comment]
Thank you, Dr. Guha for your feedback.

We are aiming for an expressive ontology + linked open data (conforming to ontology) + enhanced web discoverability of the library.

So you suggest that we use a more library-friendly ontology (like BIBFRAME, BIBO, etc.) for the RDF store and define mappings to Schema.org. These mappings are, then, allowed to be a little lossy like flattening out a structured list of author information into a single schema:author property (containing comma-separated author names) of the schema:CreativeWork in question.

I encountered similar issues while modeling other library metadata as well.

Your suggestions and feedback are invited. 
They will be immensely helpful to us.

Thanks,
Debarshi

**Comment by RichardWallis** [comment]
@dksanyal Your assumption from @rvguha's answer is correct - using something more domain specific (such as Bibframe) for your system store is correct.

However I would use multiple schema:author properties for detailing several authors - providing links (to VIAF, or similar,  or your own Person definitions) or adding Person, or Organization, definitions in line instead of concatenating names into a single Text value.

That way you would only loose the specific ordering semantics.

~Richard.

**Comment by dksanyal** [comment]
Thank you @RichardWallis  for your explanation and suggestion.
But currently Google Structured Data Testing Tool flags the error "Duplicate key found." when I use  schema:author multiple times for a creative work.

**Comment by RichardWallis** [comment]
The Google SDTT is not only checking for valid Schema.org but also for usefulness within Google specific products/services such as Rich Results (where for example there may only be one author label available for display).

JSON-LD such as this:
```  "@context": "http://schema.org",
  "@type": "Book",
  "name": "Weaving the Web",
  "author": ["http://viaf.org/viaf/85312226","http://viaf.org/viaf/874883"],
```
...is valid Schema.org, where all properties are repeatable.

Note sometimes the primary author is emphasised by also adding them as ```creator```.

~Richard.

**Comment by dksanyal** [comment]
Thanks a lot.  
Even though repetition of a property is not currently supported in Google SDTT, one can use a JSON array - instead of a string concatenation - to indicate multiple values.
