### ISSUE TITLE
What happened to http://schema.rdfs.org/all.json?

### ISSUE THREAD

**Issue by guest271314** [schemaorg/schemaorg#1867]
What happened to http://schema.rdfs.org/all.json?

FYI "Definition"  and "Excerpt" have been published at http://guest271314.com/data/html/microdata/vocabulary/extend/Definition.html, https://github.com/guest271314/Definition/blob/master/Definition.json and http://guest271314.com/data/html/microdata/vocabulary/extend/Excerpt.html, 
https://github.com/guest271314/Definition/blob/master/Excerpt.json for over three years.

Is there an existing single JSON document containing all of the both endorsed and terms and definitions in the wild which could be used to substitute for the now defunct http://schema.rdfs.org/all.json?

**Comment by RichardWallis** [comment]
You may find what you are looking for here: http://schema.org/docs/developers.html#defs

**Comment by guest271314** [comment]
@RichardWallis schema.jsonld has replaced all.json?

**Comment by RichardWallis** [comment]
Not as such, as schema.rdfs.org is/was not part of the release process of Schema.org.

I believe that it was created, by another group, to fulfil the need for machine readable dumps of the Schema.org vocabulary prior to the definition files I referenced being made available.

As (again I believe) all.json contained only the terms from the core vocabulary, then schema.jsonld will be the nearest match.   

If you want a file that contains the definitions for all core terms and terms from the hosted extensions ( auto, bib, health-lifesci, iot, meta and pending)  the all-layers file contains these.
