### ISSUE TITLE
Physician should be a subtype of Person

### ISSUE THREAD

**Issue by carl-burnett** [schemaorg/schemaorg#1876]
It's very strange to me that Physician is only being considered a LocalBusiness and a MedicalOrganization. It should also be a Person, so that we can use properties like affiliation, gender, honorificSuffix, etc.

**Comment by twamarc** [comment]
Thanks opening this again @carl-burnett .
The topic was highly discussed some months ago, without any conclusion:
Readr the following threads:
https://github.com/schemaorg/schemaorg/issues/280#issuecomment-253944253
but the most conclusive I think is this:
https://github.com/schemaorg/schemaorg/issues/1410
Let's see the community intersts, and find a way forward
