### ISSUE TITLE
stupidProperty property does not exists for related type BusOrCoaches in property csv file

### ISSUE THREAD

**Issue by khalyomede** [schemaorg/schemaorg#1880]
The property `http://schema.org/stupidProperty` does not exists in downloadable file at `http://schema.org/version/latest/all-layers-properties.csv` (mentionned in properties of type `http://schema.org/BusOrCoach`.

Is that an april fool or a real missing property?

**Comment by khalyomede** [comment]
Gave it a search and found 4 other occurences of this "property":

- In `http://schema.org/CancelAction` type
- In `http://schema.org/Motorcycle` type
- In `http://schema.org/MotorizedBicycle` (seems to not approve motorcycles)
- In `http://schema.org/Vehicle` (nor all that can be driven obivously)

Any clue guys?

**Comment by danbri** [comment]
Please ignore 'stupidProperty', it is/was a test of the "attic" area of the
site, where we document old terms (superseded / obsoleted).

The thinking is that once something has been in schema.org we should keep
some minimal documentation, but that it should be mostly hidden away. It
seems we didn't hide it well enough as you found it...

**Comment by khalyomede** [comment]
Okay got it thank you !

**Comment by khalyomede** [comment]
I guess you will do the same for its type counterpart `http://schema.org/StupidType` (which is referenced as a sub-type of `http://schema.org/Thesis`?
