### ISSUE TITLE
How to run without Google App Engine

### ISSUE THREAD

**Issue by NeoCN** [schemaorg/schemaorg#1903]
How to run this site without Google App Engine ？ Just want to mirror schema.org because it can not be visited in China~

**Comment by RichardWallis** [comment]
The data behind the site is available in various forms (JSON-LD, RDF/XML, Turtle, Triple, CSV) to download from the [Developers](http://schema.org/docs/developers.html) page.  The 'all-layers' version will contain all you need.

The html web pages are created dynamically in the App Engine so, currently, they are not available for download/mirroring or running in an another architecture.   Also the generated html includes calls to script code, for on page features such as site search and formatting etc., hosted by Google.

Making it easier for access from restricted geographies such as China is something I am looking at, alongside other architectural considerations.

I would be interested to hear how you would intend to implement such a mirror and keep it in sync with the main site.

~Richard

**Comment by NeoCN** [comment]
@RichardWallis Google related services are banned in China, so if you want to make it easier for access from restricted geographies such as China, `Google Cloud` should not be used. 

My simple way to mirror and keep it sync with main site is just use `git pull` and run it under another domain~ Now I realized that it is not simple to run it without `Google App Engine`~ We can run it in Docker with `local development server` but feel weird~

**Comment by RichardWallis** [comment]
In the short term that is probably the best way.  You will still have issues with included files (eg.jquery.js) sourced from Google, but that should be comparatively easy to handle..  Also the search function is handled by a Google Custom Search Engine.

To help me as I explore this area, can you share:  Is Github directly visible in China?  Are there other cloud services, such as Amazon Web Services that are visible from China?  Are there equivalent Cloud services available in China, with APIs available outside China.

**Comment by NeoCN** [comment]
Github is directly visible in China. [`AWS China`](https://amazonaws-china.com/?nc2=h_lg) may be a choice.
