### ISSUE TITLE
schema.org for provenance information?

### ISSUE THREAD

**Issue by acka47** [schemaorg/schemaorg#1905]
We are currently working on adding more provenance information to the entries of a dataset where RDF descriptions of resources are created from a legacy data base. We started with looking into the PROV ontology (see https://github.com/hbz/lobid-resources/issues/809#issue-316248933) but I noticed that we could also use schema.org and even convey a bit more information with it. The general approach in using schema.org for provenance information would look like this:

```json
{
  "@context":{
    "@vocab":"http://schema.org/",
    "resultOf":{
      "@reverse":"result"
    }
  },
  "@id":"http://lobid.org/resources/HT014422806#!",
  "@type":"Book",
  "name":"The elements",
  "mainEntityOfPage":{
    "@id":"http://lobid.org/resources/HT014422806",
    "resultOf":{
      "@type":"Action",
      "endTime":"2018-04-27T14:23:10",
      "instrument":{
        "@id":"https://github.com/hbz/lobid-resources",
        "name":"Software lobid-resources"
      },
      "object":{
        "@id":"http://lobid.org/hbz01/HT014422806",
        "name":"Entry from the hbz union catalog"
      }
    }
  }
}
```

As I haven't found an already existing example where schema.org is used like this I want to reassure myself that it actually makes sense and that schema.org is as good a vocabulary choice as PROV ontology for our use case. What do you think?

**Comment by RichardWallis** [comment]
The jsonld seems syntacticly correct to me.

Reading it is telling me that some thing of type _Book_ with the id _http://lobid.org/resources/HT014422806#!_ has the name "_The elements_", is was produced by some undefined action at 23:10 on 27th April 2018.

The action was performed using some undefined thing with the id _https://github.com/hbz/lobid-resources_, named "_Software lobid-resources_".   The action was performed on an undefined thing with the id _http://lobid.org/hbz01/HT014422806_ named "_Entry from the hbz union catalog_".

This to me raises the following questions:
- Would the [CreateAction](http://schema.org/CreateAction) be a better Action type to use, indicating that the instrument created http://lobid.org/resources/HT014422806#!.
- What type of thing is the instrument?  Would the [SoftwareApplication](http://schema.org/SoftwareApplication) type be appropriate here.
- What sort of thing is http://lobid.org/hbz01/HT014422806?  Would _CreativeWork_, _Book_, or _DataFeedItem_ be appropriate? 
--  Is its name really "Entry from the hbz union catalog"? 
- It seems to me that it would be appropriate to indicate that http://lobid.org/resources/HT014422806#! is sameAs http://lobid.org/hbz01/HT014422806

**Comment by acka47** [comment]
Thank you, Richard, for this comment. I assume that you generally find it reasonable to use schema.org for this. Your questions are very helpful:

> - Would the CreateAction be a better Action type to use, indicating that the instrument created http://lobid.org/resources/HT014422806#!.

Yes, this makes sense. We will use that instead.

> - What type of thing is the instrument? Would the SoftwareApplication type be appropriate here.

Yes, we will add the type.

> - What sort of thing is http://lobid.org/hbz01/HT014422806? Would CreativeWork, Book, or DataFeedItem be appropriate?

As we distinguish between the actual book and a description in our model, this would be the description as exported from the catalog (=a record). So `DataFeedItem` might be the proper type if it is used like "record from a dataset"...

> -- Is its name really "Entry from the hbz union catalog"?

This is just a generic label we use for all those entries.

> - It seems to me that it would be appropriate to indicate that http://lobid.org/resources/HT014422806#! is sameAs http://lobid.org/hbz01/HT014422806

Yes, it definitely is ok when using `schema:sameAs` but it is not the same in terms of `owl:sameAs` as one identifies the actual book while the other identifies a description. We will think about adding this statement.

**Comment by acka47** [comment]
Thinking about it, the type `UpdateAction` probably makes more sense as most of the time the resource is re-created by the Action and only the first time a new resource is created.

**Comment by RichardWallis** [comment]
@acka47 I don't see any reason why this would not work.

If you did use DataFeedItem, then I would suggest the name, in this case, was "_The elements_" and then possibly use disambiguatingDescription for "Entry from the hbz union catalog", or even use some of the available properties to identify where the record is coming from.

**Comment by RichardWallis** [comment]
Using _UpdateAction_ or one of its appropriate subtypes (_AddAction_, _ReplaceAction_) would allow you to identify the collection that the Book _isPartOf_

**Comment by acka47** [comment]
Closing, as we actually implemented this using a lot of schema.org, see https://github.com/hbz/lobid-resources/issues/809
