### ISSUE TITLE
add enumerated values to schema context

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1906]
http://sdo-auto-fix.appspot.com/docs/automotive.html#hybrid_car (#1677 ex2 jsonld) uses this markup to ensure enumeration values are emitted as URL:
```json
  "steeringPosition":{"@id":"http://schema.org/LeftHandDriving"},    
  "driveWheelConfiguration":{"@id":"http://schema.org/RearWheelDriveConfiguration"},
```
However, it's better to follow http://iiif.io/api/annex/notes/design_patterns/#use-strings-for-enumerated-flags and add this to the schema context:
```json
  "steeringPosition":{"@type":"@id", "@id":"schema:steeringPosition"},
  "LeftHandDriving":{"@id":"schema:LeftHandDriving"}, // etc for all enum values
  "driveWheelConfiguration":{"@type":"@id", "@id":"schema:driveWheelConfiguration"},
  "RearWheelDriveConfiguration":{"@id":"schema:RearWheelDriveConfiguration"}, // etc for all enum values
```
Then you can emit values in the simplest possible way:
```json
  "steeringPosition":"LeftHandDriving",
  "driveWheelConfiguration":"RearWheelDriveConfiguration",
```

**Comment by VladimirAlexiev** [comment]
cc @danbri @sopekmir @trypuz @RichardWallis

**Comment by RichardWallis** [comment]
Would be comparatively simple to introduce this into the code that produces the context, when an Enumeration subtype is being output.

Would need to check the impact for types that are subtypes of Enumerations combined with other types.  eg. http://schema.org/CreditCard.
