### ISSUE TITLE
provider as property for MedicalSpecialty/Medical Service

### ISSUE THREAD

**Issue by nateanalytics** [schemaorg/schemaorg#1908]
Marking up service pages or medical specialty pages, I don't see a way to show that this service or specialty is provided by the hospital, since MedicalSpecialty, MedicalTest, MedicalProcedure, and MedicalTherapy. 

The property of "provider" is not recognized for MedicalProcedure, MedicalTest, MedicalTherapy, or MedicalSpecialty. 

Is there a way to add "provider" as a property?

**Comment by RichardWallis** [comment]
A provider of the medical services (MedicalProcedure, MedicalTest, MedicalTherapy and their subtypes) can indicate this by using the [availableService](http://health-lifesci.schema.org/availableService) property.

**Comment by nateanalytics** [comment]
Maybe I wasn’t clearer in my initial post.

If the page is specifically about the medical specialty, then has the
doctors that perform that specialty, there’s nothing that determines that
the medicalSpecialty is provided or performed by these physicians. If @type
is “medicalSpecialty.”

Think of it like a service page, where the page can be about House Cleaning
services, which are provided by these companies. Is there a way to have a
page about a Medical Specialty that is provided by this hospital or
performed by doctors?

Your example works if the page is about the physician or the hospital with
that medical specialty.

I’m sorry if I’m not being clear.


-- 
Nate Griffin

On May 2, 2018 at 9:53:00 AM, Richard Wallis (notifications@github.com)
wrote:

A provider of the medical services (MedicalProcedure, MedicalTest,
MedicalTherapy and their subtypes) can indicate this by using the
availableService <http://health-lifesci.schema.org/availableService>
property.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/schemaorg/schemaorg/issues/1908#issuecomment-386005695>,
or mute the thread

**Comment by RichardWallis** [comment]
@nateanalytics I think I understood your use case:
```
<div>
    <h1>Hospitals and other organizations offering proceedure:</h1>
    <div itemscope itemtype="http://schema.org/MedicalProcedure">
        <h2 itemprop="name">Body Transplant</h2>
        <meta itemprop="url" content="#medproc1">
    </div>
    <div itemscope itemtype="http://schema.org/Hospital">
        <h3 itemprop="name">Body Swap Hospital</h3>
        <meta itemprop="availableService" content="#medproc1">
    </div>
    <div itemscope itemtype="http://schema.org/MedicalClinic">
        <h3 itemprop="name">Transplants R us Inc</h3>
        <meta itemprop="availableService" content="#medproc1">
    </div>
</div>
```

**Comment by nateanalytics** [comment]
I was using JSON-ld for this instance, but you may have just clarified what I’m trying to do won’t work for that.
