### ISSUE TITLE
Add workload on CourseInstance ?

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1909]
CourseInstances differ in their duration and oftentimes their workload (daily/weekly/etc).

In looking internally at Ericsson, I noticed we have all our training summarized by Duration and Workload so that employees can see if they can allocate time for additional training during a quarter or year.

Workload - how many hours per week is expected (lecture, lab work)

@philbarker Thoughts ?

**Comment by philbarker** [comment]
Yes, seems useful and more realistic than dividing the `typicalLearningTime` of the `Course` by the `duration` of the `CourseInstance` or trying to add up any `subEvent`s

A text value, I guess, for example "2 hours of lectures, 1 hour of lab work and 3 hours of independent study time per week."

**Comment by stuartasutton** [comment]
Yes, this is useful. I'd note, however, that in many courses, that work load is set at the Course level (e.g., by university formulas for hours by credit units awarded etc). So, I'd think we might include both Course and CourceInstance as domain depending on where it is articulated in a given instance.

**Comment by philbarker** [comment]
@stuartasutton I think that there is less benefit in adding to`workload` to `Course` as `typicalLearningTime` already covers the common use case of needing to accumulate X hours of 'learning' for Y credits. The dividing up into some-many hours per week seems to be inherently a property of `CourseInstance`. That said, I think there is little damage to be done and it might increase uptake from those who don't really want to present separate `CourseInstance`s so it could be worthwhile.

**Comment by philbarker** [comment]
Hi @science I think `timeRequired` is more appropriate for what you describe.

**Comment by philbarker** [comment]
Pull request uses definition "The amount of work expected of students on the course, often provide as a figure per week or per month, and may be broken down by type. For example, "2 hours of lectures, 1 hour of lab work and 3 hours of independent study per week", and does not have Course in domain. That seemed to me to be more in keeping with the way we model Course / CourseInstance, and Couse already having [`timeRequired`](https://schema.org/timeRequired) but I don't have very strong feelings about it.

**Comment by stuartasutton** [comment]
Phil, did you mean "in the course" and not "on the course"? While there will likely be overlap on occasion between  [`timeRequired`](https://schema.org/timeRequired) and `workload`, they are qualitatively different.

**Comment by philbarker** [comment]
Stuart, I meant "students on the course" in the sense of "students taking the course". A quick google suggests that "on the course" may be en-GB idiom and "in the course" en-US. Would "students taking the course" sound more natural to US ears?

I agree that workload and timeRequired are qualitatively different, for example timeRequired will be (approx) the same for all instances of a Course where as workload (per week, and as divided up by activity) could be exactly what varies between different instances, which is why I think workload is more of a CourseInstance property than a Course property.

**Comment by stuartasutton** [comment]
Phil, "students taking the course" is a suitable international compromise.
