### ISSUE TITLE
JSON-LD context proposal: make recipeInstructions and other properties default to lists

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1910]
# Proposal: declare some properties as being list containers in JSON-LD

I propose adding to our json-ld context declarations such as: 

> "recipeInstructions":{"@id":"schema:recipeInstructions","@container":"@list"}

* This will affect only JSON-LD representations of schema.org data, and the cross-domain list patterns based around ItemList, ListItem would continue to be usable.
* It means that parsers will be justified in preserving the in-document order of the values of those properties
* This makes lists (and lists of lists) significantly more readable in JSON(-LD) and addresses a big usability issue, which is that people see the array notation ('[', ']') and then are confused that the ordering is lost.
* We should consider possible negative impact on existing implementations
* How problematic is this change for existing JSON-LD parsers? Cases like ...
  * e.g. "recipeInstructions": "1. foo 2. bar"
  * e.g. "recipeInstructions": [ "1. foo 2. bar" ]
  * e.g. "recipeInstructions": [ "1. foo", "2. bar" ]

My judgment is that the usability and readability win for publishers makes this worth doing, but I want to consult the wider JSON-LD implementor community before going further with the idea.

# Problem statement 

To elaborate on the problem, consider the case of recipe markup in JSON-LD.

There are fields for the various *ingredients* and for the *instruction* steps. The critical difference is that nobody cases for the order of the ingredients, whereas the instructions need to be ordered. 

The problem is complicated by the fact that JSON does not support repeated uses of the same field on an object; this means that JSON-LD requires array syntax even for simple repetition of a property.

## Example

``` javascript
{
  "@context": "http://schema.org/",
  "id": "r1",
  "type": "Recipe",
  "name": "Strawberry-Mango Mesclun Recipe",
  "recipeYield": "12 servings",
  "nutrition": {
    "@type": "NutritionInformation",
    "servingSize": "1 bowl",
    "calories": "319 cal",
    "fatContent": "20.2 g"
  },
  "recipeIngredient": [  // <- want this property to be merely repeated; order doesn't matter
    "1/2 cup sugar",
    "3/4 cup canola oil",
    "1 teaspoon salt"
  ],
  "recipeInstructions": [  <- but for this one to be parsed as containing an ordered list
    "step one here",
    "step two here",
    "step three here"
  ]
}
```

Adding the declaration to our context file is a way of telling JSON-LD parsers that the 2nd array here is one that encodes significant order, whereas the first can be ignored. The default otherwise is that order is ignored, which forces us to use unwieldy and complex structures to keep it.

# Inline context

Here is another version which has the context declaration inline. This can be useful for testing in JSON-LD tools

``` javascript

{
  "@context": [
    "http://schema.org/",
    {"recipeInstructions": { "@id": "schema:recipeInstructions","@container": "@list"} }
  ],

  "id": "r1",
  "type": "Recipe",
  "name": "Strawberry-Mango Mesclun Recipe",
  "recipeYield": "12 servings",
  "nutrition": {
    "@type": "NutritionInformation",
    "servingSize": "1 bowl",
    "calories": "319 cal",
    "fatContent": "20.2 g"
  },
  "recipeIngredient": [  // <- want this property to be merely repeated; order doesn't matter
    "1/2 cup sugar",
    "3/4 cup canola oil",
    "1 teaspoon salt"
  ],
  "recipeInstructions": [  <- but for this one to be parsed as containing an ordered list
    "step one here",
    "step two here",
    "step three here"
  ]
}

```

**Comment by danbri** [comment]
Ping @gkellogg @azaroth42 @msporny @iherman @draggett

**Comment by danbri** [comment]
Testing in JSON-LD 1.0 Playground. Note that the triples linked list RDF representation could be converted into other ordering representations downstream from JSON-LD parsing.

# Example 1.

```
{
  "@context": [
    "http://schema.org/",
    {"recipeInstructions": { "@id": "schema:recipeInstructions","@container": "@list"} }
  ],
  "recipeInstructions": [ "step two here"  ]
}

Results:

* _:b0 <http://schema.org/recipeInstructions> _:b1 .
* _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "step two here" .
* _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
```

# Example 2

```
{
  "@context": [
    "http://schema.org/",
    {"recipeInstructions": { "@id": "schema:recipeInstructions","@container": "@list"} }
  ],
  "recipeInstructions":  "step two here"  
}
```
Results: as above.

# Example 3

```
{
  "@context": [
    "http://schema.org/",
    {"recipeInstructions": { "@id": "schema:recipeInstructions","@container": "@list"} }
  ],
  "recipeInstructions": [ "a", "b","c"  ]
}

Results:

* _:b0 <http://schema.org/recipeInstructions> _:b1 .
* _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "a" .
* _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b2 .
* _:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "b" .
* _:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b3 .
* _:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "c" .
* _:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .

**Comment by azaroth42** [comment]
:+1: to this proposal

**Comment by nicolastorzec** [comment]
👍

**Comment by gkellogg** [comment]
This should be pretty transparent to existing conforming JSON-LD processors, as `@list` support is in the test suite.

The RDF list representation only comes into effect when turned into RDF (obviously), and those familiar with that ecosystem know how to deal with it. But, there alternative list representations, and there is an open issue json-ld/json-ld.org#595 that provides some alternatives for representing ordered values, at the expense of added processor complexity. Down-stream processing may be the way to address it.

Note that RDFa examples could use the `@inlist` attribute to get a similar result, although not Microdata.

**Comment by danbri** [comment]
Thanks @gkellogg for taking a look, much appreciated. You have eased my main concern somewhat, which is for full JSON-LD users. We can also note that nowhere did we promise never to change the Schema.org context file; it has been evolving in various ways as best practices and issues get discussed.

**Comment by danbri** [comment]
I've also asked on [public-linked-json](https://lists.w3.org/Archives/Public/public-linked-json/2018May/0000.html), to help ensure any affected parties see the proposal.

**Comment by niklasl** [comment]
Yes, this is a useful declaration of what is to be expected for such properties. They make less sense without order, and any consumers relying on them would have ran into problems in practise without this. Thus changing it now seems completely beneficial.

**Comment by kaefer3000** [comment]
For me, that makes sense, as using lists is exactly how we describe workflows in RDF (with the aim of executing them on Linked Data, [see a working paper](https://arxiv.org/abs/1804.05044), [an ontology](http://purl.org/wild/vocab), and [an example](http://people.aifb.kit.edu/co1683/2018/iswc-wild/workflows/fig1.ttl)). I think recipe instructions can be regarded as some sort of simple workflow.

**Comment by RichardWallis** [comment]
In principle I welcome this proposal, not least as it will remove the need to launch into a mini '_The principles of RDF_' lecture, when often challenged with the assumption that the order of things within a page somehow influences the understanding of a data consumer.   

I will leave it to the JSON-LD gurus to come to a consensus to the best way to implement. 

In practice I think we need to address the following:

1.  If I use this approach will Google [other data consumers are available] take any notice of it? - Not my question but an entirely expected question from the community.
2. The syntax of .rdfa files (e.g. data/schema.rdfa) that define the vocabulary should be enhanced to enable the easy declaration of properties that should be identified in this way in the Schema.org context file.  The code that generates the context file would need to be upgraded to reflect this.
3. We should adopt @gkellogg's recommendation to adopt \@inlist for RDFa serialisation.
4. Appropriate examples should be updated to reflect the changes **at the same time as** the release.
5.  There should be documentation produced to describe how to mark up lists (ordered and not ordered) in all three serialisations.

**Comment by tilid** [comment]
I like the idea to bring an order to arrays. 
I've tried to realize how it may affect current users and current parsers. First of all, I've looked at Yandex's services, which using JSON-LD (they should be ok with this JSON-LD context version). 
It would be great to create some different example and broad explanation for webmasters (and for JSON-LD consumers)

**Comment by danbri** [comment]
Ok, this is looking rather close to a consensus view. To address the points @RichardWallis raised:

1. Yes, we expect to use this approach at Google when documenting examples that contain order in JSON-LD, at least around recipes associated howto markup.
2. Yes that would be one option, also this has been an issue for other aspects of the context file, I've created a tracking bug. #1913 
3. @inlist is certainly a similar mechanism for RDFa (at the instance data level), but I do not want to slow down progress here for JSON-LD by requiring consensus on yet another file format and its ecosystem.
4. Examples - yes - and suggestions welcomed. We have previously donated examples to Schema.org from Google's documentation site, and can do that again easily. Can also change the recipes.
5. Yes, we ought to do that. We may not have a grand unified theory of lists that explains exactly how the different itemlist-based idioms, W3C's two RDF list constructs, and other patterns relate. I think we should begin with clear examples for recipeInstructions and build out from there, rather than starting with generalities.

**Comment by lanthaler** [comment]
:+1: fully support this proposal. It makes the implicit contract explicit and solves a couple of surprising problems people otherwise encounter. 

Btw. the inline context could be simplified to

```jsonld
{
  "@context": [
    "http://schema.org/",
    {"recipeInstructions": { "@container": "@list"} }
  ],
  ...
}
```

It would be great if schema.org could be updated so that the documentation of a property would explicitly call out whether a property's value is supposed to be an ordered list or not. If that would be done as part of the machine-readable definition, both the docs and the context could be auto-generated.

**Comment by RichardWallis** [comment]
I support @lanthaler's suggestion:

> It would be great if schema.org could be updated so that the documentation of a property would explicitly call out whether a property's value is supposed to be an ordered list or not. If that would be done as part of the machine-readable definition, both the docs and the context could be auto-generated.

I suspect any other approach would introduce a manual maintenance overhead that would be difficult to keep synchronised.

However, such references as they appear in human readable documentation would need to be clarified as to what it means for serialisations other than json-ld.

**Comment by tmarshbing** [comment]
I support the changes being described above, including the added examples and documentation.

**Comment by danbri** [comment]
Ok, let's do this...

**Comment by danbri** [comment]
I suggest initially we mark up "recipeInstructions" and "step"(s)* as JSON-LD list-valued properties, and then evaluate from there before doing others.

(*) conventions for plurality of property naming might need some attention (and flexibility)

**Comment by danbri** [comment]
I have sent out a [v3.4 release draft](https://lists.w3.org/Archives/Public/public-schemaorg/2018May/0030.html) which doesn't include this change, since we have a few areas of work:

 * identifying potential other properties beyond recipeInstructions
 * figuring out what to do for the HowTo-related case, whose vocabulary is entangled with ItemList-related terminology (and where 'step' vs 'steps' might need more attention).
 * implementation practicalities - https://github.com/schemaorg/schemaorg/issues/1913
 * examples and documentation

**Comment by Pingguin** [comment]
Yes I'm heré very sóon I will appear....

**Comment by danbri** [comment]
I still think we should do this

**Comment by RichardWallis** [comment]
I also agree we should.

From an implementation point of view we would need to do the following:
1. Identify a suitable predicate for a triple in the property definition for _recipeInstructions_ and other similar properties, to indicate it is of this type.
2. Update the code that creates the context file to output the relevant directives.
3. Design a minor update to the UI that indicates to developers that a property infers this functionality, that also links to...
4. Add documentation explaining the capability
5. Create relevant example(s).
6. Post a succesful initial implementation, instigate a process to identify other suitable candidate properties.

**Comment by akuckartz** [comment]
Why was this closed ?!

**Comment by danbri** [comment]
I need to make the stale action bot less aggressive! will reopen

**Comment by msporny** [comment]
> My judgment is that the usability and readability win for publishers makes this worth doing, but I want to consult the wider JSON-LD implementor community before going further with the idea.

I missed the notification the first time through. Agree that this should be done (like everyone else)... also, noting @jvandriel 's concerns as things that should be answered.

**Comment by rrlevering** [comment]
At Google we cheat often and use source order as a fallback in cases where ItemList/position is not used.  Yes, this is incorrect and yes, with complex node merges it gets bad but in the common case it usually works.

I have been talking to Dan for years now about how to improve this.  There are issues that were brought up in this conversation that are not as simple as sticking it in the context file.  Or if it was, it would be superficial markers and not technically valid.  schema.org doesn't have any native support for RDF list structures.  If the range of a property is a certain type, is a list of that type valid or not?

So I'm in favor of a context change, but I want schema.org to explicitly say something like RDF collections are supported on any predicate or has to be explicitly added to each predicate range so it can be correctly parsed/validated.  Otherwise it's kinda meaningless and half-implemented in only JSON-LD.

**Comment by rrlevering** [comment]
Ok, that's a start on the extraction side.  But triples themselves are still not ordered intrisically right?  JSON-LD list notation specifies that they turn into RDF lists when @list is used whereas Microdata has no such guidance.  You would need support in the Microdata -> RDF standard as well.

What we could do in Google's parser at least is assume that multi-value properties imply RDF list (a formal list structure) IFF the range of the predicate has a List<....> type or something like that.  That's generally how we use schema to override syntactical limitations (like a lack of strong data typing in Microdata).
