### ISSUE TITLE
Which version of SiteNavigationElement is correct?

### ISSUE THREAD

**Issue by alexzubovich** [schemaorg/schemaorg#1912]
```
<ul itemscope itemtype="https://schema.org/SiteNavigationElement">
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-1">Page 1</a></li>
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-2">Page 2</a></li>
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-3">Page 3</a></li>
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-4">Page 4</a></li>
</ul>
```

or

```
<ul>
   <li itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement"><a itemprop="url" href="https://example.com/page-1"><span itemprop="name">Page 1</span></a></li>
   <li itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement"><a itemprop="url" href="https://example.com/page-2"><span itemprop="name">Page 2</span></a></li>
   <li itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement"><a itemprop="url" href="https://example.com/page-3"><span itemprop="name">Page 3</span></a></li>
   <li itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement"><a itemprop="url" href="https://example.com/page-4"><span itemprop="name">Page 4</span></a></li>
</ul>
```

**Comment by Meteor0id** [comment]
I have been reading up on this as well today and finally settled on:

<ul itemprop="WebPageElement" itemscope itemtype="http://schema.org/SiteNavigationElement">
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-1">Page 1</a></li>
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-2">Page 2</a></li>
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-3">Page 3</a></li>
   <li itemprop="name"><a itemprop="url" href="https://example.com/page-4">Page 4</a></li>
</ul>

By default, the parent itemscope is of type WebPage, and it accepts a property of WebPageElement.
Notice I also changed it to http://schema.org rahter than https://. I might be mistaken but I think the vocab is best referenced as http:// .

**Comment by Meteor0id** [comment]
you don't have to use a list btw:
```
<nav itemprop="WebPageElement" itemscope itemtype="http://schema.org/SiteNavigationElement">
<a itemprop="url" href="https://example.com/page-1"><span itemprop="name">Page 1</span></a>
<a itemprop="url" href="https://example.com/page-2"><span itemprop="name">Page 2</span></a>
<a itemprop="url" href="https://example.com/page-3"><span itemprop="name">Page 3</span></a>
<a itemprop="url" href="https://example.com/page-4"><span itemprop="name">Page 4</span></a>
</nav>
```

**Comment by Meteor0id** [comment]
yea nevermind me. WebPageElement is appearently not a child of WebPage. I have to agree things can get very confusing with schema.org vocab. But if you leave the itemprop="webpageelement" part out, you should be fine.

**Comment by alexzubovich** [comment]
When marking with [this](https://github.com/schemaorg/schemaorg/issues/1912#issuecomment-396053484) method we get this (from Google Search Console):
![search_console_structured_data](https://user-images.githubusercontent.com/16488560/41216161-cf5d67ae-6d5b-11e8-96b2-989622ab5a30.jpg)
(Google sees here one menu item)

**Comment by Meteor0id** [comment]
Also see:
[stackoverflow - what-is-the-correct-use-of-schema-org-sitenavigationelement](https://stackoverflow.com/questions/12491102/what-is-the-correct-use-of-schema-org-sitenavigationelement#22133880)

I tested it in google, and got the same result as you @alexzubovich. This is gettign ridiculous. Schema's vocabulairy is a total mess when it comes to anything realted to WebPageElement. I think the issues in't with you or with Google, its with schema vocab, it just isn't clear how this tpye should be used, and thus google uses it in a different manner than the rest of us.

My advise:
Untill WepPageElement has been revised, avoud any property or tpye related to it. Marking up your navigation element won't have much impact anyway, althoug I am also in favor of marking up as much as we can, including site navigation elements. But as for now, the schma vocab is such a mess on this subject, there is no good way to use it.

Anything to do with WebPageElement has to be revised. It just does not make sense. For now, don't use it.

**Comment by jhabdas** [comment]
Google isn't the only structured data testing tool:
https://webmaster.yandex.com/tools/microtest/

Pass in the following markup:

```
<nav itemscope itemtype="http://schema.org/SiteNavigationElement">
  <meta itemprop="name" content="Navigation Menu">
  <a itemprop="url" href="/">Overview</a>
  <a itemprop="url" href="/feature/">Features</a>
  <a itemprop="url" href="/module/">Modules</a>
  <a itemprop="url" href="/shortcode/">Shortcodes</a>
  <a itemprop="url" href="/extra/">Extras</a>
  <a itemprop="url" href="/search/">Search</a>
</nav>
```

And out pops some neatly structured property-value pairs for the item:

<img width="428" alt="screen shot 2018-10-15 at 8 08 18 pm" src="https://user-images.githubusercontent.com/440298/46950077-2351f880-d0b6-11e8-85c0-3215a0796190.png">

**Comment by unor** [comment]
From #1251:

> - I often saw that the existing properties get used incorrectly, for example:
>   - Authors use a `SiteNavigationElement` for each navigation link (not for the whole navigation) or a single `SiteNavigationElement` with multiple `name`/`url` properties (not for the name/URL of the navigation, but of the navigation entries).

For providing data about each navigation link, you could use a MTE with `SiteNavigationElement` and `ItemList`, where each list item is a `WebPage` ([JSON-LD example](https://stackoverflow.com/a/52766577/1591669), [Microdata example](https://stackoverflow.com/a/45379111/1591669)).
