### ISSUE TITLE
Price field error

### ISSUE THREAD

**Issue by mikeflanny** [schemaorg/schemaorg#1915]
Hi,

I've added dynamic JSON-LD on a client page through GTM. Everything is pulling exactly as intended. My only problem is the price comes over as such $16,980.

It is how it shows on the site. Is there a way to grab this field and modify it to comply with the standards?

The site is here: http://handsautos.com/2009-Jeep-Wrangler/Used-SUV/Stratford-CT/9937245/Details.aspx

**Comment by RichardWallis** [comment]
As this is the community for the definition and enhancement of the Schema.org vocabulary, not proprietary tools that use it, this is not really the forum for this question.  

I suggest directing directing your question to the [GTM forum](https://productforums.google.com/forum/#!forum/tag-manager), where I am sure someone will be able to code up how to strip the '$' from your price string.
