### ISSUE TITLE
describe physical classes of a person: eg skin type, face shape, body shape, Seasonal Color group, 3d geometry face and body. 

### ISSUE THREAD

**Issue by Torgrima** [schemaorg/schemaorg#1917]
I would like to have standard labels for a person's physical appearance, then it can be easier to create product filters to matching product and the person. 

e.g if you sell glasses on the web, it will be easyer to recomend the best shape, color and size that will fit a spesific person given a spesific face shape, 3d geometry of the head and what Seasonal Color group the person belong to. 

This data will be important for cosmetic/fashion industry, headdress/hearsalong etc.

**Comment by danbri** [comment]
If such formats exist, we can come up with a way to reference them from
schema.org, but this is closer to computer gaming than to our areas of
expertise

**Comment by Torgrima** [comment]
Thanks for quick response, if you got the impression that this is more related to computer gaming then e-commerce and product matching. I will try to give some more details. 

Some products like glasses, hear styles and makeup rules is linked especially to a Face shape and Body Shape. The shape can be calculated and grouped easily with a decision tree. 

-The “Face shape” class is typical grouped into labels like: Square, rectangle, triangle, Trapezoid, Hexagon Oval, Circle and Oblong.

http://drjerryepstein.org/content/science-face-reading-practitioners-guide-morphology
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132726 

-Color theory gives you a better understanding of the concept behind the seasonal color analysis, and how a coloring is assessed.
Each person's coloring (hair, skin and eyes) will have a dominant characteristic which is a primary factor in deciding their seasonal group. The class «Seasonal Color» can be calculated and grouped with a decision tree.  http://www.thechicfashionista.com/your-best-perfect-colors.html 

-The class “Skin type” is very much dependent on what Seasonal Color group you belong to with some extra features. The class “Skin type” is typical labeled in 6 groups after the Fitzpatrick scale. but can be sub grouped depending of the accuracy you want. 
The skin type is dependent on how much UV exposure the skin can handle eg 1 MED (210 j/cm2). 
before it gets sunburn, pigmented, d-vitamin: https://en.wikipedia.org/wiki/Fitzpatrick_scale 

-3d geometry is important when you want to sell clothes, shoe or any type of item that should fit a specific body, especially when there is a lack of international size standards. 
Now there is an issue getting the correct size when doing online shopping.

**Comment by danbri** [comment]
Do ecommerce/product sites already have data that makes these distinctions?
