### ISSUE TITLE
Release listing is missing anchor ids since version v1.91

### ISSUE THREAD

**Issue by eliaskaerle** [schemaorg/schemaorg#1918]
The list of schema.org releases (http://schema.org/docs/releases.html) is missing IDs in the table's rows to refere to as anchors.

e.g.: [http://schema.org/docs/releases.html#v3.1](http://schema.org/docs/releases.html#v3.1)

Last time this was addes was version 1.91. 
e.g.: [http://schema.org/docs/releases.html#v1.91](http://schema.org/docs/releases.html#v1.91)

`<tr id="v1.91">`

**Comment by danbri** [comment]
Looks like we have been using `<span id="v3.3"></span>` instead.  It seems to work, e.g. http://schema.org/docs/releases.html#v3.3 - are you having problems?

**Comment by eliaskaerle** [comment]
Works for
* http://schema.org/docs/releases.html#v3.3 (kinda, wrong position)
* http://schema.org/docs/releases.html#v2.2
* ...

works NOT for
* http://schema.org/docs/releases.html#v3.2
* http://schema.org/docs/releases.html#v3.1
* http://schema.org/docs/releases.html#v3.0
