### ISSUE TITLE
Flip the switch to use https

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1925]
@RichardWallis - can you look into this? From https://medium.com/google-cloud/app-engine-transition-your-website-to-https-b280f0bf5147 and similar it seems a change we make in the .yaml files. We need to make sure the 'http' form of the site continues to work (by redirecting).

**Comment by RichardWallis** [comment]
As discussed previously (#716) this, as a simple request is comparatively easy to implement as we already handle various redirects in the user interface, and/or we could have a blanket 301 redirect to https implemented in .yaml files.  However it has some ramifications which need thinking through.

**Current state:**
- The underlying appengine instances for both webschemas and schemaorg operate in both http & https.   
- Directed from the actual domains - schema.org operates in both http & https, webschemas.org only operates in http mode.
  - To fix this, the owner of the webschems.org domain (with access to DNS configuration) needs to follow the instructions that flow from this command ```gcloud domains verify webschemas.org``` See Issue (#1739)
- There are no redirects from http to https on either configuration.
- The canonical URLs for terms shown on the term pages, regardless of method of access are http based.
- The JSON-LD Context file, retrieved by accessing either http://schema.org or https://schem.org requesting content of type ```application/ld+json```, only references  http://schema.org in its "@vocab" and "schema" entries.

**Options to consider:**
- redirect all html [only] traffic to https
  - This would result in the odd situation of a https request resulting in a page which declares a canonical URL in http form.  This is the current state for users typing https into their browsers.
  - Machine-readable versions (xml, turtle, json-ld, csv, etc. plus json-ld context) would still operate from the canonical http URL as well as https.
- Redirect all traffic to https
  - This would result in the odd situation of a https request resulting in a page which declares a canonical URL in http form.
  - Machine-readable calls will all be redirected to https, yet the URLs in the returned data definitions will be http based.
- move to https for all interactions and for term and vocabulary canonical URLs
  - This could create compatibility problems for sites that use the [canonical] schema.org URIs/URLs in the processing of consumed data or in providing supporting tools.
  - This could be partially ameliorated by including a ```sameAs``` triple, referencing the [old] http version, into to [new] https term definitions.

**Comment by danbri** [comment]
Thanks for the detailed notes.  I think we're heading towards option 2.5 with 3.0 later down the line...

**Comment by RichardWallis** [comment]
If we go for full [redirected] https operation, we need to fix the webschemas.org https settings.  @danbri can you organise that anyway.

Until we move to https based canonical URIs it could make sense, as forward compatibility preparation for when we do, to do the the couple of lines of code to add in a ```sameAs``` to the equivalent https URI for the current http based terms.    This could also currently help consumers who are getting both http & https URIs from publishers for Schema terms anyway.
eg.  <http://schema.org/Thing> <http://schema.org/sameAs> <https://schema.org/Thing>

If/when move to https canonical URLs, it would be then very simple to flip that bit of code to do the reverse sameAs for backwards compatibility.

@danbri If you could do the webschemas.org stuff quickly, this flip could potentially make 3.4.

**Comment by VladimirAlexiev** [comment]
> canonical URLs for terms ... are http based

This is the most important consideration. Think of the billions of existing triples using http.
From this point of view, I think treating https as the secondary URL is the right approach.
Cheers!

**Comment by VladimirAlexiev** [comment]
I think `schema:sameAs` is better because it's not a symmetric relation.

**Comment by Aaranged** [comment]
On the flip side (and perhaps counter-intuitively, given the nomenclature) I would add for the benefit of the search engines [a `rel=canonical`](https://support.google.com/webmasters/answer/139066?hl=en) that declares the `https://` version.

E.g. for Book:
`<link rel="canonical" href="https://schema.org/Book" />`

This in recognition of the fact that Google _et al._ are going to prefer `https://` over `http://` anyway (as @RichardWallis notes these are copy and pasted, and when users enter schema.org through a Google search these days that'll almost always be `https://`) , and this will give search engine indexes a clearer idea of what to do when they encounter a `https://` URL.  This won't break anything for any integrator, but will make things clearer for the search engines.

**Comment by chaals** [comment]
+1 to doing this, FWIW - the plan is seeming about right (I love it when a plan comes close to fruition but hasn't yet revealed the bit we didn't anticipate)

**Comment by RichardWallis** [comment]
Released in V3.4

**Comment by thadguidry** [comment]
@danbri what do you want to do about the equivalent mappings in Wikidata ?  Leave them as http:// for provenance and "good citizen" ?  Additionally add https:// as well, just in case ?  Let me know either way.

**Comment by RichardWallis** [comment]
Good question - are the mappings to the definition pages (https) or canonical URIs (http)?

**Comment by thadguidry** [comment]
http

**Comment by RichardWallis** [comment]
In that case they are mapping to the canonical URI for the term, as you might find in a triple.  Not the documentation page.

My 2 cents is - leave as is.

@danbri ?

**Comment by thadguidry** [comment]
Yeah, I'd leave as-is for provenance.  But is it worthwhile to add https also ?  We can have more than 1 equivalent mapping.... 1 with http and 1 with https... Wikidata clients can then choose which one they will use, or can even do a SPARQL filter on for that matter.

**Comment by danbri** [comment]
As-is for now. We should publish a Python script that turns our RDF dumps into an https: flavour, for people who want to use RDF tooling and canonicalize to the https variant.

**Comment by RichardWallis** [comment]
@danbri we could do that, on the publicly shared presumption that in the none to distant future we will move the vocabulary's canonical URIs to https.  I am wondering however if whilst helping some it would introduce confusion for others.

The latest's dumps include sameAs statements between http & https canonical URIs - I think we should see how that is used etc. before making a significant move here.
