### ISSUE TITLE
How to declare 2 sets of openingHours on the same day

### ISSUE THREAD

**Issue by cbejensen** [schemaorg/schemaorg#1927]
If a business is open on Sundays from 7am - 11pm and 1pm - 5pm, how would you write this? Would you just have to declare the day twice like this?

`"openingHours": ["Su 7:00-11:00", "Su 13:00-17:00"]`

Or is there a better way?

**Comment by magico** [comment]
Yes, that's correct.

**Comment by cbejensen** [comment]
Thanks!
