### ISSUE TITLE
'review' and 'aggregateRating' omit Event, Brand, Service

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#193]
http://schema.org/review
http://schema.org/aggregateRating
http://schema.org/Event

1. it seems perfectly legit to review and rate an Event (e.g. theatre performance, concert etc.).
2. reviews can be expressed using itemReviewed, but not via 'review', which is just silly. See also https://github.com/rvguha/schemaorg/issues/161

**Comment by thadguidry** [comment]
Ah yes, we definitely need this.

Broadway Musicals and Theater (Playbill.com and its magazine) are good examples. (Note that Playbill reviews the individual production's performance itself....NOT the written play itself, which is a review of the CreativeWork)

**Comment by vholland** [comment]
Can we also add Brand and Service? It seems legitimate to have reviews for these types as well.

**Comment by mfhepp** [comment]
+1

**Comment by thadguidry** [comment]
-1 for Brand....I think its too high level.  Opinions count but...oh wait...just thought of my buddy Spencer over at State.com ... yeah, they probably would like something for Brand...although collecting facts and having hard supporting evidence of a 3 or 4 aggregateRating on Apple seems a bit of a stretch. :) In all seriousness. 

OK,
+1 for adding Brand and Service.

**Comment by DDeering** [comment]
+1

Great idea to allow reviews/ratings for Brand and Service
