### ISSUE TITLE
Extend the range of contentRating to include Rating

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1935]
Currently http://schema.org/contentRating expects a Text value like 'MPAA PG-13'. It would be nice to follow the example of http://schema.org/starRating and extend the range of contentRating to allow for a http://schema.org/Rating. That way we could be explicit about the rating organization and the rating value.

**Comment by danbri** [comment]
Good point. We should do this. /cc @tmarshbing @tilid @scor @rvguha @nicolastorzec

**Comment by Aaranged** [comment]
+1!  Just to provide a use case both the South African [Film & Publication Board](http://www.fpb.org.za/) and the [British Board of Film Classification](https://bbfc.co.uk/) have the content rating "18".  This value is obviously a lot more meaningful if it can be connected to the originating rating organization.

**Comment by danbri** [comment]
Done. This didn't seem to be one for standing upon ceremony...
