### ISSUE TITLE
Is it possible to provide rRDF schema standard format for the structure description of concept?

### ISSUE THREAD

**Issue by wxlfrank** [schemaorg/schemaorg#1936]
Right now in the schema.org website, the structure information of concepts is presented as HTML table.
For example, for the concept, Person, its field and relationship are presented as 
![image](https://user-images.githubusercontent.com/10045917/41091915-fb393e3c-6a47-11e8-8096-80cb03b544ef.png)
Is it possible to provide the structure information in an RDF schema standard format?

**Comment by RichardWallis** [comment]
Details on how to get machine readable formats for individual terms, or in downloadable files for all or parts of the vocabulary are available on the [developers page](http://schema.org/docs/developers.html).

**Comment by thadguidry** [comment]
@RichardWallis I've created a PR https://github.com/schemaorg/schemaorg/pull/1937 that hopefully provides more clarity on what is available, right on the main Schemas page.

**Comment by wxlfrank** [comment]
Thank you very much.

Just a suggestion, in the machine-readable format files, you use schema specific properties, like schema:domainincludes. Hope such properties can be replaced with owl or rdfs properties for better reusage in the future.
