### ISSUE TITLE
Flight type is missing documentation

### ISSUE THREAD

**Issue by sumutcan** [schemaorg/schemaorg#1938]
![image](https://user-images.githubusercontent.com/1269403/41103447-79d55e08-6a69-11e8-9721-9cdedf998182.png)

Hi all, 
When I visit the page for the type Flight, I cannot see any properties for the type. Is something wrong with the page rendering?

Greetings
Umut

**Comment by RichardWallis** [comment]
Hi there - thanks for the alert.  

This instance now fixed.

It is an occasional problem, with caching of page rendering, which we hope to fix fully in a later release of Schema.org.
