### ISSUE TITLE
Request for schema.org/Product returns "defined in an extension" page

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#1939]
A request for [http://schema.org/Product](http://schema.org/Product) returns the message:

**Schema.org Extensions**
The term 'Product' is not in the schema.org core vocabulary, but is defined in an extension:
- core: Product

![s-product](https://user-images.githubusercontent.com/1033730/41112884-fffd5da8-6a34-11e8-96b6-7c151b843fd4.png)

Obviously a request for this URL should instead return the actual Product page.

**Comment by magico** [comment]
Is that still the case? I'm seeing the expected Product type and all its properties.

**Comment by christo26** [comment]
Yup. https://schema.org/Product

**Comment by Aaranged** [comment]
Must have been a temporary bug - now resolving correctly for me.  Closing.
