### ISSUE TITLE
Add landArea property to AdministrativeArea

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1940]
There currently is no way to state the land area of a City, State, or Country. We should add a property ```landArea``` to ```AdministrativeArea``` with a range of ```QuantitativeValue```.

**Comment by danbri** [comment]
And what does it mean?

eg Is there a standard definition in common use that works for mountainous
or other less flat areas, or at least provides guidance?

Doesn't need to be superprecise GIS. Maybe "typically horizontal component,
wrt mountainous areas" is enough.

**Comment by thadguidry** [comment]
@danbri typically just "surface area" works well enough.  https://www.wikidata.org/wiki/Property:P2046

**Comment by vholland** [comment]
I try a drive-by suggestion and I get all these questions. ;-)

@thadguidry I will take a look.

**Comment by thadguidry** [comment]
@vholland Hey, at least this is part of your job ! :)  Some of us do this for free ! :) Don't you feel extra special now, lolol ?

**Comment by danbri** [comment]
The original usecase for this was apparently DataCommons.org, who have been
making use of it

https://browser.datacommons.org/kg?dcid=landArea

it seems broadly useful
