### ISSUE TITLE
An NGO can also be seen as a NewsMediaOrganisation

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/schemaorg#1942]
NGO's often report on spesific matters, sometimes even including news articles and interviews within a certain theme of subjects.

For example, I am currently working with a NGO which will focus on (very losely translated) "ethical decisions in recent matters". They will be writing background news articles on each of the subjects they cover, but the subjects they cover on can vary widely.

The issue:
Thet would be best described as an NGO, since they do not only report on matters, but also organise debates and public awareness campaigns. Yet they are also a NewsMediaOrginisation, since they do background research on those matters and write articles on them.

NewsMediaOrganisation might be too explicit. There are many organisations which report news along with other activities which also define their organisation. Reporting news is not something exclusively done by a certain type of organisation, and thus cannot be defined as such.

**Comment by Meteor0id** [comment]
I think what we really need is a name for organisations which do not fall in any of the other categories, and which DO exclusively report on news.
The change I am proposing is to rename this group so it is clrealy only meant for orginisations which do not have other main acitvities besides reporting news.

**Comment by danbri** [comment]
Schema.org types are not exclusive, you can use several on a single thing, where appropriate. For example, something might be both a Book and also a Product. Or it might be an NGO and also a NewsMediaOrganization. Does that help at all?

**Comment by Meteor0id** [comment]
It would help, if schema.org was clear about this within the official documentation. Web-crawlers I checked still only accept one type. Schema.org should be more explicit about this, stating that at least for proper implementation, multiple types should be considered valid.

This lack of exlicit standardization is something I have seen a lot in the schema.org vocab, this ticket only comments on one such issue.


Besides the above, I doubt that crawlers for example will find a way to make good use of multiple types. Where possible, we should avoid the need for an organisation to call itself multiple things. Therefore, with respect to NewsMediaOrganisation, I recommand rephrasing the type to more explicitly apply only to organisations whos activity is REPORTING news.
I am lookign for a simulair distinction as was proposedto enhance on news article:
ReportageNewsArticle, AnalysisNewsArticle, OpinionNewsArticle, ReviewNewsArticle, BackgroundNewsArticle, AdvertiserContentArticle, SatiricalArticle

News is to broad a concept. Therefore NewsOrganisation is also too braod a concept. Let's try to split that up into more explicit types, and depreciate NewsOrganisation type itself.

**Comment by danbri** [comment]
> It would help, if schema.org was clear about this within the official documentation. 

https://schema.org/docs/datamodel.html 

* We have a set of types, arranged in a multiple inheritance hierarchy where each type may be a sub-class of multiple types.

> This lack of explicit standardization is something I have seen a lot in the schema.org vocab, this ticket only comments on one such issue.

The above seems pretty clear, regarding multiple types. 

> Web-crawlers I checked still only accept one type

I was involved with fixing Google's support for multiple types. Here's [an example](https://search.google.com/structured-data/testing-tool?url=https://gist.githubusercontent.com/danbri/96584379cdc90ccf632f5410083ddb15/raw/cf21f203a02af4a2efbb433b9635214e29705f48/gistfile1.txt) that works, and shows the JSON-LD syntax:

```
{
"@context": "http://schema.org/",
 "@type": [ "Book", "product" ],
 "isbn": "1234",
 "gtin8": "5678",
 "name": "A thing that is a product and a book"
 }
```

Note that we can also have types (like LocalBusiness) which have multiple independent supertypes declared within schema.org, in addition to this more free-form mixing.

> I doubt that crawlers for example will find a way to make good use of multiple types. 

It's more about search engines and similar making products/features than crawling. The value of multiple types is that it allows us some degree of "mix and match" between areas of the large Schema.org vocabulary. 

News is indeed a broad concept, and your feedback on the NewsMediaOrganization definition is noted. One reason we have it is to provide a hub for several related properties. I shall close out this issue now, but we'll find it here when reviewing NewsMediaOrganization in future.

There is a short document also at https://schema.org/docs/news.html which provides an overview of some other areas that touch on news, notably TV/media.
