### ISSUE TITLE
Properties without domainIncludes & rangeIncludes values

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1944]
_interactionCount_ has no domainIncludes or rangeIncludes values
_exchangeRate_ has no no domainIncludes values

These were identified by tests introduced in PR (#1943)

These need fixing before that PR is merged

**Comment by trypuz** [comment]
@RichardWallis I see two candidates: CurrencyConversionService and/or ExchangeRateSpecification. The last one is in pending.

**Comment by RichardWallis** [comment]
@trypuz  I am not convinced that either of those are valid. 

- [ExchangeRateSpecification](http://pending.schema.org/ExchangeRateSpecification) already has a _currentExchangeRate_ property.

- [CurrencyConversionService](schema.org/CurrencyConversionService) - _A service to convert funds from one currency to another currency_ - would not have a specific _exchangeRate_ associated with it.  An _exchangeRate_ would be associated with an individual currency paired with another.

The more I look at it, I believe _exchangeRate_ is a property that was superseded by _currentExchangeRate_ and hence is surplus to to the requirements of the 'current' vocabulary.

**Comment by RichardWallis** [comment]
Following discussion with some of the proposers of the _exchangeRate_ property I have removed its definition.

@danbri do you have thoughts on _interactionCount_
