### ISSUE TITLE
Browsing items between different extensions generates bad links

### ISSUE THREAD

**Issue by nclu** [schemaorg/schemaorg#1949]
There's no option for "core + current extension" when browsing, for example, fibo.schema.org
When browsing the full hierarchy items from life-science extension appear but lead to error/redirect pages. The links on those pages incorrectly concatenates both extension domain names to create a bad url.

ex. http://fibo.schema.org/MedicalScholarlyArticle
links to http://health-lifesci.fibo.schema.org/MedicalScholarlyArticle

**Comment by RichardWallis** [comment]
This [incorrect] behaviour stems from two issues:
- The DNS setup should not have enabled the subdomain fibo.schema.org as there is not currently an enabled  extension 'fibo'.

- When the process _does_ receive a request for a subdomain URL, that does not map to an enabled extension, it should gracefully handle it by redirecting to the base domain 'schema.org'  .
  -  The internal redirect logic between extensions and the core, assumes it is operating with valid extension based URLs

**Comment by RichardWallis** [comment]
Released in V3.4
