### ISSUE TITLE
Corrections-related vocabulary proposed in collaboration with Trust Project

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1950]
This picks up a single theme from the larger issue #1688 

From https://github.com/schemaorg/schemaorg/issues/1688#issuecomment-367222874

* That we add a new property "correction", whose value is 
* a new subtype of Comment called "CorrectionComment"; 
* also "correctedWork" applying to that type, to allow the relevant CreativeWork to be indicated.

```
{  
   "@context": "http://schema.org",
   "@type":"ReportageNewsArticle",
   "url":"https://www.nytimes.com/2018/01/23/movies/oscars-snubs-surprises.html",
   "publisher":"...",
   "datePublished":"...",
   "dateModified":"...",
   "Headline":"...",
   "mainEntityOfPage":"https://www.nytimes.com/2018/01/23/movies/oscars-snubs-surprises.html",
   "correction":{  
      "@type":"CorrectionComment",
      "text":"An earlier version of this article misstated the number of times Denzel Washington has been nominated for an Oscar. His nod for 'Roman J. Israel, Esq.' brings the total to nine, not eight.",
      "datePublished":"2018-01-23",
      "correctedWork":"https://www.nytimes.com/2018/01/23/movies/oscars-snubs-surprises.html"
   }
}
```

**Comment by DamonHD** [comment]
Would it be helpful to lift my example CorrectionComment for the docs, though I accept that I may not be quite matching the intended purpose?

http://www.earth.org.uk/holiday-low-carbon.html#Air
