### ISSUE TITLE
SportsEvent should also use the "sport" property

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1951]
Currently, to say a World Cup game is a football/soccer game, one must list at least one team or competitor and then use the http://schema.org/sport property there. It would be nice to support the simplified case of:

```
{
  "@context": "http://schema.org/",
  "@type": "SportsEvent",
  "name": "World Cup 2018",
  "sport": "https://www.wikidata.org/wiki/Q2736",
  "startDate": "2018-06-14",
  "endDate": "2018-07-15"
}
```

To support this, we would need to add https://schema.org/SportsEvent to the domain.

**Comment by danbri** [comment]
seems useful, any objections?

**Comment by RichardWallis** [comment]
+1

**Comment by acumon** [comment]
How about making the type of the sport property Thing instead of URL so that one can use the name property? the URL can also be passed by the "url" or "same_as" property.

**Comment by vholland** [comment]
I submitted PR #2400 for the immediate change and suggested a new type in issue #2401

**Comment by vholland** [comment]
Included in schema.org 6.0.
