### ISSUE TITLE
Rdfs definition and vocab

### ISSUE THREAD

**Issue by spidfire** [schemaorg/schemaorg#1952]
I was looking at the page: http://schema.org/name
And I found this in the source code:
```
<div id="mainContent" vocab="http://schema.org/" typeof="rdfs:Property" resource="http://schema.org/name">
...
<h1 property="rdfs:label" class="page-title">name</h1>
...
<div property="rdfs:comment">The name of the item.</div>
```

but I couldn't find a reference to the rdfs prefix(http://www.w3.org/2000/01/rdf-schema\#) and is the vocab not overcomplete here?

**Comment by RichardWallis** [comment]
From  https://www.w3.org/2011/rdfa-context/rdfa-1.1 : 

_This list of predefined prefixes have been defined for RDFa as an “initial context”: essentially, RDFa users can use these prefixes without having the obligation of defining the prefixes in the HTML code._

Amongst the comprehensive list is thi

```rdfs      http://www.w3.org/2000/01/rdf-schema#     RDF Schema      RDF Semantics```
