### ISSUE TITLE
Plurals

### ISSUE THREAD

**Issue by westurner** [schemaorg/schemaorg#196]
A method of specifying plurals could be helpful for UI generation:

e.g. 'Course' plural: 'Courses'@en

**Comment by chaals** [comment]
Lots of languages have complications for plurals, including case and gender.
When counting things Russian has one form for 1, 21, 31, 41, … a second one for 2-4, 22-24, 32-34, 42-44, … and a different one for the remaining number of things, or for indeterminate numbers.
I'm not sure a "pluralLabel" is a good idea, and I would rather leave it to SKOS to suffer the pain…

**Comment by westurner** [comment]
Got it. Thank you for clarifying.

**Comment by danbri** [comment]
I don't see us going anywhere with this anytime soon, so I'll close it. Don't let that stop folks discussing things here, though...
