### ISSUE TITLE
Website missing properties for certain types

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1960]
It looks like the website is missing properties for some types. For example, http://schema.org/MusicComposition lists no properties, but the examples show https://schema.org/lyrics and https://schema.org/composer. Those pages list them as properties for MusicComposition.

**Comment by danbri** [comment]
ping @RichardWallis - can you take a look?

**Comment by RichardWallis** [comment]
Issue fixed - looks like our caching problem has not fully been resolved.

**Comment by danbri** [comment]
Can you make diagnosis a priority? Is there a tracking issue?
