### ISSUE TITLE
[Proposal] Add @Person.workedFor

### ISSUE THREAD

**Issue by probablyup** [schemaorg/schemaorg#1961]
This would work similarly to `@Person.alumniOf` but only take an `@Organization`. This is a complimentary property to `@Person.worksFor` to allow for a richer history of the `@Person`'s past work experience.

**Comment by hubick** [comment]
How about adding an @EmploymentEvent subtype of @BusinessEvent , and then just use @Person.performerIn (as "participant")?

Then you can use @Event.organizer for the employer and all their info, plus it then automatically gives you all the other stuff you'll want like @Event.startDate , @Event.endDate , @Event.subEvent , etc.

**Comment by vholland** [comment]
This is one of the use cases for Role. It would look something like:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Person",
  "name": "Jane Doe",
  "worksFor": {
    "@type": "Role",
    "worksFor": {
      "@type": "Organization",
      "name": "ACME Products"
    },
    "startDate": "2018",
    "endDate": "2019",
    "roleName": "Q&A Specialist"
  }
}
</script>
```

**Comment by jhabdas** [comment]
I see `worksFor` is already there but it strikes me as less useful than something like `employedBy`, which more closely matches `alumniOf` and connotes an employee/employer relationship.

**Comment by jhabdas** [comment]
Perhaps this discussion could be merged with https://github.com/schemaorg/schemaorg/issues/1698
