### ISSUE TITLE
[Proposal] Add @Season.seasonNumber

### ISSUE THREAD

**Issue by pheyvaer** [schemaorg/schemaorg#1962]
At the moment it's not possible to state what the order is of the different seasons of a single show, if we don't consider RDF lists. Therefore, I would suggest to add the property `seasonNumber`: position of the season within an ordered group of seasons. This is analogue to [episodeNumber](https://schema.org/episodeNumber).

**Comment by vholland** [comment]
I think this is the caching bug popping up again as it is available if you view https://schema.org/seasonNumber.

@RichardWallis

**Comment by pheyvaer** [comment]
Yes indeed. I can see it now. Thanks!
