### ISSUE TITLE
file:///Users/wallisr/ in Vocabulary definition

### ISSUE THREAD

**Issue by davidglezz** [schemaorg/schemaorg#1965]
I found these in https://schema.org/version/3.4/schema.jsonld and I think could be a mistake:

```
{
  "@id": "file:///Users/wallisr/Development/Schema/master/schemaorg/data/schema.rdfa",
  "http://purl.org/dc/terms/source": [
    {
      "@id": "http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#IIT-CNR.it"
    },
    {
      "@id": "http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#Tourism"
    }
  ]
},
```

Affected documents: data/releases/3.4/...

https://github.com/schemaorg/schemaorg/search?q=file%3A%2F%2F%2FUsers%2Fwallisr%2FDevelopment%2FSchema%2Fmaster%2Fschemaorg%2Fdata%2Fschema.rdfa&unscoped_q=file%3A%2F%2F%2FUsers%2Fwallisr%2FDevelopment%2FSchema%2Fmaster%2Fschemaorg%2Fdata%2Fschema.rdfa

**Comment by RichardWallis** [comment]
This is not an issue that was introduced in V3.4 see this from V3.3
```
    {
      "@id": "file:///Users/danbri/sdo/official/schemaorg/data/schema.rdfa",
      "http://purl.org/dc/terms/source": [
        {
          "@id": "http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#IIT-CNR.it"
        },
        {
          "@id": "http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#Tourism"
        }
      ]
    },
```
Still needs fixing though.
Should not effect import of vocabulary definition from these files, except for the addition of a few  surplus housekeeping triples.

Can be fixed at next convenient release - no need for an urgent patch.

/cc @danbri
