### ISSUE TITLE
question: example of imageObject with caption, name and description

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/schemaorg#1966]
I find the available properties for imageObject https://schema.org/ImageObject have a somewhat confusing overlap.

The microdata example shows use of the property name (whcih is not mentioned as an inhearited property of thing!)

But if an image has a name, and a description, and a caption.. which is which?!
Obviously in most cases one would not use all three on the same imageObject, yest to understand the precise difference and pikc the right one, I aks for an example of an imageObject having all three of these properties.

In my case, I am working on images wiht text overlay and a caption below them. The overlaying text is a bit long, so I would say that qualifies as a description. The text underneath the image however could both be called the name of the image and the caption. At first guess I would say it's below the image so it is a caption, yet than this object has no name. Search engines might not index my imageObject if it has no name.

Or maybe support for the property name on an imageObejct should be dropped?

**Comment by Meteor0id** [comment]
Also a typical schema.org issue is that <img /> takes multiple attributes worth marking, but I can give it only one property. Alt, src and title all say something about an image whcih might be of value when indexing a page. Yet I can't define the the title as the itemprop name, the alt as the name and the src as a url.

**Comment by Dataliberate** [comment]
> Obviously in most cases one would not use all three on the same
imageObject

Why not:

name: “President Trump"
caption: "President Trump at his inauguration." (The caption displayed
under the image)
description: “President Donald Trump pictured at his inauguration - January
20 2017”


> is that  takes multiple attributes worth marking, but I can give it only
one property.

Not sure what you mean.

{
    "@type": "ImageObject",
    "name": "President Trump",
    "url": "http://example.com/imgs/123.jpg",
    "alternateName": "Picture of Donald Trump"
}

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by Meteor0id** [comment]
And now with microdata. I am very curious where that name is gonna go.

**Comment by RichardWallis** [comment]
Much depends on the structure of your html, but here are a few potential options:

```
<div itemscope itemtype="http://schema.org/ImageObject">
  <h3 itemprop="caption">Picture of Donald Trump</h3>
  <img src="prestrump.jpg" alt="Picture of Donald Trump" itemprop="contentUrl" />
  <meta itemprop="name" content="Donald Trump">
  <span itemprop="description">President Donald Trump pictured at his inauguration - January 20 2017</span>
</div>
```
```
<div itemscope itemtype="http://schema.org/ImageObject">
  <h2 itemprop="name">Donald Trump</h2>
  <img src="prestrump.jpg" alt="Picture of Donald Trump" itemprop="contentUrl" />
  <h3 itemprop="caption">Picture of Donald Trump</h3>
  <span itemprop="description">President Donald Trump pictured at his inauguration - January 20 2017</span>
</div>
```
```
<div itemscope itemtype="http://schema.org/ImageObject">
  <h2 itemprop="name">Donald Trump</h2>
  <img src="prestrump.jpg" alt="Picture of Donald Trump" itemprop="contentUrl" />
  <meta itemprop="alternateName">Picture of Donald Trump</h3>
  <span itemprop="description">President Donald Trump pictured at his inauguration - January 20 2017</span>
</div>
```

Note I’m using _contentUrl_ instead of _url_ - a more appropriate approach for _ImageObject_ to link to “[Actual bytes of the media object, for example the image file or video file.](https://schema.org/contentUrl)”

~Richard
