### ISSUE TITLE
Add an 'edit examples' link

### ISSUE THREAD

**Issue by westurner** [schemaorg/schemaorg#1972]
As a contributor, it'd be useful to click 'edit' on an/the example(s) in the node detail template.

I added the #examples anchor awhile back and should've/could've also added #examples-jsonld, #examples-microdata.

https://schema.org/CreativeWork#examples

Without an identifier for each example, it's not a good idea to deep link into the examples by ordinal index (e.g. #examples-jsonld-2) if the source order of the examples may change.

What sort of edit on GitHub URIs can we add?

**Comment by RichardWallis** [comment]
@westurner you identify an uncompleted project where each new example has an individual identifier.  (I'm trying to track down the issue that covers it)

For example the following reference can be found in the file ```sdo-tourism-examples.txt```:
```TYPES: #tourism-1 TouristAttraction, isAccessibleForFree```
Resulting in the anchor id ```tourism-1``` being attached to the example when it appears  on the definition pages for _TouristAttraction_ and _isAccessibleForFree_.

Unfortunately as yet the significant efforts to retrospectively apply such identifiers to all previous examples have not been applied.

The current functionally adds default identifiers, as you observe, where no value has been defied.  

You are correct that this status is not desirable and we should look into the possibility of maybe applying such identifiers to all examples retrospectively and then introduce a test to enforce example identifiers.

**Comment by RichardWallis** [comment]
As to providing links to examples using JSON-LD, Microdata, or RDFa, is a good suggestion.
I am not so sure how easy or wise it would be to provide editing links for the examples, for a couple of reasons.

Firstly there is currently no reference within the system as to which examples.txt file is the source for an example.  Of course such management data could be integrated.

Secondly, the vast majority of user of the schema.org site use it for reference not for access to the source definitions.  The default UI may not the most appropriate place to introduce such functionality.

**Comment by danbri** [comment]
I think there's something to do here. Maybe not "edit" exactly, but at least a pointer to the relevant github file (and yes, every example ought to have a stable ID)

**Comment by danbri** [comment]
To @RichardWallis 's point, I agree. Would need to be hidden in main view even on desktop.
