### ISSUE TITLE
New type for ShortStory?

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1976]
I am looking through the bib.schema.org extensions and did not see a type for short stories. It would be good to add this.

@RichardWallis in case I missed the type or previous discussion.

**Comment by danbri** [comment]
Seems to be a close match at Wikidata https://www.wikidata.org/wiki/Q49084 - we should have some best practice to include that in our machine-readable definitions

**Comment by RichardWallis** [comment]
New ShortStory type added - see replacement PR #1979 

As to close match.  We could introduce a default style for referencing this in the rdfs:comment.

My preference would be to add a new recognised triple in the rdfa files indicating the relationship.  

Two options for predicate would be either skos:closeMatch; or we add a new meta.schema.org property with a name such as closeMatch or similarTo (maybe itself defined as being closeMatch to skos:closeMatch) a bit convoluted but more schema like.

Whichever, we could then add a formatted reference to term displays in the same way as we currently do for inverseOf

**Comment by thadguidry** [comment]
I would love it if we could begin displaying relationships against Wikidata.
I am OK with skos:closeMatch since it skips the transitive check.
As far as placement... if we begin down the path of using Meta properties, then it could lend itself well to allowing others to suggest and maintain SKOS alignment of Schema.org as well.  Then again, it could open a can of worms, but those would be very useful little worms...SKOS folks could actually help contribute more Meta and even help us maintain it.

**Comment by RichardWallis** [comment]
Uplifted the discussion about defining and displaying closeMatch relationships with Wikidata into its own issue (#1980).

Please use that issue to discuss that topic, otherwise this thread about a _ShortStory_ may become a long story on a different topic!

**Comment by RichardWallis** [comment]
Implemented in [release 3.5 ](https://schema.org/docs/releases.html#v3.5)

**Comment by westurner** [comment]
Should there be new types for: Screenplay, Speech, SpeechPerformance, AudioRecording?


Is a *Screenplay* a Play?
Is a Play a performance of a *Screenplay*?
(Like an EducationEvent (.assesses, .educationalLevel, .teaches)
or like a CourseInstance (.courseMode, .instructor)?)

Is there yet a way to indicate that a [SpeechPerformance] Event is physically accessible?

How should the typed copy of a ShortStory Manuscript be ?

Could there be an *AudioRecording* (?) which includes MusicRecording and a SpeechPerformance of a Speech TextDigitalDocument & Speech PresentationDigitalDocument (for a teleprompter) which was originally a handwritten Manuscript but is now a deck and speaker notes and timings and then one or more recordings thereof with translations of the subtitles?

**Comment by westurner** [comment]
From https://schema.org/CreativeWorkSeries :

> Specific subtypes are available for describing [TVSeries](https://schema.org/TVSeries), [RadioSeries](https://schema.org/RadioSeries), [MovieSeries](https://schema.org/MovieSeries), [BookSeries](https://schema.org/BookSeries), [Periodical](https://schema.org/Periodical) and [VideoGameSeries](https://schema.org/VideoGameSeries). In each case, the [hasPart](https://schema.org/hasPart) / [isPartOf](https://schema.org/isPartOf) properties can be used to relate the CreativeWorkSeries to its parts. The general CreativeWorkSeries type serves largely just to organize these more specific and practical subtypes.
