### ISSUE TITLE
DOC,BUG: schemaorg.owl OWL does not validate

### ISSUE THREAD

**Issue by westurner** [schemaorg/schemaorg#198]
schema.org OWL ontology fails to validate:

* http://schema.org/docs/schemaorg.owl
* https://raw.githubusercontent.com/rvguha/schemaorg/master/docs/schemaorg.owl
* https://github.com/rvguha/schemaorg/commits/master/docs/schemaorg.owl

Validators:

1. http://mowl-power.cs.man.ac.uk:8080/validator/

2. ~ RDFlib rdfpipe (`pip install rdflib`)

```bash
$ rdfpipe -i xml -o xml https://raw.githubusercontent.com/rvguha/schemaorg/master/docs/schemaorg.owl
Traceback (most recent call last):
# [ ... ]
"../lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: https://raw.githubusercontent.com/rvguha/schemaorg/master/docs/schemaorg.owl:1:81: mismatched tag
```

SeeAlso: #197 "BLD: Always generate RDF, OWL, JSON-LD"

**Comment by danbri** [comment]
@westurner we already link to the main URL, hyperlinked as "See also TopBraid's version.". I'd rather leave it to their page to track specific variants, formats etc in case they change.

**Comment by westurner** [comment]
Thanks. Closing.

seeAlso: "Link to TopBraid Schema.org OWL versions #62"

**Comment by boanuge** [comment]
Hi,
To be clear, does "https://github.com/schemaorg/schemaorg/blob/master/docs/schemaorg.owl"
not work any more?
(I also failed to import the file "schemaorg.owl" using JENA library or Protege.
But "http://topbraid.org/schema/schema.rdf" worked.)

I hope there is an official(?) OWL working version in http://schema.org site.
Any comments are welcome.
And thank you very much in advance.

Kind regards,

**Comment by danbri** [comment]
The file schemaorg.owl (as explained in http://schema.org/docs/datamodel.html ) is obsolete, and not integrated with the site. I believe that the discussion above ought to make that reasonable clear too.

In general, schema.org might work from an 'OWL Full' perspective, but we are not attempting to fit within the OWL DL family of modeling restrictions. @HolgerKnublauch may want to comment on the TopQuadrant OWL-flavored version.

**Comment by HolgerKnublauch** [comment]
Thanks for keeping the reference to my version in. I admit I am not always updating it - this isn't automated. I hope to provide a SHACL version in the future too, maybe for FPWD.
