### ISSUE TITLE
Schema Address

### ISSUE THREAD

**Issue by lisabroadhead** [schemaorg/schemaorg#1981]
I was just wondering what best practice is. Should the telephone number and URL go inside the address tag, or out? Below is the code,

 {
 	"@context":"https:\/\/schema.org",
 	"@type":"LocalBusiness",
 	"@id":"#company",
 	"name":"Nifty Marketing",
 	"image":"https:\/\/http-assets.s3.amazonaws.com\/template\/logo-34710?102311261",
 	"address":{
 		"@type":"PostalAddress",
 		"streetAddress":"1340 Overland Avenue",
 		"addressLocality":"Burley",
 		"addressRegion":"ID",
 		"postalCode":"83318",
 		"telephone":"(800) 381-4959",
 		"url":"niftymarketing.com"
 	},
 	"aggregateRating":{
 		"@type":"AggregateRating",
 		"reviewCount":6,
 		"ratingValue":4.8
 	}
 } 

![screen shot 2018-07-09 at 1 59 32 pm](https://user-images.githubusercontent.com/37422388/42472944-58e751a8-8380-11e8-80d1-58369c946453.png)

Schema.org mark up has it outside the address: https://schema.org/address

But if you look under the documentation of Schema.org PostalAddress - https://schema.org/PostalAddress -the documentation it shows you can have telephone and URL inside the address tag.

What is best practice??

**Comment by thadguidry** [comment]
Scroll down and look at Example 8 and click on the JSON-LD tab https://schema.org/PostalAddress

Its shows that telephone and URL are _not_ part of an address.

**Comment by lisabroadhead** [comment]
Thank you for your comment was very helpful! And I updated my original post to include a screenshot of the code.

**Comment by Download** [comment]
I believe `url` is actually a property of `thing`, so *every* type has a `url` field.

Schema.org is IOT-ready!
