### ISSUE TITLE
Include property "partOfSeries" for all types of "Article"

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/schemaorg#1982]
We write articles wich are part of a series on a spesific topic. There are no seasons or episodes invloved, but we could call the group of articles ona spesific topic a series.

Thea series also has no start or end date, but has a topic as its binding factor. ("about", "description" or "name" will likely be enough to describe the series)

Articles wihtin the series might also be follow ups on previous articles, or might stand alone within the series.

"a series" in this sense can be synonymous to "a topic". The added value of regarding it as a dort of series is that they can be grouped together, and do not only hang together by simulair "about".

Alternaticely, we may introduce a whole new type named "Topic". A topic has subjects below it, a subject has articles below it. Or an article can be an immidiate child of a topic.

**Comment by RichardWallis** [comment]
I would use [CreativeWorkSeries](https://schema.org/CreativeWorkSeries) for this.  It gives you _description_, _about_ etc., and only if you need it startDate, endDate, & issn.

**Comment by Meteor0id** [comment]
yes, that gives me a way to describe the series itself, but I have no way of describing the parts of this series, since the propery "partOfSeries" currently only applies to "Clip
CreativeWorkSeason
Episode"

My proposal is to include the property partOfSeries for any Article type. Additionally we may discus coming up with seperate types, but just having this existing property apply to articles will solve the issue in a relatively simple way.

**Comment by Dataliberate** [comment]
You can just use *isPartOf* to indicate that any *CreativeWork*, or
subtype, is part of another *CreativeWork*, or subtype.

As CreativeWorkSeries is a subtype of *CreativeWork* and so are the
articles in the series, you have the full power and flexibility of isPartOf
and hasPart to build your relationships.

Note. *partOfSeries* is a sub property of *isPartOf*  - just a
specialisation of the functionality that was introduced prior to
some rationalisation around series that occurred a while back.  As you can
see with the capabilities of isPartOf and hasPart, not totally required.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by Meteor0id** [comment]
This is not in line with the title, but it would be a bit odd to open a new ticket:

There is no "partOfSeries" or "partOf" for an Event. While theater events do sometimes occur as series. Not talking cinnema, which is a whole thing on its own, but I am talking about a series of events realted to eachother, as part of a tour for example.

**Comment by Meteor0id** [comment]
Should also elaborate taht an event might be part of a series consisting not only of events but also of other creativeworks such as articles. A series as a topic may contain articles AND events. Something eventSeries also does not cover.

**Comment by RichardWallis** [comment]
Firstly, see description of [EventSeries](https://pending.schema.org/EventSeries): "_A series of Events. Included events can relate with the series using the superEvent property._" - and the inverse _subEvent_ is available.

This highlights a defect in the [example](https://pending.schema.org/EventSeries#examples) where _hasPart_ has been used, which is not available for the EventSeries Type.  I will raise a separate issue to fix that.

Secondly,  a _CreativeWork_, such as an _Article_, is not an Event, it may be what an Event is [about](https://schema.org/about), or be the CreativeWork that is the [workFeatured](https://schema.org/workFeatured) or [workPerformed](https://schema.org/workPerformed) at an _Event_.

There may be situations where something could be described as **both** a _CreativeWork_ and an _Event_, then it should be declared as such: ```"@type": ["CreativeWork","Event"]``` . If that something was in an EventSeries, you would use _subEvent_ / _superEvent_ to relate it.
