### ISSUE TITLE
Can content contain a url? Yandex sais not, schema.org sais yes.

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/schemaorg#1985]
Yandex validators throws errors at meta elements iwt a content containing a url. However this is clearly shown as an example on schema.org for example here (microdata example): https://schema.org/isLiveBroadcast

Is Yandex implementing schema wrong?

**Comment by unor** [comment]
The example is invalid.

If the value is a URL, `link` (instead of `meta`) must be used:

```html
<link itemprop="isLiveBroadcast" href="http://schema.org/True" />
```

**Comment by Meteor0id** [comment]
Wait hold on, which are correct and which are not?

<meta itemprop="something" content="true" />
<meta itemprop="something" content="True" />
<link itemprop="something" href="http://schema.org/true" />
<link itemprop="something" href="http://schema.org/True" />

Unless I remember poorly, I have seen examples differin on this all over the place.

https://schema.org/isAccessibleForFree
https://schema.org/publicAccess

Things like these make me think of schema as a very unprofessional effort. You simply dont push faulty examples.

**Comment by Meteor0id** [comment]
For anyone wondering: I would go with `<link itemprop="something" href="http://schema.org/True" /> and <link itemprop="something" href="http://schema.org/False" />`

**Comment by Meteor0id** [comment]
Yandex:
`WARNING: the value "" in the field publicAccess is an invalid value for the boolean`
when using:
`<link itemprop="publicAccess" href="http://schema.org/True" />`

**Comment by unor** [comment]
If you want to use a Text value (instead of a URL value), you can use the `meta` element, e.g.:

```html
<meta itemprop="isLiveBroadcast" content="True" />
```

Schema.org is liberal in what kind of values a property can have. Whether consumers support/recognize all the possibilities is a different question; it’s their choice.

**Comment by Meteor0id** [comment]
Open graph does not recognise <link property="og:url" href="http://www.imdb.com/title/tt0117500/" /> but does expect <meta property="og:url" content="http://www.imdb.com/title/tt0117500/" />

Yet here we have schema.org stating exactly the opposite: <meta itemprop="url" content="http://www.imdb.com/title/tt0117500/" /> is invalid and <link itemprop="url" href="http://www.imdb.com/title/tt0117500/" /> is valid.

Come on!
Liberal is one thing, but there would be no internet if it wasn't for consensus. This way schema.org is not adding to the world wide web but spreading confusion.

The same goes for text values vs url values. Schema can't leave people haning on that and say pick one at random. If it's gonna be like that it's worthless.

Pick a side for the use of url vs text values, and pick a side for referencing links with link elemnts or meta elements.

**Comment by unor** [comment]
**Re. `meta`/`link`:** The requirement doesn’t come from Schema.org, [it comes from HTML](https://stackoverflow.com/a/24659620/1591669). Which means that the documentation for the Open Graph Protocol [suggests to use invalid HTML+RDFa](https://stackoverflow.com/a/41916286/1591669).

**Re. values:** The list "Values expected to be one of these types" on each property page suggests what kind of values authors *should* provide. If it says `Boolean`, my understanding is that it’s expected to be a URL value. See also #130:

> There's also the issue that such values very often show up as literals in data, even if they should be URIs. Could either try to fix documentation to encourage URI use, or document this as an 'expect the unexpected' pattern.

**Comment by Meteor0id** [comment]
Thank you for putting up with me Unor.

I request the devs of schema.org add a clear statement about both these issues on the site:

- Clearly state at every example with a URI value that the proper way to do so is using a link, not meta element, and thus, those saying otherwise are at fault. (such as the official site for open graph currently!)
Also communicate to implementors to chekc their implementation for this.

- Also add a clear statement on proper use of booleans. It is not ok to have one organisation expect URI's and have another expect text. A choise must be made so there is a decision to reference to. Personally I favor being explicit about it, and only allowing URI's as valid use of schema vocab.
The same goes for the use of DateTime by the way. Clear examples are needed, and there should not be multiple ways to state a DataTime (cause at this time it is unclear wether this should be done using content="" and datetime="" or using datetime="" alone.


Devs just can't expect people to start using scheam.org more braodly if every validator or indexer can pick his own flavour for  these kind of basic properties.

**Comment by RichardWallis** [comment]
Implemented
