### ISSUE TITLE
Duplicate definition of 'license' and other terms in json-ld context file

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1986]
Raised via schemaorg mailing list [by Tim Cole](https://lists.w3.org/Archives/Public/public-schemaorg/2018Jun/0199.html):

> What is the intended meaning of the term "license" in the context of a schema.org description serialized as json-ld? The term is defined twice in https://schema.org/docs/jsonldcontext.json (also if you retrieve context document from http://schema.org or https://schema.org using content negotiation).
>  
> Lines 22-25:
> ...
>         "ical": "http://www.w3.org/2002/12/cal/icaltzd#",
>         "license": "http://www.w3.org/1999/xhtml/vocab#license",
>         "ma": "http://www.w3.org/ns/ma-ont#",
> ...
>  
> Lines 1748-50
> ...
>         "letterer": { "@id": "schema:letterer"},
>         "license": { "@id": "schema:license", "@type": "@id"},
>         "line": { "@id": "schema:line"},
> ...
>  
> Since the schema:license definition appears later in the context document, I assume it wins over the definition linking to the xhtml vocabulary, but perhaps it would be a good idea to clean this up in the schema.org context document? Unless this is unavoidable in how context document is being generated. So in my json-ld I would use the key "license" to refer to schema:license property and the key "xhv:license" to refer to license property as defined in xhtml vocabulary? (Semantic difference is minimal, so I'm probably being pedantic.)
> 

The definition of ```"license": "http://www.w3.org/1999/xhtml/vocab#license",``` seems unnecessary so could be easily dropped.

Tim also raises:

> Note, there are a number of other duplicated keys in the schema.org context document besides license, but none of them are contradictory (and so less chance of misinterpretation). E.g., the definition of the prefix "org" (lines 27 & 28) and the definitions of many terms from the Health and Life Sciences Extension (health-lifesci) such as  Nursing (lines 684-85), SurgicalProcedure (lines 979-980), etc. Less of a concern, but would it be possible to clean these up since (if I'm remembering correctly) duplicated keys violate a SHOULD in the JSON standard and some parsers object to duplicated keys?

This looks likely to be something to do with Enumeration values that have more than one super-type.  Fix required

**Comment by danbri** [comment]
Richard - could you add a unit test so that we don't trip ourselves up here again?

**Comment by RichardWallis** [comment]
Will do when the current trip hazard is fixed.

**Comment by RichardWallis** [comment]
Fixed in PR #2378
