### ISSUE TITLE
Question: proper use of property events

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/schemaorg#1987]
```

(itemscope is NGO)

<ul itemprop="events">
									<li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent"><a itemprop="url" href="" target="_self"><time itemprop="doorTime" itemscope itemtype="http://schema.org/DataTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time><span itemprop="name" class="event_name">test item</span><span itemprop="partOf" itemscope itemtype="http://schema.org/CreativeWorkSeries" class="event_theme">Digitale Rechten<meta itemprop="url" content="link naar thema overzicht hier" /></span>
									<!--<span class="event_access">Vrije toegang</span>--></a></li>
									<li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent"><a itemprop="url" href="" target="_self"><time itemprop="doorTime" itemscope itemtype="http://schema.org/DataTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time><span itemprop="name" class="event_name">een aanzienlijk langer test item want dit kan voorkomen dus moet getest worden</span><span itemprop="partOf" itemscope itemtype="http://schema.org/CreativeWorkSeries" class="event_theme">Digitale Rechten<meta itemprop="url" content="link naar thema overzicht hier" /></span>
									<!--<span class="event_access">Vrije toegang</span>--></a></li>
									<li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent"><a itemprop="url" href="" target="_self"><time itemprop="doorTime" itemscope itemtype="http://schema.org/DataTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time><span itemprop="name" class="event_name">test item</span><span itemprop="partOf" itemscope itemtype="http://schema.org/CreativeWorkSeries" class="event_theme">Digitale Rechten<meta itemprop="url" content="link naar thema overzicht hier" /></span>
									<!--<span class="event_access">Vrije toegang</span>--></a></li>
								</ul>
```

Events are quite confusing. There is a property events, a property event and a type Event.
Googles validator seems to choke on the example above in a weird way.

Some examples are dated as can be seen by the occurence of itemscope="" , but that is besides the point.

I am looking for a way to mark up a list of coming events current events and past events. The events are part of the activities of an organisation, and thus stand in the context of the organisation.

The events might not all be part of series. This is simply a list of upcoming events.

**Comment by Dataliberate** [comment]
“*Events are quite confusing. There is a property events, a property event
and a type Event.*”

If you check the documentation, events <https://schema.org/events> is a
property that has been superseded by event <https://schema.org/event>.

As to your example - although this list is not a support list for how
validation tools from data consumers interpret the vocabulary, there are a
few very obvious errors:

   - *events* - a superseded property
   - *partOf* - not a property available for *TheaterEvent*
   - *doorTime* - expects a data type - an ISO 8601 formatted string, as
   you have included in the “content” attribute (you need to drop the
   itemscope and itemtype from the <time> elements.

Although the SDTT reports errors for missing *startDate* & *location*
values, that is a constraint that the tool applies. The Schema.org is valid
without them.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by Meteor0id** [comment]
"obvious errors"

Excuse me? It wasn't quite that obvious to me by the improper examples for event, lack of documentation about dateTime and nonsense errors thown by the validator.

Could you show me a proper version of the sample in the first post? Because I am still not clear about a listing of events and an exprespion of dateTime. Although it is probably obvious right?

**Comment by Meteor0id** [comment]
should quickly point out one one these lines is a owrk of progress:
<meta itemprop="url" content="link naar thema overzicht hier" /> sais in Dutch "link to something will come here"
as pointed out in https://github.com/schemaorg/schemaorg/issues/1985 this must become a link element. <link itemprop="url" href="http://example.com" />

Not an anchor element, because than we would get anchors withing anchors (invalid), and we prefer to keep each event a single clickable item.

I will replace that line of text later with a valid url. For now that turns it into:

```
<ul itemprop="events">
									<li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent"><a itemprop="url" href="" target="_self"><time itemprop="doorTime" itemscope itemtype="http://schema.org/DataTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time><span itemprop="name" class="event_name">test item</span><span itemprop="partOf" itemscope itemtype="http://schema.org/CreativeWorkSeries" class="event_theme">Digitale Rechten<link itemprop="url" href="link naar thema overzicht hier" /></span>
									<!--<span class="event_access">Vrije toegang</span>--></a></li>
									<li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent"><a itemprop="url" href="" target="_self"><time itemprop="doorTime" itemscope itemtype="http://schema.org/DataTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time><span itemprop="name" class="event_name">een aanzienlijk langer test item want dit kan voorkomen dus moet getest worden</span><span itemprop="partOf" itemscope itemtype="http://schema.org/CreativeWorkSeries" class="event_theme">Digitale Rechten<link itemprop="url" href="link naar thema overzicht hier" /></span>
									<!--<span class="event_access">Vrije toegang</span>--></a></li>
									<li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent"><a itemprop="url" href="" target="_self"><time itemprop="doorTime" itemscope itemtype="http://schema.org/DataTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time><span itemprop="name" class="event_name">test item</span><span itemprop="partOf" itemscope itemtype="http://schema.org/CreativeWorkSeries" class="event_theme">Digitale Rechten<link itemprop="url" href="link naar thema overzicht hier" /></span>
									<!--<span class="event_access">Vrije toegang</span>--></a></li>
								</ul>
```



*events* is superceeded by a property wich can only be used for a single event. Missing a way of listing coming and past events.
*doorTime*  expects a DateTime as its value. Why whould I not set the type explicitly to DateTime?

**Comment by RichardWallis** [comment]
@Meteor0id 

See reworked example below.

_events_ is superseded, so should not be used.
All properties within Schema.org can be repeated.  Therefore you can use multiple _event_ properties.

_doorTime_ expects DateTime which is a [DataType](https://schema.org/DataType), data types (Boolean, Date, DateTime, Number, Text, Time) are represented as values not instances of types.

As per the [description](https://schema.org/DateTime), a DateTime is represented in "the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm] (see Chapter 5.4 of ISO 8601)".

Notes on update on your example below:

- removed ```itemprop="events"```  - superseded property, results in multiple _event_  properties being associated with the enclosing type.
- removed ```itemscope itemtype="http://schema.org/DataTime"``` from doorTime - value will be extracted from _content_ attribute, no enclosed type.
- Changed _CreativeWorkSeries_ to _EventSeries_ - _TheaterEvent_ is an _Event_ subtype not a CreativeWork subtype
-  changed _partOf_ to _superEvent_  - _partOf_ is not a property of _EventSeries_
-  wrapped the name of the series within a _name_ property.

Testing this in Google's SDTT now only throws up errors and warnings for properties, such as location & startDate, which they find necessary or recommended for some of their functions, although the Schema.org markup is valid.

Hope this helps.   All who actively participate in Schema.org will attest that there could and should be more and better documentation and examples.   As an open cooperative initiative where the vast majority of efforts to extend and improve the vocabulary comes from volunteers, who also have day jobs, it is not always easy to find those willing to apply their limited time to documentation, especially retrospective documentation.  Also, as you are discovering, it is not only Schema.org that is part of the learning curve, some of the lesser known areas of Microdata, RDFa, JSON-LD, and HTML syntax are important too.

~Richard.

```
<ul>
    <li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent">
        <a itemprop="url" href="" target="_self">
            <time itemprop="doorTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time>
            <span itemprop="name" class="event_name">test item</span>
            <span itemprop="superEvent" itemscope itemtype="http://schema.org/EventSeries" class="event_theme">
                <span itemprop="name">Digitale Rechten</span>
                <link itemprop="url" href="link naar thema overzicht hier" />
            </span>
        </a>
    </li>

    <li itemprop="event" itemscope itemtype="http://schema.org/TheaterEvent">
        <a itemprop="url" href="" target="_self">
            <time itemprop="doorTime" content="2018-05-08T17:00" datetime="2018-05-08T19:30"><span class="event_time">17:00</span><span class="event_date">Vandaag</span></time>
            <span itemprop="name" class="event_name">een aanzienlijk langer test item want dit kan voorkomen dus moet getest worden</span>
            <span itemprop="superEvent" itemscope itemtype="http://schema.org/EventSeries" class="event_theme">
                <span itemprop="name">Digitale Rechten</span>
                <link itemprop="url" href="link naar thema overzicht hier" />
            </span>
        </a>
    </li>
</ul>
```
