### ISSUE TITLE
Collections of Questions/Answers?

### ISSUE THREAD

**Issue by whelks-chance** [schemaorg/schemaorg#1995]
I'm looking to see what the best "type" is for a collection of Questions and Answers, when describing large sets of administrative data such as national census surveys.

Schema.org has Questions and Answers, but no real collective grouping which feels appropriate. The closest I've seen is either Dataset or CreativeWork, but these are not a good fit. Dataset implies the survey responses are attached, which is rarely true. CreativeWork implies (to me) a work of fiction, art or media.

This is quite surprising, due to the number of surveys out there in the world, which are a major source of data/information gathering. I'd have thought that a Survey or Questionnaire type would have been one of the first things added.

Worth noting, there is a huge body of work trying to create metadata for such things, like the DDI:

http://www.ddialliance.org/explore-documentation

But this appears very XML heavy. Perhaps there is a way to convert between the two formats?

Am I missing something really obvious?

Many thanks,

**Comment by RichardWallis** [comment]
There is the [Collection](https://bib.schema.org/Collection) Type. "_A created collection of Creative Works or other artefacts._" . As both _Question_ & _Answer_ are _CreativeWork_ subtypes, it should be well purposed for the job.

With reference to things such as DDI, I wonder if [DefinedTerm](https://pending.schema.org/DefinedTerm) alongside other Schema types could be used to form a widely consumable layer around such data.

**Comment by whelks-chance** [comment]
Thank you for this, Collection is probably the way to go unless something more specific is added in future.

As for DDI, the more I look into it, the bigger that challenge appears to be. A proper wrapper for this data would be great, but there's not a high probability that I will have the time to write it myself, unless I can ask my employer to fund me for several months to figure it all out...

**Comment by RichardWallis** [comment]
Answered
