### ISSUE TITLE
missionCoveragePrioritiesPolicy also relevatn to other organisations

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/schemaorg#2000]
Currently missionCoveragePrioritiesPolicy is only available to newsMediaOrganizations. However, an NGO also publishes news items relevant to the topics they cover. Thgey might cover multiple topics, with articles sourcing from multiple organisations or persons, between which they also need to prioritize.

Taking an NGO as an example of another organisation whcih could make use of this property:
An NGO has a mission
An NGO does sometimes cover news
An NGO does sometiems need to prioritize
An NGO might publish a (public) policy about their mission coverage priorities

Hence an NGO could benefit from having missionCoveragePrioritiesPolicy as an available property.

**Comment by RichardWallis** [comment]
Defining any particular Organization as both an NGO and a NewsMediaOrganization would achieve the same goal, for the circumstance you describe:
```
<div itemscope itemtype="http://schema.org/NGO">
     <link itemprop="additionalType" href="http://schema.org/NewsMediaOrganization"/>
```
or
```
   "@type": ["NGO", "NewsMediaOrganization"],
```

**Comment by Meteor0id** [comment]
Alright. I reconsidered and agree. If an NGO does indeed cover news, it shoudl make use of additionalType to indicate being a NewsMediaOrganisation.

Thank you for pointing this out.
