### ISSUE TITLE
using property "offers" on an "Event" is downright weird. we have "Ticket" for this, which makes more sense

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/schemaorg#2002]
First example here shows how the property "offers" is used. This term however relates better to a product or service, an Event is not a product and might not be a service.
https://schema.org/Offer#examples

I propose depriciating the property "offers" for "Event" and subsituting it with "Ticket".

Yes, an organisation or person might offer a ticket for an event. But An event itself has no offers (pural noun), and an event makes no offers (verb), an event has tickets. And there might be an url to a sales page, or a location where tickets may be bought related to an event.

I have not yet worked out a proposal of how the type ticket and the type event should be used together, but with this ticket I atleast open te discussion about it.

**Comment by nmaynes** [comment]
I came across this issue while looking at the Event Schema entry. What does it take to close this issue? It seems like the _offers_ property will stand for the time being. Can the issue be closed to reflect that?

**Comment by RichardWallis** [comment]
Closing as based on my comment above, there is unlikely to be change in this area.

**Comment by Meteor0id** [comment]
Right, and so this old mistake gets carried forward in the future, only being used more and having an bigger impact later on. It seems obvious to me that this will lead to many mistakes and confusion in the future which could have been prevented right here.

I thought we had issue trackers to keep track of issues, even if it wasn't going to move any time soon. Closing ticket just means losing the issue out of sight.

**Comment by HughP** [comment]
One solution would be to use the "WontFix" label (or some variant) and
leave it open.

**Comment by nmaynes** [comment]
I realize I am offering an opinion based on minimal experience but seeing as this thread is for discussion, I'd like to follow up with what @Meteor0id said. How does changing offers to ticket improve the way an Event is represented? Events like concerts certainly could have tickets but can't the Event type be used for something as simple as a press conference or as complex as a historical Event like 9/11, the Moon Landing, etc? Or what about natural disasters? Are they a subclass of event? Curious to get anyone's take on this.

**Comment by RichardWallis** [comment]
@Meteor0id I've added the **Closed and Noted (possibly Queued)** tag to this issue, which I should have done at the time - sorry.

@nmaynes As with many, inherited from super-types, properties found in the vocabulary, you would not need to define _offers_ (or tickets) for Events for which they were not relevant, such as you suggest.  It is a bit like the _faxNumber_ property for the _Volcano_ type.
