### ISSUE TITLE
Super-property "rdfs:label" is linked to non-existing page

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#2008]
From [`name`](https://schema.org/name):

> **Super-properties**  
> [`rdfs:label`](https://schema.org/rdfs:label)

`rdfs:label` is linked to [https://schema.org/rdfs:label](https://schema.org/rdfs:label), which responds with 404.

**Comment by unor** [comment]
Not my call, but I’d say a link to the stable version of the spec makes the most sense:

https://www.w3.org/TR/2014/REC-rdf-schema-20140225/#ch_label

(+ a link icon that conveys it’s an external link)

**Comment by RichardWallis** [comment]
@grosscol @unor - Yes somewhere such as that.

FYI I am working on some enhancements to the core software, that runs the schema.org site, that will enable it to handle external [to Schema] references such as this a little more elegantly than highlighted here.

I will feed these thoughts into that.
~Richard.

**Comment by RichardWallis** [comment]
Fixed
