### ISSUE TITLE
Gifts on offers markup

### ISSUE THREAD

**Issue by mdromed** [schemaorg/schemaorg#2009]
Hi everyone.
How can i offer a free gift inside my offer markup?
The idea is Google SERP shows it near to price like this:

Product 1 - Soccer Ball
This product is awesome and nice!
Buy it!
www.myweb.com

Price: $29.00
Avaliability: In Stock
Free Gift:  red soccer t-shirt

It is possible?

**Comment by RichardWallis** [comment]
Create an _Offer_ to describe the Free Gift (price  zero, etc.)
Then associate it with the main offer by ether:
1. Link it via the _addOn_ property of the main offer
2. Create an _AggregateOffer_ describing the offer with a free gift, and then attach the main offer and free offer to the aggregate's _offers_ property.

**Comment by mdromed** [comment]
But will Google show gift like rich snippets into SERP list? 

El 3 de julio de 2020 17:06:46 CEST, Richard Wallis <notifications@github.com> escribió:
Create an _Offer_ to describe the Free Gift (price  zero, etc.)
Then associate it with the main offer by ether:
1. Link it via the _addOn_ property of the main offer
2. Create an _AggregateOffer_ describing the offer with a free gift, and
then attach the main offer and free offer to the aggregate's _offers_
property.  

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/schemaorg/schemaorg/issues/2009#issuecomment-653588595

mdromed

**Comment by RichardWallis** [comment]
That is a question for the forums hosted by Google.

**Comment by mdromed** [comment]
ok thanks 

El 3 de julio de 2020 19:42:18 CEST, Richard Wallis <notifications@github.com> escribió:
That is a question for the forums hosted by Google. 



> On 3 Jul 2020, at 18:21, mdromed <notifications@github.com> wrote:
> 
> ﻿
> But will Google show gift like rich snippets into SERP list? 
> 
> El 3 de julio de 2020 17:06:46 CEST, Richard Wallis
<notifications@github.com> escribió:
> Create an _Offer_ to describe the Free Gift (price zero, etc.)
> Then associate it with the main offer by ether:
> 1. Link it via the _addOn_ property of the main offer
> 2. Create an _AggregateOffer_ describing the offer with a free gift,
and
> then attach the main offer and free offer to the aggregate's _offers_
> property. 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
>
https://github.com/schemaorg/schemaorg/issues/2009#issuecomment-653588595
> 
> mdromed
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/schemaorg/schemaorg/issues/2009#issuecomment-653633466

mdromed
