### ISSUE TITLE
Error in JSON-LD context file re encodingFormat?

### ISSUE THREAD

**Issue by iherman** [schemaorg/schemaorg#2019]
https://schema.org/encodingFormat defines the value to be either a URL or a string (ie, either a usual MIME format or a URL for additional (non-IANA registered) types. However, the relevant line in the schema.org context file is:

```
"encodingFormat": { "@id": "schema:encodingFormat", "@type": "@id"},
```

The effect is that if one has:

```
 {
    ...
    "encodingFormat" : "text/html",
    ...
}
 ```

then one gets, when expanding (with the JSON-LD playground):

```
        "http://schema.org/encodingFormat": [
          {
            "@id": "https://json-ld.org/playground/text/html"
          }
        ],
```

which is, from a JSON-LD point of view, correct, but I do not think this is the intention.

I believe the `"@type":"@id"` should be removed from the context file.

**Comment by danbri** [comment]
Thanks, noted and tagged "bug"...
