### ISSUE TITLE
Allow byArtist to accept a Person as well as a MusicGroup

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2020]
http://schema.org/MusicAlbum and http://schema.org/MusicRecording use http://schema.org/byArtist to designate the artist credited with an album. Currently, the only acceptable type is http://schema.org/MusicGroup.

While MusicGroup's description says it can be used for individual artists, it is a subtype of http://schema.org/PerformingGroup, which does not.

Given it makes distinguishing groups from individuals, the simplest thing would be to expand the range of ```byArtist``` to accept http://schema.org/Person as well.

**Comment by thadguidry** [comment]
@vholland so we are saying that our Group Types should be considered restricted for use of MORE THAN 1 PERSON ?  I'm fine with that restriction.

In some databases, a Music Group could be used for either 1 person or a group.  We might want to mention something about our restriction in our MusicGroup and PerformingGroup definitions ?

**Comment by vholland** [comment]
@thadguidry Yes, that was my thought. Both definitions would need updating.

**Comment by danbri** [comment]
SGTM. Can you make a PR (with a line giving docs/releases.html text ideally:)

**Comment by vholland** [comment]
When I said tomorrow, I must have meant in the metaphorical sense. Anyway, see PR #2038

**Comment by RichardWallis** [comment]
Implemented in [release 3.5 ](https://schema.org/docs/releases.html#v3.5)
