### ISSUE TITLE
Specify audio and video "clips" with startTime/endTime properties on MediaObject

### ISSUE THREAD

**Issue by earljwagner** [schemaorg/schemaorg#2021]
The associatedMedia for a CreativeWork may actually be just a part of an AudioObject or VideoObject. For example, an anthology film may depict several short stories. We want each story to be associated with just its segment, not the entire film.

We should allow the segments or clips to be specified by adding startTime and endTime properties on MediaObject of type DateTime.

**Comment by martinbean** [comment]
I second this. I have a video on demand site that carries professional wrestling content, so it would be good if I had some way to mark up each match (as content providers can create “chapters” for individual matches).

**Comment by danbri** [comment]
Makes sense (and merged), but perhaps there's a role for adapting https://schema.org/Clip maybe as a second type on these objects too?

**Comment by vholland** [comment]
http://schema.org/startTime and http://schema.org/endTime both expect ISO 8601 strings. As it is difficult to specify an offset in ISO 8601, I suggest building off @danbri 's suggest of using https://schema.org/Clip.

We can then add the following properties to Clip:
*startOffset*: The start time of the clip expressed as the number of seconds from the beginning of the longer work. 

*endOffset*: The start time of the clip expressed as the number of seconds from the beginning of the longer work.

An example of this new markup would be:

```
{
  "@context": "http://schema.org/",
  "@type": "VideoObject",
  "name": "Cat video",
  "duration": "P10M",
  "hasPart": {
    "@type": "Clip",
    "name": "Segment where cat jumps",
    "startOffset": 30,
    "endOffset": 45
  }
}
```

**Comment by vholland** [comment]
I didn't see objections, so implemented PR #2127

**Comment by RichardWallis** [comment]
Implemented in [release 3.5 ](https://schema.org/docs/releases.html#v3.5)

**Comment by martinbean** [comment]
Just seen the comments on this.

> As it is difficult to specify an offset in ISO 8601

Would an offset not just be a duration?
https://en.wikipedia.org/wiki/ISO_8601#Durations

It just seems weird that in the example given:

```json
{
  "@context": "http://schema.org/",
  "@type": "VideoObject",
  "name": "Cat video",
  "duration": "P10M",
  "hasPart": {
    "@type": "Clip",
    "name": "Segment where cat jumps",
    "startOffset": 30,
    "endOffset": 45
  }
}
```

We now have a mixture of ISO-style duration (`P10M`) and seconds values in `startOffset` and `endOffset`.

**Comment by Downchuck** [comment]
> We now have a mixture of an ISO-style duration value (`P10M`) and seconds values in `startOffset` and `endOffset`.

In addition, the example suggests `startOffset` and `endOffset` are integers - and while the spec is clear that it's numeric, implementations may not follow it.
