### ISSUE TITLE
How can I write a general product JSON for the products in my shopify website?

### ISSUE THREAD

**Issue by YanYanNg** [schemaorg/schemaorg#2022]
Hello,

Does anyone know how to write/generate a general product JSON codes that is applicable to all products in my website?

**Comment by tobiasboyd** [comment]
That doesn't seem quite like an issue, unless it's with the discoverability of the docs...

There are some handy tools for generating examples, like https://www.jamesdflynn.com/json-ld-schema-generator/

I don't use Shopify, but I assume it shouldn't be too hard to get it to generate that JSON-LD. A quick look turned up this:

https://feedarmy.com/kb/shopify-microdata-for-google-shopping/

Good luck!

**Comment by Dataliberate** [comment]
You could try this: 
https://www.schemaapp.com/

They have a shopify plug-in

**Comment by GuiguiWeb** [comment]
An other shopify app: https://apps.shopify.com/json-ld-for-seo

**Comment by manishjainin** [comment]
I would recommend not buying any tool or plugin. Like JSON LD cost a lot. The digital marketing agency that I worked with provided the below code and it worked like charm.

```
{% if template contains 'product' %}
  <script type="application/ld+json">
  {
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "{{product.title|escape}}",
  "productID": "{{product.id}}",
  "image": "https:{{product.featured_image | product_img_url: 'master' }}",
  "description": "{{product.description|strip_html|escape}}",
  "brand": { 
      "@type": "Thing",
      "name": "{{product.vendor}}"      
    }, 
  "offers": {
      "@type": "Offer",
      "priceCurrency": "{{shop.currency}}",
      "price": "{{product.price|money_without_currency}}",
      "availability": "{% if product.available %}http://schema.org/InStock{% else %}http://schema.org/OutOfStock{% endif %}",
      "url":"{{shop.url}}{{product.url}}"
    }
  } 
  </script>
  {% endif %}
```

Shoutout to https://vrdigital.com.au
