### ISSUE TITLE
Product properties have disappeared from web documentation!

### ISSUE THREAD

**Issue by PierrePX** [schemaorg/schemaorg#2023]
https://schema.org/Product : 
![image](https://user-images.githubusercontent.com/38721835/43197385-4d2e00f4-900b-11e8-93d2-a2772bf29edd.png)

only the category survives

**Comment by PierrePX** [comment]
When compared to the Product properties listed in child entity, like ProductModel, we have plenty there:

https://schema.org/ProductModel
![image](https://user-images.githubusercontent.com/38721835/43197444-79a5cad6-900b-11e8-9630-88082796c911.png)

**Comment by RichardWallis** [comment]
Hi @PierrePX  This is symptomatic of an issue that is being worked on at the moment.

I have taken some action to correct it, which may take a while to work through the web caching infrastructure.

~Richard

**Comment by PierrePX** [comment]
Cool thanks.
