### ISSUE TITLE
Questions about dev, extend schema.

### ISSUE THREAD

**Issue by Hikingyo** [schemaorg/schemaorg#2024]
I jus have forked this project and run on my pc.
All work fine, but when i'm visting http://localhost:8080/releases/<my_release>
I got a 404 message.
When I compare schema-all.html in older release, like current in data/releases/3.4, I appeare  that mine are poorly thin.
Where I made a mistake ?

**Comment by RichardWallis** [comment]
Many of the pages you reference are only built at the time of a release.

A local instance is mainly to test how the term pages and their contents look and that the tests scripts run OK.

For an insight into what is done at release time, check out the [releasing notes](https://github.com/schemaorg/schemaorg/blob/master/RELEASING.TXT).

**Comment by Hikingyo** [comment]
I have found what I did wrong and all work fine.
Thanks for your answer.
