### ISSUE TITLE
Online OWL version of schema.org has incorrect char encoding for some characters

### ISSUE THREAD

**Issue by nicholascar** [schemaorg/schemaorg#2025]
The OWL file for schema.org, https://schema.org/docs/schemaorg.owl, has the following characters that prevent RDF parsing:

’
è
—
“
”
西遊記
Tây du ký bình khảo
物种起源

**Comment by RichardWallis** [comment]
I have noted that the encoding value in the file is "utf8" and probably should be "UTF-8"

Nevertheless the file seems to load OK in to Protégé where  these characters display OK;

![image](https://user-images.githubusercontent.com/13315406/43518600-86245aba-9584-11e8-8017-148ed17f5234.png)

Is it a particular parser you are having problems with?

**Comment by nicholascar** [comment]
Yes, I think it's that it's "utf8" not "UTF-8". It was using Python's [rdflib](https://pypi.org/project/rdflib/) for RDF parsing where it failed. Presumably rdflib can't assume "utf8" is "UTF-8" where as Protege can?

**Comment by RichardWallis** [comment]
Fixed

**Comment by nicholascar** [comment]
Thanks
