### ISSUE TITLE
Missing comma in Flight example

### ISSUE THREAD

**Issue by edwardmp** [schemaorg/schemaorg#203]
Hi,

I noticed the example on the page http://schema.org/Flight is missing a comma, making it invalid JSON-LD.

The comma is missing after the "seller" block:
  ```
"seller": {
      "@type": "Airline",
      "name": "United",
      "iataCode": "UA"
}  <---- comma should be inserted here
"departureAirport": {
      "@type": "Airport",
      "name": "San Francisco Airport",
      "iataCode": "SFO"
},
```
I confirmed the invalidation by using http://json-ld.org/playground/index.html.

By the way, it would be useful if an aircraft registration number (tail number) could be added to aircraft/vehicle (http://schema.org/aircraft).

**Comment by danbri** [comment]
Fixed, thanks!
