### ISSUE TITLE
Breadcrumbs bad link (Property)

### ISSUE THREAD

**Issue by GuiguiWeb** [schemaorg/schemaorg#2033]
In breadcrumbs :
https://meta.3-3d.schemaorgae.appspot.com/Property instead of https://meta.schema.org/Property

<img width="366" alt="capture d ecran 2018-08-08 a 17 04 21" src="https://user-images.githubusercontent.com/26392178/43845822-2797cd5c-9b2d-11e8-993c-9046a7ed0000.png">

Seen on the page: https://schema.org/openingHours

**Comment by danbri** [comment]
@RichardWallis how did this sneak in?

**Comment by RichardWallis** [comment]
@danbri Not sure.

Checking page source now, it is not visible.  I believe it is an obscure symptom of the caching problem we are working on.

**Comment by RichardWallis** [comment]
Not an issue anymore
