### ISSUE TITLE
Add VisualArtwork vocabulary based on proposal

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#204]
From https://www.w3.org/wiki/WebSchemas/VisualArtwork

https://github.com/danbri/schemaorg/pull/30

**Comment by danbri** [comment]
Re-opened as labelled as 'implementing' due to a couple more details:
- [ ] https://github.com/schemaorg/schemaorg/pull/293 Added URL as an expected type (in addition to Text) to the VisualArtwork properties of "artform", "surface", and "material" 
- [ ] The descriptions for depth and height should probably be updated, too. If you look at http://sdo-stantz.appspot.com/VisualArtwork, the descriptions for depth, height, and width are each a little different. I think they should all be, “The {blah} of the item.” (from Tom Marsh)

**Comment by danbri** [comment]
I've attended to those last 2 details. @tmarshbing @lazaruscorporation how is it looking? are we done?

**Comment by lazaruscorporation** [comment]
@danbri looks good to me!

**Comment by tmarshbing** [comment]
@danbri looks good to me, too. Closing it.
