### ISSUE TITLE
Expected value of accessModeSufficient should be ItemList

### ISSUE THREAD

**Issue by mattgarrish** [schemaorg/schemaorg#2040]
As discussed in https://github.com/schemaorg/schemaorg/issues/1100, accessModeSufficient should expect one or more "ItemList" but it ended up with "Text" in the final release.

Also, as noted in https://github.com/schemaorg/schemaorg/issues/1100#issuecomment-256657296, the first example should be corrected to use ItemList.

Web publications is looking to implement the property according to the incorrect text value expectation: https://github.com/w3c/wpub/issues/300

/cc @madeleinerothberg @clapierre @avneeshsingh

**Comment by clapierre** [comment]
I know that @danbri helped a lot with the AccessModeSufficient when we were working on how to do multiple ItemLists in the various RDFa / JSON implementation examples, I would like to know what happened is it just an example that was incorrectly added and missed?  Or if there was something fundamentally wrong with our implementation.

**Comment by mattgarrish** [comment]
I suspect these were just oversights. We were busy working on EPUB's implementation, where we knew we had to convert to strings for the package document, and probably missed these last two tweaks.

Hopefully these are just straight-ahead bug fixes, but welcome the input if not.

**Comment by madeleinerothberg** [comment]
Yes, where markup allows, AccessModeSufficient should accept one or more ItemLists so that each combination of modes (which represent a single usage style) are bound to each other, and more than one distinct usage style can be documented.

**Comment by RichardWallis** [comment]
Implemented in PR #2041
