### ISSUE TITLE
schema.org/health-lifesci.schema.org examples?

### ISSUE THREAD

**Issue by Uzgraph** [schemaorg/schemaorg#2044]
Question about health-lifesci.schema.org/MedicalImagingTechnique
No example I see.

My site about ultrasonography and on pages there are the diagnostic videos and images of cases. How can I mark such content by schema.org/health-lifesci.schema.org syntax? 

Something like this?
<div itemprop="Ultrasound" itemscope itemtype ="http://schema.org/MedicalImagingTechnique">
...
</div>

**Comment by twamarc** [comment]
@Uzgraph please complete your message.
Yes, most of examples are still missing for ``` schema.org/health-lifesci.schema.org``` . As the community will adopt the vocab, more examples will be provided.

**Comment by Uzgraph** [comment]
<div itemprop="Ultrasound" itemscope itemtype="http://schema.org/MedicalImagingTechnique">

my case...

</div>

**Comment by Uzgraph** [comment]
[code]<div itemprop="Ultrasound" itemscope itemtype="http://schema.org/MedicalImagingTechnique">

my case...

</div>[/code]

**Comment by Uzgraph** [comment]
[div itemprop="Ultrasound" itemscope itemtype="http://schema.org/MedicalImagingTechnique"]
my case ...
[/div]

**Comment by Uzgraph** [comment]
[div itemprop="CaseSeries" itemscope itemtype="http://schema.org/MedicalObservationalStudyDesign"]
[div itemprop="Diagnostic" itemscope itemtype="http://schema.org/MedicalDevicePurpose"]
[div itemprop="Ultrasound" itemscope itemtype="http://schema.org/MedicalImagingTechnique"]

my case ...

[/div]
[/div]
[/div]
I.e. case of diagnostic ultrasound

**Comment by danbri** [comment]
Thank you for the suggestion! It has been noted, tagged and filed for future reference. I am closing this issue to help us manage the huge number of suggestions we get, but we do appreciate that you've taken the time, and we encourage continued discussion here.

See also #2050 for background on issue-closing.

**Comment by danbri** [comment]
Regarding the health / lifesci / medical vocabulary, we are particularly interested to collect any examples of it being consumed by applications.
