### ISSUE TITLE
SearchAction validation fails with Google Structered Data Testing Tool

### ISSUE THREAD

**Issue by Download** [schemaorg/schemaorg#2046]
Go to https://schema.org/SearchAction
Find the code sample marked Example 1 and copy the JSON
Go to https://search.google.com/structured-data/testing-tool
Choose Code snippet and paste the code sample
Press RUN TEST

You get the following error message:

> Type WebSite has invalid nesting. Properties should be applied to SearchAction.

This is the snippet in question:

```json
{
  "@context": "http://schema.org",
  "@type": "SearchAction",
  "agent": {
    "@type": "Person",
    "name": "John"
  },
  "query": "What is the answer to life the universe and everything?"
}
```

Even if I reduce this example to the bare minimum:

```json
{
  "@context": "http://schema.org",
  "@type": "SearchAction"
}
```

I still get the same error message. If I change the type to FindAction, the error message goes away.

Could there be an error in the schema? 
Or do you guys happen to know if this is an error in the tool?

**Comment by danbri** [comment]
Schema.org isn't Google - we can't offer any kind of support for Google products and services here. You might try the Google Product Forums, eg https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Astructured-data%7Csort:relevance%7Cspell:false
