### ISSUE TITLE
Proposal: Introduce UploadAction to accompany DownloadAction

### ISSUE THREAD

**Issue by Download** [schemaorg/schemaorg#2048]
Since we have [DownloadAction](https://schema.org/DownloadAction) it's a bit weird that we don't have [UploadAction](https://schema.org/UploadAction). The closest I can find is [TransferAction](https://schema.org/TransferAction), which doesn't really fit.

**Comment by danbri** [comment]
Thank you for the suggestion! It has been noted, tagged and filed for future reference. I am closing this issue to help us manage the huge number of suggestions we get, but we do appreciate that you've taken the time, and we encourage continued discussion here.

See also #2050 for background on issue-closing.

**Comment by danbri** [comment]
This sounds plausible to me, although if we're not careful it could look like we're reproducing a model of HTTP. It would be good to have at least one application committing to using such a type  before we adopt this.

**Comment by Download** [comment]
What is 'an application committing to using such a type'? How can an application commit to using a type that is not in the schema? I filed this issue because I wanted to use UploadAction for my application but alas it does not exist. So now my application is using Action with name="upload".
