### ISSUE TITLE
Closing many issues, after tagging. Discussions are still welcome...

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2050]
Schema.org is a project with a broad scope. We use this public Github to collect and discuss ideas for improving it. This has left us with (at this moment) 828 open issues. We need to close some as "interesting, thanks for the idea". 

To support this we now have two labels, one for closing as "unlikely to implement" (without further evidence or motivation), and one for "closed and noted" (and possibly queued for later attention). In both cases, ongoing discussion, especially evidence from publishing or consuming implementors, is still welcome. The plan is to leave "open" as representing issues we are trying to make progress on in the immediate future (approximately the next release or two). 

As project webmaster and chair of the Community Group, I will take responsibility for this process, and for liaison between these discussions and our Steering Group. Please don't be offended if your issue is closed in this way!  We need to do this due to the broad scope of the project. It's important to collect as many suggestions and ideas as possible, without drowning the project in a million issues...

This issue was created so it can be linked from issues that are closed, to explain the process. For more background see also our [CONTRIBUTING](https://github.com/schemaorg/schemaorg/blob/master/CONTRIBUTING.md) document for useful links, especially on [how we work](http://schema.org/docs/howwework.html).

**Comment by akuckartz** [comment]
Alternatively you could use different tags for open issues. Closed issues regularly get next to no attention by anyone.

**Comment by chaals** [comment]
I'm happy with closing issues for now, since having a shorter list is a way to think you might get to none. But I would prefer the tag that means "closed, but only because we haven't figured this out yet" have a name that more clearly suggests it is explicitly considered a candidate for reopening later...
