### ISSUE TITLE
MonetaryAmountDistribution example does not match the documentation

### ISSUE THREAD

**Issue by tko** [schemaorg/schemaorg#2058]
https://pending.schema.org/MonetaryAmountDistribution

The JSON-LD example on the page contains
```js
  "estimatedSalary": {
    "@type": "MonetaryAmountDistribution",
    "duration": "1Y",
    "currency": "USD",
    "percentile10": 72000,
    "percentile25": 86000,
    "median": 109000,
    "percentile75": 120000,
    "percentile90": 140000
  }
```

of all the properties only `currency` is actually documented.

**Comment by Aaranged** [comment]
These properties are all in [pending](https://pending.schema.org/).  E.g.:
- [duration](https://schema.org/duration)
- [percentile10](https://pending.schema.org/percentile10)

However, on another note, for all of these properties the "Used on these types" referenced is [QuantitativeValueDistribution](https://pending.schema.org/QuantitativeValueDistribution).
As MonetaryAmountDistribution is not a subtype of QuantitativeValueDistribution (they are both subtypes of QuantitativeValue), these properties wouldn't be valid for MonetaryAmountDistribution.

Accordingly, either MonetaryAmountDistribution should be modelled as a subtype of QuantitativeValueDistribution, or the domain of these properties should be extended to include MonetaryAmountDistribution.

Having written what I did above I see on #1698 that it is the first of these solutions that was indeed proposed by @vholland (emphasis mine): "New type MonetaryAmountDistribution: *A subtype of QuantitativeValueDistribution* for describing a statistical distribution of monetary amounts."

**Comment by vholland** [comment]
Yes, the intention was to make MonetaryValueDistribution a subtype of QuantitativeValueDistribution.

**Comment by danbri** [comment]
Fixed in master branch for next release
