### ISSUE TITLE
Clarify Rating e.g. itemReviewed should be applicable to Rating; make Rating a CreativeWork?

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#206]
http://schema.org/Rating

http://schema.org/itemReviewed is attached to AggregateRating and Review. I can't see how you'd indicate a simple (and non-aggregate) Rating without packaging it in a Review, unless we add:

Rating domainIncludes itemReviewed.

See also:
- #140 (closed in favour of this issue)
- https://github.com/schemaorg/schemaorg/issues/161 itemReviewed inverseOf review

**Comment by danbri** [comment]
On second thoughts I'm not sure about that commit. A Rating can't have an author/creator yet. Needs more thought.

**Comment by danbri** [comment]
It seems reasonable to know who made a Rating.

Currently that is only doable by proxy through a review. Should we allow author/creator on intangibles like Rating, or say that Rating is a CreativeWork?

**Comment by thadguidry** [comment]
@danbri I think you could say that Rating is a CreativeWork and it offers a few useful properties.

Examples:  
1. secondaryContributor is useful for 2 Thumbs Up (because it has 2 contributors),
2. audience could capture the Rating audience, for instance, Parents, or Librarians
3. position could capture its position in the series (although you need to handle Scale as well, position 2  in a list of 5 where 1 is highest).
4. sourceOrganization - useful for capturing the magazine (Consumer Reports, MotorTrend, CNET) or organization that the Rating author ("Big Bad Bob" gave the gadget 4 stars) was working for.
etc.

**Comment by danbri** [comment]
@rvguha is +1 on Rating moving under CreativeWork instead of Intangible.

**Comment by chaals** [comment]
+ reply@
- notifications@

Seems reasonable. Inter alia, some ratings are pretty creative ;)

23.01.2015, 01:36, "Dan Brickley" <notifications@github.com>:
> @rvguha is +1 on Rating moving under CreativeWork instead of Intangible.
>
> —
> Reply to this email directly or view it on GitHub.

--
Charles McCathie Nevile - web standards - CTO Office, Yandex
chaals@yandex-team.ru - - - Find more at http://yandex.com

**Comment by tmarshbing** [comment]
What is wrong with just using Review as-is for ratings? It seems to have all of the necessary properties. Just don't fill in the reviewBody, and you have a rating. Perhaps we could rename Review to RatingOrReview to make the purpose clearer if we update the intended usage in this way?

**Comment by danbri** [comment]
@tmarshbing do you mean making Review the new supertype of our existing Rating type? Or abandoning Rating in favour of Review as-is? We'd need the numeric properties from Rating and AggregateRating, and there are 1000s of sites using it, so I guess you mean the former. 

Regarding a rename (or shared supertype), Review only adds 'itemReviewed', 'reviewBody', 'reviewRating'. Since a (RatingOr)Review that was just a Rating wouldn't need either reviewRating (because it would *be* the Rating), nor reviewBody (because Ratings are numeric), we'd still only really be discussing itemReviewed as the common ground. Our approach in such cases historically has been to avoid the creation of intermediate 'modeling artifact' types such as a common supertype for ratings + reviews, and to simply add an additional type/property association. Which brings us back to the original proposal, augmented by this discussion:

* Add: itemReviewed domainIncludes Rating.
* Change: ~~Rating subClassOf Intangible~~ to: Rating subClassOf CreativeWork.

The result would be that a Rating (rather than just an AggregateRating) could have an itemReviewed property whose value was anything at all, as well as all the various provenance etc. properties from CreativeWork such as author, dateCreated, dateModified etc.

## Counter-arguments to doing this

* We perpetuate a blurring of lines between ratings and reviews, since it might properly be expected to have the rating-to-item relationship named itemRated rather than itemReviewed.
* We extend the inconsistency between 'itemReviewed' and its near-inverse 'review'. Already 'http://schema.org/itemReviewed' allows Thing, whereas the nearest, closest relationship going in the opposite direction, 'http://schema.org/review', applies only to a hand-picked list of types (CreativeWork, Offer, Organization, Place, Product). For example you cannot currently review an Event (tracked as #193) and describe that using something like 'event_3 review review-43'; instead you have to turn it around and reverse the assertion: 'review-43 itemReviewed event_3'. 

The change considered here would extend the difference between the 'itemReviewed' and 'review', unless we also allowed "Review" to point to ratings, i.e. either adding  "review rangeIncludes Rating" or else - as @tmarshbing suggests - introduce subtyping and terminology that says that a Rating is just a special kind of Review. 

FWIW I think you might see the recently reworked google webmaster documentation as evidence in favour of @tmarshbing 's suggestion: the docs on reviews + ratings is filed in a link whose url and sidebar title is simple "[for reviews](https://developers.google.com/webmasters/structured-data/rich-snippets/reviews)".

If we went in this direction, the changes would be:

* Change: ~~Rating subClassOf Intangible~~ to: Rating subClassOf Review.
* Remove: ~~ itemReviewed domainIncludes AggregateRating~~ (as this would be implied via Review supertype).
* Change definition of Review type from "A review of an item - for example, of a restaurant, movie, or store." to something like "A review of an item - for example, of a restaurant, movie, or store. Reviews can be textual (indicated via reviewBody) or numeric, in which case they are called Ratings. For a textual Review that carries an associated quantitative rating, use the reviewRating property" to reference a Rating. When the main review itself carries ratings (e.g. "was this review helpful" evaluations), they can be indicated using aggregateRating.
* Tweak definitions of reviewRating and aggregateRating accordingly.

At this point I'm agnostic about what we should do, but believe the following are requirements:

* allow a Rating (without a textual Review alongside it) to apply to anything.
* (continue to) allow reviews and ratings of any kind of thing, not just a short-list of picked types.
* clarify the relationship between 'x review y' vs 'y itemReviewed x' w.r.t. expected types for x and y.
* allow our various CreativeWork properties (author, dates etc.) to apply to any Rating.

**Comment by danbri** [comment]
@tmarshbing do you mean making Review the new supertype of our existing Rating type? 
Or abandoning Rating in favour of Review as-is? We'd need the numeric properties from Rating and AggregateRating, 
and there are 1000s of sites using it, so I guess you mean the former.

Regarding a rename (or shared supertype), Review only adds 'itemReviewed', 'reviewBody', 'reviewRating'.  Since a (RatingOr)Review that was just a Rating wouldn't need either reviewRating (because it would *be* the Rating), nor reviewBody (because Ratings are numeric), we'd still only really be discussing  itemReviewed as the common ground. Our approach in such cases historically has been to avoid the  creation of intermediate 'modeling artifact' types such as a common supertype for ratings + reviews, and to simply add an additional type/property association. Which brings us back to the original 
proposal, augmented by this discussion:

## Proposal 1: itemReviewed applies to Ratings, which are CreativeWorks.

* Add: itemReviewed domainIncludes Rating.
* Change: ~~Rating subClassOf Intangible~~ to: Rating subClassOf CreativeWork.

The result would be that a Rating (rather than just an AggregateRating) could have an itemReviewed 
property whose value was anything at all, as well as all the various provenance etc. properties from CreativeWork such as author, dateCreated, dateModified etc.

## Counter-arguments to proposal 1:

* We perpetuate a blurring of lines between ratings and reviews, since it might properly be expected to have the rating-to-item relationship named itemRated rather than itemReviewed.
* We extend the mismatch between 'itemReviewed' and its near-inverse 'review'. Already 'http://schema.org/itemReviewed' allows Thing, whereas the nearest, closest relationship going in the opposite direction, 'http://schema.org/review', applies only to a hand-picked list of types (CreativeWork, Offer, Organization, Place, Product). For example you cannot currently use 'review' on an Event (tracked as #193), i.e. describe an event review via something like 'event_3 review review-43'; instead you have to turn it around and reverse the assertion: 'review-43 itemReviewed event_3'.

The change considered here would continue the difference between the 'itemReviewed' and 'review', 
unless we also allowed the 'review' property to point to ratings, i.e. either adding  "review 
rangeIncludes Rating" or else - as @tmarshbing suggests - introduce subtyping and 
terminology that says that a Rating is just a special kind of Review.

FWIW I think you might see the recently reworked google webmaster documentation as evidence in favour 
of @tmarshbing 's suggestion: the docs on reviews + ratings is filed in a link whose url and sidebar 
title is simple "[for reviews](https://developers.google.com/webmasters/structured-data/rich-snippets/reviews)".

If we went in this direction, the changes would be:

## Proposal 2: itemReviewed applies to Ratings, which are a subtype of Review.

* Change: ~~Rating subClassOf Intangible~~ to: Rating subClassOf Review.
* Remove: ~~ itemReviewed domainIncludes AggregateRating~~ (as this would be implied via Review supertype).
* Change definition of Review type from "A review of an item - for example, of a restaurant, movie, or store." to something like "A review of an item - for example, of a restaurant, movie, or store. Reviews can be textual (indicated via reviewBody) or numeric, in which case they are called Ratings. For a textual Review that carries an associated quantitative rating, use the reviewRating property" to reference a Rating. When the main review itself carries ratings (e.g. "was this review helpful" evaluations), they can be indicated using aggregateRating.
* Tweak definitions of reviewRating and aggregateRating accordingly.

## Conclusions / Requirements

At this point I'm agnostic about what we should do, but believe the following are requirements:

* allow a Rating without a textual Review alongside it to apply to anything.
* allow our various CreativeWork properties (author, dates etc.) to apply directly on an Rating without needing it to be the reviewRating of a Review.
* (continue to) allow reviews and ratings of any kind of thing, not just a short-list of picked types.
* clarify the relationship between 'x review y' vs 'y itemReviewed x' w.r.t. expected types for x and y.

**Comment by thadguidry** [comment]
@danbri  You forgot one of the other requirements.  Review and Rating will both need to be able to apply an author (through CreativeWork or whatever).

**Comment by danbri** [comment]
I thought I covered that via saying "allow our various CreativeWork properties (author, dates etc.) to apply directly on a Rating" (Review already has authors, though I agree we could note that as a continuing requirement).

**Comment by thadguidry** [comment]
@danbri must...have....more....Coffee.  (so sorry, you did after re-reading)

I prefer proposal 1 ... shotgun approach without needing to worry about reviewRating.

**Comment by tmarshbing** [comment]
I was trying to propose something slightly different than 1 or 2. I was just saying to:
- Update the documentation for the existing Review type almost as suggested in proposal 2, but something like this instead: "A review of an item - for example, of a restaurant, movie, or store. Reviews can be textual (indicated via reviewBody) or numeric~~, in which case they are called Ratings~~(indicated via reviewRating) or both. For a textual Review that carries an associated quantitative rating, use the 'reviewRating' property to reference a Rating. When the main review itself carries ratings (e.g. 'was this review helpful?' evaluations), they can be indicated using aggregateRating."
- Optionally, rename the existing Review type to RatingOrReview to better match the updated description.

This doesn't satisfy the second requirement from @danbri because you still have to put the rating in the reviewRating property to get to the CreativeWork properties, but I personally think this is OK. My reasoning is:
- Making Rating derive from Review kind of works, but it adds complexity and multiple ways of representing a rating (I can still create a Review with no reviewBody).
- If Rating doesn't derive from Review, then enumerating all reviews and ratings for something becomes a challenge, especially if some of the reviewRating's for some of the reviews duplicate some of the ratings in the (presumably to-be-created) ratings property.
- But most of all, I think the existing system pretty much "just works" with a bit of clarification in the documentation. So why make bigger changes?

**Comment by danbri** [comment]
I propose we postpone this until after the sdo-gozer release, unless someone (@tmarshbing ?) cares to work this up into an implementable set of exact changes. Still seems worth serious attention, but we have ~ 20 issues blocking sdo-gozer...
