### ISSUE TITLE
Is there a Python API client?

### ISSUE THREAD

**Issue by vsoch** [schemaorg/schemaorg#2061]
In that creators of schemas for scientific domains are commonly using python (and well, sometimes R, but that is more statistics and less bio/neuro) I wanted to ask if there is a Python client? For example, if I'm preparing a dataset as I loop I would want to do this:

```python
from schemaorg import Schema
from schemaorg.extensions.health_lifesci import *
from glob import glob

# Create schema
schema = Schema()

anatomical = BrainStructure(bodyLocation="head", function="thinking")
schema.add(anatomica)
schema.save("schema.json")
```
The above would export to whatever format(s) are desired, and then the schema itself could be used however needed! The library could also have functions for interacting with a schema. For example, in datalad you have [extractors](http://docs.datalad.org/en/latest/metadata.html) for metadata that would typically parse over files and use a metadata definition to create a "meta metadata" object. This is actually where I'd want to put different kinds of validation, which also could be supplied

```
from schemaorg.validators import SchemaValidator
validator = SchemaValidator("schema.json")

anats = glob("*.nii.gz")

for anat_file in anats:
    validator.validate(anat)
```

With different levels for warnings, errors, coinciding with python logging, etc. Things like validators, nice graphical UIs, and transfer, and reports could be generated based on a (default) export of the current schemas, and then the user could specify a custom one of course.

I found a few libraries for extraction, or general parsing, but not what I'm thinking of, e.g.
 - https://github.com/edsu/microdata
 - I see a lot of python [here where we are](https://github.com/schemaorg/schemaorg) but this seems more relevant to maintaining the site / functions here?
 - [more general](https://pypi.org/project/schema/)
 - [pyLD](https://pypi.org/project/PyLD/) could be used for a specific export

The library I'm looking for would be more of a template generator and vaidator, and used not by developers but by dataset providers / generators. This would be a nice start / foundation for building a lot of the things I'm wanting to do, and making it easy for scientists, so I'd like to ask about it, and if there isn't one, I would like to give it a first shot :)

**Comment by danbri** [comment]
The Python you can see in this repo is generally focussed on running and publishing the site, and are probably not a good fit (or stable APIs) for general usage.  You might find that the general RDF APIs from something like rdflib address some of the needs here, in that you can create data graphs via API call and then the library will handle things like generating legal JSON-LD syntax.

**Comment by vsoch** [comment]
ok cool! This is something I'll think more about / take a shot at coming up with a simple solution because I'll definitely need it down the line! For the site that I'm generating at [openschemas.github.io](https://openschemas.github.io) I'm using [map2model](https://www.github.com/openschemas/map2model) and I'm about to add validation functions to that. But for a client to interact with the schemas (and do some of the examples above) I think I'll make a similar, small related tool.

**Comment by vsoch** [comment]
Heyo! If you are interested, I created a schemaorg python module (see [verbose writeup here](https://vsoch.github.io/2018/schemaorg/)) and would love contributions and working with schema.org on this. It differs in what is provided in this repo because it intends to provide programmatic access to the specifications themselves, and help software developers to read / extract / dump out what they need to build software around the schemas. 

Here's a good entrypoint to a basic example and the repository. https://openschemas.github.io/schemaorg/

**Comment by henrieglesorotos** [comment]
Are you still using your solution @vsoch ? Considering doing something similar.

**Comment by vsoch** [comment]
I am happy to pick up work / development (and support you to contribute) if there is interest! In terms of actually using it, I haven't found a good use case for is so largely have not.
