### ISSUE TITLE
Need types for biographical and autobiographical materials and interviews

### ISSUE THREAD

**Issue by EnnexMB** [schemaorg/schemaorg#2063]
There's nothing in the hierarchy that touches on the concepts of interviews and of biographical and autobiographical materials. I'm not exactly sure where these go. An interview is an action, a creative work, and an event. Within creative works, biographical and autobiographical material can be a book, a speech, an article, a movie, a stage play (which doesn't seem to be a listed type), a radio program (again, no type for this, unless it's an episode of a series), etc. But, for example, for a book that's an autobiography, it really is insufficient to categorize it just as a book. The fact that it's an autobiography is the most significant thing about it. But it's also not okay to list autobiography as a subtype of book, because it could be an article, movie, etc.

Perhaps there's a better way to do this, but it looks to me like we need three new types:

- Thing > CreativeWork > Biographical
- Thing > CreativeWork > Autobiographical
- Thing > CreativeWork > Interview

I have suggested the first two terms as adjectivals because people usually think of "biography" and "autobiography" as refering to books, and we need these terms to be more general.

For their properties, a biographical would have an author (which would the speaker if it's a speech or radio program) and a subject person. For an interview, the author would be the interviewer and there would also be one or more subject persons. For an autobiographical, the author and subject person would be the same.

**Comment by Dataliberate** [comment]
These would be values for the genre property of CreativeWork and/or its
subtypes.

Either as text values:
   "genre": "Biography"
   "genre": "Autobiography"
   "genre": "Interview"
or URI values:
   "genre": "http://id.loc.gov/authorities/genreForms/gf2014026049"
   "genre": "http://id.loc.gov/authorities/genreForms/gf2014026047"
   "genre": "http://id.loc.gov/authorities/genreForms/gf2014026115"

Note the Library of Congress has wealth of definitions
<http://id.loc.gov/search/?q=&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2FgenreForms>
in this area.
~Richard


Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by danbri** [comment]
@EnnexMB - does that answer your question?

**Comment by EnnexMB** [comment]
It does, partly, thanks for asking. I'm still working on this and will probably have a follow-up question next week. Thank you.

**Comment by EnnexMB** [comment]
It makes sense to treat these categories as genres, but how am I supposed to know what values are valid?

Schema.org specifies `genre` as a property of `CreativeWork`, but the [webpage for `genre`](https://schema.org/genre) does not say anything about what values are valid. The examples on that page use a value in the form of a URL from the [Getty Vocabularies](http://vocab.getty.edu/). @Dataliberate [suggested above](https://github.com/schemaorg/schemaorg/issues/2063#issuecomment-422531155) using either the text values "Biography", "Autobiography", and "Interview" or [URL values from the Library of Congress](http://id.loc.gov/). Surely I can't use just any text value I choose or values from any vocabulary I come across on the Internet. So how do I know what values are valid for `genre` (or for other such properties)?
