### ISSUE TITLE
Is there a type that could be used to describe ferries?

### ISSUE THREAD

**Issue by vlahanas** [schemaorg/schemaorg#2068]
Similar to describing a Flight and an Airline, I would like to ask if there are similar types to describe a ferry trip.

**Comment by RichardWallis** [comment]
There is no specific ferry trip type.

You could however use the generic [Trip](https://schema.org/Trip) type, using the _name_ and/or _description_ properties to indicate it is a trip on a ferry.  Also the _provider_ Organization being presumably a Ferry company would also help.

**Comment by vlahanas** [comment]
Thank you for your help, that makes sense. Just another question (hopefully, not a silly one). Where inside the Organization object could the type of company being described, since Ferry Company is not an existing type?
