### ISSUE TITLE
Missing /Bridge as subclassOf /CivicStructure

### ISSUE THREAD

**Issue by redaktor** [schemaorg/schemaorg#207]
http://schema.org/CivicStructure

**Comment by danbri** [comment]
Added in @RichardWallis 's merge - https://github.com/schemaorg/schemaorg/pull/648/files#diff-200232fafee461b4217385c536cb093eR2331

**Comment by danbri** [comment]
This is queued up for review in the next release (sdo-ganymede). Thanks!
