### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by derekenos** [schemaorg/schemaorg#2073]
The "Offer" (and most of the other) schema link on:

https://schema.org/docs/schemas.html

links to:

https://1.3-4-1.schemaorgae.appspot.com/Offer

which results in this `SSL_ERROR_BAD_CERT_DOMAIN` error in Firefox 62.0 Ubuntu:

>1.3-4-1.schemaorgae.appspot.com uses an invalid security certificate. The certificate is only valid for the following names: *.appspot-preview.com, *.a.run.app, *.appspot.com, *.thinkwithgoogle.com, *.withgoogle.com, *.withyoutube.com, appspot-preview.com, appspot.com, run.app, thinkwithgoogle.com, withgoogle.com, withyoutube.com

**Comment by derekenos** [comment]
The issue has resolved itself. Good job, issue.
"Offer" now links to: https://schema.org/Offer
The others are fixed too.

**Comment by RichardWallis** [comment]
Thanks for spotting !
Working on making the  fix permanent.
