### ISSUE TITLE
Description for CreativeWork is wrong

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#2075]
The description beneath the breadcrumbs on [CreativeWork](https://schema.org/CreativeWork) reads:
> No comment

It should read:
> The most generic kind of creative work, including books, movies, photographs, software programs, etc.

Issue started occurring on [27 Sept. 2018](https://web.archive.org/web/20180927230058/https://schema.org/CreativeWork).

**Comment by RichardWallis** [comment]
Thanks @Aaranged for spotting.
More information towards helping improve the stability of the site.  Latest engineering fix went in on 27th - still more work to do.

**Comment by danbri** [comment]
@RichardWallis is this fixed? I'm not seeing it any more, at least.

**Comment by RichardWallis** [comment]
Yes it is.  

As I imply in my earlier response, there is more work to do on the stability front.  The latest upgrade has not fixed everything.  Strangely enough this particular new symptom has given me a clue to a new area of focus.

**Comment by RichardWallis** [comment]
Issue to be subsumed into issue #2060.
