### ISSUE TITLE
Update our RDFS to use cleaner idioms

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2076]
We have a lot of historically ugly RDFa in the RDFS+- definitions used in Schema.org.

The original reasoning was to try to have the schema files look useful in a human-facing browser view. This never really worked. 

The RDFa has repetitions in it that cause errors, and make it harder to understand. 

For a draft elsewhere I came up with a regex 

> subClassOf" href="http://schema.org/[^"]+">[^<]+</a>

... to help convert to markup like this:

>        <link property="rdfs:subClassOf" href="http://schema.org/Intangible" />

This will obviously need some care, and makes diffing with older versions via the surface syntax less useful. I think it's worth doing.

**Comment by danbri** [comment]
In Atom editor fwiw, 

Search:
> subClassOf" href="http://schema.org/([^"]+)">([^<]+)</a>
Replace:
> "rdfs:subClassOf" href="http://schema.org/$1"/>

**Comment by danbri** [comment]
And 

* <a property="http://schema.org/domainIncludes" href="http://schema.org/([^"]+)">([^<]+)</a> etc

**Comment by RichardWallis** [comment]
Introduction of .ttl files fixes this.
