### ISSUE TITLE
Add more export formats (e.g. as offered but obsolete at schema.rdfs.org)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#208]
schema.rdfs.org offers JSON and CSV views of schema.org. However it is un-maintained. We are now reasonably well set up to do more of this kind of thing within schema.org itself than when both sites were first launched.
- [ ] JSON(-LD)
- [ ] Turtle https://github.com/schemaorg/schemaorg/issues/317
- [ ] CSV
- [ ] Other?

**Comment by gebrits** [comment]
@danbri is this still on the agenda? Specifically looking for an up-to-date json-LD representation including attribute-types

**Comment by danbri** [comment]
Yup, this still matters...

**Comment by 3sv** [comment]
There is a json-ld representation at the root of schema.org that is served by content negotiation (accept header application/ld+json - explained in the wiki here: https://github.com/schemaorg/schemaorg/wiki/JsonLd)

@danbri Are there plans to allow partial requests in json-ld to schema.org, ie getting https://schema.org/Person in json-ld format?

**Comment by RichardWallis** [comment]
@3sv checkout the export formats section on meta-issue (#3) to see what's on the pending list. 

I'm hoping to get on to many of these soon.

**Comment by morseltech** [comment]
@RichardWallis when you say 'export format' do you mean 'alternative representations'? I can't see the point of having https://schema.org/Person in json-ld format if the URL is not https://schema.org/Person. Each representation should use content negotiation via the HTTP Accept header right?

**Comment by BigBlueHat** [comment]
@morseltech see the content of #1351. Specifically:
> Introduced content negotiation on per-term pages for the following accept types, mapping to the associated file extension types:...

Happy to see this happening, fwiw! 😁

**Comment by morseltech** [comment]
Awesome. When are these changes expected to be release on the site?

**Comment by danbri** [comment]
We're overdue for a release, I hope to finalize a release candidate this week, and to get it published this year.

**Comment by morseltech** [comment]
Fantastic news. This provides huge benefits, not least of which is people that as scared of RDF don't need to see the underlying RDF and also that each term reference becomes an example for modelling in json-ld. Good job schema.org team. Yay!

**Comment by pmackay** [comment]
May I ask, when might a CSV download be available?

**Comment by danbri** [comment]
Early access to CSV and related improvements: http://webschemas.org/docs/developers.html

This will be on the schema.org site in the next release.
