### ISSUE TITLE
Can we use define / document the subset of JSON-LD that doesn't rely on external context files?

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2080]
@RichardWallis would you mind taking a look at this?

Two immediate usecases:

1. our own schemas instead of using our baroque RDFS-in-RDFa-in-HTML5 syntax, we did look at using JSON-LD but the parser's dependency on reading in a ('the'?) Schema.org context file made it horribly confusing.

2. IoT. Schema.org in JSON-LD makes a lot of sense for some IoT scenarios, but only if it can be parsed without signalling across the internet to hosts of the vocabularies/schemas it is using.

If we can use @vocab instead of @context there should be a deterministic mapping from JSON-LD files into triples, without requiring consultation of a context. The cost is a little more verbosity - using defaults for thing-vs-thing, maybe always absolute URIs too.

/cc @vholland (and @rvguha who will say "just use MCF":)

**Comment by gkellogg** [comment]
The use (and avoidance) of external context files is under active discussion in w3c/json-ld-syntax#9 and w3c/json-ld-syntax#20 due for an in-depth discussion on the next call (2018-10-12) and/or at TPAC. We'd like to accommodate this usage pattern in JSON-LD 1.1; participation in the discussion encouraged.
