### ISSUE TITLE
Fix / advertise anchors for examples

### ISSUE THREAD

**Issue by tfrancart** [schemaorg/schemaorg#2081]
Last time I wanted to create a link to the Examples section of a class, or to a precise example in the page. 
It turns out that :

- it is possible to link to the "Examples" section (https://schema.org/Person#examples) but the anchor is nowhere visible other than in the HTML code
- examples do have anchors, again nowhere visible except in HTML code, and these anchors have strange names (id="Invoice-gen-265")

A behavior with the nice "link" icon appearing left to the title when we hover the mouse (à la github wiki : https://github.com/schemaorg/schemaorg/wiki) could be nice.
Having the same to link to the properties table and term definition would be wise.

**Comment by RichardWallis** [comment]
Nice suggestion
