### ISSUE TITLE
Add a property to JobPosting to describe restrictions on applicant location 

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2083]
Some jobs (particularly telecommuting jobs) have requirements on the applicant's location. For example, can work remotely, but must be in USA or Europe. I propose adding a property ```applicantLocationRequirements``` to describe this situation.

For example:

```
{
  "@context": "http://schema.org/",
  "@type": "JobPosting",
  "name": "Telecommute from anywhere in USA!",
  "applicantLocationRequirements": {
    "@type": "Country",
    "sameAs": "https://www.wikidata.org/wiki/Q30",
    "name": "USA"
  }
}
```

Note: This is separate from citizenship or work visa requirements, which I think are complicated enough that we should handle those separately.

**Comment by vholland** [comment]
See PR #2092

**Comment by RichardWallis** [comment]
Implemented in [release 3.5 ](https://schema.org/docs/releases.html#v3.5)

**Comment by alexrodba** [comment]
How would you restrain to only Europe if it is not a country?

**Comment by RichardWallis** [comment]
As the expected value type for the [applicantLocationRequirements](https://schema.org/applicantLocationRequirements) property is [AdministrativeArea](https://schema.org/AdministrativeArea) you could define it simply thus:
```
  "applicantLocationRequirements": {
    "@type": "AdministrativeArea",
    "sameAs": "http://www.wikidata.org/entity/Q458",
    "name": "European Union"
  }
 ```

**Comment by alexrodba** [comment]
Oh, that's brilliant, thank you!

**Comment by alexrodba** [comment]
It throws a warning: 
![image](https://user-images.githubusercontent.com/6558119/60985393-b7977600-a33d-11e9-9f52-c1572e87f0fb.png)

Was that expected?

**Comment by jvandriel** [comment]
That's a Google specific issue (which aren't handled here). If you run the markup through http://linter.structured-data.org/ all's fine.

**Comment by rostameali110110-blip** [comment]
سلام.عزیزان من متاسفانه توانایی پرداخت پول چند جلد حکمت سه جلد را دارا نمی باشم . چنانچه لطف کنید بفرستید در اولین فرصت مبلغ ذکر شده را ارسال می کنم . سپاسگزارم.
البرز رستمی
