### ISSUE TITLE
json-ld context has temporalCoverge as @id not @value; also encodingFormat is tricky

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2087]
"temporalCoverage": { "@id": "schema:temporalCoverage", "@type": "@id"},
in https://schema.org/docs/jsonldcontext.json resulting in bad output in json-ld playground etc.

Encoding Format sort of could be either ... but I'm seeing 

_:b3 <http://schema.org/encodingFormat> <https://json-ld.org/playground/CSV> .

**Comment by RichardWallis** [comment]
Not sure exactly what you are saying.

What change would you recommend in https://schema.org/docs/jsonldcontext.json to fix this?

**Comment by RichardWallis** [comment]
@danbri  - is this still an issue?

If yes, give me an example of what it should be.

**Comment by danbri** [comment]
It's only an issue for json-ld tools not updated for 1.1 afaik
