### ISSUE TITLE
remove "logo" as a required property on "publisher/@type=Organization"

### ISSUE THREAD

**Issue by regineheberlein** [schemaorg/schemaorg#2088]
Request: remove "logo" as required property on publisher/@type=Organization.

Description: 
I'm getting an error in the [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) due to a missing "logo" property on "publisher/@type=Organization" when describing a blog post:

`"blogPost": {
        "headline": "Isabella Piccini",
        "publisher": {
            "@type": "Organization",
            "name": "The Trustees of Princeton University"
        },`

The "logo" property is NOT required (i.e. doesn't throw the same error), however, on @type=Blog/publisher/@type=Organization:

` "@type": "Blog",
    "headline": "Graphic Arts Collection",
    "url": "www.graphicarts.princeton.edu",
    "publisher": {
        "@type": "Organization",
        "name": "The Trustees of Princeton University"
    },`

My feeling is not every organization has a logo, so it shouldn't be a required property. At the very least, though, the requirement should be consistent.

**Comment by RichardWallis** [comment]
In the Schema.org vocabulary there are no required properties or cardinality constraints.

The Structured Data Testing Tool is a service provided by Google for testing schema.org output with respect to their services.

Schema.org isn't Google - we can't offer any kind of support for Google products and services here. You might try the Google Product Forums, eg https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Astructured-data%7Csort:relevance%7Cspell:false

**Comment by regineheberlein** [comment]
Thanks @RichardWallis for the constructive answer and redirect.
