### ISSUE TITLE
encodingFormat as property of MediaObject

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#2098]
https://schema.org/MediaObject shows encodingFormat as a property from MediaObject and as a property inherited from CreativeWork, which seems wrong.

**Comment by RichardWallis** [comment]
Does seem a little odd - will investigate.

**Comment by jschiavetto** [comment]
I've been searching for Software Encoding, but i got nothing. Somebody can help-me?

**Comment by jschiavetto** [comment]
> Does seem a little odd - will investigate.

Did you found something?

**Comment by smrgeoinfo** [comment]
@jschiavetto 'Software Encoding' do you mean something like [Computer Language](https://schema.org/ComputerLanguage)

**Comment by RichardWallis** [comment]
Checking out [MediaObject](https://schema.org/MediaObject) the _encodingFormat_ property is defined as both a direct property of _MediaObject_ and one inherited from _CreativeWork_.

From a usage of the vocabulary point of view, this duplication has no impact.  The reason it has occurred is that the definition of the _MediaObject_ type specifically includes that property to emphasise its relevance to a MediaObject.

@jschiavetto can you expand on your use case  as to why software encoding is relevant to a media object.
