### ISSUE TITLE
New type: Degree

### ISSUE THREAD

**Issue by rleslie-georgefox** [schemaorg/schemaorg#2099]
First time posting on here, so I apologize in advance for the protocol mistakes I'm likely making.

I'd like to propose a new type for degree programs.

Hierarchically, I'm not sure this makes sense under:

- Action
- CreativeWork
- Event
- Organization
- Person
- Place

Maybe Intangible or Product? Or something new?

Properties could include degree category (associate, bachelor's, master's, doctorate), duration, number of courses, field of study, cost, accrediting body, etc.

Does this seem like a useful addition?

**Comment by philbarker** [comment]
Hello. Welcome. Sorry I missed this when you posted it, but I think we have what you need covered.

If by "degree" you mean the course of study leading to a degree such as a B.S. or M.Sc., then [Course](http://schema.org/Course) is what you want.

More likely by "degree" you mean the credential awarded on successful completion of such a course. So this is a type of EducationalOccupationalCredential, so see issue #1779 the discussions around the W3C [EOCred community group](https://www.w3.org/community/eocred-schema/) on the [mail list](https://lists.w3.org/Archives/Public/public-eocred-schema/) and [wiki](https://www.w3.org/community/eocred-schema/wiki/Main_Page), and the [pull request](https://github.com/schemaorg/schemaorg/pull/1978) closing issue 1779. This has been merged and so will be reviewed for possible inclusion in the pending section of the next version of schema.org.

**Comment by rleslie-georgefox** [comment]
I did mean the latter, and you're right, it does look like you've got it
covered. Thank you, Phil!

What's the best way to track progress on this?

**Comment by philbarker** [comment]
Not sure how best to track this now that the pull request is merged and issue 1779 closed. Next step is review for schema.org version 3.5, so maybe follow #2052 which is the tracking issue for that.

**Comment by rleslie-georgefox** [comment]
Thank you!
