### ISSUE TITLE
ListItem page not rendering correctly, much information missing

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#2101]
The [ListItem](https://schema.org/ListItem) page is rendering incorrectly.  Its breadcrumb path, description, property table and more are missing (it should look like [this](https://web.archive.org/web/20180901000056/https://schema.org/ListItem)).

Looking at Wayback it appears to have been this way since the end of September 2018.

![listitem](https://user-images.githubusercontent.com/1033730/48956804-e6c1ba00-ef09-11e8-996a-beeb36836e30.png)

**Comment by RichardWallis** [comment]
Display anomaly corrected.

Closing in favour of issue #2060
