### ISSUE TITLE
What is a RadioStation?

### ISSUE THREAD

**Issue by njh** [schemaorg/schemaorg#2102]
Hi,

I am looking at adding schema.org properties to my website [radiodns.uk](https://www.radiodns.uk/). 

The website has five main concepts (based on the RaidoDNS standard - TS 102 818 v3.1.1):

* **Authority** (an organisation that provides the details of services, this may be the broadcaster or a technology provider)
* **Bearer** a specific frequency or transmission
* **Multiplex** (a DAB multiplex aka Ensemble)
* **Service** (a radio station, broadcast on multiple transmissions)
* **Transmitter** (a transmission site, that broadcasts one or more services)

<img src="https://github.com/njh/radiodns-uk/blob/master/docs/data-model.png?raw=true" width="533" height="388" alt="Data Model Diagram" />

So far I have mapped the following on to schema.org:

* **Authority**: https://schema.org/Organization
* **Bearer**: https://schema.org/BroadcastFrequencySpecification ? (see #1004)
* **Multiplex**: ❌
* **Service**: https://schema.org/RadioChannel
* **Transmitter**: https://schema.org/Place ?

But it has left me wondering what a [RadioStation](https://schema.org/RadioStation) is? The description of 'A radio station' isn't very descriptive. It looks like it is an organisation that broadcasts one or more RadioChannels?

To me a RadioStation would be a better name for a RadioChannel. The word 'Channel' is rarely used when talking about radio.

Thanks,

nick.

**Comment by njh** [comment]
Thank you very much!

I think I have enough to start implementing and I will see what else comes up while I do that.
This should be a useful reference for other people too.

**Comment by thadguidry** [comment]
@MichaelAndrews-RM Would you mind adding the above from Vicky into our Wiki ?

**Comment by thadguidry** [comment]
@RichardWallis @danbri Could we improve the RadioStation description as well ?

I propose:
> The organization that runs a radio broadcasting service, traditionally called a "radio station".  For the concept of a radio broadcasting service, see https://schema.org/BroadcastService

**Comment by RichardWallis** [comment]
Sounds like a useful suggestion.

Reopening to flag for actioning.

**Comment by njh** [comment]
Note I am now publishing:

* 425 Broadcast Services: https://www.radiodns.uk/services
  - with BroadcastFrequencySpecification for the FM bearers
* 1033 Places (Transmitters) - example: https://www.radiodns.uk/transmitters/se222281

**Comment by thadguidry** [comment]
@njh It'd be nice to see on your services page, a column with a checkmark for RadioTag support, instead of having to click onto each one to see if it supports it.

For multiplexes, There is no description field (they are useful) on your JSON on https://www.radiodns.uk/multiplexes/c1ce.json

For Multiplexes: I think we are still lacking guidance either on the description of BroadcastService or elsewhere that notes if/how a Multiplex can be structured? or am I wrong and its hiding somewhere else?

**Comment by njh** [comment]
1. What is your interest in RadioTag? [RadioTag](http://radiodns.wpengine.com/wp-content/uploads/2014/02/rtag01_v100_draft_7.pdf) has not been officially standardised yet, although Global and BBC have had public implementations. Some people have actually suggested that I remove references to it from the site.

2. Multiplex information currently comes from Ofcom. They don't provide a description. I guess I could possibly synthesise one from the other properties of the multiplex "SDL National is a multiplex with X transmitters and provides Y services". The other thing I have been considering is finding a way to lookup multiplexes in Wikidata. So a description could come from there: https://www.wikidata.org/wiki/Q25022034

3. I don't believe there is anything that would allow modelling the concept of a multiplex in schema.org at the moment. The closest thing is probably 'CableOrSatelliteService'. A DAB Multiplex is probably similarly enough to a DVB multiplex to have one concept for both.

**Comment by thadguidry** [comment]
1.  Oh, I didn't know that RadioTag was not standardised... in that case, ignore.
2.  The Wikidata lookup seems useful to get the description.  (seems you are the one typing those, so cool)
3.  I'll leave this in your hands for suggestions/proposals since you seem more qualified. (and we appreciate your insight)

**Comment by RichardWallis** [comment]
Closed via commit b666adb
