### ISSUE TITLE
Height above Sea Level

### ISSUE THREAD

**Issue by njh** [schemaorg/schemaorg#2104]
Hi,

Is it possible to specify a [Place](https://schema.org/Place)'s height above sea level?
I guess it would need to include unit (mine are measured in metres)

nick.

**Comment by Dataliberate** [comment]
‘elevation’ is a property of the ‘GeoCoordinates’ type you can assign to the ‘geo’ property of ‘Place’

It expects values defined by the WGS 84 standard. 

~Richard.

**Comment by njh** [comment]
Ah, of course, thanks @Dataliberate!

It would be good to be explicit about the units for elevation:
https://schema.org/elevation

Metres v. fractions of a kilometre?
And I am sure Americans would try using Feet...

**Comment by Dataliberate** [comment]
Not found a specific reference in my limited search from a phone but things like geojson seem to assume metres above mean sea level.  

If you supply the value as a number, I also would assume that.  If you supply it as a text, then things like 1,000m & 3,280ft would be understood by search engines I believe.  

But I don’t ‘know’ any of that as a fact. 

Anyone else up on this ?

~Richard 

Sent from my iPhone

**Comment by VladimirAlexiev** [comment]
All CRS that I know seem to measure elevation in Meters. So I think a clarification to that effect is warranted.
@njh could you please edit the issue title appropriately?

>If you supply it as a text, then things like 1,000m & 3,280ft would be understood by search engines I believe.

I doubt that very much, but Schema always allows Text. 
So an example like "3280 ft" could be given, with a warning that the value may not be interpreted appropriately. I've removed the comma and added a space for easier parsing, eg https://ci.mines-stetienne.fr/lindt/index.html will actually interpret this correctly, but only in Jena and given an appropriate datatype, eg
`"3280 ft"^^cdt:ucum`

**Comment by RichardWallis** [comment]
Recommend description of elevation property should be enhanced thus:

The elevation of a location (WGS 84). Values are of the form '<Number> <unit of measure>'. E.g., '1,000 m', '3,200 ft'.  Numbers alone should be assumed to be a value in metres.

**Comment by njh** [comment]
Thanks for this improvement!

**Comment by danbri** [comment]
For reference, this is what we eventually put into the (very informal) w3c wgs84 basic geo vocab:

```
<rdf:Property rdf:about="http://www.w3.org/2003/01/geo/wgs84_pos#alt">
 <rdfs:domain rdf:resource="http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing" />
 <rdfs:label>altitude</rdfs:label>
 <rdfs:comment>The WGS84 altitude of a SpatialThing (decimal meters above the local reference ellipsoid).</rdfs:comment>
</rdf:Property>

See https://www.w3.org/2003/01/geo/ http://www.w3.org/2003/01/geo/wgs84_pos
