### ISSUE TITLE
Add subtitleLanguage to BroadcastEvent

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2110]
There are times when broadcasters add subtitles, particularly of live events. It would be nice to be able to specify the subtitle language by expanding the domain of ```subtitleLanguage``` to include ```BroadcastEvent```.

**Comment by vholland** [comment]
Implemented as PR #2142

**Comment by vholland** [comment]
@danbri I realize I had accidentally deleted the branch before this can be merged.

**Comment by RichardWallis** [comment]
Implemented in [Release 4.0](https://schema.org/docs/releases.html#v4.0)
