### ISSUE TITLE
Tie JSON-LD with microdata: is the Structured Data Testing Tool buggy or is my code erroneous?

### ISSUE THREAD

**Issue by e-orlov** [schemaorg/schemaorg#2115]
I'm trying to tie JSON-LD (WebPage) with BredacrumbList (microdata) with id/itemid and the Testing Tool interpretes my code not as i expect. The code is:

```
<script type="application/ld+json">
{
"@context": "http://schema.org",
"@type": "Webpage",
"id": "https://www.example.com#Webpage",
"breadcrumb": {
"@type": "BreadcrumbList",
"@id": "https://www.example.com#BreadcrumbList"
}
}
</script>

<ol itemscope itemtype="http://schema.org/BreadcrumbList" itemid="https://www.example.com#BreadcrumbList">
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
<a itemprop="item" rel="up up up" title="a" href="/a/">
<span itemprop="name">a</span></a>
<meta itemprop="position" content="1" /></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
<a itemprop="item" rel="up up" title="b" href="/b/">
<span itemprop="name">b</span></a>
<meta itemprop="position" content="2" /></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
<a itemprop="item" rel="up" title="c" href="/c/">
<span itemprop="name">c</span></a>
<meta itemprop="position" content="3" /></li>
</ol>

```
I expect the testing tool recognizes the relation of `WebPage`, `BreadcrumbList` and its `ListItems` - but no: WebPage and BreadrumbList are displayed as two data types and on Webpage the testing tool triggers an error about non-existing, but required `ListItem`, which should in my understanding be inherited from the microdata BreadcrumbList.

**The question is**: does the tool have problems with interpretation of different kinds of markup, or is it my code, which is erroneous?

**Comment by danbri** [comment]
Hi! Sorry, Schema.org is not an appropriate place for Google support questions.  Can you take it to https://productforums.google.com/forum/#!categories/webmasters/structured-data ? (please drop a cross-link in here so folks can follow the trail...)
