### ISSUE TITLE
bibliograph.net getting obsolete?

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#2116]
Hi @RichardWallis!
http://bibliograph.net looks nice but seems that it's not maintained. It says "The Editor of BiblioGraph.net will track changes to the published terms from Schema.org and update this site to reflect them". But:
- still has http://bibliograph.net/free, whereas the property has been renamed to https://schema.org/isAccessibleForFree, which says "Supersedes free"
- still has http://bibliograph.net/publishedBy, whereas this has been adopted as https://schema.org/publishedBy
- http://bibliograph.net/docs/feedback.html is broken

Many of the terms are now adopted in https://bib.schema.org/, but not all (eg Globe and Kit are missing). 
What is the status of bibliograph.net, and maybe a warning/deprecation notice on the home page is warranted?

**Comment by danbri** [comment]
I'll leave this with Richard to track and follow up, but I don't think we need an open issue at schema.org for it.
