### ISSUE TITLE
Dataset search engine working with Linked data descriptions based on W3C ontologies ?

### ISSUE THREAD

**Issue by alko-k** [schemaorg/schemaorg#2118]
Dear all, 

dataset search engine understands/indexes pages including schema.org descriptions in a certain json format. Is there a plan for the dataset search to index Linked Data pages published as e.g. json_LD or RDF/XML, that are annotated with schema.org or other standardised ontologies and vocabularies?

Many thanks
Alexandra

**Comment by RichardWallis** [comment]
Hi! Sorry, Schema.org is not an appropriate place for Google support questions. 

Can you take it to https://productforums.google.com/forum/#!categories/webmasters/structured-data ?

**Comment by alko-k** [comment]
Thanks  Richard
