### ISSUE TITLE
Problems with rdfs:class missing in places on extensions

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#2119]
Some extensions, like [health-lifesci](https://github.com/schemaorg/schemaorg/blob/master/data/ext/health-lifesci/med-health-core.rdfa), are using `typeof="rdfs:Class"` but there's some kind of disconnect I cannot quite put my finger on...

Context:  TPT and I are working on a Schema.org <-> Wikidata mapping review tool and noticed the following rule was thrown up as an error within the tool:
**http://schema.org/Psychiatric is mapped as equivalent class to psychiatry (Q7867) but is not an instance of rdfs:Class or owl:Class.**

In reviewing the Schema.org output, I see the following:
```
schema:Psychiatric a schema:MedicalSpecialty ;
    rdfs:label "Psychiatric" ;
    schema:isPartOf <http://health-lifesci.schema.org> ;
    schema:sameAs <https://schema.org/Psychiatric> ;
    rdfs:comment "A specific branch of medical science that is concerned with the study, treatment, and prevention of mental illness, using both medical and psychological therapies." ;
    rdfs:subClassOf schema:MedicalBusiness .
```
```
schema:MedicalSpecialty a rdfs:Class ;
    rdfs:label "MedicalSpecialty" ;
    schema:isPartOf <http://health-lifesci.schema.org> ;
    schema:sameAs <https://schema.org/MedicalSpecialty> ;
    rdfs:comment "Any specific branch of medical science or practice. Medical specialities include clinical specialties that pertain to particular organ systems and their respective disease states, as well as allied health specialties. Enumerated type." ;
    rdfs:subClassOf schema:MedicalEnumeration,
        schema:Specialty .
```

Thoughts?  Something I am unaware of or overlooking?

**Comment by RichardWallis** [comment]
```schema:MedicalSpecialty``` is an Enumeration subclass, whereas ```schema:Psychiatric``` is an enumeration value

**Comment by thadguidry** [comment]
But Psychiatric can also be a subClassOf of [OccupationalTherapy](https://schema.org/OccupationalTherapy).
Example:
Psychiatric is a kind of OccupationalTherapy provided typically from a Medical Specialist in the Medical Speciality of Psychiatry.

This is the kind of things that the mapping review tool is surfacing for us.  A few bits of, how shall I say, expanded viewpoints? where we might want to revisit or review the structure in Schema.org for the better?

**Comment by RichardWallis** [comment]
[Psychiatric](https://health-lifesci.schema.org/Psychiatric) is only defined [in Schema.org] as one of the Enumeration members of [MedicalSpecialty](https://health-lifesci.schema.org/MedicalSpecialty)

[In Schema.org] [OccupationalTherapy](https://schema.org/OccupationalTherapy) has no subtypes. The particular speciality of an instance being qualified, by providing as a value to its _relevantSpecialty_ property (inherited from MedicalEntity) a _MedicalSpecialty_  enumeration member, such as  _Psychiatric_.

@thadguidry Theoretically we could address how _Psychiatric_ is defined and how the example definition you provide could be accommodated, in ways other than providing it as a value for the _relevantSpecialty_ of an OccupationalTherapy entity.

However, I suggest that the same thoughts would have to be applied to the other 40+ enumeration members of _MedicalSpecialty_.  Something I am not too sure we would want to embark upon.

**Comment by thadguidry** [comment]
We absolutely want to embark upon.
You are forgetting how each one of the MedicalSpecialty's is also a Field of Study.
We had previously debated and said that ANYTHING could be a Field of Study with enough interest... Pie Baking, etc.

In Freebase, we had "FieldOfStudy".  It was useful to see the links between OccupationalCategory and Fields of Study.  This currently cannot be done because Thing:subjectOf cannot take another Thing, only CreativeWork or Event.
And @philbarker 's Course and Educational endeavors are also lacking links between a Course and Field of Study, and no property.
Person:knowsAbout could take a FieldOfStudy as well.

It's a gaping hole that we have.  How to plug it.  If we agree that anything could be studied, then that's fine, but let's plug this hole.  We have Multitype now, so that helps.  But holding these back as only Enumerations is extremely limiting in areas of Education, Jobs, etc.

**Comment by RichardWallis** [comment]
OK the original premiss of this issue has evolved into something else.

As the vocabulary is currently defined, there are not missing ```rdfs:class``` statements.

As you identify potentially there is a much broader issue that goes beyond MedicalSpecialty's.  I suggest that a more appropriately titled issue be created in which can rehearse potential solutions, ramifications, and expected usages.

To that end I suggest that this particular issue should be closed,

**Comment by thadguidry** [comment]
Closing.

**Comment by thadguidry** [comment]
New Issue #2122
