### ISSUE TITLE
property of property

### ISSUE THREAD

**Issue by pldawn** [schemaorg/schemaorg#2120]
http://schema.org/alumniOf is a http://schema.org/Property, not a http://schema.org/Class.

So how can I directly define a http://schema.org/Property of a http://schema.org/Property (such as http://schema.org/Role's function) ?

**Comment by RichardWallis** [comment]
@pldawn I am a little confused as to what is the basis of your question so I will provide some, hopefully helpful, background.

Firstly a general comment, building upon the basic [documentation](https://schema.org/docs/datamodel.html), about [Property](https://meta.schema.org/Property) and other terms from the [meta.schema.org](https://meta.schema.org/) extension:

> The meta extension contains terms primarily designed to support the implementation of the Schema.org vocabulary itself. It includes terms such as Class, Property, domainIncludes and supersededBy. They are not currently advocated for widespread use across the web.

[alumniOf](https://schema.org/alumniOf) as you indicate is indeed a Property, with two main attributes as defined in  [schema.rdfa](https://github.com/schemaorg/schemaorg/blob/master/data/schema.rdfa), and similar files, that specify the current state and shape of the vocabulary:

- [domainIncludes](https://meta.schema.org/domainIncludes) - indicates which type(s) ([Class](https://meta.schema.org/Class)) the Property is expected to be used with.  In the case of alumniOf there is only one domain includes -  [Person](https://schema.org/Person).

- [rangeIncludes](https://meta.schema.org/rangeIncludes) - indicates which type(s) ([Class](https://meta.schema.org/Class)) are the expected value(s) to be assigned to the property in instance data.  In the case of alumniOf there are two rangeIncludes statements - [EducationalOrganization](https://schema.org/EducationalOrganization) & [Organization](https://schema.org/Organization)
_Note 1_: All Schema defined Types (Thing, or subtypes of Thing and its subtypes)  and [Data Types](https://schema.org/docs/full.html#datatype_tree) are valid values for a rangeIncludes definition.
_Note 2_: There are special cases that apply, within Schema.org, that effectively add two default types to the rangeIncludes of _all_ properties - [Text](https://schema.org/Text) & [Role](https://schema.org/Role).  This provides flexibility for a text value to be used when a full type definition of a thing, or its URL, is not available in instance data.   Also, in the case of Role, it enables the ability to qualify the relationship between a property and its value. (Not going into detail here, for more info see [The Role of Role in Schema.org](https://dataliberate.com/2015/04/15/the-role-of-role-in-schema-org/)) 

Back to your question, and based upon this background; what are you trying to achieve?

**Comment by danbri** [comment]
(I'm going to go ahead and close this issue, as it doesn't seem to be something we can address by improving schema.org. We can keep chatting here, but the project has way too many open issues and needs to focus.)

In general in our approach, properties like alumniOf aren't instantiated in the same way that classes like Person are. The Role mechanism is a (somewhat awkward) workaround for that.  However if you were using schema.org properties to label the edges in a graph database using the Property Graph data model, you could attach meta-information to each occurrence of alumniOf (e.g. from=, to= dates). The main markup standards we use - JSON-LD, Microdata and RDFa - do not have this facility.
