### ISSUE TITLE
Is there any schema for the forum

### ISSUE THREAD

**Issue by tryazi** [schemaorg/schemaorg#2123]
Is there any application for forum pages. Discussforumposting is not enough

**Comment by RichardWallis** [comment]
What more are you looking for?

**Comment by tryazi** [comment]
I've used it and have never seen an impact on google search results. image to give the warning. In every discussion can not take place in the picture.

The results I expect are listing the forum topics such as QA. That's the truth.

**Comment by tryazi** [comment]
> What more are you looking for?

I've used it and have never seen an impact on google search results. image to give the warning. In every discussion can not take place in the picture.

The results I expect are listing the forum topics such as QA. That's the truth.

**Comment by RichardWallis** [comment]
OK - there are two aspect to this.

Firstly, the capabilities of the [Schema.org] vocabulary to enable, or not, the description of a forum and the postings within it.  If there are any inadequacies in this either with the vocabulary model itself, or the description of its terms, or the associated examples, this is the correct place to make specific suggestions and proposals as to how things can be improved.

Secondly, there is the use that data consumers (eg. Google, Bing, Yahoo!, etc.) make of data shared using the vocabulary.  If there are questions or issues in that area, this is not the appropriate place for such support questions.  A more appropriate place (for Google) might be https://productforums.google.com/forum/#!categories/webmasters/structured-data

**Comment by tryazi** [comment]
Thanks Richard
