### ISSUE TITLE
Can SportsEvent use StadiumOrArena as its location?

### ISSUE THREAD

**Issue by DaveyJake** [schemaorg/schemaorg#2124]
I apologize if this is an obvious question but based on all that I've read, the website does not explicitly say that a `SportsEvent`'s `location` can be of the type `StadiumOrArena`.

I'm currently drafting a proposed schema for all upcoming international rugby matches and I'm unsure if the following example I'm using is correct:

```javascript
{
  '@context': 'http://schema.org',
  '@type': 'SportsEvent',
  'location': {
    '@type': 'StadiumOrArena',
    'name': 'Sam Boyd Stadium',
    'address': {
      'addressCountry': 'USA',
      'addressLocality': 'Las Vegas',
      'addressRegion': 'NV',
      'postalCode': '89122',
      'streetAddress': '7000 E Russell Rd',
    }
  }
}
```

Again, my apologies if this is rather obvious but I just want to make sure I'm following the hierarchy correctly.  Any thoughts would be much appreciated.

Cheers!

**Comment by RichardWallis** [comment]
The simple answer is: Yes.

The [location](https://schema.org/location) property has expected types that include _Place_,  [StadiumOrArena](https://schema.org/StadiumOrArena) is a subtype of _Place_ so is a valid type to use on that property.
