### ISSUE TITLE
Add nsn (nato stock number) for product IDs

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2126]
See also https://en.wikipedia.org/wiki/NATO_Stock_Number

> The NATO stock number (NSN) is an identifier used to identify products that are sold armies that are part of NATO or allied with it. This includes various supplies (batteries, personal gear) which are sold in the general market.

> The NSN is well defined, with a structure and clear allocation rules, it is useful for products that are not typically identified by a GTIN. 

The NSN can be used to group products that have the same specification in cases where GTIN is not available. 

Proposal:
* The nsn field is a new field of schema.org/Product that specifies the NSN of the product. 

(this proposal came from conversations with colleagues at Google Shopping, who report that this field is widely used in several nations)

**Comment by nicolastorzec** [comment]
+1  on adding NSN to Product.

On a related note:
* Would it make sense to explicitly distinguish the product identifiers that can be used to search or group or match products across merchants, from the product identifiers that can't?
* I think it's a common use case, and users are already confused with terms like SKU, GTIN, UPC, etc.
* It could take various forms: e.g., a note in the descriptions, tags, sub-properties, etc.

**Comment by MichaelAndrews-RM** [comment]
Clearly having common product identifiers is a need shared by many publishers.  While GTIN is probably the most universal product identifier, other identifiers will also be useful in different scenarios.

We if can agree on which identifiers schema.org wants to support/promote, I will be be happy (with the expert insight of @thadguidry) to write up community documentation relating to what to mention, and how to express it in schema.org.

**Comment by thadguidry** [comment]
GTIN, EAN, UPC, SKU (that covers 99% of all world markets, including China who now uses GS1 standards with GTIN https://www.gs1.org/articles/1977/alibaba-group-gs1-gs1-china-gdsn-project-joint-announcement )

**Comment by MichaelAndrews-RM** [comment]
I understand that the original request related to:

>products that are not typically identified by a GTIN.

GTIN is extensive, but not comprehensive.  It has great coverage of consumer goods such as clothing but may not be as thorough for B2B products.  Geographic coverage is important, but product coverage is also a consideration.

**Comment by thadguidry** [comment]
@MichaelAndrews-RM Sure, get some more examples of how to use Product Identifiers that are "not common".  NSN is just one of those.  This proposal @danbri has for a separate "nsn" property is fine, but we need these kinds of examples also added to the http://schema.org/Product examples as well as the Wiki explaining the array method.  I have had to explain this to a few other folks offline, so I know its something that trips them up.

```json
{
  "@context": "http://schema.org",
  "@type": "Product",
  "productID":  ["nsn:123456","asin:991133","barney:RugsackCanvasBlack123"],
  "description": "U.S. Army official canvas rugsack (takes a licking keeps on kicking)",
  "name": "Rugsack, canvas, black"
}

**Comment by danbri** [comment]
https://webschemas.org/nsn

**Comment by nsnlookupjn** [comment]
We have implemented the NSN field for all NATO NSNs at our site [https://www.nsnlookup.com](https://www.nsnlookup.com)

If you are adding the NSN Field then you may want to consider adding the CAGE Code field to Brand and Organization as this is the very well defined Unique Entity Identifier used by NATO Countries to identify approved and non-approved sources of each NSN as well as all Government Contractors to NATO for both Products and Services.

[https://en.wikipedia.org/wiki/Commercial_and_Government_Entity_code](https://en.wikipedia.org/wiki/Commercial_and_Government_Entity_code)

I am a 30-year veteran of the NATO Codification Database and its structures if anyone would like to reach to me directly for more discussion and information.
