### ISSUE TITLE
eligibleRegion and ineligbleRegion have different associated types

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#213]
http://schema.org/eligibleRegion
http://schema.org/ineligibleRegion

eligibleRegion is applicable on more types, but fails to allow Place.

ineligibleRegion is applicable on fewer types (not Demand or DeliveryChargeSpecification), and anticipates Place but not GeoShape, Text.

There is no obvious reason for these properties to vary. 

Exact proposal:
 
* [ ] Add: http://schema.org/ineligibleRegion domainIncludes Demand, DeliveryChargeSpecification.
* [ ] Add: http://schema.org/ineligibleRegion rangeIncludes GeoShape, Text
* [ ] Add: http://schema.org/eligibleRegion rangeIncludes Place

(We might also consider their relationship to Action types while we're at it - spawn separate issue?)

**Comment by danbri** [comment]
I think we should do this.

**Comment by chaals** [comment]
agreed

**Comment by tmarshbing** [comment]
+1

**Comment by mfhepp** [comment]
I submitted a pull request that fixes this: https://github.com/schemaorg/schemaorg/pull/392.

**Comment by danbri** [comment]
Thanks @mfhepp 

What we have now (after the pull request was merged), for ref:

rdfa data/schema.rdfa | grep eligibleRegion | egrep 'domain|range' | sort
    <http://schema.org/eligibleRegion> <http://schema.org/domainIncludes> <http://schema.org/DeliveryChargeSpecification> .
    <http://schema.org/eligibleRegion> <http://schema.org/domainIncludes> <http://schema.org/Demand> .
    <http://schema.org/eligibleRegion> <http://schema.org/domainIncludes> <http://schema.org/Offer> .
    <http://schema.org/eligibleRegion> <http://schema.org/rangeIncludes> <http://schema.org/GeoShape> .
    <http://schema.org/eligibleRegion> <http://schema.org/rangeIncludes> <http://schema.org/Place> .
    <http://schema.org/eligibleRegion> <http://schema.org/rangeIncludes> <http://schema.org/Text> .
    <http://schema.org/ineligibleRegion> <http://schema.org/domainIncludes> <http://schema.org/DeliveryChargeSpecification> .
    <http://schema.org/ineligibleRegion> <http://schema.org/domainIncludes> <http://schema.org/Demand> .
    <http://schema.org/ineligibleRegion> <http://schema.org/domainIncludes> <http://schema.org/Offer> .
    <http://schema.org/ineligibleRegion> <http://schema.org/rangeIncludes> <http://schema.org/GeoShape> .
    <http://schema.org/ineligibleRegion> <http://schema.org/rangeIncludes> <http://schema.org/Place> .
    <http://schema.org/ineligibleRegion> <http://schema.org/rangeIncludes> <http://schema.org/Text> .

**Comment by mfhepp** [comment]
that looks good to me
