### ISSUE TITLE
BreadcrumbList page lacks breadcrumbs, property table

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#2134]
At time of writing [the BreadcrumbList page](https://schema.org/BreadcrumbList) lacks breadcrumbs and any entries in its property list.

This is how the first screen appears currently:
![breadcrumblist-current](https://user-images.githubusercontent.com/1033730/51876186-948f8180-231c-11e9-9b70-0fa018f19cde.png)

This is how the first screen _should_ appear ([Wayback capture of 15 Jun. 2018](https://web.archive.org/web/20180615002631/https://schema.org/BreadcrumbList)):
![breadcrumblist-20180615](https://user-images.githubusercontent.com/1033730/51876213-ae30c900-231c-11e9-955b-c05a7c67f791.png)

Note that this mirrors some of the rendering issues I reported in now-resolved issue #2101.

I'm not sure that anything can be done to ameliorate these rendering bugs, but I think the fact they keep recurring suggests that any logic that _can_ be applied to prevent them from appearing (e.g. some sort of automated QA routine) would be highly beneficial, as these bugs aren't inconsequential.  To use this current issue as an example, a "power user" like myself can tell that because (as per the description) that a "BreadcrumbList is an ItemList" that it's a more specific type of ItemList, and that ItemList properties are then available when marking up the type.  But those unfamiliar with the schema would likely be unaware of where this type falls in the hierarchy, and so be unaware or uncertain of which properties they can use here.

**Comment by RichardWallis** [comment]
Display anomaly corrected.

Closing in favour of issue #2060
