### ISSUE TITLE
Create a new MediaGallery type

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2139]
Schema.org has http://schema.org/ImageGallery, but increasingly pages are collections of mixed-media. It would be nice to have http://schema.org/MediaGallery for this use case. ImageGallery could then be made a subtype of MediaGallery.

**Comment by danbri** [comment]
We should do this! 

Can we say anything about how MediaGallery and MediaObject relate? A mixed-media e.g. JSON-LD example would be great.

**Comment by danbri** [comment]
Would ImageGallery be subtype of MediaGallery?

**Comment by gmackenz** [comment]
Yes, a subtype (see [https://github.com/schemaorg/schemaorg/issues/2139#issue-407793956](vholland) above)

**Comment by danbri** [comment]
Ah I missed that sentence, thanks @gmackenz!

**Comment by gmackenz** [comment]
I'm almost certain I did this wrong Dan, where should have the commits been be set to push to? Certainly not schemaorg:master... Been too long since I've edited in Schema.Org (or used GitHub).

**Comment by vholland** [comment]
Included in schema.org 6.0
