### ISSUE TITLE
Expand the range of 'mainContentOfPage' to Thing

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#215]
http://schema.org/mainContentOfPage

Being able to indicate the main Entity of a WebPage has been discussed several times during 2014 yet nothing has been done about it so far.

The general consensus was that it should be possible to indicate which entity on a WebPage is  considered to be the 'main entity'. The discussion then continued to be about whether the range for 'mainContentOfPage' should be expanded to Thing for this, or whether a new property (mainEntity) should be created.

Most who participated in the discussion were in favor of expanding the range of 'mainContentOfPage' to Thing. 

During the discussion the request was also made if the sponsors could equally support this update and have their validation & webmaster tools as well as their search results reflect their support, once the update has been released, because:

If something like:
```
<body itemscope itemtype="http://schema.org/WebPage">
  <div itemprop="mainContentOfPage" itemscope itemtype="http://schema.org/Product">
    ...
  </div>
<body>
```
Doesn't get the same search result snippet as:
```
<body>
  <div itemscope itemtype="http://schema.org/Product">
    ...
  </div>
<body>
```
Chances are very slim folks will start using it.

Any input?

**Comment by danbri** [comment]
We will address the underlying requirement, but it is unlikely we'll use the mainContentOfPage property to do this. The way mainContentOfPage is defined it is more about the actual markup elements in the page, rather than the underlying real world entity that is described by that markup. So I'll mark this 'wont fix' but will open another issue to track mainEntity discussions better. Thanks!

**Comment by jvandriel** [comment]
>
> *"is more about the actual markup elements in the page"*


WebPageElements, let's make sure we discuss those as well because ever
since you made a remark about maybe wanting to reconsider their usefulness
(as in markup for makup's sake) I have started doubting their usefulness as
well. So much that I'd like to discuss whether or not we should keep
schema.org/WebPageElement (and it's subClasses) or not.

2015-01-21 12:35 GMT+01:00 Dan Brickley <notifications@github.com>:

**Comment by jvandriel** [comment]
"is more about the actual markup elements in the page"

WebPageElements... Let's make sure we discuss those as well. Because ever since you made a remark about their usefulness (as in markup for makup's sake) I have started doubting their usefulness as well. So much that I'd like to discuss whether or not we should keep schema.org/WebPageElement (and it's subClasses) in schema.org or not.

**Comment by danbri** [comment]
Ok I think this dialogue has served its purpose - closing the issue. Thanks @jvandriel !
