### ISSUE TITLE
Add property to IndividualProduct

### ISSUE THREAD

**Issue by DDmUSA** [schemaorg/schemaorg#2150]
The existing schema for an IndividualProduct does not offer a means to indicate that the product is compatible with one or more other products, so I am suggesting an additional property exist for IndividualProduct, with the new property to be known as:   isCompatibleWith (and the property can have one or more values)

**Comment by MichaelAndrews-RM** [comment]
I think the concept `isCompatibleWith` could be understood in different ways, and therefore could be difficult to use consistently.  Schema.org already has two more specific properties relating to compatibility:

[isAccessoryOrSparePartFor](https://schema.org/isAccessoryOrSparePartFor)
[isConsumableFor](https://schema.org/isConsumableFor)

Also the GS1 Web vocabulary has
[Has Dependent Proprietary Product](https://gs1.org/voc/dependentProprietaryProduct)

**Comment by thadguidry** [comment]
I think for exactly the reasons you state, that compatibility can be understood in different ways showcases the need for an abstract type.
What that type needs to look like?  Dunno, but often in manufacturing or product development/marketing its called a CompatibilityMatrix and often times just a simple list, or a table with rows and columns.  How that looks for Schema.org would be where refinement of why/how Things are compatible, and could be handled by our existing subtypes or new or borrowed.

@DDmUSA Can you give us just 1 example of a value you would capture with your proposed property isCompatibleWith?  Generic or very specific?  Ex. "PC's" , "Marine environments"

**Comment by danbri** [comment]
ok, so we can think of this as a proposal for a more generic superproperty of the two existing schema.org properties @MichaelAndrews-RM mentions, i.e. isAccessoryOrSparePartFor
and isConsumableFor.

At which point (unless someone is stepping up to say they're consuming the new term), I think for now we should say:

Thank you for the suggestion! It has been noted, tagged and filed for future reference. I am closing this issue to help us manage the huge number of suggestions we get, but we do appreciate that you've taken the time, and we encourage continued discussion here.

#2050
