### ISSUE TITLE
Check codebase is happy with terms beginning with a number

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2151]
@RichardWallis can you confirm that a type called "3DModel" should be ok in our codebase? i.e. we don't have any assumptions that terms begin with A-Z, a-z ...

**Comment by RichardWallis** [comment]
Codebase is fine with this.

Made adjustments to tests that complained.  Now we can accept term names that begin with zero or more numerics before the normal capitalisation rules.   

This was carried out as part of commmit #[259e6a151fc18bc9014e02645167ffd5bd8e32c4](https://github.com/schemaorg/schemaorg/commit/259e6a151fc18bc9014e02645167ffd5bd8e32c4)
