### ISSUE TITLE
 Automatic annotation using AI

### ISSUE THREAD

**Issue by MartinLichtblau** [schemaorg/schemaorg#2157]
Is is possible to automatically annotate unstructured data on websites with the help of Artifical Intelligence?

With todays Machine Learning techniques, and formemost Neural Networks, it should be possible to detect relevant website passages and apply the appropriate schema on data fragments, hence automatically structure heterogenous sources and eventually create a semantic web. Since there is already lots of data in the Linked Open Data cloud it should be possible to use it as labeled data to create some supervised artifical agents to classify new data. 
Do you know whether such tools already exist? Or who is working on it right know? IMO that's the only path to unfold the semantic web and make it our reality.

**Comment by danbri** [comment]
There are a variety of tools and projects in that direction, but we can't really answer such questions here.

You might look at the proceedings of conferences like ISWC and ESWC, or at software like https://stanbol.apache.org/
