### ISSUE TITLE
Offers, review, or aggregateRating for custom products

### ISSUE THREAD

**Issue by barrad0s** [schemaorg/schemaorg#2161]
Hello everyone,
As this is my first post, apologies if this is the wrong place.
As noticed by many, google webmaster tools has been showing this error to products:

> Either "offers", "review", or "aggregateRating" should be specified

I run a website that manufacturers custom items, which are displayed as "products", using schema for description, name etc, however, no pricing, reviews or rating is displayed, since they are made to order, always a little different. This is by choice and as far as pricing, I can't and don't want to show pricing.
Is this error hurting me? Should I change this somehow, remove the schema? Is this schema incorrect for custom products?

**Comment by RichardWallis** [comment]
@barrad0s As you may have suspected, this is not the right place for such a question.  This is the place to make specific suggestions and proposals as to how things can be improved with the Schema.org vocabulary itself. 

Your question is more appropriate for those that  consume it (eg. Google, Bing, Yahoo!, etc.)  A more appropriate place to ask your question (for Google) might be [https://productforums.google.com/forum/#!categories/webmasters/structured-data](https://productforums.google.com/forum/#!categories/webmasters/structured-data)

**Comment by barrad0s** [comment]
@RichardWallis thank you. I guess my real question was whether I should or not use schema for custom products.
