### ISSUE TITLE
Adding a waitTime property to a Recipe

### ISSUE THREAD

**Issue by Djyp** [schemaorg/schemaorg#2164]
I'm creating a Recipe class in a new project and I'm using the vocabulary on https://schema.org/Recipe, of course.
Looking at different recipes online and offline, I often see a "wait time". It's useful, for example, when the dish needs to cool down or when a dough needs to leaven. Of course this piece of information is in the instructions but it's not reported in a property. That would let apps, assistants and search engines have a more accurate way to tell how long it takes to make a recipe.

So why not create a new property called waitTime, usiing the Duration type ?

If not, how would you tell the wait time using the current properties ?

EDIT :
- Description proposal : `The total time needed to wait between steps, in ISO 8601 duration format.`
- I just realized this may be more useful in **HowTo**

**Comment by SleeplessByte** [comment]
@Djyp IIRC, we used `totalTime - prepTime - (performTime | cookTime)` to determine `waitTime`. 

Listed as: "Time not prepping or cooking" (and therefore waiting/resting)

**Comment by Djyp** [comment]
Apparently people are totally ok with it. I just thought adding a waitTime would be more precise :thinking:
I suggest we clode this issue
