### ISSUE TITLE
Dentist services

### ISSUE THREAD

**Issue by dronur07** [schemaorg/schemaorg#2165]
Hi all!
I am a dentist and creating a new website and planning to use microdata. But i am really confused about which microdata suits for my website.

Using dentist extension i think this is the right choice, but i do not know how to choose my service type.

I ve found in Github that;
[https://gist.github.com/gera3d/1169aa8ea5576dc3779f](url)
he sets dental implants as a medical procedure, but schema.org/dentist doesnt have medical procedure?

I ve decided to use service (because professional service deprecated), but i dont know it will helps about explanation what are dental implants.

<script type="application/ld+json">
{

"@context": "http://schema.org/",
  "@type": "Service",
  "serviceType": "Dental Implant"
"name": "Dental Implant"
"description": "Dental implant is a medical device..."

Thank you

**Comment by RichardWallis** [comment]
hi @dronur07 

If in addition to [Dentist](https://schema.org/Dentist) you define you or your MedicalBusiness as a [Physician](https://health-lifesci.schema.org/Physician) and/or [MedicalClinic](MedicalClinic), you will be able to use the [availableService](https://health-lifesci.schema.org/availableService) property to link to a [MedicalProcedure](https://health-lifesci.schema.org/MedicalProcedure) description of your dental implant [fitting] service.  Equally, if you also add the type [Service](https://schema.org/Service) to that description you will be able to use it to assign to the [itemOffered](https://schema.org/itemOffered) property in an [Offer](https://schema.org/Offer) that is [offeredBy](https://schema.org/offeredBy) you.

Hope that helps.

**Comment by dronur07** [comment]
@RichardWallis Thank you for your help.
