### ISSUE TITLE
Decimal separators

### ISSUE THREAD

**Issue by pierrefar** [schemaorg/schemaorg#2166]
Hi

Decimal separators need a another look. For example, in #99, https://schema.org/price says _"Use '.' (Unicode 'FULL STOP' (U+002E)) rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator."_ But such guidance is not given for other numeric properties such as https://schema.org/ratingValue . I would argue `ratingValue` is as important as `price` as they're usually found together.

One approach is to write such guidance when a numeric property is of the type Text, but also add specific instructions on https://schema.org/Number saying to use decimal points as the separator and commas for groups as per current standards ([Wikipedia ref](https://en.wikipedia.org/wiki/Decimal_separator#Current_standards)).

Thanks.

**Comment by danbri** [comment]
Hi Pierre! Yes, this makes sense. Number may be a better place for the advice.

**Comment by pierrefar** [comment]
Thanks @danbri . From experience, I know many people use text as that's easier. Being clear there too will help. My 2c.
