### ISSUE TITLE
https://pending.schema.org/Occupation #4 errors

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#2167]
[Schema:Occupation](https://pending.schema.org/Occupation) the 4th example will not pass GSDTT

**Comment by vholland** [comment]
The first hasOccupation block needs the type (Occupation) set.

And the comma needs to be removed after  "PhD in Physics"

**Comment by RichardWallis** [comment]
Also spotted extra commas in examples 1 & 3.

Fixed all - now in PR #2168
