### ISSUE TITLE
Schema:familyName

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#2169]
Feature: Allow us to express **familyName** with the value and sameAs. Example: [Prophit - wikidata](https://www.wikidata.org/wiki/Q37565943) and other ancestral sites for a given family name.

**Comment by RichardWallis** [comment]
In theory that should already be possible as by default all properties can expect types Text, URL & Role ([Documentation](https://schema.org/docs/datamodel.html#conformance)).

So:
```
{
  "@context": "http://schema.org",
  "@type": "Person",
  "name": "Denver Prophit Jr",
  "familyName": "http://www.wikidata.org/entity/Q37565943"
}
```

**Comment by inetbiz** [comment]
@RichardWallis the issue is the wikidata entry base label doesn't spell my last name. I had to add an alias.

**Comment by danbri** [comment]
Thank you for the suggestion! It has been noted, tagged and filed for future reference. I am closing this issue to help us manage the huge number of suggestions we get, but we do appreciate that you've taken the time, and we encourage continued discussion here.

#2050
