### ISSUE TITLE
The rdfs:subClassOf links in RDFa markup have room for improvement

### ISSUE THREAD

**Issue by jaw111** [schemaorg/schemaorg#217]
For example the RDFa on http://schema.org/Blog states:

```
schema:Blog rdfs:subClassOf schema:Blog .
```

Whereas one would expect:

```
schema:Blog rdfs:subClassOf schema:CreativeWork .
```

Furthermore on the pages for datatypes the values for rdfs:subClassOf are literals, for example http://schema.org/URL states:

```
 schema:URL rdfs:subClassOf "URL"@en .
```

Whereas one would expect:

```
schema:URL rdfs:subClassOf schema:Text .
```

**Comment by danbri** [comment]
We didn't get to this for gozer release, bumping to next release (which I hope follows soon!)

**Comment by danbri** [comment]
The first thing seems fixed, 

> ```<h4><span class='breadcrumbs'><a   href="/Thing">Thing</a> &gt; <link  property="rdfs:subClassOf" href="http://schema.org/CreativeWork" /><a   href="/CreativeWork">CreativeWork</a> &gt; <a   href="/Blog">Blog</a></span>```
 

and the second, 

> ```<h4><span class='breadcrumbs'><a href="DataType">DataType</a> &gt; <link  property="rdfs:subClassOf" href="http://schema.org/Text" /><a   href="/Text">Text</a> &gt; <a   href="/URL">URL</a></span>```
