### ISSUE TITLE
Schema for food Item?

### ISSUE THREAD

**Issue by kadnan** [schemaorg/schemaorg#2171]
I am working on a food delivery website. I am able to find MenuItem schema but it is for listing page. All I want to implement Schema format for a single Item, say for Italian Pizza on the individual food item page. I am confused which one should I pick, `Product` or `MenuItem`? I also want to show delivery time.

**Comment by rootree** [comment]
Hi @kadnan ! Have you got any answer?

**Comment by RichardWallis** [comment]
I would suggest that you use ```Product``` to describe the Pizza  and/or ```Product``` **and** ```MenuItem``` when referencing it from a ```Menu``` or ```MenuSection```.

eg. ``` "@type": ["Product","MenuItem"],```
