### ISSUE TITLE
Add a property on CreativeWork to specify access rights

### ISSUE THREAD

**Issue by anarchivist** [schemaorg/schemaorg#2173]
It would be useful to specify access rights for CreativeWorks. This was originally surfaced as part of the proposal made for Schema Architypes, an extension for archives and their collections, but in discussion, it became clear that this applies to lots of other domains, including other materials held by cultural heritage institutions, datasets created and used in research, and so forth. 

I believe access rights should be understood as distinct from `license` and `hasDigitalDocumentPermission`.

Examples:

An archival collection:

```jsonld
{
  "@context": "http://schema.org/",
  "@type": "Collection",
  "url": "https://www.lib.ncsu.edu/findingaids/mc00351",
  "name": "Animal Rights Network records",
  "accessRights": "This collection is open for research; access requires at least 48 hours advance notice."
}
```

A digitized letter from an archival collection:

```jsonld
{
  "@context": "http://schema.org/",
  "@type": "CreativeWork",
  "url": "https://purl.stanford.edu/bp158wj7223",
  "name": "Margaret Mitchell letter to Herschel Bricknell, 1936 August 22",
  "accessRights": "Online content is available for access via the Special Collections Reading Room."
}
```

A dataset:

```jsonld
{
  "@context": "http://schema.org/",
  "@type": "Dataset",
  "@id": "https://doi.org/10.7910/DVN/0OLJLM",
  "name": "Restricted Access WFHS Leef Manager Linking Data, Version 1.0",
  "accessRights": "Access to this dataset can be obtained by visiting the Work, Family & Health Network web page and following the instructions: http://projects.iq.harvard.edu/wfhn/restricted-access-data."
}
```

Additional context and examples:

* For archives, see standards like [ISAD(G) §3.4.1](https://www.ica.org/sites/default/files/CBPS_2000_Guidelines_ISAD%28G%29_Second-edition_EN.pdf), [DACS §4.2](https://www2.archivists.org/standards/DACS/part_I/chapter_4/1_conditions_governing_access), and [MARC21's 506 field](https://www.loc.gov/marc/bibliographic/bd506.html), and [EAD's `<accessrestrict/>` tag](https://www.loc.gov/ead/tglib/elements/accessrestrict.html). Detailed examples can be found at [#1784 (comment)](https://github.com/schemaorg/schemaorg/pull/1784#issuecomment-471126664).
* Related properties: `dct:accessRights` ([proposed in DCAT revision](https://w3c.github.io/dxwg/dcat/#license-rights))
* Related vocabularies: [COAR access_rights](http://vocabularies.coar-repositories.org/documentation/access_rights/), [ePrints access rights](https://www.webarchive.org.uk/wayback/en/archive/2018/http://www.ukoln.ac.uk/repositories/digirep/index/Eprints_AccessRights_Vocabulary_Encoding_Scheme), [Standardized terminology for Access Restrictions](https://www.oclc.org/content/dam/oclc/digitalregistry/506F_vocabulary.pdf), [SEADATANET access restrictions](http://seadatanet.maris2.nl/v_bodc_vocab_v2/browse.asp?order=conceptid&formname=search&screen=0&lib=l08&v0_0=&v1_0=conceptid%2Cpreflabel%2Caltlabel%2Cdefinition%2Cmodified&v2_0=0&v0_1=&v1_1=conceptid&v2_1=3&v0_2=&v1_2=preflabel&v2_2=3&v0_3=&v1_3=altlabel&v2_3=3&v0_4=&v1_4=modified&v2_4=9&v0_5=&v1_5=modified&v2_5=10&x=35&y=18&v1_6=&v2_6=&v1_7=&v2_7=), [CEDS learning resource access rights](https://ceds.ed.gov/element/001561)

See past discussion on #1784, #1758, #1759, and #900 ([comment](https://github.com/schemaorg/schemaorg/issues/900#issuecomment-159276107)).

**Comment by RichardWallis** [comment]
The more I look at this possibility/proposal the more sense it makes to me.

OK, its probably not applicable to all CreativeWork subtypes (e.g. menu, howTo, Question) but I can think of scenarios where it would be applicable to a large proportion of the rest.

**Comment by danbri** [comment]
accessRights is the wrong name for this. Lets call it accessInfo. 

"access requires at least 48 hours advance notice" isn't really about rights to anything for anyone, if anything it is closer to openingHours. Same for ""Access to this dataset can be obtained by visiting the Work, Family & Health Network web page and following the instructions: http://projects.iq.harvard.edu/wfhn/restricted-access-data.", "Online content is available for access via the Special Collections Reading Room."

**Comment by RichardWallis** [comment]
Suggested alternative property name 'conditionsOfAccess'

With description:
Conditions that affect the availability of, or method(s) of access to, the item. For example "_Available by appointment from the Reading Room_" or "_Accessible only from logged-in accounts_ ".

cc/ @anarchivist

**Comment by anarchivist** [comment]
Either of the two proposed alternate property names sound fine to me.

**Comment by vroddon** [comment]
What about hasPolicy?
http://www.w3.org/ns/odrl/2/hasPolicy
https://www.w3.org/TR/odrl-vocab/

**Comment by RichardWallis** [comment]
The name conditionsOfAccess was used

**Comment by ytlim696** [comment]
> It would be useful to specify access rights for CreativeWorks. This was originally surfaced as part of the proposal made for Schema Architypes, an extension for archives and their collections, but in discussion, it became clear that this applies to lots of other domains, including other materials held by cultural heritage institutions, datasets created and used in research, and so forth. 
> 
> I believe access rights should be understood as distinct from `license` and `hasDigitalDocumentPermission`.
> 
> Examples:
> 
> An archival collection:
> 
> ```jsonld
> {
>   "@context": "http://schema.org/",
>   "@type": "Collection",
>   "url": "https://www.lib.ncsu.edu/findingaids/mc00351",
>   "name": "Animal Rights Network records",
>   "accessRights": "This collection is open for research; access requires at least 48 hours advance notice."
> }
> ```
> 
> A digitized letter from an archival collection:
> 
> ```jsonld
> {
>   "@context": "http://schema.org/",
>   "@type": "CreativeWork",
>   "url": "https://purl.stanford.edu/bp158wj7223",
>   "name": "Margaret Mitchell letter to Herschel Bricknell, 1936 August 22",
>   "accessRights": "Online content is available for access via the Special Collections Reading Room."
> }
> ```
> 
> A dataset:
> 
> ```jsonld
> {
>   "@context": "http://schema.org/",
>   "@type": "Dataset",
>   "@id": "https://doi.org/10.7910/DVN/0OLJLM",
>   "name": "Restricted Access WFHS Leef Manager Linking Data, Version 1.0",
>   "accessRights": "Access to this dataset can be obtained by visiting the Work, Family & Health Network web page and following the instructions: http://projects.iq.harvard.edu/wfhn/restricted-access-data."
> }
> ```
> 
> Additional context and examples:
> 
> * For archives, see standards like [ISAD(G) §3.4.1](https://www.ica.org/sites/default/files/CBPS_2000_Guidelines_ISAD%28G%29_Second-edition_EN.pdf), [DACS §4.2](https://www2.archivists.org/standards/DACS/part_I/chapter_4/1_conditions_governing_access), and [MARC21's 506 field](https://www.loc.gov/marc/bibliographic/bd506.html), and [EAD's `<accessrestrict/>` tag](https://www.loc.gov/ead/tglib/elements/accessrestrict.html). Detailed examples can be found at [#1784 (comment)](https://github.com/schemaorg/schemaorg/pull/1784#issuecomment-471126664).
> * Related properties: `dct:accessRights` ([proposed in DCAT revision](https://w3c.github.io/dxwg/dcat/#license-rights))
> * Related vocabularies: [COAR access_rights](http://vocabularies.coar-repositories.org/documentation/access_rights/), [ePrints access rights](https://www.webarchive.org.uk/wayback/en/archive/2018/http://www.ukoln.ac.uk/repositories/digirep/index/Eprints_AccessRights_Vocabulary_Encoding_Scheme), [Standardized terminology for Access Restrictions](https://www.oclc.org/content/dam/oclc/digitalregistry/506F_vocabulary.pdf), [SEADATANET access restrictions](http://seadatanet.maris2.nl/v_bodc_vocab_v2/browse.asp?order=conceptid&formname=search&screen=0&lib=l08&v0_0=&v1_0=conceptid%2Cpreflabel%2Caltlabel%2Cdefinition%2Cmodified&v2_0=0&v0_1=&v1_1=conceptid&v2_1=3&v0_2=&v1_2=preflabel&v2_2=3&v0_3=&v1_3=altlabel&v2_3=3&v0_4=&v1_4=modified&v2_4=9&v0_5=&v1_5=modified&v2_5=10&x=35&y=18&v1_6=&v2_6=&v1_7=&v2_7=), [CEDS learning resource access rights](https://ceds.ed.gov/element/001561)
> 
> See past discussion on #1784, #1758, #1759, and #900 ([comment](https://github.com/schemaorg/schemaorg/issues/900#issuecomment-159276107)).
