### ISSUE TITLE
Improve model for schema:DataType

### ISSUE THREAD

**Issue by jaw111** [schemaorg/schemaorg#218]
http://schema.org/DataType

In relation to #217 it would seem from the current hierarchy that schema:DataType is the super-class of schema:Boolean, schema:Date, etc.

This would infer that any literal value is a schema:DataType, which seems illogical.

It would seem more logical that:

- the existing datatype classes have type schema:DataType rather than be a sub-class of it
- a top-level class schema:Literal class is introduced (analogous to rdfs:Literal) of which all the existing data types are a sub-class

The result should be something like:

    schema:DataType a rdfs:Class ;
      rdfs:subClassOf schema:Class .
    
    schema:Literal a schema:DataType .
    
    schema:Boolean a schema:DataType ;
      rdfs:subClassOf schema:Literal .
    
    schema:Date a schema:DataType ;
      rdfs:subClassOf schema:Literal .

**Comment by danbri** [comment]
@rvguha can you take a look?

**Comment by rvguha** [comment]
Yes, jaw111 is absolutely right. This does mean that DataType is a class of classes.

**Comment by danbri** [comment]
Thanks. Re-opened as I'm only closing issues once we've addressed them. We'll need to tweak schema.rdfa here...

**Comment by danbri** [comment]
The vocab side of this is fixed in sdo-gozer, alongside #130. UI/python consequences of the new structure are tracked as #463.
