### ISSUE TITLE
Extend the domain of contentUrl to include Clip

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2180]
It is sometimes useful to be able to point to the resource (e.g. MP4 file) for a Clip rather than the page on which the Clip resides. To differentiate this case, it would be good to extend the domain for 'contentUrl' to include Clip, so one could write:

```
{
  "@context": "http://schema.org/",
  "@type": "Clip",
  "url": "http://www.example.com/my_video",
  "contentUrl": "http://www.example.com/my_video.mp4"
}
```

**Comment by danbri** [comment]
(Vicki and I talked about this and, after thinking on how this relates to MediaObject, came up with "encoding" instead, which already gives us this expressivity:

```
{
  "@context": "http://schema.org/",
  "@type": "Clip",
  "url": "http://www.example.com/my_video",
  "encoding": 
     { 
     "@type": "VideoObject", 
     "url": "http://www.example.com/my_video.mp4"
     }
}

I think we can close this for now...
