### ISSUE TITLE
numberOfRooms not a property for Type Hotel

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2184]
Whilst checking examples it was identified that the [numberOfRooms](https://schema.org/numberOfRooms) property does not have [Hotel](https://schema.org/Hotel), or one of its super-types, in its domainIncludes.

As per the examples _numberOfRooms_ makes sense as a property for _Hotel_.  The assumption being that this is an oversight.

There is more than one way to solve this:

1.  Add [Hotel](https://schema.org/Hotel) to the domainIncludes of _numberOfRooms_

2. Add [LodgingBusiness](https://schema.org/LodgingBusiness) to the domainIncludes of _numberOfRooms_.  This may solve the same issue for other _LodgingBusiness_ subtypes.

3. Add [Accommodation](https://schema.org/Accommodation) as a further super-type of Hotel.

/cc @mfhepp

**Comment by MichaelAndrews-RM** [comment]
Thinking about this extensibly, numberOfRooms could also be a property of a house for sale.  If that were ever a use case to support, wouldn't want it limited to rental-oriented entities.

**Comment by RichardWallis** [comment]
[House](https://schema.org/House) & [Apartment](https://schema.org/Apartment) are subtypes of [Accommodation](https://schema.org/Accommodation) which [numberOfRooms](https://schema.org/numberOfRooms) has in its rangeIncludes.  So for a house/apartment for sale scenario it is already there.
