### ISSUE TITLE
DataType seems to point to itself as a parent?

### ISSUE THREAD

**Issue by mitar** [schemaorg/schemaorg#2194]
Since April 1 release, when you look at https://schema.org/DataType, it shows at the top in breadcrump:

```
DataType > DataType
```

So `DataType` is child of `DataType`? Is this on purpose? This makes it a circular definition which our parser does not consume gladly.

**Comment by rok** [comment]
Is `DataType` a `DataType`?

**Comment by RichardWallis** [comment]
Fixed in 3.5 post release patch fixes #2196
