### ISSUE TITLE
what value for 'ratingValue' when rating

### ISSUE THREAD

**Issue by redochka** [schemaorg/schemaorg#2197]
what value for 'ratingValue' when rating ?

Google complains with : `Missing value in field 'ratingValue'`

**Comment by RichardWallis** [comment]
Checkout the [examples](https://schema.org/ratingValue#examples) for the property, and the other properties used with [Rating](https://schema.org/Rating).

- [bestRating](https://schema.org/bestRating): "The highest value allowed in this rating system. If bestRating is omitted, 5 is assumed."

- [worstRating](https://schema.org/worstRating): "The lowest value allowed in this rating system. If worstRating is omitted, 1 is assumed."
