### ISSUE TITLE
What are the required attributes for DataDownload?

### ISSUE THREAD

**Issue by vsoch** [schemaorg/schemaorg#2198]
hey everyone! I'm adding a DataDownload to a Dataset, and I'm curious what attributes are absolutely required? I'm looking here https://schema.org/DataDownload and all I see (with a required string) are things like playerType (not what I'd expect!) I would expect minimally to have a url, no? Any advice would be greatly appreciated - the goal of this is to add a download link to some of the table templates here https://openschemas.github.io/schemaorg/#7-embed-in-html-with-json-ld.

Note the original discussion is at https://github.com/openschemas/schemaorg/issues/21. Thanks much!

**Comment by chrisgorgo** [comment]
This might help: https://developers.google.com/search/docs/data-types/dataset#download

Example

```JSON
{
  "@context":"https://schema.org/",
  "@type":"Dataset",
  "name":"NCDC Storm Events Database",
  "description":"Storm Data is provided by the National Weather Service (NWS) and contain statistics on...",
  "url":"https://catalog.data.gov/dataset/ncdc-storm-events-database",
  "sameAs":"https://gis.ncdc.noaa.gov/geoportal/catalog/search/resource/details.page?id=gov.noaa.ncdc:C00510",
  "creator":{
     "@type":"Organization",
     "url": "https://www.ncei.noaa.gov/",
     "name":"OC/NOAA/NESDIS/NCEI > National Centers for Environmental Information, NESDIS, NOAA, U.S. Department of Commerce",
     "contactPoint":{
        "@type":"ContactPoint",
        "contactType": "customer service",
        "telephone":"+1-828-271-4800",
        "email":"ncei.orders@noaa.gov"
     }
  },
  "distribution":[
     {
        "@type":"DataDownload",
        "encodingFormat":"CSV",
        "contentUrl":"http://www.ncdc.noaa.gov/stormevents/ftp.jsp"
     },
     {
        "@type":"DataDownload",
        "encodingFormat":"XML",
        "contentUrl":"http://gis.ncdc.noaa.gov/all-records/catalog/search/resource/details.page?id=gov.noaa.ncdc:C00510"
     }
  ]
}

**Comment by vsoch** [comment]
Thank you! That should be enough for a good start :) I'm going out for a run but I'll pick up when I get back!

**Comment by vsoch** [comment]
Simple (ugly) download link button is added to templates, and I used the examples provided above as a best guess at required fields. It's an ugly button, but I'm sure I'll style it at some point in the future when I wake up and am horrified by the ugliness. Closing issue!
