### ISSUE TITLE
more examples for Action (illustrating use of potentialAction, actionStatus, result)

### ISSUE THREAD

**Issue by elf-pavlik** [schemaorg/schemaorg#220]
http://schema.org/Action
http://schema.org/potentialAction
http://schema.org/actionStatus

I start this issue to track work on enhancing quality and quantity of examples for _Action_, especially providing versions for those used for _potentialAction_ and transition between various statuses. Also illustrating better how to relate _Action_ to its _result_.
We can also include equivalents for examples @jasnell wrote for draft of Activity Streams 2.0 https://www.w3.org/wiki/Activity_Streams/Expanded_Vocabulary

I already did started some work in https://github.com/danbri/schemaorg/pull/15 and in various emails, which I will link to from here as I dig them up.

**Comment by danbri** [comment]
Thanks! do keep us posted on your investigations. Maybe Sam can take a look at https://github.com/danbri/schemaorg/pull/15  too?

**Comment by danbri** [comment]
I've marked https://github.com/schemaorg/schemaorg/issues/155 as a wontfix and indicated discussion should continue here. One point is that 404'ing pseudo properties like query-input is not helpful; we should catch those and give a sensible human-friendly explanation. So a little bit of python hacking is needed (hence I've added a 'python' label to the issue).

**Comment by elf-pavlik** [comment]
@samuelgoto could you please take another look at https://github.com/danbri/schemaorg/pull/15, merge / cherry-pick whatever you agree with and then we will continue conversation here? thanks!

**Comment by elf-pavlik** [comment]
Some early sketches attempting to capture how Action and it result artifact(s) can relate available in https://github.com/w3c-social/social-vocab e.g.

![Follow](https://docs.google.com/drawings/d/1zFWdjo_phs60Lr7dyoXyd4PQ9hOBxadlU8FZDQIAPHg/pub?w=960&h=540)

I also just created another placeholder for discussion about Offline / Online & Human (activity) / API (operation) in https://github.com/w3c-social/social-vocab/issues/12

![Activity/Operation](https://docs.google.com/drawings/d/19CzkPitEb1DecTr0UXELt8wTWsBfPo3rcc53uIY4IY8/pub?w=1343&h=720)
