### ISSUE TITLE
Allow Text type for @Person.worksFor

### ISSUE THREAD

**Issue by darkenedsky** [schemaorg/schemaorg#2201]

**Comment by RichardWallis** [comment]
@darkenedsky  If you check out the [conformance](https://schema.org/docs/datamodel.html#conformance) section in the Data Model documentation, you will find all properties, in addition to the documented expected types, can accept [Text](https://schema.org/Text), [URL](https://schema.org/URL), & [Role](https://schema.org/Role) as values. 

Sometimes to emphasise the expected use of a property, one or more of these types are specifically referenced as an expected type.

Having said that, even if you only have the name of an organisation a Person worksFor, you can still define it as an Organization:
```
...
  "@type": "Person:,
  "name": "A Worker",
  "worksFor": {
     "@type": "Organization",
     "name": "Acme Corp"
   },
...
```
