### ISSUE TITLE
Organization: ChamberOfCommerceNumber

### ISSUE THREAD

**Issue by fruitl00p** [schemaorg/schemaorg#2208]
Are there any plans to allow for 'specifying' the chamber of commerce number of an organisation? In alot of (European) countries this refers to a (inter) national database listing which would allow us a higher level of specificity... 

thanks!

**Comment by RichardWallis** [comment]
Beyond the initial few identifier types (duns, leiCode, taxId) there are many many potential identifier types, such as chamber of commerce number, company number, etc., etc., plus their geographically specific equivalents.

As with other identifier types, for product types, service types, etc., it is not practical to add specific properties for each and every specific type.

In recognition of the needs for many identifier types, the [identifier](https://schema.org/identifier) property was expanded to  accept a [PropertyValue](https://schema.org/PropertyValue) as a value.

The use of _PropertyValue_ enables the association of arbitrary _identifier_ values, qualified by the identifier type.

Check out the [example](https://schema.org/identifier#identifier-2) which shows the association of a Company Number with an Organization.   With minor tweaks this could be used to describe the chamber of commerce number.

This should help your needs, without requiring changes to the vocabulary.

**Comment by mfhepp** [comment]
I am glad to see that the PropertyValue mechanism, which got so some criticism when proposed, gets so popular ;-)

A bit of background info is here:
- https://www.w3.org/wiki/WebSchemas/PropertyValuePairs

Martin

**Comment by fruitl00p** [comment]
Aaah! Great, too bad the [google snippet tester](https://search.google.com/structured-data/testing-tool) fails to see that the propertyValue is part of an organization... 

```html
<section itemscope itemtype="http://schema.org/Organization">
<h2 itemprop="name">
    My Org
</h2>
<address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <div itemprop="streetAddress">My street 15</div>
    <span itemprop="postalCode">1234AB</span>
    <span itemprop="addressLocality">My City</span>
    <a itemprop="telephone" href="tel:+311234567890">+31 123 456 7890</a>
    <a href="mailto:info@myorg.com" itemprop="email">info@myorg.com</a>
</address>
<div itemprop="identifier" itemscope itemtype="http://schema.org/PropertyValue">
    <span itemprop="propertyID">Chamber of Commerce</span> Amsterdam <span itemprop="value">12345678</span>
</div>
VAT CODE <span itemprop="vatID">NL123456789B01</span>
</section>
```
But it's a (great) solution for the incredibly diverse method of identification across the world :)

Thanks!

**Comment by RichardWallis** [comment]
The more it is utilised, the greater chance of consumers recognising it.

**Comment by rvguha** [comment]
While PropertyValues are accepted, it should be recognized that they are a
means of last resort. They are to be used only when there isn't an accepted
schema. There should be no expectation of interoperability.

guha
