### ISSUE TITLE
paymentDueDate should have range Date, not DateTime

### ISSUE THREAD

**Issue by gkellogg** [schemaorg/schemaorg#2211]
According to [paymentDueDate](https://schema.org/paymentDueDate) values are expected to be of type DateTime, although examples use a Date format such as `2015-01-30`.

According to [DateTime](https://schema.org/DateTime), values are of the form `[-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]`, so they **MUST** include the time component, but examples routinely don't. [Date](https://schema.org/Date) is more appropriate, where values are of the form `[-]CCYY-MM-DD`

Alternatively, DateTime should be updated to allow for both Date and DateTime values.

Other properties to consider:

* availabilityEnds
* availabilityStarts
* availableFrom
* availableThrough
* dateIssued (dateCreated is okay)
* orderDate
* validFrom
* validThrough

See for example sdo-invoice-examples.txt:30.

**Comment by RichardWallis** [comment]
I think the most appropriate, and consistent action would be to define the properties you list as expecting both Date and DateTime, as for _dateCreated_.

**Comment by RichardWallis** [comment]
@danbri Your thoughts on this?

**Comment by danbri** [comment]
I think we should make a unified project at looking over all the date, schedule, event and calendar structures, so I'd pass on this for 3.7.

**Comment by RichardWallis** [comment]
implemented
