### ISSUE TITLE
Invalid MedicalCondition Examples

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2214]
Travis Ci scripts checking syntax in examples files has identified several errors in the examples provided in the [data/ext/health-lifesci/medicalCondition-examples.txt](https://github.com/schemaorg/schemaorg/blob/master/data/ext/health-lifesci/medicalCondition-examples.txt) file.

The same error is in all three serialisations: MICRODATA (from line 34) RDFA (from line 136) JSON (from 238).

Error report:
```
 Results:
        property  schema:possibleTreatment
          Object _:b12(schema:DrugClass) not compatible with rangeIncludes (schema:MedicalTherapy)
          Object _:b13(schema:Drug) not compatible with rangeIncludes (schema:MedicalTherapy)
          Object _:b11(schema:DrugClass) not compatible with rangeIncludes (schema:MedicalTherapy)
          Object _:b10(schema:Drug) not compatible with rangeIncludes (schema:MedicalTherapy)
        property  schema:secondaryPrevention
          Object _:b22(schema:LifestyleModification) not compatible with rangeIncludes (schema:MedicalTherapy)
          Object _:b20(schema:LifestyleModification) not compatible with rangeIncludes (schema:MedicalTherapy)
          Object _:b21(schema:LifestyleModification) not compatible with rangeIncludes (schema:MedicalTherapy)
```
Although [Drug](https://schema.org/Drug) & [DrugClass](https://schema.org/DrugClass) make [human] logical sense as values for the [possibleTreatment](https://schema.org/possibleTreatment) property, they are not within its rangIncludes.

Although [LifestyleModification](https://schema.org/LifestyleModification) makes [human] logical sense as a value for the [secondaryPrevention](https://schema.org/secondaryPrevention) property, it is not within its rangeIncludes.

Are these errors mistakes in the creation of the examples, or do they highlight an intention that was not followed through.

Options to fix:

- Remove misleading examples.
- Replace with valid examples.
- Update examples, using multi-type entities, to be valid.
- Propose a PR to enhance the vocabulary in this area to satisfy the intention.

cc/ @twamarc for comment.

**Comment by twamarc** [comment]
Thanks @Dataliberate for the check! Those are errors from the creation of the examples.
I support the 3rd option to fix this: Update examples, using multi-type entities, to be valid.

**Comment by RichardWallis** [comment]
@twamarc can I ask you to take a look at implementing that option?

**Comment by danbri** [comment]
Yes, please fix the examples to match the current vocabulary. I would prefer we don't change that vocabulary much without stronger evidence of usage.

**Comment by twamarc** [comment]
@RichardWallis , @danbri, --Hmm, I suggest to deprecate this example for the time being, while I think how to make a valid  example, using multi-type entities. (without touching rangeIncludes of https://schema.org/possibleTreatment or https://schema.org/secondaryPrevention)
