### ISSUE TITLE
'producer' and 'Organization'

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#222]
http://schema.org/producer

The description of the [`producer` property](http://schema.org/producer) currently is:

> The person or organization who produced the work (e.g. music album, movie, tv/radio series etc.).

Problems:

* It says "person or organization", but it lists only `Person` under "Values expected to be one of these types", not `Organization`.

* In addition to `CreativeWork `, it lists `Organization` under "Used on these types". But can an organization have a producer?

Maybe `Organization` should be moved from "Used on these types" to "Values expected to be one of these types"?

**Comment by thadguidry** [comment]
The person or organization who produced the CreativeWork.

Inverse on Person would be workProduced - "The work produced by this Person".
Inverse on Organization would be workProduced - "The work produced by this Organization".

IMHO.

**Comment by vholland** [comment]
I see. There is a copy/paste error where Organization is the domain instead of the range.

**Comment by danbri** [comment]
Fixed, and queued up for sdo-stantz release - http://sdo-stantz.appspot.com/producer
