### ISSUE TITLE
Duplicate type "http://schema.org/Text"

### ISSUE THREAD

**Issue by khalyomede** [schemaorg/schemaorg#2226]
**Explaination**

A duplicate type is found on the CSV file of the types.

**Reproduce the issue**

- Download the CSV file : https://schema.org/version/3.5/schema-types.csv
- In the column "url", filter on "http://schema.org/Text"
- You can see 2 occurences of this type with exactly the same data

**Expected result**

No duplicate found.

**Version**
3.5

**Comment by RichardWallis** [comment]
Closed in favour of composite issue #2229.
