### ISSUE TITLE
schema:isAccessibleForFree for websites which requires authentication

### ISSUE THREAD

**Issue by Min27** [schemaorg/schemaorg#2230]
1. is it recommended to use this property for websites  which requires authentication ie user needs to log in?
2. what about using this to mark up preview content/ trailers? 

TIA!

**Comment by RichardWallis** [comment]
1. The intention associated with this property is financially based.  Having CreativeWork, Event, Place & PublicationEvent in its domain I believe emphasises this.

2. Although closely related, a trailer should be described separately from the full work.  In such a case there would be no problem having a trailers described as ```"isAccessibleForFree": "True"``` whilst the main content described ```"isAccessibleForFree": "False"```

Implicit in this question is the aspect of how to describe access conditions/rights that are not financially based.  Issue #2173 _Add a property on CreativeWork to specify access rights_ (PR #2205)
proposes a new property _accessRights_ that will be very useful in this area.
