### ISSUE TITLE
JSON used to generate Schema.NET implementation of Schema.org includes incomplete information for AcceptedPaymentMethod on Offer

### ISSUE THREAD

**Issue by MEmanuelsson** [schemaorg/schemaorg#2236]
Trying to use the Schema.NET (https://github.com/RehanSaeed/Schema.NET) implementation of Schema.org to tag the content of our page but stumbled across an issue that you can read more about here: https://github.com/RehanSaeed/Schema.NET/issues/42

Not really sure about which JSON that's being referred to here but maybe you can help us out with this?

**Comment by RichardWallis** [comment]
@RehanSaeed Can you share your analysis of the bug in the schema.org JSON that you use to generate classes.

Also, how are you importing the JSON-LD, from a download file or via content negotiation?

**Comment by RehanSaeed** [comment]
`https://schema.org/version/latest/all-layers.jsonld` has the following for the `PaymentMethod` enumeration but not the values:

```json
{
  "@id": "http://schema.org/PaymentMethod",
  "@type": "rdfs:Class",
  "http://purl.org/dc/terms/source": {
    "@id": "http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsClass"
  },
  "rdfs:comment": "...",
  "rdfs:label": "PaymentMethod",
  "rdfs:subClassOf": {
    "@id": "http://schema.org/Enumeration"
  }
}
```

E.g. The `GenderType` enumeration has the following as an example of what I'm expecting to see for an enumeration:

```json
{
  "@id": "http://schema.org/GenderType",
  "@type": "rdfs:Class",
  "rdfs:comment": "An enumeration of genders.",
  "rdfs:label": "GenderType",
  "rdfs:subClassOf": {
    "@id": "http://schema.org/Enumeration"
  }
}
{
  "@id": "http://schema.org/Male",
  "@type": "http://schema.org/GenderType",
  "rdfs:comment": "The male gender.",
  "rdfs:label": "Male"
}
{
  "@id": "http://schema.org/Female",
  "@type": "http://schema.org/GenderType",
  "rdfs:comment": "The female gender.",
  "rdfs:label": "Female"
}
```

**Comment by MEmanuelsson** [comment]
Considering the documentation (https://schema.org/PaymentMethod) says "Commonly used values" maybe this should instead be a string if the available values to choose from can not be defined in an enum? 

If this is to be defined in an enum it will also cause another problem for us where we'd like to define a payment method only available in Sweden for our offers. I guess it's hard to have this enum covering all available payment methods all over the world, unless there is a way that I don't know of to specify custom payment methods?

**Comment by danbri** [comment]
We merged this for v6.0 prematurely. I have now reverted the PR to give us time to handle it properly.

https://lists.w3.org/Archives/Public/public-schemaorg/2020Jan/0008.html has more discussion.

**Comment by RichardWallis** [comment]
PR #2614 should have improved things here.

**Comment by RichardWallis** [comment]
As identified by @MEmanuelsson the [PaymentMethod](https://schema.org/PaymentMethod) enumeration has no defined enumeration values.  It only has "Commonly used values"  mentioned in the description.

In such circumstances, tools could be enabled to enter external enumeration URIs
