### ISSUE TITLE
modelYear/vehicleModelYear instead of modelDate/vehicleModelDate for https://schema.org/Car?

### ISSUE THREAD

**Issue by MEmanuelsson** [schemaorg/schemaorg#2240]
Trying to tag our cardetail pages (using Schema.NET, https://github.com/RehanSaeed/Schema.NET) on our site I notice that since modelDate/vehicleModelDate is of type Date, this value is being printed out as "2015-01-01T00:00:00+00:00" for instance, instead of just "2015". Is there a certain reason why these fields are of type Date and not Number? If not possible to change modelDate/vehicleModelDate, maybe it should be taken into consideration to add fields for modelYear/vehicleModelYear?

**Comment by MichaelAndrews-RM** [comment]
Perhaps someone involved with the original decision (which I was not) can offer an definitive explanation.  

Here's how I would think about it.  Dates are different from numbers.  Applications may have a need to compare a modelDate with another date, such as today.  Some applications may want to know how old the car is: comparing today's date with the modelDate.  Or compare the modelDate with defined dates for servicing, registration, or some legal requirement.  

I appreciate the modelDate is not a precise indication of the real date the model was introduced, and it certainly doesn't indicate when the car was made.  But it is a concrete date that enables comparison with other kinds of dates.

**Comment by RichardWallis** [comment]
A view from the source vocabulary point of view....

Both [modelDate](https://schema.org/modelDate) & [vehicleModelDate](https://schema.org/vehicleModelDate) are properties that expect a type of [Date](https://schema.org/Date) as a value.  _Date_ is described as '_A date value in [ISO 8601 date format](https://en.wikipedia.org/wiki/ISO_8601)._'  
This means that these are valid values for a _Date_:
- ```YYYY                          ``` eg. 2015
- ```YYYY-MM             ```eg. 2015-02
- ```YYYY-MM-DD  ```eg. 2015-02-28
- ```YYYYMMDD       ```eg. 20150228

Note to have a time component  a property needs to have been defined as expecting [DateTime](https://schema.org/DateTime) values.  The pattern for _DateTime_ values being ```[-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]      ``` defined in ISO 8601.

So in the vocabulary and serialisations of data, these types in effect are expected to be a string which conforms to the patterns as defined in in ISO 8601.

Within .net code I presume you are creating DateTime Structs, parsing values from ISO8601 strings.  This obviously results in the effect @MEmanuelsson is reporting as non defined elements have to default to something (such as zero). The challenge being how you translate into ISO8601 for output, with or without a time component.

Or I suppose you could create a special structure that not only holds the individual date/time components, but also the relevant ISO8601 string, plus supporting functionality........

**Comment by MEmanuelsson** [comment]
@RichardWallis  Thanks for the explanation! I'll pass this question back over to Schema.NET. Creating a special structure for Date and also DateTime sounds like the right way to go forward with this.
