### ISSUE TITLE
Add ActionAccessSpecification to the domain for ineligibleRegion

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2242]
Authors can specify where an Action is available using http://schema.org/eligibleRegion. In some cases, it is easier to say where the Action cannot be performed. To that end, we should add http://schema.org/ActionAccessSpecification to the domain of http://schema.org/ineligibleRegion.

**Comment by RichardWallis** [comment]
Implemented in [Release 4.0](https://schema.org/docs/releases.html#v4.0)
