### ISSUE TITLE
Qualifying 'isSimilarTo' to describe the relation between products/services

### ISSUE THREAD

**Issue by jaw111** [schemaorg/schemaorg#2255]
I have a use case for electronic components where I want to describe cross-references between parts. This can be parts from one or different suppliers.

The requirement is to describe the quality of the match (exact/close/broad) and provide additional comments on the relation (why it is a match).

I can think of at least two ways to do this.

**Use `Role` to reify the relation**

In JSON-LD:

```json
{
  "@context": "http://schema.org",
  "@id": "http://acme.com/part/1N4148",
  "@type": "ProductModel",
  "mpn": "1N4148",
  "manufacturer": "http://acme.com",
  "isSimilarTo": {
    "@type": "Role",
    "roleName": "close",
    "description": "a pin-to-pin drop in replacement with exact match of package and close match of parametric features",
    "isSimilarTo": "http://acme.com/part/1N4149"
  }
}
```

**Use a new class to model the relation**

Imagine a new class `CrossReference` used as follows, assumes the relation is symmetric (could also be used to relate more than 2 products):

```json
{
  "@context": "http://schema.org",
  "@type": "CrossReference",
  "qualityOfCross": "close",
  "description": "a pin-to-pin drop in replacement with exact match of package and close match of parametric features",
  "model": [
    "http://acme.com/part/1N4148",
    "http://acme.com/part/1N4149"
  ]
}
```

**Comment by RichardWallis** [comment]
With the vocabulary as it stands your first option is a valid way to use  ```Role```.

You could propose something like your second option, but it would need some supporting arguments as to who would use and consume such data if shared.

A middle path could be to propose a specific subtype of ```Role``` (```SimilarityRole``` ?) with a specific property to describe the level of similarity.

At this early stage I would go for the first option and see how adoption goes.
