### ISSUE TITLE
Question - A site can be two types at once? can be a book and a course?

### ISSUE THREAD

**Issue by colomet** [schemaorg/schemaorg#2259]
If I have site wich is a book, i do use the type book, but what if is a textbook, can I use the type course too? and to be two different things at once?

thanks

**Comment by Aaranged** [comment]
Dunno that your resource is necessarily a Book and a Course - at first blush I'd say it was a Book that you could qualify with the property learningResourceType, providing the value there "Textbook".

But one way or another, an object _can_ be two different things at once (known as a multi-typed entity, or MTE).  Here's how you declare two types using JSON-LD:
`<script type="application/ld+json">`
`{`
`  "@context": "http://schema.org",`
`  "@type": ["ItemList", "CreativeWork"],`
