### ISSUE TITLE
True/False are both  instances *and* subclasses of Boolean

### ISSUE THREAD

**Issue by sesuncedu** [schemaorg/schemaorg#226]

**Comment by danbri** [comment]
For reference,

        danbri-macbookpro:data danbri$ rdfa schema.rdfa | grep '/True'
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/Boolean> .
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#label> "True" .
        <http://schema.org/True> <http://www.w3.org/2000/01/rdf-schema#comment> "The boolean value true" .
        <http://schema.org/True> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .
        danbri-macbookpro:data danbri$ rdfa schema.rdfa | grep '/False'
        <http://schema.org/False> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Boolean> .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/Boolean> .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#label> "False" .
        <http://schema.org/False> <http://www.w3.org/2000/01/rdf-schema#comment> "The boolean value false" .

@rvguha  - is there some deep reason for this, or it something got lost in translation somewhere?

**Comment by danbri** [comment]
Closing as duplicate of https://github.com/schemaorg/schemaorg/issues/130
