### ISSUE TITLE
Formatting issue in CSV output for accelerationTime

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2262]
See closed PR request #2261.

Shows unusual formatting in CSV file entry for [accelerationTime](https://schema.org/accelerationTime).

Issue is either wrong formatting in source data, or potentially in CSV creation process.

If source data - can we have a test to spot other occurrences.

**Comment by damenleeturks** [comment]
It looks like its on several other lines than just that one (see: https://github.com/schemaorg/schemaorg/pull/2263)

**Comment by RichardWallis** [comment]
Fixed
