### ISSUE TITLE
Missing business type - please add Psychotherapy

### ISSUE THREAD

**Issue by MikeWhelan** [schemaorg/schemaorg#2275]
This is a request to include "psychotherapy" or "counselling" in the Business Type listings. I'm not sure what the parent category would be... possibly "health and beauty business" although that is definitely not ideal. This is the definition of this profession, which may help to categorise it correctly:  
"Psychotherapy is a type of therapy used to treat emotional problems and mental health conditions"

**Comment by psychology-tools** [comment]
💁‍♀️ https://schema.org/Psychiatric 

Thing > Organization > LocalBusiness > MedicalBusiness :: Psychiatric 

Thing > Place > LocalBusiness > MedicalBusiness :: Psychiatric
