### ISSUE TITLE
readonlyValue VS mutableValue

### ISSUE THREAD

**Issue by Lcfvs** [schemaorg/schemaorg#2280]
Hi,

Your spec allows to specify if a property value is `readonly` or not, with the current description:

> Whether or not a property is mutable. Default is false. Specifying this for a property that also has a value makes it act similar to a "hidden" input in an HTML form.

Imho, it's a few confusing, because (referring to the HTML behavior) a property can be `readonly` for the user but not for the system.

Moreover, sometimes, a user value is required before to be readonly, like for a contract term, the contractors, ...

[More infos](https://github.com/mamund/collection-json/pull/14)

Is it actually possible to distinct them?

**Comment by RichardWallis** [comment]
This issue is not a SDO issue
