### ISSUE TITLE
Extend caption to schema:MediaObject domain

### ISSUE THREAD

**Issue by Tpt** [schemaorg/schemaorg#2282]
`schema:caption` has for domain `AudioObject`, `ImageObject` and `VideoObject`. Would it make sense to extend this domain to `MediaInfo` to state in the documentation that it is fine to use `schema:caption` on all medias where this property make sense?

This [issue has been raised](https://www.mediawiki.org/wiki/Topic:V1ff02axtpezo1ig) about [a proposal](https://www.mediawiki.org/wiki/User:Tpt/WikibaseMediaInfo_RDF_Dump_Format) to use `schema:caption` as part of the RDF mapping of the [Structured Data on Commons](https://commons.wikimedia.org/wiki/Commons:Structured_data) datamodel.

**Comment by RichardWallis** [comment]
This does not appear to be relevant to SDO itself.
