### ISSUE TITLE
Example uses AggregateOffer as type for offers, while doc says it's Offer only

### ISSUE THREAD

**Issue by BenMorel** [schemaorg/schemaorg#2283]
https://schema.org/offers says:

> Values expected to be one of these types
> `Offer`

But example 1 on the same page says:

```json
{
  "@context": "http://schema.org",
  "@type": "Product",

  "offers": {
    "@type": "AggregateOffer",
    "highPrice": "$1495",
    "lowPrice": "$1250",
    "offerCount": "8",
    "offers": []
  }
}
```

If it's OK for `offers` to contain `AggregateOffer`, this should be documented as such; if not, the example should be fixed?

**Comment by jvandriel** [comment]
`AggregateOffer` is a subtype of `Offer`, meaning anywhere an `Offer` is expected an `AggregateOffer` may be used as well.

**Comment by BenMorel** [comment]
How could I miss this...
Thanks!
