### ISSUE TITLE
Description of  type usage when not in the rangeIncludes of any property

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#2286]
I noticed that [https://schema.org/Patient](https://schema.org/Patient) doesn't have an area at the bottom of the page stating: 
> Instances of Patient may appear as values for the following properties

Is this a bug or does that mean there aren't any properties that have `Patient` as an expected value?

**Comment by RichardWallis** [comment]
Checking the data - this means there aren't any properties that have ```Patient``` as an expected value.

This is valid, as a ```Patient``` instance can be used as value for any property that expects a type that is a superclass of ```Patient```.

Should that information be provided to a developer, is a separate question.  In many cases that information could be voluminous.

**Comment by jvandriel** [comment]
Thanks for checking @RichardWallis !

I was looking for 'Patient' code examples when I noticed there weren't any properties mentioned that expect it as their value. Just wanted to make sure I hadn't uncovered a bug.

 Though might I request that somewhere in the future pages show a message stating:
> _"Instances of $type are not expected as values for any properties at the moment"_

as opposed to simply omitting the entire area below:
> _"Instances of $type may appear as values for the following properties"_

**Comment by RichardWallis** [comment]
@jvandriel Good point.

Perhaps:
> "Instances of $type are not expected as values for any properties at the moment, however they may be used as values for properties that expect one of its super-types"

**Comment by jvandriel** [comment]
That would do the job quite nicely in my book!

**Comment by RichardWallis** [comment]
Closed as code to implement is now in [sdopythonapp](https://github.com/schemaorg/sdopythonapp) repo.
See issue [#5](https://github.com/schemaorg/sdopythonapp/issues/5)
