### ISSUE TITLE
PropertyValue & PropertyValueSpecification conflicts & missing relation

### ISSUE THREAD

**Issue by Lcfvs** [schemaorg/schemaorg#2287]
# Conflicts
- The `PropertyValue` and the `PropertyValueSpecification` define some common properties (`mxValue`, `minValue`, ...), but how to resolve them? The spec doesn't seems to define the priority.

# Missing relation
- The spec doens't define how the `PropertyValue` and the `PropertyValueSpecification` are related, missing property, like `PropertyValue.valueSpecification`?

**Comment by RichardWallis** [comment]
The properties of a Type (such as [PropertyValue](https://schema.org/PropertyValue)) and their expected values are defined as potential to be used in the definition of instance data. As such there are no supplied constraints as to cardinality and/or data values.

Having said that, there are in some cases documentation guidelines to expected/intended use. 

One such document is in regard to the [use of Action](https://schema.org/docs/actions.html) and its subtypes.   You will find reference to the usage of the ```PropertyValueSpecification``` type in that document.

**Comment by Lcfvs** [comment]
@RichardWallis Ok, thanks, even if I don't really understand why we need some guidelines for that.

Imho, the `PropertyValueSpecification` deprecates the common properties in `PropertyValue`. An unique way to define them seems preferable, avoiding arbitrary preferences between implementations.
