### ISSUE TITLE
Structured product returns

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2288]
(proposal from Google)

It would be useful for Schema.org to have expressivity that allowed various merchants to describe their return policies. As always there are various levels of detail that might be made explicit. Our suggestion is to start with something like the following:

Main concepts: 

* Return Policy URL 
* Return Window Type [Finite, Infinite, Final Sale (no returns accepted)] 
* Refund Type [Store Credit, Full Refund, Exchange] 
* Return Fees [Original shipping, return shipping, restocking fees] 

Plus these as "useful to have":

* Are in-store returns offered? [Yes, No] 
* Exceptions [Category, Return Information including window, type, fees] 

Exceptions would be things like "this policy applies to everything except fish and electronics..." and are consequently difficult here because of the lack of a common taxonomy to point into. The usual Schema.org workaround in such a case would be to at least document text or URL values.

**Comment by danbri** [comment]
First cut at an implemented proposal: 
 * https://webschemas.org/ProductReturnPolicy
 * definitions: https://github.com/schemaorg/schemaorg/blob/master/data/ext/pending/issue-2288.rdfa

Example usage (I've not added this to repo):

```
{
"@context": "http://schema.org/",
"@type": "Organization",
"name": "Macys",
"url": "https://www.macys.com/",
"hasProductReturnPolicy": 
  {
    "@type": "http://schema.org/ProductReturnPolicy",
     "productReturnLink": "https://www.customerservice-macys.com/app/answers/detail/a_id/140/~/what-is-macys-return-policy%3F",
    "productReturnCategory": "Finite",
    "productReturnDays": "180",
    "refundType": "FullRefund",
    "inStoreReturnsOffered": "True",
    "productReturnExceptions": "Apple Products, area rugs, backstage, beauty box, bluemercury, bonus gifts, bridal salon, cosmetics & fragrances, designer brands, dresses, final sale/as is furniture and mattresses, finish line, fur vault, furniture, gourmet food & wine, home accessories, jewelry, last act, lighting, locker room by lids, maternity, mattresses, optical, personal care, small electrics, style your ring, sunglass hut"
  }
}
```

**Comment by rhroyston** [comment]
[hasProductReturnPolicy](https://schema.org/hasProductReturnPolicy) does not pass [Google's structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/). You can paste the snippet in there.

**Comment by RichardWallis** [comment]
@rhroyston That's probably because there is some inevitable delay between new terms entering the vocabulary specification and they being supported in various testing tools and environments.

The assumption is they will be soon. It might be worth providing feedback in the SDTT to encourage it's support.

**Comment by danbri** [comment]
(See #2381 for the renaming)

**Comment by RichardWallis** [comment]
Implemented

**Comment by otto-poulpe** [comment]
I've got issues with https://schema.org/ReturnFeesEnumeration, only https://schema.org/FreeReturn can be validate on https://search.google.com/test/rich-results, but it does not fit my need... I would rather use https://schema.org/ReturnShippingFees.. Here is my Json mark up : 
"offers": {
    "@type": "Offer",
    "url": "https://www.vapoter.fr/t17553-frm-alfaliquid-10ml",
    "priceCurrency": "EUR",
    "price": "5.9",
    "priceValidUntil": "2025-03-25",
    "availability": "https://schema.org/InStock",
    "itemCondition": "https://schema.org/NewCondition",
     "hasMerchantReturnPolicy": {
              "@type": "MerchantReturnPolicy",
              "applicableCountry": "FR",
              "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
              "merchantReturnDays": 14,
              "returnMethod": "https://schema.org/ReturnByMail",
              "returnFees": "https://schema.org/RestockingFees"
          }

Help me please !!

**Comment by patrickreiner** [comment]
Hi, apparently (according to ahrefs.com) the field "applicableCountry" is required for "MerchantReturnPolicy".

My issue is, the return policy is valid worldwide, so I cannot specify a ISO code for the country (e.g. US).

How can I tackle this?
