### ISSUE TITLE
Confusing MedicalCode properties

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#2293]
I'm quite confused on how to specify a `MedicalCode`, reason being there a 3 methods of doing so by using either:

1) `codeValue` + `codingSystem`
2) `codeValue` + `inCodeSet`
3) `indefinedTermSet` + `termCode`

Now I understand the inheritance of properties of super types can lead to some strange options (eg, a Vulcano with a telephone number) though in this particular case I think there's good reason to add some code examples to illustrate which would be the prefered way of specifying ICD-9 and ICD-10 codes.

I dare to say I'm pretty experienced with the health-lifesci domain though nevertheless am totally at a loss which of the 3 methods I should use. (option (1) used to be the way to do this before DefinedTerm and CategoryCode existed).

Any suggestions on how we could clarify the current ambiguous (at least for me) situation?

**Comment by twamarc** [comment]
@jvandriel I would go for option 1 and to add 2 systems as we did for ICD11 project, to repeat the sequence. what do you think?

**Comment by jvandriel** [comment]
I'm very much tempted to use option 1 as that how I did it before `DefinedTermSet`was introduced though I'm doubtful doing so as I have no clue what the current desired method is by any (possible) health-lifesci data consumers out there.

Do you have any idea about that @twamarc ?

**Comment by twamarc** [comment]
Hmmm! I have no experience in using the https://schema.org/DefinedTermSet unfortunately. So I would still go for option 1 we are used to :) !

**Comment by philbarker** [comment]
Looks like codeValue need not be defined as a property of MedicalCode as it is now inherited from CategoryCode, but no matter, it's the same property there twice. codingSystem looks like it provides the same information as the name of a DefinedTermSet used as for he inCodeSet property. So if you don't need to identify the source of the code any more precisely than with a string, then you're fine with option 1.
BTW, there's no reason for not using 1 and 2: 
codeValue = 12345...
codingSystem = 'ICD-9'
inCodeSet = <uri of ICD-9> or a CategoryCodeSet with name and URL properties.

**Comment by jvandriel** [comment]
Taking possible current data consumers into account as well as the fact that `DefinedTermSet` is pretty new makes the feel the best option for support is by going for `codeValue` + `codingSystem`.

Though for the foreseeable future it might be an idea to supersede them with `indefinedTermSet` + `termCode` to prevent any confusement any other publisher (like myself) could have.

Does this sound like a good idea?

**Comment by jorgepa77** [comment]
I'm still totally lost... Please, can anyone provide a short example of a ld+json of @type": "MedicalCode" for a single ICD10 code ? Thanks

**Comment by jvandriel** [comment]
I'm closing this issue until there's a consumer that indicates there's a need to resolve this issue.
