### ISSUE TITLE
Latest 3.8 schema missing definition of PhysicalActivityCategory

### ISSUE THREAD

**Issue by nextdude** [schemaorg/schemaorg#2301]
The [latest version of the schema (3.8)](http://schema.org/version/latest/schema.ttl) includes a reference to the enumeration `schema:PhysicalActivityCategory` as a range for the `schema:category` property, but does not contain the enumeration definition. This is true across all the formats for the schema and seems to go back to at least v3.6.

**Comment by RichardWallis** [comment]
This is another symptom of issue #2302.  The 'schema' dump file does not contain term definitions from extended sections of the vocabulary (PhysicalActivityCategory is defined as part of the health-lifesci section).

I recommend using the all-layers download <[http://schema.org/version/latest/all-layers.ttl](http://schema.org/version/latest/all-layers.ttl)>.

The current set of download files is a little confusing as it emphasises the segregation between sections (previously referred to as extensions) which is no longer treated with the significance as previously.

I am going to close this issue and raise a new one to recommend some rationalisation in this area.
