### ISSUE TITLE
References to pending classes and properties exist in the current schema

### ISSUE THREAD

**Issue by nextdude** [schemaorg/schemaorg#2302]
The current [schema download](http://schema.org/version/latest/schema.ttl), which shouldn't contain pending items, still contains references to those items. Probably not an issue for systems that are using inferencing, but for non-inferencing systems that are processing the schema, it can cause a problem. 

For instance, the `DE-IM9` `geoXXX` properties are defined with ranges that include the pending `GeospatialGeometry` class. However, because its pending, the `GeospatialGeometry` class itself isn't defined in the schema. This inconsistency can cause automatic processing of the schema file to fail.

Another example is the pending `CssSelectorType`, which is defined as the range for `cssSelector` property. The `CssSelectorType` definition doesn't appear in the schema.

I think whatever code is being used to produce the schemas is properly ignoring the pending definitions, but not properly ignoring references to them.

**Comment by RichardWallis** [comment]
I recommend using the all-layers download <[http://schema.org/version/latest/all-layers.ttl](http://schema.org/version/latest/all-layers.ttl)> it contains all sections of the vocabulary including pending, thus bypassing these issues.

**Comment by RichardWallis** [comment]
Closed in favour of issue #2304
