### ISSUE TITLE
Add image & button to tabular datasets jsonld

### ISSUE THREAD

**Issue by exploter** [schemaorg/schemaorg#2305]
I'm trying to add a image and  button to tabular datasets schema (CSVW +schemaorg)
Using the flowing json/ld:

https://pastebin.com/JiEB46ti
Now i need to add an image and button can i use base64Binary or html data type from CSVW Vocabulary ?
For example:

https://pastebin.com/5EjpE042
Or:
https://pastebin.com/wxTEZ02f

Any other solution?

WBR
Menashe

**Comment by RichardWallis** [comment]
Not relevant for SDO
