### ISSUE TITLE
Add Place to domain of latitude and longitude

### ISSUE THREAD

**Issue by tjann** [schemaorg/schemaorg#2307]
Currently, schema.org packages the properties [latitude](https://schema.org/latitude) and [longitude](https://schema.org/longitude) (along with other properties) in type GeoCoordinates; [Places](https://schema.org/Place) can then have property [geo](https://schema.org/geo) -> [GeoCoordinates](https://schema.org/GeoCoordinates).

In many instances, this is extraneous modularization, and it could be useful for a Place to be able to use latitude and longitude properties without creating a GeoCoordinate.

In terms of usage, datacommons.org already uses lat/longs as properties of Places.

**Comment by danbri** [comment]
SGTM but see also #1874 for a variation

**Comment by danbri** [comment]
PR: https://github.com/schemaorg/schemaorg/pull/2308

**Comment by tjann** [comment]
Thanks, Dan!

**Comment by RichardWallis** [comment]
Implemented in PR#2308
