### ISSUE TITLE
Must be datePublished a DateTime?

### ISSUE THREAD

**Issue by hankfrinkel** [schemaorg/schemaorg#2309]
Is the schema.org definition wrong? Because Google description means datePublished is a DateTime but on schema.org is datePublished only a Date.

https://developers.google.com/search/docs/data-types/article?hl=en#non-amp
https://schema.org/NewsArticle

**Comment by psychology-tools** [comment]
No.

The ‘datePublished’ property applies to a broad range of publication types, most of which will have a publication date, but not a specific publication time (newspapers, books, journal articles, etc).

The only publication types with publication times are online news articles, blog posts, tweets, etc. The ‘createdAt’ property expects a DateTime datatype, and is probably more reflective of what you mean here.

But in any case, both the Date and DateTime datatypes are ISO8601 so you can include a time with a date if you want, but to require a publication time for this property would cause lots of problems.

**Comment by akuckartz** [comment]
DateTime != Date therefore the two specifications are contradictory.

**Comment by RichardWallis** [comment]
Recommend the expansion of the rangeIncludes of ```datePublished``` to include  ```DateTime```.

This would reflect the need for some more accurate information about when a CreativeWork is published.

**Comment by RichardWallis** [comment]
Implemented in PR #2380
