### ISSUE TITLE
Review lyrics property for MusicComposition

### ISSUE THREAD

**Issue by jroedel** [schemaorg/schemaorg#2314]
Hi everyone, I'm trying to implement the `lyrics` property of a `MusicComposition` on a website, but it seems very awkward to me that the lyrics property be of type CreativeWork. 

**Use case**: page showing song lyrics with guitar chords, accompanied by markup which would show lyrics without the chords; perhaps for google to consume. 

Simply putting text as the property, Google's structured data checker interprets it as another CreativeWork whose name is the lyrics text I set.

I would argue that it's clear that a song's lyrics don't constitute a separate CreativeWork in a great majority of cases. Perhaps the authors of this property were thinking of exceptions such as Simple Gifts which has several derived lyrics, but these could easily be understood as separate MusicalCompositions.

Thanks for the consideration

**Comment by WeaverStever** [comment]
@jroedel

Not quite sure what problem you are having, the Example 1 on MusicComposition seems to test fine on  SDTT.  The testing tool also accepts a name when I add it to the lyric section.  I.e. the testing tool is not identifying the "text" as the "name" in Example 1.

 Is the page you are marking up online?  An example would help, the testing tool returns a single MusicCompsition object.

**Comment by jroedel** [comment]
Thanks for your quick response. I have an example online: https://schoenstatt.link/en/SL95363C/dona-nobis-pacem

Admittedly, I didn't notice that the example uses the `lyrics` property, but all the same it seems strange to me to define a new CreativeWork, only to use the `text` property (when MusicComposition itself is a CreativeWork).

Now I know how to make it work at least; if I'm the only one who sees this as a problem, feel free to close the issue. 

Thanks!

**Comment by WeaverStever** [comment]
@jroedel 

The creativeWork is within the lyric. Maybe this example will help you:

Say you want the same song, with two language versions of the lyric.

~~~~
<script type="application/ld+json">
{
  "@context":"https:\/\/schema.org",
  "@type":"MusicComposition",
  "@id":"https:\/\/schoenstatt.link\/en\/SL95363C",
  "name":"Dona nobis pacem",
  "inLanguage":"la",
  "genre":"Religious",
  "isFamilyFriendly":true,
  "composer":[],
  "lyricist":[],
  "lyrics":[{
    "@type": "CreativeWork",
    "name": "common lyric",
    "inLanguage":"la",
    "text": "Dona nobis pacem\n\nDona nobis pacem, pacem.\nDona nobis pacem.\n"
  },{
    "@type": "CreativeWork",
    "name": "alternate lyric",
    "inLanguage":"en",
    "text": "An English translation of the lyric,"
  }
  
  ],
  "musicalKey":"C"
}
</script>
~~~~

**Comment by RichardWallis** [comment]
Answered
