### ISSUE TITLE
Using the "Language" element/property

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2315]
Greetings,

I'm looking to implement on my website a few articles about languages. I'd like to mark them up with schema.org using microdata; particularly: https://schema.org/Language

1. When declaring an item type should we use `http` or `https`? The getting started guide illustrates with `http` but schema.org's website is `https`. 

2. `alternateName` this property is interesting... I am wondering How I would mark up the French name for German... In English we say _German_ that would be something like: `alternateName@en`, while in German they say _Deutsch_ `alternateName@de` to indicate that this is the German language variety of the value in the property `Language/name` and in French they say _Allemand_  (plus or minus some agreement marker); so this would be something like `alternateName@fr`. So, how does one indicate the language in which/for which an alternate name is indicated? I could use the HTML `lang="fr"` in the element surrounding the text, but does that translate well for JSON-LD expressions of schema.org?

2. I am familiar with BCP47. The note at the top of the item type says that this code can (should be) be used in the  `alternateName` field. I am wondering why this code is not to be used with the `identifier` property? Can anyone shed some light on this?

**Comment by randyhoulahan** [comment]
RE:2
https://www.w3.org/2018/jsonld-cg-reports/json-ld/#string-internationalization

**Comment by RichardWallis** [comment]
1.  The current canonical definition of a term is http based (see the [more...] link on documentation pages) - it is the website that is currently https.  However many data consumers are forgiving in this respect.  Also see this [FAQ answer](https://schema.org/docs/faq.html#19).

2. The intention in the description I believe is to indicate, as per it can be for any entity type, that potentially it has in addition to its ```name``` value, one or more ```alternateName```.  Both ```name``` & ``` alternateName```, as for any Text value, can have a language tagged string value.
In your use case I would be inclined to define several ```name``` values for each language used for the ```name``` ("German"@en, "Deutsch"@de, "Allemand"@fr), etc.

3. I can see why you are suggesting this, as ```Language``` in the context you are using it is a definition of the term itself, from the set 'BCP47.    In his case I see a couple of options.  a) Also define the entity as a [DefinedTerm](https://schema.org/DefinedTerm), or b) specifying as a fully detailed identifier:
```
"identifier": {
 "@type": "PropertyValue",
   "propertyID": "BCP47",
   "value":  "en"
   }
```

**Comment by RichardWallis** [comment]
Answered
