### ISSUE TITLE
FAQPage and Question on different webpages. Google shows error for Question.

### ISSUE THREAD

**Issue by jsmoriss** [schemaorg/schemaorg#2317]
Visually, I have a FAQ webpage with links to individual Question/Answer webpages.

The FAQPage markup in the FAQ webpage has no errors - each Question/Answer is correctly included in the "mainEntity" property of FAQPage.

The individual Question/Answer webpages are a problem though. These are simple Question/Answer webpages -- they are not FAQPages, although they are included in FAQPages, and they are not QAPages -- they are Question/Answer pages. :)

The markup is correct, but the Google structured data testing tool issues a warning:

"Missing a FAQPage markup item on page to which this item should be associated."

I've tried using an isPartOf property to tell Google that this Question/Answer is part of a FAQPage on another URL, but Google seems to ignore that property.

Is there are proper way to tell Google that this Question/Answer is part of a FAQPage on another URL?

FYI - Here's a real-world example:

https://wpsso.com/docs/plugins/wpsso/faqs/

Thanks,

js.

**Comment by RichardWallis** [comment]
I wouldn't normally answer such a question in this forum, it is usually reserved for discussions and proposals about the structure of the vocabulary itself, not how a data consumer such as the Structured Data Testing Tool interprets instance data. In such a case I would recommend that is asked in a forum associated with the SDTT.

However, there is a shortage of examples around QAPage and FAQPage and some clarity around this issue may help us towards creating some such examples.

Firstly, to clarify an assumption you wrongly make.  _Question_ & _Answer_ are not types of page, they are separate entity types like _Address_, _Person_, _Book_, etc. whereas _QAPage_ & _FAQPage_ are subtypes of _WebPage_.

After some investigation, it is clear that the SDTT is not happy with a _Question_ type definition that is not the _mainEntity_ of a _WebPage_ of some sort.

If this association is defined in the _WebPage_ definition as per this example:
```
[	
 {
	"@context": "http://schema.org",
        "@id": "#P1",
        "name": "Question page",
	 "@type": "WebPage",
         "mainEntity": {
            "@type": "Question",
            "@id": "#Q1"
         }
 },
 {
    "@context": "http://schema.org",
    "@id": "#Q1",
    "@type": "Question",
    "name": "What is the answer to...",
```
Everything is fine.

If it is defined using the _mainEntityOfPage_ property of the _Question_ thus:
```
[	
 {
	"@context": "http://schema.org",
	"@id": "#p1",
        "name": "Question page",
	 "@type": "QAPage"
 },
 {
    "@context": "http://schema.org",
     "@id": "#Q1",
    "@type": "Question",
    "name": "What is the answer to...",    
    "mainEntityOfPage": "#P1",
```
the Question definition is OK **as long as the page it references is of type QAPage or FAQPage.**, as in this example.

However, the tool complains about a FAQPage or QAPage definition that does not include a mainEntity property, so you have to include that reverse relationship also.

As a reminder, these constraints are being applied by the testing tool and are not a function of the Schema.org vocabulary.

**Comment by WeaverStever** [comment]
@RichardWallis 

Thanks for providing this example, I ran into this currently unresolved problem last month.
