### ISSUE TITLE
Type Product and Hotel used for representing any kind of accommodation by OTA's

### ISSUE THREAD

**Issue by igor-susic** [schemaorg/schemaorg#2319]
Not a regular Github issue, but this is the best place at least in my mind to ask this one.

I have noticed that Online Travel Agencies use in most cases either Product or Hotel types to mark their accommodation listings. 

In particular everything that goes under Priceline group usually uses Hotel, and others including AirBnb use Product type. 

Now, in this space, search engines like Google do not support Accommodation/Apartment/House types for any kind of user improvement snippets at least not according to their official documentation [Supported Structured data](https://developers.google.com/search/docs/data-types/article). 

My questions are: what is "best" way to mark any type of accommodation? Does it even matter if you mark private accommodation that is type of House as Hotel or Product, when really either search engines can't see the difference or  won't bother to read the markup how it is supposed to. In which case all these schemas for structured data lose a little sense when companies that founded the group do not support it's efforts at least in space that's big as online traveling.

Please add label question to this one :)

**Comment by OmarJAH** [comment]
Hi there,
I gonna leave this useful link regarding the topic:
https://schema.org/docs/hotels.html

But one thing is what schema.org allows/suggests to be used, another thing is what consuming agents (google rich snippets) allows/expects. 

You are right, Google is also a founder of SDO (schema.org), but different politics/requirements make them use/recommend a slightly different version of SDO, one that at times is contradictory to the version provided by the schema.org vocabulary itself.
e.g. Google's guideline for Flight Reservation suggests using the property "reservationNumber" (see https://developers.google.com/gmail/markup/reference/flight-reservation ), which does not even exist in schema.org (see https://schema.org/reservationNumber and https://schema.org/FlightReservation).

That being said, your question is more regarding the acceptance of schema.org in context of Google's rich snippets, that on the schema.org vocabulary itself. So I would recommend asking your question in their forum: https://support.google.com/webmasters/threads?hl=en&thread_filter=(category:structured_data)

If you have found/will find interesting answers to your question, feel free to share them with us :)
