### ISSUE TITLE
2.4 children? We say Number where we mean Integer 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#232]
http://schema.org/numAdults
http://schema.org/numChildren
http://schema.org/additionalNumberOfGuests
http://schema.org/Integer
http://schema.org/Number
http://schema.org/LodgingReservation 

We should review http://schema.org/Number "Instances of Number may appear as values for the following properties". 

Also suspicious: http://schema.org/additionalNumberOfGuests ...

Reported by Simon Spero @sesuncedu in http://lists.w3.org/Archives/Public/public-vocabs/2015Jan/0057.html

**Comment by vholland** [comment]
I changed the range for:
- numAdults
- numChildren
- numberOfItems
- numberOfEpisodes
- numberOfSeasons
- partySize
- playersOnline
- ratingCount
- reviewCount

See pull request #420.

**Comment by danbri** [comment]
Thanks :)
