### ISSUE TITLE
should isPartOf and hasPart accept URL?

### ISSUE THREAD

**Issue by chrisgorgo** [schemaorg/schemaorg#2321]
Currently, two properties denoting relationships between `CreativeWork` - `isBasedOn` and `sameAs` accept URL as a value. This makes it easy to link entities without providing extensive markup.

The same is not true for `hasPart` and `isPartOf` - those require `CreativeWork` entity. Is this on purpose or merely an omission that could be rectified? Allowing URL for those values would make syntax cleaner and more consistent.

**Comment by RichardWallis** [comment]
Although URL is not listed as an expected type for these properties, it still can be used (as for all properties).

See [documentation](https://schema.org/docs/datamodel.html#conformance) for clarification: "_some types such as Role and URL can be used with all properties_"

**Comment by chrisgorgo** [comment]
Thanks @RichardWallis!
@danbri should we add this to documentation explicitly (as it is the case with `sameAs`) or just leave it as it is and close the issue?

**Comment by whitten** [comment]
I'm of the opinion that readers are lazy enough to have only skimmed the documentation, and a situation like @chrisgorgo found himself will just generated FAQs unless the ability to use Role and URL is made more explicit in cases where it logically could be used.

**Comment by danbri** [comment]
There's also a case to add URL here explicitly as it is a likely value, and our system will automatically make @ -id the default in the JSON-LD context if we do so.

**Comment by RichardWallis** [comment]
implemented in commit 6969f50
