### ISSUE TITLE
Reverse property of Event/attendee for a Person or Organization

### ISSUE THREAD

**Issue by davux** [schemaorg/schemaorg#2324]
Hello,

I would like to describe the fact that a Person or Organization is an attendee of a given Event, from the perspective of said Person or Organization. Something like (in JSON):

```json
{
  "@context": "http://schema.org",
  "type": "Person",
  "name": "Jane Doe",
  "attendeeAt": {
    "type": "Event",
    "id": "xxxx",
    "description": "Great Event"
  }
}
```
However I can't see anything like that. I'm kind of new to this, but I would say Person and Organization should get a new optional attribute `attendeeAt` (or similar). That attribute would, in other words, be the reverse attribute for `attendee` in Event. Otherwise, what would be the recommended approach?

Thanks!

**Comment by RichardWallis** [comment]
If there is a fine line between having useful reverse properties for common relationships between types, and overwhelming the vocabulary with reverse properties for everything.

Others may agree that a new ```attendeeAt``` property for ```Person``` is a good idea.  I personally think that the use cases for it are a bit limited.

In which case you will obviously question how you achieve what you describe.  Fortunately JSON-LD comes to the rescue with the ability to describe reverse relationships:
```
{
  "@context": "http://schema.org",
  "type": "Person",
  "name": "Jane Doe",
  "@reverse": {
    "attendee": {
        "type": "Event",
        "id": "xxxx",
        "description": "Great Event"
    }
  }
}
```
~Richard.
