### ISSUE TITLE
schema:purpose is poorly defined

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#233]
http://schema.org/purpose

```
"1:  The range of schema:purpose has no purpose. MedicalDevicePurpose OR Thing  = Thing"
```

Reported by Simon Spero @sesuncedu in http://lists.w3.org/Archives/Public/public-vocabs/2015Jan/0056.html

There is more at fault here than the range of the property (and https://github.com/schemaorg/schemaorg/blob/master/tests/test_graphs.py#L97 ought to have caught that, but didn't)

This looks to me like http://schema.org/purpose was repurposed from the original medical vocabulary (i.e. a Diagnostic or Therapeutic http://schema.org/MedicalDevice as purpose of a http://schema.org/MedicalDevice ), generalizing it for use with http://schema.org/PayAction and http://schema.org/AllocateAction. The definition "A goal towards an action is taken. Can be concrete or abstract." is action-centric.

Nearby, there is a proposal for more/better/fixed medical and health vocabulary. We should have a look there for what is proposed for 'purpose'. We should also check in with Actions vocab users to see if it is being used. I have found no evidence that either sense of 'purpose' is seeing significant active usage.

**Comment by twamarc** [comment]
+1 generalizing it (extending domain/range or shift it under 'Thing'.)
In the proposal this was not done:
http://demoschemed.appspot.com/purpose

To check vocab users to see if it is being used: just from my side, I am already using it in couple of instances, but this cannot prevent extending it as we can fix our model accordingly.

**Comment by sesuncedu** [comment]
It's a lot easier to run tests in groovy or clojure w/ java, since you have a lot more tools and reasoners to work with. I haven't tried to configure Travis-CI for multiple independent build systems, but at worst its easy enough to do it in gradle.  

[The real WTF is microdata forcing a flat namespace onto everything (except instances). 
The medical vocabulary is the best / worst example... Microdata can be fixed if Google wants it. The / expansion mechanism backs things into a bit of a corner, but URL scheme kludgery can open the way for prefixes.]

**Comment by danbri** [comment]
Thanks Marc, Simon. On Simon's points:

RDFa and JSON-LD use flat namespaces too, right?

The site itself is Python-based and we might add rdflib as  dependency there, but dragging in java feels heavy. Nothing wrong with running additional tools of course. Gregg @gkellogg had some Ruby linter that also caught a bunch of problems, however I never got it running locally due to Ruby version pains.

**Comment by gkellogg** [comment]
The main difference between RDFa, JSON-LD and Microdata is that Microdata only easily allows a single namespace, but it doesn't need to be flat. For example, you could do the following:

    <div itemscope='' itemtype="http://example.org/Person">
      <p>Name: <span itemprop="name/extension">Amanda</span></p>
    </div>

This also works in RDFa

    <div typeof="schema:Person">
      <p>Name: <span property="schema:name/extension">Amanda</span></p>
    </div>

And JSON-LD

    {
      "@context": {"ex": "http://example.org"},
      "@type": "ex:Person",
      "ex:name/extension": "Amanda"
    }

@danbri just install rvm; easy to handle multiple ruby versions, but the linter can be made to run on most any version of Ruby, so no excuse!

**Comment by sesuncedu** [comment]
I would not add groovy & java to the running site; for the build process
it's a different issue.  Python dependency management is a squeaky pip
(jython simplifies this by having the package not work).
Ruby's gem system is generally surprisingly unsurprising.

Dependency management in java is pretty good (especially  if you don't
access it from maven).

Mapping domain and range  includes to owl union classes,  generically
naming them, then classifying the ontology, is very revealing (subtly
different sets; heavily reused patterns, etc).

purpose was  noteworthy because it induced the only class that was
equivalent to schema:Thing :-)

**Comment by sesuncedu** [comment]
Microdata has the arbitrary restriction on "vocabulary" that applies even
if all property names are absolute, and sort of blocks the use of
abbreviated IRIs, unless you abuse URI schemes.

schema.org is somewhat trapped because of the / is subsumption hack.

**Comment by gkellogg** [comment]
@sesuncedu said:

> Microdata has the arbitrary restriction on "vocabulary" that applies even
if all property names are absolute, and sort of blocks the use of
abbreviated IRIs, unless you abuse URI schemes.

Hmm, not sure where you see the restriction on `@itemprop` where the value is an absolute URI. Certainly, the Microdata to RDF spec will properly emit such properties.

From the Microdata spec:

> Each token must be either:

> * If the item is a typed item: a defined property name allowed in this situation according to the specification that defines the relevant types for the item, or
> * A valid URL that is an absolute URL defined as an item property name allowed in this situation by a vocabulary specification, or

The first just said defined by _a_ vocabulary, not necessarily the vocabulary used in `@itemtype`.

**Comment by sesuncedu** [comment]
It's the itemtype restriction - hence all the additionalType cruft, and the
need for absolute URI properties for all but the primary vocabulary.

There quite a few very odd ranges and definitions, caused by merging
independent vocabularies together...

**Comment by danbri** [comment]
How about:

rangeIncludesHint as a property relating a Property to a Class representing a type that is a subtype of a rangeIncludes value but is particularly pertinent (e.g. might be explicitly indicated in UI).

For example,

        rdfa schema.rdfa | grep foodEstablishment
        <http://schema.org/foodEstablishment> <http://www.w3.org/2000/01/rdf-schema#comment> "A sub property of location. The specific food establishment where the action occurred." .
        <http://schema.org/foodEstablishment> <http://www.w3.org/2000/01/rdf-schema#subPropertyOf> <http://schema.org/location> .
        <http://schema.org/foodEstablishment> <http://schema.org/rangeIncludes> <http://schema.org/FoodEstablishment> .
        <http://schema.org/foodEstablishment> <http://www.w3.org/2000/01/rdf-schema#label> "foodEstablishment" .
        <http://schema.org/foodEstablishment> <http://schema.org/rangeIncludes> <http://schema.org/Place> .
        <http://schema.org/foodEstablishment> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
        <http://schema.org/foodEstablishment> <http://schema.org/domainIncludes> <http://schema.org/CookAction> .

... here we already know that FoodEstablishment since Place is applicable. And lots of different places can be eaten at, even if their relevant facilities are rarely modeled or documented. So we could say "foodEstablishment rangeIncludesHint FoodEstablishment" to highlight the most relevant subtype.

**Comment by danbri** [comment]
Moving discussion back to 'purpose' itself. I believe the definition as-is is pretty weak, but I do not propose amending it for our next upcoming release (sdo-gozer). I'm marking this for attention in Q2 milestone, where we'll need to consider the wider story around medical/health and its relationship to the extensions mechanism #429.

**Comment by danbri** [comment]
This was removed for usability reasons - see https://github.com/schemaorg/schemaorg/issues/2435
