### ISSUE TITLE
Issue with nokogiri gem causing security alert for continuous integration tests

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2333]
Github is reporting a [security alert](https://github.com/schemaorg/schemaorg/network/alert/scripts/Gemfile.lock/nokogiri/open) for the version of **nokogiri** gem.

As it is only used in the Travis continuous integration tests it is very unlikely to be an issue for our environment.  However it needs fixing to remove the alert.

**Comment by RichardWallis** [comment]
Fixed in master

**Comment by gkellogg** [comment]
In the future, rather than editing Gemfile.lock by hand, run “bundle update”.

**Comment by RichardWallis** [comment]
Thanks @gkellogg for the hint.

I don't have that in my dev environment so I went for the path of least resistance ;-)

**Comment by gkellogg** [comment]
Feel free to assign me any tasks related to the Ruby environment.
