### ISSUE TITLE
Add SoftwareApplication to itemOffered expected values

### ISSUE THREAD

**Issue by JeffreyBurns** [schemaorg/schemaorg#2337]
Google is expecting that a SoftwareApplication includes Offer schema. https://developers.google.com/search/docs/data-types/software-app#softwareapplication

You can nest the Offer schema within the SoftwareApplication just fine. However if you wish to have Offer schema as the primary entity then you cannot nest SoftwareApplication under the itemOffered property. 

If we agree that SoftwareApplications should have Offer schema, then it makes sense to me that it should be able to function in either direction.

**Comment by inetbiz** [comment]
Neither can you nest WebApplication @danbri

**Comment by jvandriel** [comment]
In easy fix to work around this is to use a multi typed entity as such:
```
{
  "@type":"Offer",
  "itemOffered":
  {
     "@type":["Product","SoftwareApplication"]
  }
}
```

**Comment by RichardWallis** [comment]
Answered
