### ISSUE TITLE
add cosmeticsStore in store specific types, also add cosmetics in product specific types.

### ISSUE THREAD

**Issue by numanzahid** [schemaorg/schemaorg#2338]
Cosmetic Store is type of local business in google and there is huge industry.
there should be local business type of cosmeticsStore as there is bookStore and toyStore.

there is very limited specific types under product thing. there should be more options and with respect to cosmeticsStore there should be cosmetics type under a product, as there is vehicle.

BTW there are even more specific types under vehicle which can also be true for cosmetics.

why there is only vehicle as real product type in schema.org. Looks like it is only for vehicle lovers. :)

**Comment by mfhepp** [comment]
Hi,
first of all: The absence of a more specific type in schema.org for a category of things does not at all imply any statement regarding the relevance of those things. Schema.org does not try to create a taxonomy of everything that exists on earth, but rather facility the extraction of information from Web content and other sources of data for a broad range of applications consuming such data, namely major search engines.

A more specific type is typically useful

1. if there are relevant consumers of the data that benefit from a more subtle distinction (e.g. if a search engine will show a different knowledge panel or layout for search results, or if other properties are needed)
AND (!)
2. if the more specific types can and will be used by owners of Web content in sufficient quality and quantity (this often depends on whether the underlying distinctions match the existing data sources of many Web sites).

Sometimes, we also have additional types solely for the purpose of making it easier for Web developers to find the proper type in the documentation, even though there will be no actual use of the type.

As for more specific product types: There are hundreds of thousands of types of products; a full taxonomy of product types is beyond the scope of schema.org. But you can combine schema.org with the 300,000+ precise product type classes provided by www.productontology.org, like e.g.

    http://www.productontology.org/doc/Cosmetics
    http://www.productontology.org/doc/Lipstick
    http://www.productontology.org/doc/Sunscreen
    http://www.productontology.org/doc/Nail_polish
    http://www.productontology.org/doc/Hand_sanitizer
    http://www.productontology.org/doc/Hair_spray
    http://www.productontology.org/doc/Lip_gloss
    http://www.productontology.org/doc/Lip_balm
    http://www.productontology.org/doc/Concealer
    http://www.productontology.org/doc/Face_powder
    http://www.productontology.org/doc/Rouge_(cosmetics)
    http://www.productontology.org/doc/Mascara
    http://www.productontology.org/doc/Eye_shadow
    http://www.productontology.org/doc/Eye_liner
    http://www.productontology.org/doc/Eyelash_extensions

The URIs above include markup examples in both Microdata and RDFa, but you can also use these additional types in JSON-LD (as many sites do).

Hope that helps!

Best wishes
Martin Hepp


-----------------------------------
martin hepp  http://www.heppnetz.de
mfhepp@gmail.com
@mfhepp

**Comment by numanzahid** [comment]
Thanks for the clear answer.
