### ISSUE TITLE
Adding cost property to a Recipe

### ISSUE THREAD

**Issue by drigomic** [schemaorg/schemaorg#2339]
To help searching and filtering based on available budget a "cost" property is suggested. 
In order to make it independent from the currency and the cost of good this property can assume the following values (Text): e.g. cheap, moderately priced, expensive.

**Comment by JohJohan** [comment]
There is a tag for estimatedCost see https://schema.org/estimatedCost

**Comment by RichardWallis** [comment]
Answered
