### ISSUE TITLE
Add gender to SportsTeam

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2341]
There is currently no way to specify the gender of the players associated with a given sports team. For example, there is no way to differentiate the University of Connecticut men's and women's basket ball teams.

I suggest we extend the domain for http://schema.org/gender to include http://schema.org/SportsTeam.

**Comment by danbri** [comment]
See https://lists.w3.org/Archives/Public/public-schemaorg/2019Oct/0013.html from @nicolastorzec 

I suggest we fix the textual definition here before finalizing v4 and come back later to the larger question of a structure mixed-gender non-person entities

**Comment by RichardWallis** [comment]
Implemented in [Release 4.0](https://schema.org/docs/releases.html#v4.0)
