### ISSUE TITLE
https://schema.org/MedicalBusiness is not present in JSON-LD format releases

### ISSUE THREAD

**Issue by erichpletsch** [schemaorg/schemaorg#2343]
Within the releases (ex. 3.8, 3.9) are three objects that reference MedicalBusiness as their parent entity - these include Dentist, Physician and Pharmacy.  However, MedicalBusiness is not contained in the JSON-LD or RDFa release.  It is included in the owl release file.

**Comment by fabricetheytaz** [comment]
It's not in CSV release too.

**Comment by RichardWallis** [comment]
Code that appears to be responsible for this defect has been been moved into a separate [sdopythonapp](https://github.com/schemaorg/sdopythonapp) repository.

This issue has been replaced by a new[ issue in that repository](https://github.com/schemaorg/sdopythonapp/issues/2)

**Comment by RichardWallis** [comment]
@erichpletsch, @fabricetheytaz,   Analysis has identified that this is not a defect.

The symptoms are the effects of the distribution of term definitions across sections of the vocabulary, based on previous [hosted extensions](https://schema.org/docs/extension.html). 

The definitions for Dentist, Physician etc. are in the core of the vocabulary, whereas MedicalBusiness, one of their super-types, is defined in one of the extensions.

The file chosen for [Downloading](https://schema.org/docs/developers.html#defs)  influences which term definitions are included.    The '_schema_' file only includes definitions from the core of the vocabulary, providing the symptoms described here -  types referenced as super-types not defined in the same file.

To avoid such issues, it is recommended to download the '_all-layers_' file, which includes all term definitions.
