### ISSUE TITLE
NewsArticle  is not a known valid target type for the itemReviewed attribute

### ISSUE THREAD

**Issue by truongemcom** [schemaorg/schemaorg#2346]
Please guide me how to fix it, thanks a lot.

**Comment by rrlevering** [comment]
This is a Google specific validation error you are referencing.  It's not a schema.org issue, which allows any Thing on itemReviewed.  Please refer to Google's documentation: https://developers.google.com/search/docs/data-types/review-snippet#review-properties

**Comment by truongemcom** [comment]
thanks
