### ISSUE TITLE
musicBy property could be made applicable to more types

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#235]
http://schema.org/musicBy

        3: schema:musicBy has a much smaller domain than actor or director

Reported by Simon Spero @sesuncedu  in http://lists.w3.org/Archives/Public/public-vocabs/2015Jan/0056.html

http://schema.org/actor and http://schema.org/director are applicable on:

* Clip 
* Episode 
* Movie 
* MovieSeries 
* RadioSeries 
* TVSeries 
* VideoGame 
* VideoGameSeries 
* VideoObject

Whereas musicBy only has: Episode, Movie, RadioSeries, TVSeries.   

Missing: Clip, MovieSeries, VideoGame, VideoGameSeries, VideoObject.

I see no reason not to make it the same list. 

/cc @vholland

**Comment by vholland** [comment]
+1. Music is a big deal in certain kinds of video games.
