### ISSUE TITLE
@context for schema.org contains "xsd1": "hhttp://www.w3.org/2001/XMLSchema#",

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [schemaorg/schemaorg#2355]
The schema.org [context file](https://schema.org/docs/jsonldcontext.jsonld) contains this odd buggy line:

`        "xsd1": "hhttp://www.w3.org/2001/XMLSchema#",`

This line is also present in every @context in the JSON-LD description of all schema.org terms (e.g., [schema:Thing](https://schema.org/Thing.jsonld)). It's probably a harmless copy-paste accident or something similar, but it's useless. Please remove.

**Comment by RichardWallis** [comment]
Code that appears to be responsible for this defect has been been moved into a separate [sdopythonapp](https://github.com/schemaorg/sdopythonapp) repository.

This issue has been replaced by a new[ issue in that repository](https://github.com/schemaorg/sdopythonapp/issues/3)
