### ISSUE TITLE
Representing mathematical objects

### ISSUE THREAD

**Issue by progval** [schemaorg/schemaorg#236]
Is there any type that could be use for representing mathematical objects? (eg. a polynomial, and integer sequence, a formula, …)

**Comment by danbri** [comment]
We have not attempted that, but I would imagine MathML would be more appropriate than us inventing specific things in schema.org for this.

* http://www.w3.org/TR/MathML/
* https://html.spec.whatwg.org/multipage/the-map-element.html#mathml
* https://wiki.whatwg.org/wiki/MathML

I don't believe Microdata supports properties whose value is complex markup but RDFa might work. /cc @gkellogg @scor 

Here's some MathML from the HTML5 spec:

        <!DOCTYPE html>
        <html>
         <head>
          <title>The quadratic formula</title>
         </head>
         <body>
          <h1>The quadratic formula</h1>
          <p>
           <math>
            <mi>x</mi>
            <mo>=</mo>
            <mfrac>
             <mrow>
              <mo form="prefix">−</mo> <mi>b</mi>
              <mo>±</mo>
              <msqrt>
               <msup> <mi>b</mi> <mn>2</mn> </msup>
               <mo>−</mo>
               <mn>4</mn> <mo>⁢</mo> <mi>a</mi> <mo>⁢</mo> <mi>c</mi>
              </msqrt>
             </mrow>
             <mrow>
              <mn>2</mn> <mo>⁢</mo> <mi>a</mi>
             </mrow>
            </mfrac>
           </math>
          </p>
         </body>
        </html>

From a schema.org perspective I guess we'd want to figure out what RDFa could be added into this page - e.g. using http://schema.org/WebPageElement or how another page might usefully describe this entire document.

Do you have a particular use case in mind?

**Comment by ProgVal** [comment]
Not exactly what I meant.

The use case I have in mind is I want to store an integer sequence (as stored in the [OEIS](http://oeis.org/)), which would be characterized by a formula, a name, a definition, a description, etc.
(I mean an infinite sequence, so http://schema.org/Enumeration is not suitable)

**Comment by gkellogg** [comment]
Microdata just recently [added support](http://www.w3.org/TR/microdata-rdf/#dfn-property-value) for <data> values to be interpreted as Integer or Double, if they parse according to xsd:integer, xsd:float, or xsd:double. Also the <meter> element uses the same rules.

Also <time> values can be interpreted as various XSD date, time and duration typed literals.

RDFa could capture the entire MathML by using `@datatype="HTML"` or `@datatype="XMLLiteral"`, but that's not included in RDFa Lite.

**Comment by thadguidry** [comment]
Working examples of MathML in practice can be found in section 6.7 of : http://natureofcode.com/book/chapter-6-autonomous-agents/

Schiffman's types in the book (thus far) can be found documented here: https://github.com/shiffman/The-Nature-of-Code-archive/blob/master/raw/chapters/math.asc

**Comment by danbri** [comment]
(I think that's http://www.mathjax.org/ rather than Chrome doing the rendering) 

(great book btw:)

**Comment by thadguidry** [comment]
@danbri Ah, your right.

**Comment by akuckartz** [comment]
W3C MathML 3.0 Approved as ISO/IEC International Standard
23 June 2015
http://www.w3.org/2015/06/mathmlpas.html.en

**Comment by chaals** [comment]
It is still unclear to me what you want to actually say…
I *think* you want to mark up bits of text like
> The series of numbers 1, 1, 2, 3, 5, 8, 13… 
> which can be represented by the an expression such as
> { f(n) = (n>2) ? f(n-1) + f(n-2) : 1 },
> are known as the fibonacci series

(I apologise to my maths teachers if there is a mistake there)

What I don't understand is how exactly you want to mark it up. Do you want to be able to link the series, the expression, and the name, like
```html
<div type="MathematicalExpression">
<span property="series">0, 7, 7, 3, 4, 7, 1, 7, 5</span> has the formula 
<mathml property="formula"><!-- some mathml --></mathml>, 
and is known as the <span property="name">wkrtsfg</span>…
```
(which is using some made-up terms like `MathematicalExpression` and `formula`)

Or have I totally missed it still?
