### ISSUE TITLE
What type of markup for cryptocurrency exchanges in json + ld?

### ISSUE THREAD

**Issue by blogi-kriptovalyut** [schemaorg/schemaorg#2369]
What type of markup for cryptocurrency exchanges in json + ld?
Hello.
The site has articles about crypto exchanges (the article has: rating, comments, reviews, how to use, etc.)

They are marked as type "Organization"

Example:
```
<Script type = "application / ld + json"> {
"@context": "http://schema.org",
"@graph": [
{
"@type": "Organization",
"name": "Binance",
"aggregateRating": {
"@type": "AggregateRating",
"ratingValue": "4.35",
"ratingCount": "180",
"bestRating": "5",
“Worst rated”: “1”
},
"overview": [
{
"@type": "UserReview",
"reviewBody": "Binance is a great platform and I use it without any problems.",
"datePublished": "2018-06-26T00: 03: 36 + 03: 00",
"author": {
"@type": "Person",
"@id": "157",
"name": "Ash",
"url": "https://bytwork.com/comment/157#comment-157"
}
}
]
}
]
} </ SCRIPT>
```

However, Google support writes:

> There are no errors, but you clearly do not intend to use the markup for its intended purpose

In this regard, the question:
For (type Organization), does this mean that it is intended to be used **only** by the organization itself?
Our pages provide information about the organization: (how to use the site (HowTo), review (article), address (if any), user ratings and comments (Review). What types of markup should I choose?
Thanks for your attention.
Help me please i'm confused!

**Comment by danbri** [comment]
You appear to be hitting (Google) policy issues that relate more to some specific Google products/features, than to schema.org itself. I suggest you raise them in the Google product forums - see https://productforums.google.com/forum/#!categories/webmasters/structured-data and nearby.
