### ISSUE TITLE
Re-evaluate possible controlled values (enums, subtypes) for applicationCategory

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#237]
http://schema.org/applicationCategory

See also https://developers.google.com/webmasters/structured-data/rich-snippets/sw-app

This vocab was originally proposed by a Google team - see https://www.w3.org/wiki/WebSchemas/SoftwareApplicationSchema - but when first incorporated into schema.org we trimmed it significantly, removing a hierarchy of application types. Google's Rich Snippets docs continued to note that they'd understand the larger proposal. 

Some time has passed, let's check in on this again and see if we're any closer to rough consensus.

The complete list of proposed types was: GameApplication, EntertainmentApplication, BusinessApplication, MultimediaApplication, DeveloperApplication, DriverApplication, EducationApplication, HealthApplication, TravelApplication, FinanceApplication, SecurityApplication, BrowserApplication, CommunicationApplication, DesktopEnhancementApplication, DesignApplication, HomeApplication, SocialNetworkingApplication, UtilitiesApplication, ReferenceApplication, SportsApplication, ShoppingApplication, MedicalApplication, OtherApplication.

**Comment by tomillo** [comment]
What's about the "DesignApplication"? It's working or not?
