### ISSUE TITLE
Version 5.0 planning (goal: 2019-11-01; expected goal: 2019-11-06)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2370]

**Comment by danbri** [comment]
-[x] https://github.com/schemaorg/schemaorg/issues/2372 - extend callSign /cc #2109 
-[x] #2374 Health info schema
-[x] #2373 Real estate properties incl bathroom
- ...

**Comment by philbarker** [comment]
Can we include #2322 link JobPostings to formal definitions of competencies under ... ? PR #2354

**Comment by danbri** [comment]
done!

**Comment by danbri** [comment]
circulated for review, https://lists.w3.org/Archives/Public/public-schemaorg/2019Oct/0033.html
