### ISSUE TITLE
Add properties for detailed real-estate description incl bathrooms

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2373]
We are missing some properties for things such as number of bathrooms, although we do have https://schema.org/numberOfRooms as a start. 

# Bathrooms 

https://schema.org/numberOfRooms is defined as 

> The number of rooms (excluding bathrooms and closets) of the accommodation or lodging business.  Typical unit code(s): ROM for room or C62 for no unit. The type of room can be put in the unitText property of the QuantitativeValue.

It would be useful to have ability to be clearer about the number of bathrooms, including notions of "full" and "half" bathroom as used in real estate rental and sales industry.

# other

* We should be able to indicate when an image is a floor layout image e.g. by dedicated property like accomodationLayoutImage
* Propose a subproperty of /category, /accomodationCategory to indicate kinds of accomodation, drawing on values from  https://ddwiki.reso.org/display/DDW17/PropertySubType+Field
and https://ddwiki.reso.org/display/DDW17/PropertyType+Field (a new subproperty lets us document this more clearly)
* How do document the length of a lease? @mfhepp what modeling idiom would you suggest? e.g. where would a /leaseLength property best be attached? Offer has temporal properties like eligibleDuration but they naturally apply to the offer and not the thing offered. But we do not model leases as explicit things, just as a enumeration option in businessFunction. An OfferForLease property would be a possibility, but that weighs against treating OfferForLease purely as a shorthand for GR. Suggestions?
* On /Apartment, a property for representing /floorLevel relative to local standards. Definition could point to Wikipedia's entry for explanation. https://en.wikipedia.org/wiki/Storey#Consecutive_number_floor_designations
* We could make some amenities easier to describe with a dedicated property. See also https://schema.org/amenityFeature. e.g.
  * hardwood floors
  * Washer dryer options (hookups vs in-unit vs on-premises)
  * Dishwasher
  * AC\Cooling\Heating
  * Balcony
  * Furnished
  * End unit - is this unit an endcap or share both walls
  * Utilities included
* Add to ApartmentComplex: Total number of units; Number of available units.
  * Maybe make some community level amenities easier to describe with a dedicated property:
Pool
  * Potentially a new type for FloorPlan/Model, including total number of units, number of available units.
* Clarify how RealEstateListing relates to these and existing GoodRelations fundamental patterns (e.g. via mainEntity), including how to indicate when a listing was posted.

**Comment by danbri** [comment]
see also eg. https://webschemas.org/floorLevel (currently under review for november release), alongside accommodationCategory, floorLevel, leaseLength, numberOfBathroomsTotal, numberOfFullBathrooms. A "floor plan" property for floor plan images likely to be proposed here too.

**Comment by marcelolara10** [comment]
> see also eg. https://webschemas.org/floorLevel (currently under review for november release), alongside accommodationCategory, floorLevel, leaseLength, numberOfBathroomsTotal, numberOfFullBathrooms. A "floor plan" property for floor plan images likely to be proposed here too.

Hello @danbri they were released or still pending? I want to know if i can use them

thanks

**Comment by danbri** [comment]
also https://github.com/schemaorg/schemaorg/commit/e7a09e6e7b72a81637b7c0e3e5f19a655e1497f3

**Comment by danbri** [comment]
@marcelolara10 these are being queued for review/release as schema.org version 6.0. Currently they are only on the pre-review staging site, webschemas.org. Nothing stops you using them but be aware change is possible, and as these are early days, they might not be widely understood yet.

**Comment by danbri** [comment]
Some additional improvements:

* Add petsAllowed to ApartmentComplex
* Add petsAllowed, amenityFeature and floorSize to FloorPlan
* Create an explicit numberOfBedRooms and allow it in Accommodation, ApartmentComplex and FloorPlan.
* In ApartmentComplex and FloorPlan the value might be a range to allow describing all apartments under that entity, so the value should allow both Number and QuantitativeValue
* Add a "book a tour" (/tourBookingPage) property - url value allowed on Accommodation and ApartmentComplex

(todo)
* CONSIDER allowing numberOfBathroomsTotal, numberOfFullBathrooms, numberOfPartialBathrooms and floorSize on ApartmentComplex
so long as semantics were clear.

**Comment by nicolastorzec** [comment]
We may want to clarify the definition for bathroom?
- [Wikipedia](https://en.wikipedia.org/wiki/Bathroom): "In some countries, the toilet is usually included in the bathroom, whereas other cultures consider this insanitary or impractical, and give that fixture a room of its own."
- For example in France you would typically get two different numbers: one for the number of rooms with a sink/bathtub/shower, and another one for the number of rooms with a toilet.

Regarding the todo item:
- I understand why numberOfBathroomsTotal, numberOfFullBathrooms, numberOfPartialBathrooms and floorSize can be useful for an hostel or B&B, but what's the use case for ApartmentComplex?

**Comment by RichardWallis** [comment]
Implemented in several commits
