### ISSUE TITLE
Property "owns" of Product Type is wrongly described

### ISSUE THREAD

**Issue by Elwinlhq** [schemaorg/schemaorg#2377]
Hi all,
I want to notify that there is an error in the description of the property "[owns](https://schema.org/owns)", which has two cases:
- [Organization](https://schema.org/Organization) Type has a property called "owns" that has as expected values "OwnershipInfo" or "Product", but its description says "Products owned by the organization or person"
- [Product](https://schema.org/Product) Type has "owns" property too, but its expected values are "Organization" or "Person" and its description says "Products owned by the organization or person".

However, "[owns](https://schema.org/owns)" property has as range values "OwnershipInfo or Product" and as domain "Organization or Person".

Therefore, I assume that the property owns of Product Type has an incorrect description of "expected values" and I am not sure if this fits for Products description, I guess it would be more like "owned". please have a look and tell me if am I wrong?

Best regards,
Elwin

**Comment by RichardWallis** [comment]
@Elwinlhq you are correct, Organization Type has a property called "owns".  However it is not correct that Product has a similar property.

What may be confusing is that _owns_ is listed on the Product page in the [section](https://schema.org/Product#incoming) headed '_Instances of Product may appear as values for the following properties_'.  _owns_  is listed there as a property that has an expected type that includes Product, and that property is found on types Person & Organization.
