### ISSUE TITLE
Does the order of schema cause an index conflict? 

### ISSUE THREAD

**Issue by mjmdesignz** [schemaorg/schemaorg#2379]
Hello,

Can the order of Schema properties @type cause Google to not index your website schema? 

I have implemented schema to my portfolio website but it seems not to be displayed on Google. its been two weeks now and nothing has appeared, I have made adjustments as well thinking it might make a difference with Google indexing my schema, but nothing. 

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fmjmdesignz.com%2Fhollywood-web-design.html

**Comment by RichardWallis** [comment]
Within the the definition of the vocabulary, the order that properties are defined has no influence on validity.

 This is not the forum to ask questions as to how Google use your data, I suggest their product forums https://productforums.google.com/forum/#!categories/webmasters/structured-data and nearby.
