### ISSUE TITLE
Vocabulary definition files not available on schema.org

### ISSUE THREAD

**Issue by allforabit** [schemaorg/schemaorg#2386]
I'm getting a 404 when I try to download the schema definition files. E.g. https://schema.org/version/5.0/schema.nt

**Comment by RichardWallis** [comment]
Currently V 5.0 is in mid deployment.

Please wait for an hour and try again.

~Richard
Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by allforabit** [comment]
Ah great thanks!
