### ISSUE TITLE
 schema.org -> Product, questions on the url, sku & review

### ISSUE THREAD

**Issue by boteha** [schemaorg/schemaorg#2395]
Hello,

I have an online retail site.

1) A lot of products exist in different versions.
For example, a ribbon of silk: 10 different sizes & colors, meaning 100 versions of the same product.
Only one web page with 100 references and 100 prices.
The type "Product" does not cover this.
Do you know of a suitable type?

2)
An example of a product sheet with only one version.

Code : 

```
<script type="application/ld+json">
{
"@context": "http://schema.org/",
"@type": "Product",
"offers":
{
"@type": "Offer",
"priceCurrency": "EUR",
"availability": "http://schema.org/InStock",
"itemCondition": "http://schema.org/NewCondition",
"seller":
{
"@type": "Organization",
"name": "monsite.com"
},
"price": "3.55",
"priceValidUntil": "2019-10-28"
},
"aggregateRating":
{
"@type": "AggregateRating",
"reviewCount": "37",
"ratingValue": "4,8"
},
"brand":
{
"@type": "Thing",
"name": "Roline"
},
"name": "Connecteur RJ45, Cat6a, blind&eacute; SFTP (STP), Keystone, premier prix",
"image": "https://www.monsite.com/im/pr/433G.jpg",
"mpn": "26.99.0366",
"description": "Ce noyau Cat6a blind&eacute; est &eacute;conomique mais sans concession sur la qualit&eacute;&nbsp;
: courbe d'att&eacute;nuation excellente, test&eacute; pour Grade 3 TV, facile &agrave; installer. | Une version (Cat6a, Blind&eacute; SFTP (STP)) &agrave; 3,55 &euro; TTC.",
"gtin13": "7611990198023"
}
</script>
```

Google me signals 3 errors:
Missing field "review"
Missing field "url"
Missing field "sku"

I have searched the schema.org website.

Missing field "review"
Propriété de Product
A review of the item
I don't understand what they want…
The propriety Description isn't sufficient?

Missing field "url"
Propriété de Thing
URL of the item
I suppose that I have to put a canonical URL as they request.
So the URL can be different than the one of the displayed page?

Missing field "sku"
Propriété de Thing
The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.
What difference with the mpn that I'm using?

Thanks in advance.

**Comment by RichardWallis** [comment]
1.  Checkout the [ProductModel](https://schema.org/ProductModel) type.
2. First a comment, the Google [Structured Data Testing Tool ](https://search.google.com/structured-data/testing-tool) is not highlighting 3 _errors_.  It is providing 3 _warnings_ which are suggesting improvements to your data that would assist their services.

However this is not the forum to ask questions as to how Google use your data, I suggest their product forums https://productforums.google.com/forum/#!categories/webmasters/structured-data and nearby.
