### ISSUE TITLE
Provide information about employer in JobPostings

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#2396]
More information that would be useful includes
- contact details for the JobPosting (this may be different / more specific than the general contact details of the hiringOrganization, may vary by the job on offer)
- an employer overview, information to attract people to work for them, e.g. what they are like as an employer. Again, this may be different to the description of the hiringOrganization for general consumption.
- a standard code (e.g. NAICS, SOC) for the industry, currently the [industry](https://schema.org/industry) property only accepts text.
The second and third of these have been piloted and found useful by the [JDX project](https://www.uschamberfoundation.org/workforce-development/JDX); All three have been discussed by the TalentSignal W3C community group (see [mail list](https://www.w3.org/community/talent-signal/wiki/Issues,_use_cases_and_requirements) thread on TalentSignal properties relating to employer information) and summaries / proposals on wiki: [Job contact details](https://www.w3.org/community/talent-signal/wiki/Contact_details_for_a_JobPosting), [Employer Overview](https://www.w3.org/community/talent-signal/wiki/Employer_Overview), and [idustry code](https://www.w3.org/community/talent-signal/wiki/Industry_a_standard_code).

**Comment by vholland** [comment]
For the contact details, can we reuse https://schema.org/contactType? Something like:

```
{
  "@context": "http://schema.org/",
  "@type": "JobPosting",
  "hiringOrganization": {
    "@type": "Organization",
    "contactPoint": {
      "@type": "ContactPoint",
      "contactType": "job applications",
      "email": "jobs@acme.com"
    }
  }
}
```

**Comment by philbarker** [comment]
@vholland that's roughly [what we came up with](https://www.w3.org/community/talent-signal/wiki/Contact_details_for_a_JobPosting) but not attached to hiringOrganization as the same hiringOrg might want different contacts for different job postings. So:
```
{
  "@context": "http://schema.org/",
  "@type": "JobPosting",
  "title": "Systems Research Engineer",
  "applicationContact": {
    "@type": "ContactPoint",
    "email": "info@example.com"
  }
}
```

**Comment by vholland** [comment]
That makes sense.

**Comment by sneha-antony** [comment]
Is it possible to pass multiple emails for a posting?

**Comment by Geraint** [comment]
> Is it possible to pass multiple emails for a posting?

This is passing in Google's rich results testing tool:

```json
{
    "@context": "https://schema.org",
    "@type": "JobPosting",
    "applicationContact": [
        {
            "@type": "ContactPoint",
            "email": "foo@example.com"
        },
        {
            "@type": "ContactPoint",
            "email": "bar@example.com"
        }
    ]
}
```
