### ISSUE TITLE
datePosted is needlessly tied to jobs, broaden it to online listings

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2397]
/cc @vholland @mfhepp

**Comment by vholland** [comment]
SGTM

**Comment by mfhepp** [comment]
SGTM, too

**Comment by RichardWallis** [comment]
What other listing types are you going to add to its domainIncludes?

**Comment by danbri** [comment]
https://webschemas.org/docs/releases.html#g2397

**Comment by RichardWallis** [comment]
Implemented in commit 64afa4e
