### ISSUE TITLE
Schema.org should say something about repeating events

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#240]
http://schema.org/Event

Either a markup model, a blog/wiki post, ... anything!

Migrating this old issue in from https://www.w3.org/2011/webschema/track/issues/11

See also http://www.w3.org/wiki/WebSchemas/RepeatingEvents  "Even if the conclusion is "describe each event individually", this should be documented."

**Comment by commadelimited** [comment]
This relates to my interests. I've been working through all Eventbrite's pages, adding Schema microformat data. Repeating events is a big thorn for us and I'd love to see what sort of solutions you can come up with.

**Comment by rvguha** [comment]
Hi Andy,

 Do you have a proposal for repeating events?

guha

**Comment by commadelimited** [comment]
@rvguha I have thoughts, but nothing concrete. It could be as simple as a master Event object, and a container for "repeatingEvents" similar to the way offers works. The master Event would have description, location, organizer, etc. while each child event would only have startDate and endDate (and perhaps a few other assorted properties).

But I feel that's such a simple approach that surely it's already been discussed and discarded?

**Comment by vholland** [comment]
I think in the past the discussion was derailed by examples with complicated event scheduling. For example, "every other Tuesday except when there are 5 Tuesdays in month and not in December" or some such.

It may be helpful to carve out the 90% of cases schema.org could handle and give guidance for more complicated use cases.

**Comment by rvguha** [comment]
Yes, lets go for the 90% case.

Something simple like what Andy suggests should go far.

Repeated events are sufficiently important that it might be ok to create
some special vocab for it, so that we don't have to create a new item for
each repitition

guha

**Comment by Dataliberate** [comment]
How about a simple repeats property on Event that takes an enumeration that takes with its inspiration from the bank standing order/instruction world - daily, week daily, weekend daily, weekly, 2 weekly, 4 weekly, monthly, 3 monthly, 6 monthly, annually?

In such a case the first event would be in the startDate, the repeats period being constrained by the endDate.

Im sure this would handle a large proportion of use cases.

~Richard

On 22 Apr 2015, at 17:50, rvguha <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, lets go for the 90% case.

Something simple like what Andy suggests should go far.

Repeated events are sufficiently important that it might be ok to create
some special vocab for it, so that we don't have to create a new item for
each repitition

guha

**Comment by rvguha** [comment]
Andy,

 What fraction of your use case will this cover?

guha

**Comment by danbri** [comment]
@commadelimited thanks for jumping in here. How do you deal with over-rides to repeating events that are specified by rule? e.g. do you have an approach to "except on bank holidays", "except on public holidays", "except on [particular set of dates]"? This is also something that crops up for us with http://schema.org/openingHours / http://schema.org/OpeningHoursSpecification ...

**Comment by commadelimited** [comment]
I think you might be complicating things. The Schema.org doesn't need to care about `every other Tuesday except when there are 5 Tuesdays in month and not in December`. It doesn't need to store that complex data sets, it only needs to know that an event has a start and end dates. Something like this is what I'm talking about. This is taken from real life, a game night that I host in Nashville...only the addresses have been changed to protect the innocent.

```
<div itemscope itemtype="http://schema.org/Event">
    <h1 itemprop="name">Monhtly Game Night</h1>
    <h2 itemprop="location">Andy's House - 1234 Main Street, Nashville, TN  37203</h2>
    <h3>6pm - 9pm</h3>
    <div itemprop="repeatedEvents">
        <div itemscope itemtype="http://schema.org/Event" itemprop="repeatedEvents">
            <p itemprop="startDate" content="2015-05-21 18:00:00">
                May 21
            </p>
            <meta itemprop="endDate" content="2015-05-21 21:00:00" />
        </div>
        <div itemscope itemtype="http://schema.org/Event" itemprop="repeatedEvents">
            <p itemprop="startDate" content="2015-06-18 18:00:00">
                June 18
            </p>
            <meta itemprop="endDate" content="2015-06-18 21:00:00" />
        </div>
    </div>
</div>
```

This event occurs on the 3rd Thursday of every month from 6 - 9pm. How we store this event in the Eventbrite DB is important to us, but it doesn't matter to Schema.org because it just needs to know an event is taking place at a specific date/time, and lasts for x amount of time. In this example the child events inherit name and location from the parent. Also real world, our game night will rotate to different locations. If that's the case then we allow props to be overridden like so:

```
<div itemscope itemtype="http://schema.org/Event">
    <h1 itemprop="name">Monhtly Game Night</h1>
    <h2 itemprop="location">Andy's House - 1234 Main Street, Nashville, TN  37203</h2>
    <h3>6pm - 9pm</h3>
    <div itemprop="repeatedEvents">
        <div itemscope itemtype="http://schema.org/Event" itemprop="repeatedEvents">
            <p itemprop="startDate" content="2015-05-21 18:00:00">
                May 21
            </p>
            <meta itemprop="endDate" content="2015-05-21 21:00:00" />
        </div>
        <div itemscope itemtype="http://schema.org/Event" itemprop="repeatedEvents">
            <p itemprop="startDate" content="2015-06-18 18:00:00">
                June 18
            </p>
            <meta itemprop="endDate" content="2015-06-18 21:00:00" />
        </div>
        <div itemscope itemtype="http://schema.org/Event" itemprop="repeatedEvents">
            <h2 itemprop="location">Bob's House - 867 Oaklawn Blvd #5309, Brentwood, TN  37287</h2>
            <p itemprop="startDate" content="2015-06-18 18:00:00">
                June 18
            </p>
            <meta itemprop="endDate" content="2015-06-18 21:00:00" />
        </div>
    </div>
</div>
```

Thoughts?

**Comment by commadelimited** [comment]
FWIW I just asked one of our PMs and we only have 2.2% of our live events as repeating events. So this isn't a big issue for us. But it would be nice to wrap up loose ends.

**Comment by mfhepp** [comment]
If we go for elements for repeating events, I suggest to go along the following -- sketchy -- route:

1. Lets define a type like RepeatingDateSpecification (which could become a supertype of OpeningHoursSpecification).

2. Expand the current model for repetition from OpeningHoursSpecification, which is based on weekly schedules, to a more generic yet simple one, e.g. two properties

    repetitionInterval = {hour, day, week, month, year) - we can use UNCEFACT codes for that
Indicates the interval in which the date repeats.

     repetitionIncrement = Number
Indicates the increments in the repetition (1 = every {hour, day, week, month, year), 2 = every other, ...)

3. Include RepeatingDateSpecification in the doamin of all relevant properties from OpeningHoursSpecification.

4. Either expand the range of startDate to include RepeatingDateSpecification or define a new property eventDates or availableDates with a domain of Event and a range of RepeatingDateSpecification.

With this simple mechanism, you should already cover a whole lot

- "Every Thursday" 
    dayOfWeek gr:Thursday
    repetitionInterval = "WEE" (for week)
    repetitionIncrement = 1 (for every week)

Exceptions can be handled by constraining the validity with validFrom and validThrough.

5. Lists of dates that do not follow a known pattern could be handled by allowing ItemList as a range for startDate or eventDates / availableDates .

That should do the trick. I could draft a pull request for Q2 if you agree to go that route.

We should note that any such rules-based mechanisms make the consumption of data more complicated for clients, but I think that in this case, it could be a sweet spot.

Even in RDF/SPARQL worlds, one could try to expand this compact form the its materialized form (finite list of dates).

Martin

**Comment by mfhepp** [comment]
As for exceptions that @danbri mentions above (also in OpeningHoursSpecification): There are at least two routes for handling those:

a) Using non-overlapping validity intervals for the OpeningHoursSpecification/RepeatingDateSpecification. You simply specify the opening hours / event dates until the week before Christmas, for the week of Christmas, and for the time after Christmas with the respective days of week (and times, in the case of opening hours).

b) include a negation mechanism, e.g. with a property like "excluding" or "exception" with a range of Date OR RepeatingDateSpecification OR ItemList

b) can get pretty complicated to process in a deterministic way, but might still be a useful way to get such information from Web sites. 

If we follow option b), we should indicate that Date should not use the advanced features of ISO 8601 and instead just use simple dates strings.

**Comment by mfhepp** [comment]
Alternative approach: We could try to use http://www.kanzaki.com/docs/ical/rrule.html for recurring dates. But I think the approach mentioned above is more appealing to users.

We should check that what we agree upon covers all that http://www.kanzaki.com/docs/ical/rrule.html mentions, though.

**Comment by wikier** [comment]
My two cents from PR #446: I think it's better to materialize descriptions of each event rather than base the model on using the [recurrence rule](http://www.kanzaki.com/docs/ical/rrule.html).

**Comment by mfhepp** [comment]
In general, I agree and have always recommended materializing facts than encoding rules in Web vocabularies. See for my full argument at
    http://ebusiness-unibw.org/pipermail/goodrelations/2011-May/000355.html

Now, however,  as @rvguha has stressed (and I agree), we are facing challenges in schema.org where Web developers will need mechanisms for exposing some kind of recurrence rules. Events and opening hours specifications are two prime examples.

**Comment by thadguidry** [comment]
@mfhepp I like your sketchy route and agree we need a RepeatingDateSpecification.  Please go forward with working towards a draft of this for Q2.  We can make refinements off of your draft later.  Main thing is getting a draft together with some basic examples, including one using negation mechanism.

**Comment by vanthome** [comment]
Just a hint, it it possible to specify Repeating intervals with ISO 8601 formatted strings. They are probably not as powerful as what ical offers but I think sufficient for simple recurring events. 

http://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals

**Comment by frankieroberto** [comment]
The problem with recurrence rules is that no-one ever thinks to put an end-date on them (even if only a tentative one that can be extended later), so you end up with meetings/events with rules like "10-11am every Tuesday" and then look at your calendar a few years into the future and see it full of events that will almost certainly never happen.

So I agree with "materialising the facts" rather than trying to encode recurrence rules, at least for events (OpeningHours feel more usable/scannable as rules).

**Comment by akuckartz** [comment]
Make it possible to formalize 90% of the real world rules and allow additional dates and exceptions.

(But even that would make it difficult to express: "will take place when the weather is fine".)

**Comment by rvguha** [comment]
The usual hack in schema.org for that is to have a different attribute/slot
that holds some enumerated list of common constraints --- InSummer,
ForOneYear, ...

guha

**Comment by rtroncy** [comment]
I have the feeling that everybody wants to have a new ```EventSeries``` type (we desperately wait for it in the [3cixty](https://www.3cixty.com/) project). The hard question is do we want to resolve at the same time the description o the ```openingHours``` of businesses or can we assume that in average, the repetitiveness of events in ```EventSeries``` are much simpler to express?

**Comment by wikier** [comment]
:+1:

Initial proposal of a subclass in PR #447.

I'm more of the opinion that `openingHours` should be bound to each concrete instance of the series, but whatever than unlocks this feature would be a good step forward.

**Comment by danbri** [comment]
Let's move this along. Can folk here please take a look at the Courses discussion, which has run directly into this topic: https://www.w3.org/community/schema-course-extend/wiki/Main_Page https://lists.w3.org/Archives/Public/public-schema-course-extend/2016Mar/0021.html

**Comment by ldodds** [comment]
Just to chime in here with another example. I'm currently looking at how to describe recurring events that relate to activities, e.g. a weekly gym or yoga session. 

While I agree that having materialized data where possible, it's useful to be able to also share events with a recurring start/end time.

The approach that's been used so far is to encode an ical recurrence rule. See [the `schedule` property in this example](https://github.com/openactive/activation/issues/6).

**Comment by rvguha** [comment]
I really like this 'schedule' approach. And we really do need to get the
vocab for recurring events.

Leigh, could you write this up as a proposal? Would be great to get this
into the next release

guha

**Comment by ldodds** [comment]
@rvguha sorry for slow response, yes I'll work up a proposal for this and submit it for review.

**Comment by rvguha** [comment]
Thanks. Look forward to it

guha

**Comment by danbri** [comment]
ideally the schedule structure will be neutral wrt what is happening on that schedule.

**Comment by magicomartinez** [comment]
Thoughts on #1457 ?

**Comment by rvguha** [comment]
This looks reasonable. Can we include this in the next release?

guha

**Comment by thadguidry** [comment]
Slow and steady progress, but we have http://schema.org/repeatFrequency now. Nice.
