### ISSUE TITLE
Introduce "authorAvatarUrl" property for "author"

### ISSUE THREAD

**Issue by fracca** [schemaorg/schemaorg#2406]
I was looking for a way to define the Avatar URL for the Author of a blog.  I would then be able to extract the URL for the Authors Avatar.

**Comment by RichardWallis** [comment]
I would presume that the author would be a **Person** , in which case the avatar would be a property of the Person description.   Would not the Person image property suffice for this purpose?

**Comment by fracca** [comment]
It was my understanding that a **Person** inherited the image property from a **Thing** and a **Blog** also inherits the same property. But in this context I would have thought the Image property was specific to the **Thing/CreativeWork** and not who created the **Thing/CreativeWork**.
In fact the **Authors Avatar** property I am proposing would be more relevant to a **CreativeWork**

**Comment by RichardWallis** [comment]
All Types inherit the _image_ property by being in a subtype relationship with _Thing_.

So a CreativeWork can have an image and so can the Person that created the CreativeWork.

Thus:
```    {
    "@context": "http://schema.org",
    "@type": "Blog",
    "name": "The Blog",
    "image": "http://example.com/blog/brand.jpg",
    "author": {
            "@type": "Person",
            "name": "A. N. Other-Writer",
            "image": "http://example.com/avitars/ano-w.jpg"
        }
    }
```

**Comment by RichardWallis** [comment]
Answered
