### ISSUE TITLE
EducationalOccupationalProgram: Google Testing Tool complains about missing mandatory fields

### ISSUE THREAD

**Issue by mynameisnotbruce** [schemaorg/schemaorg#2409]
Hi everyone,

please be kind to a Schema beginner here. I was very happy to see that there's now a definition for `EducationalOccupationalProgram`. However, playing around with it, I encountered errors in the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool).

More specifically, the tool will complain that the snippet is not valid if certain fields are missing, when I (as a developer and/or user) would consider them optional in the scope of a given context.

For example, all of these yield errors if missing, but should probably be optional:

- `timeToComplete`
- `provider` `address` and `contactPoint`
- `identifier`
- `offers`
- `identifier`

Now I have no idea whether this is an issue in the official definition, or on Google's end, but I think it could cause problems if a set of structured data is considered erroneous and invalid, rather than acceptably incomplete. So I hope this observation is of some value.

**Comment by RichardWallis** [comment]
Hi,

What you seeing is the difference between the Schema.org vocabulary, in which currently all properties are optional; and the testing tool for an individual data consumer helping you identify what data format will operate best in within the services they offer.

Also note in the particular tool you reference the difference between warnings and errors.  

If you wish to question their logic behind their choices, their forums are the best place to try.

**Comment by mynameisnotbruce** [comment]
Thank you!

Just a follow-up: Where can I see in the official definition whether a property is meant to be optional? (I didn't see notes on http://schema.org/EducationalOccupationalProgram)

"Also note in the particular tool you reference the difference between warnings and errors." - Indeed, and all of those were listed as errors if missing, not warnings. I'll follow your suggestion and take it to their forums then.

**Comment by RichardWallis** [comment]
All properties for each type are currently optional, there are no cardinality constraints in the vocabulary definition.

**Comment by mynameisnotbruce** [comment]
OK, thank you. Just for anyone else finding this in the future, apparently Google is making all of those fields mandatory on purpose for their own specific feature: https://developers.google.com/search/docs/data-types/job-training
