### ISSUE TITLE
Investigate status of CORS

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2412]
@RichardWallis can you investigate status of our CORS implementation?

I'm hearing we have issues:

`Did you know schema.org does not support OPTIONS method in HTTP and do not CORS?
You can’t read an ontology term from a script. Supporting CORS on GET isn't a thing as CORS requires the browser to send a OPTIONS first`

**Comment by danbri** [comment]
hmm I guess this should be in the other repo, sorry!

**Comment by RichardWallis** [comment]
Addressed in  [sdopythonapp issue 6](https://github.com/schemaorg/sdopythonapp/issues/6)

Ready for test when a new version is uploaded to webschemas.org.

@danbri  When it is, can you ask who you heard it from to try it out.

**Comment by danbri** [comment]
Ok, how does it look now?

**Comment by RichardWallis** [comment]
```curl -i -L  -X OPTIONS http://webschemas.org```

Returns what looks to be the correct output:
```
HTTP/2 204 
content-type: text/html; charset=utf-8
cache-control: no-cache
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD, OPTIONS
....
```

Also if request includes an ```Origin``` header its value is used in the ```Access-Control-Allow-Origin``` response:
``` curl -i -L -H "Origin: http://example.com"  -X GET http://webschemas.org```

Returns
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://example.com
Content-Type: text/html
...
```

**Comment by RubenVerborgh** [comment]
`curl -i -L -X OPTIONS http://webschemas.org` is missing
```
Access-Control-Allow-Headers: Accept, Accept-Language
```
or, at the very least just `Accept`.

The reason for this is that, even though `Accept` is safelisted (https://fetch.spec.whatwg.org/#no-cors-safelisted-request-header-name), it loses that status if its value contains more than 128 characters (https://fetch.spec.whatwg.org/#cors-safelisted-request-header). And 128 is not a lot for RDF-based clients if they start including all RDF variants in `Accept`. (Full discussion in https://github.com/whatwg/fetch/issues/862)

**Comment by RichardWallis** [comment]
Fixes applied in sdopythonapp ( https://github.com/schemaorg/sdopythonapp/issues/6#issuecomment-579829695 )
Will ship with next schemaorg release (v7.0)

**Comment by RichardWallis** [comment]
Apart from one outstanding issue [comment](https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-652349679) All concerns addressed so closing.
