### ISSUE TITLE
Add hasCourse property to courseInstance

### ISSUE THREAD

**Issue by thill-odi** [schemaorg/schemaorg#2416]
At the moment pointers between Courses and CourseInstances are unidirectional: Course has a hasCourseInstance property, but there is no inverse to point from CourseInstances to their parent Course objects. This is extremely useful, however, in cases where Courses and CourseInstances are, for example, published in separate data feeds or on separate webpages, and simplifies the work for consumers of such data.

**Comment by RichardWallis** [comment]
There is a fine line between having useful reverse properties for common relationships between types, and overwhelming the vocabulary with reverse properties for everything.

Others may agree that a new instanceOfCourse property for CourseInstances is a good idea. I personally think that the use cases for it are a bit limited.

In which case you will obviously question how you achieve what you describe. Fortunately JSON-LD (and RDFa) comes to the rescue with the ability to describe reverse relationships:

{
  "@context": "http://schema.org",
  "type": "CourseInstance",
  "name": "Structured Data 101 - January Workshop",
  "@reverse": {
    "hasCourseInstance": {
        "type": "Course",
        "name": "Structured Data 101 "
    }
  }
}
~Richard.

**Comment by philbarker** [comment]
@thill-odi hello, do you have examples of Course and CourseInstance data being published separately? 

I had thought that much of the information that you would want to provide for an instance could only be provided as properties of the Course, and so data for Course and CourseInstance would have to published together, or reconciled after gathering; in that latter case I didn't think it would matter much whether the link went from the Course to the CourseInstance or vice versa. So the expectation was either nesting one way or the other (with `@reverse` for the other as @RichardWallis shows) or publishing as separate objects and CourseInstances having `@id`s that hasCourseInstance could reference.  

Let us know if that doesn't work for you.

**Comment by nickevansuk** [comment]
Just updating on this issue for those in the future who may come across this:

In our use case Course is embedded in CourseInstance in data feeds, so they are published together, just represented the other way around: hence the need for something like `instanceOfCourse`.
