### ISSUE TITLE
Add logo property to Course

### ISSUE THREAD

**Issue by thill-odi** [schemaorg/schemaorg#2417]
In some domains - e.g. the physical activity and personal development sectors - individual courses may be heavily branded. For this reason, the 'logo' property should be made available on Courses, allowing providing organizations to associate branding with their offerings.

**Comment by njall** [comment]
Is this not covered by the _image_ property?

**Comment by EricAxel** [comment]
If I understand the usage being referred to here, the sponsor relationship (https://schema.org/sponsor) might be the right fit. If the course is a CreativeWork, it can have a sponsor (Organization or person).

Would that work?

--Eric

Eric Axel Franzon
