### ISSUE TITLE
Add property for the types of financial aid available for an EducationalOccupationalProgram

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2418]
I propose we add a property ```financialAidEligible``` to ```EducationalOccupationalProgram``` to allow authors to list the types of aid students may use when attending. The value would be the name of the program as text.

I looked at many pages and the list of types of aid is somewhat dizzying, even when restricted to USA-based institutions, so I don't think it is practical to have an enumerated list.

**Comment by stuartasutton** [comment]
Vicki, could the range be both Text and DefinedTerm. You are right that there are lots of programs in the U.S. for financial assistance, some generally applicable nation-wide and some by states. It's unlikely that there will be ever be a single enumeration; but there are some lists emerging; e.g.,  https://credreg.net/ctdl/terms#FinancialAssistance.

**Comment by vholland** [comment]
Yes, DefinedTerm makes sense. I was trying to avoid trying to define terms in schema.org, but we should use external lists.

**Comment by vholland** [comment]
Implemented in PR #2425 including the use of DefinedTerm.

**Comment by danbri** [comment]
PR merged. Edited  data/ext/pending/issue-2418.rdfa  to add "isPartOf pending" markup.

**Comment by vholland** [comment]
Included in schema.org 6.0
