### ISSUE TITLE
Add regionsIntended to MediaObject

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2422]
Authors can currently use ```regionsAllowed``` to specify where a ```MediaObject``` can be viewed. It would be nice to have a way to specify the target region for media. For example, a ```MediaObject``` may be available across the EU, but intended for people in Spain.

Adding ```regionsIntended``` as an analog to ```regionsAllowed``` would allow for this use case.

**Comment by philbarker** [comment]
How about using `audience`?

**Comment by vholland** [comment]
Of course! Thanks for the suggestion.
