### ISSUE TITLE
schema.org has NGO, EducationalOrganization, SportsTeam, GovernmentOrganization but not Labo[u]r Union

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#243]
http://schema.org/Organization

Migrated in from https://www.w3.org/2011/webschema/track/issues/17

```
    http://schema.org/Organization has various subtypes including Corporation etc, but doesn't cover Labo[u]r Union.

    Raised by Kendall Clark, https://twitter.com/kendall/status/210422142620286976

    The schema has the following subtypes currently: Corporation, EducationalOrganization, GovernmentOrganization, LocalBusiness, NGO, PerformingGroup, SportsTeam

    The British English variant of this concept is http://en.wikipedia.org/wiki/Trade_union

    Generally Schema.org uses US English, but if a more neutral term / spelling is available, that helps.
```

(there's a draft proposal around somewhere in RDFa/RDFS too)

**Comment by danbri** [comment]
Earlier proposal was:

        <h1>WorkersUnion</h1>

        <div typeof="rdfs:Class" resource="http://schema.org/WorkersUnion">
          <span class="h" property="rdfs:label">WorkersUnion</span>
          <span property="rdfs:comment">A Workers Union (also known as a Labor Union, Labour Union, orTrade Union) is an organization that promotes the interests of its worker members by collectively bargaining with management, organizing, and political lobbying.</span>
          <span>Subclass of: <a property="rdfs:subClassOf" href="http://schema.org/Organization">Organization</a></span>
          <span>Source:  <a property="dc:source" href="http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_WorkersUnionClass">WebSchemas community</a></span>
        </div>

From https://dvcs.w3.org/hg/webschema/raw-file/b4c3ad199322/schema.org/ext/workersunion.html

**Comment by danbri** [comment]
This is now available in the development version of the pending extension: 

  http://pending.webschemas.org/WorkersUnion

**Comment by RobRoseKnows** [comment]
Should the [NAICS](http://pending.schema.org/naics) attribute reflect the industry that the union represents or the NAICS of unions (813930)?

**Comment by danbri** [comment]
This is a small sensible change, nobody objected, we should just put it in the core. 

(and sorry for the late reply @RobRoseKnows - it should reflect the union's industry)
