### ISSUE TITLE
What if some jobs does't provide salary amount for job offers

### ISSUE THREAD

**Issue by josephmiller2000** [schemaorg/schemaorg#2430]
What if some company do not provide basic salary information for their job offers. This happens often with many job recruitment. They normal disclose the salary information once the particular person is hired for the job.  

In this case? what can i do? I have tried to add 0 in the min and max value. But this does not look good. 
"value": {
      "@type": "QuantitativeValue",
      "minValue": 0,
      "maxValue": 0,
      "unitText": "MONTH"
    }

I can't even remove those information from the schema, i end up with error ( warring ) value is missing.

Here is my full schema.

{
  "@context" : "https://schema.org/",
  "@type" : "JobPosting",
  "title" : "Chennai Port Trust Recruitment 2019 - Deputy Secretary Posts",
  "description" : "Chennai Port Trust Recruitment 2019 - Deputy Secretary Posts - Central Government Job | Job In Chennai | Last Date : 10.01.2020 | Total Vacancy : 01",
  "datePosted" : "2019-12-14",
  "validThrough" : "2020-01-10",
  "employmentType" : "FULL_TIME",
  "identifier": {
    "@type": "PropertyValue",
    "name":  "Chennai Port Trust",
    "value": ""
  },
  "hiringOrganization" : {
    "@type" : "Organization",
    "name" : "Chennai Port Trust",
    "sameAs" : "https://www.chennaiport.gov.in/",
    "logo" : "https://www.1govtjob.com/wp-content/uploads/2019/11/Chennai-Port-Trust-Recruitment-2019.jpg"
  },
  "jobLocation": {
  "@type": "Place",
    "address": {
    "@type": "PostalAddress",
    "streetAddress": "Rajaji Salai",
    "addressLocality": "Chennai",
    "addressRegion": "TN",
    "postalCode": "600001",
    "addressCountry": "IN"
    }
  },
  "baseSalary": {
    "@type": "MonetaryAmount",
    "currency": "INR",
    "value": {
      "@type": "QuantitativeValue",
      "minValue": -1,
      "maxValue": -1,
      "unitText": "MONTH"
    }
  }
}

**Comment by RichardWallis** [comment]
Note the warning message from the Structured Data Testing Tool, which I presume you are using:

> The baseSalary field is recommended. Please provide a value if available.

It is recommended, not mandated.  If you do not have a value for baseSalary, do not supply one.  Trying to supply false values such as 0 or -1 is nonsensical.

The warnings are a feature of a particular testing tool, testing how appropriate data is for consumption by their services.  The Schema.org vocabulary itself has no such constraints.

Therefore this is not the forum to ask questions as to how Google use your data, I suggest their product forums https://productforums.google.com/forum/#!categories/webmasters/structured-data and nearby.
