### ISSUE TITLE
PreOrder ItemAvailability wording needlessly excludes non-deliverable items 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2433]
Second half of "Indicates that the item is available for pre-order, but will be delivered when generally available." is not needed for concept of "pre-order" and excludes services, collectables, etc.

**Comment by danbri** [comment]
https://github.com/schemaorg/schemaorg/commit/00ab7d90bd80bc7298a09ee9b4c5523cfde7ec67

Noted in docs/releases.html

**Comment by SignpostMarv** [comment]
would it not be preferable to replace "delivered" with "fulfilled" ?

**Comment by RichardWallis** [comment]
Implemented in commit 00ab7d9
