### ISSUE TITLE
Add Vehicle to the domain of  amenityFeature

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#2434]
After reading up on issue #2373 I was wondering whether the domain of schema.org/amenityFeature could be expanded to schema.org/Vehicle?

Reason being that most motorhomes and towed trailers have a lot of the same amenities one would describe for an Accommodation.

Now of course, I could use a multi-typed entity for this (Vehicle, Accommodation) though to me this feels like stretching it a bit far (a Vehicle isn't a Place but travels to one after all), or would that be just fine?

**Comment by danbri** [comment]
Sounds like one of those places where theoretically the vocabulary might be applicable, but it might be prudent to wait until there's a consuming application interest in going to that level of detail. Adding expressivity has value of course, but it also comes with costs (complexity for people trying to understand the schemas, etc.).

**Comment by jvandriel** [comment]
I'll close this issue until there's an actual candidate consumer for this type of data.
