### ISSUE TITLE
Delete health-lifesci properties with misleadingly general names

### ISSUE THREAD

**Issue by tjann** [schemaorg/schemaorg#2435]
First step of a larger [health-lifesci](http://health-lifesci.schema.org/) cleanup cycle.

Intend to decrease confusion and incorrect usage of properties. Also frees these property names for future use.

Examples:
http://schema.org/action
http://schema.org/background
http://schema.org/cause
http://schema.org/cost
https://schema.org/function
https://schema.org/indication
https://schema.org/origin
https://schema.org/outcome
https://schema.org/overview
https://schema.org/phase
https://schema.org/population
https://schema.org/purpose
http://schema.org/source

**Comment by danbri** [comment]
Thanks for that list, @tjann. I agree - we have let these unused terms clutter schema.org for too long, and it is time to address their usability impact.

For some of these it may be worth finding alternative idioms that are more consistent with the non-medical core of schema.org (e.g. for drug cost).

**Comment by danbri** [comment]
Also include https://schema.org/subtype

**Comment by smrgeoinfo** [comment]
looks like https://schema.org/purpose is not health-lifesci specific (Domain is Thing....)

**Comment by christo26** [comment]
Concur that these items should put in the Schema.org health-lifesci "attic"/archive, as they are too generic.

**Comment by semantoya** [comment]
Hi Tiffany,
As a domain expert in medical diagnostics  I'm  frequently puzzled by the lack of expressiveness of the terms used in the health-lifesci vocabulary. However, this is also true for other vocabularies and ontologies. 
So, we are working on a highly expressive  IVD reference model that shall be unambiguously interpretable and trustworthy. This model is to be used in the daily practice of healthcare workers. The high granularity will hamper the general use in the public domain.

Instead, we are considering to the definitions of official governmental (IVDR, MDR)  and institutional documents as a framework for tagging general subjects.  

You can contact me if you are interested in this initiative.

Best Regards
Frans

**Comment by rvguha** [comment]
Given that they are not being used, let us just remove them. Given how
badly named they are, their presence, even if only in the attic, will lead
to confusion.

guha

**Comment by tjann** [comment]
Updated Issue name to reflect deletion instead of archive/attic

**Comment by danbri** [comment]
I agree re delete rather than archive, for these

In the case of Drug having a "cost" property, DrugCost, which in turn has
non-core properties like costCurrency, I think (should we decide the drug
info terms are keepers) we ought to modernize anyway and use more standard
core patterns

**Comment by tjann** [comment]
PR #2448

**Comment by tjann** [comment]
Thinking about leaving indication for now, as it's used in many examples/docs

**Comment by tjann** [comment]
I can also leave out "cause" for now, and include it in a PR where I add "cause" to core schema instead. Thoughts? The rest are not mentioned in the text examples under the health-lifesci folder nor https://schema.org/docs/meddocs.html

**Comment by rvguha** [comment]
I would rather we remove cause as well

**Comment by danbri** [comment]
/cause was the only one I was wavering on, although it too has an
unfortunate name.

 I think it over-reaches in scope but may have some value in mapping out
core patterns relating conditions, drugs, symptoms etc.

Having said that I still argue for delete. A better named (and more
flexible, eg /possibleMedicalCause) would be easy to add freshly to Pending
or core if the need arises.

FWIW my specific need would be related to making schema.org subsets of
Wikidata available. I haven't looked to see if a property like this would
be easy to populate from Wikidata. Genes, diseases and drugs can be
usefully exported eg see here for example that can populate a neo4j graph
database with these connections:
https://github.com/elixir-europe/BioHackathon-projects-2019/blob/master/projects/28/src/g2g/wikidata_disease_bioschema.g2g

so, let's delete /cause.

**Comment by danbri** [comment]
I've merged the PR from @tjann; these properties are now gone. From my comment there,

> I'll also add /subtype, and find some way of recording the names of deleted terms in the RDFS representation in case tools want to use that information to help people know when they're using outdated terms.

**Comment by RichardWallis** [comment]
Implemented in PR #2448

**Comment by Amousey** [comment]
cause was needed for https://schema.org/MedicalCondition - please restore - it doesn't make sense to have a MedicalCondition with a riskFactor but not a cause, medicalCause or possibleCause are alternate names that could be uses for clarity. The example on https://schema.org/MedicalCause is not working because of this.

**Comment by Amousey** [comment]
Just to clarify: this is for the core schema.

It is already on the page in the example of [https://schema.org/MedicalCondition](https://schema.org/MedicalCondition)  and as above was removed despite a degree of uncertainty, see #2878 for code example.

Currently MedicalCondition has a riskFactor but not a cause, which makes no sense. 

Alternate names would be acceptable to me eg `medicalCause` or `possibleCause`

Plain English example would be:
MedicalCondition Influenza
cause influenza A virus
cause influenza B virus
riskFactor diabetes
riskFactor asthma
epidemiology over 50s, healthcare workers

**Comment by chrisspradling1980** [comment]
Amen!
