### ISSUE TITLE
Addition of geo and OpeningHours to Organization

### ISSUE THREAD

**Issue by sinclr4** [schemaorg/schemaorg#2437]
Within the NHS in England, we publish directories of services which we make available on the site (www.nhs.uk) for citizens to search for. Some of these directories are not NHS organisation but are relevant to healh. An example of this is weight loss: https://www.nhs.uk/ServiceDirectories/Pages/GenericServiceDetails.aspx?id=10827535 

Within the JSON-LD I am looking to define this as an Organization as the mapping to the existing types is not always possible, but also want to put the geo information and OpeningHours into the data. Could this be considered please.

**Comment by RichardWallis** [comment]
I suggest you look to defining these as a [LocalBusiness](https://schema.org/LocalBusiness) or one of its [subtypes](https://schema.org/LocalBusiness#subtypes) which then gives you access to both location/address and openingHours information.
