### ISSUE TITLE
How can I add AggregateRating for type of article.

### ISSUE THREAD

**Issue by aminaghamiri** [schemaorg/schemaorg#2441]
Hi!
I wanna add AggregateRating for my posts and type of my datatype is article .
How Can I add rating to rich result.

**Comment by RichardWallis** [comment]
Check out the first example in the [AggregateRating](https://schema.org/AggregateRating#eg-10) documentation.  Although this example for the review of a Product, the principle is the same for an Article.

One or more Reviews described, then an AggregateRating describing the aggregate of the review ratings.

That is how to add to your structured data. It is obviously up to the consumers of your data as to if and how they then use it in any results.  Check out their documentation (eg.  https://developers.google.com/search/reference/overview - Structured Data) for more detail.
