### ISSUE TITLE
Pending implementation term references in Vocabulary Definition Files

### ISSUE THREAD

**Issue by davidglezz** [schemaorg/schemaorg#2442]
Some terms are not defined (because they are pending or for some other reason) but these terms are referenced by others.

Example:
https://schema.org/MoneyTransfer
Term not found in https://schema.org/version/latest/schema.ttl
but is referenced in:
`schema:amount schema:domainIncludes schema:MoneyTransfer ;`

All Vocabulary Definition Files involved.

Full list of referenced terms:
```
schema:MonetaryGrant not found
schema:MoneyTransfer not found
schema:PhysicalActivity not found
schema:ExchangeRateSpecification not found
schema:EducationalOccupationalProgram not found
schema:GeospatialGeometry not found
schema:DietarySupplement not found
schema:Drug not found
schema:WorkBasedProgram not found
schema:Chapter not found
schema:TouristDestination not found
schema:TouristTrip not found
schema:EducationalOccupationalCredential not found
schema:HealthInsurancePlan not found
schema:Audiobook not found
schema:LinkRole not found
schema:Grant not found
schema:MedicalStudy not found
```

Version 5.0
Not tested on 4.0
0 Problems on ~3.6

**Comment by RichardWallis** [comment]
The reason for this is that the definition files named schema.* only include the core vocabulary terms .  They do not therefore include terms defined in the pending, auto, bib, etc. areas.

For tests such as this, the _all-layers.*_ files (eg. https://schema.org/version/latest/all-layers.ttl) should be used.  These contain all terms.

Having moved away from emphasising the separation between such 'extension' areas.  It might make sense to reduce the number of different definition files and their contents, to a single file type.  That would be the equivalent to _all-layers.* probably renamed _schema.*__

**Comment by davidglezz** [comment]
If it is correct that there may be references to terms not included in the file, then I can close this issue.
