### ISSUE TITLE
Enumeration values - rationalisation definition and display

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2444]
Evaluation of PR #2250 which rationalised issues in the definition Enumeration Values, it was identified that the fix had wider ramifications and was therefore reversed in PR #2443.

In summary two sorts of  Enumeration Values (EVs) have emerged as Schema.org has evolved.

1.  A basic EV  (eg. [Male](https://schema.org/Male) or [Paperback](https://schema.org/Paperback))  - defined as being typeof a subtype of Enumeration (eg. [GenderType](https://schema.org/GenderType) or  [BookFormatType](https://schema.org/BookFormatType)).

2. A Type that is also an EV (eg. [PaymentCard](https://schema.org/PaymentCard) or [DrugClass](https://schema.org/DrugClass)).  In addition to being a member of the Enumeration type (eg. 
[PaymentMethod](https://schema.org/PaymentMethod) or [MedicalEnumeration](https://schema.org/MedicalEnumeration)) they also are a Type with the potential to be in the domainIncludes or rangeIncludes of specific properties.

The objective of this issue is to identify the various permutations that have evolved in this area; how EVs should be defined in the source RDFa files and resultant downloadable definition files; how they should be identified in the application code and displayed; and be the subject of tests to prevent future divergence.

**Comment by danbri** [comment]
@RichardWallis FYI - I've suggested to my colleague @lucy-kind that she takes a look at the enums situation. We have been chatting about ways of modeling per-country enumerations (e.g. for officially-inspired lists of kinds of non-profit, or government social benefit schemes). I think subtyping ought to work, e.g.  subclassing like Thing > Intangible > Enumeration > Benefits > UKBenefits, but we'll need to document any assumptions being made at the website level.

**Comment by RichardWallis** [comment]
Per country/sector enumerations sounds like a potentially useful idea.

We should however rationalise the differing ways enumerations have been implemented over time before laying too much on top of them.

I believe your subclassing suggestion will fit well with the type 1. I described above.

@lucy-kind  Drop me a line and I'll take you through what went before.

**Comment by RichardWallis** [comment]
Pull #2614 closes this issue in its current form.
There may well be opportunity for further rationalisation in the future.
