### ISSUE TITLE
Why mention 'appengine' in the GitHub description? It may not give the right impression to some viewers. [feedback about discoverability/ SEO]

### ISSUE THREAD

**Issue by hangtwenty** [schemaorg/schemaorg#2451]
Seeing 'appengine' in the description made me wonder... _Has this project become vendor-specific to Google somehow?_ 

I realized pretty quickly that it was just saying that this repo is specifically for the spec itself, and the app that gets deployed, and GAE/appengine is used for hosting.

Maybe this was a silly thought, but I wanted to post while it was still fresh in mind. Maybe some passers-by will not look closer. Maybe they'd even close the tab pretty quick, yet keep a memory that schema.org was some vendor thing. I personally don't mind vendor-specific things as much as some of my colleagues have, but nonetheless... even just looking at it literally, it's confusing to have `(appengine)` mentioned right at the top.

If you'd like a suggestion on what to change it to:

> Schema.org - this repo contains the schemas, and the web app running at http://schema.org/

**Comment by hangtwenty** [comment]
I also want to clarify:

* I'm aware that this project was founded by Google and others (Google, Microsoft, Yahoo and Yandex" per the homepage), I just don't think that's relevant in the short GitHub description.
* It shouldn't matter, but I'm a very satisfied user of Google Cloud... Just emphasizing it's not about _which_ brand, just that on a high level it's not really about any specific brand or vendor.

**Comment by danbri** [comment]
Our project practicalities involve managing schemas (a bunch of neutral definition files) and running an actual site (which happens currently to use python, Google appengine), and be hosted on Microsoft's excellent Github platform. If people are discouraged by this, that is a pity, but we don't have the resources within the project to build our own collaborative versioned filesystem sharing machinery or issue tracker, or cloud hosting system.

**Comment by hangtwenty** [comment]
It seem like my point was missed. I'm sorry if I wasn't clear. It's not about using the tools or not. 

It's about appealing to a wider audience with basically no additional effort. 

There is no apparent benefit to mentioning appengine in the project description. I would think it takes more effort to send that response than to just delete '(appenegine)' from the description.
