### ISSUE TITLE
Add a property to accompany /license that explains how to acquire licenses etc.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2454]
We have had a property /license for some years ("A license document that applies to this content, typically indicated by URL."). Sometimes publishers have mistaken this for a property that points to a page for getting (e.g. buying) a license.

This proposal is to add a term to address this need. Calling it /usageInfo rather than something more specific, to allow us to address related usecases.

Definition: 

```
Thing > CreativeWork 
Property:  https://schema.org/usageInfo
Values: CreativeWork, URL
```

> The schema.org "usageInfo" property indicates further information about a creative work. This property is applicable both to works that are freely available and to those that require payment or other transactions. It can reference additional information e.g. community expectations on preferred linking and citation conventions, as well as purchasing details. For something that can be commercially licensed, usageInfo can provide detailed, resource-specific information about licensing options. 

> This property can be used alongside the license property which indicates license(s) applicable to some piece of content. The usageInfo property can provide information about other licensing options, e.g. acquiring commercial usage rights for an image that is also available under non-commercial creative commons licenses.

**Comment by philbarker** [comment]
That name might lead to confusion. To me it sounds more like information on how something is used (e.g. "used by 40% of sites on the web"). `licenseCondition` or `licenseExpectation` might be better.

The phrase "further information about a creative work" in the explanation is very ambiguous; better make it "further information about licensing a creative work"

Maybe think about wrapping this into Offer rather than CreativeWork. 

`offerCondition` : "further information on requirements and expectations regarding the an offer to transfer some rights to an item or to provide a service"

**Comment by danbri** [comment]
Thanks @philbarker. Considering this comment and talking with others, including colleagues from Google who are expecting to build around this, I agree that the initial property is a bit too loose. This was on my advice as, while info about license acquisition was a big motivator here, there are other usecases we might cover too. I have just added an additional more explicit property into the Pending draft called /acquireLicensePage which has /usageInfo as a superproperty. I would rather not involve offer in detail at this stage, but the page we point to obviously has potential for being host to that sort of thing (and more).

**Comment by nicolastorzec** [comment]
I also find the phrase "indicates further information about a creative work` ambiguous". I'd use a more specific explanation, such as "indicates further information about the rights and obligations associated with (the usage of) a creative work".

**Comment by WeaverStever** [comment]
Perhaps we should look at an inverse to this property for "free to use" content on a website?  

I downloaded a social media icon yesterday, but the Creative Commons - Share Alike citation terms required that the host to be linked in the footer of the website. Of course, I went elsewhere and found a truly free icon.

A licensesAquired property could be useful for these Creative Commons citations, purchased or leased artwork and music licensing for video background music and cover songs.

**Comment by RichardWallis** [comment]
Implemented in commits b866e1f & fde3730

**Comment by Abhishek5772705** [comment]
<div vocab="https://schema.org/" typeof="WebSite">
    <link property="url" href="http://www.example.com/"/>
    <form property="potentialAction" typeof="https://schema.org/SearchAction">
      <meta property="target" content="http://www.example.com/search?q={query}"/>
      <input property="query" type="text" name="query">
      <input type="submit">
    </form>
</div>

**Comment by Abhishek5772705** [comment]
I love universe
