### ISSUE TITLE
New properties for EducationalOccupationalProgam

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2460]
As the use of EducationalOccupationalProgram expands, we are seeing authors having trouble distinguishing between EducationalOccupationalProgram and WorkBasedProgram. In some countries, there is little to no distinction.

As part of this, we would like to modify EducationalOccupationalProgram to be a true superclass of WorkBasedProgram. As part of this, I propose:

- Changing the domains of occupationalCategory and trainingSalary to include EducationalOccupationalProgram.
- Add a new property ```programType``` for describing the type of program. This property would have a range of ```Text``` or ```DefinedTerm``` and would allow for some flexibility in specifying the type of program as understood in the country/region where it is defined.

**Comment by vholland** [comment]
Added PR #2461 which might help clarify.

**Comment by philbarker** [comment]
Is there now any difference between EducationalOccupationalProgram and WorkBasedProgram (apart from the definition)?  Are both needed?

**Comment by vholland** [comment]
From what we are seeing in the ecosystem, we may want to eventually deprecate WorkBasedProgram as most programs don't cleanly fall into education vs work.

**Comment by siuc-nate** [comment]
Do you have a reasonably thorough example list of values for this property? Does it align to anything that already exists in CEDS or some similar vocabulary?

Failing that, is it intended to provide the means by which the program is delivered (e.g. online, in person, etc.) or the methods used by the program (e.g. lecture, lab work, hands-on activities, etc.), or something else?

I'd like to see how well it aligns with some of the terms we use in CTDL.  The schema.org definition gives three examples, but that's not quite enough for me to tell.

**Comment by RichardWallis** [comment]
Main issue was addressed in commit 31c974a
Now closing
