### ISSUE TITLE
schemaorg.owl Not Found

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#2472]
https://schema.org/docs/developers.html > Experimental/Unsupported > OWL has a broken link:
https://schema.org/docs/schemaorg.owl : 404 Not Found

It gives a number of warnings, including:
- schema:domainIncludes and schema:rangeIncludes values are converted into rdfs:domain and rdfs:range values using owl:unionOf to capture the multiplicity of values. Included in the range values are the, implicit within the vocabulary, default values of Text, URL, and Role.
- As an experimental feature, there are no expectations as to its interpretation by any third party tools.

If this rendition is deprecated, remove the link and text in section "OWL".
Otherwise, please restore the file schemaorg.owl.

cc @holgerknublauch @Dataliberate

**Comment by RichardWallis** [comment]
Not sure why this link is broken - it is not broken on the webschemas.org test site. (https://webschemas.org/docs/schemaorg.owl)

Needs investigating as to how it could have been dropped on the production site.

**Comment by danbri** [comment]
Yeah I thought something was up with this file, some confusion on whether it's generated with all the other derived artifacts or not maybe?

**Comment by RichardWallis** [comment]
It 'should' be  generated with all the other derived artefacts.

The suspicion is that somehow that did not happen when the post v6.0 patch was applied.

**Comment by VladimirAlexiev** [comment]
https://webschemas.org/docs/schemaorg.owl also returns 404 Not Found.

**Comment by RichardWallis** [comment]
Needs investigating to get fix into V7.0 - will expedite

**Comment by RichardWallis** [comment]
Fixed in PR#2478
