### ISSUE TITLE
Issue with nokogiri (< 1.10.8) gem causing security alert

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2475]
[Alert](https://github.com/schemaorg/schemaorg/network/alert/scripts/Gemfile.lock/nokogiri/open) flagging security problem with nokogiri gem < 1.10.8

cc. @gkellogg can you handle this for us.

**Comment by gkellogg** [comment]
Will do.

**Comment by RichardWallis** [comment]
Fix in PR #2476
