### ISSUE TITLE
schema.jsonld doesn't use the sdo JSONLD context

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#2477]
http://schema.org/version/latest/schema.jsonld uses a very poor context:
```json
  "@context": {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
```
It doesn't use sdo's own context: https://schema.org/docs/jsonldcontext.json.
Therefore it uses full URLs everywhere, and unwieldy `@id` keys.

(My problem is that therefore I can't easily convert it to GraphQL because I don't have usable short names for classes and props.
http://schema.org/version/latest/schema.ttl doesn't have this problem.)

**Comment by RichardWallis** [comment]
The reason for this is that including sdo's own context resulted in some 'circular' errors for JSON-LD processors.  (If I remember correctly - it was a while back when this was last visited)

Will revisit the issue to clarify and see if there might be a way forward.

**Comment by VladimirAlexiev** [comment]
Can you just include all the namespaces used by schema.jsonld?

**Comment by danbri** [comment]
@RichardWallis I remember the circularity and version confusion being an issue when we discussed using JSON-LD as the on-disk representation in the definition files. Is it also a problem here? /cc @gkellogg

**Comment by RichardWallis** [comment]
@danbri I need to do a little experimentation here to identify what, if any, is still the problem in including the schema.org context in this output.

Any thoughts from @gkellogg would be helpful.

**Comment by akuckartz** [comment]
@github-actions Why did you close this issue?!

**Comment by VladimirAlexiev** [comment]
Disturbing !
Cc @danbri @RichardWallis
