### ISSUE TITLE
Relationship between Courses and EducationalOccupationalPrograms

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#2483]
A [EducationalOccupationalProgram](https://schema.org/EducationalOccupationalProgram) is defined as something that "would define a discrete set of opportunities (e.g., job, courses) that together constitute a program"

Credential Engine would like to provide information on Programs that lead to qualifications/educational occupational credentials, including information about a Program's constuent [Courses](https://schema.org/Course).

A simple approach would be to extend the domain of hasPart to  EducationalOccupationalPrograms.  Perhaps a more thorough approach would be distinguish between optionalCourses and requiredCourses, as in HE at least there is often a core set of courses that must be taken, and a variety of options to either offer a broader base or more specialized finish to a Program.

Any thoughts?  @vholland ?

**Comment by vholland** [comment]
If hasPart satisfies Credential Engine's use case, I think we should go with that and tackle more complicated use cases as they arise.

Every conversation I have had about modeling required vs optional courses has become overly complicated as every university (let alone different university systems or countries) seems to have a different way to track this.

**Comment by WeaverStever** [comment]
Some example broad Types for programCredentials that might suit this purpose

- Enrichment
- Certificate
- Licensure
- AssociateDegree
- AssociateDegreeForTransfer
- BachelorDegree
- MastersDegree
- PhDDegree
- ProfessionalDegree

Then the constituent courses could be added to each of the relevant Types under an external ontology such as the CIP or other.
https://nces.ed.gov/ipeds/cipcode/Default.aspx?y=56

**Comment by siuc-nate** [comment]
After a brief discussion with @philbarker on this today, it seems like a "hasCourse" property would be more appropriate, as:
- It would avoid any complications with hasPart (either now or down the road)
- It keeps the scope and usage of the property tight
- It harmonizes with the existing "hasCourseInstance" property (e.g. EducationalOccupationalProgram.hasCourse > Course.hasCourseInstance > CourseInstance)

**Comment by philbarker** [comment]
PR #2559 adds hasCourse property with caveats about not implying it is mandatory, or even that it is availble to all 
`hasCourse: A course or class that is one of the learning opportunities that constitute an educational/occupational program. No information is implied about whether the course is mandatory or optional; no guarantee is implied about whether the course will be available to everyone on the program.` 
@WeaverStever not sure how your suggestions relate to what we intend; I think they are covered by [`educationalCredentialAwarded`](https://schema.org/educationalCredentialAwarded) with various values of credentialCategory on [EOCred](https://schema.org/EducationalOccupationalCredential) referred to. Apologies for any misunderstanding.

**Comment by philbarker** [comment]
@danbri I'm happy to redraft PR #2559 in turtle if there was no other reason for not accepting it than attention being elsewhere.

**Comment by philbarker** [comment]
@danbri I think the bot closed this prematurely as there was a solution submitted but not committed. PR #2679 is the same solution now in ttl.
