### ISSUE TITLE
Role documentation

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#2489]
on the page https://schema.org/Role one example uses this structure

```
<script type="application/ld+json">
  {
    "@context": "http://schema.org/",
    "@type": "Person",
    "name": "Albert Einstein",
    "hasOccupation":
    {
      "@type": "Role",
      "hasOccupation": {
        "@type": "Occupation",
        "name": "Patent examiner",
        "occupationalCategory": "23-2099.00"
      }
    }
  }
</script>

```
But the property `hasOccupation` is not defined for `@Role` .
Should the page be updated to feature the property `hasOccupation` ?

**Comment by RichardWallis** [comment]
[Role](https://schema.org/Role) is a Type which within Schema.org has special characteristics which enables it to have as a property the property is provided as a value for.

Check out these blog posts for a more detailed description is use and use-cases:

- [Introducing Role](http://blog.schema.org/2014/06/introducing-role.html)
- [The role of Role in Schema.org](https://www.dataliberate.com/2015/04/15/the-role-of-role-in-schema-org/)

**Comment by jaygray0919** [comment]
Good to know, but would not have known without your note.
