### ISSUE TITLE
contentLocation is ambiguous

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#249]
http://schema.org/contentLocation

"Discussing how to represent where a Movie was filmed, e.g. productionCountry. Discussing CreativeWork's existing contentLocation property, it is clear the text is ambiguous. 

http://schema.org/contentLocation "The location of the content." (Place) 

Is this where a book is currently located? In real life? Or about-ness, e.g. Pirates of the Caribbean is about the Caribbean?"

**Comment by vholland** [comment]
A discussion of this issue is over at Issue #323. I'll close this issue to avoid confusion.
