### ISSUE TITLE
Missing Schema.org/MedicalBusiness annotations

### ISSUE THREAD

**Issue by thomasdegroot18** [schemaorg/schemaorg#2491]
### Missing Schema.org/MedicalBusiness annotations.

When visualizing the schema.org hierarchy in our visualizer I noticed that the class http://schema.org/Medicalbusiness was missing a subClassOf relation to the http://schema.org/LocalBusiness, as well as the other annotations belonging to a Class. 

Should this be added to the schema?

**Comment by davefeg** [comment]
Please make sure about CAPS... this ``http://schema.org/Medicalbusiness ```cannot resolve.
But this one ``http://schema.org/MedicalBusiness``  can :).

**Comment by thomasdegroot18** [comment]
Thanks, I for the missing typo Closing it.
