### ISSUE TITLE
Schema Property "gender" is missing in schema-properties.csv

### ISSUE THREAD

**Issue by satyam-bala** [schemaorg/schemaorg#2499]
Property "gender" is missing in schema-properties.csv, but there are schema types Person, SportsTeam, which are using this attribute.

**Comment by RichardWallis** [comment]
Not obvious why this is the case - needs investigating.

As a workaround, it is available in ```all-layers-properties.csv```

**Comment by RichardWallis** [comment]
Reason it is not in ```schema-properties.csv``` is that the definition has been updated in a pending issue (#2341) it has therefore been identified as part of the pending section.   As per the workaround it is available in ```all-layers-properties.csv```
