### ISSUE TITLE
EducationalOrganization -  subOrganization vs department

### ISSUE THREAD

**Issue by dakala** [schemaorg/schemaorg#2507]
I've got a problem with the schema for `EducationalOrganization` within the context of a university, college or tertiary institution.

For a multi-campus setup, the main location is the `EducationalOrganization` and each campus a `subOrganization`. No problem. The `parentOrganization` and `subOrganization` properties work well here.

However, it's the academic departments in a given `EducationalOrganization` that is posing a problem. I'm not sure having a single level of `department` property is sufficient. Take the following scenarios, for example:

1. University (`EducationalOrganization`)
    - Faculty (`Department`)
        - Department (???)

2. College/School (`EducationalOrganization`)
    - Department (`Department`)

3. University (`EducationalOrganization`)
    - College/School  (`Department`)
        - Department  (???)

And in places like Poland, the hierarchy is even more complex:

4. University - Uniwersytet (`EducationalOrganization`)
    - Faculty - Wydział  (`Department`)
        - Institute - Instytut  (???)
            - Chair - Katedra  (???)
                - Department - Zakład   (???)
                    - Research group - Pracownia, Zespół  (???)

If we have something like `subDepartment` and `parentDepartment` (which will be similar to `parentOrganization` and `subOrganization`) will that not take care of this hierarchy problem?

**Comment by philbarker** [comment]
There is no `Department` class, the `department` property points to an `Organization`. So you have two choices,
1. ignore the academic nomenclature and treat faculties, colleges, schools as "departments",
University (`EducationalOrganization`) -`department`-> Faculty (`EducationalOrganization`) -`department`-> Institute  (`EducationalOrganization`) ...
or
2. use the `subOrganization` property,
University (`EducationalOrganization`) -`subOrganization`-> Faculty (`EducationalOrganization`) -`subOrganization`-> Institute  (`EducationalOrganization`) ...

FWIW it looks like the `department` relationship is more about what you get in "[department stores](https://en.wikipedia.org/wiki/Department_store)" than academia, so I would go with option 2.

You could use `additonalType` if you have a local need to disambiguate the different levels of `EducationalOrganization`

**Comment by dakala** [comment]
Thanks @philbarker, for the insight. I noticed the description for `department` had the example of stores but missed the  fact that there's no `Department` class.
