### ISSUE TITLE
Can we have these as part of all-layers-properties.csv

### ISSUE THREAD

**Issue by satyam-bala** [schemaorg/schemaorg#2509]
The below types are kinds of properties of primitive type Text, but they are defined in all-layers-types.csv.
I think it make more sense these should part of all-layers-properties.csv
    CssSelectorType
    PronounceableText
    XPathType

Generating the Schema would be easier if they follow certain standards.

**Comment by RichardWallis** [comment]
As these are Types, not Properties, their definition can be found in the _all-layers-types.csv_ file.
