### ISSUE TITLE
Schema.org should define how to use SKOS-like vocabularies

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#251]
Migrating in from https://www.w3.org/2011/webschema/track/issues/30

```
    Stephane Corlosquet, Jean Delahousse and others have explored proposals
    for representing SKOS in Schema.org. After much discussion on 
    public-vocabs@w3.org and amongst schema.org partners, we didn't 
    achieve consensus on doing this. A followup proposal "MiniSKOS" 
    has received broadly positive feedback. This issue tracks the 
    MiniSKOS proposal.

    See http://www.w3.org/wiki/WebSchemas/SKOS for earlier discussion, 
    http://lists.w3.org/Archives/Public/public-vocabs/2013Nov/0121.html for miniskos proposal.
```

This also relates to the issues we sometimes discuss as 'external enumerations'.

**Comment by danbri** [comment]
see also https://www.w3.org/2011/webschema/track/issues/31  Schema.org miniSKOS proposal needs careful design for LRMI targetUrl property

        "From Phil Barker, http://lists.w3.org/Archives/Public/public-vocabs/2013Nov/0128.html 
        http://lists.w3.org/Archives/Public/public-vocabs/2013Nov/att-0128/00-part
        also on LRMI list, see https://groups.google.com/forum/#!topic/lrmi/jwgo02DpQzY

        Phil notes that the original miniSKOS proposal declares targetUrl as having a 
        possible expected type of 'Topic'. The properties of that Topic (described 
        locally or remotely) are similar to those of the 
        http://schema.org/AlignmentObject which has the http://schema.org/targetUrl property."

**Comment by mfhepp** [comment]
See also the recent discussion re isSimilarTo, https://github.com/schemaorg/schemaorg/issues/582
