### ISSUE TITLE
MedicalAudience  and PhysicalExam: Ambiguity with multiple inheritance 

### ISSUE THREAD

**Issue by satyam-bala** [schemaorg/schemaorg#2510]
MedicalAudience
Thing > Intangible > Audience > PeopleAudience > MedicalAudience
Thing > Intangible > Enumeration > MedicalEnumeration > MedicalAudience
Thing > Intangible > Audience > MedicalAudience

PhysicalExam
Thing > Intangible > Enumeration > MedicalEnumeration > PhysicalExam
Thing > MedicalEntity > MedicalProcedure > PhysicalExam

Shall we all the Enumeration types as separate names.  
For example: PhysicalExam is used in MedicalSign, which doesnt explain it is using Enumeration or 
MedicalProcedure implementation.

Solution:
All the classes extending both Enumeration and other implementations should have separate name.

For Example:

MedicalAudienceEnumeration
Thing > Intangible > Enumeration > MedicalEnumeration > MedicalAudienceEnumeration

MedicalAudience
Thing > Intangible > Audience > PeopleAudience > MedicalAudience
Thing > Intangible > Audience > MedicalAudience

PhysicalExamEnumeration
Thing > Intangible > Enumeration > MedicalEnumeration > PhysicalExamEnumeration

PhysicalExam
Thing > MedicalEntity > MedicalProcedure > PhysicalExam

**Comment by RichardWallis** [comment]
These are part of a set of known anomalies covered by issue #2444 (_Evaluation of PR #2250 which rationalised issues in the definition Enumeration Values, it was identified that the fix had wider ramifications and was therefore reversed in PR #2443._)

I am going to close this issue in favour of that more encompassing issue.
