### ISSUE TITLE
CreditCard - Ambiguity with multiple inheritance and Enumeration

### ISSUE THREAD

**Issue by satyam-bala** [schemaorg/schemaorg#2511]
The CreditCard definition hierarchy: 
Thing > Intangible > Enumeration > PaymentMethod > PaymentCard > CreditCard
Thing > Intangible > Service > FinancialProduct > LoanOrCredit > CreditCard
Thing > Intangible > Service > FinancialProduct > PaymentCard > CreditCard

If any other Type referring the CreditCard as a member, they can't tell which type should be used Enumeration type or other implementation type.

Suggestion:
All the enumerations should have a separate name like CreditCardEnumeration.

Looking forward for your response.

**Comment by RichardWallis** [comment]
These are part of a set of known anomalies covered by issue #2444 (_Evaluation of PR #2250 which rationalised issues in the definition Enumeration Values, it was identified that the fix had wider ramifications and was therefore reversed in PR #2443._)

Thanks for your input which will be noted.  However, I am going to close this issue in favour of that more encompassing issue.
