### ISSUE TITLE
Enumeration "DeliveryMethod" members incorrect in all-layers-types.csv

### ISSUE THREAD

**Issue by satyam-bala** [schemaorg/schemaorg#2512]
As per the definition of https://schema.org/DeliveryMethod, the members LockerDelivery, OnSitePickup, ParcelService.

But the 'enumerationtype' column value not consistent in all the three types: LockerDelivery, OnSitePickup, ParcelService.

**Comment by RichardWallis** [comment]
Fixed in PR #2655
