### ISSUE TITLE
'PaymentCard' definition in all-layers-types.csv, not as per Schema.org

### ISSUE THREAD

**Issue by satyam-bala** [schemaorg/schemaorg#2513]
As per https://schema.org/PaymentMethod, members - PaymentCard.
And PaymentCard definition is 
Thing > Intangible > Enumeration > PaymentMethod > PaymentCard
Thing > Intangible > Service > FinancialProduct > PaymentCard

Please move PaymentMethod from subTypeOf column to enumerationtype column of PaymentCard type in all-layers-types.csv.

**Comment by RichardWallis** [comment]
These are part of a set of known anomalies covered by issue #2444 (_Evaluation of PR #2250 which rationalised issues in the definition Enumeration Values, it was identified that the fix had wider ramifications and was therefore reversed in PR #2443._)

Thanks for your input which will be noted.  However, I am going to close this issue in favour of that more encompassing issue.
