### ISSUE TITLE
Allow more Expected Types for ApplicationDeadline

### ISSUE THREAD

**Issue by reginafcompton** [schemaorg/schemaorg#2520]
# Description
The WorkBasedProgram and EducationBasedProgram have an `ApplicationDeadline` field with `Date` as the expected type. 

I am currently working with Goodwill International to store their program data using Schema.org definitions (ultimately, for ingestion by Google pathways). Goodwill programs have a flexible understanding of "application deadlines," in that the deadline can be "ongoing" or "rolling." 

# Requested Change
Can the Program schema broaden how it stores information about application deadlines? E.g., allow for "Text" or "DefinedTerm" as an Expected Type, so that "rolling" or "ongoing" can be acceptable values for this field.

**Comment by reginafcompton** [comment]
@vholland – I am tagging you per a suggestion from @philbarker.

Do you have any thoughts on this? I could open a PR, if you're not opposed to it. Thanks in advance!

**Comment by vholland** [comment]
Supporting schema.org/Text makes sense to me.

With that said, taking off my schema.org hat and putting on my Google hat, if authors are interested in providing markup for Google features, they should follow the recommendations in the Google developer docs.

**Comment by reginafcompton** [comment]
Thank you @vholland ! 

I opened a PR to address this issue: https://github.com/schemaorg/schemaorg/pull/2607 I welcome your review on it, Vicki.

(And for your "Google hat" – I agree. Goodwill plans to follow the Pathways documentation for the time being, at least until/if Pathways adjusts the ApplicationDeadline field given the (hopefully) new Schema.org definition.)

**Comment by RichardWallis** [comment]
Closed in favour of that PR #2607
