### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by ersanyakit** [schemaorg/schemaorg#2523]
What is the best schema for all makes and models of vehicles?

> {
  "@context": "http://schema.org",
  "@type": [
    "CollectionPage",
    "Vehicle"
  ],
  "brand": "MERCEDES",
  "description": "MERCEDES BRAND DESCRIPTION",
  "name": "MERCEDES",
  "image": "mercedes-logo.jpg",
  "mainEntity": {
    "@type": "ItemList",
    "itemListElement": [
      {
        "@type": [
          "Car",
          "ProductModel"
        ],
        "url": "http://google.com",
        "name": "MERCEDES A180",
        "description": " ",
        "image": "https://image.com/random.jpg"
      },
      {
        "@type": [
          "Car",
          "ProductModel"
        ],
        "url": "http://google.com",
        "name": "MERCEDES E200",
        "description": " ",
        "image": "https://image.com/random.jpg"
      }
    ]
  }
}

- mercedes

1. - e200
2. - c180
3. - a180

- bmw

1. 1.16
2. 320
3. 520

- audi

1. tt
2. a3
3. a4
4. a5

am i doing this correctly?
thanks for your advices

**Comment by RichardWallis** [comment]
This list is more for the discussion of the structure of the Schema.org vocabulary itself, as against its use and interpretation by data consumers such as major search engines.

In closing this issue however I will offer a couple of personal thoughts on your question.

Preferably a site would simply provide an individual page for each entity (Car in your case)  that would include its Schema description as the _mainEntity_ of that _WebPage_. A collection page, linking to those individual pages, should not then need structured markup.

If that is not practical, you could mark up the collection page following guidelines from such a data consumer. (eg. [Google](https://developers.google.com/search/docs/guides/sd-policies#multiple-elements))
