### ISSUE TITLE
HowTo Warnings in JSON-LD mark up

### ISSUE THREAD

**Issue by cricketmcanally** [schemaorg/schemaorg#2525]
I continuously get warnings on my HowToSection, Steps, and Tips saying "one of image or video must be provided", "The name field is recommended.", and "the url field is recommended". However, those fields do not apply in my case AND the examples in schema.org do not include these fields either. https://schema.org/HowToDirection 
why would google's structured data testing tool throw these warnings, and how can we get around that? The webmaster of the site that my article is posted on says that i need to ensure i have no warnings.
Thanks!

**Comment by WeaverStever** [comment]
Google tends to call them Rich Snippets and changes requirements to fit their needs.

**Mark up your how-to pages with structured data**
https://developers.google.com/search/docs/data-types/how-to

Should be a working sample here.
https://search.google.com/test/rich-results?utm_campaign=devsite&utm_medium=jsonld&utm_source=how-to
