### ISSUE TITLE
Q: Which schema.org type should be used for a hackathon?

### ISSUE THREAD

**Issue by gonzalocasas** [schemaorg/schemaorg#2526]
There is the generic [Event](https://schema.org/Event) type and there are several subtypes, but nothing seems to fit exactly a hackathon. Are there any options, or could we propose a new type to be added somehow?

**Comment by danbri** [comment]
Good idea. Adding it to Pending section...

Thanks!

**Comment by gonzalocasas** [comment]
@danbri cool, thanks! I link the issue where I originally proposed something this basic idea to an open source hackathon platform we use quite a bit: https://github.com/hackathons-ftw/dribdat/issues/112
