### ISSUE TITLE
http(s)://schema.org/version/latest/schema.rdf link broken

### ISSUE THREAD

**Issue by mr-c** [schemaorg/schemaorg#2527]
It 302 redirects to https://schema.org/version/Unknown/schema.rdf => 404 Not Found

**Comment by RichardWallis** [comment]
Fixed

**Comment by mr-c** [comment]
Confirmed, thank you!

**Comment by mr-c** [comment]
These are broken again

**Comment by RichardWallis** [comment]
Checkout the new [from V9.0] download [file naming and contents](https://schema.org/docs/developers.html#defs).
