### ISSUE TITLE
hasOccupation shouldn't have same restrictions as Occupation

### ISSUE THREAD

**Issue by HectorLS** [schemaorg/schemaorg#2530]
Hello,
I'm filling this snippets of code on [Google Data Testing Tool](https://search.google.com/structured-data/testing-tool/)

**🧐 Last snippet for fast testing on the link**

So i have the creator object and i wanted to add the occupation _( because seems to be way more complete than jobTitle, which by the way i don't understand the difference)_ 
The problem appears when the dev complain about two keys required and recommended

type | KEY | Message
-- | -- | --
❌| estimatedSalary | A value for the estimatedSalary field is required.
⚠️ | mainEntityOfPage | The mainEntityOfPage field is recommended. Please provide a value if available.

> Hey Google, my salary is not of your business ! 

I see that Occupation is also used for searching Job position, in that case it makes sense to be a WARNING, but i think it should never be a required key, since: 
 - is nobody business
 - for job position, they may have a range of salary or may not depending of the person skills

```json
# ..............
"creator": {
	"@type": "Person",
	"name": "${PERSON NAME HERE}",
	"email": "${PERSON EMAIL HERE}",
	"funder": "${BRAND NAME HERE}",
	"jobTitle": "Photographer",
	"hasOccupation": {
		"name": "Photographer",
		"description": "Artist",
		"occupationalCategory": {
			"@type": "CategoryCode",
			"codeValue": "3431",
			"name": "Photographers"
		},
		"occupationLocation": [
			{
				"@type": "Country",
				"name": "United States"
			}
		]
	}
}


#..........
```

For fast copy and test i did this snippet just wrapped with the schema context
```json
{
	"@context": "http://schema.org",
	"@type": "ListItem",
	"creator": {
		"@type": "Person",
		"name": "${PERSON NAME HERE}",
		"email": "${PERSON EMAIL HERE}",
		"funder": "${BRAND NAME HERE}",
		"jobTitle": "Photographer",
		"hasOccupation": {
			"name": "Photographer",
			"description": "Artist",
			"occupationalCategory": {
				"@type": "CategoryCode",
				"codeValue": "3431",
				"name": "Photographers"
			},
			"occupationLocation": [
				{
					"@type": "Country",
					"name": "United States"
				}
			]
		}
	}
}
```

**Comment by HughP** [comment]
I ran into the same error+warning today when I was trying to mark up my CV with JSON+LD. So should we avoid using the term unless we also publish a salary?

**Comment by RichardWallis** [comment]
These warnings / errors are a feature of a particular testing tool, testing how appropriate data is for consumption by their services.  The Schema.org vocabulary itself has no such constraints.

Therefore this is not the forum to ask questions as to how Google use your data, I suggest their product forums https://productforums.google.com/forum/#!categories/webmasters/structured-data and nearby.

**Comment by HectorLS** [comment]
Sorry @RichardWallis  i thought that schema.org was the one specifying the required fields
