### ISSUE TITLE
Add government benefits coverage to SpecialAnnouncement

### ISSUE THREAD

**Issue by lucy-kind** [schemaorg/schemaorg#2534]
This will allow coverage of different government benefits info under the SpecialAnnouncement object in schema.org. This is pertinent to the ongoing covid-19 situation, and will allow government sites to markup their pages which provide benefits information.

Under SpecialAnnouncement:

Add new property of "governmentBenefitsInfo", which takes new type of "BenefitsInfoSpecification".

Under GovernmentBenefitsInfoSpecification:

Add new property of "legislationJurisdiction"
Add property of "url".
Add new property of "benefitsType", which takes new type of CovidBenefitsType as its value (enum).
Add new property “benefitsFrom”.
Add new property “beneficiaryType” (takes properties from “audience”).

Under CovidBenefitsType:

Create list of enums:
   Unemployment support
   Business support
   One-time payments
   Paid leave
   Parental support
   Disability support
   Health care
   Basic income

**Comment by RichardWallis** [comment]
Merged in #2538
