### ISSUE TITLE
category domainIncludes URL: wrong domain

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#2536]
https://schema.org/category "is Used on these types... URL" i.e.
```
schema:category schema:domainIncludes schema:URL 
```

But `URL` is a datatype so it can't have outgoing properties.

This is a regression, introduced in the last 2 months.
@danbri @RichardWallis

**Comment by RichardWallis** [comment]
That is a bit odd and needs investigating.

**Comment by danbri** [comment]
my bad - this was a bug in my implementation of #2490 - fixing
