### ISSUE TITLE
PhysicalActivityCategory missing in turtle

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#2537]
The turtle export at https://schema.org/docs/developers.html
is missing class https://schema.org/PhysicalActivityCategory.

That class is used in
```ttl
schema:category schema:rangeIncludes schema:PhysicalActivityCategory
```

@danbri @RichardWallis

**Comment by RichardWallis** [comment]
As _PhysicalActivityCategory_  is part of the health-lifesci area of the vocabulary, its definition is not contained in the schema.ttl download file version. This only contains terms defined in the vocabulary core.

To ensure you receive definitions for terms in all areas of the vocabulary, select the all-layers version of download files.  For example: https://schema.org/version/latest/all-layers.ttl.

**Comment by VladimirAlexiev** [comment]
1: PhysicalActivityCategory is note defined in all-layers.ttl either.

2: Even if you were right: if it's not defined in schema.ttl, why it is used as range?

3: And how about these:
http://schema.org/CategoryCode
http://schema.org/CssSelectorType
http://schema.org/DefinedTerm
http://schema.org/EducationalOccupationalCredential
http://schema.org/GeospatialGeometry
http://schema.org/XPathType

**Comment by RichardWallis** [comment]
The reason for this is historical, as these areas of the vocabulary evolved from layers/extensions into areas and today it is more of a tagging mechanism, the separation makes little sense.  

There is a need for rationalisation in this area and there is an open issue to cover it #2304

**Comment by VladimirAlexiev** [comment]
I checked all classes above, and they are defined in https://schema.org/version/latest/schemaorg-current-https.ttl. Good!
