### ISSUE TITLE
EducationalOrganizations should be CivicStructures

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2540]
From the discussion at https://twitter.com/dannysullivan/status/1248363322912563205

For some reason, educational organizations (universities, elementary schools, etc) are listed under ```Organization``` but are not under ```CivicStructure```. It is strange to not consider these physical places as well.

I propose adding ```CivicStructure``` as a supertype of ```EducationalOrganization``` in addition the the existing ```Organization```. This is similar to the pattern for ```LocalBusiness```.

**Comment by danbri** [comment]
This LGTM

Fast-tracking for covid-19 response /cc @tmarshbing @scor @nicolastorzec @tilid @rvguha

**Comment by danbri** [comment]
https://github.com/schemaorg/schemaorg/pull/2541 is failing checks

> INFO:test_graphs:Term 'http://schema.org/2526' has nonexistent supertype: 'http://schema.org/@@@@'

Merging and fixing

**Comment by danbri** [comment]
@vholland maybe you fixed it already? the file in pending seemed ok to me, although as this isn't new vocab I'll move the fix into core.

**Comment by vholland** [comment]
Included in schema.org 7.04
