### ISSUE TITLE
CreativeWork description duplication

### ISSUE THREAD

**Issue by mattgarrish** [schemaorg/schemaorg#2544]
Not sure if this is the best place to report it, but I'm finding a lot of the property descriptions are being duplicated (or triplicated) on the web site now. It only seems to be happening with CreativeWork, though.

**Comment by RichardWallis** [comment]
@mattgarrish can you supply some examples of what you are seeing.

**Comment by mattgarrish** [comment]
The description for `abstract`, for example, is:

> An abstract is a short description that summarizes a CreativeWork. An abstract is a short description that summarizes a CreativeWork.

`acquireLicensePage` has:

> Indicates a page documenting how licenses can be purchased or otherwise acquired, for the current item. Indicates a page documenting how licenses can be purchased or otherwise acquired, for the current item.

There's not specific pattern I can see to why some are duplicated and others aren't, but when you reach `url` it even comes out three times:

> URL of the item. URL of the item. URL of the item.

I get the same in Firefox, Chrome and Edge on Windows 10.

**Comment by RichardWallis** [comment]
Will investigate - thanks for the heads up.

**Comment by RichardWallis** [comment]
This coincided with problems with hosting cloud service.

Now appears to be OK.
