### ISSUE TITLE
Cost/price missing in ImagingTest

### ISSUE THREAD

**Issue by philippeski** [schemaorg/schemaorg#2546]
Hi 
There is no way to add the price directly to Imaging test.
It's super important for user, because in this kind of test, price is the most important selection criteria. 
Maybe i'm wrong and there is way that i can't  find. 
Could you help me by adding the price property there or maybe describing me how to do it. 
Thx in advance !

**Comment by jvandriel** [comment]
You can indicate the price of an [ImageObject](https://schema.org/ImageObject) by adding an [Offer](https://schema.org/Offer) via the [offers](https://schema.org/offers) property as such:
```
{
  "@type":"ImageObject",
  "url":"https://example.com/some-image-jpg",
  "offers":
  {
     "@type":"Offer",
     "price":"20",
     "priceCurrency":"USD"
  }
}
```
