### ISSUE TITLE
Feature Request: Senior/At Risk Shopping Hours

### ISSUE THREAD

**Issue by jeffmcnabb** [schemaorg/schemaorg#2547]
Hello, I have looked through the latest release addressing COVID updates, however I don't see a way that I can add Senior/Those At High-Risk Shopping Hours for retailer locations. 
Is this something I am missing, or is this a Schema that is possible in the works? Thank you for your help. We have hundreds of retailers adding these special shopping hours, and I am looking at a way for Google to index them.

**Comment by StevenBlack** [comment]
This seems quite specific, and would benefit from abstraction.

For example, 

* swimming pools and other rec facilities may have women-only activity times.  These are for religious or other reasons.

* stores may have Sunday hours, for similar reasons.

* transit systems have Sunday and holiday schedules....

**Comment by jeffmcnabb** [comment]
> This seems quite specific, and would benefit from abstraction.
> 
> For example,
> 
> * swimming pools and other rec facilities may have women-only activity times.  These are for religious or other reasons.
> * stores may have Sunday hours, for similar reasons.
> * transit systems have Sunday and holiday schedules....

Thank you for the response, Steven. I can tell you that our clients are Grocery Stores, if that helps at all. I see what you mean by abstracting this. One aspect I haven't figured out, is that a) these should be temporary to some degree, and b) they are often somthing like "Every Wednesday", and so it's not very easy to use the Holiday Hours schema out of spec. 
Wondering if there's another way I can do it that Google would show the result in search. One thing I've used so far was creating a separate "Place" inside of a retailer location, and making it's hours only be the 1 hour on wednesday mornings. However, this still hides the listing away under a few levels on a google search.

**Comment by StevenBlack** [comment]
@jeffmcnabb upon looking deeper, it appears like this may already be covered.

See [Schedule](https://schema.org/Schedule) and, in particular, its [exceptDate](https://schema.org/exceptDate) property.

> Thing > Property > exceptDate 

> Defines a Date or DateTime during which a scheduled Event will not take place. The property allows exceptions to a Schedule to be specified. If an exception is specified as a DateTime then only the event that would have started at that specific date and time should be excluded from the schedule. If an exception is specified as a Date then any event that is scheduled for that 24 hour period should be excluded from the schedule. This allows a whole day to be excluded from the schedule without having to itemise every scheduled event.

**Comment by jeffmcnabb** [comment]
@StevenBlack A few things I see with that: 1) We use **OpeningHoursSpecification**, not Schedule, because they are local businesses. 2) The exceptDate appears to be a pending property. 3) I'd like a standardized way these would be identified as a COVID related event, in hope that Google will index it/display it easily, when a customer searches for store hours.
  
That said, it seems to me this this might be closer to what I should use: https://schema.org/specialOpeningHoursSpecification
However, I cannot figure out how to use that Schema in Microdata.

**Comment by jeffmcnabb** [comment]
I'll try using some Microdata like this; However, I hope to see Google and others adopt a standardised way to list this information, as it seems nearly every store is adopting this type of shopping hour.
  
`<div>`  
`    <h1>Middle of Nowhere Foods</h1>`  
`    <h2>Opening hours</h2>`  
`      <meta itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 07:00-20:00">`  
`      <p>Open daily <time datetime="09:00:00">9am</time>-<time datetime="20:00:00">2pm</time>  </p>`  
`    <ul>`  
`      <h3>COVID-19 Senior and At Risk Shopping Hour: `  
`        <li itemprop="specialOpeningHoursSpecification" itemscope itemtype="http://schema.org/specialOpeningHoursSpecification"  content="We 07:00-08:00">`  
`        <time itemprop="opens" datetime="07:00:00">7am</time>-<time itemprop="closes" datetime="08:00:00">8am</time>`  
`      </h3>`  
`      </li>`  
`    </ul>`  
`  </div>`

**Comment by jeffmcnabb** [comment]
I apologize for the hassle; It seems Google has now posted official guidelines on this, and suggest using the new SpecialAnnouncement property. https://developers.google.com/search/docs/data-types/special-announcements
  
Not ideal long term, but I will mark this as resolved for now.
