### ISSUE TITLE
How does this format relate with openrecipe format?

### ISSUE THREAD

**Issue by synergiator** [schemaorg/schemaorg#2548]
Please see:
https://github.com/techhat/openrecipeformat

**Comment by RichardWallis** [comment]
I am not aware there has been interaction between those involved with openrecipe and Schema.org.

However a brief look at openrecipe indicates many similarities between Schema [Recipe](https://schema.org/Recipe)  and [HowTo](https://schema.org/HowTo) which it builds upon.
