### ISSUE TITLE
guidance on using PropertyValue for identifier

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#2549]
The guidance given in the data model for using `PropertyValue` types for `identifier` properties [says](https://schema.org/docs/datamodel.html#identifierBg) 

>  a PropertyValue pair ('name', 'identifier') pair can be used when a standard URI form of the identifier is unavailable

However, Google's [guidance on JobTraining (Beta)](https://developers.google.com/search/docs/data-types/job-training) uses a better-looking pattern:
```      
"identifier": {
         "@type": "PropertyValue",
         "propertyID": "CIP2010",
         "value": "12.3456"
      }
```
This avoids giving the identifier an identifier, and as propertyID is there and more specific than name we might as well use it.

Can we include this pattern in the documentation?

(tbh, `PropertyValue` has so many properties that are difficult to interpret in this context is would be much easier for implementers just to have `IdentifierValue` type with properties `identifierScheme` and `value`.)

**Comment by HughP** [comment]
I second @philbarker 's observations, as I also recently found the variation two documentations confusing as I struggled through JSON+LD implementation. https://schema.org/identifier has two JSON+LD examples, but out of 15 examples for https://schema.org/PropertyValue only 1 has an example for JSON+Ld.

In my case I was trying to describe a Ph.D dissertation as part of an Academic CV. I was looking for how I should specify a term in the name. I understand the guidance to be to use a URI in the `"name"` value. But I could not identify a single URI for the handel system, which is broadly used in academic publishing; similarly I was unsure what to use in the case of DOIs: should DOI go in the name value or should "Document Object Identifier", or should some URL such as the base to the doi resolver service?

The content below is where I landed. I'm not sure if it is the best example, but if it is helpful for variety of examples, I'm happy to let it be used as such...

```JSON
{"@type": "Thesis",
"schemaVersion": "https://schema.org/version/7.0/",
"sdDatePublished": "2020-04-12T17:21:36+02:00",
"@id": "https://hdl.handle.net/1794/25259",
"name":"Nominalization and predication in U̱t-Ma'in",
"identifier":
 {
     "@type": "PropertyValue",
     "name": "Handle System",
     "value": "1794/25259"
 },
"author": "Rebecca Dow Smith Paterson",
"inSupportOf": "Doctor of Philosophy",
"copyrightHolder": "Rebecca Dow Smith Paterson",
"copyrightYear": "2019",
"datePublished": "2019",
"license": "https://creativecommons.org/licenses/by-nd/4.0/",
"inLanguage": "en-US",
"keywords": ["Linguistics","Nominalization","U̠t-Ma'in", "Kainji language", "morphosyntax", "Nigeria", "predication"],
"description": "PhD Dissertation in Linguistics from the University of Oregon."
}
```

**Comment by danbri** [comment]
Sounds like this does need attention

**Comment by smrgeoinfo** [comment]
see https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#identifier  for ESIP guidance on identifiers in PropertyValue

**Comment by philbarker** [comment]
@danbri if this does need attention, shouldn't the issue be re-opened?
