### ISSUE TITLE
 Vocabulary Definition Files of IOT cannot be found on the server

### ISSUE THREAD

**Issue by canercelik** [schemaorg/schemaorg#2554]
I tried JSON and CSV formats, results were same : 

"Error: Not Found
The requested URL /version/7.04/ext-iot.rdf was not found on this server."

Same error for 7.03, 7.02 and 7.01.

**Comment by RichardWallis** [comment]
The reason for this is that the iot area of the vocabulary is currently an empty a placeholder for the introduction of future terms.  The process that produces the definition files, not finding any terms, does not produce the files for that area.

Based upon the outcome of issue #2304 (Rationalisation of dump files) we can either close or fix this issue.

**Comment by danbri** [comment]
There is a community nearby working towards this, check out https://github.com/iot-schema-collab/iotschema

I think we can close this issue, @RichardWallis
