### ISSUE TITLE
Richshop

### ISSUE THREAD

**Issue by 0842854175** [schemaorg/schemaorg#2557]
ฉันอยากได้โครงสร้าง ตลาดอีคอมเมิร์ธ ออนไลน์ Richshop ระบบบริการผู้ค้า

**Comment by RichardWallis** [comment]
English translation:

> I would like structure Marketing, e-commerce, online bank Richshop system vendors.

A good start would be to take a look at Google's Structured Data pages - https://developers.google.com/search/docs/guides/search-gallery
