### ISSUE TITLE
SpecialAnnouncement still not a Class

### ISSUE THREAD

**Issue by joshin2017** [schemaorg/schemaorg#2560]
When can we expect SpecialAnnouncement as "@type": "rdfs:Class" in https://schema.org/version/latest/schema.jsonld ?

**Comment by RichardWallis** [comment]
As _ SpecialAnnouncement_  is part of the pending area of the vocabulary, its definition is not contained in the _schema.jsonld_ download file version. This file only contains terms defined in the vocabulary core.

To ensure you receive definitions for terms in all areas of the vocabulary, select the _all-layers_ version of download files.  For example: https://schema.org/version/latest/all-layers.jsonld.
