### ISSUE TITLE
use of inLanguage in name

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2566]
Greetings,

I am asking for clairy on the usage of schema "name" https://schema.org/name.  _What are the legal objects of the name property?_ The instructions seem to indicate that the only expected value is text.

Use: 
If I am describing the name of something, the name might change depending on the language in use. Good examples are Germany cities, Munich (München@de, Munich@en, Munich@fr, Monaco di Baviera@it)  and Cologne (Cologne@en, Köln@de, Cologne@fr, Colonia@it). 

So, as the instructions of the name property indicate it can take text such as: `Cologne` but can I legally put other clarifying content in the name property? _an array instead of just text_, such as:

```JSON
  "name": [{ 
"name": "Cologne",
"inLanguage": "en"},
{ "name": "Köln",
"inLanguage": "de"
},
{ "name": "Cologne",
"inLanguage": "fr"
},
{ "name": "Colonia",
"inLanguage": "it"
}
],

```

Does it seem to be a bit recursive to use the name property inside of the name property? Is there a better option?

**Comment by vholland** [comment]
There are a variety of ways to do [string internationalization in JSON-LD](https://www.w3.org/TR/json-ld11/#string-internationalization). If you are overriding the language for a specific property, you can do something like:

```
"name": [
  {
    "@value": "Cologne",
    "@language": "en"
  },
  {
    "@value": "Köln",
    "@language": "de"
  },
  {
    "@value": "Cologne",
    "@language": "fr"
  },
  {
    "@value": "Colonia",
    "@language": "it"
  }
]
```

**Comment by akuckartz** [comment]
@vholland As a native citizen of Cologne I like that example :-)

One could even add "Kölle" for the dialect "Kölsch"
https://ksh.m.wikipedia.org/wiki/K%C3%B6lle
https://en.m.wikipedia.org/wiki/Colognian_dialect
