### ISSUE TITLE
Add property/type/enum counts (with/without superseded terms) to full.html

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#257]
This would save me from goofing around with grep every time @rvguha asks how many terms we have.

**Comment by stuartrobinson** [comment]
I assume that the goal here is to automatically update the counts with every build. Would that just be a matter of querying the contents of schema.rdfa?

**Comment by danbri** [comment]
@stuartrobinson - missed your comment here, but yes. Looks like we did it, too - only in schemas.html not full.html so closing here.

http://schema.org/docs/schemas.html has "The core vocabulary currently consists of 583 Types, 846 Properties, and 114 Enumeration values."

We don't currently break out stats for the extensions...
