### ISSUE TITLE
Sale_Price along with Price in Scheme

### ISSUE THREAD

**Issue by Rammahawar** [schemaorg/schemaorg#2570]
Hi All,

Want to know that can we put both price in micro-data. Eg. price and sale_price

1. Price is Product price
2. Sale_Price is Discounted price

Here is the example:
Product is **A**
Price is $1500
and After 10% Discount **Sale_Price** is $1350

**Comment by RichardWallis** [comment]
You would describe multiple [offers](https://schema.org/offers) for the [Product](https://schema.org/Product).
One [Offer](http://schema.org/Offer) describing the normal price and conditions.  Others describing price etc. for "Sale Price", "Special Offer", etc.  - including time or other availability constraints.

**Comment by Rammahawar** [comment]
> You would describe multiple [offers](https://schema.org/offers) for the [Product](https://schema.org/Product).
> One [Offer](http://schema.org/Offer) describing the normal price and conditions. Others describing price etc. for "Sale Price", "Special Offer", etc. - including time or other availability constraints.

**Comment by Rammahawar** [comment]
> You would describe multiple [offers](https://schema.org/offers) for the [Product](https://schema.org/Product).
> One [Offer](http://schema.org/Offer) describing the normal price and conditions. Others describing price etc. for "Sale Price", "Special Offer", etc. - including time or other availability constraints.

Thanks for reply @RichardWallis 

Can you the info in detail. What will be schema code or how can we define in micro-data.
