### ISSUE TITLE
Content negotiation broken. 

### ISSUE THREAD

**Issue by msbachler** [schemaorg/schemaorg#2578]
Home page returns html not jsonld.

curl -L -H 'Accept: application/ld+json' https://schema.org/
curl -L -H 'Accept: application/ld+json' http://schema.org/

**Comment by teledyn** [comment]
This has also shut down the json-ld playground and apps using RDFLib/rdflib-jsonld

**Comment by teledyn** [comment]
update at 16:20 EDT: that curl test now returns HTML again (for a while today it was returning binary) but still leaves our json-ld apps broken

**Comment by danbri** [comment]
This is a known problem. We were hit with a substantial DOS attack a few days ago, and it took the site largely offline. We have made several changes to be more robust, one of which was to replace the content-negotiated and dynamically generated homepage with a static HTML document.

Instead of HTTP content negotiation we are adopting the use of a Link: header as specified in the new JSON-LD 1.1 specifications. The new code is on webschemas.org already and will be on the main official site i.e. schema.org in near future. See https://gist.github.com/danbri/6c715ff96fe9e7a43adeba1776b51c18 for sample HTTP transcript via curl.

* See https://www.w3.org/TR/json-ld11/#alternate-document-location for Link: spec
*  https://w3c.github.io/json-ld-api/tests/remote-doc-manifest#tla03 is the test for this piece of the spec. @gkellogg tells me there are 5 implementations reported as passing it.
* We are also restoring CORS headers to the homepage URL

While I regret that this has been inconvenient to various folk, maybe it can help kickstart discussion of robustness in JSON-LD parsing? It is not ideal to have software processes which assume 100% perfect access to remote networked services. At Schema.org we [expressed concerns](https://lists.w3.org/Archives/Public/public-linked-json/2014Jan/0001.html) back in 2014 (/cc @rvguha) that

> [...] we do have concerns about the
schema.org *website* forming an integral part of numerous unknown
software systems and applications. It ought to be possible to do
useful things with schema.org-based json-ld without a dependency on
the Web site.

It would be good if JSON-LD parsers all had a documented option to pass in a fallback context URL (or context data) if the documents' self-declared context is currently inaccessible. Perhaps some kind of "do your best to parse this even if heuristics are used" mode which should be ok for certain kinds of application.

**Comment by danbri** [comment]
ok you should be seeing headers for the homepage URL again, i.e.

* access-control-allow-credentials: true
* access-control-allow-headers: Accept
* access-control-allow-origin: *
* link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"

**Comment by kidehen** [comment]
Simple test suite for this problem, just go to [this JSON-LD playground page](https://tinyurl.com/kk7k5qt). 

Currently, I still have CORS sandbox related issues in my browser.

**Comment by gkellogg** [comment]
> While I regret that this has been inconvenient to various folk, maybe it can help kickstart discussion of robustness in JSON-LD parsing? It is not ideal to have software processes which assume 100% perfect access to remote networked services. At Schema.org we [expressed concerns](https://lists.w3.org/Archives/Public/public-linked-json/2014Jan/0001.html) back in 2014 (/cc @rvguha) that
> 
> > [...] we do have concerns about the
> > schema.org _website_ forming an integral part of numerous unknown
> > software systems and applications. It ought to be possible to do
> > useful things with schema.org-based json-ld without a dependency on
> > the Web site.
> 
> It would be good if JSON-LD parsers all had a documented option to pass in a fallback context URL (or context data) if the documents' self-declared context is currently inaccessible. Perhaps some kind of "do your best to parse this even if heuristics are used" mode which should be ok for certain kinds of application.

Caching frequently used contexts is a [Best Practice](https://w3c.github.io/json-ld-bp/#cache-context). My distiller as well as the linter do this, and works fine with the schema.org context. These are both based on the [Ruby json-ld gem](https://github.com/ruby-rdf/json-ld/), with preloaded contexts optionally coming from [json-ld-preloaded](https://github.com/ruby-rdf/json-ld-preloaded) which is updated periodically.

[jsonld.js](https://github.com/digitalbazaar/jsonld.js), which forms the heart of https://json-ld.org/playground (along with [PyLD](https://github.com/digitalbazaar/pyld)), also caches contexts, but only for the lifetime of the process. There is a facility to pass in these contexts, but not utilized AFAIK on the playground.

**Comment by gkellogg** [comment]
> It would be good if JSON-LD parsers all had a documented option to pass in a fallback context URL (or context data) if the documents' self-declared context is currently inaccessible. Perhaps some kind of "do your best to parse this even if heuristics are used" mode which should be ok for certain kinds of application.

@msporny's [Hashlink proposal](https://github.com/digitalbazaar/hashlink) does this, allowing for local copies, out-of-band, and multiple fallback URLs. This really needs to be handled with URI semantics, not per-standard.

**Comment by kidehen** [comment]
I still don't see any "Link:" headers in the HTTP Response coming from schema.org. 

```
curl -IL https://schema.org/Organization
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Accept
Access-Control-Allow-Credentials: true
ETag: 24751200522143328a2749670516490683481
Last-Modified: Fri, 22 May 2020 14:33:28 GMT
X-Cloud-Trace-Context: 13c57c73ebb31d5d24093b7817cd45b8
Content-Length: 113514
Date: Fri, 22 May 2020 14:46:18 GMT
Server: Google Frontend
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```
In addition, https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-632272889 is still alive re JSON-LD playground.

I am a little confused about the way forward, right now. 

/cc @danbri

**Comment by kidehen** [comment]
Note, the following does include "Link:" headers in the schema.org HTTP response.

```
curl -IL https://schema.org/
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept
Access-Control-Allow-Origin: *
Link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"
access-control-allow-methods: GET
Date: Fri, 22 May 2020 14:42:15 GMT
Expires: Fri, 22 May 2020 14:52:15 GMT
ETag: "JCOM7A"
X-Cloud-Trace-Context: dc7f65f74878f0085b39ac48273e5ff6
Content-Type: text/html
Content-Encoding: gzip
Server: Google Frontend
Content-Length: 2362
Age: 485
Cache-Control: public, max-age=600
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

So I guess it is now down to an update in "jsonld.js" re JSON-LD playground. 

/cc @danbri

**Comment by RichardWallis** [comment]
Currently the Link header is only implemented on the home (http://schema.org) page.

I may be wrong but I would expect that is the only URL that would need to link to the context.

**Comment by kidehen** [comment]
> Currently the Link header is only implemented on the home (http://schema.org) page.
> 
> I may be wrong but I would expect that is the only URL that would need to link to the context.

Okay, that's fine actually.

**Comment by dlongley** [comment]
@danbri,

> ok you should be seeing headers for the homepage URL again, i.e.
> 
> access-control-allow-credentials: true
> access-control-allow-headers: Accept
> access-control-allow-origin: *
> link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"

I suspect that an additional CORS header:

> access-control-expose-headers: Link

Must be added to enable browsers to access the "Link" header to find the schema.org JSON-LD context.

**Comment by gkellogg** [comment]
@pchampin noticed that the schema.org access-control-allow-headers header only allows "Access", and not "Link". That might be the issue.

The JSON-LD CG disused this, and we'll document this somewhere under Best Practices, as it's a new pattern.

```
curl -I https://schema.org
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-headers: Accept
access-control-allow-origin: *
link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"
access-control-allow-methods: GET
date: Fri, 22 May 2020 16:32:56 GMT
expires: Fri, 22 May 2020 16:42:56 GMT
etag: "JCOM7A"
x-cloud-trace-context: 740eedb20756ed6df62593fa7144f4e1
content-type: text/html
server: Google Frontend
content-length: 5084
age: 178
cache-control: public, max-age=600
alt-svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

Perhaps it should be `access-control-allow-headers: Accept, Link` or maybe it doesn't need to include "Accept" any longer.

**Comment by dlongley** [comment]
@gkellogg,

That header (access-controller-allow-headers) is for which headers the server will accept from the browser. The use of `Accept` there is unnecessary as it is already a "[CORS safe listed request header](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_request_header)". So that header could be removed. What is missing the the CORS header that exposes response headers to the client:

`access-control-expose-headers: Link`

**Comment by RichardWallis** [comment]
@dlongley, @gkellogg Thanks for the head[er]s up.

I will add the ```access-control-expose-headers: Link``` reference and @danbri will notify when it has been pushed to the site.

**Comment by dlongley** [comment]
Thanks @RichardWallis!

**Comment by danbri** [comment]
Gregg pointed out that we probably wanted access-control-allow-headers: Accept

Fix in progress

**Comment by danbri** [comment]
Ah sorry I see I missed the later comments posted here :) Anyway it should be live soon. Thanks @dlongley @gkellogg @RichardWallis !

**Comment by gkellogg** [comment]
Credit to @pchampin for noticing the omission.

**Comment by danbri** [comment]
ok how does it look now?

>curl --head https://schema.org/ 
>HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-headers: Accept
access-control-allow-origin: *
link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"
access-control-allow-methods: GET
access-control-expose-headers: Link
date: Fri, 22 May 2020 19:53:12 GMT
expires: Fri, 22 May 2020 20:03:12 GMT

**Comment by gkellogg** [comment]
Still seeing `access-control-allow-headers: Accept`, which I think should be `access-control-allow-headers: Link`.

You can try the Person example on the [JSON-LD playground](https://json-ld.org/playground/) once deployed.

**Comment by kidehen** [comment]
> Still seeing `access-control-allow-headers: Accept`, which I think should be `access-control-allow-headers: Link`.
> 
> You can try the Person example on the [JSON-LD playground](https://json-ld.org/playground/) once deployed.

Yes re  ```access-control-allow-headers: Link``` which is easy to miss by the human eye.

**Comment by davidlehn** [comment]
I think jsonld.js on the json-ld.org playground may have some bugs with Link handling.  It's getting the header, but is still failing.  It may be a code path that hasn't been used or tested before.  I'll debug that side.

**Comment by kidehen** [comment]
> Yes re `access-control-allow-headers: Link` which is easy to miss by the human eye.

Actually, ```Access-Control-Allow-Headers: Accept, Link``` is a little more accommodating.

**Comment by gkellogg** [comment]
But, Link isn't an inbound header, as Accept is. perhaps it's correct to use the `access-control-expose-headers: Link` and the issue lies in the library, as @davidlehn suggested.

**Comment by davidlehn** [comment]
jsonld.js XHR document loader had a bug.  Fixed.  Playground updated and seems to work now.

**Comment by kidehen** [comment]
True, in this use-case scenario. For JSON-LD Playground it is the "jsonld.js" library for sure, but in a more generic sense, the header patterns could be a little clearer. 

Ultimately, "Link:" can be used on either side, but that's beyond this current topic as it relates more to User Agent Identity and Single-Page Apps (identified by value of Origin:) etc :) 

[1] https://lists.w3.org/Archives/Public/public-linked-json/2015Mar/0007.html -- some older rumblings with Mark Nottingham about HTTP headers

**Comment by kidehen** [comment]
> jsonld.js XHR document loader had a bug. Fixed. Playground updated and seems to work now.

Works now!

**Comment by Sarke** [comment]
Can we safely assume that `https://schema.org/docs/jsonldcontext.jsonld` will be the valid URL for the foreseeable future?

**Comment by RichardWallis** [comment]
> Can we safely assume that https://schema.org/docs/jsonldcontext.jsonld will be the valid URL for the foreseeable future?

As I have always been taught 'Assumptions are dangerous'

However, that is the file that the previous content negotiation redirected to.
 
As far as guaranteeing the site will direct you to the correct place for any particular release, your software should follow the _Link_ direction in the http headers as described.

Directly accessing the _jsonldcontext.jsonld_ file is possible, but at your own risk of future updates breaking your dependancy.

**Comment by kidehen** [comment]
> As I have always been taught 'Assumptions are dangerous'
> 
> However, that is the file that the previous content negotiation redirected to.
> 
> As far as guaranteeing the site will direct you to the correct place for any particular release, your software should follow the _Link_ direction in the http headers as described.
> 
> Directly accessing the _jsonldcontext.jsonld_ file is possible, but at your own risk of future updates breaking your dependancy.

Yep!

The "Link:"  relation SHOULD become the canonical method for determining the location of the JSON-LD document identified by https://schema.org/ . 

```
curl --head https://schema.org/
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept
Access-Control-Allow-Origin: *
Link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"
access-control-allow-methods: GET
access-control-expose-headers: Link
```

**Comment by stain** [comment]
> > It would be good if JSON-LD parsers all had a documented option to pass in a fallback context URL (or context data) if the documents' self-declared context is currently inaccessible. Perhaps some kind of "do your best to parse this even if heuristics are used" mode which should be ok for certain kinds of application.
> 
> @msporny's [Hashlink proposal](https://github.com/digitalbazaar/hashlink) does this, allowing for local copies, out-of-band, and multiple fallback URLs. This really needs to be handled with URI semantics, not per-standard.

Here is how [JSON-LD-Java](https://github.com/jsonld-java/jsonld-java#loading-contexts-from-classpath) (used by Jena and RDF4J) allows classpath binding for JSON-LD resources - basically works like a pre-warmed cache.

**Comment by stain** [comment]
@davidlehn was this made live on https://json-ld.org/playground/ ? All examples still seems broken.

jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.

**Comment by davidlehn** [comment]
@stain Yeah, playground was updated and works.  However, it looks like schema.org is serving invalid headers now.
```
Access to XMLHttpRequest at 'https://schema.org/' from origin 'https://json-ld.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value '\*'.
```
This is the problem:
```
access-control-allow-origin: \*
```
The content-type isn't working either.  I commented over on https://github.com/schemaorg/schemaorg/issues/2595 since problems might be related.

**Comment by rubensworks** [comment]
Things appear to be mostly working now on my end as well.

However, it looks like the CORS headers are missing on http://schema.org/.
Even though http://schema.org/ just redirects to https://schema.org/ with a 301, CORS headers are still required, otherwise browsers will not follow the redirect.

```
$ curl -v http://schema.org/
*   Trying 2a00:1450:400e:80b::200e...
* TCP_NODELAY set
* Connected to schema.org (2a00:1450:400e:80b::200e) port 80 (#0)
> GET / HTTP/1.1
> Host: schema.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: https://schema.org/
< X-Cloud-Trace-Context: fa9caa9b10a312078b5be850caca95db
< Date: Thu, 04 Jun 2020 07:45:02 GMT
< Content-Type: text/html
< Server: Google Frontend
< Content-Length: 0
<
* Connection #0 to host schema.org left intact
```

**Comment by davidlehn** [comment]
@rubensworks In the case of the json-ld playground, "http://schema.org/" is handled as a special case and rewritten to https so that issue won't be seen there.

**Comment by danbri** [comment]
I think we're done here for now. We can continue to track the issue as it affects JSON-LD client libraries/applications but I think things are fixed on the Schema.org side now.

**Comment by rubensworks** [comment]
@danbri the [missing CORS headers](https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-638673155) on the http->https redirect appear to still be a problem.
This causes several tools on our end to break when schema.org contexts are loaded.
For example: https://rdf-play.rubensworks.net/#url=https%3A%2F%2Fpietercolpaert.be%2F

As @davidlehn has mentioned, a fix could be hacked into these tools, but requiring all (client-side) tools to implement a schema.org workaround does not seem like a scalable solution to me.

**Comment by RichardWallis** [comment]
The inability to define output headers for the http->https redirect is a function of the hosting environment for the site.  When running in static mode we depend on its inbuilt (redirect to https) functionality and that does not appear to have that capability.

I have raised [an issue](https://issuetracker.google.com/issues/160257643) with the providers.

**Comment by rubensworks** [comment]
@RichardWallis Is there any way we could help resolving this issue?

A number of people seem to be running into this problem lately. The way this problem is being solved is by hardcoding the `@context` as `https://schema.org/docs/jsonldcontext.jsonld`, which is not ideal, as this may break these tools in the future should the context location change.

**Comment by danbri** [comment]
@rubensworks rather than hardcode, could you update @ context references to use https:// and then parse with the newer JSON-LD header-reading rules? I know it is not ideal, but moving towards https: as canonical is healthy anyway. We can also look into the server-side options but it would quite likely mean moving the whole thing to a different serving platform.

**Comment by rubensworks** [comment]
> rather than hardcode, could you update @ context references to use https:// 

This seems like a good suggestion for data publishers.
Problem here is that many people are still using the http-based context, as was recommended in the past, which makes this (unfortunately) a breaking change.

> parse with the newer JSON-LD header-reading rules?

Yes, our tools already do this, according to the JSON-LD 1.1 spec.

In the meantime, I'll look into handling schema.org contexts as a special case in our tools as a temporary workaround as suggested in https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-638957220.

**Comment by pietercolpaert** [comment]
Content negotiation is broken again - can we reopen this issue?

**Comment by pietercolpaert** [comment]
Seems like there’s a discovery mechanism of JSON-LD 1.1 in place now:
```
$ curl -I https://schema.org/
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-headers: Accept
access-control-allow-methods: GET
access-control-allow-origin: *
access-control-expose-headers: Link
link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"
date: Mon, 15 Feb 2021 13:54:49 GMT
expires: Mon, 15 Feb 2021 14:04:49 GMT
etag: "v7F5aA"
x-cloud-trace-context: dd16f85b9ce4ab00811a02c231c2c860
content-type: text/html
server: Google Frontend
content-length: 5334
age: 181
cache-control: public, max-age=600
alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

**Comment by RichardWallis** [comment]
@pietercolpaert Yes, that is the supported linking route to the JSON-LD context document.
Other forms of content negotiation are not supported.
If you need a full dump of the current vocabulary checkout: https://schema.org/docs/developers.html#defs
