### ISSUE TITLE
Image URL and SVG

### ISSUE THREAD

**Issue by johnsamuelwrites** [schemaorg/schemaorg#2580]
Taking a look at the Schema.org https://schema.org/image, there is no restriction on the image format. However Google Structured Data testing tool https://search.google.com/structured-data/testing-tool returns an error saying that the URL is invalid for SVG images. See the screenshot below.

![image](https://user-images.githubusercontent.com/8275121/82669190-49009580-9c3b-11ea-8aa7-bc533ac612fe.png)

However, if I change the SVG format to PNG, it works. Check the screenshot below

![image](https://user-images.githubusercontent.com/8275121/82669443-bd3b3900-9c3b-11ea-8bbd-5b1c3ea16040.png)

I am wondering this is a problem related to Google Structured Data testing tool or whether schema.org has a list of allowed formats.

**Comment by jvandriel** [comment]
The limitation of not accepting SVG files is solely a limitation by Google. schema.org itself doesn't have a list of allowed file types. So you'll have to take this issue to [their forum](https://support.google.com/webmasters/threads?hl=en&thread_filter=(category:structured_data)).

**Comment by jeannieh** [comment]
Hi John Samuel and Jarno van Driel,


It is interesting that Google accepts the SVG image format for ClaimReview,
but not other types, in my experience.

Jeannie Hill
Hill Web Creations
Digital Marketing, Google Analytics, PPC & SEO Consultant | When you're
serious about marketing, you employ winning strategies.
Office  651.460.2496 <(651)%20460-2496> |Cell  651.206.2410
<(651)%20206-2410>
jeannie@hillwebcreations.com | Hill Web Creations on LinkedIn
<http://www.linkedin.com/profile/view?id=22161273&authType=name&authToken=NBrD&invAcpt=218672614_I176303754_215&trk=eml-comm_invm-b-profile-newinvite&fromEmail=&ut=2B3u0P9-t-NRQ1>
 | Hill Web Creations <http://www.hillwebcreations.com/>

**Comment by johnsamuelwrites** [comment]
Thanks @jvandriel  and @jeannieh for  your replies. 

For reference, I have posted an issue here: https://support.google.com/webmasters/thread/50085133

**Comment by danbri** [comment]
Thanks all - indeed this is a Google product question, let's close this issue here.
