### ISSUE TITLE
Review schema.org performance

### ISSUE THREAD

**Issue by ldexterldesign** [schemaorg/schemaorg#2585]
<img width="1792" alt="Screenshot 2020-05-28 at 02 43 58" src="https://user-images.githubusercontent.com/1715809/83086244-7fe90800-a08e-11ea-8c7c-e94c60c5060d.png">

<img width="1792" alt="Screenshot 2020-05-28 at 02 43 47" src="https://user-images.githubusercontent.com/1715809/83086247-824b6200-a08e-11ea-918d-ca1577a68b1c.png">

Is it just me?

[TTFB] is bad. Is the website zipped and CPU not up to it by chance?

Disclaimer: client, not server, type person 🤫

Sincerely

[ttfb]: https://en.wikipedia.org/wiki/Time_to_first_byte#TTFB_vs_load_time

**Comment by RichardWallis** [comment]
@ldexterldesign thanks for the heads up, its not just you.

We are aware of some current performance issues with the Schema.org site.  It is running in a slightly downgraded mode following being hit with a substantial DOS attack a few days ago.

We are expecting to apply some upgrades very soon which should substantially improve both robustness and performance.

**Comment by RichardWallis** [comment]
We have just made live a new version of the webschemas.org & schema.org sites based upon 100% static files.  They should be more robust and performant.

Let us know if you discover anything we have missed.

**Comment by ldexterldesign** [comment]
Wow, much faster - thanks

Care to divulge your new stack?

Sincerely

**Comment by RichardWallis** [comment]
https://cloud.google.com/appengine/docs/standard/python/getting-started/hosting-a-static-website
