### ISSUE TITLE
Multiple SoftwareApplication URLs and operating systems

### ISSUE THREAD

**Issue by ePirat** [schemaorg/schemaorg#2586]
I'm a bit confused how SoftwareApplication is supposed to be used, as the documentation is a bit lacking there. Is it expected that one SoftwareApplication property is used per version and operating system that the application is available on? It seems like that way I would duplicate quite a bit of common data in each one or is there a way around this?
If thats not how it's supposed to be done, how would I properly specify multiple versions, download URLs and operating systems for a SoftwareApplication?

I tried:

```
  "downloadURL" : [
    "https://example.org/installer_win32.exe",
    "https://example.org/installer_mac.pkg"
  ],
  "operatingSystem" : [
    "Windows 7",
    "Linux"
  ],
```

which is accepted by the validator but it does not seem that useful as there is no way to tell which URL belongs to which operating system?

**Comment by jvandriel** [comment]
Per version of the ```SoftwareApplication``` you indeed need to create an item. Based on your example you'd get something like this (could also be contained within an ```ItemList```):

```
[
  {
    "@type":"SoftwareApplication",
    "downloadURL":"https://example.org/installer_win32.exe",
    "operatingSystem":"Windows 7"
  },
  {
    "@type":"SoftwareApplication",
    "downloadURL":"https://example.org/installer_mac.pkg",
    "operatingSystem":"macOS"
  },
  {
    "@type":"SoftwareApplication",
    "downloadURL":"https://example.org/installer_linux.rpm",
    "operatingSystem":"Linux"
  }
]
```

**Comment by RichardWallis** [comment]
I think we can close this now.
