### ISSUE TITLE
Proposal to add StudentPaper and subtypes to CreativeWork

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#259]
http://schema.org/CreativeWork

A [proposal](http://lists.w3.org/Archives/Public/public-vocabs/2015Jan/0080.html) to add several subtypes of CreativeWork for StudentPapers

## Motivation

There are many sites for search and download of essays and other student papers (http://www.echeat.com/, http://www.essayzone.com/, etc).

## Proposal 

New types could be used for it. It could be Thing->CreativeWork->StudentPaper with some new properties:

* fileType (text) - format of file (doc, pdf, TeX, etc.).
* fileSize(Number) - size of file with this paper
* usedIn (text) - information about university or school where this paper was used

### subtypes of StudentPaper 

Could be several subtypes for different kind of student papers.
 
Thing->CreativeWork->StudentPaper->Dissertation

A document submitted in support of candidature for an academic degree or professional qualification presenting the author's research and findings

Thing->CreativeWork->StudentPaper->Coursework

Coursework is work performed by students or trainees for the purpose of learning.

Thing->CreativeWork->StudentPaper->StudentEssay

Essays are generally scholarly pieces of writing giving the author's own argument, but the definition is vague, overlapping with those of an article, a pamphlet and a short story.

Thing->CreativeWork->StudentPaper->BookReport

A book report is an assignment issued to students in schools to read a book and write about that book

Thing->CreativeWork->StudentPaper->StudentReport

A book report is an assignment issued to students in schools to find information about something and write about it.

Thing->CreativeWork->StudentPaper->Examination

Examinations is an assessment intended to measure a test-taker's knowledge, skill, aptitude, physical fitness, or classification in many other topics (e.g., beliefs).

Thing->CreativeWork->StudentPaper->Student PracticalWork

Student practical work is a text report about some work making by student

**Comment by danbri** [comment]
Questions from public vocabs:

* subtype ScholarlyArticle instead?
* relationship to the existing LRMI properties in schema.org

**Comment by thadguidry** [comment]
There are lots of kinds of Papers / Articles...why not use Enums or classifier property under CreativeWork ?  "Paper", "Essay", "Report", "Dissertation", "Coursework/Homework", "Exam"...

Many Papers will have the need for format of file, size, usedIn.

**Comment by tilid** [comment]
I don't think that subtype of ScholarlyArticle is a good idea. In my mind StudentPaper is slightly wider than ScholarlyArticle . 
About relationship to the existing LRMI properties in schema.org. I think we can make StudentPaper  subtype of CreativeWork and place specific type of student paper in learningResourceType property from LRMI. Then it's need not make so many subtypes of StudenPaper

**Comment by tilid** [comment]
Hi
After some letter from public-vocab I think we should close this task. The reason why I think so is that the most of potential users is cheating sites and I agree with those of you who told me that it is not very ethical to make special markup for them
