### ISSUE TITLE
Multi-line Text?

### ISSUE THREAD

**Issue by dandv** [schemaorg/schemaorg#2591]
Is Text consisting of multiple lines supported? If so, what is the line separator? `\n`, I assume?

May help to specify these at https://schema.org/Text .

**Comment by chrisspradling1980** [comment]
<br> I believe

**Comment by vholland** [comment]
Support depends on the reader of the data. The separator depends on whether the markup uses JSON-LD, microdata, or RDFa.

If you have a specific feature or product in mind, you are better asking this question on those product forums.

**Comment by dandv** [comment]
Wow thanks for the help

**Comment by akuckartz** [comment]
This is underspecified.
