### ISSUE TITLE
https://schema.org/docs/schema_org_rdfa.html 404s

### ISSUE THREAD

**Issue by mr-c** [schemaorg/schemaorg#2593]

**Comment by RichardWallis** [comment]
This is a consequence of some recent internal reengineering.
Did you follow a link to this file - if so can you tell where from.
Or have you previously used it - if so what is your use case.
~Richard

**Comment by mr-c** [comment]
Hello @RichardWallis 

That URL (or the http version of it) was part of the recommended manner of using schema.org annotations in Common Workflow Languages files: https://github.com/search?l=Common+Workflow+Language&q=schema_org_rdfa.html&type=Code (1,454 results)

Now we recommend `https://schema.org/version/latest/schema.rdf`

FYI https://schema.org/version/8.0/ and similar (as linked to from https://schema.org/docs/releases.html ) also 404 now

**Comment by RichardWallis** [comment]
Thanks for the input @mr-c 

I would recommend ```https://schema.org/version/latest/all-layers.rdf``` as it contains definitions for all schema.org terms, not just those in the core vocabulary.

I have raised an issue (#2594) for the 404 from https://schema.org/version/8.0/ , currently https://schema.org/version/8.0 works OK.

**Comment by stain** [comment]
The top of release documents like https://schema.org/version/8.0 also links to "rdfa" like <http://schema.org/docs/schema_org_rdfa.html> so I expect loads of these links to it around the world.

**Comment by mr-c** [comment]
Thank you @RichardWallis , can you make the advice about which RDF file to link to explicit at https://schema.org/docs/developers.html ?

**Comment by mr-c** [comment]
For parsing speed, I think we will continue to recommend https://schema.org/version/latest/schema.rdf as the default ; users are welcome to use the expanded `all-layers.rdf` if needed

**Comment by stain** [comment]
Perhaps add links to the JSON-LD `@context` to <https://schema.org/docs/developers.html> now that the `@context` no longer points to the JSON-LD context.

**Comment by safo-bart** [comment]
Hi guys, I am maintaining one drupal page and it is using easyrdf PHP library. Now, some parts of the page are not working because removed subpage from schema.org. I think it influences more libraries :) Can you please return back subpage /docs/schema_org_rdfa.html  ? thank you :)

`Doctrine\Common\Proxy\Exception\InvalidArgumentException: Invalid uri + EasyRdf_Http_Exception: HTTP request for https://schema.org/docs/schema_org_rdfa.html failed: Not Found`

**Comment by stain** [comment]
http://schema.org/docs/schema_org_rdfa.html also referenced from https://schema.org/version/7.04/ and many other places, so I think it needs to be reinstated.

**Comment by danbri** [comment]
the page at the other end of the URL encoded the canonical ground truth of schema.org in triples; I don't think we committed to the URL or the file format in perpetuity. But it would be good to redirect the URL somewhere or put up a page explaining the situation...

**Comment by stain** [comment]
Perhaps redirect it to the last known RDFa version which can have a HTML banner on it. I don't suggest moving back to editing RDFa as the Turtle is so much easier!

**Comment by danbri** [comment]
@stain it looks like the links in the datestamped releases should be pointing to schema.rdfa in the same directory, and not to the non-datestamped URL under discussion here. For example, https://schema.org/version/7.04/schema.rdfa /cc @RichardWallis

**Comment by RichardWallis** [comment]
@danbri 
We have a few options here:

1.  Do nothing and accept this as a, now, historical anomaly.
2. Go through all the old releases and manually correct the link to be version specific.
3. As @stain suggests, redirect to the last known version, with added explanatory html banner added.
4. As schema.rdfa is no longer (post V8.0) shipped; put a holding document in its place describing how to find the historical versions and how to obtain other data dumps (eg. schema.ttl, all-layers.ttl) as a replacement.

(_my preference is for option 4._)

**Comment by danbri** [comment]
Yes, (4.) makes sense. We should guide people away from the RDFa. It is almost always *not* what people need.

It would be good to make sure the Github release tags are all in place too, so we can link to them (or even use Github Releases machinery) from docs/releases.html

**Comment by RichardWallis** [comment]
@danbri 
OK I'll create a PR to do 4.
On the releases stuff I'll do a bit of digging that will hopefully lead to another PR.

**Comment by RichardWallis** [comment]
Fixed by issue #2656

**Comment by lutsik** [comment]
Sorry for a potentially inappropriate place to ask this, but can it be that https://schema.org/version/latest/schema.rdf is again broken? CWL workflows using it seem to have lots of problems.

**Comment by RichardWallis** [comment]
Hi Pavlo,

The *schema.rdf* file you reference has not been part of the Schema.org
release since the version 9.0 <https://schema.org/docs/releases.html#v9.0>
release in July 2020, when the rationalisation of dump files
<https://schema.org/docs/releases.html#v9.0> took place.

~Richard.
