### ISSUE TITLE
Link to https://schema.org/version/8.0/ - 404s

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2594]
Since move to static pages.

https://schema.org/version/8.0 does not 404

**Comment by stain** [comment]
This means all the links from https://schema.org/docs/releases.html are 404. Slash vs non-slash?

**Comment by RichardWallis** [comment]
Both https://schema.org/version/8.0 & https://schema.org/version/8.0/ should work.

Working on a fix

**Comment by RichardWallis** [comment]
Fixed in commit e2683d58c9d9f3625751b8bfc8b3eec9af569c3b

**Comment by RichardWallis** [comment]
Fixed in deployment to schema.org 2020-06-03T12:00:00Z
