### ISSUE TITLE
Meta robots is preventing the site from being indexed by search engines

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#2598]
A quick sampling of pages on https://schema.org suggests that this has been added to the main site pages (i.e. property and type pages, but perhaps not all documentation pages):
`<meta name="robots" content="noindex">`

Per [Google's documentation](https://developers.google.com/search/reference/robots_meta_tag), this "instructs search engines not to show the page in search results." As per screenshots below, pages are starting to drop out of the search engines' indexes.

Solution is straightforward: remove the tag altogether (or change the value of `content` from "noindex" to "index"), and then resubmit the site's XML sitemap to ensure expeditious re-indexing of any URLs that may have disappeared.

![s1](https://user-images.githubusercontent.com/1033730/84162037-c6dae400-aa24-11ea-8d45-9bd5dcdacf75.jpg)
![s2](https://user-images.githubusercontent.com/1033730/84162060-cd695b80-aa24-11ea-80bb-3d1f83d4a9ab.jpg)

**Comment by RichardWallis** [comment]
Looks like an unintended consequence of moving to static pages - will investigate.

**Comment by RichardWallis** [comment]
Fix applied 2020-06-10.
Will require some time for crawlers to reindex things.
