### ISSUE TITLE
A previous emplyment property for Person type ?

### ISSUE THREAD

**Issue by HugoScott** [schemaorg/schemaorg#2601]
Hi

I'd like to make a suggestion for an addition to the Schema.

I'm doing some markup for a consultant whose major E-A-T credibility boost is the companies he has worked for but I can't find a decent way to include this data.

Ideally, what would be very cool would be to be able to use something like a "workedFor" property like this 

`"workedFor":[
    	{
	        "@type": "OrganizationRole",
	        "worksFor": {
	            "@type": "Organization",
	            "name": "Microsoft"
	        },
	        "roleName":"Assistant coffee maker",
	        "startDate": "1986",
	 	"endDate": "1996",
	 	"description":"This is the job description",
	        "responsibilities":"This and that"
    	},
	    	"@type": "OrganizationRole",
	        "worksFor": {
	            "@type": "Organization",
	            "name": "Apple"
	        },
	        "roleName":"Chief coffee maker",
	        "startDate": "1996",
	 	"endDate": "2006",
	 	"description":"This is the job description",
	        "responsibilities":"This and that"
    	}]`

the problem with this is that the Person has had three different scenarios 

- Employed as a regular employee
- Hired as a consultant by a company for their own business
- Hired as a subcontractor by a company to handle the business of a third party

Do you have any thoughts on this? Does it sound like a good suggestion?
Or would it be better to suggest something more open-ended like "hiredBy" with maybe a "hireType" property or something like that to specify the relationship?

Thanks

**Comment by RichardWallis** [comment]
Within the vocabulary as it currently is, I would suggest making use of the _name_ property.
```
"worksFor":[ 
  { 
      "@type": "OrganizationRole", 
      "name": "Consultancy Engagement",
      "worksFor": { 
         "@type": "Organization", 
         "name": "Microsoft" 
     }, 
     "roleName":"Assistant coffee maker", 
     "startDate": "1986", 
     "endDate": "1996", 
     "description":"This is the job description"
}, 
{
   "@type": "OrganizationRole", 
   "name": "Short term contract",
   "worksFor": { 
      "@type": "Organization", 
      "name": "Apple" 
    }, 
    "roleName":"Chief coffee maker", 
    "startDate": "1996", 
    "endDate": "2006", 
    "description":"This is the job description"
   } 
}
]
```

For more detailed and specific expansion you could propose an extension to the  _OrganizationRole_ type to see if it would gain any traction.

**Comment by HugoScott** [comment]
Hi Richard,

Thanks you for your reply.

That looks really good - maybe I could include a productontology "sameAs" to clarify the different relationships :
http://www.productontology.org/doc/Employment_contract
http://www.productontology.org/doc/Consultant
http://www.productontology.org/doc/Subcontractor

I'll have a think about possible expansions for the OrganizationRole, but this seems to be good

Thanks again
