### ISSUE TITLE
Reformat status type enumeration lists to be nested under StatusEnumeration

### ISSUE THREAD

**Issue by lucy-kind** [schemaorg/schemaorg#2604]
A nested structure for enumerations will be implemented to prevent a combinatorial explosion of enumerated items in any enumeration list.

New nested structure for status types will appear as such:

Enumeration:
- StatusEnumeration (new Schema.org object)
 
Contains the following Enumerated Items:
- ActionStatusType
-     ActiveActionStatus
-     CompletedActionStatus
-     FailedActionStatus
-     PotentialActionStatus
- EventStatusType
-     EventCancelled
-     EventMovedOnline
-     EventPostponed
-     EventRescheduled
-     EventScheduled
- GameServerStatus
-     OfflinePermanently
-     OfflineTemporarily
-     Online
-     OnlineFull
- LegalForceStatus
-     InForce
-     NotInForce
-     PartiallyInForce
- OrderStatus
-     OrderCancelled
-     OrderDelivered
-     OrderInTransit
-     OrderPaymentDue
-     OrderPickupAvailable
-     OrderProblem
-     OrderProcessing
-     OrderReturned
- PaymentStatusType
-     PaymentAutomaticallyApplied
-     PaymentComplete
-     PaymentDeclined
-     PaymentDue
-     PaymentPastDue
- ReservationStatusType
-     ReservationCancelled
-     ReservationConfirmed
-     ReservationHold
-     ReservationPending

**Comment by danbri** [comment]
This is queued to go out as part of version 9.0 (next week)
