### ISSUE TITLE
VideoObject example 1, should duration be PT1M33S instead of T1M33S?

### ISSUE THREAD

**Issue by JeandreDT** [schemaorg/schemaorg#2608]
https://schema.org/VideoObject
Lines 1253, 1312, and 1422:
Example 1's interview duration is "T1M33S". Should it not be "PT1M33S" because it's a period of time, rather than a specific time?

The rope duration looks correct: "PT4M5S".

**Comment by RichardWallis** [comment]
Fixed in commit c28517b03099050b8204aa629e14d37d847cb8a4 
Will appear in next release.
