### ISSUE TITLE
[more...] tab missing on static version

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2610]
Raised following [comment](https://github.com/schemaorg/schemaorg/issues/2516#issuecomment-648820337)  by @vberkel on issue #2516.

[more...] tab missing on Term pages.

**Comment by RichardWallis** [comment]
Fixed in commit 2628610e37b95fbe80d99a0b15f281cd193f0be8

Will appear in next deploy.

**Comment by danbri** [comment]
Thanks!
