### ISSUE TITLE
Can not find how to retrieve schema ?

### ISSUE THREAD

**Issue by redradist** [schemaorg/schemaorg#2615]
Can not find how to retrieve schema for example for https://schema.org/SportsEvent to verify data structure ?

I have tried to find examples in `Python` or `JavaScript`, but have not found ... (
I have found this example, but cannot figure out how to get specification for https://schema.org/SportsEvent from schema.org ... ?

Any help will be appreciated ...

**Comment by danbri** [comment]
http://schema.org/docs/developers.html
