### ISSUE TITLE
Add vocabulary for describing vehicles / automobiles / automotive

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#262]
http://schema.org/Car
http://schema.org/Vehicle

A substantial and detailed proposal has been prepared by Martin Hepp, see associated pull request: https://github.com/schemaorg/schemaorg/pull/80

Announcement / discussion: http://lists.w3.org/Archives/Public/public-vocabs/2014Dec/0057.html

Original W3C wiki link https://www.w3.org/wiki/WebSchemas/Vehicles

See [2015-01-09 review](https://lists.w3.org/Archives/Public/public-vocabs/2015Jan/0002.html) from @tmarshbing which suggests amongst other things partitioning the proposal into smaller sections.

See also #263 for the property-value proposal, which supports the proposal.

**Comment by mfhepp** [comment]
I have just created a pull request 

    https://github.com/schemaorg/schemaorg/pull/379

that is a trimmed-down version of the automotive part of the original proposal and addresses the comments received in the meantime.

**Comment by mfhepp** [comment]
Note that we need https://github.com/schemaorg/schemaorg/issues/263 (Property-Values) for this proposal to be consistent, because the unitText property is referenced but not contained in this pull request.

**Comment by danbri** [comment]
http://www.fileformat.info/info/unicode/char/1f697/automobile.svg

**Comment by mfhepp** [comment]
Is the logo for the respective blogpost ;-) ?

**Comment by danbri** [comment]
This is partially queued up for sdo-gozer and partially coming later as an extension. I'll therefore leave the issue open and update the milestone.

See http://sdo-gozer.appspot.com/docs/releases.html#automotive

**Comment by danbri** [comment]
Q: I see "Typical unit code(s): C62" in several definitions but don't understand this. Searching around it seems to be in the original OWL ontology from @mfhepp too, so I don't think I introduced it in error.

**Comment by mfhepp** [comment]
C62 is the correct un/cefact common code for "piece" or "no unit".

martin

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by danbri** [comment]
I thought you were up a mountain!

We made some last minute tweaks but http://schema.org/Car is live. Can you take a quick look? The tweaks were all in the direction discussed previously, i.e. avoiding "using up" generic terms for vehicle-specific concepts. Mostly the changes were to names to indicate the vehicle scope, although in a couple of places they're slightly broadened (to Product). See https://github.com/schemaorg/schemaorg/commit/f1eaf070efcabe10669afcb74604c8070bfee9ae for a summary.

**Comment by jvandriel** [comment]
_"I thought you were up a mountain!"_

Can't we leave the man one week alone?   ;)

**Comment by mfhepp** [comment]
If this is not considered too specific a topic, it could be added to the FAQs - what do you think?

**Comment by danbri** [comment]
We have a fairly weak high-level overview of all our vocabulary at http://schema.org/docs/schemas.html (and linked from navigation toolbar on each page). I'd suggest updating that would be more useful.

Re FAQ I am also thinking to create a "technical FAQ" with some details in, e.g. url/URL,sameAs, mainEntity...

**Comment by mfhepp** [comment]
I think we should close this issue and continue work on the automotive extension part as https://github.com/schemaorg/schemaorg/issues/509

**Comment by danbri** [comment]
Agreed. -> #509
