### ISSUE TITLE
bad example: DigitalDocumentPermissionType -> DigitalDocumentPermission

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#2631]
The JSON-LD example here: https://schema.org/DigitalDocument

generates the following error on GSDTT:
DigitalDocumentPermissionType is not a known valid target type for the hasDigitalDocumentPermission property.

warning: permissionType
http://schema.org/WritePermission (The property permissionType is not recognized by Google for an object of type DigitalDocumentPermissionType.)

warning: grantee
The property grantee is not recognized by Google for an object of type DigitalDocumentPermissionType.

**Comment by danbri** [comment]
This may be more a problem on the Google side, but it deserves investigation - thanks!

**Comment by jaygray0919** [comment]
@danbri As you know SDTT is being deprecated in favor of RRT. We have run SDTT-valid scripts thru RRT and they fail. But also, per your comment, there is valid schema.org JSON-LD that is not valid in the Google tools. To learn that, a *very* close read of Google documentation is necessary. There are cases where an array is schema.org-valid but invalid on Google testing tools. One can deal with "warnings" where there is a different implementation of `domainIncludes` or `rangeIncludes`, but errors call out the occasional disconnect between the two platforms. We're hoping that new energy around RRT may work to resolve some of the differences, in case you get involved with RRT ...
/jay

**Comment by danbri** [comment]
It's just a bad example within schema.org. Changing "DigitalDocumentPermissionType" to "DigitalDocumentPermission" seems to fix it:

```
{
  "@context": "https://schema.org",
  "@type": "DigitalDocument",
  "name": "New schema.org types proposal",
  "author": "Alice",
  "hasDigitalDocumentPermission": [
    {
      "@type": "DigitalDocumentPermission",
      "permissionType": "http://schema.org/WritePermission",
      "grantee": {
        "@type": "Person",
        "email": "alice@example.com"
      }
    },
    {
      "@type": "DigitalDocumentPermission",
      "permissionType": "http://schema.org/ReadPermission",
      "grantee": {
        "@type": "Audience",
        "audienceType": "public"
      }
    }
  ]
}
</script><title></title></head><body></body></html>
```

**Comment by danbri** [comment]
p.s. @jaygray0919 on the Google tooling front, I hear you
