### ISSUE TITLE
Add eduQuestionType property to Question

### ISSUE THREAD

**Issue by lucy-kind** [schemaorg/schemaorg#2636]
The type PracticeProblem will have the parent type Quiz. It will take these new property of problemType:

PracticeProblem; Subtype of Quiz: An interactive problem.
problemType; Property of PracticeProblem: The format of practice problem being given. Example: "Multiple choice", "Open ended", "Flashcard". Takes Text as value.

EDIT: per community feedback below, this functionality will be covered by adding eduQuestionType (previously problemType) to the existing Question type. Usage can further be specified by using the existing property of learningResourceType under Question, which will take the Text value of "Practice problem".

**Comment by jmarks** [comment]
How is Quiz different than an Assessment, and how is PracticeProblem
different than an Assessment Item? All are learning resources which can
assess defined skills through the Alignment Object. Let's not be short
sighted and think of a Quiz as only part of a course and not just another
class of an Assessment learning resource type.

**Comment by philbarker** [comment]
Is a PracticeProblem a single question? Because a quiz is a set of questions, so a single problem cannot be a subtype of a set. Questions and Tests both fall under the assessment domain, but just as ListItem is not a subtype of ItemList, question is not a subtype of Test. If you want to do Assessments, you will need Assessment as a supertype.

@jmarks : the difference is, of course, that all Quizzes are Assessments, not all Assessments are Quizzes.

**Comment by lucy-kind** [comment]
Hi Phil and Joshua, we've been reflecting on it and you do make very valid points; therefore it does seem like we can simplify this schema.

As you pointed out, Phil, a quiz is a set of questions, but a set can be 1 or more questions. Therefore a quiz with one question is still a quiz. 

Per your insights and suggestions, we've refactored to remove the new type of PracticeProblem; instead, we will use Question, with a new property called eduQuestionType (previously problemType) that takes Text as a value. The resulting schema is Quiz type with a property hasPart: Question, with the potential for 1 to n questions in the quiz.

**Comment by jmarks** [comment]
Nice!

**Comment by philbarker** [comment]
Thanks @lucy-kind, that sounds right.
