### ISSUE TITLE
Properties/Values for color blindness

### ISSUE THREAD

**Issue by westurner** [schemaorg/schemaorg#2644]
How should resource accessibility information in regards to colorblindness be expressed given existing or new schema.org properties and property values?

(Spurned by a suggestion to add color vision deficiency metadata to Matplotlib colormaps: 
https://github.com/matplotlib/matplotlib/issues/17893 )

https://en.wikipedia.org/wiki/Color_blindness

**Comment by earthrefresh** [comment]
To clarify, is the suggestion for the inclusion of properties that inform whether or not a specific resource has colorblind-friendly options, e.g. hasColorblindMode or something similar?

**Comment by westurner** [comment]
I suppose we could regard whether a resource passed color-blindness accessibility tests as an accessibilityFeature?

https://schema.org/accessibilityFeature links to https://www.w3.org/wiki/WebSchemas/Accessibility , which lists a few possible text values.

Why are hardly-normalized text values preferred over URIs? Would Enumerations be the more current approach?
