### ISSUE TITLE
New property suggestions: copyrightNotice and creditLine

### ISSUE THREAD

**Issue by bquinn** [schemaorg/schemaorg#2659]
We at [IPTC](https://iptc.org/) are working with the schema.org team to create a definitive mapping between [IPTC embedded photo metadata fields](https://iptc.org/standards/photo-metadata/) and their equivalent schema.org properties.

Out of that work has come a couple of suggestions for new properties which aren't covered exactly in the current schema, and suggestions for clarifications.

* New property on CreativeWork: https://schemaorg/copyrightNotice
Description: Contains any necessary copyright notice for asserting the intellectual property for this Creative Work and should identify the current owner of the copyright for the Work.
rdf:type: https://schema.org/Text

* New property on CreativeWork: named either https://schema.org/creditLine or https://schema.org/creditText
Description: The credit to person(s) and/or organization(s) which is required be used when the Creative Work is published.
rdf:type: https://schema.org/Text

We also have some requests for clarifications in the docs:
* Make it clear when to use “author” and when to use “creator”. Currently the definitions seem to overlap. Can we make it clear when each property should be used?

* Make it clear when to use “description” vs "abstract" and “caption”. Currently ImageObject defines caption but also has description which is inherited from Thing, plus abstract inherited from CreativeWork.

**Comment by danbri** [comment]
Thanks @bquinn - this looks fairly straightforward

On "author" / "creator", I think they are effectively synonyms except that it is conventional to use the word "creator" for media objects and "author" for primarily textual creations. We can clarify this. Dublin Core started out with "author" and moved to "creator" after a workshop on images, I believe.

**Comment by WeaverStever** [comment]
The Type would also be important here, not only for still photographs, but for all creative works.

1. Creative Commons types supported?
2. Is Fair Use encouraged? (news clips, video snippets, etc)
3. In music, it is very difficult to determine if it is okay for independent artists to cover songs in music videos.  On YouTube the "Sync" are presumed unless the owner flags the video.  It would be very good to know if sync rights are denied before expending the effort to cover and produce the song / offering.

**Comment by bquinn** [comment]
Thanks for your comment @WeaverStever.

Creative Commons licences can already be specified using the http://schema.org/license property on CreativeWork - see https://developers.google.com/search/docs/data-types/image-license-metadata#structured-data for more info on how Google will soon use that info to display some licence information on search results pages for images.

For a Creative Commons work, the copyrightNotice property could contain something like "Copyright 2020 Barbara Smith. Some Rights Reserved" (see https://creativecommons.org/faq/#what-does-some-rights-reserved-mean), or "Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International license."

Regarding your second point, I don't think the copyright owner asserting whether fair use is encouraged or not changes the legal status of the work or of any derived work. Do you have an example where this is used in practice?

Re your third point, schema.org has recently introduced a new property on CreativeWork, https://schema.org/acquireLicensePage, which was intended to be used for requesting image reuse licences but happily it should also work well for the case of requesting a synchronisation licence for a piece of music. For musicians that refuse sync licences, they could put a message on their acquireLicensePage that says so. Otherwise this URL could point to the creator's instructions for how to obtain a sync licence.

**Comment by WeaverStever** [comment]
@bquinn
Thanks for the link to acquireLicensePage. I'm seeing that  https://schema.org/usageInfo seems related.

My point is that there are two perspectives to consider, one is the from the organization asserting the copyright/conditions, the other is from the consumer complying with those conditions.

As for my second point, content experts may borrow a clip from a mainstream news outlet and create a derived creative work.  Regardless to the law, YouTube and Facebook will take down the new work if any DMCA claim is made against it -- bogus or not.  If the original work has Fair Use and terms declared,  the platform can be assured that the copyright claim is not authentic and move on.

Another issue comes to mind, photographers will often license their work to a media outlet; however, that license will often have a begin and end date.

**Comment by bquinn** [comment]
Hi @danbri, is there anything else you need from us before finalising this?

We are happy with `creditText` if you're worried about misinterpretation of `creditLine`.

**Comment by zeroexp** [comment]
Hi @danbri  -- just wanting to ask if there are any additional decisions finalized here :-) Assuming that @bquinn is correct on the schema:copyrightNotice for the matching iptc field...and also, had you thought more about CreditText or CreditLine for addtional credit(s) from the iptc:creditLine?

**Comment by danbri** [comment]
let's go with `creditText` rather than `creditLine` then.

I'll draft up something for v11.0 and we can work through the details.

As for `author` vs `creator`, Dublin Core ended up using `creator` after considering images, I believe.

We have both, we say they are equivalent in English - do we want to go further and say that for any x and y related by `author` they are also related by `creator` (and vice-versa), i.e. implying e.g. that images and other non-textual creative works are `author`ed?
