### ISSUE TITLE
Orders schema updates

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#266]
http://schema.org/Order

Wiki proposal: https://www.w3.org/wiki/WebSchemas/Orders_enhancement

**Comment by vholland** [comment]
See pull request https://github.com/schemaorg/schemaorg/pull/325/files

**Comment by tmarshbing** [comment]
For orderItemId, should we rename that to orderItemNumber to be consistent with http://schema.org/orderNumber?

How can you tell the product ordered for a given OrderItem? I see the property from Order -> orderedItem -> OrderItem, but I think we should also add OrderItem to the domain of orderedItem. Which then introduces the possibility of a loop. If we're worried about the loop, we could always separate out orderedItem (range Product) from a new property orderLine (range OrderItem, which could then be renamed to OrderLine).

**Comment by realworldobject** [comment]
Or perhaps:

schema:id
    a rdf:Property;
    schema:domainIncludes schema:Thing;
    schema:rangeIncludes schema:Text .



On Mar 10, 2015, at 7:45 PM, tmarshbing <notifications@github.com<mailto:notifications@github.com>> wrote:


For orderItemId, should we rename that to orderItemNumber to be consistent with http://schema.org/orderNumber?

How can you tell the product ordered for a given OrderItem? I see the property from Order -> orderedItem -> OrderItem, but I think we should also add OrderItem to the domain of orderedItem. Which then introduces the possibility of a loop. If we're worried about the loop, we could always separate out orderedItem (range Product) from a new property orderLine (range OrderItem, which could then be renamed to OrderLine).

-

**Comment by vholland** [comment]
I updated [the pull request](https://github.com/schemaorg/schemaorg/pull/325/files) to add orderedItem to the list of properties. This allows one to link directly from the OrderItem to the Product.

I also added an example of this.

**Comment by tmarshbing** [comment]
Looks good!

**Comment by chaals** [comment]
Looks OK to me.

**Comment by vholland** [comment]
Merged into sdo-gozer.
