### ISSUE TITLE
Error in - Government Service Example 4 

### ISSUE THREAD

**Issue by krishna-pearl** [schemaorg/schemaorg#2661]
https://schema.org/GovernmentService#GovernmentService-gen-623

**Current Schema**

`<script type='application/ld+json'>
{
  "@context": "http://schema.org",
  "@type": "GovernmentService",
  "name": "Veterans Affairs Emergency Mental Health",
  "serviceType": "Psychiatric Emergency Services",
  "serviceOperator": {
    "@type": "GovernmentOrganization",
    "name": "US Department of Veterans Affairs"
  },
  "areaServed": {
    "@type": "AdministrativeArea",
    "name": "Massachusetts"
  },
  "audience": {
    "@type": "Audience",
    "name": "Veterans"
  },
  "availableChannel": {
    "@type": "ServiceChannel",
    "name": "Urgent Care Clinic",
    "availableLanguage": {
      "@type": "Language",
      "name": "Spanish",
      "alternateName": "es"
    },
    "serviceLocation": {
      "@type": "Hospital",
      "name": "VA Boston -- West Roxbury",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "1400 VFW Parkway",
        "addressLocality": "West Roxbury",
        "addressRegion": "MA",
        "postalCode": "02132"
      }
    }
  }
}
</script>`

**Updated Fix**

`
<script type='application/ld+json'>
{
  "@context": "http://schema.org",
  "@type": "GovernmentService",
  "name": "Veterans Affairs Emergency Mental Health",
  "serviceType": "Psychiatric Emergency Services",
  "serviceOperator": {
    "@type": "GovernmentOrganization",
    "name": "US Department of Veterans Affairs"
  },
  "areaServed": {
    "@type": "AdministrativeArea",
    "name": "Massachusetts"
  },
  "audience": {
    "@type": "Audience",
    "name": "Veterans"
  },
  "availableChannel": {
    "@type": "ServiceChannel",
    "name": "Urgent Care Clinic",
    "availableLanguage": {
      "@type": "Language",
      "name": "Spanish",
      "alternateName": "es"
    },
    "serviceLocation": {
      "@type": "Hospital",
      "name": "VA Boston -- West Roxbury",
      "image": "example.com/img1",
      "telephone":"0123456789",
      "priceRange":"100$-999$",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "1400 VFW Parkway",
        "addressLocality": "West Roxbury",
        "addressRegion": "MA",
        "postalCode": "02132"
      }
    }
  }
}
</script>
`

**Comment by RichardWallis** [comment]
@krishna-pearl can you clarify what error you are fixing?

**Comment by krishna-pearl** [comment]
I find missing information in This Schema code

**Comment by RichardWallis** [comment]
@krishna-pearl missing based upon what?

**Comment by krishna-pearl** [comment]
Example 4 Removed From The Website Now
