### ISSUE TITLE
Add explanation property to Answer

### ISSUE THREAD

**Issue by lucy-kind** [schemaorg/schemaorg#2665]
Create new property of explanation for Answer type.

Description: A step-by-step or full explanation about Answer. Can outline how this Answer was achieved or contain more broad clarification or statement about it.

Takes Comment/WebContent as value.

**Comment by danbri** [comment]
ping @rvguha on the naming

I am totally sold on having a property that does this (useful for Q/A and Quiz application areas), but the word "explanation" is very general. Should we consider something verbose like /answerExplanation ?

**Comment by danbri** [comment]
From email:

> Guha> I would prefer the more specific term.
