### ISSUE TITLE
'master' branch renamed 'main'

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2668]
If you see this message, read on: 

```
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

The branch previously known as **master** [i.e. default] in the schemaorg repo has been renamed **main**.

For everyone collaborating solely through the website, this should not really affect you. If you are using git tools to manage a local copy of our repository, you will need to take a minute to update your copy to match.

This process involves:

- Creating new branch _main_ as a copy of _master_
- Making that branch the default for the repository
- Rebasing all PRs to be based on _main_
- adding documentation for developers to understand what to do on their systems

For details see file:  https://github.com/schemaorg/schemaorg/blob/main/MASTER_BRANCH_RENAME.md

**Comment by RichardWallis** [comment]
Done

**Comment by danbri** [comment]
Thanks @RichardWallis! I've [announced it on Twitter](https://twitter.com/danbri/status/1286290808220639233). See also https://github.com/github/renaming for how to do this on other repos, and for background on this renaming.
