### ISSUE TITLE
Multiple output formats/content negotiation is unavailable

### ISSUE THREAD

**Issue by alexkreidler** [schemaorg/schemaorg#2674]
#1351 added the ability to go to any schema.org URL, append the format you wanted, and get that response. It also enabled specifying the format via the `Accept` header.

I had remembered testing this on the production `schema.org` site and having it work a few months ago

As of today I get a 404 error both when adding the extension or using the Accept header, on both `schema.org` and `webschemas.org`.

![image](https://user-images.githubusercontent.com/11166947/88494849-cae7a480-cf85-11ea-8052-d32a4569fa36.png)
```http
http GET https://schema.org/Book.jsonld Accept:application/ld+json -v
GET /Book.jsonld HTTP/1.1
Accept: application/ld+json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: schema.org
User-Agent: HTTPie/1.0.3

HTTP/1.1 404 Not Found
Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 288
Content-Type: text/html; charset=UTF-8
Date: Mon, 27 Jul 2020 01:20:50 GMT
Server: Google Frontend
X-Cloud-Trace-Context: 92b53aa3b11269bca4beff250b695285;o=1

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Not Found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Not Found</h1>
<h2>The requested URL <code>/Book.jsonld</code> was not found on this server.</h2>
<h2></h2>
</body></html>
```

However when requesting `https://schema.org/Book` without `.jsonld`, even with the `Accept` header, it simply returned the HTML page content.

It may just be something weird on my end, but if anyone else could test as well that'd be great.

This feature truly realizes the goals of Linked Data. It seems like we lose a lot of functionality if we lose this feature.

Also relevant: #1355

**Comment by alexkreidler** [comment]
Well apparently this was
1. an intentional change
2. because of a Denial of Service attack which caused the site to be down

Which if is the case, it would be great if someone could provide some more insight into that. I can't really see why content negotiation would increase risk or likelihood of success of attack?

And someone is supposedly working on replacing this with using the `Link` header. However it's been 4 months and it seems there's no progress (I can't see a Link header when I use DevTools)

See: https://lists.w3.org/Archives/Public/public-schemaorg/2020May/

Personally, I think the ideal situation is to **both** serve the Link header and allow for content negotiation.

**Comment by RichardWallis** [comment]
@alexkreidler You are correct in your information that these changes were introduced as part of a rapid restructure following the DOS attack a few weeks back.  

The dynamic processing and redirection required to facilitate content negotiation and the functionality you reference were one of the features identified as potential vulnerabilities for that, and future possible, attacks.  To that end, the restructuring took the approach of producing a totally static site with all pages constructed into html files prior to uploading to the serving platform.

As to the provision of machine readable representations of the vocabulary, this has been maintained with the [Vocabulary Definition File](https://schema.org/docs/developers.html#defs) downloads, and the serving of a static JSON-LD context via use of a Link header as specified in the latest JSON-LD specs.  The later of these being achieved by appending specific http response headers to the serving of the now static home page, thus not requiring and application specific processing.

The effect of this restructuring has been to deliver a more stable and robust site, with added benefits in its response.

As was noted on the developer page, the content negotiation and other format availability, for individual pages, were considered experimental features when they were available.  There is always a possibility in a restructuring, especially a necessarily rapid one, that some experimental and or little used features may not be carried forward.

I hope this gives you some of the background you were looking for.

~Richard.

**Comment by alexkreidler** [comment]
Duplicate of #2578
