### ISSUE TITLE
Errors in Schema Item List Example 3

### ISSUE THREAD

**Issue by krishna-pearl** [schemaorg/schemaorg#2675]
https://schema.org/ItemList#ItemList-gen-218

**Errors  Name** - Duplicate values for itemListElement.position are not allowed.
![image](https://user-images.githubusercontent.com/67366617/88632661-8832e300-d0d1-11ea-9d4d-ffb7429354e6.png)

**Url Is Missing** - Value Url Is Missing (Same with Example 2 ) 

 ![image](https://user-images.githubusercontent.com/67366617/88632543-5752ae00-d0d1-11ea-9c81-53e843afd098.png)

**Duplicate position no** -  
![image](https://user-images.githubusercontent.com/67366617/88632506-4a35bf00-d0d1-11ea-9d03-208977afc511.png)

I Hope You Change It Soon And We Get A Fresh New Schema Soon  [schema.org](schema.org).

**Comment by WeaverStever** [comment]
In the structured data testing tool, to make this work, all of your content has to be on the same page. (I.e., the urls must be separate anchor tags (id="mytag") on the same page.)

See also: https://developers.google.com/search/docs/data-types/carousel

**All values provided for itemListElement.item.url must point to the same page.**
~~~~
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ItemList",
  "name": "Top music artists",
  "url": "https://example.com/Billboard_200#Most_cumulative_weeks_at_number_one",
  "description": "The artists with the most cumulative weeks at number one according to Billboard 200",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "item": {
        "@type": "MusicGroup",
        "url":"https://example.com/Billboard_200#The_Beatles",
        "name": "Beatles"
      }
    },
    {
      "@type": "ListItem",
      "position": 2,
      "item": {
        "@type": "MusicGroup",
         "url":"https://example.com/Billboard_200#Garth_Brooks",
        "name": "Garth Brooks"
      }
    },
    {
      "@type": "ListItem",
      "position": 3,
      "item": {
        "@type": "MusicGroup",
         "url":"https://example.com/Billboard_200#Michael_Jackson",
        "name": "Michael Jackson"
      }
    },
    {
      "@type": "ListItem",
      "position": 4,
      "item": {
        "@type": "MusicGroup",
         "url":"https://example.com/Billboard_200#Whitney_Houston",
        "name": "Whitney Houston"
      }
    }
  ]
}
</script>
~~~~

**Comment by krishna-pearl** [comment]
@schemaorg Update This In [Schema.org](Schema.org)
