### ISSUE TITLE
Release Creation

### ISSUE THREAD

**Issue by BBudnicki** [schemaorg/schemaorg#2676]
@danbri 

I am working with a local version of schema.org and saw that you generated the content of releases/9.0. Is this a manual process or is there a script you can point me to?
https://github.com/schemaorg/schemaorg/tree/main/data/releases/9.0

When running createstaticsite.sh i receive an error "No module named dev_appserver".  Is this script supposed to generate those files as well?

 runpythonapp.sh loads the site on localhost as expected so I know the Google Apps Engine SDK is installed. However maybe the checks to find the SDK path within createstaticsite.sh are not as robust as within runpythonapp.sh

If this was a poor place to ask this question, please refer me to where I can ask similar questions in the future. I would be happy to contribute back to the project, especially the SOFTWARE_README.md & STATICBUILD_README.md They are missing a detailed explanation of the Google Apps Engine install process.

Brandon

**Comment by danbri** [comment]
It isn't optimised for others to use right now. @RichardWallis may have some pointers. We are having a rethink about the site codebase currently...

**Comment by RichardWallis** [comment]
As @danbri said, this area is not currently optimised for others to use right now.

However in answer to your questions:
- The Release Version 9.0 [you reference](https://github.com/schemaorg/schemaorg/tree/main/data/releases/9.0) was generated manually in preparation for future releases to be created automatically when the repository is tagged in a certain way.  The upcoming V10.0 will confirm, or not, that I have that configured correctly.

 - During development we have not experienced the error you identified with _createstaticsite.sh_.  You may be correct that similar robustness checking to that used in _runpythonapp.sh_ may be appropriate here too. I will look into it.

There is a delicate balance between including absolutely everything within readme files, or allowing the documentation provided by third parties for supporting software to handle the detail of those features.  Something to review during the rethink Dan mentioned.

**Comment by BBudnicki** [comment]
@danbri  & @RichardWallis thank you both for the thoughtful responses. Iv'e been a consumer of Schema.org for years and appreciate the work you are doing.

I bring up your publishing process because I am working with the [Citizen Science Association](https://www.citizenscience.org/) 
 to publish their schema. Our members are trying to make our API's interoperable, which requires the schema to have more rigidity than schema.org. Your codebase might make a good template, as there is a strong desire to use machine readable format (TTL, JSON-LD, or RDFa) as the source of truth for a series of interconnected pages.

I know opinions are a dime dozen. If you have any meeting discussing your architecture, id be very interested to listen in. Otherwise I am researching a custom Jekyll GitHub.io solution and Docusaurus GitHub.io solution. If you are planning a substantial re-write, id be happy to share those findings.

**Comment by RichardWallis** [comment]
@BBudnicki Following up on this...

When we tagged the v10.0-release the corresponding release was auto generated :-)  
However manual intervention was required to tweak the release label and promote it to be the latest release.

Also as someone working with a local version, you may be interested to note that in preparation for V11.0 we have reconfigured the codebase, reduced dependancies, and simplified the creation and test running of the site.  See the updated version of [SOFTWARE_README](https://github.com/schemaorg/schemaorg/blob/main/SOFTWARE_README.md) for details.

I am going to close this issue now.

**Comment by kristiaanvandeneynde** [comment]
@RichardWallis I've read the link you posted, but cannot figure out how to make https://schema.org/version/9.0/schema.jsonld or https://schema.org/version/10.0/schema.jsonld work

**Comment by RichardWallis** [comment]
@kristiaanvandeneynde there are couple of changes that have occurred over recent updates to Schema.org that shape an answer to your questions.

Firstly, the simplified approach to the creation and test running of the site means that you can only locally generate output files for the current release you are working on.  These are then located in the ```/releases/{version No}``` directory of the created site and made available for download via the ```/version/{version No}/*``` or ```/version/latest/*``` URLs.  

In addition, from this version onwards, the significant amount of vary rarely used data contained in data files from previous versions, is not being uploaded to the servers hosting the running version of the site at Schema.org. If copies of these files from previous versions are required, they can be downloaded from the [/data/releases](https://github.com/schemaorg/schemaorg/tree/main/data/releases) area of this repository.

Secondly, from version 9.0 onwards the naming of these files changed to reflect the evolution of the vocabulary and its partial coverage by the contents of files from previous versions.   The new naming, and contents, of these files are described in the [documentation](https://schema.org/docs/developers.html#defs). The reasoning behind the changes was discussed [here](https://github.com/schemaorg/schemaorg/issues/2683#issuecomment-669879045).
