### ISSUE TITLE
Add Tax Codes to Product

### ISSUE THREAD

**Issue by marcusorjames** [schemaorg/schemaorg#2677]
This is in some way related to #380 - Representing VAT component of a price.

- As is identified in #380 many countries have a VAT system.
- Not only this but products can have tax codes, identifying the tax obligations and exemptions customers have when purchasing the product
- For example in the UK, Childrens clothes are exempt from VAT.
- Different systems use different codes, I'm not sure if there is a standard usually there are
  - Zero Rate
  - Standard
  - Exempt
  - Reduced Rate
  - No VAT
  - Reverse Charge
- Tax Codes are required for financial ledger entries

It is proposed that Products have a taxCode field in order to identify this.

**Comment by RichardWallis** [comment]
Tax is applicable to the potential [Offer](http://schema.org/Offer) for sale, not necessarily the Product which could be simultaneously on offer in many regions and therefore tax regimes.

As you point out issue #380 references this with a discussion of how the [PriceSpecification](https://schema.org/PriceSpecification) of an Offer could be enhanced.   Although an old issue, #380 is still relevant in this matter.

**Comment by marcusorjames** [comment]
Agreed, when making an [Offer](http://schema.org/Offer), the [PriceSpecification](https://schema.org/PriceSpecification) as described in #380 is not granular enough on how the price is constructed. Indicating a tax code at this level I think as you say is more accurate because of the potential of the product on offer in many regions.

The necessity in my circumstance is because specifically for accounting ledgers, they need to understand what code was applied to the offered product.
