### ISSUE TITLE
buildowlfile.py generating `owl:datatypeProperty` rather than `owl:DatatypeProperty` 

### ISSUE THREAD

**Issue by skwlilac** [schemaorg/schemaorg#2684]
A small typo at line 329 in `scripts/buildowlfile.py` applies the wrong class URI to datatype properties.

**Comment by RichardWallis** [comment]
Well spotted @skwlilac - Fixed in commit f8eab43 for next release.

**Comment by RichardWallis** [comment]
Fixed in V10.0
