### ISSUE TITLE
Question: How to provide actual image data?

### ISSUE THREAD

**Issue by James-Hudson3010** [schemaorg/schemaorg#2696]
There is sch:ImageObject, but that class is designed to hold information about an image and not the image data. Let's say I wanted to attach the actual PNG data (encoded as base64, for example) in a schema.org class and property. What is the appropriate way to do that?

**Comment by Wombarly** [comment]
There is a `contentUrl` property on `MediaObject`. If you base64 encode your image you can pass it along as a [Data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) by prefixing it with: `data:image/png;base64,`
