### ISSUE TITLE
Question: what schema type to use for volunteer opportunities?

### ISSUE THREAD

**Issue by eugeneford** [schemaorg/schemaorg#2701]
Hello there, I've been looking to available schema types for a while and did not find a dedicated one for Volunteer opportunities. The closest one I can think of is a JobPosting, but i'm not sure whether it is appropriate. Can someone advice please?

**Comment by solstice-born** [comment]
I would use [JobPosting](https://schema.org/JobPosting) schema, and under [employmentType ](https://schema.org/employmentType) you would put "volunteer".
