### ISSUE TITLE
Redundant Properties for subclass / parent

### ISSUE THREAD

**Issue by vberkel** [schemaorg/schemaorg#2703]
Following a Tom Marsh mail list comment in the v10 release candidate about redundant properties, I found the following classes have parents which already have the associated property. The suggested fix would be to remove the property domainIncludes for the classes and keep the parent. 

| class | parent | property | 
|---|---|---|
| schema:Accommodation | schema:Place | schema:amenityFeature | 
| schema:Apartment | schema:Accommodation | schema:numberOfRooms | 
| schema:EducationalOrganization | schema:Organization | schema:alumni | 
| schema:House | schema:Accommodation | schema:numberOfRooms | 
| schema:LodgingBusiness | schema:Place | schema:amenityFeature | 
| schema:MediaObject | schema:CreativeWork | schema:encodingFormat | 
| schema:ProductModel | schema:Product | schema:isVariantOf | 
| schema:SingleFamilyResidence | schema:House | schema:numberOfRooms | 
| schema:SingleFamilyResidence | schema:Accommodation | schema:numberOfRooms | 
| schema:Suite | schema:Accommodation | schema:numberOfRooms | 
| schema:Vehicle | schema:Product | schema:productionDate | 
| schema:Vehicle | schema:Product | schema:purchaseDate | 

FYI; the SPARQL query I used is:
```
SELECT * 
WHERE {
		?class rdfs:subClassOf+ ?parent . 	
		?property schema:domainIncludes ?class .
		?property schema:domainIncludes ?parent .
} 
```

**Comment by danbri** [comment]
Thanks for your attention to detail! 

I think sometimes there have been occasions where we have done this by design, because the supertype was a more tenuous fit for the properties than the more specific type, but it was also sometimes useful on the supertype. But looks like some oversight / duplication that could be tidied up, thanks. 

p.s. nice use of SPARQL :)
