### ISSUE TITLE
workFeatured inverse of workFeatured?

### ISSUE THREAD

**Issue by ljgarcia** [schemaorg/schemaorg#2708]
Hi all, @danbri @philbarker, @AlasdairGray 

We want to establish a link from/to [CourseInstance](https://schema.org/CourseInstance) and CreativeWork](https://schema.org/CreativeWork), i.e. a CourseInstance has a training material that is a CreativeWork. The property [workFeatured](https://schema.org/workFeatured) seems to work for both directions which is confusing so we want to double check whether we are properly understanding the descriptions or whether the property should be revised.

The property at [workFeatured](https://schema.org/workFeatured) is described as "A work featured in some event, e.g. exhibited in an ExhibitionEvent. Specific subproperties are available for workPerformed (e.g. a play), or a workPresented (a Movie at a ScreeningEvent)."
With values expected to be one of these types: CreativeWork
And used on these types: Event

What we get from the property description page is CreativeWork - workFeatured - Event, which coincides with the use in CreativeWork.

However, what we get from [Event](), parent type for CourseInstance, is Event - workFeatured - CreativeWork

Is workFeatured inverse of itself? Should the expected values on the property description page include both CreativeWork and Event? Should the use on these types on the property description page include both CreativeWork and Event? Is there a mistake in the usage or description of this workFeatured property?

Thanks!

**Comment by philbarker** [comment]
I think you are either seeing something I am not or mis-reading the [definition of workFeatured](https://schema.org/workFeatured) 

I see it as working only one way: used on type Event, value expected to be Creative work, so 
`(Event)--[workFeatured]->(CreativeWork)`, as you describe for CourseInstance. 

("used on" refers to the domain of the property, so the type of subject in a statement; the value expected for a property is what it points to; the range of the property, so the type of object in a statement)

**Comment by ljgarcia** [comment]
@philbarker I realized about my mistake... looong pages, tables looking quite the same, long week, I got lost. Thanks for clarifying. I am closing this issue now.

**Comment by philbarker** [comment]
@ljgarcia it's Friday, you're nearly there, have a good weekend.
