### ISSUE TITLE
Incorrect RDFa markup for properties on schema.org ( 'rdfs:Property' instead of 'rdf:Property')

### ISSUE THREAD

**Issue by YarnSeemannsgarn** [schemaorg/schemaorg#2713]
Example:

https://schema.org/name

Incorrect RDFa markup:

`<div id="mainContent" vocab="http://schema.org/" typeof="rdfs:Property" resource="http://schema.org/name">`

Corrected RDFa markup:

`<div id="mainContent" vocab="http://schema.org/" typeof="rdf:Property" resource="http://schema.org/name">`

**Comment by danbri** [comment]
You're correct - thanks for taking the time to report this.

I have suggested that we drop the RDFa from these pages and instead encourage people to use our schema definitions as a coherent whole. The in-page RDFa is a disconnected fragment extracted from the larger graph of definitions which we publish in downloadable form at https://schema.org/docs/developers.html . It also uses http: prefixes and we are gradually migrating towards https:.

Are you using this markup for something, or you just happened to notice it?

**Comment by YarnSeemannsgarn** [comment]
I just noticed it when i checked the HTML, because we ([STI Innsbruck](https://www.sti-innsbruck.at/)) are building a [new vocabulary browser](https://github.com/semantifyit/schema-org-vocab-browser) for external vocabularies which are based on the schema.org vocabulary.

The browser uses the same CSS you use for [schema.org](https://schema.org/)
