### ISSUE TITLE
Add permissive access-control-allow-origin to the 301 redirect on all HTTP pages

### ISSUE THREAD

**Issue by alexkreidler** [schemaorg/schemaorg#2721]
Currently a request to `https://schema.org/Person` returns response headers including:
`access-control-allow-origin: *`. This allows for scripts from all domains across the web to successfully make XHR requests to the page, which is vital to allow JSON-LD clients to dereference IRIs like `https://schema.org/Person` and extract the RDFa or other linked data attributes from the page.

Unfortunately, a request to `http://schema.org/Person`, although it's only a 301 redirect, doesn't include any CORS headers, which means that the request is blocked.

In Firefox 78 I get:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://schema.org/Person. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://schema.org/Person. (Reason: CORS request did not succeed).
```

This issue is compounded by #2720, because some JSON-LD clients trying to dereference the following:
```json
{
    "@context": "https://schema.org",
    "@type": "Person",
    "some": "data that's irrelevant"
}
```
Will go to `https://schema.org` -> `https://schema.org/docs/jsonldcontext.jsonld` and since the context links to HTTP versions of the resources, then `http://schema.org/Person`, where the request is blocked.

Fixing either the cors headers or the https instead of http context (#2720) would fix my specific situation which is the combination of the two described here.

Thanks for your work!

**Comment by danbri** [comment]
As far as I understand from reading the docs (and @RichardWallis also investigated) we are constrained around this, for as long as we continue using Google App Engine.

Can you expand a little on "since the context links to HTTP versions of the resources"? Are you trying to fetch /Person ?

**Comment by RichardWallis** [comment]
Yes we are constrained ad @danbri describes.  We can only define CORS and other headers on requests to https.  http requests are automatically redirected without intervention.

**Comment by alexkreidler** [comment]
Yeah I just saw https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-652349679.

@danbri what I mean by "since the context links to HTTP versions of the resources" is described more in #2720. The context file that schema.org links to uses a line like ` "schema": "http://schema.org/"` to create the prefix, which means the IRIs for every node are expanded to HTTP IRIs. For clients that want to fetch data about the nodes via their IRIs, they then run into this issue if they are in the browser and have CORS.

**Comment by RichardWallis** [comment]
@alexkreidler - it is a little difficult to be trying to answer this across two issues.

However I think we can close this one as there is little we can do about it.  

Following the DOS attack earlier this year, the entire site was converted to a set of static pages and files with no on-server processing.  The situation with the hosting server environment (Google App Engine) for such a site is:
- The server 301 redirects all http calls to https - this is a simple configuration and gives no opportunity to define headers, CORS or otherwise, to be included with the response.
