### ISSUE TITLE
OfferShippingDetails does not provide for min amount/qty for shippingRate

### ISSUE THREAD

**Issue by jsmoriss** [schemaorg/schemaorg#2731]
The shippingRate, which is a MonetaryAmount, does not allow for a minimum order amount or quantity to get that shippingRate (for example, free shipping if spending $100 or more, or buy 5 to get free shipping). The shippingSettingsLink allows us to provide a URL to a webpage with additional shipping details for that rate, but this assumes that 1) this rate is not unique to this product / offer, that 2) we have a webpage with those shipping details. There should be a way to add ShippingRateSettings directly in the OfferShippingDetails instead of forcing the use of a URL.

**Comment by danbri** [comment]
@alex-jansen

**Comment by alex-jansen** [comment]
@jsmoriss The idea behind the separate /shippingSettingsLink is that many offers typically share the same shipping settings, so it would be repetitive and error-prone to add the same settings over and over again for each individual offer. 

As far as 1) is concerned: a specific shipping rate setting (such as free shipping over $100) as defined on the URL specified by /shippingSettingsLink can be labeled using the /shippingLabel property and then referenced as such from the subset of offers where that setting applies to.

**Comment by jsmoriss** [comment]
@alex-jansen A few things to keep in mind:

1) The @id can be used to avoid repeating the same information (one block has the information and all others simply use the @id reference).

2) Most e-commerce shops, like WooCommerce for example, do not have a shipping settings page, so there's no URL to a shipping settings page available.

3) I'm not saying the shippingSettingsLink is not useful (for those shops that do have a shipping settings page), I'm saying the value of shippingRate is too limited for most e-commerce shops.

js.

**Comment by alex-jansen** [comment]
@jsmoriss One of the issues we considered is that the typical use-case of a $XX free shipping threshold is that this holds for any combination of offers, for example 1x A, 2x B and 1x C. This means it is an account-level setting, and not an individual offer-level setting. Adding it to an individual offer would only make sense if it is interpreted for that specific offer, which seems uncommon?

For the free shipping quantity it might be more natural to interpret this at the offer level ("order min. 5x A for free shipping"), but this seems much less common than free shipping based on a $ amount. What is your experience in this area?

**Comment by jsmoriss** [comment]
@alex-jansen Yes, if you look at the issue from a top-down approach, a "$100 for free shipping" offer (for example), would apply to the whole store, and could be included in a shipping details page, BUT programmatically, using WooCommerce as an example, the markup is created per product (so bottom-up instead of top-down) - when you have a product, you put together its offer (price per variation, per currency, any min/max limits, available shipping options, etc). The available shipping options may vary based on the product or variation size, weight, and any shop owner selected shipping methods (ie. some products can only ship ground). Based on this, you can determine the shipping cost per region, any shipping cost adjustments for quantity, total purchase, coupons, etc., and then include those costs and regions in the markup. Having the possibility to include free shipping, for example, for min quantities, min purchase total, and/or coupon, would be great as these are all possibilities.

So once you factor in the shipping region, shipping method (ground, air, etc.), and any shipping cost modifiers, yes, you could build a unique ID string and use that in the shippingSettingsLink page, or you can include it in the current product markup using an @id string to avoid duplicate markup in the @graph. That is, in my opinion, both more efficient and less prone to error (since it avoids having to check if the unique ID string actually exists in the shippingSettingsLink page when adding it to the product markup).

Some additional thoughts:

Keep in mind that WooCommerce, and all other e-commerce platforms that I know of (and I know of many), do not have a "shipping settings" page, so a shippingSettingsLink value is not available. The markup could certainly be created easily enough programmatically if that page existed (like the shop page, product page, cart page, checkout page, etc.), but in the case of WooCommerce and all other platforms I know if, that page does not exist.

I have not, so far, seen any other properties like shippingSettingsLink that force cutting-up the Schema markup into multiple pages. I've found that using @id within a @graph avoids duplication, so if duplication is a concern, why not just use an @id?

js.

**Comment by alex-jansen** [comment]
@jsmoriss I believe#3617 is addressing your comments, both in terms of being able to specify minimum order amount or quantity for individual offers, as well as leveraging @id to specify both merchant-wide shipping settings and avoiding repeating the same information.
