### ISSUE TITLE
Ability to identify a location of "unknown" with Place or Location?

### ISSUE THREAD

**Issue by lrosenthol** [schemaorg/schemaorg#2741]
For the Content Authenticity Initiative (https://contentauthenticity.org/), we would like to be able to clearly state that a given asset was created at an unknown location.  This would be to disambiguate from "no location provided" to "unable to provide a location" (eg. for security/privacy reasons).

Is there a standard method for this?  If not, can we define one?

**Comment by dr-shorthair** [comment]
Over in OGC we defined a set of generic 'null' values (or 'nil reasons') to be used generally for such situations. 
The set included:
- unknown
- missing
- withheld
- inapplicable
- above-detection-limit
- below-detection-limit
- other (brief explanation in text)

Might be useful in SDO?
