### ISSUE TITLE
Structured Data Testing Tool

### ISSUE THREAD

**Issue by WeaverStever** [schemaorg/schemaorg#2742]
The  [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) is scheduled to be shut down.  The replacement, [Rich Result Test](https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=message) currently only provides a binary "eligible" or "ineligible" without a debugger.  Additionally, the Rich Result test does not appear to detect several itemtypes.

The viability of this project seems in doubt if we don't have a feedback mechanism from the platform that controls 85% of search.

Thoughts?

**Comment by akuckartz** [comment]
> The viability of this project seems in doubt if we don't have a feedback mechanism from the platform that controls 85% of search.

No.

**Comment by WeaverStever** [comment]
See item: **a Schema Markup Validator: adopting SDTT to add validation to Schema.org site** #2790

**Comment by alex-jansen** [comment]
Given that both the Google-specific RRT validator and the generic Schema markup validator are alive with no plans to deprecate either we can close this issue.
