### ISSUE TITLE
PhotoStudio Mikro Verileri (JSON-LD)

### ISSUE THREAD

**Issue by mesutuca33** [schemaorg/schemaorg#2743]
hello my situation is a bit complicated but I hope it will be understandable. Please don't give Direct Minus. I searched this Thread a lot and could not find it anywhere.

I have a Photo Studio and there are contents related to it, but I could not quite figure out how will the microdata structure be.
Microdata construction is as follows.

1.How accurate is Organization for Photo Studio?

2.Will Every Page Become a Website Microdata?

3.Does Web Page have to be on every page? For example, Do You Have To Be On The Article Page?

**Page structure**

Home page >(Have only Normal Slider) **is this page a webpage?**

Products > (Bulk Product Display Page) **Is this page a product list?**

Videos > Collected video page **Is this the Video Gallery?**

Gallery > Photo gallery **what will this place be listed as?**

Blog > Wedding, engagement henna Articles and so on.
about us > **what will this place be listed as?**

contact **what will this place be listed as?**

```
<script type="application/ld+json">{
        "@context": "https:/schema.org",
        "@graph": [
            {
                "@type": "Organization",
                "name": "",
                "url": "...",
                "sameAs": ["...."],
                "logo": {
                    "@type": "ImageObject",
                    "url": "...",
                    "caption": "...",
                    "@id": "http://example.com/#logo"
                },
                "image": {
                    "@id": "http://example.com/#logo"
                },
                "location": {
                    "@id": "http://example.com/#local-place"
                },
                "address": {
                    "@id": "http://example.com/#local-place-address"
                },
                "@id": "http://example.com/#organization"
            },
            {
                "@type": "WebSite",
                "url": "http://example.com",
                "name": "...",
                "description": "...",
                "publisher": {
                    "@id": "http://example.com/#organization"
                },
                "potentialAction": {
                    "@type": "SearchAction",
                    "target": "http://example.com/?q={search_term_string}",
                    "query-input": "required name=search_term_string"
                },
                "@id": "http://example.com/#website"
            },
            {
                "@type": "WebPage",
                "url": "http://example.com/iletisim",
                "inLanguage": "en",
                "name": "...",
                "isPartOf": {
                    "@id": "http://example.com/#website"
                },
                "datePublished": "...",
                "dateModified": "...",
                "description": "...",
                "breadcrumb": {
                    "@id": "http://example.com/#breadcrumb"
                },
                "primaryImageOfPage": {
                    "@id": "http://example.com/#primaryimage"
                },
                "@id": "http://example.com/#webpage"
            },
            {
                "@type": "ImageObject",
                "url": "http://example.com/image.jpg",
                "width": 900,
                "height": 600,
                "license": "http://example.com/license",
                "caption": "...",
                "@id": "http://example.com/#primaryimage"
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "item": {
                            "@type": "WebPage",
                            "url": "http://example.com",
                            "name": "...",
                            "@id": "http://example.com"
                        }
                    }
                ],
                "@id": "http://example.com/#breadcrumb"
            },
            {
                "@type": "Place",
                "name": "...n",
                "address": {
                    "@type": "PostalAddress",
                    "streetAddress": "...",
                    "addressLocality": "...",
                    "postalCode": "...",
                    "addressRegion": "...",
                    "addressCountry": "...",
                    "@id": "http://example.com/#local-place-address"
                },
                "geo": {
                    "@type": "GeoCoordinates",
                    "latitude": "...",
                    "longitude": "..."
                },
                "openingHoursSpecification": {
                    "@type": "OpeningHoursSpecification",
                    "dayOfWeek": [
                        "Monday",
                        "Tuesday",
                        "Wednesday",
                        "Thursday",
                        "Friday",
                        "Saturday",
                        "Sunday"
                    ],
                    "opens": "09:00",
                    "closes": "20:30"
                },
                "telephone": "...",
                "@id": "http://example.com/#local-place"
            }
        ]
    }
</script>
```

**Comment by WeaverStever** [comment]
Not really supposed to do this here, but hope this helps you.

The latest guidance from John Muller (Google) is that the Organization markup should only be on your home page (not every page).

If you are a single location brick and mortar business, you are probably better off using https://schema.org/LocalBusiness

Website should be in a stand-alone script also only on the home page.

Webpage is usually assumed or it would be the outer-most itemtype on your page(s).
https://schema.org/WebPage

You only describe what is on the page.

More specific Types (of webpage -- so top level of your page script)
AboutPage
CheckoutPage
CollectionPage
ContactPage
FAQPage
ItemPage
MedicalWebPage
ProfilePage
QAPage
RealEstateListing
SearchResultsPage

See also 
https://schema.org/VideoGallery
https://schema.org/ImageGallery

**Comment by mesutuca33** [comment]
The diagram above is present on every page is this wrong?

**Comment by WeaverStever** [comment]
It is probably not wrong as long as it tests okay on the [SDTT](https://search.google.com/structured-data/testing-tool).

Here's the Organization conversation.
https://www.searchenginejournal.com/google-do-not-put-organization-schema-markup-on-every-page/289981/#close

**Comment by mesutuca33** [comment]
> [SDTT'de](https://search.google.com/structured-data/testing-tool) iyi test ettiği sürece muhtemelen yanlış değildir .
> 
> İşte Organizasyon görüşmesi.
> https://www.searchenginejournal.com/google-do-not-put-organization-schema-markup-on-every-page/289981/#close

I read the interview, but thank you.For example, the organization
If it exists on the Home Page, I need to add it to other pages. have I got it right?
do you use Skype

**Comment by WeaverStever** [comment]
The Google team doesn't really give a definitive answer in the video.
Probably the most important thing is to only have one script for when you make changes.

In the past, I have put Organization scripts in the CMS's footer, so it is on every page, but easy to change properties like contact email, open hours etc.

sorry no skype

**Comment by mesutuca33** [comment]
To say something, I am really confused, I've been dealing with this for 2 weeks and I make new changes at the end of every work I do. I'm even cooled off using schema. which site I looked at the source code. org in grap. There is website webpage and localbusiness fix.

**Comment by mesutuca33** [comment]
a question like this, for example
example.com/page/weddingstories

There are videos on this page collectively.
schema for this page
1-website (SearchAction)
2-webpage (page information)
3-BreadcrumbList
4-itemlist (VIDEO OBJECT)
and
5-Localbusines
### **Is it true that way**
or Item List  BreadcrumbList
Should it be combined?

**Comment by WeaverStever** [comment]
Maybe easier to understand if you use separate scripts.

The website script
https://schema.org/WebSite
~~~
<script type="application/ld+json">
  {
      "@type": "WebSite",
      "url": "http://example.com/",
      "name": "...",
      "description": "...",
      "publisher": {
          "@id": "http://example.com/#organization"
      },
      "potentialAction": {
          "@type": "SearchAction",
          "target": "http://example.com/?q={search_term_string}",
          "query-input": "required name=search_term_string"
      },
      "@id": "http://example.com/#website"
  }
</script>
~~~
https://schema.org/Organization
~~~~
<script type="application/ld+json">
            {
                "@type": "Organization",
                "name": "",
                "url": "https://example.com/",
                "sameAs": ["...."],
                "logo": {
                    "@type": "ImageObject",
                    "url": "...",
                    "caption": "...",
                    "@id": "http://example.com/#logo"
                },
                "image": {
                    "@id": "http://example.com/#logo"
                },
                "location": {
                    "@id": "http://example.com/#local-place"
                },
                "address": {
                    "@id": "http://example.com/#local-place-address"
                },
                "@id": "http://example.com/#organization"
            }
</script>
~~~~

and localBusiness -- only if you have a commercial customer presence
if you don't have a store-front, you should not need this
 https://schema.org/LocalBusiness

~~~~
<script type="application/ld+json">
{
    "@type": "LocalBusiness",
    "name": "...n",
    "telephone": "...",
    "@id": "http://example.com/#local-place",
    "url": "https://example.com/",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "...",
        "addressLocality": "...",
        "postalCode": "...",
        "addressRegion": "...",
        "addressCountry": "...",
        "@id": "http://example.com/#local-place-address"
    },
    "geo": {
        "@type": "GeoCoordinates",
        "latitude": "...",
        "longitude": "..."
    },
    "openingHoursSpecification": {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday"
        ],
        "opens": "09:00",
        "closes": "20:30"
    }
}
</script>
~~~~

and the webpage(s)
https://schema.org/WebPage

~~~~
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": "....",
    "url": "https;//example.com/thisPageName",
    "additionalType": "https://en.wikipedia.org/wiki/Photography",
    "description": "....",
    "publisher": {
        "@type": "CollegeOrUniversity",
        "name": "MIT OpenCourseWare"
    },
    "license": "http://creativecommons.org/licenses/by-nc-sa/3.0/us/deed.en_US"
}
</script>

~~~~

**Comment by mesutuca33** [comment]
thank you. I have 2 offices in the same city. How can I specify this? Local Business?

**Comment by WeaverStever** [comment]
Yes, only one organization, use two local business scripts like the one I provided, make sure that the @id is different for each one.

A breadcrumb list is for navigation -- not many sites use them anymore -- they are hard to maintain.
Home > Albums > Weddings

For an itemlist like a photo gallery there is some code samples here.

https://developers.google.com/search/docs/data-types/carousel

**Comment by mesutuca33** [comment]
will i use this on every page? Or is it just for the home page?
```
<script type="application/ld+json">
            {
                "@type": "Organization",
                "name": "",
                "url": "https://example.com/",
                "sameAs": ["...."],
                "logo": {
                    "@type": "ImageObject",
                    "url": "...",
                    "caption": "...",
                    "@id": "http://example.com/#logo"
                },
                "image": {
                    "@id": "http://example.com/#logo"
                },
                "location": {
                    "@id": "http://example.com/#local-place"
                },
                "address": {
                    "@id": "http://example.com/#local-place-address"
                },
                "@id": "http://example.com/#organization"
            }
</script>
```

**Comment by WeaverStever** [comment]
Website and Organization -- use once on your home page.

**Comment by mesutuca33** [comment]
> Website and Organization -- use once on your home page.

Thanks for your help. If I can do it without stuck

**Comment by WeaverStever** [comment]
Let's take this offline if you have more questions 
steven.kritzer gmail

**Comment by mesutuca33** [comment]
> steven.kritzer
Is there a place you use online
