### ISSUE TITLE
Example 3 of VideoGame is incorrect

### ISSUE THREAD

**Issue by djalilhebal** [schemaorg/schemaorg#2746]
In [Example 3](https://schema.org/VideoGame#eg-0449), "employee" is repeated.
This usage is incorrect since the latter value overrides the previous ones.
The `"employees"` attribute should be used instead of `"employee"`.

```js
{
  "@context": "https://schema.org",
  "@type": "VideoGame",
  "name": "Fallout 3",
  "url": "http://fallout.wikia.com/wiki/Fallout_3",
  "playMode": "SinglePlayer",
  "author": {
    "name":"Bethesda Game Studios",
    "url":"http://www.bethsoft.com/",
    "founder":"Christopher Weaver",
    "foundingDate":"1986",
    "employee":"Vlatko Andonov",
    "employee":"Todd Howard",
    "employee":"Ashley Cheng"
    },
    // ...
}
```

PS: I am totally new to JSON-LD and stuff, so I'm not sure if this is the best place to post this issue (as opposed to Google Forms) and not confidant enough to make a PR.

**Comment by RichardWallis** [comment]
Fixed in V11.0 release.
