### ISSUE TITLE
No Organization Type for Distillery or Craft Spirits

### ISSUE THREAD

**Issue by JessSmithCO** [schemaorg/schemaorg#2750]
Hello World,

I am setting up an organizational schema for a distillery (no tasting room, only warehouse) and am having issues setting this up.
Has anyone done this for an alcohol brand?

No Organization Type for Distillery or Craft Spirits

The only thing I found was this, but they do not sell food or have a tasting room, only a corporate office, and warehouse
Distillery
Thing > Organization > LocalBusiness > FoodEstablishment > Distillery
Thing > Place > LocalBusiness > FoodEstablishment > Distillery

Thank you for the help!!

**Comment by RichardWallis** [comment]
You are placing too much semantic emphasis on the Types that Distillery inherits its properties.

If the organisation refers to itself as a Distillery, [Distillery](https://schema.org/Distillery) is the appropriate type.

All properties are optional so select the ones that help you best describe the organisation.

**Comment by JessSmithCO** [comment]
So would I then @RichardWallis list it like such

  “@context”: “https://schema.org”,
  “@type”: “Organization”,
  “@type”: “Distillery”,

**Comment by RichardWallis** [comment]
@JessSmithCO  No need to list it as an Organization and a Distillery, as Distillery is a subtype of Organization.

For info:  If you were to list it with multiple types the syntax would be like this:
```
{
  “@context”: “https://schema.org”,
  "@type": ["Distillery","TouristAttraction"],
 ...
```

**Comment by JessSmithCO** [comment]
Thanks, @RichardWallis

**Comment by WeaverStever** [comment]
@JessSmithCO 
See also, the naics property for the US and isicV4 property for EU.

https://schema.org/naics
https://www.naics.com/naics-code-description/?code=312140#:~:text=NAICS%20Code%3A%20312140%20Distilleries%20%7C%20NAICS%20Association

https://schema.org/isicV4
https://unstats.un.org/unsd/publication/seriesm/seriesm_4rev4e.pdf (keyword distilling)
