### ISSUE TITLE
Errors (X)HTML in RDFa pages

### ISSUE THREAD

**Issue by BorderCloud** [schemaorg/schemaorg#2773]
Hello

I try to parse IRIs of schemaorg.
For example : http://schema.org/isPartOf

My RDFa parser (semargl-rdf4j)  say me : 
`[Fatal Error] :81:3: The element type "meta" must be terminated by the matching end-tag "</meta>".`

Can you close yours HTML tags ? (with />)

Thanks ;)

NB :[ you can use the W3C validator to check](https://validator.w3.org/check?uri=http%3A%2F%2Fschema.org%2FisPartOf&charset=%28detect+automatically%29&doctype=XHTML+1.0+Strict&group=0)

**Comment by jvandriel** [comment]
The W3C validator was set to XHTML yet the site is in HTML5. When you run the test again with the validator set to HTML there isn't much wrong.

Could it be the same thing is happening with your RDFa parser?

**Comment by BorderCloud** [comment]
Unfortunately this parser does not seem to support XML errors :-/

**Comment by RichardWallis** [comment]
Closing.

Note: From V11.0 onwards (provisional release date 2020-11-30) RDFa data within term page html is superseded by an _application/ld+json_ script element.

A preview of this can be seen at [webschemas.org](https://webschemas.org/isPartOf)
