### ISSUE TITLE
it should be easier to associate a Menu with a FoodService

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2774]
Feedback from Google implementation work: It is currently rather painful and indirect to associate a Menu with a FoodService.

Consider adding something like 

> https://schema.org/hasMenu schema:domainIncludes https://schema.org/FoodService .

**Comment by AESEO1** [comment]
/hasMenu could then have recipe nested 
you could also go as far as to mention if it contains nuts for example for alleges 
or if it recipe is vegan for people looking for specialist restaurants that cater to there needs  

so would make sense to me
