### ISSUE TITLE
Two Recipes One Schema

### ISSUE THREAD

**Issue by JessSmithCO** [schemaorg/schemaorg#2775]
Hello All.
As I am still a novice at schema, I require some help from all the experts.
I am trying to add two recipes to a one-page schema. It will recognize the first recipe but not the second one.
Am I supposed to add an item list to this?

Here is what I have so far:

[Recipe-Schema.docx](https://github.com/schemaorg/schemaorg/files/5592744/Recipe-Schema.docx)

Thank you in advance,
Jessica

**Comment by jaygray0919** [comment]
See: https://developers.google.com/search/docs/data-types/recipe

**Comment by JessSmithCO** [comment]
Thank you @jaygray0919 
I figured out my issue as well, I need to have each recipe as its own script and not combined.
Happy Thanksgiving,
Jessica
