### ISSUE TITLE
Issues with Markdown Comments in v11

### ISSUE THREAD

**Issue by Eyas** [schemaorg/schemaorg#2780]
1. https://schema.org/Series comment is:
     ```
     \n          A Series in schema.org is a group of related items, typically but not necessarily of the same kind. See also [[CreativeWorkSeries]], [[EventSeries]].
     ```

    Which renders as a code block due to the leading spaces.

2. https://schema.org/ReserveAction comment is:

    `"Reserving a concrete object.\\n\\nRelated actions:\\n\\n* [[ScheduleAction]]</a>: Unlike ScheduleAction, ReserveAction reserves concrete objects (e.g. a table, a hotel) towards a time slot / spatial allocation."`

    There's an unmatched closing `</a>` tag.

**Comment by RichardWallis** [comment]
Fixed in v11.01
