### ISSUE TITLE
Broken relative links on /docs/developers.html due to {{staticPath}}

### ISSUE THREAD

**Issue by Tiggerito** [schemaorg/schemaorg#2808]
https://schema.org/docs/developers.html

Relative links like "/docs/schemaorg.owl" are being converted to "{{staticPath}}/docs/schemaorg.owl" on the live page. Which is broken.

**Comment by RichardWallis** [comment]
Fixed in 918ffc6

**Comment by Tiggerito** [comment]
If I new it was that simple!
