### ISSUE TITLE
The branch property has been superseded by properties that don't yet exist.

### ISSUE THREAD

**Issue by Tiggerito** [schemaorg/schemaorg#2809]
Using

https://schema.org/version/latest/schemaorg-all-http.jsonld

I'm adding checks for SupersededBy. My code found that https://schema.org/branch had the following two properties referenced, but they are not defined:

http://schema.org/veinBranch 
http://schema.org/nerveBranch

**Comment by RichardWallis** [comment]
Fixed in 74b19f5
