### ISSUE TITLE
Proposal to add support for structured sizes and measurements

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#2811]
In Release 9.0 a new [/size](https://schema.org/size) property was published (see issue #2587) to model product sizes as free-form text.

As a follow-up to address the still open items from issue #2587 and in collaboration with @danbri and @mfhepp we are now proposing to also allow a more structured way of specifying product sizes. 

For example, apparel sizes are often expressed as a combination of one or more of the following attributes:
- a size **system**, typically a country, region, or standard identifier (e.g., "eu", "iso 8559").
- a size **group** (e.g., "big and tall", "petite"), typically used together with age group and gender information to identify a fashion department.
- A size **code** (per the size system and size group), for example "3XL" or "32Wx34L".
- one or more manufacturer-defined **measurements** of the product (e.g. for pants: "waist" with a measurement of 32 inches and "inseam" with a measurement of 34 inches).
- one or more (ranges of) **measurement**(s) for the intended consumer (e.g. "waist" between 30 and 32 inches and "inseam" between 33 and 35 inches). 

We propose to add a few new types and properties to model these size-related attributes, building on prior art such as the GS1 Web Vocabulary ([SizeDetails](https://www.gs1.org/voc/SizeDetails)) and the CPI Ontology ([example](http://www.ebusiness-unibw.org/ontologies/cpi/evaluation/jeans.n3), [reference](http://www.ebusiness-unibw.org/ontologies/cpi/ns)). 

We also propose to generalize the concept of a "measurement" since it applies to many types of products (i.e., not just wearables). For example a bicycle has wheel and frame measurements, and a screw has gauge and thread-distance measurements. 

Given the size of the proposal, an external Google Docs [document](https://docs.google.com/document/d/1MbYXG8wRallckDFbqY2NYc8Y83gUGA4ABDHdMclxzQA) is created for review and inline comments.

Adding @mgh128 and @jvandriel based on the discussion in #2587.

**Comment by danbri** [comment]
/cc @philarcher 

To be explicit, this is a direction that Google both supports for the general ecosystem, and expects (if adopted) to actively implement.

**Comment by philarcher** [comment]
Thanks @danbri & @alex-jansen. I'll take a look and ask @mgh128 for support in that.

**Comment by mgh128** [comment]
Thanks - I read through the Google Doc yesterday evening and the approach seems logical and reusable for various types of products.  We (GS1) are happy to help support this.  In the near term, feel free to extract any of our code lists etc. from https://www.gs1.org/voc or the Turtle / JSON-LD versions linked from https://www.gs1.org/standards/gs1-smartsearch/1-6
We'll also keep this approach in mind as we expand the GS1 Web vocabulary to support further categories of products.

**Comment by alex-jansen** [comment]
Thanks @mgh128 and @philarcher. I create a first draft (including a full example) of the proposed schemas and submitted a pull request for review by @danbri and @mfhepp, please take a look. 

I did not directly import the code lists from GS1 (so I could follow the enumeration naming conventions in core Schema.Org) but I took care to include the GS1 enumeration values for wearable size types, groups, and systems with two exceptions: I did not add ONE_DIMENSION for gs1:SizeTypeCode (I am not sure about its role?) and also WOMENS_TALL and MENS_TALL for gs1:SizeGroupCode (since these can be constructed by providing multiple values, e.g., WOMENS and TALL). Also note that I followed EN-13402 to enumerate body measurement dimensions. This does not include for example measurement for shoes and others which we might to add add. 

Comments welcome!

**Comment by danbri** [comment]
Thanks, @mgh128 @philarcher. Let's get this merged into Pending, so that the design can be explored using the normal Schema.org site navigation / linking etc machinery.

**Comment by RichardWallis** [comment]
Implemented in V12.0

**Comment by dr-shorthair** [comment]
> We also propose to generalize the concept of a "measurement" since it applies to many types of products (i.e., not just wearables). For example a bicycle has wheel and frame measurements, and a screw has gauge and thread-distance measurements.

Also science ... There are usually _at least_ three items of information involved:

1. The property being measured (waist, wheel diameter, density, concentration ...)
2. a number or category
3. a scale (unit of measurement) or reference-system

**Comment by iiic** [comment]
Hi all

I found i contradiction in this scheme's example… there is `QuantitativeValue` with reference https://schema.org/WearableMeasurementChest but that url doesn't exists it leads to 404.

It's because WearableMeasurementChest is missing in WearableMeasurementTypeEnumeration ( https://schema.org/WearableMeasurementTypeEnumeration ) or bad value in this example ?

**Comment by alex-jansen** [comment]
Good catch @iiic, this should have been https://schema.org/WearableMeasurementChestOrBust.

Fixed and created a merge request.
