### ISSUE TITLE
per-property term pages say 'subclass of' instead of 'subproperty of'

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2817]
@RichardWallis could you fix this? It's confusing for people. Properties aren't subclasses of anything. We use rdfs:subPropertyOf. Can you update the term page and/or infoblock to use the language of subproperties?

https://github.com/schemaorg/schemaorg/blob/main/templates/terms/InfoBlock.j2 and nearby...

**Comment by RichardWallis** [comment]
Fixed via 4aa2093
