### ISSUE TITLE
Add duration property to Episode

### ISSUE THREAD

**Issue by lucy-kind** [schemaorg/schemaorg#2820]
Add duration as a property of TVEpisode. duration takes Duration (the type) as value

**Comment by danbri** [comment]
Only TVEpisode? Not PodcastEpisode, RadioEpisode? Why not the supertype, Episode? https://schema.org/Episode ...?

**Comment by lucy-kind** [comment]
Good point! I've edited it to be attached to Episode instead

**Comment by akselinurmio** [comment]
Any updates on this? For example, type [Movie](https://schema.org/Movie)  already has `duration` property.

**Comment by philbarker** [comment]
@akselinurmio  Looks like it has been implemented but the issue not closed

**Comment by RichardWallis** [comment]
Indeed it has. https://schema.org/Episode

Closing now
