### ISSUE TITLE
inverse property for isBasedOn

### ISSUE THREAD

**Issue by renevoorburg** [schemaorg/schemaorg#2838]
We are in need of a property that is the owl:inverseOf for schema:isBasedOn . Such a property does not exist in schema, as of yet. A clear name for such a new property might be hasDerivative.

**Comment by dr-shorthair** [comment]
Why do you need an inverse property? 
You can just use the reverse triple in the data or query.

**Comment by renevoorburg** [comment]
> Why do you need an inverse property?
> You can just use the reverse triple in the data or query.
> 


In a sense, of course, inverse properties are never strictly required.

Inverse properties help our (thinking about http://data.bibliotheken.nl/) human users. They will make the published data better to read and understand.

For example, when a publication is digitized (scanned etc.), the (page about the) digitized version will show a link using 'isBasedOn' to the printed original.
Similarly, for the (page about the) printed orginal we would like to present a link to the derived digital publications. That is a pattern users of data.bibliotheken.nl expect.

Thanks, René
