### ISSUE TITLE
Alias "@id" to "id" ?

### ISSUE THREAD

**Issue by akuckartz** [schemaorg/schemaorg#286]
This was suggested by @msporny in https://github.com/json-ld/json-ld.org/pull/380#issuecomment-71382239 and https://github.com/json-ld/json-ld.org/pull/380#issuecomment-71392999

The other "@"-properties would be renamed as well.

I created the same issue here: https://github.com/HydraCG/Specifications/issues/95

**Comment by dbs** [comment]
Note that the actual suggestion by @msporny was:

> Any chance that you might alias "@id" -> "id", and "@type" -> "type" in the AS2 JSON-LD Context in the future?

"alias" is subtly but significantly different from "rename"!

**Comment by gkellogg** [comment]
Exactly, as @msporny said, the `@` keywords are intentional so that JSON-LD won't mess up someone's existing JSON serialization. But, when an application is expecting it, then aliasing keywords is often the right thing to do. And, for using with JavaScript `.id` is much more convenient than `["@id"]`.

The only keyword that can't be aliased is `@context`.

**Comment by danbri** [comment]
I am not aware of any major schema.org JSON-LD consumption actually using information from the @context file, so I'm wary of pushing such a change. Perhaps when/if JSON-LD consumer implementations mature this would be easier to roll out. For now I'm going to file this under "dim and distant future", although I appreciate that it has some aesthetic and practical appeal.

**Comment by danbri** [comment]
(I'll leave this open though as it is a reasonable request to revisit.)

**Comment by danbri** [comment]
If any other major JSON-LD -using vocabularies are aliasing @id and @type, it would be good to hear about it here.

**Comment by danbri** [comment]
done,

```
{
  "@context": {
        "type": "@type",
        "id": "@id",
```
