### ISSUE TITLE
/ProductGroup discussion link refers to the wrong page

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#2864]
I just noticed that on https://schema.org/ProductGroup the link to Github discussion is referring to the wrong issue. It's currently referring #2597, which should be #1797 instead.

**Comment by RichardWallis** [comment]
Fixed in commit bb43de6

**Comment by jvandriel** [comment]
I just noticed the link still refers to #2597 as opposed to #1797.

**Comment by RichardWallis** [comment]
It is fixed in the source and will appear in the next release
