### ISSUE TITLE
Email support for EventReservation deletion

### ISSUE THREAD

**Issue by kolya-kra** [schemaorg/schemaorg#2865]
The issue I am facing is not directly an issue with the Schema.org schemas but with the Schema.org support in emails. I am currently using schema.org `FlightReservations` and `HotelReservations` to create, update and delete calendar entries in Google Calendar by sending the schema.org markups via email. Now I would also like to use Schema.org `EventReservations` with Gmail and Google Calendar to automatically create, update and delete events in Google Calendar. Creating calendar entries from `EventReservations` is working but I can not update or delete existing event reservation calendar entries. I would like to know whether this is an issue from Gmail and whether updating and deleting `EventReservations` is still supported by Gmail and Google Calendar. I have not been able to find any statement from Google relating that issue.

This is the schema I was using to create and delete calendar event in Google Calendar:
```
{
  "@context": "http://schema.org",
  "@type": "EventReservation",
  "reservationNumber": "FIH101",
  "reservationStatus": "http://schema.org/Confirmed", //"http://schema.org/Cancelled" for deleting the event
  "underName": {
    "@type": "Person",
    "name": "John Smith"
  },
  "reservationFor": {
    "@type": "Event",
    "name": "Concert",
    "startDate": "2022-03-07T19:30:00-08:00",
    "location": {
      "@type": "Place",
      "name": "AT&T Park",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "24 Willie Mays Plaza",
        "addressLocality": "San Francisco",
        "addressRegion": "CA",
        "postalCode": "94107",
        "addressCountry": "US"
      }
    }
  }
}
```

**Comment by rrlevering** [comment]
This is not the right forum to ask a Google-specific schema use question.  I think you maybe want to ask at https://support.google.com/mail/community?
