### ISSUE TITLE
Syntax error unable to find

### ISSUE THREAD

**Issue by angeluisfc** [schemaorg/schemaorg#2866]
I'm trying to mark up several recipes as ItemList.
I've checked with Google tool but it's something wrong with the last "}".
Don't know what is it. If someone could help would be grate.
Thanks

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "ItemList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": "1",
      "item": {
        "@context": "https://schema.org/",
        "@type": "Recipe",
        "name": "YOGUR CON FRUTAS",
        "image": {
 			"type": "ImageObject" ,
 			"url": "https://cryomx.com/wp-content/uploads/2019/09/Yogur-con-frutas.jpg" ,
 			"height": "453",
 			"width": "680"
 		},       
 		"recipeIngredient":[
 			"1 taza de yogur natural bajo en grasa y azúcar" ,
 			"1 porción mediana de trozos de frutas de tu elección" ],
 		"description": "El yogur con frutas es una de las muchas opciones de desayuno para una dieta saludable. Es importante elegir un yogur sin azúcares y grasas. Así podrá formar parte de los desayunos saludables para dieta baja en grasas."		
		},
        },
    ],
},
</script>

**Comment by jvandriel** [comment]
The issue are the additional commas at the end (```}, }, ], },```).

If you remove them things are fine.

```
<script type = "application/ld+json">
{
  "@context":"https://schema.org",
  "@type":"ItemList",
  "itemListElement": 
  [
    {
      "@type":"ListItem",
      "position":"1",
      "item":
      {
        "@context":"https://schema.org/",
        "@type":"Recipe",
        "name":"YOGUR CON FRUTAS",
        "image":
        {
          "type":"ImageObject",
          "url":"https://cryomx.com/wp-content/uploads/2019/09/Yogur-con-frutas.jpg",
          "height":"453",
          "width":"680"
        },
        "recipeIngredient":
        [
          "1 taza de yogur natural bajo en grasa y azúcar",
          "1 porción mediana de trozos de frutas de tu elección"
        ],
        "description":"El yogur con frutas es una de las muchas opciones de desayuno para una dieta saludable. Es importante elegir un yogur sin azúcares y grasas. Así podrá formar parte de los desayunos saludables para dieta baja en grasas."
      }
    }
  ]
}
</script>
```

**Comment by RichardWallis** [comment]
You have unnecessary trailing commas after arrays or lists of elements.

This is a working version - I have also removed the unnecessary second ```@context``` statement.
```
<script type="application/ld+json">
{
	"@context": "https://schema.org",
	"@type": "ItemList",
	"itemListElement": [
		{
			"@type": "ListItem",
			"position": "1",
			"item": {
				"@type": "Recipe",
				"name": "YOGUR CON FRUTAS",
				"image": {
					"type": "ImageObject",
					"url": "https://cryomx.com/wp-content/uploads/2019/09/Yogur-con-frutas.jpg",
					"height": "453",
					"width": "680"
				},
				"recipeIngredient": [
					"1 taza de yogur natural bajo en grasa y azúcar",
					"1 porción mediana de trozos de frutas de tu elección"
				],
				"description": "El yogur con frutas es una de las muchas opciones de desayuno para una dieta saludable. Es importante elegir un yogur sin azúcares y grasas. Así podrá formar parte de los desayunos saludables para dieta baja en grasas."
			}
		}
	]
}
</script>```

**Comment by angeluisfc** [comment]
Many thanks!!!!
I've tried this mark up and it works.
However, I've to wait in order to see how it works on "real life" after Google crawled the URL again:
Any suggestion is welcome!

<script type="application/ld+json">
  | {
  | "@context": "https://schema.org",
  | "@type": "ItemList",
  | "itemListElement": [
  | {
  | "@type": "ListItem",
  | "position": "1",
  | "item": {
  | "@context": "https://schema.org/",
  | "@type": "Recipe",
  | "name": "YOGUR CON FRUTAS",
  | "url": "https://cryomx.com/desayunos-para-adelgazar/#YOGUR-CON-FRUTAS",
  | "image": {
  | "type": "ImageObject" ,
  | "url": "https://cryomx.com/wp-content/uploads/2019/09/Yogur-con-frutas.jpg" ,
  | "height": "453",
  | "width": "680"
  | },
  | "recipeIngredient":[
  | "1 taza de yogur natural bajo en grasa y azúcar" ,
  | "1 porción mediana de trozos de frutas de tu elección" ],
  | "description": "El yogur con frutas es una de las muchas opciones de desayuno para una dieta saludable. Es importante elegir un yogur sin azúcares y grasas. Así podrá formar parte de los desayunos saludables para dieta baja en grasas."
  | }
  | },
  | {
  | "@type": "ListItem",
  | "position": "2",
  | "item": {
  | "@context": "https://schema.org/",
  | "@type": "Recipe",
  | "name": "SMOOTHIE DE PLÁTANO CON AVENA",
  | "url": "https://cryomx.com/desayunos-para-adelgazar/#SMOOTHIE-DE-PLATANO-CON-AVENA",
  | "image": {
  | "type": "ImageObject" ,
  | "url": "https://cryomx.com/wp-content/uploads/2019/09/Smoothie-de-platano.jpg" ,
  | "height": "453",
  | "width": "680"
  | },
  | "recipeIngredient": [
  | "1 plátano natural",
  | "1 puño de frutos rojos",
  | "350 mililitros de leche baja en grasa o vegetal",
  | "1 cucharada de semillas de chía",
  | "3 cucharadas de copos de avena",
  | "Una cucharada de miel para endulzar"],
  | "description": "El smoothie de plátano con avena es una receta sencilla y práctica. Lo mejor de todo es que es muy económica y deliciosa. Es de fácil digestión y nos ayuda a saciarnos y darle a nuestro cuerpo el potasio que necesita."
  | }
  | },
  | {
  | "@type": "ListItem",
  | "position": "3",
  | "item": {
  | "@context": "https://schema.org/",
  | "@type": "Recipe",
  | "name": "CEREALES INTEGRALES CON FRUTAS",
  | "url": "https://cryomx.com/desayunos-para-adelgazar/#CEREALES-INTEGRALES-CON-FRUTAS",
  | "image": {
  | "type": "ImageObject" ,
  | "url": "https://cryomx.com/wp-content/uploads/2019/09/Cereales-integrales.jpg" ,
  | "height": "453",
  | "width": "680"
  | },
  | "recipeIngredient": [
  | "1 taza de cereales integrales sin azúcar",
  | "1 puño de frutos rojos",
  | "1 taza de leche baja en grasas o vegetal",
  | "1 cucharada de miel"],
  | "description": "Si queremos incluir en nuestra dieta desayunos saludables los cereales integrales son una gran opción. Son deliciosos, aportan muchas vitaminas y nos ayudan a saciar el hambre."
  | }
  | },
  | {
  | "@type": "ListItem",
  | "position": "4",
  | "item": {
  | "@context": "https://schema.org/",
  | "@type": "Recipe",
  | "name": "TOSTADA CON AGUACATE Y QUESO FRESCO",
  | "url": "https://cryomx.com/desayunos-para-adelgazar/#TOSTADA-CON-AGUACATE-Y-QUESO-FRESCO",
  | "image": {
  | "type": "ImageObject" ,
  | "url": "https://cryomx.com/wp-content/uploads/2019/09/Tostada-de-aguacate.jpg" ,
  | "height": "453",
  | "width": "680"
  | },
  | "recipeIngredient": [
  | "1 tostada pan integral",
  | "3 rodajas de aguacate fresco",
  | "50 gramos de queso fresco",
  | "1 chorrito de aceite de oliva extra virgen"],
  | "description": "Las tostadas de pan integral con aguacate y queso fresco es uno de los desayunos para adelgazar preferidos de muchos. El aguacate es rico en ácido fólico y nos ayuda a reducir el colesterol. Por otra parte, es rico en grasas saludables."
  | }
  | },
  | {
  | "@type": "ListItem",
  | "position": "5",
  | "item": {
  | "@context": "https://schema.org/",
  | "@type": "Recipe",
  | "name": "OMELETTE DE ESPINACAS Y QUESO PANELA",
  | "url": "https://cryomx.com/desayunos-para-adelgazar/#OMELETTE-DE-ESPINACAS-Y-QUESO-PANELA",
  | "image": {
  | "type": "ImageObject" ,
  | "url": "https://cryomx.com/wp-content/uploads/2019/09/Omelette-de-espinacas.jpg" ,
  | "height": "453",
  | "width": "680"
  | },
  | "recipeIngredient": [
  | "2 huevos enteros o 3 claras de huevos",
  | "60 gramos de espinacas",
  | "50 gramos de queso panela",
  | "Un chorrito de aceite de oliva extra virgen"],
  | "description": "El omelette de espinacas y queso panela es un gran desayuno para dieta baja en grasas. Lo mejor es que es uno de los desayunos más ricos en proteínas y libre de hidratos de carbono."
  | }
  | },
  | {
  | "@type": "ListItem",
  | "position": "6",
  | "item": {
  | "@context": "https://schema.org/",
  | "@type": "Recipe",
  | "name": "HUEVOS REVUELTOS CON CHAMPIÑONES",
  | "url": "https://cryomx.com/desayunos-para-adelgazar/#HUEVOS-REVUELTOS-CON-CHAMPINONES",
  | "image": {
  | "type": "ImageObject" ,
  | "url": "https://cryomx.com/wp-content/uploads/2019/09/Huevos-revueltos.jpg" ,
  | "height": "453",
  | "width": "680"
  | },
  | "recipeIngredient": [
  | "2 huevos",
  | "1/2 taza de champiñones",
  | "1 chorrito de aceite de oliva"],
  | "description": "Unos huevos revueltos con champiñones pueden ser los mejores aliados que nos ayuden a perder los kilitos que tenemos de más. Los champiñones contienen mucha fibra y pocas calorías, por lo que estaremos satisfechos sin excedernos."
  | }
  | }
  | ]
  | }
  | </script>
