### ISSUE TITLE
Potential problem with @Dataset/property

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#2868]
`@Dataset/property` has expected type `@DataDownload`

`@DataDownload` is a subClass of `@MediaObject` and has one property: `measurementTechnique`

In order to annotate `@DataDownload` with properties such as `contentUrl` and `encodingFormat`, we must use properties from `@MediaObject`

so we have these triples:
`@Dataset distribution @Datadownload`
`@DataDownload encoding @MediaObject`

However, when we define a *specific, reusable* @MediaObject with target properties (contentUrl and encodingFormat), GSDTT does not accept the @MediaObject properties.

Instead, GSDTT requests that target properties (contentUrl and encodingFormat) be linked directly on `@DataDownload`.

Does schema.org disallow a superClass (e.g. `@MediaObject`) to link with its subClass (`@DataDownload`)?

We don't see any other pattern to define @MediaObject once and then reuse it for an `@Dataset` using the property `distribution`.

**Comment by RichardWallis** [comment]
As [DataDownload](https://schema.org/DataDownload) is a subType of [MediaObject](https://schema.org/MediaObject) you can use the combined properties of it and its super types.  No need to link to an encoding of what is already effectively an encoding of the [DataSet](https://schema.org/Dataset).
eg.
```
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Dataset",
    "name": "Interesting Data",
    "description": "A collection of interesting data",
    "distribution": [
        {
            "@type": "DataDownload",
            "name": "Interesting Data (CSV Format)",
            "encodingFormat": "text/csv",
            "contentUrl": "http://example.com/downloads/InterestingData.csv"
        },
        {
            "@type": "DataDownload",
            "name": "Interesting Data (XML Format)",
            "encodingFormat": "text/xml",
            "contentUrl": "http://example.com/downloads/InterestingData.xml"
        }
    ]
}
</script>
```

**Comment by jaygray0919** [comment]
@RichardWallis Right you are Richard. We got caught up in our knickers trying to reuse a structure. Thank you for the polite reminder :->
/jay
