### ISSUE TITLE
Write down that Event.endDate is the non-inclusive end

### ISSUE THREAD

**Issue by dilyanpalauzov** [schemaorg/schemaorg#2874]
https://ips-bas.org/2021/01/21/покана-за-участие-в-международна-науч/ describes an event “Refugees – Fears, Understanding, Empathy”, which happens on 17th March 2021.  This event is mapped to an iCalendar file: https://aaa.bapha.be/c/4/bfc7c227-834c-4fc1-b23f-1b961ff173f7.ics .  The file contains:
```
BEGIN:VEVENT
SUMMARY:Refugees – Fears\, Understanding\, Empathy
DTSTART;VALUE=DATE:20210517
DTEND;VALUE=DATE:20210518
END:VEVENT
```

Per RFC 5545 DTSTART is the inclusive start and DTEND is the non-inclusive end.  The above event file reflects that the event is on 17th May and not 18h May 2021.

From the iCalendar file another file is generated https://aaa.bapha.be/s/4/bfc7c227-834c-4fc1-b23f-1b961ff173f7.ics_en.html which contains structured data:

```iCalendar
"startDate":"2021-05-17T00:00:00+0300",
"endDate":"2021-05-18T00:00:00+0300",
```

I am currently in Timezone UTC+3.  When I search in Google for the event, G. shows:
![ref-google](https://user-images.githubusercontent.com/4992947/116807294-0fb6f200-ab3b-11eb-9672-08752e3f8d24.png)

so it prints as dates 17 and 18th May.

https://schema.org/Event defines the fields:

* endDate - type: Date or DateTime - The end date and time of the item (in ISO 8601 date format).
* startDate - type: Date or DateTIme - The start date and time of the item (in ISO 8601 date format).

Please extend the definition of endDate and startDate, by stating that endDate is the non-inclusive end and and startDate is the inclusive start.

I could in theory map the iCalendar file to "startDate":"2021-05-17", "endDate": "2021-05-18", but this will not help further: it is still unclear, whether "endDate": "2021-05-18",  is the inclusive or non-inclusive end.

**Comment by rrlevering** [comment]
This is mostly about Google's visual treatment, I believe.  You should probably question their forums for that display.  The interpretation might be assuming a non-inclusive end and just be a visual quirk of using midnight as the end time.  For instance, if the event was more granular it would not be considered incorrect to write May 17 3-5pm.   In that case, the end time is being used in the display even though it's assumed by the viewer that 5pm is not part of the time.  As an alternative workaround, you might be able to specify the more specific times of the event (which likely doesn't actually run until midnight) and likely get a better visual treatment.

**Comment by dilyanpalauzov** [comment]
The defininion of endDate is imprecise.  For `"startDate":"2021-05-17", "endDate": "2021-05-18"` it is not well-defined, if the event lasts one or two days.

To resolve this, I am asking to write down, that endDate is the non-inclusive end.
