### ISSUE TITLE
Locality for OfflineEventAttendanceMode

### ISSUE THREAD

**Issue by UtopiaOpera** [schemaorg/schemaorg#2875]
Suggestion for OfflineEventAttendanceMode to pertain to an audience in a locality and or group. For example, online dating events would target an audience locality and wouldn't be something of interest by people globally. Maybe a sub cat of onlineMeeting / videoConference / onlineGroupEvent / onlineVideoGathering and location options.

**Comment by jvandriel** [comment]
```Event``` has an 'audience``` property you can use for that, e.g.

```
{
  "@context":"https://schema.org",
  "@type":"Event",
  "name":"Date night",
  "audience":
  {
    "@type":"Audience",
    "name":"Singles",
    "geographicArea":
    {
      "@type":"City",
      "name":"New York"
    }
  }
}
```

Does this suffice for your intended purposes?
