### ISSUE TITLE
Additional FlightReservation -related properties

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#288]
http://schema.org/FlightReservation

It has been suggested that additional properties around FlightReservation (or on Ticket, Airline etc.) would improve the usefulness of our flight reservations vocabulary. @vholland has been working on a specific proposal.

**Comment by vholland** [comment]
I have added some properties related to boarding passes at https://github.com/vholland/schemaorg/commit/b8f85c9e0a3c4816b8b5625dd2516b69ab200980.

Specifically, the proposed new properties on FlightReservation are:

passengerSequenceNumber: The passenger's sequence number as assigned by the airline.

passengerPriorityStatus: The priority status assigned to a passenger for security or boarding (e.g. FastTrack or Priority).

securityScreening: The type of security screening the passenger is subject to.

And on Airline:

boardingPolicy: The type of boarding policy used by the airline (e.g. zone-based or group-based).

**Comment by vholland** [comment]
See pull request https://github.com/schemaorg/schemaorg/pull/324/files

**Comment by tmarshbing** [comment]
@vholland, what is the difference between the existing http://schema.org/boardingGroup property and the proposed passengerSequenceNumber property?

Also, can you update the examples to show the usage of the new properties?

**Comment by vholland** [comment]
boardingGroup is something like "Group A" or "Zone 1" which determines the order people board the plane.

The passengerSequenceNumber is a unique identifier the airline uses for the passenger.

I'll update the examples as well.

**Comment by tmarshbing** [comment]
OK, thanks. I guess I don't travel enough. I hadn't seen (or noticed) the unique ID for a passenger before.

**Comment by vholland** [comment]
The [pull request](https://github.com/schemaorg/schemaorg/pull/324/files) has expanded examples.

I also incorporated @chaals suggestion to not try to enumerate the security screening programs. The securityScreening property now expects Text.

**Comment by chaals** [comment]
Looks good to me.

**Comment by vholland** [comment]
Merged into sdo-gozer.
