### ISSUE TITLE
Proposal to expand support for product return policies

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#2880]
**Context** - This is a proposal from Google based on our experience consuming schema.org /[MerchantReturnPolicy](https://schema.org/MerchantReturnPolicy) markup and working with similar data from online merchants. If it were accepted, it would make it easier for us and others to understand eCommerce return policies.

### **Introduction**

Schema.Org currently supports a limited subset of product return policies through type /[MerchantReturnPolicy](https://schema.org/MerchantReturnPolicy). Certain return policies that are common in the industry are not supported through this type, for example product returns to a different country than the shipping country, restocking fees, and different fees based on item condition (unopened or used). We therefore propose to add a few additional types and properties for a more comprehensive coverage of common return policies in the eCommerce industry.

### **Proposal**

We propose to expand schema.org with a few enumeration types and new properties:

*   Support for more return methods, through a new enumeration /_ReturnMethodEnumeration_, with values such as /_ReturnByMail_, /_ReturnInStore_, and /_ReturnAtKiosk_. 
*   Support for different types of return labels through a new enumeration /_ReturnLabelSourceEnumeration_, with values such as /_ReturnLabelDownloadAndPrint_, /_ReturnLabelInBox,_ /_ReturnLabelCustomerResponsibility_
*   Add additional types of return fees to existing enumeration /_ReturnFeesEnumeration_, with common values such as  /_ReturnFeesCustomerResponsibility_ and /_FreeReturn_.

We will use these new enumerations and values to add a few new properties related to return methods, fees, and labels for use on existing type /[MerchantReturnPolicy](https://schema.org/MerchantReturnPolicy):

**<span style="text-decoration:underline;">Return methods</span>**

*   /_returnMethod_ of (new) type /_ReturnMethodEnumeration_. This improves on the existing more limited Boolean /[inStoreReturnsOffered](https://schema.org/inStoreReturnsOffered).
*   /_returnPolicyCountry_ of (existing) type /[Country](https://schema.org/Country) to allow the specification of a country where the return has to be sent to.

**<span style="text-decoration:underline;">Return fees</span>**

*   /_itemDefectReturnFee_ of type /_ReturnFeeEnumeration_ to specify return fees for defect products.
    *   With corresponding property _/itemDefectReturnShippingFeeAmount_ of type /[MonetaryAmount](https://schema.org/MonetaryAmount), to be provided when /_itemDefectReturnFee_ has value /_ReturnShippingFee_
*   /_customerRemorseReturnFee_ of type /_ReturnFeeEnumeration_, to specify return fees for products returned due to customer remorse.
    *   With corresponding property /_customerRemorseReturnShippingFeeAmount_ of type /[MonetaryAmount](https://schema.org/MonetaryAmount), to be provided when _/customerRemorseReturnFee_ has value /_ReturnShippingFee_
*   /_restockingFee_ of type /[MonetaryValue](https://schema.org/MonetaryAmount) to represent a fixed restocking fee, or of type /[Number](https://schema.org/Number) to represent a percentage of the paid product price.
*   [/itemCondition](https://schema.org/itemCondition) of type [/OfferItemCondition](https://schema.org/OfferItemCondition) to specify the condition of the item accepted for returns, for example /[NewCondition](https://schema.org/NewCondition), [DamagedCondition](https://schema.org/DamagedCondition), or /[UsedCondition](https://schema.org/UsedCondition).

**<span style="text-decoration:underline;">Return labels</span>**

*   /_itemDefectReturnLabelSource_ of type /_ReturnLabelSourceEnumeration_ to specify how the customer can get a return label for defect items.
*   /_customerRemorseReturnLabelSource_ of type /_ReturnLabelSourceEnumeration_ to specify how the customer can get a return label for products returned due to customer remorse.

### **Other additions**

In addition to the just proposed new properties and types related to return methods, fees, and labels, we have also seen that it is common in the industry to have different return policies during holiday periods. We therefore also propose to allow merchants to specify such seasonal overrides through a new property /_returnPolicySeasonalOverride_ of new type /_MerchantReturnPolicySeasonalOverride_ on type /[MerchantReturnPolicy](https://schema.org/MerchantReturnPolicy) with the following existing properties:

*   [/returnPolicyCategory](https://schema.org/returnPolicyCategory)
*   [/merchantReturnDays](https://schema.org/merchantReturnDays), for use when [returnPolicyCategory](https://schema.org/returnPolicyCategory) equals [MerchantReturnFiniteReturnWindow](https://schema.org/MerchantReturnFiniteReturnWindow). 
    *   we propose to add [Date](https://schema.org/Date) and [DateTime](https://schema.org/DateTime) to the range of [/merchantReturnDays](https://schema.org/merchantReturnDays) to allow for fixed latest return dates.
    *   For the existing range of [Integer](https://schema.org/Integer) we propose to change the definition to the number of days from the delivery date (instead of from the purchase date).
*   [/startDate](https://schema.org/startDate)
*   [/endDate](https://schema.org/endDate)

Finally, to increase flexibility related to return policies we also propose to add property [/additionalProperty](https://schema.org/additionalProperty) to [/MerchantReturnPolicy](https://schema.org/MerchantReturnPolicy) to allow for generic or custom return-policy related fields.

**Comment by alex-jansen** [comment]
Completed as part of Version 13.

**Comment by JessycaFrederick** [comment]
I would like to request a new field under /ReturnMethodEnumeration

Why: Online stores selling alcohol in the United States cannot legally accept returns by mail, however many offer store credit for bottles the customer doesn't want or like. It's a return without having to return the product.

At present, there is no way to communicate this accurately with schema.

/RefundTypeEnumeration has the StoreCredit part, but we need a corresponding value for /ReturnMethodEnumeration that supports a return method of "keep the product." 

I realize this is a strange corner case, but there are 1000s of online merchants selling alcohol in the US.

**Comment by alex-jansen** [comment]
That sounds reasonable! I will try to include that into the next Schema.org release.
