### ISSUE TITLE
Schema Markup Validator highlights erroneous errors on first load of XHTML document

### ISSUE THREAD

**Issue by acabal** [schemaorg/schemaorg#2908]
Not sure if this is the right place to report validator bugs. If there's a better place I'm happy to move this issue there.

When attempting to validate an XHTML document, on the first load the schema validator marks `<meta>` elements with `@property` in the `og:` or `twitter:` namespace as errors, and refuses to display any results. However, if you make any immaterial edit to the code window (for example, place a newline or a space somewhere), then press the "validate" button, the validator correctly clears the errors and displays the schema results.

Here's a picture after loading https://standardebooks.org/ebooks/theodore-dreiser/an-american-tragedy (served as `application/xhtml+xml`). Note that the validator has marked `<meta property="og:title">` and other similar `<meta>` elements as errors and no schema information is displayed.

![before](https://user-images.githubusercontent.com/866144/122430016-d86c9b00-cf58-11eb-9f0e-e7933c12c27f.png)

Here's a picture after adding a newline after `<head>` directly into the editor window, then pressing the `validate` button:

![after](https://user-images.githubusercontent.com/866144/122430104-eae6d480-cf58-11eb-9fd9-97e965babde9.png)

**Comment by danbri** [comment]
Thanks! This is a fine place for now, we'll have to figure out a workflow.

**Comment by acabal** [comment]
In this case, the book *is* the webpage--it is the browser-friendly HTML representation of the actual unzipped contents of the corresponding book epub file, and drilling down deeper into its file hierarchy exposes the book's textual contents as they are laid out in the epub itself. In theory one could send a request to that URL with `Accept: application/epub+zip` and get the epub file as the response (though this is not implemented).

**Comment by thadguidry** [comment]
Agree with @danbri and also I don't think there is anything inherently wrong with also using multi-typing and saying that a webpage is a Book and WebPage.  Both are CreativeWorks.  Tons of more specific subtypes under [CreativeWork](https://schema.org/CreativeWork)

**Comment by rrlevering** [comment]
Luckily we don't have to have this argument at all.  This clearly is a bug regardless of whether we think webpages are the entities they contain/reference.

**Comment by danbri** [comment]
@rrlevering I was deliberately not going down that tedious rathole! Books are special in a way that they're broadly the same sort of thing as web content, whereas restaurants, cities, people etc are clearly not. Anyway yeah let's focus on the bug.

**Comment by acabal** [comment]
> Does using
> 
> `<article class="ebook" typeof="schema:Book" about="/ebooks/theodore-dreiser/an-american-tragedy#item">`
> 
> fix the behaviour?

Yes, adding a hash to `@about` does seem to work (both `#item` and `#test` worked). But is that something we want to do be doing as a correct implementation of a schema? (I don't actually know)
