### ISSUE TITLE
Upgrade playerType values

### ISSUE THREAD

**Issue by Maxou44** [schemaorg/schemaorg#2913]
Hello,

The VideoObject contains a field "playerType", the documentation indicates that we can use "Flash or Silverlight", maybe it could be nice to add the "HTML5" value to the list (used by Youtube and other video providers)?

It could be interesting to change the Text type by an Enum to make detection easier by external parsers

https://schema.org/VideoObject

Have a great day,
Maxime

**Comment by chrisspradling1980** [comment]
I'm curious to how resolve(?) or perhaps a resolution HTML4 closure may
intercept the HTML5 ease of usage contextual mark up has had in Schema.
