### ISSUE TITLE
Normalize CreativeWork Play

### ISSUE THREAD

**Issue by WeaverStever** [schemaorg/schemaorg#2918]
Condensing the discussion on "Persons engaged in TheaterEvents #503'" as a proposal for the next release. 

**Problem**
The pending type (https://schema.org/Play) has no independent properties that you would expect to find for a play: director, actor, productionCompany, musicBy, trailer, beginDate, endDate.

**The following types have similar specific properties that are missing from Play:**
Clip
CreativeWorkSeason
Episode
MovieSeries
RadioSeries
TVSeries

The additional properties are needed so that the person offering the metadata can describe a collection of **past** events (aka a production), for inclusion in a contributing artist's resume or CV without having to supply irrelevant (or unavailable) data associated with a pending Event.

Google Rich Snippets and Wikidata appear to understand the Event (type) to be pending at some future time -- in the context of an opportunity to attend still exists.  In WikiData, a past event would be more accurately described as an occurrence.

**Proposed solution:**

Thing > CreativeWork > Play should be similar to "Thing > CreativeWork > Movie", available as a top-level type and not be required to have TheaterEvent or BroadcastEvent as a parent type (just to be able to include the actor property). 

Additionally, because the singular and the plural for "play" is often the same word, Play should be listed as a "more specific type" of CreativeWorkSeries.  

Inclusion in CreativeWorkSeries for disambiguation between a performance in a production and a collection of performances within a production.  (It is not uncommon for a production of a play to also be described as production(s) when performed or engaged in different locations. I.e. the Boston production of _CATS_)

Specific types for CreativeWorkSeries are currently:

BookSeries
MovieSeries
Periodical
PodcastSeries
RadioSeries
TVSeries
VideoGameSeries

Similar to Periodical, a separate instance of "PlaySeries" would not be required if startDate and endDate are included as specific properties within Play -- so the type covers both the singular and plural understanding of the word.

Related discussion:
**Persons engaged in TheaterEvents #503**

A very similar problem addressed and closed last month  (by adding specific properties to the type).
**Expect existing 'actor' property on existing PodcastSeries #2896**

**Comment by WeaverStever** [comment]
Similar issue here #2961

**Comment by thadguidry** [comment]
I've also sent feedback (3rd time now) to Google to get "Plays" added as a filter option on their Events search:

![image](https://user-images.githubusercontent.com/986438/150457870-076373ed-ffae-4bed-9dac-b3e5abe014b5.png)

**Comment by WeaverStever** [comment]
@thadguidry 
I did a deep dive as to why Google seems to ignore structured data in their shows / events sections.  What I found is that YouTube (aka Google) is partnered with certain ticket vendors AXS, Eventbrite, SeeTickets, Ticketmaster, DICE.  
https://support.google.com/youtube/answer/7570245?hl=en

Basically, if your event is not ticketed with one of the above vendors, you won't see the event on Google's shows / events section, it is quite possible that Plays are already supported by Google, but most venues handle their own ticketing.

What I saw some evidence of was competing businesses using structured data to advertise non-existent events at competitor's businesses. The targeted business owner would complain to Google, so Google needed a better way to identify legitimate events.  Sadly, unless the event is ticketed with one of the Google / YouTube partners, I don't think structured data does anything.  (I advise my artists to take the gig that is ticketed with one of the partner vendors if they have a choice.)

**Comment by WeaverStever** [comment]
Giving this a bump.  https://schema.org/Play still has no native properties Properties.

Play should probably have similar properties to https://schema.org/MovieSeries

**Comment by WeaverStever** [comment]
Bump
https://schema.org/Play has no native properties, only Creativework and Thing.  

https://schema.org/Play should probably have similar properties to https://schema.org/MovieSeries

**Comment by WeaverStever** [comment]
It appears that Rich Result Test no longer penalizes (past) Events that do not contain Offers (warning only). 
 The https://schema.org/TheaterEvent will work for describing a past performance or collection of performances as long as the Event type does not "require" the Offers property.
