### ISSUE TITLE
ItemAvailability CustomMade type

### ISSUE THREAD

**Issue by dustcrawler** [schemaorg/schemaorg#2926]
Our company sells products that are in stock but we also make custom made products. I can't seem to find the proper schema type. Is there any and if not can it be added? I'm talking about this list (https://schema.org/ItemAvailability). Thanks in advance.

**Comment by alex-jansen** [comment]
This seems related to the request in #3183, would a new enumeration value `MadeToOrder` work for this scenario?

**Comment by alex-jansen** [comment]
Added [MadeToOrder](https://schema.org/MadeToOrder) to Release 28.0, so closing as completed.
