### ISSUE TITLE
What is the Id in the local business schema structure data 

### ISSUE THREAD

**Issue by Muhaiyuddin** [schemaorg/schemaorg#2930]
I want to add schema structure data for my business but I don't know what to fill in the Id url and url section `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "name": "",
  "image": "",
  "@id": "what should I write here",
  "url": "what should I write here",
  "telephone": "",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "",
    "addressLocality": "",
    "postalCode": "",
    "addressCountry": ""
  }  
}
</script>`

Help me out in this issue

**Comment by JasmineDWillson** [comment]
Hello! Generally speaking, both the @id and the URL should be the canonical URL of the homepage for the site that represented the business.

Here's an example:
`<script type="application/ld+json"> { "@context": "https://schema.org", "@type": "LocalBusiness", "name": "", "image": "", "@id": "https://thisismybusiness.com/", "url": "https://thisismybusiness.com/", "telephone": "", "address": { "@type": "PostalAddress", "streetAddress": "", "addressLocality": "", "postalCode": "", "addressCountry": "" } } </script>`

Google also recently announced that the @id is no longer required for Local Business markup, noting "The url property alone is a sufficient identifier to understand the local business."
Source: https://developers.google.com/search/updates#july-2021

**Comment by WeaverStever** [comment]
The @id field is useful for describing which part of the page your markup describes.  

For the root, or the entirety of the page,
(This is the way the Yoast schema plugin handles the id for root of the page)
~~~~
<script type="application/ld+json"> 
{ "@context": "https://schema.org",
   "@type": "LocalBusiness", 
   "@id": "https://thisismybusiness.com/#", 
   "url": "https://thisismybusiness.com/", 
   ...
} </script>
~~~~
For a section on the same page that describes your product, 
~~~~
<script type="application/ld+json"> 
{ "@context": "https://schema.org",
   "@type": "Product", 
   "@id": "https://thisismybusiness.com/#myproduct", 
   "url": "https://thisismybusiness.com/", 
   ...
} </script>
~~~~

In the case of a section of a page, it is defined by its id and the @id corresponds to the "anchor" on the page.
~~~~
<div id="myproduct">
    <p> my product details</p>
</div>
~~~~

**Comment by WeaverStever** [comment]
Also, 

If you are getting schema markup from another source (perhaps an Event plugin), if that markup is missing some (required) properties and has an @id, you can provide more extensive on-page markup and merge the two using the same @id property.

If the @id is missing, or if you don't use it in your local script, the SDTT will display two separate scripts for the same event.

**Comment by Muhaiyuddin** [comment]
Thanks @JasmineDWillson @WeaverStever
