### ISSUE TITLE
Support contributor roles for CreativeWork

### ISSUE THREAD

**Issue by gjvnq** [schemaorg/schemaorg#2931]
A simple way to do this would be to have a ```Contributor```  class (to be used in attributes like ```author```, ```contributor``` and ```creator```) with the following properties:

  * ```who```: a ```Person``` or ```Organization```.
  * ```roles```: an array of URIs for the role. Usually one of the following:
    * An UUID for the [Contributor Roles Taxonomy](http://credit.niso.org), e.g.: ```urn:uuid:0c8ca7d4-06ad-4527-9cea-a8801fcb8746``` for supervisor.
    * A [Library of Congress relator](https://id.loc.gov/vocabulary/relators.html), e.g.: ```http://id.loc.gov/vocabulary/relators/tyg``` for typographer
  * ```details```: text description explaining what the contributor did.

A more sphisticated way to handle this is to create a ```Contribution``` class that contains the following attributes:

  * ```who```: a ```Person``` or ```Organization```.
  * ```role```: same as ```role``` of ```Contributor``` but a single value instead of an array.
  * ```part```: URI or text specifying what part of the larger work this contribution applies to (e.g. a specific chapter).
  * ```details```: text description explaining what this contribution is about did.

Crucially, if a person does more than one thing, they have multiple ```Contribution``` instances instead of a single ```Contributor``` one.

**Comment by WeaverStever** [comment]
This could have interesting uses in the music industry. In many cases a contributor will accept a portion of the residual in lieu of payment.

It could be useful for clarifying the ownership relationship...

- Contribution for hire? (currency and amount)
- Contribution for partnership? (percent)
- Contribution for philanthropy? (disclosure of possible conflicts of interest)

**Comment by gjvnq** [comment]
I am not sure that having this kind of financial info fits with schema.org idea.

As for the conflict of interests, a simple URL could be placed in a ```confilctOfInterest``` attribute of ```CreativeWork```.

**Comment by WeaverStever** [comment]
@gjvnq 

Just bringing it up for completeness.  These could be left out of the declaration and used internally.  It would be good to work toward a JSON schema definition for music publishing, The data definitions they are currently using are from the Cobol era, circa 1970s,

**Comment by gjvnq** [comment]
Makes sense.

**Comment by RichardWallis** [comment]
The 'contributor' concept in Schema.org has evolved from vocabularies such as Dublin Core and bibliographic vocabularies.

It broadly identifies who contributed [creative] content to a CreativeWork. (author, director, artist, etc.).  Financial contribution to a project etc. is a different issue.
