### ISSUE TITLE
hasOccupation for Role?

### ISSUE THREAD

**Issue by activey** [schemaorg/schemaorg#2932]
Hi,

I'm sorry if this question already occured but I'm having problems with understanding what documentation is saying about "hasOccupation" attribute. According to it, this attribute should allow both Role and Occupation: "The Person's occupation. For past professions, use Role for expressing dates." while it can only accept Occupation type: "Values expected to be one of these types: Occupation".

I'm trying to model it in Java but this one blocks me here ...

Many thanks for any help here,
Lukasz

**Comment by activey** [comment]
This is exactly the example I'm refering to :) I cannot use Role for hasOccupation property because documentation clearly states that it has to be of type Occupation, not Role. So what is wrong here - documentation or example? Still you can clearly see that Occupation has no common denominator with Role. Thanks

**Comment by RichardWallis** [comment]
Ah, I see your confusion.

As mentioned [in the documentation](https://schema.org/docs/datamodel.html#conformance) Role is a type, as are URL & Text, that is acceptable value for any property.

[Previous discussions](https://github.com/schemaorg/schemaorg/issues/2787#issuecomment-743094648) have addressed the confusion this causes.  Potentially some more subclasses of Role need creating, plus being more specific as to their use.  As yet, a specific proposal has to be developed and actioned.

**Comment by activey** [comment]
Oh, ok, I'm sorry I'm not super familiar the way how schema.org works but does that mean that when looking at documentation for this property: https://schema.org/hasOccupation we can say that it can hold value of any type no matter what "Values expected to be one of these types" says?

**Comment by RichardWallis** [comment]
We can say that it can hold a value of one of the defined expected type(s), or a URL, Text, or Role (which includes a hasOccupation property)

**Comment by activey** [comment]
Ok sorry, maybe I just can't express my problem properly hehe, here is the screenshot to picture it:

![image](https://user-images.githubusercontent.com/1751891/127893406-b952065e-650b-41da-889b-e210b34583d6.png)

As you can see expected type is only one - Occupation, so how is it possible it is valid to have @type = Role instead?

**Comment by activey** [comment]
Or is it all about that Role is a "special kind" of class wrapping any other inside? :/

**Comment by philbarker** [comment]
@activey yep, Role is "special". That said I don't think it would hurt to add it to the expected range of the properties where you would most expect to see it used.

**Comment by RichardWallis** [comment]
@philbarker That, and potentially adding some appropriate subclasses of Role, are what the previous discussions were about.

**Comment by activey** [comment]
Ok, I think I get it now, thanks for the clarification :)
