### ISSUE TITLE
A new subtype of TVEpisode: TVStandalone

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#2940]
### Discussed in https://github.com/schemaorg/schemaorg/discussions/2939

Entity Type: TVStandalone

Intended purpose: Capture standalone/one-off shows that don't fit into the traditional TVSeries/TVEpisode/TVSeason model: breaking news, election specials, documentary specials, TVShows with just 1 episode such as Frosty The Snowman, any other standalone TV episode that doesn’t connect to any TVSeries as such.

This is a proposal from Google as a means to help identify and better handle such special television broadcast content.

**Comment by RichardWallis** [comment]
Would this not be handled in a simpler way by introducing a boolean property for the [Episode](https://schema.org/Episode) Type of 'standaloneEpisode' with a suitable description.

That way it would not be constraining the description of standalone shows to only TV shows.  It would also include Radio and Podcasts.

**Comment by gmackenz** [comment]
Richard I'll ask my colleagues as that seems a better notion for a boolean property on [Episode](https://schema.org/Episode).

**Comment by alex-jansen** [comment]
obsolete, so closing.
