### ISSUE TITLE
Add existing CreativeWork as an expected type for existing description property

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#2942]
Currently the [description](https://schema.org/description) property expects only [Text](https://schema.org/Text). This is insufficient if there is additional information that needs to be conveyed with the text string (like authorship, licensing information, expiration date, etc.). I would propose we allow descriptions to also be [CreativeWorks](https://schema.org/CreativeWork) which has such properties allowing attaching various annotations to a text string.

This is proposal comes from Google to allow us to better handle/process description text for media and other content.

**Comment by RichardWallis** [comment]
I  believe I can see where this is coming from - presuming that this is referring to the use case of types of Things (eg. Products) that do not have such properties, and not CreativeWorks / CreativeWork subtypes (as they already have those properties).

However, it is not that simple. For example, the _expires_ property in a _CreativeWork_ linked from the _description_ property of a _Product_ would describe when the CreativeWork will expire, not the _Product_ it is linked from.  The same is true for the other suggested as useful properties, they are describing the CreativeWork, not the Thing that has that CreativeWork as its description.

I can see the benefit of being able to have a CreativeWork as a description - eg. a BlogPosting acting as a quality description of a Place.  But it would be logically incorrect to assume that properties of a linked CreativeWork description [other than its textual content] expand the information about the entity that links to it.

**Comment by WeaverStever** [comment]
Isn't this what the https://schema.org/about does for us?

**Comment by RichardWallis** [comment]
_about_ and _description_ could be considered to be inverse of each other in this context, yes.  As in the content of the [description] CreativeWork will be 'about' the Thing it describes. For mark up simplicity you might want to explicitly assert the relationship from the Thing end.

However, this bit of semantics doesn't address what appears to be the main suggestion in this issue - that properties (expires, author, license, etc.) of the describing CreativeWork, would be informational as to the status of the Thing it is describing.

**Comment by gmackenz** [comment]
Thanks for the feedback Richard. That was the intent, the string of text is a CreativeWork in of itself with attributes that are not about the Product/TVEpisode this text string is a description of. The properties on CreativeWork would add additional context/information just about the string of text.

Is there another way we can attach dates, licensing, sources to a string value? Would we need a new type to capture the text value and additional information about the text? What would that look like? PriceSpecification?

**Comment by RichardWallis** [comment]
@gmackenz Now you explain it that way I am more comfortable.   

However, are you not proposing what is already possible via the [subjectOf](https://schema.org/subjectOf) property?

**Comment by gmackenz** [comment]
@RichardWallis I don't believe that would work as that is for the object and not applicable directly for the description text of that object. So for example: a TV programming data feed using schema.org markup for a TVEpisode for a TV program that includes a description string supplied from a NBC source that is only contractually available for 6 months. We can't capture that data currently in schema.org as far as I can tell. I don't believe subjectOf would work for that usage.

**Comment by RichardWallis** [comment]
@gmackenz now you flesh out that scenario it appears a bit too specific for linking to via the _description_ property.

A simple Text description, as you indicate, has no information about its authorship, licensing, expiry date etc.  Hence to capture that sort of thing you are looking to a CreativeWork or subtype thereof.  

With current Schema capability that would be a CreativeWork (eg. Article) that would be [about](https://schema.org/about) the program.  Via the inverse the program's markup could indicate that it is [subjectOf](https://schema.org/subjectOf) the article.

The only difference I am picking up from your description of the need, is that somehow you want to indicate that the relationship between the entity (TV Program) and its description will expire.  Or is it you want the link to remain but indicate that the descriptive text has past its expires data.

**Comment by gmackenz** [comment]
Revisiting this as there is growing need for Google to have a means of annotating text with additional information (localizing restrictions, time of use, etc.) for the 'description' text that may be provided by content providers for MediaObjects (mostly VideoObjects for now such as Films, TV Shows, TV Episodes, etc.).

Either we can expand the domainIncludes of [description](https://schema.org/description) to include both [Text](https://schema.org/Text) and [CreativeWork](https://schema.org/CreativeWork) and use the latter's properties for additional information about the description text content.

```
:description a rdf:Property ;
    rdfs:label "description" ;
    :domainIncludes :Thing ;
    :rangeIncludes :CreativeWork,
        :Text ;
    rdfs:comment "A description of the item." ;
    owl:equivalentProperty dc:description .
```

Or we could instead expand the domainIncludes of [description](https://schema.org/description) to include both [Text](https://schema.org/Text) and a new TextObject subtype of [MediaObject](https://schema.org/MediaObject). A new MediaObject subtype of TextObject would allow us to have specific properties later in regards to text as opposed to audio, video, etc.

```
:TextObject a rdfs:Class ;
    rdfs:label "TextObject" ;
    :isPartOf <https://pending.schema.org> ;
    rdfs:subClassOf schema:MediaObject ;
    rdfs:comment "A text file." .

:description a rdf:Property ;
    rdfs:label "description" ;
    :domainIncludes :Thing ;
    :rangeIncludes :Text,
        :TextObject ;
    rdfs:comment "A description of the item." ;
    owl:equivalentProperty dc:description .

```

**Comment by philbarker** [comment]
See also #1379 and #276 and suggestion of treating the (structured) abstract of an academic work as a CreativeWork.

**Comment by RichardWallis** [comment]
In principle I support your second (TextObject) option - using some of the general CreativeWork subtypes such as VideoObject or Sculpture would not be particularly useful as a description.

In practice if we implemented TextObject, we should handle at least in the description of the type, some of the inevitable questions that would arise.  Such as, is this type for plain text only or is html, markdown, or other text formats acceptable.

**Comment by gmackenz** [comment]
> In practice if we implemented TextObject, we should handle at least in the description of the type, some of the inevitable questions that would arise. Such as, is this type for plain text only or is html, markdown, or other text formats acceptable.

So what is allowed for Text currently?

I believe TextObject's text should be pretty much text format-agnostic.

**Comment by smrgeoinfo** [comment]
Seems like having an 'encodingFormat' property on text object would be a good, extensible way to indicate how to interpret the bitstream for the TextObject.  Might be even better if it were a subProperty - 'textEncodingFormat'.

**Comment by mfhepp** [comment]
I think this is a tricky issue, and a quick, pragmatic fix can lead us into a lot of trouble. Text content is used everywhere in markup, and we can easily end up in cyclic dependencies and inconsistencies. Just a few examples:

- in RDF syntaxes, text content can have a language tag, but any richer type for "text plus meta-data" could easily introduce multiple ways of expressing the same thing.
- Text is such a basic type of content that adding a level of indirection here will add a lot of burden to consumers of data and break many legacy applications.

IMO, there are multiple separate issues to be addressed, at least the following:

1. Being able to **attach 'stable' meta-data like licensing, authorship, etc. to a textual representation.**
2. **Versioning / temporal aspects:** When has this text been published, crawled, etc. (for temporal aspects in Knowledge Graphs, see e.g. the nice [paper by Franz Krause et al.](https://arxiv.org/abs/2207.09964). **This is orthogonal to the first problem and it may be difficult to be clear about the scope of any such meta-data** (is the product description updated? or the product? or the offer?).
3. **Formal links between derivative works,** translations, different syntaxes of the same text, like English vs. German product descriptions, long vs. short descriptions; plain text vs. Markdown vs. HTML. 
4. **Being able to use richer syntaxes in text content, like Markdown and HTML** while being able to indicate the syntax (e.g. adding a [Media Type](https://www.iana.org/assignments/media-types/media-types.xhtml).

I am sure there are more.

For all of these, there are potential dependencies on

- **the syntax** being used (e.g. [language tags in RDF/RDFa etc.](https://www.w3.org/TR/rdf11-concepts/#dfn-language-tag) and [language containers in JSON-LD](https://w3c.github.io/json-ld-syntax/#language-indexing),
- **the vocabulary;** [see the many schema.org properties with `DateTime` in their range](https://schema.org/DateTime).
- and, to a lesser degree, **the protocols**, like HTTP response header parameters.

Before we open a can of worms, we should, IMO, either

- develop a minimal, generic solution that is conceptually clean, or
- limit the extension to a narrow application area, e.g. by just allowing a new text value for product descriptions etc.

Ping @danbri

**Comment by HughP** [comment]
When I hear "text Encoding" I think "ASCII", "UTF-8", etc. not "text markup" such as HTML, Markdown, etc.

**Comment by alex-jansen** [comment]
Hi @danbri We indeed should not add a new type to the range of /description and I also don't think that is needed since  /digitalSourceType was already added to /CreativeWork (and thus inherited by /TextObject) in Release 14.0 back in January. So I think we can actually close this issue, which is what I am doing now ;)
