### ISSUE TITLE
buildsite.py fails (new release of RDFlib causing issue?)

### ISSUE THREAD

**Issue by epaulson** [schemaorg/schemaorg#2946]
Hello - 

While running 'software/buildsite.py -a' for local testing, and since at least July 22nd in the Github CI runs, the build has been failing with this error:

```
Version: 14.0  Released: 2021-XX-XX
  File "/home/runner/work/schemaorg/schemaorg/software/util/buildsite.py", line 367, in <module>
    processFiles()
  File "/home/runner/work/schemaorg/schemaorg/software/util/buildsite.py", line 336, in processFiles
    buildfiles.buildFiles(FILES)
  File "/home/runner/work/schemaorg/schemaorg/software/util/buildfiles.py", line 362, in buildFiles
    content = func(p)
  File "/home/runner/work/schemaorg/schemaorg/software/util/buildfiles.py", line 191, in exportrdf
    _exportrdf(extype,allGraph,currentGraph)
  File "/home/runner/work/schemaorg/schemaorg/software/util/buildfiles.py", line 225, in _exportrdf
    out = g.serialize(format=fmt,auto_compact=True,**kwargs).decode()
AttributeError: 'str' object has no attribute 'decode'
Building site in 'software/site' directory
```

It looks like the difference is that RDFlib 6.0.0 has been released as of July 20 - the most recent CI build that worked pulled in RDFlib 5.0.0, and if I specify RDFlib 5.0.0 in my local requirements.txt buildsite.py is successful. 

This is probably just going through and removing the .decode() in places where it used to be needed but is no longer necessary, but someone who knows the code better should probably make sure.

**Comment by RichardWallis** [comment]
@epaulson thanks for the heads up on this.

I will check into it.  

 I see RDFlib 6.0.0 specifies Python 3.7 as a minimum whereas we currently specify 3.6 - will need a dependancy check too.

**Comment by rscheele** [comment]
I've solved this issue locally by reverting my library rdflib-jsonld to 0.5.0 

Then removing the .decode() in line 832 of sdotemsource.py changing it to 
`        ret = g.serialize(format=format,auto_compact=True,**kwargs)`
And removing .decode() in line 225 of buildfiles.py
`        out = g.serialize(format=fmt,auto_compact=True,**kwargs)`

Then there were some issues with encoding after removing .decode() so I had to add `encoding='utf8'` to some of the files, more specifically
Line 73 in buildtempages.py
`        f = open(termFileName(term.id),"w", encoding='utf8')`
Line 288 in buildocspages.py
`                    f = open(fn,"w", encoding='utf8')`
Line 222 & 223 in buildfiles.py
`        f = open(fn,"w", encoding='utf8')
        af = open(afn,"w", encoding='utf8')`
Line 316 & 317 in buildfiles.py
`    csvfile = open(fn,'w', encoding='utf8')
    acsvfile = open(afn,'w', encoding='utf8')`
Line 366 in buildfiles.py
`                        f = open(fn,"w", encoding='utf8')`

**Comment by RichardWallis** [comment]
PR #2990 Fixes. this

Thanks @rscheele for sharing your experience on this.
