### ISSUE TITLE
ISSN example goes against guidance

### ISSUE THREAD

**Issue by edent** [schemaorg/schemaorg#2952]
According to http://www.bl.uk/help/get-an-isbn-or-issn-for-your-publication#:~:text=Display%20of%20the%20issn

> The number should be printed thus: ISSN 0000-0000
> it should be preceded by the initials ISSN followed by a single space

However, the examples given in https://schema.org/Periodical display it with an errant colon

> ISSN: 0140-6736

See also https://www.issn.org/understanding-the-issn/assignment-rules/the-issn-l-for-publications-on-multiple-media/

Are you happy for me to made (an admittedly pedantic) edit to https://github.com/schemaorg/schemaorg/blob/main/data/sdo-periodical-examples.txt#L28

**Comment by RichardWallis** [comment]
> Are you happy for me to made (an admittedly pedantic) edit to https://github.com/schemaorg/schemaorg/blob/main/data/sdo-periodical-examples.txt#L28

For consistency the same edit would also be required for lines 11 & 56

No reason why you should not submit a PR for this.
