### ISSUE TITLE
Expected type of Organization -> member

### ISSUE THREAD

**Issue by Kiaba** [schemaorg/schemaorg#2959]
When we open https://schema.org/Organization
You can see that member has next list of expected types:
- Organization
- Person

If we open https://schema.org/OrganizationRole
You can see example:
```
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Cryptography Users",
  "member": {
    "@type": "OrganizationRole",
    "member": {
      "@type": "Person",
      "name": "Alice"
    },
    "startDate": "1977"
  }
}
```

It means that Organization -> member has incorrect list of expected types or OrganizationRole cannot be member and we have to change example.

Inheritance:
Thing > Organization
Thing > Person
Thing > Intangible > Role > OrganizationRole

**Comment by RichardWallis** [comment]
This pattern comes from the special characteristics of the [Role](https://schema.org/Role) type, of which [OrganizationRole](https://schema.org/OrganizationRole) is a subtype.

See issue #2787 and this [comment](https://github.com/schemaorg/schemaorg/issues/2787#issuecomment-743094648) for an explanation.

The proposed clarification:

> I believe we could possibly make things a little simpler by adding the _Role_ subtypes - _OrganizationRole_, _EmployeeRole_, _PerformanceRole_, and possibly _LinkRole_ -  to the range of appropriate properties (_alumniOf_, _worksFor_, _memberOf_, _actor_, etc.).  Also based upon your second example, there may be a case for a new _Role_ subtype of _OccupationRole_.

... is still awaiting further support / action.

**Comment by Kiaba** [comment]
@RichardWallis One additional question about Organization Role:
Role, OrganizationRole, EmployeeRole do not have property member but in examples we can see it.
```
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Cryptography Users",
  "member": {
    "@type": "OrganizationRole",
    "member": {
      "@type": "Person",
      "name": "Alice"
    },
    "startDate": "1977"
  }
}
```

**Comment by thadguidry** [comment]
@Kiaba `"member"` is the pass down property of `"@type": "Organization"` and as @RichardWallis stated is part of the pattern of Role.  We blogged about it early in it's introduction: http://blog.schema.org/2014/06/introducing-role.html
In the blog, you can notice the **Ghostbusters -- actor -->  (PerformanceRole) -- actor -->**
where **actor** is simply passed down from the originating type "Movie" from Ghostbusters.  It's not a property on the **(PerformanceRole)** as you are thinking and visually might look like unfortunately.
We probably should have used the phrase "passed down" which I use to explain to folks when training them.
Instead we said this in the [Role](https://schema.org/Role) definition

> Such properties can be attached to a Role entity, which is then associated with the main entities using ordinary properties like 'member' or 'actor'.
