### ISSUE TITLE
Add a new property (careProvider) to MedicalProcedure

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#296]
http://schema.org/MedicalProcedure

Currently schema.org/MedicalProcedure provides no method of expressing who will perform the procedure. To me this seems to be an omission. 

For this reason I'd like to suggest adding a new property to schema.org/MedicalProcedure, namely:
careProvider

Possible description:
"A medical organization or person providing health care service(s)."

Another route could be a Multi Type Entity like [MedicalProcedure Service], so to be able to use 'provider', but IMHO this doesn't seem to be fitting either as I consider a 'care provider' to be a different beast than just a 'provider', especially for consumers of medical data.

To support my proposal I've already started implementing the property on a website: http://bit.ly/1EP52Cy
(and before anybody says anything - I know this page has an issue with the enumeration member PlasticSurgery, it's being fixed).

Note:
This property is also part of the MedicalEntity 'modification' proposal (https://github.com/schemaorg/schemaorg/pull/11), though this issue suggest a simpler version than the proposal does as the proposal also encompasses new schema.org Types.

**Comment by thadguidry** [comment]
@jvandriel  I dunno.  I feel that the Multi Type Entity would be a better approach, practically because we say that MedicalProcedure is a class of Service, and that seems right to me.  I differ also in that I consider a "care provider" to be the same beast, but more specialized than a "provider".

**Comment by twamarc** [comment]
+1. Making careProvider a subproperty of provider.
+1. Making MedicalProcedure  Multi Type Entity.

**Comment by jvandriel** [comment]
_"I differ also in that I consider a "care provider" to be the same beast, but more specialized than a "provider"."_

Good point, I stand corrected.   :)

_"Get MedicalProcedure, MedicalTest, and MedicalTherapy as specific types under http://schema.org/Service"_

+1

Personally I'm not too crazy about the idea for an MTE either, because imagine one has a MedicalProcedure containing an Offer. That would lead to a MTE containing 3 types:

```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": ["MedicalProcedure","Service","Product" ], 
    "name": "Some procedure name"
    "careProvider": {
        "@type": "Physician",
        "@id": "#physician",
        "name": "etc"
    },
    "offers": {
        "@type": "Offer",
        "seller": "#physician",
        "priceSpecification": {
            "@type": "PriceSpecification", 
            "mixPrice": "5000",
            "maxPrice": "10000",
            "priceCurrency": "USD"
        },
    },
}
</script>
```

_"That is what is needed, IMHO, not a new property."_

Originally this was my POV as well but the folks behind the MedicalEntity modification proposal (http://bit.ly/165EvWk) insisted they need/want it to be named 'careProvider', which I can understand from their POV. So how about what @twamarc suggested by adding it as a subproperty od 'provider'?

**Comment by jvandriel** [comment]
Since the ```offers``` property has been added to ```Service``` as of schema.org 3.0 I no longer see the need to keep this issue open.
