### ISSUE TITLE
Validator requeres occupationLocation and estimatedSalary fields

### ISSUE THREAD

**Issue by Itsnotmatrix** [schemaorg/schemaorg#2962]
For the Person page https://schema.org/Person during validation there is an error for Person page here: 
https://search.google.com/test/rich-results 
System requeres: no field "occupationLocation", no field  "estimatedSalary". 
In my case it's a page for dentist who wrote an article about teeth care, so it's strange that we got the recommendation about salary field, it's not a job search.

The other key point of the issue is that even adding such fields still doesnt' help, validator shows the error anyway. 

Also the important fact is that here https://validator.schema.org/ all is ok.

Maybe somebody has met the similar issue?

**Comment by danbri** [comment]
This is a Google issue not a Schema.org issue - please try Google's forums!
