### ISSUE TITLE
LandmarksOrHistoricalBuildings type not registering on Google Rich Text Results

### ISSUE THREAD

**Issue by stuartdevstars** [schemaorg/schemaorg#2966]
We've been using the data type "LandmarksOrHistoricalBuildings" on a new site and seems to validate correctly when run it through the validator on schema.org but we get no results on Rich Text Results. 

For example: https://validator.schema.org/#url=https%3A%2F%2Ffriendsoffriendlesschurches.org.uk%2Fchurch%2Fst-mary-magdalene-boveney-buckinghamshire%2F

vs

https://search.google.com/test/rich-results/result?id=9cQid_iOj7g0mEvY26nvZg

I notice that both https://www.english-heritage.org.uk and https://www.nationaltrust.org.uk both use the Local Business style for a properties such as Stone Henge (https://search.google.com/test/rich-results/result?id=F3m74fsJfADoFQnzbIIoyw). Does this mean we should not use the Schema type  "LandmarksOrHistoricalBuildings" and use "Local businesses" instead ?

**Comment by chrisspradling1980** [comment]
Please keep in mind a concept insights object revealed in reversal]] ¬
