### ISSUE TITLE
Page for 'Address' type exists

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#297]
AFAIK `Address` is not a defined type, but it has a page: 

http://schema.org/Address

Currently showing "No comment" and two (old?) examples using [`PostalAddress`](http://schema.org/PostalAddress).

**Comment by danbri** [comment]
Thanks! The examples were the cause:

 grep Address data/*txt| grep "TYPES:" | grep -v Postal 
data/examples.txt:TYPES:  Organization,Address
data/examples.txt:TYPES:  Event,Place,Address,AggregateOffer

**Comment by danbri** [comment]
http://sdo-stantz.appspot.com/Address is now 404, as it should be, and http://sdo-stantz.appspot.com/PostalAddress#examples is showing the missing examples. Thanks :)
