### ISSUE TITLE
additional compact IRIs in examples

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2971]
Greetings,

I am looking for a good (clear) example of `isBasedOn` usage in JSON+LD. The one example that appears in the documentation https://schema.org/isBasedOn is replicated below.

My question is: _within the isBasedOn unit why is it `schema:name` instead of just `name`?_ If this is correct then please help me understand it better as I am not following the need for the additional declaration. But perhaps this example is not clearly written and should be revised. Any help or discussion is appreciated.

```
<script type="application/ld+json">
{
  "@context":  "https://schema.org/",
  "@type": "CreativeWork",
  "name": "Derivative Work",
  "text": "In copyright law, a derivative work is an expressive creation that includes major elements of a previously created original work. An example of a derivative work is L.H.O.O.Q, or Mona Lisa With a Moustache, by Marcel Duchamp.",
  "isBasedOn": {
    "@type": "CreativeWork",
    "schema:name": "Derivative Work",
    "schema:publisher": "wikipedia",
    "schema:url": "https://en.wikipedia.org/wiki/Derivative_work"
  }
}
</script>
```

**Comment by RichardWallis** [comment]
Removed 'schema:' references from example to clarify things.

In commit #26640a4 so will be in next release
