### ISSUE TITLE
Update links to accessibility property vocabs

### ISSUE THREAD

**Issue by mattgarrish** [schemaorg/schemaorg#2982]
accessibilityAPI, accessibilityControl, accessibilityFeature, accessibilityHazard currently reference the vocabulary we were maintaining in the WebSchemas wiki, but now that we have a CG to maintain those terms we've republished them at https://www.w3.org/2021/a11y-discov-vocab/latest/

We should update the links in those properties (and add to accessMode and accessModeSufficient, which embed some terms) to point to the new vocabulary.

I'd suggest switching the current text from:

> " (WebSchemas wiki lists possible values)."

to:

> Values should be drawn from the [approved vocabulary](https://www.w3.org/2021/a11y-discov-vocab/latest/#).

with links into the appropriate lists of terms for each property.

/cc @clapierre @madeleinerothberg

**Comment by madeleinerothberg** [comment]
+1

**Comment by clapierre** [comment]
Agreed

**Comment by mattgarrish** [comment]
Closing this issue as it's fixed with https://github.com/schemaorg/schemaorg/pull/2985
