### ISSUE TITLE
Thing and isPartOf

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2984]
Greetings,

I am describing Game pieces and am looking at https://schema.org/Thing which is the expected property of https://schema.org/gameItem . So I want to add to gameItem what game it belongs to.... I should be able to do that with isPartOf... but IsPartOf is not listed as an available option on gameItem. What am I missing? why is this not allowed? I want to make the assertion that one thing is part of another thing.

**Comment by danbri** [comment]
We have chosen to keep isPartOf as relating creative work stuff. Even there it is super vague, frankly. If we had it cover all of everything, it would be almost meaningless. I don't think we currently have a way to do what you want with gameItem. Can you give a full example?

**Comment by HughP** [comment]
@danbri Thank you for taking a look at this with me. I appropriate your thoughtful consideration. 

I'll try and layout the use-case. Let's say I am a game-piece vendor (there are lots of these, one famous one is [Meeplesource](https://meeplesource.com)). Maybe I sell something like the following:

* [figures for war games](https://www.games-workshop.com/en-US/Warhammer-40-000)
* [special cards for deck-building games](https://boardgamegeekstore.com/collections/frontpage/products/concordia-8-forum-cards-navegador-privilege-cards) or [also this example](https://boardgamegeekstore.com/collections/frontpage/products/seasons-speedwall-promo)
* [wood cut figures for strategy games](https://meeplesource.com/products.php?cat=29)
* Digital [NFT based characters for online games](https://opensea.io/collection/axie)

Game Pieces are things, but in some cases they are also creative works. (Copyright, a concept which also applies to creative works, can apply to sculptures which are "things").  I am trying to describe listings of game pieces and one useful attribute is what game those pieces were intended to be played with. 

From a game marketer's perspective there are three game item types [[game box](https://www.meeplerealty.com), game pieces, [game instructions](https://www.ebay.com/b/Video-Game-Manuals-Inserts-Box-Art/182174/bn_16566359?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5336728181&customid=&toolid=10001)]. From a game buyer's perspective the interest is in game pieces is most generalized by three types of game pieces: [characters, boards, accessories]. To me this suggests that there are five primary distinctions which would help facilitate interaction between buyers and sellers: [game box, game instructions, game piece:[game character, game board, accessory game pieces]].

So when we have a store offering a game piece as the object of the offer things seem to breakdown with the schema.org vocabulary. [gameItem](https://schema.org/gameItem) is only a property of [Game](https://schema.org/Game) and [VideoGame](https://schema.org/VideoGame). As such listing a game item for sale is challenging. _Maybe gameItem should be a schema.org type?_ As a type it could then express the above five distinctions.

Let me share some code. It does not validate at the moment because offer is not valid on thing (and material is not valid either).

But the code generally shows that I am trying to market a game piece and part of that marketing is to connect it to the game it is designed to be used with. However, schema.org takes the perspective that I must define the game as a type rather than the game piece.



```
{
  "@context": "https://schema.org",
  "@type": "Game",
  "schemaVersion": "13.0",
  "sdDatePublished": "2021-11-04",
  "sdPublisher": {
    "@type": "Organization",
    "name": "Royal Protocol",
    "url": "https://royalprotocol.io"
  },
  "name": "Carrcassone",
  "gameItem": {
    "@type": "Thing",
      "description": "A humanoid character in a game. Usually used as a place holder in a boardgame which has a board location dominance strategy.",
      "name": [{
          "@value": "Meeple",
          "@language": "en"
        },
        {
          "@value": "Meeple",
          "@language": "de"
        }
      ],
      "sameAs": "https://www.wikidata.org/wiki/Q95993854",
      "offers": [
        {
          "@type": "Offer",
          "offeredBy": {
            "@type": "Organization",
            "name": "Meeple Source",
            "url": "https://meeplesource.com"
          },
          "priceCurrency": "USD",
          "price": "0.10",
          "availableAtOrFrom": "https://www.boardgamegeek.com/boardgame/123386/baden-wurttemberg-catan#buyacopy",
          "material": "Wood"
        }, 
        {
          "@type": "Offer",
          "offeredBy": {
            "@type": "Organization",
            "name": "BryBelly",
            "url": "https://www.amazon.com/stores/Brybelly/page/818E0709-619F-4C7C-B3B3-8235EFE99863?ref_=ast_bln"
          },
          "priceCurrency": "USD",
          "price": "0.50",
          "availableAtOrFrom": "https://www.amazon.com/Assorted-Wooden-Meeples-Pieces-Brybelly/dp/B0767NPZWN",
          "material": "Plastic"
        }
          ]
    }
  }
}
```

**Comment by RichardWallis** [comment]
If you approach it from a slightly different view, the figure can be defined as a _Product_ - you are offering it for sale.  A _Product_ that _isRelatedTo_ the game.

The game itself could also be considered as a _Product_ as well as a _Game_.

Putting that together in a simple way would give the following:
```
{
  "@context": "https://schema.org",
  "@id": "https://royalprotocol.io/game1",
  "@type": ["Game","Product"],
  "schemaVersion": "13.0",
  "sdDatePublished": "2021-11-04",
  "sdPublisher": {
    "@type": "Organization",
    "name": "Royal Protocol",
    "url": "https://royalprotocol.io"
  },
  "name": "Carrcassone",
  "gameItem": {
    "@type": "Product",
      "description": "A humanoid character in a game. Usually used as a place holder in a boardgame which has a board location dominance strategy.",
      "name": [{
          "@value": "Meeple",
          "@language": "en"
        },
        {
          "@value": "Meeple",
          "@language": "de"
        }
      ],
      "isRelatedTo": "https://royalprotocol.io/game1",
      "sameAs": "https://www.wikidata.org/wiki/Q95993854",
      "offers": [
        {
          "@type": "Offer",
          "offeredBy": {
            "@type": "Organization",
            "name": "Meeple Source",
            "url": "https://meeplesource.com"
          },
          "priceCurrency": "USD",
          "price": "0.10",
          "availableAtOrFrom": "https://www.boardgamegeek.com/boardgame/123386/baden-wurttemberg-catan#buyacopy",
          "material": "Wood"
        }, 
        {
          "@type": "Offer",
          "offeredBy": {
            "@type": "Organization",
            "name": "BryBelly",
            "url": "https://www.amazon.com/stores/Brybelly/page/818E0709-619F-4C7C-B3B3-8235EFE99863?ref_=ast_bln"
          },
          "priceCurrency": "USD",
          "price": "0.50",
          "availableAtOrFrom": "https://www.amazon.com/Assorted-Wooden-Meeples-Pieces-Brybelly/dp/B0767NPZWN",
          "material": "Plastic"
        }
          ]
    }
  }
}
```
In production mode I would probably code it up as an @graph using @ids for each main item but I hope the above shows what I am trying to show.

**Comment by jaygray0919** [comment]
Very nice @RichardWallis . This issue recently surfaced on [StackOverflow](https://stackoverflow.com/questions/70012285/how-best-to-describe-material-of-parts-of-a-schema-org-product-in-json-ld#comment123780239_70012285). Had to pivot away from `hasPart` (had a brain freeze per @danbri guidance) to `isConsumableFor`. The absence of a reciprocal term is a little awkward but doable.

**Comment by danbri** [comment]
We have no plans to cover this usecase currently, sorry! Closing but this issue remains in the archives in case we revisit the topic.
