### ISSUE TITLE
Problems schema:additionalType as subproperty of rdf:type

### ISSUE THREAD

**Issue by marco-brandizi** [schemaorg/schemaorg#2986]
I'm copy-pasting the following from a discussion we had in BioSchemas (#BioSchemas/specifications/issues/538):

In my opinion, the fact that `additionalType` extends `rdf:type` can be problematic. In particular,
I have strings that I convert into "sample properties" and then enrich with ontology terms using 
text mining tools (eg, ZOOMA, Bioportal Annotator). The result is something like:

```turtle
ex:prop1234 rdf:type schema:PropertyValue;
  schema:propertyID "Sample Characteristic";
  schema:value "seed size"; # The string it was created from
  schema:additionalType ex:seed, ex:size # computed by text mining, not much under manual control
```

with `additionalType` as subproperty of `rdf:type`, the case above implies a couple of formally wrong statements: one, the property value is an information artifact entity, and not a seed. Two, seed and size are disjoint classes (and declared as such in many actual ontologies).  

This might not be very important if you don't expect to use a formal (OWL) reasoner with your data, yet I don't like to introduce such potential inconsistencies in my data.  

So, my proposal would be to remove this rdf:type inheritance and to have something that is less formally committing in its place (first candidate I can think of is `dc:type`).

**Comment by dr-shorthair** [comment]
I agree. `dcterms:type` is a useful, informal adjunct to `rdf:type`. A similar pattern in schema.org would be a good way of supporting common use-cases.

**Comment by smrgeoinfo** [comment]
The problem I see in your example is that the additionalTypes seem to me to be related to the property and its value. In your example the propertyID should be ex:size, in a record that looks more like:

```
{....
@type:"Dataset",
"about":ex:seed,
"variableMeasured": [
{
      "@type": "PropertyValue",
      "propertyID": "ex:size",
      "name": "seed size",   
      "unitText": "mm"
    },

],
... }
```
where I've seen schema:additionalType as useful is when an object requires properties not associated with the @type content in Schema.org are needed in a resource description-- the type specifies the kind of object in the encoding.

**Comment by marco-brandizi** [comment]
@smrgeoinfo, I don't follow you. Mine is an example of a biosample characteristic in biological data. `ex:prop1234` is a property of a biosample, conceptually, its type is "Sample Characteristic" and its string value is "seed size". Then, when such a property is linked to a term like `http://purl.obolibrary.org/obo/TO_0000391` (seed size), it's to state that the sample characteristic value refers to seed size.

Other examples of type/value pair are: "Specie/Homo Sapiens", "Sample Reference Code/123".

That said, unless I'm missing something, the schema.org way to model this pairs is `propertyID/value`, I don't follow why `ex:size` should go into property ID. why there isn't a value anymore, and where to put "Sample Characteristic" or "Specie" (which I need to track somewhere, cause this is the type for the end user).

As for the role of adding types to `@type`, it's what I'm trying to do. My primary `@type` is `PropertyValue`, then there might be further qualifiers, but the problem I'm having is basically that they can't be as formally committing as they're in RDF/OWL (via rdf:type), essentially, I need something more informal for those relations.

**Comment by smrgeoinfo** [comment]
Perhaps the problem is the scope of the use case. I'm thinking that 'PropertyValue' is being used in the range of 'variableMeasured' to describe a Dataset schema content -- what are the properties associated with the entity represented by each record in a dataset. In this case, it is assumed that each 'variableMeasured' is a characteristic of the entity represented by the dataset record.   Schema.org is (as usual) ambiguous, and PropertyValue could also be used to specify a value instance -- my interpretation is that 'value' in a 'PropertyValue' instance is a value of the property identified by 'propertyID' in the context of whatever is the subject for the triple that has the 'PropertyValue' instance as its object.  
 
In documentation for a dataset schema, specific property values are not specified - one might specify the range for the values (min, max, controlled vocabulary...), but the 'value' property of 'PropertyValue' is not used (unless its a constant in that dataset). 

Perhaps your use case is something different?

**Comment by marco-brandizi** [comment]
@smrgeoinfo, thanks. I don't think my cases are very different than what you say, or what is given in the [examples](https://schema.org/PropertyValue).

For instance, for the case `sample1 -> Specie = Homo Sapiens`, it's quite clear that we should have: 

```haskell
sample1 a bioschema:Biosample;
  schema:name "Biosample 1";
  schema:additionalProperty [
    a schema:PropertyValue;
    # I could use this, instead of propertyID, in order to track the original unique ID, eg, as it comes from a 
    # a database
    schema:identifier "myVocabulary:Specie";
    # I could use this for the label
    schema:name "Sample Specie";
    schema:value "Homo Sapiens"
  ]
  ...
.
```

but then, the main problem I have it's when I want to attach URIs as further qualifiers for the property value. In this case, they might be:

1. https://en.wikipedia.org/wiki/Human
1. http://purl.bioontology.org/ontology/NCBITAXON/9606
1. https://en.wikipedia.org/wiki/Homo_Sapiens_1900

where the first two are correct and compatible (conceptually, they're the same type), the third is not (it's a book, it might have been produced by some text mining tool).

So, if `additionalType` stays as it is, how could I add the (ontology) reference above (which aren't exactly additional types)? Can I use `schema:propertyID` multiple times for a given property value? Or should I use `schema:about`? Or something else?
