### ISSUE TITLE
CreativeWorkSeries, CreativeWork, and isPartOf

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2987]
Greetings,

Why is it the case that https://schema.org/CreativeWork does not say that https://schema.org/CreativeWorkSeries is a valid option for the property "isPartOf"? https://schema.org/isPartOf (in the sense of "expected type")

**Comment by RichardWallis** [comment]
The expected types for the [isPartOf](https://schema.org/isPartOf) property include [CreativeWork](https://schema.org/CreativeWork) (and therefore its subtypes).  [CreativeWorkSeries](https://schema.org/CreativeWorkSeries) is a subtype of _CreativeWork_ so is a valid option for _isPartOf_.
