### ISSUE TITLE
Rebase code for failing PRs

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#2992]
Following the fix of #2946, caused by the upgrading of some dependant python libraries such as rdflib, PRs that were failing (such as #2958) now pass CI tests.

For the failing PRs to pass the CI tests the code behind the PR had to be rebased against the current state of the main branch.  This was simple for PRs based on branches in this repository.

However several PRs (#2941, #2953, #2965, #2985 and possibly #2738) are hosted in branches in other forked repositories.  In these cases the code in those repositories, should be rebased against the main branch in this repository.

This issue is to capture to actions to achieve that

**Comment by gmackenz** [comment]
How do I do a Rebase, I am very unfamiliar with github.

**Comment by RichardWallis** [comment]
@gmackenz Let's see how others get on with this question over the next few days.  Then we may come up with an easy shared way to do it.

Git always has several ways do do anything!

**Comment by danbri** [comment]
I hate to make work for contributors, but my go-to git documentation is https://xkcd.com/1597/

**Comment by dr-shorthair** [comment]
I've definitely done that.

**Comment by dr-shorthair** [comment]
(saved my work elsewhere, and made a fresh clone)

**Comment by mattgarrish** [comment]
If you want to do it straight from github, I just realized they have a "Fetch upstream" button in your fork. If there are no merge conflicts, it should update everything for you. If not, it'll open a pull request so you can resolve the conflicts.

The old fashioned way I followed is to open a pull request yourself to merge main here into your fork.

**Comment by RichardWallis** [comment]
@mattgarrish  great suggestion, but where is this wonderful button.  I don't see it on the Github site.

Also. Github documentation on how to merge from upstream into a fork:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/merging-an-upstream-repository-into-your-fork

**Comment by mattgarrish** [comment]
If you go to a fork, it should appear in the Code tab just below the various buttons at the top (at the left edge):

<img width="538" alt="Fetch upstream button" src="https://user-images.githubusercontent.com/1565164/142459265-048ee360-8e80-4ea3-bf7d-e5f5a60e20df.PNG">
 
It's also documented here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by RichardWallis** [comment]
Ah that is not visible to me when I view someone else's fork repo.   Presumably you need to be the owner.

**Comment by philbarker** [comment]
I can confirm that it works for me on forks that I own. Thank you @mattgarrish !

**Comment by mattgarrish** [comment]
> Presumably you need to be the owner.

Yes. If you don't have write access, you could only request the owner sync their repository by going into the pull request tab and open a pull request that pulls the latest changes in this repository across to theirs.

If you want to prompt fixes for the broken PRs, you'd need to open a PR for each one.  For example, you could update 2965 here: https://github.com/acka47/schemaorg/compare/main...schemaorg:main
