### ISSUE TITLE
Does Thing have datePublished and dateModified?

### ISSUE THREAD

**Issue by dilyanpalauzov** [schemaorg/schemaorg#2993]
https://schema.org/datePublished and https://schema.org/dateModified pretend, that `datePublished` and `dateModified` are properties of Thing.

However, the definition of Thing at https://schema.org/Thing does not think so.

**Comment by philbarker** [comment]
@dilyanpalauzov no, they're not properties of Thing.

If you are looking at the bit at the top of the pages for those properties  that reads:
> Thing > Property :: dateModified

this means simply that dateModified is an _instance_ of the Property class, which is a subClass of Thing.

To see which classes those properties can be used on, look at the second table on the page.
