### ISSUE TITLE
potentially wrong supertype for the type Mass

### ISSUE THREAD

**Issue by sumutcan** [schemaorg/schemaorg#2994]
Is there any reason why https://schema.org/Mass is not a subtype of QuantitativeValue? It is currently a subtype of Quantity and its description says "Properties that take Mass as values are of the form '<Number> <Mass unit of measure>'. E.g., '7 kg'." 

This looks like a better fit for QuantitativeValue for me or even just Text with an inherent structure as specified in the description.

**Comment by danbri** [comment]
This reflects poor integration of two similar but distinct ways of talking about quantities that we have. It is deserving of cleanup.  We have some other related issues eg https://github.com/schemaorg/schemaorg/issues/1078
