### ISSUE TITLE
AudioObject and physical carriers

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2998]
Greetings,

In the context of Archives and archives with historical carriers of audio (LP, cassette tapes, wire, paper player reels, 8 tracks, etc.) When the archived object is one of these audio physical media carriers how should this be indicated?

Let's assume that we would use https://schema.org/ArchiveComponent  . Is the only option to use "material" and indicate the carrier? If I understand things we can't use https://schema.org/AudioObject via "audio" unless the audio object is a digital file. Is this a correct limitation of the use of   https://schema.org/AudioObject?

**Comment by RichardWallis** [comment]
[ArchiveComponent](https://schema.org/ArchiveComponent) should be applied to a fully described item to indicate that it is part of an archive.  An entity described as a _Book_ and an _ArchiveComponent_ is a book within an archive, as against just a book.

However, that does not address the core of your question - how to describe audio captured on an LP, cassette etc.

Taking the broadest interpretation of [AudioObject](https://schema.org/AudioObject) I believe it is not necessarily limited to digital formats only.  _playerType_ could be used to indicate Record Player, Cassette player, etc.

Taking inspiration from the way you would describe an instance of a book using a combination of the _Book_ and _Product_ types, a combination of AudioObject and Product may be useful here to indicate the physical description of an LP Record, Cassette tape, etc.
