### ISSUE TITLE
inLanguage Use in MusicComposition example

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2999]
Greetings,

In example No.1 under [Music Composition](https://schema.org/MusicComposition) the attribute **inLanguage** is applied directly to the type MusicComposition. 

```
 "@type": "MusicComposition",
    "inLanguage": "EN",

...
```

Would it be more accurate to apply the **inLanugage** attribute to just the lyrics as in:

```
 "@type": "MusicComposition",
    "lyrics": {
      "@type": "CreativeWork",
           "inLanguage": "en",
           "text": "I  read the news today oh boy..."
    }
```

How does the language attribute apply to the whole Composition?
From a syntax POV for the schema.org vocabulary I understand the inheritance from CreativWork, but are we making reasonable and accurate assertions if we apply **inLanugage** to music composition without focusing it on (making the assertion about) the lyrics?

**Comment by RichardWallis** [comment]
@HughP Although the current example is syntactically correct your suggestion improves the meaning.

Applied in commit #9080a1 and will appear in the next release.
