### ISSUE TITLE
General chaos around questions/answers in ReplyAction, AskAction vs Question, Answer, question property vs lack of answer property.

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#300]
http://schema.org/ReplyAction
http://schema.org/Answer

Original issue: I was looking at the lint errors outlined in issue #53. At some point in the proposal process, ReplyAction had an "answer" property, which was removed prior to official adoption. It would be useful to link ReplyAction to schema.org/Answer in some way, so the body of the reply can be modeled.  

Consider also #183 re RsvpAction

Notes: 

when the Question + Answer vocab was modeled we originally made an 'answer' property to point to answer. Later it became 'http://schema.org/suggestedAnswer' which was a superproperty of the more specific http://schema.org/acceptedAnswer.  Meanwhile the q/a-related action types AskAction, ReplyAction have an example (which uses AskAction but is catalogued against the ReplyAction type in data/examples.txt) which uses simple textual values (rather than e.g. 'text' property of an Answer or Question). This all needs some cleaning.

**Comment by danbri** [comment]
Related vocabulary (see UserComments cleanup issue #170 : 

    <http://schema.org/replyToUrl> <http://schema.org/domainIncludes> <http://schema.org/UserComments> .

If we are modeling replies, we might pause briefly at least to consider possibility of modeling more of http://schema.org/EmailMessage (although modeling all of email headers is a big task).

**Comment by danbri** [comment]
@vholland  

Vicki, I've filed this under Gozer for now. Any thoughts on whether that is feasible? Feels like a worthy thing to clean up alongside UserComments?

**Comment by vholland** [comment]
It seems like we should be able to add the "comment" property to RsvpAction, so someone can provide something of type Comment.

The only question in my mind is whether "comment" will be renamed as part of issue #417.

**Comment by danbri** [comment]
(I vote for leaving 'comment' as-is)

**Comment by danbri** [comment]
@vholland so sdo-gozer already has 'comment' on RsvpAction, see http://sdo-gozer.appspot.com/docs/releases.html#sdo-gozer "F*x to #183: comment property now applicable to an RsvpAction, and can have Comment as values.".

Can you elaborate on how this relates to the ReplyAction and Answer situation? 

Perhaps every Question, and every Answer, is a Comment? we don't have that type structure currently. And we do do say that a Comment is a comment on something, whereas Question is more free-floating. Answer at least seems to be a candidate for being a Comment subtype. In which case setting domainIncludes on 'comment' to cover ReplyAction could work: some ReplyAction would have a 'comment' whose value would be some Answer (which is also a Comment via type hierarchy).

**Comment by vholland** [comment]
I think I was confusing this with issue #183. Otherwise, my reply doesn't make sense, even to me. ;-)

**Comment by danbri** [comment]
I started a proposal - draft here https://gist.github.com/danbri/18febeb5334515460be4 - but had 2nd thoughts. Firstly the example tagged as ReplyAction is actually using AskAction. The example has both a question and an answer. Secondly I realise we have a 'question' property whose value is purely text (i.e. unrelated to Question or Answer), whereas 'answer' as a property does not exist. I will retitle this issue to indicate the broader unacceptable mess.

**Comment by danbri** [comment]
I've closed #444 which noted specifically that "http://schema.org/ReplyAction has an example demonstrating AskAction, and using a bogus 'answer' property. "   - seems best dealt with here.

**Comment by elf-pavlik** [comment]
I see some similarities between
* Question/Answer vs. AskAction/ReplyAction
* Demand/Offer vs. TakeAction/GiveAction (as **future** PotentialAction not **past** Activity)

Also it makes sense to me that just as people can *reply* to some *Question* with many different *Answer*, people can *reply* to some *Demand* with many different *Offers*. @mfhepp 

I started lately experimenting with illustrating relations between Actions/Activities and QualifiedRelations/N-aryRelations in those early/free experiments https://github.com/w3c-social/social-vocab e.g.

![Follow](https://docs.google.com/drawings/d/1zFWdjo_phs60Lr7dyoXyd4PQ9hOBxadlU8FZDQIAPHg/pub?w=960&h=540)

Soon I'll try to follow up with more details on #220

**Comment by vholland** [comment]
I'm trying to move this forward. In pull request #467, I

1. Went with @danbri's suggestion of making http://schema.org/Answer a subtype of http://schema.org/Comment.
2. Changed http://schema.org/question to expect http://schema.org/Question instead of Text.
3. Added http://schema.org/resultComment as a property of http://schema.org/ReplyAction.
3. Cleaned up examples on http://schema.org/AskAction, http://schema.org/ReplyAction, and http://schema.org/QAPage.

**Comment by danbri** [comment]
Thanks, @vholland . Odd: "We can’t automatically merge this pull request.", wonder what clashed. I'll do it manually...

**Comment by danbri** [comment]
<div typeof="rdf:Property" resource="http://schema.org/resultComment">
      <span class="h" property="rdfs:label">resultComment</span>
      <span property="rdfs:comment">A sub property of result. The Comment created or sent as a result of this action.</span>
      <link property="rdfs:subPropertyOf" href="http://schema.org/result" />
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/CommentAction">CommentAction</a></span>
<<<<<<< HEAD
=======
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/ReplyAction">ReplyAction</a></span>
>>>>>>> d92b4ee0b6d08c324a8f561b5f2a9f0be8841b1b
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Comment">Comment</a></span>
    </div>

**Comment by danbri** [comment]
This is it. Can you confirm what the domain/range ought to be? 

    <div typeof="rdf:Property" resource="http://schema.org/resultComment">
      <span class="h" property="rdfs:label">resultComment</span>
      <span property="rdfs:comment">A sub property of result. The Comment created or sent as a result of this action.</span>
      <link property="rdfs:subPropertyOf" href="http://schema.org/result" />
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/CommentAction">CommentAction</a></span>
    <<<<<<< HEAD
    =======
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/ReplyAction">ReplyAction</a></span>
    >>>>>>> d92b4ee0b6d08c324a8f561b5f2a9f0be8841b1b
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Comment">Comment</a></span>
    </div>

Assuming for now that we want both CommentAction, ReplyAction in domain, and Comment as range.

**Comment by danbri** [comment]
Changes + docs/releases.html update are in and pushed:

Please take a look - http://sdo-gozer.appspot.com/docs/releases.html#sdo-gozer and nearby.

**Comment by danbri** [comment]
I believe this was fixed in #300 ... closing.
