### ISSUE TITLE
MusicComposition examples 2 & 3 are not relevant

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#3000]
Greetings,

In examples 2 & 3 on [MusicComposition](https://schema.org/MusicComposition) we see something like the following:

```
"@type": "MusicRecording",
```

or 

```
"@type": "MusicRelease",
```

Examples 2 & 3 do not demonstrate the schema.org type `@MusicComposition`. Therefore their placement is confusing. -- I recommend moving them to their respective pages which do discuss their indicated `@type` values. I was looking for examples of how MuiscCompositions treat duration, examples 2 & 3 both use **duration**. These examples do validate with **duration** but in fact **duration** is not directly able to be part of MusicComposition. The validation for use of **duration** comes from their `@types`. So, again confusing.

**Comment by RichardWallis** [comment]
[Example 2](https://schema.org/MusicComposition#eg-0390) does reference a MusicComposition as it can be used for the value of the _recordingOf_ property of a _MusicRecording_ type.

You are correct that example 3 makes no reference to the _MusicComposition_ type and should be moved.

As to _duration_, the nearest property of _MusicComposition_ is _timeRequired_ which does not seem appropriate.  I would support adding the _duration_ property to _MusicComposition_.

**Comment by WeaverStever** [comment]
I believe that **MusicComposition** refers to the work itself, there does not need to be a recording to be considered published and therefore a duration would be incorrect as the tempo or Beats Per Minute (BPM) would be determined by the recording artist.  The MusicComposition (work / creativework) is the product that composer and lyricist put to paper.

The **MusicRecording** is a unique recording of the licensed work (MusicComposition) which is where the duration would be included. The MusicRecording (aka master) should maintain the same ISRC across mediums (CD, vinyl, tape, streaming) and subsequent licensed releases of the master by other labels / distributors.  An ISRC exception would be musicvideos, which are sometimes assigned different ISWC codes when the music is synced to film.

The **MusicRelease**, is the specific date / time for the region where the MusicRecording was released, for example US and Canada may have different release dates than the UK.  The MusicRelease can also denote the release on a different medium (CD, vinyl, tape, streaming), of the recording or the work.  Also, a re-release, perhaps on a "best of" album etc.

Two pieces of information that are missing from the music schema are the Interested Party Information (IPI), an identifier for performers, writers and publishers used by the Performing Rights Organizations (PRO - CMO). And the ISNI, which YouTube uses in their ContentID system.

**Comment by RichardWallis** [comment]
Upon reflection @WeaverStever's comment '_a duration would be incorrect as the tempo or Beats Per Minute (BPM) would be determined by the recording artist_' is correct and is probably the reason that it was not included in the original specification of this type.

To capture the duration of a piece, _MusicRecording_ should be used and related to the _MusicComposition_ description via the _recordingOf_ property.

As to example 3.  This has been removed from the specification via commit #f6eea29 and will [dis]appear in the next release.

@WeaverStever the IPI and ISNI could be applied using a _PropertyValue_ assigned to the _identifier_ property.

**Comment by WeaverStever** [comment]
I've published a related code example (workInProgress) here:

https://github.com/WeaverStever/MusicComposition---JSON-LD-example

**Comment by HughP** [comment]
thank you.

**Comment by WeaverStever** [comment]
@HughP 
If you go to https://github.com/notifications you can highlight the thread/mention and select "save" on the right hand side.
