### ISSUE TITLE
Nesting in PropertyValueSpecification's in Action.object and Action.result (input/output constraints)

### ISSUE THREAD

**Issue by SM0TVI** [schemaorg/schemaorg#3003]
So trying to wrap my brains around `Action`s, I found myself pondering questions which aren't clearly (to my reading) specified in the [Schema.org Actions document](https://schema.org/docs/actions.html). When specifying input/output parameter constraints, how deep nesting is allowed, if at all, when you have somewhat complex input and output parameters?
Another, related, question is what kind of references are allowed, i.e. whether you can specify by `{ "@id": ... }` or need to specify it all in one place.
As to my ideas if the answered aren't specified, I would only allow  `{ "@id" : ... }` references at the top level, i.e.
...
`"object" : {
  "@id" : "reference-to-separate-object-spec-here.ldjson"
},
"result":{
  "@id": "reference-to-separate-result-spec-here.ldjson"
}`
...
As to how deep nesting, I would personally expect on the order of 5 or 10 levels, I think either would cover the most complex input data before you would have to reasonably split it into appropriate sized and scoped chunks anyhow.
I ran across these questions when writing a `PropertyValueSpecification` for an `UpdateAction` on an object which has 2-3 levels of nesting on an object (TL;DR is updating various fields for a `Country` Type object).

**Comment by smrgeoinfo** [comment]
For the [EarthCube Resource Registry](https://doi.org/10.5281/zenodo.3840743) we've been working on how to describe APIs and service based distributions using schema:Action. Here's a couple examples of what we're suggesting:

https://github.com/earthcube/ecrro/blob/master/Examples/Interface-ChordsWebAPIv2-SDO-toLoad.json
https://github.com/earthcube/ecrro/blob/master/Examples/Service-IRIS-fsdnEvent-JSON.json

see also some issues I raised a while back https://github.com/schemaorg/suggestions-questions-brainstorming/issues/62
