### ISSUE TITLE
Validation Errors for Type Annotated Values in JSON-LD

### ISSUE THREAD

**Issue by tobiasschweizer** [schemaorg/schemaorg#3005]
We are using JSON-LD to represent our metadata. We are using <https://validator.schema.org> to make sure that our metadata is valid.

In some cases, we use type annotations in JSON-LD to express that a value is an `xsd:date` or `xsd:float` etc.

However, these annotations do not pass validation:
![Screenshot 2021-12-06 at 12 00 29](https://user-images.githubusercontent.com/6000023/144835043-cc6cff54-02d7-49bf-9af1-6f69938a0c0d.png)

We are using https://datashapes.org/schema.ttl as a reference implementation for our SHACL shapes that are applied in our own validation process. By convention, we encode an `schema:Date` as an `xsd:date`. For numerical values, we use `xsd:integer` or `xsd:float`, depending on the required precision.

Do the errors indicate that our data is actually wrong or is this rather a limitation of the validator (JSON-LD/RDF support)?

**Comment by tobiasschweizer** [comment]
Ok, thanks a lot for your answer. Does this mean that schema.org aware clients could not handle datatypes like `xsd:float` etc. correctly?

**Comment by jaygray0919** [comment]
IMHO you should "define your world" using `@context` and validate your expressions using SDL.
That will assure you that your expressions are correct.
In general, use a schema.org term and expand its definition using `sameAs`.
In other words, lead with schema terms/properties and complement your expressions with statements used by other structured data markups.
We are heavy users of `@Property` and `@Class` to implement/expand the implied logic encoded with `sameAs`.

**Comment by HughP** [comment]
Jay,
I'm learning something here about "sameAs" that I did not know before. That
is, I was only ever using "sameAs" to relate two physical entities within
the concept of Schema.org vocabulary. Such as a person described in my
resource and their wikidata entry. So I am wondering how the "sameAs"
concept works when defining @Property and @Class entities. Do you have some
code I can read to see what is being talked about? I am also recently doing
some work where I am mixing schema.org vocabulary with a custom vocabulary.

all the best,
- Hugh

**Comment by jaygray0919** [comment]
You can do a simple test. Identify a Wikidata property (with which you are familiar) that has no corresponding schema property.
Next, create a simple `@Class` tree (using `supersededBy`) where the leaf node is `sameAs` a schema type.
Then, for your new `@Property` set the`@Class` leaf node using `domainIncludes`.
Then validate on SMV.
When you share back your test case, I'll share a larger `@Graph` that uses `@Class` to organize `@Language` according to a Wikipedia tree.
Once you see that consumed on SMV, I'll share another example that implements `OWL` properties.
