### ISSUE TITLE
One ParentOrganization and 3 SubOrganization in same Address?

### ISSUE THREAD

**Issue by AngieRamIbiza** [schemaorg/schemaorg#3014]
I'm having an issue with my Local Bussiness. We offer 3 different services and now all of them will be in different web pages, domain etc. Plus the Parent organization, that makes 4 web pages, and in 2 languages makes 8 of them. How can I arrange the Schema situation? Can I use Parent/Sub as a solution? And what about the languages?

**Comment by RichardWallis** [comment]
The clue to the way forward maybe in your wording "_We offer 3 different services_"

I suggest you look into individually describing those [Service](https://schema.org/Service)s and link them via [Offer](https://schema.org/Offer)s to the organisation(s) offering them.

If you do have a hierarchy of organisations to describe, _parentOrganization_ & _subOrganization_ properties are designed for that purpose.  Make sure you include an identifying URI (in JSON-LD the @id value) in those descriptions, especially if the organisations have their own web presence.

Language [of display] for a page is more a topic for html issues.  However, description of a _Service_, can include via the _availableChannel_ property a descriptions of _ServiceChannel_ including _availableLanguage_.  Also when describing an _Organization_, _Service_ or whatever you have the option to provide multiple _name_ & _alternateName_ properties.
