### ISSUE TITLE
recreate schema.org/source with a sensible definition

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#3015]
Previously: 
  * https://github.com/schemaorg/schemaorg/issues/2435
  * https://github.com/schemaorg/schemaorg/issues/2919

Noting that Dublin Core [have](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/source) : 
  * Definition: "A related resource from which the described resource is derived."
  * Comment: "This property is intended to be used with non-literal values. The described resource may be derived from the related resource in whole or in part. Best practice is to identify the related resource by means of a URI or a string conforming to a formal identification system."

Various folks have requested something like this in Schema.org. It would be good to work through details. Is it for relations between documents (same as https://schema.org/isBasedOn ?). Provenance in some sense? etc.

**Comment by AlasdairGray** [comment]
Within the [Bioschemas](https://bioschemas.org) proposals we want to track the provenance of where we have reused a property or class definition, or taken inspiration from. For example, the [ChemicalSubstance](https://schema.org/ChemicalSubstance) reuses the definition of [ChEBI:59999 (Chemical substance)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=59999). Similarly several properties reuse definitions from other ontologies.

It would be good to formalise this link with a property.
