### ISSUE TITLE
Longitude example for Empire State Building should be negative value

### ISSUE THREAD

**Issue by mgh128** [schemaorg/schemaorg#3026]
The examples at https://schema.org/longitude and https://schema.org/longitude and https://schema.org/GeoCoordinates and https://schema.org/geo in Microdata, RDFa, JSON-LD for the Empire State Building (at 40.748433 N, 73.985656 W) should show a negative value (-73.98) instead of a positive value (73.98) because longitude is conventionally measured with positive values to the east of the prime / Greenwich meridian and with negative values to the west of the prime / Greenwich meridian.

Please correct the errors in the examples so that every occurrence of 73.98 becomes -73.98.

**Comment by RichardWallis** [comment]
Fixed in commit 1d8b0b3  wil appear in next release.
