### ISSUE TITLE
There is no way to specify the account details for service invoices

### ISSUE THREAD

**Issue by tmarshbing** [schemaorg/schemaorg#303]
From https://lists.w3.org/Archives/Public/public-vocabs/2015Jan/0126.html:

The water bill and Visa bill examples are still throwing me a bit. I feel that there ought to be somewhere to represent the original agreement between the consumer and the service provider and that the invoice should refer back to that thing. Without this, the invoice doesn’t adequately describe why payment is due. Do you agree? If so, how would you represent the original agreement? Maybe we need an Account type, or more specifically a ServiceAccount type? Something that would represent the current balance, transaction history (water usage in the water bill case, purchases, interest, and fees in the Visa case). Maybe we could include this type in a future iteration?

**Comment by thadguidry** [comment]
@tmarshbing The original agreement is actually in many cases an Order. http://schema.org/Order
The Order is the customers acceptance of an line from an Offer. http://schema.org/Offer
And we already have both.
Please review them both and see if there is something within Order or Offer that does not fit your liking and then add to this issue and change the issue title appropriately.

Also, you may want to scroll down through this list of Document Types from UBL 2.1 to see if there is a type that you are thinking of more specifically that Schema.org should have: http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.html#S-UBL-2.1-DOCUMENT-SCHEMAS

**Comment by tmarshbing** [comment]
@thadguidry Statement or Utility Statement from that list seem like the most applicable, but they weren't what I originally intended.

I now think there are two distinct concepts I was mixing up: agreements and statements. Let's take two examples:

Credit card:
- The agreement: In a credit card agreement, the consumer gets access to credit in exchange for a set of terms and conditions such as interest rates, repayment terms, penalties, credit limits, etc.
- The statement: In a credit card statement, the consumer can see things like the current month's activity, the periodic rate, credit available, etc.
- The "something else": In an online banking website, the consumer can also see more in-depth information on past purchases (not just this months'), payments, etc. Is this a statement, too?

Water service:
- The agreement: In the water service agreement, the customer gets access to water service at their residence in exchange for a set of terms and conditions such as backflow testing requirements, payment terms, penalties, etc.
- The statement: In a water service statement, the customer can see things like meter readings, consumption per day or per month, consumption vs. the same period last year, etc.

So, if I get an invoice/bill for a service, it seems like there is at least an agreement (aka contract?) and possibly also a statement associated with it. These are the concepts I think should be represented/linked. I don't see a way to specify any of the fields I listed in my examples on either Order or Offer. IMO, that's OK, because I think that agreement and statement are and should be separate concepts from Order or Offer.

**Comment by danbri** [comment]
Rescheduled for Q2, but it would be good to plan next steps here. @tmarshbing any thoughts? /cc @vholland

**Comment by tmarshbing** [comment]
@danbri I think we can move this to the distant, hazy future milestone. If we get more interest in making these additions, we can bring this back to a nearer milestone and have further discussion on the details. I don't have an immediate need for them.

**Comment by danbri** [comment]
Thanks, it has been sent into the future (like https://www.youtube.com/watch?v=nY3kZswIG3U ) but I'll leave it open so it is easier to find.
