### ISSUE TITLE
How to state education history?

### ISSUE THREAD

**Issue by goldingdamien** [schemaorg/schemaorg#3045]
Is there an appropriate way to record education history? (May not have received a credential)

The following schemas are available, but don't seem to specify long-term education information with dates.

https://schema.org/EducationEvent
https://schema.org/EducationalOrganization
https://schema.org/alumniOf
https://schema.org/alumni
https://schema.org/EducationalOccupationalCredential

**Comment by philbarker** [comment]
@goldingdamien The W3C [Credentials Community Group](https://www.w3.org/community/credentials/) has a working group [VC-Ed](https://github.com/w3c-ccg/vc-ed) which is looking at how to use [Verifiable Credentials](https://www.w3.org/TR/vc-data-model/) to do this. Essentially, the question is how to use the VC to provide the information about who's history it is, when it happened and who says so, all in a privacy-centric but sharable way.

**Comment by goldingdamien** [comment]
@philbarker Thanks. Looks good. Is there a common workaround while it is in early stages? Or should I just use custom schema or try to use the in-development models you linked?

**Comment by philbarker** [comment]
Sorry, I can't really say what you should do. Hopefully if you use the terms you mention above (along with [hasCredential](https://schema.org/hasCredential)) in the VC model you stray far from what VC-Ed finally comes up with.

**Comment by goldingdamien** [comment]
Ok, thanks.
