### ISSUE TITLE
EventSeries should accept ListItem under locations

### ISSUE THREAD

**Issue by dmcbrn** [schemaorg/schemaorg#3047]
Series of evens can all be held at different locations.

Probably related to #240

**Comment by chrisspradling1980** [comment]
Like a cult or socially pseudo political gang! Makes since sense I've been
wondering when programmers was gonna be making a gang ya heard me!!

**Comment by dmcbrn** [comment]
Is it correct to just add array of Locations? If so then this can be closed.

**Comment by dmcbrn** [comment]
You can use arrays of Events. It validates correctly in https://validator.schema.org/.

I do not know if there's any difference between using ListItem or array of objects.
