### ISSUE TITLE
 TradeAction should allow a priceSpecification as well as price

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#305]
TradeAction's price property only takes text or number. It should also take a PriceSpecification for more specific price models.

**Comment by vholland** [comment]
I just remembered that price is a property of PriceSpecification. To avoid a loop, the change should be to the "priceSpecification" property.

**Comment by danbri** [comment]
Done: http://sdo-stantz.appspot.com/TradeAction
