### ISSUE TITLE
Document Organization Annotations for Online Marketplaces 

### ISSUE THREAD

**Issue by MatthiasWiesmann** [schemaorg/schemaorg#3064]
There is currently no documentation for the new [`OnlineStore`](https://github.com/schemaorg/schemaorg/pull/3030) type, in particular for the case of sellers of online marketplaces.
The documentation should explain how the following seller information is expressed:

* Seller name
* Seller address
* Seller account age
* Seller image
* Seller logo
* Number of transactions
* Seller ratings

**Comment by danbri** [comment]
Can you suggest some example data that can be added in e.g. JSON-LD?

**Comment by danbri** [comment]
Added and published as part of v14 release. Thanks again!
