### ISSUE TITLE
Drug should inherit from Product

### ISSUE THREAD

**Issue by MatthiasWiesmann** [schemaorg/schemaorg#3069]
The [Drug](https://schema.org/Drug) object should inherit from [Product](https://schema.org/Product), as clearly these are _Any offered product or service_. In particular, the following Product attributes are relevant for Drugs: 

* [gtin](https://schema.org/gtin) – NDCs are mapped into GTIN space, and many countries have special GTIN ranges for drugs. 
* [releaseDate](https://schema.org/releaseDate)
* [countryOfOrigin](https://schema.org/countryOfOrigin)
* [offers](https://schema.org/offers)

The following attribute are already present in both objects:

* [manufacturer](https://schema.org/manufacturer)

**Comment by RichardWallis** [comment]
Seems like a good idea

**Comment by MatthiasWiesmann** [comment]
Added Pull Request #3094 that implements this. Also made DietarySupplement inherit from Product, for the same reasons.

**Comment by danbri** [comment]
Tagged for next release
