### ISSUE TITLE
Why is additionalType an URL?

### ISSUE THREAD

**Issue by xplosionmind** [schemaorg/schemaorg#3078]
In the [`additionalType` specification page](https://schema.org/additionalType) it is indicated that it should be an URL, shouldn’t it be `Text` or `itemList` (a list of additional types), instead?

**Comment by RichardWallis** [comment]
An additionalType should be a type from the Schema.org, or potentially another, vocabulary.

Such types are defined by their URL.  eg. https://schema.org/Product as per the [example](https://schema.org/additionalType#eg-0393) on the additionalType page.  In Microdata serialisation the full URL is quoted, in JSON-LD it is inferred from the context.

As per all properties in schema.org, multiple values can be supplied if needed.
