### ISSUE TITLE
Search results type title/anchor link elements (links) effectively disappear on hover- turning white

### ISSUE THREAD

**Issue by sheriffderek** [schemaorg/schemaorg#3090]
Title and screenshot will do the trick
![scheme org](https://user-images.githubusercontent.com/2066617/163453449-7f75c647-e730-4520-aea2-f79bf1dd0af4.png)

**Comment by ahmad-fayyaz** [comment]
I faced this problem while using the website too. I can work on this.

**Comment by ahmad-fayyaz** [comment]
Fixed! https://github.com/schemaorg/schemaorg/pull/3669

**Comment by alex-jansen** [comment]
PR merged, so closing this one. Thanks for fixing!
