### ISSUE TITLE
DataType has incorrect subClassOf definition

### ISSUE THREAD

**Issue by dgraham-io** [schemaorg/schemaorg#3105]
Current subClassOf: definition for schema:DataType  is
`{"@id": "rdfs:Class"}`
which doesn't exist, should be
`{"@id": "schema:Class"}`

**Comment by philbarker** [comment]
Hello David,  rdfs:Class is https://www.w3.org/2000/01/rdf-schema#Class

If you are parsing the schema.org definition files it's important to realise that it contains a few external references.

**Comment by dgraham-io** [comment]
ok, thanks.
