### ISSUE TITLE
HTML typo on "releases" page

### ISSUE THREAD

**Issue by lazaruscorporation** [schemaorg/schemaorg#311]
Current page at http://sdo-stantz.appspot.com/docs/releases.html#sdo-stantz reads "Corrected a case typo in Stéphane Corlosquet." due to missing quote in html. Submitting a porposed file change/pull request now...

**Comment by danbri** [comment]
Yay, typos in our typo fixes!

**Comment by lazaruscorporation** [comment]
Closing this as fix is now merged

**Comment by danbri** [comment]
Thanks, Paul!
