### ISSUE TITLE
Proposal to add a few properties to express shipping dimensions of a Product

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3120]
**Context** - This is a proposal from Google based on our experience consuming schema.org [Offer](https://schema.org/Offer) markup and working with similar data from online merchants. If it were accepted, it would make it easier for us and others to understand shipping dimensions (and associated delivery fees) for products sold online. 

**Proposal** - Schema.org supports the specification of product dimensions through properties [depth](https://schema.org/depth), [width](https://schema.org/width), [height](https://schema.org/height), and [weight](https://schema.org/weight). However, delivery dimensions of a product can be substantially different from the product's dimensions itself, for example flat-pack furniture that needs to be assembled after delivery, or fragile items that require heavy protective materials for transport. Such shipping dimensions can also vary depending on the merchant, so are typically related to an Offer and not a Product. We therefore propose to add 4 new properties _shippingWidth, shippingHeight, shippingLength_, and _shippingWeight_. All 4 properties will be of type [QuantitativeValue](https://schema.org/QuantitativeValue) and will be for use on class [Offer](http://schema.org/Offer).

**Alternatives**

*   Instead of adding 4 new properties we could add the existing [depth](https://schema.org/depth), [width](https://schema.org/width), [height](https://schema.org/height), and [weight](https://schema.org/weight) properties for use on [Offer](https://schema.org/Offer) (currently these are only available on Product). However, this might be ambiguous and cause confusion. 
*   A more flexible alternative would be adding the 4 existing properties [depth](https://schema.org/depth), [width](https://schema.org/width), [height](https://schema.org/height), and [weight](https://schema.org/weight) for use on [OfferShippingDetails](https://schema.org/OfferShippingDetails), which allows for multiple packaging options for the same product. However, this might be unnecessary since packaging is typically the same independent from the shipping destination. 
*   Yet another alternative would be adding a new _ShippingDimension_ structured type (to be used on [Offer](https://schema.og/Offer) using a new property), and adding the 4 existing dimension properties for use on this new type.
*   Instead of the "shipping" prefix we could decided to use a "package" or "shippingPackage" prefix for the property names.

**Comment by danbri** [comment]
Thanks, Martin!

**Comment by danbri** [comment]
pinging @mfhepp  - did you get a chance to look at this?

**Comment by danbri** [comment]
Let's not have height-related (sub?) properties for all the xyzHeight situations that might arise. Schema.org is broadly comfortable with having properties be specialized in different ways for different types without multiplying their names.

> A more flexible alternative would be adding the 4 existing properties [depth](https://schema.org/depth), [width](https://schema.org/width), [height](https://schema.org/height), and [weight](https://schema.org/weight) for use on [OfferShippingDetails](https://schema.org/OfferShippingDetails),

I suggest we start here.

**Comment by alex-jansen** [comment]
Released in 15.0
