### ISSUE TITLE
Proposal to add support for shipping origin

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3122]
**Context** - This is a proposal from Google based on our experience consuming schema.org [Offer](https://schema.org/Offer) markup and working with similar data from online merchants. If it were accepted, it would make it easier for us and others to understand delivery routes for products sold online.

**Proposal** - Schema.org supports the specification of shipping **destinations** (through the [shippingDestination](https://schema.org/shippingDestination) property) where an online merchant delivers ordered products to. However, Schema.org currently does not support shipping **origins**, where merchants ship the product from. Often a product's shipping source is relevant information for consumers, so propose to add a new _shippingOrigin_ property of type [DefinedRegion](http://schema.org/DefinedRegion) for use on type [OfferShippingDetails](https://schema.org/OfferShippingDetails).

**Alternatives** - Instead of adding the shipping origin under [OfferShippingDetails](https://schema.org/OfferShippingDetails) we could consider adding it under [Offer](https://schema.org/Offer) directly to avoid having to repeat the origin for every separate [OfferShippingDetails](https://schema.org/OfferShippingDetails) instance. However, the flexibility of having different origins depending on the destination is useful, especially for retailers with multiple fulfillment centers and warehouses.

**Comment by danbri** [comment]
Queued for staging

This seems a useful amendment to Schema.org's handling of shipping information - I am understanding this as feedback on the usefulness of OfferShippingDetails etc. during its Pending trial period. For now I have attached the new property just to that path, and solicit views on whether associating it also with Offer would be useful.

**Comment by danbri** [comment]
Prematurely marked as 'fixed'! Reopening.

**Comment by alex-jansen** [comment]
Released in 15.0
