### ISSUE TITLE
Proposal to add support for Amazon's ASIN product identifier

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3123]
**Context** - This is a proposal from Google based on our experience consuming schema.org [Product ](https://schema.org/Product)markup and working with similar data from online merchants. If it were accepted, it would make it easier for us and others to identify products sold online.

**Proposal** - Schema.org supports a variety of industry-standard product identifiers, for example [gtin](https://schema.org/gtin), [mpn](http://schema.org/mpn), and [nsn](https://schema.org/nsn). We propose to add a new property _asin_ of type [Text](https://schema.org/Text) for use on [Product](https://schema.org/Product), representing the Amazon Standard Identification Number. Given its common and broad use in the industry it would be beneficial to allow products to be identified with their corresponding ASIN code in structured data.

**Alternatives** - An alternative option would be supporting ASIN through the existing [productID](https://schema.org/productID) property. However, given the broad usage of ASIN, support as a first-class property seems more appropriate.

**Comment by ntwi** [comment]
I disagree and believe this will further enable monopolization from Amazon. Giving Amazon identifiers special treatment seems unfair in the grand scheme of things.

**Comment by chrisspradling1980** [comment]
This is not true what you just said.
The EWS is specifically put into dataset to mimick a human closet and
demonizing automation services is "Anti-trust" however, you just marked
"Anti-Commerce".

This is the last thing we need as freelance open source. The more
financially sound your bot reliance is, the healthier your online
entrepreneurship as presence takes presidencies.

**Comment by jdevalk** [comment]
Sounds smart indeed. We could add support to [Yoast WooCommerce SEO](https://yoast.com/wordpress/plugins/yoast-woocommerce-seo/) for this easily and quickly.

**Comment by danbri** [comment]
Thanks all

 * @ntwi I hear you and respectfully disagree. As is often the case, markup can have multiple uses. If you want to make the meaning of other identifiers widely understood, it is common to express mappings between identification schemes. By adding this very widely used identifier, Schema.org is providing a foundation that could be used for many things, including the expression of mappings to e.g. GTINs, or perhaps even Wikidata.
 * @chrisspradling1980 I see your comment but I really cannot understand it. I believe you're disagreeing with @ntwi's point and have not expressed a specific view on /asin as an addition to schema.org.
 * @jdevalk Thank you! Please update us here if/when you've added support.

I will go ahead and code this up for the Pending area (where as usual it will remain until we have evidence it is being consumed). I believe the most typical values will be strings but we should also anticipate the use of URIs/URLs as property values, similar to GS1's move towards [Digital Link](https://www.gs1.org/docs/Digital-Link/HowAndWhy_GS1_Digital_Link.pdf) with [/gtin](https://schema.org/gtin) /cc @philarcher. During Pending review we should also solicit Amazon (/cc @savas) for their perspective.

**Comment by jdevalk** [comment]
@danbri unfortunately, we/Yoast can't add support for ASIN until this gets merged, as the Schema validator will throw errors for it, causing a barrage of emails to our support team usually :)

**Comment by alex-jansen** [comment]
Released in 15.0
