### ISSUE TITLE
Search Page's Titles are white/disappear on hover

### ISSUE THREAD

**Issue by aliviarochester** [schemaorg/schemaorg#3126]
When using the search feature at the top of the website, the search results page (for example: https://schema.org/docs/search_results.html?q=real%20estate), has hover issues with the title color.

When hovering over the title, such as, "RealEstateListing - Schema.org Type", the title turns white, making it hard to read/ not ADA compliant. 

<img width="1096" alt="Screen Shot 2022-06-20 at 3 36 10 PM" src="https://user-images.githubusercontent.com/98556040/174668370-4042daaf-eb19-446b-a660-e91f1bb30da9.png">
<img width="336" alt="Screen Shot 2022-06-20 at 3 36 46 PM" src="https://user-images.githubusercontent.com/98556040/174668376-1c9747e0-e058-422c-9d98-4c10ef4eda5d.png">

**Comment by danbri** [comment]
@RichardWallis can you investigate?

**Comment by alex-jansen** [comment]
Looks like this has been resolved, at least I cannot reproduce.
