### ISSUE TITLE
Proposal to add new property /checkoutUrl on /Offer

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3135]
**Context** 

This is a proposal from Google based on our experience consuming schema.org markup and working with similar data from online merchants. If it were accepted, it would make it easier for us and others to understand URLs used by online merchants to send consumers to checkout pages for products sold online.

**Proposal** 

Schema.org currently provides a [/urlTemplate](https://schema.org/urlTemplate) property with values of type [/Text](https://schema.org/Text), used to specify a templated URL following [RFC6570](https://schema.org/urlTemplate). In the world of eCommerce, such templated URLs are important in the case of checkout URLs, where a consumer clicks on a product for a one-click purchase, sending the user directly to a checkout page, passing in parameters such as for example a logged-in consumer id, product identifier, quantity, discount code, and more.

We therefore propose to add a new **/checkoutUrl** property for use on the [/Offer](https://schema.org/Offer) type to allow merchants to specify a checkout page URL to allow online checkout of the offered product. The property would be a templated URL to allow passing-in of aforementioned parameters to the checkout page. We can decide to allow values of type [/Text](https://schema.org/Text) for **/checkoutUrl** or we could introduce new types, for example, **/UrlTemplate** as a subtype of [/Text ](https://schema.org/Text)or [URL](https://schema.org/URL).

**Comment by danbri** [comment]
Ok I have coded up the easy bits, but the question about the field names still needs some thought.

**Comment by danbri** [comment]
Rough cut: https://webschemas.org/checkoutPageURLTemplate

**Comment by danbri** [comment]
Staging looks OK (with minor tweaks today - fixed and refixed markup bug, and added another field, discount code). Queued for Release notes.

**Comment by alex-jansen** [comment]
Released in 15.0
