### ISSUE TITLE
Add MovieClip as a parallel to TVClip and RadioClip

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#314]
schema.org/TVClip and schema.org/RadioClip exist. It would be nice to have a type for MovieClip.

**Comment by danbri** [comment]
Would we have VideoGameClip too?

**Comment by chaals** [comment]
+ reply@- notifications@Without being up to my neck in the sue cases, I would prefer to have "audioClip" and "VideoClip" (although they might keep the historic names). cheers 31.01.2015, 02:30, "Dan Brickley" <notifications@github.com>:Would we have VideoGameClip too?—Reply to this email directly or view it on GitHub.   --Charles McCathie Nevile - web standards - CTO Office, Yandexchaals@yandex-team.ru - - - Find more at http://yandex.com

**Comment by danbri** [comment]
While we're here - to clarify, are 'audio'(AudioObject)  and 'video('VideoObject') the right way to link the actual audio/video contents of a clip? i.e. there's an indirection through a MediaObject to get to the actual bytes via http://schema.org/contentUrl ... (and via other structures for embedded players)

**Comment by vholland** [comment]
+1 to some value in knowing the clip is part of TV, Radio, etc is useful.

I considered proposing VideoGameClip as well, so it may be worthwhile to add it at the same time.

**Comment by danbri** [comment]
@vholland  - since we try not to 'over model' things via intermediate types ("SubtypableOnlineMediaClipEntityPrototype etc :), I think the pressure is more on us here socially to make sure relevantly similar terms get treated reasonably similarly. We've done that when adding video game lately so it seems worth tracking that here if possible.

**Comment by vholland** [comment]
See https://github.com/schemaorg/schemaorg/pull/326/files

**Comment by tmarshbing** [comment]
+1 to MovieClip, VideoGameClip vs. AudioClip, VideoClip. The former matches how we have modeled series, seasons, and episodes, which seem conceptually closer to clips than MediaObject does.

**Comment by vholland** [comment]
Merged into sdo-gozer.
