### ISSUE TITLE
BroadcastService supertype should be Service, not Thing.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#315]
We have a variety of service-related types, and it makes not sense for BroadcastService to sit at the top below http://schema.org/Thing - let's find a better home for it. Proposal: set supertype of BroadcastService to be http://schema.org/Service. It was a mistake to add it under Thing, rather than under Intangible or Service.

Nearby we currently have:

* <http://schema.org/Service> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/Intangible> .
* <http://schema.org/FinancialService> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/LocalBusiness> .
* <http://schema.org/ProfessionalService> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/LocalBusiness> .

Although you could argue that the FinancialService and ProfessionalService types aren't necessarily local and also shouldn't be all under http://schema.org/Service, that's a wider debate. 

http://schema.org/Service seems a bearable if vague fit. It is under Intangible, and already has a couple of subtypes (Taxi and GovernmentService).

/cc @vholland

**Comment by rvguha** [comment]
sgtm

**Comment by jvandriel** [comment]
Sorry for crossposting but could http://schema.org/MedicalProcedure have http://schema.org/Service set as supertype as well, as raised in issue #296 ?

**Comment by tmarshbing** [comment]
This change looks good, but it also creates an awkward duplication between area and serviceArea, both of which are now applicable to BroadcastService. Should we deprecate area as part of this change?

**Comment by vholland** [comment]
+1 to deprecating area.
