### ISSUE TITLE
Missing description for CollectionPage

### ISSUE THREAD

**Issue by alexander-schranz** [schemaorg/schemaorg#3153]
I'm searching what the correct type of a overview webpage is. Example a "Blog Overview" or a "News Overview" or "Product Overview". I did stumble over the `CollectionPage` but I'm not sure if that is correct. Also not sure how pagination is handled in schema org to tell that it is over multiple pages? An example of a "Overview" Page with pagination I think would be great and is a common usage on every website.

**Comment by WeaverStever** [comment]
@alexander-schranz 

Have you had a look at https://schema.org/CreativeWorkSeries ? 

This would probably be correct for a Blog or a News overview,  [offers](https://schema.org/offers) and [reviews](https://schema.org/review) appear to be eligible properties for products.

> ...[hasPart](https://schema.org/hasPart) / [isPartOf](https://schema.org/isPartOf) properties can be used to relate the CreativeWorkSeries to its parts.

For haspart and ispartof, Yoast has an interesting (advanced) concept.
https://yoast.com/yoast-seo-11-0/

**Comment by alexander-schranz** [comment]
Thx for the links sounds very interesting.
