### ISSUE TITLE
/distribution should make it more clear that property is repeatable

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#3155]
https://schema.org/distribution 

> A downloadable form of this dataset, at a specific location, in a specific format.

I suggest at a minimum,

> A downloadable form of this dataset, at a specific location, in a specific format. This property can be repeated if different variations are available.

**Comment by danbri** [comment]
(this is motivated by user/publisher feedback around Google Dataset Search, where the repeatability wasn't obvious from schema.org documentation)

**Comment by smrgeoinfo** [comment]
+1.

**Comment by danbri** [comment]
Thanks, @smrgeoinfo 

It only took a minute so here's [a commit](https://github.com/schemaorg/schemaorg/commit/f773323e191920894ee8d09ff4e49761d975683f).

Queued for staging.

**Comment by danbri** [comment]
Tweaked further in https://github.com/schemaorg/schemaorg/commit/c09523ea5b824952f5c1e3a01e2c8fd3eb9d212f including adding "all or part" to DataDownload.

> -    rdfs:comment "A dataset in downloadable form." ;
> +    rdfs:comment "All or part of a [[Dataset]] in downloadable form. " ;

**Comment by RichardWallis** [comment]
Implemented
