### ISSUE TITLE
Missing field "applicantLocationRequirements" in Job Posting

### ISSUE THREAD

**Issue by abhi28091989** [schemaorg/schemaorg#3161]
I am using WordPress Plugin [https://wordpress.org/plugins/job-postings/](url)
I got an Error in google search result Job posting 

> Missing field "applicantLocationRequirements"

Please find SS Here: [https://snipboard.io/5soeRx.jpg](url)
[https://snipboard.io/D6Susx.jpg](url)

I have coding exist in my plugin for "applicantLocationRequirements" field
` 
                        if( $remote == 'on' && $remote_data ){
                            $remote_data = unserialize($remote_data);

                            if( count($remote_data) >= 1 && $remote_data[0]['type'] != '' && $remote_data[0]['name'] != '' ){

                                if(count($remote_data) == 1){
                                    self::$json_ld['applicantLocationRequirements'] = json_decode(json_encode(array('@type' => $remote_data[0]['type'], 'name' => $remote_data[0]['name'])), FALSE);
                                }else{
                                    $data_array = array();
                                    foreach($remote_data as $data){
                                        $data_array[] = array('@type' => $data['type'], 'name' => $data['name']);
                                    }
                                    self::$json_ld['applicantLocationRequirements'] = json_decode(json_encode($data_array), FALSE);
                                }
                            }
                        }

                        if( $remote == 'on' ){
                            self::$json_ld['jobLocationType'] = "TELECOMMUTE";
                        }`
Please Suggest me Something i am really Fadeup  with that.

**Comment by RichardWallis** [comment]
@abhi28091989 Indeed your page is not outputting an [applicantLocationRequirements](https://schema.org/applicantLocationRequirements) property for the [JobPosting](https://schema.org/JobPosting) type as can be seen from the [Markup Validator](https://validator.schema.org/#url=https%3A%2F%2Fjobfyworld.com%2Fjob%2Fcashkaro-recruitment-2022-jobs-for-freshers-analyst-customer-relationship-management-posts%2F).

As all properties in the vocabulary are optional, that is not an error.

However, some data consumers do place stricter constraints on their data requirements.  Issues regarding such should be addressed to their support forums.

As to the Wordpress plugin you are using not outputting markup that matches such requirements, it is their support channels that should be used to ask for enhancements to reflect your needs.

This is not the place to address either of those issues beyond the Schema.org vocabulary itself.

**Comment by abhi28091989** [comment]
But how to solve that i really need an suggestions.
