### ISSUE TITLE
Validator cannot recognise mixture of tagged and untagged strings in JSON-LD

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#3165]
A combination of language tagged and untagged strings assigned to a single property causes the tagged strings to be reported as errors.  

Cut down example:
```
{
    "@context": "https://schema.org",
    "@type": "schema:Person",
    "name": "Lee, Kuan Yew",
    "alternateName": [
        "Li Guangyao",
        "LKY",
        {
            "@language": "zh",
            "@value": "李光耀"
        },
        {
            "@language": "ta",
            "@value": "லீ, குவான் யூ"
        },
        "Harry Lee Kuan Yew"
    ],
    "birthDate": "1923-09-16"
}
```
Results in : 
![image](https://user-images.githubusercontent.com/13315406/185806724-1d4ff7b7-d5a8-4653-ab8c-47a2e0c41765.png)
 
Remove the non-tagged strings from the array assigned to the alternateName property and the tagged strings are captured correctly:
![image](https://user-images.githubusercontent.com/13315406/185806882-b1f5f4a9-1ab7-4c18-8c16-d1458106365f.png)

Remove the tagged strings and the non-tagged strings are captured correctly.

Separate the tagged and non-tagged arrays into separate statements, results in a _Duplicate key found_ error.

Outcome is that you cannot represent a name, alternateName or similar properties with multiple values if they are a mixture of tagged and untagged strings.  A common occurrence in countries where English is not the, or only, primary language.

Note: Other tools such as the JSON-LD Playground correctly process the example.

**Comment by rrlevering** [comment]
This should be working as intended now.  @value tags have much better support now in JSON-LD parsing (though SMV doesn't show language of the triple in the UI).

**Comment by RichardWallis** [comment]
Thanks @rrlevering for the fix!

> (though` SMV doesn't show language of the triple in the UI).

Would be nice if it did someday ;-)

Closing issue
