### ISSUE TITLE
JsonLd set hiringOrganization as confidential but only shows the string confidential expected?

### ISSUE THREAD

**Issue by 28development** [schemaorg/schemaorg#3170]
### Discussed in https://github.com/schemaorg/schemaorg/discussions/3169

<div type='discussions-op-text'>

<sup>Originally posted by **28development** August 25, 2022</sup>
Hi,

Not sure if this is the expected behavior so I am just asking here:

We added JsonLd to our site and it works good so far, but I think that the confidential property does not really work in our setup.

This is out setup:

```
{
   "@context":"https://schema.org",
   "@type":"JobPosting",
   "datePosted":"2022-08-25",
   "description":"exam. Altenpflegefachkraft (m/w/d) - Vielfalt am Arbeitsplatz entdecken!",
   "title":"exam. Altenpflegefachkraft (m/w/d) - Vielfalt am Arbeitsplatz entdecken!",
   "employmentType":[
      "full_time",
      "part_time"
   ],
   "baseSalary":{
      "@type":"MonetaryAmount",
      "currency":"EUR",
      "value":{
         "@type":"QuantitativeValue",
         "unitText":"MONTH",
         "minValue":3100,
         "maxValue":3600
      }
   },
   "hiringOrganization":"confidential",
   "jobLocation":{
      "@type":"Place",
      "address":{
         "@type":"PostalAddress",
         "addressCountry":"Deutschland",
         "addressLocality":"München",
         "postalCode":"81925"
      }
   },
   "applicantLocationRequirements":{
      "@type":"Country",
      "name":"DE"
   }
}
```

This is how we set the confidential prop like it is described in the docs:

`   "hiringOrganization":"confidential",`

But currently the JSON-LD view shows as a company name "confidential" which is wrong I think, what are we missing here?
Seems like schema.org does not even have a properly with the name `confidential` for the organization field.

**Comment by danbri** [comment]
No need to duplicate your existing discussion post. Schema.org is independent from Google. I will - as I said - investigate and report back.
