### ISSUE TITLE
The isPartOf column is empty in CSV downloads

### ISSUE THREAD

**Issue by jrockowitz** [schemaorg/schemaorg#3180]
The isPartOf column in the [schemaorg-all-https-properties.csv](https://github.com/schemaorg/schemaorg/blob/main/data/releases/14.0/schemaorg-all-https-properties.csv) is completely blank meanwhile, in [schemaorg-all-https.jsonld](https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/14.0/schemaorg-all-https.jsonld ) , the 'schema:isPartOf' is populated as expected.

I noticed this because the isPartOf column for the https://schema.org/Schedule  type should contain https://pending.schema.org.

**Comment by jrockowitz** [comment]
@RichardWallis Thank you for the quick fix.

**Comment by RichardWallis** [comment]
Released in V15.0
