### ISSUE TITLE
Proposal: ItemAvailability : MadeToOrder

### ISSUE THREAD

**Issue by jwaes** [schemaorg/schemaorg#3183]
I would propose to add the ItemAvailablity enumeration an entry that represents the case where a product is made to order. This use-case does not fit in any of the available entries.

https://schema.org/ItemAvailability

**Comment by mfhepp** [comment]
Sounds good to me.

**Comment by alex-jansen** [comment]
This was [added](https://schema.org/MadeToOrder) as part of Release 28.0
