### ISSUE TITLE
Add /additionalProperty for use on /Offer

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3199]
Currently /additionalProperty is available on /Product but not on /Offer. We propose to extend it for use on /Offer to allow the representation of additional offer characteristics as property-value pairs.

**Comment by whitten** [comment]
Sales tax is often dependent upon the geographic region where the sale occurs. 

How do you intend to model this ?

**Comment by alex-jansen** [comment]
Added in #3441
