### ISSUE TITLE
Recipe recipeIngredient is Text but can be also ItemList

### ISSUE THREAD

**Issue by alexander-schranz** [schemaorg/schemaorg#3200]
Currently https://schema.org/Recipe but in the example it is a array list so I think it should not only be defined as `Text` but also as `ItemList`.

**Comment by rrlevering** [comment]
Arrays in JSON-LD syntax don't imply http://schema.org/ItemList currently.  Every predicate in schema.org is allowed to be specified multiple times and in JSON-LD that's the syntax to do that.

**Comment by rrlevering** [comment]
And as a rule of thumb, ItemList tends to be added to things only when order is seen as very intrinsic/important (which RDF doesn't have by default).

**Comment by alexander-schranz** [comment]
@rrlevering thank you for the clarification!
