### ISSUE TITLE
Broken link/typo on releases page

### ISSUE THREAD

**Issue by lazaruscorporation** [schemaorg/schemaorg#321]
On the releases page, in the section for the latest 1.93 releases, the first line contains a typo ("materials" should be "material") and the link should got to schema.org/material not schema.org/materials (the latter correctly produces a 404 error)

**Comment by lazaruscorporation** [comment]
Fixed the above in PR #322

**Comment by danbri** [comment]
At least the 404 was right ;) Thanks, will sneak the fix in.
