### ISSUE TITLE
Question: can articleBody accept Array of Text?

### ISSUE THREAD

**Issue by X7md** [schemaorg/schemaorg#3231]
Hi, I have question about `articleBody`.

let's say: I have this markdown

```md
# Big Title
Paragraph

## Heading
Paragraph below heading...

## Another heading...

Paragraph below another heading...
```

I wanna do something like:

```json
{
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      "headline": "Big Title",
      "articleBody": [{
      "@type": "Text",
      "value": "Paragraph",
      },
      {
      "@type": "Text",
      "Heading": "Heading",
      "value": "Paragraph below heading...",
      },
     {
      "@type": "Text",
      "Heading": "Another heading...",
      "value": "Paragraph below another heading...",
      },
      ],
      "datePublished": "2015-02-05T08:00:00+08:00",
      "dateModified": "2015-02-05T09:20:00+08:00",
      "author": {
          "@type": "Person",
          "name": "me",
          "url": "https://example.com/profile/me"
        }
}
```

Is that make sense?

**Comment by RichardWallis** [comment]
Unfortunately no.

[Text](https://schema.org/Text) is a Data Type and as such does not have properties such as _heading_.

As all properties are repeatable in Schema you could have repeated _articleBody_ properties but I'm not sure that is what you want, or how it would be interpreted by data consumers.

There has been discussion elsewhere #3033 as to how Text and its [subtypes](https://schema.org/Text#subtypes) may be expanded/improved to handle situations that might include yours - although the discussion is quiet at the moment.
