### ISSUE TITLE
Validator is not working

### ISSUE THREAD

**Issue by fajela** [schemaorg/schemaorg#3233]
Not sure who to address with that. But schema validator is not working for 12+ hours -> https://validator.schema.org/
It throws a message: "There was an error validating your mark-up." for anything at all. If I could help with bringing it back to life, I'd be happy to.

**Comment by RichardWallis** [comment]
Its working for me.

Do you have a URL or sample that is failing for you?

**Comment by fajela** [comment]
Now working for me as well. thanks!

**Comment by danbri** [comment]
There was an issue with excessive automated page requests, now fixed. As a
reminder, this service is designed for humans to use and not as a web
service software component.

Cheers,

Dan

**Comment by CharlieDigital** [comment]
@danbri is the source for the validator available in one of the repos?  As in #3262 I think folks are willing to run it themselves.

**Comment by danbri** [comment]
No, it is a part of the Google Search infrastructure and not suitable for
release
