### ISSUE TITLE
Add paymentUrl to Invoice

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#327]
From [public-vocabs](http://lists.w3.org/Archives/Public/public-vocabs/2015Feb/0022.html):

"I saw your thread 'New schema for Invoices' and looks like it has already been published - http://schema.org/Invoice One property that seems to be missing is 'paymentUrl'. I do see it as part of http://schema.org/Order, but should we also add it to Invoice?"

Seems reasonable to me.

**Comment by danbri** [comment]
This sounds plausible to me, +1.

**Comment by vholland** [comment]
I'm going to contradict myself. Should we instead prefer PayAction? You would have:

{
  "@context": "http://schema.org/",
  "@type": "Invoice",
  "description": "January 2015 American Express bill",
  "potentialAction": {
    "@type": "PayAction",
    "target": "http://www.amex.com/january_2015_bill"
  }
}

If so, we should deprecate paymentUrl in favor of this mechanism across the board.

**Comment by dschulten** [comment]
To help decide this, it would be good to have an analyis of some flows which show how payments really work with actual payment providers. It seems payments are usually handled not by just GETting some URL but by server-side procedures and redirects which finally bring you to a page where you enter account data or payment details which are specifically for your invoice. You hardly ever go to a payment url with a form just like that. Hence I am afraid a simple payment url is not of much use, no matter if it is on PayAction or on Invoice.

**Comment by tmarshbing** [comment]
I agree with @dschulten that a simple URL doesn't fully model the payment interaction. I personally would still make the change @vholland suggested to support PayAction as a potentialAction on an Order or Invoice and deprecate paymentUrl. For now, the action can just be used to navigate the consumer to the URL where they can go through the flow @dschulten describes. In future updates, we can add additional complexity to mark up more of this process if desired.

**Comment by vholland** [comment]
The discussion seems to have quieted. I'm going to close the issue for now and we can re-open if people still feel a need for this property.
