### ISSUE TITLE
Product image is missing

### ISSUE THREAD

**Issue by sovetski** [schemaorg/schemaorg#3278]
Hi,

On this documentation: https://developers.google.com/search/docs/appearance/structured-data/product, we have an 'image' for the Product like:
`{
...,
  "image": "https://www.example.com/waterheater.jpg",
...
}`

But on the official documentation: https://schema.org/Product, we have only 1 "image" field, but it is added under "Properties from Thing" instead of "Properties from Product", maybe it can be used on both?

**Comment by Tiggerito** [comment]
It can. The Product class inherits properties from the classes it is based on. And everything is based on Thing.
