### ISSUE TITLE
Markup errors in AggregateOffer examples

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#3298]
The https://schema.org/AggregateOffer markup examples contain a couple of errors:
```
"offers": {
    "@type": "AggregateOffer",
    "highPrice": "$1495",
    "lowPrice": "$1250",
    "offerCount": "8",
```
and

```
"offers": {
    "@type": "AggregateOffer",
    "lowPrice": "$35",
    "offerCount": "1938"
```

In both case there's a price currency symbol in the pricing values. Providing number values and adding a `priceCurrency` property instead would be better. Secondly in JSON-LD `Number` values should be without double quotes.
```
"offers": {
    "@type": "AggregateOffer",
    "priceCurrency": "USD",
    "highPrice": 1495,
    "lowPrice": 1250,
```
And the second example only has a `lowPrice`. Since there's no `highPrice` it'd be better to use `price` instead.

```
"offers": {
    "@type": "AggregateOffer",
    "priceCurrency": "USD",
    "price": 35,
    "offerCount": 1938
```

**Comment by RichardWallis** [comment]
Whilst inspecting errors in identified examples ([eg-0011](https://schema.org/AggregateOffer#eg-0011), [eg-0461](https://schema.org/AggregateOffer#eg-0461)) also identified similar 'priceCurrency' in near by Offer examples ([eg-0174](https://schema.org/Offer#eg-0174), [eg-0202](https://schema.org/Offer#eg-0202), [eg-0208](https://schema.org/Offer#eg-0208))

Will fix together

**Comment by jvandriel** [comment]
Thanks @RichardWallis

**Comment by jvandriel** [comment]
No worries, I don't want to put it all on your back. 

The reason I asked is because quite recently, yet again, I had a discussion with some folks about how they sometimes don't understand the often subtle differences between schema.org examples and those provided by Google, and that because of this markup examples copied from schema.org sometimes don't seem to satisfy the Rich Result Test even after they have modified their examples.

And so I'm contemplating helping out by by going through (all of?) schema.org examples to see what I can update and actualize to modern patterns.

Now don't get me wrong, I don't intend on making sure everything complies with what Google wants (not that crazy), it's more about actualizing as many of the examples as I can, thus trying to prevent copy and paste errors for folks that aren't all that experienced in this stuff.
