### ISSUE TITLE
Unlimited integer value for JSON-LD schema

### ISSUE THREAD

**Issue by alexanderdross** [schemaorg/schemaorg#3299]
How would you write an AggregateOffer schema JSON-LD to display an unlimited "offerCount" parameter

E.g if the digital product such as a PDF is available for free and therefore unlimited available

**Comment by RichardWallis** [comment]
You are misinterpreting the meaning of _offerCount_ in the context of the use of [AggregateOffer](https://schema.org/AggregateOffer): 

> "_When a single product is associated with multiple offers (for example, the same pair of shoes is offered by different merchants), then AggregateOffer can be used._"

In that case _offerCount_ indicates the number of separate Offers aggregated together, not the number of products available.
