### ISSUE TITLE
Need a way to specify minimum required order on DeliveryChargeSpecification

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#330]
DeliveryChargeSpecification allows an author to specify a deliveryMethod, eligibleRegion, and price, but there is no way to specify a minimum purchase for delivery. For example, many sites have different delivery price structures. I may pay $5 for delivery, but order over $50 are free.

We should add a minimumRequiredPurchase property to specify the purchase required for the given delivery charge.

**Comment by vholland** [comment]
See [change #338](https://github.com/schemaorg/schemaorg/pull/338/files).

**Comment by tmarshbing** [comment]
Should this include both the price and the currency, or is the currency expected to be inferred from the price specification for the item(s) being delivered? Also, the range for price is Number or Text, but for minimumRequiredPurchasePrice is only Number. Why the discrepancy?

**Comment by vholland** [comment]
I assumed minimumRequiredPurchasePrice would use the same currency as the "price" in the PriceSpecification.

The discrepancy on Number vs Text was an oversight on my part. I'll fix that.

**Comment by tmarshbing** [comment]
Makes sense. Thanks.

**Comment by vholland** [comment]
I added Text.

**Comment by tmarshbing** [comment]
@vholland, which commit? I don't see it.

**Comment by vholland** [comment]
@mfhepp pointed out on Issue #338 that this idea already exists as http://schema.org/eligibleTransactionVolume, so I deleted the change.
