### ISSUE TITLE
in csv, DataType's subTypeOf is not Class

### ISSUE THREAD

**Issue by huang12zheng** [schemaorg/schemaorg#3305]
in csv, DataType's subTypeOf is 
https://schema.org/http://www.w3.org/2000/01/rdf-schema#Class. it should be https://schema.org/Class
or just http://www.w3.org/2000/01/rdf-schema#Class

you could also find raw data with 'search 
`http://schema.org/http://www.w3.org/2000/01/rdf-schema#Class`'  in
https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/15.0/schemaorg-current-http-types.csv

**Comment by RichardWallis** [comment]
Fixed in source - will appear in next release.
