### ISSUE TITLE
AddressCountry description recommending ISO-3166-1

### ISSUE THREAD

**Issue by nissimsan** [schemaorg/schemaorg#3310]
In an effort to get more consistent data, we recently cranked up the description of addressCountry in our reference to https://schema.org/addressCountry, being slightly more insisting using ISO 3166-1 alpha-2 country code: https://github.com/w3c-ccg/traceability-vocab/pull/282

Would you consider the same? For example changing the description to a recommendation: 

> The country. The use of two-letter [ISO 3166-1 alpha-2 country code](http://en.wikipedia.org/wiki/ISO_3166-1) is recommended, for example, US.

**Comment by nissimsan** [comment]
Hi Dan, 

Sure. The ambition is to build cross-border supply chain knowledge graphs. Data structures generally aligns with traditional paper forms (think Invoices, Bills of Lading, Purchase Orders, etc), but is wrapped as Verifiable Credentials, so you can sign data platform-independently. 

When assembling data graphs, `US` and `USA` becomes two separate nodes, although the intention is to reference the same country. So we're asking to guide users providing a consistent alpha-2 formatting to make nodes snap together more easily.

**Comment by LarsArtmann** [comment]
I would consider this still relevant, every time I read the current description the "US**A**" confused me.

**Comment by miller79** [comment]
Can this issue be closed with the merged changes from this PR? #3364

**Comment by nissimsan** [comment]
@miller79 , yes certainly an improvement. Let's get this closed - thank you everyone!
