### ISSUE TITLE
Solving for Spamming of Dataset Provenance

### ISSUE THREAD

**Issue by icy-td** [schemaorg/schemaorg#3337]
The page ecb929(dot)com(slash)clinton-body-count-spreadsheet (URL has be obfuscated) is a scraped, corrupted version of tesladeaths.com that sports an equally fraudulent version of the site's dataset structured data. Because of the scraped and doctored structured data, the spam site apparently hijacked the provenance of the dataset and influenced the Google Dataset Search: https://datasetsearch.research.google.com/search?src=3&query=tesla%20deaths&docid=L2cvMTF0X3Q0a3dwcg%3D%3D . "Tesla Lethality Dataset" is **not** the canonical version.

Besides attempting to alert Google about the spam site (which hasn't helped at all) I want to propose adding a new, negative property. Ideally, the property would indicate that a dataset, a website, any creativework is distinct from some provided URL and that the provided URL is spam. I recognize that disambiguatingDescription exists, but also that it is description-based and unlikely to be useful for crawlers, etc. Ideas welcome.

**Comment by MatthiasWiesmann** [comment]
I will argue that the certification object and the W3C trusted credentials are a better solution to this.
Closing, please reopen if needed.
