### ISSUE TITLE
the schema.org context contains a duplicate key "geo"

### ISSUE THREAD

**Issue by pchampin** [schemaorg/schemaorg#3339]
... and some JSON parsers are choking on this.

More precisely, the first "geo" (line 17) is used as the common namespace prefix for http://www.opengis.net/ont/geosparql#, while the second one (line 1959) is a shortcut for http://schema.org/geo .

I think the best solution is to remove line 17:
- the other declaration of "geo"  is more directly useful for schema.org users
- nowhere in the context is the `geo:` prefix used
- in all the parsers that I have tested, line 1959 overrides line 17 anyway

**Comment by pchampin** [comment]
Oh, and by the way, while duplicate keys are tolerated in JSON, they are explicitly forbidden in JSON-LD:

https://www.w3.org/TR/json-ld11/#dfn-json-object

> In JSON-LD the names in an object must be unique.

**Comment by RichardWallis** [comment]
Fix will appear in next release
