### ISSUE TITLE
accessibilityHazard content

### ISSUE THREAD

**Issue by philwareham** [schemaorg/schemaorg#334]
The Schema.org site lists the following example `content` for `accessibilityHazard`...

    <meta itemprop="accessibilityHazard" content="noFlashing"/>
    <meta itemprop="accessibilityHazard" content="noMotionSimulation"/>
    <meta itemprop="accessibilityHazard" content="noSound"/>

But the linked reference page [WebSchemas wiki lists possible values](http://www.w3.org/wiki/WebSchemas/Accessibility) lists them as follows...

    <meta itemprop="accessibilityHazard" content="noFlashingHazard"/>
    <meta itemprop="accessibilityHazard" content="noMotionSimulationHazard"/>
    <meta itemprop="accessibilityHazard" content="noSoundHazard"/>

Which is the correct implementation? Thanks!

**Comment by danbri** [comment]
@chaals can you take a look?

**Comment by chaals** [comment]
It's listed "implemented on 10-100 pages". I suggest we change the schema.org content.

**Comment by chaals** [comment]
Hopefully I'll make a pull request to do this.

Having hazard in the name seems better - not all flashing is a flashing hazard…

**Comment by philwareham** [comment]
Makes sense to me, thanks!

**Comment by chaals** [comment]
Worky for you?

**Comment by danbri** [comment]
Alright, this is merged in and queued for the next release which I'd like to see out in a modest number of days...
