### ISSUE TITLE
Schema for medical website

### ISSUE THREAD

**Issue by hamza00199** [schemaorg/schemaorg#3340]
I have a website on menstruation. It has four categories. The first three are related to "menstrual health," and the fourth one is related to "affiliate menstrual products." I am using the "medicalwebpage" schema for the first three categories and the "article" schema, along with the "product" schema, for the fourth category. In this "article schema" for the fourth affiliate product category, I am using "medicalwebpage" as the "mainentityofpage" because my affiliate article also has the "lastreviewed" and "reviewedby" schema, which are properties of a webpage, not the article itself. 
(Please note that we are a team of doctors, and this website is based on medical content related to menstruation)
1) Am i using correct structure? 
2) What if i use "article" schema on all 4th categories with "medicalwebpage" as "mainentityofpage"? 
3) What if i use "medicalwebpage" schema on all 4th categories with "article" as "mainentityofpage"? 
4) Or i have to use "medicalwebpage" for the first 3 categories and "webpage" for the product one? 
5) Also many websites are using "newsarticle" schema for their product pages?
Kindly answer me in details as i am very confused about these schemas. Thankyou

**Comment by MatthiasWiesmann** [comment]
Schema.org only defines the schema, not how various systems, including web-indexers will interpret them.
I think you question pertains to the second category.
