### ISSUE TITLE
VideoGameSeries example on VideoGame uses gameLocation

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#335]
On:
http://schema.org/VideoGame

The last example (JSON-LD) is for VideoGameSeries, and employs the property "gameLocation".

`<script type="application/ld+json">`
`{`
`  "@context": "http://schema.org",`
`  "@type": "VideoGameSeries",`
`  "name":"Mass Effect",`
`  "genre":["ARPG", "third-person shooter"],`
`  "author":"BioWare",`
`  "character":{`
`  "@type":"Person",`
`  "name":"Shepard",`
`  "birthDate":"2154-04-11"`
`  },`
`  "gameLocation":`
`  {"@type":"Place",`
`  "name":"Citadel",`
`[...]`

However, while "gameLocation" is a valid property for VideoGame, it is *not* a valid property for VideoGameSeries.

**Comment by thadguidry** [comment]
Would you rather it be called gameSeriesLocation ?

**Comment by Aaranged** [comment]
@thadguidry "gameLocation" is just fine.  The bug I'm pointing out isn't that the label is a bad one, but that the example for VideoGameSeries uses a property - gameLocation - which isn't a property listed under VideoGameSeries.

Either removing the gameLocation property declaration from the example *or* adding gameLocation as a property under VideoGameSeries will clean up the example.  FWIW I favor the latter, as indeed a video game *series* can have a location.

**Comment by danbri** [comment]
Thanks. It seems appropriate to allow this, one way or another.

**Comment by vholland** [comment]
+1 It seems more useful to add gameLocation to VideoGameSeries rather than modifying the example.

**Comment by danbri** [comment]
I'll tentatively add it to the sdo-gozer build, but let's get some more +1s here before confirming. @tilid ? @tmarshbing @pmika ?

**Comment by thadguidry** [comment]
+1 to add gameLocation property under VideoGameSeries.  I need it, and so
does Aaron.

**Comment by tmarshbing** [comment]
+1 to add gameLocation to VideoGameSeries.

**Comment by danbri** [comment]
Hearing no complaints, let's close out the issue.
