### ISSUE TITLE
We should have a more helpful 404 page

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#3351]
@RichardWallis before we went to 100% static-served site, I think our 404 handling was friendlier. Currently it is very 1994-flavoured and raw. Can you wire up a more friendly page with at least site branding and search box? It would be good if we could customize it to mention that Schema.org terms are case sensitive, e.g. don't write "article" if you mean "Article" (even though people do). In theory we could do something in JS to offer possible links to the correct page in such cases but even a search form would be wonderful.

**Comment by lacinajir** [comment]
I second this, it's very frustrating for users like me.
