### ISSUE TITLE
Invalid enum value in field 'returnPolicyCategory' It shows error in google schema scanner

### ISSUE THREAD

**Issue by Sidddes** [schemaorg/schemaorg#3360]
`<script` type="application/ld+json">
{
  "@context": "https://schema.org/",
  "@type": "Product",
  "name": "Personalised Canvas Photo Prints",
  "image": "https://printposters.in/canvas-prints/assets/images/canvas_prints.webp",
  "description": "India's Largest Online Personalised Canvas Photo Prints Store with the Highest Quality Canvas Picture Frame and Art Printing along with free delivery near your doorstep.",
  "brand": {
    "@type": "Brand",
    "name": "Printposters.in"
  },
  "sku": "kqtldnuy",
  "offers": {
    "@type": "Offer",
    "url": "https://printposters.in/canvas-prints/",
    "itemCondition": "https://schema.org/NewCondition",
    "priceValidUntil": "2024-12-31",
    "availability": "https://schema.org/InStock",
    "priceSpecification": [
      {
        "@type": "UnitPriceSpecification",
        "price": 250,
        "priceCurrency": "INR",
        "validFrom": "2022-10-01",
        "validThrough": "2024-12-31",
        "priceCategory": "https://schema.org/ListPrice"
      },
      {
        "@type": "UnitPriceSpecification",
        "price": 150,
        "priceCurrency": "INR",
        "validFrom": "2022-10-01",
        "validThrough": "2024-12-31",
        "priceCategory": "https://schema.org/SalePrice"
      }
    ],
    "price": 60,
    "priceCurrency": "INR",
    "deliveryTime": {
      "@type": "ShippingDeliveryTime",
      "handlingTime": {
        "@type": "QuantitativeValue",
        "value": 2,
        "unitCode": "DAY"
      }
    },
    "shippingDetails": {
      "@type": "OfferShippingDetails",
      "deliveryTime": {
        "@type": "ShippingDeliveryTime",
        "businessDays": {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "https://schema.org/Monday",
            "https://schema.org/Tuesday",
            "https://schema.org/Wednesday",
            "https://schema.org/Thursday",
            "https://schema.org/Friday",
            "https://schema.org/Saturday"
          ]
        },
        "cutoffTime": "12:00:15Z",
        "handlingTime": {
          "@type": "QuantitativeValue",
          "minValue": 1,
          "maxValue": 2,
          "unitCode": "d"
        },
        "transitTime": {
          "@type": "QuantitativeValue",
          "minValue": 1,
          "maxValue": 10,
          "unitCode": "d"
        }
      },
      "shippingRate": {
        "@type": "MonetaryAmount",
        "value": 0,
        "currency": "INR"
      },
      "shippingDestination": {
        "@type": "DefinedRegion",
        "addressCountry": "IN"
      },
      "eligibleTransactionVolume": {
        "@type": "PriceSpecification",
        "minPrice": 300,
        "priceCurrency": "INR"
      },
      "appliesToDeliveryMethod": {
        "@type": "ShippingRateSettings",
        "shippingRate": {
          "@type": "MonetaryAmount",
          "value": 100,
          "currency": "INR"
        }
      }
    },
    "hasMerchantReturnPolicy": {
      "@type": "MerchantReturnPolicy",
      "description": "If the product is damaged, Printposters.in will replace this product.",
      "applicableCountry": "IN",
      "returnPolicyCategory": 
      {
        "@type": "http://schema.org/ProductReturnPolicy",
        "productReturnCategory": "Finite",
        "productReturnDays": "7",
        "refundType": "FullRefund",
        "inStoreReturnsOffered": "True",
        "productReturnExceptions": "If the product is damaged, Printposters.in will replace this product."
      }
    }
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.88",
    "bestRating": "5",
    "worstRating": "1",
    "reviewCount": "29954"
  },
  "review": {
    "@type": "Review",
    "name": "Suresh",
    "reviewBody": "A good and best quality canvas prints with an excellent price deal.",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": "5",
      "bestRating": "5",
      "worstRating": "1"
    },
    "datePublished": "2022-08-01",
    "author": {"@type": "Person", "name": "Suresh"}
  }
}
</script>

**Comment by RichardWallis** [comment]
Checkout the defention of https://schema.org/returnPolicyCategory : 

> Values expected to be one of these types
> [MerchantReturnEnumeration](https://schema.org/MerchantReturnEnumeration)
> 

ie. One of the _MerchantReturnEnumeration_ values:

- [MerchantReturnFiniteReturnWindow](https://schema.org/MerchantReturnFiniteReturnWindow)
- [MerchantReturnNotPermitted](https://schema.org/MerchantReturnNotPermitted)
- [MerchantReturnUnlimitedWindow](https://schema.org/MerchantReturnUnlimitedWindow)
- [MerchantReturnUnspecified](https://schema.org/MerchantReturnUnspecified)

You supplied a [_ProductReturnPolicy_](https://schema.org/ProductReturnPolicy) not only not an expected type but also a superseded term.
