### ISSUE TITLE
Why the property "actor" is allowed to be located at "PerformanceRole" ?

### ISSUE THREAD

**Issue by taguchiseq** [schemaorg/schemaorg#3366]
I have a question about https://schema.org/PerformanceRole. The property `actor` is not defined in `PerformanceRole`. However, the property `actor` is used in the following example, and the example is judged to be successful by the validator https://validator.schema.org/ . Why the property `actor` is allowed to be located at `PerformanceRole` ?

> https://schema.org/PerformanceRole
```json
{
  "@context": "https://schema.org",
  "@type": "Movie",
  "name": "Ghostbusters",
  "sameAs": "http://en.wikipedia.org/wiki/Ghostbusters",
  "actor": {
    "@type": "PerformanceRole",
    "actor": {
      "@type": "Person",
      "name": "Bill Murray"
    },
    "characterName": "Dr. Peter Venkman"
  }
}
```

>
<img width="964" alt="image" src="https://github.com/schemaorg/schemaorg/assets/45484071/e47ad93b-0cbb-40f1-a661-b29d22d4e6ae">

**Comment by RichardWallis** [comment]
What you are seeing are the effects of using a [Role](https://schema.org/Role) type, or one of its subtypes ([PerformanceRole](https://schema.org/PerformanceRole) in his case).

When a _Role_ type or subtype is used as the value of a property (in this case _actor_) that property becomes a valid property for the Role type in that circumstance.  Hence the example you highlight.

_Role_ provides a way of annotating the relationship between types.  For example a Person's membership of a team by startDate/endDate, or as in this case an actor by the characterName they played.

For a more detailed explanation check out thes two blog posts: [Introducing 'Role'](http://blog.schema.org/2014/06/introducing-role.html) and [The role of Role in Schema.org](https://dataliberate.com/2015/04/15/the-role-of-role-in-schema-org/)

**Comment by taguchiseq** [comment]
Thank you @RichardWallis ! Thanks to the blog posts, I understood the reason why a `Role` type reuse the property `actor`.

http://blog.schema.org/2014/06/introducing-role.html
><img width="500" alt="image" src="https://github.com/schemaorg/schemaorg/assets/45484071/760002fc-5041-4b16-8740-2f983a6b1fd6">

><img width="500" alt="image" src="https://github.com/schemaorg/schemaorg/assets/45484071/8c8dfc75-183e-44f7-a3e5-6dbbb724f3f0">

**Comment by WeaverStever** [comment]
Relating to actor, this discussion raises the question how do you associate an acting role with a Person?
(I.e., when your page is about a person rather than a film, or other, performance)

This seems to work for the schema testing tool and the Rich Results Test.

~~~~
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Bill Murray",
  "performerIn": {
    "@type": [
      "Movie",
      "Event"
    ],
    "name": "Ghostbusters",
    "sameAs": "http://en.wikipedia.org/wiki/Ghostbusters",
    "startDate": "1984-06-08",
    "Location": "New York City",
    "image": "http://example.com/image.jpg",
    "actor": {
      "@type": "PerformanceRole",
      "actor": {
        "@type": "Person",
        "name": "Bill Murray"
      },
      "characterName": "Dr. Peter Venkman"
    }
  }
}
~~~~

**Comment by WeaverStever** [comment]
@KalleOlaviNiemitalo 

Yes thanks, @id would provide disambiguation -- indicating both Bill Murray(s) are the same person. 

seems to work in both debuggers (warnings, but no errors on Google)

~~~~
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Bill Murray",
  "@id": "https://example.com/ghostbusters#billmurray",
  "performerIn": {
    "@type": [
      "Movie",
      "Event"
    ],
    "name": "Ghostbusters",
    "sameAs": "http://en.wikipedia.org/wiki/Ghostbusters",
    "startDate": "1984-06-08",
    "Location": "New York City",
    "image": "http://example.com/image.jpg",
    "actor": {
      "@type": "PerformanceRole",
      "actor": {
        "@type": "Person",
        "name": "Bill Murray",
        "@id": "https://example.com/ghostbusters#billmurray"
      },
      "characterName": "Dr. Peter Venkman"
    }
  }
}
~~~~
