### ISSUE TITLE
serviceType should have URL as a data type

### ISSUE THREAD

**Issue by schmudde** [schemaorg/schemaorg#3372]
From the documentation, `serviceType` values are expected to be one of these types:

- [GovernmentBenefitsType](https://schema.org/GovernmentBenefitsType)
- [Text](https://schema.org/Text)

But the example is a URL, which seems like a reasonable data type. Can we change the schema or shall I make a PR to update the example?

```
  "governmentBenefitsInfo": {
    "@type": "GovernmentService",
    "name": "Paycheck Protection Program",
    "url":  "https://www.sba.gov/funding-programs/loans/coronavirus-relief-options/paycheck-protection-program-ppp",
    "provider": {
      "@type": "GovernmentOrganization",
      "name": "US Small Business Administration"
     },
    "serviceType": "https://schema.org/BusinessSupport",
    "audience": {
      "@type": "Audience",
      "name": "Small businesses"
     }
```

**Comment by schmudde** [comment]
Thanks @KalleOlaviNiemitalo. 

So you're suggesting that I put a PR in and update the `serviceType` example? e.g.

```
  "governmentBenefitsInfo": {
    "@type": "GovernmentService",
    "name": "Paycheck Protection Program",
    "url":  "https://www.sba.gov/funding-programs/loans/coronavirus-relief-options/paycheck-protection-program-ppp",
    "provider": {
      "@type": "GovernmentOrganization",
      "name": "US Small Business Administration"
     },
    "serviceType": {"@id": "https://schema.org/BusinessSupport"},
    "audience": {
      "@type": "Audience",
      "name": "Small businesses"
     }
```

Though [this schema you pulled](https://github.com/schemaorg/schemaorg/blob/main/data/releases/22.0/schemaorg-current-https.jsonld) seems pretty awkward to me, fundamentally:

```
      "@id": "schema:BusinessSupport",
      "@type": "schema:GovernmentBenefitsType",
```

I arrived in this place because I'm trying to provide more information about this type of service. It seems that JSON-LD is probably the best way, either way:

```
 "object": {"@type": "Service",
            "provider": {"@type": "Organization",
                         "url": "https://myspace.com",
                         "name": "My Space"},
            "serviceType": {"@id": "https://example.com/accounts/logins"}}
```

**Comment by RichardWallis** [comment]
Sorry, a bit late to this thread.

One of the _[serviceType](https://schema.org/serviceType)_ expected values is [GovernmentBenefitsType](https://schema.org/GovernmentBenefitsType), which is  an _enumeration type_.  

As one of the members of that enumeration is [BusinessSupport](https://schema.org/BusinessSupport), the URL of that enumeration member 'https://schema.org/BusinessSupport' is a valid value for the serviceType property.

Hence the example is valid.

**Comment by schmudde** [comment]
Thanks for the clear explanation, @RichardWallis. Example is valid and there seems to be little interest in extending the `serviceType` property to support anything more than text and [GovernmentBenefitsType](https://schema.org/GovernmentBenefitsType). Closing.
