### ISSUE TITLE
extend the domain and range of `skills`

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#3381]
Currently `skills` applies only to `JobPosting, Occupation`. IMHO it should also apply to `Person, Organziation`:
- To fill a posting, the Person must have the requisite skills: so it should be possible to record this against the person
- Similar for an org: it may possess collective skills being the sum of its employee's skills, or its own "emergent" skills

**Comment by MatthiasWiesmann** [comment]
This sounds straightforward, any objection?

**Comment by philbarker** [comment]
Should be OK so long as the definition gets tweaked.

**Comment by alex-jansen** [comment]
Fixed in #3651
