### ISSUE TITLE
Correct usage of subjectOf

### ISSUE THREAD

**Issue by WilkoMarketing** [schemaorg/schemaorg#3382]
Hello,

I would appreciate some assistance with using the "subjectOf" property. I am trying to use this property to reference an external website, but I am unsure whether I should use "url" or "name." I have noticed that some websites use either of them, but I believe "url" is more appropriate:

"subjectOf":
{
"@type": "Thing",
"url": "https://www.example.com/"
}

or:

"subjectOf":
{
"@type": "Thing",
"name": "https://www.example.com/"
},

I would be grateful if you could help me understand which one is the correct way to use it.

Thank you!

**Comment by RichardWallis** [comment]
```
"subjectOf":
{
"@type": "Thing",
"url": "https://www.example.com/"
}
```

Is correct.

A fuller example could be:
```
<script type="application/ld+json">
{
  "@context": "https://schema.org/",
  "@type": "Person",
  "name": "Harry Smith",
  "subjectOf": {
     "@type": "Website",
     "url": "http://example.com",
     "name": "Harry's Web Site"
  }
}
```

**Comment by WilkoMarketing** [comment]
Thank you very much @RichardWallis for your reply!
In case im using "subjectOf" for refering a specific website article/page (instead of a website´s homepage as the example of the previous message), such as http://example.com/article-about-something, would you use "Article" or "WebPage" instead? For example:

"subjectOf":
{
"@type": "Article",
"url": "http://example.com/article-about-something"
}

Or

"subjectOf":
{
"@type": "WebPage",
"url": "http://example.com/article-about-something"
}

Thank you!

**Comment by RichardWallis** [comment]
> would you use "Article" or "WebPage"

That depends upon how you would describe (in schema.org terms) the thing you are referencing - is it just a _Webpage_ or is it an _Article_, that is possibly the [mainEntityOfPage](https://schema.org/mainEntityOfPage) of a Webpage

**Comment by WilkoMarketing** [comment]
Thank you!

**Comment by RichardWallis** [comment]
In an ideal world, say in a local system when you have direct access to all the data you need, you are correct.  A process could follow all references and infer things from what is found. 

However, search engines scaled across the whole web may, or may not, crawl the url at some stage, but when efficiently parsing the code they are presented with, they need a hint.

**Comment by WilkoMarketing** [comment]
Thank you!
