### ISSUE TITLE
Range of programmingLanguage: Language instead of Thing?

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#341]
The [`programmingLanguage` property](http://schema.org/programmingLanguage) currently has a range of `Thing`.

Its definition ("The computer programming language.") suggests that it could/should be [`Language`](http://schema.org/Language) instead:

> Natural languages such as Spanish, Tamil, Hindi, English, etc. **and programming languages** such as Scheme and Lisp.

**Comment by danbri** [comment]
Thanks. Yes this could do with more care (as could 'Language' itself). We don't want to include lists of actual languages (human, computer or hybrid) as part of the schema.org core, but we should document ways of using external enumerations e.g. Wikipedia/Wikidata and it might make sense to break out subtypes of Language.

**Comment by danbri** [comment]
While there are other issues here (Code has a problematic name, see also unrelated 'code' property), writing Language rather than Thing seems a harmless improvement. I'll do that now and close out this specific issue. Thanks again!

**Comment by danbri** [comment]
Done - http://sdo-gozer.appspot.com/programmingLanguage
