### ISSUE TITLE
I've got issues with https://schema.org/ReturnFeesEnumeration

### ISSUE THREAD

**Issue by otto-poulpe** [schemaorg/schemaorg#3412]
I've got issues with https://schema.org/ReturnFeesEnumeration, only https://schema.org/FreeReturn can be validate on https://search.google.com/test/rich-results, but it does not fit my need... I would rather use https://schema.org/ReturnShippingFees.. Here is my Json mark up :
"offers": {
"@type": "Offer",
"url": "https://www.vapoter.fr/t17553-frm-alfaliquid-10ml",
"priceCurrency": "EUR",
"price": "5.9",
"priceValidUntil": "2025-03-25",
"availability": "https://schema.org/InStock",
"itemCondition": "https://schema.org/NewCondition",
"hasMerchantReturnPolicy": {
"@type": "MerchantReturnPolicy",
"applicableCountry": "FR",
"returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
"merchantReturnDays": 14,
"returnMethod": "https://schema.org/ReturnByMail",
"returnFees": "https://schema.org/ReturnShippingFees"
}

Help me please !!

**Comment by otto-poulpe** [comment]
No one can help me here ??!!! @alex-jansen ?

**Comment by MatthiasWiesmann** [comment]
Could you please explain your question in a more structured fashion, i.e. two parts, a) what you did b) what you expect. 
Currently, the main issue I see in your snippet is there is an offer, but no product.

**Comment by Tiggerito** [comment]
The Google docs for Product indicate to use returnShippingFeesAmount if there is a fee.

https://developers.google.com/search/docs/appearance/structured-data/product#merchant-listings_product

![image](https://github.com/schemaorg/schemaorg/assets/4947018/f74210be-c041-4328-8272-3af5fc3b85b1)

I believe the Rich Result Test is incorrectly reporting a warning that returnFees is missing in this case:

![image](https://github.com/schemaorg/schemaorg/assets/4947018/ff9cc579-f6e8-45f9-964f-04abb16dacea)

**Comment by otto-poulpe** [comment]
<script type="application/ld+json">
{
  "@context": "https://schema.org/", 
  "@type": "Product", 
  "name": "FRM Alfaliquid 10ml",
   "image": ["https://www.vapoter.fr/images/products/p_17553-29142-frm-alfaliquid-10ml.jpg","https://www.vapoter.fr/images/products/p_17553-27652-frm-alfaliquid-10ml-2.jpg"],
  "description": "Découvrez le nouveau e-liquide Classic de Alfaliquid ! D'une contenance de 10ml, le FRM possède un taux de PG/VG de 76/24 et est fabriqué en France.",
  "brand": {
    "@type": "Brand",
    "name": "ALFALIQUID"
  },
  "gtin13": ["3662572106855","978020137962"],
  "offers": {
    "@type": "Offer",
    "url": "https://www.vapoter.fr/t17553-frm-alfaliquid-10ml",
    "priceCurrency": "EUR",
    "price": "5.9",
    "priceValidUntil": "2025-03-25",
    "availability": "https://schema.org/InStock",
    "itemCondition": "https://schema.org/NewCondition",
     "hasMerchantReturnPolicy": {
              "@type": "MerchantReturnPolicy",
              "applicableCountry": "FR",
              "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
              "merchantReturnDays": 14,
              "returnMethod": "https://schema.org/ReturnByMail",
              "returnFees": "https://schema.org/OriginalShippingFees"
          },
   "returnShippingFeesAmount": {
            "@type": "MonetaryAmount",
            "value": 7.40,
            "currency": "EUR"
          },
    "shippingDetails": {
          "@type": "OfferShippingDetails",
          "shippingRate": {
            "@type": "MonetaryAmount",
            "value": 7.40,
            "currency": "EUR"
          },
          "shippingDestination": {
            "@type": "DefinedRegion",
            "addressCountry": "FR"
          },
          "deliveryTime": {
            "@type": "ShippingDeliveryTime",
            "handlingTime": {
              "@type": "QuantitativeValue",
              "minValue": 0,
              "maxValue": 1,
              "unitCode": "DAY"
          },
            "transitTime": {
              "@type": "QuantitativeValue",
              "minValue": 1,
              "maxValue": 3,
              "unitCode": "DAY"
          }

        }
    }
 },

  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "5",
    "bestRating": "5",
    "worstRating": "0",
    "ratingCount": "2",
    "reviewCount": "2"
  },
  "review": [{
    "@type": "Review",
    "name": "Avis de Nathalieb",
    "reviewBody": "Produit conforme à mes attentes",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": "5",
      "bestRating": "5",
      "worstRating": "0"
    },
    "datePublished": "2023-11-09",
    "author": {"@type": "Person", "name": "Nathalieb"},
    "publisher": {"@type": "Organization", "name": "TrustPilot"}
  },{
    "@type": "Review",
    "name": "Avis de Pascale H.",
    "reviewBody": "commande impeccable comme toujours",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": "5",
      "bestRating": "5",
      "worstRating": "0"
    },
    "datePublished": "2023-10-25",
    "author": {"@type": "Person", "name": "Pascale H."},
    "publisher": {"@type": "Organization", "name": "TrustPilot"}
  }]
}
</script>

**Comment by otto-poulpe** [comment]
I just can't solve that problem.. each time i have errors that shouldn't appear..

**Comment by jvandriel** [comment]
@otto-poulpe the cause of your issue can be found in Google Feature Guide Documentation.

<img width="877" alt="Screen Shot 2024-01-15 at 11 17 43 AM" src="https://github.com/schemaorg/schemaorg/assets/7320889/703910b1-9c32-48d1-9dbb-6cdad16b9bcd">

**Comment by jvandriel** [comment]
You should consider using https://validator.schema.org/ to validate your markup as well so that you can make sure it aligns with the vocabulary's constraints. That way you can be certain any other error/warning you than get in the RRT is a Google specific one - which we generally don't handle here and should be discussed over at Google's developers forum.

**Comment by otto-poulpe** [comment]
It's all good now !! Thanks for your help community !!

**Comment by Tiggerito** [comment]
@otto-poulpe How did you fix it?

**Comment by otto-poulpe** [comment]
<script type="application/ld+json">
{
  "@context": "https://schema.org/", 
  "@type": "Product", 
  "name": "FRM Alfaliquid 10ml",
   "image": ["https://www.vapoter.fr/images/products/p_17553-29142-frm-alfaliquid-10ml.jpg","https://www.vapoter.fr/images/products/p_17553-27652-frm-alfaliquid-10ml-2.jpg"],
  "description": "Découvrez le nouveau e-liquide Classic de Alfaliquid ! D'une contenance de 10ml, le FRM possède un taux de PG/VG de 76/24 et est fabriqué en France.",
  "brand": {
    "@type": "Brand",
    "name": "ALFALIQUID"
  },
  "gtin13": ["3662572106855","978020137962"],
  "offers": {
    "@type": "Offer",
    "url": "https://www.vapoter.fr/t17553-frm-alfaliquid-10ml",
    "priceCurrency": "EUR",
    "price": "5.9",
    "priceValidUntil": "2025-03-25",
    "availability": "https://schema.org/InStock",
    "itemCondition": "https://schema.org/NewCondition",
     "hasMerchantReturnPolicy": {
              "@type": "MerchantReturnPolicy",
              "applicableCountry": "FR",
              "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
              "merchantReturnDays": 14,
              "returnMethod": "https://schema.org/ReturnByMail",
              "returnFees": "https://schema.org/ReturnShippingFees",
              "returnShippingFeesAmount": {
                      "@type": "MonetaryAmount",
                      "value": 7.40,
                      "currency": "EUR"
          }
          },

    "shippingDetails": {
          "@type": "OfferShippingDetails",
          "shippingRate": {
            "@type": "MonetaryAmount",
            "value": 7.40,
            "currency": "EUR"
          },
          "shippingDestination": {
            "@type": "DefinedRegion",
            "addressCountry": "FR"
          },
          "deliveryTime": {
            "@type": "ShippingDeliveryTime",
            "handlingTime": {
              "@type": "QuantitativeValue",
              "minValue": 0,
              "maxValue": 1,
              "unitCode": "DAY"
          },
            "transitTime": {
              "@type": "QuantitativeValue",
              "minValue": 1,
              "maxValue": 3,
              "unitCode": "DAY"
          }

        }
    }
 },

  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "5",
    "bestRating": "5",
    "worstRating": "0",
    "ratingCount": "2",
    "reviewCount": "2"
  },
  "review": [{
    "@type": "Review",
    "name": "Avis de Nathalieb",
    "reviewBody": "Produit conforme à mes attentes",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": "5",
      "bestRating": "5",
      "worstRating": "0"
    },
    "datePublished": "2023-11-09",
    "author": {"@type": "Person", "name": "Nathalieb"},
    "publisher": {"@type": "Organization", "name": "TrustPilot"}
  },{
    "@type": "Review",
    "name": "Avis de Pascale H.",
    "reviewBody": "commande impeccable comme toujours",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": "5",
      "bestRating": "5",
      "worstRating": "0"
    },
    "datePublished": "2023-10-25",
    "author": {"@type": "Person", "name": "Pascale H."},
    "publisher": {"@type": "Organization", "name": "TrustPilot"}
  }]
}
</script>


I had to write returnFees even if it's not freereturn, and i insert returnShippingFeesAmount inside "hasMerchantReturnPolicy" No more errors or warnings !!

**Comment by Tiggerito** [comment]
So returnShippingFees is secretly a valid value. Maybe they need to update the documentation.

**Comment by jvandriel** [comment]
As I can't find any Google documentation making any mention about any of the Rich Result Test's nuanced warnings I decided to test @otto-poulpe's  markup for each of the enumeration values for `returnFees `, just so that there something documented somewhere.

**No errors or warnings** 
1. `"returnFees": "https://schema.org/ReturnShippingFees"` + `"returnShippingFeesAmount": { "@type": "MonetaryAmount", "value": 7.40` - Because the enum value indicates there are fees involved, which are subsequently provided.
2. `"returnFees": "https://schema.org/FreeReturn"` + `"returnShippingFeesAmount": { "@type": "MonetaryAmount", "value": 0` - Because there are no fees involved, also indicated by the 0 fees amount value

**Warning: Number out of range for field "value" (optional)** 
1. `"returnFees": "https://schema.org/FreeReturn"` + `"returnShippingFeesAmount": { "@type": "MonetaryAmount", "value": 7.40` - Because returning something can't be free and cost 7.40 at the same time. 0 would be the only correct value here. 

**Warning: Invalid enum value in field "returnFees" (optional)** - Indicating these enumeration valuea are not supported 
1. `"returnFees": "https://schema.org/OriginalShippingFees"` 
2. `"returnFees": "https://schema.org/RestockingFees"`

**Warning: Invalid value in field "returnShippingFeesAmount" (optional)**
1. `"returnFees": "https://schema.org/ReturnFeesCustomerResponsibility"` + `"returnShippingFeesAmount": { "@type": "MonetaryAmount", "value": 7.40` - Because the enumeration value indicates the costs are the responsibility of the individual customer and not that of the publisher of the markup. `"MonetaryAmount", "value": ""` would be the only correct annotation here. But than, why would you want to publish `returnShippingFeesAmount` markup if there is no data to publish.

**Comment by alex-jansen** [comment]
thanks for the detailed feedback, we will look into our validation and the documentation and make sure it matches.

**Comment by jvandriel** [comment]
Let it be clear that I very much appreciate the RRT's nuanced validation output. I hadn't run into them myself yet, so I'm glad @otto-poulpe provided the example.

I just thought it was a shame that the info links that come with those warnings refer to documentation that don't make any mention of that. Which I get from a guideline perspective as describing all that might be a bit much but at the same time, if you go through the effort of building such nuanced validation you might as well make folks aware of it.
