### ISSUE TITLE
Activity area: Certifications and credentials

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#3418]
This issue represents the activity area around certifications and credentials e.g. see #3230. It is an area where we anticipate ongoing work, as well as a need to liaise between perspectives around e-commerce product markup and standards (e.g. GS1), education/jobs/skills, and cross-domain standards like W3C's Verifiable Credentials.

I have asked @alex-jansen and @MatthiasWiesmann to take a lead preparing changes and additions here. Generally this will be by queueing PRs in the usual manner but for simple fixes and improvements I would encourage direct publication of a schema.org release. In the past we have tiptoed on this and created confusion through an over-abundance of staging mechanisms (webschemas.org, Pending etc.). For 2024 let's try just improving things without excess bureaucracy.

**Comment by MatthiasWiesmann** [comment]
The certification object was added here: https://schema.org/Certification

**Comment by alex-jansen** [comment]
Since we added the [Certification](https://schema.org/Certification) type in #3441 after extensive discussions in #3230 we can close this issue.
