### ISSUE TITLE
Add a new property to support color swatches

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3423]
**Context** - This is a proposal from Google based on our experience consuming schema.org [Product](https://schema.org/Offer) markup and working with similar data from online merchants. If it were accepted, it would make it easier for us and others to understand the colors of products sold online.

**Proposal** - Schema.org supports the specification of product colors through property [color](https://schema.org/color) of type [Text](https://schema.org/Text). A disadvantage of only allowing a free-form textual description of a color is that it provides a lot of room for interpretation. For example "Charcoal" and "Ash" are both shades of the color Gray, but it is hard for a user to understand the difference just based on the textual description. Many popular apparel websites therefore show a color swatch image together with the color name to allow the user to visualize the color of a product variant. 

Given the common use of color swatches in the industry we propose to add a new _colorSwatch_ property as sub-property of [image](https://schema.org/image) with values of type [URL](https://schema.org/URL) or [ImageObject](https://schema.org/ImageObject).

**Comment by Tiggerito** [comment]
In the platform I work on a color swatch is just the HTML color code. like ff0000. Would there be any way to support that?

**Comment by alex-jansen** [comment]
We could look into that as part of the color attribute. One of the things to consider here is that we often see apparel colors described as combinations, for example "black white colorblock", which cannot be described with a single color code.

**Comment by Tiggerito** [comment]
Would an array of the colors involved make sense?

How about having color support better parsing of the text content to recognise hex codes, URLs and finally a plain text description. Or even have extra types for the color property to formally indicate an image or hex code or other another color system for it?

**Comment by alex-jansen** [comment]
Good ideas, although I also think representing colors is probably a different (and complex!) topic for which we should maybe revive https://github.com/schemaorg/schemaorg/issues/938? For example, we could follow standard color code lists (see for example [gs1:ColourCodeListCode](https://www.gs1.org/voc/ColourCodeListCode), which seems to be a common industry practice.
