### ISSUE TITLE
Description of sampleType

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#343]
The description of the [`sampleType` property](http://schema.org/sampleType) currently is:

> Full (compile ready) solution, code snippet, inline code, scripts, template.

As far as I understand it, it lists possible example values instead of describing the purpose of the property.

I think it should start with a description instead, followed by these example values.

(On a side note, I wonder why it’s called "`sampleType`" instead of something like "`codeType`", as `Code` is not only for *samples* of code.)

**Comment by danbri** [comment]
Fixed, thanks!
