### ISSUE TITLE
Confusion around "author" - validator disagrees with documentation

### ISSUE THREAD

**Issue by edent** [schemaorg/schemaorg#3434]
I have comments on my blog. Some comments come from people, and the author is a Person. Some comments are pingbacks / trackbacks where the author is a Website.

The Validator shows this without errors:

![Screenshot of the validator](https://github.com/schemaorg/schemaorg/assets/837136/92b12fc7-b880-4966-9d13-901b1c87caa7)

The Google Search Console disagrees and says it is invalid:

![Screenshot of an error message](https://github.com/schemaorg/schemaorg/assets/837136/8b8f4211-9202-4aa9-bc31-b8aa4a189619)

The documentation - https://schema.org/author - says the only acceptable values should be an Organisation or a Person.

So, should I go with the Validator or the Documentation?

**Comment by MatthiasWiesmann** [comment]
Would you mind attaching the original schema.org data for validation / checking?

**Comment by edent** [comment]
The URl is https://shkspr.mobi/blog/2010/10/hack-your-kindle/#comment-1418

The specific comment is:
```html
<ol class="comment-list">
	<li id="comment-1418" class="pingback even thread-even depth-1" itemid="#comment-1418" itemscope itemtype="https://schema.org/Comment">
		<article id="div-comment-1418" class="comment-body">
			<time class="comment-meta commentmetadata" datetime="2010-10-04T09:17:17+01:00" itemprop="dateCreated"><a href='#comment-1418' itemprop='url'>2010-10-04 09:17</a></time>
			<div class="comment-author" itemprop="https://schema.org/author" itemscope itemtype="https://schema.org/Organization">
				<h3 class="says"><span class="fn" itemprop="name"><img class="pingback-favicon no-border-radius" alt="" loading="lazy" src="https://icons.duckduckgo.com/ip9/web.archive.org.ico"> <a class='url' href='https://web.archive.org/web/20160619022623/http://gadgeteer.org.uk/2010/10/04/got-a-kindle-3-useful-links/' itemprop='url' rel='external nofollow ugc'>Got a Kindle 3? Useful links | UK Gadgeteer Website</a></span>:</h3>
			</div>
			<div class="comment-text" itemprop="text">
				<p>[...] new Kindle 3? If so, I&#8217;ve found a couple of links of useful information for you.&nbsp; Firstly, Terence Eden has posted some really useful tips including how to setup the ability to view comics (such as the [...]</p>
			</div>
		</article>
	</li>
</ol>
```

**Comment by MatthiasWiesmann** [comment]
Both the schema.org validator and the Google one seem happy. 

https://search.google.com/test/rich-results/result?id=Z3fUiAbK7blRsoxa7CRDmQ

**Comment by edent** [comment]
Looks like this was fixed at some point in the last year. Thanks for notifying me.
