### ISSUE TITLE
extending rangeIncludes of dates predicates

### ISSUE THREAD

**Issue by twamarc** [schemaorg/schemaorg#345]
Hello again,
I'm suggesting to extend rangeIncludes of the following date predicates by adding http://schema.org/DateTime classe.
Predicates are:
-http://schema.org/startDate
-http://schema.org/endDate
-http://schema.org/orderDate
-http://schema.org/dateCreated
-http://schema.org/releaseDate
-http://schema.org/dateModified

By adding http://schema.org/DateTime classe in range we will be able to use them also if time is provided. Otherwise it can be by default T00:00:00Z (I think there's no harm)
Any feedback here is welcome.

Marc

**Comment by danbri** [comment]
Thanks. I've tagged this with a cluster of related date/time/event issues.
