### ISSUE TITLE
The property title is not recognized by Schema.org vocabulary.

### ISSUE THREAD

**Issue by Juan-Videla** [schemaorg/schemaorg#3457]
Estimados, tengan todos muy buenas tardes, les escribo pues tengo una duda y no se a quien recurrir, resulta que desde parte de mi equipo me dicen que tenemos cerca de 10000 errores en los datos estructurados de unos productos, les dejo un print

![image](https://github.com/schemaorg/schemaorg/assets/149697924/ad5a97a2-d312-435d-9b5e-0a3c30cd4cae)

Pero no se como poder solucionarlo, al revisar schema veo la advertencia de este producto (
https://www.beststore.cl/hubs-switches/60815-cisco-business-350-series-350-24t-4g-conmutador-l3-gestionado-24-x-10-100-1000-4-x-sfp-montaje-en-rack-0889728294027.html)

![image](https://github.com/schemaorg/schemaorg/assets/149697924/fde9a71f-cd90-4a90-93e8-fe0edbab5eed)

Me gustaría saber como poder solucionar esto, si alguno de ustedes sabe me sería de mucha ayuda

**Comment by philbarker** [comment]
@Juan-Videla creo que necesita usar `schema:name`; no hay un properdad `title` por Product.

(apologies for my poor Spanish)

**Comment by Juan-Videla** [comment]
Muchas gracias, haremos las pruebas

**Comment by MatthiasWiesmann** [comment]
Closing as this seems fixed.
