### ISSUE TITLE
Keywords property of CreativeWork

### ISSUE THREAD

**Issue by lazaruscorporation** [schemaorg/schemaorg#347]
Hi

The current instruction on http://schema.org/keywords is "Keywords or tags used to describe this content. Multiple entries in a keywords list are typically delimited by commas."

I'd like to suggest that we also allow the keywords property to be used multiple times within a Type when describing something (and update the informative text on http://schema.org/keywords to describe this), as this will allow easier parsing by a client. For example:

```
<div vocab="http://schema.org/" typeof="Movie">
  ...
  <ul>
    <li property="keywords">Ghostbusters</li>
    <li property="keywords">Movies</li>
    <li property="keywords">etc</li>
  </ul>
```

This would also allow for better LOD implementation (as proposed in #346 ) as follows:

```
<div vocab="http://schema.org/" typeof="Movie">
  ...
  <ul>
    <li property="keywords" resource="http://example.org/lod/uri/ghostbusters">Ghostbusters</li>
    <li property="keywords" resource="http://example.org/lod/uri/movie">Movies</li>
    <li property="keywords" resource="http://example.org/lod/uri/etc">etc</li>
  </ul>
```

Paul

**Comment by danbri** [comment]
While I appreciate the general motivation, in this case wouldn't 'about' work? http://schema.org/about
i.e. "The subject matter of the content."? Do the URLs you give correspond to a specific set of keywords, or to the underlying concept?

**Comment by lazaruscorporation** [comment]
Hi @danbri 

I'm not sure and it's probably one of those grey areas open to interpretation (at least for me!). 'about' expects an instance of schema.org/Thing, not a URL, so it's not ideal for use for linked data. Yes, you could mark-up an instance of 'Thing' and then use that instance's 'sameAs' property to implement LOD, but that starts to produce messy & extraneous markup (example below):

```
<div vocab="http://schema.org/" typeof="Movie">
  ...
  <ul>
    <li property="about" typeof="Thing"><span property="sameAs" resource="http://example.org/lod/uri/ghostbusters">Ghostbusters</span></li>
    <li property="about" typeof="Thing"><span property="sameAs" resource="http://example.org/lod/uri/movie">Movies</span></li>
    <li property="about" typeof="Thing"><span property="sameAs" resource="http://example.org/lod/uri/etc">Etc</span></li>
  </ul>
</div>
```

I guess the question is: what's the difference between "about" and "keywords" - while described in different words ("the subject matter of the content" vs "Keywords or tags used to describe this content") they would appear to be duplicates/synonyms under that interpretation.

I've always presumed that 'about' was intended to be a *single* reference to another schema.org 'object' on the same web page (since it has to be an instance of schema.org/Thing) that is the *main subject* of the item, and that 'keywords' were a set of multiple subject classifications (like tags as used on blogs, and so by extension could be used for controlled vocabularies such as Getty AAT, Library of Congress Subject Headings, etc).

**Comment by Dataliberate** [comment]
Hi Paul,

As everything is effectively a Thing, I think you are being to literal
about the definition of 'about'.

In the Works (e.g. http://worldcat.org/entity/work/data/5925259), and
resource data (e.g.. http://www.worldcat.org/oclc/64750133 - checkout the
LD section at the end of the page), data published from WorldCat we (OCLC)
use the identifiers for things defined by several agencies [FAST, VIAF,
LCSH, etc.] to define about-ness.

There is a semantic discussion to have as to if the URIs are for the
things, that the CreativeWork is about, or for descriptions that have those
things as their focus.  The answer seems to vary dependant on the source of
the description/identifier as well as the type of thing being described -
is it a thing such as a person or is it a pure concept such as happiness.

Whatever, in the current pragmatic world that Schema operates within, it
seems to work well whatever the answer eventually might be.   Having
published 300+ million resource and 200 million Work descriptions this
approach appears to work and be well received by consumers.

As to keywords, I believe they are just 'words', and/or lists of words,
that would be associated  with an item to assist searching - as would be
found in a keyword index on a traditional search interface.

~Richard.

**Comment by lazaruscorporation** [comment]
Hi Richard

Looking at the markup on the worldcat site it looks like this would be OK:

```
<div vocab="http://schema.org/" typeof="VisualArtwork">
  <h1 property="name">Mona Lisa</h1>
  <ul>
    <li property="about" typeof="Thing" span resource="http://vocab.getty.edu/aat/300015637">Portraits</li>
    <li property="about" typeof="Thing" span resource="http://vocab.getty.edu/aat/300021143">Late Renaissance</li>
    <li property="about" typeof="Thing" resource="http://vocab.getty.edu/aat/300111198">Italian</li>
  </ul>
```

Is that correct? If so then I'd be happy to use "about" instead of "keywords", and will close this issue since it was due to my misinterpretation of the use of keywords/about.

Paul

**Comment by Dataliberate** [comment]
That looks good to me 

~Richard

**Comment by lazaruscorporation** [comment]
Brilliant - I'll close this issue as a non-issue, then!
