### ISSUE TITLE
This issue is being tagged as Stale due to inactivity.

### ISSUE THREAD

**Issue by barnesric56** [schemaorg/schemaorg#3471]
This issue is being tagged as Stale due to inactivity.

_Originally posted by @github-actions in https://github.com/schemaorg/schemaorg/issues/1154#issuecomment-670804462_

**Comment by VladimirAlexiev** [comment]
Hey, you are not a spammer, are you?
I looked at this and your comments in 1154 and they don't make much sense.
Schema.org has nothing to do with LLM.

**Comment by barnesric56** [comment]
I applologise, i am new to the area and picked up the information from another document in github. I will continue to read more before asking questions in the future. Appologies again

**Comment by VladimirAlexiev** [comment]
Well, this is not a question. 
A github bot "auto-resolves" issues, which is a practice I hate and is not appropriate for this project.
But maintainers (@danbri) are swamped with requests so that artificially decreases work-load...

**Comment by MatthiasWiesmann** [comment]
Closing this.
