### ISSUE TITLE
Proposal for enhance dc:source citations, mapping sources to LOV

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#348]
**Proposal**

Proposal for enhance [schema.org](http://schema.org) source citations, mapping sources to [LOV - Linked Open Vocabularies](http://lov.okfn.org).

-----

**Explaining in detail**

As stated in the [datamodel page](http://schema.org/docs/datamodel.html), the canonical machine representation of schema.org is in RDFa:
    http://schema.org/docs/schema_org_rdfa.html
so, this is the source-code of the schema.org standard. 

When checking `schema_org_rdfa` we can see some classes and properties that cite their sources with `dc:source`.
In the site the templating system transforms the `dc:source` in an "Acknowledgements" section. 

Example: the source of http://schema.org/Product was *GoodRelations*.

```xml
    <div typeof="rdfs:Class" resource="http://schema.org/Product">
      <span class="h" property="rdfs:label">Product</span>
      <span property="rdfs:comment">Any offered product or service. 
          For example: a pair of shoes; a concert ticket; the rental of a car; a haircut; 
          or an episode of a TV show streamed online.</span>
       <span>Subclass of: <a property="rdfs:subClassOf" href="http://schema.org/Thing">Thing</a></span>
       <span>Source:  
        <a property="dc:source"
        href="http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsProperties"
         >GoodRelationsProperties</a>
      </span>
</div>
```
so the proposal is to change the `href` value from W3C/Wiki to a more robust, reliable and expressive one, that I think is LOV. In the example the proposal is to replace "http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#source_GoodRelationsProperties" to "http://lov.okfn.org/dataset/lov/vocabs/gr".

Any other reference-vocabulary can be checked in http://lov.okfn.org/dataset/lov/vocabs

**Comment by danbri** [comment]
Thanks, yes I've begun work on this (see also https://github.com/schemaorg/schemaorg/issues/84 ). The 'dc:source' hack was more about generating the acknowledgements UI in the site. If you look you'll also see more vocabulary oriented mappings e.g. view-source:http://schema.org/Event

Bear with us on this, we're also figuring out how it relates to our extensions work and to finding a place in the site UI for these details (alongside RDFa). But yes, we definitely share the goal of having clearer vocabulary mappings visible to humans and machines.

**Comment by ppKrauss** [comment]
Sorry, I not saw  #84  before... So, perfect (!), we agree. Well, there are agreement about the `href` value?

I think [LOV](http://lov.okfn.org/dataset/lov/vocabs)  is a reliable and well-maintained "index of vocabularies". Is better than "self citation"... We can generate a dump of LOV cited entries in the `github.com/schemaorg/schemaorg` for safe, and to maintain the [mappings page](http://schema.rdfs.org/mappings.html).

**Comment by ppKrauss** [comment]
See  this *first step* at [my proposals/testing/issue84etAl](https://github.com/ppKrauss/schemaorg/tree/sdo-gozer/proposals/testing/issue84etAl) and the  [diffs with LOV links implementation here](https://github.com/ppKrauss/schemaorg/commit/1bc594f108e2ebeaa5bec80139db13a5748a472f). 

PS: all at [my pull request](https://github.com/schemaorg/schemaorg/pull/354) to add `/proposal` folder.

**Comment by danbri** [comment]
Thanks for the discussion, I'm closing #348 now as this general issue is addressed in #84. We have 170+ open issues so there's value in focussing the discussion under fewer headings.

**Comment by ppKrauss** [comment]
Yes, here 348 is a sub-issue of #84. Thanks to merge/organize (!). 

PS: I not understand the answer (there or here): let's LOV? or not??

**Comment by danbri** [comment]
Directionality is important. It is useful for the definition of e.g. http://schema.org/Person to make the claim "this is equivalent to foaf:Person". But also useful to collect such mappings from the wider world (including LOV and Wikidata, which currently are not well integrated).

Here's a quick view of the equivalencies we have listed in-house so far:

        rdfa schema.rdfa | grep equivalent
        <http://schema.org/Dataset> <http://www.w3.org/2002/07/owl#equivalentClass> <http://www.w3.org/ns/dcat#Dataset> .
        <http://schema.org/Dataset> <http://www.w3.org/2002/07/owl#equivalentClass> <http://purl.org/dc/dcmitype/Dataset> .
        <http://schema.org/pagination> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/ontology/bibo/pages> .
        <http://schema.org/author> <http://www.w3.org/2000/01/rdf-schema#comment> "The author of this content. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably." .
        <http://schema.org/gtin13> <http://www.w3.org/2000/01/rdf-schema#comment> "The <a href=\"http://apps.gs1.org/GDD/glossary/Pages/GTIN-13.aspx\">GTIN-13</a> code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceeding zero. See <a href=\"http://www.gs1.org/barcodes/technical/idkeys/gtin\">GS1 GTIN Summary</a> for more details." .
        <http://schema.org/Periodical> <http://www.w3.org/2002/07/owl#equivalentClass> <http://purl.org/ontology/bibo/Periodical> .
        <http://schema.org/PublicationIssue> <http://www.w3.org/2002/07/owl#equivalentClass> <http://purl.org/ontology/bibo/Issue> .
        <http://schema.org/DataCatalog> <http://www.w3.org/2002/07/owl#equivalentClass> <http://www.w3.org/ns/dcat#DataCatalog> .
        <http://schema.org/Class> <http://www.w3.org/2000/01/rdf-schema#comment> "A class, also often called a 'Type'; equivalent to rdfs:Class." .
        <http://schema.org/Event> <http://www.w3.org/2002/07/owl#equivalentClass> <http://purl.org/dc/dcmitype/Event> .
        <http://schema.org/DataDownload> <http://www.w3.org/2002/07/owl#equivalentClass> <http://www.w3.org/ns/dcat#Distribution> .
        <http://schema.org/pageStart> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/ontology/bibo/pageStart> .
        <http://schema.org/issueNumber> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/ontology/bibo/issue> .
        <http://schema.org/description> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/dc/terms/description> .
        <http://schema.org/issn> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/ontology/bibo/issn> .
        <http://schema.org/Property> <http://www.w3.org/2000/01/rdf-schema#comment> "A property, used to indicate attributes and relationships of some Thing; equivalent to rdf:Property." .
        <http://schema.org/ImageObject> <http://www.w3.org/2002/07/owl#equivalentClass> <http://purl.org/dc/dcmitype/Image> .
        <http://schema.org/isbn> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/ontology/bibo/isbn> .
        <http://schema.org/Person> <http://www.w3.org/2002/07/owl#equivalentClass> <http://xmlns.com/foaf/0.1/Person> .
        <http://schema.org/Dataset> <http://www.w3.org/2002/07/owl#equivalentClass> <http://rdfs.org/ns/void#Dataset> .
        <http://schema.org/pageEnd> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/ontology/bibo/pageEnd> .
        <http://schema.org/volumeNumber> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/ontology/bibo/volume> .

My rough picture was to pull in wikidata's mappings as another *.rdfa file (the codebase reads data/*rdfa when the site starts up, btw). We could do same for a LOV export. Before that I'm working on integration of better parses via rdflib since our RDFa parser is pretty rough.

**Comment by ppKrauss** [comment]
Ok, thanks the summary of "roadmap" and "working in progress" of the (core) Schema team.

-----

About parse **Wikidata's mappings**: I can generate another [schema_org_rdfa](http://schema.org/docs/schema_org_rdfa.html), with   [the **GoogleDoc with spreadsheet**](https://docs.google.com/spreadsheets/d/1KeTSrVjSHRfVRwSgg6-LN0pu6nVre7cspUrkf_gfMm8/) enhances, as  showed later in the #280's phase1.

About **LOV**: ok, let's add a column "LOV link" at the same spreadsheet... that is, can we do some  concrete work about it?  

About *both*: generate a separated  *..rdfa file* (instead merge into *schema_org_rdfa*) as you suggested, is ok, is only a matter of configure my (or your) parser.
