### ISSUE TITLE
ENH: class/property lookup JS widget

### ISSUE THREAD

**Issue by westurner** [schemaorg/schemaorg#349]
As a schema.org learner and implementor, I want to lookup classes and properties (through the web).

- [ ] ENH,REF: Choose an RDFJS framework
  * http://www.w3.org/community/rdfjs/wiki/Comparison_of_RDFJS_libraries
  * features/parser_support: { jsonld, n3, ttl, rdfxml }
    * http://json-ld.org/
- [ ] ENH,UBY: Autocomplete control with an index of classes, properties, extensions
  - [ ] Add control to docs/full?
  - [ ] Add control to front page? (ala http://prefix.cc)

Other Ideas

- ENH,UBY: Node descriptions initially collapsed showing just labels;
  Expand nodes as they are viewed (like code folding);
  Expand All, Collapse All
  - Tree Control
    - jsTree (jQuery)
- ENH,UBY: (re-)Differentiate `a:visited` links

Alternative Strategies

* Ctrl-F  is fast, but not case insensitive, or fuzzy
* grep -i -C 10 is case insensitive but extra-browser
* http://schema.org/docs/full.html
* http://schema.org/docs/schema_org_rdfa.html (*outdated / out of sequence?*)
* http://schema.org/docs/tree.jsonld (*experimental*)
* https://github.com/schemaorg/schemaorg/tree/sdo-ganymede/data/releases/2.0
  * https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/releases/2.0/schema.nt
  * https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/releases/2.0/schema.rdfa
  * https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/releases/2.0/schema-all.html
    * https://www.google.com/search?q=site:schema.org+inurl:schema-all.html
* http://schema.org > "Schemas" > "See also the **releases** page for recent updates and project history." > 2.0
      * http://schema.org/version/2.0/
        * http://schema.org/version/2.0/schema.rdfa
        * http://schema.org/version/2.0/schema.nt

**Comment by danbri** [comment]
There is an underdocumented and experimental JSON view of the tree that might be of interest: http://schema.org/docs/tree.jsonld

**Comment by westurner** [comment]
There's a JSON-LD editor with autocomplete here:

* http://json-ld.org/playground/
* http://json-ld.org/playground/#/gist/c05f56aee2cae1848758 (shows use of `{ "@container": "@list" }`)

Namespace completion would be really cool. There are some great RDFJS projects and components; a few links to resources:

* https://text.allmende.io/p/rdfjs
* https://www.w3.org/community/rdfjs/wiki/Comparison_of_RDFJS_libraries
* https://github.com/rdfjs/rdfjs.github.io

**Comment by danbri** [comment]
I don't think we're going to formally take this on, so I'll close out the issue. More tools would be cool, of course...

**Comment by westurner** [comment]
- Are there solutions for RDFS vocabulary exploration which would work with schema.org JSONLD?

- Are there versioned release URLs for schema.org JSON-LD?
