### ISSUE TITLE
change recipeIngredient from text to custom object

### ISSUE THREAD

**Issue by Pebkac03** [schemaorg/schemaorg#3495]
I have seen multiple older issues about this but I am raising it again since I think time has brought even more reasons for this to be changed.

I believe a recipeIngredient should follow a model similar to instructions which can be of either type text or HowTo. This would mean ingredients could have their amount, allergens, and other applicable designations specified.

This would allow traditional consumers like recipe managers like Mealie, Tandoor, Nextcloud coockbok, etc. To get more data when importing recipes. I also think with AI becoming more prevalent it would aid in AI searches for recipes, allowing them to provide recipes based on users' queries easier and with more accuracy. One example would be searching for a recipe for someone allergic to dairy. Would a LLM be able to figure out what foods fit that description? Would it be able to realise milk is dairy but soy milk is not?

**Comment by MatthiasWiesmann** [comment]
Could you provide an example of what this structure would look like?

**Comment by Pebkac03** [comment]
Yes, here is an an example in JSON:


```json
RecipeIngredient: {
  display: "400g mozarella"
  name: "Mozarella",
  amount: 400,
  unit: "grams",
  allergens: ["dairy", "lactose"]
}
```

**Comment by MatthiasWiesmann** [comment]
I would suggest something that uses the existing structured for measurements. 

```
ingredient: {
 "@type": "RecipeIngredient"
  display: "400g mozarella"
  name: "Mozarella",
  amount: {
    "@type": "QuantitativeValue"
    "value": 400
    "unitText": "grams"
    "unit": "GRM"
  }
}
```

Allergens are in my opinion a tricky one, as they have legal implications, for instance the EU defines 14 allergens. Sor for instance to be valid in the EU, the list of allergens should be ["milk"].
Maybe this should be represented using a DefinedTerm, i.e. 

```
ingredient: {
 "@type": "RecipeIngredient"
  display: "400g mozarella"
  name: "Mozarella",
  amount: {
    "@type": "QuantitativeValue",
    "value": 400,
    "unitText": "grams",
    "unit": "GRM"
  } ,
  allergens {
      "@type": "DefinedTerm"
      "termCode": "milk",
      "inDefinedTermSet": "http://example.com/EU-allergens"
  } 
}
```

Does this make sense?

**Comment by Pebkac03** [comment]
Yes, I tried to make it less verbose and was unaware of the already existing schemas you included.

This seems to me to be better. I do however not know if there are any negative implications of it being this much more verbose than just plain text, anyone with webdev experience that could chime in on this?

**Comment by MatthiasWiesmann** [comment]
Actually, I think defining a FoodProduct subclass and attaching the allrgens to the nutrition information would help us here, as we could attach the allergens there. 

```
receipeIngredient: {
   "@type": "IngredientItem"
   ingredient: { 
      "@type": "FoodProduct"
      "name": "Crazy Chocolate Bar™" 
      "nutritionInformation": {
         "@type": "NutritionInformation"
         "allergens" {
            "@type": "DefinedTerm"
            "termCode": "milk",
            "inDefinedTermSet": "http://example.com/EU-allergens"
         }
      }
    }
    "amount": {
      "@type": "QuantitativeValue",
      "value": 400,
      "unitText": "grams",
      "unit": "GRM"
  } ,
}
 ```

**Comment by Pebkac03** [comment]
My only concerns are the verbosity and if defining yet another class is necessary.

Also, the display is missing. Is this intentional or not?

**Comment by MatthiasWiesmann** [comment]
> My only concerns are the verbosity and if defining yet another class is necessary.

I would rather have additional classes that have redundant, badly defined fields like a simple text `amount`. 
Allergens are also needed for Food Products, so we need something consistent. 
If you have a simpler structure to propose. 

> Also, the display is missing. Is this intentional or not?

Just omitted for brievity.

**Comment by Pebkac03** [comment]
That's fair, then I don't have any additional issues.

**Comment by MatthiasWiesmann** [comment]
Thanks, I will close this issue, please-reopen it if needed.
