### ISSUE TITLE
articleBody and text

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#351]
`CreativeWork` defines [`text`](http://schema.org/text):

> The textual content of this CreativeWork.

`Article` defines [`articleBody`](http://schema.org/articleBody):

> The actual body of the article.

Is there a difference between "actual body" and "textual content", e.g., is one broader? Are there cases for an `Article` where only _one_ of these properties applies?

I wonder if we need `articleBody` at all, and if yes, if it should be a sub property of `text`.

**Comment by scor** [comment]
I remember telling @danbri about this, but never ended up filing an issue for that. +1.

'text' was introduced with the Comment type: http://www.w3.org/wiki/WebSchemas/Comment#Core_Proposal

**Comment by Dataliberate** [comment]
I was about to add a +1 for rationalising things in this area when a
thought struck me....

Is a Text sufficient, in either case, to represent the body of an Article
or CreativeWork?  Many articles contain formatting, images, etc., that can
only be represented in formats more complex than plain old text - html,
pdf, etc.

This question may be solved simply by adding URL [to the actual body] as a
type.

~Richard.

On 22 February 2015 at 18:29, Stephane Corlosquet <notifications@github.com>
wrote:

> I remember telling @danbri <https://github.com/danbri> about this, but
> never ended up filing an issue for that. +1.
>
> 'text' was introduced with the Comment type:
> http://www.w3.org/wiki/WebSchemas/Comment#Core_Proposal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schemaorg/schemaorg/issues/351#issuecomment-75481527>.
>



-- 
Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Tel: +44 (0)7767 886 005

Linkedin: http://www.linkedin.com/in/richardwallis
Skype: richard.wallis1
Twitter: @rjw

**Comment by vholland** [comment]
I'm trying to clean up some old issues. See pull request #1017

**Comment by tomayac** [comment]
Something that I am unclear about is whether [`schema:Text`](https://schema.org/Text) can be HTML text, or if it actually needs to be plain text? @Dataliberate's doubts seem similar.

Looking at the original [`rnews:articleBody`](http://dev.iptc.org/rNews-1-The-Article-Class), the authors clearly included HTML text:

```
[…]
@prefix rnews: <http://iptc.org/std/rNews/2011-10-07#> .
 
<http://dev.iptc.org/rNews-Sample-Story>  
  a  rnews:Article ;
  rnews:articleBody "<p>Having largely succeeded in...";
  […]
```

The [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) happily accepts both, plain text and HTML text, but it might be nice to have clarity as to what to expect.

**Comment by vholland** [comment]
It looks like this was resolved.
