### ISSUE TITLE
Add a /proposals folder in the  /schemaorg folder

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#352]
A "current proposal repository" proposal.

**See [`/proposals` folder working on my fork](https://github.com/ppKrauss/schemaorg/tree/sdo-gozer/proposals)**

-----

Process mechanism using the `/proposal` folder
=======================================

1. **Create** an issue here, to generate an *issue number*. <br/>Example: the issue "Transcribe equivalentProperty and Class mappings" creation, generated the *issue number 84*,  [`github.com/schemaorg/schemaorg/issues/84`](https://github.com/schemaorg/schemaorg/issues/84). 
2. **Discuss** the issue at public-vocabs@w3.org mail list and/or commenting at `github.com/schemaorg/schemaorg/issues/NUMBER`
3. (a collaborator with minimal `git` skills) **Consolidates** the proposal, with discussion results in a `Readme.md` text (and  in a modified source files when need), and submit it as a fork (new folder `testing/issueNUMBER`) of the `/proposals` folder at Github.
4. Review the `testing/issueNUMBER/Readme.md` with all  collaborators, like in a Wiki.
5. When the https://github.com/schemaorg *manager* agree that `testing/issueNUMBER` **is mature**, he/she decides: or accepts described changes; or move the folder to `stable/issueNUMBER` for hold (enhance with more serious tests and discussions).  

To merge more issues in a "main issue", rename the `testing/issueNUMBER` folder of the main issue to `testing/issueNUMBERetAl`, and document in the Readme the list of secondary issues.

Rationale
=========
People in the *Schema.org* discussions are coming from different fields and have different skills to collaborate, so, they are not obligated to know how to create `git`  branches... But they need some near or equal level of collaboration than a programmer with `git` skills.
The Github tools for "edit and commit" an `Readme.md` are the best will for this kind of broad collaboration. If you know how edit an issue, you know hou to edit a `Readme.md`.

Also the problem of **"to consolidate issue discussion in one document"** can be solved with the creation of the `/issueNUMBER/Readme.md` files.

------

NOTES
======

About W3C and Schema.org  communities using Github (and my personal view of the collaborative work here), 

 * **E-mail lists, Github-issue discussion, etc. problem**:  there are no "proposal consolidation"... Because consolidation need some centralization, somebody in charge, etc. 

 * **Github typical problem**:  the pressure of github forks (on the project's managers). The collaborators  will be fork more and more...  Creating pression on @danbri and [others](https://github.com/schemaorg/schemaorg/graphs/contributors),  to check, review, etc.  because each *git merge* is a delicate (and time consumer) operation, and ideally must to performed with some community feedback.

 * (by other hand...) **Github is so good when a fork is for self-evident  bug correctoins**. Example: to read [my *bug report 355*](https://github.com/schemaorg/schemaorg/issues/355) is more time-consumer for @danbri, than [a merge of my changed `data/schema.rdfa`](https://github.com/ppKrauss/schemaorg/commit/7f9fdd3885f9fbec742d1450a7dc62813dbc2273).

 * **A possible solution**: to concentrate "working in progress" and "proposal consolidations processes" in another place... My suggestion (here) was to **concentrate under a `/proposals` folder**. So a lot of fork/merge can be performed under   `/proposals` without any @danbri preocupation.  And @danbri can delegate to others — my suggestion is @danbri (or community) elects the user in charge of each relevant issue —, some aspects of "proposal consolidations processes" under the `/proposals`.

----

This is the current status of this "experiment" for consolidations, 

* [issue280](https://github.com/ppKrauss/schemaorg/tree/sdo-gozer/proposals/testing/issue280)

* [issue84etAl](https://github.com/ppKrauss/schemaorg/tree/sdo-gozer/proposals/testing/issue84etAl)

**Comment by danbri** [comment]
Thanks for your thoughts on this. We won't adopt directly but I'll tag them so they show up when people are looking at related issues.
