### ISSUE TITLE
adas.it

### ISSUE THREAD

**Issue by adasit** [schemaorg/schemaorg#3526]
laptop-stock-esfahan-isfahan-price-gharanti-new-it
اصفهان-لپتاپ-لپ تاپ-نو-استوک-آداس آی تی-آداس-کامپیوتر-گارانتی-قیمت-کیفیت

**Comment by adasit** [comment]
0913061809
-اصفهان-مجتمع تجاری عالی قاپو-طبقه همکف-پلاک 252

**Comment by MatthiasWiesmann** [comment]
Gibberish. Closing.
