### ISSUE TITLE
Incorrect example under http://schema.org/Question

### ISSUE THREAD

**Issue by magicomartinez** [schemaorg/schemaorg#353]
The current example under http://schema.org/Question is malformed with incorrect nesting of the suggestedAnswer inside suggestedAnswer. 

Google's testing tool also highlights this as an error:

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/944051/6327358/143cf8c6-bb53-11e4-9d6f-7f512fa52c25.png)

**Comment by vholland** [comment]
Fixed in https://github.com/schemaorg/schemaorg/pull/496.
