### ISSUE TITLE
The program cannot read my link URL, while Google can still read it

### ISSUE THREAD

**Issue by nhantam** [schemaorg/schemaorg#3534]
The program cannot read my link URL, while Google can still read it.

Could you help me check link: https://phaata.com/zip-code/ma-zip-ho-chi-minh-1309.html Why https://validator.schema.org/ not check but Google still read?

**Comment by MatthiasWiesmann** [comment]
It seems your server is not serving the page to the schema.org crawler, maybe there are some blocked ip addresses?
I would suggest you copy-paste the HTML of your page as a workaround.
