### ISSUE TITLE
PROTEGÉ Y SHEMA.ORG

### ISSUE THREAD

**Issue by PIJEPI** [schemaorg/schemaorg#3541]
Como se podría añadir un concepto de shema.org a en la herramienta de software Protegé sin necesidad de importar  esto dos ficheros https://schema.org/docs/schemaorg.owl  y https://schema.org/docs/developers.html. Y cual de estos dos ficheros es mejor para trabar en protege.
Gracias

**Comment by MatthiasWiesmann** [comment]
This is something you should clear up with the developers of the Protegé software. 
Closing.
