### ISSUE TITLE
Update to Schema.org site

### ISSUE THREAD

**Issue by rvguha** [schemaorg/schemaorg#3544]
The schema.org site has not had a UI refresh since we first launched in 2011.

Adriana Olmos and Carolyn Au have worked on a refresh. An early version can be found at https://1-dot-schemaorgtest-425516.uc.r.appspot.com/

Please send feedback.

**Comment by jvandriel** [comment]
I like the new look (it will take a while to get used to after having the same look for so long). 

One of the things I'd like to see changed is the padding of table cells, specifically the small vertical padding. This causes me to find the table rows hard to read (their content is too close together). 

Maybe the table cell CSS could be changed to:
```
.definition-table td {
    padding: 5px; // 5px all the way around
    margin: 0;
    vertical-align: top;
    border-bottom: 1px solid #f0f0f0;
}
```

Next to that, on mobile devices the `<table>` breaks out of the main content, causing horizontal scrolling to be somewhat of a strange experience.

<img width="408" alt="Screen Shot 2024-06-06 at 1 08 17 PM" src="https://github.com/schemaorg/schemaorg/assets/7320889/e23d7b2e-edac-40b1-b596-0e35371cb049">


This could be resolved by adding a wrapper `<div>` around the `<table>`, with some accompanying CSS to make the `<table>` scroll horizontally without breaking out of the main bounding box.

```
.table-wrapper {
  overflow-x: auto;
}

<div class="table-wrapper">
  <table class="definition-table">
    ...
  </table>
</div>
```

**Comment by thijsvanhal** [comment]
Since JSON-LD is the recommended method (and probably the most used?) my suggestion would be to change the order of examples where JSON-LD would be the first one.

![image](https://github.com/schemaorg/schemaorg/assets/26331947/41b2eb71-6146-4cb0-baef-15b2e1b52a58)

**Comment by gondimedia** [comment]
I would recommend a dark mode version of the site.

**Comment by jeannieh** [comment]
I like the clean, crisp new look for easy readability. The issue on mobile of text expanding beyond the bounding box can be readily solved with CSS. It may help to add “position: relative;” to the td code that Jarno has offered.
![IMG_4990](https://github.com/schemaorg/schemaorg/assets/495968/9877c4cb-574b-493c-8041-14e7ce0f277b)

**Comment by jvandriel** [comment]
To improve the readability of the releases pages the same `<div class="table-wrapper">` could be used for its `<table>`, though it seems it also needs some additional CSS modifications.

```
#mainContent td ul, 
#mainContent td ol,
#mainContent td ul li, 
#mainContent td ol li {
  list-style: inside;
  margin: 0;
  padding: 0;
}

#mainContent td ul li + li, 
#mainContent td ol li + li {
  margin: 0.5em 0 0 0;
}
```

<img width="409" alt="mobile-improved-readability" src="https://github.com/schemaorg/schemaorg/assets/7320889/403b5f7a-aea5-4bb3-a0bd-323314c65f2c">

**Comment by jvandriel** [comment]
There's one feature that's been on my wishlist for a long time already and that's a full overview of schema.org's properties. 

Pretty much the same presentation as the full Types and DataTypes hierarchies, only than a list of all the properties that can be expanded to see which Classes they belong to. It could be placed below the Datatypes list, it doesn't need its own URL.

Right now finding properties is really hard if you don't know their domain.

**Comment by Juggala** [comment]
I like the fact it's clean, although I do find **reading long descriptions** is a bit less UX-friendly **when sentences are very wide** (on maximized windows on a standard or big/widescreen monitor).

The fix is basically as easy as adding a _max-width_ (for example 900px) to the #mainContent container.

**Comment by raramuridesign** [comment]
On the docs pages it would be great to have more spacing above the h2,h3 etc
Similar to this. 
h3:first-child and h2:first-child with less margin. 
![image](https://github.com/schemaorg/schemaorg/assets/902376/0da3d678-1fd6-4a2b-ba4f-a9a1e7447cb7)

**Comment by Alireza-Naji** [comment]
i believe that adding Dark Mode to schema.org UI would be valuable improvement. i urge you to consider this. thanks

**Comment by beets** [comment]
Thank you all for your feedback!

We've fixed the overflow issue with tables on mobile (the releases table scrolls, while the schema property tables were reverted back to showing all content inline without scroll where possible. We also added a max-width to the content and updated the padding/margin in various areas.

The changes are here: https://2-dot-schemaorgtest-425516.uc.r.appspot.com/

**Comment by jvandriel** [comment]
I like the fix for the table on the releases page, as well as the new margins/paddings, but I'm sorry to say that I'm not that crazy about inlining the content of type/property tables. I liked these more when I could horizontally scroll (but maybe that's just me).

**Comment by RedCardinal** [comment]
Search results aren't picking up new font styles: https://2-dot-schemaorgtest-425516.uc.r.appspot.com/docs/search_results.html?q=review

I see some wiser minds providing feedback on the tabular layouts, but am I the only one who needs to do some mental gymnastics to figure out latest tabular layout on mobile? It may be a tail-chasing-dog issue if most traffic comes in as Desktop, but I see the following issues on Mobile:
* main table header row will need to be adjusted for the new mobile layout;
* when I look at each row, I can't help but think these are cards.  I think it's a funky border issue, but my poor 50yo eyes just see stacked cards.  A regular table with overflow to the right, perhaps with sticky th, might be more useful?

**Comment by KajKandler** [comment]
I wished the validator would get a better interface for the detected schema:
- collapsible tree
- a property order not defined by alphabet (*) or randomness, yet by some sensible grouping.
- a graph view of the entities involved
- a view where the entities are shown in a @graph array fashion (deduplicated)
-- with links to jump between the reference and definition of an entity

(*) I know JSON is unordered, which still makes it hard to read for humans despite popular claims.

**Comment by beets** [comment]
Thanks all for the feedback! 
- Applied the new typeface on the search results and improved the pagination readability.
- For Tables the cells are wrapping as in the older version to allow for readability without having to scroll horizontally. This helps with accessibility and is existing behavior on the site.
- We'll address the validator separately from this update.

Changes are staged here:
https://3-dot-schemaorgtest-425516.uc.r.appspot.com/

**Comment by beets** [comment]
Thanks all for the feedback and comments! This has been pushed to schema.org

**Comment by EduardoZepeda** [comment]
I just enter the site after weeks of not worrying about SEO, and I was shocked by the new design! the site looks awesome! Tidy and minimalist! Keep up with the good work guys!
