### ISSUE TITLE
Class labels with space

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#355]
at current https://github.com/schemaorg/schemaorg/blob/sdo-gozer/data/schema.rdfa
some classes (`rdfs:Class`) are in the form "Label Label" instead "LabelLabel" in the `rdfs:label` span value.

 *  Bus Trip (http://schema.org/BusTrip)
 * Program Membership (http://schema.org/ProgramMembership)
 * Train Trip (http://schema.org/TrainTrip)
 
-----

It is a problem when you use a XPath (to retrive the Classe's properties) lilke

   //div[@typeof='rdf:Property' and ./span/a[@property='$INCs' and @href='http://schema.org/$class']]/span[@property='rdfs:label']

**Comment by ppKrauss** [comment]
I do the correction, [you can view it navigating here](https://github.com/ppKrauss/schemaorg/commit/7f9fdd3885f9fbec742d1450a7dc62813dbc2273), but it is a pending fork.

**Comment by danbri** [comment]
Thanks. We haven't decided what to do on this point yet. It might be that we represent both, but choose a second property. It is useful to represent the strict identifier for a type/property/enum, but also to have a short more human-oriented version (which might help for multi-lingual translations).

**Comment by danbri** [comment]
I see part of this is duplicated in  https://github.com/schemaorg/schemaorg/pull/386 from @vholland so I'll implement it from there. We'll stick with "no spaces in labels" for now, although people have argued it should work differently the bulk of the vocabulary has labels simply matching the term ID. Thanks!
