### ISSUE TITLE
Consider adding a value at Itemavailabilty with the name Order

### ISSUE THREAD

**Issue by thomas298** [schemaorg/schemaorg#3559]
Consider adding a value at Itemavailabilty with the name Order that will apply for the products that are not immediately available (Instock) but available after a client orders them within a certain period.
Outofstock does not match either because it is interpeted that the client has to wait for restocking.
Any of the other values does not match either.

**Comment by alex-jansen** [comment]
Added [MadeToOrder](https://schema.org/MadeToOrder) in Release 28.0, so closing as done.
