### ISSUE TITLE
Add ratings for content suitability (children, teenagers, adults) to Schema.org

### ISSUE THREAD

**Issue by mediaprophet** [schemaorg/schemaorg#3560]
Issue Description:

**Proposal:**
Currently, Schema.org provides a robust framework for marking up various types of content on the web, but there is a gap in specifying the suitability of content for different age groups (children, teenagers, adults).

**Problem Statement:**
There is a growing need for websites and online platforms to indicate the age-appropriateness of their content. This information is crucial for parents, educators, and content filters to ensure that users are accessing material suitable for their age group. However, there is no standardized way in Schema.org to specify these age ratings.

**Objective:**
The objective of this proposal is to introduce new properties or extend existing ones in Schema.org to allow content creators to specify age ratings for their web content. These ratings would cover categories such as content suitable for children (e.g., under 12), teenagers (e.g., 13-17), and adults (18+).

**Example Use Cases:**

1. A children's educational website wants to mark its content as suitable for ages 5-10.
2. A streaming service wishes to mark certain movies and TV shows as suitable for teenagers aged 13-17.
3. An adult-oriented website needs to indicate that its content is intended for users 18 and older.

**Implementation Details:**

1. **New Properties**: Introduce new properties (e.g., contentRatingForChildren, contentRatingForTeenagers, contentRatingForAdults) under the existing Schema.org hierarchy.

2. **Integration with Existing Types**: Ensure compatibility with existing types such as CreativeWork and WebPage so that these ratings can be applied to various types of content.
  
3. **Documentation and Guidelines**: Provide clear guidelines and examples in the Schema.org documentation on how to use these new properties effectively; including, considerations about browser functionality and/or plugins that may restrict access to content for certain users.

**Benefits:**

- **Clarity for Users:** Users, especially parents and guardians, will have clearer information about the appropriateness of web content for different age groups.
- **Enhanced Filtering:** Content filters and parental controls can use these ratings to restrict access to content based on user-defined age settings.
- **Standardization:** Establishing a standard for age ratings on the web promotes consistency across different platforms and improves accessibility.

Next Steps:

- Discuss and refine the proposed properties and their integration within the Schema.org community.
- Develop consensus on the implementation details through community feedback.
- Update Schema.org documentation and schemas accordingly.

Additional Notes:
This enhancement aligns with evolving trends in content regulation and user protection on the internet, aiming to provide a safer and more informed browsing experience for all users.

Tags: enhancement, content-rating, schema-extension, community-feedback

**Comment by jvandriel** [comment]
Have you looked into the audience property @mediaprophet?

It seems to me it allows one to express what you're describing:

```json
{
  "@context": "https://schema.org",
  "@type": "CreativeWork",
  "audience": {
    "@type": "PeopleAudience",
    "name": "teenagers",
    "suggestedMinAge": 13,
    "suggestedMaxAge": 17
  }
}
```

**Comment by mediaprophet** [comment]
ChatGPT says the following;

Question: Explain the difference between schemaorg for content moderation
for the purpose of enabling a client to make the world wide web safe for
children vs. https://schema.org/PeopleAudience or
https://schema.org/ParentAudience

Answer:
The difference lies primarily in the purpose and focus of the schemas:

1. **Schema.org for Content Moderation (Child Safety):**
   - **Purpose:** This schema would focus specifically on marking up web
content to indicate its suitability for children in terms of
age-appropriate content and safety.
   - **Usage:** It would provide properties or guidelines for publishers
and platforms to annotate their content with age ratings or safety
indicators (e.g., "suitable for ages 5-10", "child-friendly").
   - **Example Use Cases:** Websites offering educational content for
children, games designed for younger audiences, or platforms hosting videos
or articles meant for kids.

2. **Schema.org/PeopleAudience or Schema.org/ParentAudience:**
   - **Purpose:** These schemas are broader in scope and focus on
describing the intended audience of a particular piece of content or
service, rather than specifically on child safety.
   - **Usage:** They are used to define characteristics of the audience
such as demographics, interests, or behaviors. This could include
properties like age range, gender, interests, or other demographic
information.
   - **Example Use Cases:** Websites targeting specific demographics such
as "young adults interested in technology", "senior citizens interested in
travel", or "parents interested in educational resources".

**Key Differences:**

- **Focus:**
  - **Child Safety Schema:** Specifically focuses on safety and
appropriateness of content for children.
  - **PeopleAudience/ParentAudience:** Focuses on describing the general
characteristics of an audience without necessarily emphasizing safety or
age appropriateness.

- **Usage:**
  - **Child Safety Schema:** Used for marking content to ensure it meets
safety and appropriateness standards for children.
  - **PeopleAudience/ParentAudience:** Used to describe the intended
demographic or audience characteristics of content, which can include but
is not limited to children.

- **Implementation:**
  - **Child Safety Schema:** Likely includes specific properties related to
age ratings, safety guidelines, and parental controls.
  - **PeopleAudience/ParentAudience:** Includes properties for demographic
information, interests, and other audience characteristics but typically
does not focus on safety ratings.

In summary, while both types of schemas aim to provide metadata about
content and its audience, Schema.org for Content Moderation for Child
Safety would be more focused on ensuring safe and appropriate content
specifically for children, whereas Schema.org/PeopleAudience or
Schema.org/ParentAudience are broader in scope, describing audience
characteristics without necessarily focusing on safety and
age-appropriateness.


Considerations otherwise:

There is a big push to ensure that the internet is safe for kids, which
i've considered to be usefully separated by age groups.  Some activities
seek to render assertive controls on the internet and in-turn also
surveillance. There is presently an apparent lack of capacity to easily set
a device to look for RDF that is able to be used to moderate what content a
device being used by a child / person under 18 (not of legal age) can
access.  Pornography sites is a simple example; perhaps more advanced
examples could include certain posts, within a stream of content - where
some may be defined to be 'adult' content.

It is known that these issues are having a significantly negative impact
upon children and in-turn also, society.

it is desirable to seek to define a solution that both seeks to address the
underlying issue and mitigate unintended consequences / misuse of methods,
by governments (for example); as to employ techniques supported on the
basis of protecting children, but as may be used for other purposes, not
good for democracy, etc.

At IETF119 i presented 'ADP' agent discovery protocol - which is an old
idea, that is intended to compliment spiders.txt  / sitemap.xml & in-turn
also, WebID related semantics.
https://datatracker.ietf.org/meeting/119/materials/slides-119-hotrfc-sessa-09-agent-discovery-protocol-00


The method seeks to provide basic public semantics at the base of a domain
/ subdomain to define the form of agent - for purposes broader than SEO.
This method is intended to depend upon a client-side process / software,
that looks for the semantic notations; thereby, designing a mechanism
where, when used with websites, the website adds the information about the
website / content; which may or may not then be verified with a 3rd party
credential or similar, and then the client requires a method to implement
settings and then augment results / experiences based upon the settings.

#### Reliable Age-Appropriate Content

@prefix schema: <https://schema.org/> .

<https://example-adult-website.com> a schema:WebSite ;

     schema:isAdultOriented "True" .

# or

@prefix acme: <http://acme.org/ratings#> .

<https://example-adult-website.com> a schema:WebSite ;

     acme:contentRating "ACME-18+" .

<https://mediaservice.tld> a schema:WebSite ;

    adp:hasEndpoint adp:childEndpoint, adp:teenEndpoint, adp:adultEndpoint .

# Child Endpoint

adp:childEndpoint a schema:EntryPoint ;

    content:suitableForAgeGroup "Under13" .

# Teen Endpoint

adp:teenEndpoint a schema:EntryPoint ;

    content:suitableForAgeGroup "13to18" .

# Adult Endpoint

adp:adultEndpoint a schema:EntryPoint ;

    content:suitableForAgeGroup "Over18" .

It occurred to me this morning that the fastest path to get something
useful implemented to protect kids - would be via schemaorg; thereafter
also, ideally, the browsers.

NOTE: the schema illustrated is illustrative - not otherwise - therein,
post as an issue in the hopes the schemaorg community / cg would 'get it',
and then figure out the best vocab to make it happen, asap.

Tim.

**Comment by mediaprophet** [comment]
IE / NB: https://www.esafety.gov.au/newsroom/media-releases/clock-ticking-for-online-industry-to-come-up-with-plan-to-protect-aussie-kids-from-porn

**Comment by chaals** [comment]
Seems like you are looking for `contentRating` which can have a text value such as "MA 15+" (An Australian classification) or "PG13" (a US classification). If you're specifically planning to identify porn, RTA possibly has you covered already...

**Comment by mediaprophet** [comment]
Yup.

Although question.  Can this be improved?

Objective would be to seek adult websites in particular to declare
themselves, and ideally in future, browsers or solutions better than a
browser extension, integrating a function to look for the mark-up.

Whilst my work on "ADP" goes a bit beyond this usecase alone, the hope is
that action can be quickly to define a solution that can be easily
implemented by sites; thereby also, via means that provides contexts rather
than censorship of internet more broadly.  Therein, it's up to the device
owner to set the parameter on local user accounts; and, like creative
commons, it's easily deployed on sites.

Different regions have different ratings systems. Would be better if
there's consideration for expected values that can be defined worldwide.

Then, perhaps, make it more complicated.

The other consideration is whether the rating has been provided by the site
owner or some 3rd party validator/credential issuer, which may then be
considered by clients; and,

Consideration about how services, like search, might be augmented to ensure
only results suitable for children, if the browser is set to that mode...

**Comment by MatthiasWiesmann** [comment]
> Different regions have different ratings systems. Would be better if there's consideration for expected values that can be defined worldwide.

Different regions have different cultural norms and legal definitions of what content is acceptable and at which age.
Whatever you choose as a global norm, there will be regions that consider it either to restrictive, or not enough. 

At any rate, defining such a norm does seem like something directly relevant to schema.org, if there were such a standard then mapping it into schema.org would be. Until then, I'll close this bug.

**Comment by mediaprophet** [comment]
wrote this a while-back:
https://docs.google.com/document/d/1c1Afo-bja_jksBEynHyG7nBDz71TAPOZYkagdoh4e6A/edit?usp=sharing


In particular, the issue of content suitability for children is a topic of
importance in various quorums.  Additionally, there are continuing
complaints about content in social networks.  In both cases, it appears
these issues are being employed as an opportunity to issue credentials
and/or 'digital identity' as is defined in a particular way, that i think
to be problematic; and others may in-future find, that an oversimplified
commercially supported approach results in unintended consequences; whilst,
i think the saying goes that 'most often failures become orphans', or some
such thing.

The initial point is to be able to produce web-extensions and/or
functionality that may then have settings about specific content that is
sought by the user to not be presented / available in the browser profile -
whether this is password protected (ie: for children) or otherwise.  I
initially focused on the use-cases relating to children specifically, but
then broadened considerations as there's stuff that many of us don't want
to see, so, its more of a personalisation 'safety protocols' (as i'd call
it) function.

The method then assumes, that websites would then add mark-up to the site
or perhaps even the <div> to then provide the ability for those tags to be
processed by the browser side, and thereby respect the users choice.. Some
use cases, like a adult / pornography website or other website that's
reasonably considered only for adults - could use the mark-up to make that
declaration, thereby disabling access to the site and indeed also,
notification to search, that may then also employ the information to modify
results, particularly if a user is logged into that search engine website,
etc.

In other cases, it could be used in the mark-up within the content, for
example twitter/x or similar, both to protect children but also, perhaps
adults don't want to see porn or some other category... thereby,
potentially the browser could filter out those posts on  the rendered
output.

but the most important / urgent example, is the one relating to seeking to
provide website owners across the world the opportunity to act and support
an initiative where users get to define settings in their childrens
computers / online use, that provides an ability to be more considerate of
their needs as young people, young minds.

certainly, doesn't seem like there's alot of interest, which is probably
why the 'digital identity' and other more concerning options are being
evaluated by governments, etc.  But, maybe its just that the idea wasn't
put forward..  I imagine it wouldn't be that hard to both figure out some
basic functionality, then get a campaign set-up to support awareness for
both website owners (what code to add) and end-users (what browser
extension / how to find the settings in browsers or online accounts).

or maybe its just not something that is considered usefully done by
schemaorg..  Dunno.  I just raised it for others to consider, on the 2nd of
july...  given, it didn't seem to be something that people were able to use
or promote (ie: as parliamentarians, etc) already.

**Comment by MatthiasWiesmann** [comment]
As I mentioned, schema.org is about representing existing information in machine readable format, not defining standards, in particular such far reaching ones. Content rating has been a subject on the internet since its inception, for instance the NetNanny was created in 1994, so it is not as you claim, that there is no interest, but because the problem is __hard__.

I would suggest you first look at the existing annotations:

* [The RTA meta header annotation](https://www.rtalabel.org/index.php?content=howto)
* [The safesearch adult attribute](https://developers.google.com/search/docs/crawling-indexing/safesearch). 
* [RFC 3514](https://www.ietf.org/rfc/rfc3514.txt)

**Comment by mediaprophet** [comment]
I think I've done my best.  So, i'll make others who may be interested know
the position, but i'm not interested in adversarial engagements with 'free'
open-source works for the betterment of humanity done at my own expense,
whilst all too often incurring further harms and costs, without means to do
anything about it; whilst also, ensuring that i maintain my obligations to
always be nice.

i presented
https://datatracker.ietf.org/meeting/119/materials/agenda-119-hotrfc-sessa-04#h.eno136kpyxqs
| https://www.youtube.com/watch?v=ZDH5eaIF_zc&t=2024s which has more
complex ways of achieving similar (and far more advanced) outcomes, but
given the importance; i thought this to be something that schemaorg &
related parties, could both implement and then promote to encourage
websites to implement, fairly quickly.

my obligation, morally, was to share that view, given it didn't appear to
already be in place.  I think my moral obligation is now fulfilled.  I'll
share the link with others, and leave it up to others as my efforts do
appear now, exhausted for this task.

There is an issue with the implications of how content on the web impacts
young people.  This issue continues to be a problem because there's no good
solutions implemented to address it effectively enough yet. I find it
difficult to believe that this would require further

There are also issues with people complaining about content on various
social networks, thereby seeking to assert content controls / restrict
speech - if content were able to be categorised perhaps people could just
turn the stuff they don't want to see, off; but if the first relatively
simple example isn't comprehensible or deemed relevant to schemaorg, then
any expansion on that would be foolish.

🙏
