### ISSUE TITLE
Proposal to support loyalty (membership) pricing by extending Organization and Offer

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3563]
## Context

This is a proposal from Google based on our experience consuming schema.org Offer and Organization markup and working with similar data from online merchants. If it were accepted, it would allow merchants to add loyalty (membership) programs and pricing to their Organization and Offer structured data and allow us and other consuming systems to better understand the various pricing options for products sold online. See also #3190. 

## Description

Products advertised or sold online often have different prices, depending on whether the consumer is a member of the merchant's loyalty program and, if so, the program tier (for example, "bronze", "silver", and "gold") the consumer is a member of.

To support the specification of such loyalty programs and the associated preferred prices as well as other benefits (such as loyalty points) we propose to add a few additional types to allow (1) the definition of the loyalty program and its member tiers offered by a business, and (2) the specification of tier-specific prices for product offers.

#### Program and Tiers

We propose to add a new class _/MemberProgram_ as a subtype of[ /Intangible](https://schema.org/Intangible) to allow the specification of a membership program. The name, description, and signup URL for the program can be defined using the inherited properties _[/name](https://schema.org/name)_, [/description](https://schema.org/description), and _[/url](https://schema.org/url)_.

We propose to also introduce a related new property _/hasMemberProgram_ with values of type _/MemberProgram_ for use on [/Organization](https://schema.org/Organization) to allow the specification of the Membership program(s) provided by the organization (typically a merchant).

To specify the various membership tiers under the program we propose to introduce a new class _/MemberProgramTier_, a subtype of[ /Intangible](https://schema.org/Intangible). The name and signup URL for the tier can be defined using the inherited properties _[/name](https://schema.org/name)_ and _[/url](https://schema.org/url)_. 

We propose to also add a new property _/forProgram_ for use on _/MemberProgramTier_ to specify the membership program the tier is a part of, For reverse linking, we also propose to add a new property _/hasTiers_ for use on _/MemberProgram_ to specify the member tier(s) part of the program.

#### Tier Requirements

To specify the requirements of each member tier we propose to add a new property _/hasTierRequirement_ with values of a new enumeration type _/TierRequirementEnumeration_ with the following values:

*   _/TierFreeToJoin_ - the tier is free to join
*   _/TierSpendingAmountRequired_ - the tier requires a specific spending amount
*   _/TierCreditCardRequired_ - the tier requires the consumer to sign up for a credit card
*   _/TierPeriodicFeeRequired_ - the tier requires a fee to be a member of the tier for a specific period, e.g., monthly or annually.

To support these requirements we also propose to add the following properties for use on _/MemberProgramTier_:

*   _/minimumSpendingAmount_ of type [/MonetaryAmount](https://schema.org/MonetaryAmount) 
    *   to be provided when _/hasTierRequirement_= _/TierSpendingAmountRequired_
*   _/creditCard_ of type /[Text](https://schema.org/Text)
    *   to be provided when _/hasTierRequirement_ = _/TierCreditCardRequired_
*   _/periodicFee_ of type [/MonetaryAmount](https://schema.org/MonetaryAmount)
    *    to be provided when _/hasTierRequirement_=_/TierPeriodicFeeRequired_
*   _/periodLength_ of type [/QuantitativeValue](https://schema.org/QuantitativeValue)
    *    to be provided when _/hasTierRequirement_=_/TierPeriodicFeeRequired_

#### Tier Benefits

To specify the benefits associated with a program tier we propose to add a new property /_hasTierBenefit_ with values of a new enumeration type _/TierBenefitEnumeration_ or of type /[Text](https://schema.org/Text) (for free-form benefits) with the following values:

*   _/TierBenefitLoyaltyPrice_
*   _/TierBenefitLoyaltyPoints_

To support these tier benefits we also propose to add existing property [/membershipPointsEarned](https://schema.org/membershipPointsEarned) to _/MemberProgramTier_,  to be provided if _/hasTierBenefit_= _/TierBenefitLoyaltyPoints_, indicating the number of loyalty points earned by the consumer per currency unit spent.

### Defining loyalty program pricing and loyalty points earned for Offers

We propose the following new properties to be able to tie an offered price to a specific member program and specify the benefits for each of its tiers:

*   Add a new enumeration value _/MemberPrice_ to existing enumeration type[ /PriceTypeEnumeration](https://schema.org/PriceTypeEnumeration) for use on property [/priceType](https://schema.org/priceType).
*   Add a new property _/validForMemberTier_ with values of type _/MemberProgramTier_ to specify that the price is only valid for members of the specific membership program and tier, when provided. Add this new property under [/PriceSpecification](https://schema.org/PriceSpecification).
*   Add existing property [/membershipPointsEarned](https://schema.org/membershipPointsEarned) to [/PriceSpecification](https://schema.org/UnitPriceSpecification) to indicate loyalty points the consumer can earn with the purchase, if different from the default specified under the tier.

### Example

The following example illustrates the definition of the member program and its tiers under an instance of an [OnlineStore ](https://schema.org/OnlineStore)(subtype of Organization), followed by a list and member price of an offer using [UnitPriceSpecification](https://schema.org/UnitPriceSpecification)

```
[
  {
    "@context": "https://schema.org",
    "@type": "OnlineStore",
    "name": "Example Online Store",
    "url": "https://www.example.com",
    "sameAs": [
      "https://example.net/profile/example12",
      "https://example.org/@example34"
    ],
    "logo": "https://www.example.com/assets/images/logo.png",
    "contactPoint": {
      "contactType": "Customer Service",
      "email": "support@example.com",
      "telephone": "+47-99-999-9900"
    },
    "vatID": "FR12345678901",
    "iso6523Code": "0199:724500PMK2A2M1SQX229",
    "hasMemberProgram": {
      "@type": "MemberProgram",
      "name": "Membership Plus",
      "description": "For frequent shoppers this is our top-rated loyalty program",
      "url": "https://www.example.com/membership-plus",
      "hasTiers": [
        {
          "@type": "MemberProgramTier",
          "@id": "#plus-tier-silver",
          "name": "silver",
          "url": "https://www.example.com/membership-plus-silver",
          "hasTierRequirement": "https://schema.org/TierFreeToJoin",
          "hasTierBenefit": [
            "https://schema.org/TierBenefitLoyaltyPoints"
          ],
          "membershipPointsEarned": 5
        },
        {
          "@type": "MemberProgramTier",
          "@id": "#plus-tier-gold",
          "name": "gold",
          "url": "https://www.example.com/membership-plus-gold",
          "hasTierRequirement": "https://schema.org/TierCreditCardRequired",
          "creditCardRequired": "Example platinum card plus",
          "hasTierBenefit": [
            "https://schema.org/TierBenefitLoyaltyPrice",
            "https://schema.org/TierBenefitLoyaltyPoints"
          ],
          "membershipPointsEarned": 10
        }
      ]
    }
  },
  {
    "@type": "Product",
    "sku": "44E01-X1100000",
    "gtin14": "98766051104399",
    "image": "https://www.example.com/coat_large_lightblue.jpg",
    "name": "Large light blue coat",
    "description": "Large wool light blue coat for the winter season",
    "color": "light blue",
    "size": "large",
    "offers": [
      {
        "@type": "Offer",
        "url": "https://www.example.com/coat?size=large&color=lightblue",
        "itemCondition": "https://schema.org/NewCondition",
        "availability": "https://schema.org/Backorder",
        "shippingDetails": {
          "@id": "https://www.example.com/shipping#shipping_policy"
        },
        "hasMerchantReturnPolicy": {
          "@id": "https://www.example.com/com/returns#return_policy"
        },
        "priceSpecification": [
          {
            "@type": "PriceSpecification",
            "price": 15,
            "priceCurrency": "USD"
          },
          {
            "@type": "PriceSpecification",
            "priceType": [
              "https://schema.org/MemberPrice"
            ],
            "validForMemberTier": {
              "@id": "https://www.example.com/com/members#plus_tier_gold"
            },
            "price": 9.95,
            "priceCurrency": "USD"
          }        
        ]
      }
    ]
  }
]

**Comment by jvandriel** [comment]
A lot of the details seem to be a translation of the Merchant Center specs for `[loyalty_program]`, however, I am missing some loyalty program benefit options Google Merchant Center does describe, like (1) Redeemable points, (2) shipping benefits, (3) Cashback (and probably some more I overlooked when glancing over the GMC specs).

Has it been given any thought on how to integrate these into the proposal in the future?
(e.g. how will `shippingDetails` fit into this if its values depend on a loyalty program?)

**Comment by alex-jansen** [comment]
Hi @jvandriel . The proposal is indeed inspired by Google Merchant Center, but Schema.org should ideally present a more general model and not be limited to what one system has modeled. I therefore do like your proposal to generalize and allow the specification of other potential benefits of loyalty programs (such as free shipping or returns). Before going into more detail, what do you then think about elevating the proposed property _/validForMemberTier_, and add it to _/Offer_ (instead of _/PriceSpecification_)? That way it is clear that the offer (with its associated price, shipping cost, return policy, etc,) is valid for a specific member-tier only. We would also not need _/priceType=/MemberPrice_. The drawback of this approach is that this would lead to more verbose markup since typically only 1 or 2 Offer properties would change depending on the member-tier, and the others would have to be duplicated. Adding @mfhepp for an opinion as well.

**Comment by jvandriel** [comment]
> _"what do you then think about elevating the proposed property /validForMemberTier, and add it to /Offer (instead of /PriceSpecification)?"_

I like that idea, although

> _"what do you then think about elevating the proposed property /validForMemberTier, and add it to /Offer (instead of /PriceSpecification)?"_

Is also a valid point of consideration. 

Would it be too much of a stretch to circumvent that by making use of the 'addon' property, so that the nested `Offer` only needs to describe the values that differ?

To me it seems its description sort of leaves enough space for such an interpretation (emphasis mine): 
_"An *additional offer* that can only be obtained in combination with the first base offer (e.g. *supplements* and* extensions* that are available for a surcharge)."_

Tha we could model something like this:
```
{
  "@type": "Offer",
  "url": "https://www.example.com/coat?size=large&color=lightblue",
  "itemCondition": "https://schema.org/NewCondition",
  "availability": "https://schema.org/Backorder",
  "shippingDetails": {
    "@id": "https://www.example.com/shipping#shipping_policy"
  },
  "hasMerchantReturnPolicy": {
    "@id": "https://www.example.com/com/returns#return_policy"
  },
  "priceSpecification": {
    "@type": "PriceSpecification",
    "price": 15,
    "priceCurrency": "USD"
  },
  "addOn": {
    "@type": "Offer",
    "validForMemberTier": {
      "@id": "https://www.example.com/com/members#plus_tier_gold"
    },
    "priceSpecification": {
      "@type": "PriceSpecification",
      "price": 9.95,
      "priceCurrency": "USD"
    }  
  }
}
```

And I very much would like to hear @mfhepp's opinion about this as well (he often has points of view I hadn't even considered).

**Comment by alex-jansen** [comment]
Not sure if addOn is the right approach, an offer for members is typically a separate offer, not an add-on offer that can only be obtained in combination with another base offer. addOn seems more intended for bundles (see also https://github.com/schemaorg/schemaorg/issues/2712#issuecomment-2145285763) . In that case I would rather take the extra verbosity.

**Comment by alex-jansen** [comment]
Just in an attempt to move this along, another approach could be to allow the specification of loyalty benefits both at the level of /Offer **AND** also on finer-grained types such as /PriceSpecification, /OfferShippingDetails, and /MerchantReturnPolicy. That would allow both complex loyalty benefits (e.g., better pricing, shipping, and return options bundled together) or more narrow-scoped benefits, e.g., only better pricing. In the latter case we can have more compact markup. Thoughts?

**Comment by Johanstormarn** [comment]
+1 for making the benefits also available on /Offer and /PriceSpecification.
Working right now with a client where we need to make /cashback available for non /CreditCard products (it's a thing in Germany for quite a broad range of products).

**Comment by alex-jansen** [comment]
Published a test site for review. Link: https://1-dot-schema-experiment.uc.r.appspot.com/MemberProgram (all the other new types can be reached from there). 
@jvandriel and @mfhepp PTAL.

**Comment by MatthiasWiesmann** [comment]
I would suggest doing the following to make things more consistent:

* `ProgramMembership` should have a `program`fields that points to a `MemberProgram`, the `programName` should be annotated to say it is preferred to have the `program` field populated.
*  `MemberProgram` should have a `hasHostingOrganization` field pointing to an `Organization`, this would act as a reverse relationship to `hasMemberProgram`. 

This would make explicit the relationship between the three objects, `MemberProgram`, `ProgramMembership`, and `MemberProgramTier`. 

Another thing I would change is the `creditCard` field of the `MemberProgramTier`, which is highly specific, and completely out of sync with the payment methods. What I would add is a `requirement` field that takes a `Thing` as object. 
I would give the example of the a creditCard requirement the following way:

```
{
  "@context": "https://schema.org",
  "@type": "MemberProgramTier",
  "hasTierRequirement": "https:/schema.org/TierCreditCardRequired"
  "requirement": {
     "@type": "CreditCard",
     "name": "FoozleCredit"
  }
 }
``` 

For other values of `TierRequirementEnumeration` the `requirement` field could be the price.

**Comment by alex-jansen** [comment]
Makes sense. Published an updated [test site]( https://1-dot-schema-experiment.uc.r.appspot.com/MemberProgram). 

Summary:
- Added new `program` property for use on [`ProgramMembership`](https://schema.org/MemberProgram).
- Added existing property [`hostingOrganization`](https://schema.org/hostingOrganization) for use on `MemberProgram`.
- Removed the enumeration of Tier requirements and simply added a new property `hasTierRequirement` with various ranges (including [`CreditCard`](https://schema.org/CreditCard)) to express the requirement for a membership tier. `Thing` might be too generic so I suggest to start with a specific set of range types, and we can always generalize to `Thing` if needed in the future.

PTAL.

**Comment by alex-jansen** [comment]
part of release 28.0
