### ISSUE TITLE
account_linking_family_map_data

### ISSUE THREAD

**Issue by qvvp1** [schemaorg/schemaorg#3573]
`{"4146943139":"{\"user_id\":\"4146943139\",\"type\":\"unlinked_account\",\"account\":{\"about_your_account_bloks_entrypoint_enabled\":true,\"account_badges\":[],\"account_category\":\"\",\"account_type\":2,\"active_standalone_fundraisers\":{\"fundraisers\":[],\"total_count\":0},\"additional_business_addresses\":[],\"address_street\":\"\",\"ads_page_id\":\"135408941328330\",\"ads_page_name\":\"تركيب مظلات\",\"aggregate_promote_engagement\":true,\"allow_automatic_previews_setting\":true,\"allow_mention_setting\":\"everyone\",\"allow_tag_setting\":\"everyone\",\"allowed_commenter_type\":\"any\",\"audio_go_dark_events\":[],\"auto_expand_chaining\":false,\"avatar_status\":{\"has_avatar\":false},\"badge_count\":0,\"besties_count\":0,\"bio_links\":[{\"click_id\":\"PAZXh0bgNhZW0CMTEAAaZGa5SsFKVa2xz78ExyM2ruPruNO3xnTW37UK0BjcbNO8I7AmvIpEEbENA_aem_ccsIohFKK2RxxEH5d1X2Ww\",\"image_url\":\"\",\"is_pinned\":false,\"is_verified\":false,\"link_id\":\"18000753815053903\",\"link_type\":\"external\",\"lynx_url\":\"https:\/\/l.instagram.com\/?u=https%3A%2F%2Fapi.whatsapp.com%2Fsend%3Fphone%3D96893607729%26app%3Dinstagram%26fbclid%3DPAZXh0bgNhZW0CMTEAAaZGa5SsFKVa2xz78ExyM2ruPruNO3xnTW37UK0BjcbNO8I7AmvIpEEbENA_aem_ccsIohFKK2RxxEH5d1X2Ww&e=AT1WL16NtwkY2TAbZ6mP2MeKpSKMoDawdsbTQrYH_jaojPI4O0LCzmakZ8iia7NxrURpdfFvVwdg7d7oWqPrFajUMnUODvUga0SiEg\",\"open_external_url_with_in_app_browser\":true,\"title\":\"الواتساب\",\"url\":\"https:\/\/api.whatsapp.com\/send?phone=96893607729&app=instagram\"}],\"biography\":\"ورشه حدادة والالمنيوم مظلات سيارات مظلات جلسات بجميع اشكالها تفصيل ابواب وشبابيك حسب الطلب وهناجر مستودعات للاستفسار  التواصل على93607729 رابط واتساب⬇\",\"biography_with_entities\":{\"entities\":[],\"raw_text\":\"ورشه حدادة والالمنيوم مظلات سيارات مظلات جلسات بجميع اشكالها تفصيل ابواب وشبابيك حسب الطلب وهناجر مستودعات للاستفسار  التواصل على93607729 رابط واتساب⬇\"},\"birthday_today_visibility_for_viewer\":\"NOT_VISIBLE\",\"break_reminder_interval\":0,\"business_contact_method\":\"CALL\",\"can_be_tagged_as_sponsor\":true,\"can_boost_post\":true,\"can_claim_page\":false,\"can_convert_to_business\":false,\"can_create_new_standalone_personal_fundraiser\":true,\"can_create_sponsor_tags\":true,\"can_crosspost_without_fb_token\":true,\"can_follow_hashtag\":true,\"can_merchant_use_shop_management\":false,\"can_see_organic_insights\":true,\"can_tag_products_from_merchants\":false,\"can_use_branded_content_discovery_as_brand\":false,\"can_use_branded_content_discovery_as_creator\":false,\"can_use_paid_partnership_messaging_as_creator\":false,\"category\":\"منتج\/خدمة\",\"category_id\":\"2201\",\"chaining_upsell_cards\":[],\"charity_profile_fundraiser_info\":{\"consumption_sheet_config\":{\"can_viewer_donate\":false,\"donation_amount_config\":{\"default_selected_donation_value\":0,\"donation_amount_selector_values\":[],\"maximum_donation_amount\":0,\"minimum_donation_amount\":0,\"prefill_amount\":0},\"donation_disabled_message\":\"لدينا مشكلة في الاتصال الآن. يرجى محاولة إجراء تبرعك في وقت آخر.\",\"has_viewer_donated\":false},\"has_active_fundraiser\":false,\"is_facebook_onboarded_charity\":false,\"pk\":\"4146943139\"},\"city_id\":\"107886405900343\",\"city_name\":\"Muscat, Oman\",\"contact_phone_number\":\"+96893607729\",\"creator_info\":{\"creator_segmentation\":\"unknown\",\"is_creator\":false},\"creators_subscribed_to_count\":0,\"daily_time_limit\":0,\"displayed_action_button_type\":\"\",\"eligible_catalog_management_entrypoints\":[],\"eligible_for_text_app_activation_badge\":false,\"eligible_shopping_formats\":[],\"eligible_shopping_signup_entrypoints\":[],\"enable_add_school_in_edit_profile\":false,\"existing_user_age_collection_enabled\":true,\"external_lynx_url\":\"https:\/\/l.instagram.com\/?u=https%3A%2F%2Fapi.whatsapp.com%2Fsend%3Fphone%3D96893607729%26app%3Dinstagram%26fbclid%3DPAZXh0bgNhZW0CMTEAAaYToAFBU6zs_n8J5KmuAcMhdyv1UYd1tdysXZ7guZnpFR72eZd0lM59miI_aem_A9p5Qy7aa0fsOYRmCGe42w&e=AT3c2e44DM0UlAXwg-CiLbbMu_Bw92-KxDFU7K2_z3j5bHw7MB2tIysn8Lwvj8CmvUGlV5sPXcLjmUCJ1J-Wns0s5fowdjsaMsVbmg\",\"external_url\":\"https:\/\/api.whatsapp.com\/send?phone=96893607729&app=instagram\",\"fan_club_info\":{},\"fb_page_call_to_action_id\":\"\",\"fbid_v2\":\"17841404294178367\",\"follow_friction_type\":0,\"follow_status_enum\":\"FollowStatusUnknown\",\"follower_count\":20124,\"following_count\":4493,\"friendship_status\":{\"blocking\":false,\"followed_by\":false,\"is_blocking_reel\":false,\"is_private\":false},\"full_name\":\"مظلات سيارات مظلات جلسات مسقط\",\"has_active_charity_business_profile_fundraiser\":false,\"has_anonymous_profile_picture\":false,\"has_chaining\":true,\"has_collab_collections\":false,\"has_disallowed_media_notes_reshare\":false,\"has_eligible_whatsapp_linking_category\":true,\"has_exclusive_feed_content\":false,\"has_fan_club_subscriptions\":false,\"has_guides\":false,\"has_highlight_reels\":true,\"has_ig_profile\":true,\"has_music_on_profile\":false,\"has_onboarded_to_text_post_app\":true,\"has_placed_orders\":false,\"has_private_collections\":false,\"has_saved_items\":true,\"has_user_ever_set_break\":false,\"has_videos\":false,\"hd_profile_pic_url_info\":{\"height\":963,\"url\":\"https:\/\/instagram.fsah1-1.fna.fbcdn.net\/v\/t51.2885-19\/357296102_149887148057192_4882095301815923338_n.jpg?_nc_ht=instagram.fsah1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=7HcUeedLrdcQ7kNvgHXAifV&edm=AEF8tYYBAAAA&ccb=7-5&oh=00_AYDIa89w4FAsyskC0cOHlLCL3JomD7IApTxgt3AbmO__rQ&oe=66A6AE3E&_nc_sid=1e20d2\",\"width\":963},\"highlights_tray_type\":\"DEFAULT\",\"id\":\"4146943139\",\"instagram_location_id\":\"\",\"interop_messaging_user_fbid\":\"112571080133060\",\"is_aggregated_time_tracking_enabled\":false,\"is_allowed_to_create_standalone_nonprofit_fundraisers\":false,\"is_api_user\":false,\"is_armadillo_message_request_eligible\":false,\"is_auto_highlight_enabled\":false,\"is_business\":true,\"is_call_to_action_enabled\":false,\"is_category_tappable\":true,\"is_creator_agent_enabled\":false,\"is_eligible_for_lead_center\":true,\"is_eligible_for_meta_verified_enhanced_link_sheet\":false,\"is_eligible_for_meta_verified_enhanced_link_sheet_consumption\":false,\"is_eligible_for_meta_verified_label\":true,\"is_eligible_for_meta_verified_links_in_reels\":true,\"is_eligible_for_meta_verified_multiple_addresses_consumption\":false,\"is_eligible_for_meta_verified_multiple_addresses_creation\":false,\"is_eligible_for_meta_verified_related_accounts\":false,\"is_eligible_for_product_tagging_null_state\":false,\"is_eligible_for_smb_support_flow\":true,\"is_eligible_to_show_fb_cross_sharing_nux\":true,\"is_epd\":false,\"is_facebook_friend\":false,\"is_facebook_onboarded_charity\":false,\"is_following_current_user\":false,\"is_hide_more_comment_enabled\":false,\"is_hiding_stories_from_someone\":true,\"is_igd_product_picker_enabled\":false,\"is_in_canada\":false,\"is_interest_account\":true,\"is_memorialized\":false,\"is_meta_ai_bot\":false,\"is_meta_verified_related_accounts_display_enabled\":false,\"is_muted_words_custom_enabled\":false,\"is_muted_words_global_enabled\":false,\"is_muted_words_spamscam_enabled\":false,\"is_new_to_instagram\":false,\"is_new_to_instagram_30d\":false,\"is_open_to_collab\":false,\"is_parenting_account\":false,\"is_private\":false,\"is_profile_action_needed\":false,\"is_profile_audio_call_enabled\":false,\"is_profile_broadcast_sharing_enabled\":true,\"is_profile_picture_expansion_enabled\":true,\"is_quiet_mode_enabled\":false,\"is_recon_ad_cta_on_profile_eligible_with_viewer\":true,\"is_regulated_c18\":false,\"is_regulated_news_in_viewer_location\":false,\"is_remix_setting_enabled_for_posts\":true,\"is_remix_setting_enabled_for_reels\":true,\"is_secondary_account_creation\":false,\"is_shopping_auto_highlight_eligible\":false,\"is_shopping_catalog_source_selection_enabled\":false,\"is_shopping_community_content_enabled\":false,\"is_shopping_revoked_for_seller\":false,\"is_shopping_settings_enabled\":false,\"is_stories_teaser_muted\":false,\"is_supervision_features_enabled\":true,\"is_tooltip_disabled_param\":false,\"is_unpublished\":false,\"is_verified\":false,\"is_whatsapp_linked\":true,\"last_follow_status\":\"FollowStatusUnknown\",\"last_seen_timezone\":\"\",\"latest_besties_reel_media\":0,\"latest_reel_media\":0,\"latitude\":23.61523,\"lead_details_app_id\":\"com.bloks.www.ig.smb.lead_gen.subpage\",\"liked_clips_count\":330,\"limited_interactions_enabled\":false,\"longitude\":58.59126,\"media_count\":342,\"merchant_checkout_style\":\"none\",\"meta_verified_related_accounts_count\":0,\"nametag\":{\"background_image_url\":\"\",\"emoji\":\"😀\",\"emoji_color\":-3384576,\"gradient\":0,\"mode\":1,\"selfie_sticker\":0,\"selfie_url\":\"\"},\"num_of_admined_pages\":0,\"open_external_url_with_in_app_browser\":true,\"page_id\":\"135408941328330\",\"page_name\":\"تركيب مظلات\",\"pinned_channels_info\":{\"has_public_channels\":true,\"pinned_channels_list\":[{\"creator_broadcast_chat_thread_preview_response\":{\"audience_type\":0,\"is_added_to_inbox\":true,\"is_collaborator\":false,\"is_follower\":false,\"is_invited_collaborator\":false,\"is_subscriber\":false},\"creator_username\":\"oman_5_8\",\"group_image_background_uri\":\"\",\"group_image_uri\":\"https:\/\/scontent.cdninstagram.com\/v\/t51.2885-19\/357296102_149887148057192_4882095301815923338_n.jpg?stp=dst-jpg_s200x200&_nc_cat=107&ccb=1-7&_nc_sid=3fd06f&_nc_ohc=CtAFD1us1WMQ7kNvgGiEpWj&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.cdninstagram.com&oh=00_AYA4FtzIsuwPVIz8Aw5Kzu7FI-mjdBAReDtX1jErjCZ3Og&oe=66A6AE3E\",\"invite_link\":\"https:\/\/ig.me\/j\/AbYueAMi5O5Y3D5E\/\",\"is_creator_verified\":false,\"is_member\":true,\"number_of_members\":5,\"should_badge_channel\":false,\"subtitle\":\"قناة رسائل جماعية • ‏٥‏ من الأعضاء\",\"thread_igid\":\"340282366841710301281178085348483570440\",\"thread_subtype\":29,\"title\":\"مظلات مسقط  مظلات سيارات مسقط مظلات جلسات  غرف زجاجيه  مظلات مدارس لتواصل ج\/ 93607729\"}]},\"pk\":\"4146943139\",\"pk_id\":\"4146943139\",\"primary_profile_link_type\":\"0\",\"profile_pic_id\":\"3136303270309313999_4146943139\",\"profile_pic_url\":\"https:\/\/instagram.fsah1-1.fna.fbcdn.net\/v\/t51.2885-19\/357296102_149887148057192_4882095301815923338_n.jpg?stp=dst-jpg_e0_s150x150&_nc_ht=instagram.fsah1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=7HcUeedLrdcQ7kNvgHXAifV&edm=AHBgTAQBAAAA&ccb=7-5&oh=00_AYALJiBvNjKBuXdKYerNn4WypaS6ygAVETgNxJiJPpjbbA&oe=66A6AE3E&_nc_sid=21e75c\",\"pronouns\":[],\"public_email\":\"\",\"public_phone_country_code\":\"968\",\"public_phone_number\":\"93607729\",\"recon_features\":{\"enable_recon_cta\":true},\"reel_auto_archive\":\"off\",\"relevant_news_regulation_locations\":[],\"request_contact_enabled\":true,\"restriction_type\":0,\"seller_shoppable_feed_type\":\"none\",\"shop_management_access_state\":\"none\",\"shopping_onboarding_state\":\"not_started\",\"should_show_category\":true,\"should_show_public_contacts\":true,\"show_account_transparency_details\":true,\"show_besties_badge\":true,\"show_conversion_edit_entry\":false,\"show_fb_link_on_profile\":false,\"show_fb_page_link_on_profile\":false,\"show_ig_app_switcher_badge\":true,\"show_insights_terms\":false,\"show_shoppable_feed\":false,\"show_text_post_app_badge\":true,\"show_text_post_app_switcher_badge\":true,\"spam_follower_setting_enabled\":true,\"strong_id__\":\"4146943139\",\"supervision_info\":{\"daily_time_limit_without_extensions_seconds\":0,\"fc_url\":\"https:\/\/familycenter.instagram.com\/dashboard\/\",\"has_guardian\":false,\"has_stated_age\":true,\"is_blocked_list_enabled\":false,\"is_daily_limit_non_blocking\":false,\"is_eligible_for_supervision\":false,\"is_guardian_of_viewer\":false,\"is_guardian_user\":false,\"is_quiet_time_feature_enabled\":false,\"is_quiet_time_non_blocking\":false,\"is_supervised_by_viewer\":false,\"is_supervised_or_in_cooldown\":false,\"is_supervised_user\":false,\"screen_time_daily_limit_seconds\":0},\"text_app_auto_archive_setting\":\"DEFAULT_NEVER\",\"text_app_last_visited_time\":0,\"text_post_app_badge_label\":\"oman_5_8\",\"text_post_app_has_fediverse_enabled\":false,\"text_post_app_joiner_number_label\":\"+100 مليون\",\"text_post_app_take_a_break_setting\":0,\"third_party_downloads_enabled\":\"1\",\"total_ar_effects\":0,\"total_clips_count\":167,\"total_igtv_videos\":0,\"transparency_product_enabled\":false,\"trial_clips_enabled\":false,\"upcoming_events\":[],\"user_id\":\"4146943139\",\"username\":\"oman_5_8\",\"usertag_review_enabled\":false,\"wa_addressable\":true,\"wa_eligibility\":0,\"whatsapp_number\":\"+96893607729\",\"zip\":\"\"},\"main_accounts\":[],\"child_accounts\":[]}"}`

**Comment by qvvp1** [comment]
@qvvp1

**Comment by cklim0815is** [comment]
> `{"4146943139":"{\"user_id\":\"4146943139\",\"type\":\"unlinked_account\",\"account\":{\"about_your_account_bloks_entrypoint_enabled\":true,\"account_badges\":[],\"account_category\":\"\",\"account_type\":2,\"active_standalone_fundraisers\":{\"fundraisers\":[],\"total_count\":0},\"additional_business_addresses\":[],\"address_street\":\"\",\"ads_page_id\":\"135408941328330\",\"ads_page_name\":\"تركيب مظلات\",\"aggregate_promote_engagement\":true,\"allow_automatic_previews_setting\":true,\"allow_mention_setting\":\"everyone\",\"allow_tag_setting\":\"everyone\",\"allowed_commenter_type\":\"any\",\"audio_go_dark_events\":[],\"auto_expand_chaining\":false,\"avatar_status\":{\"has_avatar\":false},\"badge_count\":0,\"besties_count\":0,\"bio_links\":[{\"click_id\":\"PAZXh0bgNhZW0CMTEAAaZGa5SsFKVa2xz78ExyM2ruPruNO3xnTW37UK0BjcbNO8I7AmvIpEEbENA_aem_ccsIohFKK2RxxEH5d1X2Ww\",\"image_url\":\"\",\"is_pinned\":false,\"is_verified\":false,\"link_id\":\"18000753815053903\",\"link_type\":\"external\",\"lynx_url\":\"https:\/\/l.instagram.com\/?u=https%3A%2F%2Fapi.whatsapp.com%2Fsend%3Fphone%3D96893607729%26app%3Dinstagram%26fbclid%3DPAZXh0bgNhZW0CMTEAAaZGa5SsFKVa2xz78ExyM2ruPruNO3xnTW37UK0BjcbNO8I7AmvIpEEbENA_aem_ccsIohFKK2RxxEH5d1X2Ww&e=AT1WL16NtwkY2TAbZ6mP2MeKpSKMoDawdsbTQrYH_jaojPI4O0LCzmakZ8iia7NxrURpdfFvVwdg7d7oWqPrFajUMnUODvUga0SiEg\",\"open_external_url_with_in_app_browser\":true,\"title\":\"الواتساب\",\"url\":\"https:\/\/api.whatsapp.com\/send?phone=96893607729&app=instagram\"}],\"biography\":\"ورشه حدادة والالمنيوم مظلات سيارات مظلات جلسات بجميع اشكالها تفصيل ابواب وشبابيك حسب الطلب وهناجر مستودعات للاستفسار  التواصل على93607729 رابط واتساب⬇\",\"biography_with_entities\":{\"entities\":[],\"raw_text\":\"ورشه حدادة والالمنيوم مظلات سيارات مظلات جلسات بجميع اشكالها تفصيل ابواب وشبابيك حسب الطلب وهناجر مستودعات للاستفسار  التواصل على93607729 رابط واتساب⬇\"},\"birthday_today_visibility_for_viewer\":\"NOT_VISIBLE\",\"break_reminder_interval\":0,\"business_contact_method\":\"CALL\",\"can_be_tagged_as_sponsor\":true,\"can_boost_post\":true,\"can_claim_page\":false,\"can_convert_to_business\":false,\"can_create_new_standalone_personal_fundraiser\":true,\"can_create_sponsor_tags\":true,\"can_crosspost_without_fb_token\":true,\"can_follow_hashtag\":true,\"can_merchant_use_shop_management\":false,\"can_see_organic_insights\":true,\"can_tag_products_from_merchants\":false,\"can_use_branded_content_discovery_as_brand\":false,\"can_use_branded_content_discovery_as_creator\":false,\"can_use_paid_partnership_messaging_as_creator\":false,\"category\":\"منتج\/خدمة\",\"category_id\":\"2201\",\"chaining_upsell_cards\":[],\"charity_profile_fundraiser_info\":{\"consumption_sheet_config\":{\"can_viewer_donate\":false,\"donation_amount_config\":{\"default_selected_donation_value\":0,\"donation_amount_selector_values\":[],\"maximum_donation_amount\":0,\"minimum_donation_amount\":0,\"prefill_amount\":0},\"donation_disabled_message\":\"لدينا مشكلة في الاتصال الآن. يرجى محاولة إجراء تبرعك في وقت آخر.\",\"has_viewer_donated\":false},\"has_active_fundraiser\":false,\"is_facebook_onboarded_charity\":false,\"pk\":\"4146943139\"},\"city_id\":\"107886405900343\",\"city_name\":\"Muscat, Oman\",\"contact_phone_number\":\"+96893607729\",\"creator_info\":{\"creator_segmentation\":\"unknown\",\"is_creator\":false},\"creators_subscribed_to_count\":0,\"daily_time_limit\":0,\"displayed_action_button_type\":\"\",\"eligible_catalog_management_entrypoints\":[],\"eligible_for_text_app_activation_badge\":false,\"eligible_shopping_formats\":[],\"eligible_shopping_signup_entrypoints\":[],\"enable_add_school_in_edit_profile\":false,\"existing_user_age_collection_enabled\":true,\"external_lynx_url\":\"https:\/\/l.instagram.com\/?u=https%3A%2F%2Fapi.whatsapp.com%2Fsend%3Fphone%3D96893607729%26app%3Dinstagram%26fbclid%3DPAZXh0bgNhZW0CMTEAAaYToAFBU6zs_n8J5KmuAcMhdyv1UYd1tdysXZ7guZnpFR72eZd0lM59miI_aem_A9p5Qy7aa0fsOYRmCGe42w&e=AT3c2e44DM0UlAXwg-CiLbbMu_Bw92-KxDFU7K2_z3j5bHw7MB2tIysn8Lwvj8CmvUGlV5sPXcLjmUCJ1J-Wns0s5fowdjsaMsVbmg\",\"external_url\":\"https:\/\/api.whatsapp.com\/send?phone=96893607729&app=instagram\",\"fan_club_info\":{},\"fb_page_call_to_action_id\":\"\",\"fbid_v2\":\"17841404294178367\",\"follow_friction_type\":0,\"follow_status_enum\":\"FollowStatusUnknown\",\"follower_count\":20124,\"following_count\":4493,\"friendship_status\":{\"blocking\":false,\"followed_by\":false,\"is_blocking_reel\":false,\"is_private\":false},\"full_name\":\"مظلات سيارات مظلات جلسات مسقط\",\"has_active_charity_business_profile_fundraiser\":false,\"has_anonymous_profile_picture\":false,\"has_chaining\":true,\"has_collab_collections\":false,\"has_disallowed_media_notes_reshare\":false,\"has_eligible_whatsapp_linking_category\":true,\"has_exclusive_feed_content\":false,\"has_fan_club_subscriptions\":false,\"has_guides\":false,\"has_highlight_reels\":true,\"has_ig_profile\":true,\"has_music_on_profile\":false,\"has_onboarded_to_text_post_app\":true,\"has_placed_orders\":false,\"has_private_collections\":false,\"has_saved_items\":true,\"has_user_ever_set_break\":false,\"has_videos\":false,\"hd_profile_pic_url_info\":{\"height\":963,\"url\":\"https:\/\/instagram.fsah1-1.fna.fbcdn.net\/v\/t51.2885-19\/357296102_149887148057192_4882095301815923338_n.jpg?_nc_ht=instagram.fsah1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=7HcUeedLrdcQ7kNvgHXAifV&edm=AEF8tYYBAAAA&ccb=7-5&oh=00_AYDIa89w4FAsyskC0cOHlLCL3JomD7IApTxgt3AbmO__rQ&oe=66A6AE3E&_nc_sid=1e20d2\",\"width\":963},\"highlights_tray_type\":\"DEFAULT\",\"id\":\"4146943139\",\"instagram_location_id\":\"\",\"interop_messaging_user_fbid\":\"112571080133060\",\"is_aggregated_time_tracking_enabled\":false,\"is_allowed_to_create_standalone_nonprofit_fundraisers\":false,\"is_api_user\":false,\"is_armadillo_message_request_eligible\":false,\"is_auto_highlight_enabled\":false,\"is_business\":true,\"is_call_to_action_enabled\":false,\"is_category_tappable\":true,\"is_creator_agent_enabled\":false,\"is_eligible_for_lead_center\":true,\"is_eligible_for_meta_verified_enhanced_link_sheet\":false,\"is_eligible_for_meta_verified_enhanced_link_sheet_consumption\":false,\"is_eligible_for_meta_verified_label\":true,\"is_eligible_for_meta_verified_links_in_reels\":true,\"is_eligible_for_meta_verified_multiple_addresses_consumption\":false,\"is_eligible_for_meta_verified_multiple_addresses_creation\":false,\"is_eligible_for_meta_verified_related_accounts\":false,\"is_eligible_for_product_tagging_null_state\":false,\"is_eligible_for_smb_support_flow\":true,\"is_eligible_to_show_fb_cross_sharing_nux\":true,\"is_epd\":false,\"is_facebook_friend\":false,\"is_facebook_onboarded_charity\":false,\"is_following_current_user\":false,\"is_hide_more_comment_enabled\":false,\"is_hiding_stories_from_someone\":true,\"is_igd_product_picker_enabled\":false,\"is_in_canada\":false,\"is_interest_account\":true,\"is_memorialized\":false,\"is_meta_ai_bot\":false,\"is_meta_verified_related_accounts_display_enabled\":false,\"is_muted_words_custom_enabled\":false,\"is_muted_words_global_enabled\":false,\"is_muted_words_spamscam_enabled\":false,\"is_new_to_instagram\":false,\"is_new_to_instagram_30d\":false,\"is_open_to_collab\":false,\"is_parenting_account\":false,\"is_private\":false,\"is_profile_action_needed\":false,\"is_profile_audio_call_enabled\":false,\"is_profile_broadcast_sharing_enabled\":true,\"is_profile_picture_expansion_enabled\":true,\"is_quiet_mode_enabled\":false,\"is_recon_ad_cta_on_profile_eligible_with_viewer\":true,\"is_regulated_c18\":false,\"is_regulated_news_in_viewer_location\":false,\"is_remix_setting_enabled_for_posts\":true,\"is_remix_setting_enabled_for_reels\":true,\"is_secondary_account_creation\":false,\"is_shopping_auto_highlight_eligible\":false,\"is_shopping_catalog_source_selection_enabled\":false,\"is_shopping_community_content_enabled\":false,\"is_shopping_revoked_for_seller\":false,\"is_shopping_settings_enabled\":false,\"is_stories_teaser_muted\":false,\"is_supervision_features_enabled\":true,\"is_tooltip_disabled_param\":false,\"is_unpublished\":false,\"is_verified\":false,\"is_whatsapp_linked\":true,\"last_follow_status\":\"FollowStatusUnknown\",\"last_seen_timezone\":\"\",\"latest_besties_reel_media\":0,\"latest_reel_media\":0,\"latitude\":23.61523,\"lead_details_app_id\":\"com.bloks.www.ig.smb.lead_gen.subpage\",\"liked_clips_count\":330,\"limited_interactions_enabled\":false,\"longitude\":58.59126,\"media_count\":342,\"merchant_checkout_style\":\"none\",\"meta_verified_related_accounts_count\":0,\"nametag\":{\"background_image_url\":\"\",\"emoji\":\"😀\",\"emoji_color\":-3384576,\"gradient\":0,\"mode\":1,\"selfie_sticker\":0,\"selfie_url\":\"\"},\"num_of_admined_pages\":0,\"open_external_url_with_in_app_browser\":true,\"page_id\":\"135408941328330\",\"page_name\":\"تركيب مظلات\",\"pinned_channels_info\":{\"has_public_channels\":true,\"pinned_channels_list\":[{\"creator_broadcast_chat_thread_preview_response\":{\"audience_type\":0,\"is_added_to_inbox\":true,\"is_collaborator\":false,\"is_follower\":false,\"is_invited_collaborator\":false,\"is_subscriber\":false},\"creator_username\":\"oman_5_8\",\"group_image_background_uri\":\"\",\"group_image_uri\":\"https:\/\/scontent.cdninstagram.com\/v\/t51.2885-19\/357296102_149887148057192_4882095301815923338_n.jpg?stp=dst-jpg_s200x200&_nc_cat=107&ccb=1-7&_nc_sid=3fd06f&_nc_ohc=CtAFD1us1WMQ7kNvgGiEpWj&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.cdninstagram.com&oh=00_AYA4FtzIsuwPVIz8Aw5Kzu7FI-mjdBAReDtX1jErjCZ3Og&oe=66A6AE3E\",\"invite_link\":\"https:\/\/ig.me\/j\/AbYueAMi5O5Y3D5E\/\",\"is_creator_verified\":false,\"is_member\":true,\"number_of_members\":5,\"should_badge_channel\":false,\"subtitle\":\"قناة رسائل جماعية • ‏٥‏ من الأعضاء\",\"thread_igid\":\"340282366841710301281178085348483570440\",\"thread_subtype\":29,\"title\":\"مظلات مسقط  مظلات سيارات مسقط مظلات جلسات  غرف زجاجيه  مظلات مدارس لتواصل ج\/ 93607729\"}]},\"pk\":\"4146943139\",\"pk_id\":\"4146943139\",\"primary_profile_link_type\":\"0\",\"profile_pic_id\":\"3136303270309313999_4146943139\",\"profile_pic_url\":\"https:\/\/instagram.fsah1-1.fna.fbcdn.net\/v\/t51.2885-19\/357296102_149887148057192_4882095301815923338_n.jpg?stp=dst-jpg_e0_s150x150&_nc_ht=instagram.fsah1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=7HcUeedLrdcQ7kNvgHXAifV&edm=AHBgTAQBAAAA&ccb=7-5&oh=00_AYALJiBvNjKBuXdKYerNn4WypaS6ygAVETgNxJiJPpjbbA&oe=66A6AE3E&_nc_sid=21e75c\",\"pronouns\":[],\"public_email\":\"\",\"public_phone_country_code\":\"968\",\"public_phone_number\":\"93607729\",\"recon_features\":{\"enable_recon_cta\":true},\"reel_auto_archive\":\"off\",\"relevant_news_regulation_locations\":[],\"request_contact_enabled\":true,\"restriction_type\":0,\"seller_shoppable_feed_type\":\"none\",\"shop_management_access_state\":\"none\",\"shopping_onboarding_state\":\"not_started\",\"should_show_category\":true,\"should_show_public_contacts\":true,\"show_account_transparency_details\":true,\"show_besties_badge\":true,\"show_conversion_edit_entry\":false,\"show_fb_link_on_profile\":false,\"show_fb_page_link_on_profile\":false,\"show_ig_app_switcher_badge\":true,\"show_insights_terms\":false,\"show_shoppable_feed\":false,\"show_text_post_app_badge\":true,\"show_text_post_app_switcher_badge\":true,\"spam_follower_setting_enabled\":true,\"strong_id__\":\"4146943139\",\"supervision_info\":{\"daily_time_limit_without_extensions_seconds\":0,\"fc_url\":\"https:\/\/familycenter.instagram.com\/dashboard\/\",\"has_guardian\":false,\"has_stated_age\":true,\"is_blocked_list_enabled\":false,\"is_daily_limit_non_blocking\":false,\"is_eligible_for_supervision\":false,\"is_guardian_of_viewer\":false,\"is_guardian_user\":false,\"is_quiet_time_feature_enabled\":false,\"is_quiet_time_non_blocking\":false,\"is_supervised_by_viewer\":false,\"is_supervised_or_in_cooldown\":false,\"is_supervised_user\":false,\"screen_time_daily_limit_seconds\":0},\"text_app_auto_archive_setting\":\"DEFAULT_NEVER\",\"text_app_last_visited_time\":0,\"text_post_app_badge_label\":\"oman_5_8\",\"text_post_app_has_fediverse_enabled\":false,\"text_post_app_joiner_number_label\":\"+100 مليون\",\"text_post_app_take_a_break_setting\":0,\"third_party_downloads_enabled\":\"1\",\"total_ar_effects\":0,\"total_clips_count\":167,\"total_igtv_videos\":0,\"transparency_product_enabled\":false,\"trial_clips_enabled\":false,\"upcoming_events\":[],\"user_id\":\"4146943139\",\"username\":\"oman_5_8\",\"usertag_review_enabled\":false,\"wa_addressable\":true,\"wa_eligibility\":0,\"whatsapp_number\":\"+96893607729\",\"zip\":\"\"},\"main_accounts\":[],\"child_accounts\":[]}"}`

**Comment by MatthiasWiesmann** [comment]
Gibberish, closing.
