### ISSUE TITLE
Proposal: "Reserved" enumeration for ItemAvailability

### ISSUE THREAD

**Issue by shakyjake** [schemaorg/schemaorg#3581]
Hiya,

Got a client who sells a lot of one-off, big-ticket items where prices are negotiated with prospective buyers and products are unavailable to others while negotiations are ongoing. It would be nice to have a `Reserved` enumeration for such situations. It could also be useful for situations like event ticketing, auctions or cinema seating.

My current strategy is to use `SoldOut` then switch back to `InStock` if an agreement isn't reached, which feels a bit wrong. `Reserved` would more accurately describe the current status of the item and the possibility of it becoming available again in the future.

**Comment by alex-jansen** [comment]
Seems reasonable, we could add `Reserved` together with `MadeToOrder` as proposed in #3183 (which also seems related to #2926)

**Comment by MatthiasWiesmann** [comment]
What about https://github.com/schemaorg/schemaorg/issues/3559

**Comment by alex-jansen** [comment]
#3559 seems very similar (or identical) to #3813, so we could close that at the same time?

**Comment by alex-jansen** [comment]
This was [added](https://schema.org/Reserved) as part of Release 28.0
