### ISSUE TITLE
Website: Bad link to terms and conditions from about page

### ISSUE THREAD

**Issue by simply-raytellis** [schemaorg/schemaorg#3585]
The "Terms and conditions" link in the footer of the About page (https://schema.org/docs/terms.html) points to the bad link https://schema.org/docs/%7B%7Bdocsdir%7D%7D/terms.html, which gives a 404 error. The correct link (https://schema.org/docs/terms.html) is present on the homepage. I've not checked any other pages to see if this issue exists on other pages.

**Comment by MatthiasWiesmann** [comment]
This affects all html files in the docs directory.

**Comment by MatthiasWiesmann** [comment]
Fixed was merged: https://github.com/schemaorg/schemaorg/pull/3601
