### ISSUE TITLE
rdfs:comment encoding... Need quotation rules?

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#359]
The `rdfs:comment` content, when representated in DOM ([libxml2](http://xmlsoft.org/)) lost the `&quot;` and `&#39;` quotation entity-representation, changing them to the UTF8 correspondent chars. 

Can we change this "rule" of [schema_org_rdfa](http://schema.org/docs/schema_org_rdfa.html) representation? Ideal is to use "UTF8 representation" in any element contents.

**Comment by danbri** [comment]
Why?

**Comment by danbri** [comment]
Closing as obsolete (we have moved to [MCF-flavored Turtle](https://docs.google.com/document/d/1xRD59jo76ED-CGT_rGxF2fAeNHMzzdwxyIUZcvq1gB0/edit#heading=h.48w7oopb2aob) for on-disk representation.
