### ISSUE TITLE
Representation of schema_org_rdfa in "canonized" Polyglot HTML5

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#360]
Only to remember that http://schema.org/docs/schema_org_rdfa.html
**is** (or is near to)  a  [Polyglot representation](http://www.w3.org/TR/html-polyglot/)... And we can use this constraint for the future, to avoid any "enhance" that lost this constraint. In other works, 

Suggestion: at github and development assume that is a XHTML5 representation, that is, a polyglot with `MIME text/xml` (**needs** only a XML-utf8 **header**).

---
# Main suggestion

(after check if it is really a polyglot html) to change the introduction,

> Note: the style of RDFa used here may change in the future. To see the substantive content of the schema, view the HTML source markup (it is a valid XHTML5 Polyglot representation). We use a simple subset of RDFa for syntax, including prefixes that are declared in the RDFa initial context.
# Secondary suggestion

Another issue for representation ... Ideal is to use a http://www.w3.org/TR/xml-c14n  (canonized) representation of atributes, spaces, etc. to avoid "false diff" on `diff` analysis.
... Ok, an "Polyglot-canonized", that not lost any Polyglot constraint.

IMPORTANTE EXAMPLE:  the space in the closed tags.. today schema_org_rdfa have a (mess) mix, some with `<tag etc/>` and some with `<tag etc />`.
- With space: `<meta charset="UTF-8" />` , `<link property="owl:equivalentClass" href="http://xmlns.com/foaf/0.1/Person" />`,  `<link property="rdfs:subPropertyOf" href="http://schema.org/location" />`, ... minority,
- Without space: `<link property="owl:equivalentClass" href="http://purl.org/dc/dcmitype/Event"/>`, `<link property="owl:equivalentProperty" href="http://purl.org/dc/terms/description"/>` , `<link property="owl:equivalentClass" href="http://purl.org/ontology/bibo/Periodical"/>`  ... majority.

CHANGES WHEN CANONIZE: sampling some typical changes in attribute order,
-  today is `<div resource="http://schema.org/AboutPage" typeof="rdfs:Class">`, canonized will be `<div typeof="rdfs:Class" resource="http://schema.org/AboutPage">`
- today is `<span>Subclass of: <a property="rdfs:subClassOf" href="http://schema.org/Thing">Thing</a></span>`, canonized will be  `<span>Subclass of: <a href="http://schema.org/Thing" property="rdfs:subClassOf">Thing</a></span>`

---
# Little errors

The version 1.93 at http://schema.org/docs/schema_org_rdfa.html 
have some other little problems... Not a matter of normalization, perhaps validation (we have an _HTML+RDFa_ validator?). 

Here something that is, before, an "HTML4 error":

```
<p>MusicRelease: Thing > CreativeWork > MusicPlaylist >  (...)</p>
```

must be

```
<p>MusicRelease: Thing &gt; CreativeWork &gt; MusicPlaylist &gt; (...) </p>
```

Ortography ("clincalPharmacology" and "clinicalPharmacology") and duplications, example:

```
    <div typeof="rdf:Property" resource="http://schema.org/clinicalPharmacology">
      <span class="h" property="rdfs:label">clinicalPharmacology</span>
      <span property="rdfs:comment">Description of the absorption and elimination of drugs, including their concentration (pharmacokinetics, pK) and biological effects (pharmacodynamics, pD).</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Drug">Drug</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
    </div>

    <div typeof="rdf:Property" resource="http://schema.org/clincalPharmacology"> 
      <span class="h" property="rdfs:label">clinicalPharmacology</span>
      <span property="rdfs:comment">Description of the absorption and elimination of drugs, including their concentration (pharmacokinetics, pK) and biological effects (pharmacodynamics, pD).</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Drug">Drug</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
      <link property="supersededBy" href="http://schema.org/clinicalPharmacology" />
    </div>
```

must be once.

**Comment by ppKrauss** [comment]
Ops, another issue for representation ... Ideal is to use a http://www.w3.org/TR/xml-c14n  (canonized) representation of atributes, spaces, etc. to avoid "false diff" on `diff` analysis.
... Ok, an "Polyglot-canonized", that not lost any Polyglot constraint.

IMPORTANTE EXAMPLE:  the space in the closed tags.. today schema_org_rdfa have a (mess) mix, some with `<tag etc/>` and some with `<tag etc />`.

* With space: `<meta charset="UTF-8" />` , `<link property="owl:equivalentClass" href="http://xmlns.com/foaf/0.1/Person" />`,  `<link property="rdfs:subPropertyOf" href="http://schema.org/location" />`, ... minority,

* Without space: `<link property="owl:equivalentClass" href="http://purl.org/dc/dcmitype/Event"/>`, `<link property="owl:equivalentProperty" href="http://purl.org/dc/terms/description"/>` , `<link property="owl:equivalentClass" href="http://purl.org/ontology/bibo/Periodical"/>`  ... majority.

**Comment by dbs** [comment]
Apart from theoretical purity, what is the actual practical value of striving for "Polyglot HTML5"? Browsers can parse and display the current HTML just fine, and the RDFa can be extracted by RDF parsers such as RDFLib just fine.

Without a compelling reason (and I'm not convinced the possibility of a "false diff" is in any way compelling, even if diff tools didn't have the ability to ignore whitespace), I fear that this issue is just noise that detracts from more substantive concerns around schema.org.

**Comment by ppKrauss** [comment]
@dbs  It is only an internal (use of tolls, etc.) operational problem... of course the objective of the issue is not to "just noise that detracts from more substantive concerns" (!), but, yes, have minor relevance, is a very low priority issue.

As you will be see bellow, it is not a proposal to "fix a bug" but, perhaps, a proposal to say *"hello, the new tools can be work with this kind of output, let's use it??"*.

**Explain the problem:**  ... the first objective of `schema_org_rdfa` is to be read (rendered and source) by any person in any browser... and if you see the HTML-source, it is a kind of HTML5.  

 * "schema_org_rdfa is to the **crown**!" constraints: need preserved as "valid HTML5".

 * "schema_org_rdfa is to the **tools**!" constraints: need to be XML.

 * "schema_org_rdfa is to **`diff`** tools!" constraints: need to be "canonized" (not "full c14n").

So, merging all: it is the proposal. software tools, online robots, etc. need to read and write the schema_org_rdfa **without impact of "little non-expected changes"**.    

I am working now with tools for #280, and I am preparing a software that read and write (modify the original schema_org_rdfa!) without impact... So, in this context, this issue is only a kind of NOTICE about the (possible if the tool used) future schema_org_rdfa representation.

**Comment by chaals** [comment]
+ reply@
- notifications@

I agree it isn't the highest priority issue on the agenda. But I think it would be useful to fix it. 

There are people who use XML toolchains, and since it should be feasible to make schema.org work for them I don't see this as "just noise".

cheers

24.02.2015, 17:30, "Dan Scott" <notifications@github.com>:
> Apart from theoretical purity, what is the actual practical value of striving for "Polyglot HTML5"? Browsers can parse and display the current HTML just fine, and the RDFa can be extracted by RDF parsers such as RDFLib just fine.
>
> Without a compelling reason (and I'm not convinced the possibility of a "false diff" is in any way compelling, even if diff tools didn't have the ability to ignore whitespace), I fear that this issue is just noise that detracts from more substantive concerns around schema.org.
>
> —
> Reply to this email directly or view it on GitHub.

--
Charles McCathie Nevile - web standards - CTO Office, Yandex
chaals@yandex-team.ru - - - Find more at http://yandex.com

**Comment by danbri** [comment]
Thanks for this. In general, schema.org as a project has not aligned itself heavily with XHTML. But the public Web pages have often been polyglot. It is probably taking a bit more care with this, so thanks for the detailed list of issues.

For the data/schema.rdfa file (which gets republished as-is at docs/schema_org_rdfa.html for now) we do already have a basic unit test to ensure that an XML parser can read the file: https://github.com/schemaorg/schemaorg/blob/sdo-gozer/tests/test_basics.py#L85

**Comment by danbri** [comment]
Obsolete (we are moving away from encoding the schemas in RDFa)
