### ISSUE TITLE
Flag CreativeWork version with `isLatest`  

### ISSUE THREAD

**Issue by athalhammer** [schemaorg/schemaorg#3614]
I've been wondering if there is a good way to flag a specific version of a creative work with `"isLatest": true`

**Comment by MatthiasWiesmann** [comment]
I would turn the question around: if you implemented a crawling system, would you believe a page that has annotation that 
`isLatest: True` ? I would not.

A recent `[dateModified](https://schema.org/dateModified)` field would be a much stronger signal, along with a annotations that make the current markup the authoritative one.

**Comment by Tiggerito** [comment]
Would you ever state "isLatest": false on your current content?

The only example I can think of is if you are listing historical versions of content. And that does not seem to be the best way to indicate the order they come in.

**Comment by MatthiasWiesmann** [comment]
> The only example I can think of is if you are listing historical versions of content. And that does not seem to be the best way to indicate the order they come in.

You can use the [version](https://schema.org/version) field to indicate that, as well as the [dateModified](https://schema.org/dateModified) fields.

**Comment by athalhammer** [comment]
hm, it is common practice to have some sort of `https://example.com/my/dataset/latest` that symlinks to `https://example.com/my/dataset/2.0.3` - everyone can sort by date or semantic version but it is this type of "provide some convenience method for my customers (that is not necessarily a symlink and more declarative)" that I'm looking for.

**Comment by athalhammer** [comment]
okay, I figure between

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
SELECT (strbefore(str(max(xsd:dateTime(CONCAT(?mod, "T00:00:00Z")))), "T") as ?latest)
WHERE {
    ?x <http://schema.org/dateModified> ?mod.
```

and 

```
SELECT ?latest
WHERE {
    ?latest <http://schema.org/isLatest> true.
```

there is not that much difference.
