### ISSUE TITLE
Example uses non-existent "Award" type

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#364]
http://schema.org/Award

The example on [`WinAction`](http://schema.org/WinAction) uses an `Award` type, which [doesn’t](http://schema.org/Award) seem to be defined:

>     "@type": "Award",

        
        <script type="application/ld+json">
        {
          "@context": "http://schema.org",
          "@type": "WinAction",
          "agent": {
            "@type": "Person",
            "name": "John"
          },
          "object": {
            "@type": "Award",
            "name": "Nobel prize"
          }
        }
        </script>

**Comment by danbri** [comment]
For this example, anything nice would be a reasonable type. I can't think of a suitable type though! 

How about: John won a book about the Nobel prize?

Not such a big prize, but we have http://schema.org/Book at least!
