### ISSUE TITLE
Link an `Action` to a `HowTo`

### ISSUE THREAD

**Issue by multimeric** [schemaorg/schemaorg#3656]
Oddly, there is no field on `Action` that describes the process being undertaken. `HowTo` fits this niche nicely, and it defines each step of the process. Therefore I propose adding the following to `Action`:

Property | Expected Type | Description
-- | -- | --
`process` | `HowTo` | Description of the process by which the action was performed

**Comment by multimeric** [comment]
Some motivation for this change is BioSchemas, which created a new subtype of `Action` called [`LabProcess`](https://bioschemas.org/types/LabProcess/0.1-DRAFT) that links to a subtype of `HowTo` (called [`LabProtocol`](https://bioschemas.org/types/LabProtocol/0.5-DRAFT)). So the need evidently exists to do this, but I think it makes sense to link them at a lower level (in schema.org).

**Comment by MatthiasWiesmann** [comment]
So your proposal would be to add a `howTo` field on `Action`that points to a `HowTo`?
Do we need to coordinate with the bioSchemas so things don't become weird on their end?

**Comment by multimeric** [comment]
Generally yes. However I'm proposing to call it `process` rather than `howTo`, but I'm open to changing the property name.

This change would make it a tiny bit confusing for bioschemas, but I don't think there's any way around that. This is because their `LabProcess` has a property called `executesLabProtocol` that links to a `LabProtocol`. However this field name is obviously not applicable to a general `Action`. So I think we just make this change, and then propose that bioschemas just use this field instead of their bespoke one.

**Comment by MatthiasWiesmann** [comment]
OK, would you be able to create a pull request for this?

**Comment by multimeric** [comment]
Done.
