### ISSUE TITLE
Inconvenient change to schema:publication

### ISSUE THREAD

**Issue by realworldobject** [schemaorg/schemaorg#366]
I notice that schema:publication has changed in such a way that it raises doubts about use for schema:Book.  I suppose the schema:releasedEvent could be used instead, but it doesn't flow off the tongue and changing it now will be awkward. As a compromise, could you add a few more subclasses of CreativeWork to the list of types where schema:publication seems appropriate?

**Comment by danbri** [comment]
If 'publication' previously had broader semantics, this may be an implementation bug. I forget offhand if the property was added for the TV/radio changes, or existed beforehand. It seems to have been like this for a while e.g. https://web.archive.org/web/20131121225532/http://schema.org/publication ... I'll need to dig around a bit for earlier definitions (and yes, that situation could also be improved). 

It seems reasonable to have a more general sense, given the general name of the property. 

/cc @vholland

**Comment by danbri** [comment]
I suggest "A publication event associated with the item."

Imaginative, I know.

**Comment by realworldobject** [comment]
+1

principle of least astonishment

**Comment by danbri** [comment]
Done & done.

**Comment by Dataliberate** [comment]
As this restores book friendliness - shouldn't we have at least Book or maybe CreativeWork in its domain?

**Comment by danbri** [comment]
I'd support that - it is effectively what the definition now says. Anyone here think otherwise?

**Comment by Dataliberate** [comment]
Domain CreativeWork that is +1

**Comment by danbri** [comment]
CreativeWork. Done.
