### ISSUE TITLE
Notes HTML rendering in Objects is broken 

### ISSUE THREAD

**Issue by MatthiasWiesmann** [schemaorg/schemaorg#3680]
The rendering of notes is broken at head. 

The ackowledgement section of the `Product` page is the following:

```Acknowledgements

GoodRelations Vocabulary Terms
--- AcknowledgementText.md
```

The `AcknowledgementText.md` file should be inlined (and converted from md to html).

**Comment by alex-jansen** [comment]
Fixed with #3681
