### ISSUE TITLE
Person "knows" Thing

### ISSUE THREAD

**Issue by pall-dinamiza** [schemaorg/schemaorg#369]
A Person can know not just other Person, but anything, (for example a Person can know a Language). Knows should be extended to Thing.

**Comment by danbri** [comment]
Thanks for the suggestion. There are as you point out many more senses of "knows" than that currently used in http://schema.org/knows

Broadly, there are various "knowing how" (skill) and "knowing that" (propositional facts) sense of "know" that go beyond the simple social link we're focussed on here. We have no plans to expand "knows" for those, so I'll go ahead and close out this issue. However, representing skills is certainly of interests, and the example (language skills) you give is already tracked as https://github.com/schemaorg/schemaorg/pull/291

(there might also be useful "kinds of knowing", skill descriptions etc. that could be attached to http://schema.org/JobPosting and to learning-related content)

Thanks again...

**Comment by realworldobject** [comment]
Skill descriptions could also be tracked using existing schema:ProfilePage/schema:specialization. For example:

@prefix : <#> .
@prefix entity: <http://www.wikidata.org/entity/> .

:A0
a schema:ProfilePage;
                schema:about entity:Q313758; # Philip Larkin
                schema:speciality entity:Q49757; # poet
                schema:speciality entity: Q182436; # librarian
                .

entity:Q313758
                a schema:Person;
                schema:name “Philip Larkin”;
                .

Jeff
