### ISSUE TITLE
+1 ClosingDaysSpecification Type

### ISSUE THREAD

**Issue by ronanguilloux** [schemaorg/schemaorg#372]
`ClosingDaysSpecification` Type is an additional StructuredValue, counterpart of `OpeningHoursSpecification`.

It scope is to ease the definition of opening/closing periods, as in an annual point of view.

__Proposal / RFC__:

Property | Expected Type | Description | Example
----------- | -------------------- | --------------- | ----------- 
closes | Date | a `Date`or a (collection of) `Date` |  `["2017-05-01", "2017-12-25", "2018-01-01"]`
closeDatesType | Text | a (collection of) HolidayType | `["BankHoliday", "PostalHoliday", "LocalHoliday"]`

This proposal also proposes to create an _HolidayType_, as in http://en.wikipedia.org/wiki/Public_holiday:
- `LocalHoliday` means the legal holiday list that apply in a certain place, as determined by a national/local administration.
- Other holiday types may be defined, as the [Bank Holiday](http://en.wikipedia.org/wiki/Bank_holiday)

**Comment by mfhepp** [comment]
I am not in favor of this approach, because the reasoning about when a shop will be open will become extremely complex. When I designed the OpeningHoursSpecification in GoodRelations, my assumption was that points of sale typically promise when they open, but not, when they close. Already now, the reasoning of whether a point of sale is open or closed can be fairly complex, because you can have seasonal opening hours (via vaidFrom and validThrough), can computing which one is given priority is non-trivial.

If you now add negation, which is pretty much absent from other parts of schema.org so far, the reasoning gets way more complicated than it already is.

**Comment by ronanguilloux** [comment]
Thank you very much for your feedback!

> my assumption was that points of sale typically promise when they open, but not, when they close

Well, this pretty much depend from the country & culture you see it.

Points of sale are far from being the only places to have open/close hours. But, as points of sale typically promise when they open but not when they close, most public buildings do exactly the opposite.

Just think about public buildings (schools, etc.) or public places (parks), civic structures, business centers, residences, landmarks, etc. : In French & Italian contexts (the ones I know the best), most of this places display time panels that are not strict timetables or schedules, but are rather a simple phrase, as "open on working days, [closed on holidays](https://www.google.fr/webhp?q=%22closed+on+holidays%22)" 

Such "holidays" concept may vary from local (regional) school holidays (FR) to Bank Holidays (UK), to Post Office holidays (India), etc.

IMHO, `closes` or `closeDatesType` properties may exactly express such information. I understand that this way to express open/closed periods is maybe not that easy to compute for a machine, but is very easy to declare and to understand, very close to the way it is expressed in natural language, and far less verbose than a timetable of opening periods separated by recurrent holidays.

**Comment by danbri** [comment]
Two thoughts:

* absolutely agree with the use-case, this crops up a lot especially with places of interest like museums who want to say that they're closed during e.g. UK Christmas (or at least some specified dates)
* I share Martin's concern for creeping complexity. We already have to deal with the two different constructions within schema.org - the property http://schema.org/openingHours  and the type (very similarly named), http://schema.org/OpeningHours . 

I'd suggest that collecting some expressive test cases and their encodings would be a good way to start, both for improving consumption of complex markup and for fixing any gaps in expressivity. 

We already have a few issues open on this, so to avoid fragmenting discussion I will close out this proposal from @ronanguilloux and link it from other existing issues.

- https://github.com/schemaorg/schemaorg/issues?q=is%3Aissue+is%3Aopen+openingHours 
- https://github.com/schemaorg/schemaorg/issues/245
- https://github.com/schemaorg/schemaorg/issues/224
- https://github.com/schemaorg/schemaorg/issues/186

**Comment by ronanguilloux** [comment]
Hi @danbri,

> I'd suggest that collecting some expressive test cases and their encodings would be a good way to start, both for improving consumption of complex markup and for fixing any gaps in expressivity.

I started for you a short list, in your online document about museum opening hours : 
https://docs.google.com/document/d/1at0hgbzZIYDppgGudm0EHSV6vpc6OIv_YDAiydWg6aw/edit

Uffizi, Mont-SAint-Michel, Louvre, Guggenheim, British Library, MoMA: Most of these “Hours & admission” museum website pages validate a “simple opening hours + (mostly) holiday-related closing dates list” model.
