### ISSUE TITLE
Add Report under Creative Work  

### ISSUE THREAD

**Issue by jkreft-usgs** [schemaorg/schemaorg#374]
Reports generated by governmental and non-governmental organizations are currently difficult to describe using schema.org, as they aren't a scholarly article, but don't really fit in anywhere else under CreativeWork either.  Report as a type under CreativeWork would give this common publication type an accurate description.  Properties for Report could be similar to that of Article, but would also include the report number, a key piece of metadata to describe reports.
- Report
  - reportBody (Text) The actual body of the report.
  - pagination (Text or Integer) Any description of pages that is not separated into pageStart and pageEnd; for example, "1-6, 9, 55" or "10-12, 46-49".
  - pageStart (Text or Integer) The page on which the work starts; for example "138" or "xvi".
  - pageEnd  (Text or Integer) The page on which the work ends; for example "138" or "xvi".
  - wordCount  (Integer) The number of words in the text of the Report.
  - reportNumber (Text or Integer) The number or other unique designator assigned to the Report by the publishing organization.

This is an example of a report that I am currently struggling to properly describe with schema.org- a Report CreativeWork type would immediately be put to use here:  http://pubs.er.usgs.gov/publication/sir20145235

**Comment by Dataliberate** [comment]
Just an observation but would a Report not be just as well served by being a subtype of Article with one new property ‘reportNumber’.

Thing > CreativeWork > Article > Report

~Richard

On 7 Mar 2015, at 00:35, jkreft-usgs <notifications@github.com<mailto:notifications@github.com>> wrote:


Reports generated by governmental and non-governmental organizations are currently difficult to describe using schema.org<http://schema.org>, as they aren't a scholarly article, but don't really fit in anywhere else under CreativeWork either. Report as a type under CreativeWork would give this common publication type an accurate description. Properties for Report could be similar to that of Article, but would also include the report number, a key piece of metadata to describe reports.

  *   Report
     *   reportBody (Text) The actual body of the report.
     *   pagination (Text or Integer) Any description of pages that is not separated into pageStart and pageEnd; for example, "1-6, 9, 55" or "10-12, 46-49".
     *   pageStart (Text or Integer) The page on which the work starts; for example "138" or "xvi".
     *   pageEnd (Text or Integer) The page on which the work ends; for example "138" or "xvi".
     *   wordCount (Integer) The number of words in the text of the Report.
     *   reportNumber (Text or Integer) The number or other unique designator assigned to the Report by the publishing organization.

This is an example of a report that I am currently struggling to properly describe with schema.org<http://schema.org>- a Report CreativeWork type would immediately be put to use here: http://pubs.er.usgs.gov/publication/sir20145235

**Comment by jkreft-usgs** [comment]
Putting the report under Article would absolutely be one way to address this issue.  It doesn't completely address the highly heterogenous nature of reports (some are really closer to books and have ISBNs and chapters), but it would address a large portion of use-cases

**Comment by danbri** [comment]
We did not have a huge amount of discussion on this, but it is a reasonable idea and so @RichardWallis and I have merged this into the work-in-progress site build to see if it enjoys rough consensus in review.

**Comment by fmpalinkas** [comment]
Hi Dan,

Any chance you can also include "Glossary" with a Term, Definition, and
Reference (URL)?

Kind regards,

Frank M. Palinkas
Senior Technical Writer
Information Architect and Developer
Quixey, Inc., Mountain View, California
Mobile: +1 650 248 5315
Web page: https://github.com/fmpalinkas/web-accessibility-tutorials/wiki
