### ISSUE TITLE
LocalBusiness/Place - openingHours

### ISSUE THREAD

**Issue by Naewis** [schemaorg/schemaorg#376]
Hello,

I had seen on https://schema.org/LocalBusiness page that there is two types of opening hours : one with Duration type, and another one with OpenningHoursSpecifications type.

I don't understand why there is two property for the same information ? Is this a "bug" ?

---

Sorry if I'm in a wrong place, I dunno where to put this question. If it's not there, could you please tell me where is the good place ?

**Comment by Naewis** [comment]
Found where to report these kind of questions. Sorry for the disturb.

**Comment by unor** [comment]
Where did you report it? AFAIK this issue queue *is* the place for reporting bugs and feature requests.

**Comment by danbri** [comment]
#245 acknowledges that our design is under-documented, thanks for the report.
