### ISSUE TITLE
Describe the type of contribution made by each contributor to a CreativeWork

### ISSUE THREAD

**Issue by hubgit** [schemaorg/schemaorg#384]
As well as [`contributor`](http://schema.org/contributor), which says "this `Person` or `Organization` made a contribution to this `CreativeWork`", it would be useful to be able to describe the type of contribution that each contributor made.

For example:

* `CreativeWork` could have one or more `contribution`, the value of which is a `Contribution`.
* Each `Contribution` could have one or more `contributor`, the value of which is a `Person` or an `Organization`.
* Each `Contribution` could have a `role`, the value of which is a `Role`, such as [those defined by Casrai for contributions to research outputs in the sciences](http://dictionary.casrai.org/Contributor_Roles).

**Comment by Dataliberate** [comment]
Check out Role<http://schema.org/Role> and the associated blog post.<http://blog.schema.org/2014/06/introducing-role.html>

In your scenario the roleName property can either contain text describing the contribution role, or a URL which could reference Library of Congress Relator Terms, or Casari Roles, or even WikiData URIs.

~Richard

On 17 Mar 2015, at 14:17, Alf Eaton <notifications@github.com<mailto:notifications@github.com>> wrote:


As well as contributor<http://schema.org/contributor>, which says "this Person or Organization made a contribution to this CreativeWork", it would be useful to be able to describe the type of contribution that each contributor made.

For example:

  *   CreativeWork could have one or more contribution, the value of which is a Contribution.
  *   Each Contribution could have one or more contributor properties, the value of which is a Person or an Organization.
  *   Each Contribution could have a role property, the value of which is a Role, such as those defined by Casrai for contributions to research outputs in the sciences<http://dictionary.casrai.org/Contributor_Roles>.

**Comment by hubgit** [comment]
@Dataliberate Good idea, thanks!

I guess it would then look something like this?

```
CreativeWork -> contributor (Role)
    -> roleName "http://dictionary.casrai.org/Contributor_Roles/Conceptualization"
    -> contributor (Person)
```

What's the difference between `roleName` (text or a URL) and the existing `name` and `url` properties of a `Role`?

**Comment by Dataliberate** [comment]
Using the URL to reference an authoritative description of the role (at Casrai in your case) provides a consistent way of define the [contribution] role.  Also by following that URL you may well get far more information than just a name, such as descriptions and names in more than one language.


~Richard

On 17 Mar 2015, at 15:38, Alf Eaton <notifications@github.com<mailto:notifications@github.com>> wrote:


@Dataliberate<https://github.com/Dataliberate> Good idea, thanks!

I guess it would then look something like this?

CreativeWork -> contributor (Role)
    -> roleName "http://dictionary.casrai.org/Contributor_Roles/Conceptualization"
    -> contributor (Person)


What's the difference between roleName (text or a URL) and the existing name and url properties of a Role?

**Comment by hubgit** [comment]
> Using the URL to reference an authoritative description of the role (at Casrai in your case) provides a consistent way of define the [contribution] role.

Would that not be possible using the existing `url` property, though?

**Comment by hubgit** [comment]
The other problem with a `CreativeWork` -> `contributor` -> `Role` -> `contributor` -> `Person` mapping is that the same person can have multiple roles on the work. How should that be written, without duplicating the `Person` object?

**Comment by vholland** [comment]
@hubgit 

You could reuse the same id. Something like:

{
  "@context": "http://schema.org",
  "@type": "CreativeWork",
  "contributor": [
      {
      "@type": "Role",
      "roleName": "illustrator",
      "contributor": {
          "@id": "http://www.example.com/Jane",
          "name": "Jane Doe"
      },
      {
      "@type": "Role",
      "roleName": "author",
      "contributor": {
          "@id": "http://www.example.com/Jane",
      },
   ]
}

**Comment by realworldobject** [comment]
It should also be possible to repeat the roleName property as many times as necessary within a single Role node.

Jeff

**Comment by vholland** [comment]
Good point! I'm not sure why I didn't think of that. :-)

**Comment by unor** [comment]
> It should also be possible to repeat the roleName property as many times as necessary within a single Role node.

Wouldn’t this mean that one and the same role has multiple role names? (In which case it shouldn’t be used for *different* roles, right?)

**Comment by realworldobject** [comment]
Since schema:Role is more like an RDF gimmick than a real class, I think this is something that the major consumers of schema.org<http://schema.org> would need to tell us.

Jeff

On Mar 17, 2015, at 6:06 PM, unor <notifications@github.com<mailto:notifications@github.com>> wrote:


It should also be possible to repeat the roleName property as many times as necessary within a single Role node.

Wouldn't this mean that one and the same role has multiple role names? (In which case it shouldn't be used for different roles, right?)

-

**Comment by hubgit** [comment]
I think keeping each `Role` distinct (each with a single `roleName`) and attaching one or more `contributor` to each `Role` makes sense, like this:

```
{
    "@context": "http://schema.org",
    "@graph": [
        {
            "@type": "Person",
            "@id": "https://example.org/person-1",
            "name": "First Person",
            "email": "first.person@example.org"
        },
        {
            "@type": "Person",
            "@id": "https://example.org/person-2",
            "name": "Second Person",
            "email": "second.person@example.org"
        },
        {
            "@type": "ScholarlyArticle",
            "name": "Example Article",
            "contributor": [
                {
                    "@type": "Role",
                    "roleName": "http://dictionary.casrai.org/Contributor_Roles/Methodology",
                    "contributor": [
                        {
                            "@type": "Person",
                            "@id": "https://example.org/person-1"
                        },
                        {
                            "@type": "Person",
                            "@id": "https://example.org/person-2"
                        }
                    ]
                },
                {
                    "@type": "Role",
                    "roleName": "http://dictionary.casrai.org/Contributor_Roles/Investigation",
                    "contributor": [
                        {
                            "@type": "Person",
                            "@id": "https://example.org/person-1"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by Dataliberate** [comment]
These options demonstrate the ‘There are many ways to skin a cat” principle.

 You could either have a CreativeWork with several individual contributor statements, each using Role to define/refine the type of contribution.
Or
  You could have a CreativeWork with several contributor statements, one for each contribution type involved using Role to define the type of contribution and to reference the Person(s) in that contribution role - as laid out below.

 I see both of these as valid approaches.

~Richard

On 18 Mar 2015, at 09:41, Alf Eaton <notifications@github.com<mailto:notifications@github.com>> wrote:


I think keeping each Role distinct (each with a single roleName) and attaching one or more contributor to each Role makes sense, like this:

{
    "@context": "http://schema.org",
    "@graph": [
        {
            "@type": "Person",
            "@id": "https://example.org/person-1",
            "name": "First Person",
            "email": "first.person@example.org<mailto:first.person@example.org>"
        },
        {
            "@type": "Person",
            "@id": "https://example.org/person-2",
            "name": "Second Person",
            "email": "second.person@example.org<mailto:second.person@example.org>"
        },
        {
            "@type": "ScholarlyArticle",
            "name": "Example Article",
            "contributor": [
                {
                    "@type": "Role",
                    "roleName": "http://dictionary.casrai.org/Contributor_Roles/Methodology",
                    "contributor": [
                        {
                            "@type": "Person",
                            "@id": "https://example.org/person-1"
                        },
                        {
                            "@type": "Person",
                            "@id": "https://example.org/person-2"
                        }
                    ]
                },
                {
                    "@type": "Role",
                    "roleName": "http://dictionary.casrai.org/Contributor_Roles/Investigation",
                    "contributor": [
                        {
                            "@type": "Person",
                            "@id": "https://example.org/person-1"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by hubgit** [comment]
@Dataliberate Could you post an example of the first option? I'm not quite seeing how it would be different…

**Comment by realworldobject** [comment]
I like the Methodology example. It gives the subtle impression that those two people collaborated on the methodology. That may be reading too much into the construction, but still…

Jeff

**Comment by hubgit** [comment]
> It gives the subtle impression that those two people collaborated on the methodology.

That's an interesting implication. It wasn't the intention to suggest that they actively collaborated in some way (it was just intended to show that both these people had this contributor role), so that could be a reason to keep them separate.

On the other hand, collapsing contributors with the same role makes it easier to produce this kind of layout, without having to do a first pass/parse to build the expected structure:

# Contributors

## Methodology

* First Person
* Second Person

## Investigation

* First Person

It's probably safest to say that there's no distinction, and that no meaning should be read into groupings of contributors and roles?

**Comment by hubgit** [comment]
Closing as `CreativeWork` -> `contributor` -> `Role` -> `contributor` is sufficient.
