### ISSUE TITLE
Clarify license on schemas

### ISSUE THREAD

**Issue by Downchuck** [schemaorg/schemaorg#388]
Currently I'm seeing two licenses, an Apache License for the git repo and a CC BY-SA (Creative Commons Attribution-ShareAlike) on the website. This seems ambiguous.

What would the terms be for actually using these schemas in software? For example, http://schema.org/PostalAddress could be trivially implemented as an IDL; let's use protobuffers for example. PostalAddress.proto could be compiled and/or used (or manually translated) into a Java project.

Does the ASL/BY-SA license follow that entire path? Does it terminate when the schema is implemented as a Protobuffer schema?

-Charles

**Comment by danbri** [comment]
I believe we now clarify this in the FAQ reasonably well - http://schema.org/docs/faq.html#18

I'll link to that from the repository readme too.

**Comment by danbri** [comment]
README.md now cites the FAQ entry for this. I'll close the issue but please reopen if you think it needs more, @Downchuck
