### ISSUE TITLE
EventType: what is the difference between Comedy and Theater?

### ISSUE THREAD

**Issue by romainlange** [schemaorg/schemaorg#397]
Hi,

I don't see the difference between these two event types.
Theater and comedy are quite synonym, isn't it?

**Comment by thadguidry** [comment]
@romainlange  Someone just needs to add a Genre property to https://schema.org/TheaterEvent
As well as adding a Production property.  The TheaterEvent is independent of the actual Theatrical Production (also known as a Play).  Where a TheatricalProduction can be of any genre, like a Comedy, Drama, etc.

@vholland Would you mind taking up this task and filling in the missing bits for TheaterEvent that are needed ?

**Comment by vholland** [comment]
As suggested in Issue #398, there are two changes required: adding genre and adding audience. We might as well do both at the same time.
