### ISSUE TITLE
EventType: remove UserInteraction

### ISSUE THREAD

**Issue by romainlange** [schemaorg/schemaorg#399]
Hi, 

Schema defines an event as

> An event happening at a certain time and location, such as a concert, lecture, or festival. Ticketing information may be added via the 'offers' property. Repeated events may be structured as separate Event objects.

UserInteraction seems more related to comments or review, thus it is definitely not an EventType. I suggest to remove it.

**Comment by vholland** [comment]
This was previously proposed as [issue #172](https://github.com/schemaorg/schemaorg/issues/172).

We should get around to doing that already. :-)
