### ISSUE TITLE
CODE: redirect http://www.schema.org/Person to http://schema.org/Person etc.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#4]
redirect http://www.schema.org/Person to http://schema.org/Person
and 
redirect https://www.schema.org/Person to https://schema.org/Person
on the basis that we prefer to see the canonical 'http://schema.org/Person' in widespread use, but if someone asks for the https then let's give it to them.

**Comment by danbri** [comment]
Extracting overly verbose TODO notes from sdoapp.py:

        #        if str(self.request.host).startswith("www.schema.org"):
        #            log.debug("www.schema.org requested. We should redirect to use schema.org as hostname, not " + self.request.host)
        #            origURL = self.request.url
        #            origURL.replace("https://", "http://")
        #            origURL.replace("//www.schema.org", "//schema.org")
        #            self.redirect(newURL, permanent=True)

see also https://webapp-improved.appspot.com/guide/routing.html?highlight=redirection

**Comment by danbri** [comment]
Also '//' '///' etc should redirect to homepage.

**Comment by danbri** [comment]
Also bib.schema.org/docs/datamodel.html etc should redirect to schema.org/docs/datamodel.html

Whereas the JSON and full.html pages probably should be per-extension as they are custom views and might show extra info.

**Comment by scor** [comment]
+1. requested more than 2 years ago at http://lists.w3.org/Archives/Public/public-vocabs/2012Dec/0035.html

**Comment by danbri** [comment]
Cleaning more TODOs from codebase:

        # TODO:
        # - handle http vs https; www.schema.org vs schema.org
        # - handle foo-input Action pseudo-properties
        # - handle /Person/Minister -style extensions

**Comment by danbri** [comment]
@scor :) 2 years ago we didn't have an opensource webapp. I'm making a cleanup pass through in sdo-scripts branch right now, removing some spaghetti so we can get extensions handled sanely...

**Comment by danbri** [comment]
Postponing until after extensions roll out.

**Comment by danbri** [comment]
From @mfhepp  in a duplicate report,

"""Currently, the schema.org main page and type/property/individual pages are served from both the naked domain AND from the www.schema.org hostname, which can lead to a proliferation of wrong class / property URLs in markup.

Instead of silently serving the content from both URLs, there should be a proper 301 redirect to the canonical URL.

As said, the problem also exists for URLs for types and properties, e.g.
http://www.schema.org/Thing

which is even more serious."""

**Comment by danbri** [comment]
Extensions rolled out. It looks like to handle this for /docs/ too (needed to avoid e.g. http://bib.schema.org/docs/datamodel.html leaking into use) we may have to stop serving them as static files in appengine. This seems a pity as I believe we'd be opting out of some CDN-like caching. Needs investigation e.g. see http://stackoverflow.com/questions/31584687/app-engine-subdomain-redirects-on-static-files-http-301 http://webapp-improved.appspot.com/guide/routing.html#domain-and-subdomain-routing https://cloud.google.com/appengine/docs/python/gettingstartedpython27/staticfiles

**Comment by danbri** [comment]
Fixed in https://github.com/schemaorg/schemaorg/commit/e674fed2b9ccbe12f73329e647081074885e0005 for per-term pages. So I'll close here. We need to redirect /docs/ too but that's a lesser problem which could be handled in js for reasons above.
