### ISSUE TITLE
Clarify relationship between Product and product type classes

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#404]
Currently, a few classes are currently subclass of Product, even though they can be used in non-product contexts. It has been discussed on the mailing list to challenge this, namely for Vehicle.

One solution is to move up all concrete types of products, like Vehicle, up to Thing and promote multi-typed entities for all cases where the entity is used as a product. The problem with that change is that it invalidates old markup, because properties from Product (e.g. gtin13) would no longer be valid (in Microdata at least)  on entities that are single-typed (e.g. just a schema:Car).

So this issue is just a reminder to keep it on the radar. 

There are two preconditions for changing this:

1. We must establish it as a standard that products are multi-typed entities in examples etc.

2. All major consumers of schema.org markup can process multi-typed entities

The changes needed would be to

- move all subtypes of Product up to Thing or a branch thereof
- move up all properties of Product that are not tied to the Product role up to that subtype(s) of Thing (e.g weight). 
- update descriptions and examples

Product would then hold only those properties that are bound to the project role.

**Comment by elf-pavlik** [comment]
Thank you @mfhepp! In my original email I also proposed adding **Tangible** class for Vehicle, Device etc. https://lists.w3.org/Archives/Public/public-vocabs/2015Mar/0153.html

I find it very unfortunate that we seem to keep struggling with limitations of Microdata. Also I find one of the beauties of RDF that you can use any property on any type unless explicitly disallowed...

**Comment by rvguha** [comment]
Can you give me a few examples of this?

I don't want to move all subtypes of Product to Thing or all the properties
to Thing.

guha

**Comment by elf-pavlik** [comment]
I would like to add that Product acting also as service adds additional confusion if we start subclassing it. In this post we see offers for flights https://plus.google.com/+BradBrewer/posts/RfY48SskHnQ If one uses Product for such, as well as other services one can Offer/Demand - bus tickets, web hosting, domain registration etc. I really don't think it should have sub classes like Vehicle, Device etc.

For properties we could look at it together with few other types e.g.
* http://schema.org/Book
* http://schema.org/MedicalDevice

In real world, both of them one can use in Offer/Demand, also both have for example *weight* and *width*. Still it may not make sense to make all of them a subclass of Product. I understand that MedicalDevice and all the MedicalEntity subtree has it's own history. But schema.org may need to soon deal with Device in general e.g. https://www.fairphone.com/ (examples already have (iPod with "@type": "Product" while use just as *instrument* in action, with no commercial, economic function). Similar with ones used together with http://schema.org/ControlAction

**Comment by mfhepp** [comment]
Following bilateral discussions, I conclude that we should close this issue for the moment and rather improve the wording for schema:Product, as proposed in 

https://github.com/schemaorg/schemaorg/issues/424.
