### ISSUE TITLE
Create mechanism for URN-style URIs for standard codes in schema.org

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#405]
schema.org could become a nice central place for defining namespaces for common standard codes, like ISO 3166 etc. We could use the new extension mechanism to define such namespaces. This would make sense even if, for copyright or other reasons, the resulting URIs would not return a meaningful human-readable or RDF description (but they could always return a default string 

"The code XYZ in the XYZ standard. For information on the standard, see <link>".

The handle for this could support CONNEG and return a boilerplate definition in RDF syntaxes, too.

This would not be the best possible URIs for a standard, but have enough authority and would not depend on ongoing updates - it would be a combination or URNs and URLs with a pseudo-meaningful representation.

See also the original discussion at https://lists.w3.org/Archives/Public/public-vocabs/2015Mar/0176.html

**Comment by realworldobject** [comment]
Here’s a pre-Linked Data attempt to compare this with:

http://info-uri.info/
http://www.ietf.org/rfc/rfc4452.txt

Jeff

**Comment by ppKrauss** [comment]
**+1** vote.  Yes, make sense! 
PS: suggestion, use/appreciate https://github.com/datasets

**Comment by ppKrauss** [comment]
Testing the suggestion... Something more to discuss

-----

A key concept in URNs at Web, so "URN-style", in my opinion, is the existence of an *URN-resolver*.  SchemaOrg  community will need:

* select/elect (**curation activity**) what are (?) the "standard codes" for SchemaOrg use. Even usual URNs like ISSN, ISBN, etc. must be pointed as "ok, we will use it".

* **express in [schema_org_rdfa](http://schema.org/docs/schema_org_rdfa.html) the URL** of the official [URN resolvers](https://en.wikipedia.org/wiki/Uniform_resource_name#Resolvers), or, when (like ISO 3166) not exist, [the URL of the open dataset](https://github.com/datasets/country-codes)... or stable URL of the URN-authority (see ex. [problem with ISSN-L](https://en.wikipedia.org/wiki/International_Standard_Serial_Number#Linking_ISSN)).

**Comment by chaals** [comment]
-1 

I don't see the value of schema as a universal scaffold for linked data, so much as a particular effort that motivates people to use it, so learn it, so build the frameworks it needs to work well.

I'd rather schema "stick to its knitting", which is providing terms for things that enable large-scale consumption, while people who already know what they are doing build stuff that's more detailed.

I think the useful symbiosis is that schema brings more people to learn the skills to move beyond schema, rather than trying to have it as some centre of everything in the linked data universe. The vocabulary and structure are bad enough and management complex enough as it is…

just my 2c worth

**Comment by Dataliberate** [comment]
"We could use the new extension mechanism to define such namespaces”

I tend to agree with Chaals about what the core of Schema should be concerned about.

However, if there is a sustainable group motivated enough to provide what Martin describes, the extension mechanism could be a great way for them to publish their efforts.

~Richard

On 1 Apr 2015, at 13:51, chaals <notifications@github.com<mailto:notifications@github.com>> wrote:


-1

I don't see the value of schema as a universal scaffold for linked data, so much as a particular effort that motivates people to use it, so learn it, so build the frameworks it needs to work well.

I'd rather schema "stick to its knitting", which is providing terms for things that enable large-scale consumption, while people who already know what they are doing build stuff that's more detailed.

I think the useful symbiosis is that schema brings more people to learn the skills to move beyond schema, rather than trying to have it as some centre of everything in the linked data universe. The vocabulary and structure are bad enough and management complex enough as it is…

just my 2c worth

**Comment by mfhepp** [comment]
First: I am not at all religious about the proposal, so I am fine with rejecting the idea. One could also argue that the w3c namespace would be a much more natural umbrella for this effort.

My main two cents are that a simple Web handler that returns a boilerplate text / RDF for standard codes could be better than deriving full RDF versions from those standards. It would take away the copyright and synchronization issue.

**Comment by Dataliberate** [comment]
My main two cents are that a simple Web handler that returns a boilerplate text / RDF for standard codes could be better than deriving full RDF versions from those standards. It would take away the copyright and synchronization issue.

+1

**Comment by ppKrauss** [comment]
Thinking in @chaals  arguments (and other later  comments/discussion), and merging with my comments about "URN-resolver"...

How about a RDFa *property* that only indicate where (URL) a value or a name can be "resolved" or "validated"?

Let's draw some **use cases**, to discuss about concrete context:

***Case-1.1***: express a [journal title] (ex. PlosOne) enforcing its unique name by its [ISSN] (ex. 1932-6203).  Thing=book, URN-like=ISBN. What  the URL for the value `1932-6203`? Is not the link to de jornal, but the link to the ISSN-resolver... Example: http://www.worldcat.org/xissn/titlehistory?issn=1932-6203  

***Case-1.2***: express a [scientific article title] (ex. "Do Reef Fish Habituate to Diver..." by Titus et al.) enforcing its unique name by its DOI (ex. 10.1371/journal.pone.0119645). Thing=article, URN-like=DOI. What  the URL for the value `10.1371/journal.pone.0119645`?    Is not the direct link to the article's page (can be a PubMed Central link), but the the link to the DOI-resolver. Well-knowed dx.doi.org,  so http://dx.doi.org/10.1371/journal.pone.0119645

***Case-1.3***: cite [RFC 7230] with a link that "reuse the name" as an URN-like name, so this link is a URN-resolver and we can imagine `urn:rfc:7230`.... Thing=doc of a techinical stadard. URN-like=RFC...  so https://tools.ietf.org/html/rfc7230

***Case-1.4***: express [Brasilian Federal Law 11705] with no confusion... In this case the URN exist, is `urn:lex:br:federal:lei:2008-06-19;11705` and the URN-Resolver is http://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2008-06-19;11705

***Case-2.1***: express a [country ISO abbreviation] (ex. US and BR) enforcing its uniqueness and semantic...  Thing=country, URN-like="ISO 3166 standard strings". What  the URL for the value `BR`? Is not the link to a `gov.br`  page, but to the  ISO 3166's "resolver"... The near is https://github.com/datasets/country-codes/blob/master/data/country-codes.csv  (or only the root to avoid big downloads).

***Case-2.2***: express a [language ISO abbreviation] ...  https://github.com/datasets/language-codes
 
------

... So what SchemaOrg can be do for us? I think it is only put the semantic in the URL: as showed by case-1.1, case-1.2, ... a property that says "it is a link to the URN-resolver to the URN value".

From these *case uses* my conclusion is: add a property **urnResolverURL** to [schema_org_rdfa](http://schema.org/docs/schema_org_rdfa.html) to use in the context of "linking URN-like values".

**Comment by westurner** [comment]
* You can use a URN anywhere (with URI-quoting (rdflib.URIRef('urn:x-example.com:/><')))
  * https://en.wikipedia.org/wiki/Uniform_resource_name#Examples

So urlResolverURL would be user-supplied input to a prefix transformation function?

**Comment by ppKrauss** [comment]
hum... You talking about something as [Javascript's `encodeURIComponent()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)? 
Ok, you can encode, but all "good statandard URN schema" have a syntax that is URI (so URL) compatible, not need transcriptions... See p.ex. the [URN LEX](http://tools.ietf.org/html/draft-spinosa-urn-lex-09), that is the most complex in the examples, and is a real case of Brazilian government use, it not need `encodeURIComponent()`.

------
**Rationale**: all "standarizable URN" (IANA or not) have a well-knowed (for user community) *URN-Resolver*, that is, an URL for this resolver. For *webservice endpoints* perspective (and [CoolURL recommendation](http://www.w3.org/TR/cooluris)), the typical resolution URL is in the form  `http://someDomain/urn:namespace:ID` , or `http://someDomain/namespaceEndPoint/ID` , where ID is an URI-compatible string.

Example (see also Case-1.2 above): http://dx.doi.com is the well-knowed resolver for "urn:x-doi" URNs. So, with SchemaOrg we can define a property *urlUrnResolver* to remember that a URL is a URN-Resolver... p. ex. `<a itemprop="urlUrnResolver" href="http://dx.doi.org/10.1038/ncomms7368">doi:10.1038/ncomms7368</a>`. 

Other example: of course, for *a priori* URNs or IANA URNs we can omit the resolver, p. ex. `<span itemprop="urn">urn:x-doi:10.1038/ncomms7368</span>`  or `<span itemprop="urn">urn:issn:2041-1723</span>`.

**Comment by westurner** [comment]
So, URN URI shorturl resolver application rules?

Similar to e.g. Turtle \@prefix statements or JSON-LD \@context rules, but with localizable labels?

rules = [('urn:x-example.com', 'example.com/ns/', 'Example DOT com')]

**Comment by westurner** [comment]
http://prefix.cc/about :

>The intention of this service is to simplify a common task in the work of RDF developers: remembering and looking up URI prefixes.
>
>You can look up prefixes from the search box on the homepage, or directly by typing URLs into your browser bar, such as http://prefix.cc/foaf or http://prefix.cc/foaf,dc,owl.ttl.
>
>New prefix mappings can be added by anyone. If multiple conflicting URIs are submitted for the same namespace, visitors can vote for the one they consider the best. You are only allowed one vote or namespace submission per day.

Linked Open Vocabularies (http://lov.okfn.org/)

* http://lov.okfn.org/dataset/lov/vocabs/schema
* http://lov.okfn.org/dataset/lov/sparql

ENH: class/property lookup JS widget #349 

* https://github.com/schemaorg/schemaorg/issues/349
* (... JSONLD, RDFJS)

**Comment by ppKrauss** [comment]
@westurner , sorry is difficult to understand your posts without good explanation/contextualization,  in the thread (here) direction...

Example: you ask about JSON-LD... yes, perhaps `@prefix` and `@context`  are good clues here, but *short-url* not make sense, the URLs must be a [PURL](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator) and the PURLs most resolve short or big URNs, like at http://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2008-06-19;11705 where `http://www.lexml.gov.br/urn/` is the resolver of the [urn of the LEX-BR namespace](https://en.wikipedia.org/wiki/Lex_(URN)). 

PS: JSON-LD is only a "technical jargon", perhaps expressing in more informal terms, as [use cases](https://github.com/schemaorg/schemaorg/issues/405#issuecomment-88501504), more people can read and discuss with us.

**Comment by westurner** [comment]
Oh, okay, so another mechanism for looking up one string and returning
another (with a *suffix*, and an HTTP API that is more or less exactly a
shorturl resolver application).

**Comment by westurner** [comment]
@ppKrauss 

IIUC [...] with localizable labels AND a resolver host?

```python

resolver_mappings = [{
  'label': ''Schema.org'@en,
  'mappings': [
    'urn:x-schema.org',
    'schema:'
  ],
  'url': 'https://resolverapi.schema.org/',
     #  http://schema.org/<suffix>
}]
```

**Comment by ppKrauss** [comment]
Thanks @westurner , make sense.  About the expression of the [Persistent URL](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator)/[URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name) relationship, the most used today is the [URI Template (RFC 6570)](https://tools.ietf.org/html/rfc6570). Examples:

Old comment | commented syntax | standard URI Template syntax
-------------------------|-----------|---------------------
@westurner's [here](#issuecomment-113598622) | `http://schema.org/<suffix>` | `http://schema.org/{suffix}`
my [here](#issuecomment-99969186) | `http://someDomain/urn:namespace:ID` |  `http://someDomain/urn:namespace:{ID}`
my [here](#issuecomment-99969186) | `http://someDomain/namespaceEndPoint/ID` |  `http://someDomain/namespaceEndPoint/{ID}`
([real cases](#issuecomment-88501504)) | http://doi.org/10.1371/journal.pone.0119645<br/>[https://lexml.gov.br/urn/urn:lex:br:federal:lei:2008;11705](https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2008;11705) | `http://doi.org/{urn_doi}`<br/>`http://www.lexml.gov.br/urn/{urn_lex}`

Important to remember that general case is not a suffix, can be something as `http://someDomain/etc1/{urn}/etc2`... But, of course, in a JSON-LD ecosystem ideal to be a suffix.
