### ISSUE TITLE
Add a mechanism for examples on property pages

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#407]
Currently, we have markup examples on Type pages only, like

http://schema.org/Offer

but not on those for properties, like

http://schema.org/deliveryLeadTime

I recommend to add a mechanism for examples on properties pages, too, because it would often be useful to explain the use of a property. Also, for types with many properties (like Offer), the examples given cannot cover all possible properties.

Note: It is understood that this is not always appropriate, because the use of a property may depend on the type it is attached to, but we should have the ability.

What is needed?

- Either define a "PROPERTY" keyword for the examples syntax, or allow properties after the TYPE keyword.
- Update the template for the properties pages
- Update the logic for generating the properties pages
- Gradually add examples for relevant properties (I would volunteer to gradually do so for GoodRelations properties)

**Comment by danbri** [comment]
Yes, we absolutely should do this. In fact it ought to work already - have you tried adding property term names on the poorly-named TYPES: line?

I'm closing this as we already track the need for property and enum examples at https://github.com/schemaorg/schemaorg/issues/179
