### ISSUE TITLE
Remove "commercial" bias from GoodRelations elements

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#424]
Product, Offer, and other elements from GoodRelations currently use labels and descriptions that are sometimes too tightly bound to traditional commercial transactions, while the underlying GoodRelations makes no such assumptions (e.g. that the compensation has to be a monetary amount).

By updating the description for those elements, we can mitigate many of the potential inconsistencies in schema.org, e.g. that some user communities do not feel that the objects or services they are offering are "products".

This is related to the task of supporting barter trade and non-monetary compensations in schema.org/GoodRelations.

**Comment by elf-pavlik** [comment]
:+1:

**Comment by danbri** [comment]
Thanks, Martin. this would be a very constructive improvement, and shouldn't affect any existing processing as it is only really a matter of descriptions (and examples).

**Comment by danbri** [comment]
Related: #385

**Comment by danbri** [comment]
See also discussion in https://plus.google.com/u/0/116204485973373967341/posts/8EuLyMFTUmu

**Comment by akuckartz** [comment]
:+1:
