### ISSUE TITLE
Add Organization to Alumni / AlumniOf

### ISSUE THREAD

**Issue by fili** [schemaorg/schemaorg#432]
Often a Person (https://schema.org/Person) can be an alumni of an organization which may not be purely educational. 

Hence I propose to include Organization (https://schema.org/Organization) to the "Values expected to be one of these types" at https://schema.org/alumniOf  and "Used on these types" at https://schema.org/alumni.

**Comment by danbri** [comment]
@shankarnat has gone ahead and implemented this in #578, ... and this has crystalized a thought I hadn't articulated before:

What relationship does someone have to have had, to count as an alumni?

We are broadening the types of Organization here, but also less explicltly, broadening the kinds of appropriate relationship too. Originally it was I think implicitly studentship as the stereotypical relationship; now we are taking other kinds of http://schema.org/member ... e.g. employees.

Consider a University Lecturer who used to work at http://en.wikipedia.org/wiki/Poppleton_University but now works at Porterhouse College Cambridge. Do we consider them (regardless of their prior education) to be an ''alumni' of Poppleton?

I think 'yes' is an ok answer but we ought to refine the textual definition. 

For example we might say: "The 'alumni' relationship encompasses various previous relationships (roughly corresponding to 'schema.org/member') that link people with organizations, including studentship, employment and other notions of membership.

**Comment by vholland** [comment]
What do we mean "alumni" beyond a relationship with an education organization? To @danbri's point, should we be using http://schema.org/member and using a Role to show the relationship has ended?

**Comment by danbri** [comment]
@fili 's original point was "an organization which may not be purely educational.". So perhaps e.g. someone who had been in a learning-like role (e.g. intern, apprentice) in a non EducationalOrganization might want to appeal to the narrower reading of alumni. A definition for that might be something like "An alumni of an Organization is someone who has been in a learning/education oriented role within the Organization; typically a student, but also e.g. apprentice, intern etc."

**Comment by fili** [comment]
@danbri is right. In addition to Merriam-webster.com an alumni can also be "a  person who is a former member, employee, contributor, or inmate" - see for reference http://en.m.wikipedia.org/wiki/Alumnus. A number of companies use the alumni label also for their former employees. Hope this helps.

**Comment by danbri** [comment]
Ok so options are:

1.) we take a fairly restricted view of "alumni" as a learner. Even in this case expanding the types to Organization does make sense, as it is reasonable for interns, apprentices etc to be considered alumni in the 'learner' sense.

2.) we take a broader view of alumni, embracing employees, inmates etc. and update text/examples accordingly. This covers more use cases but introduces vagueness - without additional more precise description we don't know much about the role someone had in an organization (inmate vs prison guard; scholar, student or administrator, etc.).  I think that can be ok and we may get into more dedicated resume-style modeling later. 

I have a weak preference for (2.). Any other opinions?

ping @shankarnat @tilid @scor @chaals @ajax-als @pmika @mfhepp @tmarshbing @rvguha @vholland

**Comment by dbs** [comment]
Making it impossible to, until such time as more dedicated resume-style modeling happens, distinguish between "formerly a student of" vs. "former a faculty member at" with respect to an educational institution is disturbing. Perhaps add a more general schema:wasSomehowAssociatedWith property to serve that felt need? (That's not a serious suggestion, obviously, but it suggests what schema:alumniOf would effectively mean in scenario 2).

Note that http://schema.org/alumniOf says it has 10,000 - 50,000 domains currently in use. Diluting the meaning of schema:alumniOf would have a potentially significant impact on those domains.

**Comment by danbri** [comment]
Thanks, Dan. 

Does it matter under (2.) that we don't distinguish people that successfully graduated versus e.g. were kicked off their course? (like my attempted A-Level in English at Chichester College of Technology, where I was ejected after 12 months :) I'd like to think I'm still an alumni of some kind, even if not covered in scholarly glory...

**Comment by dbs** [comment]
http://www.concordia.ca/alumni-friends/benefits-services/alumni-services/alumni-id-card.html is a relatively common approach, I think (with variations on how many credits of course; how fuzzy is a bear?):

"If you have completed at least 30 credits and have not been enrolled in courses for at least one year, you are considered an attendee: a non-graduate with full alumni privileges."

**Comment by fili** [comment]
I would expect alumnus to be verified. For example:

https://www.linkedin.com/groups/NYPD-Alumni-1835955/about -> "Your profile must reflect past employment as a sworn member of the NYPD"

or

http://www.ibm.com/ibm/greateribm/faq.shtml -> "The Greater IBM Connection is the official IBM Alumni Relations program"

or 
https://sites.google.com/a/googlealumni.com/welcome/ 
https://www.microsoftalumni.com/
etc.

I do understand the concern of potentially devalueing the alumniOf schema for existing websites, however is the current schema too restrictive and a missed opportunity for more adoption? 

The type of organization can be specified, e.g.
currently: https://schema.org/Person > alumniOf > EducationalOrganization 
proposal: https://schema.org/Person > alumniOf > Organization > EducationalOrganization

Just a thought ...

**Comment by danbri** [comment]
Even if we mention org type, eg Edu Org, that does not necessarily imply student (vs janitor, professor etc)

**Comment by shankarnat** [comment]
I feel that alumni is valid for Organizations too.
For example; lot of organizations call their past employees as alumni in the real world. 
Just restricting it to Edu Org wuold not solve the purpose

Acc to Wikipedia - An alumnus (masculine, plural alumni) or alumna (feminine, plural alumnae) is a former student or pupil of a school, college, or university. Commonly, but not always, the word refers to a graduate of the educational institute in question.[1] An alumnus can also be a former member, employee, contributor, or inmate, as well as a former student.

I think maybe adding something like a role/association with the alumni. 
Like the role could be "Student","Employee"; qualifying that alumni relationship could be helpful .

Thoughts ?

**Comment by danbri** [comment]
@chaals in #588 comments "I prefer the broader sense of alumni."

**Comment by danbri** [comment]
The schema.org steering group had a call yesterday (#588 has agenda/notes), and discussed this. We had mixed views on whether alumni/alumniOf should be broadened beyond education. Given the lack of consensus, and the existing usage that tends towards the narrow reading, we decided to stay with the status-quo property meaning which we take to be a relationship between a person and an educational institution that the attended (for some unspecified but significant period) as a learner.

This means that we won't merge in @shankarnat 's #578 (but thanks for implementing!). Tweaks to the textual definitions of alumni and alumniOf to clarify its meaning would still be appropriate; textual suggestions welcomed. We also noted that it might be worth looking around at designs for representing cv/resume histories with more precision.

@fili I propose therefore we close out this issue as-is, on the understanding that EducationalOrganization is conceived broadly (i.e. need not always be school/college/university), and a reminder that things can have multiple independent types. On that point btw many thanks to @Dataliberate whose #567 improves the display within schema.org of types that have multiple supertypes. So if you were to see 'alumniOf' used with e.g. Company that would be perfectly reasonable, regardless of whether the type EducationalOrganization was explicitly mentioned.

**Comment by danbri** [comment]
@vholland thanks for opening #598. Let's close up here, and channel any discussion about clarifying our 'alumni' wording over there. Thanks again @fili for helping us realise we have some ambiguity to address.

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all

**Comment by sumutcan** [comment]
Hi all,
Just wondered if there is reason to keep EducationalOrganization in the range of alumniOf together with Organization. Organization is already the supertype of EducationalOrganization.

**Comment by danbri** [comment]
@sumutcan sometimes we include a broader type (like Organization) to capture corner cases, although the most obvious and common use is a more restricted type (EducationalOrganization). In such situations we have tended to keep the specific type there too, to highlight it. Although in a sense it is formally un-necessary, it is still often a helpful thing to do and helps to keep usage of the schemas grounded in typical usecases.
