### ISSUE TITLE
Site navigation: Boolean / True / False should be navigable and breadcrumb'd

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#433]
The fix for #130 means that True and False are now only instances of Boolean, and not subtypes.

We should either declare them Enumeration (and debug the resulting wonky HTML) or directly support navigation and breadcrumb display of these inter-term relationships.

(see 'parentStack' etc in codebase, api.py)

**Comment by danbri** [comment]
I didn't get this fixed for the release. I intend to address it as a software fix rather than formal schema release and push out an update in a matter of days.

**Comment by RichardWallis** [comment]
Fixed by #130 & #463
