### ISSUE TITLE
Need define rdf:type for http://schema.org/Thing

### ISSUE THREAD

**Issue by Nashev** [schemaorg/schemaorg#434]
Need add to schema.org statements to glue definition gap

`<http://schema.org/Thing> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type><http://www.w3.org/2000/01/rdf-schema#Class> .`

also useful may be predicate owl:equivalentClass or rdfs:subClassOf:

`<http://schema.org/Thing> <http://www.w3.org/2002/07/owl#equivalentClass><http://www.w3.org/2000/01/rdf-schema#Class> .`

or 

`<http://schema.org/Thing> <http://www.w3.org/2000/01/rdf-schema#subClassOf><http://www.w3.org/2000/01/rdf-schema#Class> .`

**Comment by danbri** [comment]
Thanks for your suggestion. We already declare Thing to be of type rdfs:Class as follows:

    <div typeof="rdfs:Class" resource="http://schema.org/Thing">
      <span class="h" property="rdfs:label">Thing</span>
      <span property="rdfs:comment">The most generic type of item.</span>
    </div>

This basically says (in RDFa) "there is an rdfs:Class whose URI is http://schema.org/Thing ..."

We don't consider Thing equivalent to rdfs:Class, and it is not a subclass of rdfs:Class, since there are many things (e.g. people, places etc.) that are not rdfs classes.

**Comment by Nashev** [comment]
I'm sorry. My copy of schema.org ontology was little erroneous, and at page http://schema.ord/Thing doesn't noted this relation in visible text, only in RDFa markup.

Now i will import from http://schema.org/docs/schema_org_rdfa.html and do not repeat this mistake

**Comment by danbri** [comment]
No need for 'sorry'; we know we need to improve the structure of our documentation to make these things easier to find. Thanks again.

**Comment by Nashev** [comment]
What about make 
`<http://schema.org/Thing> <http://www.w3.org/2000/01/rdf-schema#subClassOf><http://www.w3.org/2000/01/rdf-schema#Resource> .`

or 
`<http://schema.org/Thing> <http://www.w3.org/2002/07/owl#equivalentClass><http://www.w3.org/2000/01/rdf-schema#Resource> .`
?

**Comment by Nashev** [comment]
or `<div typeof="rdfs:Class" resource="http://schema.org/Thing">` must be interpret as this autimatically?

**Comment by Nashev** [comment]
There are some direct subclasses for rdfs:Resource are in base ontologies:

```
rdfs	Resource
  rdfs	Class
  rdfs	Container
  rdfs	Literal
  rdf	List
  rdf	Property
  rdf	Statement
  owl	AllDifferent
  owl	AllDisjointClasses
  owl	AllDisjointProperties
  owl	Annotation
  owl	Axiom
  owl	NegativePropertyAssertion
  owl	Ontology
```

**Comment by mfhepp** [comment]
Note that schema.org is agnostic about the general W3C Semantic Web stack of standards - to the degree possible, it tries not to conflict with RDF, OWL, SPARQL etc., but it does not depend on it nor does it strive for formal compatibility.

So I would keep that link to RDF/RDFs out of schema.org, because it is a specific grounding to a W3C standard that is not critical for schema.org.

**Comment by Nashev** [comment]
@mfhepp, but `typeof="rdfs:Class"` is already mentonied in schema.org!

**Comment by mfhepp** [comment]
Yes, but that was afaik just a very loose integration into RDF.

Also note that that the relationship between rdfs:Class and rdfs:Resource is already defined in the RDFS spec:

http://www.w3.org/TR/rdf-schema/#ch_class

Also note that the editors of the RDFS spec are also heavily involved in schema.org, so we can assume they know ;-)

**Comment by Nashev** [comment]
I see in http://www.w3.org/TR/rdf-schema/#ch_resource there are noted that ALL classes must be are subclasses of rdfs:Resource.

And in http://www.w3.org/2000/01/rdf-schema I see this:
```
rdfs:Class a rdfs:Class ;
	rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> ;
	rdfs:label "Class" ;
	rdfs:comment "The class of classes." ;
	rdfs:subClassOf rdfs:Resource .
```

Also I see http://www.w3.org/2002/07/owl have own Thing, and it's also not defined as any subclass... 
```
owl:Thing a owl:Class ;
     rdfs:label "Thing" ;
     rdfs:comment "The class of OWL individuals." ;
     rdfs:isDefinedBy <http://www.w3.org/2002/07/owl#> .
```
It's not only schhema.org problem, but also OWL ontology too! ;)

**Comment by Nashev** [comment]
In other words: If anything is a rdfs:Class, it must be rdfs:subClassOf of anything or it must be equivalent of the rdfs:Resource

**Comment by mfhepp** [comment]
No. Not "it must be", but it automatically is. Also note that rdfs:Resource is in fact an instance of rdfs:Class.

The exact semantics of RDF and RDFS are actually pretty complicated, but mostly irrelevant for schema.org. The same holds for OWL. schema.org is not designed to be an OWL ontology, though it can be approximately translated into one.

**Comment by Nashev** [comment]
in case of it is automatically is, it must be actually declared in ontology text, just like it declared for rdfs:Class in text of rdfs ontology! In RDF graph must not be implicit triples, all of them must be explicitly defined.

**Comment by mfhepp** [comment]
No. The basic RDF / RDFS semantics are built into an RDF repository. No need to put all RDF / RDFS axioms into an ontology. For the formal specs, see here

    http://www.w3.org/TR/rdf-mt/

See also 

    https://jena.apache.org/documentation/inference/#rdfs

If you want to learn how this works, look into the rulesets in the source code of popular reasoners, e.g. in Jena:

    https://github.com/apache/jena/tree/6252acede5822d8ffacec141d20c88028c25836c/jena-core/src/main/resources/etc

However, the whole thread is going very much off topic, and, it makes no sense to discuss the foundations of RDF in the context of a closed issue of schema.org. If you want to carry this further, use an appropriate W3C mailing list like semantic-web@w3.org.

**Comment by danbri** [comment]
As Martin says, in RDF applications it is very common to omit triples that are implied.

**Comment by Nashev** [comment]
Ouch! (

**Comment by danbri** [comment]
I had not expected that to be painful news! One benefit of having a few inference rules is that it allows messages to be more compact.

For example, when a site says something about a LocalBusiness, we also know that they are talking about a Place and an Organisation...

**Comment by Nashev** [comment]
I'v found http://www.w3.org/TR/2002/WD-rdf-mt-20021112/#VocabEntailment now

**Comment by akuckartz** [comment]
@Nashev Please do not refer to obsolete documents. The current RDF Semantics specification is http://www.w3.org/TR/2014/REC-rdf11-mt-20140225/

And as already mentioned: this issue is closed and not an appropriate place to discuss RDF.

**Comment by danbri** [comment]
So long as the issue stays *closed*, a bit of chat is ok imho. Having 100s
of open issues is a much bigger problem for us...
