### ISSUE TITLE
hasPart and isPartOf domain and range extension

### ISSUE THREAD

**Issue by unsteady** [schemaorg/schemaorg#436]
schema:isPartOf  and  schema:hasPart  have a domainIncludes and rangeIncludes set to schema:CreativeWork. This seems a bit restrictive. OTOH there are equivalent properties like schema:containedIn for schema:Place.

Why not set domain and range of those two properties to schema:Thing, and get rid of more specific avatars (or redefine them as subproperties)?

**Comment by mfhepp** [comment]
+1

**Comment by danbri** [comment]
The logic/philosophy literature around this (e.g. take a skim at http://plato.stanford.edu/entries/mereology/ ) is exactly why we have chosen not to attempt a more generalized account of parts. The notion is overloaded enough even when applied to document-like concepts. Thank you for the suggestion @unsteady but we have no plans in that direction.

A related and more experimental idea would be to collect up all the properties in schema.org which do feel "part-whole-like" and give them a common type or super-property. But where do you stop? It would certainly be interesting to see whether a collection of existing schema.org properties could be assembled which independent observers all agreed were relations between various wholes and their parts.

**Comment by thadguidry** [comment]
@unsteady hasPart and isPartof can also be thought of as static relationships.  Walking the nodes in a graph database can also highlight those relationships and give you a bigger picture of the whole and it's parts through discovery of various related properties.  Like Dimitris highlights in relfinder http://www.visualdataweb.org/relfinder.php Look at the Kill Bill and Pulp Fiction where you could say all those Persons found are part of those 2 movies.  With the right tools, you often do not need to statically assign Parts, you can just derive them automatically and use Metaschema (like we did in Freebase).

**Comment by danbri** [comment]
... one natural problem being that you don't expect cycles in a "partOf' graph, yet allowing so many different senses to count as 'parts' opens up possibilities for just this. For example if characters appearing in works means that they are part of the work, and if sections of works, alternate versions of works, formats, translations etc., are also works, it can get pretty tangled pretty quickly. Sometimes it is better to focus on more explicit relationships.

**Comment by unsteady** [comment]
@danbri @mfhepp @thadguidry Thanks for the comments. I know the conceptual difficulties underlying mereology and understand that schema.org should no more venture in them than it has with OWL subtleties. 
My point was more about terminology. If "isPartOf" and "hasPart" are used only for CreativeWork, what will be used for some Thing which has part(s) and is not covered by a specific attribute? 
Why about renaming the properties used for CreativeWork with a more specific name, like "isPartOfWork" and "hasPartWork" (or something less ackward)?

**Comment by danbri** [comment]
"or something less awkward" is where we always come unstuck. In the absence of a compelling proposal, we'll stick with the status quo. The difficulty of "isPartOfWork" is that it needs to read nicely with all the subtypes of CreativeWork too. I'll close out this issue for now, but thanks for the thought and discussion.

**Comment by elf-pavlik** [comment]
I brought pretty much same issue to the public-vocabs list few weeks ago
[sub/super (Event, Organization, Place, CreativeWork etc.)](https://lists.w3.org/Archives/Public/public-vocabs/2015Mar/0182.html)

**Comment by danbri** [comment]
Closing this for now. Discussion is on file in case we wake it up!
