### ISSUE TITLE
Legal Form (type of business) is missing for Organizations

### ISSUE THREAD

**Issue by vanthome** [schemaorg/schemaorg#452]
I've modelled some e-commerce related stuff in the past
and need to specify the legal form of business.
To describe legal form instances I came up with a vocab:

https://w3id.org/legal_form/
https://github.com/n-fuse/legal-form-vocab

What I would like to see in schema.org is a property on 
http://schema.org/Organization for this.
A sensible name would be `legalForm` I think.

I have also created a list with instances of the European legal forms:

https://github.com/n-fuse/legal-form-vocab/blob/master/legal_form-instances.jsonld

As you can see there are quite a lot and thus I think it
is pointless to have an enumeration in schema.org for now.
Therefore, the range(includes) should be `Thing` I guess.

**Comment by akuckartz** [comment]
:+1: for using SKOS
