### ISSUE TITLE
Proposed Comic artwork properties from bib extension should include domain of VisualArtwork(?)

### ISSUE THREAD

**Issue by dbs** [schemaorg/schemaorg#455]
Per #431 the proposal for Comic defines a number of new properties (artist, colorist, inker, letterer, and penciler) that are desired to describe Comics in a way that supports the Grand Comics Database (comics.org) description of comics in a straightforward manner (that is, without requiring Role reification).

It's not clear whether these properties, currently proposed for the "bib" extension, should include the domain of VisualArtwork. They would quite likely be useful, but as VisualArtwork is in "core" and the work is defined for a Comics context within the "bib" extension, it's not clear where the boundaries of extension proposals apply.

**Comment by danbri** [comment]
Yes, that would be fine and good. We want to encourage all terms to fit together nicely.

Extension-to-extension relations might be trickier, if only in terms of getting ux / navigation right. /cc @rvguha

**Comment by danbri** [comment]
@dbs can I close this? /cc @Dataliberate

**Comment by danbri** [comment]
ping @dbs/@dataliberate ... is this all folded in?

**Comment by dbs** [comment]
If you're asking "have you added VisualArtwork to the domain of the proposed Comic properties?" in your branch at https://github.com/dbs/schemaorg/commits/bibex_comics_coverart then the answer is no, but I can easily do that and will follow up with a pull request.

**Comment by danbri** [comment]
Yes that was what I should have asked :) thanks!
