### ISSUE TITLE
numberOfEmployees should be applicable to Organization

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#456]
https://lists.w3.org/Archives/Public/public-vocabs/2015Apr/0059.html

  why is the domain of <http://schema.org/numberOfEmployees> set to
schema:BusinessAudience? Shouldn't it be schema:Organization instead?

Although https://lists.w3.org/Archives/Public/public-vocabs/2015Apr/0060.html points out, some organizations might not have employees (e.g. a Residents' Association, or Anarchists Society, or many kinds of club), there are many kinds of organization for which an employee count is relevant. 

Regarding Scope, let's keep this fix simple. Context: It is also worth noting that some organizations have important relationships other than employment, and that schema.org does not enumerate all such relations.  For example, the students or alumni of a University are not employees. Similarly with companies and their owners, customers and contractors. If we were to attempt a general approach to counting, we would need to include time as a parameter (and probably model with Role).  There are also some discussions around other count-related properties, which like numberOfEmployees are hardcoded for a particular measure at a particular time (e.g. see offerCount, ratingCount, upvoteCount, downvoteCount, answerCount, UserPlays, screenCount, answerCount, wordCount, reviewCount). The point of this paragraph is to argue that a simple fix is the best action at this point.

Proposal:

* Add: numberOfEmployees domainIncludes Organization

This is worth doing immediately, without delaying for any broader discussion of other relationship types (e.g. http://schema.org/member), time-indexing, etc.  Note that there has also been some discussion about a generalized model for measurement, motivated by modeling concerns around sport, where many different kinds of thing are counted obsessively. See https://www.w3.org/wiki/WebSchemas/Measurement

**Comment by vholland** [comment]
+1 sounds good to me.

**Comment by chaals** [comment]
+1 for the record

**Comment by mfhepp** [comment]
It would make sense to include QuantitativeValue to the range of numberOfEmployees, for this will allow ranges (50 - 100 employees), or open intervals (up to 50, at least 5 employees).

**Comment by danbri** [comment]
@mfhepp  - I believe we do that already. http://schema.org/numberOfEmployees

**Comment by mfhepp** [comment]
You are right, sorry! No need for action.

**Comment by danbri** [comment]
Np, thanks for following the issue tracker :)
