### ISSUE TITLE
Documentation page should reflect current mailing list, group

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#457]
At:
http://schema.org/docs/documents.html

We currently find these two lines:
* [Schema.org Discussion Group](http://lists.w3.org/Archives/Public/public-vocabs/): public-vocabs@w3\.org - Forum for finding answers to questions, etc. The older discussion group is referenced [here](http://groups.google.com/group/schemaorg-discussion).
* Community discussions: the [W3C Web Schemas group](http://www.w3.org/wiki/WebSchemas) hosts a collection of [proposals] (http://www.w3.org/wiki/WebSchemas/SchemaDotOrgProposals) for additions and improvements to schema.org.

I won't detail all possible modifications (especially as the sponsors may wish to retain some of this information), but simply note the main points that should be updated
* The new mailing list is public-schemaorg@w3\.org (at <https://lists.w3.org/Archives/Public/public-schemaorg/>)
* There is now a Schema.org Community Group (at <https://www.w3.org/community/schemaorg/>)

On a related note, the [proposal page] (http://www.w3.org/wiki/WebSchemas/SchemaDotOrgProposals) linked on the existing Documentation page also makes two references to the deprecated list:
"Email discussion remains in the WebSchemas public-vocabs list here at W3C."
"Schema.org public discussions happen via the public-vocabs@w3\.org W3C mailing list for discussions."

**Comment by danbri** [comment]
Ok I believe this is fixed in sdo-gozer (queued up at sdo-gozer.appspot.com and webschemas.org for tire-kicking); I've also updated the W3C wiki somewhat. Thanks!
