### ISSUE TITLE
Fix navigation between DataType and its members, i.e. Boolean, Text, Date, DateTime, Time, Number 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#463]
The vocab issues #130 #218 are resolved. This issue tracks their python/navigation consequences.

Specifically the old treatment of DataType as a supertype of Boolean, Text etc gave us a nice list of "more specific types", allowing navigation from DataType to its members. We need to replace that.

See also https://github.com/schemaorg/schemaorg/wiki/AppEngine for some Python code that can run in http://localhost:8000/console when double-checking the live schema triples (running a pure standard RDFa parser against data/schema.rdfa will not exactly match what we are coding against).

Minimally:

- [ ] when we are on /DataType we should be able to get to /Boolean /Date etc.
- [ ] when we are on /Boolean, /Date etc we should be able to get to /DataType

We could avoid adding a quick regretable hack to the Python by (for now) simply updating the descriptions of these to use relative hyperlinks, but that is equally ugly. 

Cleaner?:

* If we are on a page for a schema.org term that subtypes Class (or hardcode for DataType),
 * make a list of "Types of this type"
   * for each type that is typeOf DataType, we'd link to it
* If we are on a page for a schema.org term that is typeOf DataType, e.g. Boolean, Text, Date, ...
  *  add a link back to DataType, "The type "Date" is a DataType type." or similar.
* When a DataType e.g. Number has subtypes such as Integer, Float, they should continue to show up as the usual "more specific types" list.
* Check that breadcrumbs hierarchy looks reasonable.

**Comment by danbri** [comment]
Also just noticed a failing test, since this modeling update broke isDataType() in api.py - will need fixing as part of this.

**Comment by danbri** [comment]
Also #469 - full.html needs attention.

Meanwhile isDataType() tests now pass although needs a closer look for subtypes.

**Comment by danbri** [comment]
I didn't get this fixed for the release. I intend to address it as a software fix rather than formal schema release and push out an update in a matter of days.

**Comment by danbri** [comment]
"matter of days" ... like 100s of days :(

**Comment by danbri** [comment]
That mostly fixed it! 

http://webschemas.org/DateTime still lacks breadcrumbs, even though http://webschemas.org/Number has breadcrumb link to its supertype and also links to subtypes.

**Comment by RichardWallis** [comment]
Fixed in 2.1
