### ISSUE TITLE
Clean out superfluous examples.txt files from bib merge

### ISSUE THREAD

**Issue by Dataliberate** [schemaorg/schemaorg#474]
bsdo-container-examples.txt was shipped by mistake - proposal didn't make the bib 1.0 cut.

bsdo-comic-examples.txt & comics-examples.txt are serving the same purpose but slightly differ in size.

@dbs can you check which is the correct version.

**Comment by dbs** [comment]
Good catch, @Dataliberate. I've addressed that in the referenced pull request (bsdo-comic-examples.txt represented an older version of comics-examples.txt, and I deleted bsdo-container-examples.txt).

**Comment by danbri** [comment]
Thanks both. Since bib: isn't in there yet, I'll move these down into data/ext/bib so they don't accidentally show up. I believe that's only likely for translation, but I think this is the best way to package extension examples anyway.

    grep TYPES data/bsdo-*txt
    data/bsdo-agent-examples.txt:TYPES: Agent
    data/bsdo-atlas-examples.txt:TYPES: Atlas
    data/bsdo-chapter-examples.txt:TYPES: Chapter
    data/bsdo-collection-examples.txt:TYPES: Collection
    data/bsdo-newspaper-examples.txt:TYPES: Newspaper
    data/bsdo-thesis-examples.txt:TYPES: Thesis, inSupportOf
    data/bsdo-translation-examples.txt:TYPES: CreativeWork,Book, translator, translationOfWork, workTranslation

**Comment by danbri** [comment]
done - https://github.com/schemaorg/schemaorg/commit/5c5350b0a38f94d75ff77a9565b4f5a1ad2b2fdd

**Comment by Dataliberate** [comment]
You need to do it for comics examples too.

BTW. The link to schemaVersion in the release notes for sdo-gozer has a random double quote on the end and so 404s.

~Richard


On 12 May 2015, at 17:32, Dan Brickley <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks both. Since bib: isn't in there yet, I'll move these down into data/ext/bib so they don't accidentally show up. I believe that's only likely for translation, but I think this is the best way to package extension examples anyway.

grep TYPES data/bsdo-*txt
data/bsdo-agent-examples.txt:TYPES: Agent
data/bsdo-atlas-examples.txt:TYPES: Atlas
data/bsdo-chapter-examples.txt:TYPES: Chapter
data/bsdo-collection-examples.txt:TYPES: Collection
data/bsdo-newspaper-examples.txt:TYPES: Newspaper
data/bsdo-thesis-examples.txt:TYPES: Thesis, inSupportOf
data/bsdo-translation-examples.txt:TYPES: CreativeWork,Book, translator, translationOfWork, workTranslation


-
