### ISSUE TITLE
Additional properties from extensions should be listed from core

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#475]
I think this is important for sdo-gozer: There should be a clickable link directly below a type indicating if there are additional properties from an extension, e.g.

Show additional properties from extension layers bib
Show additional properties from extension layers xyz

Ideally, that link would be a row in the table of properties, on the first position following the type name (e.g. below "Properties from Book").

The link should branch to the same type in the extensions layer.

It should also be made clearer whether properties and types from the extensions are to be used from within the core namespace or with the extension prefix. I think that only the former is feasible for developers. As  a side note: We should really test whether Web developers can understand the usage of elements from the extensions. I find it pretty hard, to be honest, but maybe a bit of additional page features can improve this.

**Comment by RichardWallis** [comment]
fixed in 2.1
