### ISSUE TITLE
JSON-LD example for extension mechanism on sdo-gozer malformed

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#483]
On:
http://sdo-gozer.appspot.com/docs/extension.html

the JSON for the bib.schema.org example is malformed, causing it to break in both the Linter and the SDTT.  Specifically, the code that reads:

```
  "author": "J.R.R Tolkien",
  "publisher": {
     "@type": "Organization",
  },
  "location": "United Kingdom",
  "name": "George Allen & Unwin",
 },
  "datePublished": "1954",
```

Should read:

```
  "author": "J.R.R Tolkien",
  "publisher": {
     "@type": "Organization",
    "location": "United Kingdom",
    "name": "George Allen & Unwin"
   },
  "datePublished": "1954",
```

A more general question about this too...

On this page we find two examples of markup in JSON-LD using reviewed extensions, one for bib.schema.org, another for gs1.schema.org.

```
<script type="application/ld+json">
{
  "@context": [ "http://schema.org/",
       { "bib": "http://bib.schema.org/" } ],
  "@id": "http://www.freebase.com/m/0h35m",
  "@type": "Book",
...
```

```
<script type="application/ld+json">
{
    "@context": "http://schema.org/",
    "@vocab": "http://gs1.schema.org/",
    "@id": "http://id.manufacturer.com/gtin/05011476100885",
    "gtin13": "5011476100885",
    "@type": "TradeItem",
...
```

I finally noticed the note after the second example (might be better before) that describes how @context can be used instead of @context + @vocab...

"Instead of writing "@context": "http://schema.org/", "@vocab": "http://gs1.schema.org/", it would be possible to simply write "@context": "http://gs1.schema.org/"

... but there's no mention in the documentation about the use of array to declare schema.org and bib.schema.org in the first example.

Is this just another of the "several variations" available using JSON-LD presented without annotation?

**Comment by jvandriel** [comment]
_"but there's no mention in the documentation about..."_

In regards the the unmentioned, what would be the microdata solution for the additional vocab?

**Comment by danbri** [comment]
Thanks, we'll do a minor update in a short number of days to fix a few non-schema things. This last release was a huge collection of changes (of all kinds). As we get the first extensions in, the extension documentation will also need to be improved substantially.

**Comment by dtjones** [comment]
Could we have a microdata example, is it as simple as just doing this?
 `<div itemscope itemtype="http://bib.schema.org/Book">`
