### ISSUE TITLE
Release snapshot format improvements

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#484]
Following #441 we have a simple "all in one page" snapshot view of each schema.org version.

This provides most definitions from schema.org versions at stable URLs. Initially:
- /version/2.0/

At this time the schema encoded in RDFa/RDFS is the canonical representation, and the HTML report is generated programmatically. This meta-issue tracks improvements to the generated HTML release summary page. We may regenerate the snapshot summary from the underlying schema data as this tooling improves, e.g. to provide better formatting and cross-referencing.

Known issues:
- [ ] enums are not represented in human-facing form
- [ ] page navigation is horrible
- [ ] page is gigantic and heavy - should we strip out the definitions, or split them into 1 main line + additional supporting text which might not need to be in the snapshot?
- [ ] other machine formats? JSON-LD, Turtle (TimBL was asking for), N-Quads.
- [ ] should back-port to previous releases.
- [ ] administrivia: document the release process in Wiki.
- [ ] use git tags.
- [ ] /version/x.y/ should link to /docs/releases.html#vx.y

**Comment by sopekmir** [comment]
Dan, I get 404 on http://schema.org/version/2.0/ 
Mirek

**Comment by Dataliberate** [comment]
Take a look at it here http://sdo-gozer.appspot.com/version/2.0/  - its not released yet.

~Richard

On 13 May 2015, at 15:12, sopekmir <notifications@github.com<mailto:notifications@github.com>> wrote:


Dan, I get 404 on http://schema.org/version/2.0/
Mirek

**Comment by danbri** [comment]
Yes, the point is a launch is imminent but there are some various things that need more attention/time. So this bug is linked from those version snapshot pages.

**Comment by danbri** [comment]
Ok, we're live. http://schema.org/version/2.0/

**Comment by mfhepp** [comment]
great! 

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by unor** [comment]
The "advice" link on http://schema.org/version/2.0/ is broken:

>     http://schema.org/version/2.0/github.com/schemaorg/schemaorg/issues

**Comment by danbri** [comment]
Doh, thanks @unor. I've silently fixed this in the live site. I didn't change the archived snapshot in data/releases/2.0/all-schema.html as 1. it isn't served anywhere 2. I think we've set expectations those HTML snapshots will be improved later, only the raw triples are frozen.

**Comment by danbri** [comment]
Closing as obsolete
