### ISSUE TITLE
Add a faq entry explaining something about the stats

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#489]
e.g. 
Q: What are the statistics?
A: Since April 2015 schema.org includes high level statistics on term usage. Note that these are from the public crawlable Web only, and do not reflect the use of schema.org in email or other non-public applications. For another source of similar data, see http://webdatacommons.org/

Update (2018): Since this hasn't been made a regular feature, we should also say something about the date (and outdatedness, maybe) of the usage data. I am working on an update though.

**Comment by unor** [comment]
Do the statistics come from a search engine index? May the source be disclosed? 

And could be added how old the statistics typically are? (e.g., how often they get updated by the source, or how often Schema.org gets new data)
