### ISSUE TITLE
Parent type for BroadcastService

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#493]
Currently [`BroadcastService`](http://schema.org/BroadcastService) is a direct child of `Thing`.

Can we make it a child of [`Service`](http://schema.org/Service), or some other type?

**Comment by danbri** [comment]
Thanks, sounds like a bug. I believe /Service was discussed as a parent. @vholland  ?

**Comment by vholland** [comment]
That is my recollection as well. In particular, inheriting the serviceArea property is needed. I'm guessing I missed adding the supertype when I modified the schema.

**Comment by unor** [comment]
Just found https://github.com/schemaorg/schemaorg/issues/315

**Comment by danbri** [comment]
Odd, it looks from #315 and https://github.com/schemaorg/schemaorg/commit/217ac4c8eb912ec5b0be6c2bd0a09ba7518534b7 that the supertype *was* added.

I've re-fixed it, and pushed the changes to work-in-progress builds on sdo-ganymede.appspot.com (our next release branch) + http://webschemas.org/BroadcastService which is a kind of volatile/wobbly upstream test site whose name doesn't change per-release.
