### ISSUE TITLE
AppEngine getting started doc needed (in Wiki)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#494]

**Comment by danbri** [comment]
* the site runs on google appengine
* pointers for installation
* reminders about Python on windows
* a note that rdflib/ library currently needed to run the unit tests

**Comment by shankarnat** [comment]
Hey @danbri I can take this up. While I ramped up on schema.org; I installed Python 2.7 on windows and set up google app engine etc and made it work E2E. But the point is it a pointer just for Windows.  I can make a doc or would try to do a 2 min video. What do you think ?

**Comment by danbri** [comment]
Great! I'd suggest starting with a simple Wiki page here in Github. Maybe write what you know about the Windows experience and we can abstract out what's common to osx, linux and windows later.

**Comment by benlk** [comment]
Making a note of the relevant wiki page: https://github.com/schemaorg/schemaorg/wiki/AppEngine
