### ISSUE TITLE
Unreviewed pull request backlog.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#495]
See https://github.com/schemaorg/schemaorg/pulls

We have a backlog of unreviewed pull requests. This is partly due to hours-in-the-day but also that they are sometimes not associated with first class issues. GitHub's UI treats pulls as pseudo-issues, but the default list of issues does not include them. 

Since various folk have been generous enough to contribute these specific change requests, this really needs fixing (both in terms of the backlog but also workflow. 

/cc @rvguha @ajax-als @tilid @chaals @vholland @tmarshbing @shankarnat @scor @mfhepp

**Comment by alex-jansen** [comment]
The Pull-request queue seems maneagable (less than 20 open issues), so closing this issue.
