### ISSUE TITLE
John wrote a book

### ISSUE THREAD

**Issue by Harald-Effenberg** [schemaorg/schemaorg#505]
Sorry for bothering again, but:

If I have a Webpage about a book, I can easily markup "This book was written by John", because there is the itemprop "author" for the type Book.

But what if I have a page about a Person? I can markup that John was born, that he married Jane and got three children Peter, Paul and Mary and that he died after all. And I am lucky if he performed in a Broadway-Show because of "performerIn".
But if he wrote a book? Climbed a mountain? Invented an inertia-less engine?

Shouldn't there be an itemprop "action" or "responsibleFor" or "caused" for a Person?

Kind regards
Harry

**Comment by danbri** [comment]
Yes, we have a type Action that seems close to what you are looking for. In Action terminology, the party responsible for causing the action is its "agent", hence 

* http://schema.org/agent
* http://schema.org/Action

There are a number of Action sub-types listed, while this isn't as open-ended as you might like it does give a basic pattern that you might extend. Hope this helps.

**Comment by danbri** [comment]
I'm going to close this issue on the hope that I've answered your question adequately; feel free to continue discussing here if more is needed (or to ask for it to be re-opened). Thanks for getting in touch!

**Comment by Harald-Effenberg** [comment]
Yes, but:

If I have a page about an Action (i.e. "writing a book"), I can markup a Person as the agent of the Action. That's okay.

But if a have a page about a Person? Who was agent in many actions? I would just have many entities on this page, one for each Action, wouldn't I? 

If I have a page about a famous man and his live, with all the data of his birth and his address and his history and I want to tell that one time, when he was a little boy, he climbed upon a tree and wasn't able to get back down:
The page becomes a page about a ClimbingTreeAction and the big man who is the main theme of the page is reduced to the agent who could not climb down.

This looks odd to me. Do you understand my concerns?

Best regards
Harry

**Comment by danbri** [comment]
Yes, it sounds like a concern about the direction in which the property is named.

Each notation (RDFa, Microdata, JSON-LD) has different tricks for dealing with this kind of thing. In each you can give URI identifiers to entities (@resource, @itemref, @id respectively). And in RDFa and JSON-LD there is also the option of a construction that reverses (@rev or @reverse) the direction of a property. Taken together (excuse the rushed overview) these give you ways of starting with a single entity of interest and then within that, listing other entities by relationship, even if the relationship name is in the "wrong" direction. If you do it by identifier/reference, you'd have the Person at the top level and then each of their Action entities alongside would have an 'agent' property whose value used the ID of that Person. If you used @rev/@reverse in RDFa or JSON-LD, you could put the Action entities nested inside the person but each indicated with @rev= or a "@reverse": { ... }  block.

**Comment by gkellogg** [comment]
This could also be a place to highlight the @itemprop-reverse feature added to the latest version of Microdata to RDF.

**Comment by unor** [comment]
@danbri You probably wanted to write `@itemid` instead of `@itemref`

**Comment by mfhepp** [comment]
@danbri btw, are there any news regarding the @itemprop-reverse feature proposal from 2014?

**Comment by gkellogg** [comment]
> On May 19, 2015, at 8:01 AM, Martin Hepp <notifications@github.com> wrote:
> 
> @danbri <https://github.com/danbri> btw, are there any news regarding the @itemprop-reverse feature proposal from 2014?
> 
Hi Martin, note that the @itemprop-reverse was added as a non-normative proposed feature to the latest Microdata to RDF note [1]. It has this status, as until there’s evidence that it’s actually used, Hixie won’t add it to the base Microdata spec (for good reasons). There are tests for this in the Microdata to RDF Test Suite [2], but I don’t know what the conformance level of this is.

What I’d like to see is for schema.org <http://schema.org/> examples that benefit from reverse properties make use of this, with some indication that the Structured Data Testing Tool will honor it, and the search engines do something reasonable with it (note that the Linter does make use of it). Until it’s in actual use, we won’t meet the pre-condition of having it as a normative feature.

The work is done, now it’s time for examples and evidence of real use in the wild. Without the examples, the evidence won’t appear.

Gregg

[1] http://www.w3.org/TR/microdata-rdf/#reverse-itemprop <http://www.w3.org/TR/microdata-rdf/#reverse-itemprop>
[2] http://w3c.github.io/microdata-rdf/tests/

**Comment by danbri** [comment]
@unor - Yes, I did mean @itemid, thanks! 

Re itemprop-reverse, I'll raise it within google. Also feel free to open a tracking bug here for schema.org documentation on the topic, rather than hiding it away within this relatively unrelated issue.
