### ISSUE TITLE
Range of datasetTimeInterval is DateTime which doesn't allow to express intervals

### ISSUE THREAD

**Issue by lanthaler** [schemaorg/schemaorg#506]
The property [datasetTimeInterval](http://schema.org/datasetTimeInterval) has a range of [DateTime](http://schema.org/DateTime) which is a point in time and not an interval. This seems wrong. Possible solutions could be to replace datasetTimeInterval with [validFrom](http://schema.org/validFrom) and [validThrough](http://schema.org/validThrough) or to introduce a new type able to express interval.s

**Comment by twamarc** [comment]
+1
BTW, do we have the predicate :timeInterval in schema?

**Comment by mfhepp** [comment]
A time interval can be modeled as schema:QuantitativeValue using minValue/maxValue and an appropriate unit code (SEC = seconds, MIN = minutes, HUR = hours, DAY = days; there are certainly more in the UN/CEFACT Common Code).

Open and closed intervals are also possible.

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp
