### ISSUE TITLE
Meta-Issue: Automotive Extension

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#509]
This is a meta-issue for collecting all input needed for the auto.schema.org extension.

Main tasks:
1. Create proper RDFa specification from remainders of the original submission.
2. Create final examples, taking into account the additional properties and the last-minute name changes in schema.org core.

Nearby: #704 for final review tracking.

**Comment by mfhepp** [comment]
For the examples, this pull-request is relevant: https://github.com/schemaorg/schemaorg/pull/482

**Comment by mfhepp** [comment]
For the record, this issue continues what is left to be done after the basic auto terms have been added to schema.org core, as per https://github.com/schemaorg/schemaorg/issues/262.

**Comment by danbri** [comment]
Two obvious tasks:

- [ ] @vholland kindly trimmed down the Car example based on my mistaken editing (sorry!), before we realised a bunch more properties were going to go into the Core layer. @mfhepp would you care to add back any properties to that example that are already now in Core?
- [ ] ext/auto/*rdfa has a rather messy file which needs to have the bits that are now in Core removed. Any chance you can take a look at that too?

**Comment by mfhepp** [comment]
Yes, I will handle that - what is your time-line for this?

**Comment by danbri** [comment]
time-line: I had a chat with @Dataliberate earlier about bib:, and we're aiming to have it wrapped up around the end of the month. Given that ESWC is 1st week June, how about aiming for the same with auto:?

**Comment by mfhepp** [comment]
Yes, that sounds doable.

**Comment by danbri** [comment]
Great! You might find also the notes in  #492 worth a glance. These are for medical/health which is different due to existing bulk of the extension being in core, but I've tried to sketch a list of questions that we should routinely be asking all extensions. This is fodder for a "how we work" doc I'm putting together...

**Comment by danbri** [comment]
Here's what we have in the filetree so far:

    rdfa data/ext/auto/auto.rdfa  | grep '#label'

    <http://schema.org/accelerationTime> <http://www.w3.org/2000/01/rdf-schema#label> "accelerationTime" .
    <http://schema.org/modelDate> <http://www.w3.org/2000/01/rdf-schema#label> "modelDate" .
    <http://schema.org/MotorizedBicycle> <http://www.w3.org/2000/01/rdf-schema#label> "MotorizedBicycle" .
    <http://schema.org/DriveWheelConfigurationValue> <http://www.w3.org/2000/01/rdf-schema#label> "DriveWheelConfigurationValue" .
    <http://schema.org/cargoVolume> <http://www.w3.org/2000/01/rdf-schema#label> "cargoVolume" .
    <http://schema.org/tongueWeight> <http://www.w3.org/2000/01/rdf-schema#label> "tongueWeight" .
    <http://schema.org/enginePower> <http://www.w3.org/2000/01/rdf-schema#label> "enginePower" .
    <http://schema.org/RentalVehicleUsage> <http://www.w3.org/2000/01/rdf-schema#label> "RentalVehicleUsage" .
    <http://schema.org/vehicleProductionDate> <http://www.w3.org/2000/01/rdf-schema#label> "vehicleproductionDate" .
    <http://schema.org/numberOfDoors> <http://www.w3.org/2000/01/rdf-schema#label> "numberOfDoors" .
    <http://schema.org/fuelCapacity> <http://www.w3.org/2000/01/rdf-schema#label> "fuelCapacity" .
    <http://schema.org/SteeringPositionValue> <http://www.w3.org/2000/01/rdf-schema#label> "SteeringPositionValue" .
    <http://schema.org/meetsEmissionStandard> <http://www.w3.org/2000/01/rdf-schema#label> "meetsEmissionStandard" .
    <http://schema.org/bodyType> <http://www.w3.org/2000/01/rdf-schema#label> "bodyType" .
    <http://schema.org/vehicleInteriorType> <http://www.w3.org/2000/01/rdf-schema#label> "vehicleInteriorType" .
    <http://schema.org/Motorcycle> <http://www.w3.org/2000/01/rdf-schema#label> "Motorcycle" .
    <http://schema.org/fuelType> <http://www.w3.org/2000/01/rdf-schema#label> "fuelType" .
    <http://schema.org/engineDisplacement> <http://www.w3.org/2000/01/rdf-schema#label> "engineDisplacement" .
    <http://schema.org/RightHandDriving> <http://www.w3.org/2000/01/rdf-schema#label> "RightHandDriving" .
    <http://schema.org/DrivingSchoolVehicleUsage> <http://www.w3.org/2000/01/rdf-schema#label> "DrivingSchoolVehicleUsage" .
    <http://schema.org/trailerWeight> <http://www.w3.org/2000/01/rdf-schema#label> "trailerWeight" .
    <http://schema.org/RearWheelDriveConfiguration> <http://www.w3.org/2000/01/rdf-schema#label> "RearWheelDriveConfiguration" .
    <http://schema.org/FrontWheelDriveConfiguration> <http://www.w3.org/2000/01/rdf-schema#label> "FrontWheelDriveConfiguration" .
    <http://schema.org/emissionsCO2> <http://www.w3.org/2000/01/rdf-schema#label> "emissionsCO2" .
    <http://schema.org/dateVehicleFirstRegistered> <http://www.w3.org/2000/01/rdf-schema#label> "dateVehicleFirstRegistered" .
    <http://schema.org/roofLoad> <http://www.w3.org/2000/01/rdf-schema#label> "roofLoad" .
    <http://schema.org/BusOrCoach> <http://www.w3.org/2000/01/rdf-schema#label> "BusOrCoach" .
    <http://schema.org/steeringPosition> <http://www.w3.org/2000/01/rdf-schema#label> "steeringPosition" .
    <http://schema.org/vehicleInteriorColor> <http://www.w3.org/2000/01/rdf-schema#label> "vehicleInteriorColor" .
    <http://schema.org/CarUsageType> <http://www.w3.org/2000/01/rdf-schema#label> "CarUsageType" .
    <http://schema.org/acrissCode> <http://www.w3.org/2000/01/rdf-schema#label> "acrissCode" .
    <http://schema.org/AWDriveWheelConfiguration> <http://www.w3.org/2000/01/rdf-schema#label> "AWDriveWheelConfiguration" .
    <http://schema.org/knownVehicleDamages> <http://www.w3.org/2000/01/rdf-schema#label> "knownVehicleDamages" .
    <http://schema.org/mileageFromOdometer> <http://www.w3.org/2000/01/rdf-schema#label> "mileageFromOdometer" .
    <http://schema.org/4WDriveWheelConfiguration> <http://www.w3.org/2000/01/rdf-schema#label> "4WDriveWheelConfiguration" .
    <http://schema.org/weightTotal> <http://www.w3.org/2000/01/rdf-schema#label> "weightTotal" .
    <http://schema.org/engineType> <http://www.w3.org/2000/01/rdf-schema#label> "engineType" .
    <http://schema.org/TaxiVehicleUsage> <http://www.w3.org/2000/01/rdf-schema#label> "TaxiVehicleUsage" .
    <http://schema.org/seatingCapacity> <http://www.w3.org/2000/01/rdf-schema#label> "seatingCapacity" .
    <http://schema.org/LeftHandDriving> <http://www.w3.org/2000/01/rdf-schema#label> "LeftHandDriving" .
    <http://schema.org/numberOfPreviousOwners> <http://www.w3.org/2000/01/rdf-schema#label> "numberOfPreviousOwners" .
    <http://schema.org/speed> <http://www.w3.org/2000/01/rdf-schema#label> "speed" .
    <http://schema.org/vehicleTransmission> <http://www.w3.org/2000/01/rdf-schema#label> "vehicleTransmission" .
    <http://schema.org/purchaseDate> <http://www.w3.org/2000/01/rdf-schema#label> "purchaseDate" .
    <http://schema.org/vehicleConfiguration> <http://www.w3.org/2000/01/rdf-schema#label> "vehicleConfiguration" .
    <http://schema.org/driveWheelConfiguration> <http://www.w3.org/2000/01/rdf-schema#label> "driveWheelConfiguration" .
    <http://schema.org/specialUsage> <http://www.w3.org/2000/01/rdf-schema#label> "specialUsage" .
    <http://schema.org/vin> <http://www.w3.org/2000/01/rdf-schema#label> "vin" .
    <http://schema.org/payload> <http://www.w3.org/2000/01/rdf-schema#label> "payload" .
    <http://schema.org/wheelbase> <http://www.w3.org/2000/01/rdf-schema#label> "wheelbase" .
    <http://schema.org/torque> <http://www.w3.org/2000/01/rdf-schema#label> "torque" .

**Comment by danbri** [comment]
There is now some basic UI for extensions now. Try http://auto.sdo-ganymede.appspot.com/MotorizedBicycle 

There are still some bugs (e.g. http://auto.sdo-ganymede.appspot.com/wheelbase says 'none' extension) and CSS + links to improve.

Are there any additional examples to come that accompany this extension? 

/cc @RichardWallis who is working on the Python lately

**Comment by danbri** [comment]
I believe a lot of the above properties ended up launched already. See http://schema.org/Vehicle 

@mfhepp - can you figure out which ones are still need to be added in the extension?

**Comment by danbri** [comment]
After talking with @mfhepp and @RichardWallis I have gone ahead and removed several properties. Further attention is needed on any I might have missed (e.g. that relate to supporting types) as well as those types themselves. I have not yet added isPartOf declarations.

Summary so far follows.

**Comment by danbri** [comment]
# Cleanup of data/auto.rdfa

This file has some terms that were in core. The list below began with all
terms defined in core (data/schema.rdfa) that are properties applicable to 
Vehicle. Note that this does not catch everything, see notes on supporting 
types inline below.

## Terms that weren't in auto.rdfa

* mileageFromOdometer
* knownVehicleDamages
* numberOfAirbags
* numberOfAxles
* numberOfForwardGears
* vehicleIdentificationNumber
* fuelEfficiency
* fuelConsumption
* cargoVolume

## terms removed from auto.rdfa today as they are in core:

* vehicleModelDate
* vehicleSeatingCapacity
* vehicleEngine
* dateVehicleFirstRegistered
* numberOfPreviousOwners
* steeringPosition # TODO: related type/props here SteeringPositionValue etc
* vehicleTransmission # TODO: similar
* vehicleInteriorColor
* numberOfDoors
* fuelType
* driveWheelConfiguration TODO: DriveWheelConfigurationValue etc.
* purchaseDate
* vehicleInteriorType
* vehicleConfiguration
* productionDate




## Modeling notes

Some props are generally useful, remove vehicle dependency:

* numberOfPreviousOwners
* productionDate
* purchaseDate

Definition(s) are confusing/vague and might be improve:

* knownVehicleDamages

**Comment by danbri** [comment]
See https://github.com/schemaorg/schemaorg/issues/429 for details of the isPartOf that needs adding  (I'll do that now).

**Comment by danbri** [comment]
@RichardWallis found some others which are now removed:

    INFO     2015-07-27 15:07:57,095 api.py:665] ERROR: RentalVehicleUsage trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,095 api.py:665] ERROR: LeftHandDriving trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,096 api.py:665] ERROR: RightHandDriving trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,096 api.py:665] ERROR: DriveWheelConfigurationValue trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,096 api.py:665] ERROR: FrontWheelDriveConfiguration trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,096 api.py:665] ERROR: DrivingSchoolVehicleUsage trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,096 api.py:665] ERROR: RearWheelDriveConfiguration trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,097 api.py:665] ERROR: SteeringPositionValue trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,097 api.py:665] ERROR: driveWheelConfiguration trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,097 api.py:665] ERROR: TaxiVehicleUsage trying to overwite home from core to http://auto.schema.org
    INFO     2015-07-27 15:07:57,098 api.py:665] ERROR: CarUsageType trying to overwite home from core to http://auto.schema.org

**Comment by danbri** [comment]
Last details:
##  rdfa auto.rdfa | grep DriveWheelConfigurationValue

    <http://schema.org/AWDriveWheelConfiguration> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DriveWheelConfigurationValue> .
    <http://schema.org/4WDriveWheelConfiguration> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DriveWheelConfigurationValue> .


## rdfa ../../schema.rdfa | grep DriveWheelConfigurationValue

    <http://schema.org/DriveWheelConfigurationValue> <http://www.w3.org/2000/01/rdf-schema#label> "DriveWheelConfigurationValue" .
    <http://schema.org/RearWheelDriveConfiguration> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DriveWheelConfigurationValue> .
    <http://schema.org/DriveWheelConfigurationValue> <http://purl.org/dc/terms/source> <http://www.w3.org/wiki/WebSchemas/SchemaDotOrgSources#Automotive_Ontology_Working_Group> .
    <http://schema.org/FourWheelDriveConfiguration> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DriveWheelConfigurationValue> .
    <http://schema.org/driveWheelConfiguration> <http://schema.org/rangeIncludes> <http://schema.org/DriveWheelConfigurationValue> .
    <http://schema.org/AllWheelDriveConfiguration> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DriveWheelConfigurationValue> .
    <http://schema.org/FrontWheelDriveConfiguration> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DriveWheelConfigurationValue> .
    <http://schema.org/DriveWheelConfigurationValue> <http://www.w3.org/2000/01/rdf-schema#comment> "A value indicating which roadwheels will receive torque." .
    <http://schema.org/DriveWheelConfigurationValue> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://schema.org/QualitativeValue> .
    <http://schema.org/DriveWheelConfigurationValue> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
