### ISSUE TITLE
Add enumerated values for http://schema.org/paymentStatus

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#518]
http://schema.org/paymentStatus takes text. It would be nice to also take defined values. Initially, we should support the following and maybe others.

PaymentComplete
PaymentDue
PaymentPastDue
PaymentDeclined

**Comment by vholland** [comment]
Implemented as pull request #523.

**Comment by chaals** [comment]
WfM. The feature creep in me looks for a partial payment made…

**Comment by mfhepp** [comment]
@chaals is right - we likely need a mechanism for deposits and partial payment. Would PartialPaymentReceived as an additional value be sufficient?

**Comment by danbri** [comment]
Per rough consensus in #587 I'm going to merge in #523. If there's interest her in addressing the partial payment / deposit angle, please continue here and we can refine.

**Comment by danbri** [comment]
Done (manually)

**Comment by danbri** [comment]
Looking at this, the enumeration wasn't showing up. I've tweaked the design from the pull request, s/Intangible/Enumeration/ and that does the job.

We might also consider that PaymentDue ("The payment is due, but still within an acceptable time to be received.") is named almost identically to the existing property http://schema.org/paymentDue ("The date that payment is due."). I would prefer not to do this - can we rename it to something more distinctive?

Related (if only by similar name) existing terms: 

* http://schema.org/OrderPaymentDue
* http://schema.org/totalPaymentDue
* http://schema.org/minimumPaymentDue

**Comment by danbri** [comment]
See http://webschemas.org/PaymentStatusType for current release candidate (also in sdo-ganymede)

**Comment by vholland** [comment]
+1 OrderPaymentDue

**Comment by danbri** [comment]
That's from a different enumeration called http://schema.org/OrderStatus whose values are already:

OrderCancelled
OrderDelivered
OrderInTransit
OrderPaymentDue
OrderPickupAvailable
OrderProblem
OrderProcessing
OrderReturned

Are these two views of the same transactions? I don't know if one enumerated value being in both enumerated lists will work very well (technically, at least).

**Comment by danbri** [comment]
action: danbri test if multiple typing works

**Comment by scor** [comment]
Note that http://schema.org/OrderStatus and http://schema.org/orderStatus also both exist. I agree this should be avoided.

Since enumeration items are types in schema.org, this is prone to happen again. Is there a lot of value in having those as types as opposed to literal values which would not be clashing with the types?

**Comment by danbri** [comment]
Looking at this for the upcoming release, I am wary of (a) having one term (OrderPaymentDue) appear in two enumerations, as this will confuse navigation. The option (b) of converging the two lists I also believe unappealing, as they currently each address different situations: http://schema.org/OrderStatus vs http://sdo-ganymede.appspot.com/PaymentStatusType.

I believe the simplest fix which allows us to proceed and improves clarity of existing terms is for the current paymentDue property to migrate to an new more explicit name: paymentDueDate.

* http://schema.org/paymentDue{Date} ("The date that payment is due."). I'll queue that up for review.

**Comment by danbri** [comment]
rdfa schema.rdfa | grep -i date | grep Property | awk '{print $1}'
        <http://schema.org/productionDate>
        <http://schema.org/scheduledPaymentDate>
        <http://schema.org/orderDate>
        <http://schema.org/liveBlogUpdate>
        <http://schema.org/candidate>
        <http://schema.org/dateModified>
        <http://schema.org/datePublished>
        <http://schema.org/releaseDate>
        <http://schema.org/candidate>
        <http://schema.org/endDate>
        <http://schema.org/dateline>
        <http://schema.org/startDate>
        <http://schema.org/dissolutionDate>
        <http://schema.org/uploadDate>
        <http://schema.org/vehicleModelDate>
        <http://schema.org/deathDate>
        <http://schema.org/foundingDate>
        <http://schema.org/dateCreated>
        <http://schema.org/purchaseDate>
        <http://schema.org/dateIssued>
        <http://schema.org/birthDate>
        <http://schema.org/previousStartDate>
        <http://schema.org/guidelineDate>
        <http://schema.org/dateVehicleFirstRegistered>
        <http://schema.org/datePosted>

Bit of research to answer the question...

Q: Should property names end with 'date' or start with 'date'?
A: Yes.

**Comment by vholland** [comment]
We also confuse 'date' and 'time'. See issue #524

**Comment by danbri** [comment]
Ok, I think we're done here. Please review c/o http://sdo-ganymede.appspot.com/docs/releases.html#sdo-ganymede
