### ISSUE TITLE
What is the best way to mark up structured, crowdsourced content that can rapidly improve?

### ISSUE THREAD

**Issue by greaber** [schemaorg/schemaorg#520]
I notice that Quora questions/answers/comments don't ever seem to get snippet treatment on Google.  Is this because they are not marked up as articles?  But what would be the correct way to mark them up (or to mark up Wikipedia articles, github issues, etc.)?  articleBody seems possibly inappropriate because the content changes so much over time (not to mention that the content has structure that articleBody would ignore).

**Comment by mfhepp** [comment]
I think it is better to reserve Github for development-related discussions. For general conceptual modeling issues around schema.org, the following mailing lists are a better place:

schema.org Mailing List <public-schemaorg@w3.org>
W3C Web Schemas Task Force <public-vocabs@w3.org>

For questions related to the specific consumption of schema.org by a single search engine, please use the respective product forums, like

    https://productforums.google.com/forum/#!forum/webmasters

In general, it is important to understand that search engines use schema.org in many different ways, and Rich Snippets or Rich Captions are just one of those. See e.g. 

    http://wiki.goodrelations-vocabulary.org/GoodRelations_for_Semantic_SEO

**Comment by danbri** [comment]
Yes, this forum is for the development of schema.org itself. For Google products, https://productforums.google.com/forum/#!categories/webmasters/structured-data is a more appropriate place to seek answers. In general schema.org provides a kind of 'dictionary' of terms that can be used (or not used) in many different ways, so it is usually better to check the documentation for applications first. In the case of Google, http://developers.google.com/structured-data/ is a pretty good entry point.
