### ISSUE TITLE
http://schema.org/CollectionPage should have a containsCollection property

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#522]
http://schema.org/CollectionPage allows authors to specify a page is a collection like an image gallery, but there is no way to specify what is in the collection.

We should add a "containsCollection" property to specify the collection.

**Comment by jvandriel** [comment]
Don't the ```mainEntity``` and ```mainEntityOfPage``` already handle this?

**Comment by vholland** [comment]
I originally thought of that, but it gets a little odd if the page is a set of images. Using `mainEntity` seems odd to use many times on the same page. I suppose authors could wrap the collection up in a list and make that the `mainEntity`.

**Comment by jvandriel** [comment]
_"I suppose authors could wrap the collection up in a list..."_

Exactly, anduring the discussions about ```schema.org/ItemList``` @Dataliberate agreed that for expressing a curated list a multi-type entity like ```["http://schema.org/CreativeWork", "http://schema.org/ItemList"] would be fine. 

So do do you still see the for need a ```containsCollection``` property than?

**Comment by vholland** [comment]
Sounds good to me. I will close this issue and add another requesting we update the examples to use this pattern.
