### ISSUE TITLE
Need to clean up startTime vs startDate

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#524]
The description for http://schema.org/startTime says:

> Note that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.

The phrase "start time" makes more sense in certain contexts than "start date", but http://schema.org/startDate is more heavily used. Is there any reason not to combine to one property?

**Comment by danbri** [comment]
I think last time we discussed this we hadn't got any notion of 'supersededBy' or suchlike... so were more cautious about changes.

**Comment by twamarc** [comment]
I have been using startDate/endDate for events in general where no time is expected; and startTime/endTime where date and time is expected. I think it makes sens to keep both. 

Of course if we accept that startDate/endDate can also have date and Time as object then startTime/endTime becomes obsolete.

**Comment by vholland** [comment]
Wee have done this in dribs and drabs. Closing in favor of opening a more targeted proposal.
