### ISSUE TITLE
Product Category as a text value comes back as invalid

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#536]
https://developers.google.com/structured-data/testing-tool/?url=https://www.holylandshopping.com/collectibles/6378-pope-john-paul-two-the-holy-land-commemorative-medal-cpm02.html even though it says you can use a text value on https://schema.org/Product

**Comment by danbri** [comment]
hi! We can't support Google products here. You might try https://productforums.google.com/forum/#!categories/webmasters/structured-data ...

(if this reflects a recent change at schema.org it might just be that the google tool is not yet updated)

**Comment by inetbiz** [comment]
The same invalid markup showed up on Yandex tester, too. @danbri https://webmaster.yandex.com/microtest.xml

**Comment by mfhepp** [comment]
FYI: As of today, the Google Structured Data Testing Tools says the markup is valid.

**Comment by inetbiz** [comment]
@mfhepp because I removed category attribute from product.
