### ISSUE TITLE
Discussion Schema transplanted from W3C Discussion for Internet forum topics/threads

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#542]
I have created a **[wiki page](https://github.com/schemaorg/schemaorg/wiki/Discussion-Schema)** that migrates most of what was discussed around Discussion Schema.

**Comment by akuckartz** [comment]
Plesse align with Activity Streams 2.0 and W3C Social Web WG.

**Comment by danbri** [comment]
+cc @elf-pavlik, our resident social Web alignment activist :)

**Comment by danbri** [comment]
p.s. thanks!

**Comment by elf-pavlik** [comment]
:+1: +@scor
seeAlso #526
