### ISSUE TITLE
Need a way to express room number in Event location

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#545]
For many events, the location includes a room name. Schema.org should support a way to specify the room.

In some cases, rooms have numeric names containing floor and room number. For example, [MIT's 26-100](https://whereis.mit.edu/?go=26).

In other cases, the room name has no location information embedded in it. For example, Stanford's [Berg Hall](https://events.stanford.edu/events/496/49631/) within the Li Ka Shing Center. Schema.org would need separate properties if we want to get to the level of floor number, etc.

**Comment by danbri** [comment]
Are you thinking that this would be a property added to PostalAddress, or Place? Or directly on the Event?

Use case seems perfectly reasonable.

**Comment by vholland** [comment]
I was thinking PostalAddress. However, if people want to be able to add properties to the room (floor number for example), maybe it should be a Place. I was hoping people would chime in before I started working on an implementation.

**Comment by mfhepp** [comment]
Maybe it is cleaner to first define a subtype schema:Room for schema:Place and then maybe add room-specific properties?

**Comment by jvandriel** [comment]
Might I suggest to have a look at how this is resolved in the acocmodation ontology http://ontologies.sti-innsbruck.at/acco/ns.html, something which might help extend schema.org/Hotel's properties as well?

**Comment by mfhepp** [comment]
I assume you have seen the "author" line at  http://ontologies.sti-innsbruck.at/acco/ns.html ;-) ?

Yes, indeed, I suggest that that ontology should be a starting point for a hotel extension for schema.org, because it is already aligned with additionalProperty and the commercial model in schema.org, i.e. room pricing will be straightforward.

**Comment by jvandriel** [comment]
_"I assume you have seen the "author" line at..."_

Yup, I was just wondering whether you were hesitant in mentioning it yourself, so I thought I might as well go ahead and do it.   :)

**Comment by vholland** [comment]
I was weighing two options:

1. Add a roomName to PostalAddress.
    - *Pros*: Simple markup
    - *Cons*: A semantic dead end

2. Something that works with the Accommodation Ontology. Room is a subtype of Place and can be containedIn another Place.
   - *Pros*:  Semantically rich, can hook into other ontologies
   - *Cons*: The markup is complicated

**Comment by mfhepp** [comment]
FYI: I am working on a pull request for turning the Accommodation Ontology into a proper schema.org extension, which will give us a clear model for rooms in hotels and also other scenarios. Expect it in June.

**Comment by vholland** [comment]
@mfhepp Great! Do you know where you will plug this in? In other words, how can I express an event is in a particular lecture hall at a university?

**Comment by mfhepp** [comment]
I think (not yet firmly) that there will be subtypes of http://schema.org/Place, namely schema.org:HotelRoom and schema:MeetingRoom, or simply schema:Room. roomNumber should then be a property thereof. Then, you can use schema:Event -> location > schema:MeetingRoom -> roomNumber.

How does that sound?

(What we need to fix is how the rooms are included in hotel offers, but I have an idea for that).

**Comment by rvguha** [comment]
Not sure what you mean by 'semantic dead end'

guha

**Comment by vholland** [comment]
@rvguha I meant that if we go with a roomName property, we can't later add the capacity of the room or other properties.

**Comment by vholland** [comment]
@mfhepp It sounds promising. It would be nice to support the simple case of schema:Room, so we don't have to enumerate all of the possible room types.

**Comment by Aaranged** [comment]
+1 to suggestion from @mfhepp.

Re "simple case of schema:Room" wouldn't it be possible to create that, and
the required property "roomNumber" without needing to enumerate more
specific sub-types?

**Comment by mfhepp** [comment]
I actually think we will need all three - schema:Room (any room), schema:HotelRoom (a room for temporary lodging), and schema:MeetingRoom. But let's wait for my accommodation proposal. It should also cover this issue.

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by akuckartz** [comment]
@mfhepp Any news regarding `schema:Room` ?

**Comment by mfhepp** [comment]
Pretty high on my todo-list, but still pending ;-)

**Comment by danbri** [comment]
ping @mfhepp - anything to share?

**Comment by mfhepp** [comment]
room number will be in the hotel pull request, preview: 

http://sdo-hotels.appspot.com/roomNumber

will be finished and shared officially today.

**Comment by mfhepp** [comment]
Currently, we have

http://sdo-hotels.appspot.com/HotelRoom
and
http://sdo-hotels.appspot.com/MeetingRoom

I could add a generic "Room" supertype if that helps in other applications. We could also merge all of them into one Room type, but actually I think the distinctions matter (HotelRooms have beds, MeetingRooms are a very particular kind of room often offered by business hotels).

Shall I add a Room supertype to the hotels proposal?

**Comment by RichardWallis** [comment]
Whilst we are changing PostalAddress we should add 'apartment' or similar.

**Comment by RichardWallis** [comment]
*Shall I add a Room supertype to the hotels proposal?*

+1

**Comment by danbri** [comment]
@mfhepp can you make roomNumber work on PostalAddress? @vholland would that help here?

**Comment by mfhepp** [comment]
@danbri @vholland yes, no problem. will be included.

**Comment by vholland** [comment]
+1 to a generic Room type for the odd cases we don't want to enumerate.

Yes, adding roomNumber to PostalAddress helps.

**Comment by rvguha** [comment]
Why do we need such a super type? How is such a generic room different from
say, my dining room?

guha

**Comment by vholland** [comment]
My thinking for a generic super type was that there are a lot cases we probably don't want to enumerate. For example, hotel ballrooms and movie theater screening rooms sometimes have room numbers. We could called these "meeting rooms", but it seems easier to have a super type.

**Comment by chaals** [comment]
I'm not sure about adding different types of rooms. I wonder if I can book Guha's dining room for a wild party - but even if not, I don't think the room type is the key bit there so much as the service provided in the first place (e.g. hotel, fitness centre, sauna, restaurant, business centre - all of which might be available in a typical expensive hotel in most countries I have visited).

The standard spanish or russian address both often require street number, building number, entrance number, floor number, and actual door number. At my basic street address I live in one of half a dozen apartments numbered 1B - which is recognised by most people as short hand for Floor: 1º Door: B but is often recorded in long form.

There are "extra instructions" of all kinds. E.g. for delivery addresses: 
"To attention RV Guha, I'd like to book your dining room with double bunk beds for my next visit to California…" 

Addresses are hard.

(NB @mfhepp I'm not sure what a CaliforniaKing is compared to other kinds, but "twin" beds are extremely common in Europe at least, and bunkbeds are not that uncommon in places people book as if they were hotels).

**Comment by vholland** [comment]
It seems like there are two use cases for "roomNumber":

1. Navigating to the building/floor/room where an event is being held whether that is a gala in a ballroom or dinner in Guha's dining room.
2. Reserving a hotel room or some other accommodation.

Can we split these use cases to make progress on each in parallel?

For the first, adding "roomNumber" (or some other property name) to PostalAddress seems sufficient. As @chaals said, addresses are hard.

For the second, we should run through some use cases to determine what information is already up on the web that could use markup.

**Comment by chaals** [comment]
For the first - finding a place in more detail, I think we want something like "moreInformation" - which is what people who do deliveries tend to have, allowing you to put "attention So-and-so" or "use the key under the doormat to open the chiimney cover, let yourself in, drink the whisky and leave the presents", or "door number 37A, hidden behind the door numbered 30s" or whatever.

For the second, I don't think this is what we are looking for. You reserve something, you get a place, which has an address or way to identify it, and you get a service (accommodation, wedding, schema.org development lesson, …). What you are reserving is more part of a service description - and that is where e.g. @mfhepp 's hotel extension giving more precise detail will actually be useful.

**Comment by vholland** [comment]
Where are we on this? Can we break the larger proposal down into smaller parts so we can move forward?

**Comment by mfhepp** [comment]
Room number is in the hotel proposal

http://sdo-hotels.appspot.com/Room

http://sdo-hotels.appspot.com/roomNumber

I will finalize the proposal and send a pull request shortly.

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by mfhepp** [comment]
Chaals:


> On 29 Sep 2015, at 16:01, chaals <notifications@github.com> wrote:
> 
> (NB @mfhepp I'm not sure what a CaliforniaKing is compared to other kinds, but "twin" beds are extremely common in Europe at least, and bunkbeds are not that uncommon in places people book as if they were hotels).


I have changed that in the proposal - you can now either use a text for the bed type or create your own instance of a http://sdo-hotels.appspot.com/BedType and attach a name, description, and image.

This is a simpler mechanism than having hard-wired enumerations in the vocabulary but still allows adding images and descriptions to bed types.

Martin

**Comment by RichardWallis** [comment]
Still think it would be useful to add roomNumber to Address.

~Richard.

**Comment by danbri** [comment]
@mfhepp - can you file an issue for the hotel room / accomodation topic, so that when the pull request comes it addresses the problem recorded in the issue? Am I right that we don't have a PR for http://sdo-hotels.appspot.com/docs/hotels.html yet? Is https://github.com/mfhepp/schemaorg/tree/hotels the place where it is being developed?

**Comment by couloir007** [comment]
I work for a museum, and would like to add room to events, and I'm trying to follow along here. Is the Room location in sdo-hotels proposed for Schema.org and not official yet, or is some subset for hotels only? Seeing this has all happened recently, I can understand if it still fails verification with Google.

Thank you,
Sean

**Comment by Aaranged** [comment]
@couloir007 A more specific type of room in sdo-hotels is:
http://sdo-hotels.appspot.com/MeetingRoom
... which might meet your needs.

However, as per the breadcrumb path above "Room" is currently constituted as a more specific type of:
http://sdo-hotels.appspot.com/Accommodation

Pinging @philbarker - I strongly suspect, based on my prior work on modelling brick-and-mortar courses, that a "Room" property will also be required by the course schema(s), since the current scope of the course extension encompasses "any type of educational course".

**Comment by mfhepp** [comment]
Note that the fact that MeetingRoom is a subtype of Accommodation should not bother you, because the latter is essentially anything that can accommodate human beings, see the definition:

"An accommodation is a place that can accommodate human beings, e.g. a hotel room, a camping pitch, or a meeting room. Many accommodations are for overnight stays, but this is not a mandatory requirement. For more specific types of accommodations not defined in schema.org, one can use additionalType with external vocabularies."

Martin


-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by mfhepp** [comment]
The hotels extension is not yet part of the live version of schema.org, but I hope we can get it into the next release.

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by couloir007** [comment]
Thank you for the responses. I've commented out the Room for now until it validates, but probably doesn't much matter at this point. Being new to Schema.org, I'm still learning how best to implement it. Would the Room an event takes place in at a Museum be containedInPlace, as in the event is in a Room with an address at a Museum, or at a Museum with an address that containsPlace Room?

**Comment by Aaranged** [comment]
Thanks @mfhepp.  While I've doubtlessly got the modelling backwards, could this schema conceivably be employed in this fashion to declare a room location?

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "Vocabulary Builders Meetup",
  "startDate": "2016-02-14T21:30",
  "location": {
    "@type": "MeetingRoom",
    "roomNumber": "DV 1146",
    "containedInPlace": {
      "@type": "Place",
      "name": "William G. Davis Building",
      "address": {
        "@type": "PostalAddress",
        "addressLocality": "Mississauga",
        "addressRegion": "ON",
        "postalCode": "L5L 1C6",
        "streetAddress": "3359 Mississauga Rd"
      }
    }
  }
}
</script>
```

**Comment by vholland** [comment]
If this hasn't been needed in 4 years, we can probably close the issue until there is a driving use case.
