### ISSUE TITLE
Text value for homeLocation validates: should it?

### ISSUE THREAD

**Issue by barrycarter** [schemaorg/schemaorg#546]
Google validates the following:

````<td itemprop="homeLocation">Kansas City, Missouri, United States</td>````

even though it's plain text, and not a contactPoint or Place.

Is this valid?

Also, does Google geocode this and understand I'm referring to a specific city at a specific location, or does it just view it as arbitrary text?

**Comment by danbri** [comment]
@barrycarter thanks for the note. However we have over 200 open issues here, if we start accepting issues on Google's products (even if schema.org related) we'll be overwhelmed. Not to mention, Yandex, Bing, etc products too...

https://productforums.google.com/forum/#!forum/webmasters is a better place for Google-oriented questions.

Re plain text, http://schema.org/docs/datamodel.html does note 

"Conformance
While we would like all the markup we get to follow the schema, in practice, we expect a lot of data that does not. We expect schema.org properties to be used with new types. We also expect that often, where we expect a property value of type Person, Place, Organization or some other subClassOf Thing, we will get a text string. In the spirit of "some data is better than none", we will accept this markup and do the best we can."

**Comment by barrycarter** [comment]
Fair enough. I do believe schema.org gains a great deal of its popularity because it's supported by Google and Microsoft, so it might be prudent to notify Google their validator is imperfect.

Followup questions:

  - Is there a better/stricter validator?

  - Given a choice between using "text" and "Place" for "Location" data, I should use Place, yes, and not assume geocoding?
