### ISSUE TITLE
Schema.org website has no favicon

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#548]
http://schema.org/ neither links to a favicon (with the [`icon` link type](http://www.w3.org/TR/2014/REC-html5-20141028/links.html#rel-icon)) nor does it provide a favicon at [`/favicon.ico`](http://schema.org/favicon.ico).

(I’m not sure, but wasn’t there a favicon some time ago?)

Proposal: Add a favicon.

It makes identifying tabs easier etc.

**Comment by danbri** [comment]
Yeah, I've been meaning to try downsizing http://philarcher.org/diary/2012/danbri/schema.org.png as a way of avoiding the larger, hairier problem of making a logo. At favicon scale http://philarcher.org/diary/2012/danbri/schema.org.png is basically a circle. Unless a better idea comes along...

**Comment by jvandriel** [comment]
How about this instead: https://drive.google.com/open?id=0Bz0mLSkD2kqjWDVsT1l3cV9ZUDQ&authuser=0

If you like it, here are some different sizes for apps as well (+ico file) as well as a text file showing what needs to be included in the <head>:
- https://drive.google.com/open?id=0Bz0mLSkD2kqjekVqTHVhOGFadDQ&authuser=0
- https://drive.google.com/open?id=0Bz0mLSkD2kqjS3NsTy1RMnVwLW8&authuser=0

**Comment by Dataliberate** [comment]
Or this: https://dl.dropboxusercontent.com/u/2064477/schemaicon.png

~Richard

On 27 May 2015, at 15:02, jvandriel <notifications@github.com<mailto:notifications@github.com>> wrote:


How about this instead: https://drive.google.com/open?id=0Bz0mLSkD2kqjWDVsT1l3cV9ZUDQ&authuser=0

If you like it, here are some different sizes for apps as well (+ico file) as well as a text file showing what needs to be included in the :

  *   https://drive.google.com/open?id=0Bz0mLSkD2kqjekVqTHVhOGFadDQ&authuser=0
  *   https://drive.google.com/open?id=0Bz0mLSkD2kqjS3NsTy1RMnVwLW8&authuser=0

**Comment by Aaranged** [comment]
+1 to the "triple" from @jvandriel.  Yours is obviously on-point @Dataliberate, but it renders poorly at smaller resolutions - and especially the 16x16 px resolution used by browsers:

https://drive.google.com/open?id=0B1P5ObsnmRcSUFVJY19oWU9zN3M&authuser=0

**Comment by mfhepp** [comment]
I would use a very simple favicon, e.g. just a red dot. Mind trademark violations, though!

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by rvguha** [comment]
we need a community vote on this :)

guha

**Comment by rvguha** [comment]
my vote goes to the simple 'schema.org' on 2 lines from Richard

guha

**Comment by mfhepp** [comment]
+1 to guha's vote

**Comment by rtroncy** [comment]
My vote would also go on schema.org written on 2 lines, so the 2nd line of https://drive.google.com/open?id=0B1P5ObsnmRcSUFVJY19oWU9zN3M&authuser=0

**Comment by twamarc** [comment]
It will be tricky to summarize/count the responses here. Maybe votes using google form can help

**Comment by danbri** [comment]
Much as I love triples (thanks @jvandriel :), I think a good part of our success comes from protecting (most  :) publishers from such notions, so I lean towards the simple 2-line text option. 

I'm happy to consult and debate more but to figure out the appengine implementation details and see this in context, I've committed a version of @Dataliberate's: see http://sdo-ganymede.appspot.com/Person (I haven't looked into state of the art, alternate sizes etc., just used some Web tool which resulted in: docs/favicon.ico: PNG image data, 64 x 64, 16-bit/color RGB, non-interlaced

As @Aaranged anticipates, this is going to be all but unreadable by most mortals. However it does serve the main purpose which is to have a blob of the appropriate colours visible in a browser tab. If anyone cares to set up an icon beauty/usability competition via google forms or whatever that might be fun...
