### ISSUE TITLE
Non- terrestrial places

### ISSUE THREAD

**Issue by barrycarter** [schemaorg/schemaorg#550]
As we look to the future, we already have named places and man-made structures on the Moon and other planets. Additionally, astronomers and even casual stargazers have a need to identify and locate non-terrestrial places.

Could we either add a field for this (eg, "ExtraTerresterialPlace") or modify Place to allow for non-Terran locations?

**Comment by mfhepp** [comment]
http://schema.org/Place already includes this option.

Let's focus on parts of schema.org that have immediate use-cases.

**Comment by barrycarter** [comment]
Which option in Place could be used to identify Mare Imbrium, for example?

I might be understanding schema.org's mission, but there are hundreds of astronomy sites out there and a lot of structured data available for planets, satellites (both natural and man-made), and stars.

Is there a reason this data would not qualify as part of schema.org's mission?

**Comment by mfhepp** [comment]
This will do the trick:

    <div itemscope itemtype="http://schema.org/Place">
        <span itemprop="name">Mare Imbrium</span>
        <link itemprop="sameAs" href="http://en.wikipedia.org/wiki/Mare_Imbrium" />
    </div>

I agree that the current mechanisms for modeling location and spatial arrangement are earth-centric (e.g.  longitude and latitude over the earth surface). But I see no reason to add mechanisms for modeling coordinate systems for other celestial bodies  in schema.org core. 

We might add subtypes to schema:Place for astronomical objects. But I think such should rather go into an extension like astro.schema.org.

As of now, you can use additionalType to be pretty precise about your data:

    <div itemscope itemtype="http://schema.org/Place">
		<link itemprop="additionalType" href="http://www.productontology.org/id/Brown_dwarf" />
        <span itemprop="name">Luhman 16</span>
		<span itemprop="description">Luhman 16 (WISE 1049−5319, WISE J104915.57−531906.1) is a binary brown-dwarf system in the southern constellation Vela at a distance of approximately 6.6 light-years (2.0 pc) from the Sun. They are the closest known brown dwarfs, and the closest system found since the measurement of the proper motion of Barnard's Star in 1916.>/span>
        <link itemprop="sameAs" href="http://en.wikipedia.org/wiki/Luhman_16" />
    </div>

**Comment by danbri** [comment]
I think Place is fine. 

GeoCoordinates and GeoShape have unarticulated assumptions - not only about which planet, but also that we are using WGS84 coords etc.

It would certainly be interesting if lots of astronomical data were being published and wanted to use schema.org, but it feels like a relatively niche interest. As Martin says we can probably find idioms using existing vocabulary for now; and perhaps that might inspire someone to explore an http://schema.org/docs/extension.html ...

**Comment by pigsonthewing** [comment]
Thank you; I do.

I would suggest allowing the specification of the globe (i.e. Moon, Mars, etc; assuming "Earth" to be the default), and the geodetic system if not the default for that globe (i.e. other than WGS84 on Earth) 

If you do use "sameAs", please use Wikidata, not Wikipedia, URIs, as the latter are more prone to link-rot when articles are moved (renamed).

For example, Mare Imbrium, would be "sameAs"  https://www.wikidata.org/entity/Q487895

**Comment by Dataliberate** [comment]
+1 for Wikidata URIs

~Richard

On 28 May 2015, at 17:18, Andy Mabbett <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you; I do.

I would suggest allowing the specification of the globe (i.e. Moon, Mars, etc; assuming "Earth" to be the default), and the geodetic system if not the default for that globe (i.e. other than WGS84 on Earth)

If you do use "sameAs", please use Wikidata, not Wikipedia, URIs, as the latter are more prone to link-rot when articles are moved (renamed).

For example, Mare Imbrium, would be "sameAs" https://www.wikidata.org/entity/Q487895

**Comment by jvandriel** [comment]
_"For example, Mare Imbrium, would be "sameAs" https://www.wikidata.org/entity/Q487895"_

Nitpicky question:
Wouldn't ```"additionalType": "https://www.wikidata.org/entity/Q487895"``` make more sense here as opposed to using the ```sameAs``` property?

**Comment by danbri** [comment]
See also mail thread: https://lists.w3.org/Archives/Public/public-schemaorg/2015May/0038.html

**Comment by mfhepp** [comment]
@jvandriel re additionalType - no, because the entity mentioned in the example is an instance of Brown_dwarf, but the same individual as https://www.wikidata.org/entity/Q487895.

As a general rule: use additionalType for www.productontology.org types and sameAs for Wikidata/DBPedia/Freebase URIs (with the exception of the relatively few URIs for types classes in those four).

**Comment by jvandriel** [comment]
I think I'm finally starting to understand the difference @mfhepp - thanks - but just to make sure I understand the difference, do you have some examples of Wikidata and DBPedia _"URIs for types classes"_ (@thadguidry already provided me with some Freebase examples)

**Comment by mfhepp** [comment]
For DBPedia, there is a relatively small, hand-crafted set of types, e.g. http://dbpedia.org/ontology/Game

www.productontology.org URIs are typically a better choice, though.

In Wikidata, there are also a few URIs that represent types, e.g.

http://www.wikidata.org/wiki/Q128207

**Comment by mfhepp** [comment]
I suggest to close this issue. For data where a few authoritative representations (Wikidata, DBPedia, Wikipedia) are sufficient, the gain of marking up a large number of Web sites will be less obvious.

Resources will be better spent for improving the Wikidata facts and data model for celestial bodies.

**Comment by pigsonthewing** [comment]
On 4 June 2015 at 08:15, Martin Hepp <notifications@github.com> wrote:

> In Wikidata, there are also a few URIs that represent types, e.g.
>
> http://www.wikidata.org/wiki/Q128207
>

More an be created, as required.

-- 
Andy Mabbett
@pigsonthewing
http://pigsonthewing.org.uk
