### ISSUE TITLE
schema:Quantity, and sub-classes are Intangible not DataType

### ISSUE THREAD

**Issue by gkellogg** [schemaorg/schemaorg#551]
Should they also subclass DataType? The documentation for Duration indicates that it's an ISO 8601 duration format, but it has properties defined from Intangible, which doesn't make sense.

Also QualitativeValue and QuantitativeValue, and their subclasses would seem to want literals, not objects.

It might be that Intangible types which are expected to take literal values should also subClass DataType, if not move to the DataType heirarchy.

**Comment by mfhepp** [comment]
At least for schema:QuantitativeValue and schema:QualitativeValue, the current position in the hierarchy is correct, as far as I can see. Both represent intangible entities that hold a certain value plus various meta-data (like units of measurement, value references,...).

**Comment by gkellogg** [comment]
Perhaps the range of properties having Quantitative/Qualitative should also include Number, to clarify usage. For example `height`; best practice would have this be structured, and units would otherwise be implied, but I can definitely see someone using an Integer as the value of `height`. The `number*` properties seem to do this already, though. `yearsInOperation` ...

It was really `Duration` I was reacting to and looking for patterns.

**Comment by mfhepp** [comment]
@gkellogg no, no, please NOT!

Let's not dilute the power of QuantitativeValue by also allowing Number, in particularly not for properties where a unit is really needed for understanding the value. I agree that QuantitativeValue is a bit under-documented, but this is on my agenda and will be available at http://wiki.goodrelations-vocabulary.org/Documentation/Quantitative_values, with examples inside schema.org.

**Comment by RLRichardson** [comment]
Gregg, also a good time for a peek at the GS1 extension

Sent from Outlook<http://taps.io/outlookmobile>




On Sun, May 31, 2015 at 1:10 AM -0700, "Martin Hepp" <notifications@github.com<mailto:notifications@github.com>> wrote:


@gkellogg<https://github.com/gkellogg> no, no, please NOT!

Let's not dilute the power of QuantitativeValue by also allowing Number, in particularly not for properties where a unit is really needed for understanding the value. I agree that QuantitativeValue is a bit under-documented, but this is on my agenda and will be available at http://wiki.goodrelations-vocabulary.org/Documentation/Quantitative_values, with examples inside schema.org.

�

**Comment by gkellogg** [comment]
The main one I'm concerned about is schema:Duration, which is described as being from ISO 8601, but is a structured type. It should be clear that a literal with datatype schema:Duration (or, essentially equivalent xsd:duration) is a valid value for properties having schema:Duration in their range.

**Comment by mfhepp** [comment]
@gkellogg I agree that schema:Duration could be a subtype of schema:Datatype, because it holds literal values.

QuantitativeValue and QualitativeValue should stay where the are, because you use a typed entity there, never a literal.

BTW, I noticed yesterday that there is quite a mess in the datatypes in the RDFa. 

- some are classes and instances at the same time
- some instances have instance
-  the use of subclass vs. instance is inconsistent.

See the following (not all statements are wrong, but they are inconsistent and we need to agree upon a canonical pattern for this). 

(Note: The good thing is that this can be fixed without breaking any markup).

Number is a class and an instance of DataType:

<div typeof="rdfs:Class http://schema.org/DataType" resource="http://schema.org/Number">
      <span class="h" property="rdfs:label">Number</span>
      <span property="rdfs:comment">Data type: Number.</span>
    </div>

Float is a class and and a subclass of Number:

    <div typeof="rdfs:Class" resource="http://schema.org/Float">
      <span class="h" property="rdfs:label">Float</span>
      <span property="rdfs:comment">Data type: Floating number.</span>
       <span>Subclass of: <a property="rdfs:subClassOf" href="http://schema.org/Number">Number</a></span>
    </div>


Boolean is a class and an instance of Datatype, and True and False are instances of Boolean:

    <div typeof="rdfs:Class http://schema.org/DataType" resource="http://schema.org/Boolean">
      <span class="h" property="rdfs:label">Boolean</span>
      <span property="rdfs:comment">Boolean: True or False.</span>
      
    </div>

    <div typeof="http://schema.org/Boolean" resource="http://schema.org/False">
      <span class="h" property="rdfs:label">False</span>
      <span property="rdfs:comment">The boolean value false.</span>
    </div>

    <div typeof="http://schema.org/Boolean" resource="http://schema.org/True">
      <span class="h" property="rdfs:label">True</span>
      <span property="rdfs:comment">The boolean value true.</span>
    </div>

Date is a class and an instance of DataType:

    <div typeof="rdfs:Class http://schema.org/DataType" resource="http://schema.org/Date">
      <span class="h" property="rdfs:label">Date</span>
      <span property="rdfs:comment">A date value in &lt;a href=&#39;http://en.wikipedia.org/wiki/ISO_8601&#39;&gt;ISO 8601 date format&lt;/a&gt;.</span>
    </div>

DateTime is a class only, while Time is a class and an instance of DataType:

    <div typeof="rdfs:Class" resource="http://schema.org/DateTime">
      <span class="h" property="rdfs:label">DateTime</span>
      <span property="rdfs:comment">A combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm] (see Chapter 5.4 of ISO 8601).</span>
    </div>
	
    <div typeof="rdfs:Class http://schema.org/DataType" resource="http://schema.org/Time">
      <span class="h" property="rdfs:label">Time</span>
      <span property="rdfs:comment">A point in time recurring on multiple days in the form hh:mm:ss[Z|(+|-)hh:mm] (see &lt;a href=&quot;http://www.w3.org/TR/xmlschema-2/#time&quot;&gt;XML schema for details&lt;/a&gt;).</span>
    </div>
	
Text is a Class and an instance of Datatype:
    <div typeof="rdfs:Class http://schema.org/DataType" resource="http://schema.org/Text">
      <span class="h" property="rdfs:label">Text</span>
      <span property="rdfs:comment">Data type: Text.</span>
    </div>

**Comment by gkellogg** [comment]
IMO, datatypes should be defined alone the lines of:

```
schema:Float a rdfs:Datatype, schema:Datatype;
  rdfs:label "Float"@en;
  rdfs:comment "Data type: Floating number."@en;
  rdfs:subClassOf schema:Number .

schema:Number a rdfs:Datatype, schema:Datatype;
  rdfs:label "Number"@en;
  rdfs:comment "Data type: Number."@en;
  rdfs:subClassOf rdfs:Literal .
```

Literals should sub-class `rdfs:Literal` (directly, or indirectly) and be instances of `rdfs:Datatype` and `schema:Datatype`. Note that `rdfs:Datatype` is already a subclass of `rdfs:Class`.

Boolean is interesting, because instances are defined, which the linter accounts for.

It's instructive to see how RDF creates literals:

```
rdf:HTML a rdfs:Datatype;
  rdfs:label "HTML";
  rdfs:comment "The datatype of RDF literals storing fragments of HTML content";
  rdfs:subClassOf rdfs:Literal;
  rdfs:isDefinedBy rdf: .
```
