### ISSUE TITLE
Google validator error or bad XML?

### ISSUE THREAD

**Issue by barrycarter** [schemaorg/schemaorg#553]
````
<div itemscope itemtype="https://schema.org/Person">
   <div itemprop="givenName">Alice</div>
   <div itemprop="parent">
      <div itemscope itemtype="https://schema.org/Person">
         <div itemprop="givenName">Bob</div> 
         <div itemprop="sibling"> 
            <div itemscope itemtype="https://schema.org/Person">
            <div itemprop="givenName">Charles</div>
            </div><!-- End person Charles --> 
         </div><!-- End itemprop sibling --> 
      </div><!-- End person Bob --> 
   </div><!-- End itemprop parent --> 
</div><!-- End person Alice --> 
````

Google's validator interprets the above as saying Alice's parent is "Bob Charles". Is this an error in the validator or am I using XML incorrectly?

My intent: Bob is Alice's parent, and Charles is Bob's sibling (and thus Alice's uncle).

Is multi-level nesting not supported?

**Comment by danbri** [comment]
Took me a while to see this one :) The 'parent' and 'sibling' properties should be on the same element as the itemscope that they point to. This seems to work in Google, Yandex and W3C checkers:

    <div itemscope itemtype="http://schema.org/Person">
       <div itemprop="givenName">Alice</div>
       <div itemprop="parent" 
            itemscope itemtype="http://schema.org/Person">
           <div itemprop="givenName">Bob</div> 
           <div itemprop="sibling" 
                itemscope itemtype="http://schema.org/Person">
               <div itemprop="givenName">Charles</div>
           </div>
       </div>
    </div>

**Comment by danbri** [comment]
p.s. this isn't exactly XML; HTML5 diverges in a few ways. If you write itemscope="" or itemscope="itemscope" it would be wellformed XML as well as HTML(5).

**Comment by Harald-Effenberg** [comment]
<div itemscope itemtype="https://schema.org/Person">
   <div itemprop="givenName">Alice</div>
   <div itemprop="parent" itemscope itemtype="https://schema.org/Person">
       <div itemprop="givenName">Bob</div>
   </div>  
   <div itemprop="sibling" itemscope itemtype="https://schema.org/Person"> 
         <div itemprop="givenName">Charles</div>
   </div> 
</div> 

But I think, the google webmaster-tools will return this as "error", because the persons have no "name"-itemprop.
Googles Structured-Data-Testing-Tool accepts givenName+familyName, but the webaster-tools want an additional "name".

**Comment by barrycarter** [comment]
@danbri Your suggestion worked. Interesting, you can even do this:

````
<div itemscope itemtype="http://schema.org/Person"> 
   <div itemprop="givenName">Alice</div> 
      <div itemprop="parent" itemscope itemtype="http://schema.org/Person" /> 
         <div itemprop="sibling" itemscope itemtype="http://schema.org/Person"> 
            <div itemprop="givenName">Charles</div> 
      </div> 
    </div> 
</div> 
````

which states Alice's uncle is Charles, even if we don't know the intermediary parent/sibling!

My original question was going to be about mapping a "cousin" relationship without knowing the intermediaries, but I think this answers that question as well.
