### ISSUE TITLE
Primitive DataTypes Page Empty

### ISSUE THREAD

**Issue by brentjett** [schemaorg/schemaorg#557]
At the bottom of http://schema.org/docs/schemas.html there's a link to Primitive Data Types (http://schema.org/DataType) which leads to en empty page. 
The spec for these data types are not included in the "full" json spec either. Looking for info.

**Comment by danbri** [comment]
Thanks for the nudge. This is my fault, we made some modeling changes which broke the navigation. I'll get it fixed up asap...

**Comment by brentjett** [comment]
Thanks a bunch! Is there a way to access the additional data types spec in JSON as well?

**Comment by yannlg** [comment]
any updates on fixing this one?

**Comment by danbri** [comment]
Thanks!
