### ISSUE TITLE
mapping to microformats vocab and link relations

### ISSUE THREAD

**Issue by elf-pavlik** [schemaorg/schemaorg#559]
## Background
- http://microformats.org/wiki/microformats2
- http://microformats.org/wiki/existing-rel-values

@rhiaro currently works on describing microformats2 as linked data ontology
- https://github.com/rhiaro/mf2rdf

I plan to provide tool (also as open source hosted service) which will parse microformats from HTML and generate JSON-LD version. It could also output optional schema.org equivalent which one could publish on the same page along microformats in HTML using [JSON-LD in HTML script tag](http://www.w3.org/TR/json-ld-syntax/#embedding-json-ld-in-html-documents) - [well supported by schema.org](http://blog.schema.org/2013/06/schemaorg-and-json-ld.html)
- https://github.com/elf-pavlik/mf2jsonld (very early work!)
### Types

| Microformats | Schema.org |
| --- | --- |
| h-adr | PostalAddress |
| h-card |  |
| h-entry | CreativeWork |
| h-event | Event |
| h-geo | Place |
| h-item |  |
| h-product | Product |
| h-listing | Offer / Demand |
| h-recipe | Recipe |
| h-resume |  |
| h-review | Review |
| h-review-aggregate | AggregateRating |
| h-feed |  |
### Properties

| Microformats | Schema.org |
| --- | --- |
| anniversary |  |
| bday |  |
| duration |  |
| end |  |
| published |  |
| reviewed |  |
| start |  |
| updated |  |
| content |  |
| description |  |
| instructions |  |
| additional-name |  |
| adr |  |
| affiliation |  |
| altitude |  |
| author |  |
| best |  |
| brand |  |
| category |  |
| contact |  |
| count |  |
| country-name |  |
| education |  |
| experience |  |
| extended-address |  |
| family-name |  |
| gender-identity |  |
| geo |  |
| given-name |  |
| honorific-prefix |  |
| honorific-suffix |  |
| ingredient |  |
| item |  |
| job-title |  |
| label |  |
| latitude |  |
| locality |  |
| location |  |
| longitude |  |
| name |  |
| nickname |  |
| note |  |
| nutrition |  |
| org |  |
| post-officbox |  |
| postal-code |  |
| price |  |
| rating |  |
| region |  |
| review |  |
| reviewer |  |
| role |  |
| sex |  |
| skill |  |
| sort-string |  |
| street-address |  |
| summary |  |
| tel |  |
| votes |  |
| worst |  |
| yield |  |
| email |  |
| identifier |  |
| impp |  |
| in-reply-to |  |
| key |  |
| logo |  |
| photo |  |
| uid |  |
| url |  |
| like-of |  |
| repost-of |  |
| bookmark-of |  |
| rsvp |  |

@tantek

**Comment by danbri** [comment]
@elf-pavlik - are you still working on this?

**Comment by elf-pavlik** [comment]
not really, my apologies for bloating the tracker!
