### ISSUE TITLE
search box on schema.org doesn't seem to work

### ISSUE THREAD

**Issue by halindrome** [schemaorg/schemaorg#560]
When I go to www.schema.org right now, the search box in the upper right corner does not allow me to type in at all.  I cannot put my cursor in it.  Weird.  NOTE: I CAN TAB INTO THE FIELD.

I am using an Asus Chromebook with the following software, not that it should be super relevant:

Version 43.0.2357.81 beta (64-bit)
Platform 6946.55.0 (Official Build) beta-channel peppy
Firmware Google_Peppy.4389.89.0

Interesting.  I tested this on Firefox (on Linux) version 38.0 and I cannot click in the search box either.  Again, I can tab into it.  I just can't click on it to get a cursor to appear.

CLARIFICATION:  If I move my arrow cursor to the VERY TOP of the search box text area, the cursor will change to a vertical var (input cursor) and I can click and type.  Otherwise it remains an arrow.

My guess is that there is some overlapping region that is grabbing events or something,

**Comment by danbri** [comment]
Thanks for taking the time to report this, I've just reproduced this here too. As for you, top area works. I remember some change to CSS around events recently (forget offhand why). Investigating...

**Comment by miloshavlicek** [comment]
:+1:

**Comment by westurner** [comment]
see also: #349 ENH: class/property lookup JS widget

**Comment by westurner** [comment]
(Though it does appear that a CSS fix with Inspect Element should be possible)

**Comment by thgh** [comment]
I also have been bothered by this. The cause for the issue is the overlapping <h1>
![overlap](https://cloud.githubusercontent.com/assets/1109982/8420125/c808935e-1ebf-11e5-997f-4aa11dc6e60c.PNG)

**Comment by Lynda333** [comment]
+1 - I can click in the box if I click on what I consider the top border of the search box.
