### ISSUE TITLE
Support for language in an EntryPoint

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#561]
Sometimes authors need to use different URLs for different Actions. For example, an OrderAction may have different URLs for English-speaking users and another for Spanish speakers.

One could infer the language by following the link and determining the language, but it would be easier if the author could write something like:

```
{
  "@context": "http://schema.org/",
  "@type": "OrderAction",
  "target": [
    {
      "@type": "EntryPoint",
      "url": "http://www.example.com/order"
      "inLanguage": "en"
    },
    {
      "@type": "EntryPoint",
      "url": "http://www.example.com/pedir"
      "inLanguage": "es"
    },
  ]
}
```

**Comment by Aaranged** [comment]
Sometimes authors need to use different URLs for other types of entities too.  For example, an Organization may have different URLs for English-speaking users and another for Spanish speakers.

Similarly, it would be easier if authors could use something like this (e.g. - the code has multiple problems, I know):

<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Organization",
  "url": [
    {
      "@type": "URL",
      "url": "http://www.example.com/en_US/",
      "inLanguage": "en"
    },
    {
      "@type": "URL",
      "url": "http://www.example.com/es_ES",
      "inLanguage": "es"
    },
  ]
}
</script>

Excuse me is this issue is conceptually too different from the OrderAction example which stimulated it, but I've run into just the same issue with URL declaration on a per-language basis.  The JSON-LD keys @language and @value work fabulously for such situations ... but only for strings.

**Comment by shankarnat** [comment]
I agree with Aaron,  the examples of wikipedia URLs[mainentityofpage] referring to entities such people/place etc. There could be the same multiple language pages for every entity type, how is it handled today ? Are there any requirements around it ?

**Comment by shankarnat** [comment]
I also see an opportunity to extend this concept to include mobile friendly URLs along with languages. This could become more important with lot of URLs having the mobile friendly version differnet from the URL, it could be helpful for mobile first scenarios. It seems to me both languages and mobile friendly URL can become properties of the type schema.org/url as it can apply to all properties where the expected type is URL. Thoughts ?

**Comment by mfhepp** [comment]
While I see value in such meta-data in schema.org, it quickly gets complicated, becausewe need to understand whether the underlying entities are the same for different languages or not.

For a schema:WebSite, this is (arguably) not a problem, but there we already have http://schema.org/inLanguage - you can say that http://de.acme.com is in German and http://us.acme.com is in English.

The same holds for http://schema.org/WebPage.

What we might add here is a property for indicating that one site or page is just a language variant of the other.

BUT 

As we turn to entities inside the page, we face the problem that while their textual description differs in multiple language, they are still the same entity.

**Comment by vholland** [comment]
@mfhepp I am not sure I understand your point. This is specifically for Actions, not URLs in general. There may not be a "page" on the other end of the URL.

To @shankarnat's point, in a mobile world, language and geography matter and we can't always follow the link to see "this is the URL for French-speaking users to order items in Canada".

**Comment by vholland** [comment]
@shankarnat It seems strange to change the semantics of URL. Should we allow the url property to expect an EntryPoint where we can add these properties?

**Comment by vholland** [comment]
I was thinking something like what I have implemented in pull request #623.

**Comment by vholland** [comment]
Is there interest in extending the "url" property to accept either a URL or an EntryPoint. I suppose the advantage is we could use EntryPoint for all of the regional and language specifications.

**Comment by danbri** [comment]
Where are we with this? @betehess 's issues around WebSite and Product in https://github.com/schemaorg/schemaorg/issues/1065 are pretty close.

**Comment by vholland** [comment]
The "inLanguage" proposal does not support the other use cases of HTML's link rel attribute.

**Comment by betehess** [comment]
@vholland I don't understand. This thread is about inLanguage not LinkRole.
I believe @dandri is referring to the discussion in #1064 where inLanguage
could be extended to all Things, including EntryPoint. Also, if I
understand correctly, LinkRole is about pages/urls, not just any kind of
entity. Am I missing something?
>
>

**Comment by danbri** [comment]
I was also confused by @vholland 's reply. Perhaps because I asked about status of #561 while also alluding to other discussions (#1064 but also the sameAs discussion). As well as #1045.

**Comment by vholland** [comment]
Yes, I thought @danbri was suggesting that inLanguage would make LinkRole unnecessary.

**Comment by danbri** [comment]
@vholland - do you want to pursue this idea here, or via the LinkRole construction? 

I made some relatively straightforward improvements around our handling of language (human and machine) as documented in #1079 but I don't think those address your concern here, or @betehess 's request in #1064 for inLanguage on more (or even on all) types.

**Comment by vholland** [comment]
I prefer LinkRole as it is more versatile.

**Comment by vholland** [comment]
Reading through, I will close this issue. (Someone can re-open if they would like to pursue updating EntryPoint.) Otherwise, I think the LinkRole as discussed in issue #1045 is cleaner and the other issues should be discussed in #1079.

**Comment by danbri** [comment]
Thanks @vholland. Let's explore making LinkRole and other (ideally more cross-domain) mechanisms work then. Makes sense to have one less open issue on this broad topic.
