### ISSUE TITLE
Microdata examples for BuyAction

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#569]
https://schema.org/BuyAction only lists JSON example. Can someone document microdata and rdfa, please?

**Comment by nueckman** [comment]
Well, there are no microdata and rdfs examples for actions at all. Any reason for that ?

**Comment by unor** [comment]
FWIW, I created a pull request for a Microdata/RDFa `WatchAction` example: https://github.com/schemaorg/schemaorg/pull/570
