### ISSUE TITLE
I Would like some new types for Realstate

### ISSUE THREAD

**Issue by thingNumber1** [schemaorg/schemaorg#571]
It would be great if there were the following types (maybe under http://schema.org/Residence):

https://schema.org/Building
https://schema.org/Condo
https://schema.org/Tower
https://schema.org/Mansion
https://schema.org/Office
https://schema.org/BusinessPremises **
https://schema.org/IndustrialShip **
https://schema.org/Plot **

**  I'm not sure if this is the correct way in english for the marked ones, but it think it is. If you can't understand what i'm trying to say just let me know and i'll try to explain it in a better way.

Also, I would like to be able to indicate the owner. So, I think its a good idea a property https://schema.org/owner (that could be usefull no only for residences).

**Comment by mfhepp** [comment]
I renamed the issue. Yes, we need an extension for real estate information, but it will not be as simple as defining new types of buildings / assets. We also need properties for parking, number of rooms, amenities, etc.

From the work on a GoodRelations extension for real estate, I have a draft of such an extension and will  work on this as time permits, but auto and hotels are higher priorities for me for the moment.

**Comment by thingNumber1** [comment]
And is there a way I can help? or the only thing I can do is stand and wait?

**Comment by mfhepp** [comment]
What would be useful to evolve this issue is

- collect a set of representative URLs of Web pages describing real estate information
- describe use cases and requirements here in Github
- add links to standards for describing real estate objects ("ACME XML Schema for Housing" or things like that, "JSON API for xyzhousing.com")

**Comment by thingNumber1** [comment]
I was thinking on something like this:

Schema / Residence (suggested subtypes):
- Schema / Building
- Schema / Condo
- Schema / Tower
- Schema / Mansion
- Schema / BusinessPremises
- SchemaIndustrialShip
- Schema / Plot
- Schema / Penthouse

Schema / Residences (action):
- Sale
- Rent
- Purchase
- Giving
- Transfer


Schema / Residences (Properties):
- Room (Room or TEXT)


Schema / Room:
- Bedroom
- Bathrooms
- Swimming pool
- Gazebo
- Garage
- Kitchen
- Dining
- Living
- Walking Closet
- Game room
- Lobby
- Basement.
- Restroom.
- Wash Area
- Family Room
- Backyard
- Garden
- Office
- Meeting room
- Conference hall
- Balcony


Property of Rooms:
- Finish (do not know if it says so in English, but I mean if the room has been stylized with wood, marble or consas well).
- Dimension
- Objects in the room (TEXT, or URL Thing)


Suggestions:
- Residence can be a product type.
- I do not know how this would be done, but there must be a way to indicate the cantiidad of each object (the property of the rooms) and the amount of each type of room in the residence.


Also here are 8 API's:

https://www.quandl.com/resources/api-for-housing-data
http://www.programmableweb.com/news/7-real-estate-apis-what-housing-crisis/2008/04/16

**Comment by Dataliberate** [comment]
My thought would be to turn this on its head.

New Subtype to Place > Building.

New enumeration BuildingType with values:

  *   Tower
  *   Condominium
  *   House
  *   Cottage
  *   Airport Terminal
  *   RailStation
  *   BusStation
  *   Shop
  *   Apartment
  *   etc.

New subtype of Building > Room

New enumeration RoomType with values:

  *   Bedroom
  *   Bathroom
  *   Kitchen
  *   LectureTheatre
  *   MeetingRoom
  *   ConferenceHall
  *   LibraryRoom
  *   BowlingLanes
  *   etc.

Current containedIn will allow the relationship between rooms & Buildings and Buildings & Buildings — e.g..room contained in an Apartment contained in a Tower.

New property for Room ‘contains’ with a range of Thing — Room contains things such as tables, seats, projectors, sound system, TV, freezer, etc.

Finally add floor, roomNumber and/or apartmentNumber to PostalAddress.

Capturing values such as dimensions etc., plus transactional information such as Offers etc.  could be handled with specific properties.  Or potentially making Building a subtype of both Place and Product.  Would need to think through potential ramifications and impacts with what Martin's real estate proposal might bring.


~Richard

On 6 Jun 2015, at 18:57, thingNumber1 <notifications@github.com<mailto:notifications@github.com>> wrote:


I was thinking on something like this:

Schema / Residence (suggested subtypes):

  *   Schema / Building
  *   Schema / Condo
  *   Schema / Tower
  *   Schema / Mansion
  *   Schema / BusinessPremises
  *   SchemaIndustrialShip
  *   Schema / Plot
  *   Schema / Penthouse

Schema / Residences (action):

  *   Sale
  *   Rent
  *   Purchase
  *   Giving
  *   Transfer

Schema / Residences (Properties):

  *   Room (Room or TEXT)

Schema / Room:

  *   Bedroom
  *   Bathrooms
  *   Swimming pool
  *   Gazebo
  *   Garage
  *   Kitchen
  *   Dining
  *   Living
  *   Walking Closet
  *   Game room
  *   Lobby
  *   Basement.
  *   Restroom.
  *   Wash Area
  *   Family Room
  *   Backyard
  *   Garden
  *   Office
  *   Meeting room
  *   Conference hall
  *   Balcony

Property of Rooms:

  *   Finish (do not know if it says so in English, but I mean if the room has been stylized with wood, marble or consas well).
  *   Dimension
  *   Objects in the room (TEXT, or URL Thing)

Suggestions:

  *   Residence can be a product type.
  *   I do not know how this would be done, but there must be a way to indicate the cantiidad of each object (the property of the rooms) and the amount of each type of room in the residence.

Also here are 8 API's:

https://www.quandl.com/resources/api-for-housing-data
http://www.programmableweb.com/news/7-real-estate-apis-what-housing-crisis/2008/04/16

**Comment by sergeliatko** [comment]
Hi guys, sorry me chiming in. 

I do have data about vacation rentals and examples of pages where they are described, wsdl services sending data around the web and Standard USA (from HomeAway) attributes for vacation rentals (might be useful for real estate as well) - 

How do we proceed? I'm new on github.

**Comment by sergeliatko** [comment]
Forgot to mension, Interested in developing a schema for Real Estate / Vacation Rentals + availability dates for rentals + rates . And I have a team of developers. That might help you somehow?

**Comment by danbri** [comment]
@thingNumber1 - thanks for suggesting this, it is a popular request and seems a good area for development. However we already have another open issue tracking the topic - #241 - so I will nevertheless go ahead and close out this issue, directing follow up discussions into #241 to avoid fragmentation. Thanks all for the discussion!
