### ISSUE TITLE
TrainTrip has examples for TranReservation

### ISSUE THREAD

**Issue by orlade** [schemaorg/schemaorg#572]
The examples on http://schema.org/TrainTrip are the same as those on http://schema.org/TrainReservation.

**Comment by danbri** [comment]
Yes, each example in our collection is tagged with the terms it illustrates. In this case we only have the one currently, i.e. https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/examples.txt#L9828

Thanks for letting us know that this looked wonky. I will go ahead and close the issue as there are many cases where more examples are needed. Thanks again!
