### ISSUE TITLE
example of JSON-LD for multiple address

### ISSUE THREAD

**Issue by thingNumber1** [schemaorg/schemaorg#574]
Hi, 

I would like to know, if I have a person with to address, how can I to specify it in JSON-LD for Schema?

For exaple, If I have this person:

**name:** John Doe
**additionalName:** Johnny
**address [PostalAddress]:**
    **streetAddress:** 1234 Peach Drive
    **addressLocality:** Wonderland
    **addressRegion:** Georgia

    {
        "@context":"http://schema.org",
        "@type":"Person",
        "name":"John Doe",
        "additionalName":"Johnny",
        "address":
        {
            "@type":"PostalAddress",
            "streetAddress":"1234 Peach Drive",
            "addressLocality":"Wonderland",
            "addressRegion":"Georgia"
        }
    }

But... what if I have to directions... lets say, this person:

**name:** John Doe
**additionalName:** Johnny
**address [PostalAddress]:**
    **streetAddress:** 1234 Peach Drive
    **addressLocality:** Wonderland
    **addressRegion:** Georgia
**address [PostalAddress]:**
    **streetAddress:** 351 White Paradise
    **addressLocality:** Wonderland
    **addressRegion:** Georgia

**Comment by unor** [comment]
[My answer](http://webmasters.stackexchange.com/a/81745/17633) to the Webmasters Stack Exchange question [Multiple addresses in JSON-LD Schema.org](http://webmasters.stackexchange.com/q/81735/17633) might help you. 

By using an array:

<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Person",
  "address":
  [
    {
      "@type": "PostalAddress"
    },
    {
      "@type": "PostalAddress"
    }
  ]
}
</script>

**Comment by thingNumber1** [comment]
Thanks a lot, i was very usefull.
