### ISSUE TITLE
Would like to see a Type or Extension for Health Insurance

### ISSUE THREAD

**Issue by ccorak** [schemaorg/schemaorg#576]
With the healthcare landscape changing, and research and shopping for healthcare dramatically increasing at the personal level (not group), there will be a greater need for content creators / plan providers / 3rd party aggregators to mark this content up moving forward. 

Our medical markup is already expansive, but doesn't include Health Insurance / Coverage. And there is markup relevant to Financial Insurance, but not health. Health would be a great addition.

**Comment by twamarc** [comment]
It would help if you can create an issue on the dedicated community to help an efficient follow up on this, here: 
- https://www.w3.org/community/schemed/
- https://github.com/twamarc/ScheMed/issues

**Comment by ccorak** [comment]
Thank you! I started another conversation in the "ScheMed/issues" area. Thanks for you time.
