### ISSUE TITLE
videoFormat on TelevisionStation vs videoFormat on BroadcastService

### ISSUE THREAD

**Issue by morganyvm** [schemaorg/schemaorg#577]
Should not videoFormat be part of BroadcastService, like the third BroadcastService example, instead of part of TelevisionStation? 
The (Broadcast)Service delivery the videoFormat. TelevisionStation is related to one or more BroadcastService, isn`t? Does it make sense? Anybody agree?

**Comment by vholland** [comment]
Oops. Yes. That is a bug in the RDFa. The example is correct.

**Comment by danbri** [comment]
ok I've fixed the non-display of the examples, and updated sdo-ganymede and webschemas test builds.

Looking at http://webschemas.org/ScreeningEvent and http://schema.org/BroadcastService proposal is to.

 * add domainIncludes BroadcastService to videoFormat property
* remove domainIncludes BroadcastService from videoFormat property
*  What about: add domainIncludes BroadcastEvent to videoFormat property also? based on https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/sdo-tv-listing-examples.txt#L111
* continue with domainIncludes ScreeningEvent videoFormat - this is correct and in examples, http://sdo-ganymede.appspot.com/videoFormat

**Comment by danbri** [comment]
Tentatively committed an implementation of the above, including BroadcastEvent.

Comments welcomed! How does http://sdo-ganymede.appspot.com/videoFormat look?

**Comment by vholland** [comment]
+1 looks good to me.

**Comment by danbri** [comment]
Ok, http://webschemas.org/docs/releases.html has the candidate release notes: 

    <li><a href="https://github.com/schemaorg/schemaorg/issues/577">Fix to #577</a>: Amended <a href="/videoFormat">videoFormat</a> to indicate that it is expected on <a href="/BroadcastEvent">BroadcastEvent</a> and <a href="/ScreeningEvent">ScreeningEvent</a>, rather than <a href="/TelevisionStation">TelevisionStation</a>.</li>

**Comment by danbri** [comment]
@mika @shankarnat @tmarshbing @chaals @tilid @ajax-als - please take a look for final sanity check

**Comment by mika** [comment]
@danbri Looks like you pinged the wrong mika

**Comment by danbri** [comment]
Oops. Do feel free to +1 unless @pmika gets there first! Sorry for the noise...

**Comment by morganyvm** [comment]
+1 looks good.
Tks you all!

**Comment by danbri** [comment]
Thanks @morganyvm. Let's leave the issue open to give the others I cc:'d a change to take a look (though I think we're very likely done here).

**Comment by morganyvm** [comment]
@danbri sorry for that. I'm a newbie here.

**Comment by danbri** [comment]
No worries, we haven't documented (or fully invented) conventions for everything here yet. Thanks again for catching this bug! :)

**Comment by shankarnat** [comment]
+1 Looks good.

**Comment by vholland** [comment]
Fixed in 2.1

**Comment by chaals** [comment]
Works for me
