### ISSUE TITLE
Generalize the term schema:source

### ISSUE THREAD

**Issue by csarven** [schemaorg/schemaorg#579]
`schema:source` is currently "The anatomical or organ system that the artery originates from."

That's not quite intuitive to me when I see the term 'source'. Could the description be more like `dcterms:source`'s "A related resource from which the described resource is derived."?

Note that there is a related term `schema:isBasedOnUrl` "A resource that was used in the creation of this resource. This term can be repeated for multiple sources."

Could the definition of `schema:source` relaxed and perhaps get rid of `schema:isBasedOnUrl`?

**Comment by danbri** [comment]
Thanks @csarven! This is another example of where we introduced medical/health terms without sufficient care for their broader meaning. @twamarc is looking into reorganizing those into a medical/health extension via W3C CG, https://www.w3.org/community/schemed/

I suggest we handle this similarly to 'action' (-> 'muscleAction') : introduce a new medical/health term that is more explicit, and migrate the old term to a more general meaning or retire it, depending on usage levels.

**Comment by csarven** [comment]
Another: `schema:sourcedFrom` "The neurological pathway that originates the neurons."

Intuitively, I would think of `schema:sourceFrom` equivalentProperty `prov:wasDerivedFrom`.
