### ISSUE TITLE
404 for Microdata snapshot

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#584]
http://schema.org/docs/datamodel.html says:

>  Obsolete snapshots of [Microdata](http://schema.org/docs/full_md.html) and [OWL](http://schema.org/docs/schemaorg.owl) experimental data dumps are also available.

The link to the Microdata snapshot is 404: http://schema.org/docs/full_md.html

**Comment by danbri** [comment]
Thanks. I think this is/was uninteresting enough that we can remove the link. Do you think anyone cares? 

e.g. https://web.archive.org/web/20150414142113/http://schema.org/docs/full_md.html

Hmm the earlier archive.org snapshots might be the only current public versioned snapshots, prior to introduction of the RDFa view...

**Comment by unor** [comment]
> Do you think anyone cares?

Nope. I think we should remove all snapshots that are no longer maintained (except for the "frozen" release snapshots, of course).
