### ISSUE TITLE
Domain of netWorth: Person and Organization?

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#585]
http://schema.org/netWorth

The currenct description:

> The total financial value of the organization or person as calculated by subtracting assets from liabilities.

But it only lists `Person` as domain, not `Organization`.

Should `Organization` be added to the domain?

**Comment by vholland** [comment]
That is a mistake in the documentation. The original proposal was to include Organizations, but it was decided that before we go down that route, we should integrate with [FIBO](http://www.edmcouncil.org/financialbusiness).

**Comment by vholland** [comment]
Fixed in pull request #594.
