### ISSUE TITLE
Is affiliation sub-property of memberOf

### ISSUE THREAD

**Issue by csarven** [schemaorg/schemaorg#596]
I'm trying to see the semantic difference between `schema:affiliation` and `schema:memberOf`. Is the former a sub-property of the latter - although not formally defined as such at the moment?

**Comment by danbri** [comment]
Yes, affiliation looks like a specialized case of memberOf to me. The latter also allows Orgs to be members of thing, and accepts programme membership as a kind of value. But I can't think of any case where x has an affiliation y, where we wouldn't also say that x is a memberOf y.

**Comment by danbri** [comment]
Merged, thanks!

**Comment by danbri** [comment]
Queued for publication, see http://sdo-ganymede.appspot.com/affiliation - thanks again
