### ISSUE TITLE
Write better examples and documentation for memberOf, worksFor, alumniOf and any others I am missing

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#598]
This is a catch all issue to write better documentation of the various ways people can be affiliated with Organizations.

There are a few properties in this area that are related, but slightly different in meaning including:
- memberOf (inverse of member)
- alumniOf (inverse of alumni)
- worksFor (inverse of employee)

At least two other issues: issue #432 and issue #596 have questions about when it is appropriate to use one of the above. Clearer documentation and examples would help, particularly if the examples illustrate how to use a http://schema.org/Role to denote tenure or type of membership.

**Comment by danbri** [comment]
* http://schema.org/memberOf: "An Organization (or ProgramMembership) to which this Person or Organization belongs." (from Organization, Person to Organization, ProgramMembership; approx 1000-10000 sites)
 * inverseOf http://schema.org/member "A member of an Organization or a ProgramMembership. Organizations can be members of organizations; ProgramMembership is typically for individuals." (~10000-50000 sites)
* http://schema.org/alumni "Alumni of educational organization." (EducationalOrganization to Person; ~10-100 sites)
 * inverseOf http://schema.org/alumniOf "An educational organizations that the person is an alumni of." (from Person to EducationalOrganization; ~10,000-50,000 sites)
* http://schema.org/worksFor "Organizations that the person works for." (from Person to Organization; ~10000-50000 sites)
* http://schema.org/founder "A person who founded this organization." (from Organization to Person; ~10000-50000 sites)
 * see also http://schema.org/foundingDate http://schema.org/foundingLocation
* http://schema.org/contactPoint "A contact point for a person or organization." (from Organization , Person to http://schema.org/ContactPoint, "A contact point—for example, a Customer Complaints department.", both contactPoint and ContactPoint ~10000-50000 sites)

**Comment by danbri** [comment]
Corner cases to consider:

* a Customer Complaints Department
  * described via "department" property
  * described via "contactPoint" markup
* a Founder and CEO who still worksFor her company
 * marked up in Microdata, RDFa and JSON-LD exploring that the HTML-based notations can be more concise than JSON-LD except that the properties are in opposite direction; would we encourage @rev / @reverse  / @itemprop-reverse ?
* ...
