### ISSUE TITLE
Excepted type of "upvoteCount" and "downvoteCount"

### ISSUE THREAD

**Issue by PendalF89** [schemaorg/schemaorg#601]
Hello!
I have comments with "Likes" and "Likes" count shows as "+5", "-3", "0" etc. Can i use this format ("+5", "-3") for "upvoteCount" and "downvoteCount" properties?

**Comment by vholland** [comment]
You may want to look at issue #137. The UserInteraction model is being updated in the next release.

**Comment by vholland** [comment]
Duplicate of issue #137.
