### ISSUE TITLE
data/schema.rdfa

### ISSUE THREAD

**Issue by dtjones** [schemaorg/schemaorg#602]
sorry really small issue but i was scraping the schema.rdfa  file and notices that 
InteractionCounter is the only tag where the resource property is not a URL. 
InteractionCounter doesn't seem to exist on the schema.org site at all

https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/schema.rdfa#L12274

**Comment by danbri** [comment]
Thanks, that does look like a bug, even though the (new and proposed) type shows up in our work-in-progress test site at http://sdo-ganymede.appspot.com/InteractionCounter /cc @vholland
