### ISSUE TITLE
Thing > Product > SomeProducts *Confusing Example*

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#604]
The example used for 'similar' products has one EAN-13 and I cannot see this as a group of items that are similar and interchangeable. Could you describe say a product category? We have a debate about when to use listItem and when to use [**someProducts**](https://schema.org/SomeProducts)

**Comment by inetbiz** [comment]
https://schema.org/SomeProducts

**Comment by RLRichardson** [comment]
Please help me understand the context for “Some Products”…

It seems to me that it would create confusion versus “Product” model…


Thanks,

Rich

Rich Richardson | Vice President, Emerging Capabilities and Industries | GS1 US
1009 Lenox Drive, Suite 202, Lawrenceville, NJ 08648 | T +1 609.620.4526 | M +1 609.610.3806 | E rrichardson@gs1us.org<mailto:rrichardson@gs1us.org> | www.GS1US.org<http://www.gs1us.org/>
The Global Language of Business | Making it possible for industries and companies to move their business forward

"The things we consider to be everyday have extraordinary effects on places we’ve never heard of."  Kate Davies
Click To Follow Me [Twitter Logo] <https://twitter.com/?lang=en>
See the It's Just Commerce™  Video at  http://youtu.be/pkrxhefQIBs
P Before printing, think about ENVIRONMENTAL responsibility

**Comment by mfhepp** [comment]
Please see here for more background:

http://wiki.goodrelations-vocabulary.org/Documentation/Product_or_Service

I will update and enhance that page in the near future.

Hope that helps.

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by inetbiz** [comment]
TY @mfhepp I hope Google Search also updates their policy guidelines for Categories. Their citation was to use schema Product. That doesn't seem to fit with a category of products. So confusion is wide-spread in the search industry, it seems.

**Comment by inetbiz** [comment]
@mfhepp That URI really didn't clarify someproducts. At the end it uses html for idiots lol. Would that mean the book in various formats? They would all have different ISBN numbers and EAN-13's [ pdf, epub, softcover, hardback, et al ]

**Comment by inetbiz** [comment]
So, which schema.org page example should I follow? Has the documentation been modified?
