### ISSUE TITLE
FoodProduct schema

### ISSUE THREAD

**Issue by yelly** [schemaorg/schemaorg#607]
Currently, the `Product` schema on schema.org is rather limited and includes a single specific product type (`Vehicle` > `Car`).
A good extension to the schema could be the addition of `FoodProduct` and some children. This could be used in online stores and catalogs (such as a brewery's listing of it's selection).
The `FoodProduct` schema could include the following properties:

1. `ingredients` - a list of [Ingredients](http://schema.org/ingredients).
2. `nutrition` - [NutritionInformation](http://schema.org/NutritionInformation).
3. `allergens` - a list of allergens in the product (as per [FALCPA](http://www.fda.gov/Food/GuidanceRegulation/GuidanceDocumentsRegulatoryInformation/Allergens/ucm106890.htm#label)). Could be from a matching enumeration.
4. `dietaryLaws` - a list of dietary laws the product adheres to ('Kosher', 'Halal'...). Should be from a matching enumeration (which can then be used in [FoodEvent](https://schema.org/FoodEvent) and [FoodEstablishment](https://schema.org/FoodEstablishment)).

There will then be room for many children. For example, BeerProduct (as a brewer, I am biased):

1. `ibu`, `srm`, `og` - some beer-specific number values.
2. `malt` - the specific malt varieties used in the beer.
3. `hops` - the specific hop varieties used in the beer.

Of course, the options here are endless.

**Comment by yelly** [comment]
This suggestion relates to #458, but differs from it in that #458 seems to be mainly recipe oriented.

**Comment by RLRichardson** [comment]
Ariel,

GS1 has a robust set of schema for all things nutritional (maybe not as robust as you’d like in the beer department), but have a look here:

http://www.gs1.org/voc or https://bitbucket.org/jaw111/gs1-voc

Rich


Rich Richardson | Vice President, Emerging Capabilities and Industries | GS1 US
1009 Lenox Drive, Suite 202, Lawrenceville, NJ 08648 | T +1 609.620.4526 | M +1 609.610.3806 | E rrichardson@gs1us.org<mailto:rrichardson@gs1us.org> | www.GS1US.org<http://www.gs1us.org/>
The Global Language of Business | Making it possible for industries and companies to move their business forward

"The things we consider to be everyday have extraordinary effects on places we’ve never heard of."  Kate Davies
Click To Follow Me [Twitter Logo] <https://twitter.com/?lang=en>
See the It's Just Commerce™  Video at  http://youtu.be/pkrxhefQIBs
P Before printing, think about ENVIRONMENTAL responsibility

**Comment by twamarc** [comment]
Needs coordination with Medical/health vocabulary extension #492 here.
We are having discussions to include some elements of FoodProduct  and FoodSubstance in the extensions. Can you open an issue via the community group so we can coordinate and follow up this?
https://www.w3.org/community/schemed/

**Comment by twamarc** [comment]
stepping back, I think we need a small vocab for food. Something between food/diet (from Health perspective) and food/recipe/product (from product/offer perspective).

We need to coordinate here. Any suggestion?

@yelly :
Need to look at your proposal breakdown:
-ingredients - a list of Ingredients. ---- a part can maybe be taken in our health extension.
-nutrition - NutritionInformation.---- this can maybe be taken in our health extension.
-allergens - this can maybe be taken in our health extension.
-dietaryLaws ---more related to product

Maybe this needs coordination with other group:
-ibu, srm, og - some beer-specific number values.
-malt - the specific malt varieties used in the beer.
-hops - the specific hop varieties used in the beer.

@yelly :any thoughts?

**Comment by danbri** [comment]
For food preferences see also airlines e.g. MealType in http://www.opentravel.org/2015A/OTA_SimpleTypes.xsd

**Comment by danbri** [comment]
We also have active food discussion in the slightly older thread at #458 - let's consolidate discussion there. I will mark this issue #607 as closed but the broader topic is very much still active. Thanks for all your comments.
