### ISSUE TITLE
CODE: Parser for data/*examples.txt ignores final entry

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#61]
Each data/*examples.txt file currently has a bogus final entry ("FakeEntryNeeded, FixMeSomeDay"), since AddExample only gets called when a next item is encountered.

https://github.com/rvguha/schemaorg/blob/master/parsers.py#L76 

Next step - let's get a failing test case for this.

**Comment by danbri** [comment]
This mostly hurts nothing but our pride, but should get fixed. Suggest next step is a branch with failing test cases.

**Comment by RichardWallis** [comment]
Fixed in Audiobook #651
