### ISSUE TITLE
A publisher can be a person.

### ISSUE THREAD

**Issue by csarven** [schemaorg/schemaorg#611]
`schema:publisher` defines itself with "The publisher of the creative work." Its range is `schema:Organization`. Is there a particular reason why `schema:Person` is not one of the possible ranges?

The definition of _publisher_ from the English dictionary generally states it to be a person or business/organization with such role. I'd like to propose the addition of:

`schema:publisher schema:rangeIncludes schema:Person .`

**Comment by chaals** [comment]
+1

**Comment by mfhepp** [comment]
+1

**Comment by vholland** [comment]
+1

**Comment by boanuge** [comment]
+1

**Comment by watilde** [comment]
+1

**Comment by shankarnat** [comment]
+1

**Comment by scor** [comment]
:+1:
