### ISSUE TITLE
Change UnRegisterAction to UnregisterAction

### ISSUE THREAD

**Issue by lanthaler** [schemaorg/schemaorg#612]
The capitalization of UnRegisterAction looks extremely weird and I couldn't find anything else in Schema.org using the same capitalization scheme. Could we change this to UnregisterAction while we still can?

**Comment by chaals** [comment]
+1

**Comment by mfhepp** [comment]
+1

**Comment by vholland** [comment]
+1

**Comment by danbri** [comment]
In public Web, "Usage: Fewer than 10 domains" seems appropriately low for making such a change. Though presumably it might be getting used in email messages for actions and not counted in the public Web stats.  I haven't found any evidence of that though, so a mild +1 from me.
