### ISSUE TITLE
Linking Orders and Deliveries

### ISSUE THREAD

**Issue by mushishi78** [schemaorg/schemaorg#613]
I'm having trouble understand how to link an `Order` with information about delivering the order. Here is the best guess I've made, but it seems to have multiple problems:

```
{
  "@context": "http://schema.org/"
  "@type": "Order",
  "acceptedOffer": {
    "@type": "Offer",
    "price": 3.75,
    "priceCurrency": "GBP"
  },
  "orderDelivery": {
    "@type": "ParcelDelivery",
    "deliveryAddress": {
      "@type": "PostalAddress",
      "streetAddress": "89 Rook Rd",
      "addressCountry": "UK",
      "postalCode": "RX48 9WW"
    },
    "deliveryStatus": {
      "@type": "DeliveryEvent",
      "offers": [
        {
          "@type": "Offer",
          "name": "RoyalMail 48",
          "price": 2.25,
          "priceCurrency": "GBP"
        },
        {
          "@type": "Offer",
          "name": "RoyalMail 24",
          "price": 3.50,
          "priceCurrency": "GBP"
        }
      ]
    },
    "expectedArrivalFrom": "2015-06-19",
    "expectedArrivalUntil": "2015-06-20",
    "hasDeliveryMethod": "http://purl.org/goodrelations/v1#DeliveryModeMail"
  },
  "orderedItem": [
    {
      "@type": "Product",
      "name": "Cool Bag",
      "offers": [
        {
          "@type": "Offer",
          "price": 1.50,
          "priceCurrency": "GBP"
        }
      ]
    },
  ],
  "orderStatus": "http://schema.org/OrderProcessing"
}
```

The first problem is that `ParcelDelivery` doesn't seem to have any way of specify the cost of the delivery. So I co-opted `DeliveryStatus`, which accepts a `DeliveryEvent`, which inherits the `offers` property from `Event`. Although this is allowed, it doesn't seem right semantically, the cost of a delivery isn't an offer on an event that is the current status of the delivery, is it?

The second problem is that in different stages of an order's lifecycle it might be meaningful to the specify the many delivery services that are available for the order and then later specify which one is specifically selected. In the example I've given, there are two offers: "RoyalMail 48" and "RoyalMail 24", however it is only implicit from the Order's `acceptedOffer` that the first service has been accepted.

The third problem is that, written this way, there is no means to express that the estimated delivery time of each offer. In the example "RoyalMail 48" would take 2-3 days and "RoyalMail 24" would take 1 day to be delivered for instance.

Sorry if I've come at this at an awkward angle or made a basic mistake in usage.

**Comment by mushishi78** [comment]
I thought it might help if I made explicit suggestions to solve my problems:

1) Add an `offers` property to `ParcelDelivery`.

2) Add an `acceptedOffer` property to both `ParcelDelivery` and `OrderItem` (the same problem applies to products).

3) Add a `deliveryTime` property to `Offer`. There's already a `deliveryLeadTime`, which is a pretty similar concept.

If there are already solutions to these problems, or better alternatives, then by all means ignore these specific suggestions.

**Comment by vholland** [comment]
My recollection is that people did not like having a price property on both the Order and the Offer specified in acceptedOffer because authors may write one value in the Order and another in the Offer.

In your use case, are you trying to specify the available shipping methods or the shipping method chosen for the particular order?

**Comment by mushishi78** [comment]
It'd be great to know the intended way to do both.

From reading the definition for `priceSpecification`, this seems like it might be the intended way to specify the delivery cost associated with an order:

```
{
  "@context": "http://schema.org/"
  "@type": "Order",
  "acceptedOffer": [
    {
      "@type": "Offer",
      "price": 3.75,
      "priceCurrency": "GBP"
    },
    {
      "@type": "Offer",
      "@id": "http://my-shop.com/defs.jsonld#RoyalMail48",
      "priceSpecification": {
        "@type": "DeliveryChargeSpecification",
        "price": 2.25,
        "priceCurrency": "GBP"
      }
    }
  ]
}
```

And then, I could specify available shipping methods by associating them with an `Organisation` like this:

```
{
  "@context": "http://schema.org/",
  "@type": "Organisation",
  "name": "My Shop"
  "makesOffer": [
    {
      "@type": "Offer",
      "@id": "http://my-shop.com/defs.jsonld#RoyalMail48",
      "priceSpecification": {
        "@type": "DeliveryChargeSpecification",
        "price": 2.25,
        "priceCurrency": "GBP"
      }
    },
    {
      "@type": "Offer",
      "@id": "http://my-shop.com/defs.jsonld#RoyalMail24",
      "priceSpecification": {
        "@type": "DeliveryChargeSpecification",
        "price": 3.50,
        "priceCurrency": "GBP"
      }
    }
  ]
}
```

Is this close to being right? It doesn't feel right. I mean it's better than my first attempt, but still... I think the `makesOffer` relation for `Organisation` is meant for offers with an `itemOffered` relation pointing to the product that the offer is actually on. Whereas it's unclear what my organisation's offers are on, except that they cost some money to deliver and humans can work out from their names that they're meant to be offers for delivery itself, but I don't think a computer would know this.

I still also don't have a way to specify any meaningful difference between the delivery offers, such as their estimated delivery time, whether they include tracking, how they are packaged, do they re-deliver if you're not in, do they ask for your signature on delivery, does the service have any reviews...etc

May I suggest a new class `DeliveryService` with these options, an `offers` or `priceSpecification` property for prices and for it to be able to be referenced from `Organisation`, `Product` and `ParcelDelivery`. I could have go at making a PR if it would help.
