### ISSUE TITLE
clarify difference between productionDate and vehicleModelDate

### ISSUE THREAD

**Issue by stuartrobinson** [schemaorg/schemaorg#617]
Some users of schema.org may be confused about the difference between productionDate and vehicleModelDate for Car. My understanding of the difference here is that productionDate is when the automobile was actually manufactured whereas the vehicleModelDate is the model year. So, a 2015 VW Jetta might be manufactured in 2014 or 2016. We should update the descriptions to clarify the difference.

**Comment by stuartrobinson** [comment]
It would also be good to clarify how releaseDate differs from productionDate and vehicleModelDate for automobiles. I've seen a few different sites use releaseDate instead of vehicleModelDate. For example, here's a "2015 Ford Escape" with a releaseDate of 2015: http://www.lebanonford.com/details/2015-Ford-Lebanon-OH/3811951

**Comment by danbri** [comment]
On Vehicle, we have:
* http://schema.org/vehicleModelDate "The release date of a vehicle model (often used to differentiate versions of the same make and model)."

On Product, Vehicle:
* http://schema.org/productionDate "The date of production of the item, e.g. vehicle."

On Product,
* http://schema.org/releaseDate "The release date of a product or product model. This can be used to distinguish the exact variant of a product."

Any suggestions for improved wording or clearer distinctions?

/cc @W3C-GAO

**Comment by mfhepp** [comment]
productionDate is the exact date of the production of a particular car. vehicleModelDate is typically the year of the technical platform specification. A Volkswagen Golf 2015 model might actually have been produced on Jan 15, 2016.

Also, vehicleModelDate is often just  year, while the productionDate an exact date. It will matter for a buyer whether the car has been built on Jan 1, 2015 or Dec 31, 2015.

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp
