### ISSUE TITLE
CollectionPage needs a way to link to the things in the collection 

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#618]
I was starting to write up documentation for issue #525, which would list the contents of the collection using mainEntityOfPage.

It occurred to me that it may be better to have a named property for this case to make  the use clearer.  A property like `linkCollection` would let us do something like:

```
{
    "@context": "http://schema.org",
    "@type": "CollectionPage",
    "name": "Vicki's favorite photos",
    "linkCollection": {
        "@type": "ItemList",
        "itemListElement: [
            {
                "@type": "ImageObject",
                "name": "photo 1",
                "url": "http://www.example.com/photo1"
            },
            ...
        ]
    }
}
```

**Comment by jvandriel** [comment]
-1

I think it will only create confusion if there are multiple properties for expressing the main content of a ```schema.org/CollectionPage```. 

For this example I'd simply use ```mainEntity``` and keep at at that.

```
{
    "@context": "http://schema.org",
    "@type": "CollectionPage",
    "name": "Vicki's favorite photos",
    "mainEntity": {
        "@type": "ItemList",
        "itemListElement: [
            {
                "@type": "ImageObject",
                "name": "photo 1",
                "url": "http://www.example.com/photo1"
            },
            ...
        ]
    }
}

**Comment by dtjones** [comment]
@jvandriel, Perfect. Your solution makes me doubt there is even an issue.

**Comment by vholland** [comment]
This could work with the right examples. My worry is it is not obvious enough.

**Comment by jvandriel** [comment]
+1 for first trying this with examples, couldn't agree more and my hope is that if we do that _"not obvious enough"_ won't be an issue (I actually had a go at it: http://bit.ly/1LoJYIm).

And since ```mainEntity``` and ```mainEntityOfPage``` are brand spanking new I'd prefer to wait and see how successful the adoption of these properties will/won't proof be before we start thinking about adding new variants (sub properties?).

**Comment by vholland** [comment]
In that case, I'll close this issue and go back to issue #525 to update the documentation.
