### ISSUE TITLE
Need schema:Archive to parallel schema:Library

### ISSUE THREAD

**Issue by dbs** [schemaorg/schemaorg#628]
In preparing to attend the LODLAM Summit 2015 (Linked Open Data for Libraries, Archives, and Museums), it is glaringly evident that we are missing a class to represent archives.

The simplest possible place to start would be to parallel schema:Library by subclassing schema:LocalBusiness with a definition such as "An entity that collects documents and records related to the activities of people or organizations."

This would enable us to describe archives as a specific class of LocalBusiness with schema.org, rather than having to use LocalBusiness directly.

**Comment by akuckartz** [comment]
:+1: for raising the issue, but not necessarily for the proposed solution (an archive is not or should not be treated as a "business").

**Comment by danbri** [comment]
On this last point, perhaps we should amend LocalBusiness to note something along lines that "businesses may also be not-for-profit or state-owned." (https://en.wikipedia.org/wiki/Business). MedicalOrganizations are a good example of that.

**Comment by Dataliberate** [comment]
+1

~Richard


On 3 Jul 2015, at 21:18, Dan Brickley <notifications@github.com<mailto:notifications@github.com>> wrote:


On this last point, perhaps we should amend LocalBusiness to note something along lines that "businesses may also be not-for-profit or state-owned." (https://en.wikipedia.org/wiki/Business). MedicalOrganizations are a good example of that.

-

**Comment by tjolliffe** [comment]
+1 @akuckartz 
I too would prefer not to associate all archives with businesses.
Some archives are maintained by for-profit institutions by private businesses certainly, but the majority are government, academic and religious. Some others are harder to categorise e.g archives of cultural groups, private papers of an individual, etc. (https://en.wikipedia.org/wiki/Archive)

@danbri @Dataliberate  To me it would be confusing and misleading to categorise archives as a type of Business (the not-for-profit/for profit distinction doesn't adequately convey the type sufficiently). 
Maybe archives could be a subclass of either the GovernmentOrganization or LocalBusiness schema, depending on the type of archive.

**Comment by dbs** [comment]
It would be nice to start with a decent rough fit for Archives in the overall type hierarchy so it can exist and start being used. If a subclass of schema:LocalBusiness is good enough for schema:Library, then I think it should be good enough for schema:Archives (at least to start with)--particularly with the amendment to the schema:LocalBusiness description suggested by @danbri .

Deeper ontological refactoring could then occur in the future.

**Comment by anarchivist** [comment]
+1 to the proposal, and +1 to @danbri's proposed amendment for later. I have some reservations about the use of schema:LocalBusiness, but not strong ones.

I would propose using the following definition for schema:Archive, taken from the ICA's [International Standard for Describing Institutions with Archival Holdings](http://www.ica.org/10198/standards/isdiah):

> **3. GLOSSARY OF TERMS AND DEFINITIONS**
> 
> ...
> **Institution with archival holdings.** An organization which keeps and preserves archival material and makes it accessible to the public.

**Comment by helrond** [comment]
+1 to the proposal, @danbri's amendment, and @anarchivist's suggestion of using the ICA-ISDIAH definition here.

**Comment by sarfarnaa** [comment]
Just joined...Potential properties needed to describe an item in an collection - I think 'Location' in both schema.org Creative object and Image Object "contentLocation" needs to be expanded out if it relates to the item, rather than the collection location. A good model is the IPTC schema, that splits out city, state, country etc.

**Comment by RichardWallis** [comment]
Useful input to the broader discussion in the Archives group:
https://www.w3.org/community/architypes/

~Richard

**Comment by anarchivist** [comment]
Ref #1758

**Comment by RichardWallis** [comment]
Closed - as conversation and a proposal has now moved into issue #1758
