### ISSUE TITLE
PublicAdmistrationService as new superclass of GovernmentService

### ISSUE THREAD

**Issue by retog** [schemaorg/schemaorg#631]
This should also include for example services offered by organs of the judiciary power.

**Comment by dbs** [comment]
I, for one, do not know what the difference is between "public administration" and "government". Can you provide more information about what the difference means, and how adding that additional superclass would practically benefit schema.org with some real examples that illustrate what it would enable?

**Comment by retog** [comment]
The motivation for the issue was that I though that services provided by institutions of the judiciary would not qualify as governmental services as I associated "government" with the executive power. Now I learn that in English government is used to refer both to "the system by which a state or community is controlled" and not only "more narrowly to refer to the collective group of people that exercises executive authority in a state" (wikipedia).

My confusion arises from the fact that Government is generally translated with the German "Regierung" which is the executive power.
