### ISSUE TITLE
Link to testing tool(s)

### ISSUE THREAD

**Issue by dandv** [schemaorg/schemaorg#632]
At http://schema.org/docs/gs.html:

> Google provides a rich snippets testing tool, which you can use to test your markup and identify any errors.

The above should link to [said tool](https://search.google.com/structured-data/testing-tool).

**Comment by danbri** [comment]
If we link to one, we should link to them all. I'd be happy pointing at the Bing, Yandex and other checkers, e.g. http://linter.structured-data.org/ and http://json-ld.org/playground/ . In an ideal world they would all give consistent results. 

That said, gs.html has barely been updated over the years and is overdue for a refresh e.g. to mention JSON-LD...
