### ISSUE TITLE
JSON-LD example for EventCancelled uses invalid date format

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#636]
On:
http://schema.org/EventCancelled

The JSON-LD example contains this declaration:
`"startDate": "Sat Sep 14"`

`startDate`, of course, requires a date in ISO 8601 format, which this is not.

Note that both the RDFa and microdata examples provide the correct value:
`2013-09-14T21:30`

**Comment by mfhepp** [comment]
Will handle that

**Comment by RichardWallis** [comment]
Now part of #865
