### ISSUE TITLE
1st Book example JSON-LD is buggy

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#644]
The Microdata and RDFa also mention WebPage; the JSON-LD mushes them together.

/cc @vholland 

Other issues with this Book example:

* the 'breadcrumb' property usage is goofy. Here I experiment with 'about' instead but we might want to just remove that now.
* Google testing tool complains that the review/rating data is missing info. Does it have a point?

    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Book",
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4",
        "reviewCount": "3077"
      },
      "author": "/author/jd_salinger.html",
      "bookFormat": "http://schema.org/Paperback",
      "about": "Books > Literature & Fiction > Classics",
      "datePublished": "1991-05-01",
      "image": "catcher-in-the-rye-book-cover.jpg",
      "inLanguage": "English",
      "isbn": "0316769487",
      "name": "The Catcher in the Rye",
      "numberOfPages": "224",
      "offers": {
        "@type": "Offer",
        "availability": "http://schema.org/InStock",
        "price": "6.99",
        "priceCurrency": "USD"
      },
      "publisher": "Little, Brown, and Company",
      "review": [
        {
          "@type": "Review",
          "author": "John Doe",
          "datePublished": "2006-05-04",
          "name": "A masterpiece of literature",
          "reviewBody": "I really enjoyed this book. It captures the essential challenge people face as they try make sense of their lives and grow to adulthood.",
          "reviewRating": "5"
        },
        {
          "@type": "Review",
          "author": "Bob Smith",
          "datePublished": "2006-06-15",
          "name": "A good read.",
          "reviewBody": "Catcher in the Rye is a fun book. It's a good book to read.",
          "reviewRating": "4"
        }
      ]
    }
    </script>

The exact example is here: https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/examples.txt#L1166

**Comment by vholland** [comment]
The breadcrumb thing is odd.

SDTT wants a proper Rating entity, so 

```"reviewRating": "5"```

becomes

`"reviewRating": {
       "@type": "Rating",
        "ratingValue": "5"
 }`

**Comment by danbri** [comment]
Note #529 ... maybe we should strip out breadcrumb from these examples for now, until we clarify whether 'breadcrumb' (the property, vs BreadcrumbList) is still useful.

**Comment by RichardWallis** [comment]
Could do - and for now we could preserve a simplified version and attach it
to breadcrumb as a text example
