### ISSUE TITLE
Need new type for How To style articles

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#647]
This has come up a few times, most recently on public-schemaorg@w3.org. There [should be a type for describing instructions outside of recipes](https://lists.w3.org/Archives/Public/public-schemaorg/2015Jul/0017.html). There are a lot of how-to videos and websites that would benefit from the ability to mark up the steps.

**Comment by chaals** [comment]
My preference would be to generalise recipes, but I could live with making something of which recipe is a subclass...

**Comment by danbri** [comment]
An intermediate case: recipes for non-human animals, e.g. DIY dog treats. I would include food recipes for all consumers (including dogs) within Recipe proper, and suggest a clean break and parallel type for 'how to' situations that don't share things like 'yield', 'nutrition', 'cookTime' etc. "Recipe for" can be super metaphorical and applied to almost anything. It would be good to keep Recipe focussed on food and nutrition, so we can improve its relationship to health/medical and product nutrition labelling (gs1) situations.

**Comment by danbri** [comment]
We could (and should) collect some examples of non-food instructions that might be usefully marked up.

For example https://github.com/jarkman/shonkbot has an ordered list of instructions for making an arduino-based robot, including the several products you'll need for doing so. Please suggest others!

**Comment by danbri** [comment]
More use cases, fairly close to foodie recipes but not conventionally considered food:

 * cover medicines (cough syrup)
 * facial scrub
 * homemade floor cleaner

**Comment by chaals** [comment]
@danbri said
> It would be good to keep Recipe focussed on food and nutrition, so we can improve its relationship to health/medical and product nutrition labelling (gs1) situations.

I disagree, but I can live with it. Let's call it a decision and be done.

What about "instructions"?

* How to plug in your devices
* How to troubleshoot your printer / heating / fancy cooking gadget
* How to make furniture (now that you buy it in pieces)

What about the things you need to do and have to apply for a visa, or to get a driver's licence?

**Comment by danbri** [comment]
Thanks re decision. I'm not "over my dead body" about this but sometimes a coin needs flipping decisively one way or the other to unblock things. Let's work through some usecases and see where that takes us, paying particular attention to which clusters of properties are needed for which scenarios.

For your howto instructions (devices, troubleshooting, furniture assembly), visa application and driver's license  ... how important are (a) sequence / order (b) pre-requisites / ingredients? Are the structures more like simple lists (maybe with optional vs required), or are they getting closer to C++ makefiles with complex tree structures? For the visa application case I can see lots of conditional branching, which is scary: "are you married to a national? are you living here currently? are you or have you ever been a member of the xyz party?" ... The others seem easier to attempt with simple list-like structures, perhaps with alternative options for the pre-requisites ('sugar or honey'...).

Related vocabulary: http://schema.org/Question and http://schema.org/Answer  ... which brings us back to the C++/makefile tarpit, the closer we get to technology. The stackexchange (stackoverflow etc.) sites are currently using Question and Answer to mark up their stuff, e.g. view-source:http://serverfault.com/questions/301123/connect-over-wifi-to-sql-server-from-another-computer

Do you have a 'recipe' (howto, instruction etc.) for "Connect over WiFi to SQL Server from another computer"?

That particular site doesn't give explicit list ordering to the answers, but you can see list-like patterns in the prose for this (randomly picked) example:

    <div itemscope itemtype="http://schema.org/Question">
      <link itemprop="image" href="//cdn.sstatic.net/serverfault/img/apple-touch-icon.png?v=6c3100d858bb">
      <h1 itemprop="name"><a href="/questions/301123/connect-over-wifi-to-sql-server-from-another-computer" class="question-hyperlink">Connect over WiFi to SQL Server from another computer</a></h1>
      <span itemprop="upvoteCount" class="vote-count-post ">1</span>
      <div class="post-text" itemprop="text">
      <p>I tried to connect over WiFi to SQL Server with SQL Server Management Studio from another computer, but it failed.</p>
      ...
     <span style="display:none;" itemprop="answerCount">4</span>
    </div>

    + several answers, e.g.

    <div id="answer-301619" class="answer" data-answerid="301619"  itemscope itemtype="http://schema.org/Answer">
      <span itemprop="upvoteCount" class="vote-count-post ">1</span>
      <div class="post-text" itemprop="text">
      <p>First, the way to address a specific SQL server instance is: SERVERNAME\INSTANCENAME</p>
      <p>So, first step is to see if you can resolve SERVERNAME (use ping or change it for an IP address).</p>
      <p>The second step is to see if the specific instance exists. Typically, the first instance of MSSQL server is using the default instabnce name (. or MSSQLSERVER). If that's the case, you can omit the instance name in your connection string and keep the server name only.</p>
    ...
    </div>

Given that the Web is awash with ordered [listicles](https://en.wikipedia.org/wiki/Listicle) there might be a trend towards sites making such structure more explicit. I haven't dug too deeply but https://en.wikipedia.org/wiki/Listicle#Collaborative has some examples.

**Comment by duckAsteroid** [comment]
You should check out [DITA task topics](http://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/dita_generic_task_topic.html). 

Note: I think this stuff goes back even further to similar looking structures in SGML.

**Comment by danbri** [comment]
Thanks @duckAsteroid - very interesting! They get around the formally-structured-vs-informal by having specs for both. We do much the same in schema.org in a few places already too.

**Comment by tomwaddington** [comment]
I run a site with [recipes](http://www.cutoutandkeep.net/projects/french-macaroons-2) and [tutorial](http://www.cutoutandkeep.net/projects/galaxy-print-shoes) content - I'd love to see something more generic than recipes, and more specific than articles for the content.

I could imagine ItemList > InstructionList, with a listitem containing step data, images/video etc.

**Comment by dragonghy** [comment]
@danbri any chance could I get some feedback for this?

**Comment by danbri** [comment]
I'd like to move ahead in this direction. Does anyone here think that we shouldn't? 

/cc @ajax-als @chaals @mfhepp @pmika @scor @shankarnat @tmarshbing @vholland @rvguha

**Comment by chaals** [comment]
On Sun, 13 Dec 2015 14:38:22 +0300, Dan Brickley  
<notifications@github.com> wrote:

>
> I'd like to move ahead in this direction. Does anyone here think that we  
> shouldn't?
agree we should

-- 
Charles McCathie Nevile - web standards - CTO Office, Yandex
  chaals@yandex-team.ru - - - Find more at http://yandex.com

**Comment by vholland** [comment]
Small nit: The JSON-LD example needs "@list" to preserve the order of the instructions. Other than that, it looks good to me.

**Comment by dragonghy** [comment]
Sorry I haven't been an active github user apparently and missed the notification.  :P

We have been actively pushing the how-to schemas with our partners and ~20 partners are using it today internationally. We have slightly updated the schemas since then. I'll update here as well.

@danbri @chaals @vholland: what's the best way to contribute to schemas.org? should I send out a pull request?

**Comment by danbri** [comment]
Thanks for the nudge - it would be good to progress this. Yes, please join the main Schema.org Community Group over at W3C - https://www.w3.org/community/csvw/ - and then submit a pull request here. The relevant files are all in the data/ directory in the repo. If anything is confusing please ping here.

**Comment by Dataliberate** [comment]
Basic structure looks fine.  @vholland "@list" would not be needed if 'position', 'nextItem', 'previousItem' were used to indicate ordering in all serialisations.

The use of 'tutorial' in the naming may conflict in other domains "noun: a period of tuition given by a university or college tutor to an individual or very small group".   Perhaps 'method' would be more appropriate "a particular procedure for accomplishing or approaching something, especially a systematic or established one"

**Comment by danbri** [comment]
re naming issues and overlaps - @philbarker could you take a look from an LRMI and courses perspective.

@dragonghy for context - we have also got some substantial efforts around markup for courses underway - see https://www.w3.org/community/schema-course-extend/

**Comment by dragonghy** [comment]
Thanks @danbri. I just signed up on w3c. It took me some time to understand how the community, the email thread and the example website come together. :) 

We are very open to rename the schemas. "method" sounds good to me. We've also been thinking about "HowTo", "StepByStepTutorial" etc. 

re: course seems very relevant. Very excited that there's already such a great discussion in the community. Here's my understanding after reading [the pull request](https://github.com/westurner/schemaorg/commit/1ef4a565e4e5e643a81b600eab93cfd94cf7e626) and [the sample page](http://course.schema-course-extend.appspot.com/Course).

The course object (at least for now) seems to be heavily designed for academia purpose but has less support for a DIY commercial provider (e.g. [brit.co's DIY content](https://www.brit.co/hanging-storage-bag/), or a [comprehensive step-by-step recipe](https://snapguide.com/guides/make-roast-pepper-salad-with-peanut-dressing/). The current new fields in course don't seem to help at much (if any). 

On the other hand, I do see a potential that some of the how-to tutorial fields may be useful to a course. Like supplies and yield (imagine it's an one-off sushi making course offered in San Francisco).

**Comment by philbarker** [comment]
@danbri On the naming & overlaps, in Higher Education at least, tutorial is already ambiguous. My experience is that the individual or small group tuition definition that @Dataliberate cites is now the exception (in practice at least, though perhaps not in people's minds), and that 
" n. Something that provides special, often individual instruction, especially:
a. A book or class that provides instruction in a particular area.
b. Computers A program that provides instruction for the use of a system or of software."
(via http://www.thefreedictionary.com/tutorial) is more prevalent. 

I don't think that calling this a tutorial causes any more confusion than already exists. Looking (briefly) at the scope of this discussion, it might be that "instruction set" would be less ambiguous and still encompass the sense of tutorial in the definition above.

**Comment by danbri** [comment]
In that case let's do it. We can try alternate wording once there is a draft implementation for wider review.

**Comment by Dataliberate** [comment]
InstructionSet sounds a good compromise. 

~Richard

**Comment by vholland** [comment]
Yes, the example either needs @list or to use nextItem or position.

**Comment by danbri** [comment]
Some related work here: https://datahub.io/dataset/human-activities-and-instructions (via @bquinn)

**Comment by socceroos** [comment]
Parallel to this proposal, are there plans to have a schema for WebGL based instructional items? Currently the 'video' schema is the closest thing but it seems improper to use.

An example: https://jig.space/view?jig=1o7L8e7d

It's both instructional and interactive. Video doesn't cover it, nor does this generic instructions proposal.

**Comment by danbri** [comment]
We ought to indicate when some Web content is available that gives deeper (textual, interactive or whatever) coverage of a recipe or HowTo...

**Comment by earljwagner** [comment]
The current proposal offers some options for other web media for instructions:
- To illustrate directions (i.e. actions) in individual steps, a HowToDirection can have before/during/afterMedia properties set.
- The "steps" property of a HowTo can be any CreativeWork, not just text.
- At the most general level, a HowTo inherits the "associatedMedia" property for CreativeWork.

**Comment by danbri** [comment]
@earljwagner yes, another pattern is also just that the page with the HowTo content also has an embedded MediaObject (in which case presumably best practice would be for the markup to make the association explicit rather than implicit, eg. with associatedMedia or the more granular options you mention). If the link isn't made it is probably still a fairly safe bet that that video is about the howto'd task.

**Comment by vholland** [comment]
We have HowTo now.
