### ISSUE TITLE
Allocating terms to the extension they are defined in

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#655]
Add an isPartOf property to term definitions in RDFa data files (defaults to 'core').
In code use this to identify homeLayer for a node.
Error check for a term being defined as part of a unknown extension, or defined in more than one.
This will not prevent a term being mentioned in more than one extension.

**Comment by danbri** [comment]
e.g. if MedicalEntity were moved into 'health', we'd express this as

* http://schema.org/MedicalEntity isPartOf http://health.schema.org/

We could also represent this as 

* http://schema.org/MedicalEntity someRelationshipHere http://health.schema.org/MedicalEntity

... but the former is fine and allows easy query of the extension within which a term is "based".
