### ISSUE TITLE
https://schema.org/branch needs a more medical/health-oriented name

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#661]

**Comment by twamarc** [comment]
Follow this at https://github.com/schemaorg/schemaorg/issues/492

@danbri : can we close this thread?

**Comment by danbri** [comment]
#492 is very general. What was the specific resolution in the pull request?

**Comment by twamarc** [comment]
I agree. Let's just reference this in @492 instead of closing it.
