### ISSUE TITLE
Final example for ItemList does not employ ItemList

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#666]
The final example on http://schema.org/ItemList doesn't use ItemList.  It uses other list types and properties, but not the one in question.

**Comment by danbri** [comment]
I found this useful, since http://schema.org/BreadcrumbList is a kind of ItemList. Do you think this is confusing people heavily? 

We could remove it, comments in the markup, ... or leave as-is. I lean towards the latter. At some point we'll add the ability to have an explanatory sentence on each example, which might help.

**Comment by Aaranged** [comment]
Since it is a more specific type of ItemList there's certainly a relationship, but as it's the same example used by BreadcrumbList I don't think it adds tremendous value.  I guess whether or not this is useful depends on whether users are expected to understand the relationship with more specific types, and therefore that this is a once-removed example for the type in question.  I think that's quite an assumption, and that one would normally expect to see, in broad terms, an example of a thing described, rather than some sub-class of that thing.

In that vein I say descendant types should sport annotations, whether that's in the example code or elsewhere.  This, too, because the site is not consistent in showing more specific types as a proxy example for the described type - though, yes, in fairness it often does.  To that end a simple it might cover all such examples merely to note for the example section that more specific types might me used.

**Comment by radusi** [comment]
The below example seems not to be valid json-ld , by SDTT. 

<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ItemList",
  "url": "http://multivarki.ru?filters%5Bprice%5D%5BLTE%5D=39600",
  "numberOfItems": "315",
  "itemListElement": [{
      "@type": "Product",
      "image": "http://img01.multivarki.ru.ru/c9/f1/a5fe6642-18d0-47ad-b038-6fca20f1c923.jpeg",
      "url": "http://multivarki.ru/brand_502/",
      "name": "Brand 502"
    },{
      "@type": "Product",
      "name": "..."
    }
  ],
    "offers": {
      "@type": "Offer",
      "price": "4399 p."
    }
}
</script>

![itemlist-broken-example](https://cloud.githubusercontent.com/assets/990840/9813724/c482f4b2-5890-11e5-958f-85c8c6a418c1.jpg)

**Comment by vholland** [comment]
Most of the errors listed relate to Google-specific features. For example, position can not be required in the general case because the ItemList may represent an unsorted set.

With that said, the output is correct that "offers" is not a property of ItemList. I'm guessing the offer was supposed to be associated with the Product above it.

**Comment by jvandriel** [comment]
It might be best to keep discussing the Google specific issues over on  https://plus.google.com/u/0/communities/103048251221048356778 @radusi.

Having said that, I also noticed the final JSON-LD example on schema.org/Product contains the same markup 'flaw'. So I've went ahead and wrote up 2 new examples. One where a schema.org/ItemList (+ ```mainEntityOfPage```) is the top level entity and one where a schema.org/CollectionPage (+ ```mainEntity```) is the top level entity.

```
<script type="application/ld+json">
{
  "@context":"http://schema.org",
  "@type":"ItemList",
  "itemListOrder":"ItemListOrderAscending",
  "itemListElement": [{
    "@type":"ListItem",
    "position":"1",
    "item":{
      "@type":"Product",
      "image":"http://example.com/some-image-1.jpg",
      "name":"Product 1",
      "url":"http://example.com/some-product-1",
      "offers": {
        "@type":"Offer",
        "price":"4399",
        "priceCurrency":"USD"
      }
    }
  },{
    "@type":"ListItem",
    "position":"2",
    "item":{
      "@type":"Product",
      "image":"http://example.com/some-image-2.jpg",
      "name":"Product 2",
      "url":"http://example.com/some-product-2",
      "offers": {
        "@type":"Offer",
        "price":"999",
        "priceCurrency":"USD"
      }
    }
  }],
  "mainEntityOfPage":{
    "@type":"CollectionPage",
    "@id":"http://example.com/products/"
  },
  "numberOfItems":"315"
}
</script>
```
```
<script type="application/ld+json">
{
  "@context":"http://schema.org",
  "@type":"CollectionPage",
  "@id":"http://example.com/products/",
  "mainEntity":{
    "@type":"ItemList",
    "itemListOrder":"ItemListOrderAscending",
    "numberOfItems":"315",
    "itemListElement": [{
      "@type":"ListItem",
      "position":"1",
      "item":{
        "@type":"Product",
        "image":"http://example.com/some-image-1.jpg",
        "name":"Product 1",
        "url":"http://example.com/some-product-1.jpg",
        "offers": {
          "@type":"Offer",
          "price":"4399",
          "priceCurrency":"EUR"
        }
      }
    },{
      "@type":"ListItem",
      "position":"2",
      "item":{
        "@type":"Product",
        "image":"http://example.com/some-image-2.jpg",
        "name":"Product 2",
        "url":"http://example.com/some-product-2.jpg",
        "offers": {
          "@type":"Offer",
          "price":"999",
          "priceCurrency":"EUR"
        }
      }
    }]
  }
}
</script>
```

**Comment by radusi** [comment]
I apologize, I used SDTT for validation, and found some errors I did not understood.

**Comment by joeinfo** [comment]
jvandriel thank you so much! 
i'd wasted all morning trying to figure out how to place multiple items into the schema of a single page. your two examples posted just above saved the day! (but, just so you know, the first example throws a very simple error in google's structured data testing tool that is very easy to fix: 
"All values provided for url must point to the same page."
a quick question... when would it be appropriate to add the type:CollectionPage (your example 1) versus skipping it (as you did with example 2)?
thank you!

**Comment by vholland** [comment]
Closing. Google tools should be discussed on Google developers' site.
