### ISSUE TITLE
Price = POA

### ISSUE THREAD

**Issue by Stuperfied** [schemaorg/schemaorg#667]
If the price of an item returns a POA, Coming Soon or other text, this is not handled by itemprop="price".

https://schema.org/price
Values expected to be one of these types
Number 
Text <-- Here is where the documents specify that price can take text values. Does this just mean numbers as strings?

Google
offers [Offer]:
priceCurrency:	AUD
availability:	http://schema.org/InStock
! price:	POA

The property POA is not a valid price specification.
Required by:
Products Rich Snippets

**Comment by Dreyer** [comment]
For what it's worth, in areas of Real Estate (among others) it is common to have a 'Price Qualifier', when in relation to property could potentially be any of the following:

- Asking Price
- Price on Application (POA)
- Guide Price
- Fixed Price
- Offers in Excess of (OIEO)
- Offers in Region of (OIRO)
- Price From
- Offers Over

A `priceQualifier` property would need to be added to https://schema.org/Offer or https://schema.org/PriceSpecification and the options enumerated as `PriceQualifierType`.

**Comment by mfhepp** [comment]
priceType is IMO sufficient for this

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by Dreyer** [comment]
`priceType` looks suitable and may work for @Stuperfied as it appears to be valid in the context of a https://schema.org/UnitPriceSpecification which makes sense for `Offers` which are considered consignments of units with a specific measurement (`unitCode` and `unitText`).

@mfhepp do you think it also makes sense for a Real Estate context where there is no need for `unitCode` and `unitText`? I guess you could include the square footage of the land covered but it doesn't seem particularly intuitive.

**Comment by danbri** [comment]
Sounds like priceType addresses the core issue. Please continue any real estate -oriented price conversations in #241 or nearby, so we can close out this issue. Thanks!
