### ISSUE TITLE
Add an UnsubscribeAction

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#669]
Schema.org has http://schema.org/SubscribeAction, but no unsubscribe action. There shoudl be reciprocal actions like http://schema.org/RegisterAction and http://schema.org/UnregisterAction.

**Comment by vholland** [comment]
And now that I look at it again, there is http://schema.org/FollowAction, but now http://schema.org/UnfollowAction.

**Comment by Download** [comment]
Yes there are more like these. 

E.g I see BefriendAction. but no UnfriendAction?
Also, UnRegisterAction uses bad spelling. The 'r' schould not be capitalized.

Most of the time, actions come in pairs. Perfoming one then the other will leave the system in the same state it started in. This should be reflected in schema.org. Many actions are missing their counterpart.

Also, where are Login/Logout? Seem like very common actions on the web but closest I find in schema.org are Join/Leave, which don't quite match.
