### ISSUE TITLE
Schema-Type for a journey

### ISSUE THREAD

**Issue by thungsten** [schemaorg/schemaorg#674]
I'm missing a type which is describing a journey.

We have diaries in which our customers can describe their journeys.
So each day has a description a journey consists of several days and each journey has a start and an end date.
How should I describe that?
Within the journey the customers may have attended other events like concerts or made (day) trips to specific locations, e.g. Eiffel Tower, Sydney. 

Is a event the proper type for this? Or has this to be created?

**Comment by realworldobject** [comment]
The notion of "diary" suggest a relationship between schema:CreativeWork and schema:Event that the newly-formed archive-related sub-group might consider.

Jeff



On Jul 28, 2015, at 5:09 PM, thungsten <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm missing a type which is describing a journey.

We have diaries in which our customers can describe their journeys.
So each day has a description a journey consists of several days and each journey has a start and an end date.
How should I describe that?
Within the journey the customers may have attended other events like concerts or made (day) trips to specific locations, e.g. Eiffel Tower, Sydney.

Is a event the proper type for this? Or has this to be created?

-
