### ISSUE TITLE
PostOffice subtype of GovernmentOffice - not in countries where PostOffice is privatized

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#682]
http://schema.org/PostOffice

Not sure this should be a subtype

**Comment by chaals** [comment]
On Thu, 30 Jul 2015 09:27:39 -0400, Dan Brickley
<notifications@github.com> wrote:

> http://schema.org/PostOffice
>
> Not sure this should be a subtype

Hmm. Some Post Offices are also a GovernmentOffice, others are not.

I guess we should not make it a subtype, but recommend that where people  
want to note that something functions as a post office and as other types  
of government office they mark that explicitly.

Which raises a more general question about why we have GovernmentOffice. A  
military base hosting foreign forces, a government stationery supply, a  
passport office, and a government-run kindergarten might all be government  
offices, but I'm not sure what that tells us...

-- 
Charles McCathie Nevile - web standards - CTO Office, Yandex
    chaals@yandex-team.ru - - - Find more at http://yandex.com
