### ISSUE TITLE
Add catalogNumber and price to VideoGame

### ISSUE THREAD

**Issue by cougrimes** [schemaorg/schemaorg#686]
We are in the middle of adding VideoGame support to all pages on Sega Retro (https://segaretro.org) but noticed that two key areas we track--the catalog number issued by a video game publisher and the price at time of release--are not supported properly by VideoGame (their corresponding tags being available in MusicRelease and Product, respectively.) 

As games are often both Creative Works AND Products, would it be possible to get this markup? Examples of this being recorded on the site include

http://segaretro.org/Ecco_the_Dolphin:_Defender_of_the_Future
http://segaretro.org/Normy%27s_Beach_Babe-O-Rama
http://segaretro.org/Mappy

**Comment by vholland** [comment]
You can do this today by combining the two types. In JSON-LD, it would look something like:

```
{
  "@context": "http://schema.org",
  "@type": ["VideoGame", "Product"],
  "name": "Mappy",
  "@id": "http://segaretro.org/Mappy",
  "productId": "T-14027",
  "offers": {
    "@type": "Offer",
    "price": 3500,
    "priceCurrency": "JPY"
  }
}
```

**Comment by mfhepp** [comment]
Hi, I agree that this is the recommended way of modeling products for which specifc types exist in schema.org, albeit not as subtypes of Product.

Note, however, that the SDTT currently complains about multi-typed entities:

 "The type is not a type known to Google."

Martin
