### ISSUE TITLE
New type for barcode images [final task: add an example]

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#687]
It would be useful if there were a child type of http://schema.org/ImageObject for barcodes (including QR codes) so that readers of the data can handle them appropriately.

**Comment by danbri** [comment]
Good idea. Is there any obvious structure here, or just pass it to the barcode tools to figure out?

**Comment by vholland** [comment]
At a minimum, it lets barcode tools do the Right Thing(tm). One thought is to add all of the gtin properties, so you don't even have to scan the barcode.

**Comment by RLRichardson** [comment]
The vast majority of barcodes don't include GTINs, and there's a potentially complicated structure associated with those that carry more than just the GTIN. QR's can be even more complicated as there aren't many structured approaches in place. Dan's suggestion to just pass it along is a good one IMHO

**Comment by danbri** [comment]
(and as I'm writing this, RLRichardson comments before I could even look up his GitHub ID :)

yes - thinking of gtin - https://github.com/zxing/zxing has a list ... probably the main thing to do is figure out how barcode images relate to the various /Product codes. I hear from the GS1 team that the numerous gtin* properties may converge on a single unified representation btw. So hypothetically, a 'gtin' property would apply directly on the image, for example? Our definitions for gtin13 and gtin8 mention EAN (e.g. gtin13 "The GTIN-13 code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13.").

See also:

 * http://barcode4j.sourceforge.net/
 * https://github.com/woo-j/OkapiBarcode
 * http://zbar.sourceforge.net/
 * http://barcode4j.sourceforge.net/
 * https://github.com/zxing/zxing

**Comment by vholland** [comment]
I added a new type, but no properties in pull request #766.

**Comment by danbri** [comment]
Merged for review/discussion. 

http://sdo-phobos.appspot.com/Barcode

Also note that we have 

<http://schema.org/ticketToken> <http://www.w3.org/2000/01/rdf-schema#comment> "Reference to an asset (e.g., Barcode, QR code image or PDF) usable for entrance." .

... in the schemas nearby. It seems complementary. We could add Barcode or CreativeWork to the range values for ticketToken but I don't think that is essential.

**Comment by kevinp1** [comment]
This would be useful. +1

**Comment by danbri** [comment]
@shankarnat @mfhepp @chaals @tilid @ajax-als @scor @mfhepp ... please review! http://sdo-phobos.appspot.com/Barcode

**Comment by chaals** [comment]
Looks OK to me. Reminds me that I need to tweak the examples for imageObjects to have descriptions… QR codes and barcodes often have *text* (property inherited from Thing), which should be in the examples when we get some.

**Comment by RichardWallis** [comment]
Looks good - would a 'associatedCode' Text property be useful to identify
the code the barcode encodes?

~Richard.

**Comment by chaals** [comment]
I would prefer we recommend using the text property (I think it is on CreativeWork actually) rather than minting a duplicate for this case...

**Comment by danbri** [comment]
Thanks @chaals. Yeah - better examples would be great. I made a pass through fairly recently adding alt text to any HTML examples using img element but you're right, there are lots of under-described images elsewhere.

@RichardWallis (on the related point), I'd suggest we use http://schema.org/text ("The textual content of this CreativeWork.") for now for textual serialization of the barcode's content.  And @chaals just agreed before I finished typing this :) Ok, fine! For codes, when we clean up 'code' property and do something to align closer to SKOS we could at treating this as a more controlled string, but given the chaotic variety of barcoding systems, text is more than adequate for now in my experience.

**Comment by RichardWallis** [comment]
suggest we use http://schema.org/text ("The textual content of this
CreativeWork.") for now for textual serialization of the barcode's content.


+1

Associated example(s) should represent this.

~Richard.

**Comment by danbri** [comment]
@RichardWallis is right - we should have at least one example of a barcode whose content as text we also supply. Proposals / contribs welcome! I'd love a book example and something like food packaging...

**Comment by danbri** [comment]
Hmm we don't actually have any precedent for schema.org examples that have inline visible images, they're all just URLs since we only show markup. I was thinking we needed an image to include.

Anyway, http://i.imgur.com/ghgr2hF.png?1 is the barcode from the back of a book - 

text is "9 780262 521123 90000" roughly (transcribed by me; how strict are the whitespace rules?)

![9 780262 521123 90000](http://i.imgur.com/ghgr2hF.png?1)

See also 

* http://www.amazon.com/Vehicles-Experiments-Psychology-Valentino-Braitenberg/dp/0262521121
* https://books.google.nl/books?id=7KkUAT_q_sQC&redir_esc=y
* http://www.worldcat.org/title/vehicles-experiments-in-synthetic-psychology/oclc/18269344

Question for extra points: if we know the creative work, product etc that the barcode codes for, how are they associated? 'about' ?

**Comment by mfhepp** [comment]
We could also simply recommend the use of 

    http://schema.org/text ("The textual content of this CreativeWork.") 

for this purpose, or http://schema.org/caption or name/description.

But I think "text" is best.

I also briefly thought about including the new type in the domain of schema:productID, but barcodes and QR codes can be used for a very broad range of things

So my proposal is to use schema:text and add 

"Use 'text' for a textual representation of the code" 

to the description of the new type.

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by mfhepp** [comment]
Oops, this is the risk of commenting via email. You have already agreed upon schema:text ;-)

**Comment by danbri** [comment]
@mfhepp wouldn't adding ""Use 'text' for a textual representation of the code"" duplicate the existing schema documentation structure? I'd rather the indication that 'text' is particularly appropriate be communicated via examples. Which brings us back to: what shall we show in the examples w.r.t. associating the Barcode with other entities? Simplest for now is just a Barcode item, nothing more, and a text property. Can we do better?

**Comment by RLRichardson** [comment]
I haven’t followed this string, but depending on what you’re attempting to do here, there are multiple options:

If it’s a simple reference example, no worries, except that you don’t provide a framework for understanding and using the textural data.

If you’re attempting to create a more useful approach that includes explanation and context, it becomes very complex very quickly.

Given the wide variety of symbologies, and associated data formats for same, you may want to consider reaching out to GS1 as a resource for feedback.

Rich Richardson | Vice President, Emerging Capabilities and Industries | GS1 US
1009 Lenox Drive, Suite 202, Lawrenceville, NJ 08648 | T +1 609.620.4526 | M +1 609.610.3806 | E rrichardson@gs1us.org<mailto:rrichardson@gs1us.org> | www.GS1US.org<http://www.gs1us.org/>
The Global Language of Business | Making it possible for industries and companies to move their business forward

"The things we consider to be everyday have extraordinary effects on places we’ve never heard of."  Kate Davies
Click To Follow Me [Twitter Logo] <https://twitter.com/?lang=en>
See the It's Just Commerce™  Video at  http://youtu.be/pkrxhefQIBs
P Before printing, think about ENVIRONMENTAL responsibility

**Comment by danbri** [comment]
To answer my own question, 'image' (linking to a barcode from something it represents) is probably better than 'about' (linking in the other direction).

@RLRichardson thanks - the goal for now is to define a simple Barcode type without trying to represent the many varied types of barcode system and content that they carry. We could potentially go deeper later in collaboration with GS1 but it is important to start simple.

The working assumption so far in this thread is that we should add a basic Barcode example, and that it should also show in the form of a 'text' property, a textual representation of the barcode's contents.  It is quite possible that richer knowledge of the barcode type, workflow context etc., would allow the code to map into richer properties (e.g. gtins) than plain text. But to establish a basic structure let's do something with 'text' first. In this context, can we work up a product-oriented example here? I'd like to have a Book example and maybe some kind of packaged food too if possible.

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all. Leaving this open as we still need to add an example of Barcode markup.

**Comment by danbri** [comment]
Ok, final works then:

* let's make an example based on http://i.imgur.com/ghgr2hF.png?1
* do we extend values of ticketToken to explicitly anticipate Barcode values?
* AOB?

**Comment by danbri** [comment]
was this ever used? examples?

**Comment by vholland** [comment]
https://schema.org/Barcode exists.
