### ISSUE TITLE
contentRating should allow for separating the rating organization from the rating.

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#689]
http://schema.org/contentRating currently expects text like "MPAA PG-13". Many authors simply provide the rating (e.g. "PG-13") and omit the rating organization.

It would be helpful to include in the range a ContentRatingScore with properties:
- contentRatingOrganization
- contentRating

It would make clear how to separate the rating organization and would allow for markup like:

```
{
  "@context": "http://schema.org",
  "@type": "Movie",
  "name":  "Ghostbusters",
  "contentRating": [
    {
      "@type": "ContentRatingScore",
      "contentRatingOrganization": {
         "@type": "Organization",
         "name": "MPAA",
      },
      "contentRating": "PG",
    },
    {
      "@type": "ContentRatingScore",
      "contentRatingOrganization": {
         "@type": "Organization",
         "name": "BBFC",
      },
      "contentRating": "PG",
    },
    {
      "@type": "ContentRatingScore",
      "contentRatingOrganization": {
         "@type": "Organization",
         "name": "France Ministry of Culture",
      },
      "contentRating": "U",
    },
  ]
}
```

**Comment by stephandreyer** [comment]
Thanks @philarcher1 for pointing me at this. My name is Stephan Dreyer and I currently co-ordinate a EU-cofunded project on making electronic age classifications interoperable ("MIRACLE"). FYI, we've developed a vocabulary for age classification at http://www.miracle-label.eu that is capable of providing information both on the age rating and the rating organization (plus, different age ratings from different organizations where available). We have focussed on XML/XSD up to now, but a MIRACLE-based JSON label would look like this (with age-issuer and age being the only mandatory elements, btw):
```
{
    "age-declaration": {
        "issuer": {
            "age-issuer": "BBFC",
            "issuer-url": "http://www.bbfc.co.uk",
            "issuer-licence": "http://www.bbfc.co.uk/sites/default/files/attachments/BBFC%20Digital%20Licence_0.pdf",
            "country": [
                "GB"
            ]
        },
        "scope-titles": {
            "BBFC-title": "HALO 3"
        }
    },
    "rating": {
        "age": 15,
        "age-icons": {
            "BBFC-symbol": "http://api.bbfc.co.uk/symbols/15.png"
        }
    },
    "content-descriptors": {
        "cd-opentext": {
            "BBFCInsightShort": "Contains strong violence"
        }
    }
}
```
Would it make sense to ponder about potential synergies between schema.org and the MIRACLE considerations?

**Comment by vholland** [comment]
We added support for this in schema.org 3.4.
