### ISSUE TITLE
Search overlapped by h1

### ISSUE THREAD

**Issue by Camwyn** [schemaorg/schemaorg#691]
On the schema.org website the `<h1>` overlaps the search box making it nearly un-clickable and thus all but unusable.
<img width="774" alt="screen shot 2015-08-03 at 5 20 08 pm" src="https://cloud.githubusercontent.com/assets/929375/9048136/baf1e49e-3a04-11e5-8115-95a41bf79489.png">

 Chrome Version 44.0.2403.125 (64-bit) OSX Yosemite Version 10.10.4 (14E46).

**Comment by danbri** [comment]
Thanks. We think @RichardWallis 's commits fixed this last night. After some other attempts we eventually added a slightly heavy-handed extra <div> for the CSS. Perhaps not ideal but usability is more important than markup beauty. Sample page (not yet pushed to schema.org proper), http://webschemas.org/Person

**Comment by RichardWallis** [comment]
Was fixed
