### ISSUE TITLE
Contributing schema for genomic data description

### ISSUE THREAD

**Issue by KimJBaran** [schemaorg/schemaorg#702]
Hi!

I (plus collaborators) would like to contribute schema for the description of genomic data. I have [posted about this](https://lists.w3.org/Archives/Public/public-schemaorg/2015Aug/0000.html) on the mailing list too, but have not heard anything back yet.

Since this is GitHub, I get a bit more technical with an example that shows what the genomic JSON-LD data description can do.

There are currently over [100 JSON-LD properties](https://www.codamono.com/biointerchange/documentation/#json-reference-cards) defined over 4 types, of which 16 properties and 2 types are specific to the software that is using those properties. The remaining 80+ properties and 2 meta-/feature-types have been compiled from the following specifications:
1. [Generic Feature Format Version 3](http://www.sequenceontology.org/gff3.shtml)
2. [Genome Variation Format](http://www.sequenceontology.org/resources/gvf.html)
3. [Variant Call Format](https://samtools.github.io/hts-specs/VCFv4.2.pdf)

All of this is actually a continuation of the work on the [Genomic Feature and Variation Ontology](https://peerj.com/articles/933/) -- except that the genomic JSON-LD specification addresses critique as received during the peer-review process.

Here is an example of a genomic feature description:

``` javascript
{
    "@context" : "https://www.codamono.com/jsonld/gvf-f1.json",
    "id" : "76",
    "locus" : {
        "landmark" : "Chr1",
        "start" : 675,
        "end" : 675,
        "strand" : "+"
    },
    "source" : "SGRP",
    "type" : "SNV",
    "dbxref" : [
        "SGRP:s01-675",
        "EMBL:AA816246"
    ],
    "reference" : {
        "sequence" : "A",
        "codon" : "GAG"
    },
    "variants" : {
        "B" : {
            "sequence" : "G",
            "codon" : "GAG"
        },
        "C" : {
            "codon" : "GGG",
            "sequence" : "T"
        }
    }
}
```

With the `@context`, this expands to (converted in the [JSON-LD Playground](http://json-ld.org/playground/)):

```
_:b0 <https://www.codamono.com/gfvo-squared#dbxref> _:b6 .
_:b0 <https://www.codamono.com/gfvo-squared#id> "76" .
_:b0 <https://www.codamono.com/gfvo-squared#locus> _:b1 .
_:b0 <https://www.codamono.com/gfvo-squared#reference> _:b2 .
_:b0 <https://www.codamono.com/gfvo-squared#source> "SGRP" .
_:b0 <https://www.codamono.com/gfvo-squared#type> "SNV" .
_:b0 <https://www.codamono.com/gfvo-squared#variants> _:b3 .
_:b1 <https://www.codamono.com/gfvo-squared#end> "675"^^<http://www.w3.org/2001/XMLSchema#integer> .
_:b1 <https://www.codamono.com/gfvo-squared#landmark> "Chr1" .
_:b1 <https://www.codamono.com/gfvo-squared#start> "675"^^<http://www.w3.org/2001/XMLSchema#integer> .
_:b1 <https://www.codamono.com/gfvo-squared#strand> "+" .
_:b2 <https://www.codamono.com/gfvo-squared#codon> "GAG" .
_:b2 <https://www.codamono.com/gfvo-squared#sequence> "A" .
_:b3 <https://www.codamono.com/gfvo-squared#alleleB> _:b4 .
_:b3 <https://www.codamono.com/gfvo-squared#alleleC> _:b5 .
_:b4 <https://www.codamono.com/gfvo-squared#codon> "GAG" .
_:b4 <https://www.codamono.com/gfvo-squared#sequence> "G" .
_:b5 <https://www.codamono.com/gfvo-squared#codon> "GGG" .
_:b5 <https://www.codamono.com/gfvo-squared#sequence> "T" .
_:b6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "SGRP:s01-675" .
_:b6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b7 .
_:b7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "EMBL:AA816246" .
_:b7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
```

At the moment, GFVO-squared properties are only described in combination with the [genomics JSON-LD reference](https://www.codamono.com/biointerchange/documentation/#json-reference-cards). An ontology file (in OWL) will be available at some point. The OWL file will be generated from the JSON-LD reference though, so in this sense, the documentation is already in a very good state.

It would be great hearing back from you.

Thanks!

Kim

**Comment by RichardWallis** [comment]
Hi Kim,

This looks like a candidate for a potential extension proposal such as
'bib' and 'auto' - checkout bib.schema.org and auto.schema.org in Schema
version 2.1 is released - just released.

The proposal should consist of a definition RDFa file - see the bib one:
https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/ext/bib/bsdo-1.0.rdfa

Also examples would ideally need defining in the various syntaxes JSON-LD,
RDFa, Microdata.

Shout if you need help in that area.

Then the proposal can be looked at and discussed by the community both for
consistency, name clashes with the rest of the vocabulary & extensions, the
use of term names that may have different meanings elsewhere, and potential
candidate for core terms.

~Richard

**Comment by indiedotkim** [comment]
@RichardWallis Hi!

Thank you for the link outs!

Can you clarify though:

> Also examples would ideally need defining in the various syntaxes JSON-LD,
RDFa, Microdata.

If I understand it correctly, then all JSON-LD examples would *also* have to be presented as RDFa and Microdata? It sounds reasonable, but I want to make sure that I get it right.

Kim

**Comment by RichardWallis** [comment]
Kim,

Yes that is correct - the examples are there for all regardless of their
preference to NRDFa, Microdata, or JSON-LD

~Richard.
