### ISSUE TITLE
Branding on http://schema.org home page rotates between schema.org, bib.schema.org, auto.schema.org

### ISSUE THREAD

**Issue by dbs** [schemaorg/schemaorg#714]
Starting at the http://schema.org home page, if I hit "Reload" consecutively in the browser, I'll see the branding header rotate between "schema.org", "auto.schema.org", and "bib.schema.org". The corresonding &lt;title> element changes from "schema.org", to "auto.schema.org", to "bib.schema.org".

Occasionally the main content of the page also changes, but interestingly enough, most of the time it displays the standard schema.org main content instead of the "bib.schema.org" or "auto.schema.org" content.

**Comment by danbri** [comment]
Thanks, investigating. This is probably poor caching where we forgot to include the site name in the lookup key. /cc @RichardWallis

**Comment by danbri** [comment]
I believe I've fixed it in https://github.com/schemaorg/schemaorg/commit/2006d1a000303a783a3a5d0dd9bcc17a0cecacf5 - perhaps gracelessly.

**Comment by danbri** [comment]
No, still problematic...

**Comment by danbri** [comment]
I've pushed various candidate fixes, since this only shows up under load. I believe changing threadsafe=true to threadsafe=false in app.yaml *may* have fixed things. Ugh.

**Comment by danbri** [comment]
see also https://cloud.google.com/appengine/docs/python/requests ... I think our imprudent use of globals (my fault, pre-Richard) bit us here.

**Comment by danbri** [comment]
Nearby: http://stackoverflow.com/questions/963080/how-can-i-create-a-variable-that-is-scoped-to-a-single-request-in-app-engine http://stackoverflow.com/questions/25949059/is-threading-local-a-safe-way-to-store-variables-for-a-single-request-in-googl
