### ISSUE TITLE
Extension pages should give canonical URL explicitly

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#717]
Even if a term is in an extension, it has a canonical URL (currently http not https) of the form:  http://schema.org/{term} 

We should update the extensions UI to make this explicit.

e.g. at top of http://auto.schema.org/BusOrCoach it should say "Canonical URL: http://schema.org/BusOrCoach "

Maybe this would be useful / consistent in the core pages too? /cc @RichardWallis @rvguha

**Comment by RichardWallis** [comment]
Agree - assigning it to myself as I've been in that area a lot lately

**Comment by danbri** [comment]
Thanks!

**Comment by danbri** [comment]
When we discussed this earlier we talked about suppressing the canonical info for 'core' terms since they already are available on their canonical URLs. However we didn't discuss what to do about core terms within an extension.

Currently https://bib.schema.org/Thesis shows canonical info, whereas https://bib.schema.org/Person and https://schema.org/Person does not. I think we should probably put canonical URL info into https://bib.schema.org/Person too. Thoughts?

**Comment by Aaranged** [comment]
Note that at time of writing these http://schema.org canonical pages lack specific <title> metadata and Google Analytics.

e.g. - http://schema.org/Thesis
<title>- schema.org</title>
+ no GA snippet at the bottom

**Comment by danbri** [comment]
Fair cop --- those pages are basically prettied up 404s (or the descendants of 404s). The best wording to use needs a bit of thought.

**Comment by RichardWallis** [comment]
Implemented in 2.1

**Comment by mfhepp** [comment]
As a general direction, I think we should consider hiding the extension mechanism from general users as much as possible, for it causes a lot of confusion.

IMO, it would be sufficient to mark the terms in a different color in the core schema.org namespace (as currently in blue) if they come from an extension, and add a link to a page describing the extension and its resources.

This is just from the top of my head, so I might have missed some dependencies ;-)

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by RichardWallis** [comment]
I agree that we must try to hide the 'mechanism' from users as much as
possible, because to the most point for those trying to mark up their data
it is just confusing noise.

However we need to do it in a way that facilitates the understanding for
those that need/want to know - mostly those communities wishing to build
upon and extend, plus of course those looking after the core.

~Richard
