### ISSUE TITLE
Populate meta description with item description

### ISSUE THREAD

**Issue by Aaranged** [schemaorg/schemaorg#725]
Currently all schema.org pages carry the same `<meta>` description.

Person - schema.org
http://schema.org/Person
`<meta name="description" content="Schema.org is a set of extensible schemas that enables webmasters to embed structured data on their web pages for use by search engines and other applications." />`

Thesis - bib.schema.org
https://bib.schema.org/Thesis
`<meta name="description" content="Schema.org is a set of extensible schemas that enables webmasters to embed structured data on their web pages for use by search engines and other applications." />`

This is not helpful for any data consumer that uses the `<meta>` description to provide users with a description in things like snippets (most notably search engines and social media networks), as the current boilerplate description does not describe any page specifically.

A better - and probably relatively easy - method of populating the meta description would be to use the item description.

Person - schema.org
http://schema.org/Person
`<meta name="description" content="A person (alive, dead, undead, or fictional)." />`

inSupportOf - bib.schema.org
https://bib.schema.org/inSupportOf
`<meta name="description" content="Qualification, candidature, degree, application that Thesis supports." />`

A slightly more sophisticated method of populating the value for `content` would prefix this with basic item information.

Person - schema.org
http://schema.org/Person
`<meta name="description" content="The schema.org type Person. A person (alive, dead, undead, or fictional)." />`

inSupportOf - bib.schema.org
https://bib.schema.org/inSupportOf
`<meta name="description" content="The bib.schema.org property inSupportOf. Qualification, candidature, degree, application that Thesis supports." />`

InStock - schema.org
https://schema.org/InStock
`<meta name="description" content="The schema.org enumeration inStock. Indicates that the item is in stock." />`

**Comment by danbri** [comment]
Yeah, this has been a quiet embarrassment for a while. I think a precursor to fixing it is either introducing substructure to our definitions (since some are large, and have hypertext etc.), or at least having a quick python function that pulls out and cleans up the first sentence or paragraph.  Another usecase for this is http://schema.org/docs/tree.jsonld - a JSON view of the type tree - which currently uses crude truncation to get a brief description of each type term.

**Comment by danbri** [comment]
@RichardWallis maybe this sits alongside all the other little TODOs around in-page RDFa?

**Comment by RichardWallis** [comment]
Long descriptions should probably be truncated to say the first paragraph?

**Comment by Aaranged** [comment]
@RichardWallis First paragraph works.  Conversely one could arbitrarily truncate based on character count (156 characters is what's commonly displayed by Google).  Not too much of an issue one way or another, as search engines will truncate anyway.
