### ISSUE TITLE
Extension Proposal: FoodProduct and Restaurant Menu with FoodProducts.

### ISSUE THREAD

**Issue by mtkocak** [schemaorg/schemaorg#726]
I am implementing datas for a Restaurant website.

Restaurant schema has menu item. However it directs to text or url here https://schema.org/Restaurant
I have to implement a menu with food's name, ingredients and price. I understand that it could extend Product but it also needs ingredients. My proposal is that to extend Product including the ingredients. 

Doing so, a food product could include ingredients and possible allergens too. Also, could have a link to recipe entity.

That's all for now.

**Comment by danbri** [comment]
Thanks! This is already under discussion in #458 - I'll close this issue so we can focus attention in one place. Thanks for raising this :)
