### ISSUE TITLE
Need Specification for Holidays Store is Closed

### ISSUE THREAD

**Issue by jchunick** [schemaorg/schemaorg#728]
There is currently no way I can see for when a store is closed. I work at a hospital which runs a store through our donation foundation. The store is closed on specific days during the year, eg. Christmas Day, New Year's Day, etc.

I don't see any valid way to identify this equally important information because the focus is on specifying the Hours of Operation or the days/times when a store is open. 

I would recommend adding something along the lines of:

`<div vocab="http://schema.org/" typeof="Store">`
`<h1 property="name">`XYZ Store`</h1>`
`<h2>`Opening hours`</h2>`
...
......
`<h2>`Store Closed On:`</h2>`
`<ul>`
   `<li property="openingHoursSpecification"  typeof="OpeningHoursSpecification">`
      `<span property="storeClosed" content="2013-12-25">`Christmas Day (Dec. 25)`</span>`
  `</li>`
  `<li property="openingHoursSpecification"  typeof="OpeningHoursSpecification">`
        `<span property="storeClosed" content="2014-01-01">`New Year's Eve (Jan. 1)`</span>`
   `</li>`
`</ul>`
`</div>`

**Comment by unor** [comment]
Related: #372
