### ISSUE TITLE
Bad linking in extensions UI

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#731]
@RichardWallis - can you take a looksee?

1.) towards end of  of http://auto.schema.org/Vehicle
"More specific Types
BusOrCoach
Car
Motorcycle
MotorizedBicycle" ... those links are bad e.g. http://auto.www.schema.org/Motorcycle should not have the 'www' there.

2.) in the "more..." reveal section at top of pages, we use ?ext=foo linking style instead of subdomain-based links.

**Comment by danbri** [comment]
Re (1.) there may be some instability here along lines we encountered last week. I find the bug unpredictable to reproduce.

But visiting http://www.schema.org/Vehicle (which we ought already to just be redirecting) does cause dodgy hyperlinks to be generated.

**Comment by RichardWallis** [comment]
Redirected with a http 301 all calls (via sdoapp.py) to www subdomain to
parent domain (ie.   www.schema.org/* to schema.org/*)

Commit
https://github.com/schemaorg/schemaorg/commit/e674fed2b9ccbe12f73329e647081074885e0005
 into Master.

**Comment by danbri** [comment]
Thanks. Published as a bugfix rather than versioned release.

Re "Re (1.) there may be some instability here along lines we encountered last week. I find the bug unpredictable to reproduce." ... did you find it 100% reproducible, or was there some indeterminacy?

**Comment by RichardWallis** [comment]
It was unpredictable because of the routes towards it and where you had been before.  Fix was 100%
