### ISSUE TITLE
Article Schema :: Keywords::Text

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#737]
I'm requesting that https://schema.org/Article => Keywords have the possibility to link to some sort of schema that describes this as a set of articles related to a specific taxonomy. Such as WordPress Tag pages.

PrestaShop has a keywords option to collect products into a specific taxonomy as well. Would that be a CollectionPage?

**Comment by vholland** [comment]
+1 to allowing a taxonomy for keywords. I would add we should do it for Thing > category as well.

**Comment by danbri** [comment]
We could do this with https://schema.org/DefinedTerm now.

**Comment by RichardWallis** [comment]
Yes, adding [DefinedTerm](https://schema.org/DefinedTerm) to the range of keywords could be a good first step in this area.

**Comment by danbri** [comment]
It's a little awkward - whether or not to explicitly allow :URL. I think we should be more consistent on this, but for now I'm putting an explicit :URL here too, since it is less likely that the defined terms will be described inline as an entity in their own right.
