### ISSUE TITLE
Add Property "volume"

### ISSUE THREAD

**Issue by radusi** [schemaorg/schemaorg#738]
"volume" property at least for products is as popular as weight, width, length, height. In EU in grocery eCommerce, is mandatory price specification / sales unit ( bottle ) and MU ( liter )

**Comment by mfhepp** [comment]
will take care.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by vholland** [comment]
This is a duplicate of issue #544. Can we continue the discussion there?
