### ISSUE TITLE
Aggregate rating not showing in Google SERP

### ISSUE THREAD

**Issue by guidoampo** [schemaorg/schemaorg#741]
HI,

Have an issue with aggregate rating, those are not showing up in Google Search Result Page but according to Schema Test implementation is correct, please take a look

https://mubi.com/films/yellow-hair

https://developers.google.com/structured-data/testing-tool/?url=https://mubi.com/films/yellow-hair

Do you have an idea how can I fix this?

Thanks

**Comment by vholland** [comment]
Unfortunately, we cannot support specific products. You may want to consult https://developers.google.com/structured-data/rich-snippets/reviews.
