### ISSUE TITLE
Represent release state of an extension

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#742]
Currently (v2.1) all extensions are described as (This is an initial exploratory release.)

Need a way to define the state of an extension in its rdfa file - schema:softwareVersion already being added to these files - and then represented on screen.

States include : released, exploratory release, released with proposed new/changed terms, etc.  - may need some thought on how to track new terms in an already released extension.

**Comment by danbri** [comment]
Yeah - we have some related issues around per-term metadata too - https://github.com/schemaorg/schemaorg/issues/465 still needs wrapping up.
