### ISSUE TITLE
What is the difference between "articleBody" and "articleSection"

### ISSUE THREAD

**Issue by shreen2008** [schemaorg/schemaorg#744]
I'm trying to implement the "Article" Schema.
But can you elaborate more "articleSection". For a blog article, what should be its typical contents.

**Comment by RichardWallis** [comment]
From the description: Articles may belong to one or more 'sections' in a magazine or newspaper, such as Sports,Lifestyle, etc

I would suggest that, unless your blog has specific sections within its structure, there would be no need for articleSection in your markup. 

For a newspaper article about football, you might expect something like "Sports Supplement" to be the content of this attribute. 



~Richard
