### ISSUE TITLE
need to  be added new properties to item type ----->person

### ISSUE THREAD

**Issue by profumairali** [schemaorg/schemaorg#745]
"item type------->person " must have the item property "  dress "
and " profession",,,
as the fashion dressing and profession are the most visiting entities in the informational web and the social web now a days.

**Comment by mfhepp** [comment]
I do not think that these two properties should be added to Person. "dress" is not of generic interest, IMO, and "profession" is well covered by http://schema.org/jobTitle.

**Comment by akuckartz** [comment]
See also #281 regarding `jobTitle`

**Comment by unor** [comment]
Re. `profession`, see also:

* https://github.com/schemaorg/schemaorg/issues/789
* https://github.com/schemaorg/schemaorg/issues/807
