### ISSUE TITLE
Clarify licensing of the documentation

### ISSUE THREAD

**Issue by memespring** [schemaorg/schemaorg#747]
It seems clear that the each schema is licensed under  Creative Commons Attribution-ShareAlike License (version 3.0). It is not clear what license the supporting documentation is provided under - is it also CC or is it covered by the Apache License that the software is provided under?

Would it be possible to add a statement to the site with the status of the supporting documentation?

**Comment by danbri** [comment]
We'll do that. Any prefs on license?

**Comment by memespring** [comment]
Thanks. I guess same as the schema are licensed would be simplest.

(for context I'm asking as I'm working my way through a set of questions on 'openness' to see if jobPosting can be adopted as a government standard: https://standards.data.gov.uk/core-assessment-questions)

**Comment by danbri** [comment]
@memespring - does http://sdo-phobos.appspot.com/docs/faq.html#18 work for you?

**Comment by memespring** [comment]
Perfect.

**Comment by danbri** [comment]
Published at http://schema.org/docs/faq.html#18 last year; closing this issue.
