### ISSUE TITLE
Missing inverse properties

### ISSUE THREAD

**Issue by 0x8890** [schemaorg/schemaorg#748]
A lot of properties are missing inverses. For example, starting from a `Movie` I may see who is an `actor` in this movie, but I cannot start from a `Person` and find which movies this person has acted in, there is no `actedIn` property. 

Should these inverse properties be represented as part of schema.org or as extensions?

**Comment by dbs** [comment]
There have been a number of discussions in the past about inverse properties on the various schema.org mailing lists.

Generally, they are to be avoided, and (per https://schema.org/inverseOf) mechanisms like RDFa's `@rev`, JSON-LD's `@reverse` and microdata's (proposed) `@itemprop-reverse` should be used instead.

See also http://www.w3.org/wiki/WebSchemas/InverseProperties

**Comment by 0x8890** [comment]
Ok, thanks!
