### ISSUE TITLE
Erroneous BreadcrumbList Example?

### ISSUE THREAD

**Issue by HorvathAdam** [schemaorg/schemaorg#750]
The Structured Data Testing Tool of Google (https://developers.google.com/structured-data/testing-tool/) finds three errors in the Example of http://schema.org/BreadcrumbList.

The Example:
<ol vocab="http://schema.org/" typeof="BreadcrumbList">
  <li property="itemListElement" typeof="ListItem">
    <a property="item" typeof="WebPage" href="https://example.com/dresses">
     <span property="name">Dresses</span></a>
     <meta property="position" content="1">
  </li>
› <li property="itemListElement" typeof="ListItem">
    <a property="item" typeof="WebPage" href="https://example.com/dresses/real">
    <span property="name">Real Dresses</span></a>
    <meta property="position" content="2">
  </li>
</ol>

The test result (in Hungarian) (so you may have to repeat the test):
![image](https://cloud.githubusercontent.com/assets/10087815/9521755/f4c28866-4cd0-11e5-98b7-a621d0aa1067.png)

**Comment by yhealjsp** [comment]
I just submitted issues is prompted this error, it should be compatible with the new version of the problem, wait for the official answer it together. #752

**Comment by RichardWallis** [comment]
Message from issue #752:

Identified and removed erroneous character in examples.

This did not fix the problem in the Structured Data Testing Tool where the
main problem appears to be.

Especially as the Yandex tool is happy with it:
https://webmaster.yandex.com/microtest.xml

We can't support Google products here. You might try
https://productforums.google.com/forum/#!categories/webmasters/structured-data


~Richard
