### ISSUE TITLE
ItemList mainEntityOfPage in version 2.1

### ISSUE THREAD

**Issue by yhealjsp** [schemaorg/schemaorg#752]
The property mainEntityOfPage in ItemList prompt must be filled, but after I filled that's still prompt an error. Please look at the following screenshot.

![1a8c3d50-843b-4d57-90b1-675c610d9a53](https://cloud.githubusercontent.com/assets/12403469/9524800/6c870b50-4d13-11e5-847a-4b919474c6a3.png)

**Comment by RichardWallis** [comment]
Identified and removed erroneous character in examples.
This did not fix the problem in the Structured Data Testing Tool where the main problem appears to be.

Especially as the Yandex tool is happy with it: https://webmaster.yandex.com/microtest.xml

We can't support Google products here. You might try https://productforums.google.com/forum/#!categories/webmasters/structured-data
