### ISSUE TITLE
Investigate gzip behaviour re schema_org_rdfa.html

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#759]
Via @mfhepp who writes "IMO, this is a bug. It should serve gzip only on request."

This is via [all.yaml](https://github.com/schemaorg/schemaorg/blob/sdo-phobos/app.yaml#L18)

````  - url: /docs/schema_org_rdfa.html
  static_files: data/schema.rdfa
  upload: data/schema.rdfa
  application_readable: True
  mime_type: text/html````

FYI: It seems that AppEngine returns a gzipped version of http://schema.org/docs/schema_org_rdfa.html as a default, i.e. even if you do not request a compressed version.


> $ curl -I http://schema.org/docs/schema_org_rdfa.html
> HTTP/1.1 200 OK
> Date: Mon, 07 Sep 2015 14:45:03 GMT
> Expires: Mon, 07 Sep 2015 14:55:03 GMT
> ETag: "ZBmLow"
> Content-Type: text/html
> Content-Encoding: gzip
> Server: Google Frontend
> Content-Length: 105525
> Age: 36
> Cache-Control: public, max-age=600
> Connection: keep-alive

**Comment by danbri** [comment]
https://cloud.google.com/appengine/kb/general?csw=1#compression 

"Google App Engine does its best to serve gzipped content to browsers that support it. Taking advantage of this scheme is automatic and requires no modifications to applications.

We use a combination of request headers (Accept-Encoding, User-Agent) and response headers (Content-Type) to determine whether or not the end-user can take advantage of gzipped content. This approach avoids some well-known bugs with gzipped content in popular browsers. To force gzipped content to be served, clients may supply 'gzip' as the value of both the Accept-Encoding and User-Agent request headers. Content will never be gzipped if no Accept-Encoding header is present."

**Comment by danbri** [comment]
curl -vvv -I http://schema.org/docs/schema_org_rdfa.html
*   Trying 31.55.163.251...
* Connected to schema.org (31.55.163.251) port 80 (#0)
> HEAD /docs/schema_org_rdfa.html HTTP/1.1
> Host: schema.org
> User-Agent: curl/7.43.0
> Accept: */*

**Comment by danbri** [comment]
Perhaps "Accept */*" is read by appengine as accepting gzip?

**Comment by mfhepp** [comment]
I do not think it is a curl-specific problem, because the problem occurs also in rdflib and urllib2 in Python.

Try:

from rdflib import Graph
schema = Graph()
schema.parse("http://schema.org/docs/schema_org_rdfa.html", format="rdfa")
print len(schema)

It will return zero.

Also,

import urllib2
schema_html = urllib2.urlopen("http://schema.org/docs/schema_org_rdfa.html").read() 
print schema_html[:200]

returns garbage.

**Comment by mfhepp** [comment]
I order to parse this properly, I have to use the following work-around:

  request = urllib2.Request("http://schema.org/docs/schema_org_rdfa.html")
  request.add_header('Accept-encoding', 'gzip')
  response = urllib2.urlopen(request)
  if response.info().get('Content-Encoding') == 'gzip':
    buf = StringIO(response.read())
    f = gzip.GzipFile(fileobj=buf)
    schema_html = f.read()
  else:
    schema_html = StringIO( response.read())

which is ugly and IMO a clear sign of a bug in the schema.org protocol layer.

**Comment by danbri** [comment]
This is an appengine issues as far as I can see - I have found no public documentation that gives an easy fix. I can ask around backstage...

**Comment by danbri** [comment]
@RichardWallis - could you have a look at this? Not burning urgent but since you looked at the HTTP header aspects recently...

**Comment by RichardWallis** [comment]
Problem appears to be corrected and working as documented:
```
$ curl  -I http://schema.org/docs/schema_org_rdfa.html
HTTP/1.1 200 OK
Date: Wed, 15 Jun 2016 14:12:30 GMT
Expires: Wed, 15 Jun 2016 14:22:30 GMT
Cache-Control: public, max-age=600
ETag: "NZisIA"
Content-Type: text/html
Server: Google Frontend
Content-Length: 849056
```

From App Engine documentation:
>  To force gzipped content to be served, clients may supply 'gzip' as the value of both the Accept-Encoding and User-Agent request headers. Content will never be gzipped if no Accept-Encoding header is present.

```
$ curl -I  -H "Accept-Encoding: gzip" -H "User-Agent: gzip" http://schema.org/docs/schema_org_rdfa.html
HTTP/1.1 200 OK
Date: Wed, 15 Jun 2016 14:15:15 GMT
Expires: Wed, 15 Jun 2016 14:25:15 GMT
Cache-Control: public, max-age=600
ETag: "NZisIA"
Content-Type: text/html
Content-Encoding: gzip
Server: Google Frontend
Content-Length: 89067
```

**Comment by danbri** [comment]
Thanks for the investigation / fix. But can we leave this open for someone else to verify it? e.g. @mfhepp

**Comment by danbri** [comment]
I had a look at @mfhepp 's python, couldn't figure out if it was telling me everything is fixed or not but this is a tweaked version than ran for me...

    #!/usr/bin/env python

    import urllib2
    from StringIO import StringIO

    request = urllib2.Request("http://webschemas.org/docs/schema_org_rdfa.html")

    request.add_header('Accept-encoding', 'gzip')

    response = urllib2.urlopen(request)

    if response.info().get('Content-Encoding') == 'gzip':
        buf = StringIO(response.read())
        f = gzip.GzipFile(fileobj=buf)
        schema_html = f.read()
        print schema_html.getvalue()
    else:
        schema_html = StringIO( response.read())
        print schema_html.getvalue()

**Comment by danbri** [comment]
Looking at curl -I http://schema.org/docs/schema_org_rdfa.html ... I'm inclined to agree that this is fixed now.

**Comment by danbri** [comment]
I asked in https://github.com/api-platform/schema-generator/issues/53 (linked above) and they report also that it seems OK now. Closing.
