### ISSUE TITLE
Add countryOfOrigin to TVSeries and Movie[done] + Product [todo]

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#767]
Sites like Wikipedia and IMDB often provide the country of origin for TV series and movies. It would be nice if they had a way to do that in markup as well. Something like:

```
{
  "@context": "http://schema.org/",
  "@type": "Movie",
  "name": "Ghostbusters",
  "countryOfOrigin": {
    "@type": "Country",
    "name": "USA"
  }
}

```

In some cases, there will be more than one country, which is fine. Authors can provide more than one value.

**Comment by vholland** [comment]
Created pull request #767. The definition is based on [FIAF cataloging rules](http://www.fiafnet.org/pdf/uk/FIAF_Cat_Rules_-_1.pdf).

**Comment by shankarnat** [comment]
+1 to this. This would be very useful for lot of foreign movies too.

**Comment by mfhepp** [comment]
I think countryOfOrigin would also be very useful for Product.

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all.

Leaving open, retitled slightly, as @mfhepp suggests this would be useful on Product too.

**Comment by vholland** [comment]
Let's close this  and if it is needed for Product we can open with a more targeted issue.
