### ISSUE TITLE
Sorting of the multi-inheritance breadcrumbs

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#769]
(For reference, it’s about https://github.com/schemaorg/schemaorg/pull/567)

I think it would make sense to sort the breadcrumbs alphabetically.

http://schema.org/Obstetric currently shows

> Thing > Intangible > Enumeration > Specialty > MedicalSpecialty :: Obstetric
> Thing > Intangible > Enumeration > MedicalSpecialty :: Obstetric
> Thing > MedicalEntity > MedicalIntangible > MedicalEnumeration > MedicalSpecialty :: Obstetric
> Thing > Intangible > Enumeration > MedicalEnumeration > MedicalSpecialty :: Obstetric 

instead of 

> Thing > Intangible > Enumeration > MedicalEnumeration > MedicalSpecialty :: Obstetric
> Thing > Intangible > Enumeration > MedicalSpecialty :: Obstetric
> Thing > Intangible > Enumeration > Specialty > MedicalSpecialty :: Obstetric
> Thing > MedicalEntity > MedicalIntangible > MedicalEnumeration > MedicalSpecialty :: Obstetric

**Comment by danbri** [comment]
@RichardWallis?

**Comment by danbri** [comment]
See https://github.com/schemaorg/schemaorg/blob/sdo-phobos/sdoapp.py#L348

**Comment by RichardWallis** [comment]
In Phobos
