### ISSUE TITLE
Documentation on extension submission and review process seriously deficient

### ISSUE THREAD

**Issue by lehors** [schemaorg/schemaorg#771]
The info currently available at http://schema.org/docs/extension.html fails to answer some basic yet crucial questions as to what it takes to get a "hosted extension" approved, including:
- How does one go at submitting an extension for consideration?
- What is the review process?
- What are the criteria for an extension to be approved as a "hosted extension"?
- Who "approves" the extension?

**Comment by danbri** [comment]
Fair comment. I hope to have progress on this in reasonably near (pre W3C TPAC) future.
