### ISSUE TITLE
Steering group description and composition don't match

### ISSUE THREAD

**Issue by lehors** [schemaorg/schemaorg#772]
The about page at http://schema.org/docs/about.html states that the steering group "includes representatives of the sponsor companies, a representative of the W3C and a small number of individuals who have contributed substantially to Schema.org" which would seem to amount to quite a few people.

Yet, "The People" section only lists 5 steering group members, 3 of which are from Google, nobody from the other sponsor companies and W3C, as being part of the steering group.

**Comment by danbri** [comment]
The usual participants from the search engine companies are Peter Mika from Yahoo; Alex, Yuliya and Charles from Yandex; Shankar, Tom and Steve from Microsoft, with Vicki and myself from Google. Guha serves in a chairing role rather than as a Google representative. In general we are not very bureaucratic about such things, and most of the work is within the Github-based community group. We could clarify that page, though I'm inclined to point off into Github for day-to-day details.

**Comment by lehors** [comment]
If the information is somewhere else and you want to simply put a pointer to it that's fine but as it stands there is no pointer to anywhere else and the info that's there is badly broken so something needs to change. :-)
You refer to a github-based community group. Where is it?

**Comment by lehors** [comment]
By the way, this isn't about being bureaucratic it is about being open and transparent. This does require some documentation effort. Right now, I find it rather difficult to know what's going on, and who's doing what.

**Comment by rvguha** [comment]
Arnaud,

 Thank you for the feedback. You are absolutely correct, we need to be
clear about all this in the documentation. One of us will get to it soon.

thanks,

guha

**Comment by danbri** [comment]
Yes - what Guha said - I meant that the steering group is pretty light touch.

Just to spell things out a bit here in advance of improving the about.html page

* W3C Schema.org Community Group is the main forum for the project - https://www.w3.org/community/schemaorg/
* It is Github-based in the sense that this repository - https://github.com/schemaorg/schemaorg/ ... 
 * is where all the materials are - examples, schemas, documentation, software
 * is where we develop more complex proposals as branches
 * provides the infrastructure for forking, branching etc for ideas to be made concrete
 * holds the issue tracker where changes are discussed 
  * issues #1 (planning), #2 (vocab changes) and #3 (tooling/infrastructure) provide some views into to the various fine-grained issues, as do the labels we attach.
* Other W3C Community Groups exist that are focussed partially or entirely on schema.org improvements, e.g. [health and medicine](https://www.w3.org/community/schemed/),  [sports](https://www.w3.org/community/sport-schema/),  [archives](https://www.w3.org/community/architypes/),
[libraries and bibliography](https://www.w3.org/community/schemabibex/), [autos](https://www.w3.org/community/gao/)... ...these groups have their own ways of working, and coordinate via the main Schema.org CG and this Github repository.
* The Steering Group has a mailing list - https://groups.google.com/forum/#!forum/schema-org-sg - mostly used for scheduling periodic phone/skype/etc calls, whose notes are posted here and linked from #1

**Comment by rvguha** [comment]
Let us create a page on the website and put this there. We can't expect someone who is looking for answers to these questions to search github.

**Comment by rvguha** [comment]
Arnaud,

   Can you help with putting this down in a form that folks like you will
understand and perhaps even be satisfied with?

guha

**Comment by akuckartz** [comment]
Copying https://github.com/schemaorg/schemaorg/issues/772#issuecomment-140408413 to a Wiki page might be a simple solution.

**Comment by danbri** [comment]
Agreed - it should go on the site, just collecting the raw materials here.

**Comment by shankarnat** [comment]
@danbri  I was unable to find the about.html updated in the http://sdo-phobos.appspot.com/docs/about.html and it is same as http://schema.org/docs/about.html. Would we do this about update in another release ?

**Comment by danbri** [comment]
@shankarnat - steve macbeth took a look.

This is live now, http://schema.org/docs/about.html (new section at end of page)

**Comment by danbri** [comment]
@lehors does this help address your concern?

**Comment by lehors** [comment]
Hi Dan,
this is a nice improvement indeed.
One small nit: the upper list of contributors has some references to the steering group but these are not consistent with the new list at the bottom. It's probably better to avoid the repetition and be done with the risk of inconsistencies.
Of course when it comes to openness this begs the question of how the current members were selected and what it takes for someone else to be so chosen but I guess this is a separate issue. :-)
Thanks.
