### ISSUE TITLE
Add a simpler mechanism to specify the platform for EntryPoint targets

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#773]
When authors use http://schema.org/Action, they have two ways to specify the platform where the Action should be executed: http://schema.org/actionApplication or http://schema.org/target with the special prefix "android-app" or "ios-app" as appropriate. (See the examples in http://schema.org/EntryPoint.)

These mechanisms are insufficient as:
- They don't support mobile web apps very well. The author should not have to specify the specific browser app.
- There is no way to distinguish mobile web URLs from URLs intended for a desktop experience.
- Authors often want the abstract notion of a particular OS, not a specific version (e.g. iOS, not iOS 9).
- With [Universal Links in iOS 9](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html), the Action will have a single URL regardless of platform.

To make it easier for developers to specify which platforms support their Action URLs, I propose the following:
- A new property on http://schema.org/EntryPoint called **targetPlatform** which takes one of the following enumeration values:
  - **IOSPlatform**
  - **AndroidPlatform**
  - **WindowsMobilePlatform**
  - **MobileWebPlatform**
  - **DesktopWebPlatform**

Authors who prefer to specify a specific application or OS version can continue to use actionApplication as they do today.

/cc @shankarnat Is there a better term for Windows Mobile?

**Comment by vholland** [comment]
Created pull request #778. Some things to note, which I would like feedback on:

1. http://schema.org/targetPlatform already exists for http://schema.org/APIReference. It does not seem entirely compatible with this proposal, so I added **actionPlatform** instead.

2. Should this be unified with http://schema.org/gamePlatform? If so, I would name the type **ComputingPlatformType** rather than **ActionPlatformType**.

/cc @chaals @ajax-als @tilid @pmika @mfhepp @shankarnat @rvguha @danbri

**Comment by danbri** [comment]
Note: if we go for this, http://schema.org/docs/actions.html will likely need an update too

**Comment by vholland** [comment]
I'd like to squeeze this into sdo-phobos if possible. Comments?

/cc @chaals @ajax-als @tilid @pmika @mfhepp @shankarnat @scor @rvguha @danbri

**Comment by danbri** [comment]
where are we with this folks? PTAL!

**Comment by tilid** [comment]
Hi
Sorry for the late answer
I think it is a good idea to unify this with http://schema.org/gamePlatform. 
Also I have a question what if target platform is not in your list (new or not very popular platform)?

**Comment by danbri** [comment]
I like idea of converging these. I would also be happy moving forward with Text/Thing/URL as the only structure for values initially. @vholland any thoughts?

**Comment by vholland** [comment]
I'm happy to move forward with Text/Thing/URL for now and unify these with a common enumeration next release. It would allow others to give input on the enumerated values required for both domains.

**Comment by danbri** [comment]
Shipped as part as http://schema.org/docs/releases.html#v2.2 - thanks everyone! Shall we leave the issue open for discussion of convergence with gamePlatform?

**Comment by vholland** [comment]
I'll close this and if we need to discuss gamePlatform, we can open a new issue with a more targeted use case.
