### ISSUE TITLE
Agenda/Notes for SG meeting 2015-09-xx (15th?)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#779]
Previous meeting: #775

# Agenda 

''datetime'': PROPOSED TEMPORARY NEW TIMESLOT. Wednesday 16-09-2015 10am PST (i.e. old time, but on Wednesday as @danbri is unavailable this Thurs.)

* review proposed changes for next release ("sdo-phobos")
 * test build + review list: http://sdo-phobos.appspot.com/docs/releases.html#sdo-phobos
 * closures for issues #687 (Barcode), #688 (DataFeed), #768 (broadcastOfEvent), #767 (countryOfOrigin) are implemented and queued for review
 * @vholland has drafted a proposal for #773 ("Add a simpler mechanism to specify the platform for EntryPoint targets") 
* review #1 - high level planning for remainder of 2015
* AOB

**Comment by pmika** [comment]
Sadly, I'll be in the air on my way to Vienna for semantics.cc

**Comment by rvguha** [comment]
Unfortunately, I won't be able to join.

guha

**Comment by danbri** [comment]
Ok, regrets from Charles, Stephane, Alex, Guha, Peter -> this isn't going to happen on Weds 2015-09-15. Topics queued for next week, PTAL.
