### ISSUE TITLE
broaden https://schema.org/fileFormat - useful for many CreativeWorks

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#790]
Currently https://schema.org/fileFormat "MIME format of the binary (e.g. application/zip)." is a text field associated only with the SoftwareApplication type.

I propose we broaden it to apply (potentially) to any CreativeWork. This would allow us for example to say that some particular Dataset is  in application/ld+json format, or that an ImageObject was image/png.

Although the name of the property is a little inelegant (it should probably have been called "media type" initially), it does not seem a huge win to change that now. I suggest instead we write something like:

* CreativeWork: fileformat(Text) - "Media type (MIME format) of the content e.g. application/zip of a SoftwareApplication binary. In cases where a CreativeWork has several media type representations, 'encoding' can be used to indicate each MediaObject alongside particular fileFormat information." 

(and link to http://www.iana.org/assignments/media-types/media-types.xhtml - in the schema we should mark this as equivalent to dc:format)

/cc @rvguha @shankarnat @vholland @chaals @mfhepp @ajax-als @pmika @tilid  @scor @mfhepp 

I'd like to squeeze this into the upcoming http://sdo-phobos.appspot.com/docs/releases.html#sdo-phobos release (improves DataFeed), if I can get some +1s here...

**Comment by vholland** [comment]
+1

**Comment by pmika** [comment]
+1

**Comment by thiagomgd** [comment]
+1

**Comment by ajax-als** [comment]
+1

**Comment by sballesteros** [comment]
+1 we are currently misusing `encodingFormat` for that.

**Comment by shankarnat** [comment]
+1

**Comment by mfhepp** [comment]
+1

**Comment by danbri** [comment]
Sounds like rough consensus (pinging @scor for steering group unanimity). I'll code it up for the next release under sdo-phobos.

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
