### ISSUE TITLE
proposal: add a storeCode property to LocalBusiness 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#791]
storeCode (Text): an identifying code representing this place of business, typically assigned by the parentOrganization for use in structured URLs.

Motivation: many sites publish information about stores and other local businesses, where the parent organization for multiple branches assigns numeric or alphanumeric IDs to each branch.  Often these are used in URL structures and as record IDs - it would be good to expose such information within schema.org markup.

example URL into Starbucks UK store finder: http://www.starbucks.co.uk/store-locator/search/location/w9%201qf/detail/3047 - here "3047" might be there storeCode of a particular branch of starbucks.

**Comment by pmika** [comment]
+1

**Comment by danbri** [comment]
From @mfhepp via Skype IM, "storecode is fine for me, no objections."

**Comment by mfhepp** [comment]
+1

**Comment by chaals** [comment]
+1… feels about right.

**Comment by magicomartinez** [comment]
+1

**Comment by danbri** [comment]
Thanks all. Here is a slight refinement, based on feedback that we could cover more usecases with a terminology tweak: let's say "branchCode" to cover multi-site organizations that are not stores (e.g. libraries, transport, public sector etc etc.).  The meaning remains essentially the same.

So something like ""A short textual code (also called "store code") that uniquely identifies a place of business. The code is typically assigned by the parentOrganization and used in structured URLs."" would address this.

**Comment by shankarnat** [comment]
+1

**Comment by danbri** [comment]
Thanks all. This is queued up and ready to go. For completeness a +1 from @scor would be great, but looks like this should go ahead...

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
