### ISSUE TITLE
Delete docs/documentation.html  ?

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#792]
As far as I can see, the file docs/documentation.html is redundant and should be removed (unless I overlooked a dependency). The link from the "Documentation" tab goes to docs/documents.html.

This might be related to issue #460.

**Comment by danbri** [comment]
Yeah, I left it in case of dangling references while waiting for "redirect foo to bar" functionality. For a while it was an out of sync version, I manually brought it up to date but you're absolutely right - it needs to go away.

After checking in both the github repo for dangling references, and with Google, I am pretty certain this file will never be missed.

**Comment by danbri** [comment]
File, what file? :)

     curl -v http://sdo-phobos.appspot.com/docs/documentation.html 2>&1 | grep "HTTP/1.1"
    > GET /docs/documentation.html HTTP/1.1
    < HTTP/1.1 404 Not Found
