### ISSUE TITLE
Add an offeredBy property to Offer

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#796]
Follow on from #764 

Inverse of makesOffer

**Comment by danbri** [comment]
Merged - PTAL: http://sdo-phobos.appspot.com/docs/releases.html

**Comment by danbri** [comment]
http://sdo-phobos.appspot.com/offeredBy

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
