### ISSUE TITLE
VOCAB: schema.org/box has the description for "polygon"

### ISSUE THREAD

**Issue by dbs** [schemaorg/schemaorg#8]
This appears to have been a problem since at least the 1.0b release (the earliest to which I have access).

**Comment by danbri** [comment]
For this looming release, I would like to make at least partial progress here:

* currently: schema.org/box "A polygon is the area enclosed by a point-to-point path for which the starting and ending points are the same. A polygon is expressed as a series of four or more space delimited points where the first and final points are identical."
* proposed: "A bounding box defining a rectangular GeoShape. Can be used to define the extent of a map or an area of interest."

Ideal of course would be to have the final sentence giving implementable detail. Can we get that too? (@ManoMarks et al?)

By analogy with polygon, but noting that 2 would be enough, ... "A box is expressed as a series of {x} space delimited points where {y}.". 

Any thoughts on x and y? e.g. "2 points", "the points define diagonally opposite corners of a square bounding box."

Any suggestions for x and y?

**Comment by danbri** [comment]
Is this enough to be an improvement?: "A bounding box defining a rectangular GeoShape. Can be used to define the extent of a map or an area of interest. A box is expressed as a series of 2 space delimited points corresponding to opposite corners of the box."

**Comment by ManoMarks** [comment]
The most common approach is [minX,minY,maxX,MaxY) where X is longitude, Y is latitude (depending on coordinate reference system). You can see this typified here:
[GeoJSON](http://geojson.org/geojson-spec.html#bounding-boxes)
[KML](https://developers.google.com/kml/documentation/kmlreference#viewformat)
[OSM](http://wiki.openstreetmap.org/wiki/Bounding_Box)

**Comment by danbri** [comment]
Thanks @ManoMarks, I'll try to merge that in. I believe the heritage of what we have here was (possibly GeoRSS-inspired) via IPTC rNews 1.0 (http://www.iptc.org/std/rNews/1.0/specification/rNews_1.0-diagram.pdf) which was added into schema.org very early. http://dev.iptc.org/rNews-1-The-GeoCoordinates-Class ...

Sorry I should have looked there before! For box they do have "A box is the area enclosed by the rectangle formed by two points. The first point is the lower corner, the second point is the upper corner. A box is expressed as two points separated by a space character.". And the other properties do closely match schema.org. Maybe I should ask them about the heritage and use so far of this?

**Comment by danbri** [comment]
Ok I've marked this one closed for now, although I'm sure other specific Geo topics will re-emerge.  It seems that schema.org via rNews is closer to GeoRSS than to GeoJSON.

I also took liberty of adding a little more explanatory text to http://sdo-gozer.appspot.com/GeoShape including some words (inspired by the georss site) retrospectively documenting our ambiguity w.r.t. whether point pairs are comma or whitespace based, i.e. we say we don't care.

**Comment by RLRichardson** [comment]
Also check out what3words.com where the entire globe has been mapped into 3X3 meter squares and assigned a name consisting of 3 randomly assigned words

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Apr 29, 2015 at 6:10 PM -0700, "Mano Marks" <notifications@github.com<mailto:notifications@github.com>> wrote:


The most common approach is [minX,minY,maxX,MaxY) where X is longitude, Y is latitude (depending on coordinate reference system). You can see this typified here:
GeoJSON<http://geojson.org/geojson-spec.html#bounding-boxes>
KML<https://developers.google.com/kml/documentation/kmlreference#viewformat>
OSM<http://wiki.openstreetmap.org/wiki/Bounding_Box>

�
