### ISSUE TITLE
GeoCoordinates improvements: allow address, mention wgs84

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#802]
This is a sub-issue of the longstanding https://github.com/schemaorg/schemaorg/issues/113 Geo* cleanup. WGS84 is implied (and used in the specs ours was based on) but wasn't mentioned. Also GeoCoordinates is hard to re-use / extend in extensions since address was a property of a Place that had the GeoCoordinates as value of a 'geo' property. We should allow the simple option of a GeoCoordinates directly carrying 'address' property.

**Comment by pmika** [comment]
+1

**Comment by mfhepp** [comment]
+1

**Comment by danbri** [comment]
I forgot to include GeoShape here too - doing both for consistency. See also https://github.com/schemaorg/schemaorg/issues/808 which supports address having simple textual fields for when data is unstructured.

**Comment by shankarnat** [comment]
+1

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
