### ISSUE TITLE
ContactPoint-specific areaServed property should be supersededBy serviceArea

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#803]
These mean the same thing. Mark areaServed as supersededBy and add ContactPoint to serviceArea definition.

**Comment by danbri** [comment]
This was a spinoff subissue from https://github.com/schemaorg/schemaorg/issues/411

**Comment by pmika** [comment]
+1

**Comment by mfhepp** [comment]
+1

**Comment by danbri** [comment]
@rvguha just made the sensible point that it would be better (c.f. #803) to have a property name that can't be easily mistaken for a type name. Therefore I propose we flip the supersededBy relationship around, and adopt areaServed as a (slightly) less-nouny preferred name. Unless anyone disagrees I'll update the draft site accordingly, with areaServed taking on the work now done by serviceArea. Currently we have both of these properties in parallel unrelated use, so one needs to be picked - I just think now I picked the wrong one.

**Comment by akuckartz** [comment]
:+1: for `areaServed`

**Comment by danbri** [comment]
Closing here, consolidating into #411 - I have reworked this to cover also eligibleRegion and availableAtOrFrom as sub-properties of areaServed.

**Comment by danbri** [comment]
see #411 for a few related updates, http://sdo-phobos.appspot.com/docs/releases.html#service-usability-fixes
