### ISSUE TITLE
socialMediaPosting: no headline for tweets

### ISSUE THREAD

**Issue by beck410** [schemaorg/schemaorg#804]
I'm currently adding rich snippets to twitter posts that are brought down by the twitter api - it is asking for a headline property but tweets do not have a proper headline - i can solve these errors by making the twitter username the headline but this isn't semantically correct

**Comment by viztastic** [comment]
+1

I am also curious as to why schema.org doesn't support basic properties such as "username" "password" "token" etc..

**Comment by vholland** [comment]
I assume the original issue is related to a specific testing tool. Consumers of schema.org often "require" certain properties for their features, but the underlying schema.org schema has no such requirements. Questions like these are better directed to the specific company or product.

I am not sure I understand the comment about "username" and "password". Can you open a new issue explaining the use case?
