### ISSUE TITLE
MedicalOrganization has supertype LocalBusiness rather than Organization

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#806]
MedicalOrganization is counter-intuitive. You would expect it be Organizations that are medical/health oriented, but it is more specific, since LocalBusiness inherits from Place too. 

This may be the case with other LocalBusiness types which put less value on their specific physical offices but worth noting and considering for the medical extension cleanup.

/cc @vholland @rvguha @RichardWallis

**Comment by jvandriel** [comment]
I'm not sure I understand your remark, do you see any problem with ```schema.org/MedicalOrganization``` being a subtype of ```schema.org/LocalBusiness```?

**Comment by danbri** [comment]
Only that it uses up the most obvious name for a broader more inclusive type for MedicalOrganizations that aren't also places. Any LocalBusiness is a Place too.

**Comment by jvandriel** [comment]
Just throwing an idea out there:

How about ```schema.org/MedicalOrganization``` becomes a subtype of ```schema.org/Organization``` for those medical/health organizations that aren't necessarely a ```schema.org/LocalBusiness```:

Organization 
    > MedicalOrganization

 And we introduce a new type ```schema.org/MedicalBusiness``` as a subtype of ```schema.org/Localbusiness which gets the subtypes ```schema.org/MedicalOrganization``` currently has?

Organization
    > LocalBusiness
        > MedicalBusiness
            > Dentist
            > DiagnosticLab
            > Hospital
            > MedicalClinic
            > Optician
            > Pharmacy
            > Physician
            > VeterinaryCare

**Comment by LeezaRodriguez** [comment]
The main problem I see with the existing schema.org/MedicalOrganization children is with 'Physician'. A physician may not necessarily have a physical office location.  I'm not sure if this has already been discussed and if this is why a change is suggested. Examples of this are: . 
1) Emergency Room physician does not usually have an office, and he may rotate through various hospitals
2) Anesthesiologist are often subcontractors to Surgery Centers and Hospitals. In the hospital setting, they may or may not be employees of the hospital. Many do not have a physical office as they do not see patients in an office setting. Instead, they simply administer anesthesia to a patient in the Operating Room. 
3) A locum-tenens physician who sub contracts part time at various organizations has no physical office

My apologies if this has already been discussed.

**Comment by twamarc** [comment]
@LeezaRodriguez 
right to raise this, and it has not been discussed. I think we need to differentiate here professions and localBusiness. I would support the suggestion of @jvandriel above.

**Comment by danbri** [comment]
There are other related cases e.g. 

* http://schema.org/Electrician as a LocalBusiness
* a http://schema.org/MusicGroup for a solo artist
 * e.g. view-source:https://musicbrainz.org/artist/cf119120-7df5-47d7-9dec-49f8837a4e40 types a single entity as Person, MusicGroup

**Comment by mfhepp** [comment]
For the record: I am fine with adding more specific types below LocalBusiness. However, I think we should have a rough idea about the maximum feasible size of that branch so that we have a guideline for deciding - I think more than 50 will be hard to handle. Also, there is naturally a strong cultural bias in any such rigid categories.

@LeezaRodriguez The fact that LocalBusiness is an Organization and a Place is a well-established design decision in schema.org. It was motivated afaik by the fact that in many Web sites, it is difficult to distinguish the legal entity from the place. However, I think it is fine to use LocalBusiness in this form for 

- individuals acting in a business setting (like sole proprietorships, freelancers, etc.) even when they are not strictly speaking an Organization and
- for businesses that do not have a fixed office location (like freelance Web developers or Emergency Room physicians), because the definition of Place is pretty broad - "Entities that have a somewhat fixed, physical extension.".

Martin

**Comment by danbri** [comment]
@mfhepp re the Place aspect of LocalBusiness, I think it is reasonable that the "place-ness" of some "LocalBusiness" may vary. For a "corner store" that never moved in 50 years it is pretty central. For a more consultancy-oriented business whose premises are work-from-home but which has occasional visitors, it is more peripheral. I'm fine with this being a pragmatic spectrum rather than trying to spell such distinctions out super-explicitly, as that leads to a brittle and confusing model.  So I think we're broadly agreeing on that point.

**Comment by RichardWallis** [comment]
I support the suggestion from @jvandriel for MedicalOrganization to become a direct subtype of Organization with the introduction of a new MedicalBusiness subtype for LocalBusiness.  I believe this will be be both more understandable and flexible.

It will enable a similar pattern to the Person + MusicGroup use referenced by @danbri.  Person + MedicalOrganization would be equally applicable to an individual member of the medical profession.  The  
MedicalBusiness type enabling a better focus on those more place oriented entities.

As highlighted by others, this ties in with other discussions around the proposed movement of many medical terms into a 'health' extension (#492).

My initial thoughts on this being that MedicalOrganization & MedicalBusiness would remain core terms, possibly refined and extended in the proposed extension.

**Comment by twamarc** [comment]
+1

**Comment by vholland** [comment]
While we are at it, can we rename Physician to PhysiciansOffice? The description states the type should be used for a doctor's office, but the name leads people to believe the type is for the individual doctor.

**Comment by rvguha** [comment]
In the first of what is going to probably become a common reply from me ...

What is the use case application that is driving this vocabulary? Who has
signed up to build that application? Who will be publishing the data that
this application consumes?

guha

**Comment by danbri** [comment]
Let's focus on cleanup of our legacy inheritance before getting distracted with expansion. Some of the medical specifics could migrate into health.schema.org as extension. 

However the modeling issues @LeezaRodriguez raises are real and crop up in other contexts: anywhere where the activity/service that a (local) business performs is more important/central than the nominal physical location of them as a Place. In her medical example, ER physicians "does not usually have an office, and he may rotate through various hospitals". "Anesthesiologist are often subcontractors to Surgery Centers and Hospitals. In the hospital setting, they may or may not be employees of the hospital. Many do not have a physical office"; "A locum-tenens physician who sub contracts part time at various organizations has no physical office" etc etc.

I believe the lesson to draw here is not "Let's add more vocabulary", but let's make sure our existing vocabulary is documented in a way that makes sense to those struggling to interpret our published definitions. 

There is nothing super-special about medicine here: the same issues crop up with people making a living as hairdressers, babysitters, massage therapists, math tutors, translators etc. Such local businesses are increasingly not "bricks and mortar"-centric; we need to make sure (per #801) that LocalBusiness and Service make sense in such a world.

One way to do this would be to add a clarification to http://schema.org/LocalBusiness to indicate that the Place aspect of a LocalBusiness can be broad, and can change over time. That would be consistent with the "somewhat fixed" wording in http://schema.org/Place.

**Comment by LeezaRodriguez** [comment]
Dan, thank you for those points. But to be clear, it's not just about the place-ness. To many webmasters,  it's not abundantly apparent what entity schema.org/Physician refers to. Is it the practice entity (aka medical practice name) or the individual physician?  I believe that this is what @vholland 's point also underscores. I think her suggestion to change the label to PhysicianOffice is a good one and that the description should also spell it out. 

I think many hospital websites are indeed using schema.org/Physician to declare the individual medical doctors (M.D.s)  within their medical practice organization.   I have been of the mindset that schema.org/Physician represents the office entity (practice name) and the doctor is represented as schema.org/Person.  Yes/no?  Perhaps my thinking has roots in the fact that Freebase typed physicians as persons, and not organizations. 

In the physical world, a physician's office is 'the medical practice' . The physician's medical practice has an entity name, whether it be 'Oncology Specialists of Maryland', or 'Department of Oncology, Hospital X'. Each entity has physicians who provide medical care at that location. .   Does schema.org/Physician  refer to:
a. practice entity name, ex: 'Oncology Specialists of Maryland' =sign on the door
b. individual physician that provides care for this entity, ex: 'Dr Smith'
c. both of the above

It would be great to have a detailed description along with this data type. Thank you.

**Comment by RichardWallis** [comment]
Looking at the current hierarchy ``Thing > Place > LocalBusiness > MedicalOrganization > Physician`` and the description "*A doctor's office.*" @vholland 's suggestion of relabelling to PhysiciansOffice would provide an obvious clarification.

As a non-medical person my assumption, before reading the description, was that it represented an 'individual physician [person] that provides care'.

A detailed description would be more helpful, but the fact that we are having this discussion indicates that descriptions are not the whole story in removing confusion. 

Perhaps the efforts to move some of the more detailed medical terms into an extension will give us the opportunity to clarify things, not only in the extension but also in the terms that remain in the core.

/cc @twamarc

**Comment by jvandriel** [comment]
I too think @vholland makes sense, and you're certainly not the forst to say _"As a non-medical person my assumption, before reading the description, was that it represented an 'individual physician [person] that provides care'"_ @RichardWallis.

But how about not only changing ```schema.org/Physician``` into ```schema.org/PhysicianOffice``` but also doing this for ```schema.org/Dentist``` ( ```schema.org/DentistOffice```) and  ```schema.org/Optician``` ( ```schema.org/OpticianOffice```)?

And what about being able to express a person's profession (#807), would a new ```profession``` for ```schema.org/Person``` property be helpful/desired?

**Comment by LeezaRodriguez** [comment]
I would also like to point out that in the USA, the federal government issues NPI (National Provider Identification) numbers to both:
-the individual physician
-organization entity (the medical practice, facility , supplier, hospital , etc)

**Comment by twamarc** [comment]
This comes back to the suggestion done before in #807. The purpose here is not expanding but is about clarification. I do not see another best way to clarify definitions there except the one suggested in  #807.
Yes, I support the  @vholland's suggestion but am afraid is not scalable: if we want to disambiguate all those terms and follow the @jvandriel idea about not only changing ``schema.org/Physician`` into ``schema.org/PhysicianOffice`` but also doing this for ``schema.org/Dentist`` ( ``schema.org/DentistOffice``) and ``schema.org/Optician`` ( ``schema.org/OpticianOffice``), Am afraid we will end up with to many deep changes.
Let's us chose the most conservative approach with just minimal additions

My 2 cents
~Marc

**Comment by danbri** [comment]
Are there many others, or just these? Electrician too? I like the *Office pattern, ... but electricians aren't very office-centric.

**Comment by twamarc** [comment]
We have more terms where it's not defined if it is the person, the office, or the service.
Some of them are under ``` http://schema.org/LocalBusiness ```  and others under : 
``` http://schema.org/ProfessionalService
	> GeneralContractor
	> Notary
	> RoofingContractor 
	> Dentist 
	> Physician
	> Optician
	> Electrician
	> HousePainter (here it's cleary said a service)
	> Locksmith
	> Plumber (here it's cleary said a service)
	> RoofingContractor
``` 
am afraid I have not populated all of them, there's a need to look into all terms

**Comment by mfhepp** [comment]
Before we open up a big task in here: I think the default pattern of having all local businesses being subclass of Place AND Organization is fine and should be kept. In GoodRelations, we had a clear separation between BusinessEntity and Location, which is conceptually nicer but leads to a lot of problems in practice - e.g. are you referring to the restaurant as a physical place or the name of the business or the legally responsible individual.

Joe's Pizza can mean
- a place in a building
- the legal entity behind the restaurant (an individual or organization)
- the name for the restaurant in the sense of a brand, which could move to another place ("Joe's Pizza has moved to 12344 ACME street").

Disambiguating those is hard for many data-sources, so I recommend to keep the current setting and NOT introduce a distinction, let alone putting that extra meaning in clumsy suffices like "XYZOffice".

The question for schema.org is not whether a distinction will in theory facilitate the use of the data, but whether publishers of data can, at Web scale, populate the distinctions reliably. If the new distinction will be a major cause of confusion, error and thus data quality problem, nothing is gained but an additional barrier to adoption.

**Comment by jvandriel** [comment]
_"I think the default pattern of having all local businesses being subclass of Place AND Organization is fine"_

+1  

I suggested introducing ```schema.org/MedicalBusiness``` because @danbri suggested ```schema.org/Place`` might be an issue here. But to be honest I don't much of a problem with it either.

The labels for certain local ```schema.org. org/LocalBusiness``` subtypes however should be something we look into.

As well as maybe introducing a new 'profession' property and possibly a ```schema.org/Profession type as suggested in #807.

**Comment by twamarc** [comment]
@mfhepp I agree with you on the idea of having all local businesses being subclass of Place AND Organization. What about services they offer? I think this should be separated (with
 
I think we should -at least separate Joe's Pizza (as a Brand pizza) which can be found in nearest supermarket ; from Joe's Pizza (a person/organization) which may be located far away.
This maybe helpful for webmasters. 

This is not different when we talk about  Dentist, Plumber, etc.

**Comment by mfhepp** [comment]
@twamarc Yes, but we already have the core elements for distinguishing a local business from its services and products.

For products, we can go the LocalBusiness  ->  makesOffer -> Offer -> itemOffered -> Product route

For services, we can either use Service -> provider -> LocalBusiness route or also use
LocalBusiness  ->  makesOffer -> Offer -> itemOffered -> Service

Joe's Pizza as a brand pizza is simply a Product or ProductModel with brand -> Brand.

Joe's Pizza as a place is a LocalBusiness.

**Comment by danbri** [comment]
Yes, we should stick with Place + Organization, ... but let's not read too much into "Place" - it needn't always be a bricks-and-mortar store with a fixed address. Some local businesses have a nominal place-of-business but are increasingly mobile/virtual...

**Comment by LeezaRodriguez** [comment]
I think we should consider the the physician person and the physician organization as separate entities.  **As this vocabulary scales out to include insurance and clinical trial data**,  we may run into problems. 

In the USA,  the US government disambiguates between the physician person and the physician office.   The physician person and the physician organization each apply for separate  NPI  numbers.  You do not exist as an individual provider person or a medical organization if you do not have an NPI number.  With insurance claims,  carriers require the NPI numbers of **both** the individual physician and the physician organization.   Also, an individual physician can practice medicine with several different physician organizations.  Malpractice policies, claims, and associated data bank history are mainly associated with individual physicians. Individual physicians must have state licenses to practice medicine. Not all medical organizations will receive a state license , as often times the burden rests on the licenses of the individual physicians and their formal certification in a designated 'Medical Specialty'.   

And with Clinical Trial registry,  while the physician organization may be the trial sponsor or site, it is the individual physician who is the Primary Investigator.

.02

**Comment by danbri** [comment]
So part of this was done as part of v3.0 just released: MedicalOrganization is subtype of Organization not LocalBusiness. It looks like we did not document very explicitly that this was changed, I will add a note to the docs/releases.html page.
