### ISSUE TITLE
Adding profession property to Person

### ISSUE THREAD

**Issue by twamarc** [schemaorg/schemaorg#807]
The need comes from the effort in health extension to clean up MedicalOrganization |Organizations | LocalBusiness definitions.
see https://github.com/schemaorg/schemaorg/issues/806 and https://github.com/twamarc/ScheMed/issues/14

The proposal there (taking suggestions from colleagues, thanks to @jvandriel) is to have: 
 ``` 
Organization 
        > MedicalOrganization 
```
and 
 ```
Organization
    > LocalBusiness
        > MedicalBusiness (new class in health extension)
            > Dentist
            > DiagnosticLab
            > Hospital
            > MedicalClinic
            > Optician
            > Pharmacy
            > Physician
            > VeterinaryCare
```
 ```
Person
    > profession (new predicate in core)
        > Profession (new class in core)
            > MedicalSpecialty
               > Cardiovascular
               > Dentistry
               > etc 
```

We avoid creating ```MedicalProfession``` as it has the same semantics with ```MedicalSpeciality````
Your input is welcome.

/cc  @jvandriel @LeezaRodriguez @danbri @vholland @rvguha @RichardWallis

**Comment by jvandriel** [comment]
Personally I think it's interesting to add a ```profession``` property to ```schema.org/Person``` although I have mixed feelings about introducing a ```schema.org/Profession``` type.

The reason why I like the idea of a (textual) property is because it helps folks express: 

_I am .... I do ... I work for ..._ A way of communicating info about yourself many folks do both on- and offline.

And usually people tend to describe their ```profession``` for the _I do_ part (in combination with their ```jobTitle```).

Now the good side of introducing a ```schema.org/Profession``` type would be that one can provide a referral to another vocabulary specifying more granular info but I'm not sure whether schema.org should provide an enumeration list for it.

Simply to prevent adding a new type I like ```schema.org/Organization```that potentially adds tons of new enumerations that will be nearly impossible to maintain.

So my question is: Are there any good vocabularies out there ( or enumeration listings) that can be used for further disambiguation?
(For going beyond a textual value for ```profession```)

**Comment by mfhepp** [comment]
@jvandriel There are e.g. 

- http://www.ilo.org/public/english/bureau/stat/isco/isco08/
- http://www.bls.gov/soc/
- https://ec.europa.eu/esco/portal/home

**Comment by RichardWallis** [comment]
-1 for a Schema.org enumeration for profession types.
A ``profession`` property for ``Person``  could provide some utility - give it a range of Text & URL and things like ``https://www.wikidata.org/wiki/Q27349`` could provide the flexible external enumeration capabilities we would be looking for.

**Comment by danbri** [comment]
Have a look at http://schema.org/JobPosting ... I'd rather we improve 'occupationalCategory' first or at least come up with something that works for describing job posters *and* job seekers...

**Comment by vholland** [comment]
As @danbri and @mfhepp suggest, it would seem better to build on 'occupationalCategory' and update the description to suggest external taxonomies beyond O*NET-SOC.

**Comment by jvandriel** [comment]
In that case, would it be an idea if the domain of ```occupationalCategory``` is expended to ```schema.org/Person```, combined with providing some examples that contain references to O*NET-SOC (and/or ISCO, SOC, ESCO)?

**Comment by mfhepp** [comment]
+1

**Comment by twamarc** [comment]
am afraid, ``` occupationalCategory``` can hardly be used in place of ```profession```. Eg. coding a site with demographic data where we have f eg. "Marc Profession Painter", to use ```<:Marc> <schema:occupationalCategory> <Painter>`` seems weird to me.

**Comment by chaals** [comment]
Hmm. @twamarc I think it actually makes a lot of sense. 

One of the obvious reasons I can see this actually being used is for matching job seekers and job postings, as danbri suggested. So using the same property seems extra-helpful.

Are there other use cases that will get implemented?

**Comment by jvandriel** [comment]
Actual cases not yet, although that could be as simple as reaching to the following examples (that @LeezaRodriguez found in minutes, giving the impression there are many more to be found):

- WebMD (web portal): http://doctor.webmd.com/doctor/ivan-borrello-md-c4bc9c82-90d7-45a0-bc0e-2f8aa610fbda-overview
- Cleveland Clinic ( well respected private teaching hospital):http://my.clevelandclinic.org/staff_directory/staff_display?doctorid=1767
- NYU Langone (well respected private teaching hospital):http://nyulangone.org/doctors/1679705230/joshua-s-silverman

All these sites currently (falsely) use ```schema.org/Physician``` to express 'professions' where they should have been expressing:
```Person > occupationalCategory > SomeThing```

**Comment by DDeering** [comment]
I like the idea of adding occupationalCategory to schema.org/Person.  I'd also love to see "skills" added to Person, since it's already a part of JobPosting as Dan mentioned.  I could see multiple uses of the property for Person, and I think that occupationalCategory, profession, and skills each would have their own unique but important role within the Person type.

**Comment by jvandriel** [comment]
That could be done the same for ```skills``` way as I now suggested for ```occupationalCategory```, namely expanding its domain to ```schema.org/Person```, while expanding its range to ```url```. While this could also be done with ```qualifications```. 

If I got it right than https://ec.europa.eu/esco/portal/home offers URIs that could be used for all three (```occupationalCategory```, ```skills```, ```qualifications```).

Although if that is agreed upon, than it might be wise to rename ```skills``` and ```qualifications``` to their single form (```skill``` and ```qualification```).

**Comment by gkellogg** [comment]
When we looked at this for sports and movies the solution was to introduce Role, so that position or characterName could be described on the role. This reflects the fact that a person may do different things in different contexts. Profession/Occupation are quite similar, but over longer periods of time.

Gregg Kellogg

**Comment by DDeering** [comment]
+1 @jvandriel

**Comment by NeverGivinUp** [comment]
+1 to the subject

I'm marking up the website of a psycho therapist and ran into a similar issue. She is specialized in eating disorders, obesity and psychological factors of gastric operations. But I don't see a way to express that in markup. Workarounds like alumniOf, award or affiliation don't apply either.

**Comment by twamarc** [comment]
+1
I keep believe having this would help:
 ```
Person
    > profession (new predicate in core)
```

**Comment by twamarc** [comment]
Discussed and seems to converge that:
The proposal there (taking suggestions from colleagues, thanks to @jvandriel) is to have:

Organization 
        > MedicalOrganization 
and

Organization
    > LocalBusiness
        > MedicalBusiness (new class in health extension)
            > Dentist
            > DiagnosticLab
            > Hospital
            > MedicalClinic
            > Optician
            > Pharmacy
            > Physician
            > VeterinaryCare
Person
    > profession (new predicate in core)
        > Profession (new class in core)
            > MedicalSpecialty
               > Cardiovascular
               > Dentistry
               > etc

**Comment by twamarc** [comment]
``` 
Organization 
        > MedicalOrganization 
```
and 
 ```
Organization
    > LocalBusiness
        > MedicalBusiness (new class in health extension)
            > Dentist
            > DiagnosticLab
            > Hospital
            > MedicalClinic
            > Optician
            > Pharmacy
            > Physician
            > VeterinaryCare
```
 ```
Person
    > profession (new predicate in core)
        > Profession (new class in core)
            > MedicalSpecialty
               > Cardiovascular
               > Dentistry
               > etc 
```

**Comment by chaals** [comment]
I'm happy to have something along these lines and don't want to argue the naming too hard - but I really would like us to avoid having `profession` and `Profession` but meaning different things…

**Comment by twamarc** [comment]
Decision: see http://www.w3.org/2015/11/06-schemed-minutes.html and https://github.com/schemaorg/schemaorg/issues/492

Summary:
1)Not move them from core to extension
2)Improvement in extension:
 ``` 
Organization 
        > MedicalOrganization 
```
and 
 ```
Organization
    > LocalBusiness
        > MedicalBusiness (new class in health extension)
            > Dentist
            > DiagnosticLab
            > Hospital
            > MedicalClinic
            > Optician
            > Pharmacy
            > Physician
            > VeterinaryCare
```
 ```
Person
    > profession (new predicate in core)
        > Profession (new class in core)
            > MedicalSpecialty
               > Cardiovascular
               > Dentistry
               > etc 
```

**Comment by namedgraph** [comment]
I'm looking at describing `Person` skills but not still seeing a good way to do it using schema.org. Why was this issue closed? This proposal makes most sense to me:
> That could be done the same way for `skills` as I suggested for `occupationalCategory`, namely expanding its domain to `schema.org/Person`

Note that occupations/professions are distinct from skills --  those are linked but [separate taxonomies](https://esco.ec.europa.eu/en/classification).
