### ISSUE TITLE
Add software provenance terms

### ISSUE THREAD

**Issue by shepazu** [schemaorg/schemaorg#809]
On a `CreativeWork`, Schema.org has `author` and `creator`, which are equivalent, and which indicate the person or people (or organization) who created the work. In addition, Schema.org should also have terms for the software which those people used to create the work. 

For example, if I create an SVG document using Inkscape or Adobe Illustrator, I'm the `creator`, but the `generator` is Inkscape or Illustrator. Currently, this is normally expressed in a comment, but I'd like to have a more formal, machine-readable set of terms for the name and version of the generator. 

The W3C PROV Ontology uses the term `prov:wasGeneratedBy`, so to match that to the simpler Schema.org terminology, I suggest the term `generator` (which is the term that Adobe products use). This should be indicated to be equivalent to `prov:wasGeneratedBy`, in whatever mapping is used for such equivalence. (An alternative term is `userAgent`, but that would probably confuse most people.)

It's also common and useful for software to provide its version, so I suggest `generatorVersion`. I can't find a simple equivalent in W3C PROV for this (though possibly you could shoehorn `prov:Revision` for that).

Finally, sometimes these generator comments include the timestamp, which might be different than the `dateCreated`; for example, if a file was converted from one format to another. We could use `dateModified` for that, or to be more precise, we could have a new term, `dateGenerated`; I don't know which would be better. The W3C PROV equivalent seems to be `prov:generatedAtTime`.

Note that it's possible for a work to be automatically created by software, with little contribution by a human (other than creating the software in the first place), so `generator` might be used on works that have no `author` or `creator`.

**Comment by RichardWallis** [comment]
I'm wondering if the desired result could not be achieved by creating a subtype of `schema:PublicationEvent` - `SoftwareOutputEvent`? which could have an `application` property referencing a `schema:SoftwareApplication` describing the creation environment in as much detail as you would ever need.   In which case the current `schema:publication` or possibly `schema:releasedEvent` on `schema:CreativeWork` would suffice.

**Comment by chaals** [comment]
That sounds like a pretty complicated approach.

I think something better would be to have a way of describing the tools you used to produce a `CreativeWork` - photoshop, an angle grinder, 7 beers and a pizza…

This kind of information has long been around for certain types of creative arts such as photography - indeed, in the digital age most photos seem to carry that already now. Likewise, it has commonly been added to web pages, etc.

But before we get too far, what is the actual use case for this data? Who is going to process it and present it? (I know there is an equivalent functionality in Flickr…)

**Comment by RichardWallis** [comment]
Something like `createdUsing`  - domainIncludes `CreativeWork`, rangeIncudes `Product`,`CreativeWork`

... *if there is a use case.*

**Comment by shepazu** [comment]
One use case is sharing between services. For example, if I use a Twitter client to post something to Twitter, Twitter might process it slightly differently than if I used a different Twitter client. Similarly, when I post something on Twitter and it's automatically reflected on Facebook, Facebook provides the contextual notice that I originally published that post on Twitter, which sets expectations about brevity, etc.

**Comment by chaals** [comment]
I know of a lot of useful things we *could* do with the information. The question is whether there is someone who is *going* to do something, because until that point I am reluctant to support adding the terms (although it seems reasonable enough to think about the design, because it is something I can imagine people wanting to use…)

**Comment by shepazu** [comment]
@chaals The Facebook example, and the Inkscape and Illustrator examples, are real-world and active today, though they don't currently use Schema.org terms.

Inkscape does include RDF for Creative Commons licensing terms, but lacking a way to express `generator`, it simply uses an XML comment. Inkscape's SVG content, and the licensing terms, are commonly used by Wikipedia and various clipart sites. I can't guarantee they would use the Schema.org terms, but it would logically fit.

I've encouraged W3C Working Groups to use Schema.org where possible, instead of minting their own custom vocabularies or terms. There is a reasonable chance that the Web Annotation WG would use the appropriate Schema.org terms in their data model, if the proper terms existed. There is currently [a discussion about reusing vocabularies to replace custom terms]( https://lists.w3.org/Archives/Public/public-annotation/2015Sep/0220.html).

As an aside, in my mind, the fewer ontologies (and namespaces) a project uses, the easier it is to use. For example, if the Web Annotation Data Model can reference one common external vocabulary, `schema`, rather than two, `dcterms` and `prov`, or more, that would reduce some complexity.

**Comment by akuckartz** [comment]
Using vocabularies is good. Therefore `prov` should be used by annotations and `schema`.

**Comment by shepazu** [comment]
@akuckartz, Can you cite some objective evidence for your assertion, your reasoning, or your conclusion?

All that aside, `prov` doesn't have a clean mapping to express software version.

**Comment by danbri** [comment]
+1 for @chaals 's concern for usecases.

An obvious complication here is whether to keep a growing log of the software tools that touch a document, or just over-write. If I create SVG in Amaya, open and edit it in Inkscape, and again in Ilustrator, is it important to anyone to have that entire trail? Is there value in knowing which app opened it last?  In the absence of someone saying "we need and will use this" it isn't clear which design wins.

I wonder if there are usecases around DataFeed too, where a feed will typically be something like JSON-LD, e.g. you might want to programmatically transform feeds that come from e.g. Drupal v10.x in ways that would be difficult if you didn't know what tool generated which feed. But again complexity lurks: many software systems are really ecosystems full of (versions of) modules and extensions.

**Comment by elf-pavlik** [comment]
if value of such *generator* property used http://schema.org/SoftwareApplication
it already hints usage of http://schema.org/softwareVersion

plase also notice [as:generator](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-generator)
