### ISSUE TITLE
 GeoShape and GeoCoordinates should allow a postalCode [edit: + country] for rough positioning.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#810]
Sub-issue of #113.

This is non-essential in that we can use GeoShape --address-- PostalAddress -- postalCode-- xyz.

But that is needlessly heavy, so let's pick out the most useful piece of PostalAddress for this purpose, postalCode. This fits well with the approach implemented in https://github.com/schemaorg/schemaorg/issues/808 which allows these to have a simple textual 'address' too.

**Comment by pmika** [comment]
Does postalCode make sense without a country?

**Comment by danbri** [comment]
You're right. It would make more sense with a Country. 

The most obvious options seem to be: 

* use address with a value of PostalAddress which has an addressCountry ...
* allow addressCountry to apply to these types directly

In passing I note that Country says "You can also provide the two-letter ISO 3166-1 alpha-2 country code." but doesn't say which property of a Country would carry such a code (e.g. alternateName? should we add something?)

**Comment by radusi** [comment]
Hi,

Just as suggestion, some time ago I came across with a ISO standard for Addresses via UPU ( Universal Postal Union - upu.net ) . 
The direction they go is ZIP CODE-COUNTRY, Thus maybe a format like Country ISO_3166-2 - Zip Code would satisfy ( ex. US-90210 would suffice ).

**Comment by danbri** [comment]
Thanks @radusi - I was also wondering in this direction, e.g. URI schemes, but I think both approaches are relatively obscure (even if the idea is very sensible).

**Comment by danbri** [comment]
I've committed some changes - see http://sdo-phobos.appspot.com/addressCountry

* addressCountry can also be used on these geo-* types directly (i.e. why force verbosity here)
* addressCountry schema finally matches its textual definition by anticipating Text values (i.e. the ISO country codes)

I believe these are both pretty sensible given the options...

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
