### ISSUE TITLE
containedIn (between Places) is named in the most annoying direction. Add inverseOf, containsPlace

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#811]
Let's rename containedIn to containedInPlace too.

**Comment by mfhepp** [comment]
I am fine with that, but I do not think it is too annoying as it stands ;-)
Note that we are using containedIn in the hotel proposal, so there is a potential merge conflict if you change the name at the time of adding my proposal.

**Comment by danbri** [comment]
Thanks, ack'd.

**Comment by danbri** [comment]
Ok

* http://sdo-phobos.appspot.com/containedInPlace
* http://sdo-phobos.appspot.com/containedIn
* http://sdo-phobos.appspot.com/containsPlace

**Comment by pmika** [comment]
+1

**Comment by scor** [comment]
:+1:

**Comment by chaals** [comment]
Looks OK to me, but again, providing crossrefs between containedInPlace and containsPlace seems sensible

**Comment by danbri** [comment]
Thanks @chaals crossrefs in this case are built in, since we declare them to be inverses of each other - see links above

**Comment by danbri** [comment]
Queued for closure after next release. http://sdo-phobos.appspot.com/containedInPlace

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
