### ISSUE TITLE
Consider specific textual changes to /Product and /Service to explain their relationship

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#812]
This is a sub-issue of #801 (and related to #411) which led to a number of small clarifying changes around services. 

The purpose of this issue is more specific: to collect, discuss and potentially implement tweaks to the _wording_ of /Service and /Product that better present schema.org's approach and the intended meaning of the relevant terms.

Improved or additional examples are welcomed too.

**Comment by danbri** [comment]
Suggestion from @jvandriel: remove  "a haircut" from /Product (carried over from #801)

**Comment by danbri** [comment]
I've left this issue open after the [v2.2 release](http://schema.org/docs/releases.html). Does anyone have concrete textual changes to propose? I see only the 'remove haircut' suggestion.

**Comment by jvandriel** [comment]
Well, I guess with the silent upgrade of adding ```offers``` to ```schema.org/Service```most of my issues with the overlap between ```schema.org/Product``` & ```schema.org/Service``` have been resolved as one no longer needs to use an MTE (```[Product,Service]```) any longer to describe commercially offered services even though ```schema.org/Product``` _can_ be used for this as well. 

So removing 'a haircut;' suffices for me.
