### ISSUE TITLE
SEO Score is changed upon inserting Schema on Website

### ISSUE THREAD

**Issue by giannettiartisans** [schemaorg/schemaorg#813]
Hello,
I am a beginner and started an online business in Jan. 2015. An SEO expert suggested using schema for posts and product listings, the problem is that when I insert schema into a product listing it modifies my SEO score on a Wordpress/WooCommerce site. It changes it from green to yellow. Also, the content is put into a white box and it looks terrible on my site due to the fact that the background is orange.

Can someone please help me on this issue?

Website: www.giannettiartisans.com
Email: giannetti.export@gmail.com

**Comment by scor** [comment]
Regarding the different look of the content, it sounds more like an implementation issue than something specific to the schema.org vocabulary. Note that the example published on the schema.org sites (for example schema.org/Person) are meant to only be examples, and will need to be adapted to your site markup. In theory, no additional HTML elements (or if any, very little) should be added to your page. Most of the time, if new HTML elements are needed to wrap a string, you should use span. If you used div, this could cause some layout issues, so be careful. If colors are changing, could be some conflicts with your CSS.

I don't know anything about the SEO score tool you are using. Which one is it? If anything, your SEO score should increase and not decrease, unless you are implementing your markup in the wrong way.

**Comment by scor** [comment]
Just checked your site markup (frontpage) and you are using JSON-LD, so it is very unlikely that this would caused the look and feel of your site to change.

**Comment by giannettiartisans** [comment]
Hello, Thanks for responding so quickly, however it is changing it up. There is a white box and the SEO is a Woo Commerce Plugin that runs an automatic analysis on the page. Not sure what to do with the CSS. I think I'm implementing correctly, it's pretty straight forward. As far as coding is concerned I have no idea if it's ok or not.

**Comment by mfhepp** [comment]
@giannettiartisans This is an implementation problem of using data markup, not an issue related to the schema.org vocabulary itself. Please try respective developer forums like stack exchange or product-related forums.
