### ISSUE TITLE
  SEO Score is changed upon inserting Schema on Website

### ISSUE THREAD

**Issue by giannettiartisans** [schemaorg/schemaorg#814]
I just posted in the forum asking for help with schema, and a moderator closed out the forum and the issue was not resolved! I am a beginner and I don't know anything about coding!! Don't offer forums for technical issues if you are just going to close it off because you don't want bad publicity! At this point I will look into taking Schema off my website!!! TERRIBLE!!

**Comment by chaals** [comment]
This forum is for technical discussion of the terms that should or should not be included in schema.org.
As such, any questions about support of particular products including the search engines and related tools that make use of schema.org markup (which was the nature of your question) are out of scope.

As suggested, please use an appropriate forum for beginner's implementation questions, such as stackoverflow.

**Comment by danbri** [comment]
What @chaals said. If your question is about Google, https://productforums.google.com/forum/#!forum/webmasters may be a better place to ask.
