### ISSUE TITLE
Add new property to Service to describe its 'mobility'

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#817]
As @danbri said in issue #806:

> Some local businesses have a nominal place-of-business but are increasingly mobile/virtual...

Increasingly, there are services like Uber, which not only have an areaServed, but the exact location of a provider is dynamic.

To that end, I propose, we add a property to http://schema.org/Service called _providerMobility_. It would expect a text value for now, but would allow us to differentiate this case.

**Comment by danbri** [comment]
+1 but please suggest some text values

**Comment by vholland** [comment]
Created pull request #820 with an example.

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
