### ISSUE TITLE
Simple mechanism for adding distance information between places

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#831]
Local businesses often indicate the distance to other places, e.g.

Hotels:
- 5 miles from the city center
- 500 m to the Museum of Modern Arts
- 25 km to Munich Airport

Real Estate:
- 1 mile to Edison Community College

While the Euclidean distance can be computed from the geo-coordinates, such sites (like HRS hotel reservation sites) typically add value by highlighting relevant places in the vicinity.

I have just submitted a pull request #832 that addresses this issue. It is based on QuantitativeValue and thus also supports temporal units of measurement (knowing of their subjectivity).

**Comment by rvguha** [comment]
These are pretty sophisticated constructs. I would like to hold off on
these until we have concrete applications that use these

guha
