### ISSUE TITLE
Name of Property 'alumniOf'

### ISSUE THREAD

**Issue by dpascotto** [schemaorg/schemaorg#837]
Shouldn't be 'alumnusOf' ?

**Comment by chaals** [comment]
If you want to be good at grammar, yes.
If you want people to get it right, quite probably not.
Given that, and the fact that it is used on "10k-50k domains" I don't think it is worth making the change.

**Comment by danbri** [comment]
Afraid I didn't go to a school that done grammar good, I think we have to accept some inelegance here. Similarly, we have avoided "schemata", although that feels better to some than "schemas". I'm going to close this issue as we're quite unlikely to change at this point. But thanks for the thought, @dpascotto :)
