### ISSUE TITLE
RDFa markup incorrect for Enumeration members

### ISSUE THREAD

**Issue by jaw111** [schemaorg/schemaorg#841]
If you check the RDFa markup in the page for [OrderDelivered](http://schema.org/OrderDelivered) you see it has type `rdfs:Property`:

    <div id="mainContent" vocab="http://schema.org/" typeof="rdfs:Property" resource="http://schema.org/OrderDelivered">

Whereas in the [source RDFa file](https://github.com/schemaorg/schemaorg/blob/sdo-phobos/data/schema.rdfa#L3917) it has type `schema:OrderStatus`:

    <div typeof="http://schema.org/OrderStatus" resource="http://schema.org/OrderDelivered">

Looks like something gets lost/mangled during generation of the published HTML pages.

**Comment by danbri** [comment]
Thanks @jaw111, @RichardWallis :) I'll close this now.

**Comment by jaw111** [comment]
Sure thing.

For the record what triggered me to open the ticket is that the Google structured data validator flags an error when byArtist is used to link to a Person resource. This seems rather counter-intuitive, but as noted the MusicGroup can also be an individual person. So, in order to have valid data, the solution would be for the publisher to add additional type info to the resource.

Regards,
John
