### ISSUE TITLE
Add Person to rangeIncludes of byArtist

### ISSUE THREAD

**Issue by jaw111** [schemaorg/schemaorg#857]
Currently the range of byArtist property is MusicGroup which does not handle the case very well where a MusicAlbum or MusicRecording is made by an individual person. To cover this Person should be added to the range of byArtist.

**Comment by RichardWallis** [comment]
From description of [MusicGroup](http://schema.org/MusicGroup):
A musical group, such as a band, an orchestra, or a choir. *Can also be a solo musician*.

**Comment by jaw111** [comment]
For the record what triggered me to open the ticket is that the Google structured data validator flags an error when byArtist is used to link to a Person resource. This seems rather counter-intuitive, but as noted the MusicGroup can also be an individual person. So, in order to have valid data, the solution would be for the publisher to add additional type info to the resource.

Regards, John
