### ISSUE TITLE
Local marketplace subtype on Localbusiness and Place type?

### ISSUE THREAD

**Issue by dockbiz** [schemaorg/schemaorg#863]
If duplicate issue please tell me and close this issue, Thank u.

**Comment by mfhepp** [comment]
I do not think we should add such a branch. Using the existing LocalBusiness type should work as well; there is no gain for the major consumers of schema.org from having a LocalMarketplace subtype.

Simply use LocalBusiness and indicate the additional details in the name and description properties.

I take the liberty to close the issue; feel free to reopen if necessary.
