### ISSUE TITLE
bug in https://schema.org/RentalCarReservation examples

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#866]
The JSON-LD example for https://schema.org/RentalCarReservation uses a non-existent property operatingCompany. This should be replaced by schema:provider and attached to the schema:RentalCarReservation, not the schema:Car.

I attach a fixed example.

[fixed-reservation-example.txt](https://github.com/schemaorg/schemaorg/files/25985/fixed-reservation-example.txt)

**Comment by mfhepp** [comment]
For proper acknowledgment: This was spotted by Jimmy Phan, see

https://lists.w3.org/Archives/Public/public-vocabs/2015Nov/0002.html

**Comment by danbri** [comment]
Thanks Jimm, Martin, Richard :) queued for release asap.
