### ISSUE TITLE
Multithreading and warmup

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#876]
Currently the application is not threadsafe which limits scaling.  In addition the spawning of new instances causes response pauses, as these need to load data before responding to requests.

A fix of this issue will result in threadsafe code and, a normal state of one or more warmed up idle instances ready for action as they are fed requests.

* [ ] multi-threading
* [ ] warmup - see https://github.com/schemaorg/schemaorg/issues/480

# Reading

* https://cloud.google.com/appengine/docs/python/config/appconfig?hl=en
* http://blog.notdot.net/2011/10/Migrating-to-Python-2-7-part-1-Threadsafe
* https://cloud.google.com/appengine/docs/python/python25/diff27#Concurrent_Requests
* http://stackoverflow.com/questions/15124866/threading-safety-in-google-app-engine-python-2-5-2-7-instances-how-it-works
* http://stackoverflow.com/questions/22527971/threads-in-google-app-engine-with-python-2-7
* http://stackoverflow.com/questions/11289606/is-python-module-loading-is-thread-safe-in-google-app-engine
* http://appenginedevelopment.blogspot.co.uk/2011/10/multi-threaded-python-27-wtfaq.html

**Comment by danbri** [comment]
What's the status of this ? Should it be rolled out asap or needs further work?

**Comment by RichardWallis** [comment]
This was fixed as part of #887 which was applied directly to master - needs back merging into sdo-deimos.

**Comment by RichardWallis** [comment]
Fixed in V3.0
