### ISSUE TITLE
Schema blogPosting isn't using the right microdata example

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#883]
https://schema.org/BlogPosting is showing liveblogposting, instead, on the microdata example.

**Comment by darmudisusanto** [comment]
hi...

**Comment by lexbi** [comment]
This is still not clear almost a year later, best example I've found is from this website: http://jsonld.com/blog-post/ 
Which itself suggests there is not enough clarification between `blog`, `BlogPosting` and  `BlogPost`.
