### ISSUE TITLE
New property for describing Map display options

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#886]
Maps often have display options, but there is no way to express those in schema.org.  I propose adding a new property ```mapDisplayOption```, which is one or more of the following MapDisplayOptionType values:

MapDisplayUserLocation
MapHideUserLocation
MapDisplayRoute
MapHideRoute

**Comment by vholland** [comment]
See pull request #892

**Comment by danbri** [comment]
This is pretty cryptic, do you still want to argue for it?

**Comment by vholland** [comment]
I don't want to hold up the next release. I will re-open when I have a better use case.
