### ISSUE TITLE
Add PreSale to the available ItemAvailability values

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#888]
I suggest adding PreSale to the ItemAvailability enumeration.

PreOrder already exists, but that generally means one can order the item, but it will not be delivered until the item is generally available.

PreSale means one can order the item and receive it before general availability.

**Comment by mfhepp** [comment]
ok

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by vholland** [comment]
See pull request #893 .

**Comment by danbri** [comment]
Added http://sdo-deimos.appspot.com/PreSale - queued for review in next release.

**Comment by danbri** [comment]
Closing per http://webschemas.org/docs/releases.html#g888
