### ISSUE TITLE
Add dropOffLocation and estimatedTravelTime to TaxiReservation

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#889]
For taxi reservations, one sometimes needs to specify the destination. It would be useful to add the `dropOffLocation` to TaxiReservation.

It would also be useful to add an `estimatedTravelTime` for the cases where taxis give that sort of information.

**Comment by danbri** [comment]
Thanks, Vicki. +1 for the basic idea, here's some nitpicking on detail:

* dropOffLocation: can we try to make http://schema.org/toLocation work, please?
* estimatedTravelTime: whatever we do should here should generalize https://schema.org/estimatedFlightDuration 
* Note that we have alongside Flight, also BusTrip, TrainTrip. These share https://schema.org/arrivalTime defined as 'estimated arrival time'. Having estimated travel times for these other kinds of trips sounds plausible too.

**Comment by vholland** [comment]
+1 to http://schema.org/toLocation

I was thinking estimatedTravelTime was more in line with estimatedFlightDuration. We might not know the arrival time, just that it is a 30 minute cab ride.

**Comment by danbri** [comment]
would you say that...

* estimatedTravelTime subPropertyOf estimatedFlightDuration ?

**Comment by vholland** [comment]
I was thinking the other way around as estimatedFlightDuration is more specific than estimatedTravelTime.

**Comment by danbri** [comment]
Yeah, it's friday 5.30pm. Didn't touch a beer yet, but I typed that one back to front. Worse, I got it right the first time and copy/paste "fixed" it to reverse the order. You are right, of course :) Hometime here, have a good weekend!

**Comment by danbri** [comment]
Ok, so "arrivalTime" is explicitly said to be estimated, but we don't have estimated in its name; "estimatedTravelTime" is also estimated, but we do. I can live with that. But let's at least cross-reference these properties in their definitions.

**Comment by vholland** [comment]
Closing in favor of the more modern issue #1310.
