### ISSUE TITLE
Description wrong for arrivalStation

### ISSUE THREAD

**Issue by rlh100** [schemaorg/schemaorg#895]
arrivalStation: The station where the train trip ends.

Should read:
The station where the train trip begins

**Comment by rlh100** [comment]
"originates" might be a better word

**Comment by danbri** [comment]
Train trip currenetly has this:
* http://schema.org/arrivalStation "The station where the train trip ends."
* http://schema.org/departureStation "The station from which the train departs."
(and similarly, departurePlatform, arrivalPlatform).

I believe this is as intended. The terminology is from the perspective of the stations, so the train trip originates or begins at the 'departure' station. It then leaves that place and arrives at the 'arrival' station where the journey originates/ends.

Am I missing something? This matches the 'departures from' and 'arrivals at' terminology e.g. in http://www.eurostar.com/uk-en/travel-information/service-information/rtti#/dep/7015400/7015400 (and more often seen at airports). If this phrasing is at all counter-intuitive we ought to work on improving the description text.

**Comment by vholland** [comment]
@danbri Correct. It is from the perspective of the traveler. The trip begins at the departureStation and ends at the arrivalStation.

**Comment by danbri** [comment]
@rlh100 - I propose we close this as 'not a mistake', but if you have thoughts on clearer wording, do please share them here. We can always re-open the issue if agreement emerges on better text.

**Comment by danbri** [comment]
Closing as outlined above; happy to discuss further if needed. Thanks for the suggestion!
