### ISSUE TITLE
Make the distinction clear between schema.org and scientific ontologies

### ISSUE THREAD

**Issue by linikujp** [schemaorg/schemaorg#897]
There is a need to distinct between the vocabulary used in schema.org and scientific ontologies, such as OBO foundry ontologies and Bioportal ontologies.

There maybe some overlaps, for example, the animal names example.
It would be better to make it clear and align with scientific world.
There should be no duplicate efforts.

**Comment by mfhepp** [comment]
Schema.org takes notions and distinctions from existing ontologies, like FOAF, Cyc, etc. A continuous alignment with external ontologies, both top-level and domain ontologies, is however out of the scope of schema.org and also infeasible. Schema.org often has to make trade-off decisions between conceptual clarity, usability and matches to existing data sources. A Web vocabulary like schema.org has different goals and constraints and goes beyond a pure "ontology engineering" project.

Thus, I take the liberty to close this issues.
