### ISSUE TITLE
https://schema.org/CarUsageType and instances should go to the auto.schema.org extension

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#898]
I think that 

https://schema.org/CarUsageType and its predefined instances should be moved from schema.org core to the auto.schema.org extension, because the only property that uses this value set type,

https://auto.schema.org/specialUsage

is also defined in the extension, not in the core.

**Comment by danbri** [comment]
Thanks. However please see #705 "auto.schema.org extension: consider renaming specialUsage as vehicleSpecialUsage, or broaden its definition"; closing in favour of that existing issue.

**Comment by mfhepp** [comment]
This is IMO a different issue. If we decide to rename and broaden specialUsage, then https://schema.org/CarUsageType and its predefined instances should be moved from schema.org core to the auto.schema.org extension AND specialUsage should be added to the core. 

Currently, it is the other way round.

**Comment by mfhepp** [comment]
Since we also have itemCondition for generic product information about special usage, I think that simply  moving https://schema.org/CarUsageType and its predefined instances  to the auto.schema.org extension and maybe renaming http://auto.schema.org/specialUsage to vehicleSpecialUsage (tbd) will be the better route.

**Comment by danbri** [comment]
Let me rephase: the current approach, which uses a generic phrase for a very car-specific concept, isn't viable. Either the definition or the name has to change. Once we have resolved that question, then we are in a sensible position to decide whether terms are core or extension. I think we agree on where the terms should best live (i.e. in auto extension, with the property renamed as above).

**Comment by mfhepp** [comment]
@danbri I agree, so let's

1. rename http://auto.schema.org/specialUsage to http://auto.schema.org/vehicleSpecialUsage in the extension AND
2. move  http://schema.org/CarUsageType and its predefined instances to auto.schema.org AND
3. double-check that specialUsage is changed to vehicleSpecialUsage in all examples.

**Comment by danbri** [comment]
Sounds good to me. We can always collect xyzSpecialUsage properties into a common superproperty in the future, if some appear.

BTW from many years ago we also have http://schema.org/specialCommitments whose name is similarly too generic for its job-centric definition; maybe we can address that in future, but I'm glad we're not compounding the issue.

**Comment by twamarc** [comment]
@mfhepp @danbri this is an interesting and my solve some issues for other extensions as well. I will try to how it looks like once applied to vague/too general terms used fro medical/health extension.

**Comment by trypuz** [comment]
@mfhepp @danbri if we rename http://auto.schema.org/specialUsage to http://auto.schema.org/vehicleSpecialUsage we will have vehicleSpecialUsage property at the same time in the core and auto extension. 

Notice that http://schema.org/vehicleSpecialUsage has neither domain nor range. 

http://auto.schema.org/vehicleSpecialUsage will have range:CarUsageType, range:Text and domain:Vehicle. IMO http://schema.org/vehicleSpecialUsage should be removed from core.

**Comment by mfhepp** [comment]
I would keep vehicleSpecialUsage  in the core. Our guideline for core vs. extension was the following:

1. Stuff that is needed for many typical auto sites, including independent dealers and car listing sites, should go in core.
2. Stuff that is likely only needed on the authoritative manufacturer pages will go into the extension.

vehicleSpecialUsage  will be used for hundreds of thousands of used car listings.

> http://schema.org/vehicleSpecialUsage has neither domain nor range.

That is an error and should be fixed, ideally in your upcoming pull-request.

**Comment by trypuz** [comment]
@mfhepp, would you agree that 
1) http://schema.org/vehicleSpecialUsage in the core has:
domain: https://schema.org/Vehicle
range: http://schema.org/QualitativeValue
range: http://schema.org/Text

2) http://auto.schema.org/vehicleSpecialUsage in the auto extension has:
domain: https://schema.org/Vehicle
range: http://schema.org/CarUsageType
range: http://schema.org/Text
