### ISSUE TITLE
use isAccessibleForFree on all Event classes [+CreativeWork]

### ISSUE THREAD

**Issue by richard-verhoeven** [schemaorg/schemaorg#900]
Is there any particular reason why the property `isAccessibleForFree` is used on the class `PublicationEvent` only? It seems to me that this is a reasonable and (if true) important property for any kind of event, so I would strongly suggest to move it to `Event`.

**Comment by danbri** [comment]
Thanks. This seems to be a case of something being added for one purpose with insufficient attention to its wider use. It was added for http://blog.schema.org/2013/12/schemaorg-for-tv-and-radio-markup.html

Generalising seems worthwhile, although you soon run into numerous subtleties (geo restrictions, free-if-you-register etc., in case of content rather than events) that are too complex for schema.org to feasibly handle. But yes we should look at applying it to other event types at least, although the current definition "A flag to signal that the publication is accessible for free." really seems more concerned with creative works than events.

**Comment by richard-verhoeven** [comment]
Regarding events, perhaps the definition could simply be changed to "A flag to signal that it is possible to attend the event for free."

Trying a systematic approach, `isAccessibleForFree` might make sense and be useful wherever the `offer` property is available, even though the textual definition might not be the same for each class. Indeed, `isAccessibleForFree` is bascially a shorthand for a particular kind of `Offer`. The latter remains available to express the mentioned subtleties.

**Comment by jgoodell2** [comment]
The concept of *access rights* is applicable to other kinds of creative work as well.

E.g. CEDS defines a controlled vocabulary for Learning Resources with these options:

* Free Access
* Free Access with Registration
* Limited Free Access
* Available for Purchase
* Available by Subscription
* Publisher Defined

See: https://ceds.ed.gov/element/001561#FreeAccess

**Comment by vholland** [comment]
PublicationEvent is odd in that it uses a different meaning of "event" than the other Event types. PublicationEvent is for when a CreativeWork becomes available for consumption. The other Event types are for planned public or social occasions.

I would argue we are better off moving PublicationEvent out from under Event and expand the ranges of properties like startDate and endDate as necessary.

**Comment by darobin** [comment]
Without getting into the many issues related to access management, we would really like to use `isAccessibleForFree` on `CreativeWork`. We have scholarly content that is Open Access (which means really to everyone) and content that isn't. It would make a lot of sense to use that property on the former, distinguishing those article from those where you get a page that's truncated after the abstract.

**Comment by danbri** [comment]
+1 for broadening it to CreativeWork; it will be useful for Course too.

**Comment by danbri** [comment]
and to Event for http://pending.webschemas.org/CourseInstance

btw @vholland - I agree there is a difference between emphasis of PublicationEvent and the other event subtypes. But both need to work both for forward-looking descriptions (potential events) and for historical logs of events actually having happened. Much as with Action, which serves a role for potential actions and for recording chains of activities that actually happened.

**Comment by RichardWallis** [comment]
+1 for broadening as described.

**Comment by danbri** [comment]
(FYI @philbarker @westurner - is this useful for courses?)

Published via http://schema.org/docs/releases.html#v3.1
http://blog.schema.org/2016/08/schemaorg-update-hotels-datasets-health.html

**Comment by philbarker** [comment]
@danbri would be better if the definition didn't mention publication

**Comment by danbri** [comment]
Good point @RichardWallis!

Ok, "A flag to signal that the publication is accessible for free."
-> "A flag to signal that the publication or event is accessible for free."

Filed as #1290, since I don't like the same issue appearing twice in /docs/releases.html
