### ISSUE TITLE
Remove @value from datePublished in Periodical JSON-LD examples

### ISSUE THREAD

**Issue by dbs** [schemaorg/schemaorg#904]
As noted by @Aaranged and related to #903, the JSON-LD examples for Periodical / ScholarlyArticle examples currently contain unnecessary `@value` stanzas that complicate the otherwise straightforward datePublished attributes. These should be removed.

**Comment by dbs** [comment]
See https://github.com/dbs/schemaorg/commit/8ecbfe027519286e0ee59f9f0fa51b7129e0ebe3 for a commit that resolves this issue.

**Comment by chaals** [comment]
+1

**Comment by danbri** [comment]
@dbs - can you send a PR against our master branch? I tried to figure a way to do this without bugging you but have totally failed!

**Comment by RichardWallis** [comment]
Fixed in #926
