### ISSUE TITLE
Possibility to Specify Percentage based Charge/ Fee/ Premium in PriceSpecification

### ISSUE THREAD

**Issue by vanthome** [schemaorg/schemaorg#908]
If I wanted to specify the surcharge for a certain payment method and that happens to be not a fixed amount but a percentage based premium, I see no way of specifying this currently.

**Comment by thadguidry** [comment]
Adding the **Credit Card Processing Fees** use case from W3C Payment Request spec https://w3c.github.io/payment-request/#conditional-modifications-to-payment-request

Fees or any Composite Price #829 (a final price made of multiple prices like http://schema.org/valueAddedTaxIncluded )

**Comment by thadguidry** [comment]
#829 has some work merged for Composite pricing that handles this use case but more abstractly however that is a bit more difficult for Payment Method providers.
