### ISSUE TITLE
What warrants a subtype without extra attributes to exist? e.g.: http://schema.org/BusinessEvent

### ISSUE THREAD

**Issue by gebrits** [schemaorg/schemaorg#928]
I'm wondering what warrants the existence of subtypes without additional attributes (to those already defined on their parenm) such as http://schema.org/BusinessEvent.

Sure BusinessEvent has a somewhat more specific description, but that seems to be a rather thin reason for existence? (along the same reasonsing, say, JapaneseRestaurant as subtype of Restaurant could also exist, etc.)

**Comment by tylerjharden** [comment]
What was your reasoning for closing this, did you end up finding an answer? Would be meaningful to have here for posterity.
