### ISSUE TITLE
Request for suitable classes/properties to represent "school term"

### ISSUE THREAD

**Issue by hubgit** [schemaorg/schemaorg#930]
It would be useful to have schema.org markup for school term dates, e.g. [this page published by Buckinghamshire County Council](http://www.buckscc.gov.uk/education/schools/term-dates/).

The most obvious mapping would be to multiple Events, but there are several problems:
1. The events don't have a specific location (in the above example, the location is essentially "all schools in Buckinghamshire").
2. The event is broken into two halves by a half term holiday - this could be a subEvent of the parent event, but a processor would have to know that the subEvent specifically represents a pause in the parent event.

[Here's what I've got so far](https://gist.github.com/hubgit/3c1455d4e9cb29f7db15), using the existing Event class + properties.

[This page](http://myschoolholidays.com/gb--Bucks) represents the same information as vevent microformats, ignoring the half term holidays.

**Comment by karllhughes** [comment]
Would teacher be relevant for this class @hubgit? I'm interested in other education related standards like courses, classes, sections, grades, etc. but school term would be a start.
