### ISSUE TITLE
Add hoursAvailable as a property of Event

### ISSUE THREAD

**Issue by frankieroberto** [schemaorg/schemaorg#932]
Whilst most Events are likely best specified through a combination of `startDate`, `doorTime` and `endDate`, there are a class of events which may span multiple days, or even weeks or months, where the public may visit at any time during specified hours.

Examples might be an `ExhibitionEvent` open for 3 months between 10:00-18:00 but closed Sundays, a `FoodEvent` (say a Christmas market or beer festival) running over several weeks or a long weekend, or a sporting event like Wimbledon (where the times of each individual match are subject to change, and attendees tend to come and go).

For these, it would be useful to be able to specify opening hours using a `hoursAvailable` property, with `OpeningHoursSpecification` as the value type.

(Note that other types of multi-day event, say the Football World Cup, might be better specified as a single event with multiple `subEvent`s for each match).

(Spun out from the conversation at #445)

**Comment by frankieroberto** [comment]
@danbri any thoughts on this?

**Comment by frankieroberto** [comment]
@danbri can I resurrect this idea? I don't think it’s particularly controversial, and would be very useful for `ExhibitionEvent`s, as well as some other subclasses of `Event`.

**Comment by magicomartinez** [comment]
There have been several attempts to create some type of fix for events with a multi-day schedule. I think the one that's further down the line is #1457 (https://pending.schema.org/Schedule). I think the current proposal would solve for most if not all the cases you mentioned.
