### ISSUE TITLE
feature req: Soft characteristics like atmosphere for FoodEstablishment

### ISSUE THREAD

**Issue by 0xgeert** [schemaorg/schemaorg#933]
Usecase: I'd like to be able to specify things like `cosy, hip, relaxed` on things like `FoodEstablishment` and `LodgingBusiness`. This property could be called `atmosphere` or something.  

Similarly, something like the existing `audience` (better `suggestedAudience`) might make sense for `FoodEstablishment` and `LodgingBusiness` as well.

Thoughts?

**Comment by danbri** [comment]
How common are such properties in sites that describe food establishments?

**Comment by chaals** [comment]
I'm not that convinced about "atmosphere".

But expanding `audience` makes sound sense to me

**Comment by gebrits** [comment]
It's available in one form or another on various sites:

Some examples: 

* Tripadvisor.com Restaurants -> 'Good for' property: with values: `bar scene, business meetings, families with children, romantic, large groups, scenic view, special occasions, ...`
* Tripadvisor.com Hotels -> 'Style' property: with values: `boutique, business, charming, classic, quaint, quiet, romantic, trendy...`
* Yelp Restaurants -> mixed up with some general features, but: `good for kids, good for groups, liked by 20-somethings, liked by 30-somethings, ...`

Based on the above: 

**LodgingBusiness.style / FoodEstablishment.style**

Tripadvisor's `style` is 1-to-1 with the `atmosphere` I had in mind. I.e.: the style/atmosphere of a certain establishment, e.g.: `boutique, business, charming, classic, quaint, quiet, romantic, trendy`

Could probably be closed vocab/enumeration.


**FoodEstablishment.goodFor**

 * what sort of audience / group usually visits said establishment, e.g.: good for kids, good for groups, 20-something, dinner with spouse
  * what type of 'sub-activity' this establishment (especially) caters to, e.g: `business meetings, bar scene, special occasions, ...`

Hard to make this a closed vocab?
Instead allow for arbitrary keyvalue-paris using PropertyValue subtype?

Other properties that might be worth considering:

**FoodEstablishment.amentities**

Pretty much covered on all restaurant-related sites: 
top of head (non-exhaustive): `delivery, outdoor seating, waiter service, take-out, has tv, dogs allowed, open 24 hours`. Open vocab.

Additionally a couple of amenities/features are so often used/ prominently displayed, that they might warrant their own property. Moreover, these properties could potentially be shared with LodgingBusiness and therefore touch on https://github.com/schemaorg/schemaorg/pull/916:

* wifi (including free/paid info)
* parking (including free/paid + offsite/onsite, etc.)
* mealsServed:  exhaustive: `breakfast, brunch, lunch, dinner, late night, (dessert)` closed vocab

**Comment by chaals** [comment]
To expand a bit on my fast comments:

I think `audience` can do what you want for style - family, grandparents, nervous foreign tourists, people with visual disabilities, very large conference groups, people who eat kosher food without gluten, Dan, …

I'm not averse to taking a set of things from tripadvisor/yelp/zagat/booking/lonely planet to get a list. But I am wary of "exhaustive" lists - where does "coffee and a bisucuit" fit in? How do we describe business lounges in airports (which have very strict audiences in one sense that isn't quite the same as a fancy new disco. And I am concerned about the wine problem. Notes of tobacco, cheese, old socks, blackcurrants and cut grass are, like many descriptions of "ambience" not sufficiently shared to expect people to use the same ones.

The amenities like parking and Wifi cover place - volcanoes *do* have parking, and parks have wifi - at least in Talinn, Estonia.

But I'd rather start off using those as `description`.

**Comment by vholland** [comment]
+1 for expanding audience.

I also agree that exhaustive lists are difficult, particularly for nebulous adjectives like "classic", which are going to have very different definitions based on geography.

I am not adverse to the idea of adding more properties for specific categories of descriptions for things like atmosphere, but we will need to allow text.

**Comment by danbri** [comment]
I'd like to agree a structure where people can stick terms like "quaint", but without those needing to be core types/properties/enumerated-values in schema.org. For those who want to work on specific detailed vocabulary for this (and that could include some Google involvement) it is important at least to figure out schema.org's extensibility hooks for dropping in such terms. http://schema.org/additionalProperty might be part of the answer (although I note that we don't seem to have any examples of  additionalProperty being used in the schema.org docs yet).

**Comment by gebrits** [comment]
Yeah, seems `goodFor` could be handled by extending `audience`. 

Moreover I see how `style` doesn't have a clear-cut enumeration and should probably be avoided as explicit property for that reason. 

So how then? 

@danbri: In some oldish discussions I've come across mini-skos / external enumerations. That would allow a user to do exactly that: create a reference to an external controlled vocabulary if I'm not mistaken. Seems a good fit for `style`, etc? Is this still on the agenda and how would `additionalProperty` relate to this? 

Pretty new to schema.org so ymmv, but what if  if `Property` would have an attribute such as `propertyType:URL`, pointing to an external controlled vocabulary. This would allow each `additionalProperty` to be typed. 

Something like: 

		<ul>
			<li itemprop="additionalProperty" itemtype="http://schema.org/PropertyValue">
				<meta itemprop="propertyType" content="http://example.com/style">
				<span itemprop="name">quaint</span>
			</li>
			<li itemprop="additionalProperty" itemtype="http://schema.org/PropertyValue">
				<meta itemprop="propertyType" content="http://example.com/style">
				<span itemprop="name">trendy</span>
			</li>
		</ul>

Thoughts?
