### ISSUE TITLE
Rendering Date without Time??

### ISSUE THREAD

**Issue by Hotkeyharry** [schemaorg/schemaorg#934]
I know that I've done that before, but now I can't render the date without time. Is it no longer posiible, or do I oversee it??  [http://schema.org/Event]
Or is there a new parameter I could not found?
thanx in advance

**Comment by RichardWallis** [comment]
Presuming that you are referring to ```startDate``` and ```endDate```, these are  [ISO 8601 date format](https://en.wikipedia.org/wiki/ISO_8601)  which allow values such as ```2015-12-15``` as well as ```2015-12-15T13:05:00Z```.

**Comment by Hotkeyharry** [comment]
but how to blend out the time??

**Comment by chaals** [comment]
just leave it out and you're fine.

**Comment by chaals** [comment]
i.e. what you have is exactly what you want.

**Comment by Hotkeyharry** [comment]
sorry, but I do not understand....

**Comment by Hotkeyharry** [comment]
;-((

**Comment by vholland** [comment]
To give examples using datePublished:

For a BlogPosting, you might have a specific date and time, so it would look like:

```
{
  "@context": "http://schema.org/",
  "@type": "BlogPosting",
  "datePublished": "2015-12-16T11:30:00-05:00"
}
```

For a news paper article, you might only have the date:
```
{
  "@context": "http://schema.org/",
  "@type": "Article",
  "datePublished": "2015-12-16"
}
```


For a book, you might only have the year:
```
{
  "@context": "http://schema.org/",
  "@type": "Book",
  "datePublished": "2015"
}
```

**Comment by Hotkeyharry** [comment]
Many thanx, the above mentioned items are logical, but I can't find it out in my code. Its within a joomla template in php coded and I can't find the parameter "@type": "Article". Am I blind?
Nevertheless many thanks!!!

```
<div class="dp-upcoming-group" style="border-color:#<?php echo $event->color?>" itemscope itemtype="http://schema.org/Event">
	<div style="clear: both;" /></div>
	     <p itemprop="Date" content="<?php echo $startDate->format('c');?>">
		<?php echo DPCalendarHelper::getDateStringFromEvent($event, $params->get('date_format'), $params->get('time_format'));?>&nbsp;
          <span itemprop="name"><?php echo htmlspecialchars($event->title)?></span>
		
	</p>
	<?php if ($event->locations)
	{
		echo DPCalendarHelperSchema::location($event->locations);
	}

	echo DPCalendarHelperSchema::offer($event);
	?>
	<div style="clear: both;" ></div>
</div>
```
