### ISSUE TITLE
Where to denote the value of types like Duration?

### ISSUE THREAD

**Issue by 0xgeert** [schemaorg/schemaorg#936]
Original Stackoverflow question [here](http://stackoverflow.com/questions/34386194/where-to-denote-the-value-of-a-duration-using-schema-org). 

The answer although seemingly correct seems to point to some ambiguity of the spec:

Verbatim: 

> I must be missing something extremely simple here but: where do I denote the actual duration-value when marking-up an actual schema.org Duration? Duration has a couple of properties (all inheriting from Thing), e.g.: `name`, `additionalType`, etc. but I was sort of expecting there to be a property called value or something. From the above link it says the duration is a quantity and should be of format ISO 8601, but where on earth do I put it?

_The apparent answer_: 

> You should put them directly as the value of the Duration property. 

Although this seems like a straightforward answer, it doesn't appear logical at all to me. After all [Duration](https://schema.org/Duration) is defined as a Thing. To me this must mean that Duration is to be marked-up as a structured object instead of just a value. After all it has all the inherited properties of Thing that must go somewhere if needed. 

Perhaps the problem is better illustrated with an example. Take the [Invoice](http://schema.org/Invoice) example in JSON-ld, where `billingPeriod` is a simple string value which is seemingly correct: 

```
   {
      "@context": "http://schema.org/",
      "@type": "Invoice",
      "description": "January 2015 Visa bill.",
      "url": "http://acmebank.com/invoice.pdf",
      "broker": {
        "@type": "BankOrCreditUnion",
        "name": "ACME Bank",
      },
      "accountId": "xxxx-xxxx-xxxx-1234",
      "customer": {
        "@type": "Person",
        "name": "Jane Doe"
      },
      "paymentDueDate": "2015-01-30",
      "minimumPaymentDue": {
        "@type": "PriceSpecification",
        "price": 15.00,
        "priceCurrency": "USD"
      },
      "totalPaymentDue": {
        "@type": "PriceSpecification",
        "price": 200.00,
        "priceCurrency": "USD"
      },
      "billingPeriod": "2014-12-21/P30D",
      "paymentStatus": "http://schema.org/PaymentDue"
  }
```

If we wanted to add extra properties to `billingPeriod` which is type Duaration, we probably could as follows: 

```
  {
      "@context": "http://schema.org/",
      "@type": "Invoice",
      "description": "January 2015 Visa bill.",
      "url": "http://acmebank.com/invoice.pdf",
      "broker": {
        "@type": "BankOrCreditUnion",
        "name": "ACME Bank",
      },
      "accountId": "xxxx-xxxx-xxxx-1234",
      "customer": {
        "@type": "Person",
        "name": "Jane Doe"
      },
      "paymentDueDate": "2015-01-30",
      "minimumPaymentDue": {
        "@type": "PriceSpecification",
        "price": 15.00,
        "priceCurrency": "USD"
      },
      "totalPaymentDue": {
        "@type": "PriceSpecification",
        "price": 200.00,
        "priceCurrency": "USD"
      },
      "billingPeriod": {
        @type: "Duration",
        @value: "2014-12-21/P30D",
        description: "The billing period"
      },
      "paymentStatus": "http://schema.org/PaymentDue"
  }
```

That's all fine, but that's rather implicit. Where does it state that `Duration` uses a `@value`-property to markup it's data? Or looked at it differently: is `@value` also valid to use on `totalPaymentDue` (type PriceSpecification)? If so, what can the value be? I'm sure the answer is _no_, but this can't be derived from the specification at the moment.

It seems to me that the above needs to be made more explicit in the documentation: for each Type, document the (now implicit) `value` property if it's used for said Type?

Alternatively, Duration could perhaps just be a Datatype instead. I.e.: a subtype of String, just like URL. This would make it explicit to just put in a string value, of format as specified by the subtype Duration, e.g.: ISO8601. 

This doesn't only apply to Duration btw. [Quantity](https://schema.org/Quantity), and more have the same problem. 

Thoughts?

**Comment by RichardWallis** [comment]
This does seem a little confusing.

It raises a couple of question.  Firstly, if a formatted string is sufficient, why do we need [Quantity](http://schema.org/Quantity) and its subtypes.  If we do need them, I for one would expect Quantity to have a 'value' property.

Whatever - some examples would help.

**Comment by mfhepp** [comment]
I think you can safely use QuantitativeValue for both Duration and Quantity. The type of value will then be encoded by the unit code.

**Comment by vholland** [comment]
I would like to see us move to QuantitativeValue, but I realize that it is more for authors to write than "7 km". At least duration has ISO 8601 to describe how to format the string, but the others can be a bit of a mess.

**Comment by mfhepp** [comment]
Note that you can always put less-structured values into the name or description properties of the QuantitativeValue.
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp
