### ISSUE TITLE
JSON-LD export missing property definitions...?

### ISSUE THREAD

**Issue by arpieb** [schemaorg/schemaorg#945]
I'm experimenting with using the JSON-LD export to automate code generation of the entire schema.org data model, but have noticed that the properties for each class are missing from the JSON-LD export.  Am I missing something, or was this intentional?  Really hoping I don't have to resort to parsing the RDFa source file...

Thanks!

**Comment by gebrits** [comment]
Here's a JSON-doc that should be kept up-to-date (see [discussion](
https://github.com/indexzero/node-schema-org/issues/4))

http://schema.link.fish/downloads/all.json

**Comment by jaygray0919** [comment]
A brilliant piece of work!

How did you generate this?

  http://schema.link.fish/downloads/all.json

Dan Brickley published a version using a structure like this:

---

{

"@context": {

    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",

    "schema": "http://schema.org/",

    "rdfs:subClassOf": { "@type": "@id" },

    "name": "rdfs:label",

    "description": "rdfs:comment",

    "children": { "@reverse": "rdfs:subClassOf" }

  },

 

"@type": "rdfs:Class",  "description": "The most generic type of item.",

"name": "Thing",

"@id": "schema:Thing",

"layer": "core",

"children": 

  [

    {

    "@type": "rdfs:Class", "rdfs:subClassOf": "schema:Thing",  "description": "An action performed by a direct agent and indirect participants upon a direct object...",

    "name": "Action",

    "@id": "schema:Action",

    "layer": "core",

    "children":

---

 

I have the source file but cannot find the thread where he published his version.

 

However, we have a processor that depends on the structure that you present.

Hence my interest in how you generated your structure (perhaps from an RDF or RDFa implementation)?

If manually produced - thank you for this implementation as a target model.

If generated with some level of automation from a source file, would like to know how you did it.

/jay

**Comment by gebrits** [comment]
@jaygray0919 : best bet is to ask @janober in the thread I pointed to. He / his company generates said json

**Comment by RichardWallis** [comment]
Closed and noted for future reference,
