### ISSUE TITLE
Should "sportsEvent" really be a sub property of "location"?

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#946]
[`ExerciseAction`](http://schema.org/ExerciseAction) can have the [`sportsEvent`](http://schema.org/sportsEvent) property (which expects a [`SportsEvent`](http://schema.org/SportsEvent) as value):

> A sub property of location. The sports event where this action occurred.

But [`location`](http://schema.org/location) expects only `Place`/`PostalAddress`/`Text`, not `Event` or `SportsEvent`.

Is this intentional? I would have assumed that sub properties should always expect a subset of the possible values for their super property.

Shouldn’t `sportsEvent` be a sub property of [`event`](http://schema.org/event) (which is from the parent type [`PlayAction`](http://schema.org/PlayAction))?

> Upcoming or past event associated with this place, organization, or action.

(Or … do we need `sportsEvent` at all if `event` could be used instead?)

**Comment by kevinSuttle** [comment]
It does seem like event should have a location property, and not the other way around.

**Comment by vholland** [comment]
+1 to making sportsEvent a sub-property of event. Although, we may want to deprecate sportsEvent altogether.

**Comment by agmckee** [comment]
Same with exerciseCourse and foodEvent, both sub-properties of location.
