### ISSUE TITLE
How to handle multiple Product / Offer options?

### ISSUE THREAD

**Issue by tahpot** [schemaorg/schemaorg#949]
How best should options for products be handled? For example, a product may have three groups of options:
- Size (S, M, L)
- Color (Red, Green, Blue)
- Material (Felt, Fur, Cotton)

Each of those options are associated with a parent product (eg: Jacket), but each have different inventory levels and prices.

I notice that color and dimensions are a property of Product, while price is a property of Offer.

Is it expected to create a new Product for each of these combinations, each with a single offer? If so, how then should they be grouped as a single Product with distinct options?

I notice there is a single category property, but that seems to only support hierarchy of categories, not multi-dimensional options.

**Comment by radusi** [comment]
@tahpot : what about this ?
 http://blog.heppresearch.com/2015/07/23/schema-org-product-variants-with-different-prices/

**Comment by tahpot** [comment]
Thanks radusi, that's a good start.

However I also want to semantically add the extra information such as "Size, Color, Material" to the Product.

Something like the following (see offerOptions property added to the example):

```
{
    "@context" : "http://schema.org",
    "@type" : "Product",
    "description" : "The Hepp Smart Watch is a unique wristwatch.",
    "name" : "Hepp Smart Watch",
    "offerOptions": {
        "size": ["S","M","L"],
        "color": ["Red", "Blue", "Green"],
        "material": ["Felt", "Fur", "Cotton"],
    }
}
```

Each of those offerOption variants should then have a specific offer attached to them.

**Comment by tahpot** [comment]
I should also point out that the weight and dimensions is attached to the product, rather than the offer which is also problematic. 

In the example above the small felt jacket will have different weight and dimensions to the large fur jacket.
