### ISSUE TITLE
extend range of isBasedOnUrl to Thing (or CreativeWork); rename to isBasedOn (or basedOn?)

### ISSUE THREAD

**Issue by sballesteros** [schemaorg/schemaorg#950]
See: https://lists.w3.org/Archives/Public/public-vocabs/2013Sep/0189.html
Somewhat related: https://github.com/schemaorg/schemaorg/issues/579

**Comment by sballesteros** [comment]
see also #975

**Comment by danbri** [comment]
Re-opening: should isBasedOnUrl have become basedOn instead of isBasedOn?

**Comment by danbri** [comment]
Ok, I looked it up. We have lots of relational properties with names beginning with "is*", so this is ok.

* isRelatedTo, isSimilarTo,  isVariantOf, isConsumableFor, isBasedOnUrl, isPartOf, isAccessoryOrSparePartFor (relational)
* isAccessibleForFree,isGift, isFamilyFriendly, isLiveBroadcast (boolean valued)

I think we're ok.
