### ISSUE TITLE
http://schema.org/VisualArtwork or http://schema.org/Thing/CreativeWork/VisualArtwork

### ISSUE THREAD

**Issue by eriam** [schemaorg/schemaorg#952]
Hello schema people

I am wondering if it makes sense to store the full hierarchy in the type of an object ?

I built an small software that spawns my objects from the store and I it's way easier to spawn them when their type match the full name of the class instead of searching in the class hierarchy the matching sub class.

So first, is it too much not compliant to store types like that:

http://schema.org/Thing/CreativeWork/VisualArtwork

Instead of 

http://schema.org/VisualArtwork

And then would it be too much not compliant to have some kind of redirection on the website ?

Does that make any sense ? I know Chewbacca is a wookie living on Endor but well .. 

Thanks

Eriam

**Comment by danbri** [comment]
The correct form is http://schema.org/VisualArtwork

Types sometimes have multiple supertypes, and we are often adding new types, and also occasionally changing the supertypes. It is better to just point using the short URL.

If you can write software that generates URLs like http://schema.org/Thing/CreativeWork/VisualArtwork
it should be trivial to create a function that takes the final string "VisualArtwork" and uses it to compose the correct URL.
