### ISSUE TITLE
schema.org/PublishAction

### ISSUE THREAD

**Issue by callahanchris** [schemaorg/schemaorg#953]
The use case I have is as follows:

A `Person` submits a `CreativeWork` to a `Periodical` with the intent of publication. If the submission is successful, this would culminate in a `PublicationEvent`, and the `Periodical` would be included in the `isPartOf` property of the `CreativeWork`. However, the outcome is unclear during the submission process, yet I would still like to include information about the `Periodical` on the `CreativeWork`.

The ideal choice seems to be to add a `potentialAction` property to the `CreativeWork` with `@type: PublishAction`, but the `PublishAction` class is not currently in schema.org.

This is just one use case, but I think that publishing things on the Web is a common operation that it is useful to describe.

Happy to make a PR for `PublishAction` if this makes sense!

**Comment by darobin** [comment]
+1
