### ISSUE TITLE
Proposal: Allow Review, Rating, and/or aggregateRating as properties for Seat

### ISSUE THREAD

**Issue by effisk** [schemaorg/schemaorg#956]
I'm very new to this, I apologise if my suggestion is not formatted properly.

I am trying to review seats within a theater. Each seat is identified by a row and a number.
Here is an example of what I am suggesting (I am using aggregateRating and Review in this example):

```
<div itemscope itemtype="http://schema.org/Seat">
    <div itemprop="seatNumber">2</div>
    <div itemprop="seatRow">AA</div>
    <div itemprop="seatSection">Orchestra</div>
    <div itemprop="alternateName">Orchestra AA2</div>
    <div itemprop="AggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <div itemprop="ratingValue">3.5</div>
        <div itemprop="reviewCount">25</div>
    </div>
    <div itemprop="review" itemscope itemtype="https://schema.org/Review">
        <span itemprop="reviewRating" itemscope itemtype="https://schema.org/Rating">
            <meta itemprop="ratingValue" content="4"/>
        </span>
        <meta itemprop="datePublished" content="2016-01-10"/>
        <strong itemprop="name">Review title</strong>
        <p itemprop="reviewBody">Here goes the review</p>
        <em itemprop="author">Author Name</em>
    </div>
</div>
```

**Comment by mfhepp** [comment]
Thanks for this! However, I am inclined against this proposal, because the most of such data is useful only in a specific context (e.g. a particular event or type of event). I do not think it makes sense to rate a single seat in a theater, and I doubt there are Web sites that currently publish a lot of such granular information without linking it to a particular event, if at all.

**Comment by effisk** [comment]
There are cases where this would be useful. I'm thinking Broadway and West End venues for instance where shows can run for decades in the same venue, and there are websites that publish that kind of information, such as seatplan.com

**Comment by mfhepp** [comment]
Ok, I did not know http://www.seatplan.com/, but are there many such sites? My rule of thumb for schema.org core elements is that they are applicable to a significant number of Web sites, like at least 10 k sites globally Everything else is better put in an extension.

**Comment by effisk** [comment]
There are not a lot of these websites yet - definitely less than 10k sites. I'll have a look at extensions. Thank you.
