### ISSUE TITLE
feature req: Organization officialUrl 

### ISSUE THREAD

**Issue by 0xgeert** [schemaorg/schemaorg#959]
To me, it would make sense to have a property `officialUrl` or `website` for Organization. 

This property would carry more semantic meaning then having to mark it up in `sameAs`.

Thoughts?

**Comment by mfhepp** [comment]
What would be the difference to schema:url?
Can't a client infer that this is the official URL simply from the provenance of the data?

I mean, if anybody can make an officialUrl statement about anybody, this opens all doors for spam and abuse, so a client will have to filter by domain authority etc. anyway. But then it can as well simply use the url property.

**Comment by Dataliberate** [comment]
I agree with Martin.  schema:url should be sufficient.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by gebrits** [comment]
perhaps I'm mistaken but, say site X uses schema.org to markup Local
businesses, such as the 21club in NY.
Afaik, LocalBusiness:url is meant to denote the url of the LocalBusiness on
site X itself correct?

I was looking for a way to set the official url of the LocalBusiness, here
http://www.21club.com/.

**Comment by Dataliberate** [comment]
In that case the URL of the LocalBusiness would be schema:url >
http://www.21club.com/web/onyc/bar_room.jsp

Then its parent organisation (LocalBusiness>schema:parentOrganisation) and
its schema:url would be http://www.21club.com/

Another possible approach could be to define schema:Brand for the chain of
restaurants and use its logo & url values

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw
