### ISSUE TITLE
PropertyValue JSON-LD example fails to validate

### ISSUE THREAD

**Issue by purewebnz** [schemaorg/schemaorg#966]
The JSON-LD sample for https://schema.org/PropertyValue has an example of multiple exifData properties for a photo. It fails validation using the Google Structured Data Testing tool due to the lack of commas between these properties. Adding the commas allows it to validate, however the validator only extracts the first exifData property, ignoring the subsequent ones. 

What is the correct syntax for providing multiple exifData or additionalProperty properties in JSON-LD? Typically this type of data would use an array, i.e. additionalProperties?

**Comment by vholland** [comment]
The example should read:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ImageObject",
  "author": "Jane Doe",
  "contentLocation": "Puerto Vallarta, Mexico",
  "contentUrl": "mexico-beach.jpg",
  "datePublished": "2008-01-25",
  "description": "I took this picture while on vacation last year.",
  "name": "Beach in Mexico",
  "exifData": [
    {
      "@type": "PropertyValue",
      "name": "Exposure Time",
      "value": "1/659 sec."
    },
    {
     "@type": "PropertyValue",
      "name": "FNumber",
      "value": "f/4.0"
    },
    {
      "@type": "PropertyValue",
      "name": "MaxApertureValue",
      "value": "2.00"
    },
    {
      "@type": "PropertyValue",
      "name": "Metering Mode",
      "value": "Pattern"
    },
    {
      "@type": "PropertyValue",
      "name": "Flash",
      "value": "Flash did not fire."
    }
  ]    
}
</script>
```

**Comment by vholland** [comment]
I updated the example in pull request #966.

**Comment by purewebnz** [comment]
Perfect, thanks.

**Comment by danbri** [comment]
Thanks! Merged for next release.
