### ISSUE TITLE
Expand the sponsor property

### ISSUE THREAD

**Issue by EricAxel** [schemaorg/schemaorg#971]
Hi all,

Apologies if I did this out of order (I'm a long time listener; first time caller here). I've already issued a pull request -- [#962](https://github.com/schemaorg/schemaorg/pull/962) -- for this, but saw in another thread that the preferred method is to create a new, corresponding issue first. Here then, is the issue...

I'm proposing to expand the range and domain of [sponsor](https://schema.org/sponsor), currently described as "Sponsor of the study." where 'study specifically refers to a [MedicalStudy](http://schema.org/MedicalStudy). In my proposal, the expanded comment defining the property is:
"A person or organization that supports a thing through a pledge, promise, or financial contribution. e.g. A sponsor of a Medical Study or a corporate sponsor of an event."

I propose that the domain be expanded from [MedicalStudy](http://schema.org/MedicalStudy) to ALSO include: [Person](http://schema.org/Person), [Event](http://schema.org/Event), and [Organization](http://schema.org/Organization). 

I propose that the range be expanded to include [Person](http://schema.org/Person), adding to [Organization](http://schema.org/Organization), which is there now.

I've created some examples in Microdata, RDFa, and JSON-LD covering the following situations:

* an Event sponsored by an Organization
* a Person sponsored by an Organization
* a Person sponsored by a Person
* an Organization sponsored by an Organization

These examples are in the file "[sdo-sponsor-examples.txt](https://github.com/EricAxel/schemaorg/blob/e08db43576a873cc7b17bacc5793a3589a88b041/data/sdo-sponsor-examples.txt)."

I can imagine there may be other uses for sponsor (CreativeWork instances -- such as an [episode](https://schema.org/Episode) of a media program), but am putting this forth as a start.

Thanks in advance for any feedback,
--Eric

**Comment by danbri** [comment]
I think we should do this and the pullrequest is already merged. 

http://webschemas.org/sponsor

@twamarc - please confirm it makes sense from the medical vocab perspective.

**Comment by danbri** [comment]
Done! Thanks...
