### ISSUE TITLE
JSON Graph?

### ISSUE THREAD

**Issue by kevinSuttle** [schemaorg/schemaorg#973]
https://github.com/jsongraph/json-graph-specification

**Comment by Dataliberate** [comment]
What are you proposing?

**Comment by danbri** [comment]
It sounds like a question, along lines of "how does schema.org relate to this (and to JSON schemas...)". @kevinSuttle  ?

**Comment by kevinSuttle** [comment]
Yes, my apologies. I should have taken the time to clarify.

**Comment by alex-jansen** [comment]
no further work needed here other than noting that the linked github project is a way of representing graph structures, it does have no relation with Schema.org currently.
