### ISSUE TITLE
Add regionsNotAllowed to MediaObject?

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#974]
The type http://schema.org/MediaObject has the property http://schema.org/regionsAllowed for specifying the countries where the media object is available. Sometimes it is easier to say where the object is not allowed.

Shall we add http://schema.org/regionsNotAllowed?

**Comment by danbri** [comment]
Allowed by whom?

**Comment by vholland** [comment]
The publisher (who ultimately needs to enforce this).
