### ISSUE TITLE
TelephoneAction

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#977]
Schema.org has many abstract actions, but nothing that translates directly to "call this person, organization, or number". We should add a TelephoneAction as a subtype of CommunicateAction. We should also extend the domain for the http://schema.org/telephone property to include the new TelephoneAction.

**Comment by danbri** [comment]
What is a telephone? :)

**Comment by danbri** [comment]
CommunicateAction is very broad as a container. If it is it important to handle the case of 2-way realtime audio via telephone numbers, should we also somehow cover various other realtime 2-way (or n-way) calling technology (audio/video)?

**Comment by vholland** [comment]
That makes sense. A CommunicateAction with a "tel:" link would work for the phone case, but ideally, we could support realtime communication links via some other connection protocol.

**Comment by vholland** [comment]
Closing until a more urgent use case arises.
