### ISSUE TITLE
Accept header q paramter parsing issues.

### ISSUE THREAD

**Issue by davidlehn** [schemaorg/schemaorg#978]
https://github.com/digitalbazaar/jsonld-cli/issues/2 exposed a problem when a request is made similar to:
`curl -v -H "Accept: application/ld+json; q=1.0, application/json; q=0.8, text/html; q=0.6, application/xhtml+xml; q=0.6" http://schema.org/`
The `Accept` header parser in `handleHomepage` at https://github.com/schemaorg/schemaorg/blob/sdo-deimos/sdoapp.py#L880 doesn't handle the space before the `q` param and returns text/html.
https://tools.ietf.org/html/rfc7231#section-5.3.2

The q value parsing is also incorrect. For example, `q=1` and `q=0` don't work.
https://tools.ietf.org/html/rfc7231#section-5.3.1

I haven't setup an instance to test with but at least the whitespace issue could likely be handled with `\s?` usage:
```python
ah = re.sub( r"\s?;\s?q=\d?\.\d+", '', ah).rstrip()
```

**Comment by danbri** [comment]
Thanks, filed as a site codebase todo.

**Comment by RichardWallis** [comment]
Moved to mea issue for all python/site tool issues #3
