### ISSUE TITLE
schema org applied to visualisations: proper markup and valid workaround to describe dynamic charts

### ISSUE THREAD

**Issue by gg4u** [schemaorg/schemaorg#979]
Hello,
1. any plan for applying schema to visualisations, therefore on SVG?
2. from http://bib.schema.org/Atlas
   I read _maps, charts, plates or tables, physical or in media form illustrating_ **any subject.**
   Is it a proper descriptor for objects representing "knowledge maps" and "references" and other media?
   If not, which?
3. How to specify further and which best practice to describe a visualisation that include SVG object:
4. Describe on the <div> container + in <html> ?
5. how to create an itemID for an object which is new?
   E.g. in this example http://bib.schema.org/Atlas the snipper show a book, I would like to create an ID for my own object
6. Is it valid to include descriptors in elements with css display:none property?
   The idea is to provide a description which can be read from bots, while the objective of the description would be explained by the visualisation (that is, the user have a "visual" description of elements in SVG rather than "textual of elements for bots").

**Comment by danbri** [comment]
This is not an area that has had much attention / discussion. I know that SVG historically supported inline metadata, but I don't know much about how that has been used in practice. Do you have any overview or data on the current conventions, issues, needs etc?

**Comment by gg4u** [comment]
Yes I would like to understand a best practice to describe content in a page structures like:
```<html>
<div id="knowledge-map-here-will-load-ajax-visualisation-about-a-topic">
<svg id="see-example-DNA">
```

Each topic, or entity, carries its own visualisation that display its context.
Example:
<img width="250" alt="screen shot 2016-02-04 at 9 30 12 am" src="https://cloud.githubusercontent.com/assets/284214/12809769/079d8eb6-cb22-11e5-9091-2fd0cf71c1e7.png">

1# Need
a. Is "Atlas" a proper markup to describe this type of content? 
If not, which rationale to choose a proper convention?

2# Tech Issues:
Visualisations are loaded via ajax and done in SVG - If I cannot describe SVG elements, I would like to include a markup in the page to help engines understand what the object is about.

a. Better to included markup in html, meta, or the wrapping div tag?
b. Is it a good practice to include an HTML list, as redundancy of elements in SVG , and hide the list to the user ? 
I thought the search engine could go through it.

As example about the picture above, something like:
```
<div id="visualisation"><svg></svg></div>
<div  itemscope itemtype="http://schema.org/Atlas???"  id="listing-elements-in-visualisation" style="display:none">
    // this block is hidden to user and meant for SEO
    // add schema markup for each element in visualisation
    // itemprop="name" DNA sameAS="wikipedia.org/DNA"
    // itemprop="name" GENE sameAS="wikipedia.org/Gene"
</div>
````

So far any entity I display could point to wikipedia, I wonder if it is good practice or could be considered as a "copy" by a search engine and penalise the site. 

#3 Conventions
In https://bib.schema.org/Atlas
I read - "Usage: Fewer than 10 domains"
better to use a selector vastly used or poorly used?
where to look for which domains are using it?

4# Creating an ItemID for each visualisation?

In  https://bib.schema.org/Atlas and itemID is used to point to a book.
```
<div itemscope itemtype="http://schema.org/Atlas" itemid="http://www.worldcat.org/oclc/41310554">
        <h1 itemprop="name">Atlas of the World</h1>
        <h2 itemprop="alternateName">National Geographic atlas of the world</h2>
        <div>Publisher: <span itemprop="bookEdition">7th ed.</span></div>
        <div>Publisher: <span itemprop="publisher">National Geographic Society</span></div>
        <div>Published: <span itemprop="datePublished">1999</span></div>
</div>
````

Is it possible and meaningful to create and itemID for each visualisation?
