### ISSUE TITLE
Provide New Local Business Type "schema.org/autohailrepair"

### ISSUE THREAD

**Issue by BrandenDunn** [schemaorg/schemaorg#988]
There is a lack of clarity between Auto Repair and Auto Hail repair please make a new schema type for this business.

**Comment by danbri** [comment]
What exactly *is* "Auto Hail repair" ? This is not a phrase I am at all familiar with - is it purely about fixing damage caused to cars by icy [hailstone](https://en.wikipedia.org/wiki/Hail) weather? 

My inclination would be to say that this is a specialized form of Auto Repair, and that it is too detailed for us to create a dedicated type for this specific kind of repair activity. There are many many things that can be repaired (or insured) w.r.t. damage to cars and other vehicles. And for that matter many kinds of thing that can be damaged by hail (or wind, lightning, water, ...).

**Comment by BrandenDunn** [comment]
Yes this is a 5 billion dollar a year industry. Its different than auto body repair  and it is not auto repair because that implies tire changes to google.  Auto Hail Repair is more specific and much needed. 

Think of it as the missing third in the way cars are repaired. If there is Auto Repair (tire Changes, Mechanical) and Auto Body Repair (crashed cars, painting)

 Auto Hail Repair is fixing hail damaged cars with Paintless Dent Repair which uses no paint or anything of the sort. The new category should be Auto Hail Repair or Paintless Dent Repair one of the two.

Thank you

**Comment by danbri** [comment]
I'm not quite following "and it is not auto repair because that implies tire changes to google"; from everything you say it is a more specific kind of automobile repair. When I search "auto repair" on Google, the word "tire" hardly appears. And schema.org is not Google; we should be guided by how things are in the world and how the concept is generally understood, rather than by the links that happen to show up in Google searches right now.

I can't find any writeups (e.g. Wikipedia) about this as a distinct industry - where does the "5 billion" figure come from?

**Comment by stuartrobinson** [comment]
I think another term for this is "paintless dent repair" (PDR) -- e.g.,

https://www.statefarm.com/claims/resources/auto/paintless-dent-repair
http://www.napdrt.org/pdr_faq.htm

But I don't see how this is different from auto body repair.

**Comment by BrandenDunn** [comment]
First thank you for your time. When I said auto repair implies tire changes to google I mean that Auto Repair involves mechanical repairs that are not related to the body of the car (transmissions, tire changes, oil changes, brake pads, engine work etc.) . Auto Body Repair involves exactly what it describes, body repairs on a car  that are caused by accidents. In the ever evolving world of semantic mark-up we are trying to be specific in order to show google what each website is about. 

This is a discrepancy that is worth expanding on because it is unique and neither category fully describes what is happening. The future of google for SEO is semantic markup and website content and I think we can both agree with that. Therefore, a local business category for either “Auto Hail Repair” or “Paintless Dent Repair” is much needed to clarify this issue. If “Real Estate Agent” and “Recycling Center” are categories I’m not sure why we can’t work together to make “Auto Hail Repair”  a category of local business 

Paintless Dent Repair is the industry and it involves repairing dents on cars with specialized tools. Research into this term will show you that it is used worldwide even though it is an emerging industry. However, most pointless dent repair is used in cities where destructive hail storms damage cars and instead of repainting the car as an auto body repair shop would do, the cars are fixed with paintless dent repair. I am in this industry and the term people search for the most is “auto hail repair”. In Denver where I am from there has been hail storms over the past two years that caused 600 million in damage and the city was under national catastrophe with insurance departments. In one city and the entire midwest and south of the US are affected similarly every year. 5 billion is a conservative estimate based on last year.

**Comment by BrandenDunn** [comment]
It is separate than auto body repair because no body repairs are being done. Body repairs are a separate industry involving painting, welding, grinding, panel replacement etc.

**Comment by BrandenDunn** [comment]
Hello

just wondering if you came to a conclusion on the new category I suggested

**Comment by mfhepp** [comment]
Actually, I think your needs can be well covered using http://www.productontology.org/doc/Paintless_dent_repair in combination with existing schema.org elements.

This should work perfectly for your case:
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>An offer to sell a / some Paintless_dent_repair</title>
</head>
<body>
<div itemscope itemtype="http://schema.org/Service">
    <link itemprop="additionalType" href="http://www.productontology.org/id/Paintless_dent_repair" />
    <span itemprop="name">.. a short name for the object ...</span>
    Product description: 
    <span itemprop="description">... a longer description ...</span>
    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
        <span itemprop="price">$19.99</span> 
    </div>
</div>
</body>
</html>
```
