### ISSUE TITLE
Usability/quality issues with Offer (price, gtin, ...)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#99]
http://schema.org/Offer
http://schema.org/price

(originally relayed from a  colleague, Matthias)
# Fixed already:
- [x] price field, can we say something clearer about localization (use of €, $ symbols, '.', ',' for decimal vs 1000s, @content?). e.g. $ is ambiguous 
- [x] we could point out '.' vs ',' are ambiguous (http://en.wikipedia.org/wiki/Decimal_mark#Hindu.E2.80.93Arabic_numeral_system).
- [x] Maybe we should we just say "without using '.' or ',' for 1000s", and using '.' for decimals? We can also note that both Microdata and RDFa allow localised human-facing markup to say one thing, but an equivalent decimal value can be written in the @content="..." attribute.
- [x] gtin. we should link to http://www.gs1us.org/about-gs1-us/media-center/press-releases/gtin-validation-guide. 
- [x] a way of indicating the main offer in a page ('mainEntity' use case?) would be useful. Fixed in #301" 
## Open...
- [ ] can we say something about whether tax is included in price?
- [ ] also consider adding examples or shortcut properties that show how to describe related products via their gtin.
- [ ] show a product example for mainEntityOfPage - the problem is that a merchant's web-site contains multiple offers, the "main" one and typically related product/offers, but also offers for the same product by different sub-sellers." e.g. http://www.walmart.com/ip/Teenage-Mutant-Ninja-Turtles-2014-Blu-ray-Gift-Set-With-Figurines-Walmart-Exclusive-Widescreen/38234327
- [ ] see also notes below...

**Comment by danbri** [comment]
I've left this overly general, semi-meta issue open for sdo-gozer. What specifics can we easily address for this current looming release? Other aspects need breaking out into their own issues and filing against Q2.

I'm aware also that a related question about area pricing - see  https://github.com/schemaorg/schemaorg/wiki/PricingByArea - was only partially answered.

/cc @mfhepp

**Comment by mfhepp** [comment]
@danbri Thanks for CCing me. I admit I did not see this issue so far. Will try to address this for the post-gozer release.
Martin

**Comment by danbri** [comment]
Yes, I don't see anything leaping forward to be included in the next release

**Comment by gmackenz** [comment]
@danbri Should we close this issue as obsolete?

**Comment by gmackenz** [comment]
Thanks for the quick response Dan, I am slowly checking all the long outstanding issues with the originators. Apologies but I lack the admin rights to be able close this issue myself.

**Comment by MatthiasWiesmann** [comment]
Closing this issue then.
