### ISSUE TITLE
countryOfOrigin should be applicable to Product, CreativeWork at least.

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#991]
Let's try to align more closely with GS1's use for products at http://gs1.org/voc/countryOfOrigin ("Code indicating the country of origin of the product.").

Currently http://schema.org/countryOfOrigin seems rather wasted, "The country of the principal offices of the production company or individual responsible for the movie or program.". It should be possible to preserve the original usecase while making this property useful on a greater range of things.
Currently we expect it on: Movie, TVEpisode, TVSeason, TVSeries.

Suggestion: "The country of origin of something, including products as well as creative works such as movie and TV content. In the case of TV and movie, this would be the country of the principle offices of the production company or individual responsible for the movie. For other creative works [ .... TODO].

Issues:
- what should we say about other creative works? 
  - http://schema.org/contentLocation "The location depicted or described in the content. For example, the location in a photograph or painting."
  - http://schema.org/locationCreated "The location where the CreativeWork was created, which may not be the same as the location depicted in the CreativeWork."
- For complex or compound products, what to say? 
- If multiple countries are applicable, is it reasonable to expect the property to be repeated?

**Comment by mgh128** [comment]
Thanks for suggesting that http://schema.org/countryOfOrigin be generalised to apply also to products.
In the GS1 vocabulary, we define three related properties:

http://gs1.org/voc/countryOfOrigin   (similar but applies to a gs1:Product (similar to a schema:Product))
http://gs1.org/voc/countryOfLastProcessing
http://gs1.org/voc/countryOfAssembly

All three properties may be useful for complex or compound products consisting of ingredients or components from multiple origins.  
In our JSON-LD markup, we're assuming that gs1:countryOfLastProcessing takes a single value but gs1:countryOfOrigin or gs1:countryOfAssembly may take multiple values of gs1:Country (similar to schema:Country) in an array.

**Comment by Dataliberate** [comment]
+1 to generalising the use of the property.

For CreativeWork http://schema.org/contentLocation  should not be
influenced, I think the current description is fine.

http://schema.org/locationCreated is a little more tricky - noting it
expects a Place.  Having said that it is totally logical that
locationCreated could be “Paris” and countryOfOrigin “France”.

Looking at this and what GS1 does, it kind of implies that Product would
also benefit from a placeOfProcessing/Manufacture/Assembly or similar.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by vholland** [comment]
Sounds good to me.

**Comment by gmackenz** [comment]
I think this still would be a good idea in 2021 to generalize this property at least onto the proposed [Product](https://schema.org/Product) and [CreativeWork](https://schema.org/CreativeWork).

**Comment by mgh128** [comment]
I agree, just as I did 5 years ago (  https://github.com/schemaorg/schemaorg/issues/991#issuecomment-185286334 )

So my question to @danbri  is whether there is any known obstacle or opposition to making this generalisation of the domain for this property and also whether the related properties in the GS1 Web vocabulary should also be merged into the core of schema.org.

**Comment by danbri** [comment]
Let's do it. I've made the change to countryOfOrigin. 

The definition is slippery given the range of things this could be applied to. I've made a start:

```
:countryOfOrigin a rdf:Property ;
    rdfs:label "countryOfOrigin" ;
    :domainIncludes :CreativeWork, :Product, :Movie,
        :TVEpisode,
        :TVSeason,
        :TVSeries ;
    :rangeIncludes :Country ;
    rdfs:comment "The country of origin of something, including products as well as creative works such as movie and TV content. I

In the case of TV and movie, this would be the country of the principle offices of the production company or individual responsible for the movie. For other kinds of [[CreativeWork]] it is difficult to provide fully general guidance, and properties such as [[contentLocation]] and [[locationCreated]] may be more applicable.

In the case of products, the country of origin of the product. The exact interpretation of this may vary by context and product type, and cannot be fully enumerated here." .
```

For countryOfLastProcessing and countryOfAssembly, I'm queing these via Pending, and taking a lead from the GS1 definitions.

@mgh128 the definitions aren't all exactly the same, but they're pretty close - should we express formal mappings somehow?

**Comment by danbri** [comment]
Drafts on work-in-progress editorial site:

 * https://webschemas.org/countryOfOrigin
 * https://webschemas.org/countryOfAssembly # just fixed a tiny typo, will be in the next push
 * https://webschemas.org/countryOfLastProcessing

The wording could be polished, e.g. https://webschemas.org/countryOfLastProcessing text (adapted from gs1's) "The place where the item (typically Product) was last processed and tested before importation." doesn't make quite so much sense if the product was never imported anywhere. @mgh128 - perhaps we could align some common text? Is the property to be ignored unless it is used on an import? does it mean /countryOfLastPreImportProcessing ?

**Comment by veganline** [comment]
https://github.com/schemaorg/schemaorg/issues/991#issuecomment-185307663

I very much hope that country of origin, or similar tags, 

- part of https://schema.org/Product
- acceptable if tagged as https://schema.org/Brand

Two reasons

(1) If you sell a product like pants from a wholesaler, that's about the only information they dare divulge about the origin because their larger customers might cut-out the middle man and go direct to the factory
(2) Country of origen could be important for tariff declarations. That's why they often tell you or sometimes volunteer the information
(3) Coke v. Pepsi is frankly not important compared to China v. Norway. There is a lot of useful information that a retailer can find linked to the country of origin that could be used to promote human rights democracy and welfare systems, if buyers agree and want to buy products from Norway not China. I understand that this is a big deal in India at the moment; people don't want to buy from China. It used to be an issued in the country where I live till the 1980s, and is returning again despite what economists think is important.

Oh that's three issues! Never mind.
