### ISSUE TITLE
Offer and OfferCatalog

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#995]
In schema.org:
`Person makesOffer`
`Offer` (is) `offeredBy Person`

Similarly:
`Person hasOfferCatalog`

But:
`OfferCatalog` cannot be related to `Person` (or `Organization`).

In addition, we would like to say:
`Offer hasPart OfferCatalog`

The reciprocal would be:
`OfferCatalog isPartOf Offer`

Do others see a problem here, or are we missing an expression that enables the above?

What might be a resolution?

Could `OfferCatalog` include the predicate:
`offerCatalogBy`?

Then, how to express a relationship between `Offer` and `OfferCatalog`?

Could `hasPart` and `isPartOf` (for `CreativeWork`) be extended to include `Offer` and `OfferCatalog`?

/jay gray

**Comment by mfhepp** [comment]
I think there was a longer discussion on related issues in the context of the original proposal.
Maybe Vicki can dig it out.
Martin

**Comment by vholland** [comment]
There was some concern about mixing Offers and OfferCatalogs in a single property, so ```hasOfferCatalog``` was created to link a Person, Organization, or Service to an OfferCatalog.

I am not sure I understand the rest of the question. An OfferCatalog is made up of one or more Offers or sub-catalogs. See the example at http://schema.org/OfferCatalog.

**Comment by jaygray0919** [comment]
@vholland How to relate `OfferCatalog` to a `@Type` other than `Thing`? For example, I would like to have the inverse of `Person` `hasOfferCatalog` `identifer` such as `OfferCatalog` `offerCatalogBy` ... `Person`. If `OfferCatalog` is treated as `CreativeWork` we could say `CreativeWork` `hasPart` ... `OfferCatalog`. As of the current schema.org release it's difficult to express a relationship between `OfferCatalog` and potentially relevant `@Types`. 

One way to think about this is similar ORE `aggregates`. (http://www.openarchives.org/ore/0.9/jsonld). Aggregates can be related to different Types. Hoping to achieve a data model for schema.org.

Let me know if I need to better document this use case.

**Comment by vholland** [comment]
A ```Person```, ```Organization```, or ```Service``` can specify it has an ```OfferCatalog``` with ```hasCatalog```. The catalog itself is composed of sub-catalogs or ```Offers``` with the ```itemOffered``` being a ```Product``` or ```Service```.

The example on http://schema.org/OfferCatalog is for  a catalog of services. A similar example for a retailer who sells widgets and widget parts would be:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Organization",
  "name": "Example Retailer",
  "hasOfferCatalog": {
    "@type": "OfferCatalog",
    "name": "Complete catalog",
    "itemListElement": [
      {
        "@type": "OfferCatalog",
        "name": "Widgets",
        "itemListElement": [
          {
            "@type": "Offer",
            "itemOffered": {
              "@type": "Product",
              "name": "large widgets",
              "price": 10.00,
              "priceCurrency": "USD"
            }
          },
          {
            "@type": "Offer",
            "itemOffered": {
              "@type": "Product",
              "name": "small widgets",
              "price": 5.00,
              "priceCurrency": "USD"
            }
          }
        ]
      },
      {
        "@type": "OfferCatalog",
        "name": "Widget parts",
        "itemListElement": [
          {
            "@type": "Offer",
            "itemOffered": {
              "@type": "Product",
              "name": "large widget parts",
              "price": 1.50,
              "priceCurrency": "USD"
            }
          },
          {
            "@type": "Offer",
            "itemOffered": {
              "@type": "Product",
              "name": "small widget parts",
              "price": 1.00,
              "priceCurrency": "USD"
            }
          }
        ]
      }
    ]
  }
}
</script>
```

**Comment by jaygray0919** [comment]
I'm not communicating well here.
Short term, we'll limit our relations in a single direction anchored by: `hasOfferCatalog`.
We'll revisit the aggregation concept at a later time.
TY for your help.
/jg
