### ISSUE TITLE
3 properties should use DateTime instead of Date

### ISSUE THREAD

**Issue by vberkel** [schemaorg/schemaorg#996]
3 properties ( [startDate](http://schema.org/startDate) [endDate](http://schema.org/endDate) and [commentTime](http://schema.org/commentTime) ) have as their range a Date and yet expect a ISO8601 values that include the time (indicated in their comment). The model restricts an Event to have startDate or endDate without time which isn't the intention. Change their property range from Date to DateTime. 

Alternatively, change startDate to startTime, endDate to endTime.

**Comment by danbri** [comment]
Thanks, this seems fair. Another option would be to say that either "Date" or "DateTime" are appropriate values.

**Comment by akuckartz** [comment]
`http://purl.org/dc/terms/W3CDTF`:smile:

**Comment by vberkel** [comment]
I like your option the best; that would best allow events that are "all day" or at specific times.

**Comment by danbri** [comment]
*bump*

Any objections to adding DateTime and leaving Date there too?

@scor @mfhepp @rvguha @chaals @shankarnat @vholland @tmarshbing

**Comment by mfhepp** [comment]
@danbri ok

**Comment by scor** [comment]
👍

**Comment by danbri** [comment]
Implemented + queued for review in upcoming release: http://webschemas.org/docs/releases.html#g996

**Comment by danbri** [comment]
Published via http://schema.org/docs/releases.html#v3.1
http://blog.schema.org/2016/08/schemaorg-update-hotels-datasets-health.html
