### ISSUE TITLE
sharedContent needs an example

### ISSUE THREAD

**Issue by KenSharp** [schemaorg/schemaorg#997]
[sharedContent ](http://schema.org/sharedContent) needs an example. It's not clear in what context you would use it. It's not clear if I should use this entity or not, or what for. It's not clear how to use it at all in fact.

Other entities have examples so it seems like a good idea to have one for this.

**Comment by Dataliberate** [comment]
Suitable example is already available for parent type SocialMediaPosting.  Created Pull Request (#998) to make that example appear on the sharedContent page.

**Comment by KenSharp** [comment]
So it does! Your commit will make it a bit easier for wallies like me though. Thanks.

**Comment by danbri** [comment]
Published - see http://schema.org/docs/releases.html
