### ISSUE TITLE
@ImageObject behavior for different @Types

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#999]
For `"@Person"`, the property `"image"` may be linked to `"@type": "ImageObject"` using a target name such as `"image-Person-1"`.

Then `"image-Person-1"` can be re-used in one or more graphs.

The same linking can be employed for the property `"logo"`, with a link to `"@type": "ImageObject"` and a target name such as `"image-Logo-1"`.

However, this linking technique cannot be employed for `"@CreativeWork"`.

For example, the Google Structured Data Testing tool requires that `"@type": "ImageObject"` and its property must be inline with the markup of `"@type": "ScholarlyArticle"`.

Furthermore, the `"logo"` for a `"publisher"` (`"@type": "Corporation"`) also must be inline with the markup of `"@type": "ScholarlyArticle"`.

This constraint defeats re-use of `"image"` and `"logo"`. We can share `"image"` and `"logo"` based on their `"name"` (ID) with `"@Person"`, `"@Event"`, `"@Place"` but not with `"@CreativeWork"`. We have to replicate the data when used for `"@CreativeWork"`.

Can the schema.org grammar be amended to allow all Types to share `"ImageObject"` for properties `"image"` and `"logo"`?

/jay gray

**Comment by vholland** [comment]
The schema.org properties "image" and "logo" do allow for an ImageObject regardless of the type. Consumers may apply their own rules of what is allowed or required.

This question is better suited for Google support.

**Comment by jaygray0919** [comment]
OK, I accept the @vholland comment. However, the Google Structure Data Testing Tool does fire an error for the schema.org structure described above. I'll submit the issue to GSDTT.
